### ISSUE TITLE
[aws-eks] Deploying 1.61.1 cluster over 1.55.0 cluster fails with error: "Cluster is already at the desired configuration"

### ISSUE THREAD

**Issue by mattchrist** [aws/aws-cdk#10142]
When deploying an EKS cluster with CDK version 1.61.1 against a stack that was deployed with 1.55.0, I get the following error from the EKS cluster custom resource provider:

> "Cluster is already at the desired configuration with endpointPrivateAccess: true , endpointPublicAccess: true, and Public Endpoint Restrictions: [0.0.0.0/0]"

### Reproduction Steps

Deploy an EKS cluster with @aws-cdk/aws-eks@1.55.0, k8s version 1.15.
Deploy the same code again but using @aws-cdk/aws-eks@1.61.1

### What did you expect to happen?

The cluster to be deployed successfully

### What actually happened?

The cluster fails to update because it is already updated.

### Environment

  - **CLI Version      :1.61.1 / 1.55.0**
  - **Framework Version:**
  - **Node.js Version:14.5.0**
  - **OS               :MacOS / AWS Codebuild Standard 3 w/ nodejs12**
  - **Language (Version): Typescript** 

### Other

--- 

This is :bug: Bug Report

**Comment by mattchrist** [comment]
I'm not able to reproduce this in a simple stack right now.

Cloudwatch logs from a cluster onEvent earlier deployment:
```
> INFO	new props:  
{
    "resourcesVpcConfig": {
        "endpointPrivateAccess": true,
        "securityGroupIds": [
          ... same as old props
        ],
        "endpointPublicAccess": true,
        "subnetIds": [
          ... same as old props
        ]
    },
    "roleArn": "redacted", //same as old
    "name": "cke", //same as old
    "version": "1.15" //same as old
}
> INFO	[AWS eks 400 1.436s 0 retries] updateClusterConfig({
  name: 'cke',
  logging: undefined,
  resourcesVpcConfig: {
    endpointPrivateAccess: true,
    endpointPublicAccess: true,
    publicAccessCidrs: undefined
  },
  clientRequestToken: 'redacted'
})
> ERROR	Invoke Error 	
{
    "errorType": "InvalidParameterException",
    "errorMessage": "Cluster is already at the desired configuration with endpointPrivateAccess: true , endpointPublicAccess: true, and Public Endpoint Restrictions: [0.0.0.0/0]",
    "code": "InvalidParameterException",
    "message": "Cluster is already at the desired configuration with endpointPrivateAccess: true , endpointPublicAccess: true, and Public Endpoint Restrictions: [0.0.0.0/0]",
    "time": "2020-09-02T19:53:24.619Z",
    "requestId": "b84d90f2-3782-4952-8a06-fd6217659831",
    "statusCode": 400,
    "retryable": false,
    "retryDelay": 85.30002572199322,
    "stack": [
        "InvalidParameterException: Cluster is already at the desired configuration with endpointPrivateAccess: true , endpointPublicAccess: true, and Public Endpoint Restrictions: [0.0.0.0/0]",
        "    at Object.extractError (/var/runtime/node_modules/aws-sdk/lib/protocol/json.js:51:27)",
        "    at Request.extractError (/var/runtime/node_modules/aws-sdk/lib/protocol/rest_json.js:55:8)",
        "    at Request.callListeners (/var/runtime/node_modules/aws-sdk/lib/sequential_executor.js:106:20)",
        "    at Request.emit (/var/runtime/node_modules/aws-sdk/lib/sequential_executor.js:78:10)",
        "    at Request.emit (/var/runtime/node_modules/aws-sdk/lib/request.js:688:14)",
        "    at Request.transition (/var/runtime/node_modules/aws-sdk/lib/request.js:22:10)",
        "    at AcceptorStateMachine.runTo (/var/runtime/node_modules/aws-sdk/lib/state_machine.js:14:12)",
        "    at /var/runtime/node_modules/aws-sdk/lib/state_machine.js:26:10",
        "    at Request.<anonymous> (/var/runtime/node_modules/aws-sdk/lib/request.js:38:9)",
        "    at Request.<anonymous> (/var/runtime/node_modules/aws-sdk/lib/request.js:690:12)"
    ]
}

**Comment by mattchrist** [comment]
I now cannot reproduce this with my over-complicated eks stacks... Closing issue.
