### ISSUE TITLE
Missing environment in CodeCommitSourceAction

### ISSUE THREAD

**Issue by gitcatrat** [aws/aws-cdk#10294]
`CodeCommitSourceAction` is missing `environment` for some reason.

### Reproduction Steps
```js
// index.js
const app = new cdk.App();

new PipelineStack(app, 'PipelineStack', {
  stackName: 'PipelineStack',
  description: 'This is a test pipeline stack.',
  env: {
    region: 'eu-west-1'
  }
});

// pipeline.js
export default class PipelineStack extends cdk.Stack {
  constructor(scope, id, props) {
    super(scope, id, props);

    const sourceArtifact = new codePipeline.Artifact();
    const cloudAssemblyArtifact = new codePipeline.Artifact();

    const pipeline = new pipelines.CdkPipeline(this, 'Pipeline', {
      pipelineName: 'TestPipeline',
      cloudAssemblyArtifact,
      sourceAction: new codepipelineActions.CodeCommitSourceAction({
        actionName: 'CodeCommitAction',
        repository: '...',
        output: sourceArtifact
      }),
      synthAction: pipelines.SimpleSynthAction.standardNpmSynth({
        sourceArtifact,
        cloudAssemblyArtifact,
        buildCommand: 'npm run build'
      })
    });
  }
}
```

### What did you expect to happen?

`cdk synth -j` should log the template.

### What actually happened?

```
MacBook-Pro:cdk-test xxx$ cdk synth -j
/Users/xxx/Desktop/cdk-test/node_modules/@aws-cdk/aws-codepipeline/lib/pipeline.js:259
            const pipelineAndActionRegionComparison = core_1.Token.compareStrings(this.env.region, actionResource.env.region);
                                                                                                                      ^

TypeError: Cannot read property 'region' of undefined
    at Pipeline.ensureReplicationResourcesExistFor (/Users/xxx/Desktop/cdk-test/node_modules/@aws-cdk/aws-codepipeline/lib/pipeline.js:259:119)
    at Pipeline._attachActionToPipeline (/Users/xxx/Desktop/cdk-test/node_modules/@aws-cdk/aws-codepipeline/lib/pipeline.js:219:38)
    at Stage.attachActionToPipeline (/Users/xxx/Desktop/cdk-test/node_modules/@aws-cdk/aws-codepipeline/lib/stage.js:110:31)
    at Stage.addAction (/Users/xxx/Desktop/cdk-test/node_modules/@aws-cdk/aws-codepipeline/lib/stage.js:69:33)
    at new Stage (/Users/xxx/Desktop/cdk-test/node_modules/@aws-cdk/aws-codepipeline/lib/stage.js:26:18)
    at Pipeline.addStage (/Users/xxx/Desktop/cdk-test/node_modules/@aws-cdk/aws-codepipeline/lib/pipeline.js:162:23)
    at new CdkPipeline (/Users/xxx/Desktop/cdk-test/node_modules/@aws-cdk/pipelines/lib/pipeline.js:62:28)
    at new PipelineStack (file:///Users/xxx/Desktop/cdk-test/infra/pipeline.js:19:22)
    at file:///Users/xxx/Desktop/cdk-test/infra/index.js:20:1
    at ModuleJob.run (internal/modules/esm/module_job.js:140:23)
Subprocess exited with error 1
```

If I `console.log(this.env, actionResource.env);` in `ensureReplicationResourcesExistFor`:
```
{ account: '${Token[AWS.AccountId.0]}', region: 'eu-west-1' } undefined
```

### Environment

  - **CLI Version      :** 1.62.0
  - **Framework Version:** 1.62.0
  - **Node.js Version:**  v14.9.0
  - **OS               :** macOS Catalina v10.15.6
  - **Language (Version):**  Javascript

--- 

This is :bug: Bug Report

**Comment by skinny85** [comment]
Hello @gitcatrat ,

what is this part of your code?

```
        repository: '...',
```

?

Thanks,
Adam

**Comment by gitcatrat** [comment]
@skinny85 Thank you for bringing my attention to this, I assumed repository wanted repository name but it actually wants Repository class.
