### ISSUE TITLE
[elbv2] There is already a Construct with name 'SecurityGroup' in MyStack [MyStack]

### ISSUE THREAD

**Issue by sarantoo** [aws/aws-cdk#10425]
Our app need to support clients via both HTTP and HTTPS (must be no redirection as some older clients do not communicate over HTTPS). So, I try to add target group to both existing listeners. The error occurs when I try to reference HTTP and HTTPS listener of an ALB using below 2 blocks of code. Comment out either block will work just fine but got error with both block defined.

### Reproduction Steps
```javascript
const listener = elbv2.ApplicationListener.fromApplicationListenerAttributes(this, "Listener", {
    listenerArn: "arn:xxx",
    securityGroupId: "sg-xxx"
})

const secureListener = elbv2.ApplicationListener.fromApplicationListenerAttributes(this, "SecureListener", {
    listenerArn: "arn:yyy",
    securityGroupId: "sg-yyy"
})

```

### What did you expect to happen?

Should be no error as we just make a reference to each listener.

### What actually happened?
```
Error: There is already a Construct with name 'SecurityGroup' in MyStack [MyStack]
    at Node.addChild (E:\Users\Dad\Projects\cdk\node_modules\constructs\lib\construct.js:414:19)
    at new Node (E:\Users\Dad\Projects\cdk\node_modules\constructs\lib\construct.js:31:28)
    at new ConstructNode (E:\Users\Dad\Projects\cdk\node_modules\@aws-cdk\core\lib\construct-compat.js:150:28)
    at Object.createNode (E:\Users\Dad\Projects\cdk\node_modules\@aws-cdk\core\lib\construct-compat.js:32:42)
    at new Construct (E:\Users\Dad\Projects\cdk\node_modules\constructs\lib\construct.js:458:32)
    at new Construct (E:\Users\Dad\Projects\cdk\node_modules\@aws-cdk\core\lib\construct-compat.js:30:9)
    at new Resource (E:\Users\Dad\Projects\cdk\node_modules\@aws-cdk\core\lib\resource.js:15:9)
    at new SecurityGroupBase (E:\Users\Dad\Projects\cdk\node_modules\@aws-cdk\aws-ec2\lib\security-group.js:13:9)
    at new MutableImport (E:\Users\Dad\Projects\cdk\node_modules\@aws-cdk\aws-ec2\lib\security-group.js:193:17)
    at Function.fromSecurityGroupId (E:\Users\Dad\Projects\cdk\node_modules\@aws-cdk\aws-ec2\lib\security-group.js:219:15)
```
### Environment

  - **CLI Version      : 1.63.0**
  - **Framework Version:**
  - **Node.js Version: v12.18.0** 
  - **OS               : Windows 10**
  - **Language (Version): JavaScript** 

### Other

--- 

This is :bug: Bug Report

**Comment by sarantoo** [comment]
Just found the solution today. By using securityGroup in stead of securityGroupId solve the problem. As securityGroupId is depreciated, that's may be the reason.

``` javascript
const listener = elbv2.ApplicationListener.fromApplicationListenerAttributes(this, "Listener", {
    listenerArn: "arn:xxx",
    // securityGroupId: "sg-xxx"
    securityGroup: ec2.SecurityGroup.fromSecurityGroupId(this, "HTTP", "sg-xxx")
})

const secureListener = elbv2.ApplicationListener.fromApplicationListenerAttributes(this, "SecureListener", {
    listenerArn: "arn:yyy",
    // securityGroupId: "sg-yyy"
    securityGroup: ec2.SecurityGroup.fromSecurityGroupId(this, "HTTP", "sg-yyy")
})
```
