### ISSUE TITLE
(route53resolver): Python AttributeError: type object 'set' has no attribute '__jsii_type__'

### ISSUE THREAD

**Issue by AungBoTun** [aws/aws-cdk#10449]
Hi guys, 
  I am try to create the route53 resolver in my account and getting error: `AttributeError: type object 'set' has no attribute '__jsii_type__'`

Code
```py
from aws_cdk import (aws_route53resolver as route53resolver,core)

class CustomeVpcStack(core.Stack):

    def __init__(self, scope: core.Construct, id: str, **kwargs) -> None:
        super().__init__(scope, id, **kwargs)
        cfnendpoint = route53resolver.CfnResolverEndpoint(
        self,"Route53endpint",
        direction="Outbound",
        ip_addresses=[{"subnet-5bce3e3d"},{"subnet-eb9474a3"}],
        security_group_ids=["sg-bc4f60c3"],
        name ="belejean",
        )
```

Error logs 
```console
Traceback (most recent call last):
  File "app.py", line 9, in <module>
    CustomeVpcStack(app, "custome-vpc")
  File "/Users//custome-vpc/.env/lib/python3.8/site-packages/jsii/_runtime.py", line 69, in __call__
    inst = super().__call__(*args, **kwargs)
  File "/Users//custome-vpc/custome_vpc/custome_vpc_stack.py", line 9, in __init__
    cfnendpoint = route53resolver.CfnResolverEndpoint(
  File "/Users//custome-vpc/.env/lib/python3.8/site-packages/jsii/_runtime.py", line 69, in __call__
    inst = super().__call__(*args, **kwargs)
  File "/Users//custome-vpc/.env/lib/python3.8/site-packages/aws_cdk/aws_route53resolver/__init__.py", line 81, in __init__
    jsii.create(CfnResolverEndpoint, self, [scope, id, props])
  File "/Users//custome-vpc/.env/lib/python3.8/site-packages/jsii/_kernel/__init__.py", line 249, in create
    args=_make_reference_for_native(self, args),
  File "/Users//custome-vpc/.env/lib/python3.8/site-packages/jsii/_kernel/__init__.py", line 136, in _make_reference_for_native
    return [_make_reference_for_native(kernel, i) for i in d]
  File "/Users/aungbotun/custome-vpc/.env/lib/python3.8/site-packages/jsii/_kernel/__init__.py", line 136, in <listcomp>
    return [_make_reference_for_native(kernel, i) for i in d]
  File "/Users//custome-vpc/.env/lib/python3.8/site-packages/jsii/_kernel/__init__.py", line 149, in _make_reference_for_native
    "data": {
  File "/Users//custome-vpc/.env/lib/python3.8/site-packages/jsii/_kernel/__init__.py", line 150, in <dictcomp>
    jsii_name: _make_reference_for_native(
  File "/Users//custome-vpc/.env/lib/python3.8/site-packages/jsii/_kernel/__init__.py", line 136, in _make_reference_for_native
    return [_make_reference_for_native(kernel, i) for i in d]
  File "/Users/custome-vpc/.env/lib/python3.8/site-packages/jsii/_kernel/__init__.py", line 136, in <listcomp>
    return [_make_reference_for_native(kernel, i) for i in d]
  File "/Users//custome-vpc/.env/lib/python3.8/site-packages/jsii/_kernel/__init__.py", line 169, in _make_reference_for_native
    kernel.create(d.__class__, d)
  File "/Users//custome-vpc/.env/lib/python3.8/site-packages/jsii/_kernel/__init__.py", line 248, in create
    fqn=klass.__jsii_type__ or "Object",
AttributeError: type object 'set' has no attribute '__jsii_type__'
```

**Comment by BenChaimberg** [comment]
The value for `ip_addresses` should be:
```
[
  route53resolver.CfnResolverEndpoint.IpAddressRequestProperty(subnet_id="subnet-5bce3e3d"),
  route53resolver.CfnResolverEndpoint.IpAddressRequestProperty(subnet_id="subnet-eb9474a3")
]
```
