### ISSUE TITLE
[ecs]  Got 'undefined' for non-optional instance of {"type":{"primitive":"string"}}

### ISSUE THREAD

**Issue by thombergs** [aws/aws-cdk#10504]
When trying to synth or deploy my Java Cdk App, I get this stacktrace:

```
Caused by: software.amazon.jsii.JsiiException: Got 'undefined' for non-optional instance of {"type":{"primitive":"string"}}
Error: Got 'undefined' for non-optional instance of {"type":{"primitive":"string"}}
    at nullAndOk (/tmp/jsii-java-runtime16644787021207320515/jsii-runtime.js:7202:15)
    at Object.deserialize (/tmp/jsii-java-runtime16644787021207320515/jsii-runtime.js:6727:17)
    at Kernel._toSandbox (/tmp/jsii-java-runtime16644787021207320515/jsii-runtime.js:8326:61)
    at /tmp/jsii-java-runtime16644787021207320515/jsii-runtime.js:6872:74
    at mapValues (/tmp/jsii-java-runtime16644787021207320515/jsii-runtime.js:7229:27)
    at Object.deserialize (/tmp/jsii-java-runtime16644787021207320515/jsii-runtime.js:6872:28)
    at Kernel._toSandbox (/tmp/jsii-java-runtime16644787021207320515/jsii-runtime.js:8326:61)
    at /tmp/jsii-java-runtime16644787021207320515/jsii-runtime.js:6957:29
    at mapValues (/tmp/jsii-java-runtime16644787021207320515/jsii-runtime.js:7229:27)
    at Kernel._wrapSandboxCode (/tmp/jsii-java-runtime16644787021207320515/jsii-runtime.js:8420:19)
    at /tmp/jsii-java-runtime16644787021207320515/jsii-runtime.js:7756:25
    at Kernel._ensureSync (/tmp/jsii-java-runtime16644787021207320515/jsii-runtime.js:8393:20)
    at Kernel.invoke (/tmp/jsii-java-runtime16644787021207320515/jsii-runtime.js:7755:26)
    at KernelHost.processRequest (/tmp/jsii-java-runtime16644787021207320515/jsii-runtime.js:7456:28)
    at KernelHost.run (/tmp/jsii-java-runtime16644787021207320515/jsii-runtime.js:7394:14)
    at Immediate._onImmediate (/tmp/jsii-java-runtime16644787021207320515/jsii-runtime.js:7397:37)
    at processImmediate (internal/timers.js:456:21)
    at software.amazon.jsii.JsiiRuntime.processErrorResponse (JsiiRuntime.java:119)
    at software.amazon.jsii.JsiiRuntime.requestResponse (JsiiRuntime.java:91)
    at software.amazon.jsii.JsiiClient.callMethod (JsiiClient.java:183)
    at software.amazon.jsii.JsiiObject.jsiiCall (JsiiObject.java:120)
    at software.amazon.jsii.JsiiObject.jsiiCall (JsiiObject.java:106)
    at software.amazon.awscdk.services.ecs.TaskDefinition.addContainer (TaskDefinition.java:54)
    at dev.stratospheric.application.EcsStack.<init> (EcsStack.java:105)
    at io.blogtrack.BlogtrackApp.main (BlogtrackApp.java:78)
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:62)
    at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke (Method.java:564)
    at org.codehaus.mojo.exec.ExecJavaMojo$1.run (ExecJavaMojo.java:282)
    at java.lang.Thread.run (Thread.java:832)
```

I assume it's because I didn't set some required field value in my constructs, but how can I find out which field value is missing?

### Reproduction Steps

This is the code I'm running within my CDK app. The exceptions happens in the call to `taskDefinition.addContainer()`:

```java
TaskDefinition taskDefinition = TaskDefinition.Builder.create(this, "ecsTaskDefinition")
                .family(StackUtil.prefixWithEnvironmentName(environmentName, "Family"))
                .cpu("256")
                .memoryMiB("512")
                .networkMode(NetworkMode.AWS_VPC)
                .compatibility(Compatibility.FARGATE)
                .executionRole(ecsTaskExecutionRole)
                .taskRole(ecsTaskRole)
                .build();

ContainerDefinitionOptions applicationContainer = ContainerDefinitionOptions.builder()
        .cpu(256)
        .memoryLimitMiB(512)
        .image(ContainerImage.fromEcrRepository(dockerRepositoryStack.getEcrRepository(), dockerImageTag))
        .logging(LogDriver.awsLogs(AwsLogDriverProps.builder()
                .logGroup(logGroup)
                .multilinePattern("^[0-9]{4}-[0-9]{2}-[0-9]{2}")
                .streamPrefix(StackUtil.prefixWithEnvironmentName(environmentName, "LogStream"))
                .build()))
        .environment(environmentVariables)
        .build();

taskDefinition.addContainer("applicationContainer", applicationContainer)
        .addPortMappings(PortMapping.builder()
                .containerPort(8080)
                .build());
```

### Environment

  - **CLI Version      :** aws-cli/2.0.7 Python/3.7.3 Linux/5.4.0-48-generic botocore/2.0.0dev11
  - **Framework Version:** 1.63.0
  - **Node.js Version:** v14.2.0
  - **OS               :** Ubuntu
  - **Language (Version):** Java openjdk version "14.0.2" 2020-07-14

--- 

This is :bug: Bug Report

**Comment by hoegertn** [comment]
I had the same error when one of my environment variable values was null/undefined. Please check if they are all non-null.

**Comment by Gnaneshwar511** [comment]
I had my system restarted and my Powershell lost environment variables. So it showed this error. I set the env. variables and it stopped showing this error.
