### ISSUE TITLE
[decdk] decdk-schema broken with node>=12

### ISSUE THREAD

**Issue by RomainMuller** [aws/aws-cdk#10510]
`decdk` has a dependency on `yargs`, and when traversing dependencies, `decdk-schema` attempts to `require.resolve('yargs/package.json');`. This is no longer possible since `yargs 16.0.0` is an ESM with an `exports` map that does not include `package.json` (meaning `package.json` is no longer part of their public API).

This results in builds failing with:
```
Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: Package subpath './package.json' is not defined by "exports" in <snip>/aws-cdk/packages/decdk/node_modules/yargs/package.json
    at throwExportsNotFound (internal/modules/esm/resolve.js:290:9)
    at packageExportsResolve (internal/modules/esm/resolve.js:496:3)
    at resolveExports (internal/modules/cjs/loader.js:450:36)
    at Function.Module._findPath (internal/modules/cjs/loader.js:490:31)
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:880:27)
    at Function.resolve (internal/modules/cjs/helpers.js:94:19)
    at Object.loadTypeSystem (<snip>/aws-cdk/packages/decdk/lib/util.js:21:52)
    at async main (<snip>/aws-cdk/packages/decdk/bin/decdk-schema.js:7:24) {
```

### Reproduction Steps

Make sure you're using `node >= 12`, then try to build `decdk`.

--- 

This is :bug: Bug Report

**Comment by Chriscbr** [comment]
Transferred to https://github.com/cdklabs/decdk/issues/9
