### ISSUE TITLE
[pipelines] self-update build fails to deploy its own pipline stack with name error

### ISSUE THREAD

**Issue by stevenalowe** [aws/aws-cdk#10585]
i have a stack to creates a CdkPipeline, and the pipeline deploys a stack with a bucket. except that the self-update fails claiming that the stack does not exist, though it's obviously there in the log

no luck finding a fix or workaround, and unable to revert versions without giving up essential features; this seemed to work in 1.59.0, broke on latest upgrade.

Log output:

```
[Container] 2020/09/29 05:56:53 Waiting for agent ping
[Container] 2020/09/29 05:56:55 Waiting for DOWNLOAD_SOURCE
[Container] 2020/09/29 05:56:56 Phase is DOWNLOAD_SOURCE
[Container] 2020/09/29 05:56:56 CODEBUILD_SRC_DIR=/codebuild/output/src985565592/src
[Container] 2020/09/29 05:56:56 YAML location is /codebuild/readonly/buildspec.yml
[Container] 2020/09/29 05:56:56 Processing environment variables
[Container] 2020/09/29 05:56:56 No runtime version selected in buildspec.
[Container] 2020/09/29 05:56:56 Moving to directory /codebuild/output/src985565592/src
[Container] 2020/09/29 05:56:56 Registering with agent
[Container] 2020/09/29 05:56:56 Phases found in YAML: 2
[Container] 2020/09/29 05:56:56  INSTALL: 1 commands
[Container] 2020/09/29 05:56:56  BUILD: 1 commands
[Container] 2020/09/29 05:56:56 Phase complete: DOWNLOAD_SOURCE State: SUCCEEDED
[Container] 2020/09/29 05:56:56 Phase context status code:  Message: 
[Container] 2020/09/29 05:56:56 Entering phase INSTALL
[Container] 2020/09/29 05:56:56 Running command npm install -g aws-cdk
/usr/local/bin/cdk -> /usr/local/lib/node_modules/aws-cdk/bin/cdk
+ aws-cdk@1.64.1
added 197 packages from 189 contributors in 6.801s

[Container] 2020/09/29 05:57:08 Phase complete: INSTALL State: SUCCEEDED
[Container] 2020/09/29 05:57:08 Phase context status code:  Message: 
[Container] 2020/09/29 05:57:08 Entering phase PRE_BUILD
[Container] 2020/09/29 05:57:08 Phase complete: PRE_BUILD State: SUCCEEDED
[Container] 2020/09/29 05:57:08 Phase context status code:  Message: 
[Container] 2020/09/29 05:57:08 Entering phase BUILD
[Container] 2020/09/29 05:57:08 Running command cdk -a . deploy InfraStack --require-approval=never --verbose
CDK toolkit version: 1.64.1 (build 14a8c8d)
Command line arguments: {
  _: [ 'deploy' ],
  a: '.',
  app: '.',
  'require-approval': 'never',
  requireApproval: 'never',
  verbose: 1,
  v: 1,
  'ignore-errors': false,
  ignoreErrors: false,
  json: false,
  j: false,
  ec2creds: undefined,
  i: undefined,
  'version-reporting': undefined,
  versionReporting: undefined,
  'path-metadata': true,
  pathMetadata: true,
  'asset-metadata': true,
  assetMetadata: true,
  'role-arn': undefined,
  r: undefined,
  roleArn: undefined,
  staging: true,
  'no-color': false,
  noColor: false,
  fail: false,
  'build-exclude': [],
  E: [],
  buildExclude: [],
  ci: false,
  execute: true,
  force: false,
  f: false,
  parameters: [ {} ],
  'previous-parameters': true,
  previousParameters: true,
  '$0': '/usr/local/bin/cdk',
  STACKS: [ 'InfraStack' ],
  'S-t-a-c-k-s': [ 'InfraStack' ]
}
merged settings: {
  versionReporting: true,
  pathMetadata: true,
  output: 'cdk.out',
  app: '.',
  context: {},
  assetMetadata: true,
  requireApproval: 'never',
  toolkitBucket: {},
  staging: true,
  bundlingStacks: [ '*' ]
}
Toolkit stack: CDKToolkit
Setting "CDK_DEFAULT_REGION" environment variable to us-west-2
Resolving default credentials
Looking up default account ID from STS
Default account ID: PIPELINEACCOUNTID
Setting "CDK_DEFAULT_ACCOUNT" environment variable to PIPELINEACCOuNTID
context: {
  'aws:cdk:enable-path-metadata': true,
  'aws:cdk:enable-asset-metadata': true,
  'aws:cdk:bundling-stacks': [ '*' ]
}
--app points to a cloud assembly, so we bypass synth
The stack InfraPipelineStack already includes a CDKMetadata resource
The stack InfraPipelineStackTestBucketStageTestBucketStack59A89726 already includes a CDKMetadata resource
No stack found matching 'InfraStack'. Use "list" to print manifest
Error: No stack found matching 'InfraStack'. Use "list" to print manifest
    at CloudAssembly.selectStacks (/usr/local/lib/node_modules/aws-cdk/lib/api/cxapp/cloud-assembly.ts:114:15)
    at CdkToolkit.selectStacksForDeploy (/usr/local/lib/node_modules/aws-cdk/lib/cdk-toolkit.ts:382:35)
    at CdkToolkit.deploy (/usr/local/lib/node_modules/aws-cdk/lib/cdk-toolkit.ts:112:20)
    at initCommandLine (/usr/local/lib/node_modules/aws-cdk/bin/cdk.ts:197:9)

[Container] 2020/09/29 05:57:09 Command did not exit successfully cdk -a . deploy InfraStack --require-approval=never --verbose exit status 1
[Container] 2020/09/29 05:57:09 Phase complete: BUILD State: FAILED
[Container] 2020/09/29 05:57:09 Phase context status code: COMMAND_EXECUTION_ERROR Message: Error while executing command: cdk -a . deploy InfraStack --require-approval=never --verbose. Reason: exit status 1
[Container] 2020/09/29 05:57:09 Entering phase POST_BUILD
```

code that causes this:

```

const app = new App({
    // NOTE: this forces new-style stack synthesis, makes missing assumeRoleArn error go away
    // cdk.json option does not always work!
    context: {
        [cxapi.NEW_STYLE_STACK_SYNTHESIS_CONTEXT]: 'true',
    }
});

new InfraPipelineStack(app, 'InfraPipelineStack', {
    env: ENVIRONMENTS.INFRA
});

```

the infrapipelinestack creates a CDKPipeline and gives it an application stage that creates a  stack containing only a bucket. The app stage is deployed to a staging environment, the pipeline is deployed to an infra environment

happy to provide additional info, copy of repo, etc. ty!

_Originally posted by @stevenalowe in https://github.com/aws/aws-cdk/issues/7319#issuecomment-699543209_

**Comment by stevenalowe** [comment]
it's possible...that i had this accidentally pointing at two different branches at the same time; it's also possible that excessive refactoring to Constructs messed up the namespaces badly enough to confuse the build. Note that the build thinks its stack is named InfraStack but the assembly it was given is named InfraPipelineStack. Unabe to reproduce again, closing with gratitude.
