### ISSUE TITLE
[ec2] Issue with selectSubnet's availability zone 

### ISSUE THREAD

**Issue by shreyasmm** [aws/aws-cdk#10596]
## :question: General Issue

I am having issue with IVpc.selectSubnets, cdk packages version 1.64.1

the below code works fine when using 
````javascript
"@aws-cdk/aws-ec2": "1.63.0",
"@aws-cdk/core": "1.63.0",
"@aws-cdk/aws-autoscaling": "1.63.0"
````
````javascript
// @common package's index.ts

// Initialize Empty Arrays
this.privateSubnets = [];

// Get Private Subnets
this.privateSubnetIds = cdk.Token.asList(this.vpcLookup.getAttString('privateSubnetIds'));
for (let subnet of this.privateSubnetIds) {
  this.privateSubnets.push(ec2.Subnet.fromSubnetId(this,subnet,subnet));
}
this.privateSubnetsRef = this.vpcRef.selectSubnets({
  subnets: this.privateSubnets,
})

//asg package's index.ts
this.autoScalingGroup = new asg.AutoScalingGroup(this, 'ASG', {
  associatePublicIpAddress: false,
  autoScalingGroupName: props.autoScalingGroupName,
  blockDevices: this.blockDevices,
  cooldown: props.cooldown,
  desiredCapacity: props.desiredCapacity,
  instanceType: new ec2.InstanceType(props.instanceType),
  keyName: props.keyName,
  machineImage: amiLookup.amiIdRef,
  maxCapacity: props.maxCapacity,
  minCapacity: props.minCapacity,
  role: this.role,
  securityGroup: this.securityGroup,
  vpc: vpcLookup.vpcRef,
  vpcSubnets: vpcLookup.privateSubnetsRef,
});
````
````bash
yarn run test
yarn run v1.22.10
$ jest --passWithNoTests
 PASS  src/__tests__/asg.test.ts
  ✓ Auto Scaling Group Created (272ms)
  ✓ Auto Scaling Group - with no Security Group Input (267ms)
  ✓ Auto Scaling Group - with no Role Input (149ms)

Test Suites: 1 passed, 1 total
Tests:       3 passed, 3 total
Snapshots:   0 total
Time:        3.748s, estimated 4s
Ran all test suites.
Done in 4.24s.
```` 

i just updated all core packages to 1.64.1
````bash
yarn run test                                          
yarn run v1.22.10
$ jest --passWithNoTests
 FAIL  src/__tests__/asg.test.ts
  ✕ Auto Scaling Group Created (70ms)
  ✕ Auto Scaling Group - with no Security Group Input (147ms)
  ✕ Auto Scaling Group - with no Role Input (34ms)

  ● Auto Scaling Group Created

    You cannot reference a Subnet's availability zone if it was not supplied. Add the availabilityZone when importing using Subnet.fromSubnetAttributes()

      286 |     // const healthCheck = new asg.HealthCheck()
      287 | 
    > 288 |     this.autoScalingGroup = new asg.AutoScalingGroup(this, 'ASG', {
          |                             ^
      289 |       associatePublicIpAddress: false,
      290 |       autoScalingGroupName: props.autoScalingGroupName,
      291 |       blockDevices: this.blockDevices,

      at ImportedSubnet.get availabilityZone [as availabilityZone] (../../node_modules/@aws-cdk/aws-ec2/lib/vpc.ts:1937:13)
      at ../../node_modules/@aws-cdk/aws-ec2/lib/vpc.ts:364:69
          at Array.map (<anonymous>)
      at Object.get availabilityZones [as availabilityZones] (../../node_modules/@aws-cdk/aws-ec2/lib/vpc.ts:364:58)
      at LookedUpVpc.reifySelectionDefaults (../../node_modules/@aws-cdk/aws-ec2/lib/vpc.ts:556:19)
      at LookedUpVpc.selectSubnetObjects (../../node_modules/@aws-cdk/aws-ec2/lib/vpc.ts:460:22)
      at LookedUpVpc.selectSubnets (../../node_modules/@aws-cdk/aws-ec2/lib/vpc.ts:359:26)
      at new AutoScalingGroup (../../node_modules/@aws-cdk/aws-autoscaling/lib/auto-scaling-group.ts:688:48)
      at new Asg (src/index.ts:288:29)
      at Object.<anonymous> (src/__tests__/asg.test.ts:14:3)
````

### The Question
Is this the expected working or am i missing something 
I tried to pass empty string and dummy values its not working
````javascript 
this.privateSubnetsRef = this.vpcRef.selectSubnets({
      subnets: this.privateSubnets,
      availabilityZones: []
    })
````

### Environment

  - **CDK CLI Version:**  1.64.1 (build 14a8c8d)
  - **Module Version:**      "@aws-cdk/aws-ec2": "1.64.1", "@aws-cdk/core": "1.64.1","@aws-cdk/aws-autoscaling": "1.64.1"
  - **Node.js Version:**  v12.18.3
  - **OS:**  Ubuntu20.04 - Pop!os 20.04
  - **Language (Version):**  Typescript

### Other information

https://github.com/aws/aws-cdk/issues/6607
https://github.com/aws/aws-cdk/issues/8301

**Comment by rix0rrr** [comment]
```ts
this.privateSubnetsRef = this.vpcRef.selectSubnets({
  subnets: this.privateSubnets,
})

// ...

  vpcSubnets: vpcLookup.privateSubnetsRef,
```

You're not supposed to pass the RESULT of `selectSubnets` but the INPUT to it:

```ts
  vpcSubnets: { subnets: this.privateSubnets },
```

**Comment by shreyasmm** [comment]
This solved the issue its working. thx @rix0rrr
