### ISSUE TITLE
[core] "FAILED, No updates are to be performed" when updating a stack with "Transform"

### ISSUE THREAD

**Issue by victorholban** [aws/aws-cdk#10650]
Updating a stack that has no change containing a "Transform" results in an error _"FAILED, No updates are to be performed"_

Following the best practices, all our AWS resources are manage using multiple CDK stack, and every time we push a change we update all the stack. Having an error on stacks that contains no changes in a CDK application with multiple stacks is breaking our CI pipeline.

### Reproduction Steps
Update a stack with a CFN Transform without making any change to it.

Example of simple stack with Transform:
```
import * as core from '@aws-cdk/core'

class TestStackWithTransforms extends core.Stack {
  constructor(scope: core.Construct, id: string, props?: core.StackProps) {
    super(scope, id, props)

    this.addTransform('AWS::Serverless-2016-10-31')
  }
}

new TestStackWithTransforms(app, 'TestStackWithTransforms')
```

### What did you expect to happen?

```
TestStackWithTransforms: deploying...
TestStackWithTransforms: creating CloudFormation changeset...

 ✅  TestStackWithTransforms (no changes)

Stack ARN:
arn:aws:cloudformation:eu-central-1:000000000000:stack/TestStackWithTransforms/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
```

### What actually happened?

```
TestStackWithTransforms: deploying...
TestStackWithTransforms: creating CloudFormation changeset...

 ❌  TestStackWithTransforms failed: Error: Failed to create ChangeSet CDK-xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx on TestStackWithTransforms: FAILED, No updates are to be performed.
    at /code/node_modules/aws-cdk/lib/api/util/cloudformation.ts:227:11
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at waitFor (/code/node_modules/aws-cdk/lib/api/util/cloudformation.ts:188:20)
    at Object.waitForChangeSet (/code/node_modules/aws-cdk/lib/api/util/cloudformation.ts:213:15)
    at Object.deployStack (/code/node_modules/aws-cdk/lib/api/deploy-stack.ts:252:32)
    at CdkToolkit.deploy (/code/node_modules/aws-cdk/lib/cdk-toolkit.ts:180:24)
    at initCommandLine (/code/node_modules/aws-cdk/bin/cdk.ts:197:9)
Failed to create ChangeSet CDK-xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx on TestStackWithTransforms: FAILED, No updates are to be performed.
```

### Environment

  - **CLI Version      :** 1.65.0
  - **Framework Version:** 1.65.0
  - **Node.js Version:** v14.2.0
  - **OS               :** macOS Catalina (10.15.7)
  - **Language (Version):** TypeScript

### Other

From my research it looks like AWS uses different statusReason if the stack has a "Transform". 
I've manage to find the file/function in CDK that is checking this [aws-cdk/packages/aws-cdk/lib/api/util/cloudformation.ts:changeSetHasNoChanges()](https://github.com/aws/aws-cdk/blob/master/packages/aws-cdk/lib/api/util/cloudformation.ts#L244)

Current version of the changeSetHasNoChanges function:
```
/**
 * Return true if the given change set has no changes
 *
 * This must be determined from the status, not the 'Changes' array on the
 * object; the latter can be empty because no resources were changed, but if
 * there are changes to Outputs, the change set can still be executed.
 */
function changeSetHasNoChanges(description) {
    return description.Status === 'FAILED'
        && description.StatusReason
        && description.StatusReason.startsWith('The submitted information didn\'t contain changes.');
}
```

Suggested fix / new version of the changeSetHasNoChanges function:
```
/**
 * Return true if the given change set has no changes
 *
 * This must be determined from the status, not the 'Changes' array on the
 * object; the latter can be empty because no resources were changed, but if
 * there are changes to Outputs, the change set can still be executed.
 */
function changeSetHasNoChanges(description) {
    return description.Status === 'FAILED'
        && description.StatusReason
        && (description.StatusReason.startsWith('The submitted information didn\'t contain changes.')
            || description.StatusReason.startsWith('No updates are to be performed.'));
}
```

This issue looks similar to the Bug Report [2553](https://github.com/aws/aws-cdk/issues/2553)

--- 

This is :bug: Bug Report

**Comment by rix0rrr** [comment]
Thanks for doing the research!
