### ISSUE TITLE
[aws-apigateway] Run generated template locally

### ISSUE THREAD

**Issue by myin142** [aws/aws-cdk#10703]
I tried to run the generated template file with `cdk synth` using `sam local start-api`. Most things seem to work except when I do an OPTIONS request. Then I get the below error.

### Reproduction Steps

Generate a template file with this code

```
		const api = new RestApi(this, 'Api', {
			defaultCorsPreflightOptions: {
				allowOrigins: ['*'],
				allowHeaders: ['Authorization'],
				allowCredentials: true,
			},
		});

		const lambda = new Function(this, 'lambda', {
			runtime: Runtime.NODEJS_12_X,
			code: Code.fromAsset('lambda'),
			handler: 'lambda.handler',
		});

		const resource = api.root.addResource('api');
		resource.addMethod('POST', new LambdaIntegration(lambda));
```

### What did you expect to happen?

I expected the OPTIONS request to have worked

### What actually happened?

```
Exception on /time [OPTIONS]
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/usr/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/lib/python3.8/site-packages/samcli/local/apigw/local_apigw_service.py", line 203, in _request_handler
    self.lambda_runner.invoke(route.function_name, event, stdout=stdout_stream_writer, stderr=self.stderr)
  File "/usr/lib/python3.8/site-packages/samcli/commands/local/lib/local_lambda.py", line 84, in invoke
    function = self.provider.get(function_name)
  File "/usr/lib/python3.8/site-packages/samcli/lib/providers/sam_function_provider.py", line 65, in get
    raise ValueError("Function name is required")
ValueError: Function name is required
```

### Environment

  - **CLI Version      :** 1.65.0 (build 1c2cba4)
  - **Framework Version:**
  - **Node.js Version:** v14.10.1
  - **OS               :** 5.4.65-1-MANJARO
  - **Language (Version):** TypeScript (3.9.3)

### Other

--- 

This is :bug: Bug Report

**Comment by nija-at** [comment]
We're not familiar with how `sam local` works unfortunately. Please reach out to the SAM CLI repo - https://github.com/aws/aws-sam-cli - with the generated template that you can find in `cdk.out/`.

If there is a specific error in the produced template, we'll be happy to help and fix.

**Comment by myin142** [comment]
Waiting for a reply in aws/aws-sam-cli#2287

**Comment by nija-at** [comment]
Thanks! Please re-open this issue or a new issue once you get more details.
