### ISSUE TITLE
[aws_cloudtrail] There is no example of add_s3_event_selector function in Python

### ISSUE THREAD

**Issue by kafka399** [aws/aws-cdk#10775]
https://docs.aws.amazon.com/cdk/api/latest/python/aws_cdk.aws_cloudtrail/Trail.html

### Reproduction Steps

I'm trying to create a trail for a S3 bucket in python, but I haven't managed to resolve the error:

        imgTrail = trail.Trail(self, 'newImageUploadTrail', management_events=trail.ReadWriteType.NONE)
        bucket_arn = 'arn:aws:s3:::{}/'.format(NEW_IMAGES_BUCKET)
        bucket_selector = trail.S3EventSelector(bucket=[bucket_arn])

        imgTrail.add_s3_event_selector([bucket_selector])

### What did you expect to happen?

I expect a trail for a specific S3 bucket to be created.

### What actually happened?

Here is the **error**

    Traceback (most recent call last):
      File "app.py", line 12, in <module>
    'region': os.environ['CDK_DEFAULT_REGION']
      File "/Users/d/ml_projects/development_packages/lib/python3.7/site-packages/jsii/_runtime.py", line 69, in __call__
    inst = super().__call__(*args, **kwargs)
      File "/Users/d/WorkDocs/ml_projects/ubiqisense/ubi_prototype/cdk/cdk/cdk_stack.py", line 45, in __init__
    imgTrail.add_s3_event_selector([bucket_selector])
      File "/Users/d/ml_projects/development_packages/lib/python3.7/site-packages/aws_cdk/aws_cloudtrail/__init__.py", line 1201, in add_s3_event_selector
    return jsii.invoke(self, "addS3EventSelector", [s3_selector, options])
      File "/Users/d/ml_projects/development_packages/lib/python3.7/site-packages/jsii/_kernel/__init__.py", line 125, in wrapped
    return _recursize_dereference(kernel, fn(kernel, *args, **kwargs))
      File "/Users/d/ml_projects/development_packages/lib/python3.7/site-packages/jsii/_kernel/__init__.py", line 319, in invoke
    args=_make_reference_for_native(self, args),
      File "/Users/d/ml_projects/development_packages/lib/python3.7/site-packages/jsii/_kernel/providers/process.py", line 351, in invoke
    return self._process.send(request, InvokeResponse)
      File "/Users/d/ml_projects/development_packages/lib/python3.7/site-packages/jsii/_kernel/providers/process.py", line 321, in send
    raise JSIIError(resp.error) from JavaScriptError(resp.stack)
    jsii.errors.JSIIError: Expected object reference, got ["arn:aws:s3:::unew-images/"]

### Environment

  - **CLI Version      :** 1.66.0 (build 459488d)
  - **Framework Version:**
  - **Node.js Version:** v10.15.3
  - **OS               :** MacOs
  - **Language (Version):** Python (3.7.3)  -->

### Other

--- 

This is :bug: Bug Report

**Comment by kafka399** [comment]
Here is working solution:

    bucket = s3.Bucket(self, id = NEW_IMAGES_BUCKET,bucket_name = NEW_IMAGES_BUCKET)
    imgTrail = trail.Trail(self, 'newImageUploadTrail', management_events=trail.ReadWriteType.WRITE_ONLY)
    bucket_selector = trail.S3EventSelector(bucket=bucket)
    imgTrail.add_s3_event_selector([bucket_selector])
