### ISSUE TITLE
[pipelines] self-update build fails with named pipeline stack

### ISSUE THREAD

**Issue by SimonAdameit** [aws/aws-cdk#10782]
When naming the pipeline stack using the `stackName` property with a different name than the `id`, the self-update build fails with an error that it cannot find the stack.

### Reproduction Steps

Create a pipeline project and give the pipeline stack a custom name.
```typescript
import * as cdk from '@aws-cdk/core';
import { PipelineStack } from '../lib/pipeline-stack';

const app = new cdk.App();

new PipelineStack(app, 'PipelineStack', {
    stackName: 'Pipeline'
});

app.synth();
```
Then deploy the project and have a look at the pipeline execution.

### What did you expect to happen?

I expected the pipeline stack to be named 'Pipeline'. This happened successfully on the first deploy from my local command line. Then I expected the pipeline build to execute successfully and update the pipeline, however this step failed. It works fine, when I don't supply a `stackName`.

### What actually happened?

The update build failed with the error message that it could not find the stack 'Pipeline'. 

```
95	No stack found matching 'Pipeline'. Use "list" to print manifest
96	Error: No stack found matching 'Pipeline'. Use "list" to print manifest
97	    at CloudAssembly.selectStacks (/usr/local/lib/node_modules/aws-cdk/lib/api/cxapp/cloud-assembly.ts:115:15)
98	    at CdkToolkit.selectStacksForDeploy (/usr/local/lib/node_modules/aws-cdk/lib/cdk-toolkit.ts:381:35)
99	    at CdkToolkit.deploy (/usr/local/lib/node_modules/aws-cdk/lib/cdk-toolkit.ts:111:20)
100	    at initCommandLine (/usr/local/lib/node_modules/aws-cdk/bin/cdk.ts:197:9)
```

### Environment

  - **CLI Version      : 1.66.0**
  - **Framework Version: 1.66.0**
  - **Node.js Version: v14.11.0** 
  - **OS               :  Linux x86_64**
  - **Language (Version): Typescript** 

### Other

--- 

This is :bug: Bug Report

**Comment by JohnFBartlett** [comment]
I'm also having this issue, but it happens regardless of whether I provide a stack name. The self-update step always fails to find the stack:

```
No stack found matching 'ServiceDeployPipelineStack'. Use "list" to print manifest
Error: No stack found matching 'ServiceDeployPipelineStack'. Use "list" to print manifest
    at CloudAssembly.selectStacks (/usr/local/lib/node_modules/aws-cdk/lib/api/cxapp/cloud-assembly.ts:115:15)
    at CdkToolkit.selectStacksForDeploy (/usr/local/lib/node_modules/aws-cdk/lib/cdk-toolkit.ts:381:35)
    at CdkToolkit.deploy (/usr/local/lib/node_modules/aws-cdk/lib/cdk-toolkit.ts:111:20)
    at initCommandLine (/usr/local/lib/node_modules/aws-cdk/bin/cdk.ts:201:9)
[Container] 2020/12/10 02:34:10 Command did not exit successfully cdk -a . deploy ServiceDeployPipelineStack --require-approval=never --verbose exit status 1
```

I'm using the base pipeline + CDK pipeline method, maybe that's why it's having trouble resolving the names?

```
...
const basePipeline = new codepipeline.Pipeline(
      this,
      "ServiceDeployPipeline",
      {
        pipelineName: "ServiceDeployPipeline",
        restartExecutionOnUpdate: true
      }
    );

    const pipeline = new CdkPipeline(this, "CDKPipeline", {

      cloudAssemblyArtifact,
      codePipeline: basePipeline,
...
```

**Comment by rix0rrr** [comment]
Probably a CLI-related issue around identifying stacks (by name or by artifact ID).

**Comment by alehatsman** [comment]
Hello,

I was able to workaround the issue with next code:

```
class MyCdkPipeline extends CdkPipeline {
  constructor(scope: cdk.Construct, id: string, props: CdkPipelineProps) {
    // pass self mutating false to prevent bug behaviour
    super(scope, id, {...props, selfMutating: false});

    const pipelineStack = cdk.Stack.of(this);

    if (props.selfMutating ?? true) {
      this.codePipeline.addStage({
        stageName: 'UpdatePipeline',
        actions: [new UpdatePipelineAction(this, 'UpdatePipeline', {
          cloudAssemblyInput: props.cloudAssemblyArtifact,
          // use logical id as pipelineStackName to get correct cli command
          pipelineStackName: pipelineStack.node.id,
          cdkCliVersion: props.cdkCliVersion,
          projectName: `${props.pipelineName}-selfupdate`,
        })]
      })
    }
  }
}
```

**Comment by cstst** [comment]
@otaviomacedo the above workaround doesn't seem to work for me on `v1.100.0`. Any idea why?
