### ISSUE TITLE
cdk pipelines 

### ISSUE THREAD

**Issue by AungBoTun** [aws/aws-cdk#10798]
.env) XXXX@MacBook-Pro piplines % cdk bootstrap --cloudfromation-execution-policies arn:aws:iam::aws:policy/AdministratorAccess
'@aws-cdk/core:newStyleStackSynthesis' context set, using new-style bootstrapping
 ⏳  Bootstrapping environment aws://XXXX/ap-southeast-1...
 ❌  Environment aws://XXXXX/ap-southeast-1 failed bootstrapping: Error: Please pass '--cloudformation-execution-policies' to specify deployment permissions. Try a managed policy of the form 'arn:aws:iam::aws:policy/<PolicyName>'.
    at Bootstrapper.modernBootstrap (/usr/local/lib/node_modules/aws-cdk/lib/api/bootstrap/bootstrap-environment.ts:101:13)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at /usr/local/lib/node_modules/aws-cdk/lib/cdk-toolkit.ts:358:24
    at async Promise.all (index 0)
    at CdkToolkit.bootstrap (/usr/local/lib/node_modules/aws-cdk/lib/cdk-toolkit.ts:355:5)
    at initCommandLine (/usr/local/lib/node_modules/aws-cdk/bin/cdk.ts:197:9)
Please pass '--cloudformation-execution-policies' to specify deployment permissions. Try a managed policy of the form 'arn:aws:iam::aws:policy/<PolicyName>'.

______

cdk.json
{
  "app": "python3 app.py",
  "context": {
    "@aws-cdk/core:enableStackNameDuplicates": "true",
    "aws-cdk:enableDiffNoFail": "true",
    "@aws-cdk/core:stackRelativeExports": "true",
    "@aws-cdk/core:newStyleStackSynthesis": "true"
  }
}

**Comment by AungBoTun** [comment]
FYI 
working now because i removed "@aws-cdk/core:newStyleStackSynthesis": "true" in cdk.json .
cdk--version 1.67.0

**Comment by AungBoTun** [comment]
FYI
working now because i removed "@aws-cdk/core:newStyleStackSynthesis": "true" in cdk.json .
cdk--version 1.67.0
