### ISSUE TITLE
[ecs] Removing cluster capacity results in catch-22 with VPC private subnet export removal

### ISSUE THREAD

**Issue by rcollette** [aws/aws-cdk#10961]
With an existing VPC (stack 1) and ECS cluster (stack 2), where the cluster has an autoscaling group defined using the addCapacity method, subsequently removing the capacity/autoscaling group results in an attempt to remove exports in stack1 for the VPC private subnets, prior to implementing the changes in stack 2.  The deployment rolls back because it cannot remove the exports from stack 1 while they are still being referenced in stack2.

When trying to deploy just stack2, it says it has a dependency on stack1, and still tries to first remove the exports prior to updating stack2

This leaves no option for deploying the changes other than to manually remove stack2 (the entire ECS cluster)

### Reproduction Steps
Create a CDK application that will create two stacks

In stack1, create a VPC like:

```typescript
    private _createVpc() {
        this.vpc = new Vpc(this, `AccountVpc`, {
            cidr: this._props.vpcCidr,
            maxAzs: this._props.vpcMaxAvailabilityZones
        });
        this._properties.vpcId = this.vpc.vpcId;
    }
```
Passing a reference to the VPC, into stack2, create an ECS cluster

```typescript
    private _createComputeCluster(vpc: Vpc) {
        const cluster = new Cluster(this, 'ComputeCluster', {
           // note this is a reference to the VPC that was created in stack1.  It is not an IVpc.
            vpc,
            clusterName: `${this._props.accountName}-${this._props.deploymentEnvironment}-compute-cluster`,
            defaultCloudMapNamespace: {
                name: `${this._props.accountName}-${this._props.deploymentEnvironment}-namespace`,
                vpc
            },
            containerInsights: true
        });
        const computeCluster = this._props.computeCluster;
        this.autoScalingGroup = cluster.addCapacity('DefaultAutoScalingGroup', {
            minCapacity: computeCluster.minCapacity,
            maxCapacity: computeCluster.maxCapacity,
            instanceType: computeCluster.instanceType,
        });
        this.autoScalingGroup.scaleOnCpuUtilization(`CpuTargetUtilizationPercent${this._props.computeCluster.cpuTargetUtilizationPercent}`, {
            targetUtilizationPercent: computeCluster.cpuTargetUtilizationPercent
        });
        this._properties.computeClusterArn = cluster.clusterArn;
        this._properties.computeClusterName = cluster.clusterName;
        this.computeCluster = cluster;
    }
```

Deploy the two stacks:
`cdk deploy "*"`

Then remove the scaling group

```typescript
    private _createComputeCluster(vpc: Vpc) {
        const cluster = new Cluster(this, 'ComputeCluster', {
            vpc,
            clusterName: `${this._props.accountName}-${this._props.deploymentEnvironment}-compute-cluster`,
            defaultCloudMapNamespace: {
                name: `${this._props.accountName}-${this._props.deploymentEnvironment}-namespace`,
                vpc
            },
            containerInsights: true
        });
        this._properties.computeClusterArn = cluster.clusterArn;
        this._properties.computeClusterName = cluster.clusterName;
        this.computeCluster = cluster;
    }
```

deploy the two stacks again.

### What did you expect to happen?

The updates to the stack containing the ECS cluster should be applied before removal of dependencies in the VPC stack.

### What actually happened?

Exports from the VPC stack are attempted to be removed before dependents that rely on them are updated.  The deployment fails and the stack updates rollback.

### Environment

  - **CLI Version      :**
  - **Framework Version:**
  - **Node.js Version:** 
  - **OS               :**
  - **Language (Version):** 

### Other

Diff output

```
Stack pdx
There were no differences
Stack pdx-dev-vpc
There were no differences
Stack pdx-dev-resources
There were no differences
US-RI026CO-MLT:cdk-account-application richardcollette$ ./cdk-diff-dev.sh 
Stack pdx
There were no differences
Stack pdx-dev-vpc
Outputs
[-] Output ExportsOutputRefAccountVpcPrivateSubnet1SubnetE64A1D73D23B0322: {"Value":{"Ref":"AccountVpcPrivateSubnet1SubnetE64A1D73"},"Export":{"Name":"pdx-dev-vpc:ExportsOutputRefAccountVpcPrivateSubnet1SubnetE64A1D73D23B0322"}}
[-] Output ExportsOutputRefAccountVpcPrivateSubnet2SubnetD38DC524436F5D95: {"Value":{"Ref":"AccountVpcPrivateSubnet2SubnetD38DC524"},"Export":{"Name":"pdx-dev-vpc:ExportsOutputRefAccountVpcPrivateSubnet2SubnetD38DC524436F5D95"}}

Stack pdx-dev-resources
IAM Statement Changes
┌───┬─────────────────────────────────────────┬────────┬─────────────────────────────────────────┬─────────────────────────────────────────┬───────────────────────────────────────────┐
│   │ Resource                                │ Effect │ Action                                  │ Principal                               │ Condition                                 │
├───┼─────────────────────────────────────────┼────────┼─────────────────────────────────────────┼─────────────────────────────────────────┼───────────────────────────────────────────┤
│ - │ ${ComputeCluster.Arn}                   │ Allow  │ ecs:DeregisterContainerInstance         │ AWS:${ComputeClusterDefaultAutoScalingG │                                           │
│   │                                         │        │ ecs:RegisterContainerInstance           │ roupInstanceRole87EB0B83}               │                                           │
│   │                                         │        │ ecs:Submit*                             │                                         │                                           │
│ - │ ${ComputeCluster.Arn}                   │ Allow  │ ecs:ListContainerInstances              │ AWS:${ComputeClusterDefaultAutoScalingG │                                           │
│   │                                         │        │ ecs:SubmitContainerStateChange          │ roupDrainECSHookFunctionServiceRoleD0A2 │                                           │
│   │                                         │        │ ecs:SubmitTaskStateChange               │ D0BE}                                   │                                           │
├───┼─────────────────────────────────────────┼────────┼─────────────────────────────────────────┼─────────────────────────────────────────┼───────────────────────────────────────────┤
│ - │ ${ComputeClusterDefaultAutoScalingGroup │ Allow  │ lambda:InvokeFunction                   │ Service:sns.amazonaws.com               │ "ArnLike": {                              │
│   │ DrainECSHookFunction53197394.Arn}       │        │                                         │                                         │   "AWS:SourceArn": "${ComputeClusterDefau │
│   │                                         │        │                                         │                                         │ ltAutoScalingGroupLifecycleHookDrainHookT │
│   │                                         │        │                                         │                                         │ opicB9813877}"                            │
│   │                                         │        │                                         │                                         │ }                                         │
├───┼─────────────────────────────────────────┼────────┼─────────────────────────────────────────┼─────────────────────────────────────────┼───────────────────────────────────────────┤
│ - │ ${ComputeClusterDefaultAutoScalingGroup │ Allow  │ sns:Publish                             │ AWS:${ComputeClusterDefaultAutoScalingG │                                           │
│   │ LifecycleHookDrainHookTopicB9813877}    │        │                                         │ roupLifecycleHookDrainHookRoleB5807D5F} │                                           │
├───┼─────────────────────────────────────────┼────────┼─────────────────────────────────────────┼─────────────────────────────────────────┼───────────────────────────────────────────┤
│ - │ *                                       │ Allow  │ ecs:Poll                                │ AWS:${ComputeClusterDefaultAutoScalingG │ "ArnEquals": {                            │
│   │                                         │        │ ecs:StartTelemetrySession               │ roupInstanceRole87EB0B83}               │   "ecs:cluster": "${ComputeCluster.Arn}"  │
│   │                                         │        │                                         │                                         │ }                                         │
│ - │ *                                       │ Allow  │ ecr:GetAuthorizationToken               │ AWS:${ComputeClusterDefaultAutoScalingG │                                           │
│   │                                         │        │ ecs:DiscoverPollEndpoint                │ roupInstanceRole87EB0B83}               │                                           │
│   │                                         │        │ logs:CreateLogStream                    │                                         │                                           │
│   │                                         │        │ logs:PutLogEvents                       │                                         │                                           │
│ - │ *                                       │ Allow  │ ec2:DescribeHosts                       │ AWS:${ComputeClusterDefaultAutoScalingG │                                           │
│   │                                         │        │ ec2:DescribeInstanceAttribute           │ roupDrainECSHookFunctionServiceRoleD0A2 │                                           │
│   │                                         │        │ ec2:DescribeInstanceStatus              │ D0BE}                                   │                                           │
│   │                                         │        │ ec2:DescribeInstances                   │                                         │                                           │
│ - │ *                                       │ Allow  │ ecs:DescribeContainerInstances          │ AWS:${ComputeClusterDefaultAutoScalingG │ "ArnEquals": {                            │
│   │                                         │        │ ecs:DescribeTasks                       │ roupDrainECSHookFunctionServiceRoleD0A2 │   "ecs:cluster": "${ComputeCluster.Arn}"  │
│   │                                         │        │                                         │ D0BE}                                   │ }                                         │
│ - │ *                                       │ Allow  │ ecs:ListTasks                           │ AWS:${ComputeClusterDefaultAutoScalingG │ "ArnEquals": {                            │
│   │                                         │        │ ecs:UpdateContainerInstancesState       │ roupDrainECSHookFunctionServiceRoleD0A2 │   "ecs:cluster": "${ComputeCluster.Arn}"  │
│   │                                         │        │                                         │ D0BE}                                   │ }                                         │
├───┼─────────────────────────────────────────┼────────┼─────────────────────────────────────────┼─────────────────────────────────────────┼───────────────────────────────────────────┤
│ - │ arn:${AWS::Partition}:autoscaling:us-ea │ Allow  │ autoscaling:CompleteLifecycleAction     │ AWS:${ComputeClusterDefaultAutoScalingG │                                           │
│   │ st-1:111111111111:autoScalingGroup:*:au │        │                                         │ roupDrainECSHookFunctionServiceRoleD0A2 │                                           │
│   │ toScalingGroupName/${ComputeClusterDefa │        │                                         │ D0BE}                                   │                                           │
│   │ ultAutoScalingGroupASG79A2340F}         │        │                                         │                                         │                                           │
└───┴─────────────────────────────────────────┴────────┴─────────────────────────────────────────┴─────────────────────────────────────────┴───────────────────────────────────────────┘
(NOTE: There may be security-related changes not in this list. See https://github.com/aws/aws-cdk/issues/1299)

Parameters
[-] Parameter SsmParameterValueawsserviceecsoptimizedamiamazonlinux2recommendedimageidC96584B6F00A464EAD1953AFF4B05118Parameter: {"Type":"AWS::SSM::Parameter::Value<AWS::EC2::Image::Id>","Default":"/aws/service/ecs/optimized-ami/amazon-linux-2/recommended/image_id"}

Resources
[-] AWS::EC2::SecurityGroup ComputeClusterDefaultAutoScalingGroupInstanceSecurityGroupD878B24E destroy
[-] AWS::IAM::Role ComputeClusterDefaultAutoScalingGroupInstanceRole87EB0B83 destroy
[-] AWS::IAM::Policy ComputeClusterDefaultAutoScalingGroupInstanceRoleDefaultPolicyE5FB8B46 destroy
[-] AWS::IAM::InstanceProfile ComputeClusterDefaultAutoScalingGroupInstanceProfile1D6A0A6A destroy
[-] AWS::AutoScaling::LaunchConfiguration ComputeClusterDefaultAutoScalingGroupLaunchConfig418EFE33 destroy
[-] AWS::AutoScaling::AutoScalingGroup ComputeClusterDefaultAutoScalingGroupASG79A2340F destroy
[-] AWS::IAM::Role ComputeClusterDefaultAutoScalingGroupDrainECSHookFunctionServiceRoleD0A2D0BE destroy
[-] AWS::IAM::Policy ComputeClusterDefaultAutoScalingGroupDrainECSHookFunctionServiceRoleDefaultPolicy0AD5188B destroy
[-] AWS::Lambda::Function ComputeClusterDefaultAutoScalingGroupDrainECSHookFunction53197394 destroy
[-] AWS::Lambda::Permission ComputeClusterDefaultAutoScalingGroupDrainECSHookFunctionAllowInvokepdxdevresourcesComputeClusterDefaultAutoScalingGroupLifecycleHookDrainHookTopic480F6A418B91F74C destroy
[-] AWS::SNS::Subscription ComputeClusterDefaultAutoScalingGroupDrainECSHookFunctionTopicE88A3B15 destroy
[-] AWS::IAM::Role ComputeClusterDefaultAutoScalingGroupLifecycleHookDrainHookRoleB5807D5F destroy
[-] AWS::IAM::Policy ComputeClusterDefaultAutoScalingGroupLifecycleHookDrainHookRoleDefaultPolicy040CA8FC destroy
[-] AWS::SNS::Topic ComputeClusterDefaultAutoScalingGroupLifecycleHookDrainHookTopicB9813877 destroy
[-] AWS::AutoScaling::LifecycleHook ComputeClusterDefaultAutoScalingGroupLifecycleHookDrainHook193A67B9 destroy
[-] AWS::AutoScaling::ScalingPolicy ComputeClusterDefaultAutoScalingGroupScalingPolicyCpuTargetUtilizationPercent709C85FDE2 destroy

```

Deploy output
```
pdx
pdx: deploying...

 ✅  pdx (no changes)

Stack ARN:
arn:aws:cloudformation:us-east-1:111111111111:stack/pdx/2e7bef50-04e8-11eb-b974-0e167b726915
pdx-dev-vpc
pdx-dev-vpc: deploying...
pdx-dev-vpc: creating CloudFormation changeset...
[█████████████████████████████·····························] (1/2)

1:27:28 PM | UPDATE_ROLLBACK_IN_P | AWS::CloudFormation::Stack            | pdx-dev-vpc
Export pdx-dev-vpc:ExportsOutputRefAccountVpcPrivateSubnet1SubnetE64A1D73D23B0322 cannot be deleted as it is in use by pdx-dev-resources



 ❌  pdx-dev-vpc failed: Error: The stack named pdx-dev-vpc failed to deploy: UPDATE_ROLLBACK_COMPLETE
    at Object.waitForStackDeploy (/Users/richardcollette/.nvm/versions/node/v12.13.0/lib/node_modules/aws-cdk/lib/api/util/cloudformation.ts:307:11)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at Object.deployStack (/Users/richardcollette/.nvm/versions/node/v12.13.0/lib/node_modules/aws-cdk/lib/api/deploy-stack.ts:283:26)
    at CdkToolkit.deploy (/Users/richardcollette/.nvm/versions/node/v12.13.0/lib/node_modules/aws-cdk/lib/cdk-toolkit.ts:180:24)
    at initCommandLine (/Users/richardcollette/.nvm/versions/node/v12.13.0/lib/node_modules/aws-cdk/bin/cdk.ts:197:9)
The stack named pdx-dev-vpc failed to deploy: UPDATE_ROLLBACK_COMPLETE

```
Excerpt from Stack2 template showing VPCZoneIdentifier having references to outputs from Stack1

```json
"ComputeClusterDefaultAutoScalingGroupASG79A2340F": {
      "Type": "AWS::AutoScaling::AutoScalingGroup",
      "Properties": {
        "MaxSize": "4",
        "MinSize": "2",
        "LaunchConfigurationName": {
          "Ref": "ComputeClusterDefaultAutoScalingGroupLaunchConfig418EFE33"
        },
        "Tags": [
          {
            "Key": "Name",
            "PropagateAtLaunch": true,
            "Value": "pdx-prd-resources/ComputeCluster/DefaultAutoScalingGroup"
          }
        ],
        "VPCZoneIdentifier": [
          {
            "Fn::ImportValue": "pdx-prd-vpc:ExportsOutputRefAccountVpcPrivateSubnet1SubnetE64A1D73D23B0322"
          },
          {
            "Fn::ImportValue": "pdx-prd-vpc:ExportsOutputRefAccountVpcPrivateSubnet2SubnetD38DC524436F5D95"
          }
        ]
      },
      "UpdatePolicy": {
        "AutoScalingReplacingUpdate": {
          "WillReplace": true
        },
        "AutoScalingScheduledAction": {
          "IgnoreUnmodifiedGroupSizeProperties": true
        }
      },
      "Metadata": {
        "aws:cdk:path": "pdx-prd-resources/ComputeCluster/DefaultAutoScalingGroup/ASG"
      }
    }
}
```

--- 

This is :bug: Bug Report

**Comment by skinny85** [comment]
Hey @rcollette ,

thanks for opening the issue. While dealing with removing cross-stack references can be tricky in the CDK, there is actually a way to do it. Check out this article: https://www.endoflineblog.com/cdk-tips-03-how-to-unblock-cross-stack-references for a step-by-step description how to unblock yourself.

Thanks,
Adam

**Comment by rcollette** [comment]
@skinny85  - Thank you for the article.   However, that is a cumbersome work-around at best.

Imagine if to deploy a change in CDK itself, you had to go through 1 round of merge reviews to do this and then another entire round of merge reviews, just for this workaround.

I don't know what the case for fixing this in all scenarios would be, because the consumer may be reliant on additions to the producing stack as well as removing dependencies from the producing stack (a real catch 22 but perhaps the cli should be doing a multi-iteration deploy, kind of like what compilers do)

However, at least in the case where the producing stack (or perhaps any stack) only has deletions, it would seem reasonable that the CLI should deploy delete only stacks after stacks that have additions/changes.

**Comment by skinny85** [comment]
> Imagine if to deploy a change in CDK itself, you had to go through 1 round of merge reviews to do this and then another entire round of merge reviews, just for this workaround.

Yes.

> I don't know what the case for fixing this in all scenarios would be, because the consumer may be reliant on additions to the producing stack as well as removing dependencies from the producing stack (a real catch 22 but perhaps the cli should be doing a multi-iteration deploy, kind of like what compilers do)

Just to make sure it's obvious, the workaround from the article covers this case as well (see https://github.com/skinny85/cdk-reference-unblocking ).

**Comment by rcollette** [comment]
keep open

**Comment by rcollette** [comment]
keep
