### ISSUE TITLE
CDK throws "ENOENT: no such file or directory, open cdk.out\manifest.json" in most commands

### ISSUE THREAD

**Issue by AlanCS** [aws/aws-cdk#11023]
Any command I try from the CDK throws this error

### Reproduction Steps

Download the code from https://github.com/AlanCS/WorkSplitCalculator
and run for example "cdk list --verbose"

### What did you expect to happen?

I copied the project from https://github.com/aws-samples/aws-cdk-examples/tree/master/csharp/capitalize-string and made a few changes (like moving to .net core 3.1) and added an API gateway, now the whole thing stopped working

just as a test, I tried to run the commands on the original example, and now those throw the same error as well

I expected to work straight out of the box

### What actually happened?

```console
# cdk list --verbose
(node:10492) ExperimentalWarning: The fs.promises API is experimental
CDK toolkit version: 1.69.0 (build 2b474b9)
Command line arguments: { _: [ 'list' ],
  verbose: 1,
  v: 1,
  'ignore-errors': false,
  ignoreErrors: false,
  json: false,
  j: false,
  ec2creds: undefined,
  i: undefined,
  'version-reporting': undefined,
  versionReporting: undefined,
  'path-metadata': true,
  pathMetadata: true,
  'asset-metadata': true,
  assetMetadata: true,
  'role-arn': undefined,
  r: undefined,
  roleArn: undefined,
  staging: true,
  'no-color': false,
  noColor: false,
  fail: false,
  long: false,
  l: false,
  '$0':
   'C:\\ProgramData\\scoop\\apps\\nodejs\\current\\bin\\node_modules\\aws-cdk\\bin\\cdk' }
cdk.json: {
  "app": "dotnet publish -c Release src"
}
merged settings: { versionReporting: true,
  pathMetadata: true,
  output: 'cdk.out',
  app: 'dotnet publish -c Release src',
  context: {},
  assetMetadata: true,
  toolkitBucket: {},
  staging: true,
  bundlingStacks: [] }
Determining if we're on an EC2 instance.
Does not look like an EC2 instance.
Toolkit stack: CDKToolkit
Setting "CDK_DEFAULT_REGION" environment variable to ap-southeast-2
Resolving default credentials
Retrieved account ID 123456789 from disk cache
Setting "CDK_DEFAULT_ACCOUNT" environment variable to 123456789
context: { 'aws:cdk:enable-path-metadata': true,
  'aws:cdk:enable-asset-metadata': true,
  'aws:cdk:version-reporting': true,
  'aws:cdk:bundling-stacks': [] }
outdir: cdk.out
env: { CDK_DEFAULT_REGION: 'ap-southeast-2',
  CDK_DEFAULT_ACCOUNT: '123456789',
  CDK_CONTEXT_JSON:
   '{"aws:cdk:enable-path-metadata":true,"aws:cdk:enable-asset-metadata":true,"aws:cdk:version-reporting":true,"aws:cdk:bundling-stacks":[]}',
  CDK_OUTDIR: 'cdk.out',
  CDK_CLI_ASM_VERSION: '6.0.0',
  CDK_CLI_VERSION: '1.69.0' }
Microsoft (R) Build Engine version 16.7.0+7fb82e5b2 for .NET
Copyright (C) Microsoft Corporation. All rights reserved.

  Determining projects to restore...
  All projects are up-to-date for restore.
  CapitalizeStringHandler -> C:\Users\AlanPC\source\repos\WorkSplitCalculator\src\CapitalizeStringHandler\bin\Release\netcoreapp3.1\CapitalizeStringHandler.dll
  CapitalizeStringHandler -> C:\Users\AlanPC\source\repos\WorkSplitCalculator\src\CapitalizeStringHandler\bin\Release\netcoreapp3.1\publish\
  CapitalizeStringHandler.Tests -> C:\Users\AlanPC\source\repos\WorkSplitCalculator\src\test\CapitalizeStringHandler.Tests\bin\Release\netcoreapp3.1\CapitalizeStringHandler.Tests.dll
  CdkStack -> C:\Users\AlanPC\source\repos\WorkSplitCalculator\src\CdkStack\bin\Release\netcoreapp3.1\CdkStack.dll
  CapitalizeStringHandler.Tests -> C:\Users\AlanPC\source\repos\WorkSplitCalculator\src\test\CapitalizeStringHandler.Tests\bin\Release\netcoreapp3.1\publish\
  CdkStack -> C:\Users\AlanPC\source\repos\WorkSplitCalculator\src\CdkStack\bin\Release\netcoreapp3.1\publish\
ENOENT: no such file or directory, open 'cdk.out\manifest.json'
Error: ENOENT: no such file or directory, open 'cdk.out\manifest.json'
    at Object.fs.openSync (fs.js:577:3)
    at Object.fs.readFileSync (fs.js:483:33)
    at Function.loadManifest (C:\ProgramData\scoop\persist\nodejs\bin\node_modules\aws-cdk\node_modules\@aws-cdk\cloud-assembly-schema\lib\manifest.ts:131:29)
    at Function.loadAssemblyManifest (C:\ProgramData\scoop\persist\nodejs\bin\node_modules\aws-cdk\node_modules\@aws-cdk\cloud-assembly-schema\lib\manifest.ts:44:21)
    at Function.load (C:\ProgramData\scoop\persist\nodejs\bin\node_modules\aws-cdk\node_modules\@aws-cdk\cloud-assembly-schema\lib\manifest.ts:83:81)
    at new CloudAssembly (C:\ProgramData\scoop\persist\nodejs\bin\node_modules\aws-cdk\node_modules\@aws-cdk\cx-api\lib\cloud-assembly.ts:52:39)
    at createAssembly (C:\ProgramData\scoop\persist\nodejs\bin\node_modules\aws-cdk\lib\api\cxapp\exec.ts:78:14)
    at Object.execProgram (C:\ProgramData\scoop\persist\nodejs\bin\node_modules\aws-cdk\lib\api\cxapp\exec.ts:74:10)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

### Environment

Running Visual Studio 2019 on a Windows 10 machine

### Other

--- 

This is :bug: Bug Report

**Comment by SomayaB** [comment]
Hi @AlanCS, I'm getting a `Page not found` error when cling on your repo link. Can you also provide the following information:

  - **CDK CLI Version:** 
  - **Node.js Version:** 
  - **OS:** 
  - **Language (Version):**

**Comment by AlanCS** [comment]
> Hi @AlanCS, I'm getting a `Page not found` error when cling on your repo link. Can you also provide the following information:
> 
* **CDK CLI Version:** 1.69.0
* **Node.js Version:** v15.0.1
* **OS:** Microsoft Windows 10 Pro
* **Language (Version):** .net core 3.1

very sorry, try again, I just made the repo public

**Comment by AlanCS** [comment]
forgive me, this was not a bug, I was a bit confused and managed to work it out
I was following the example https://github.com/aws-samples/aws-cdk-examples/blob/master/csharp/capitalize-string/cdk.json#L2
but that line was throwing errors (MSBUILD : error MSB1008: Only one project can be specified.); so I remove teh run command, thinking it was optional
turns out the right command was separated by pipe
```c#
dotnet publish -c Release CapitalizeStringHandler/src/CapitalizeStringHandler | dotnet run -p src/CapitalizeString
```

**Comment by wcheek** [comment]
For me, this was also not a bug. I had accidentally removed `app.synth()` at the bottom of my `app.py`. Add it back and you should be good to go!
