### ISSUE TITLE
Error running cdk bootstrap

### ISSUE THREAD

**Issue by deccy-mcc** [aws/aws-cdk#11219]
We have just started getting this error running cdk bootstrap -

+ cdk bootstrap --context Version=OurVersion --context Environment=OurEnvironment --context DeploymentType=Full
Traceback (most recent call last):
  File "app.py", line 3, in <module>
    from aws_cdk import core
  File "/usr/local/lib/python3.6/site-packages/aws_cdk/core/__init__.py", line 904, in <module>
    import jsii
  File "/usr/local/lib/python3.6/site-packages/jsii/__init__.py", line 4, in <module>
    from ._runtime import (
  File "/usr/local/lib/python3.6/site-packages/jsii/_runtime.py", line 10, in <module>
    from ._kernel import Kernel
  File "/usr/local/lib/python3.6/site-packages/jsii/_kernel/__init__.py", line 15, in <module>
    from .providers import BaseProvider, ProcessProvider
  File "/usr/local/lib/python3.6/site-packages/jsii/_kernel/providers/__init__.py", line 2, in <module>
    from .process import ProcessProvider
  File "/usr/local/lib/python3.6/site-packages/jsii/_kernel/providers/process.py", line 16, in <module>
    import cattr  # type: ignore
  File "/usr/local/lib/python3.6/site-packages/cattr/__init__.py", line 1, in <module>
    from .converters import Converter, GenConverter, UnstructureStrategy
  File "/usr/local/lib/python3.6/site-packages/cattr/converters.py", line 18, in <module>
    from ._compat import (
  File "/usr/local/lib/python3.6/site-packages/cattr/_compat.py", line 31, in <module>
    from typing import get_args, get_origin  # NOQA
ImportError: cannot import name 'get_args'
Subprocess exited with error 1

I have tried pinning the version of aws_cdk and the python libraries we use to 1.70.0 (which worked yesterday), but we still get the same error.

Any help would be appreciated.

**Comment by deccy-mcc** [comment]
UPDATE:

We discovered that the library cattrs has also been updated since yesterday, specifying the previous version of cattrs (1.0.0) in our pip install has allowed us to get around the issue for now.

I assume there is an incompatibility between the latest version of cdk and cattrs

**Comment by jaystary** [comment]
I had the same problem with 3.6.11 - changing the python version (in my case 3.8.3) fixed the issue for me.

**Comment by jorgenfroland** [comment]
I aslo got this error on python 3.6.8 (Windows 10) after upgrading to aws cdk 1.71.0. I also fixed this by downgrading cattrs to 1.0.0. Looks like 1.1.0 (which was installed) is yanked, but Im not able to install 1.1.1. Got this error: ERROR: No matching distribution found for cattrs==1.1.1. So not able to verify if 1.1.1 is compatible.

**Comment by RomainMuller** [comment]
The issue is `cattrs@1.1.0` dropped support for Python 3.6. I'm preparing a PR to fix this issue by declaring a platform-dependent dependency...

**Comment by RomainMuller** [comment]
By the way, @deccy-mcc - thank you very much for reporting this and your independent findings.
