### ISSUE TITLE
[pipelines] Cannot use `DockerImage.fromAsset()` as CodeBuild environment

### ISSUE THREAD

**Issue by asterikx** [aws/aws-cdk#11425]
The `SelfMutate` action fails with the error `Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?`

My pipeline uses a custom build image in the `Build` stage through `codebuild.LinuxBuildImage.fromAsset`. This requires building and publishing the build image in the `SelfMutate` action.

This is likely due to missing `privileged: true` in the `SelfMutation` CodeBuild project:

https://github.com/aws/aws-cdk/blob/bf1c1c197bae895bba4ff5088b03d4e9b7d1692f/packages/%40aws-cdk/pipelines/lib/actions/update-pipeline-action.ts#L59-L76

### Reproduction Steps

```ts
const buildProject = new codebuild.PipelineProject(this, 'BuildProject', {
  buildSpec: codebuild.BuildSpec.fromSourceFilename('buildspec.yml'),
  environment: {
    buildImage: codebuild.LinuxBuildImage.fromAsset(this, 'BuildImage', {
      directory: path.join(__dirname, 'build-image'),
    }),
  },
});
const synthAction = new codepipeline_actions.CodeBuildAction({
  actionName: 'Build',
  project: buildProject,
  input: sourceArtifact,
  outputs: [cloudAssemblyArtifact],
});
```

### What did you expect to happen?

The `SelfMutate` action can invoke Docker to build the custom build image.

### What actually happened?

The `SelfMutate` action could not invoke Docker.

Error trace:

```
PipelineStack: deploying...
--
PipelineStack: deploying...
Assuming role 'arn:aws:iam::XXXXXXXXXXXX:role/cdk-hnb659fds-deploy-role-XXXXXXXXXXXX-eu-central-1'.
Waiting for stack CDKToolkit to finish creating or updating...
[0%] start: Publishing e8b2cd44815671370f30cd36ed6bf04788aadc936896ce7e63d94822c137c429:XXXXXXXXXXXX-eu-central-1
Retrieved account ID XXXXXXXXXXXX from disk cache
Assuming role 'arn:aws:iam::XXXXXXXXXXXX:role/cdk-hnb659fds-file-publishing-role-XXXXXXXXXXXX-eu-central-1'.
[0%] check: Check s3://cdk-hnb659fds-assets-XXXXXXXXXXXX-eu-central-1/e8b2cd44815671370f30cd36ed6bf04788aadc936896ce7e63d94822c137c429
[0%] upload: Upload s3://cdk-hnb659fds-assets-XXXXXXXXXXXX-eu-central-1/e8b2cd44815671370f30cd36ed6bf04788aadc936896ce7e63d94822c137c429
[50%] success: Published e8b2cd44815671370f30cd36ed6bf04788aadc936896ce7e63d94822c137c429:XXXXXXXXXXXX-eu-central-1
[50%] start: Publishing a67245d91d0552ef5f12da7797006b386702cfa0b2002a65f8435b728b249199:XXXXXXXXXXXX-eu-central-1
Retrieved account ID XXXXXXXXXXXX from disk cache
Assuming role 'arn:aws:iam::XXXXXXXXXXXX:role/cdk-hnb659fds-image-publishing-role-XXXXXXXXXXXX-eu-central-1'.
Retrieved account ID XXXXXXXXXXXX from disk cache
[50%] check: Check XXXXXXXXXXXX.dkr.ecr.eu-central-1.amazonaws.com/cdk-hnb659fds-container-assets-XXXXXXXXXXXX-eu-central-1:a67245d91d0552ef5f12da7797006b386702cfa0b2002a65f8435b728b249199
Call failed: describeImages({"repositoryName":"cdk-hnb659fds-container-assets-XXXXXXXXXXXX-eu-central-1","imageIds":[{"imageTag":"a67245d91d0552ef5f12da7797006b386702cfa0b2002a65f8435b728b249199"}]}) => The image with imageId {imageDigest:'null', imageTag:'a67245d91d0552ef5f12da7797006b386702cfa0b2002a65f8435b728b249199'} does not exist within the repository with name 'cdk-hnb659fds-container-assets-XXXXXXXXXXXX-eu-central-1' in the registry with id 'XXXXXXXXXXXX'
[50%] debug: docker login --username AWS --password-stdin https://XXXXXXXXXXXX.dkr.ecr.eu-central-1.amazonaws.com
[50%] debug: docker inspect cdkasset-a67245d91d0552ef5f12da7797006b386702cfa0b2002a65f8435b728b249199
[50%] build: Building Docker image at /codebuild/output/src189637107/src/asset.a67245d91d0552ef5f12da7797006b386702cfa0b2002a65f8435b728b249199
[50%] debug: docker build --tag cdkasset-a67245d91d0552ef5f12da7797006b386702cfa0b2002a65f8435b728b249199 .
Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
[100%] fail: docker build --tag cdkasset-a67245d91d0552ef5f12da7797006b386702cfa0b2002a65f8435b728b249199 . exited with error code 1: Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?

 ❌  PipelineStack failed: Error: Failed to publish one or more assets. See the error messages above for more information.
    at Object.publishAssets (/usr/local/lib/node_modules/aws-cdk/lib/util/asset-publishing.ts:25:11)
    at CloudFormationDeployments.publishStackAssets (/usr/local/lib/node_modules/aws-cdk/lib/api/cloudformation-deployments.ts:262:7)
    at CloudFormationDeployments.deployStack (/usr/local/lib/node_modules/aws-cdk/lib/api/cloudformation-deployments.ts:154:5)
    at CdkToolkit.deploy (/usr/local/lib/node_modules/aws-cdk/lib/cdk-toolkit.ts:180:24)
    at initCommandLine (/usr/local/lib/node_modules/aws-cdk/bin/cdk.ts:200:9)
Failed to publish one or more assets. See the error messages above for more information.
Error: Failed to publish one or more assets. See the error messages above for more information.
    at Object.publishAssets (/usr/local/lib/node_modules/aws-cdk/lib/util/asset-publishing.ts:25:11)
    at CloudFormationDeployments.publishStackAssets (/usr/local/lib/node_modules/aws-cdk/lib/api/cloudformation-deployments.ts:262:7)
    at CloudFormationDeployments.deployStack (/usr/local/lib/node_modules/aws-cdk/lib/api/cloudformation-deployments.ts:154:5)
    at CdkToolkit.deploy (/usr/local/lib/node_modules/aws-cdk/lib/cdk-toolkit.ts:180:24)
    at initCommandLine (/usr/local/lib/node_modules/aws-cdk/bin/cdk.ts:200:9)

[Container] 2020/11/11 16:06:30 Command did not exit successfully cdk -a . deploy PipelineStack --require-approval=never --verbose exit status 1
[Container] 2020/11/11 16:06:30 Phase complete: BUILD State: FAILED
[Container] 2020/11/11 16:06:30 Phase context status code: COMMAND_EXECUTION_ERROR Message: Error while executing command: cdk -a . deploy PipelineStack --require-approval=never --verbose. Reason: exit status 1
[Container] 2020/11/11 16:06:30 Entering phase POST_BUILD
```

### Environment

  - **CDK CLI Version  : 1.73**
  - **Framework Version: 1.73**

--- 

This is :bug: Bug Report

**Comment by rix0rrr** [comment]
Why does your `synth` action want to run Docker? Is it because you are using `aws-lambda-nodejs` ?

**Comment by rix0rrr** [comment]
We did not allow this on purpose, as we don't want jobs running arbitrary Docker commands on purpose.

**Comment by asterikx** [comment]
Well, my pipeline uses a custom build image in the `Build` stage (using `codebuild.LinuxBuildImage.fromAsset`, which uses `DockerImageAsset` from [`aws-ecr-assets`](https://docs.aws.amazon.com/cdk/api/latest/docs/aws-ecr-assets-readme.html) under the hood).

During the `SelfMutate ` action, the CDK will synth the pipeline stack. Since the `PipelineStack` contains a `DockerImageAsset`, the CDK will build and upload the Docker image to ECR.

**Comment by asterikx** [comment]
I'm not using `aws-lambda-nodejs` btw.

I can work around this issue by deploying the pipeline stack manually using the CLI whenever changes were made to the Dockerfile. Asset fingerprinting will prevent building the image in the `SelfMutate` action when nothing changed.

**Comment by rix0rrr** [comment]
It is true that this requires a `privilegedMode` flag on the SelfMutate action. Feels a little dangerous/unnecessary to enable this by default. It will have to become a parameter.

**Comment by mrpackethead** [comment]
@rix0rrr ...  Aggree that it is not somethign you'd turn on by default.    Just like you may need to turn on privildged mode in the build stage..  Optional is the right way to do this.

In my case, i'm bundling lambdas with my own lambda bundler  ( this is so, we can use our own priviate pypi repo, and also not use docker images from docker hub, which gets our security people excited ).   I'm also creating a couple fo docker images, that form part of my pipeline..     This is so i can do an integration with non support repos. ( in my case Azure Devops ).

I would suggest that instead of just a parameter to run in privlidged mode, that you allow to you optionally set any environment value..  In my case not only did i want to set privildiged mode, i also wanted to change the build container size.

My workaround was to breakout the escape hatches.

```
 # Create the Pipeline
        self.pipeline = pipelines.CdkPipeline(self, project_name + 'cdkPipeline',
            cloud_assembly_artifact = cloud_assembly_artifact,
            pipeline_name = f'{project_name}pipeline',
            source_action = pipeline_source_action,
            synth_action = synth_action,
            self_mutating = pipeline_cfg['Pipeline']['SelfMutate']
        )

        #Breakout the escape hatches, and make the self mutating codebuild run privilidged
        if pipeline_cfg['Pipeline']['SelfMutate'] == True:

            compute_type = {
                'SMALL': 'BUILD_GENERAL1_SMALL',
                'MEDIUM': 'BUILD_GENERAL1_MEDIUM',
                'LARGE': 'BUILD_GENERAL1_LARGE',
                'X2_LARGE': 'BUILD_GENERAL1_2XLARGE'
            }

            mutating_codebuild = self.pipeline.node.find_child(id ='UpdatePipeline')
            codebuild_project = mutating_codebuild.node.find_child(id ='SelfMutation')
            raw_code_build = codebuild_project.node.default_child    
            raw_code_build.add_override("Properties.Environment.PrivilegedMode", "True")
            raw_code_build.add_override("Properties.Environment.ComputeType", compute_type[pipeline_synth_cfg['Environment']['ComputeType']])
 ```
