### ISSUE TITLE
[lambda] confusing error message when env var is None

### ISSUE THREAD

**Issue by alex9311** [aws/aws-cdk#11456]
I accidentally had a lambda env variable set to None and the error that came back was really hard to understand. It took me a while to figure out my environment was the problem

### Reproduction Steps

```python
#!/usr/bin/env python3

from aws_cdk import (core, aws_ec2, aws_lambda)

env = {"account": "569661598120", "region": "us-west-2"}
app = core.App()

my_stack = core.Stack(app, "my-stack", env=env)

my_lambda = aws_lambda.Function(
        my_stack,
        "my_lamda",
        function_name="my_lambda",
        runtime=aws_lambda.Runtime.PYTHON_3_8,
        code=aws_lambda.Code.asset("./"),
        handler='foo.handler',
        environment={"MY_ENV_VAR": None},
    )

```

### What did you expect to happen?

A meaningful error saying an environment field was set to `None`

### What actually happened?
go the error:
```
jsii.errors.JavaScriptError: 
  Error: Got 'undefined' for non-optional instance of {"type":{"primitive":"string"}}
      at nullAndOk (/home/alex/git/test/cdk-repro/.env/lib/python3.8/site-packages/jsii/_embedded/jsii/jsii-runtime.js:7204:15)
      at Object.deserialize (/home/alex/git/test/cdk-repro/.env/lib/python3.8/site-packages/jsii/_embedded/jsii/jsii-runtime.js:6729:17)
      at Kernel._toSandbox (/home/alex/git/test/cdk-repro/.env/lib/python3.8/site-packages/jsii/_embedded/jsii/jsii-runtime.js:8328:61)
      at /home/alex/git/test/cdk-repro/.env/lib/python3.8/site-packages/jsii/_embedded/jsii/jsii-runtime.js:6874:74
      at mapValues (/home/alex/git/test/cdk-repro/.env/lib/python3.8/site-packages/jsii/_embedded/jsii/jsii-runtime.js:7231:27)
      at Object.deserialize (/home/alex/git/test/cdk-repro/.env/lib/python3.8/site-packages/jsii/_embedded/jsii/jsii-runtime.js:6874:28)
      at Kernel._toSandbox (/home/alex/git/test/cdk-repro/.env/lib/python3.8/site-packages/jsii/_embedded/jsii/jsii-runtime.js:8328:61)
      at /home/alex/git/test/cdk-repro/.env/lib/python3.8/site-packages/jsii/_embedded/jsii/jsii-runtime.js:6959:29
      at mapValues (/home/alex/git/test/cdk-repro/.env/lib/python3.8/site-packages/jsii/_embedded/jsii/jsii-runtime.js:7231:27)
      at Kernel._wrapSandboxCode (/home/alex/git/test/cdk-repro/.env/lib/python3.8/site-packages/jsii/_embedded/jsii/jsii-runtime.js:8422:19)
      at Kernel._create (/home/alex/git/test/cdk-repro/.env/lib/python3.8/site-packages/jsii/_embedded/jsii/jsii-runtime.js:7934:26)
      at Kernel.create (/home/alex/git/test/cdk-repro/.env/lib/python3.8/site-packages/jsii/_embedded/jsii/jsii-runtime.js:7678:21)
      at KernelHost.processRequest (/home/alex/git/test/cdk-repro/.env/lib/python3.8/site-packages/jsii/_embedded/jsii/jsii-runtime.js:7458:28)
      at KernelHost.run (/home/alex/git/test/cdk-repro/.env/lib/python3.8/site-packages/jsii/_embedded/jsii/jsii-runtime.js:7396:14)
      at Immediate._onImmediate (/home/alex/git/test/cdk-repro/.env/lib/python3.8/site-packages/jsii/_embedded/jsii/jsii-runtime.js:7399:37)
      at processImmediate (node:internal/timers:462:21)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "app.py", line 10, in <module>
    my_lambda = aws_lambda.Function(
  File "/home/alex/git/test/cdk-repro/.env/lib/python3.8/site-packages/jsii/_runtime.py", line 69, in __call__
    inst = super().__call__(*args, **kwargs)
  File "/home/alex/git/test/cdk-repro/.env/lib/python3.8/site-packages/aws_cdk/aws_lambda/__init__.py", line 12552, in __init__
    jsii.create(Function, self, [scope, id, props])
  File "/home/alex/git/test/cdk-repro/.env/lib/python3.8/site-packages/jsii/_kernel/__init__.py", line 250, in create
    response = self.provider.create(
  File "/home/alex/git/test/cdk-repro/.env/lib/python3.8/site-packages/jsii/_kernel/providers/process.py", line 336, in create
    return self._process.send(request, CreateResponse)
  File "/home/alex/git/test/cdk-repro/.env/lib/python3.8/site-packages/jsii/_kernel/providers/process.py", line 321, in send
    raise JSIIError(resp.error) from JavaScriptError(resp.stack)
jsii.errors.JSIIError: Got 'undefined' for non-optional instance of {"type":{"primitive":"string"}}

```

### Environment

  - **CDK CLI Version  :** 1.71.0 
  - **Framework Version:** 1.71.0 
  - **Node.js Version:** v15.1.0
  - **OS               :** ubuntu 18.04
  - **Language (Version):** python 3.8.6

--- 

This is :bug: Bug Report

**Comment by alex9311** [comment]
if someone can point me to where this error might be caught gracefully I'd be happy to do the PR

**Comment by nija-at** [comment]
We have an issue to track supporting `undefined` (or `None` in Python) - https://github.com/aws/aws-cdk/issues/4085

Usually validations would go into [`function.ts`](https://github.com/aws/aws-cdk/blob/master/packages/%40aws-cdk/aws-lambda/lib/function.ts).
 However, in this case, we already have this enforced via [type checks](https://github.com/aws/aws-cdk/blob/989d15f654bcf1ca5c4d2cc2e1b38a5513105e49/packages/%40aws-cdk/aws-lambda/lib/function.ts#L69). With Python, we're unable to enforce any of these type checks.
