### ISSUE TITLE
[aws-stepfunctions-tasks] SagemakeCreateEndpointConfig cannot accept JsonPath.numberAt() for initialInstanceCount

### ISSUE THREAD

**Issue by ntroutman** [aws/aws-cdk#11597]
You cannot define and compile a SFN Task for SageMakerCreateEndpointConfig that uses sfn.JsonPath.numberAt() for defining the initialInstanceCount of a Production Variant. It throws an error saying instance count must be at least 1 due to the number being returned by numberAt being < 0 (When dumping the construct the value looks like `      initialInstanceCount: -1.8881545897088593e+289`

### Reproduction Steps

```typescript
new sfn.StateMachine(this, 'SageMakerEndpointDeploymentWorkflow', {
            definition: 
                new tasks.SageMakerCreateEndpointConfig(this, 'SagemakerEndpointConfig', {
                    endpointConfigName: sfn.JsonPath.stringAt("$.model.name"),
                    productionVariants: [{
                        initialInstanceCount: sfn.JsonPath.numberAt("$.sm_endpoint_config.instance_count"),
                        instanceType: ec2.InstanceType.of(ec2.InstanceClass.M5, ec2.InstanceSize.XLARGE),
                        modelName: sfn.JsonPath.stringAt("$.model.name"),
                        variantName: sfn.JsonPath.stringAt("$.model.name"),
                    }],
                    resultPath: "$.sm_endpoint_config"
                })
                .next(new sfn.Succeed(this, "Endpoint Deployted")),
            timeout: cdk.Duration.minutes(60),
        })
```

### What did you expect to happen?

That the workflow would compile correctly and could be deployed.

### What actually happened?

```
XXXXX/node_modules/monocdk/lib/aws-stepfunctions-tasks/lib/sagemaker/create-endpoint-config.js:80
                throw new Error('Must define at least one instance');
                ^

Error: Must define at least one instance
    at XXXXX/node_modules/monocdk/lib/aws-stepfunctions-tasks/lib/sagemaker/create-endpoint-config.js:80:23
    at Array.forEach (<anonymous>)
    at SageMakerCreateEndpointConfig.validateProductionVariants (XXXXX/node_modules/monocdk/lib/aws-stepfunctions-tasks/lib/sagemaker/create-endpoint-config.js:78:39)
    at new SageMakerCreateEndpointConfig (XXXXX/node_modules/monocdk/lib/aws-stepfunctions-tasks/lib/sagemaker/create-endpoint-config.js:23:14)
    at new SageMakerCreateEndpointConfig (XXXXX/dist/lib/sagemakerTasks.js:22:9)
    at SageMakerEndpointDeploymentWorkflow.createEndpointConfig (XXXXX/dist/lib/sagemakerEndpointDeploymentStepFunction.js:36:16)
    at new SageMakerEndpointDeploymentWorkflow (XXXXX/dist/lib/sagemakerEndpointDeploymentStepFunction.js:14:24)
    at new LaunchOrchestratorStack (XXXXX/dist/lib/launchOrchestratorStack.js:42:53)
    at Object.<anonymous> (XXXXX/dist/lib/app.js:45:23)
```

### Environment

  - **CDK CLI Version  :** 1.72.0
  - **Framework Version:**  @amzn/cdk-build/2.0.0  
  - **Node.js Version:** node-v12.19.0
  - **OS               :** linux-x64 (AL2012)
  - **Language (Version):** TypeScript

### Other

The issue is that `validateProductionVariants` checks if the initialInstanceCount < 1 without making a check to see if the number is actually an encoded token for JsonPath expansion.

**create-endpoint-config.js**
```typescript
    validateProductionVariants() {
        if (this.props.productionVariants.length < 1 || this.props.productionVariants.length > 10) {
            throw new Error('Must specify from 1 to 10 production variants per endpoint configuration');
        }
        this.props.productionVariants.forEach((variant) => {
            if (variant.initialInstanceCount && variant.initialInstanceCount < 1)
                throw new Error('Must define at least one instance');
            if (variant.initialVariantWeight && variant.initialVariantWeight <= 0) {
                throw new Error('InitialVariantWeight has minimum value of 0');
            }
        });
    }
```

--- 

This is :bug: Bug Report

**Comment by ryparker** [comment]
Hey @ntroutman 👋🏻 

Thank you for submitting this bug report! Would you mind providing more information on how you're setting the value for `$.sm_endpoint_config.instance_count` in your `sfn.JsonPath`? To better prioritize this issue we'd like to confirm how that value is being set before assuming this is a bug.

**Comment by peterwoodworth** [comment]
Closing this issue due to staleness - Ping us if you have additional concerns!
