### ISSUE TITLE
[codebuild] cdk synth returns an error when codebuild.Project has cache property

### ISSUE THREAD

**Issue by datariomj** [aws/aws-cdk#11616]
Cache property doesn't work. Even when using codebuild.Cache.none().
Running cdk synth returns an error: "Trying to resolve a non-data object. Only token are supported for lazy evaluation. Path: ${pathName}. Object: ${obj}"

### Reproduction Steps

**cache-error.ts**
```typescript
import { Construct, Stack, StackProps } from '@aws-cdk/core';
import * as codebuild from '@aws-cdk/aws-codebuild';
import { Bucket } from '@aws-cdk/aws-s3';

export class CacheErrorStack extends Stack {
  constructor(scope: Construct, id: string, props?: StackProps) {
    super(scope, id, props);

    // came from https://docs.aws.amazon.com/cdk/api/latest/docs/aws-codebuild-readme.html#s3-caching
    new codebuild.Project(this, 'Project', {
      source: codebuild.Source.bitBucket({
        owner: 'awslabs',
        repo: 'aws-cdk',
      }),
      cache: codebuild.Cache.bucket(new Bucket(this, 'Bucket'))
    });
  }
}
```

### What did you expect to happen?
cdk synth should be successful

### What actually happened?
cdk synth returns an error: "Trying to resolve a non-data object. Only token are supported for lazy evaluation. Path: ${pathName}. Object: ${obj}"

### Environment
  - **CDK CLI Version : 1.74.0**
  - **Framework Version: 1.74.0**
  - **Node.js Version: v12.16.2**
  - **OS               : Windows 10**
  - **Language (Version): TypeScript (3.9.7)**

### Other
**Error Log:**
```
D:\infra\node_modules\@aws-cdk\core\lib\private\resolve.ts:85
    throw new Error(`Trying to resolve a non-data object. Only token are supported for lazy evaluation. Path: ${pathName}. Object: ${obj}`);
          ^
Error: Resolution error: Resolution error: Resolution error: Resolution error: Trying to resolve a non-data object. Only token are supported for lazy evaluation. Path: /cache/_toCloudFormation. Object: () => ({
                type: 'S3',
                location: core_1.Fn.join('/', [bucket.bucketName, options && options.prefix || core_1.Aws.NO_VALUE]),
            }).
Object creation stack:
  at Execute again with CDK_DEBUG=true to capture stack traces.
Object creation stack:
  at Execute again with CDK_DEBUG=true to capture stack traces..
    at resolve (D:\infra\node_modules\@aws-cdk\core\lib\private\resolve.ts:85:11)
    at Object.resolve (D:\infra\node_modules\@aws-cdk\core\lib\private\resolve.ts:53:32)
    at resolve (D:\infra\node_modules\@aws-cdk\core\lib\private\resolve.ts:159:39)
    at Object.resolve (D:\infra\node_modules\@aws-cdk\core\lib\private\resolve.ts:53:32)
    at Object.resolve (D:\infra\node_modules\@aws-cdk\core\lib\private\resolve.ts:159:39)
    at Object.produce (D:\infra\node_modules\@aws-cdk\core\lib\private\cloudformation-lang.ts:70:24)
    at LazyString.resolve (D:\infra\node_modules\@aws-cdk\core\lib\lazy.ts:159:26)
    at RememberingTokenResolver.resolveToken (D:\infra\node_modules\@aws-cdk\core\lib\resolvable.ts:135:24)
    at RememberingTokenResolver.resolveToken (D:\infra\node_modules\@aws-cdk\core\lib\private\resolve.ts:191:18)
    at resolve (D:\infra\node_modules\@aws-cdk\core\lib\private\resolve.ts:137:29)
```
--- 

This is :bug: Bug Report

**Comment by skinny85** [comment]
Hello @datariomj ,

thanks for opening the issue, but I was not able to reproduce your problem. I tried with version `1.74.0`, and I'm able to synthesize the application without issues. Here's a GitHub repository with my code: https://github.com/skinny85/cdk-codebuild-cache-problem , let me know if it doesn't work for you.

Thanks,
Adam

**Comment by datariomj** [comment]
Yeah. It's working now and I can't replicate the issue anymore. Closing this issue. Thank you.
