### ISSUE TITLE
[ec2] ec2.ClientVpnEndpoint.ConnectionLogOptions not definable from C#

### ISSUE THREAD

**Issue by chillitom** [aws/aws-cdk#11649]
The following code fails with the message
```
Unhandled exception. Amazon.JSII.Runtime.JsiiException: Missing required properties for @aws-cdk/aws-ec2.CfnClientVpnEndpointProps: connectionLogOptions
   at Amazon.JSII.Runtime.Services.Client.TryDeserialize[TResponse](String responseJson)
   at Amazon.JSII.Runtime.Services.Client.ReceiveResponse[TResponse]()
```

```csharp
using System.Collections.Generic;
using System.Linq;
using Amazon.CDK;
using Amazon.CDK.AWS.CertificateManager;
using Amazon.CDK.AWS.EC2;
using Amazon.CDK.AWS.Logs;

namespace BrokenStack {
    public class VpnStack : Stack {

        public Vpc Vpc { get; }
        public CfnClientVpnEndpoint Vpn { get; set; }

        public VpnStack(Construct parent, string id, IStackProps props) : base(parent, id, props) {
            Vpc = new Vpc(this, "Vpc", new VpcProps {
                Cidr = "10.1.0.0/16",
                EnableDnsHostnames = true,
                EnableDnsSupport = true
            });

            var serverCert =
                Certificate.FromCertificateArn(this, "ServerCertificate",
                    "arn:aws:acm:eu-west-2:12344:certificate/12345678-78ed-42de-912b-b57267d62584");

            var logGroup = new LogGroup(this, "ClientVpnLogGroup", new LogGroupProps {
                Retention = RetentionDays.ONE_MONTH
            });

            var logStream = logGroup.AddStream("ClientVpnLogStream");

            Vpn = new CfnClientVpnEndpoint(this, "ClientVpn", new CfnClientVpnEndpointProps {

                ClientCidrBlock = "10.2.0.0/16",

                // https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-ec2-clientvpnendpoint-clientauthenticationrequest.html
                AuthenticationOptions = new [] {
                    new Dictionary<string, object> {
                        ["Type"] = "federated-authentication",
                        ["FederatedAuthentication"] = new Dictionary<string, string> {
                            // https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-ec2-clientvpnendpoint-federatedauthenticationrequest.html
                            ["SAMLProviderArn"] = "arn:aws:iam::12345:saml-provider/Okta-ClientVPN"
                        }
                    }
                },

                ServerCertificateArn = serverCert.CertificateArn,

                // https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-ec2-clientvpnendpoint-connectionlogoptions.html
                ConnectionLogOptions = new Dictionary<string, object> {
                    ["CloudwatchLogGroup"] = logGroup.LogGroupName,
                    ["CloudwatchLogStream"] = logStream.LogStreamName,
                    ["Enabled"] = false
                },

                // only traffic bound for our 
                SplitTunnel = true,

                // https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-ec2-clientvpnendpoint-tagspecification.html
                TagSpecifications = new[] {
                    new {
                        ResourceType = "client-vpn-endpoint",
                        Tags = new [] {
                            new { Key = "Name", Value = "Client VPN" }
                        }
                    }
                }
            });

            var dependable = new ConcreteDependable();

            var assocs = Vpc.PrivateSubnets.Select((psn, i) =>
                  new CfnClientVpnTargetNetworkAssociation(
                      this,
                      "ClientVpnNetworkAssociation-" + i,
                      new CfnClientVpnTargetNetworkAssociationProps {
                          ClientVpnEndpointId = Vpn.Ref,
                          SubnetId = psn.SubnetId
                      })).ToList();

            assocs.ForEach(assoc => dependable.Add(assoc));

            new CfnClientVpnAuthorizationRule(this, "VpnAuthRule", new CfnClientVpnAuthorizationRuleProps {
                ClientVpnEndpointId = Vpn.Ref,
                TargetNetworkCidr = "0.0.0.0/0",
                AuthorizeAllGroups = true,
                Description = "Allow All"
            });
        }
    }
}
```
No matter how I try to specify `ConnectionLogOptions` I always get the same error message, I transcribed this into Typescript and it ran with no problems and the synthesized CF looked good.

  - **CDK CLI Version  :** 1.74.0
  - **Framework Version:** 1.74.0
  - **Node.js Version:** 14.15.1
  - **OS               :** Windows
  - **Language (Version):** C# 9, dotnet 5.

--- 

This is :bug: Bug Report

**Comment by NGL321** [comment]
Unclear why the `bug` label was removed. Please adjust if I am incorrect in re-adding it
