### ISSUE TITLE
[aws-eks] Failed to create Cluster / FargateCluster in HK region (ap-east-1)

### ISSUE THREAD

**Issue by limouren** [aws/aws-cdk#11644]
Failed to create a Cluster / FargateCluster with minimal setup of a single VPC and a single FargateCluster in `ap-east-1`. The creation is successfully in another region with everything else being the same (the region I have tried is `us-east-2`).

### Reproduction Steps

```python
from aws_cdk import (
    core,
    aws_ec2 as ec2,
    aws_eks as eks,
)

class MyStack(core.Stack):
    def __init__(self, scope: core.Construct, construct_id: str, **kwargs) -> None:
        super().__init__(scope, construct_id, **kwargs)

        vpc = ec2.Vpc(
            self,
            "VPC",
            cidr="10.0.0.0/16",
            nat_gateways=1,
            max_azs=3,
        )

        cluster = eks.FargateCluster(
            self,
            "EKS",
            version=eks.KubernetesVersion.V1_18,
            cluster_name="CLUSTER_NAME",
            vpc=vpc,
        )
```

Replacing FargateCluster with Cluster would fail with the same reason.

### What did you expect to happen?

EKS cluster on fargate created successfully.

### What actually happened?

The following error is observed in cmdline:

```
02:07:41 | CREATE_FAILED        | Custom::AWSCDK-EKS-Cluster            | EKS/Resource/Resource/Default
Failed to create resource. The security token included in the request is invalid

Logs: /aws/lambda/MYAPP-dev-debug-awscdkawse-OnEventHandler42BEBAE0-ZYDZ6DUZUQU7

at Object.extractError (/var/runtime/node_modules/aws-sdk/lib/protocol/json.js:52:27)
at Request.extractError (/var/runtime/node_modules/aws-sdk/lib/protocol/rest_json.js:55:8)
at Request.callListeners (/var/runtime/node_modules/aws-sdk/lib/sequential_executor.js:106:20)
at Request.emit (/var/runtime/node_modules/aws-sdk/lib/sequential_executor.js:78:10)
at Request.emit (/var/runtime/node_modules/aws-sdk/lib/request.js:688:14)
at Request.transition (/var/runtime/node_modules/aws-sdk/lib/request.js:22:10)
at AcceptorStateMachine.runTo (/var/runtime/node_modules/aws-sdk/lib/state_machine.js:14:12)
at /var/runtime/node_modules/aws-sdk/lib/state_machine.js:26:10
at Request.<anonymous> (/var/runtime/node_modules/aws-sdk/lib/request.js:38:9)
at Request.<anonymous> (/var/runtime/node_modules/aws-sdk/lib/request.js:
02:07:41 | ROLLBACK_IN_PROGRESS | AWS::CloudFormation::Stack            | MYAPP-dev-debug
The following resource(s) failed to create: [EKSE2753513]. Rollback requested by user.















 ❌  MYAPP-dev-debug failed: Error: The stack named MYAPP-dev-debug failed creation, it may need to be manually deleted from the AWS console: ROLLBACK_COMPLETE
    at Object.waitForStackDeploy (/Users/limouren/.config/yarn/global/node_modules/aws-cdk/lib/api/util/cloudformation.ts:305:11)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at Object.deployStack (/Users/limouren/.config/yarn/global/node_modules/aws-cdk/lib/api/deploy-stack.ts:283:26)
    at CdkToolkit.deploy (/Users/limouren/.config/yarn/global/node_modules/aws-cdk/lib/cdk-toolkit.ts:180:24)
    at initCommandLine (/Users/limouren/.config/yarn/global/node_modules/aws-cdk/bin/cdk.ts:200:9)
The stack named MYAPP-dev-debug failed creation, it may need to be manually deleted from the AWS console: ROLLBACK_COMPLETE
```

Here is the content of the related cloudwatch log group:

```
START RequestId: 26673b37-4372-44ae-b3bd-3bbde8a657a4 Version: $LATEST
2020-11-23T18:07:38.262Z	26673b37-4372-44ae-b3bd-3bbde8a657a4	INFO	
{
    "assumeRole": {
        "RoleArn": "arn:aws:iam::096934248855:role/MYAPP-dev-debug-EKSCreationRole6166D41F-BHCOL5ZYYMEJ",
        "RoleSessionName": "AWSCDK.EKSCluster.Create.23edf944-38c6-426a-ac8a-b220d2e1eae2"
    }
}

2020-11-23T18:07:38.379Z	26673b37-4372-44ae-b3bd-3bbde8a657a4	INFO	onCreate: creating cluster with options: 
{
    "resourcesVpcConfig": {
        "endpointPrivateAccess": true,
        "securityGroupIds": [
            "sg-0fd572ebefe6fe59e"
        ],
        "endpointPublicAccess": true,
        "subnetIds": [
            "subnet-0c53a7012988fd345",
            "subnet-09450e18b30836d8a",
            "subnet-09f03b0686c1a971f",
            "subnet-0904e5e57ba47b2e6",
            "subnet-08d8bb24b15aef14d",
            "subnet-0f621098a48f89a60"
        ]
    },
    "roleArn": "arn:aws:iam::096934248855:role/MYAPP-dev-debug-EKSRoleE1D5681C-1K05L6J1EEYNK",
    "name": "MYAPP-eks-dev-debug",
    "version": "1.18"
}

2020-11-23T18:07:39.981Z	26673b37-4372-44ae-b3bd-3bbde8a657a4	INFO	[AWS sts 200 1.598s 0 retries] assumeRole({
  RoleArn: 'arn:aws:iam::096934248855:role/MYAPP-dev-debug-EKSCreationRole6166D41F-BHCOL5ZYYMEJ',
  RoleSessionName: 'AWSCDK.EKSCluster.Create.23edf944-38c6-426a-ac8a-b220d2e1eae2'
})
2020-11-23T18:07:40.238Z	26673b37-4372-44ae-b3bd-3bbde8a657a4	INFO	[AWS eks 403 1.83s 0 retries] createCluster({
  resourcesVpcConfig: {
    endpointPrivateAccess: true,
    securityGroupIds: [ 'sg-0fd572ebefe6fe59e', [length]: 1 ],
    endpointPublicAccess: true,
    subnetIds: [
      'subnet-0c53a7012988fd345',
      'subnet-09450e18b30836d8a',
      'subnet-09f03b0686c1a971f',
      'subnet-0904e5e57ba47b2e6',
      'subnet-08d8bb24b15aef14d',
      'subnet-0f621098a48f89a60',
      [length]: 6
    ]
  },
  roleArn: 'arn:aws:iam::096934248855:role/MYAPP-dev-debug-EKSRoleE1D5681C-1K05L6J1EEYNK',
  name: 'MYAPP-eks-dev-debug',
  version: '1.18',
  clientRequestToken: 'c9c225eb-75d8-4685-9039-176061570466'
})
2020-11-23T18:07:40.239Z	26673b37-4372-44ae-b3bd-3bbde8a657a4	ERROR	Invoke Error 	
{
    "errorType": "UnrecognizedClientException",
    "errorMessage": "The security token included in the request is invalid",
    "code": "UnrecognizedClientException",
    "message": "The security token included in the request is invalid",
    "time": "2020-11-23T18:07:40.208Z",
    "requestId": "acd403d3-e5bc-48d9-af55-417e74806d34",
    "statusCode": 403,
    "retryable": false,
    "retryDelay": 22.448417950703337,
    "stack": [
        "UnrecognizedClientException: The security token included in the request is invalid",
        "    at Object.extractError (/var/runtime/node_modules/aws-sdk/lib/protocol/json.js:52:27)",
        "    at Request.extractError (/var/runtime/node_modules/aws-sdk/lib/protocol/rest_json.js:55:8)",
        "    at Request.callListeners (/var/runtime/node_modules/aws-sdk/lib/sequential_executor.js:106:20)",
        "    at Request.emit (/var/runtime/node_modules/aws-sdk/lib/sequential_executor.js:78:10)",
        "    at Request.emit (/var/runtime/node_modules/aws-sdk/lib/request.js:688:14)",
        "    at Request.transition (/var/runtime/node_modules/aws-sdk/lib/request.js:22:10)",
        "    at AcceptorStateMachine.runTo (/var/runtime/node_modules/aws-sdk/lib/state_machine.js:14:12)",
        "    at /var/runtime/node_modules/aws-sdk/lib/state_machine.js:26:10",
        "    at Request.<anonymous> (/var/runtime/node_modules/aws-sdk/lib/request.js:38:9)",
        "    at Request.<anonymous> (/var/runtime/node_modules/aws-sdk/lib/request.js:690:12)"
    ]
}

END RequestId: 26673b37-4372-44ae-b3bd-3bbde8a657a4
REPORT RequestId: 26673b37-4372-44ae-b3bd-3bbde8a657a4	Duration: 2018.85 ms	Billed Duration: 2100 ms	Memory Size: 128 MB	Max Memory Used: 87 MB	Init Duration: 390.54 ms	
```

### Environment

  - **CDK CLI Version  :** aws-cli/2.1.1 Python/3.9.0 Darwin/19.6.0 source/x86_64
  - **Framework Version:** 1.74.0 (build e86602f)
  - **Node.js Version:** v12.18.4
  - **OS               :** macOS 10.15.7
  - **Language (Version):** Python 3.7.5

### Other

1. The profile is valid as `cdk deploy` can be run successfully by commenting the Cluster construct, which would create a VPC successfully.
2. The user has `AdministratorAccess` to the account.

--- 

This is :bug: Bug Report

**Comment by iliapolo** [comment]
@limouren Is this still relevant?
