### ISSUE TITLE
[@aws-cdk/aws-lambda-python]  Azure DevOps - unable to prepare context

### ISSUE THREAD

**Issue by wojtii** [aws/aws-cdk#11671]
Hi, I have a project with a python3.8 lambda and Pipfile (I have also tried `requirements.txt`). When I try to deploy it in the Azure DevOps pipeline with command `cdk deploy --require-approval=never` I get error:
```
unable to prepare context: the Dockerfile (.../node_modules/@aws-cdk/aws-lambda-python/lib/Dockerfile.dependencies) must be within the build context
```
From the other project I know that it works in similar environment with `requirements.txt` in the `1.63` version. I have also verified that if I revert cdk in this project to `1.63` and remove `Pipfile` it is also working. Deployment from my own machine works in all cases. I have temporary reverted to `1.63` and use `pipenv lock` to be able to deploy this project.

### Reproduction Steps
cdk file:
```ts
import { PythonFunction } from "@aws-cdk/aws-lambda-python";
import * as cdk from "@aws-cdk/core";
export class Stack extends cdk.Stack {
  constructor(scope: cdk.Construct, id: string, props: cdk.StackProps) {
    super(scope, id, props);
    new PythonFunction(this, "SomeFunction", {
      handler: "handler",
      entry: "./src",
      index: "handler.py",
      runtime: Runtime.PYTHON_3_8,
      // ...
    });
  }
}
```
and src contains `handler.py` with `handler` and `Pipfile` with dependencies.

### What did you expect to happen?
Correct deployment of the lambda in the pipeline like on my machine.

### What actually happened?
Error:
```
unable to prepare context: the Dockerfile (.../node_modules/@aws-cdk/aws-lambda-python/lib/Dockerfile.dependencies) must be within the build context
```

### Environment

  - **CDK CLI Version  :** 1.74.0
  - **Framework Version:** 1.74.0
  - **Node.js Version:** 12
  - **OS               :** ubuntu-latest (vmImage)
  - **Language (Version):** Python 3.8

### Other

From what I have seen the file `Dockerfile.dependencies` is not present in the working `1.63` version.

--- 

This is :bug: Bug Report

**Comment by otakusid** [comment]
I have a similar issue when trying to use PythonFunction

```
(.venv) λ cdk synth
jsii.errors.JavaScriptError:
  Error: [Status 1] stdout:


  stderr: unable to prepare context: unable to get relative Dockerfile path: Rel: can't make C:\Users\admin\AppData\Local\Temp\jsii-kernel-nsmKW5\node_modules\@aws-cdk\aws-lambda-python\lib\Dockerfile.dependencies relative to D:\_work\infrastructure.cis-monitoring-consumer\src
      at dockerExec (C:\Users\admin\AppData\Local\Temp\jsii-kernel-nsmKW5\node_modules\@aws-cdk\core\lib\bundling.js:144:19)
      at Function.fromAsset (C:\Users\admin\AppData\Local\Temp\jsii-kernel-nsmKW5\node_modules\@aws-cdk\core\lib\bundling.js:41:24)
      at Object.bundle (C:\Users\admin\AppData\Local\Temp\jsii-kernel-nsmKW5\node_modules\@aws-cdk\aws-lambda-python\lib\bundling.js:33:43)
      at new PythonFunction (C:\Users\admin\AppData\Local\Temp\jsii-kernel-nsmKW5\node_modules\@aws-cdk\aws-lambda-python\lib\function.js:37:30)
      at d:\_work\infrastructure.cis-monitoring-consumer\.venv\lib\site-packages\jsii\_embedded\jsii\jsii-runtime.js:3556:49
      at Kernel._wrapSandboxCode (d:\_work\infrastructure.cis-monitoring-consumer\.venv\lib\site-packages\jsii\_embedded\jsii\jsii-runtime.js:4040:16)
      at Kernel._create (d:\_work\infrastructure.cis-monitoring-consumer\.venv\lib\site-packages\jsii\_embedded\jsii\jsii-runtime.js:3556:26)
      at Kernel.create (d:\_work\infrastructure.cis-monitoring-consumer\.venv\lib\site-packages\jsii\_embedded\jsii\jsii-runtime.js:3300:21)
      at KernelHost.processRequest (d:\_work\infrastructure.cis-monitoring-consumer\.venv\lib\site-packages\jsii\_embedded\jsii\jsii-runtime.js:13119:28)
      at KernelHost.run (d:\_work\infrastructure.cis-monitoring-consumer\.venv\lib\site-packages\jsii\_embedded\jsii\jsii-runtime.js:13057:14)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "app.py", line 10, in <module>
    stack = MonitoringConsumer(app, 'cis-monitoring-consumer')
  File "c:\_work\infrastructure.cis-monitoring-consumer\.venv\lib\site-packages\jsii\_runtime.py", line 69, in __call__
    inst = super().__call__(*args, **kwargs)
  File "c:\_work\infrastructure.cis-monitoring-consumer\infrastructure\monitoring_consumer.py", line 116, in __init__
    'SLACK_WEBHOOK_URL': slack_channel.value_as_string
  File "c:\_work\infrastructure.cis-monitoring-consumer\.venv\lib\site-packages\jsii\_runtime.py", line 69, in __call__
    inst = super().__call__(*args, **kwargs)
  File "c:\_work\infrastructure.cis-monitoring-consumer\.venv\lib\site-packages\aws_cdk\aws_lambda_python\__init__.py", line 239, in __init__
    jsii.create(PythonFunction, self, [scope, id, props])
  File "c:\_work\infrastructure.cis-monitoring-consumer\.venv\lib\site-packages\jsii\_kernel\__init__.py", line 257, in create
    for iface in getattr(klass, "__jsii_ifaces__", [])
  File "c:\_work\infrastructure.cis-monitoring-consumer\.venv\lib\site-packages\jsii\_kernel\providers\process.py", line 347, in create
    return self._process.send(request, CreateResponse)
  File "c:\_work\infrastructure.cis-monitoring-consumer\.venv\lib\site-packages\jsii\_kernel\providers\process.py", line 332, in send
    raise JSIIError(resp.error) from JavaScriptError(resp.stack)
jsii.errors.JSIIError: [Status 1] stdout:


stderr: unable to prepare context: unable to get relative Dockerfile path: Rel: can't make C:\Users\admin\AppData\Local\Temp\jsii-kernel-nsmKW5\node_modules\@aws-cdk\aws-lambda-python\lib\Dockerfile.dependencies relative to D:\_work\infrastructure.cis-monitoring-consumer\src
Subprocess exited with error 1
```

## Environment

- CDK CLI Version : 1.77.0
- Framework Version: 1.77.0
- Node.js Version: 15.3.0
- OS : Windows 10
- Language (Version): Python 3.7.4

**Comment by daterr** [comment]
I ran into this issue using Jenkins for CI/CD. In my case, the solution was to upgrade the version of Docker being run (it was using 17.something before), to 19.03.14 (the latest stable). I'm not sure what the minimum version needed is, but it would be helpful if that information could be included in the documentation.

**Comment by eladb** [comment]
@wojtii can you let us know if upgrading to a new docker version solves this issue?

**Comment by wojtii** [comment]
Yes it does, I have used version `19.03.14`, so the issue is only for docker version `17`

**Comment by corymhall** [comment]
@wojtii can you let me know if you are still seeing this issue on the latest version? We have made some changes to the way lambda-python performs docker bundling.

**Comment by wojtii** [comment]
> @wojtii can you let me know if you are still seeing this issue on the latest version? We have made some changes to the way lambda-python performs docker bundling.

Hi, it works for me, thanks for reaching back 🙂, I will close the issue
