### ISSUE TITLE
java.lang.IllegalStateException: Shutdown in progress

### ISSUE THREAD

**Issue by majasb** [aws/aws-cdk#11709]
Exception is logged when Java VM is shutting down.

### Reproduction Steps

Kotlin unit test synthesizing an empty app:
```
import software.amazon.awscdk.core.App
import kotlin.test.Test
import kotlin.test.assertEquals

class AssemblyTest {
    @Test fun testSynthesize() {
        val app = App()
        val cloudAssembly = app.synth()
        assertEquals(0, cloudAssembly.stacks.size)
    }
}
```

### What did you expect to happen?

No stacktrace logged.

### What actually happened?
```
Exception in thread "Terminate jsii client" java.lang.IllegalStateException: Shutdown in progress
	at java.base/java.lang.ApplicationShutdownHooks.remove(ApplicationShutdownHooks.java:82)
	at java.base/java.lang.Runtime.removeShutdownHook(Runtime.java:241)
	at software.amazon.jsii.JsiiRuntime.terminate(JsiiRuntime.java:224)
at java.base/java.lang.Thread.run(Thread.java:835)
```

### Environment

  - **CDK CLI Version  : 1.75.0 (build 7708242)**
  - **Framework Version: 1.75.0**
  - **Node.js Version: v12.6.0**
  - **OS               : macOS 11.0.1 (20B29)**
  - **Language (Version): Java (12.0.1)**

### Other

--- 

This is :bug: Bug Report

**Comment by john-tipper** [comment]
I am seeing the same issue with CDK CLI 1.71.0 (build 953bc25)

**Comment by maciejwalkowiak** [comment]
I am seeing the same issue with downgrading even to CLI 1.40.0

**Comment by pkatul** [comment]
I also face the same issue. 
CLI version - aws-cli/1.16.292

**Comment by michaelbrewer** [comment]
Some issue her

CLI version - 1.75.0 (build 7708242)
Java version - openjdk 11.0.8 2020-07-14 LTS
Operating system - macOS 10.15.7 (19H15)
Node version - v12.20.0

**Comment by timmattison** [comment]
Same here, but my stacks still launch successfully

AWS CLI version - aws-cli/2.0.62 Python/3.7.4 Darwin/18.7.0 exe/x86_64
CDK version - 1.75.0

**Comment by kdavisk6** [comment]
Same issue, and same result as @timmattison.  Also, it appears intermittently.  The Stack does get built and deployed successfully.

**Comment by michaelbrewer** [comment]
Very strange issue

**Comment by levischuckeats** [comment]
I started receiving this today, it appears to run when maven runs tests.

**Comment by RomainMuller** [comment]
Hey! Thanks for reporting! It appears the de-registering method cannot be called during VM shutdown, causing this stack trace to be logged. It should not affect your application's ability to run correctly and can be ignored until we release an updated version of the runtime which no longer attempts the illegal operation.

@all-contributors add majasb for bug

**Comment by RomainMuller** [comment]
Hey! Thanks for reporting! It appears the de-registering method cannot be called during VM shutdown, causing this stack trace to be logged. It should not affect your application's ability to run correctly and can be ignored until we release an updated version of the runtime which no longer attempts the illegal operation.

@all-contributors add @majasb for bug
