### ISSUE TITLE
(core): Cannot automatic cross-stack reference lists (impacts VpcEndpoint)

### ISSUE THREAD

**Issue by chillitom** [aws/aws-cdk#11700]
Most likely user error but I get the following error when trying to define an A record using `InterfaceVpcEndpointTarget`

```
 ❌  ProductionVpnStack failed: Error [ValidationError]: Template format error: The Value field of every Outputs member must evaluate to a String.
    at Request.extractError (C:\Users\Tom\AppData\Roaming\npm\node_modules\aws-cdk\node_modules\aws-sdk\lib\protocol\query.js:50:29)
    at Request.callListeners (C:\Users\Tom\AppData\Roaming\npm\node_modules\aws-cdk\node_modules\aws-sdk\lib\sequential_executor.js:106:20)
    at Request.emit (C:\Users\Tom\AppData\Roaming\npm\node_modules\aws-cdk\node_modules\aws-sdk\lib\sequential_executor.js:78:10)
    at Request.emit (C:\Users\Tom\AppData\Roaming\npm\node_modules\aws-cdk\node_modules\aws-sdk\lib\request.js:688:14)
    at Request.transition (C:\Users\Tom\AppData\Roaming\npm\node_modules\aws-cdk\node_modules\aws-sdk\lib\request.js:22:10)
    at AcceptorStateMachine.runTo (C:\Users\Tom\AppData\Roaming\npm\node_modules\aws-cdk\node_modules\aws-sdk\lib\state_machine.js:14:12)
    at C:\Users\Tom\AppData\Roaming\npm\node_modules\aws-cdk\node_modules\aws-sdk\lib\state_machine.js:26:10
    at Request.<anonymous> (C:\Users\Tom\AppData\Roaming\npm\node_modules\aws-cdk\node_modules\aws-sdk\lib\request.js:38:9)
    at Request.<anonymous> (C:\Users\Tom\AppData\Roaming\npm\node_modules\aws-cdk\node_modules\aws-sdk\lib\request.js:690:12)
    at Request.callListeners (C:\Users\Tom\AppData\Roaming\npm\node_modules\aws-cdk\node_modules\aws-sdk\lib\sequential_executor.js:116:18) {
  code: 'ValidationError',
  time: 2020-11-25T11:19:18.268Z,
  requestId: 'e7bf3cde-00cb-400b-b456-d15b54183d68',
  statusCode: 400,
  retryable: false,
  retryDelay: 641.5201941716402
}
Template format error: The Value field of every Outputs member must evaluate to a String.
```

### Reproduction Steps

Create a Vpc, InterfaceVpcEndpoint, RestApi, HostedZone and ARecord as configured in the code below.

```typescript
        const vpc = new ec2.Vpc(this, 'Vpc', {
            cidr: '10.1.0.0/16',
            enableDnsHostnames: true,
            enableDnsSupport: true,            
        })

        const vpcEndpoint = new ec2.InterfaceVpcEndpoint(this, 'ApiVpcEndpoint', {
            vpc: this.vpc,
            service: {
                name: 'com.amazonaws.eu-west-2.execute-api',
                port: 443
            },
            subnets: {
                subnets: this.vpc.privateSubnets
            },
            privateDnsEnabled: true,
            open: true
        })

        const hostedZone = new route53.HostedZone(this,
            'HostedZone',
            {
                vpcs: [vpc],
                zoneName: 'api.XXX.XXX' // redacted
            })

        const aRecord = new route53.ARecord(this, 'CustomDomainAliasRecord', {
            zone: hostedZone,
            target: route53.RecordTarget.fromAlias(new targets.InterfaceVpcEndpointTarget(vpcEndpoint))
        })

        const api = new apigateway.RestApi(this, 'mock-api', {
            endpointConfiguration: {
                types: [apigateway.EndpointType.PRIVATE],
                vpcEndpoints: [vpcEndpoint],
            },
            domainName: {
                certificate: cert,
                domainName: 'api.XXX.XXX', //redacted
            },
            policy: new iam.PolicyDocument({
                statements: [
                    new iam.PolicyStatement({
                        principals: [new iam.AnyPrincipal],
                        actions: ['execute-api:Invoke'],
                        resources: ['execute-api:/*'],
                        effect: iam.Effect.ALLOW,
                        conditions: {
                            StringEquals: {
                                "aws:SourceVpce": vpcEndpoint.vpcEndpointId
                            }
                        }
                    })
                ]
            }),
        })
```

### What did you expect to happen?

ARecord created pointing to Vpc endpoint.

### What actually happened?

Error message detailed above.

### Environment

  - **CDK CLI Version  :**  1.75.0
  - **Framework Version:** 1.75.0
  - **Node.js Version:** 14.15.1
  - **OS               :** Windows
  - **Language (Version):** TypeScript (4.1.2)

### Other

--- 

This is :bug: Bug Report

**Comment by rix0rrr** [comment]
From this code it's hard to tell where the `Output` is coming from.

Can you look at the `cdk.out/MyStack.template.json` file and copy/paste the section labeled `"Outputs": { ... }` ?

**Comment by chillitom** [comment]
These are the two outputs from deploying the stack with the `InterfaceVpcEndpointTarget` and dependency that defines the VPC.

```json
"Outputs": {
    "ExportsOutputRefApiVpcEndpointB4A4BC0CF110A445": {
      "Value": {
        "Ref": "ApiVpcEndpointB4A4BC0C"
      },
      "Export": {
        "Name": "ProductionVpnStack:ExportsOutputRefApiVpcEndpointB4A4BC0CF110A445"
      }
    },
    "ExportsOutputRefVpc8378EB38272D6E3A": {
      "Value": {
        "Ref": "Vpc8378EB38"
      },
      "Export": {
        "Name": "ProductionVpnStack:ExportsOutputRefVpc8378EB38272D6E3A"
      }
    },
    "ExportsOutputFnGetAttApiVpcEndpointB4A4BC0CDnsEntries1304E767": {
      "Value": {
        "Fn::GetAtt": [
          "ApiVpcEndpointB4A4BC0C",
          "DnsEntries"
        ]
      },
      "Export": {
        "Name": "ProductionVpnStack:ExportsOutputFnGetAttApiVpcEndpointB4A4BC0CDnsEntries1304E767"
      }
    },
    "ExportsOutputFnGetAttVpc8378EB38CidrBlock14DD2396": {
      "Value": {
        "Fn::GetAtt": [
          "Vpc8378EB38",
          "CidrBlock"
        ]
      },
      "Export": {
        "Name": "ProductionVpnStack:ExportsOutputFnGetAttVpc8378EB38CidrBlock14DD2396"
      }
    },
    "ExportsOutputRefVpcPrivateSubnet1Subnet536B997AFD4CC940": {
      "Value": {
        "Ref": "VpcPrivateSubnet1Subnet536B997A"
      },
      "Export": {
        "Name": "ProductionVpnStack:ExportsOutputRefVpcPrivateSubnet1Subnet536B997AFD4CC940"
      }
    },
    "ExportsOutputRefVpcPrivateSubnet2Subnet3788AAA1380949A3": {
      "Value": {
        "Ref": "VpcPrivateSubnet2Subnet3788AAA1"
      },
      "Export": {
        "Name": "ProductionVpnStack:ExportsOutputRefVpcPrivateSubnet2Subnet3788AAA1380949A3"
      }
    }
  }
```

The `InterfaceVpcEndpointTarget` is defined in the stack with the below outputs.

```json
  "Outputs": {
    "mockapiEndpointA37E302E": {
      "Value": {
        "Fn::Join": [
          "",
          [
            "https://",
            {
              "Ref": "mockapi27ECB3C9"
            },
            ".execute-api.",
            {
              "Ref": "AWS::Region"
            },
            ".",
            {
              "Ref": "AWS::URLSuffix"
            },
            "/",
            {
              "Ref": "mockapiDeploymentStageprodF1AA592B"
            },
            "/"
          ]
        ]
      }
    }
  }
}
```

**Comment by chillitom** [comment]
n.b. the outputs are unchanged if I comment out the target.

```javascript
//        new route53.ARecord(this, 'CustomDomainAliasRecord', {
//            zone: hostedZone,
//            target: route53.RecordTarget.fromAlias(new targets.InterfaceVpcEndpointTarget(props.vpcEndpoint))
//        })
```

**Comment by rix0rrr** [comment]
> These are the two outputs from deploying the stack with the `InterfaceVpcEndpointTarget` and dependency that defines the VPC.

Wait, this confuses me.

> from deploying the stack 

The error you are reporting prevents your stack from deploying, right? So is the template fragment you pasted from a template that successfully deployed? Or is it the template you TRIED to deploy but failed to?

**Comment by rix0rrr** [comment]
In any case, it's most likely this:

```
    "ExportsOutputFnGetAttApiVpcEndpointB4A4BC0CDnsEntries1304E767": {
      "Value": {
        "Fn::GetAtt": [
          "ApiVpcEndpointB4A4BC0C",
          "DnsEntries"
        ]
      },
      "Export": {
        "Name": "ProductionVpnStack:ExportsOutputFnGetAttApiVpcEndpointB4A4BC0CDnsEntries1304E767"
      }
```

**Comment by rix0rrr** [comment]
For now, it looks like you can't use `VpcEndpoint` in a cross-stack manner.

**Comment by chillitom** [comment]
> The error you are reporting prevents your stack from deploying, right? So is the template fragment you pasted from a template that successfully deployed? Or is it the template you TRIED to deploy but failed to?

Sorry, yes, should have said attempted deployment

**Comment by chillitom** [comment]
As an aside maybe the error produced by the validation could include the name of the Output.

**Comment by damnhandy** [comment]
Any updates on this issue? I'm running into the same thing as of CDK `1.116.0` and a reasonable work around remains elusive.

**Comment by joshs85** [comment]
This is still an issue.  Is there any plan to fix this?
