### ISSUE TITLE
Issues with some python modules upgrade from 1.74.0 to 1.75.0 yesterday

### ISSUE THREAD

**Issue by pandrel** [aws/aws-cdk#11710]
Unable to synth. The code was working till yesterday, But when i moved the code to a new folder and installed the requirements, the synth no longer works. 

### What actually happened?

```console
 ❯ cdk synth
jsii.errors.JavaScriptError:
  /private/var/folders/gw/w_p9d2l152q8ccvh34t_k711zlj_s5/T/jsii-kernel-JqXboD/node_modules/@aws-cdk/aws-ec2/lib/vpc-endpoint.js:137
          const region = core_1.Lazy.uncachedString({
                                     ^

  TypeError: core_1.Lazy.uncachedString is not a function
      at new InterfaceVpcEndpointAwsService (/private/var/folders/gw/w_p9d2l152q8ccvh34t_k711zlj_s5/T/jsii-kernel-JqXboD/node_modules/@aws-cdk/aws-ec2/lib/vpc-endpoint.js:137:36)
      at Object.<anonymous> (/private/var/folders/gw/w_p9d2l152q8ccvh34t_k711zlj_s5/T/jsii-kernel-JqXboD/node_modules/@aws-cdk/aws-ec2/lib/vpc-endpoint.js:148:53)
      at Module._compile (node:internal/modules/cjs/loader:1102:14)
      at Object.Module._extensions..js (node:internal/modules/cjs/loader:1131:10)
      at Module.load (node:internal/modules/cjs/loader:967:32)
      at Function.Module._load (node:internal/modules/cjs/loader:807:14)
      at Module.require (node:internal/modules/cjs/loader:991:19)
      at require (node:internal/modules/cjs/helpers:92:18)
      at Object.<anonymous> (/private/var/folders/gw/w_p9d2l152q8ccvh34t_k711zlj_s5/T/jsii-kernel-JqXboD/node_modules/@aws-cdk/aws-ec2/lib/vpc.js:14:24)
      at Module._compile (node:internal/modules/cjs/loader:1102:14)
```

The above exception was the direct cause of the following exception:

```console
Traceback (most recent call last):
  File "app.py", line 5, in <module>
    from resources.vpcStack import vpcStack
  File "/Users/pandrel/work/git/rumc-data-project/cdk/resources/vpcStack.py", line 1, in <module>
    from aws_cdk import (
  File "/Users/pandrel/work/git/rumc-data-project/cdk/.venv/lib/python3.8/site-packages/aws_cdk/aws_cloudformation/__init__.py", line 26, in <module>
    from ._jsii import *
  File "/Users/pandrel/work/git/rumc-data-project/cdk/.venv/lib/python3.8/site-packages/aws_cdk/aws_cloudformation/_jsii/__init__.py", line 12, in <module>
    import aws_cdk.aws_lambda._jsii
  File "/Users/pandrel/work/git/rumc-data-project/cdk/.venv/lib/python3.8/site-packages/aws_cdk/aws_lambda/__init__.py", line 540, in <module>
    from ._jsii import *
  File "/Users/pandrel/work/git/rumc-data-project/cdk/.venv/lib/python3.8/site-packages/aws_cdk/aws_lambda/_jsii/__init__.py", line 14, in <module>
    import aws_cdk.aws_ec2._jsii
  File "/Users/pandrel/work/git/rumc-data-project/cdk/.venv/lib/python3.8/site-packages/aws_cdk/aws_ec2/__init__.py", line 1075, in <module>
    from ._jsii import *
  File "/Users/pandrel/work/git/rumc-data-project/cdk/.venv/lib/python3.8/site-packages/aws_cdk/aws_ec2/_jsii/__init__.py", line 25, in <module>
    __jsii_assembly__ = jsii.JSIIAssembly.load(
  File "/Users/pandrel/work/git/rumc-data-project/cdk/.venv/lib/python3.8/site-packages/jsii/_runtime.py", line 43, in load
    _kernel.load(assembly.name, assembly.version, os.fspath(assembly_path))
  File "/Users/pandrel/work/git/rumc-data-project/cdk/.venv/lib/python3.8/site-packages/jsii/_kernel/__init__.py", line 243, in load
    self.provider.load(LoadRequest(name=name, version=version, tarball=tarball))
  File "/Users/pandrel/work/git/rumc-data-project/cdk/.venv/lib/python3.8/site-packages/jsii/_kernel/providers/process.py", line 344, in load
    return self._process.send(request, LoadResponse)
  File "/Users/pandrel/work/git/rumc-data-project/cdk/.venv/lib/python3.8/site-packages/jsii/_kernel/providers/process.py", line 332, in send
    raise JSIIError(resp.error) from JavaScriptError(resp.stack)
jsii.errors.JSIIError: core_1.Lazy.uncachedString is not a function
Subprocess exited with error 1
```

### Environment

  - **CDK CLI Version  :**
  - **Framework Version:**
  - **Node.js Version:** 
  - **OS               :**
  - **Language (Version):** 

### Other

Comparing the pip packages versions found some modules are upgraded. 

Package list where the code is not working:
```
❯ pip list
Package                             Version Location
----------------------------------- ------- -------------------------------------------------------
attrs                               20.3.0
aws-cdk.assets                      1.75.0
aws-cdk.aws-apigateway              1.75.0
aws-cdk.aws-apigatewayv2            1.75.0
aws-cdk.aws-applicationautoscaling  1.75.0
aws-cdk.aws-autoscaling             1.75.0
aws-cdk.aws-autoscaling-common      1.75.0
aws-cdk.aws-autoscaling-hooktargets 1.75.0
aws-cdk.aws-batch                   1.75.0
aws-cdk.aws-certificatemanager      1.75.0
aws-cdk.aws-cloudformation          1.75.0
aws-cdk.aws-cloudfront              1.75.0
aws-cdk.aws-cloudwatch              1.75.0
aws-cdk.aws-codebuild               1.75.0
aws-cdk.aws-codecommit              1.75.0
aws-cdk.aws-codeguruprofiler        1.75.0
aws-cdk.aws-codepipeline            1.75.0
aws-cdk.aws-cognito                 1.75.0
aws-cdk.aws-ec2                     1.75.0
aws-cdk.aws-ecr                     1.75.0
aws-cdk.aws-ecr-assets              1.75.0
aws-cdk.aws-ecs                     1.75.0
aws-cdk.aws-efs                     1.75.0
aws-cdk.aws-elasticloadbalancing    1.75.0
aws-cdk.aws-elasticloadbalancingv2  1.75.0
aws-cdk.aws-events                  1.75.0
aws-cdk.aws-events-targets          1.75.0
aws-cdk.aws-glue                    1.75.0
aws-cdk.aws-iam                     1.75.0
aws-cdk.aws-kinesis                 1.75.0
aws-cdk.aws-kinesisfirehose         1.75.0
aws-cdk.aws-kms                     1.75.0
aws-cdk.aws-lambda                  1.75.0
aws-cdk.aws-logs                    1.75.0
aws-cdk.aws-rds                     1.75.0
aws-cdk.aws-route53                 1.75.0
aws-cdk.aws-route53-targets         1.75.0
aws-cdk.aws-s3                      1.75.0
aws-cdk.aws-s3-assets               1.75.0
aws-cdk.aws-sam                     1.75.0
aws-cdk.aws-secretsmanager          1.75.0
aws-cdk.aws-servicediscovery        1.75.0
aws-cdk.aws-sns                     1.75.0
aws-cdk.aws-sns-subscriptions       1.75.0
aws-cdk.aws-sqs                     1.75.0
aws-cdk.aws-ssm                     1.75.0
aws-cdk.aws-stepfunctions           1.75.0
aws-cdk.aws-transfer                1.75.0
aws-cdk.cloud-assembly-schema       1.74.0
aws-cdk.core                        1.74.0
aws-cdk.custom-resources            1.75.0
aws-cdk.cx-api                      1.74.0
aws-cdk.region-info                 1.74.0
cattrs                              1.1.1
constructs                          3.2.42
jsii                                1.15.0
pip                                 20.2.1
publication                         0.0.3
python-dateutil                     2.8.1
setuptools                          49.2.1
six                                 1.15.0
typing-extensions                   3.7.4.3
```

Package list from folder where the cdk synth is working:
```
❯ pip list
Package                             Version Location
----------------------------------- ------- -----------------------------------------------------
attrs                               20.3.0
aws-cdk.assets                      1.74.0
aws-cdk.aws-apigateway              1.74.0
aws-cdk.aws-apigatewayv2            1.74.0
aws-cdk.aws-applicationautoscaling  1.74.0
aws-cdk.aws-autoscaling             1.74.0
aws-cdk.aws-autoscaling-common      1.74.0
aws-cdk.aws-autoscaling-hooktargets 1.74.0
aws-cdk.aws-batch                   1.74.0
aws-cdk.aws-certificatemanager      1.74.0
aws-cdk.aws-cloudformation          1.74.0
aws-cdk.aws-cloudfront              1.74.0
aws-cdk.aws-cloudwatch              1.74.0
aws-cdk.aws-codebuild               1.74.0
aws-cdk.aws-codecommit              1.74.0
aws-cdk.aws-codeguruprofiler        1.74.0
aws-cdk.aws-codepipeline            1.74.0
aws-cdk.aws-cognito                 1.74.0
aws-cdk.aws-ec2                     1.74.0
aws-cdk.aws-ecr                     1.74.0
aws-cdk.aws-ecr-assets              1.74.0
aws-cdk.aws-ecs                     1.74.0
aws-cdk.aws-efs                     1.74.0
aws-cdk.aws-elasticloadbalancing    1.74.0
aws-cdk.aws-elasticloadbalancingv2  1.74.0
aws-cdk.aws-events                  1.74.0
aws-cdk.aws-events-targets          1.74.0
aws-cdk.aws-glue                    1.74.0
aws-cdk.aws-iam                     1.74.0
aws-cdk.aws-kinesis                 1.74.0
aws-cdk.aws-kinesisfirehose         1.74.0
aws-cdk.aws-kms                     1.74.0
aws-cdk.aws-lambda                  1.74.0
aws-cdk.aws-logs                    1.74.0
aws-cdk.aws-rds                     1.74.0
aws-cdk.aws-route53                 1.74.0
aws-cdk.aws-route53-targets         1.74.0
aws-cdk.aws-s3                      1.74.0
aws-cdk.aws-s3-assets               1.74.0
aws-cdk.aws-sam                     1.74.0
aws-cdk.aws-secretsmanager          1.74.0
aws-cdk.aws-servicediscovery        1.74.0
aws-cdk.aws-sns                     1.74.0
aws-cdk.aws-sns-subscriptions       1.74.0
aws-cdk.aws-sqs                     1.74.0
aws-cdk.aws-ssm                     1.74.0
aws-cdk.aws-stepfunctions           1.74.0
aws-cdk.aws-transfer                1.75.0
aws-cdk.cloud-assembly-schema       1.74.0
aws-cdk.core                        1.74.0
aws-cdk.custom-resources            1.74.0
aws-cdk.cx-api                      1.74.0
aws-cdk.region-info                 1.74.0
cattrs                              1.1.1
constructs                          3.2.40
jsii                                1.14.1
pip                                 20.2.1
publication                         0.0.3
python-dateutil                     2.8.1
setuptools                          49.2.1
six                                 1.15.0
typing-extensions                   3.7.4.3
```

Downgrading all cdk modules package to 1.74.0 worked. 

--- 

This is :bug: Bug Report

**Comment by ScDavid** [comment]
Got the same error on CDK version 1.74.0 on a new CDK app.
What I did:
- new empty folder
- cdk init app --language=python
- write code to build lambda, role, bucket
- install requirements

On cdk synth I get the error on the line where I import lambda module. If I remove Lambda it works fine.

**Comment by rix0rrr** [comment]
Noticing your initial package list looks a little wonky:

```
aws-cdk.aws-sns-subscriptions       1.75.0
aws-cdk.aws-sqs                     1.75.0
aws-cdk.aws-ssm                     1.75.0
aws-cdk.aws-stepfunctions           1.75.0
aws-cdk.aws-transfer                1.75.0
aws-cdk.cloud-assembly-schema       1.74.0
aws-cdk.core                        1.74.0
aws-cdk.custom-resources            1.75.0
aws-cdk.cx-api                      1.74.0
aws-cdk.region-info                 1.74.0
```

Might be you upgraded while pip was in an inconsistent state, netting you some packages at `1.75.0` and others at `1.74.0`?

**Comment by rix0rrr** [comment]
Thanks for including the package list in your bug report! Without that this would have been insanely hard to debug!

**Comment by MrArnoldPalmer** [comment]
@pandrel I was able to reproduce this by using aws-cdk.aws-lambda at v1.75.0 with aws-cdk.core at v1.74.0. Upgrading core to v1.75.0 fixed the issue for me. Definitely reopen and let us know if that doesn't solve it for you.
