### ISSUE TITLE
(apigatewayv2): Lambda authorizer doesn't grant permission and unable to assign policy using CDK syntax

### ISSUE THREAD

**Issue by missourian55** [aws/aws-cdk#11766]
After creating lambda authorizer the invocation policies are not assigned 

### Reproduction Steps
``` java
 // Authorizer lambda function
        final Function authorizerFunction = Function.Builder.create(this, AUTHORIZER_LAMBDA)
            .runtime(JAVA_11)
            .code(fromAsset(FUNCTION_LOCATION))
            .handler("hello.SomeClass::handleRequest")
            .memorySize(getMemorySize())
            .timeout(seconds(30))
            .build();

        // Business lambda function
        final Function businessFunction = Function.Builder.create(this, BUSINESS_LAMBDA)
            .runtime(JAVA_11)
            .code(fromAsset(FUNCTION_LOCATION))
            .handler("io.SomeClass::handleRequest")
            .memorySize(getMemorySize())
            .build();

        // Http API
        final LambdaProxyIntegration proxyIntegration = LambdaProxyIntegration.Builder
            .create()
            .payloadFormatVersion(VERSION_2_0)
            .handler(businessFunction)
            .build();

        final HttpApi httpApi = HttpApi.Builder.create(this, "some")
            .defaultIntegration(proxyIntegration)
            .build();

        // Authorizer for APIGW-v2

        final CfnAuthorizer authorizer = CfnAuthorizer.Builder.create(this, "some"))
            .apiId(httpApi.getHttpApiId())
            .authorizerPayloadFormatVersion("2.0")
            .authorizerResultTtlInSeconds(seconds(120).toSeconds())
            .authorizerType("REQUEST")
            .identitySource(asList("$request.header.Authorization"))
            .authorizerUri("arn:aws:apigateway:" + getenv("AWS_DEFAULT_REGION") + ":lambda:path/2015-03-31/functions/"
                    + authorizerFunction.getFunctionArn() + "/invocations")
            .enableSimpleResponses(true) 
            .name("Some")
            .build();

```

### What did you expect to happen?

I want to have a policy auto assigned after authorizer creation similar to REST API. Right now I am enabling it through console which creates a policy like below. 

```json
{
  "Version": "2012-10-17",
  "Id": "default",
  "Statement": [
    {
      "Sid": "123b-5fbc-a7d0-1a43c8b22b81",
      "Effect": "Allow",
      "Principal": {
        "Service": "apigateway.amazonaws.com"
      },
      "Action": "lambda:InvokeFunction",
      "Resource": "arn:aws:lambda:us-east-1:123452:function:Some-authorizerD212W1CD-DKCF4FTJ2A1C",
      "Condition": {
        "ArnLike": {
          "AWS:SourceArn": "arn:aws:execute-api:us-east-1:123456:mfe34dr3u8/authorizers/blhlet"
        }
      }
    }
  ]
}
```

### What actually happened?

When I tried below code I am facing **Circular dependency** and `A PolicyStatement used in an identity-based policy cannot specify any IAM principals` issue. Any suggestions on how to fix this?

```java

        final PolicyStatement p1 = PolicyStatement.Builder.create()
            .effect(Effect.ALLOW)
            .principals(asList(ServicePrincipal.Builder.create(("apigateway.amazonaws.com")).build()))
            .actions(asList("lambda:InvokeFunction"))
            .resources(asList(authorizerFunction.getFunctionArn()))
            .conditions(new HashMap<String, Object>() {
                {
                    put("ArnLike", new HashMap<String, String>() {
                        {
                            put("AWS:SourceArn", Fn.getAtt(authorizer.getLogicalId(), "Arn").toString());
                        }
                    });
                }
            }).build();

        authorizerFunction.addToRolePolicy(p1);
```

### Environment

  - **CDK CLI Version  :** 1.75.0
  - **Framework Version:**
  - **Node.js Version:**  v12.18.0
  - **OS               :** macos
  - **Language (Version):**  Java 11

### Other

```java
authorizer/ServiceRole/DefaultPolicy] A PolicyStatement used in an identity-based policy cannot specify any IAM principals.
Error: Validation failed with the following errors:
  [Test/authorizer/ServiceRole/DefaultPolicy] A PolicyStatement used in an identity-based policy cannot specify any IAM principals.
    at validateTree (/private/var/folders/gg/2d825wm160v86v5w5r8h413h0000gq/T/jsii-kernel-pSW8fq/node_modules/@aws-cdk/core/lib/private/synthesis.js:164:15)
    at Object.synthesize (/private/var/folders/gg/2d825wm160v86v5w5r8h413h0000gq/T/jsii-kernel-pSW8fq/node_modules/@aws-cdk/core/lib/private/synthesis.js:23:9)
    at App.synth (/private/var/folders/gg/2d825wm160v86v5w5r8h413h0000gq/T/jsii-kernel-pSW8fq/node_modules/@aws-cdk/core/lib/stage.js:90:41)
    at /private/var/folders/gg/2d825wm160v86v5w5r8h413h0000gq/T/jsii-java-runtime13296992936493022836/jsii-runtime.js:3380:51
    at Kernel._wrapSandboxCode (/private/var/folders/gg/2d825wm160v86v5w5r8h413h0000gq/T/jsii-java-runtime13296992936493022836/jsii-runtime.js:4040:16)
    at /private/var/folders/gg/2d825wm160v86v5w5r8h413h0000gq/T/jsii-java-runtime13296992936493022836/jsii-runtime.js:3380:25
    at Kernel._ensureSync (/private/var/folders/gg/2d825wm160v86v5w5r8h413h0000gq/T/jsii-java-runtime13296992936493022836/jsii-runtime.js:4017:20)
    at Kernel.invoke (/private/var/folders/gg/2d825wm160v86v5w5r8h413h0000gq/T/jsii-java-runtime13296992936493022836/jsii-runtime.js:3379:26)
    at KernelHost.processRequest (/private/var/folders/gg/2d825wm160v86v5w5r8h413h0000gq/T/jsii-java-runtime13296992936493022836/jsii-runtime.js:13119:28)
    at KernelHost.run (/private/var/folders/gg/2d825wm160v86v5w5r8h413h0000gq/T/jsii-java-runtime13296992936493022836/jsii-runtime.js:13057:14)
    at software.amazon.jsii.JsiiRuntime.processErrorResponse (JsiiRuntime.java:127)
```

If I use below option the policy is open to all apiGateways in this account, which I don't want

```java
authorizerFunction.grantInvoke((new ServicePrincipal("apigateway.amazonaws.com")));
```

```json
{
  "Version": "2012-10-17",
  "Id": "default",
  "Statement": [
    {
      "Sid": "Test-authorizerInvokeServicePrincipalapigatewayamazonawscom51DER56-BX7ADAZX5V65",
      "Effect": "Allow",
      "Principal": {
        "Service": "apigateway.amazonaws.com"
      },
      "Action": "lambda:InvokeFunction",
      "Resource": "arn:aws:lambda:us-east-1:123456:function:Test-authorizerDSE4D-FA99LV32PGTU"
    }
  ]
}
```
--- 

This is :bug: Bug Report

**Comment by missourian55** [comment]
Finally figured out how to add most restrictive permission for authorizer lambda function. You have to construct authorizer ARN manually
` arn:aws:execute-api:aws-region:aws-account:apigw-ref/authorizers/authorizer-ref`
```java
        final CfnApi api = (CfnApi) httpApi.getNode().getDefaultChild();
        final String sourceArn =
            format("arn:%s:execute-api:%s:%s:%s/authorizers/%s", getPartition(), getRegion(), getAccount(), api.getRef(),
                authorizer.getRef());
        authorizerFunction.addPermission("SomeName", Permission.builder()
            .principal(ServicePrincipal.Builder.create(("apigateway.amazonaws.com")).build())
            .action("lambda:InvokeFunction")
            .sourceArn(sourceArn)
            .build());
```
