### ISSUE TITLE
(elbv2): unable to utilize add_security_group method on ALB in Python

### ISSUE THREAD

**Issue by michaelsimon** [aws/aws-cdk#11812]
Unable to utilize `add_security_group` on an ALB construct to add more than one security group to an ALB.
This appears to have been implemented in PR #10244.

### Reproduction Steps

See code sample below.

### What did you expect to happen?

Add SG to ALB

### What actually happened?

Received Error during cdk synth
`AttributeError: 'ApplicationLoadBalancer' object has no attribute 'add_security_group'`

### Environment

  - **CDK CLI Version  :** 1.75.0
  - **Framework Version:** Python
  - **Node.js Version:** 10.19.0
  - **OS:** macOS Catalina 10.15.7
  - **Language (Version):** Python (3.8.2)

### Other

```python
from aws_cdk import core
import aws_cdk.aws_ec2 as ec2
import aws_cdk.aws_elasticloadbalancingv2 as elb
import aws_cdk.aws_autoscaling as autoscaling
import aws_cdk.aws_certificatemanager as acm
import aws_cdk.aws_iam as iam

class EC2Stack(core.Stack):

    def __init__(self, scope: core.Construct, id: str, vpc, **kwargs) -> None:
        super().__init__(scope, id, **kwargs)

        alb = elb.ApplicationLoadBalancer(self, "Prod-WP-App-ALB-WEST",
                                          vpc=vpc, 
                                          ip_address_type=elb.IpAddressType.IPV4,
                                          deletion_protection=False,
                                          idle_timeout=core.Duration.minutes(2),
                                          internet_facing=True,
                                          load_balancer_name="Prod-WP-App-ALB-WEST",
                                          http2_enabled=True
                                          )

        alb.add_security_group(ec2.SecurityGroup.from_security_group_id(self, "sgALBCFlookup", security_group_id=sgALBCF.security_group_id,mutable=False))
```
**Command**: `cdk synth Prod-Wordpress-EC2 --profile=www-prod`
```bash
>>Traceback (most recent call last):
  File "app.py", line 25, in <module>
    ec2_stack = EC2Stack(app, "Prod-Wordpress-EC2",
  File "/Users/msimon/.pyenv/versions/3.8.2/lib/python3.8/site-packages/jsii/_runtime.py", line 66, in __call__
    inst = super().__call__(*args, **kwargs)
  File "/Users/msimon/Desktop/Web Projects/AWS VPC/new-vpc-alb-asg-mysql/stack/cdk_ec2_stack.py", line 145, in __init__
    alb.add_security_group(ec2.SecurityGroup.from_security_group_id(self, "sgALBCFlookup", security_group_id=sgALBCF.security_group_id,mutable=False))
AttributeError: 'ApplicationLoadBalancer' object has no attribute 'add_security_group'
Subprocess exited with error 1```

**Comment by njlynch** [comment]
Hi @michaelsimon ,

You wrote in the your CDK CLI version is 1.75.0; what version(s) of the CDK library are you using? This functionality has been present since CDK 1.63.0, so you'll want to ensure all packages are at least that version. Do note that all CDK packages need to be at the same version.

**Comment by michaelsimon** [comment]
My apologies, I had an outdated version of the python libraries. Thank you for your assistance.
