### ISSUE TITLE
(stepfunctions-tasks): SageMakerCreateTrainingJob.resource_config cannot use JSONPath.stringAt for ec2.InstanceType

### ISSUE THREAD

**Issue by zhuoyue0515** [aws/aws-cdk#11928]
CDK throws an error when passing ec2.InstanceType(JsonPath.stringAt(...)) when defining the instance type used for tasks.SageMakerCreateTrainingJob.resource_config, quite similar to this [issue](https://github.com/aws/aws-cdk/issues/11605) which is recently fixed by this [PR](https://github.com/aws/aws-cdk/pull/11749), would be good to also fix for resource_config:)

### Reproduction Steps
```
training_step = sfn_tasks.SageMakerCreateTrainingJob(
self, 
"Train Model", 
training_job_name=training_job_name, 
algorithm_specification=algorithm_specification,
resource_config=sfn_tasks.ResourceConfig(
instance_count=1,
instance_type=aws_ec2.InstanceType(sfn.JsonPath.string_at('$.params.InstanceType')),
volume_size=core.Size.gibibytes(10),
volume_encryption_key=self.get_kms_key()
))
```
### What did you expect to happen?
That I could refer to the step-functions state using JsonPath to configure the instance type used in an SageMaker Training Job

### What actually happened?

```
jsii.errors.JavaScriptError:
  Error: Field references must be the entire string, cannot concatenate them (found 'ml.${Token[params.InstanceType.323]}')
      at jsonPathString (/private/var/folders/gq/b1d_51jx4nsfqmx8m5xs30q00000gp/T/jsii-kernel-El8Yv0/node_modules/@aws-cdk/aws-stepfunctions/lib/json-path.js:193:15)
      at Object.renderString [as handleString] (/private/var/folders/gq/b1d_51jx4nsfqmx8m5xs30q00000gp/T/jsii-kernel-El8Yv0/node_modules/@aws-cdk/aws-stepfunctions/lib/json-path.js:142:18)
      at recurseObject (/private/var/folders/gq/b1d_51jx4nsfqmx8m5xs30q00000gp/T/jsii-kernel-El8Yv0/node_modules/@aws-cdk/aws-stepfunctions/lib/json-path.js:86:41)
      at recurseObject (/private/var/folders/gq/b1d_51jx4nsfqmx8m5xs30q00000gp/T/jsii-kernel-El8Yv0/node_modules/@aws-cdk/aws-stepfunctions/lib/json-path.js:101:24)
      at Object.renderObject (/private/var/folders/gq/b1d_51jx4nsfqmx8m5xs30q00000gp/T/jsii-kernel-El8Yv0/node_modules/@aws-cdk/aws-stepfunctions/lib/json-path.js:31:12)
      at Function.renderObject (/private/var/folders/gq/b1d_51jx4nsfqmx8m5xs30q00000gp/T/jsii-kernel-El8Yv0/node_modules/@aws-cdk/aws-stepfunctions/lib/fields.js:192:28)
      at SageMakerCreateTrainingJob._renderTask (/private/var/folders/gq/b1d_51jx4nsfqmx8m5xs30q00000gp/T/jsii-kernel-El8Yv0/node_modules/@aws-cdk/aws-stepfunctions-tasks/lib/sagemaker/create-training-job.js:108:40)
      at SageMakerCreateTrainingJob.toStateJson (/private/var/folders/gq/b1d_51jx4nsfqmx8m5xs30q00000gp/T/jsii-kernel-El8Yv0/node_modules/@aws-cdk/aws-stepfunctions/lib/states/task-base.js:62:21)
      at StateGraph.toGraphJson (/private/var/folders/gq/b1d_51jx4nsfqmx8m5xs30q00000gp/T/jsii-kernel-El8Yv0/node_modules/@aws-cdk/aws-stepfunctions/lib/state-graph.js:91:43)
      at Branches.branches.map.b (/private/var/folders/gq/b1d_51jx4nsfqmx8m5xs30q00000gp/T/jsii-kernel-El8Yv0/node_modules/@aws-cdk/aws-stepfunctions/lib/states/state.js:268:48)
```

### Environment

  - **CDK CLI Version  :1.77.0
  - **Framework Version:@amzn/cdk-build/2.0.0
  - **Node.js Version:v10.22.1
  - **OS               :macOS 10.15.7
  - **Language (Version): Python (3.8.3) 

--- 

This is :bug: Bug Report

**Comment by zhuoyue0515** [comment]
Any update here:)?

**Comment by zhuoyue0515** [comment]
@shivlaks Hi, do we still have plan to fix this?

**Comment by RomainGuillemaud** [comment]
Hi @shivlaks, is there any update on this issue?
