### ISSUE TITLE
(lambda): Error creating DockerImageFunction

### ISSUE THREAD

**Issue by SZubarev** [aws/aws-cdk#11975]
I'm trying to deploy containerized lambda function from local Dockerfile.
I tried to build the container locally using the Dockerfile - build is fine.

### Reproduction Steps

Error happeining when deploying function using the code:
```
new lambda.DockerImageFunction(this, 'ContainerLambdaFunction', {
      code: lambda.DockerImageCode.fromImageAsset(path.join(__dirname, '../..')),
    });
```

The same lambda is deployed and running normally using the below code from the image pushed to ECR:

```
const repo = ecr.Repository.fromRepositoryName(this, 'EcrRepo', "contlambda");

const containerFn = new lambda.DockerImageFunction(this, 'ECRFunction', {
      code: lambda.DockerImageCode.fromEcr(repo),
});
```

### What did you expect to happen?

Image is built and pushed to ECR, lambda function is created and deployed

### What actually happened?

Getting the error

```
Error: ENAMETOOLONG: name too long, mkdir '/Users/szubarev/projects/go/containerlambda/cdk/cdk.out/asset.1b410129b410ece8609787ac006897230e515f69b407f8c72b64a6bb0af1c821/cdk/cdk.out/asset.1b410129b410ece8609787ac006897230e515f69b407f8c72b64a6bb0af1c821/cdk/cdk.out/asset.1b410129b410ece8609787ac006897230e515f69b407f8c72b64a6bb0af1c821/cdk/cdk.out/asset.1b410129b410ece8609787ac006897230e515f69b407f8c72b64a6bb0af1c821/cdk/cdk.out/asset.1b410129b410ece8609787ac006897230e515f69b407f8c72b64a6bb0af1c821/cdk/cdk.out/asset.1b410129b410ece8609787ac006897230e515f69b407f8c72b64a6bb0af1c821/cdk/cdk.out/asset.1b410129b410ece8609787ac006897230e515f69b407f8c72b64a6bb0af1c821/cdk/cdk.out/asset.1b410129b410ece8609787ac006897230e515f69b407f8c72b64a6bb0af1c821/cdk/cdk.out/asset.1b410129b410ece8609787ac006897230e515f69b407f8c72b64a6bb0af1c821/cdk/cdk.out/asset.1b410129b410ece8609787ac006897230e515f69b407f8c72b64a6bb0af1c821/cdk/cdk.out/asset.1b410129b410ece8609787ac006897230e515f69b407f8c72b64a6bb0af1c821/cdk/cdk.out/asset.1b410129b410ece8609787ac006897230e515f69b407f8c72b64a6bb0af1c821'
    at Object.mkdirSync (node:fs:1003:3)
    at copyDirectory (/Users/szubarev/projects/go/containerlambda/cdk/node_modules/@aws-cdk/core/lib/fs/copy.ts:48:10)
    at copyDirectory (/Users/szubarev/projects/go/containerlambda/cdk/node_modules/@aws-cdk/core/lib/fs/copy.ts:49:7)
    at copyDirectory (/Users/szubarev/projects/go/containerlambda/cdk/node_modules/@aws-cdk/core/lib/fs/copy.ts:49:7)
    at copyDirectory (/Users/szubarev/projects/go/containerlambda/cdk/node_modules/@aws-cdk/core/lib/fs/copy.ts:49:7)
    at copyDirectory (/Users/szubarev/projects/go/containerlambda/cdk/node_modules/@aws-cdk/core/lib/fs/copy.ts:49:7)
    at copyDirectory (/Users/szubarev/projects/go/containerlambda/cdk/node_modules/@aws-cdk/core/lib/fs/copy.ts:49:7)
    at copyDirectory (/Users/szubarev/projects/go/containerlambda/cdk/node_modules/@aws-cdk/core/lib/fs/copy.ts:49:7)
    at copyDirectory (/Users/szubarev/projects/go/containerlambda/cdk/node_modules/@aws-cdk/core/lib/fs/copy.ts:49:7)
    at copyDirectory (/Users/szubarev/projects/go/containerlambda/cdk/node_modules/@aws-cdk/core/lib/fs/copy.ts:49:7)
```

### Environment

  - **CDK CLI Version  :** 1.77.0
  - **Framework Version:**
  - **Node.js Version:**  v15.3.0
  - **OS               :** MacOS 10.15.7
  - **Language (Version):**  TypeScript

### Other

--- 

This is :bug: Bug Report

**Comment by nija-at** [comment]
The path you have provided should not include the root of the package. The package root is where `cdk.out` is placed by default and is where the asset is bundled as part of synthesis. 

Typically, a folder within the package structure is provided as the asset path. This folder should have a `Dockerfile` present in it.

**Comment by SZubarev** [comment]
Is there a way to specify context folder for docker build or it's always location of Dockerfile provided?
