### ISSUE TITLE
(aws-ec2): Maximum call stack size exceeded after (Resolution error:){loop}

### ISSUE THREAD

**Issue by bilardi** [aws/aws-cdk#12250]
When it is created the EC2 instance with **block_devices** property, the **synth()** method returns the error message below:

```
      at Array.join (<anonymous>)
      at resolve (/private/var/folders/g6/c78f9__d7sgdjk90r24112200000gp/T/jsii-kernel-bAd8X3/node_modules/@aws-cdk/core/lib/private/resolve.js:18:35)
      at Object.resolve (/private/var/folders/g6/c78f9__d7sgdjk90r24112200000gp/T/jsii-kernel-bAd8X3/node_modules/@aws-cdk/core/lib/private/resolve.js:29:33)
      at DefaultTokenResolver.resolveToken (/private/var/folders/g6/c78f9__d7sgdjk90r24112200000gp/T/jsii-kernel-bAd8X3/node_modules/@aws-cdk/core/lib/resolvable.js:48:30)
      at resolve (/private/var/folders/g6/c78f9__d7sgdjk90r24112200000gp/T/jsii-kernel-bAd8X3/node_modules/@aws-cdk/core/lib/private/resolve.js:95:33)
      at Object.resolve (/private/var/folders/g6/c78f9__d7sgdjk90r24112200000gp/T/jsii-kernel-bAd8X3/node_modules/@aws-cdk/core/lib/private/resolve.js:29:33)
      at RememberingTokenResolver.resolveToken (/private/var/folders/g6/c78f9__d7sgdjk90r24112200000gp/T/jsii-kernel-bAd8X3/node_modules/@aws-cdk/core/lib/resolvable.js:48:30)
      at RememberingTokenResolver.resolveToken (/private/var/folders/g6/c78f9__d7sgdjk90r24112200000gp/T/jsii-kernel-bAd8X3/node_modules/@aws-cdk/core/lib/private/resolve.js:142:22)
      at resolve (/private/var/folders/g6/c78f9__d7sgdjk90r24112200000gp/T/jsii-kernel-bAd8X3/node_modules/@aws-cdk/core/lib/private/resolve.js:95:33)
      at Object.resolve (/private/var/folders/g6/c78f9__d7sgdjk90r24112200000gp/T/jsii-kernel-bAd8X3/node_modules/@aws-cdk/core/lib/private/resolve.js:29:33)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "possible_bug.py", line 105, in <module>
    app.synth()
  File "/Users/alessandra.bilardi/.env/lib/python3.8/site-packages/aws_cdk/core/__init__.py", line 13777, in synth
    return jsii.invoke(self, "synth", [options])
  File "/Users/alessandra.bilardi/.env/lib/python3.8/site-packages/jsii/_kernel/__init__.py", line 125, in wrapped
    return _recursize_dereference(kernel, fn(kernel, *args, **kwargs))
  File "/Users/alessandra.bilardi/.env/lib/python3.8/site-packages/jsii/_kernel/__init__.py", line 315, in invoke
    response = self.provider.invoke(
  File "/Users/alessandra.bilardi/.env/lib/python3.8/site-packages/jsii/_kernel/providers/process.py", line 362, in invoke
    return self._process.send(request, InvokeResponse)
  File "/Users/alessandra.bilardi/.env/lib/python3.8/site-packages/jsii/_kernel/providers/process.py", line 332, in send
    raise JSIIError(resp.error) from JavaScriptError(resp.stack)
jsii.errors.JSIIError:
```

This error is preceded and followed by **Maximum call stack size exceeded** after (**Resolution error:**){loop}
See the entire log file in attach for the details.

### Reproduction Steps

When in the **aws_ec2.Instance()** you add the **block_devices** property,

```python
        volume = ec2.BlockDeviceVolume(self)
        volume.ebs(
            delete_on_termination=params['delete_on_termination'],
            volume_size=params['volume_size'],
            volume_type=ec2.EbsDeviceVolumeType(params['volume_type'])
        )
        block_device = ec2.BlockDevice(
            device_name=params['device_name'],
            volume=volume
        )
        ec2_instance = ec2.Instance(self, ec2_name,
            machine_image=params['machine_image'],
            vpc=params['vpc'],
            security_group=params['security_group'],
            instance_type=ec2.InstanceType(params['instance_type']),
            key_name=params['key_name'],
            block_devices=[block_device] # without this line, all works fine
        )     
```

And then you synthesize the app by **app.synth()**, the synthesization fails with the error message described above.

You can try the requirements and script files in attach with these commands:

```bash
python3 -m venv .env
source .env/bin/activate
pip install -r requirements.txt
python3 possible_bug.txt
```

or

```bash
docker run -it -v $(pwd):/work masahif/aws-cdk-python38 bash
pip install -r requirements.txt
python3 possible_bug.txt
```

### What did you expect to happen?

I expected to create an EC2 instance with a specific block_device like the parameters passed.

### What actually happened?

The cloud assembly of EC2 instance fails when it is synthesized.

### Environment

  - **CDK CLI Version  :** 1.80.0 (build 31132ca)
  - **Framework Version:** 1.80.0
  - **Node.js Version:** v14.5.0
  - **OS               :** the same reason on mac with Python 3.8.2 and on docker with alpine + Python 3.8.7
  - **Language (Version):** Python 3.8

### Other

See the requirements, log and script files in attach.
[requirements.txt](https://github.com/aws/aws-cdk/files/5747883/requirements.txt)
[possible_bug.log](https://github.com/aws/aws-cdk/files/5747877/possible_bug.log)
[possible_bug.txt](https://github.com/aws/aws-cdk/files/5747878/possible_bug.txt)

--- 

This is :bug: Bug Report

**Comment by rix0rrr** [comment]
```
  volume = ec2.BlockDeviceVolume(self)
volume.ebs(
```

Should have been:

```
volume = ec2.BlockDeviceVolume.ebs(...)
```

-------

jsii should have prevented what you did for two reasons:

* The constructor is `protected` -- you should not have been allowed to instantiate this class 
* The `ebs` method is `static` -- you should not have been allowed to call it on an *instance*

Turning this into a jsii bug report/feature request, to add runtime checks into the codegen that would detect and error on these illegal call patterns.

**Comment by RomainMuller** [comment]
> The constructor is `protected` -- you should not have been allowed to instantiate this class

The jsii protocol _must_ allow invoking `protected` constructors, or else it is impossible to extend a class with a `protected` constructor. There is no way to distinguish between this being invoked by an `__init__` function delegating to `super` versus a direct call as was done here...

> The `ebs` method is `static` -- you should not have been allowed to call it on an instance

Does Python really make a distinction though?

**Comment by bilardi** [comment]
> ```
>   volume = ec2.BlockDeviceVolume(self)
> volume.ebs(
> ```
> 
> Should have been:
> 
> ```
> volume = ec2.BlockDeviceVolume.ebs(...)
> ```

I've tested your suggestion and it works fine !

I think it could be useful to sign this specific class not instantiable: https://docs.aws.amazon.com/cdk/api/latest/python/aws_cdk.aws_autoscaling/BlockDeviceVolume.html
