### ISSUE TITLE
(aws-lambda-python): cannot run tests due to 'docker exited with status 1'

### ISSUE THREAD

**Issue by erudisch** [aws/aws-cdk#12264]
When using `PythonLayerVersion` and `PythonFunction` from `aws-lambda-python` i'm not able to test my infrastructure due to the error `docker exited with status 1`

### Reproduction Steps

Test a stack using `jest`. This stack includes the following python layer:

```
import * as pythonlambda from '@aws-cdk/aws-lambda-python';

const commons = new pythonlambda.PythonLayerVersion(this, 'Common', {
    entry: './commons_python',
});
```

When testing this stack:

```
test('Api Gateway Created', () => {
  const app = new cdk.App({
      outdir: './cdk.out',
  });
  // WHEN
  const stack = new CustomStack(app, 'MyTestStack');
  // THEN
  expectCDK(stack).to(haveResource('AWS::Lambda::LayerVersion'));
});
```

this happens:

`docker exited with status 1`

```
      45 |         });
      46 | 
    > 47 |         const commons = new pythonlambda.PythonLayerVersion(this, 'Common', {
         |                         ^
      48 |             entry: './commons_python',
      49 |         });

      at dockerExec (node_modules/@aws-cdk/core/lib/bundling.ts:318:11)
      at Function.fromAsset (node_modules/@aws-cdk/core/lib/bundling.ts:126:5)
      at Object.bundle (node_modules/@aws-cdk/aws-lambda-python/lib/bundling.ts:57:41)
      at new PythonLayerVersion (node_modules/@aws-cdk/aws-lambda-python/lib/layer.ts:47:13)
      at new OrdersStack (lib/backend/orders-stack.ts:47:28)
      at new BackendStack (lib/backend/backend-stack.ts:44:24)
      at Object.<anonymous> (test/backend.test.ts:50:19)
```

This also happens with `PythonFunction`.

### What did you expect to happen?

Test checks for resource `'AWS::Lambda::LayerVersion'`

### What actually happened?

Test fails with `docker exited with status 1`

### Environment

  - **CDK CLI Version  :*1.80.0*
  - **Framework Version:*1.80.0*
  - **Node.js Version:*v13.8.0*
  - **OS               :*mac os 11.1*
  - **Language (Version):*TypeScript (4.1.3)*

--- 

This is :bug: Bug Report

**Comment by erudisch** [comment]
I was able to solve the issue. The problem was that i pull the images from a private ecr. that why i had to set my account data properly and do the docker login before running the tests.

So in every `test.ts` that uses a docker specific lambda add this:

```
const env = {
    account: <ACCOUNT>,
    region: <REGION>,
};
```

and modify your package.json accordingly:

```
"test": "docker login -u AWS -p $(aws ecr get-login-password --region <REGION>)<ACCOUNT>.dkr.ecr.<REGION>.amazonaws.com && jest",
```
