### ISSUE TITLE
(aws_rds): cluster_endpoint.port returns wrong data

### ISSUE THREAD

**Issue by brugnara** [aws/aws-cdk#12286]
I'm creating a new RDS Postgres cluster, then a random number is returned instead of the right `port`.

I need the Entrypoint data for a Docker and I'm following [this](
https://docs.aws.amazon.com/cdk/api/latest/python/aws_cdk.aws_rds/Endpoint.html#aws_cdk.aws_rds.Endpoint). So I'm using the `cluster_endpoint` object obtained after the cluster creation but for `.port`, a wrong data is returned (random number: `-1.88815458970879e+289` instead of `${Token[TOKEN.187]}`). 

This problem doesn't occur when reading `.socket_address` prop.

More details and logs as follows.

### Reproduction Steps

```python
# prep:
vpc = ec2.Vpc(self, "VPCWiki", max_azs=3)
dbCluster = rds.DatabaseCluster(
    self,
    "DBwiki",
    engine=rds.DatabaseClusterEngine.aurora_postgres(
        version=rds.AuroraPostgresEngineVersion.VER_11_8
    ),
    instance_props={"vpc_subnets": {
            "subnet_type": ec2.SubnetType.PRIVATE
        },
        "vpc": vpc
    }
)

# log:
print(dbCluster.cluster_endpoint)
print(dbCluster.cluster_endpoint.hostname)
print(dbCluster.cluster_endpoint.port)
print(dbCluster.cluster_endpoint.socket_address)
```

```
# gives:
<aws_cdk.aws_rds.Endpoint object at 0x111dbd040>
${Token[TOKEN.182]}
-1.88815458970879e+289
${Token[TOKEN.182]}:${Token[TOKEN.187]}
```

### What did you expect to happen?

`-1.88815458970879e+289` should be `${Token[TOKEN.187]}`.

### What actually happened?

`-1.88815458970879e+289` is returned, causing errors when used:

```python
containerImage = ecs.ContainerImage.from_registry("requarks/wiki:2")
container = task.add_container(
    "DockerWiki",
    image=containerImage,
    environment={
        "DB_HOST": dbCluster.cluster_endpoint.hostname,
        "DB_PORT": dbCluster.cluster_endpoint.port,
        [...]
```

```bash
cdk synth

# outputs:
[...]
jsii.errors.JSIIError: Expected a string, got -1.88815458970879e+289 (number)
```

### Environment

  - **CDK CLI Version  :** 1.80.0 (build 31132ca)
  - **Framework Version:** ???
  - **Node.js Version:** v12.16.0
  - **OS               :** macOS 10.15.7
  - **Language (Version):** Python (3.9.1)

### Other

```
cdk synth
<aws_cdk.aws_rds.Endpoint object at 0x10b4ea220>
${Token[TOKEN.182]}
-1.88815458970879e+289
${Token[TOKEN.182]}:${Token[TOKEN.187]}
jsii.errors.JavaScriptError:

  Error: Expected a string, got -1.88815458970879e+289 (number)
      at Object.deserialize (/Users/vrut/dev/praim/iac/wiki/.venv/lib/python3.9/site-packages/jsii/_embedded/jsii/jsii-runtime.j
s:4378:23)
      at Kernel._toSandbox (/Users/vrut/dev/praim/iac/wiki/.venv/lib/python3.9/site-packages/jsii/_embedded/jsii/jsii-runtime.js
:3950:61)
      at /Users/vrut/dev/praim/iac/wiki/.venv/lib/python3.9/site-packages/jsii/_embedded/jsii/jsii-runtime.js:4512:74
      at mapValues (/Users/vrut/dev/praim/iac/wiki/.venv/lib/python3.9/site-packages/jsii/_embedded/jsii/jsii-runtime.js:4869:27
)
      at Object.deserialize (/Users/vrut/dev/praim/iac/wiki/.venv/lib/python3.9/site-packages/jsii/_embedded/jsii/jsii-runtime.j
s:4512:28)
      at Kernel._toSandbox (/Users/vrut/dev/praim/iac/wiki/.venv/lib/python3.9/site-packages/jsii/_embedded/jsii/jsii-runtime.js
:3950:61)
      at /Users/vrut/dev/praim/iac/wiki/.venv/lib/python3.9/site-packages/jsii/_embedded/jsii/jsii-runtime.js:4597:29
      at mapValues (/Users/vrut/dev/praim/iac/wiki/.venv/lib/python3.9/site-packages/jsii/_embedded/jsii/jsii-runtime.js:4869:27
)
      at Object.deserialize (/Users/vrut/dev/praim/iac/wiki/.venv/lib/python3.9/site-packages/jsii/_embedded/jsii/jsii-runtime.j
s:4593:20)
      at Kernel._toSandbox (/Users/vrut/dev/praim/iac/wiki/.venv/lib/python3.9/site-packages/jsii/_embedded/jsii/jsii-runtime.js
:3950:61)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):

  File "/Users/vrut/dev/praim/iac/wiki/app.py", line 9, in <module>
    WikiStack(app, "wiki")
  File "/Users/vrut/dev/praim/iac/wiki/.venv/lib/python3.9/site-packages/jsii/_runtime.py", line 69, in __call__
    inst = super().__call__(*args, **kwargs)
  File "/Users/vrut/dev/praim/iac/wiki/wiki/wiki_stack.py", line 60, in __init__
    container = task.add_container(
  File "/Users/vrut/dev/praim/iac/wiki/.venv/lib/python3.9/site-packages/aws_cdk/aws_ecs/__init__.py", line 18079, in add_contai
ner
    return jsii.invoke(self, "addContainer", [id, props])
  File "/Users/vrut/dev/praim/iac/wiki/.venv/lib/python3.9/site-packages/jsii/_kernel/__init__.py", line 125, in wrapped
    return _recursize_dereference(kernel, fn(kernel, *args, **kwargs))
  File "/Users/vrut/dev/praim/iac/wiki/.venv/lib/python3.9/site-packages/jsii/_kernel/__init__.py", line 315, in invoke
    response = self.provider.invoke(
  File "/Users/vrut/dev/praim/iac/wiki/.venv/lib/python3.9/site-packages/jsii/_kernel/providers/process.py", line 362, in invoke
    return self._process.send(request, InvokeResponse)
  File "/Users/vrut/dev/praim/iac/wiki/.venv/lib/python3.9/site-packages/jsii/_kernel/providers/process.py", line 332, in send
    raise JSIIError(resp.error) from JavaScriptError(resp.stack)
jsii.errors.JSIIError: Expected a string, got -1.88815458970879e+289 (number)
Subprocess exited with error 1

cdk --version
1.80.0 (build 31132ca)

node -v
v12.16.0

python --version
Python 3.9.1
```

--- 

This is :bug: Bug Report

**Comment by skinny85** [comment]
Hey @brugnara ,

don't worry about the values here, these are so-called Tokens (more extensive explanation: https://docs.aws.amazon.com/cdk/latest/guide/tokens.html ).

What you want is to convert your number Token into a String:

```python
containerImage = ecs.ContainerImage.from_registry("requarks/wiki:2")
container = task.add_container(
    "DockerWiki",
    image=containerImage,
    environment={
        "DB_PORT": Token.asString(dbCluster.cluster_endpoint.port),
```

Hoe this helps!

Thanks,
Adam

**Comment by brugnara** [comment]
Thanks @skinny85 !

That worked like..

![magic.gif](https://media.tenor.com/images/1fb93e098589d31f5023b7d32418f013/tenor.gif)

Could be useful, in your opinion, having the `port` value returned as a Token by default or I am missing something, maybe?

Again, thanks a million!

**Comment by skinny85** [comment]
Well, then you would get the same problem when you wanted to pass `port` somewhere a `number` was expected... you would have to do `Token.as_number(port)`.

It seems natural that `port` is a number, so at least you only have to go through the hassle of converting when you're passing it somewhere a String is expected.

I'm resolving this one, let me know if you need anything else from my side for this issue 🙂.

Thanks,
Adam
