### ISSUE TITLE
(awslint): awslint and all dependent modules builds failing

### ISSUE THREAD

**Issue by Jacob-Doetsch** [aws/aws-cdk#12303]
awslint tests check LICENSE and NOTICE for consistency in the current year, but the LICENSE and NOTICE files still have 2020 as the copyright year rather than 2021

### Reproduction Steps
reproducing in the aws-ec2 module checkout latest master, run the following in the project root
```bash
git clean -fdx
yarn
cd packages/@aws-cdk/aws-ec2
../../../scripts/buildup  # awslint checks of LICENSE and NOTICE fail since it's 2021 now
```
Every module is probably affected because they presumably all rely on awslint

### What did you expect to happen?
Expected buildup script against aws-ec2 to complete successfully against master

### What actually happened?
buildup script fails due to awslint checking LICENSE and NOTICE files and out-of-date copyrights
```
In package package.json
- [license/license-file] LICENSE should contain exactly '                                 Apache License
                           Version 2.0, January 2004
                        http://www.apache.org/licenses/

   TERMS AND CONDITIONS FOR USE, REPRODUCTION, AND DISTRIBUTION

   1. Definitions.
...omitted...
   distributed under the License is distributed on an "AS IS" BASIS,
   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
   See the License for the specific language governing permissions and
   limitations under the License.
' (fixable)
```
```
[license/notice-file] NOTICE does NOT begin with AWS Cloud Development Kit (AWS CDK),Copyright 2018-2021 Amazon.com, Inc. or its affiliates. All Rights Reserved.,'
Error: Some package.json files had errors
    at main (/home/jake/aws-cdk/tools/pkglint/bin/pkglint.js:26:15)
    at Object.<anonymous> (/home/jake/aws-cdk/tools/pkglint/bin/pkglint.js:29:1)
    at Module._compile (node:internal/modules/cjs/loader:1102:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1131:10)
    at Module.load (node:internal/modules/cjs/loader:967:32)
    at Function.Module._load (node:internal/modules/cjs/loader:807:14)
    at Module.require (node:internal/modules/cjs/loader:991:19)
    at require (node:internal/modules/cjs/helpers:92:18)
    at Object.<anonymous> (/home/jake/aws-cdk/tools/pkglint/bin/pkglint:2:1)
    at Module._compile (node:internal/modules/cjs/loader:1102:14)
npm ERR! code 1
npm ERR! path /home/jake/aws-cdk/packages/awslint
npm ERR! command failed
npm ERR! command sh -c eslint . --ext=.ts && pkglint
```

### Environment

  - **CDK CLI Version  :** v1.81.0
  - **Framework Version:** v1.81.0
  - **Node.js Version:** v15.2.1
  - **OS               :** Ubuntu (WSL)
  - **Language (Version):** TypeScript, JavaScript (haven't tested others)

### Other
Proposed fix at https://github.com/aws/aws-cdk/pull/12304
Updating the LICENSE and NOTICE files from 2020 to 2021 solves the issue.

--- 

This is :bug: Bug Report

**Comment by Jacob-Doetsch** [comment]
Resolved by https://github.com/aws/aws-cdk/pull/12314
