### ISSUE TITLE
Java ECS: Container with only UDP mapping throws exceptions because there's no TCP port

### ISSUE THREAD

**Issue by stijnvanpoucke** [aws/aws-cdk#12371]
### The Question
I want to create a portmapping using UDP

              
      ContainerDefinition xRayContainerDefinition = ContainerDefinition.Builder
              .create(this, "xray-deamon")
              .taskDefinition(taskDefinition)
              .cpu(128)
              .memoryLimitMiB(256)
              .image(xRayImage)
              .build();
      
      PortMapping xRayPortMapping = PortMapping.builder()
              .containerPort(2000)
              .protocol(Protocol.UDP)
              .build();
      xRayContainerDefinition.addPortMappings(xRayPortMapping);

but I receive an exception because there's no TCP mapping

### Environment

  - **CDK CLI Version:** 1.82.0
  - **Module Version:** software.amazon.awscdk:ecs:1.82.0, core:1.82.0, ...
  - **Node.js Version:** v12.18.1
  - **OS:** macOS High Sierra
  - **Language (Version):** Java (8)

### Other information
*Stack Trace*
`> Task :run
Exception in thread "main" software.amazon.jsii.JsiiException: Container 'a-service-infra-nonprod-stack/xray-deamon' has no mapping for port undefined and protocol tcp. Did you call "container.addPortMappings()"?
Error: Container 'a-service-infra-nonprod-stack/xray-deamon' has no mapping for port undefined and protocol tcp. Did you call "container.addPortMappings()"?
    at FargateTaskDefinition._validateTarget (/private/var/folders/mh/wd307pvn6pg009r2g3pw0j0mk3jmc0/T/jsii-kernel-vHCbKp/node_modules/@aws-cdk/aws-ecs/lib/base/task-definition.js:168:19)
    at FargateService.loadBalancerTarget (/private/var/folders/mh/wd307pvn6pg009r2g3pw0j0mk3jmc0/T/jsii-kernel-vHCbKp/node_modules/@aws-cdk/aws-ecs/lib/base/base-service.js:223:44)
    at FargateService.get defaultLoadBalancerTarget [as defaultLoadBalancerTarget] (/private/var/folders/mh/wd307pvn6pg009r2g3pw0j0mk3jmc0/T/jsii-kernel-vHCbKp/node_modules/@aws-cdk/aws-ecs/lib/base/base-service.js:465:21)
    at FargateService.attachToApplicationTargetGroup (/private/var/folders/mh/wd307pvn6pg009r2g3pw0j0mk3jmc0/T/jsii-kernel-vHCbKp/node_modules/@aws-cdk/aws-ecs/lib/base/base-service.js:188:21)
    at ApplicationTargetGroup.addTarget (/private/var/folders/mh/wd307pvn6pg009r2g3pw0j0mk3jmc0/T/jsii-kernel-vHCbKp/node_modules/@aws-cdk/aws-elasticloadbalancingv2/lib/alb/application-target-group.js:64:35)
    at /private/var/folders/mh/wd307pvn6pg009r2g3pw0j0mk3jmc0/T/jsii-java-runtime8203345414453370292/jsii-runtime.js:3380:51
    at Kernel._wrapSandboxCode (/private/var/folders/mh/wd307pvn6pg009r2g3pw0j0mk3jmc0/T/jsii-java-runtime8203345414453370292/jsii-runtime.js:4040:16)
    at /private/var/folders/mh/wd307pvn6pg009r2g3pw0j0mk3jmc0/T/jsii-java-runtime8203345414453370292/jsii-runtime.js:3380:25
    at Kernel._ensureSync (/private/var/folders/mh/wd307pvn6pg009r2g3pw0j0mk3jmc0/T/jsii-java-runtime8203345414453370292/jsii-runtime.js:4017:20)
    at Kernel.invoke (/private/var/folders/mh/wd307pvn6pg009r2g3pw0j0mk3jmc0/T/jsii-java-runtime8203345414453370292/jsii-runtime.js:3379:26)
        at software.amazon.jsii.JsiiRuntime.processErrorResponse(JsiiRuntime.java:127)
        at software.amazon.jsii.JsiiRuntime.requestResponse(JsiiRuntime.java:99)
        at software.amazon.jsii.JsiiClient.callMethod(JsiiClient.java:184)
        at software.amazon.jsii.Kernel.call(Kernel.java:52)
        at software.amazon.awscdk.services.elasticloadbalancingv2.ApplicationTargetGroup.addTarget(ApplicationTargetGroup.java:74)
`

**Comment by dzonekl** [comment]
I noticed the  [ecs-extensions module](https://aws.amazon.com/blogs/containers/general-availability-amazon-ecs-service-extensions-for-aws-cdk/) , ( which helps deploying an xray sidecar) is only available as a  javascript module, java version coming soon?

**Comment by stijnvanpoucke** [comment]
The workaround was to put our other container in the same task first. Meaning defining a different container which does has a tcp port mapping before defining the UDP only container.

**Comment by peterwoodworth** [comment]
The `ecs-service-extensions` module is still only available in TS/JS. I'm glad you've been able to find a workaround!
