### ISSUE TITLE
(aws-emr): CfnSecurityConfiguration name property can not be used if not set 

### ISSUE THREAD

**Issue by JonathanTaws** [aws/aws-cdk#12419]
Using the `CfnSecurityConfiguration` resource, if the `name` property is not set, I did not find a way to reference the generated name in my stack. If I reference the `name` property as a parameter to another resource (e.g. a Lambda function taking the EMR Security configuration name as an environment variable), it is not possible to deploy the stack. To deploy the stack, I have to explicitly define the `name` property, even though it is marked as optional (cf. https://docs.aws.amazon.com/cdk/api/latest/python/aws_cdk.aws_emr/CfnSecurityConfiguration.html#aws_cdk.aws_emr.CfnSecurityConfiguration.name and https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-emr-securityconfiguration.html#cfn-emr-securityconfiguration-name) 

As an error when deploying (`cdk synth`), I get: 
```
jsii.errors.JSIIError: Got 'undefined' for non-optional instance of {"type":{"primitive":"string"}}
```

The only way I managed to get this working is to use the `ref` property of `CfnSecurityConfiguration` rather than the `name`, which gets set properly and can be referenced in my Lambda function. However I am unsure if `ref` and `name` can/could differ, which makes me uncomfortable using a different property. As context, EMR needs the `name` of the EMR Security Configuration when launching it, and there's no way to give EMR an `arn` of the EMR security configuration, as there doesn't seem to be one explicity set. 

### Reproduction Steps

In Python: 
```
emr_security_conf = emr.CfnSecurityConfiguration(
            scope=self,
            id='Security Configuration',
            security_configuration={
                "EncryptionConfiguration": {
                    "EnableInTransitEncryption": False,
                    "EnableAtRestEncryption": False,
                },
            }
        )

_lambda.Function(
            self, 'TestFunction',
            runtime=_lambda.Runtime.PYTHON_3_7,
            handler='test.handler',
            code=_lambda.Code.asset('testr'),
            environment=dict(EMR_SECURITY_CONF_NAME=emr_security_conf.name)
        )
```

### What did you expect to happen?

To be able to reference `CfnSecurityConfiguration.name` in other resources of my stack. 

### What actually happened?

```
jsii.errors.JavaScriptError: 
  Error: Got 'undefined' for non-optional instance of {"type":{"primitive":"string"}}
      at nullAndOk (/Users/Documents/Projects/TestProject/.env/lib/python3.8/site-packages/jsii/_embedded/jsii/jsii-runtime.js:4423:15)
      at Object.deserialize (/Users/Documents/Projects/TestProject/.env/lib/python3.8/site-packages/jsii/_embedded/jsii/jsii-runtime.js:3948:17)
      at Kernel._toSandbox (/Users/Documents/Projects/TestProject/.env/lib/python3.8/site-packages/jsii/_embedded/jsii/jsii-runtime.js:3531:61)
      at /Users/Documents/Projects/TestProject/.env/lib/python3.8/site-packages/jsii/_embedded/jsii/jsii-runtime.js:4093:74
      at mapValues (/Users/Documents/Projects/TestProject/.env/lib/python3.8/site-packages/jsii/_embedded/jsii/jsii-runtime.js:4450:27)
      at Object.deserialize (/Users/Documents/Projects/TestProject/.env/lib/python3.8/site-packages/jsii/_embedded/jsii/jsii-runtime.js:4093:28)
      at Kernel._toSandbox (/Users/Documents/Projects/TestProject/.env/lib/python3.8/site-packages/jsii/_embedded/jsii/jsii-runtime.js:3531:61)
      at /Users/Documents/Projects/TestProject/.env/lib/python3.8/site-packages/jsii/_embedded/jsii/jsii-runtime.js:4178:29
      at mapValues (/Users/Documents/Projects/TestProject/.env/lib/python3.8/site-packages/jsii/_embedded/jsii/jsii-runtime.js:4450:27)
      at Object.deserialize (/Users/Documents/Projects/TestProject/.env/lib/python3.8/site-packages/jsii/_embedded/jsii/jsii-runtime.js:4174:20)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "app-local.py", line 32, in <module>
    TestStack(
  File "/Users/Documents/Projects/TestProject/.env/lib/python3.8/site-packages/jsii/_runtime.py", line 69, in __call__
    inst = super().__call__(*args, **kwargs)
  File "/Users/Documents/Projects/TestProject/core_stack.py", line 394, in __init__
    account_score_launcher = LauncherConstruct(
  File "/Users/Documents/Projects/TestProject/.env/lib/python3.8/site-packages/jsii/_runtime.py", line 69, in __call__
    inst = super().__call__(*args, **kwargs)
  File "/Users/Documents/Projects/TestProject/launcher_construct.py", line 19, in __init__
    self._handler = _lambda.Function(
  File "/Users/Documents/Projects/TestProject/.env/lib/python3.8/site-packages/jsii/_runtime.py", line 69, in __call__
    inst = super().__call__(*args, **kwargs)
  File "/Users/Documents/Projects/TestProject/.env/lib/python3.8/site-packages/aws_cdk/aws_lambda/__init__.py", line 12199, in __init__
    jsii.create(Function, self, [scope, id, props])
  File "/Users/Documents/Projects/TestProject/.env/lib/python3.8/site-packages/jsii/_kernel/__init__.py", line 250, in create
    response = self.provider.create(
  File "/Users/Documents/Projects/TestProject/.env/lib/python3.8/site-packages/jsii/_kernel/providers/process.py", line 347, in create
    return self._process.send(request, CreateResponse)
  File "/Users/Documents/Projects/TestProject/.env/lib/python3.8/site-packages/jsii/_kernel/providers/process.py", line 332, in send
    raise JSIIError(resp.error) from JavaScriptError(resp.stack)
jsii.errors.JSIIError: Got 'undefined' for non-optional instance of {"type":{"primitive":"string"}}
```

### Environment

  - **CDK CLI Version  :**  1.80.0 (build 31132ca)
  - **Framework Version:** 
  - **Node.js Version:**  v13.8.0
  - **OS               :** MacOS 
  - **Language (Version):**  Python 3.8.1

### Other

--- 

This is :bug: Bug Report

**Comment by iliapolo** [comment]
@JonathanTaws 

> The only way I managed to get this working is to use the ref property of CfnSecurityConfiguration rather than the name

Yes, this is the correct way of referencing the name that CloudFormation generates on your behalf. From their [documentation](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-emr-securityconfiguration.html#aws-resource-emr-securityconfiguration-return-values):

> When you pass the logical ID of this resource to the intrinsic Ref function, Ref returns returns the security configuration name, such as mySecurityConfiguration.

The reason you get `undefined` when accessing `.name` is because this represents the name passed in the configuration during initialization, and not the deployed value. 

This is a common pattern and confusion with L1 resources, and we are trying to address it to make it clearer, but you can feel perfectly comfortable using `.ref`.

**Comment by JonathanTaws** [comment]
> @JonathanTaws
> 
> > The only way I managed to get this working is to use the ref property of CfnSecurityConfiguration rather than the name
> 
> Yes, this is the correct way of referencing the name that CloudFormation generates on your behalf. From their [documentation](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-emr-securityconfiguration.html#aws-resource-emr-securityconfiguration-return-values):
> 
> > When you pass the logical ID of this resource to the intrinsic Ref function, Ref returns returns the security configuration name, such as mySecurityConfiguration.
> 
> The reason you get `undefined` when accessing `.name` is because this represents the name passed in the configuration during initialization, and not the deployed value.
> 
> This is a common pattern and confusion with L1 resources, and we are trying to address it to make it clearer, but you can feel perfectly comfortable using `.ref`.

Thanks for pointing the documentation out, I missed the part at the bottom on the `Ref` - this is helpful and confirms `ref` is the right method to use. Would be great to have this also part of the docs in the CDK as you mentioned.
