### ISSUE TITLE
(core): Cross Reference Stack variable fails on deployment due to incorrectly rendered CfnOutput.value

### ISSUE THREAD

**Issue by NukaCody** [aws/aws-cdk#12523]
When sharing a member variable across stacks, it fails if any attributes return a non-string value. For example, if I export [Active Directory attrDnsIPAddresses](https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-directoryservice.CfnMicrosoftAD.html#attrdnsipaddresses),  which returns a `string[]`

```typescript
export class MadStack extends Stack {
  public madDomains: string[]

  constructor(scope: Construct, id: string, props: MadStackProps) {
    super(scope, id, props);
    
    // ...snip

    this.madDomains = this.ad.attrDnsIpAddresses;
  }
}
```

This renders:

```json
    "ExportsOutputFnGetAttMADDnsIpAddresses4E87A825": {
      "Value": {
        "Fn::GetAtt": [
          "MAD",
          "DnsIpAddresses"
        ]
      },
      "Export": {
        "Name": "MadStack:ExportsOutputFnGetAttMADDnsIpAddresses4E87A825"
      }
    }
```

The value field only takes a string and Fn::GetAtt returns an array of strings in this case. After a manual edit, I can successfully deploy the stack.

```json
    "ExportsOutputFnGetAttMADDnsIpAddresses4E87A825": {
      "Value": {
         "Fn::Join" : [ ",", { "Fn::GetAtt": [ "MAD", "DnsIpAddresses" ] }  ]
      },
      "Export": {
        "Name": "MadStack:ExportsOutputFnGetAttMADDnsIpAddresses4E87A825"
      }
    }
```

### What I tried for workarounds

Running through a debugger, I tried to use escape hatches or manual overwrites but this `CfnOutput` node is generated after `app.synth()` is called. Which (by learning the hard way) meant that I couldn't modify the stack's `CfnOutput` node.

### Environment

  - **CDK CLI Version  :*1.84.0*
  - **Framework Version:*1.84.0*
  - **Node.js Version:*v14.15.1* 
  - **OS               :*Windows*
  - **Language (Version):*Typescript* 

### Other

Stacktrace

```bash
 ❌  MadStack failed: Error [ValidationError]: Template format error: The Value field of every Outputs member must evaluate to a String.
    at Request.extractError (C:\Users\codyj\AppData\Roaming\npm\node_modules\aws-cdk\node_modules\aws-sdk\lib\protocol\query.js:50:29)
    at Request.callListeners (C:\Users\codyj\AppData\Roaming\npm\node_modules\aws-cdk\node_modules\aws-sdk\lib\sequential_executor.js:106:20)
    at Request.emit (C:\Users\codyj\AppData\Roaming\npm\node_modules\aws-cdk\node_modules\aws-sdk\lib\sequential_executor.js:78:10)
    at Request.emit (C:\Users\codyj\AppData\Roaming\npm\node_modules\aws-cdk\node_modules\aws-sdk\lib\request.js:688:14)
    at Request.transition (C:\Users\codyj\AppData\Roaming\npm\node_modules\aws-cdk\node_modules\aws-sdk\lib\request.js:22:10)
    at AcceptorStateMachine.runTo (C:\Users\codyj\AppData\Roaming\npm\node_modules\aws-cdk\node_modules\aws-sdk\lib\state_machine.js:14:12)
    at C:\Users\codyj\AppData\Roaming\npm\node_modules\aws-cdk\node_modules\aws-sdk\lib\state_machine.js:26:10
    at Request.<anonymous> (C:\Users\codyj\AppData\Roaming\npm\node_modules\aws-cdk\node_modules\aws-sdk\lib\request.js:38:9)
    at Request.<anonymous> (C:\Users\codyj\AppData\Roaming\npm\node_modules\aws-cdk\node_modules\aws-sdk\lib\request.js:690:12)
    at Request.callListeners (C:\Users\codyj\AppData\Roaming\npm\node_modules\aws-cdk\node_modules\aws-sdk\lib\sequential_executor.js:116:18) {
  code: 'ValidationError',
  time: 2021-01-15T03:09:17.580Z,
  requestId: '2d3a7a0a-9855-4efe-a791-2e349821f016',
  statusCode: 400,
  retryable: false,
  retryDelay: 595.9487603140714
}
Template format error: The Value field of every Outputs member must evaluate to a String.
```

--- 

This is :bug: Bug Report

**Comment by NukaCody** [comment]
As a workaround, I can default to traditional `CfnOutput` combined with `Fn.importValue()`


```typescript
    // Old

    this.madDomains = this.ad.attrDnsIpAddresses;
```

```typescript
    // New

    new CfnOutput(this, domainId+'1', {
      value: Fn.select(0, this.ad.attrDnsIpAddresses),
      exportName: domainId+'1',
    });

    new CfnOutput(this, domainId+'2', {
      value: Fn.select(0, this.ad.attrDnsIpAddresses),
      exportName: domainId+'2',
    });
```

The above exports and the below imports

```typescript
// Old (inside main.ts or /bin)

madStack.ad.attrDnsIpAddresses
```

```typescript
// New (inside main.ts or /bin)
const domains = [
  Fn.importValue(config.domainId+'1'),
  Fn.importValue(config.domainId+'2'),
];
```

**Comment by rix0rrr** [comment]
Why don't you:

```ts
    new CfnOutput(this, 'Domain', {
      value: Fn.join(',', this.ad.attrDnsIpAddresses),
      exportName: 'Domains',
    });
```

And

```ts
const importList = Fn.split(',', Fn.importValue('Domains'));
const domains = [
  Fn.select(0, importList),
  Fn.select(1, importList),
];
```

?

**Comment by NukaCody** [comment]
@rix0rrr Both work, but it doesn't address the original issue. The documentation says that CDK generates CfnOutput and Import's for you when you follow this pattern (https://docs.aws.amazon.com/cdk/latest/guide/resources.html#resource_stack)

```typescript
export class MadStack extends Stack {
  public madDomains: string[]

  constructor(scope: Construct, id: string, props: MadStackProps) {
    super(scope, id, props);
    
    // ...snip

    this.madDomains = this.ad.attrDnsIpAddresses;
  }
}

// Use the member elsewhere
MadStack.madDomains
```

But it doesn't account for items that return multiple values in a array like `this.ad.attrDnsIpAddresses.` At the very least, the documentation should address this edge case. Just to save someone from hours of debugging trying to figure out `[ValidationError]: Template format error: The Value field of every Outputs member must evaluate to a String.` could potentially refer to this limitation.
