### ISSUE TITLE
(cdk-pipelines): Asset manifest paths for Assets build use backslash when deployed from a Windows machine

### ISSUE THREAD

**Issue by aax** [aws/aws-cdk#12540]
When I deploy my simplistic CdkPipeline with an ApplicationStage from a Windows machine, the generated buildspec for the Assets codebuild project contains Windows-paths with backslashes to reference the asset manifest files from the cloud assembly artefact. This crashes when run in CodeBuild because a Linux image is used. See below the generated buildspec taken from the CodeBuild console.

### Reproduction Steps

```
app = core.App()

pipeline = CdkPipeline(
    app, "Pipeline",
    cloud_assembly_artifact=cloud_assembly_artifact,
    source_action=...,
    synth_action=...
 )
pipeline.add_application_stage(SomeApplicationStageWithAssets(...))

app.synth()
```

### What did you expect to happen?

When deployed and the CodePipeline is triggered, it should run through all the steps (source, build, assets, application).

### What actually happened?

Error message in CodeBuild logs:
```
[Container] 2021/01/15 16:36:26 Running command cdk-assets --path "assembly-CICDPipeline-master-Stack-ApplicationStage\CICDPipelinemasterStackApplicationStageApplication4E51AD1E.assets.json" --verbose publish "c42b69e9b4b36b7640a283f55c91b71cc9ddcf6fb218a03db53cbc54f10a5303:current_account-current_region"
--
28 | Error: Cannot read asset manifest at 'assembly-CICDPipeline-master-Stack-ApplicationStage\CICDPipelinemasterStackApplicationStageApplication4E51AD1E.assets.json': ENOENT: no such file or directory, stat 'assembly-CICDPipeline-master-Stack-ApplicationStage\CICDPipelinemasterStackApplicationStageApplication4E51AD1E.assets.json'
29 | at Function.fromPath (/usr/local/lib/node_modules/cdk-assets/lib/asset-manifest.js:38:19)
30 | at Object.publish (/usr/local/lib/node_modules/cdk-assets/bin/publish.js:8:40)
31 | at /usr/local/lib/node_modules/cdk-assets/bin/cdk-assets.js:32:25
32 | at Object.handler (/usr/local/lib/node_modules/cdk-assets/bin/cdk-assets.js:56:15)
33 | at Object.runCommand (/usr/local/lib/node_modules/cdk-assets/node_modules/yargs/build/index.cjs:446:48)
34 | at Object.parseArgs [as _parseArgs] (/usr/local/lib/node_modules/cdk-assets/node_modules/yargs/build/index.cjs:2697:57)
35 | at Object.get [as argv] (/usr/local/lib/node_modules/cdk-assets/node_modules/yargs/build/index.cjs:2651:25)
36 | at main (/usr/local/lib/node_modules/cdk-assets/bin/cdk-assets.js:43:9)
37 | at Object.<anonymous> (/usr/local/lib/node_modules/cdk-assets/bin/cdk-assets.js:59:1)
38 | at Module._compile (internal/modules/cjs/loader.js:1015:30)
```

### Environment

  - **CDK CLI Version  :** 1.85.0
  - **Framework Version:** 1.85.0
  - **Node.js Version:**  v15.5.0
  - **OS               :** Windows 10
  - **Language (Version):**  Python

### Other

The generated buildspec for the assets step of the pipeline (note the backslash in the path given to cdk-assets):
```
{
  "version": "0.2",
  "phases": {
    "install": {
      "commands": "npm install -g cdk-assets"
    },
    "build": {
      "commands": [
        "cdk-assets --path \"assembly-CICDPipeline-master-Stack-ApplicationStage\\CICDPipelinemasterStackApplicationStageApplication4E51AD1E.assets.json\" --verbose publish \"c42b69e9b4b36b7640a283f55c91b71cc9ddcf6fb218a03db53cbc54f10a5303:current_account-current_region\""
      ]
    }
  }
}
```

--- 

This is :bug: Bug Report

**Comment by rix0rrr** [comment]
I could have sworn I fixed this. Thanks for the report.
