### ISSUE TITLE
nodeunit: Deprecation warnings from source-map-support

### ISSUE THREAD

**Issue by eladb** [aws/aws-cdk#1256]
```
(node:3882) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
    at showFlaggedDeprecation (buffer.js:160:11)
    at new Buffer (buffer.js:175:3)
    at Array.<anonymous> (/usr/local/lib/node_modules/nodeunit/node_modules/source-map-support/source-map-support.js:149:21)
    at /usr/local/lib/node_modules/nodeunit/node_modules/source-map-support/source-map-support.js:53:24
    at mapSourcePosition (/usr/local/lib/node_modules/nodeunit/node_modules/source-map-support/source-map-support.js:171:21)
    at wrapCallSite (/usr/local/lib/node_modules/nodeunit/node_modules/source-map-support/source-map-support.js:343:20)
    at /usr/local/lib/node_modules/nodeunit/node_modules/source-map-support/source-map-support.js:378:26
    at Array.map (<anonymous>)
    at Function.prepareStackTrace (/usr/local/lib/node_modules/nodeunit/node_modules/source-map-support/source-map-support.js:377:24)
    at createStackTrace (/Users/benisrae/code/cdk-latest2/aws-cdk/packages/@aws-cdk/cdk/lib/core/construct.ts:439:15)
    at RepositoryResource.addMetadata (/Users/benisrae/code/cdk-latest2/aws-cdk/packages/@aws-cdk/cdk/lib/core/construct.ts:215:19)
    at new StackElement (/Users/benisrae/code/cdk-latest2/aws-cdk/packages/@aws-cdk/cdk/lib/cloudformation/stack.ts:335:10)
    at new Referenceable (/Users/benisrae/code/cdk-latest2/aws-cdk/packages/@aws-cdk/cdk/lib/cloudformation/stack.ts:427:1)
    at new Resource (/Users/benisrae/code/cdk-latest2/aws-cdk/packages/@aws-cdk/cdk/lib/cloudformation/resource.ts:82:5)
    at new RepositoryResource (/Users/benisrae/code/cdk-latest2/aws-cdk/packages/@aws-cdk/aws-ecr/lib/ecr.generated.ts:88:13)
    at new Repository (/Users/benisrae/code/cdk-latest2/aws-cdk/packages/@aws-cdk/aws-ecr/lib/repository.ts:54:22)
```

**Comment by fulghum** [comment]
@eladb – do you have a recommendation on this one?  Is there a new version of nodeunit that addresses this, or any other dependency options?

**Comment by eladb** [comment]
Yes. We want to move to jest across the board

**Comment by SomayaB** [comment]
Nothing actionable here other than moving to jest across the board. Closing this issue. Feel free to reopen.
