### ISSUE TITLE
(imagebuilder) Circular reference when creating simple AMI builders 

### ISSUE THREAD

**Issue by alexiswl** [aws/aws-cdk#12562]
A circular resolution error is generated when retrying to generate an AMI building pipeline. I am unable to determine what component of the cdk app has a circular dependency

### Reproduction Steps

CDK app can be found at https://github.com/umccr/aws_parallel_cluster/tree/cdk-image-builder/ami

The following steps can generate the error:

```
# Change to cdk directory from git root
cd ami

# Activate cdk venv
. .venv/bin/activate

# Run cdk ls with context parameters
cdk ls \
 --context ACCOUNT="843407916570" \
 --context REGION="ap-southeast-2" \
 --context TAGS="Key=Stack,Value=ParallelCluster" \
 --context S3_READ_ROLE="github_actions_s3" \
 --context PARENT_IMAGE="ami-04b4a20ee9f67608f" \
 --context INFRASTRUCTURE_TYPE="t2.medium" \
 --context S3_CONFIG_ROOT="s3://umccr-research-dev/parallel-cluster" \
 --context GIT_TAG="2.10.1-1.0.1"
```

### What did you expect to happen?

The cfn template to complete

### What actually happened?

```
jsii.errors.JavaScriptError:
  Error: Resolution error: Resolution error: Unable to resolve object tree with circular reference. Path: /Resources/${Token[ami.parallelClusterImageRecipe.LogicalID.75]}/Properties/components/0/node/host/node/host/node/host/node/host/node/host/node/host/node/host/
node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/
host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/
node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/
host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host..
      at resolve (/tmp/jsii-kernel-i9p0s1/node_modules/@aws-cdk/core/lib/private/resolve.js:35:15)
      at Object.resolve (/tmp/jsii-kernel-i9p0s1/node_modules/@aws-cdk/core/lib/private/resolve.js:29:33)
      at resolve (/tmp/jsii-kernel-i9p0s1/node_modules/@aws-cdk/core/lib/private/resolve.js:118:43)
      at Object.resolve (/tmp/jsii-kernel-i9p0s1/node_modules/@aws-cdk/core/lib/private/resolve.js:29:33)
      at resolve (/tmp/jsii-kernel-i9p0s1/node_modules/@aws-cdk/core/lib/private/resolve.js:118:43)
      at Object.resolve (/tmp/jsii-kernel-i9p0s1/node_modules/@aws-cdk/core/lib/private/resolve.js:29:33)
      at resolve (/tmp/jsii-kernel-i9p0s1/node_modules/@aws-cdk/core/lib/private/resolve.js:118:43)
      at Object.resolve (/tmp/jsii-kernel-i9p0s1/node_modules/@aws-cdk/core/lib/private/resolve.js:29:33)
      at resolve (/tmp/jsii-kernel-i9p0s1/node_modules/@aws-cdk/core/lib/private/resolve.js:118:43)
      at Object.resolve (/tmp/jsii-kernel-i9p0s1/node_modules/@aws-cdk/core/lib/private/resolve.js:29:33)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "app.py", line 51, in <module>
    app.synth()
  File "/c/Users/awluc/OneDrive/GitHub/UMCCR/aws_parallel_cluster/ami/.venv/lib/python3.7/site-packages/aws_cdk/core/__init__.py", line 14459, in synth
    return jsii.invoke(self, "synth", [options])
  File "/c/Users/awluc/OneDrive/GitHub/UMCCR/aws_parallel_cluster/ami/.venv/lib/python3.7/site-packages/jsii/_kernel/__init__.py", line 125, in wrapped
    return _recursize_dereference(kernel, fn(kernel, *args, **kwargs))
  File "/c/Users/awluc/OneDrive/GitHub/UMCCR/aws_parallel_cluster/ami/.venv/lib/python3.7/site-packages/jsii/_kernel/__init__.py", line 319, in invoke
    args=_make_reference_for_native(self, args),
  File "/c/Users/awluc/OneDrive/GitHub/UMCCR/aws_parallel_cluster/ami/.venv/lib/python3.7/site-packages/jsii/_kernel/providers/process.py", line 362, in invoke
    return self._process.send(request, InvokeResponse)
  File "/c/Users/awluc/OneDrive/GitHub/UMCCR/aws_parallel_cluster/ami/.venv/lib/python3.7/site-packages/jsii/_kernel/providers/process.py", line 332, in send
    raise JSIIError(resp.error) from JavaScriptError(resp.stack)
jsii.errors.JSIIError: Resolution error: Resolution error: Unable to resolve object tree with circular reference. Path: /Resources/${Token[ami.parallelClusterImageRecipe.LogicalID.75]}/Properties/components/0/node/host/node/host/node/host/node/host/node/host/node/h
ost/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/n
ode/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/h
ost/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/n
ode/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host..
/tmp/jsii-kernel-i9p0s1/node_modules/@aws-cdk/core/lib/private/refs.js:129
            throw e;
            ^

Error: Resolution error: Resolution error: Unable to resolve object tree with circular reference. Path: /Resources/${Token[ami.parallelClusterImageRecipe.LogicalID.75]}/Properties/components/0/node/host/node/host/node/host/node/host/node/host/node/host/node/host/no
de/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/ho
st/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/no
de/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/ho
st/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host..
    at resolve (/tmp/jsii-kernel-i9p0s1/node_modules/@aws-cdk/core/lib/private/resolve.js:35:15)
    at Object.resolve (/tmp/jsii-kernel-i9p0s1/node_modules/@aws-cdk/core/lib/private/resolve.js:29:33)
    at resolve (/tmp/jsii-kernel-i9p0s1/node_modules/@aws-cdk/core/lib/private/resolve.js:118:43)
    at Object.resolve (/tmp/jsii-kernel-i9p0s1/node_modules/@aws-cdk/core/lib/private/resolve.js:29:33)
    at resolve (/tmp/jsii-kernel-i9p0s1/node_modules/@aws-cdk/core/lib/private/resolve.js:118:43)
    at Object.resolve (/tmp/jsii-kernel-i9p0s1/node_modules/@aws-cdk/core/lib/private/resolve.js:29:33)
    at resolve (/tmp/jsii-kernel-i9p0s1/node_modules/@aws-cdk/core/lib/private/resolve.js:118:43)
    at Object.resolve (/tmp/jsii-kernel-i9p0s1/node_modules/@aws-cdk/core/lib/private/resolve.js:29:33)
    at resolve (/tmp/jsii-kernel-i9p0s1/node_modules/@aws-cdk/core/lib/private/resolve.js:118:43)
    at Object.resolve (/tmp/jsii-kernel-i9p0s1/node_modules/@aws-cdk/core/lib/private/resolve.js:29:33)
Subprocess exited with error 1
```

### Environment

  - **CDK CLI Version  :**  1.85.0 (build 5f44668)
  - **Framework Version:**  How do I determine the framework version?
  - **Node.js Version:**  v13.11.0
  - **OS               :**  WSL2 on Windows 10
  - **Language (Version):**  python 3.7.6

### Other

--- 

This is :bug: Bug Report

**Comment by skinny85** [comment]
Sorry, I was not able to reproduce the error. For me, running 

```
$ npx cdk ls \
>  --context ACCOUNT="843407916570" \
>  --context REGION="ap-southeast-2" \
>  --context TAGS="Key=Stack,Value=ParallelCluster" \
>  --context S3_READ_ROLE="github_actions_s3" \
>  --context PARENT_IMAGE="ami-04b4a20ee9f67608f" \
>  --context INFRASTRUCTURE_TYPE="t2.medium" \
>  --context S3_CONFIG_ROOT="s3://umccr-research-dev/parallel-cluster" \
>  --context GIT_TAG="2.10.1-1.0.1"
```

produces `ami` (which I believe is the name of the only Stack in the application).

I have noticed that for some reason, you freeze the version of the `aws-cdk.core` package to `1.77.0` [here](https://github.com/umccr/aws_parallel_cluster/blob/61c533f999374454dfb3a12f3cf032dd9986274a/ami/setup.py#L22-L22), while the rest of your dependencies are "latest". That's not a good idea; I would stop doing that. It could be the cause of your problems.

Thanks,
Adam

**Comment by alexiswl** [comment]
Thanks @skinny85,

Would you recommend freezing all or keeping all as latest?

**Comment by skinny85** [comment]
I'm personally a fan of freezing them all. You can do it very easily with a local variable, here's an example from a `setup.py` in one of my projects:

```python
cdk_version = '1.87.1'

setuptools.setup(
    # other properties...

    install_requires=[
        f"aws-cdk.core=={cdk_version}",
        f"aws-cdk.aws_iam=={cdk_version}",
        f"aws-cdk.aws_sqs=={cdk_version}",
        f"aws-cdk.aws_sns=={cdk_version}",
        f"aws-cdk.aws_sns_subscriptions=={cdk_version}",
        f"aws-cdk.aws_s3=={cdk_version}",
        f"aws-cdk.aws_codebuild=={cdk_version}",
        f"aws-cdk.aws_codecommit=={cdk_version}",
        f"aws-cdk.aws_codepipeline=={cdk_version}",
        f"aws-cdk.aws_codepipeline_actions=={cdk_version}",
    ],
```

**Comment by skinny85** [comment]
Then, updating is a separate commit that can be reviewed, tested, rolled back, etc.

And your builds are 100% reproducible.
