### ISSUE TITLE
(ec2): CfnVPCPeeringConnection at 'PeeringConnection' should be created in the scope of a Stack, but no Stack found

### ISSUE THREAD

**Issue by mimozell** [aws/aws-cdk#12590]
I'm unable to create a VPC peering connection.

### Reproduction Steps

```
        CfnVPCPeeringConnection.Builder.create(scope, "PeeringConnection")
            .vpcId(vpc.vpcId)
            .peerVpcId(peerVpcId)
            .peerOwnerId(props?.env?.account)
            .peerRegion(props?.env?.region)
            .tags(
                listOf(
                    CfnTag.builder()
                        .key("Name")
                        .value("Peering connection between ....")
                        .build()
                )
            )
            .build()
```
### What did you expect to happen?

I'm expecting a peering connection to be created given that I have 2 VPCs and have provided all the necessary details. I'm setting environment properties (account and region) at the stack property level, but adding them as static values to the code above made no difference (as expected). When removing the code above, the stack deployment completes successfully.

### What actually happened?

```
Exception in thread "main" software.amazon.jsii.JsiiException: CfnVPCPeeringConnection at 'PeeringConnection' should be created in the scope of a Stack, but no Stack found
Error: CfnVPCPeeringConnection at 'PeeringConnection' should be created in the scope of a Stack, but no Stack found
    at _lookup (/private/var/folders/_n/fglfzbt113s4hn2x1_btq_hr0000gn/T/jsii-kernel-uniiQn/node_modules/@aws-cdk/core/lib/stack.js:143:23)
    at _lookup (/private/var/folders/_n/fglfzbt113s4hn2x1_btq_hr0000gn/T/jsii-kernel-uniiQn/node_modules/@aws-cdk/core/lib/stack.js:145:20)
    at Function.of (/private/var/folders/_n/fglfzbt113s4hn2x1_btq_hr0000gn/T/jsii-kernel-uniiQn/node_modules/@aws-cdk/core/lib/stack.js:127:27)
    at new CfnElement (/private/var/folders/_n/fglfzbt113s4hn2x1_btq_hr0000gn/T/jsii-kernel-uniiQn/node_modules/@aws-cdk/core/lib/cfn-element.js:28:36)
    at new CfnRefElement (/private/var/folders/_n/fglfzbt113s4hn2x1_btq_hr0000gn/T/jsii-kernel-uniiQn/node_modules/@aws-cdk/core/lib/cfn-element.js:106:1)
    at new CfnResource (/private/var/folders/_n/fglfzbt113s4hn2x1_btq_hr0000gn/T/jsii-kernel-uniiQn/node_modules/@aws-cdk/core/lib/cfn-resource.js:27:9)
    at new CfnVPCPeeringConnection (/private/var/folders/_n/fglfzbt113s4hn2x1_btq_hr0000gn/T/jsii-kernel-uniiQn/node_modules/@aws-cdk/aws-ec2/lib/ec2.generated.js:13234:9)
    at /private/var/folders/_n/fglfzbt113s4hn2x1_btq_hr0000gn/T/jsii-java-runtime11183175874171433552/jsii-runtime.js:3589:49
    at Kernel._wrapSandboxCode (/private/var/folders/_n/fglfzbt113s4hn2x1_btq_hr0000gn/T/jsii-java-runtime11183175874171433552/jsii-runtime.js:4073:16)
    at Kernel._create (/private/var/folders/_n/fglfzbt113s4hn2x1_btq_hr0000gn/T/jsii-java-runtime11183175874171433552/jsii-runtime.js:3589:26)
        at software.amazon.jsii.JsiiRuntime.processErrorResponse(JsiiRuntime.java:117)
        at software.amazon.jsii.JsiiRuntime.requestResponse(JsiiRuntime.java:89)
        at software.amazon.jsii.JsiiClient.createObject(JsiiClient.java:89)
        at software.amazon.jsii.JsiiEngine.createNewObject(JsiiEngine.java:603)
        at software.amazon.awscdk.services.ec2.CfnVPCPeeringConnection.<init>(CfnVPCPeeringConnection.java:35)
        at software.amazon.awscdk.services.ec2.CfnVPCPeeringConnection$Builder.build(CfnVPCPeeringConnection.java:294)
       ....
```

### Environment

  - **CDK CLI Version**: 1.85.0
  - **Framework Version:**
  - **Node.js Version:**  v12.16.3
  - **OS               :** MacOS Catalina
  - **Language (Version):**  Kotlin (Java 8)

### Other

I can see that the error is coming from [here](https://github.com/aws/aws-cdk/blob/master/packages/%40aws-cdk/core/lib/stack.ts#L191), but I don't understand what is required to fix the issue.

--- 

This is :bug: Bug Report

**Comment by mimozell** [comment]
Seems like I was using scope wrong in this case. Switching to using `this` instead of `scope` fixed the issue.
        CfnVPCPeeringConnection.Builder.create(this, "PeeringConnection")
            .vpcId(vpc.vpcId)
            .peerVpcId(peerVpcId)
            .peerOwnerId(props?.env?.account)
            .peerRegion(props?.env?.region)
            .tags(
                listOf(
                    CfnTag.builder()
                        .key("Name")
                        .value("Peering connection between ....")
                        .build()
                )
            )
            .build()
