### ISSUE TITLE
(cli): duplicate section header in ~/.aws/config and ~/.aws/credentials causes "Unable to resolve AWS account"

### ISSUE THREAD

**Issue by b2jrock** [aws/aws-cdk#12781]
If you have a duplicate section header in `~/.aws/config` and `~/.aws/credentials`, cdk (for example `cdk bootstrap`) will throw a `Unable to resolve AWS account to use. It must be either configured when you define your CDK or through the environment`. This will happen regardless of how you choose to auth: environment variables, `--profile` on the command line, etc. While this is likely a misconfiguration, it's not an issue with other AWS tools(notably awscli and golang sdk) which simply ignore the duplicate sections.

When running in `-vvv` verbose mode, I see:
```Unable to determine the default AWS account: TypeError: Cannot redefine property: foo-some-profile```

It seems the keyspace is shared when parsing both files.

### Reproduction Steps
Add a section in `~/.aws/credentials`: 
```ini
[foo-some-profile]
aws_access_key_id = ASIAWexample
aws_secret_access_key = my_key
aws_session_token = my_token
```

Add a section in `~/.aws/config`:
```ini
[foo-some-profile]
region = us-west-2
```
Note: this is the misconfiguration, should be: `[profile foo-some-profile]`

`cdk bootstrap` in a cdk project or any cdk command that requires auth.

### What did you expect to happen?
I expected the behavior to match that of awscli or the golang sdk where the section is ignored. Barring that, a hint for what's gone wrong in this scenario would be useful. Perhaps a hint that something went wrong loading the config file.

### What actually happened?

```Unable to determine the default AWS account: TypeError: Cannot redefine property: foo-some-profile```

### Environment

  - **CDK CLI Version  :** 1.86.0 (build a10cfcf)
  - **Framework Version:** 1.86.0 
  - **Node.js Version:** v14.15.4
  - **OS               :** Linux a3435a72f460 4.19.121-linuxkit #1 SMP Tue Dec 1 17:50:32 UTC 2020 x86_64 GNU/Linux
  - **Language (Version):** all

### Other

```
Unable to determine the default AWS account: TypeError: Cannot redefine property: foo-some-profile
    at Function.defineProperty (<anonymous>)
    at /usr/local/share/nvm/versions/node/v14.15.4/lib/node_modules/aws-cdk/node_modules/aws-sdk/lib/shared-ini/ini-loader.js:11:14
    at Array.forEach (<anonymous>)
    at IniLoader.parseFile (/usr/local/share/nvm/versions/node/v14.15.4/lib/node_modules/aws-cdk/node_modules/aws-sdk/lib/shared-ini/ini-loader.js:8:26)
    at IniLoader.loadFrom (/usr/local/share/nvm/versions/node/v14.15.4/lib/node_modules/aws-cdk/node_modules/aws-sdk/lib/shared-ini/ini-loader.js:56:30)
    at Object.getProfilesFromSharedConfig (/usr/local/share/nvm/versions/node/v14.15.4/lib/node_modules/aws-cdk/node_modules/aws-sdk/lib/util.js:969:42)
    at ProcessCredentials.load (/usr/local/share/nvm/versions/node/v14.15.4/lib/node_modules/aws-cdk/node_modules/aws-sdk/lib/credentials/process_credentials.js:75:31)
    at ProcessCredentials.coalesceRefresh (/usr/local/share/nvm/versions/node/v14.15.4/lib/node_modules/aws-cdk/node_modules/aws-sdk/lib/credentials.js:205:12)
    at ProcessCredentials.refresh (/usr/local/share/nvm/versions/node/v14.15.4/lib/node_modules/aws-cdk/node_modules/aws-sdk/lib/credentials/process_credentials.js:163:10)
    at ProcessCredentials.get (/usr/local/share/nvm/versions/node/v14.15.4/lib/node_modules/aws-cdk/node_modules/aws-sdk/lib/credentials.js:122:12)
```

--- 

This is :bug: Bug Report

**Comment by rix0rrr** [comment]
This is not fixable for us, caused by the [aws-sdk-js](https://github.com/aws/aws-sdk-js/issues).
