### ISSUE TITLE
[aws-ecs] Error: No container named '${Token[TOKEN.129]}'. Did you call "addContainer()"?

### ISSUE THREAD

**Issue by petehanssens** [aws/aws-cdk#12875]
/Users/peter/cloudshuttle/projects/sitebud/cdk/node_modules/@aws-cdk/aws-ecs/lib/base/task-definition.ts:376
          firelensConfig: {
            ^
Error: No container named '${Token[TOKEN.129]}'. Did you call "addContainer()"?

### Reproduction Steps

Tried to deploy the following 

```
....
    const amundsenFrontend = new ecs.FargateTaskDefinition(this, 'AmundsenFrontend', {
      cpu: 1024,
      executionRole: executionRole,
      memoryLimitMiB: 4096,
      taskRole: taskRole,
    })

    amundsenFrontend.addContainer('AmundsenFrontendContainer', {
      image: ecs.ContainerImage.fromRegistry('amundsendev/amundsen-frontend'),
      logging: frontendLogging,
      // environment: {
      //   SEARCHSERVICE_BASE: '',
      //   METADATASERVICE_BASE: ''
      // }
    })
```

### What actually happened?

`
/Users/peter/cloudshuttle/projects/sitebud/cdk/node_modules/@aws-cdk/aws-ecs/lib/base/task-definition.ts:376
          firelensConfig: {
            ^
Error: No container named '${Token[TOKEN.129]}'. Did you call "addContainer()"?
    at FargateTaskDefinition._validateTarget (/Users/peter/cloudshuttle/projects/sitebud/cdk/node_modules/@aws-cdk/aws-ecs/lib/base/task-definition.ts:376:13)
    at FargateService.loadBalancerTarget (/Users/peter/cloudshuttle/projects/sitebud/cdk/node_modules/@aws-cdk/aws-ecs/lib/base/base-service.ts:449:40)
    at new FargateStack (/Users/peter/cloudshuttle/projects/sitebud/cdk/lib/fargate.ts:155:28)
    at Object.<anonymous> (/Users/peter/cloudshuttle/projects/sitebud/cdk/bin/cdk.ts:18:1)
    at Module._compile (node:internal/modules/cjs/loader:1108:14)
    at Module.m._compile (/Users/peter/cloudshuttle/projects/sitebud/cdk/node_modules/ts-node/src/index.ts:1056:23)
    at Module._extensions..js (node:internal/modules/cjs/loader:1137:10)
    at Object.require.extensions.<computed> [as .ts] (/Users/peter/cloudshuttle/projects/sitebud/cdk/node_modules/ts-node/src/index.ts:1059:12)
    at Module.load (node:internal/modules/cjs/loader:973:32)
    at Function.Module._load (node:internal/modules/cjs/loader:813:14)
npm ERR! code 1
npm ERR! path /Users/peter/cloudshuttle/projects/sitebud/cdk
npm ERR! command failed
npm ERR! command sh -c ts-node "--prefer-ts-exts" "bin/cdk.ts"

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/peter/.npm/_logs/2021-02-04T22_33_57_775Z-debug.log
Subprocess exited with error 1
`

### Environment

  - **CDK CLI Version  : 1.87.1 (build 9eeaa93)
  - **Framework Version:**
  - **Node.js Version: v15.5.0
  - **OS               :       System Version: macOS 11.1 (20C69)
      Kernel Version: Darwin 20.2.0
      Boot Volume: Macintosh HD
      Boot Mode: Normal
  - **Language (Version): Typescript (1.88.0)

--- 

This is :bug: Bug Report

**Comment by SoManyHs** [comment]
Hi @petehanssens,

Are you using firelens ? Would you mind including the rest of your stack, or at least the bit where `frontendLogging` is being defined?

Thanks!
