### ISSUE TITLE
(aws_wafv2): Can't synthesize simple WebACL with visibility_config

### ISSUE THREAD

**Issue by corvax19** [aws/aws-cdk#12933]
Hi,

Can't synthesize stack of simple WebACL with visibility_config specified.

### Reproduction Steps

app.py:
```
#!/usr/bin/env python3

from aws_cdk import core
from aws_cdk import aws_wafv2 as wafv2

app = core.App()
webACL = wafv2.CfnWebACL(app, "WebACL",
    default_action=wafv2.CfnWebACL.DefaultActionProperty.allow,
    scope='REGIONAL',
    visibility_config = wafv2.CfnWebACL.VisibilityConfigProperty(
      metric_name = "MyMetric",
      sampled_requests_enabled = True,
      cloud_watch_metrics_enabled = True
    )
)
```

cdk.json:
```
{
  "app": "python3 app.py",
  "versionReporting": false,
  "context": {
      "@aws-cdk/core:enableStackNameDuplicates": "true",
      "aws-cdk:enableDiffNoFail": "true",
      "@aws-cdk/core:stackRelativeExports": "true"
  }
}
```

### What did you expect to happen?

I expect the stack to synthesize without error.

### What actually happened?

Synthesize fails with following error:
```
(venv) corvax19@mbpro15 cdk-waf-bug % cdk synthesize
Traceback (most recent call last):
  File "app.py", line 18, in <module>
    cloud_watch_metrics_enabled = True
  File "/Users/corvax19/cdk-waf-bug/venv/lib/python3.7/site-packages/jsii/_runtime.py", line 83, in __call__
    inst = super().__call__(*args, **kwargs)
  File "/Users/corvax19/cdk-waf-bug/venv/lib/python3.7/site-packages/aws_cdk/aws_wafv2/__init__.py", line 2989, in __init__
    jsii.create(CfnWebACL, self, [scope_, id, props])
  File "/Users/corvax19/cdk-waf-bug/venv/lib/python3.7/site-packages/jsii/_kernel/__init__.py", line 268, in create
    args=_make_reference_for_native(self, args),
  File "/Users/corvax19/cdk-waf-bug/venv/lib/python3.7/site-packages/jsii/_kernel/__init__.py", line 141, in _make_reference_for_native
    return [_make_reference_for_native(kernel, i) for i in d]
  File "/Users/corvax19/cdk-waf-bug/venv/lib/python3.7/site-packages/jsii/_kernel/__init__.py", line 141, in <listcomp>
    return [_make_reference_for_native(kernel, i) for i in d]
  File "/Users/corvax19/cdk-waf-bug/venv/lib/python3.7/site-packages/jsii/_kernel/__init__.py", line 158, in _make_reference_for_native
    for python_name, jsii_name in mapping.items()
  File "/Users/corvax19/cdk-waf-bug/venv/lib/python3.7/site-packages/jsii/_kernel/__init__.py", line 158, in <dictcomp>
    for python_name, jsii_name in mapping.items()
  File "/Users/corvax19/cdk-waf-bug/venv/lib/python3.7/site-packages/jsii/_kernel/__init__.py", line 174, in _make_reference_for_native
    kernel.create(d.__class__, d)
  File "/Users/corvax19/cdk-waf-bug/venv/lib/python3.7/site-packages/jsii/_kernel/__init__.py", line 267, in create
    fqn=klass.__jsii_type__ or "Object",
AttributeError: type object 'property' has no attribute '__jsii_type__'
Subprocess exited with error 1

```

### Environment

  - **CDK CLI Version  :**
```
(venv) corvax19@mbpro15 cdk-waf-bug % cdk --version
1.88.0 (build f65009b)
```
  - **Framework Version:**
```
(venv) corvax19@mbpro15 cdk-waf-bug % pip3 freeze
attrs==20.3.0
aws-cdk.assets==1.88.0
aws-cdk.aws-applicationautoscaling==1.88.0
aws-cdk.aws-autoscaling==1.88.0
aws-cdk.aws-autoscaling-common==1.88.0
aws-cdk.aws-certificatemanager==1.88.0
aws-cdk.aws-cloudformation==1.88.0
aws-cdk.aws-cloudtrail==1.88.0
aws-cdk.aws-cloudwatch==1.88.0
aws-cdk.aws-cloudwatch-actions==1.88.0
aws-cdk.aws-codeguruprofiler==1.88.0
aws-cdk.aws-ec2==1.88.0
aws-cdk.aws-ecr==1.88.0
aws-cdk.aws-ecr-assets==1.88.0
aws-cdk.aws-efs==1.88.0
aws-cdk.aws-elasticloadbalancing==1.88.0
aws-cdk.aws-elasticloadbalancingv2==1.88.0
aws-cdk.aws-events==1.88.0
aws-cdk.aws-iam==1.88.0
aws-cdk.aws-kms==1.88.0
aws-cdk.aws-lambda==1.88.0
aws-cdk.aws-logs==1.88.0
aws-cdk.aws-resourcegroups==1.88.0
aws-cdk.aws-route53==1.88.0
aws-cdk.aws-s3==1.88.0
aws-cdk.aws-s3-assets==1.88.0
aws-cdk.aws-sam==1.88.0
aws-cdk.aws-secretsmanager==1.88.0
aws-cdk.aws-sns==1.88.0
aws-cdk.aws-sns-subscriptions==1.88.0
aws-cdk.aws-sqs==1.88.0
aws-cdk.aws-ssm==1.88.0
aws-cdk.aws-wafv2==1.88.0
aws-cdk.cloud-assembly-schema==1.88.0
aws-cdk.core==1.88.0
aws-cdk.custom-resources==1.88.0
aws-cdk.cx-api==1.88.0
aws-cdk.region-info==1.88.0
cattrs==1.1.2
cdk-ec2-key-pair==2.1.1
cdk-iam-floyd==0.112.1
constructs==3.3.16
jsii==1.20.1
publication==0.0.3
python-dateutil==2.8.1
six==1.15.0
typing-extensions==3.7.4.3
```

  - **Node.js Version:** 
```
(venv) corvax19@RK-veloce-mbpro15 cdk-waf-bug % node --version
v12.16.1
```

  - **OS               :**
macOS 11.2 (20D64)

  - **Language (Version):** 
```
(venv) corvax19@mbpro15 cdk-waf-bug % python -V
Python 3.7.3
```

### Other

--- 

This is :bug: Bug Report

**Comment by njlynch** [comment]
Same issue as #7841 (and I suspect #11611).

https://docs.aws.amazon.com/cdk/api/latest/python/aws_cdk.aws_wafv2/CfnWebACL.html#defaultactionproperty

Change your default_action line to this:
```python
default_action=wafv2.CfnWebACL.DefaultActionProperty(allow={}),
```

That should solve the issue. If not, please feel free to re-open.
