### ISSUE TITLE
(HttpApi): cannot addRoutes with HttpProxyIntegration

### ISSUE THREAD

**Issue by dnltsk** [aws/aws-cdk#12950]
The [example code](https://docs.aws.amazon.com/cdk/api/latest/docs/aws-apigatewayv2-integrations-readme.html#http-proxy) regarding `HttpApi` and  `HttpProxyIntegration` fails due to
```
TS2322: Type 'HttpProxyIntegration' is not assignable to type 'IHttpRouteIntegration'.
```

### Reproduction Steps
```typescript

import { HttpApi, HttpMethod } from '@aws-cdk/aws-apigatewayv2';
import { HttpProxyIntegration } from "@aws-cdk/aws-apigatewayv2-integrations";

const booksIntegration = new HttpProxyIntegration({
  url: 'https://get-books-proxy.myproxy.internal',
});

const httpApi = new HttpApi(this, 'HttpApi');

httpApi.addRoutes({
  path: "/books",
  methods: [ HttpMethod.GET ],
  integration: booksIntegration  // <- breaks due to "Type 'HttpProxyIntegration' is not assignable to type 'IHttpRouteIntegration'"
});
```
### What did you expect to happen?

That the code works fine ;-)

### What actually happened?

Executing the code by executing `cdk list` for instance. throws the following error stack:
```
/Users/.../cdk/node_modules/ts-node/src/index.ts:434
    return new TSError(diagnosticText, diagnosticCodes)
           ^
TSError: ⨯ Unable to compile TypeScript:
lib/report-api-frontend-stack.ts:84:7 - error TS2322: Type 'HttpProxyIntegration' is not assignable to type 'IHttpRouteIntegration'.
  Types of property 'bind' are incompatible.
    Type '(_: HttpRouteIntegrationBindOptions) => HttpRouteIntegrationConfig' is not assignable to type '(options: HttpRouteIntegrationBindOptions) => HttpRouteIntegrationConfig'.
      Types of parameters '_' and 'options' are incompatible.
        Type 'import("/Users/.../cdk/node_modules/@aws-cdk/aws-apigatewayv2/lib/http/integration").HttpRouteIntegrationBindOptions' is not assignable to type 'import("/Users/.../cdk/node_modules/@aws-cdk/aws-apigatewayv2-integrations/node_modules/@aws-cdk/aws-apigatewayv2/lib/http/integration").HttpRouteIntegrationBindOptions'.
          The types of 'route.httpApi.defaultStage' are incompatible between these types.
            Type 'import("/Users/.../cdk/node_modules/@aws-cdk/aws-apigatewayv2/lib/http/stage").HttpStage | undefined' is not assignable to type 'import("/Users/.../cdk/node_modules/@aws-cdk/aws-apigatewayv2-integrations/node_modules/@aws-cdk/aws-apigatewayv2/lib/http/stage").HttpStage | undefined'.
              Type 'import("/Users/.../cdk/node_modules/@aws-cdk/aws-apigatewayv2/lib/http/stage").HttpStage' is not assignable to type 'import("/Users/.../cdk/node_modules/@aws-cdk/aws-apigatewayv2-integrations/node_modules/@aws-cdk/aws-apigatewayv2/lib/http/stage").HttpStage'.
                Types have separate declarations of a private property 'httpApi'.

84       integration: booksIntegration
         ~~~~~~~~~~~

  node_modules/@aws-cdk/aws-apigatewayv2/lib/http/route.d.ts:130:14
    130     readonly integration: IHttpRouteIntegration;
                     ~~~~~~~~~~~
    The expected type comes from property 'integration' which is declared here on type 'AddRoutesOptions'

    at createTSError (/Users/.../cdk/node_modules/ts-node/src/index.ts:434:12)
    at reportTSError (/Users/.../cdk/node_modules/ts-node/src/index.ts:438:19)
    at getOutput (/Users/.../cdk/node_modules/ts-node/src/index.ts:578:36)
    at Object.compile (.../cdk/node_modules/ts-node/src/index.ts:775:32)
    at Module.m._compile (/Users/.../cdk/node_modules/ts-node/src/index.ts:858:43)
    at Module._extensions..js (internal/modules/cjs/loader.js:1167:10)
    at Object.require.extensions.<computed> [as .ts] (/Users/.../cdk/node_modules/ts-node/src/index.ts:861:12)
    at Module.load (internal/modules/cjs/loader.js:996:32)
    at Function.Module._load (internal/modules/cjs/loader.js:896:14)
    at Module.require (internal/modules/cjs/loader.js:1036:19)
Subprocess exited with error 1
```

### Environment

  - **CDK CLI Version  :** 1.88.0 (build f65009b)
  - **Framework Version:** 1.88.0 
  - **Node.js Version:** v13.12.0
  - **OS               :** Mac 11.2 (20D64)
  - **Language (Version):** TypeScript (3.9.7)

--- 

This is :bug: Bug Report

**Comment by nija-at** [comment]
`HttpIntegration` **is** of the type `IHttpRouteIntegration`. The [documentation](https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-apigatewayv2-integrations.HttpProxyIntegration.html) says so and so does the [code](https://github.com/aws/aws-cdk/blob/b92188d0021c8bff8b0a17fd161a19896834e293/packages/%40aws-cdk/aws-apigatewayv2-integrations/lib/http/http-proxy.ts#L29).

I suspect you've somehow pulled in different versions of CDK packages. Can you check the actual version of `@aws-cdk/aws-apigatewayv2` and `@aws-cdk/aws-apigatewayv2-integrations` in your `package.json` or `yarn.lock` files.
They MUST be the same.

**Comment by dnltsk** [comment]
Your're right. 
Everything now works fine after I run `npx npkill`. 
Thanks for your comment.
