### ISSUE TITLE
(apigatewayv2): Regression in 1.87.0

### ISSUE THREAD

**Issue by hoegertn** [aws/aws-cdk#13007]
The changes in #12528 introduced a regression when having the following setup:

ApiStack -> ChildStack with Lambda, HttpRoute, etc

By moving the instantiation of the HttpIntegration class to the `HttpApi. _addIntegration` method the scope was changed from the Route to the HttpApi object. This leads to a cyclic reference in the architecture described above.

So starting with 1.87.0 all my ApiGateway applications no longer synthesize.

### Environment

  - **Framework Version:** 1.87.0
  - **Node.js Version:** v14.15.4
  - **OS               :** macOS
  - **Language (Version):** TS

### Other

```
'myapp-backend-pipeline/myapp-backend-dev/Api' depends on 'myapp-backend-pipeline/myapp-backend-dev/Api/Config' (myapp-backend-pipeline/myapp-backend-dev/Api -> myapp-backend-pipeline/myapp-backend-dev/Api/Config/Fncors/Resource.Arn, myapp-backend-pipeline/myapp-backend-dev/Api -> myapp-backend-pipeline/myapp-backend-dev/Api/Config/Fnopenapi/Resource.Arn). Adding this dependency (myapp-backend-pipeline/myapp-backend-dev/Api/Config -> myapp-backend-pipeline/myapp-backend-dev/Api/Api/Resource/Resource.Ref) would create a cyclic reference.
Error: 'myapp-backend-pipeline/myapp-backend-dev/Api' depends on 'myapp-backend-pipeline/myapp-backend-dev/Api/Config' (myapp-backend-pipeline/myapp-backend-dev/Api -> myapp-backend-pipeline/myapp-backend-dev/Api/Config/Fncors/Resource.Arn, myapp-backend-pipeline/myapp-backend-dev/Api -> myapp-backend-pipeline/myapp-backend-dev/Api/Config/Fnopenapi/Resource.Arn). Adding this dependency (myapp-backend-pipeline/myapp-backend-dev/Api/Config -> myapp-backend-pipeline/myapp-backend-dev/Api/Api/Resource/Resource.Ref) would create a cyclic reference.
    at BackendApiImplStack._addAssemblyDependency (/Users/hoegertn/repo/myapp/backend/node_modules/@aws-cdk/core/lib/stack.ts:724:13)
    at Object.addDependency (/Users/hoegertn/repo/myapp/backend/node_modules/@aws-cdk/core/lib/deps.ts:52:20)
    at BackendApiImplStack.addDependency (/Users/hoegertn/repo/myapp/backend/node_modules/@aws-cdk/core/lib/stack.ts:479:5)
    at resolveValue (/Users/hoegertn/repo/myapp/backend/node_modules/@aws-cdk/core/lib/private/refs.ts:103:12)
    at Object.resolveReferences (/Users/hoegertn/repo/myapp/backend/node_modules/@aws-cdk/core/lib/private/refs.ts:33:24)
    at Object.prepareApp (/Users/hoegertn/repo/myapp/backend/node_modules/@aws-cdk/core/lib/private/prepare-app.ts:31:3)
    at Object.synthesize (/Users/hoegertn/repo/myapp/backend/node_modules/@aws-cdk/core/lib/private/synthesis.ts:24:3)
    at myappBackendStage.synth (/Users/hoegertn/repo/myapp/backend/node_modules/@aws-cdk/core/lib/stage.ts:188:23)
    at synthNestedAssemblies (/Users/hoegertn/repo/myapp/backend/node_modules/@aws-cdk/core/lib/private/synthesis.ts:52:13)
    at synthNestedAssemblies (/Users/hoegertn/repo/myapp/backend/node_modules/@aws-cdk/core/lib/private/synthesis.ts:54:7)
```

--- 

This is :bug: Bug Report

**Comment by hoegertn** [comment]
ping @eladb @nija-at

**Comment by NetaNir** [comment]
@hoegertn Thanks for letting us know, and for tagging the right people! Much appreciated. While we look into this - can you share a repro?

**Comment by NGL321** [comment]
Tracking in #13021

**Comment by hoegertn** [comment]
> @hoegertn Thanks for letting us know, and for tagging the right people! Much appreciated. While we look into this - can you share a repro?

https://github.com/hoegertn/httproute-regression

**Comment by nija-at** [comment]
Thanks for reporting @hoegertn. I'm looking into fixing this.

Let's continue tracking this here - https://github.com/aws/aws-cdk/issues/13021
