### ISSUE TITLE
(apigatewayv2): cyclic dependency introduced when HttpApi and Route are in different stacks

### ISSUE THREAD

**Issue by NGL321** [aws/aws-cdk#13021]
Please add your +1 👍 to let us know you have encountered this
---

### Overview:

From @hoegertn:

> The changes in #12528 introduced a regression when having the following setup:
> 
> ApiStack -> ChildStack with Lambda, HttpRoute, etc
> 
> By moving the instantiation of the HttpIntegration class to the `HttpApi. _addIntegration` method the scope was changed from the Route to the HttpApi object. This leads to a cyclic reference in the architecture described above.
> 
> So starting with 1.87.0 all my ApiGateway applications no longer synthesize.

#### Complete Error Message:
```
'myapp-backend-pipeline/myapp-backend-dev/Api' depends on 'myapp-backend-pipeline/myapp-backend-dev/Api/Config' (myapp-backend-pipeline/myapp-backend-dev/Api -> myapp-backend-pipeline/myapp-backend-dev/Api/Config/Fncors/Resource.Arn, myapp-backend-pipeline/myapp-backend-dev/Api -> myapp-backend-pipeline/myapp-backend-dev/Api/Config/Fnopenapi/Resource.Arn). Adding this dependency (myapp-backend-pipeline/myapp-backend-dev/Api/Config -> myapp-backend-pipeline/myapp-backend-dev/Api/Api/Resource/Resource.Ref) would create a cyclic reference.
Error: 'myapp-backend-pipeline/myapp-backend-dev/Api' depends on 'myapp-backend-pipeline/myapp-backend-dev/Api/Config' (myapp-backend-pipeline/myapp-backend-dev/Api -> myapp-backend-pipeline/myapp-backend-dev/Api/Config/Fncors/Resource.Arn, myapp-backend-pipeline/myapp-backend-dev/Api -> myapp-backend-pipeline/myapp-backend-dev/Api/Config/Fnopenapi/Resource.Arn). Adding this dependency (myapp-backend-pipeline/myapp-backend-dev/Api/Config -> myapp-backend-pipeline/myapp-backend-dev/Api/Api/Resource/Resource.Ref) would create a cyclic reference.
    at BackendApiImplStack._addAssemblyDependency (/Users/hoegertn/repo/myapp/backend/node_modules/@aws-cdk/core/lib/stack.ts:724:13)
    at Object.addDependency (/Users/hoegertn/repo/myapp/backend/node_modules/@aws-cdk/core/lib/deps.ts:52:20)
    at BackendApiImplStack.addDependency (/Users/hoegertn/repo/myapp/backend/node_modules/@aws-cdk/core/lib/stack.ts:479:5)
    at resolveValue (/Users/hoegertn/repo/myapp/backend/node_modules/@aws-cdk/core/lib/private/refs.ts:103:12)
    at Object.resolveReferences (/Users/hoegertn/repo/myapp/backend/node_modules/@aws-cdk/core/lib/private/refs.ts:33:24)
    at Object.prepareApp (/Users/hoegertn/repo/myapp/backend/node_modules/@aws-cdk/core/lib/private/prepare-app.ts:31:3)
    at Object.synthesize (/Users/hoegertn/repo/myapp/backend/node_modules/@aws-cdk/core/lib/private/synthesis.ts:24:3)
    at myappBackendStage.synth (/Users/hoegertn/repo/myapp/backend/node_modules/@aws-cdk/core/lib/stage.ts:188:23)
    at synthNestedAssemblies (/Users/hoegertn/repo/myapp/backend/node_modules/@aws-cdk/core/lib/private/synthesis.ts:52:13)
    at synthNestedAssemblies (/Users/hoegertn/repo/myapp/backend/node_modules/@aws-cdk/core/lib/private/synthesis.ts:54:7)
```

### Related Issues:

First reported by @hoegertn: #13007

**Comment by NGL321** [comment]
Original Issue: #13007

**Comment by hoegertn** [comment]
@NGL321 The regression is in the HttpRoute of the ApiGateway v2. Maybe you want to edit the title.

**Comment by hoegertn** [comment]
You can find a repro here: https://github.com/hoegertn/httproute-regression

**Comment by peterwoodworth** [comment]
I was able to reproduce the issue on 1.89.0 using my own code that was essentially the same as the repro @hoegertn provided

**Comment by hoegertn** [comment]
refs #13010

**Comment by nija-at** [comment]
@hoegertn already has a tentative fix - #13010. Thanks!

Do you need help with this @hoegertn? Looks like the build is failing.

**Comment by hoegertn** [comment]
Let's see. The build failure was somewhere else in the build process.

**Comment by nija-at** [comment]
Since we've had only one report in 6 days (since the latest release), I'm reducing the priority of this issue to a p1. I'll re-raise the priority if this changes substantially.

We're actively working on fixing this for the next release.

**Comment by hoegertn** [comment]
Given that it is broken since `1.87.0` this is fine for me. It only happens in multi-stack setups and not many people might do this.
