### ISSUE TITLE
(core): Dependency errors between stacks now occur

### ISSUE THREAD

**Issue by Blufe** [aws/aws-cdk#13169]
After creating a VPC, I specify that VPC and create an RDS.
It was work fine to CDK 1.89.0.
When I set the CDK to 1.90.0 and more, I got the following error. 

```
Error: 'App-Devintegrate-CI/Network' depends on 'App-Devintegrate-CI/Database' (App-Devintegrate-CI/Network -> App-Devintegrate-CI/Database/DBInstance/Resource.Endpoint.Port). Adding this dependency (App-Devintegrate-CI/Database -> App-Devintegrate-CI/Network/TapVpc/privateSubnet1/Subnet.Ref) would create a cyclic reference.
```

### Reproduction Steps

- network-stack.ts
```
import * as cdk from "@aws-cdk/core"
import * as ec2 from "@aws-cdk/aws-ec2"

export class NetworkStack extends cdk.Stack {
  public readonly vpc: ec2.Vpc
  public readonly dbConnectionGroup: ec2.SecurityGroup

  constructor(scope: cdk.Construct, id: string, props?: cdk.StackProps) {
    super(scope, id, props)

    this.vpc = new ec2.Vpc(this, "TapVpc", {
      maxAzs: 2,
      natGateways: 1,
      cidr: "10.0.0.0/16",
      subnetConfiguration: [
        {
          name: "public",
          subnetType: ec2.SubnetType.PUBLIC,
          cidrMask: 24,
        },
        {
          name: "private",
          subnetType: ec2.SubnetType.PRIVATE,
          cidrMask: 24,
        },
      ],
      enableDnsSupport: true,
      enableDnsHostnames: true,
    })

    this.dbConnectionGroup = new ec2.SecurityGroup(this, "Proxy to DB Connection", {
      securityGroupName: "ProxyToDB",
      vpc: this.vpc,
    })
  }
}
```

- database-stack.ts
```
import * as cdk from "@aws-cdk/core"
import * as ec2 from "@aws-cdk/aws-ec2"
import * as rds from "@aws-cdk/aws-rds"
import * as secrets from "@aws-cdk/aws-secretsmanager"

export interface DatabaseStackProps extends cdk.StackProps {
  readonly vpc: ec2.Vpc,
  readonly dbConnectionGroup: ec2.SecurityGroup,
}

export class DatabaseStack extends cdk.Stack {
  public readonly dbCredsSecret: secrets.Secret

  constructor(scope: cdk.Construct, id: string, props: DatabaseStackProps) {
    super(scope, id, props)

    this.dbCredsSecret = new secrets.Secret(this, "DBCredentialsSecret", {
      secretName: "RdsCredentials",
      generateSecretString: {
        secretStringTemplate: JSON.stringify({
          username: "admin",
        }),
        generateStringKey: "password",
        passwordLength: 40,
        excludePunctuation: true,
        includeSpace: false,
      },
    })

    const rdsInstance = new rds.DatabaseInstance(this, "DBInstance", {
      instanceIdentifier: "SampleDB",
      engine: rds.DatabaseInstanceEngine.mysql({
        version: rds.MysqlEngineVersion.VER_5_7_31,
      }),
      credentials: rds.Credentials.fromSecret(this.dbCredsSecret),
      databaseName: "my_database",
      parameterGroup: new rds.ParameterGroup(this, "ParameterGroup", {
        description: "SampleDBParam",
        engine: rds.DatabaseInstanceEngine.mysql({
          version: rds.MysqlEngineVersion.VER_5_7_31,
        }),
        parameters: {
          "character_set_client": "utf8mb4",
          "character_set_server": "utf8mb4",
        },
      }),
      instanceType: ec2.InstanceType.of(
        ec2.InstanceClass.T2,
        ec2.InstanceSize.MICRO
      ),
      vpc: props.vpc,
      vpcSubnets: {
        subnetType: ec2.SubnetType.PRIVATE,
      },
      securityGroups: [props.dbConnectionGroup],
      removalPolicy: cdk.RemovalPolicy.DESTROY,
      deletionProtection: false,
    })
  }
}
```

- pipeline-stack.ts
```
import * as actions from "@aws-cdk/aws-codepipeline-actions"
import * as cdk from "@aws-cdk/core"
import * as codepipeline from "@aws-cdk/aws-codepipeline"
import { CdkPipeline } from "@aws-cdk/pipelines"

import { NetworkStack } from "./network-stack"
import { DatabaseStack } from "./database-stack"

export class PipelineStack extends cdk.Stack {
  constructor(scope: cdk.Construct, id: string, props?: cdk.StackProps) {
    super(scope, id, props)

    // ...

    const pipeline = new CdkPipeline(this, "CdkPipeline", {
      cloudAssemblyArtifact,
      codePipeline,
    })

    const stage = pipeline.addStage("Prepare")

    const nwStack = new NetworkStack(this, "Network")
    const dbStack = new DatabaseStack(this, "Database", {
      vpc: nwStack.vpc,
      dbConnectionGroup: nwStack.dbConnectionGroup,
    })

    stage.addActions(
      new actions.CloudFormationCreateUpdateStackAction({
        actionName: "Network",
        stackName: `App-${envname}-Prepare-Network`,
        templatePath: cloudAssemblyArtifact.atPath(`${nwStack.artifactId}.template.json`),
        adminPermissions: true,
        runOrder: 1,
      }),
      new actions.CloudFormationCreateUpdateStackAction({
        actionName: "Database",
        stackName: `App-${envname}-Prepare-Database`,
        templatePath: cloudAssemblyArtifact.atPath(`${dbStack.artifactId}.template.json`),
        adminPermissions: true,
        runOrder: 2,
      }),
    )
  }
}
```

### What did you expect to happen?

- I'm trying to create a resource such as RDS by specifying that VPC after creating the VPC.

### What actually happened?

- New CDK version now (1.90.0 or 1.90.1) causes dependency error between Stacks.

```
$ npx cdk synth -c env=dev

/usr/local/src/app/node_modules/@aws-cdk/core/lib/stack.ts:724
  return dest;
            ^
Error: 'App-Devintegrate-CI/Network' depends on 'App-Devintegrate-CI/Database' (App-Devintegrate-CI/Network -> App-Devintegrate-CI/Database/DBInstance/Resource.Endpoint.Port). Adding this dependency (App-Devintegrate-CI/Database -> App-Devintegrate-CI/Network/TapVpc/privateSubnet1/Subnet.Ref) would create a cyclic reference.
    at DatabaseStack._addAssemblyDependency (/usr/local/src/app/node_modules/@aws-cdk/core/lib/stack.ts:724:13)
    at Object.addDependency (/usr/local/src/app/node_modules/@aws-cdk/core/lib/deps.ts:52:20)
    at DatabaseStack.addDependency (/usr/local/src/app/node_modules/@aws-cdk/core/lib/stack.ts:479:5)
    at resolveValue (/usr/local/src/app/node_modules/@aws-cdk/core/lib/private/refs.ts:100:12)
    at Object.resolveReferences (/usr/local/src/app/node_modules/@aws-cdk/core/lib/private/refs.ts:30:24)
    at Object.prepareApp (/usr/local/src/app/node_modules/@aws-cdk/core/lib/private/prepare-app.ts:31:3)
    at Object.synthesize (/usr/local/src/app/node_modules/@aws-cdk/core/lib/private/synthesis.ts:24:3)
    at App.synth (/usr/local/src/app/node_modules/@aws-cdk/core/lib/stage.ts:188:23)
    at Object.<anonymous> (/usr/local/src/app/deployments/cdk/pipeline.ts:30:5)
    at Module._compile (node:internal/modules/cjs/loader:1091:14)
npm ERR! code 1
npm ERR! path /usr/local/src/app
npm ERR! command failed
npm ERR! command sh -c ts-node "deployments/cdk/pipeline.ts"

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/{username}/.npm/_logs/2021-02-20T09_04_46_540Z-debug.log
Subprocess exited with error 1
npm ERR! code 1
npm ERR! path /usr/local/src/tver/ordering-system
npm ERR! command failed
npm ERR! command sh -c cdk "synth" "-c" "env=dev"

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/{username}/.npm/_logs/2021-02-20T09_04_46_626Z-debug.log
```

### Environment

  - **CDK CLI Version  :**
```
1.90.0 and more
```
  - **Node.js Version:** 
```
$ npm version
{
  'tver-ads-platform': '0.1.0',
  npm: '7.5.4',
  node: '15.9.0',
  v8: '8.6.395.17-node.25',
  uv: '1.41.0',
  zlib: '1.2.11',
  brotli: '1.0.9',
  ares: '1.17.1',
  modules: '88',
  nghttp2: '1.42.0',
  napi: '7',
  llhttp: '2.1.3',
  openssl: '1.1.1i',
  cldr: '37.0',
  icu: '67.1',
  tz: '2019c',
  unicode: '13.0'
}
```
  - **OS               :**
```
macOS 11.1
```
  - **Language (Version):** 
```
TypeScript 3.9.9
```

### Other

Is there a problem here?
https://github.com/aws/aws-cdk/commit/4b0abbcdc6efe2d37e2a9eee382848d2de82de5c#diff-7de7a9b97d113787b7858f507b978336c49a4c2e5637cee138800ca9fdb1eb1aL427 

--- 

This is :bug: Bug Report

**Comment by rix0rrr** [comment]
It might have been because of that change. Looks like the fact that it used to work before was an accident.

Don't create the security group in your VPC stack, create it in the database stack (or better yet -- don't create one and let the construct automatically create one for you).

**Comment by Blufe** [comment]
Oh... I see.
Thanks !!
