### ISSUE TITLE
(aws-cdk.aws-route53): setting CfnRecordSetGroup.record_sets fails

### ISSUE THREAD

**Issue by rectalogic** [aws/aws-cdk#13163]
Setting or appending to `CfnRecordSetGroup.record_sets` fails.

### Reproduction Steps

```python
        group = route53.CfnRecordSetGroup(
            self,
            "InternalPrivateDNS",
            hosted_zone_id=zone.ref,
            comment="Internal private DNS",
        )
        recordset = route53.CfnRecordSetGroup.RecordSetProperty(
            name="host.foo.aws.cureatr.com.",
            type="A",
            resource_records=["10.0.0.5"],
            ttl=300,
        )
        group.record_sets = [recordset]
```

I will attach a full repro example.

### What did you expect to happen?

I want to dynamically set or append (`group.record_sets += [recordset]`) to the list of record_sets

### What actually happened?
```
$ npx cdk synth
jsii.errors.JavaScriptError:
  Error: Value did not match any type in union: Value did not match any type in union: Expected a string, got 300 (number), Expected object reference, got {"$jsii.struct":{"fqn":"@aws-cdk/aws-route53.CfnRecordSetGroup.RecordSetProperty","data":{"name":"host.foo.aws.cureatr.com.","type":"A","aliasTarget":null,"comment":null,"failover":null,"geoLocation":null,"healthCheckId":null,"hostedZoneId":null,"hostedZoneName":null,"multiValueAnswer":null,"region":null,"resourceRecords":["10.0.0.5"],"setIdentifier":null,"ttl":300,"weight":null}}}, Expected object reference, got [{"$jsii.struct":{"fqn":"@aws-cdk/aws-route53.CfnRecordSetGroup.RecordSetProperty","data":{"name":"host.foo.aws.cureatr.com.","type":"A","aliasTarget":null,"comment":null,"failover":null,"geoLocation":null,"healthCheckId":null,"hostedZoneId":null,"hostedZoneName":null,"multiValueAnswer":null,"region":null,"resourceRecords":["10.0.0.5"],"setIdentifier":null,"ttl":300,"weight":null}}}]
      at Kernel._toSandbox (/private/var/folders/v1/y34vbhp158x18m1dqjzb57mw0001yl/T/tmp41nxhiem/lib/program.js:3079:23)
      at /private/var/folders/v1/y34vbhp158x18m1dqjzb57mw0001yl/T/tmp41nxhiem/lib/program.js:2524:159
      at Kernel._wrapSandboxCode (/private/var/folders/v1/y34vbhp158x18m1dqjzb57mw0001yl/T/tmp41nxhiem/lib/program.js:3148:24)
      at /private/var/folders/v1/y34vbhp158x18m1dqjzb57mw0001yl/T/tmp41nxhiem/lib/program.js:2524:104
      at Kernel._ensureSync (/private/var/folders/v1/y34vbhp158x18m1dqjzb57mw0001yl/T/tmp41nxhiem/lib/program.js:3129:28)
      at Kernel.set (/private/var/folders/v1/y34vbhp158x18m1dqjzb57mw0001yl/T/tmp41nxhiem/lib/program.js:2524:22)
      at KernelHost.processRequest (/private/var/folders/v1/y34vbhp158x18m1dqjzb57mw0001yl/T/tmp41nxhiem/lib/program.js:9457:36)
      at KernelHost.run (/private/var/folders/v1/y34vbhp158x18m1dqjzb57mw0001yl/T/tmp41nxhiem/lib/program.js:9420:22)
      at Immediate._onImmediate (/private/var/folders/v1/y34vbhp158x18m1dqjzb57mw0001yl/T/tmp41nxhiem/lib/program.js:9421:46)
      at processImmediate (internal/timers.js:461:21)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "app.py", line 9, in <module>
    RecordsStack(app, "records")
  File "/Users/aw/Projects/cureatr/dev/cureatr/experiments/cdk/records/.venv/lib/python3.7/site-packages/jsii/_runtime.py", line 83, in __call__
    inst = super().__call__(*args, **kwargs)
  File "/Users/aw/Projects/cureatr/dev/cureatr/experiments/cdk/records/records/records_stack.py", line 38, in __init__
    group.record_sets = [recordset]
  File "/Users/aw/Projects/cureatr/dev/cureatr/experiments/cdk/records/.venv/lib/python3.7/site-packages/aws_cdk/aws_route53/__init__.py", line 2252, in record_sets
    jsii.set(self, "recordSets", value)
  File "/Users/aw/Projects/cureatr/dev/cureatr/experiments/cdk/records/.venv/lib/python3.7/site-packages/jsii/_kernel/__init__.py", line 304, in set
    value=_make_reference_for_native(self, value),
  File "/Users/aw/Projects/cureatr/dev/cureatr/experiments/cdk/records/.venv/lib/python3.7/site-packages/jsii/_kernel/providers/process.py", line 354, in set
    return self._process.send(request, SetResponse)
  File "/Users/aw/Projects/cureatr/dev/cureatr/experiments/cdk/records/.venv/lib/python3.7/site-packages/jsii/_kernel/providers/process.py", line 330, in send
    raise JSIIError(resp.error) from JavaScriptError(resp.stack)
jsii.errors.JSIIError: Value did not match any type in union: Value did not match any type in union: Expected a string, got 300 (number), Expected object reference, got {"$jsii.struct":{"fqn":"@aws-cdk/aws-route53.CfnRecordSetGroup.RecordSetProperty","data":{"name":"host.foo.aws.cureatr.com.","type":"A","aliasTarget":null,"comment":null,"failover":null,"geoLocation":null,"healthCheckId":null,"hostedZoneId":null,"hostedZoneName":null,"multiValueAnswer":null,"region":null,"resourceRecords":["10.0.0.5"],"setIdentifier":null,"ttl":300,"weight":null}}}, Expected object reference, got [{"$jsii.struct":{"fqn":"@aws-cdk/aws-route53.CfnRecordSetGroup.RecordSetProperty","data":{"name":"host.foo.aws.cureatr.com.","type":"A","aliasTarget":null,"comment":null,"failover":null,"geoLocation":null,"healthCheckId":null,"hostedZoneId":null,"hostedZoneName":null,"multiValueAnswer":null,"region":null,"resourceRecords":["10.0.0.5"],"setIdentifier":null,"ttl":300,"weight":null}}}]
Subprocess exited with error 1
```

### Environment

  - **CDK CLI Version  :** 1.90.0 (build 7edba31)
  - **Framework Version:** 1.90.0
  - **Node.js Version:** v14.15.0
  - **OS               :** macOS 10.15.7
  - **Language (Version):** Python 3.7.9

--- 

This is :bug: Bug Report

**Comment by rectalogic** [comment]
Full repro
[records.zip](https://github.com/aws/aws-cdk/files/6012663/records.zip)

**Comment by rectalogic** [comment]
`ttl=300` needs to be `ttl="300"` in the `route53.CfnRecordSetGroup.RecordSetProperty`
