### ISSUE TITLE
(cloudfront): custom EdgeFunction aliases clash

### ISSUE THREAD

**Issue by arjunnaha** [aws/aws-cdk#13237]
When using multiple CloudFront `EdgeFunction`'s with custom aliases, the physical names conflict.

### Reproduction Steps

```typescript
import * as cloudfront from "@aws-cdk/aws-cloudfront";
import * as origins from "@aws-cdk/aws-cloudfront-origins";
import * as lambda from "@aws-cdk/aws-lambda";
import * as core from "@aws-cdk/core";
import * as iam from "@aws-cdk/aws-iam";

import { Stack, StackProps } from "@_org_/lib-infra-common";

export class EdgeLambdaStack extends Stack {
  constructor(scope: core.Construct, customProps: StackProps, stackProps: core.StackProps = {}) {
    super(scope, customProps, stackProps);

    const myFunc1 = new cloudfront.experimental.EdgeFunction(this, "MyFunction1", {
      runtime: lambda.Runtime.NODEJS_10_X,
      handler: "index.handler",
      code: lambda.Code.fromInline("return"),
    });
    myFunc1.currentVersion.addAlias("live");

    const myFunc2 = new cloudfront.experimental.EdgeFunction(this, "MyFunction2", {
      runtime: lambda.Runtime.NODEJS_10_X,
      handler: "index.handler",
      code: lambda.Code.fromInline("return"),
    });
    myFunc2.currentVersion.addAlias("live");
  }
}

```

### What did you expect to happen?
Both EdgeLambda functions would be generated with unique stack/physical names.

### What actually happened?

```
Error: There is already a Construct with name 'Aliaslive' in Stack [edge-lambda-stack-c8c09337b87f7807acc2002239aca2181ae1916d18]
    at Node.addChild (/Users/arjunnaha/Developer/_org_/web-marketing/node_modules/constructs/src/construct.ts:534:13)
    at new Node (/Users/arjunnaha/Developer/_org_/web-marketing/node_modules/constructs/src/construct.ts:75:22)
    at new ConstructNode (/Users/arjunnaha/Developer/_org_/web-marketing/node_modules/@aws-cdk/core/lib/construct-compat.ts:277:24)
    at Object.createNode (/Users/arjunnaha/Developer/_org_/web-marketing/node_modules/@aws-cdk/core/lib/construct-compat.ts:71:11)
    at new Construct (/Users/arjunnaha/Developer/_org_/web-marketing/node_modules/constructs/src/construct.ts:575:26)
    at new Construct (/Users/arjunnaha/Developer/_org_/web-marketing/node_modules/@aws-cdk/core/lib/construct-compat.ts:68:5)
    at new Resource (/Users/arjunnaha/Developer/_org_/web-marketing/node_modules/@aws-cdk/core/lib/resource.ts:116:5)
    at new FunctionBase (/Users/arjunnaha/Developer/_org_/web-marketing/node_modules/@aws-cdk/aws-lambda/lib/function-base.js:17:9)
    at new QualifiedFunctionBase (/Users/arjunnaha/Developer/_org_/web-marketing/node_modules/@aws-cdk/aws-lambda/lib/function-base.js:262:9)
    at new Alias (/Users/arjunnaha/Developer/_org_/web-marketing/node_modules/@aws-cdk/aws-lambda/lib/alias.ts:140:5)
```

### Environment

  - **CDK CLI Version:** 1.90.1 (build 0aee440)
  - **Framework Version:** 1.90.1
  - **Node.js Version:** v15.5.0
  - **OS:** macOS Big Sur 11.2.1
  - **Language (Version):** TypeScript (4.1.3)

--- 

This is :bug: Bug Report

**Comment by njlynch** [comment]
Thanks for the bug report! Fix posted for review.
