### ISSUE TITLE
(aws-ec2): Volume creation does not work (python)

### ISSUE THREAD

**Issue by ncrothe** [aws/aws-cdk#13322]
I have tried to create an aws_ec2.Volume using CDK for Python following the example from the docs. I am getting an error I fail to understand and debug: `cdk.Resource.isResource is not a function`

Getting a similar error when trying with raw CfnVolume, so possibly bug in there?

### Reproduction Steps
Minimal example based on what is in the docs:
```
from aws_cdk import (
    core,
    aws_ec2 as ec2
)

class TmpStack(core.Stack):

    def __init__(self, scope: core.Construct, construct_id: str, **kwargs) -> None:
        super().__init__(scope, construct_id, **kwargs)

        volume = ec2.Volume(self, "sdfwsefwefVolume",
            availability_zone="us-west-2a",
            size=core.Size.gibibytes(500),
            encrypted=True
        )
```

### What did you expect to happen?

`cdk synth` runs successfully and creates a Cloudformation stack including the specified

### What actually happened?

Getting an error on running `cdk synth`. Originally occured in larger stack, when removing the volume resource, error disappears and the rest synthesizes.
Base error message:
`jsii.errors.JSIIError: cdk.Resource.isResource is not a function`

### Environment

  - **CDK CLI Version  :** 1.90.0 (build 7edba31)
  - **Framework Version:** ???
  - **Node.js Version:** v14.15.5
  - **OS               :** Ubuntu-18.04-WSL
  - **Language (Version):** Python 3.6.9

### Other
Full error log
```
$ cdk synth
jsii.errors.JavaScriptError:
  TypeError: cdk.Resource.isResource is not a function
      at new CfnVolume (/tmp/jsii-kernel-N5EKbM/node_modules/@aws-cdk/aws-ec2/lib/ec2.generated.js:15016:45)
      at new Volume (/tmp/jsii-kernel-N5EKbM/node_modules/@aws-cdk/aws-ec2/lib/volume.js:244:26)
      at /tmp/tmpujb6nc37/lib/program.js:2720:58
      at Kernel._wrapSandboxCode (/tmp/tmpujb6nc37/lib/program.js:3148:24)
      at Kernel._create (/tmp/tmpujb6nc37/lib/program.js:2720:34)
      at Kernel.create (/tmp/tmpujb6nc37/lib/program.js:2461:29)
      at KernelHost.processRequest (/tmp/tmpujb6nc37/lib/program.js:9457:36)
      at KernelHost.run (/tmp/tmpujb6nc37/lib/program.js:9420:22)
      at Immediate._onImmediate (/tmp/tmpujb6nc37/lib/program.js:9421:46)
      at processImmediate (internal/timers.js:461:21)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "app.py", line 13, in <module>
    TmpStack(app, "prometheus-global", env=env_global)
  File "/some/path/cdk_project/.venv/lib/python3.6/site-packages/jsii/_runtime.py", line 83, in __call__
    inst = super().__call__(*args, **kwargs)
  File "/some/path/cdk_project/cdk/tmp_stack.py", line 14, in __init__
    encrypted=True
  File "/some/path/cdk_project/.venv/lib/python3.6/site-packages/jsii/_runtime.py", line 83, in __call__
    inst = super().__call__(*args, **kwargs)
  File "/some/path/cdk_project/.venv/lib/python3.6/site-packages/aws_cdk/aws_ec2/__init__.py", line 39598, in __init__
    jsii.create(Volume, self, [scope, id, props])
  File "/some/path/cdk_project/.venv/lib/python3.6/site-packages/jsii/_kernel/__init__.py", line 272, in create
    for iface in getattr(klass, "__jsii_ifaces__", [])
  File "/some/path/cdk_project/.venv/lib/python3.6/site-packages/jsii/_kernel/providers/process.py", line 348, in create
    return self._process.send(request, CreateResponse)
  File "/some/path/cdk_project/.venv/lib/python3.6/site-packages/jsii/_kernel/providers/process.py", line 330, in send
    raise JSIIError(resp.error) from JavaScriptError(resp.stack)
jsii.errors.JSIIError: cdk.Resource.isResource is not a function
Subprocess exited with error 1
```

--- 

This is :bug: Bug Report

**Comment by rix0rrr** [comment]
Fairly sure the cause of this is going to be a version mismatch between the CDK libraries. Can you double-check the versions of all packages that are installed for you?

**Comment by ncrothe** [comment]
Python packages in the venv:
[versions.txt](https://github.com/aws/aws-cdk/files/6076619/versions.txt)

and cdk version: 1.90.0 (build 7edba31)

**Comment by ncrothe** [comment]
I noticed the mix of 1.90.0 and 1.91.0.
So I recreated my venv, reinstalled all required packages. Seems to be all 1.91.0 now. 
Ran cdk synth in the fresh env. Worked this time. Would indicate your hunch was right. Thanks for the suggestion.

Is that expected behaviour for a minor version bump?

**Comment by rix0rrr** [comment]
You need to bump everything, yes

**Comment by ncrothe** [comment]
@rix0rrr If that is necessary, is it possible to maybe enforce lib synchronicity? Or at least provide a less confusing error message, because I am sure this is a situation one can find oneselve in easily.
I guess what happened in my case is that I set up the project and the first couple requirements shortly before the version bump and then added new reqs while working on it, not noticing the version bump. And then getting a very unhelpful error.
