### ISSUE TITLE
(stepfunctions-tasks): SageMaker CreateModel primaryContainer should not be mandatory

### ISSUE THREAD

**Issue by tuliocasagrande** [aws/aws-cdk#13405]
I'm using the SageMakerCreateModel construct to deploy a SageMaker model, but instead of using the `PrimaryContainer` parameter to deploy a single model, I'd like to use the `Containers` parameter, therefore constituting an **inference pipeline**.

The problem is that PrimaryContainer is a mandatory parameter:
- JS: https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-stepfunctions-tasks.SageMakerCreateModel.html
- Python: https://docs.aws.amazon.com/cdk/api/latest/python/aws_cdk.aws_stepfunctions_tasks/SageMakerCreateModel.html

CreateModel documentation page (PrimaryContainer is not mandatory): https://docs.aws.amazon.com/sagemaker/latest/APIReference/API_CreateModel.html

Another reference:
> Instead of setting one `PrimaryContainer`, you use the `Containers` parameter. 
https://docs.aws.amazon.com/sagemaker/latest/dg/inference-pipelines.html

### Reproduction Steps

```python
def get_create_model(self, sagemaker_role):
    return tasks.SageMakerCreateModel(
        self, 'CreateModel',
        model_name=sfn.JsonPath.string_at('$.ModelName'),
        containers=[
            tasks.ContainerDefinition(
                environment_variables=sfn.TaskInput.from_json_path_at(
                    '$.Preprocessing.Environment'),
                image=tasks.DockerImage.from_json_expression(sfn.JsonPath.string_at(
                    '$.Preprocessing.Image')),
                model_s3_location=tasks.S3Location.from_json_expression(
                    '$.Preprocessing.ModelDataUrl'),
            ),
            tasks.ContainerDefinition(
                image=tasks.DockerImage.from_json_expression(sfn.JsonPath.string_at(
                    '$.TrainingJob.Image')),
                model_s3_location=tasks.S3Location.from_json_expression(
                    '$.TrainingJob.ModelDataUrl'),
            )
        ],
        role=sagemaker_role,
        comment='Create a SageMaker Model',
        input_path='$.CreateModel',
        result_path='$.CreateModel.Output',
    )
```
### What did you expect to happen?

I expected to deploy without errors.

### What actually happened?

It raised a missing required parameter error:
```bash
Traceback (most recent call last):
  File "app.py", line 12, in <module>
    MlSkeletonStack(app, "ml-skeleton", stack_name=stack_name)
  File "/Users/tulioalb/code/work/too-seguros/ml-skeleton/.venv/lib/python3.8/site-packages/jsii/_runtime.py", line 83, in __call__
    inst = super().__call__(*args, **kwargs)
  File "/Users/tulioalb/code/work/too-seguros/ml-skeleton/ml_skeleton/ml_skeleton_stack.py", line 26, in __init__
    deploy_sm = get_deploy_sm(self, ml_artifacts_bucket, sagemaker_role)
  File "/Users/tulioalb/code/work/too-seguros/ml-skeleton/ml_skeleton/state_machines/deploy/deploy.py", line 10, in get_deploy_sm
    create_model_step = get_create_model(self, sagemaker_role)
  File "/Users/tulioalb/code/work/too-seguros/ml-skeleton/ml_skeleton/state_machines/deploy/steps/step1_create_model/create_model.py", line 39, in get_create_model
    return tasks.SageMakerCreateModel(
  File "/Users/tulioalb/code/work/too-seguros/ml-skeleton/.venv/lib/python3.8/site-packages/jsii/_runtime.py", line 83, in __call__
    inst = super().__call__(*args, **kwargs)
TypeError: __init__() missing 1 required keyword-only argument: 'primary_container'
Subprocess exited with error 1
```

### Environment

  - **CDK CLI Version:**  1.89.0 (build df7253c)
  - **Framework Version:**
  - **Node.js Version:** v10.13.0
  - **OS :** macOS Catalina
  - **Language (Version):** Python (3.8.5)

### Other

If I deploy with PrimaryContainer, it works fine, but doesn't suffice my needs.

```python
def get_create_model(self, sagemaker_role):
    return tasks.SageMakerCreateModel(
        self, 'CreateModel',
        model_name=sfn.JsonPath.string_at('$.ModelName'),
        primary_container=tasks.ContainerDefinition(
            environment_variables=sfn.TaskInput.from_json_path_at(
                '$.Preprocessing.Environment'),
            image=tasks.DockerImage.from_json_expression(sfn.JsonPath.string_at(
                '$.Preprocessing.Image')),
            model_s3_location=tasks.S3Location.from_json_expression(
                '$.Preprocessing.ModelDataUrl'),
        ),
        role=sagemaker_role,
        comment='Create a SageMaker Model',
        input_path='$.CreateModel',
        result_path='$.CreateModel.Output',
    )
```

--- 

This is :bug: Bug Report

**Comment by ericwush** [comment]
+1
If the mandatory check can be removed and delegate the validation to the `CreateModel` API.

**Comment by donatoaz** [comment]
I don't think this should have been closed. This is still a bug in cdk v2.76.

**Comment by stefan-ce** [comment]
This is still a bug in CDK v2.214. How do we handle this - can it be reopen or do we need to create a new issue?
