### ISSUE TITLE
jsii: Using aws-sdk with jsii results in TypeError: undefined is not a function

### ISSUE THREAD

**Issue by dhruvdakoria** [aws/aws-cdk#13404]
### Affected Languages

- [ X ] `TypeScript` or `Javascript`
- [ ] `Python`
- [ ] `Java`
- [ ] .NET (`C#`, `F#`, ...)

### General Information
* **JSII Version:** 1.24.0 (build b722f66), typescript 3.9.9
* **Platform:**     Linux ip-10-160-248-225 4.14.209-117.337.amzn1.x86_64 #1 SMP Mon Dec 14 21:04:29 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux 

### What is the problem?
When installing aws-sdk and running jsii, results in error _TypeError: undefined is not a function_

Here's a section from package.json of my cdk construct - 
 
```
"devDependencies": {
    "@aws-cdk/assert": "1.91.0",
    "@types/jest": "^26.0.10",
    "@types/node": "10.17.27",
    "aws-sdk": "^2.857.0",
    "jest": "^26.4.2",
    "jsii": "^1.24.0",
    "jsii-docgen": "^1.8.63",
    "jsii-pacmak": "^1.24.0",
    "ts-jest": "^26.5.3",
    "typescript": "~3.9.7"
  },
  "peerDependencies": {
    "@aws-cdk/core": "1.91.0",
    "@aws-cdk/aws-ssm": "1.91.0",
    "constructs": "^3.3.55",
    "aws-sdk": "^2.857.0"
  },
  "bundledDependencies": {
    "aws-sdk": "^2.857.0"
  },
  "dependencies": {
    "@aws-cdk/aws-ssm": "1.91.0",
    "@aws-cdk/core": "1.91.0",
    "aws-sdk": "^2.857.0",
    "constructs": "^3.3.55"
  }
```

**Without aws-sdk as a dependency both jsii and jsii-pacmak works fine.**

### Verbose Log

```
$ jsii --verbose
Error: TypeError: undefined is not a function
    at Object.loadProjectInfo (/home/ec2-user/.nvm/versions/node/v10.23.1/lib/node_modules/jsii/lib/project-info.js:21:146)
    at /home/ec2-user/.nvm/versions/node/v10.23.1/lib/node_modules/jsii/bin/jsii.js:67:46
    at Object.<anonymous> (/home/ec2-user/.nvm/versions/node/v10.23.1/lib/node_modules/jsii/bin/jsii.js:86:3)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
```

**Comment by peterwoodworth** [comment]
Closing because you opened this up [here.](https://github.com/aws/jsii/issues/2652)
