### ISSUE TITLE
(@aws-cdk/assert): matchTemplate fails on ApiGateway

### ISSUE THREAD

**Issue by pseudoblau** [aws/aws-cdk#13491]
### Reproduction Steps
Have a simple test that matches if a stack is a superset of an empty object:

```
test('Empty Stack', () => {
    const app = new cdk.App();
    // WHEN
    const stack = new Test.TestStack(app, 'MyTestStack');
    // THEN
    expectCDK(stack).to(matchTemplate({
      "Resources": { }
    }, MatchStyle.SUPERSET))
});
```

and a simple Stack with an ApiGateway:
```
export class TestStack extends cdk.Stack {
  constructor(scope: cdk.Construct, id: string, props?: cdk.StackProps) {
    super(scope, id, props);

    const api = new apigateway.RestApi(this, 'books-api');
    api.root.addMethod('ANY');
  }
}
```

### What did you expect to happen?

The simple test should pass as it does with other stacks that include for example sns topics, sqs queues, DynamoDBs.

### What actually happened?

The test fails:
```
Template comparison produced unacceptable match

       8 |     const stack = new Test.TestStack(app, 'MyTestStack');
       9 |     // THEN
    > 10 |     expectCDK(stack).to(matchTemplate({
         |                      ^
      11 |       "Resources": {

      at StackMatchesTemplateAssertion.assertOrThrow (node_modules/@aws-cdk/assert/lib/assertions/match-template.ts:38:13)
      at StackInspector._to (node_modules/@aws-cdk/assert/lib/inspector.ts:25:15)
      at StackInspector.to (node_modules/@aws-cdk/assert/lib/inspector.ts:15:14)
      at Object.<anonymous> (test/test.test.ts:10:22)
```

### Environment

  - **CDK CLI Version  :** 1.92.0 (build de536cc)
  - **Framework Version:** 1.92.0
  - **Node.js Version:** v14.15.4
  - **OS               :** Fedora 33 
  - **Language (Version):** TypeScript 

### Other

--- 

This is :bug: Bug Report

**Comment by shreyasmm** [comment]
Facing Same issue in 1.92 CDK Typescript, Not Specific to api gateway my all tests are Failing
```` 
None of 0 resources matches resource 'Custom::AmiLookup' with {
      "$objectLike": {
        "ServiceToken": {
          "Fn::ImportValue": "AmiFunctionArn"
        },
      }
    }.

      21 |   });
      22 |
    > 23 |   expectCDK(stack).to(haveResource("Custom::AmiLookup",{
         |                    ^
      24 |     "ServiceToken": {
      25 |       "Fn::ImportValue": "AmiFunctionArn"
      26 |     },

      at HaveResourceAssertion.assertOrThrow (../../node_modules/@aws-cdk/assert/lib/assertions/have-resource.ts:100:13)
      at StackInspector._to (../../node_modules/@aws-cdk/assert/lib/inspector.ts:25:15)
      at StackInspector.to (../../node_modules/@aws-cdk/assert/lib/inspector.ts:15:14)
      at Object.<anonymous> (src/__tests__/common.test.ts:23:20)
````

Another Example
````
yarn run v1.22.10
$ jest --passWithNoTests
ts-jest[config] (WARN) The option `tsConfig` is deprecated and will be removed in ts-jest 27, use `tsconfig` instead
 FAIL  src/__tests__/s3.test.ts (11.528 s)
  ✕ S3 Bucket Created (38 ms)
  ✕ S3 Bucket Glacier Lifecycle Policy Created (10 ms)
  ✕ S3 Bucket Infrequent Access Lifecycle Policy Created (9 ms)
  ✕ S3 Abort Incomplete Multipart Upload Lifecycle Policy Created (7 ms)
  ✕ S3 Expire Lifecycle Policy Created (6 ms)

  ● S3 Bucket Created

    None of 0 resources matches resource 'AWS::S3::Bucket' with {
      "$objectLike": {
        "BucketName": "shrey-cdk-test",
        "PublicAccessBlockConfiguration": {
          "BlockPublicAcls": true,
          "BlockPublicPolicy": true,
          "IgnorePublicAcls": true,
          "RestrictPublicBuckets": true
        }
      }
    }.

       9 |     bucketName: 'shrey-cdk-test',
      10 |   });
    > 11 |   expectCDK(stack).to(haveResource("AWS::S3::Bucket",{
         |                    ^
      12 |     BucketName: 'shrey-cdk-test',
      13 |     PublicAccessBlockConfiguration: {
      14 |       BlockPublicAcls: true,

      at HaveResourceAssertion.assertOrThrow (../../node_modules/@aws-cdk/assert/lib/assertions/have-resource.ts:100:13)
      at StackInspector._to (../../node_modules/@aws-cdk/assert/lib/inspector.ts:25:15)
      at StackInspector.to (../../node_modules/@aws-cdk/assert/lib/inspector.ts:15:14)
      at Object.<anonymous> (src/__tests__/s3.test.ts:11:20)

  ● S3 Bucket Glacier Lifecycle Policy Created

    None of 0 resources matches resource 'AWS::S3::Bucket' with {
      "$objectLike": {
        "BucketName": "shrey-cdk-test",
        "LifecycleConfiguration": {
          "Rules": [
            {
              "AbortIncompleteMultipartUpload": {
                "DaysAfterInitiation": 7
              },
              "Status": "Enabled"
            },
            {
              "Status": "Enabled",
              "Transitions": [
                {
                  "StorageClass": "GLACIER",
                  "TransitionInDays": 180
                }
              ]
            }
          ]
        }
      }
    }.

      29 |     glacierTransitionAfter: cdk.Duration.days(180)
      30 |   });
    > 31 |   expectCDK(stack).to(haveResource("AWS::S3::Bucket",{
         |                    ^
      32 |     "BucketName": 'shrey-cdk-test',
      33 |     "LifecycleConfiguration": {
      34 |       "Rules": [

      at HaveResourceAssertion.assertOrThrow (../../node_modules/@aws-cdk/assert/lib/assertions/have-resource.ts:100:13)
      at StackInspector._to (../../node_modules/@aws-cdk/assert/lib/inspector.ts:25:15)
      at StackInspector.to (../../node_modules/@aws-cdk/assert/lib/inspector.ts:15:14)
      at Object.<anonymous> (src/__tests__/s3.test.ts:31:20)

  ● S3 Bucket Infrequent Access Lifecycle Policy Created

    None of 0 resources matches resource 'AWS::S3::Bucket' with {
      "$objectLike": {
        "BucketName": "shrey-cdk-test",
        "LifecycleConfiguration": {
          "Rules": [
            {
              "AbortIncompleteMultipartUpload": {
                "DaysAfterInitiation": 7
              },
              "Status": "Enabled"
            },
            {
              "Status": "Enabled",
              "Transitions": [
                {
                  "StorageClass": "STANDARD_IA",
                  "TransitionInDays": 90
                }
              ]
            }
          ]
        }
      }
    }.

      62 |     infrequentAccessTransitionAfter: cdk.Duration.days(90)
      63 |   });
    > 64 |   expectCDK(stack).to(haveResource("AWS::S3::Bucket",{
         |                    ^
      65 |     "BucketName": 'shrey-cdk-test',
      66 |     "LifecycleConfiguration": {
      67 |       "Rules": [

      at HaveResourceAssertion.assertOrThrow (../../node_modules/@aws-cdk/assert/lib/assertions/have-resource.ts:100:13)
      at StackInspector._to (../../node_modules/@aws-cdk/assert/lib/inspector.ts:25:15)
      at StackInspector.to (../../node_modules/@aws-cdk/assert/lib/inspector.ts:15:14)
      at Object.<anonymous> (src/__tests__/s3.test.ts:64:20)

  ● S3 Abort Incomplete Multipart Upload Lifecycle Policy Created

    None of 0 resources matches resource 'AWS::S3::Bucket' with {
      "$objectLike": {
        "BucketName": "shrey-cdk-test",
        "LifecycleConfiguration": {
          "Rules": [
            {
              "AbortIncompleteMultipartUpload": {
                "DaysAfterInitiation": 7
              },
              "Status": "Enabled"
            }
          ]
        }
      }
    }.

      94 |     bucketName: 'shrey-cdk-test',
      95 |   });
    > 96 |   expectCDK(stack).to(haveResource("AWS::S3::Bucket",{
         |                    ^
      97 |     "BucketName": 'shrey-cdk-test',
      98 |     "LifecycleConfiguration": {
      99 |       "Rules": [

      at HaveResourceAssertion.assertOrThrow (../../node_modules/@aws-cdk/assert/lib/assertions/have-resource.ts:100:13)
      at StackInspector._to (../../node_modules/@aws-cdk/assert/lib/inspector.ts:25:15)
      at StackInspector.to (../../node_modules/@aws-cdk/assert/lib/inspector.ts:15:14)
      at Object.<anonymous> (src/__tests__/s3.test.ts:96:20)

  ● S3 Expire Lifecycle Policy Created

    None of 0 resources matches resource 'AWS::S3::Bucket' with {
      "$objectLike": {
        "BucketName": "shrey-cdk-test",
        "LifecycleConfiguration": {
          "Rules": [
            {
              "AbortIncompleteMultipartUpload": {
                "DaysAfterInitiation": 7
              },
              "Status": "Enabled"
            },
            {
              "ExpirationInDays": 360,
              "Status": "Enabled"
            }
          ]
        }
      }
    }.

      117 |     expirationAfter: cdk.Duration.days(360)
      118 |   });
    > 119 |   expectCDK(stack).to(haveResource("AWS::S3::Bucket",{
          |                    ^
      120 |     "BucketName": 'shrey-cdk-test',
      121 |     "LifecycleConfiguration": {
      122 |       "Rules": [

      at HaveResourceAssertion.assertOrThrow (../../node_modules/@aws-cdk/assert/lib/assertions/have-resource.ts:100:13)
      at StackInspector._to (../../node_modules/@aws-cdk/assert/lib/inspector.ts:25:15)
      at StackInspector.to (../../node_modules/@aws-cdk/assert/lib/inspector.ts:15:14)
      at Object.<anonymous> (src/__tests__/s3.test.ts:119:20)

Test Suites: 1 failed, 1 total
Tests:       5 failed, 5 total
Snapshots:   0 total
Time:        20.34 s
Ran all test suites.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
````

**Comment by nija-at** [comment]
@pseudoblau - not sure I understand your assertion in the test case. 
If you have a stack with a `RestApi` and a method configured on the `RestApi` construct, why do you expect the template be empty?

The template would indeed contain *at least* a `AWS::ApiGateway::RestApi` and a `AWS::ApiGateway::Method` resources.

**Comment by pseudoblau** [comment]
@nija-at I am using `MatchStyle.SUPERSET`. I expect any template to be a superset of an empty template. As I stated, the test succeeds if I use other Resources than an ApiGateway.

**Comment by nija-at** [comment]
Yes, you are correct. It does indeed fail for ApiGateway.

The problem is that the `RestApi` construct adds a [CloudFormation output section](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/outputs-section-structure.html) here and the `matchTemplate` API does not account for this in its superset option - https://github.com/aws/aws-cdk/blob/ab2c48e05ca3e2edf04e21a41051a46a5061b2dc/packages/%40aws-cdk/aws-apigateway/lib/restapi.ts#L545

**Comment by nija-at** [comment]
The code responsible for this is here - https://github.com/aws/aws-cdk/blob/ab2c48e05ca3e2edf04e21a41051a46a5061b2dc/packages/%40aws-cdk/assert/lib/assertions/match-template.ts#L80-L86

The logic seems to be that any change to the 'Parameters' or 'Outputs' sections should be considered a diff even if `MatchStyle.SUPERSET` is used. It's not immediately clear why it's configured like this.
