### ISSUE TITLE
core/deployment: deploy does not work when bootstrapped with  custom bucket name

### ISSUE THREAD

**Issue by mt-rpranata** [aws/aws-cdk#13516]
We are trying to bootstrap with a custom bucket name. When running `deploy`, we got

```
[100%] fail: No bucket named 'cdk-my-assets-111111111111-ap-northeast-1'. Is account 111111111111 bootstrapped?
```

### Reproduction Steps

1. Run bootstrap

    ```
    npx cdk bootstrap aws://111111111111/ap-northeast-1 \
      --public-access-block-configuration \
      --toolkit-stack-name toolkit-custom-stack-name \
      --bootstrap-bucket-name toolkit-custom-bucket-name \
      --qualifier "my-stuff"
    ```

1. Run `deploy`

    ```
    npx cdk deploy my-real-stack \
       --app "npx ts-node bin/my-real-stack.ts" \
       --toolkit-stack-name toolkit-custom-stack-name \
       --bootstrap-bucket-name toolkit-custom-bucket-name \
       --require-approval never \
       --no-execute \
       --exclusively \
       --verbose
    ```

### What did you expect to happen?

The deployment works 

### What actually happened?

It says the bucket does not exist. The bucket name in the error message is not the bucket name that I would expect. I think this is the default bucket name

### Environment

  - **CDK CLI Version  :** 1.91.0 (build 0f728ce)
  - **Framework Version:**
  - **Node.js Version:** v14.16.0
  - **OS               :** Mac OS Big Sur 11.2.2 (20D80)
  - **Language (Version):** TypeScript

### Other

```
 ❌  my-real-stackfailed: Error: Failed to publish one or more assets. See the error messages above for more information.
    at Object.publishAssets (<#path_to_proj#>/node_modules/aws-cdk/lib/util/asset-publishing.ts:25:11)
    at CloudFormationDeployments.publishStackAssets (<#path_to_proj#>/node_modules/aws-cdk/lib/api/cloudformation-deployments.ts:277:7)
    at CloudFormationDeployments.deployStack (<#path_to_proj#>/node_modules/aws-cdk/lib/api/cloudformation-deployments.ts:160:5)
    at CdkToolkit.deploy (<#path_to_proj#>/node_modules/aws-cdk/lib/cdk-toolkit.ts:180:24)
    at initCommandLine (<#path_to_proj#>/node_modules/aws-cdk/bin/cdk.ts:208:9)
Failed to publish one or more assets. See the error messages above for more information.
```

--- 

This is :bug: Bug Report

**Comment by rix0rrr** [comment]
If you change default names you need to tell the synthesizer in your CDK app about the new names: https://docs.aws.amazon.com/cdk/latest/guide/bootstrapping.html#bootstrapping-custom-synth
