### ISSUE TITLE
(aws-eks): ClusterName set from CfnParameter.ValueAsString leads to cluster creation failure

### ISSUE THREAD

**Issue by vgribok** [aws/aws-cdk#13532]
Cluster construct ClusterName property can be set only from actual string, but not from CfnParameter. With former, everything works, with latter cluster fails with
```
 31/37 | 2:51:02 PM | CREATE_FAILED        | Custom::AWSCDK-EKS-Cluster            | dapr-eks-cluster/Resource/Resource/Default (daprekscluster2E17A6A2) Failed to create resource. User: arn:aws:sts::123456798012:assumed-role/DaprOnAwsCdkStack-dapreksclusterCreationRoleAD-15Q5O7NOURTLF/AWSCDK.EKSCluster.Create.19f88dee-763a-43e6-a56f-fa7ae61c9e8d is not authorized to perform: eks:CreateCluster on resource: arn:aws:eks:us-east-2:123456798012:cluster/dapr--
```

### Reproduction Steps

// C# example
```C#
using Amazon.CDK;
using Amazon.CDK.AWS.EKS;

namespace DaprOnAwsCdk
{
    public class DaprOnAwsCdkStack : Stack
    {
        internal DaprOnAwsCdkStack(Construct scope, string id, IStackProps props = null) : base(scope, id, props)
        {
            var eksClusterName = new CfnParameter(this, "EksClusterName", new CfnParameterProps{
				Default = "my-cluster",
				Description = "The name of the Kubernetes cluster to be created",
				Type = "String"
			  });

            var cluster = new Cluster(this, "eks-cluster", new ClusterProps {
                ClusterName = eksClusterName.ValueAsString, // replace with "my-cluster" to - it will work
                Version = KubernetesVersion.V1_19,
            });
        }
    }
}
```

### What did you expect to happen?
EKS cluster gets created successfully

Create an EKS cluster

### What actually happened?

`cdk deploy` reliably fails in the middle of the process - tested many times in different regions.

### Environment

  - **CDK CLI Version  : 1.92.0**
  - **Framework Version: 1.92.0**
  - **Node.js Version:**  15.5.0
  - **OS               :** Windows 10
  - **Language (Version):**  C# 8, .NET Core 3.1

### Other

```
 31/37 | 2:51:02 PM | CREATE_IN_PROGRESS   | Custom::AWSCDK-EKS-Cluster            | dapr-eks-cluster/Resource/Resource/Default (daprekscluster2E17A6A2) Resource creation Initiated
 31/37 | 2:51:02 PM | CREATE_FAILED        | Custom::AWSCDK-EKS-Cluster            | dapr-eks-cluster/Resource/Resource/Default (daprekscluster2E17A6A2) Failed to create resource. User: arn:aws:sts::123456798012:assumed-role/DaprOnAwsCdkStack-dapreksclusterCreationRoleAD-15Q5O7NOURTLF/AWSCDK.EKSCluster.Create.19f88dee-763a-43e6-a56f-fa7ae61c9e8d is not authorized to perform: eks:CreateCluster on resource: arn:aws:eks:us-east-2:123456798012:cluster/dapr--cluster

Logs: /aws/lambda/DaprOnAwsCdkStack-awscd-OnEventHandler42BEBAE0-G9ORTL6IEE83

    at Object.extractError (/var/runtime/node_modules/aws-sdk/lib/protocol/json.js:52:27)
    at Request.extractError (/var/runtime/node_modules/aws-sdk/lib/protocol/rest_json.js:55:8)
    at Request.callListeners (/var/runtime/node_modules/aws-sdk/lib/sequential_executor.js:106:20)
    at Request.emit (/var/runtime/node_modules/aws-sdk/lib/sequential_executor.js:78:10)
    at Request.emit (/var/runtime/node_modules/aws-sdk/lib/request.js:688:14)
    at Request.transition (/var/runtime/node_modules/aws-sdk/lib/request.js:22:10)
    at AcceptorStateMachine.runTo (/var/runtime/node_modules/aws-sdk/lib/state_machin
        new CustomResource (C:\Users\joeuser\AppData\Local\Temp\jsii-kernel-2qMjJT\node_modules\@aws-cdk\core\lib\custom-resource.js:30:25)
        \_ new ClusterResource (C:\Users\joeuser\AppData\Local\Temp\jsii-kernel-2qMjJT\node_modules\@aws-cdk\aws-eks\lib\cluster-resource.js:34:26)
        \_ new Cluster (C:\Users\joeuser\AppData\Local\Temp\jsii-kernel-2qMjJT\node_modules\@aws-cdk\aws-eks\lib\cluster.js:293:50)
        \_ C:\Users\joeuser\AppData\Local\Temp\lqmeippu.1rp\lib\program.js:2720:58
        \_ Kernel._wrapSandboxCode (C:\Users\joeuser\AppData\Local\Temp\lqmeippu.1rp\lib\program.js:3148:24)
        \_ Kernel._create (C:\Users\joeuser\AppData\Local\Temp\lqmeippu.1rp\lib\program.js:2720:34)
        \_ Kernel.create (C:\Users\joeuser\AppData\Local\Temp\lqmeippu.1rp\lib\program.js:2461:29)
        \_ KernelHost.processRequest (C:\Users\joeuser\AppData\Local\Temp\lqmeippu.1rp\lib\program.js:9457:36)
        \_ KernelHost.run (C:\Users\joeuser\AppData\Local\Temp\lqmeippu.1rp\lib\program.js:9420:22)
        \_ Immediate._onImmediate (C:\Users\joeuser\AppData\Local\Temp\lqmeippu.1rp\lib\program.js:9421:46)
        \_ processImmediate (node:internal/timers:463:21)
 31/37 | 2:51:03 PM | ROLLBACK_IN_PROGRESS | AWS::CloudFormation::Stack            | DaprOnAwsCdkStack The following resource(s) failed to create: [daprekscluster2E17A6A2]. Rollback requested by user.
```

--- 

This is :bug: Bug Report

**Comment by banagevikas** [comment]
I'm facing similar issue with TypeScript

**Comment by codeJack** [comment]
Same issue reproduced with a python based CDK app.

**Comment by gzus85** [comment]
> Same issue reproduced with a python based CDK app.

Also facing the same with Python.
