### ISSUE TITLE
aws-dynamodb: error on ddb autoscaling

### ISSUE THREAD

**Issue by thomaszooman** [aws/aws-cdk#13594]
Hi, i follow the example in [cdk example](https://docs.aws.amazon.com/cdk/api/latest/docs/aws-dynamodb-readme.html#configure-autoscaling-for-your-table) to enable autoscaling, but error on `CfnScalingPolicyProps`

### code snippet
```javascript
const cdk = require( "@aws-cdk/core" );
const ddb = require( "@aws-cdk/aws-dynamodb" );

const config_version = new ddb.Table(this, "CONFIG_VERSION",
{
    tableName: "CONFIG_VERSION",
    billingMode: ddb.BillingMode.PROVISIONED,
    readCapacity: 2,
    writeCapacity: 2,
    partitionKey:
    {
        name: "engineno",
        type: ddb.AttributeType.STRING
    },
    removalPolicy: cdk.RemovalPolicy.RETAIN,
    encryption: ddb.TableEncryption.AWS_MANAGED
});
const readScaling = config_version.autoScaleReadCapacity(
{
	minCapacity: 2,
	maxCapacity: 20
});
const writeScaling = config_version.autoScaleWriteCapacity(
{
	minCapacity: 2,
	maxCapacity: 20
});
readScaling.scaleOnUtilization(70);
writeScaling.scaleOnUtilization(70);
```

### stacktraces
```
backend/deploy/cdk/node_modules/@aws-cdk/core/lib/resolvable.js:68
            throw e;
            ^

CfnSynthesisError: Resolution error: Supplied properties not correct for "CfnScalingPolicyProps"
  targetTrackingScalingPolicyConfiguration: supplied properties not correct for "TargetTrackingScalingPolicyConfigurationProperty"
    targetValue: required but missing.
    at ValidationResult.assertSuccess (backend/deploy/cdk/node_modules/@aws-cdk/aws-applicationautoscaling/node_modules/@aws-cdk/core/lib/runtime.js:139:19)
    at cfnScalingPolicyPropsToCloudFormation (backend/deploy/cdk/node_modules/@aws-cdk/aws-applicationautoscaling/lib/applicationautoscaling.generated.js:375:48)
    at CfnScalingPolicy.renderProperties (backend/deploy/cdk/node_modules/@aws-cdk/aws-applicationautoscaling/lib/applicationautoscaling.generated.js:478:16)
    at PostResolveToken.ret.Resources [as processor] (backend/deploy/cdk/node_modules/@aws-cdk/aws-applicationautoscaling/node_modules/@aws-cdk/core/lib/cfn-resource.js:293:52)
    at PostResolveToken.postProcess (backend/deploy/cdk/node_modules/@aws-cdk/aws-applicationautoscaling/node_modules/@aws-cdk/core/lib/util.js:81:21)
    at Object.postProcess (backend/deploy/cdk/node_modules/@aws-cdk/core/lib/private/resolve.js:59:82)
    at DefaultTokenResolver.resolveToken (backend/deploy/cdk/node_modules/@aws-cdk/core/lib/resolvable.js:59:38)
    at resolve (backend/deploy/cdk/node_modules/@aws-cdk/core/lib/private/resolve.js:128:55)
    at Object.resolve (backend/deploy/cdk/node_modules/@aws-cdk/core/lib/private/resolve.js:57:48)
    at resolve (backend/deploy/cdk/node_modules/@aws-cdk/core/lib/private/resolve.js:143:51) {
  type: 'CfnSynthesisError'
}
```

### Environment

  - **CDK CLI Version  :** 1.93.0 (build c506d3b)
  - **Framework Version:** `"aws-cdk": "1.93.0"`
  - **Node.js Version:** v14.16.0
  - **OS               :** macOS 10.15.7 (19H512)
  - **Language (Version):** javascript

### Other

--- 

This is :bug: Bug Report

**Comment by skinny85** [comment]
Hi @thomaszooman ,

thanks for opening the issue. The problem is that the `scaleOnUtilization` method does not take a number, but a `UtilizationScalingProps` interface. See here: https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-dynamodb.IScalableTableAttribute.html#scalewbronwbrutilizationprops.

So, the code should be:

```ts
        const config_version = new ddb.Table(this, "CONFIG_VERSION", {
            tableName: "CONFIG_VERSION",
            billingMode: ddb.BillingMode.PROVISIONED,
            readCapacity: 2,
            writeCapacity: 2,
            partitionKey: {
                name: "engineno",
                type: ddb.AttributeType.STRING
            },
            removalPolicy: cdk.RemovalPolicy.RETAIN,
            encryption: ddb.TableEncryption.AWS_MANAGED,
        });
        const readScaling = config_version.autoScaleReadCapacity({
            minCapacity: 2,
            maxCapacity: 20
        });
        const writeScaling = config_version.autoScaleWriteCapacity({
            minCapacity: 2,
            maxCapacity: 20
        });
        readScaling.scaleOnUtilization({ targetUtilizationPercent: 70 });
        writeScaling.scaleOnUtilization({ targetUtilizationPercent: 70 });
```

If you change the line `const ddb = require( "@aws-cdk/aws-dynamodb" );` to `import * as ddb from '@aws-cdk/aws-dynamodb';`, the TypeScript compiler will catch this error for you.

Thanks,
Adam
