### ISSUE TITLE
Can't create physical name for DatabaseInstance

### ISSUE THREAD

**Issue by besh0y** [aws/aws-cdk#13832]
Hello there!
I'm trying to create a DB instance with CDK and then reference it in a read replica in a different region.
Since one way to do that is using PhysicalName.GENERATE_IF_NEEDED ( [#226](https://github.com/aws/aws-cdk-rfcs/issues/226) ) in the resource that needs to be referenced I tried to use it in my DB instance, yet it throws every time I attempt to generate a physical name.
   

### Reproduction Steps:
create the following DB instance in a stack that gets a VPC in props

```ts
new DatabaseInstance(this, 'db', {
    databaseName: PhysicalName.GENERATE_IF_NEEDED,
    engine: DatabaseInstanceEngine.postgres({ version: PostgresEngineVersion.of('13.1', '13') }),
    vpcSubnets: {
        subnetType: ec2.SubnetType.PRIVATE,
    },
    vpc: props.vpc,
});
```
### Error Log

```/Users/beshoy/Desktop/cqa-api/node_modules/@aws-cdk/core/lib/private/physical-name-generator.ts:91
    throw new Error('Invalid physical name passed to CloudFormation. Use "this.physicalName" instead');
          ^
Error: Resolution error: Resolution error: Resolution error: Invalid physical name passed to CloudFormation. Use "this.physicalName" instead...
    at GeneratedWhenNeededMarker.resolve (/Users/beshoy/Desktop/cqa-api/node_modules/@aws-cdk/core/lib/private/physical-name-generator.ts:91:11)
    at RememberingTokenResolver.resolveToken (/Users/beshoy/Desktop/cqa-api/node_modules/@aws-cdk/core/lib/resolvable.ts:147:24)
    at RememberingTokenResolver.resolveToken (/Users/beshoy/Desktop/cqa-api/node_modules/@aws-cdk/core/lib/private/resolve.ts:273:18)
    at resolve (/Users/beshoy/Desktop/cqa-api/node_modules/@aws-cdk/core/lib/private/resolve.ts:202:51)
    at Object.resolve [as mapToken] (/Users/beshoy/Desktop/cqa-api/node_modules/@aws-cdk/core/lib/private/resolve.ts:112:77)
    at TokenizedStringFragments.mapTokens (/Users/beshoy/Desktop/cqa-api/node_modules/@aws-cdk/core/lib/string-fragments.ts:71:33)
    at RememberingTokenResolver.resolveString (/Users/beshoy/Desktop/cqa-api/node_modules/@aws-cdk/core/lib/resolvable.ts:168:22)
    at RememberingTokenResolver.resolveString (/Users/beshoy/Desktop/cqa-api/node_modules/@aws-cdk/core/lib/private/resolve.ts:277:23)
    at resolve (/Users/beshoy/Desktop/cqa-api/node_modules/@aws-cdk/core/lib/private/resolve.ts:160:48)
    at Object.resolve (/Users/beshoy/Desktop/cqa-api/node_modules/@aws-cdk/core/lib/private/resolve.ts:112:77)
Subprocess exited with error 1
error Command failed with exit code 1.
```

### Environment:

    CLI Version: 2.1.29
    Framework Version: 1.95.1
    Node.js Version: v14.15.3
    OS: macOS 11.2
    Language (Version): TypeScript
--- 

This is :bug: Bug Report

**Comment by skinny85** [comment]
Thanks for opening the issue @besh0y. Confirming this is a bug. I'm working on a fix.

**Comment by skinny85** [comment]
@besh0y can you show your code creating the Instance, and how it's used?

**Comment by besh0y** [comment]
**db.ts file**
createT3Db(
		stack: Construct,
		id: string,
		databaseName: string,
		size: ec2.InstanceSize,
		multiAZ: boolean,
		vpc: ec2.Vpc,
	) {
		const engine = DatabaseInstanceEngine.postgres({ version: PostgresEngineVersion.of('13.1', '13') });
		return new DatabaseInstance(stack, id, {
			engine,
			instanceType: ec2.InstanceType.of(ec2.InstanceClass.T3, ec2.InstanceSize.SMALL),
			// deletionProtection: true,
			databaseName,
			multiAz: multiAZ,
			monitoringInterval: Duration.seconds(60),
			enablePerformanceInsights: true,
			parameterGroup: new ParameterGroup(stack, `${id}-parameter-group`, {
				engine,
				parameters: { 'cron.database_name': databaseName },
			}),
			vpcSubnets: {
				subnetType: ec2.SubnetType.PRIVATE,
			},
			vpc,
		});
	}
	
**DB stack file**

	const databaseName = PhysicalName.GENERATE_IF_NEEDED;

		this.dbInstance = this.db.createT3Db(
			this,
			`${id}-instance`,
			databaseName,
			ec2.InstanceSize.SMALL,
			isProduction,
			props.vpc,
		);

**Comment by skinny85** [comment]
You're using the wrong property - the physical name of `DatabaseInstance` is `instanceIdentifier`, not `databaseName` (the latter one controls the name of the default created Postgres database inside the Instance).

**Comment by peterwoodworth** [comment]
Closing because it seems like the issue has been solved, also has gone more than 2 weeks without response. Please ping me if you want to reopen this issue 😄

**Comment by JoshMcCullough** [comment]
> the physical name of `DatabaseInstance` is `instanceIdentifier`

Who would have expected that? I mean all the other constructs (or many) use "<thing>Name". Well, it got me!
