### ISSUE TITLE
aws-glue: glue_version type issue with CfnJob

### ISSUE THREAD

**Issue by csmcallister** [aws/aws-cdk#13855]
The `glue_version` argument to `aws_glue.CfnJob` should be a string according to the type hint and documentation, but passing a string raises a jssi error: `jsii.errors.JSIIError: Expected a number, got "2" (string)`. Passing an int or float similarly raises an issue: `jsii.errors.JSIIError: Expected a string, got 2 (number)`. This prevents you from using anything but the default version.

### Reproduction Steps

Create a new cdk project and define a stack with glue in in:

```bash
mkdir glue
cd glue
cdk init --language python
source env/bin/activate
pip install aws-cdk.aws-glue==1.95.1 aws-cdk.aws-iam==1.95.1
```

Then update the stack in `./glue/glue_stack.py`:

```python
from aws_cdk import core
from aws_cdk import aws_glue as glue
from aws_cdk import aws_iam as iam


class GlueStack(core.Stack):

    def __init__(self, scope: core.Construct, construct_id: str, **kwargs) -> None:
        super().__init__(scope, construct_id, **kwargs)

        glue_role = iam.Role(
            self, "ExecuteGlueHudiJobRole",
            assumed_by=iam.ServicePrincipal('glue.amazonaws.com'),
        )

        # The code that defines your stack goes here
        glue_security_config = glue.CfnSecurityConfiguration(
            self, "GlueJobsSecurityConfig",
            name='SecurityConfig',
            encryption_configuration=glue.CfnSecurityConfiguration.EncryptionConfigurationProperty()
        )
        glue_job = glue.CfnJob(
            self, "GlueJob",
            command=glue.CfnJob.JobCommandProperty(
                name='mygluejob',
                python_version='3',
                script_location=f's3://my-bucket/my_job.py'
            ),
            connections=glue.CfnJob.ConnectionsListProperty(),
            default_arguments={
                '--job-language': 'python',
                '--additional-python-modules': 'botocore==1.18.5,boto3==1.15.5',
            },
            execution_property=glue.CfnJob.ExecutionPropertyProperty(
                max_concurrent_runs=1
            ),
            glue_version='2.0', # <- this is where the issue is (using '2' also doesn't work)
            max_capacity=2,
            max_retries=0,
            name='Job',
            role=glue_role.role_arn,
            security_configuration=glue_security_config.name,
        )
```

### What did you expect to happen?

I'd expect this to pass through jsii with `cdk` commands.

### What actually happened?

But this happens:

```bash
cdk diff
jsii.errors.JavaScriptError: 
  Error: Expected a string, got 2 (number)
      at Object.deserialize (/private/var/folders/gh/gxw44cxd1pzbbx7mrg2pgj39y1zqhh/T/tmpklzim9k0/lib/program.js:8870:31)
      at Kernel._toSandbox (/private/var/folders/gh/gxw44cxd1pzbbx7mrg2pgj39y1zqhh/T/tmpklzim9k0/lib/program.js:8505:69)
      at /private/var/folders/gh/gxw44cxd1pzbbx7mrg2pgj39y1zqhh/T/tmpklzim9k0/lib/program.js:9070:37
      at mapValues (/private/var/folders/gh/gxw44cxd1pzbbx7mrg2pgj39y1zqhh/T/tmpklzim9k0/lib/program.js:9341:35)
      at Object.deserialize (/private/var/folders/gh/gxw44cxd1pzbbx7mrg2pgj39y1zqhh/T/tmpklzim9k0/lib/program.js:9066:28)
      at Kernel._toSandbox (/private/var/folders/gh/gxw44cxd1pzbbx7mrg2pgj39y1zqhh/T/tmpklzim9k0/lib/program.js:8505:69)
      at /private/var/folders/gh/gxw44cxd1pzbbx7mrg2pgj39y1zqhh/T/tmpklzim9k0/lib/program.js:8553:42
      at Array.map (<anonymous>)
      at Kernel._boxUnboxParameters (/private/var/folders/gh/gxw44cxd1pzbbx7mrg2pgj39y1zqhh/T/tmpklzim9k0/lib/program.js:8553:27)
      at Kernel._toSandboxValues (/private/var/folders/gh/gxw44cxd1pzbbx7mrg2pgj39y1zqhh/T/tmpklzim9k0/lib/program.js:8539:29)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "app.py", line 9, in <module>
    GlueStack(app, "glue")
  File "/Users/scottmcallister/Desktop/glue/.venv/lib/python3.8/site-packages/jsii/_runtime.py", line 83, in __call__
    inst = super().__call__(*args, **kwargs)
  File "/Users/scottmcallister/Desktop/glue/glue/glue_stack.py", line 22, in __init__
    glue_job = glue.CfnJob(
  File "/Users/scottmcallister/Desktop/glue/.venv/lib/python3.8/site-packages/jsii/_runtime.py", line 83, in __call__
    inst = super().__call__(*args, **kwargs)
  File "/Users/scottmcallister/Desktop/glue/.venv/lib/python3.8/site-packages/aws_cdk/aws_glue/__init__.py", line 3359, in __init__
    jsii.create(CfnJob, self, [scope, id, props])
  File "/Users/scottmcallister/Desktop/glue/.venv/lib/python3.8/site-packages/jsii/_kernel/__init__.py", line 275, in create
    response = self.provider.create(
  File "/Users/scottmcallister/Desktop/glue/.venv/lib/python3.8/site-packages/jsii/_kernel/providers/process.py", line 344, in create
    return self._process.send(request, CreateResponse)
  File "/Users/scottmcallister/Desktop/glue/.venv/lib/python3.8/site-packages/jsii/_kernel/providers/process.py", line 326, in send
    raise JSIIError(resp.error) from JavaScriptError(resp.stack)
jsii.errors.JSIIError: Expected a string, got 2 (number)
```

### Environment

  - **CDK CLI Version  :** 1.91.0
  - **Framework Version:** 1.95.1 (also tried with 1.87.1)
  - **Node.js Version:** v15.10.0
  - **OS:** macOs Catalina 10.15.6 (19G2021)
  - **Language (Version):** python 3.8.7

--- 

This is :bug: Bug Report

**Comment by csmcallister** [comment]
Just reloaded the project and it works. Looks like I made a mistake with the `max_capacity` argument!
