### ISSUE TITLE
(aws-lambda): Problem when using lambda.DockerImageCode.fromImageAsset

### ISSUE THREAD

**Issue by bigkraig** [aws/aws-cdk#14008]
I'm converting a Lambda function from `lambda.DockerImageCode.fromEcr` to `lambda.DockerImageCode.fromImageAsset`, but I am receiving this error when the asset is published.

I have two environments that I am deploying to, one is working.

The working account is using credentials provisioned to the same account.

The account that is failing has credentials provisioned in a separate account (111111111111), and is assuming roles inside of the destination account (222222222222). This is working for s3 assets with`file-publishing-role`. 

```
Retrieved account ID 111111111111 from disk cache                                                                                            
Assuming role 'arn:aws:iam::222222222222:role/cdk-cwf-file-publishing-role-222222222222-us-west-2'.                                          
[75%] check: Check s3://cdk-cwf-assets-222222222222-us-west-2/9e2b83ddc6e64b5dd22d71c91ce9dd432afb6c323b7e57fd43a71563e3180ea7.json          
[75%] upload: Upload s3://cdk-cwf-assets-222222222222-us-west-2/9e2b83ddc6e64b5dd22d71c91ce9dd432afb6c323b7e57fd43a71563e3180ea7.json        
[87%] success: Published 9e2b83ddc6e64b5dd22d71c91ce9dd432afb6c323b7e57fd43a71563e3180ea7:222222222222-us-west-2                             
[87%] start: Publishing d8f8caea493a75f5314d21633b02c94c61f7242a6001a98c30f455e478a101f5:833710463778-us-west-2                              
Retrieved account ID 111111111111 from disk cache                                                                                            
Assuming role 'arn:aws:iam::222222222222:role/cdk-cwf-image-publishing-role-222222222222-us-west-2'.                                         
[100%] fail: Need to perform AWS calls for account 222222222222, but the current credentials are for 111111111111                            
```

### Environment

  - **CDK CLI Version  :** 1.97.0
  - **Framework Version:** 1.97.0
  - **Node.js Version:** v14.16.0
  - **OS               :** MacOS & Linux
  - **Language (Version):** 

### Other

--- 

This is :bug: Bug Report

**Comment by nija-at** [comment]
Hi @bigkraig -

Thanks for filing this issue. The amount of information you've provided here is not sufficient for us to determine what happened.

Can you provide a short example and reproduction steps? Here are some guidelines - http://sscce.org/

**Comment by bigkraig** [comment]
> Hi @bigkraig -
> 
> Thanks for filing this issue. The amount of information you've provided here is not sufficient for us to determine what happened.
> 
> Can you provide a short example and reproduction steps? Here are some guidelines - http://sscce.org/

I was able to get more details as to what is going on by running `cdk-assets publish -v` directly. The error from cdk is misleading, as this shows a timeout on docker login.

```
info   : [87%] start: Publishing 1edb7bc1bf6c7f846c5b5d1fe98a7e0579ff2c67dbc44e6dc5a2c9d2d7dfa5f0:222222222222-us-west-2
verbose: Assume arn:aws:iam:: 222222222222:role/cdk-cwf-image-publishing-role-222222222222-us-west-2
verbose: [87%] check: Check 222222222222.dkr.ecr.us-west-2.amazonaws.com/cdk-cwf-container-assets-222222222222-us-west-2:1edb7bc1bf6c7f846c5b5d1fe98a7e0579ff2c67dbc44e6dc5a2c9d2d7dfa5f0
verbose: [87%] debug: docker login --username AWS --password-stdin https://222222222222.dkr.ecr.us-west-2.amazonaws.com
error  : [100%] fail: docker login --username AWS --password-stdin https://222222222222.dkr.ecr.us-west-2.amazonaws.com exited with error code 1: Error response from daemon: Get https://222222222222.dkr.ecr.us-west-2.amazonaws.com/v2/: net/http: request canceled (Client.Timeout exceeded while awaiting headers)
Failure: Error: docker login --username AWS --password-stdin https://222222222222.dkr.ecr.us-west-2.amazonaws.com exited with error code 1: Error response from daemon: Get https://222222222222.dkr.ecr.us-west-2.amazonaws.com/v2/: net/http: request canceled (Client.Timeout exceeded while awaiting headers)
    at ChildProcess.<anonymous> (/Users/kamador/src/content-web-frontend/sysops/cdk/node_modules/cdk-assets/lib/private/shell.js:46:24)
    at Object.onceWrapper (events.js:422:26)
    at ChildProcess.emit (events.js:315:20)
    at ChildProcess.EventEmitter.emit (domain.js:467:12)
    at maybeClose (internal/child_process.js:1048:16)
    at Socket.<anonymous> (internal/child_process.js:439:11)
    at Socket.emit (events.js:315:20)
    at Socket.EventEmitter.emit (domain.js:467:12)
    at Pipe.<anonymous> (net.js:673:12)
```
