### ISSUE TITLE
elasticloadbalancingv2: NetworkListener with TLS protocol and Certificate causes circular reference

### ISSUE THREAD

**Issue by rkane2002** [aws/aws-cdk#14024]
When creating a NetworkLoadBalancer with a listener configured for TLS termination and a ACM certificate associated synthesizing the stack fails with a circular reference error.  

### Reproduction Steps

```python
from aws_cdk import core
import aws_cdk.aws_elasticloadbalancingv2 as elbv2
import aws_cdk.aws_route53 as r53
import aws_cdk.aws_certificatemanager as acm
import aws_cdk.aws_ec2 as ec2

class TestStack(core.Stack):

    def __init__(self, scope: core.Construct, construct_id: str, **kwargs):
        super().__init__(scope, construct_id, **kwargs)
    
        vpc = ec2.Vpc.from_lookup(self, "VPC", vpc_id = "vpc-12345")
        hosted_zone = r53.HostedZone.from_lookup(self, "HostedZone", domain_name="test.com")

        subnets =  [
                        ec2.Subnet.from_subnet_attributes(self, "Subnet1", 
                                                                subnet_id="subnet-12345",
                                                                availability_zone="us-east-1a"),
                        ec2.Subnet.from_subnet_attributes(self, "Subnet2", 
                                                                subnet_id="subnet-12345",
                                                                availability_zone="us-east-1b")
                    ]

        

        cert = acm.Certificate(self, "Certificate",
                               domain_name = "foo.test.com",
                               validation = acm.CertificateValidation.from_dns(hosted_zone))

        lb = elbv2.NetworkLoadBalancer(self, "PubNLB",
                                       cross_zone_enabled=True,
                                       vpc=vpc,
                                       internet_facing=True,
                                       vpc_subnets=ec2.SubnetSelection(subnets=subnets))

        tg = elbv2.NetworkTargetGroup(self, "TG",
                                      protocol=elbv2.Protocol.TCP,
                                      port=80, 
                                      target_type=elbv2.TargetType.INSTANCE,                                     
                                      vpc=vpc)
        
        lb.add_listener("TLSListener",
                        certificates=[cert],
                        port=443,
                        protocol=elbv2.Protocol.TLS,
                        default_target_groups=[tg])
```

### What did you expect to happen?

I should get a valid stack with an internet facing NLB, listening on 443 using the ACM certificate for TLS termination.

### What actually happened?

Synth fails with a circular reference error.

### Environment

  - **CDK CLI Version  :** 1.97.0
  - **Framework Version:** 1.97.0
  - **Node.js Version:** 10.19.0
  - **OS               :** Ubuntu 20.04 LTS
  - **Language (Version):** Python 3.8

### Other

Stacktrace for the exception:

```
jsii.errors.JavaScriptError: 
  Error: Resolution error: Resolution error: Unable to resolve object tree with circular reference. Path: /Resources/${Token[test.TLSListenter.Resource.LogicalID.106]}/Properties/certificates/0/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host..
      at resolve (/tmp/jsii-kernel-1uXPAm/node_modules/@aws-cdk/core/lib/private/resolve.js:63:15)
      at Object.resolve (/tmp/jsii-kernel-1uXPAm/node_modules/@aws-cdk/core/lib/private/resolve.js:57:48)
      at resolve (/tmp/jsii-kernel-1uXPAm/node_modules/@aws-cdk/core/lib/private/resolve.js:143:51)
      at Object.resolve (/tmp/jsii-kernel-1uXPAm/node_modules/@aws-cdk/core/lib/private/resolve.js:57:48)
      at resolve (/tmp/jsii-kernel-1uXPAm/node_modules/@aws-cdk/core/lib/private/resolve.js:143:51)
      at Object.resolve (/tmp/jsii-kernel-1uXPAm/node_modules/@aws-cdk/core/lib/private/resolve.js:57:48)
      at resolve (/tmp/jsii-kernel-1uXPAm/node_modules/@aws-cdk/core/lib/private/resolve.js:143:51)
      at Object.resolve (/tmp/jsii-kernel-1uXPAm/node_modules/@aws-cdk/core/lib/private/resolve.js:57:48)
      at resolve (/tmp/jsii-kernel-1uXPAm/node_modules/@aws-cdk/core/lib/private/resolve.js:143:51)
      at Object.resolve (/tmp/jsii-kernel-1uXPAm/node_modules/@aws-cdk/core/lib/private/resolve.js:57:48)
```

--- 

This is :bug: Bug Report

**Comment by njlynch** [comment]
This error is unfortunately quite misleading. In my experience, an error referencing `0/node/host/node/host/node/host.....` means that the wrong type is being passed in somewhere.

In your case, it's the `certificates=[cert],`. Per the [add_listener](https://docs.aws.amazon.com/cdk/api/latest/python/aws_cdk.aws_elasticloadbalancingv2/ApplicationLoadBalancer.html#aws_cdk.aws_elasticloadbalancingv2.ApplicationLoadBalancer.add_listener) docs, the `certificates` type should be an array of `IListenerCertificate`, which is implemented by [`ListenerCertificate`](https://docs.aws.amazon.com/cdk/api/latest/python/aws_cdk.aws_elasticloadbalancingv2/ListenerCertificate.html#aws_cdk.aws_elasticloadbalancingv2.ListenerCertificate.from_certificate_manager).

Instead of `certificates=[cert]`, try `certificates=[elbv2.ListenerCertificate.from_certificate_manager(cert)]`. That will resolve the error.

Closing this out, but please comment and mention me if you need anything else!
