### ISSUE TITLE
Can't import aws_cdk vip python3: AttributeError: '_NodeProcess' object has no attribute '_process'

### ISSUE THREAD

**Issue by Tusenka** [aws/aws-cdk#14040]
### Reproduction Steps
install aws_cdk
unisntall/install jessi
![image](https://user-images.githubusercontent.com/7852737/113993872-8f63e080-985d-11eb-8b82-aa7e7f438345.png)

Run 
`import os
import string

from aws_cdk import (
    aws_s3 as _s3,
    aws_cloudfront as _cloudfront,
    aws_cloudfront_origins as _cloudfront_origins,
    core,
    aws_certificatemanager as _aws_certificatemanager
)`

### What did you expect to happen?
app.py return empty result

### What actually happened?
AttributeError: '_NodeProcess' object has no attribute '_process'
![image](https://user-images.githubusercontent.com/7852737/113994145-cfc35e80-985d-11eb-8f79-1f47818fb9a1.png)
log:
`Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/importlib/resources.py", line 188, in path
    yield Path(reader.resource_path(resource))
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/jsii/_runtime.py", line 43, in load
    _kernel.load(assembly.name, assembly.version, os.fspath(assembly_path))
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/jsii/_kernel/__init__.py", line 254, in load
    self.provider.load(LoadRequest(name=name, version=version, tarball=tarball))
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/jsii/_kernel/providers/process.py", line 338, in load
    return self._process.send(request, LoadResponse)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/jsii/_utils.py", line 24, in wrapped
    stored.append(fgetter(self))
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/jsii/_kernel/providers/process.py", line 333, in _process
    process.start()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/jsii/_kernel/providers/process.py", line 259, in start
    env=environ,
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/subprocess.py", line 769, in __init__
    restore_signals, start_new_session)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/subprocess.py", line 1516, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'node': 'node'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/igracheva/IdeaProjects/aws-cdk-s3-cloudfront/app.py", line 4, in <module>
    from aws_cdk import (
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/aws_cdk/aws_s3/__init__.py", line 465, in <module>
    from ._jsii import *
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/aws_cdk/aws_s3/_jsii/__init__.py", line 11, in <module>
    import aws_cdk.aws_events._jsii
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/aws_cdk/aws_events/__init__.py", line 214, in <module>
    from ._jsii import *
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/aws_cdk/aws_events/_jsii/__init__.py", line 11, in <module>
    import aws_cdk.aws_iam._jsii
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/aws_cdk/aws_iam/__init__.py", line 489, in <module>
    from ._jsii import *
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/aws_cdk/aws_iam/_jsii/__init__.py", line 11, in <module>
    import aws_cdk.core._jsii
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/aws_cdk/core/__init__.py", line 910, in <module>
    from ._jsii import *
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/aws_cdk/core/_jsii/__init__.py", line 11, in <module>
    import aws_cdk.cloud_assembly_schema._jsii
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/aws_cdk/cloud_assembly_schema/__init__.py", line 75, in <module>
    from ._jsii import *
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/aws_cdk/cloud_assembly_schema/_jsii/__init__.py", line 15, in <module>
    "cloud-assembly-schema@1.94.1.jsii.tgz",
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/jsii/_runtime.py", line 43, in load
    _kernel.load(assembly.name, assembly.version, os.fspath(assembly_path))
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/contextlib.py", line 161, in __exit__
    raise RuntimeError("generator didn't stop after throw()")
RuntimeError: generator didn't stop after throw()
Exception ignored in: <function _NodeProcess.__del__ at 0x7feaf84cdea0>
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/jsii/_kernel/providers/process.py", line 224, in __del__
    self.stop()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/jsii/_kernel/providers/process.py", line 281, in stop
    if not self._process.stdin.closed:
AttributeError: '_NodeProcess' object has no attribute '_process'`

### Environment

  - **CDK CLI Version  :**
  - **Framework Version:**
  - **Node.js Version:** 
  - **OS               :**
  - **Language (Version):** 

### Other

--- 

This is :bug: Bug Report

**Comment by Tusenka** [comment]
OS: Mac Big Mister 11.2.2

**Comment by Tusenka** [comment]
cured by restarting
Sorry.

**Comment by peterwoodworth** [comment]
@Tusenka is there any need for me to look into this or did you figure it out?

**Comment by peterwoodworth** [comment]
It looks like you've got it, ping me if you need this opened again.
