### ISSUE TITLE
ec2: InterfaceVpcEndpoint does not like vpc from_lookup

### ISSUE THREAD

**Issue by timwelch** [aws/aws-cdk#14066]
When running this code:

```

        self.vpc = ec2.Vpc.from_lookup(
            self,
            id=rekor.id_str('vpc'),
            vpc_name=self.vpc_name,
            is_default=False
        )
        self.private_subnets = ec2.SubnetSelection(
            one_per_az=True,
            subnet_group_name="app"
            )

        self.interface_vpc_endpoint_service = _ec2.InterfaceVpcEndpointService(
            name='com.amazonaws.' + self.region + '.execute-api',
            port=443
        )

        self.vpc_endpoint = _ec2.InterfaceVpcEndpoint(
            self,
            rekor.id_str('apigw-vpcendpoint'),
            service=self.interface_vpc_endpoint_service,
            vpc=self.vpc,
            subnets=self.private_subnets,
            private_dns_enabled=True
        )
```

The expected outcome would be a successful cdk diff and deploy.
The results however, on a brand new pull from github without a cdk.context.json already existing with the VPC information inside of it... is a stacktrace with this error:

```
jsii.errors.JSIIError: Cannot create a VPC Endpoint with no subnets

```

IF I comment the InterfaceVpcEndpoint resource out ... and run the cdk diff, then I get a valid DIFF and the cdk.context.json file is created with the vpc from_lookup successfully finding subnets .

After that initial cdk diff, I can uncomment the InterfaceVpcEndpoint resource and the cdk diff now runs and deploy runs fine. This is not cohesive to a jenkins pipeline, where I won't be baking in that synthesized cdk.context.json file, and I don't want to write a special script to comment out the InterfaceVpcEndpoint resource (and subsequent resources that are using it) in order to synth that cdk.context.json file.

### Reproduction Steps

Repro steps are above in the code I pasted.

### What did you expect to happen?

Expected the CDK DIFF to run successfully, generating the cdk.context.json file and then allowing me to run cdk deploy.

### What actually happened?

Error somehow running the vpc from_lookup to grab the subnets inside of the vpc.

### Environment

  - **CDK CLI Version  : 1.97.0 (build c52c2dc) **
  - **Framework Version: python 3.7 **
  - **Node.js Version: v15.3.0 (MacOS) and v12.22.1 (AmazonLinux 2) **
  - **OS               : MacOS 11.2.1 BigSur and AmazonLinux 2 **
  - **Language (Version): 3.9.0 (MacOS) and 3.7.9 (AmazonLinux 2) **

### Other

StackTrace

```
jsii.errors.JavaScriptError: 
  Error: Cannot create a VPC Endpoint with no subnets
      at InterfaceVpcEndpoint.endpointSubnets (/private/var/folders/zc/bb72t8fx5255j0kh02z5bpy80000gn/T/jsii-kernel-yUL9L6/node_modules/@aws-cdk/aws-ec2/lib/vpc-endpoint.js:435:19)
      at new InterfaceVpcEndpoint (/private/var/folders/zc/bb72t8fx5255j0kh02z5bpy80000gn/T/jsii-kernel-yUL9L6/node_modules/@aws-cdk/aws-ec2/lib/vpc-endpoint.js:388:32)
      at /private/var/folders/zc/bb72t8fx5255j0kh02z5bpy80000gn/T/tmpu591svqa/lib/program.js:8154:58
      at Kernel._wrapSandboxCode (/private/var/folders/zc/bb72t8fx5255j0kh02z5bpy80000gn/T/tmpu591svqa/lib/program.js:8582:24)
      at Kernel._create (/private/var/folders/zc/bb72t8fx5255j0kh02z5bpy80000gn/T/tmpu591svqa/lib/program.js:8154:34)
      at Kernel.create (/private/var/folders/zc/bb72t8fx5255j0kh02z5bpy80000gn/T/tmpu591svqa/lib/program.js:7895:29)
      at KernelHost.processRequest (/private/var/folders/zc/bb72t8fx5255j0kh02z5bpy80000gn/T/tmpu591svqa/lib/program.js:9479:36)
      at KernelHost.run (/private/var/folders/zc/bb72t8fx5255j0kh02z5bpy80000gn/T/tmpu591svqa/lib/program.js:9442:22)
      at Immediate._onImmediate (/private/var/folders/zc/bb72t8fx5255j0kh02z5bpy80000gn/T/tmpu591svqa/lib/program.js:9443:46)
      at processImmediate (node:internal/timers:463:21)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/timothywelch/rekor/github/rekor-ops-tmate/cdks/tmate-persistence/app.py", line 31, in <module>
    _stack = TmateStack(
  File "/Users/timothywelch/env/lib/python3.9/site-packages/jsii/_runtime.py", line 83, in __call__
    inst = super().__call__(*args, **kwargs)
  File "/Users/timothywelch/rekor/github/rekor-ops-tmate/cdks/tmate-persistence/lib/tmate.py", line 131, in __init__
    self.lambdas = _lambdas(
  File "/Users/timothywelch/env/lib/python3.9/site-packages/jsii/_runtime.py", line 83, in __call__
    inst = super().__call__(*args, **kwargs)
  File "/Users/timothywelch/rekor/github/rekor-ops-tmate/cdks/tmate-persistence/lib/lambdas.py", line 87, in __init__
    self.vpc_endpoint = _ec2.InterfaceVpcEndpoint(
  File "/Users/timothywelch/env/lib/python3.9/site-packages/jsii/_runtime.py", line 83, in __call__
    inst = super().__call__(*args, **kwargs)
  File "/Users/timothywelch/env/lib/python3.9/site-packages/aws_cdk/aws_ec2/__init__.py", line 46410, in __init__
    jsii.create(InterfaceVpcEndpoint, self, [scope, id, props])
  File "/Users/timothywelch/env/lib/python3.9/site-packages/jsii/_kernel/__init__.py", line 275, in create
    response = self.provider.create(
  File "/Users/timothywelch/env/lib/python3.9/site-packages/jsii/_kernel/providers/process.py", line 344, in create
    return self._process.send(request, CreateResponse)
  File "/Users/timothywelch/env/lib/python3.9/site-packages/jsii/_kernel/providers/process.py", line 326, in send
    raise JSIIError(resp.error) from JavaScriptError(resp.stack)
jsii.errors.JSIIError: Cannot create a VPC Endpoint with no subnets
```

--- 

This is :bug: Bug Report

**Comment by rix0rrr** [comment]
> where I won't be baking in that synthesized cdk.context.json file

Regardless of everything else, and I agree this should work: our recommendation is still to commit the `cdk.context.json` file.

**Comment by timwelch** [comment]
> > where I won't be baking in that synthesized cdk.context.json file
> 
> Regardless of everything else, and I agree this should work: our recommendation is still to commit the `cdk.context.json` file.

I hear what you're saying, I do. But, we use Jenkins and create pipelines for CDK deployments.

So for that to work, our flow would need to alter a bit, which seems incongruent with a healthy deployment model. Imagine we do development of the CDK in a dev environment. So, ok, we can commit the cdk.context.json file for that. But, when we create the stage/prod pipelines to run off of master commits or whatever, we would then need to 'deploy' or at least 'diff' outside of the Jenkins into stage and/or prod to generate that cdk.context.json file. And then commit it back. But, developers don't even have access to Prod... Only Jenkins does. That completely breaks / changes / alters the way we would do pipelines. 

So I get that it could be helpful as an interim step, in the long-term, we would not be running cdk diffs / deploys outside of jenkins in order to create / stage / commit that cdk.context.json for every environment we deploy to.

**Comment by skinny85** [comment]
@timwelch maybe the discussion in https://github.com/aws/aws-cdk/issues/14006  is relevant for you?

**Comment by timwelch** [comment]
Reading the link presented in that issue I find that I am questioning how this can be true?

```
We recommend that your project's context files be placed under version control along with the rest of your application, as the information in them is part of your app's state and is critical to being able to synthesize and deploy consistently. It is also critical to successful automated deployment of stacks that rely on context values (for example, using CDK Pipelines): since the deployment system won't have access to your AWS account, it will rely on the cached values in the context files.
```

How can the CDK pipeline NOT have access to your AWS account? You cannot deploy to an account, create resources, edit resources, delete resources, without having ACCESS to the AWS account. 

Please explain further exactly how a CDK pipeline would NOT have access to do a vpc/subnet lookup or synth the things needed to create the context file?

**Comment by mrpackethead** [comment]
@rix0rrr .. how do you synth all the stacks that are in stages from teh CLI to even get them to populate cdk.context.json..

FYI. I have pipelines with multiple stages, each stage may have multiple stacks in differnet environments.     Synth creates them all, but they populate with the dummys values. ( as expected ).. 

 I've been looking at this  ( https://github.com/aws-samples/cdk-assume-role-credential-plugin ) to see if i can get it to do some work. 
 
 This lack of working Lookups is really problematic and the suggested approaches just dnt' cut it.   I've seriouslyk considered dtiching pipeline and just writign our own codepipeline..

**Comment by mrpackethead** [comment]
The other issue is.  In several situations we cant' even synth against an account. We dont' ( and never will ) have direct access to it. 

Work with these assumptions.. 

*WE* only have access to commit to a repo, that becomes the source of the pipeline.   ( somone will have done an inital cdk deploy to set it up )

The codebuild process that runs the synth step will have have permission to assume a 'readonly' role in the accounts where things are going to be deployed to.

**Comment by Jerry-AWS** [comment]
Following this; I'd like to make sure that what's in the Developer Guide is correct.

**Comment by khan-a1** [comment]
My current workaround for this is to have an init stack:
```
import * as cdk from '@aws-cdk/core';
import * as ec2 from '@aws-cdk/aws-ec2';
export class ContextInitStack extends cdk.Stack {
  constructor(scope: cdk.Construct, id: string, props: NetworkingProps) {
    super(scope, id, props);


    const stagingVPC = ec2.Vpc.fromLookup(this, 'migrationVPC', {
      vpcId: vpcId,
      isDefault: false
    });
  }
}

const app = new cdk.App();
new ContextInitStack(app, `ContextInitStack`, { })

}
```

and then have a script (initContext.sh) that first synths the dummy stack and then runs the main index.ts file. This way when the index.ts and associated stacks run, they already have the vpc details in the context file:

```
cdk -a "npx ts-node lib/context_init_stack.ts" synth
cdk -a "npx ts-node --prefer-ts-exts bin/index.ts" synth
```
Finally change the app key value to "  "app": "./initContext.sh" in the cdk.json file. I have multiple cross account stacks so I loop through them and run the Init stack once for each vpc lookup.

**Comment by ManukCipo** [comment]
> My current workaround for this is to have an init stack:
> 
> ```
> import * as cdk from '@aws-cdk/core';
> import * as ec2 from '@aws-cdk/aws-ec2';
> export class ContextInitStack extends cdk.Stack {
>   constructor(scope: cdk.Construct, id: string, props: NetworkingProps) {
>     super(scope, id, props);
> 
> 
>     const stagingVPC = ec2.Vpc.fromLookup(this, 'migrationVPC', {
>       vpcId: vpcId,
>       isDefault: false
>     });
>   }
> }
> 
> const app = new cdk.App();
> new ContextInitStack(app, `ContextInitStack`, { })
> 
> }
> ```
> 
> and then have a script (initContext.sh) that first synths the dummy stack and then runs the main index.ts file. This way when the index.ts and associated stacks run, they already have the vpc details in the context file:
> 
> ```
> cdk -a "npx ts-node lib/context_init_stack.ts" synth
> cdk -a "npx ts-node --prefer-ts-exts bin/index.ts" synth
> ```
> 
> Finally change the app key value to " "app": "./initContext.sh" in the cdk.json file. I have multiple cross account stacks so I loop through them and run the Init stack once for each vpc lookup.

I am having the same issue and I doing something similar. First initialize the new stack only running  **ec2.Vpc.fromLookup** using a VPC id from an existing VPC in the account then I am able to run the stack with all the configs I want to apply. If I don't initialize the new stack doing that the VPC info is not added to **cdk.context.json**

**Comment by m1n9o** [comment]
Yeah, I am having the same issue as well.

**Comment by giseburt** [comment]
For those looking into this as well, let me gather a few docs together and a workaround. I'll start with the workaround:

1. In your stack, use `const vpc = ec2.Vpc.fromLookup(...)`
2. Then, *before building anything that uses the `vpc`*, check to see if the `vpc` is fully formed, or "looked up". So far as I can tell, the only way to achieve this (without internal knowledge of the objects, which is fragile) is with subnets:
    ```typescript
    const vpc = ec2.Vpc.fromLookup(this, `VPC-to-lookup`, {
      vpcName
    });

    // grab the subnets just for the subnets.isPendingLookup property
    const subnets = vpc.selectSubnets();
    if (subnets.isPendingLookup) {
      // return before using the vpc, the cdk will rerun immediately after the lookup
      return;
    }
    ```
3. Then you can safely use the `vpc`, knowing that it's been looked up.

That works, in short, because the `cdk` utility will look at the synth results and if there are any pending lookups, it will execute them and rerun the synth. By returning if the vpc needs looked up, you both prevent an error in trying to use the vpc with dummy values as well as save some time building out other arch that'll be rebuilt anyway. (There may be some optimization here anyway, best not to assume, so I wouldn't lean on this last part too much.)

See docs [here](https://docs.aws.amazon.com/cdk/v2/guide/context.html#context_methods):

> If a required context value isn't available, the AWS CDK app notifies the AWS CDK CLI that the context information is missing. The CLI then queries the current AWS account for the information, stores the resulting context information in the `cdk.context.json` file, and executes the AWS CDK app again with the context values.

For a more long-term solution, I feel that many of the values in the [`DUMMY_VPC_PROPS`](https://github.com/aws/aws-cdk/blob/743b1f4f0124d9fd6d3b22e104303d39b3e37e67/packages/%40aws-cdk/aws-ec2/lib/vpc.ts#L2176-L2245) should be tokens, so that the checks such as those in [`ClientVpnEndpoint`](https://github.com/aws/aws-cdk/blob/743b1f4f0124d9fd6d3b22e104303d39b3e37e67/packages/%40aws-cdk/aws-ec2/lib/client-vpn-endpoint.ts#L296-L302) will detect that it's not a resolved value and do the right thing.

Of course choosing which ones to make tokens needs to be looked at carefully. But even if just the cider blocks (in the vpc and the subnets) were made into `vpcCidrBlock: Lazy.string({ produce: () => '1.2.3.4/5' }),` that would go a *long* way to making this transparent. As it is now, you can't call `vpc.addClientVpnEndpoint(...)` on a looked up vpc, as it'll fail that cider test linked to above.

**Comment by heitorlessa** [comment]
Having the same issue but without CDK CLI (we're using CDK as a lib and handling other operations ourselves [Asset bundling, Stack create/delete]) -- is there any chance these lookup dummy values can be `tokens` instead?

**Comment by Leo10Gama** [comment]
Hi, it seems like this issue has been open for quite a while, and I'm having trouble replicating it. If you're still facing this issue, could you provide some steps on how I can reproduce it?

**Comment by Leo10Gama** [comment]
Closing this issue due to not receiving a response for quite some time. If the problem still persists, please open a new issue with updated reproducible code so we can best resolve it.
