### ISSUE TITLE
core: App with multiple stacks requires exact same --context vars for each stack deploy command

### ISSUE THREAD

**Issue by lindsaybloomsonos** [aws/aws-cdk#14083]
I have an app that has 2 stacks (1 for staging env and 1 for production env). When I run the `cdk deploy` command for the production stack, using only the context vars that stack requires, I would get the following error: 

```bash
.../node_modules/monocdk/lib/aws-secretsmanager/lib/secret.ts:336
        class Import extends SecretBase implements ISecretTargetAttachment {
                      ^
Error: must use only one of `secretCompleteArn` or `secretPartialArn`
    at Function.fromSecretAttributes (.../node_modules/monocdk/lib/aws-secretsmanager/lib/secret.ts:336:23)
    at Function.fromSecretCompleteArn (.../node_modules/monocdk/lib/aws-secretsmanager/lib/secret.ts:263:23)
    at new NextJSFargateService (.../node_modules/@sonos-inc/cdk-nextjs/src/cdk-nextjs-fargate-service.ts:86:29)
    at new NextJsTemplateApplicationStack (.../cdk/stacks/application-stack.ts:15:29)
    at Object.<anonymous> (.../cdk/index.ts:10:1)
    at Module._compile (internal/modules/cjs/loader.js:1137:30)
    at Module.m._compile (.../.npm/_npx/1bf7c3c15bf47d04/node_modules/ts-node/src/index.ts:1056:23)
    at Module._extensions..js (internal/modules/cjs/loader.js:1157:10)
    at Object.require.extensions.<computed> [as .ts] (.../.npm/_npx/1bf7c3c15bf47d04/node_modules/ts-node/src/index.ts:1059:12)
    at Module.load (internal/modules/cjs/loader.js:985:32)
```

The only way around this error was to include the same `--context` values in the `cdk deploy` command that are required for my staging stack.

### Reproduction Steps

Create a cdk App that has 2 stacks. For example:
```js
import { App } from "monocdk"
import { StagingStack } from "./stacks/application-stack"
import { ProdStack } from "./stacks/prod-stack"

const app = new App()

new StagingStack(app, "StagingStack", {
<some args>
})

new ProdStack(app, "ProductionStack", {
<some args>
})
```

The `StagingStack` should accept some context vars, and the `ProductionStack` should accept some different context vars (e.g.  `const domainName = this.node.tryGetContext("domainName")`).

Try running `cdk deploy ProductionStack --context domainName=example.com`.

### What did you expect to happen?

The stack should deploy with no errors.

### What actually happened?

```bash
.../node_modules/monocdk/lib/aws-secretsmanager/lib/secret.ts:336
        class Import extends SecretBase implements ISecretTargetAttachment {
                      ^
Error: must use only one of `secretCompleteArn` or `secretPartialArn`
    at Function.fromSecretAttributes (.../node_modules/monocdk/lib/aws-secretsmanager/lib/secret.ts:336:23)
    at Function.fromSecretCompleteArn (.../node_modules/monocdk/lib/aws-secretsmanager/lib/secret.ts:263:23)
    at new NextJSFargateService (.../node_modules/@sonos-inc/cdk-nextjs/src/cdk-nextjs-fargate-service.ts:86:29)
    at new NextJsTemplateApplicationStack (.../cdk/stacks/application-stack.ts:15:29)
    at Object.<anonymous> (.../cdk/index.ts:10:1)
    at Module._compile (internal/modules/cjs/loader.js:1137:30)
    at Module.m._compile (.../.npm/_npx/1bf7c3c15bf47d04/node_modules/ts-node/src/index.ts:1056:23)
    at Module._extensions..js (internal/modules/cjs/loader.js:1157:10)
    at Object.require.extensions.<computed> [as .ts] (.../.npm/_npx/1bf7c3c15bf47d04/node_modules/ts-node/src/index.ts:1059:12)
    at Module.load (internal/modules/cjs/loader.js:985:32)
```

### Environment

  - **CDK CLI Version  : 2.1.18
  - **Framework Version: 1.96.0
  - **Node.js Version: 12.18.4
  - **OS             MacOS  : 10.15.7
  - **Language (Version): TypeScript

This is :bug: Bug Report

**Comment by rix0rrr** [comment]
Yep, this is a consequence of how error reporting has been designed.

There's unfortunately not really a lot we can do about that now. Best I can give you is to NOT instantiate one of the stacks that depend on some context that may not be present.
