### ISSUE TITLE
(aws-lambda-nodejs): Docker failures do not stop stack deployment

### ISSUE THREAD

**Issue by nihalgonsalves** [aws/aws-cdk#14115]
Docker failures do not stop the execution and deployment of a CDK stack.

This applies to both the actual Docker bundling command and the command hooks.

### Reproduction Steps

1. For example, stop the Docker daemon and try deploying a stack with a `NodejsFunction`:
    
    ```sh
    $ <redacted>/node_modules/.bin/cdk deploy -c <redacted>
    $ <redacted>/node_modules/.bin/ts-node --prefer-ts-exts --project ./tsconfig.json cdk/cdk.ts
    Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
    ERRO[0000] Can't add file <redacted>/node_modules/@aws-cdk/aws-lambda-nodejs/lib/bundling.js to tar: io: read/write on closed pipe
    Error: docker exited with status 1
        at dockerExec (<redacted>/node_modules/@aws-cdk/core/lib/bundling.ts:455:11)
        at Function.fromBuild (<redacted>/node_modules/@aws-cdk/core/lib/bundling.ts:271:5)
        at new Bundling (<redacted>/node_modules/@aws-cdk/aws-lambda-nodejs/lib/bundling.ts:81:46)
        at Function.bundle (<redacted>/node_modules/@aws-cdk/aws-lambda-nodejs/lib/bundling.ts:40:17)
        at new NodejsFunction (<redacted>/node_modules/@aws-cdk/aws-lambda-nodejs/lib/function.ts:116:22)
        at InfraStack.lambdaFunction (<redacted>/<redacted-b>/cdk/infra.ts:243:12)
        at <redacted>/<redacted-b>/cdk/infra.ts:52:50
        at new InfraStack (<redacted>/<redacted-b>/cdk/infra.ts:101:7)
        at setup (<redacted>/<redacted-b>/cdk/cdk.ts:59:22)
        at processTicksAndRejections (node:internal/process/task_queues:94:5)
    <redacted>: deploying...
    <redacted>: creating CloudFormation changeset...
    [██████████████████████████████████████████████████████████] (62/62)
    
     ✅  <redacted>
    
    Stack ARN:
    arn:aws:cloudformation:eu-central-1:<redacted>
    ```

2. Or use a command hook which exits with a non-zero exit code:
    
    ```sh
    Error: Failed to bundle asset <redacted>, bundle output is located at <redacted>/<redacted-b>/cdk.out/bundling-temp-xxx-error: Error: docker exited with status 1
        at AssetStaging.bundle (<redacted>/node_modules/@aws-cdk/core/lib/asset-staging.ts:472:13)
        at AssetStaging.stageByBundling (<redacted>/node_modules/@aws-cdk/core/lib/asset-staging.ts:330:10)
        at stageThisAsset (<redacted>/node_modules/@aws-cdk/core/lib/asset-staging.ts:196:35)
        at Cache.obtain (<redacted>/node_modules/@aws-cdk/core/lib/private/cache.ts:24:13)
        at new AssetStaging (<redacted>/node_modules/@aws-cdk/core/lib/asset-staging.ts:221:44)
        at new Asset (<redacted>/node_modules/@aws-cdk/aws-s3-assets/lib/asset.ts:127:21)
        at AssetCode.bind (<redacted>/node_modules/@aws-cdk/aws-lambda/lib/code.ts:277:20)
        at new Function (<redacted>/node_modules/@aws-cdk/aws-lambda/lib/function.ts:583:29)
        at new NodejsFunction (<redacted>/node_modules/@aws-cdk/aws-lambda-nodejs/lib/function.ts:113:5)
        at InfraStack.lambdaFunction (<redacted>/packages/service/vehicle-mission-sync/cdk/infra.ts:242:12)
    <redacted>: deploying...
    <redacted>: creating CloudFormation changeset...
    ```

In both cases, the error is reported, but CDK goes on to deploy the stack.

In the case of the Docker error, this was critical, because the functions were not synthesised, and what CDK went on to do was remove them entirely when deploying.

This is enough to showcase the second error:

```ts
import { NodejsFunction } from '@aws-cdk/aws-lambda-nodejs';

// ...

new NodejsFunction(this, 'foo', {
  functionName,
  entry: '...',
  handler: '...',
  bundling: {
    forceDockerBundling: true,
    commandHooks: {
      // this is enough to cause the error log but not fail the deployment
      afterBundling: () => ['exit 1'],
      beforeBundling: () => [],
      beforeInstall: () => [],
    },
  },
};
```
### What did you expect to happen?

Docker or commandHook errors should cause the deployment process to stop.

### What actually happened?

The invalid state is synthesised & deployed, hiding actual errors.

### Environment

  - **CDK CLI Version  :** 1.97.0 (build c52c2dc)
  - **Framework Version:** `"@aws-cdk/aws-lambda-nodejs": "^1.97.0",`
  - **Node.js Version:**  v15.14.0
  - **OS               :** macOS Big Sur 11.2.1
  - **Language (Version):**  TypeScript (Version 4.2.3)

### Other

--- 

This is :bug: Bug Report

**Comment by eladb** [comment]
Copy @jogold

**Comment by jogold** [comment]
Looks like something in `core` when bundling.

@nihalgonsalves does it fail when running `cdk synth`?

Will try to reproduce.

**Comment by nihalgonsalves** [comment]
@jogold Same behaviour on synth, it's successful:

```sh
$ <>/.bin/cdk synth
$ <>/.bin/ts-node --prefer-ts-exts --project ./tsconfig.json cdk/cdk.ts
Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
Error: docker exited with status 1
    at dockerExec (<>/@aws-cdk/core/lib/bundling.ts:455:11)
    at Function.fromBuild (<>/@aws-cdk/core/lib/bundling.ts:271:5)
    at new Bundling (<>/@aws-cdk/aws-lambda-nodejs/lib/bundling.ts:81:46)
    at Function.bundle (<>/@aws-cdk/aws-lambda-nodejs/lib/bundling.ts:40:17)
    at new NodejsFunction (<>/@aws-cdk/aws-lambda-nodejs/lib/function.ts:116:22)
    at InfraStack.lambdaFunction (<>/cdk/infra.ts:243:16)
    at <>/cdk/infra.ts:52:50
    at new InfraStack (<>/cdk/infra.ts:101:7)
    at setup (<>/cdk/cdk.ts:59:22)
    at processTicksAndRejections (node:internal/process/task_queues:94:5)
Successfully synthesized to <>/cdk.out
Supply a stack id (<>, <>, <>, ...) to display its template.
```

**Comment by jogold** [comment]
Cannot reproduce... just to rule out something linked to error handling: what happens when you add a `throw new Error('test');` before the `new NodejsFunction(...)`?

**Comment by nihalgonsalves** [comment]
@jogold I should've tried that before, that was the issue:

We had something like this in our entry CDK file:

```ts
const app = new cdk.App();

const setup = async () => {
  // other setup tasks

  // ...

  new FooStack(app, ...);
}

setup().catch((err) => console.error(err));
```

The catch swallowed the error of course.

Sorry for the bother and thanks for the help!
