### ISSUE TITLE
(aws-lambda-nodejs): Runtime.ImportModuleError aws-sdk dependency

### ISSUE THREAD

**Issue by hugomallet** [aws/aws-cdk#14188]
Hi,

I'm trying to use the lambda nodejs bundling but I have a runtime error: 

```sh
Runtime.ImportModuleError: Error: Cannot find module 'aws-sdk/lib/config_service_placeholders',
        Require stack:,
        - /var/task/index.js,
        - /var/runtime/UserFunction.js,
        - /var/runtime/index.js,
            at _loadUserApp (/var/runtime/UserFunction.js:100:13),
            at Object.module.exports.load (/var/runtime/UserFunction.js:140:17),
            at Object.<anonymous> (/var/runtime/index.js:43:30),
            at Module._compile (internal/modules/cjs/loader.js:999:30),
            at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10),
            at Module.load (internal/modules/cjs/loader.js:863:32),
            at Function.Module._load (internal/modules/cjs/loader.js:708:14),
            at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:60:12),
            at internal/main/run_main_module.js:17:47
```

My config : 
```js
new NodejsFunction(this, 'Function', {
    bundling: {
        externalModules: [
            'aws-sdk', // Use the 'aws-sdk' available in the Lambda runtime
            'mongodb-client-encryption',
        ],
        forceDockerBundling: true,
        nodeModules: [
            'mongoose',
        ],
        sourceMap: true,
    },
    entry: './index.js',
    handler: 'handler',
    runtime: Runtime.NODEJS_14_X,
});
```

I tried to move aws-sdk to nodeModules field but it didn't change anything.

**Comment by hugomallet** [comment]
Finally found the error. vscode automatically imported a wrong file into my code 🤯 😡  

This was the cause somewhere in my code : 
```js
const { ConfigurationServicePlaceholders } = require('aws-sdk/lib/config_service_placeholders');
```
