### ISSUE TITLE
aws-cdk: Unhandled exception. Amazon.JSII.Runtime.JsiiException: Cannot find a package lock file (`yarn.lock` or `package-lock.json`). Please specify it with `depsFileLockPath`.

### ISSUE THREAD

**Issue by viventra** [aws/aws-cdk#14193]
### The Question

I created a CDK project for testing Lambda@Edge. While doing `cdk synth` or `cdk deploy`, I get the following error:

```
Unhandled exception. Amazon.JSII.Runtime.JsiiException: Cannot find a package lock file (`yarn.lock` or `package-lock.json`). Please specify it with `depsFileLockPath`.
   at Amazon.JSII.Runtime.Services.Client.TryDeserialize[TResponse](String responseJson)
   at Amazon.JSII.Runtime.Services.Client.ReceiveResponse[TResponse]()
   at Amazon.JSII.Runtime.Services.Client.Send[TRequest,TResponse](TRequest requestObject)
   at Amazon.JSII.Runtime.Services.Client.Create(CreateRequest request)
   at Amazon.JSII.Runtime.Services.Client.Create(String fullyQualifiedName, Object[] arguments, Override[] overrides, String[] interfaces)
   at Amazon.JSII.Runtime.Deputy.DeputyBase..ctor(DeputyProps props)
   at Constructs.Construct..ctor(DeputyProps props)
   at Amazon.CDK.Construct..ctor(DeputyProps props)
   at Amazon.CDK.Resource..ctor(DeputyProps props)
   at Amazon.CDK.AWS.Lambda.FunctionBase..ctor(DeputyProps props)
   at Amazon.CDK.AWS.Lambda.Function..ctor(DeputyProps props)
   at Amazon.CDK.AWS.Lambda.Nodejs.NodejsFunction..ctor(Construct scope, String id, INodejsFunctionProps props)
   at Authlambda.AuthlambdaFunction..ctor(Construct scope, String id, NodejsFunctionProps props) in D:\Giri\temp\authlambda\src\Authlambda\AuthlambdaFunctionsStack.cs:line 26
   at Authlambda.AuthlambdaFunctionsStack..ctor(Construct scope, String id, AuthlambdaFunctionsStackProps props) in D:\Giri\temp\authlambda\src\Authlambda\AuthlambdaFunctionsStack.cs:line 38
   at Authlambda.Program.Main(String[] args) in D:\Giri\temp\authlambda\src\Authlambda\Program.cs:line 14
Subprocess exited with error 3762504530
```

### Environment

  - **CDK CLI Version:**  1.96.0 (build 39f3df8)
  - **Module Version:** 
  - **Node.js Version:**  v14.15.4
  - **OS:**  Microsoft Windows [Version 10.0.19042.867]
  - **Language (Version):**  CDK project language is C#, Lambda@Edge functions are in plain Javascript (Runtime version for Lambda@Edge is configured through CDK constructs at Runtime.NODEJS_10_X)

### Other information

AuthlambdaFunctionStack.cs:
```
using Amazon.CDK;
using Amazon.CDK.AWS.Lambda;
using Amazon.CDK.AWS.Lambda.Nodejs;

namespace Authlambda
{
    // The region for the lambda@edge functions must be us-east-1
    public class AuthlambdaFunctionsStackProps : StackProps 
    {
        public static Environment DefaultFunctionStackEnv = new Environment { Region = "us-east-1" };

        internal AuthlambdaFunctionsStackProps() {
            this.Env = DefaultFunctionStackEnv;
        }
    }

    // This helper class captures the handler function and version information.
    // The version information is required to attach the lambda@edge handler to cloudfront
    public class AuthlambdaFunction
    {
        public NodejsFunction function;
        public Version_ version;

        internal AuthlambdaFunction(Construct scope, string id, NodejsFunctionProps props)
        {
            function = new NodejsFunction(scope, id, props);
            version = new Version_(scope, $"{id}version", new VersionProps() {
                Lambda = function
            });
        }
    }
    public class AuthlambdaFunctionsStack : Stack
    {
        public AuthlambdaFunction loginHandler;
        public AuthlambdaFunction checkAuthHandler;
        internal AuthlambdaFunctionsStack(Construct scope, string id, AuthlambdaFunctionsStackProps props = null) : base(scope, id, props)
        {
            loginHandler = new AuthlambdaFunction(this, "loginHandler", new NodejsFunctionProps() {
                Entry = "src/lambdaEdge/login.js",
                Handler = "handler",
                Runtime = Runtime.NODEJS_10_X
            });

            checkAuthHandler = new AuthlambdaFunction(this, "checkAuthHandler", new NodejsFunctionProps() {
                Entry = "src/lambdaEdge/checkAuth.js",
                Handler = "handler",
                Runtime = Runtime.NODEJS_10_X
            });
        }
    }
}
```

src/lambdaEdge/login.js:
```
'use strict';

exports.handler = (event, context, callback) => {
    const request = event.Records[0].cf.request;
    const headers = request.headers;

    /* URI encode the original request to be sent as redirect_url in query params */
    //const encodedRedirectUrl = encodeURIComponent(`https://${headers.host[0].value}${request.uri}?${request.querystring}`);
    const appstate = "loggedin";
    const sessionid = 123
    const response = {
        status: '200',
        multiValueHeaders: {
            'Set-Cookie': [`appstate=${appstate}`, `sessionid=${sessionid}`]
        },
    };
    callback(null, response);
};
```

My Program Main function that instantiates the stack. My cloudfront distribution is in the ap-south-1 region and is dependent on the lambda@Edge functions defined on the global us-west-1 region. I have commented out the cloudfront stack. So, the error is with the AuthlambdaFunctionStack. (The cloudfront stack alone without the dependency  deploys).

```
        public static void Main(string[] args)
        {
            var app = new App();

            var theFunctionsStack = new AuthlambdaFunctionsStack(app, "AuthlambdaFunctionsStack", new AuthlambdaFunctionsStackProps(){
            });

            /*
            new AuthlambdaStack(app, "AuthlambdaStack", new AuthlambdaStackProps() {
                functionsStack = theFunctionsStack
            });
            */
            app.Synth();
        }
```
I have bootstrapped CDK on `us-west-1` region.

So far, my Javascript has no external dependencies and I took the boilerplate Javascript code from AWS documentation for Lambda@Edge and modified it slightly. I have also tried adding a package.json to my lambdaEdge source folder.

What am I missing? How do I get a basic Javascript Lambda@Edge function working?

**Comment by viventra** [comment]
Found the fix!

```
            loginHandler = new AuthlambdaFunction(this, "loginHandler", new NodejsFunctionProps() {
                Entry = "src/lambdaEdge/login.js",
                Handler = "login.handler",
                Runtime = Runtime.NODEJS_10_X,
                DepsLockFilePath = "src/lambdaEdge/package-lock.json"      // This had to be changed to point to a package-lock.json file
            });

            checkAuthHandler = new AuthlambdaFunction(this, "checkAuthHandler", new NodejsFunctionProps() {
                Entry = "src/lambdaEdge/checkAuth.js",
                Handler = "checkAuth.handler",
                Runtime = Runtime.NODEJS_10_X,
                DepsLockFilePath = "src/lambdaEdge/package-lock.json"     // This had to be changed to point to a package-lock.json file
            });
```
