### ISSUE TITLE
(aws-cdk): `cdk synth` fails with Unhandled exception. Amazon.JSII.Runtime.JsiiException: Failed to bundle asset xxxx, bundle output is located at yyyy: Error: docker exited with status 1

### ISSUE THREAD

**Issue by viventra** [aws/aws-cdk#14203]
I have a CDK project in C# that is intended to deploy a test static site backed by S3 on cloudfront and Lamda@Edge functions for authorization at the cloudfront edge. I understand that Lambda@Edge needs to be deployed on us-east-1. My website deployment region is ap-south-1.

My CDK project has two stacks. One for deploying the Lambda@Edge on us-east-1 and my main stack for deploying the website on ap-south-1 (my default region). (At this time, I have commented out my main stack deployment due to this error as part of trying to isolate the problem)

My Lambda@Edge functions are written in plain Javascript and are configured for running on NodeJS 10.x runtime through the CDK construct.

When I run `cdk synth`, I get the following runtime error:

`cdk synth` fails with 
```
Unhandled exception. Amazon.JSII.Runtime.JsiiException: Failed to bundle asset xxxx, bundle output is located at yyyy: Error: docker exited with status 1
```

### Reproduction Steps

My Lambda@Edge deployment stack:

```
using Amazon.CDK;
using Amazon.CDK.AWS.Lambda;
using Amazon.CDK.AWS.Lambda.Nodejs;

namespace Authlambda
{
    // The region for the lambda@edge functions must be us-east-1
    public class AuthlambdaFunctionsStackProps : StackProps 
    {
        public static Environment DefaultFunctionStackEnv = new Environment { Region = "us-east-1" };

        internal AuthlambdaFunctionsStackProps() {
            this.Env = DefaultFunctionStackEnv;
        }
    }

    // This helper class captures the handler function and version information.
    // The version information is required to attach the lambda@edge handler to cloudfront
    public class AuthlambdaFunction
    {
        public NodejsFunction function;
        public Version_ version;

        internal AuthlambdaFunction(Construct scope, string id, NodejsFunctionProps props)
        {
            function = new NodejsFunction(scope, id, props);
            version = new Version_(scope, $"{id}version", new VersionProps() {
                Lambda = function
            });
        }
    }
    public class AuthlambdaFunctionsStack : Stack
    {
        public AuthlambdaFunction loginHandler;
        public AuthlambdaFunction checkAuthHandler;
        internal AuthlambdaFunctionsStack(Construct scope, string id, AuthlambdaFunctionsStackProps props = null) : base(scope, id, props)
        {
            var currentDir = System.Environment.CurrentDirectory;

            loginHandler = new AuthlambdaFunction(this, "loginHandler", new NodejsFunctionProps() {
                Entry = $"{currentDir}/src/lambdaEdge/login.js",
                Handler = "login.handler",
                Runtime = Runtime.NODEJS_10_X,
                DepsLockFilePath = $"{currentDir}/src/lambdaEdge/package-lock.json"
            });

            checkAuthHandler = new AuthlambdaFunction(this, "checkAuthHandler", new NodejsFunctionProps() {
                Entry = $"{currentDir}/src/lambdaEdge/checkAuth.js",
                Handler = "checkAuth.handler",
                Runtime = Runtime.NODEJS_10_X,
                DepsLockFilePath = $"{currentDir}/src/lambdaEdge/package-lock.json"
            });
        }
    }
}
```

The login.js Lambda@Edge function:

```
'use strict';

exports.handler = (event, context, callback) => {
    const request = event.Records[0].cf.request;
    const headers = request.headers;

    /* URI encode the original request to be sent as redirect_url in query params */
    //const encodedRedirectUrl = encodeURIComponent(`https://${headers.host[0].value}${request.uri}?${request.querystring}`);
    const appstate = "loggedin";
    const sessionid = 123
    const response = {
        status: '200',
        multiValueHeaders: {
            'Set-Cookie': [`appstate=${appstate}`, `sessionid=${sessionid}`]
        },
    };
    callback(null, response);
};
```

The Lambda@Edge checkAuth.js function:
```
'use strict';

function parseCookies(headers) {
    const parsedCookie = {};
    if (headers.cookie) {
        headers.cookie[0].value.split(';').forEach((cookie) => {
            if (cookie) {
                const parts = cookie.split('=');
                parsedCookie[parts[0].trim()] = parts[1].trim();
            }
        });
    }
    return parsedCookie;
}

exports.handler = (event, context, callback) => {
    const request = event.Records[0].cf.request;
    const headers = request.headers;

    /* Check for session-id in request cookie in viewer-request event,
     * if session-id is absent, redirect the user to sign in page with original
     * request sent as redirect_url in query params.
     */

    /* Check for session-id in cookie, if present then proceed with request */
    const parsedCookies = parseCookies(headers);
    if (parsedCookies && parsedCookies['appstate'] === 'loggedin') {
        callback(null, request);
        return;
    }

    /* URI encode the original request to be sent as redirect_url in query params */
    //const encodedRedirectUrl = encodeURIComponent(`https://${headers.host[0].value}${request.uri}?${request.querystring}`);
    const response = {
        status: '302',
        statusDescription: 'Found',
        headers: {
            location: [{
                key: 'Location',
                //value: `https://www.example.com/signin?redirect_url=${encodedRedirectUrl}`,
                value: `/`,
            }],
        },
    };
    callback(null, response);
};
```

My CDK project folder structure:

![image](https://user-images.githubusercontent.com/58381025/114990312-0597c100-9eb6-11eb-8df0-2304f24a94a8.png)

### What did you expect to happen?

I am running the `cdk synth` from commandline with my default region as `ap-south-1`. My expectation is that the AuthlambdaFunctionStack.cs is setting the Lambda@Edge region by setting the Env property of StackProps to the `us-east-1` region (required for Lambda@Edge) and the synth would complete successfully and the stack would deploy to `us-east-1`.

### What actually happened?

```
D:\Giri\temp\authlambda>cdk synth
#1 [internal] load build definition from Dockerfile
#1 sha256:673342caf6d225028aa6d733dd7295fa52a8f01857da3125a7486abc0afeed39
#1 transferring dockerfile: 1.02kB 0.0s done
#1 DONE 0.1s

#2 [internal] load .dockerignore
#2 sha256:8c82e26fb60396d2fc290f2ef2190a670ed5aaaa3e7c5b10fc9f134c583ecf8e
#2 transferring context:
#2 transferring context: 2B 0.0s done
#2 DONE 0.1s

#3 [internal] load metadata for public.ecr.aws/sam/build-nodejs10.x:latest
#3 sha256:3eb43c85f05c07b2529eeda10b5176b79aa79117c4d444174b6cbfeb43fe4c5e
#3 DONE 3.1s

#10 [1/7] FROM public.ecr.aws/sam/build-nodejs10.x@sha256:50d8803b1093c797ef6fcafca28dd80778da556782799d1938738df21ea6cbb7
#10 sha256:8bdf16b4cbcfe216a9083c86bb491e3a23c9b7cf810462926404f21798e3e957
#10 DONE 0.0s

#7 [5/7] RUN mkdir /tmp/yarn-cache &&     chmod -R 777 /tmp/yarn-cache &&     yarn config set cache-folder /tmp/yarn-cache
#7 sha256:e0271ab7015fa4d42a52fbe2ccf1c6821d4a7ee8166d831d28752c6b22f1ecee
#7 CACHED

#8 [6/7] RUN npm config --global set update-notifier false
#8 sha256:28c4373fc7f5d7a7278f399b913ec54b4d057381967d86be53f802123908170d
#8 CACHED

#4 [2/7] RUN npm install --global yarn@1.22.5
#4 sha256:3aeadce73ed42fb9e69eb1ded7b2f4d63dc2bba99854b4b7de377e69e1d6d688
#4 CACHED

#5 [3/7] RUN npm install --global --unsafe-perm=true esbuild@0
#5 sha256:45dec92bfc6d60c790e8725e22d6321910d2909ad009a7f4391b00e2d2d99ce7
#5 CACHED

#6 [4/7] RUN mkdir /tmp/npm-cache &&     chmod -R 777 /tmp/npm-cache &&     npm config --global set cache /tmp/npm-cache
#6 sha256:dbb6229acc0e9ff65dabaa543df0ba3fffee425682c321108547e55302ec7027
#6 CACHED

#9 [7/7] RUN /sbin/useradd -u 1000 user && chmod 711 /
#9 sha256:3bd8469c613d43e279b3e546d512c36f54bd83fe595a0111d189c9e316747b0d
#9 CACHED

#11 exporting to image
#11 sha256:e8c613e07b0b7ff33893b694f7759a10d42e180f2b4dc349fb57dc6b71dcab00
#11 exporting layers done
#11 writing image sha256:beae2a16a4fc14d93f84de34e846d4fa71acbb812f91f19b316db50dfc8b66b4
#11 writing image sha256:beae2a16a4fc14d93f84de34e846d4fa71acbb812f91f19b316db50dfc8b66b4 0.0s done
#11 naming to docker.io/library/cdk-b1cc4dc3f9f88844fa82052aa392180ed61e539fad316afbeb5aecd8b6c0123e done
#11 DONE 0.1s
Bundling asset AuthlambdaFunctionsStack/loginHandler/Code/Stage...
esbuild cannot run locally. Switching to Docker bundling.
 > error: Could not resolve "/asset-input/login.js"

1 error
Unhandled exception. Amazon.JSII.Runtime.JsiiException: Failed to bundle asset AuthlambdaFunctionsStack/loginHandler/Code/Stage, bundle output is located at D:\Giri\temp\authlambda\cdk.out\bundling-temp-5f9e26bcad512c877c63e125e3ba776e715aaa4580864983839595604be5fef6-error: Error: docker exited with status 1
   at Amazon.JSII.Runtime.Services.Client.TryDeserialize[TResponse](String responseJson)
   at Amazon.JSII.Runtime.Services.Client.ReceiveResponse[TResponse]()
   at Amazon.JSII.Runtime.Services.Client.Send[TRequest,TResponse](TRequest requestObject)
   at Amazon.JSII.Runtime.Services.Client.Create(CreateRequest request)
   at Amazon.JSII.Runtime.Services.Client.Create(String fullyQualifiedName, Object[] arguments, Override[] overrides, String[] interfaces)      
   at Amazon.JSII.Runtime.Deputy.DeputyBase..ctor(DeputyProps props)
   at Constructs.Construct..ctor(DeputyProps props)
   at Amazon.CDK.Construct..ctor(DeputyProps props)
   at Amazon.CDK.Resource..ctor(DeputyProps props)
   at Amazon.CDK.AWS.Lambda.FunctionBase..ctor(DeputyProps props)
   at Amazon.CDK.AWS.Lambda.Function..ctor(DeputyProps props)
   at Amazon.CDK.AWS.Lambda.Nodejs.NodejsFunction..ctor(Construct scope, String id, INodejsFunctionProps props)
   at Authlambda.AuthlambdaFunction..ctor(Construct scope, String id, NodejsFunctionProps props) in D:\Giri\temp\authlambda\src\Authlambda\AuthlambdaFunctionsStack.cs:line 26
   at Authlambda.AuthlambdaFunctionsStack..ctor(Construct scope, String id, AuthlambdaFunctionsStackProps props) in D:\Giri\temp\authlambda\src\Authlambda\AuthlambdaFunctionsStack.cs:line 40
   at Authlambda.Program.Main(String[] args) in D:\Giri\temp\authlambda\src\Authlambda\Program.cs:line 14
Subprocess exited with error 3762504530
```

### Environment

  - **CDK CLI Version  :** 1.96.0 (build 39f3df8)
  - **Framework Version:** 
  - **Node.js Version:**  v14.15.4 (for cdk commandline); Runtime.NODEJS_10_X for Lambda#Edge configured through the construct
  - **OS               :** Microsoft Windows [Version 10.0.19042.928]
  - **Language (Version):**  C#  (dotnet Version:   3.1.401, Commit:    5b6f5e5005)
 

### Other

Initially, I was facing synth errors due to the  `Entry` and `DepsLockFilePath` properties of the Lambda@Edge function using relative paths. I made them absolute and that fixed the earlier problem.

Example fix done for `Entry` and `DepsLockFilePath` to make them absolute paths:
```
                Entry = $"{currentDir}/src/lambdaEdge/login.js",
                Handler = "login.handler",
                Runtime = Runtime.NODEJS_10_X,
                DepsLockFilePath = $"{currentDir}/src/lambdaEdge/package-lock.json"
```

The Javascript Lambda@Edge functions have no dependencies so far. So, my package.json doesn't list any.

--- 

This is :bug: Bug Report

**Comment by jogold** [comment]
Can you remove the `Handler` prop and rerun? The exported handler is named `handler` in your files so you should be able to use the default.

**Comment by viventra** [comment]
I tried this,

```
            loginHandler = new AuthlambdaFunction(this, "loginHandler", new NodejsFunctionProps() {
                Entry = $"{currentDir}/src/lambdaEdge/login.js",
                Handler = "handler",
                Runtime = Runtime.NODEJS_10_X,
                DepsLockFilePath = $"{currentDir}/src/lambdaEdge/package-lock.json"
            });
```

and this,

```
            loginHandler = new AuthlambdaFunction(this, "loginHandler", new NodejsFunctionProps() {
                Entry = $"{currentDir}/src/lambdaEdge/login.js",
                //Handler = "handler",
                Runtime = Runtime.NODEJS_10_X,
                DepsLockFilePath = $"{currentDir}/src/lambdaEdge/package-lock.json"
            });
```

Both are giving the same error:

```
... (initial logs omitted) ...

Use 'docker scan' to run Snyk tests against images to find vulnerabilities and learn how to fix them
Bundling asset AuthlambdaFunctionsStack/loginHandler/Code/Stage...
esbuild cannot run locally. Switching to Docker bundling.
 > error: Could not resolve "/asset-input/login.js"

1 error
Unhandled exception. Amazon.JSII.Runtime.JsiiException: Failed to bundle asset AuthlambdaFunctionsStack/loginHandler/Code/Stage, bundle output is located at D:\Giri\temp\authlambda - Copy\cdk.out\bundling-temp-e00b593f575cfd058dedfec94f34cad7fdcb8c3bbf8118189ddb55faf7452daf-error: Error: docker exited with status 1
   at Amazon.JSII.Runtime.Services.Client.TryDeserialize[TResponse](String responseJson)
   at Amazon.JSII.Runtime.Services.Client.ReceiveResponse[TResponse]()
   at Amazon.JSII.Runtime.Services.Client.Send[TRequest,TResponse](TRequest requestObject)
   at Amazon.JSII.Runtime.Services.Client.Create(CreateRequest request)
   at Amazon.JSII.Runtime.Services.Client.Create(String fullyQualifiedName, Object[] arguments, Override[] overrides, String[] interfaces)
   at Amazon.JSII.Runtime.Deputy.DeputyBase..ctor(DeputyProps props)
   at Constructs.Construct..ctor(DeputyProps props)
   at Amazon.CDK.Construct..ctor(DeputyProps props)
   at Amazon.CDK.Resource..ctor(DeputyProps props)
   at Amazon.CDK.AWS.Lambda.FunctionBase..ctor(DeputyProps props)
   at Amazon.CDK.AWS.Lambda.Function..ctor(DeputyProps props)
   at Amazon.CDK.AWS.Lambda.Nodejs.NodejsFunction..ctor(Construct scope, String id, INodejsFunctionProps props)
   at Authlambda.AuthlambdaFunction..ctor(Construct scope, String id, NodejsFunctionProps props) in D:\Giri\temp\authlambda\src\Authlambda\AuthlambdaFunctionsStack.cs:line 26
   at Authlambda.AuthlambdaFunctionsStack..ctor(Construct scope, String id, AuthlambdaFunctionsStackProps props) in D:\Giri\temp\authlambda\src\Authlambda\AuthlambdaFunctionsStack.cs:line 40
   at Authlambda.Program.Main(String[] args) in D:\Giri\temp\authlambda\src\Authlambda\Program.cs:line 14
```

**Comment by viventra** [comment]
Also, I discovered the @aws-cdk/aws-cloudfront.experimental module and am now using the EdgeFunction construct and it works. That has helped me move on. However, I am keen to see how to make the stable construct work.

```
using Amazon.CDK.AWS.CloudFront.Experimental;

...

            loginHandler = new EdgeFunction(this, "loginHandler", new EdgeFunctionProps() {
                Code = Code.FromAsset("src/lambdaEdge"),
                Handler = "login.handler",
                Runtime = Runtime.NODEJS_12_X,
                Description = "Login handler Lambda@Edge"
            });
```

I guess the convention used by `@aws-cdk/aws-cloudfront.experimental` and `@aws-cdk/aws-lambda` in API gateway seem similar, whereas Lambda@Edge seems to require a different convention while defining lambda functions.

**Comment by rix0rrr** [comment]
Closing as I don't believe this is a bug in CDK.
