### ISSUE TITLE
github.com/aws/aws-cdk-go/awscdk: Cannot set targets in target group

### ISSUE THREAD

**Issue by stroem** [aws/aws-cdk#14212]
### The Question
I am trying to connect a lambda-target to an Application Target Group in golang by writing like this:

```go
...
import (
	"github.com/aws/aws-cdk-go/awscdk/v2/awselasticloadbalancingv2"
	"github.com/aws/aws-cdk-go/awscdk/v2/awselasticloadbalancingv2targets"
)
...
	targetGroup := awselasticloadbalancingv2.NewApplicationTargetGroup(stack, jsii.String("TargetGroup"),
		&awselasticloadbalancingv2.ApplicationTargetGroupProps{
			Vpc: vpc,
			Targets: &[]awselasticloadbalancingv2.IApplicationLoadBalancerTarget{
				awselasticloadbalancingv2targets.NewLambdaTarget(lambda),
			},
			TargetType: awselasticloadbalancingv2.TargetType_LAMBDA,
		})
```

But when trying to run synth on the code, I get this error, which doesn't say to much of what the error acually is?! 
```
panic: "Expected object reference, got {\"Type__awselasticloadbalancingv2IApplicationLoadBalancerTarget\":{}}"

goroutine 1 [running]:
github.com/aws/jsii-runtime-go.Create(0x164ef56, 0x3d, 0xc00011db48, 0x3, 0x3, 0x16093a0, 0xc0006b6ed0)
        /Users/***/go/pkg/mod/github.com/aws/jsii-runtime-go@v1.27.0/runtime.go:172 +0xb53
github.com/aws/aws-cdk-go/awscdk/v2/awselasticloadbalancingv2.NewApplicationTargetGroup(0xc641c48, 0xc000695068, 0xc0003e8920, 0xc0001be140, 0xc000695068, 0xc0006b6bd0)
        /Users/***/go/pkg/mod/github.com/aws/aws-cdk-go/awscdk/v2@v2.0.0-alpha.10/awselasticloadbalancingv2/awselasticloadbalancingv2.go:2380 +0xed
main.NewServerlessStack(0xc641c20, 0xc000196200, 0x1629d06, 0xa, 0x0, 0x0, 0xc000196440, 0x0, 0x0, 0x0, ...)
        /Users/***/go/src/github.com/***/serverless-app/cdk/cdk.go:101 +0xc85
main.main()
        /Users/***/go/src/github.com/***/serverless-app/cdk/cdk.go:208 +0x458
exit status 2
Subprocess exited with error 1
```

I found a "workaround" calling the `targetGroup.AddTarget(...)`.
This issue can also be reproduces by populating the list in DefaultActions for `awselasticloadbalancingv2.NewApplicationListener` aswell, but found no "workaround".

Am I using the functions wrong? Or is it a bug?

### Environment

  - **CDK CLI Version:** 2.0.0-alpha.10 (build db0878e) (same issue in 1.98.0)
  - **Module Version:** 2.0.0-alpha.10
  - **Node.js Version:** v15.11.0
  - **OS:** macOS Big Sur
  - **Language (Version):** go version go1.16 darwin/amd64

**Comment by stroem** [comment]
Reproduce with ApplicationListener
```go
	awselasticloadbalancingv2.NewApplicationListener(stack, jsii.String("ALBListener"), &awselasticloadbalancingv2.ApplicationListenerProps{
		LoadBalancer: alb,
		DefaultAction: awselasticloadbalancingv2.ListenerAction_Forward(
			&[]awselasticloadbalancingv2.IApplicationTargetGroup{
				targetGroup,
			},
			&awselasticloadbalancingv2.ForwardOptions{
				StickinessDuration: awscdk.Duration_Minutes(jsii.Number(1)),
			},
		),
		Protocol: awselasticloadbalancingv2.ApplicationProtocol_HTTP,
		Port:     jsii.Number(80),
		Open:     jsii.Bool(false),
	})
```

Error message
```
panic: "Expected object reference, got {\"Type__constructsConstruct\":{}}"

goroutine 1 [running]:
github.com/aws/jsii-runtime-go.StaticInvoke(0x164ac40, 0x35, 0x1628349, 0x7, 0xc00053bb68, 0x2, 0x2, 0x1523fe0, 0xc000011200)
        /Users/***/go/pkg/mod/github.com/aws/jsii-runtime-go@v1.27.0/runtime.go:241 +0x19b
github.com/aws/aws-cdk-go/awscdk/v2/awselasticloadbalancingv2.ListenerAction_Forward(0xc00000df08, 0xc0000111f0, 0xc0004dd320, 0x2c6131c8)
        /Users/***/go/pkg/mod/github.com/aws/aws-cdk-go/awscdk/v2@v2.0.0-alpha.10/awselasticloadbalancingv2/awselasticloadbalancingv2.go:8388 +0xda
main.NewServerlessStack(0x2c6099a0, 0xc000434540, 0x1629dcd, 0xa, 0x0, 0x0, 0xc000434780, 0x0, 0x0, 0x0, ...)
        /Users/***/go/src/github.com/***/serverless-app/cdk/cdk.go:122 +0xe6e
main.main()
        /Users/***/go/src/github.com/***/serverless-app/cdk/cdk.go:206 +0x458
exit status 2
Subprocess exited with error 1
```

**Comment by peterwoodworth** [comment]
@MrArnoldPalmer is this a JSII issue?

**Comment by MrArnoldPalmer** [comment]
@peterwoodworth it might be, I'll repro this and get back to you.

**Comment by peterwoodworth** [comment]
I can't reproduce this on Typescript, so this is likely a JSII bug. Thank you for the submission @stroem!

**Comment by MrArnoldPalmer** [comment]
@stroem finally getting back to working on Go and investigating this, though I wasn't able to reproduce. Can you try updating your cdk, nodejs, and go versions? Here is my example stack I was able to deploy.

<details>
  <summary>Click to expand!</summary>
  
```go
package main

import (
        "path/filepath"
	"github.com/aws/aws-cdk-go/awscdk/v2"
        ec2 "github.com/aws/aws-cdk-go/awscdk/v2/awsec2"
	elb "github.com/aws/aws-cdk-go/awscdk/v2/awselasticloadbalancingv2"
	lambda "github.com/aws/aws-cdk-go/awscdk/v2/awslambda"
	targets "github.com/aws/aws-cdk-go/awscdk/v2/awselasticloadbalancingv2targets"
	"github.com/aws/constructs-go/constructs/v10"
	"github.com/aws/jsii-runtime-go"
)

type Issue14212StackProps struct {
	awscdk.StackProps
}

func NewIssue14212Stack(scope constructs.Construct, id string, props *Issue14212StackProps) awscdk.Stack {
	var sprops awscdk.StackProps
	if props != nil {
		sprops = props.StackProps
	}
	stack := awscdk.NewStack(scope, &id, &sprops)
        vpc := ec2.NewVpc(stack, jsii.String("Vpc"), nil)

        code, _ := filepath.Abs("lambda")
        handler := lambda.NewFunction(stack, jsii.String("MyLambdaFunction"), &lambda.FunctionProps{
          Runtime: lambda.Runtime_GO_1_X(),
          Handler: jsii.String("main"),
          Code: lambda.Code_FromAsset(&code, nil),
        })

        elb.NewApplicationTargetGroup(stack, jsii.String("TargetGroup"), &elb.ApplicationTargetGroupProps{
          Vpc: vpc,
          Targets: &[]elb.IApplicationLoadBalancerTarget{ targets.NewLambdaTarget(handler) },
          TargetType: elb.TargetType_LAMBDA,
        })

	return stack
}

func main() {
	app := awscdk.NewApp(nil)

	NewIssue14212Stack(app, "Issue14212Stack", &Issue14212StackProps{
		awscdk.StackProps{
		},
	})

	app.Synth(nil)
}
```
</details>

Please reopen this if you're still experiencing the issue!
