### ISSUE TITLE
(aws_lambda_python): PythonFunction breaks pipelines

### ISSUE THREAD

**Issue by hinnerk** [aws/aws-cdk#14305]
`aws_lambda_python.PythonFunction` compiles and zips a Python Lambda's dependencies using a docker container. `pipelines.SimpleSynthAction.standard_npm_synth` runs `cdk synth` on CodeBuild without access to docker, resulting in the error "Cannot connect to the Docker daemon at...".

### Reproduction Steps

1. set up Github repo, AWS accounts (assuming separate deployment and development accounts) and Github Token in the secrets manager
2. deploy pipeline
3. push code to repo, that should trigger a deployment
4. watch the deployment fail

This code demonstrate the issue, but given the amount of set up it requires I did not test it, so please beware of typos. It's a simplified version of the code that failed for me, so I expect it to generally work.

Stack, Stage and Pipeline, comment out the "stage" lines to only deploy the pipeline:

```python
from aws_cdk import (
    aws_lambda,
    aws_lambda_python,
    core,
    aws_codepipeline,
    aws_codepipeline_actions as cpa,
    pipelines,
)
from os import path


class MinimalStack(core.Stack):
    def __init__(
        self,
        scope: core.Construct,
        id: str,
        **kwargs,
    ) -> None:
        super().__init__(scope, id, **kwargs)

        aws_lambda_python.PythonFunction(
            self,
            "SomeLambda",
            entry=path.join(path.dirname(__file__), "lambda"),
            index="somecode.py",
            handler="handler",
            runtime=aws_lambda.Runtime.PYTHON_3_8,
        )


class MinimalStage(core.Stage):
    def __init__(self, scope: core.Construct, id: str, **kwargs):
        super().__init__(
            scope,
            id,
            env=core.Environment(
                account="XXX",
                region="YYY",
            ),
            **kwargs,
        )

        MinimalStack(
            self,
            "MinimalStack",
        )


class PipelineStack(core.Stack):
    def __init__(self, scope: core.Construct, id: str, **kwargs) -> None:
        super().__init__(
            scope,
            id,
            env=core.Environment(
                account="AAAAAA",
                region="BBBBB",
            ),
            **kwargs,
        )

        source_artifact = aws_codepipeline.Artifact()
        cloud_assembly_artifact = aws_codepipeline.Artifact()

        pipeline = pipelines.CdkPipeline(
            self,
            "MinimalPipeline",
            pipeline_name="MinimalPipeline",
            cloud_assembly_artifact=cloud_assembly_artifact,
            source_action=cpa.GitHubSourceAction(
                action_name="GitHub",
                output=source_artifact,
                oauth_token=core.SecretValue.secrets_manager("WHATEVER"),
                trigger=cpa.GitHubTrigger.POLL,
                owner="someone",
                repo="minimalrepo",
            ),
            synth_action=pipelines.SimpleSynthAction.standard_npm_synth(
                source_artifact=source_artifact,
                cloud_assembly_artifact=cloud_assembly_artifact,
                install_command="npm install -g aws-cdk && pip install -r requirements.txt",
                # TODO: re-enable after resolving PythonFunction docker dependency
                # build_command="python -m unittest discover",
                synth_command="cdk synth",
            ),
        )

        stage = MinimalStage(
            self,
            "MINIMAL-EXAMPLE",
        )
        pipeline.add_application_stage(stage)
```

The lambda code, file `lambda/somecode.py`:

```python
import logging
from faker import Faker

log = logging.getLogger(__name__)


def handler(request, context):
    log.info("Got this request:", request)
    fake = Faker()
    return fake.address()
```

The dependency declaration, living in `lambda/requirements.txt`:

```
faker==8.1.0 \
    --hash=sha256:26c7c3df8d46f1db595a34962f8967021dd90bbd38cc6e27461a3fb16cd413ae \
    --hash=sha256:44eb060fad3015690ff3fec6564d7171be393021e820ad1851d96cb968fbfcd4
python-dateutil==2.8.1 \
    --hash=sha256:73ebfe9dbf22e832286dafa60473e4cd239f8592f699aa5adaf10050e6e1823c \
    --hash=sha256:75bb3f31ea686f1197762692a9ee6a7550b59fc6ca3a1f4b5d7e32fb98e2da2a
    # via faker
six==1.15.0 \
    --hash=sha256:30639c035cdb23534cd4aa2dd52c3bf48f06e5f4a941509c8bafd8ce11080259 \
    --hash=sha256:8b74bedcbbbaca38ff6d7491d76f2b06b3592611af620f8426e82dddb04a5ced
    # via python-dateutil
text-unidecode==1.3 \
    --hash=sha256:1311f10e8b895935241623731c2ba64f4c455287888b18189350b67134a822e8 \
    --hash=sha256:bad6603bb14d279193107714b288be206cac565dfa49aa5b105294dd5c4aab93
    # via faker
```

### What did you expect to happen?

The docker part to seamlessly work on CodeBuild. I was surprised to see that our unit tests, that basically run `cdk synth` work on Github Actions, apparently there's enough docker infrastructure available for this to run.

### What actually happened?

`cdk synth` step fails without docker:

```
...
[Container] 2021/04/21 14:54:36 Phase complete: PRE_BUILD State: SUCCEEDED
164 | [Container] 2021/04/21 14:54:36 Phase context status code:  Message:
165 | [Container] 2021/04/21 14:54:36 Entering phase BUILD
166 | [Container] 2021/04/21 14:54:36 Running command cdk synth
167 | Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
168 | jsii.errors.JavaScriptError:
169 | Error: docker exited with status 1
170 | at dockerExec (/tmp/jsii-kernel-IpTMEP/node_modules/@aws-cdk/core/lib/bundling.js:254:15)
171 | at Function.fromBuild (/tmp/jsii-kernel-IpTMEP/node_modules/@aws-cdk/core/lib/bundling.js:169:9)
172 | at Object.bundle (/tmp/jsii-kernel-IpTMEP/node_modules/@aws-cdk/aws-lambda-python/lib/bundling.js:36:35)
173 | at new PythonFunction (/tmp/jsii-kernel-IpTMEP/node_modules/@aws-cdk/aws-lambda-python/lib/function.js:39:30)
174 | at /tmp/tmpylhien1c/lib/program.js:8154:58
175 | at Kernel._wrapSandboxCode (/tmp/tmpylhien1c/lib/program.js:8582:24)
176 | at Kernel._create (/tmp/tmpylhien1c/lib/program.js:8154:34)
177 | at Kernel.create (/tmp/tmpylhien1c/lib/program.js:7895:29)
178 | at KernelHost.processRequest (/tmp/tmpylhien1c/lib/program.js:9479:36)
179 | at KernelHost.run (/tmp/tmpylhien1c/lib/program.js:9442:22)
...
```

### Environment

  - **CDK CLI Version  :** 1.100.0
  - **Framework Version:** 1.100.0
  - **Node.js Version:** unknown, whatever's installed on aws/codebuild/standard:4.0
  - **OS               :** Linux, aws/codebuild/standard:4.0
  - **Language (Version):** Python 3.8, whatever's installed on aws/codebuild/standard:4.0

### Other

Nothing else.

Edit: Too many moving parts for a simple bug report, this might require a bug repository instead. I forgot (at least) to add `app.py`, `cdk.json`, `package.json`, the top level `requirements.txt` which references the python cdk packages and where to put the cdk code.

--- 

This is :bug: Bug Report

**Comment by hinnerk** [comment]
Duplicate of #9217 and solved by adding `environment` setting `privileged=True`.

```python
            synth_action=pipelines.SimpleSynthAction.standard_npm_synth(
                source_artifact=source_artifact,
                cloud_assembly_artifact=cloud_assembly_artifact,
                install_command="npm install -g aws-cdk && pip install -r requirements.txt",
                # This solves my issue:
                environment=aws_codebuild.BuildEnvironment(
                    build_image=aws_codebuild.LinuxBuildImage.STANDARD_4_0,
                    privileged=True
                ),
                build_command="python -m unittest discover",
                synth_command="cdk synth",
            ),
```
