### ISSUE TITLE
(@aws-cdk/aws-rds): Can't use existing VPC in ServerlessCluster

### ISSUE THREAD

**Issue by qaismyname** [aws/aws-cdk#14312]
Using an existing VPC when trying to create a ServerlessCluster fails due to `TypeError: Cannot read property 'selectSubnets' of undefined`.

### Reproduction Steps

```
const someVpc = ec2.Vpc.fromLookup(this, 'vpc', {
            vpcId: 'vpc-abcdef'
        })


const cluster = new rds.ServerlessCluster(this, 'AnotherCluster', {
            engine: rds.DatabaseClusterEngine.AURORA_MYSQL,
            parameterGroup: rds.ParameterGroup.fromParameterGroupName(this, 'ParameterGroup', 'default.aurora-postgresql10'),
            someVpc,
            scaling: {
                // @ts-ignore
                autoPause: Duration.minutes(10), // default is to pause after 5 minutes of idle time
                minCapacity: rds.AuroraCapacityUnit.ACU_8, // default is 2 Aurora capacity units (ACUs)
                maxCapacity: rds.AuroraCapacityUnit.ACU_32, // default is 16 Aurora capacity units (ACUs)
            }
        });
```

leads to

```
/Users/qaiser/foo/stack/node_modules/@aws-cdk/aws-rds/lib/serverless-cluster.ts:404
    const defaultPort = attrs.port ? ec2.Port.tcp(attrs.port) : undefined;
                                   ^
TypeError: Cannot read property 'selectSubnets' of undefined
    at new ServerlessCluster (/Users/qaiser/foo/stack/node_modules/@aws-cdk/aws-rds/lib/serverless-cluster.ts:404:36)
    at VatIdCheckerStack.createRdsInstances (/Users/qaiser/git/foo/stack/lib/vat-id-checker-stack.ts:195:25)
    at new VatIdCheckerStack (/Users/qaiser/git/foo/stack/lib/vat-id-checker-stack.ts:27:14)
    at Object.<anonymous> (/Users/qaiser/git/foo/stack/bin/vat-id-checker.ts:11:1)
    at Module._compile (node:internal/modules/cjs/loader:1108:14)
    at Module.m._compile (/Users/qaiser/git/foo/stack/node_modules/ts-node/src/index.ts:1056:23)
    at Module._extensions..js (node:internal/modules/cjs/loader:1137:10)
    at Object.require.extensions.<computed> [as .ts] (/Users/qaiser/foovat-id-checker/stack/node_modules/ts-node/src/index.ts:1059:12)
    at Module.load (node:internal/modules/cjs/loader:973:32)
    at Function.Module._load (node:internal/modules/cjs/loader:813:14)

```

I have tried different `aws-cdk/aws-rds` versions but the error persists.

### What did you expect to happen?

I was expecting that I can import an existing VPC and use it.

### What actually happened?

It seems that the error doesn't happen for newly created VPCs, e.g.

```
const vpc = new ec2.Vpc(this, 'myrdsvpc');

const cluster = new rds.ServerlessCluster(this, 'AnotherCluster', {
            engine: rds.DatabaseClusterEngine.AURORA_MYSQL,
            parameterGroup: rds.ParameterGroup.fromParameterGroupName(this, 'ParameterGroup', 'default.aurora-postgresql10'),
            vpc,
            scaling: {
                // @ts-ignore
                autoPause: Duration.minutes(10), // default is to pause after 5 minutes of idle time
                minCapacity: rds.AuroraCapacityUnit.ACU_8, // default is 2 Aurora capacity units (ACUs)
                maxCapacity: rds.AuroraCapacityUnit.ACU_32, // default is 16 Aurora capacity units (ACUs)
            }
        });
```

### Environment

  - **CDK CLI Version  :*1.98.0 (build 79f4512)*
  - **Framework Version:*1.100.0*
  - **Node.js Version:** v15.8.0
  - **OS               :*osx 11.2.3 (20D91*
  - **Language (Version):*ts 4.2.4* 

--- 

This is :bug: Bug Report

**Comment by qaismyname** [comment]
closing the issue since i found a programming error on my side

i forgot to name the vpc parameter as in

```
{
vpc: vpc
}
```

but had

```
{
vpc
}
```

![](https://media1.giphy.com/media/3xz2BLBOt13X9AgjEA/giphy.gif)
