### ISSUE TITLE
(@aws-cdk/pipelines.CdkPipeline) Update Pipeline Stage's UpdateSelf missing cloudformation permissions on role

### ISSUE THREAD

**Issue by gurkarangulati** [aws/aws-cdk#14351]
I am currently building a pipeline utilizing pipelines.CdkPipeline as follows below. While making the pipeline, both the SimpleSynthAction as well as the automatically added SelfMutate Action (in the UpdatePipeline automatically added stage) are missing the cloudformation:DescribeStacks and cloudformationGetTemplate permissions. For the synth action as you see below I added this through the role_policy_statements list parameter. Is this something that is a bug or expected? Secondly, I'm unsure how to do this with the SelfMutate Action inside the UpdatePipeline Stage that gets automatically created for us when utilizing the pipelines.CdkPipeline. The Role used on the UpdatePipeline Stage, that is automatically created, is missing cloudformation:DescribeStacks, cloudformationGetTemplate on the CDKToolkit Stack and the stack you look to deploy this into. This same role, is also missing s3 permissions to write to the CDKToolKitBucket. Based on my perspective this would be a bug because no matter what the CdkPipeline will have to synth and upload to the s3 bucket if the template is large, and it will need access to those cloudformation stacks. Please show me how to provide these to the automatically created UpdatePipeline Stage and UpdatePipeline Stage role  and also explain if this is a bug, feature request, or implementation difference?

```
        pipeline_source_action = aws_codepipeline_actions.CodeCommitSourceAction(output=pipeline_source_artifact,
                                                                                     repository=source_repo,
                                                                                     action_name=f"SourceCCRepo_{repo}",
                                                                                     branch=self._branch)

        pipeline_synth_action = pipelines.SimpleSynthAction.standard_npm_synth(
            action_name=f"Build_{repo}",
            cloud_assembly_artifact=pipeline_cloud_assembly_artifact,
            source_artifact=pipeline_source_artifact,
            install_command='pip install -r requirements.txt --ignore-installed;npm install -g aws-cdk; cdk bootstrap',
            build_command="npx cdk synth -vvvv",
            role_policy_statements=[
                aws_iam.PolicyStatement(actions=["cloudformation:DescribeStacks", "cloudformation:GetTemplate"],
                                        resources=[
                                            f"arn:aws:cloudformation:{self._config.region}:{self._config.account}:stack/CDKToolkit*",
                                            f"arn:aws:cloudformation:{self._config.region}:{self._config.account}:stack/{self._stack_id}*"])])

        pipeline_cp = aws_codepipeline.Pipeline(scope=self, id=f"{pipeline_name}cp_id",
                                                artifact_bucket=self._pipeline_asset_bucket, cross_account_keys=False,
                                                pipeline_name=pipeline_name, restart_execution_on_update=True)


        pipeline = pipelines.CdkPipeline(self, id=f"{pipeline_name}_id",
                                         cloud_assembly_artifact=pipeline_cloud_assembly_artifact,
                                         code_pipeline=pipeline_cp, source_action=pipeline_source_action,
                                         synth_action=pipeline_synth_action, vpc=self._vpc)


### Environment

  - **CDK CLI Version:** 1.100.0
  - **Module Version:** 1.100.0
  - **Node.js Version:** 6.14.11
  - **OS:** Windows 10/ Linux
  - **Language (Version):** Python 3.9

**Comment by rix0rrr** [comment]
Can you paste the CodeBuild output of the SelfMutate action?

**Comment by plumdog** [comment]
@rix0rrr Can confirm that it failed for me on 1.102.0 but then worked on 1.89.0. I have not tried version between these.

The portion of the output that I have saved before destroying the pipeline and retrying with older CDK looks like:
```
❌  AuthorizationPipeline failed: AccessDenied: User: arn:aws:sts::123412341234:assumed-role/MyAppSelfMu-ABC123/AWSCodeBuild-abc123-abc123 is not authorized to perform: cloudformation:GetTemplate on resource: arn:aws:cloudformation:eu-west-2:123412341234:stack/MyApp/abc123-abc123
```

**Comment by peterwoodworth** [comment]
@gurkarangulati are you able to provide what rix0rrr asked for?

**Comment by baartch** [comment]
I'm facing the same issue.

The following is the log of the SelfMutate action:

```
<!--StartFragment-->
[Container] 2021/05/26 12:54:35 Waiting for agent ping
--
2 | [Container] 2021/05/26 12:54:38 Waiting for DOWNLOAD_SOURCE
3 | [Container] 2021/05/26 12:54:38 Phase is DOWNLOAD_SOURCE
4 | [Container] 2021/05/26 12:54:38 CODEBUILD_SRC_DIR=/codebuild/output/src706847944/src
5 | [Container] 2021/05/26 12:54:38 YAML location is /codebuild/readonly/buildspec.yml
6 | [Container] 2021/05/26 12:54:38 Processing environment variables
7 | [Container] 2021/05/26 12:54:38 No runtime version selected in buildspec.
8 | [Container] 2021/05/26 12:54:38 Moving to directory /codebuild/output/src706847944/src
9 | [Container] 2021/05/26 12:54:38 Registering with agent
10 | [Container] 2021/05/26 12:54:38 Phases found in YAML: 2
11 | [Container] 2021/05/26 12:54:38  INSTALL: 1 commands
12 | [Container] 2021/05/26 12:54:38  BUILD: 1 commands
13 | [Container] 2021/05/26 12:54:38 Phase complete: DOWNLOAD_SOURCE State: SUCCEEDED
14 | [Container] 2021/05/26 12:54:38 Phase context status code:  Message:
15 | [Container] 2021/05/26 12:54:38 Entering phase INSTALL
16 | [Container] 2021/05/26 12:54:38 Running command npm install -g aws-cdk
17 | /usr/local/bin/cdk -&gt; /usr/local/lib/node_modules/aws-cdk/bin/cdk
18 | &nbsp;
19 | &gt; aws-sdk@2.903.0 postinstall /usr/local/lib/node_modules/aws-cdk/node_modules/aws-sdk
20 | &gt; node scripts/check-node-version.js
21 | &nbsp;
22 | + aws-cdk@1.106.0
23 | added 180 packages from 215 contributors in 7.315s
24 | &nbsp;
25 | [Container] 2021/05/26 12:54:51 Phase complete: INSTALL State: SUCCEEDED
26 | [Container] 2021/05/26 12:54:51 Phase context status code:  Message:
27 | [Container] 2021/05/26 12:54:51 Entering phase PRE_BUILD
28 | [Container] 2021/05/26 12:54:51 Phase complete: PRE_BUILD State: SUCCEEDED
29 | [Container] 2021/05/26 12:54:51 Phase context status code:  Message:
30 | [Container] 2021/05/26 12:54:51 Entering phase BUILD
31 | [Container] 2021/05/26 12:54:51 Running command cdk -a . deploy MyAppRepositoriesStack --require-approval=never --verbose
32 | CDK toolkit version: 1.106.0 (build fe32f1c)
33 | Command line arguments: {
34 | _: [ 'deploy' ],
35 | a: '.',
36 | app: '.',
37 | 'require-approval': 'never',
38 | requireApproval: 'never',
39 | verbose: 1,
40 | v: 1,
41 | lookups: true,
42 | 'ignore-errors': false,
43 | ignoreErrors: false,
44 | json: false,
45 | j: false,
46 | debug: false,
47 | ec2creds: undefined,
48 | i: undefined,
49 | 'version-reporting': undefined,
50 | versionReporting: undefined,
51 | 'path-metadata': true,
52 | pathMetadata: true,
53 | 'asset-metadata': true,
54 | assetMetadata: true,
55 | 'role-arn': undefined,
56 | r: undefined,
57 | roleArn: undefined,
58 | staging: true,
59 | 'no-color': false,
60 | noColor: false,
61 | fail: false,
62 | all: false,
63 | 'build-exclude': [],
64 | E: [],
65 | buildExclude: [],
66 | ci: false,
67 | execute: true,
68 | force: false,
69 | f: false,
70 | parameters: [ {} ],
71 | 'previous-parameters': true,
72 | previousParameters: true,
73 | '$0': '/usr/local/bin/cdk',
74 | STACKS: [ 'MyAppRepositoriesStack' ],
75 | 'S-t-a-c-k-s': [ 'MyAppRepositoriesStack' ]
76 | }
77 | merged settings: {
78 | versionReporting: true,
79 | pathMetadata: true,
80 | output: 'cdk.out',
81 | app: '.',
82 | context: {},
83 | debug: false,
84 | assetMetadata: true,
85 | requireApproval: 'never',
86 | toolkitBucket: {},
87 | staging: true,
88 | bundlingStacks: [ '*' ],
89 | lookups: true
90 | }
91 | Toolkit stack: CDKToolkit
92 | Setting "CDK_DEFAULT_REGION" environment variable to eu-central-1
93 | Resolving default credentials
94 | Looking up default account ID from STS
95 | Default account ID: 123456789012
96 | Setting "CDK_DEFAULT_ACCOUNT" environment variable to 123456789012
97 | context: {
98 | 'aws:cdk:enable-path-metadata': true,
99 | 'aws:cdk:enable-asset-metadata': true,
100 | 'aws:cdk:version-reporting': true,
101 | 'aws:cdk:bundling-stacks': [ '*' ]
102 | }
103 | --app points to a cloud assembly, so we bypass synth
104 | MyAppRepositoriesStack: deploying...
105 | Waiting for stack CDKToolkit to finish creating or updating...
106 | MyAppRepositoriesStack: checking if we can skip deploy
107 | Call failed: getTemplate({"StackName":"MyAppRepositoriesStack","TemplateStage":"Original"}) =&gt; User: arn:aws:sts::123456789012:assumed-role/MyAppRepositoriesStac-PipelineUpdatePipelineSe-MQXOT87CX32H/AWSCodeBuild-8e592d74-2a6b-4e5c-b39c-fa28ef7d6556 is not authorized to perform: cloudformation:GetTemplate on resource: arn:aws:cloudformation:eu-central-1:123456789012:stack/MyAppRepositoriesStack/7e350680-be1f-11eb-b835-0a05df596088 (code=AccessDenied)
108 | &nbsp;
109 | ❌  MyAppRepositoriesStack failed: AccessDenied: User: arn:aws:sts::123456789012:assumed-role/MyAppRepositoriesStac-PipelineUpdatePipelineSe-MQXOT87CX32H/AWSCodeBuild-8e592d74-2a6b-4e5c-b39c-fa28ef7d6556 is not authorized to perform: cloudformation:GetTemplate on resource: arn:aws:cloudformation:eu-central-1:123456789012:stack/MyAppRepositoriesStack/7e350680-be1f-11eb-b835-0a05df596088
110 | at Request.extractError (/usr/local/lib/node_modules/aws-cdk/node_modules/aws-sdk/lib/protocol/query.js:50:29)
111 | at Request.callListeners (/usr/local/lib/node_modules/aws-cdk/node_modules/aws-sdk/lib/sequential_executor.js:106:20)
112 | at Request.emit (/usr/local/lib/node_modules/aws-cdk/node_modules/aws-sdk/lib/sequential_executor.js:78:10)
113 | at Request.emit (/usr/local/lib/node_modules/aws-cdk/node_modules/aws-sdk/lib/request.js:688:14)
114 | at Request.transition (/usr/local/lib/node_modules/aws-cdk/node_modules/aws-sdk/lib/request.js:22:10)
115 | at AcceptorStateMachine.runTo (/usr/local/lib/node_modules/aws-cdk/node_modules/aws-sdk/lib/state_machine.js:14:12)
116 | at /usr/local/lib/node_modules/aws-cdk/node_modules/aws-sdk/lib/state_machine.js:26:10
117 | at Request.&lt;anonymous&gt; (/usr/local/lib/node_modules/aws-cdk/node_modules/aws-sdk/lib/request.js:38:9)
118 | at Request.&lt;anonymous&gt; (/usr/local/lib/node_modules/aws-cdk/node_modules/aws-sdk/lib/request.js:690:12)
119 | at Request.callListeners (/usr/local/lib/node_modules/aws-cdk/node_modules/aws-sdk/lib/sequential_executor.js:116:18) {
120 | code: 'AccessDenied',
121 | time: 2021-05-26T12:54:52.048Z,
122 | requestId: 'ae9340fd-e1f8-47a3-98b4-9eed1ad2c0ad',
123 | statusCode: 403,
124 | retryable: false,
125 | retryDelay: 37.640754280187984
126 | }
127 | User: arn:aws:sts::123456789012:assumed-role/MyAppRepositoriesStac-PipelineUpdatePipelineSe-MQXOT87CX32H/AWSCodeBuild-8e592d74-2a6b-4e5c-b39c-fa28ef7d6556 is not authorized to perform: cloudformation:GetTemplate on resource: arn:aws:cloudformation:eu-central-1:123456789012:stack/MyAppRepositoriesStack/7e350680-be1f-11eb-b835-0a05df596088
128 | AccessDenied: User: arn:aws:sts::123456789012:assumed-role/MyAppRepositoriesStac-PipelineUpdatePipelineSe-MQXOT87CX32H/AWSCodeBuild-8e592d74-2a6b-4e5c-b39c-fa28ef7d6556 is not authorized to perform: cloudformation:GetTemplate on resource: arn:aws:cloudformation:eu-central-1:123456789012:stack/MyAppRepositoriesStack/7e350680-be1f-11eb-b835-0a05df596088
129 | at Request.extractError (/usr/local/lib/node_modules/aws-cdk/node_modules/aws-sdk/lib/protocol/query.js:50:29)
130 | at Request.callListeners (/usr/local/lib/node_modules/aws-cdk/node_modules/aws-sdk/lib/sequential_executor.js:106:20)
131 | at Request.emit (/usr/local/lib/node_modules/aws-cdk/node_modules/aws-sdk/lib/sequential_executor.js:78:10)
132 | at Request.emit (/usr/local/lib/node_modules/aws-cdk/node_modules/aws-sdk/lib/request.js:688:14)
133 | at Request.transition (/usr/local/lib/node_modules/aws-cdk/node_modules/aws-sdk/lib/request.js:22:10)
134 | at AcceptorStateMachine.runTo (/usr/local/lib/node_modules/aws-cdk/node_modules/aws-sdk/lib/state_machine.js:14:12)
135 | at /usr/local/lib/node_modules/aws-cdk/node_modules/aws-sdk/lib/state_machine.js:26:10
136 | at Request.&lt;anonymous&gt; (/usr/local/lib/node_modules/aws-cdk/node_modules/aws-sdk/lib/request.js:38:9)
137 | at Request.&lt;anonymous&gt; (/usr/local/lib/node_modules/aws-cdk/node_modules/aws-sdk/lib/request.js:690:12)
138 | at Request.callListeners (/usr/local/lib/node_modules/aws-cdk/node_modules/aws-sdk/lib/sequential_executor.js:116:18)
139 | &nbsp;
140 | [Container] 2021/05/26 12:54:52 Command did not exit successfully cdk -a . deploy MyAppRepositoriesStack --require-approval=never --verbose exit status 1
141 | [Container] 2021/05/26 12:54:52 Phase complete: BUILD State: FAILED
142 | [Container] 2021/05/26 12:54:52 Phase context status code: COMMAND_EXECUTION_ERROR Message: Error while executing command: cdk -a . deploy MyAppRepositoriesStack --require-approval=never --verbose. Reason: exit status 1
143 | [Container] 2021/05/26 12:54:52 Entering phase POST_BUILD
144 | [Container] 2021/05/26 12:54:52 Phase complete: POST_BUILD State: SUCCEEDED
145 | [Container] 2021/05/26 12:54:52 Phase context status code:  Message:

<!--EndFragment-->

```

**Comment by berenddeboer** [comment]
Same issue with CDK 1.106. I assumed I had to give more permissions, so was reading up on how to do that. But this is the out of the box error.

**Comment by berenddeboer** [comment]
The error seems to be in `update-pipeline-actions.ts`:

```
selfMutationProject.addToRolePolicy(new iam.PolicyStatement({
      actions: ['cloudformation:DescribeStacks'],
      resources: ['*'], // this is needed to check the status of the bootstrap stack when doing `cdk deploy`
    }));
```
If you add "cloudformation:GetTemplate" you get really odd behaviour: it seems to pick some random (first?) stack. I first had two stacks, the normal stack, and a separate pipeline stack. That behaviour doesn't seem very well supported from reading the code. So merged this all into one stack.

Then my deployment fails with:

```

Preparing asset 4cd61014b71160e8c66fe167e43710d5ba068b80b134e9bd84508cf9238b2392: {"path":"asset.4cd61014b71160e8c66fe167e43710d5ba068b80b134e9bd84508cf9238b2392","id":"4cd61014b71160e8c66fe167e43710d5ba068b80b134e9bd84508cf9238b2392","packaging":"zip","sourceHash":"4cd61014b71160e8c66fe167e43710d5ba068b80b134e9bd84508cf9238b2392","s3BucketParameter":"AssetParameters4cd61014b71160e8c66fe167e43710d5ba068b80b134e9bd84508cf9238b2392S3BucketBF7A7F3F","s3KeyParameter":"AssetParameters4cd61014b71160e8c66fe167e43710d5ba068b80b134e9bd84508cf9238b2392S3VersionKeyFAF93626","artifactHashParameter":"AssetParameters4cd61014b71160e8c66fe167e43710d5ba068b80b134e9bd84508cf9238b2392ArtifactHashE56CD69A"}
Storing asset asset.4cd61014b71160e8c66fe167e43710d5ba068b80b134e9bd84508cf9238b2392 at s3://totally-random-s3-bucket-in-my-account/assets/4cd61014b71160e8c66fe167e43710d5ba068b80b134e9bd84508cf9238b2392.zip
```

I.e. preparing assets, then picking some random bucket.  It's not random in the sense I always get this one, but I have no clue why this one. It's some test CDK project made by someone in my organisation.

**Comment by berenddeboer** [comment]
Some more hacking: have changed the deploy command to:

```
cdk -a . deploy example --require-approval=never --verbose --toolkit-stack-name example
```

This then fails with:

```
example failed: Error: The CDK toolkit stack (example) does not have an output named BucketName. Use 'cdk bootstrap' to correct this.
```

I can "cdk deploy" fine from my local machine.

**Comment by berenddeboer** [comment]
Ah right, I think I'm starting to get this. This is pretty new stuff. So CDK didn't attempt to write to a random stack at all, but to the bootstrap stack. So my stack needs to have permissions to write to this [bootstrap stack](https://docs.aws.amazon.com/cdk/latest/guide/bootstrapping.html) it seems.

**Comment by berenddeboer** [comment]
OK, I think I got this fixed: people. Try setting:

```
"@aws-cdk/core:newStyleStackSynthesis": true
```

in `cdk.json` and rerun `cdk bootstrap`. Then you don't need GetTemplate permission and you don't seen these errors.

**Comment by baartch** [comment]
> OK, I think I got this fixed: people. Try setting:
> 
> ```
> "@aws-cdk/core:newStyleStackSynthesis": true
> ```
> 
> in `cdk.json` and rerun `cdk bootstrap`. Then you don't need GetTemplate permission and you don't seen these errors.

Thank you very much!! Now that you mention it, I remember adding this to a test project once before 🤦

**Comment by rix0rrr** [comment]
Great to hear that you figured it out!
