### ISSUE TITLE
@aws-cdk/custom-resources: not possible to update from 1.79.0 => 1.100.0

### ISSUE THREAD

**Issue by jimfleming** [aws/aws-cdk#14396]
Custom resources recently changed the encoding of their parameters to a JSON string. This appears to make it impossible to update CDK or the custom resources module from 1.79 to 1.100. Previous versions did not require a `JSON.parse` call in the lambda to read the custom resource parameters.

### Reproduction Steps

1. Deploy a custom resource on cdk@1.79.0 + @aws-cdk/custom-resources@1.79.0.
2. Update to cdk@1.100.0 + @aws-cdk/custom-resources@1.100.0.
3. Deploy the same custom resource.

### What did you expect to happen?

It should deploy successfully without tearing down the stack which does not appear to be possible.

### What actually happened?

Fails to deploy with an error: `awsService[call.action] is not a function.`

This is because `call` is a JSON blob on 1.100 instead of an object as in 1.79. This blob isn't parsed in the old lambda and so `action` is not a property of `call`.

### Environment

  - **CDK CLI Version: 1.79.0**
  - **Framework Version: 1.79.0**
  - **Node.js Version: 14.16.1**
  - **OS: MacOS Big Sur 11.2.3 (20D91)**
  - **Language (Version): Node 14.16.1**

### Other

```
user@Users-MacBook-Pro repo % cdk deploy MyStack --force
MyStack: deploying...
[0%] start: Publishing a5a55f40f05c1031f30cc935c76b58b0b7dbc81e70845edf4ef615d6580ae04d:current
[50%] success: Published a5a55f40f05c1031f30cc935c76b58b0b7dbc81e70845edf4ef615d6580ae04d:current
[50%] start: Publishing 67b7823b74bc135986aa72f889d6a8da058d0c4a20cbc2dfc6f78995fdd2fc24:current
[100%] success: Published 67b7823b74bc135986aa72f889d6a8da058d0c4a20cbc2dfc6f78995fdd2fc24:current
MyStack: creating CloudFormation changeset...
1:43:48 PM | UPDATE_FAILED        | Custom::AWS             | CustomGroupThingGroup16FE0278
Invalid PhysicalResourceId
  new CustomResource (/Users/user/Projects/repo/node_modules/@aws-cdk/core/lib/custom-resource.js:30:25)
  \_ new AwsCustomResource (/Users/user/Projects/repo/node_modules/@aws-cdk/custom-resources/lib/aws-custom-resource/aws-d response status [FAILED] from custom resource. Message returned: awsService[call.action] is not a function (RequestId:
custom-resource.js:213:31)
  \_ new IoTThingGroup (/Users/user/Projects/repo/lib/constructs/IoTThingGroup.js:19:28)
  \_ new MyStack (/Users/user/Projects/repo/lib/stacks/MyStack.js:152:33)
  \_ Object.<anonymous> (/Users/user/Projects/repo/bin/repo.js:35:24)
  \_ Module._compile (internal/modules/cjs/loader.js:1063:30)
  \_ Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
  \_ Module.load (internal/modules/cjs/loader.js:928:32)
  \_ Function.Module._load (internal/modules/cjs/loader.js:769:14)
  \_ Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)
  \_ internal/main/run_main_module.js:17:47
[██████████▌···············································] (2/11)
1:43:48 PM | UPDATE_FAILED        | Custom::AWS             | CustomGrou...p/Resource/Default
Invalid PhysicalResourceId
1:43:48 PM | UPDATE_FAILED        | Custom::AWS             | GreengrassV2IoTThi...y/Resource/Default
Received response status [FAILED] from custom resource. Message returned: awsService[call.action] is not a function (RequestId:
6bf48d89-7c2e-485f-a674-d300a95693e0)
1:43:50 PM | UPDATE_ROLLBACK_IN_P | AWS::CloudFormation::Stack | MyStack
The following resource(s) failed to update: [DefaultThingGroupC189758C, GreengrassV2IoTThingPolicyC8BED6A5, CustomGroup
ThingGroup16FE0278, GreengrassTokenExchangeRoleAliasFA0CF103].
1:44:51 PM | UPDATE_FAILED        | Custom::AWS             | CustomGrou...p/Resource/Default
Received response status [FAILED] from custom resource. Message returned: Missing required key 'thingGroupProperties' in params
(RequestId: 681ed503-b8d5-4e88-beee-41b036588aa8)
1:44:52 PM | UPDATE_ROLLBACK_FAIL | AWS::CloudFormation::Stack | MyStack
The following resource(s) failed to update: [DefaultThingGroupC189758C, CustomGroupThingGroup16FE0278].
 ❌  MyStack failed: Error: The stack named MyStack failed to deploy: UPDATE_ROLLBACK_FAILED (The following resource(s) failed to update: [DefaultThingGroupC189758C, CustomGroupThingGroup16FE0278]. )
    at Object.waitForStackDeploy (/usr/local/lib/node_modules/aws-cdk/lib/api/util/cloudformation.ts:307:11)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at Object.deployStack (/usr/local/lib/node_modules/aws-cdk/lib/api/deploy-stack.ts:297:26)
    at CdkToolkit.deploy (/usr/local/lib/node_modules/aws-cdk/lib/cdk-toolkit.ts:180:24)
    at initCommandLine (/usr/local/lib/node_modules/aws-cdk/bin/cdk.ts:208:9)
The stack named MyStack failed to deploy: UPDATE_ROLLBACK_FAILED (The following resource(s) failed to update: [DefaultThingGroupC189758C, CustomGroupThingGroup16FE0278]. )
```

--- 

This is :bug: Bug Report

**Comment by jogold** [comment]
Can you share the event received by the handler?

**Comment by jimfleming** [comment]
```
{
    "RequestType": "Delete",
    "ServiceToken": "...",
    "ResponseURL": "...",
    "StackId": "...",
    "RequestId": "...",
    "LogicalResourceId": "...",
    "PhysicalResourceId": "...",
    "ResourceType": "Custom::AWS",
    "ResourceProperties": {
        "ServiceToken": "...",
        "Delete": "{\"service\":\"Iot\",\"action\":\"deleteThingGroup\",\"parameters\":{\"thingGroupName\":\"ThingName\"}}",
        "InstallLatestAwsSdk": "true",
        "Create": "{\"service\":\"Iot\",\"action\":\"createThingGroup\",\"parameters\":{\"thingGroupName\":\"ThingName\"},\"physicalResourceId\":{\"responsePath\":\"thingGroupArn\"}}",
        "Update": "{\"service\":\"Iot\",\"action\":\"updateThingGroup\",\"parameters\":{\"thingGroupName\":\"ThingName\"},\"physicalResourceId\":{\"responsePath\":\"thingGroupArn\"}}"
    }
}
```

**Comment by jogold** [comment]
So it fails during the `Delete`, did you change the physical resource id? And the `Update` event succeeds?

**Comment by jimfleming** [comment]
> did you change the physical resource id?

Nope.

>  And the Update event succeeds?

Nope.

In fact, nothing should be deleted or updated. No changes were made between deployments.

The missing `thingGroupProperties` is a red herring. Even if specified, it would also be missing because of the JSON string not being parsed. It is not required if `thingGroupName` is provided.

**Comment by jogold** [comment]
@jimfleming I was able to successfully deploy the following with v1.79.0

```ts
new cr.AwsCustomResource(this, 'ListBuckets', {
  onUpdate: {
    service: 'S3',
    action: 'listBuckets',
    physicalResourceId: cr.PhysicalResourceId.of('buckets'),
    outputPath: 'Buckets.0.Name'
  },
  policy: cr.AwsCustomResourcePolicy.fromStatements([
    new iam.PolicyStatement({
      actions: ['s3:*'],
      resources: ['*']
    })
  ]),
  installLatestAwsSdk: false,
});
```

then upgrade to v1.101.0 and deploy again.

With v1.101.0 the custom resource gets update because its properties change (new format) but the underlying Lambda function code is updated before so it correctly parses the new format. Since I'm not changing the physical resource id, my custom resource doesn't receive a Delete event.

Anything special in your setup that I'm missing?

**Comment by jimfleming** [comment]
We're using `onCreate` and `onDelete` as well as `cr.PhysicalResourceId.fromResponse`. See full example below:

```
const policy = cr.AwsCustomResourcePolicy.fromSdkCalls({
  resources: cr.AwsCustomResourcePolicy.ANY_RESOURCE,
});

new cr.AwsCustomResource(this, 'ThingGroup', {
  onCreate: {
    service: 'Iot',
    action: 'createThingGroup',
    parameters: {
        thingGroupName: thingGroupName,
    },
    physicalResourceId: cr.PhysicalResourceId.fromResponse('thingGroupArn'),
  },
  onUpdate: {
    service: 'Iot',
    action: 'updateThingGroup',
    parameters: {
        thingGroupName: thingGroupName,
    },
    physicalResourceId: cr.PhysicalResourceId.fromResponse('thingGroupArn'),
  },
  onDelete: {
    service: 'Iot',
    action: 'deleteThingGroup',
    parameters: {
      thingGroupName: thingGroupName,
    },
  },
  policy: policy,
  logRetention: logs.RetentionDays.ONE_DAY,
});
```

Perhaps our `physicalResourceId` is incorrectly defined causing an unnecessary delete?

**Comment by jogold** [comment]
Can you try this?
* Upgrade CDK to latest
* Remove the `onUpdate` and `onDelete` calls
* Synth / Deploy
* Put back the `onUpdate` and `onDelete` call
* Synth / Deploy

**Comment by jimfleming** [comment]
This still fails. I'm not entirely sure what operation should be called on this custom resource without onUpdate/onDelete. I believe the cause of the error is the same. The new CDK posts custom resource props as a JSON blob while the currently deployed custom resource handler expects an object.

```
CustomResource attribute error: Vendor response doesn't contain thingGroupName key in object
arn:aws:cloudformation:<region>:<account>:stack/MyStack/<uuid>|MyThingGroup|<uuid> in S3 bucket <bucket>
9:08:23 AM | UPDATE_FAILED        | Custom::AWS             | MyThingGroup.../Resource/Default
Received response status [FAILED] from custom resource. Message returned: Missing required key 'thingGroupProperties' in params (
RequestId: <uuid>)
9:08:24 AM | UPDATE_ROLLBACK_FAIL | AWS::CloudFormation::Stack | MyStack
The following resource(s) failed to update: [MyThingGroup].



 ❌  MyStack failed: Error: The stack named MyStack failed to deploy: UPDATE_ROLLBACK_FAILED (The following resource(s) failed to update: [MyThingGroup]. )
    at Object.waitForStackDeploy (/Users/user/node_modules/aws-cdk/lib/api/util/cloudformation.ts:307:11)
    at processTicksAndRejections (node:internal/process/task_queues:93:5)
    at Object.deployStack (/Users/user/node_modules/aws-cdk/lib/api/deploy-stack.ts:294:26)
    at CdkToolkit.deploy (/Users/user/node_modules/aws-cdk/lib/cdk-toolkit.ts:180:24)
    at initCommandLine (/Users/user/node_modules/aws-cdk/bin/cdk.ts:209:9)
The stack named MyStack failed to deploy: UPDATE_ROLLBACK_FAILED (The following resource(s) failed to update: [MyThingGroup]. )
```

**Comment by jogold** [comment]
Let's try the other way around:
* On v1.79.0, remove the `onUpdate` and `onDelete` calls
* Deploy
* Update to > 1.100.0, deploy
* PUt back the `onUpdate` and `onDelete` calls

**Comment by rix0rrr** [comment]
I'm pretty sure this has nothing to do with the upgrade to 1.100.0 -- you also wouldn't have been able to update the ThingGroup if you had stayed on 1.79.0.

That's because `UpdateThingGroup`, which you're calling, has a required parameter called `thingGroupProperties`, which you're not passing in your set of Update arguments:

https://docs.aws.amazon.com/iot/latest/apireference/API_UpdateThingGroup.html

The error message you pasted even told you:

```
Received response status [FAILED] from custom resource. Message returned: Missing required key 'thingGroupProperties' in params 
```

**Comment by jimfleming** [comment]
As discussed above thingGroupProperties is not required per the docs but it was provided in tests anyway. It will always be undefined because the payload is not in the correct format after the version bump. This was confirmed through logging inside of the lambda handler. Updating the thing group works fine on previous versions.

I don't have time to further debug this issue but this is readily reproducible using the custom resource provided above.
