### ISSUE TITLE
(ssm): Dynamic SSM parameter reference introduced in #14205 doesn't work for lists

### ISSUE THREAD

**Issue by tomas-mazak** [aws/aws-cdk#14476]
In CDK 1.101.0 a breaking change was introduced (PR #14205): References to SSM parameters now don't use CFN parameters of type `AWS::SSM::Parameter::Value<String>`, but use dynamic resolution using `{{resolve:ssm:...}}`. This way, no CFN function can be applied on the parameter value, because as it seems those are evaluated before the parameter resolution.

For us, this means we cannot import any list values from SSM parameters, because `Fn::Split` cannot be applied.

### Reproduction Steps

```ts
    const getStringListParam = (name: string) => {
      return Fn.split(',', StringParameter.valueForStringParameter(scope, `${basePath}/${name}`));
    };

    const vpc = Vpc.fromVpcAttributes(scope, id, {
      vpcId: ssm.StringParameter.valueForStringParameter(scope, `${basePath}/VpcId`),
      availabilityZones: getStringListParam('AvailabilityZones'),
      privateSubnetIds: getStringListParam('PrivateSubnetIds'),
      privateSubnetRouteTableIds: getStringListParam('PrivateSubnetRouteTableIds'),
    });
```

### What did you expect to happen?

The code above works perfectly fine up to aws-cdk version `1.100.0`

### What actually happened?

In `1.101.0`, the above code renders to 

```
              "Fn::Split": [
                ",",
                "{{resolve:ssm:/platform/vpc/default/PrivateSubnetIds}}"
              ]
```
what is failing in Cloudformation (IDs obfuscated): 

```
The subnet ID 'subnet-1111111,subnet-222222' is not valid (Service: AmazonElasticLoadBalancing; Status Code: 400; Error Code: InvalidSubnet; Request ID: 1111-2222-3333-4444-5555; Proxy: null)
```

### Environment

  - **CDK CLI Version  :** 1.101.0
  - **Framework Version:** 1.101.0
  - **Node.js Version:** v10.19.0
  - **OS               :** Ubuntu 20.04.2 LTS
  - **Language (Version):** TypeScript

--- 

This is :bug: Bug Report

**Comment by tapz** [comment]
Reading the repository arn from SSM does not work either anymore:

```
export class FooBarStack extends core.Stack {
  constructor(scope: core.Construct, id: string, props: FooBarStackProps) {
    super(scope, id, props);
    ...
    const repoArn = ssm.StringParameter.fromStringParameterName(
      this,
      `FooBarRepositoryArn`,
      `/foobar-repository-arn`
    );

    const repo = ecr.Repository.fromRepositoryAttributes(this, 'FooBarRepository', {
      repositoryName: 'foobar',
      repositoryArn: repoArn.stringValue,
    });

    const container = taskDefinition.addContainer(`FooBarContainer`, {
      image: ecs.ContainerImage.fromEcrRepository(repo, 'prod'),
      ...
    });
    ...
}
```

Produces an invalid template:

 ```
            "Image": {
              "Fn::Join": [
                "",
                [
                  {
                    "Fn::Select": [
                      4,
                      {
                        "Fn::Split": [
                          ":",
                          "{{resolve:ssm:/foobar-repository-arn}}"
                        ]
                      }
                    ]
                  },
                  ".dkr.ecr.",
                  {
                    "Fn::Select": [
                      3,
                      {
                        "Fn::Split": [
                          ":",
                          "{{resolve:ssm:/foobar-repository-arn}}"
                        ]
                      }
                    ]
                  },
                  ".",
                  {
                    "Ref": "AWS::URLSuffix"
                  },
                  "/foobar:prod"
                ]
              ]
            },
```

...which causes an error when deploying:

```
FoorBarStack failed: Error [ValidationError]: Template error: Fn::Select  cannot select nonexistent value at index 4
    at Request.extractError (/usr/local/Cellar/aws-cdk/1.101.0/libexec/lib/node_modules/aws-cdk/node_modules/aws-sdk/lib/protocol/query.js:50:29)
    at Request.callListeners (/usr/local/Cellar/aws-cdk/1.101.0/libexec/lib/node_modules/aws-cdk/node_modules/aws-sdk/lib/sequential_executor.js:106:20)
    at Request.emit (/usr/local/Cellar/aws-cdk/1.101.0/libexec/lib/node_modules/aws-cdk/node_modules/aws-sdk/lib/sequential_executor.js:78:10)
    at Request.emit (/usr/local/Cellar/aws-cdk/1.101.0/libexec/lib/node_modules/aws-cdk/node_modules/aws-sdk/lib/request.js:688:14)
    at Request.transition (/usr/local/Cellar/aws-cdk/1.101.0/libexec/lib/node_modules/aws-cdk/node_modules/aws-sdk/lib/request.js:22:10)
    at AcceptorStateMachine.runTo (/usr/local/Cellar/aws-cdk/1.101.0/libexec/lib/node_modules/aws-cdk/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at /usr/local/Cellar/aws-cdk/1.101.0/libexec/lib/node_modules/aws-cdk/node_modules/aws-sdk/lib/state_machine.js:26:10
    at Request.<anonymous> (/usr/local/Cellar/aws-cdk/1.101.0/libexec/lib/node_modules/aws-cdk/node_modules/aws-sdk/lib/request.js:38:9)
    at Request.<anonymous> (/usr/local/Cellar/aws-cdk/1.101.0/libexec/lib/node_modules/aws-cdk/node_modules/aws-sdk/lib/request.js:690:12)
    at Request.callListeners (/usr/local/Cellar/aws-cdk/1.101.0/libexec/lib/node_modules/aws-cdk/node_modules/aws-sdk/lib/sequential_executor.js:116:18) {
  code: 'ValidationError',
  time: 2021-05-04T11:10:33.741Z,
  requestId: '4c9c2be6-d329-4245-99f4-f1671abc146e',
  statusCode: 400,
  retryable: false,
  retryDelay: 161.3208368473147
}
Template error: Fn::Select  cannot select nonexistent value at index 4
```

**Comment by jogold** [comment]
@MrArnoldPalmer should #14205 be reverted? There's also https://github.com/aws/aws-cdk/pull/14205#issuecomment-831762640.

**Comment by MrArnoldPalmer** [comment]
@jogold I do think we should revert at this point, we will have to revisit and see where to go from here. I do want to get this in, maybe in v2 if we can't figure out a way to not break these use cases?

**Comment by jogold** [comment]
> @jogold I do think we should revert at this point, we will have to revisit and see where to go from here. I do want to get this in, maybe in v2 if we can't figure out a way to not break these use cases?

#14527

**Comment by tomas-mazak** [comment]
@jogold @MrArnoldPalmer sorry if this is off topic but I think that this issue also shows a little gap in CDK tests - the tests assert that "code renders to expected CFN template" but not whether such template is valid and semantically correct - it would be awesome if CloudFormation could be run in some dry-run mode, where it would call the tester's mock API instead of the actual resource providers ... with assertions like: "creation of ABC resource was requested with XYZ parameters". What do you think?
