### ISSUE TITLE
(aws-cdk): Using Aspects with Python

### ISSUE THREAD

**Issue by rectalogic** [aws/aws-cdk#14507]
With CDK v2 the `_on_prepare()` hook is gone and one recommendation is to use Aspects.
These don't seem to work with Python.

### Reproduction Steps

```python
#!/usr/bin/env python3
import os

import aws_cdk as cdk
from constructs import IConstruct


class StackAspect(cdk.IAspect):
    def visit(self, node: IConstruct) -> None:
        print(f"visiting {node}");


app = cdk.App()
stack = cdk.Stack(app, "AspectsStack")
cdk.Aspects.of(stack).add(StackAspect())

app.synth()
```

### What did you expect to happen?
The Aspect should run during the prepare stage.

### What actually happened?
```
Traceback (most recent call last):
  File "app.py", line 15, in <module>
    cdk.Aspects.of(stack).add(StackAspect())
  File "/Users/aw/Projects/cureatr/dev/cureatr/experiments/cdk/aspects/.venv/lib/python3.8/site-packages/aws_cdk/__init__.py", line 1466, in add
    return typing.cast(None, jsii.invoke(self, "add", [aspect]))
  File "/Users/aw/Projects/cureatr/dev/cureatr/experiments/cdk/aspects/.venv/lib/python3.8/site-packages/jsii/_kernel/__init__.py", line 128, in wrapped
    return _recursize_dereference(kernel, fn(kernel, *args, **kwargs))
  File "/Users/aw/Projects/cureatr/dev/cureatr/experiments/cdk/aspects/.venv/lib/python3.8/site-packages/jsii/_kernel/__init__.py", line 340, in invoke
    response = self.provider.invoke(
  File "/Users/aw/Projects/cureatr/dev/cureatr/experiments/cdk/aspects/.venv/lib/python3.8/site-packages/jsii/_kernel/providers/process.py", line 359, in invoke
    return self._process.send(request, InvokeResponse)
  File "/Users/aw/Projects/cureatr/dev/cureatr/experiments/cdk/aspects/.venv/lib/python3.8/site-packages/jsii/_kernel/providers/process.py", line 311, in send
    data = json.dumps(req_dict, default=jdefault).encode("utf8")
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/json/__init__.py", line 234, in dumps
    return cls(
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/Users/aw/Projects/cureatr/dev/cureatr/experiments/cdk/aspects/.venv/lib/python3.8/site-packages/jsii/_kernel/providers/process.py", line 151, in jdefault
    raise TypeError("Don't know how to convert object to JSON: %r" % obj)
TypeError: Don't know how to convert object to JSON: <__main__.StackAspect object at 0x10f81f580>
```

### Environment

  - **CDK CLI Version  :** 2.0.0-rc.1 (build 983379b)
  - **Framework Version:** aws_cdk_lib-2.0.0rc1, constructs-10.0.5
  - **Node.js Version:** v14.16.0
  - **OS               :** macOS 10.15.7
  - **Language (Version):** python 3.8.8

--- 

This is :bug: Bug Report

**Comment by rectalogic** [comment]
Need to `@jsii.implements(core.IAspect)`

**Comment by keepler-ivanmarques** [comment]
Using this same sample with the jsii annotation results in a Javascript error.

```
#!/usr/bin/env python3

import jsii
import aws_cdk as cdk
from constructs import IConstruct


@jsii.implements(cdk.IAspect)
class StackAspect(cdk.IAspect):
    def visit(self, node: IConstruct) -> None:
        print(f"visiting {node}");


app = cdk.App()
stack = cdk.Stack(app, "AspectsStack")
cdk.Aspects.of(stack).add(StackAspect())

app.synth()
```

Result:

```

jsii.errors.JavaScriptError:
  TypeError: Cannot read property 'setContext' of undefined
      at App.loadContext (/private/var/folders/dk/g35p0fxd719dz_nbyct9y1b40000gp/T/jsii-kernel-bXMWaf/node_modules/aws-cdk-lib/lib/core/lib/app.js:78:23)
      at new App (/private/var/folders/dk/g35p0fxd719dz_nbyct9y1b40000gp/T/jsii-kernel-bXMWaf/node_modules/aws-cdk-lib/lib/core/lib/app.js:39:14)
      at /private/var/folders/dk/g35p0fxd719dz_nbyct9y1b40000gp/T/tmpa5vwueu9/lib/program.js:8367:58
      at Kernel._wrapSandboxCode (/private/var/folders/dk/g35p0fxd719dz_nbyct9y1b40000gp/T/tmpa5vwueu9/lib/program.js:8795:24)
      at Kernel._create (/private/var/folders/dk/g35p0fxd719dz_nbyct9y1b40000gp/T/tmpa5vwueu9/lib/program.js:8367:34)
      at Kernel.create (/private/var/folders/dk/g35p0fxd719dz_nbyct9y1b40000gp/T/tmpa5vwueu9/lib/program.js:8108:29)
      at KernelHost.processRequest (/private/var/folders/dk/g35p0fxd719dz_nbyct9y1b40000gp/T/tmpa5vwueu9/lib/program.js:9692:36)
      at KernelHost.run (/private/var/folders/dk/g35p0fxd719dz_nbyct9y1b40000gp/T/tmpa5vwueu9/lib/program.js:9655:22)
      at Immediate._onImmediate (/private/var/folders/dk/g35p0fxd719dz_nbyct9y1b40000gp/T/tmpa5vwueu9/lib/program.js:9656:46)
      at processImmediate (internal/timers.js:464:21)


```

**Comment by keepler-ivanmarques** [comment]
Using this same sample with jsii.implements annotation results in an error again:

```
#!/usr/bin/env python3

import jsii
import aws_cdk as cdk
from constructs import IConstruct


@jsii.implements(cdk.IAspect)
class StackAspect(cdk.IAspect):
    def visit(self, node: IConstruct) -> None:
        print(f"visiting {node}")


app = cdk.App()
stack = cdk.Stack(app, "AspectsStack")
cdk.Aspects.of(stack).add(StackAspect())

app.synth()
```

## Result
```
TypeError: Don't know how to convert object to JSON: <__main__.StackAspect object at 0x1036462b0>
```


## Environment
CDK CLI Version : 2.0.0-rc.23
Framework Version: aws_cdk_lib-2.0.0rc23, constructs-10.0.5
Node.js Version: v14.17.6
OS : macOS 11.2
Language (Version): python 3.8.9
