### ISSUE TITLE
Constructing software.amazon.awscdk.core.App Throws JsiiException

### ISSUE THREAD

**Issue by egglestonbd** [aws/aws-cdk#14592]
### The Question
When running a Junit Jupiter CDK Stack Test (estabilished from the initializer project), 
the construction of software.amazon.awscdk.core.App throws the following Exception.  

What configurations do we need to use to ensure that we are not failing with this exception?

```
software.amazon.jsii.JsiiException: Child process exited unexpectedly!
```

We have also seen this with the following stack:

```
software.amazon.jsii.JsiiException: Child process exited unexpectedly!
	at org.mypackage.cdk.myawsservice.CdkStackTest.testStack(StackTest.java:xx)

/builds/workspace/project/tmp/jsii-java-runtime799975129425301004/bin/jsii-runtime.js:4
    3129: module => {

                  ^
SyntaxError: Unexpected token >
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
```

We have seen this with versions: 1.97.0 & 1.100.0 of our CDK libraries.
We are consuming/using: software/amazon/jsii/jsii-runtime/1.29.0/jsii-runtime-1.29.0.jar (Note, our projects also are downloading 26-29).
We are running under Java 8.

Boiled down test class:

```
package org.mypackage.cdk.myawsservice;

import org.junit.jupiter.api.Test;
import software.amazon.awscdk.core.App;

class CdkStackTest {

  @Test
  void testStack() {
    App cdkApp = new App();
  }

}
```

### Environment

  - **CDK CLI Version:** 1.97.0 - 1.100.0
  - **Module Version:** ??
  - **Node.js Version:** v14.16.1
  - **OS:** Debian GNU/Linux 9 (stretch)
  - **Language (Version):** Java (8)

### Other information
None

**Comment by roskelleycj** [comment]
I wrapped the exception and logged this:

```
03:30:10.036 [main] INFO org.mypackage.cdk.myawsservice.CdkStackTest - Error occurred trying to construct the App! 
software.amazon.jsii.JsiiException: Client not created
	at software.amazon.jsii.JsiiRuntime.getClient(JsiiRuntime.java:348)
	at software.amazon.jsii.JsiiEngine.getClient(JsiiEngine.java:150)
	at software.amazon.jsii.JsiiEngine.loadModule(JsiiEngine.java:188)
	at software.amazon.jsii.JsiiEngine.loadModule(JsiiEngine.java:185)
	at software.amazon.jsii.JsiiEngine.createNewObject(JsiiEngine.java:597)
	at software.amazon.awscdk.core.App.<init>(App.java:47)
	at org.mypackage.cdk.myawsservice.CdkStackTest.constructApp(TestCdkStack.java:??)
        ... (Lots of Junipter/maven surefire logs)
```

Not sure that is useful though.

**Comment by rix0rrr** [comment]
This seems to be a jsii issue.

**Comment by RomainMuller** [comment]
Are you positive this runs with `node 14.x`? This looks like the kind of error you'd get if you were running with a node version that does not support `=>` notation yet (like node 6 or something). It might be that the test framework is manipulating the `$PATH` and you're not running what you think you are...

**Comment by kambleaa007** [comment]
Why closed this without resolving
I also face issue

Exception in thread "main" software.amazon.jsii.JsiiError: Failed to bundle asset APIStack/ImageGetAndSaveLambda/Code/Stage, bundle output is located at C:\Users\ashis\AppData\Local\Temp\cdk.out8oiXYK\asset.c21aaeea96db56d9f2b3aa436d4bc00549a2f460b8b7262e48a11f094e4acd74-error: Error: spawnSync docker ENOENT
Error: Failed to bundle asset APIStack/ImageGetAndSaveLambda/Code/Stage, bundle output is located at C:\Users\ashis\AppData\Local\Temp\cdk.out8oiXYK\asset.c21aaeea96db56d9f2b3aa436d4bc00549a2f460b8b7262e48a11f094e4acd74-error: Error: spawnSync docker ENOENT
    at AssetStaging.bundle (C:\Users\ashis\AppData\Local\Temp\jsii-kernel-0rfWdo\node_modules\aws-cdk-lib\core\lib\asset-staging.js:2:614)
    at AssetStaging.stageByBundling (C:\Users\ashis\AppData\Local\Temp\jsii-kernel-0rfWdo\node_modules\aws-cdk-lib\core\lib\asset-staging.js:1:4225)
    at stageThisAsset (C:\Users\ashis\AppData\Local\Temp\jsii-kernel-0rfWdo\node_modules\aws-cdk-lib\core\lib\asset-staging.js:1:1633)
    at Cache.obtain (C:\Users\ashis\AppData\Local\Temp\jsii-kernel-0rfWdo\node_modules\aws-cdk-lib\core\lib\private\cache.js:1:242)
    at new AssetStaging (C:\Users\ashis\AppData\Local\Temp\jsii-kernel-0rfWdo\node_modules\aws-cdk-lib\core\lib\asset-staging.js:1:2028)
    at new Asset (C:\Users\ashis\AppData\Local\Temp\jsii-kernel-0rfWdo\node_modules\aws-cdk-lib\aws-s3-assets\lib\asset.js:1:736)
    at AssetCode.bind (C:\Users\ashis\AppData\Local\Temp\jsii-kernel-0rfWdo\node_modules\aws-cdk-lib\aws-lambda\lib\code.js:1:4628)
    at new Function (C:\Users\ashis\AppData\Local\Temp\jsii-kernel-0rfWdo\node_modules\aws-cdk-lib\aws-lambda\lib\function.js:1:2803)
    at Kernel._Kernel_create (C:\Users\ashis\AppData\Local\Temp\jsii-java-runtime1709192525862307865\lib\program.js:10108:25)
    at Kernel.create (C:\Users\ashis\AppData\Local\Temp\jsii-java-runtime1709192525862307865\lib\program.js:9779:93)
        at software.amazon.jsii.JsiiRuntime.processErrorResponse(JsiiRuntime.java:150)
        at software.amazon.jsii.JsiiRuntime.requestResponse(JsiiRuntime.java:116)
        at software.amazon.jsii.JsiiClient.createObject(JsiiClient.java:89)
        at software.amazon.jsii.JsiiEngine.createNewObject(JsiiEngine.java:614)
        at software.amazon.awscdk.services.lambda.Function.<init>(Function.java:53)
        at software.amazon.awscdk.services.lambda.Function$Builder.build(Function.java:1126)
        at com.cwworkshop.api.APIStack.<init>(APIStack.java:80)
        at com.cwworkshop.WorkshopApp.main(WorkshopApp.java:30)
Bundling asset APIStack/ImageGetAndSaveLambda/Code/Stage...

PS D:\Algorithm\Aws\AWSWorkshop\amazon-codewhisperer-workshop\java\infrastructure>

**Comment by kambleaa007** [comment]
> Are you positive this runs with `node 14.x`? This looks like the kind of error you'd get if you were running with a node version that does not support `=>` notation yet (like node 6 or something). It might be that the test framework is manipulating the `$PATH` and you're not running what you think you are...

PS D:\Algorithm\Aws\AWSWorkshop\amazon-codewhisperer-workshop\java\infrastructure> node -v
v18.14.2


Still having issue

**Comment by MrArnoldPalmer** [comment]
@kambleaa007 your error is unrelated. You can open a new issue with a reproduction, but your error message is saying that the directory of the asset your pointing to doesn't exist, so double check that first.
