### ISSUE TITLE
(pipelines): npx cdk synth fails after new AWS SDK NodeJS version check

### ISSUE THREAD

**Issue by barry-the-sender** [aws/aws-cdk#14636]
The AWS SDK is checking for the Node version since version 2.903.0: https://github.com/aws/aws-sdk-js/blame/v2.903.0/scripts/check-node-version.js

Since then the CodeBuild build is failing at the `npx cdk synth` step. We are only using the CDK and are not using the AWS-SDK otherwise. We have upgraded all CDK dependencies to 1.103 and the following error still persists. 

```
[Container] 2021/05/11 09:41:01 Running command npx cdk synth
--
80 | internal/modules/cjs/loader.js:883
81 | throw err;
82 | ^
83 |  
84 | Error: Cannot find module '/root/.npm/_npx/260/lib/node_modules/cdk/node_modules/aws-cdk/node_modules/aws-sdk/scripts/check-node-version.js'
85 | at Function.Module._resolveFilename (internal/modules/cjs/loader.js:880:15)
86 | at Function.Module._load (internal/modules/cjs/loader.js:725:27)
87 | at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)
88 | at internal/main/run_main_module.js:17:47 {
89 | code: 'MODULE_NOT_FOUND',
90 | requireStack: []
91 | }
92 | npm ERR! code ELIFECYCLE
93 | npm ERR! errno 1
94 | npm ERR! aws-sdk@2.903.0 postinstall: `node scripts/check-node-version.js`
95 | npm ERR! Exit status 1
96 | npm ERR!
97 | npm ERR! Failed at the aws-sdk@2.903.0 postinstall script.
98 | npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

### Reproduction Steps

Setup a simple CDK Pipeline with the npm synth action:

```
      synthAction: SimpleSynthAction.standardNpmSynth({
        sourceArtifact,
        cloudAssemblyArtifact,
        buildCommand: 'npm run build',
        environment: {
          buildImage: LinuxBuildImage.STANDARD_5_0
        }
      })
```

### What did you expect to happen?

`npx cdk synth` to succeed.

### Environment

  - **CDK CLI Version  :**
  - **Framework Version:**
  - **Node.js Version:** 
  - **OS               :**
  - **Language (Version):** 

### Other

--- 

This is :bug: Bug Report

**Comment by barry-the-sender** [comment]
I found the issue: I didn't specify aws-cdk in the package.json, so it must have pulled an older version. To address this, make sure to `npm install aws-cdk` (not globally) so it lands in the package.json.
