### ISSUE TITLE
(cli): failed cloudformation deployment should show individual resource errors (in addition to stack error)

### ISSUE THREAD

**Issue by rix0rrr** [aws/aws-cdk#14780]
Right now, a failing stack deployment  always says something like "deployment failed: rollback requested by user" (or something).

This is what CloudFormation says the `StatusReason` is.

That's fair enough, but it's almost never useful. Typically, the error will be somewhere in the resource event log, and will be a message for a resource that ends up in `CREATE_FAILED` or `UPDATE_FAILED`:

```
12:34:82 | S3Bucket | CREATE_FAILED | Bucket with name 'foo' already exists
```

We should remember the individual error messages and print those again at the end.

---

This is a :rocket: Feature Request

**Comment by BenChaimberg** [comment]
It seems like we [already actually do this](https://github.com/aws/aws-cdk/blob/f4a2938cf6773bf80e3316abda82d03aed051108/packages/aws-cdk/lib/api/util/cloudformation/stack-activity-monitor.ts#L619). The final output of a failed deployment looks something like this:
```
TestAppStack: deploying...                                                                                                                                                           
TestAppStack: creating CloudFormation changeset...                                                                                                                                   
6:44:44 PM | CREATE_FAILED        | AWS::S3::Bucket        | TestAppBucket59492B1A                                                                                                   
cdk-chaimber-test-bucket already exists                                                                                                                                              
                                                                                                                                                                                     
        new Bucket (/Users/chaimber/opensource/aws-cdk/packages/@aws-cdk/aws-s3/lib/bucket.ts:1331:22)                                                                               
        \_ new TestAppStack (/Users/chaimber/opensource/test-app/lib/test-app-stack.ts:19:20)                                                                                        
        \_ Object.<anonymous> (/Users/chaimber/opensource/test-app/bin/test-app.ts:6:1)                                                                                              
        \_ Module._compile (node:internal/modules/cjs/loader:1102:14)                                                                                                                
        \_ Module.m._compile (/Users/chaimber/opensource/test-app/node_modules/ts-node/src/index.ts:1056:23)                                                                         
        \_ Module._extensions..js (node:internal/modules/cjs/loader:1131:10)                                                                                                         
        \_ Object.require.extensions.<computed> [as .ts] (/Users/chaimber/opensource/test-app/node_modules/ts-node/src/index.ts:1059:12)                                             
        \_ Module.load (node:internal/modules/cjs/loader:967:32)                                                                                                                     
        \_ Function.Module._load (node:internal/modules/cjs/loader:807:14)                                                                                                           
        \_ Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:76:12)                                                                                        
        \_ main (/Users/chaimber/opensource/test-app/node_modules/ts-node/src/bin.ts:198:14)                                                                                         
        \_ Object.<anonymous> (/Users/chaimber/opensource/test-app/node_modules/ts-node/src/bin.ts:288:3)                                                                            
        \_ Module._compile (node:internal/modules/cjs/loader:1102:14)                                                                                                                
        \_ Object.Module._extensions..js (node:internal/modules/cjs/loader:1131:10)                                                                                                  
        \_ Module.load (node:internal/modules/cjs/loader:967:32)                                                                                                                     
        \_ Function.Module._load (node:internal/modules/cjs/loader:807:14)                                                                                                           
        \_ Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:76:12)                                                                                        
        \_ node:internal/main/run_main_module:17:47                                                                                                                                  
                                                                                                                                                                                     
6:44:44 PM | ROLLBACK_IN_PROGRESS | AWS::CloudFormation::Stack | TestAppStack                                                                                                        
The following resource(s) failed to create: [TestAppBucket59492B1A]. Rollback requested by user.                                                                                     
                                                                                                                                                                                     
                                                                                                                                                                                     
 ❌  TestAppStack failed: Error: The stack named TestAppStack failed creation, it may need to be manually deleted from the AWS console: ROLLBACK_COMPLETE                            
    at Object.waitForStackDeploy (/Users/chaimber/opensource/aws-cdk/packages/aws-cdk/lib/api/util/cloudformation.ts:305:11)                                                         
    at processTicksAndRejections (node:internal/process/task_queues:93:5)                                                                                                            
    at Object.deployStack (/Users/chaimber/opensource/aws-cdk/packages/aws-cdk/lib/api/deploy-stack.ts:294:26)                                                                       
    at CdkToolkit.deploy (/Users/chaimber/opensource/aws-cdk/packages/aws-cdk/lib/cdk-toolkit.ts:180:24)                                                                             
    at initCommandLine (/Users/chaimber/opensource/aws-cdk/packages/aws-cdk/bin/cdk.ts:209:9)                                                                                        
The stack named TestAppStack failed creation, it may need to be manually deleted from the AWS console: ROLLBACK_COMPLETE
```

However, it seems that this traceback is often overwritten by the progress bar, resulting in a final output of:
```
TestAppStack: deploying...                                                                                                                                                           
TestAppStack: creating CloudFormation changeset...                                                                                                                                   
[████████▎·················································] (1/7)                                                                                                                   
                                                                                                                                                                                     
6:41:29 PM | CREATE_FAILED        | AWS::S3::Bucket        | TestAppBucket                                                                                                           
cdk-chaimber-test-bucket already exists                                                                                                                                              
6:41:29 PM | ROLLBACK_IN_PROGRESS | AWS::CloudFormation::Stack | TestAppStack                                                                                                        
The following resource(s) failed to create: [TestAppBucket59492B1A]. Rollback requested by user.                                                                                     
                                                                                                                                                                                     
                                                                                                                                                                                     
                                                                                                                                                                                     
                                                                                                                                                                                     
                                                                                                                                                                                     
                                                                                                                                                                                     
                                                                                                                                                                                     
                                                                                                                                                                                     
                                                                                                                                                                                     
                                                                                                                                                                                     
                                                                                                                                                                                     
                                                                                                                                                                                     
                                                                                                                                                                                     
                                                                                                                                                                                     
                                                                                                                                                                                     
                                                                                                                                                                                     
                                                                                                                                                                                     
                                                                                                                                                                                     
                                                                                                                                                                                     
                                                                                                                                                                                     
 ❌  TestAppStack failed: Error: The stack named TestAppStack failed creation, it may need to be manually deleted from the AWS console: ROLLBACK_COMPLETE                            
    at Object.waitForStackDeploy (/Users/chaimber/.nvm/versions/node/v15.3.0/lib/node_modules/aws-cdk/lib/api/util/cloudformation.ts:305:11)                                         
    at processTicksAndRejections (node:internal/process/task_queues:93:5)                                                                                                            
    at Object.deployStack (/Users/chaimber/.nvm/versions/node/v15.3.0/lib/node_modules/aws-cdk/lib/api/deploy-stack.ts:294:26)                                                       
    at CdkToolkit.deploy (/Users/chaimber/.nvm/versions/node/v15.3.0/lib/node_modules/aws-cdk/lib/cdk-toolkit.ts:180:24)                                                             
    at initCommandLine (/Users/chaimber/.nvm/versions/node/v15.3.0/lib/node_modules/aws-cdk/bin/cdk.ts:209:9)                                                                        
The stack named TestAppStack failed creation, it may need to be manually deleted from the AWS console: ROLLBACK_COMPLETE
```
I needed to disable the in-progress printing to get the first snippet to occur, but I'm not sure if it's a machine-dependent issue.

Going forward, we can:
1. remove the stack from the failed resources list
2. ensure the progress bar does not overwrite the failed resources list

Let me know what you think!
