### ISSUE TITLE
(aws_sns_subscriptions): EmailSubscription 'Only root constructs may have an empty ID' error when a parameter used as the email

### ISSUE THREAD

**Issue by amkuchta** [aws/aws-cdk#14919]
### Description
Using the following code, the stack fails to deploy:

```typescript
import { Construct } from 'constructs';
import {
  aws_sns as sns,
  aws_sns_subscriptions as subscriptions,
} from 'aws-cdk-lib';
import { KmsKeys } from './kms-keys';

export interface SnsTopicsProps {
  adminEmail: string;
  kmsKeys: KmsKeys;
  stackName: string;
}

export class SnsTopics extends Construct {
  public readonly notifications: sns.Topic;

  constructor(scope: Construct, id: string, props: SnsTopicsProps) {
    super(scope, id);

    this.notifications = new sns.Topic(this, 'Notifications', {
      displayName: `${props.stackName}-Notifications`,
      masterKey: props.kmsKeys.snsMasterKey,
    });

    this.notifications.addSubscription(
      new subscriptions.EmailSubscription(props.adminEmail)
    );
  }
}
```

The error thrown is as follows:

```
Error: Only root constructs may have an empty ID
    at new Node (C:\Users\amkuc\Source\Repos\video-on-demand-on-aws\aws-vod-cdk\node_modules\constructs\src\construct.ts:65:13)
    at new Construct (C:\Users\amkuc\Source\Repos\video-on-demand-on-aws\aws-vod-cdk\node_modules\constructs\src\construct.ts:449:17)
    at new Resource (C:\Users\amkuc\Source\Repos\video-on-demand-on-aws\aws-vod-cdk\node_modules\aws-cdk-lib\lib\core\lib\resource.ts:122:9)
    at new Subscription (C:\Users\amkuc\Source\Repos\video-on-demand-on-aws\aws-vod-cdk\node_modules\aws-cdk-lib\lib\aws-sns\lib\subscription.ts:76:9)
    at Topic.addSubscription (C:\Users\amkuc\Source\Repos\video-on-demand-on-aws\aws-vod-cdk\node_modules\aws-cdk-lib\lib\aws-sns\lib\topic-base.ts:74:9)
    at new SnsTopics (C:\Users\amkuc\Source\Repos\video-on-demand-on-aws\aws-vod-cdk\lib\sns-topics.ts:27:24)
    at new AwsVodCdkStack (C:\Users\amkuc\Source\Repos\video-on-demand-on-aws\aws-vod-cdk\lib\aws-vod-cdk-stack.ts:103:23)
    at Object.<anonymous> (C:\Users\amkuc\Source\Repos\video-on-demand-on-aws\aws-vod-cdk\bin\aws-vod-cdk.ts:18:1)
    at Module._compile (node:internal/modules/cjs/loader:1102:14)
    at Module.m._compile (C:\Users\amkuc\Source\Repos\video-on-demand-on-aws\aws-vod-cdk\node_modules\ts-node\src\index.ts:1056:23)
```

### Reproduction Steps
Attempt to generate a deployment that includes an `EmailSubscription` construct; a sample can be found [here](https://github.com/amkuchta/video-on-demand-on-aws/tree/cdk-conversion/aws-vod-cdk).

### What did you expect to happen?
The application should deploy with an SNS Topic that has an `EmailSubscription`.

### What actually happened?
See the above error message.

### Environment

  - **CDK CLI Version  :** 2.0.0-rc5
  - **Framework Version:** Typescript
  - **Node.js Version:** 15.3.0
  - **OS               :** Windows 10
  - **Language (Version):** Typescript 4.2.4

### Other

--- 

This is :bug: Bug Report

**Comment by njlynch** [comment]
This error would occur if the `props.adminEmail` was an empty string; are you sure the string is being set? I see in your code it's coming from `const adminEmail = this.node.tryGetContext('adminEmail') ?? '';`. I'd replace that with something like this as a first troubleshooting step:

```ts
const adminEmail = this.node.tryGetContext('adminEmail');
if (!adminEmail) { throw new Error('something wrong getting the adminEmail context!'); }
```

**Comment by amkuchta** [comment]
I'll give this a shot after work this evening.  The rest of my context variables are getting pulled ok, so I don't know why this one wouldn't be, but it is worth a shot!

**Comment by amkuchta** [comment]
So, it looks like you are right, @njlynch - the value is not being set from the context.  But that raises a new question for me of why that isn't happening when (almost) all of my other context variables are being set just fine (there is one other one that is also not set for some reason).  I'm going to dig into that - I'll open a new ticket if need be.

Thanks!
