### ISSUE TITLE
(stepfunctions): state machine name validation fails when tokens are used in name

### ISSUE THREAD

**Issue by jpascoe** [aws/aws-cdk#14923]
A bug was introduced in 1.93.0 that causes code to break using cdk creating step function with cf parameter value used in step function name.

https://github.com/aws/aws-cdk/issues/13289
https://github.com/aws/aws-cdk/commit/6c3d4071746179dde30f615602592c2523daa56e
https://github.com/aws/aws-cdk/commit/58de0de5a54b9d8fb4658566e85ef408c8861088

### Reproduction Steps

    project_id = core.CfnParameter(
        self, id='Project Id', description='Must be unique within your account. \
        Only lowercase characters, . and - are allowed. Max 12 character length.',
        constraint_description='Must be lowercase char, numbers, . or - with a length of 1-12 char.',
        allowed_pattern='([a-z0-9.-])+', max_length=12) 

    sfn_sandbox_sm, sfn_preprod_sm, sfn_prod_sm = self.create_step_functions(
        suffix='inference', project_id=project_id)
    
    sfn_sandbox_sm = stepfunctions.StateMachine(
        self, f'state-machine-{suffix}-sandbox', definition=start_state_sandbox,
        state_machine_name=f'ml-factory-sf-{suffix}-{project_id.value_as_string}-sandbox'
    )

### What did you expect to happen?

Step function is created as it was in v1.92.0

### What actually happened?

 Traceback (most recent call last):
      File "app.py", line 61, in <module>
        env=environ)
      File "/usr/local/share/pip-global/jsii/_runtime.py", line 83, in __call__
        inst = super().__call__(*args, **kwargs)
      File "/workspaces/ml-factory-aws/stacks/cdk_pipeline_stack.py", line 95, in __init__
        deployment_id='test', env=preprod_env)
      File "/usr/local/share/pip-global/jsii/_runtime.py", line 83, in __call__
        inst = super().__call__(*args, **kwargs)
      File "/workspaces/ml-factory-aws/stacks/cdk_pipeline_stage_stack.py", line 51, in __init__
        env=account_env)
      File "/usr/local/share/pip-global/jsii/_runtime.py", line 83, in __call__
        inst = super().__call__(*args, **kwargs)
      File "/workspaces/ml-factory-aws/stacks/s3_resource_stack.py", line 42, in __init__
        env=account_env)
      File "/usr/local/share/pip-global/jsii/_runtime.py", line 83, in __call__
        inst = super().__call__(*args, **kwargs)
      File "/workspaces/ml-factory-aws/stacks/ds_sc_product_stack.py", line 77, in __init__
        suffix='inference', project_id=project_id)
      File "/workspaces/ml-factory-aws/stacks/ds_sc_product_stack.py", line 1199, in create_step_functions
        state_machine_name=f'ml-factory-sf-{suffix}-{project_id.value_as_string}-sandbox',
      File "/usr/local/share/pip-global/jsii/_runtime.py", line 83, in __call__
        inst = super().__call__(*args, **kwargs)
      File "/usr/local/share/pip-global/aws_cdk/aws_stepfunctions/__init__.py", line 5100, in __init__
        jsii.create(StateMachine, self, [scope, id, props])
      File "/usr/local/share/pip-global/jsii/_kernel/__init__.py", line 282, in create
        for iface in getattr(klass, "__jsii_ifaces__", [])
      File "/usr/local/share/pip-global/jsii/_kernel/providers/process.py", line 344, in create
        return self._process.send(request, CreateResponse)
      File "/usr/local/share/pip-global/jsii/_kernel/providers/process.py", line 326, in send
        raise JSIIError(resp.error) from JavaScriptError(resp.stack)
    jsii.errors.JSIIError: State Machine name must match "^[0-9a-zA-Z+!@._-]+$". Received: ml-factory-sf-inference-${Token[TOKEN.327]}-sandbox

### Environment

  - **CDK CLI Version  : 1.93.0 (build c506d3b)**
  - **Framework Version:**
  - **Node.js Version: v14.17.0**
  - **OS               : Debian**
  - **Language (Version): Python 3.7.10** 

### Other

https://stackoverflow.com/questions/67769103/how-do-i-use-cloudformation-parameter-in-a-stepfunction-name

--- 

This is :bug: Bug Report

**Comment by shivlaks** [comment]
@jpascoe I believe this issue was resolved with #13970 which was included as of [`v1.98.0`](https://github.com/aws/aws-cdk/releases/tag/v1.98.0)

**Comment by shivlaks** [comment]
i'm resolving this issue as I believe it's already been fixed. feel free to re-open if i've missed something and there is still an outstanding issue that requires attention.
