### ISSUE TITLE
Windows Subsystem for Linux Support (SyntaxError: Unexpected token 'export')

### ISSUE THREAD

**Issue by MightyCrabKing** [aws/aws-cdk#15059]
Hi,

I'm currently trying to setup a new project with the CDK however im experiencing the following error after install:

cdk --version
/usr/local/lib/node_modules/aws-cdk/node_modules/uuid/dist/esm-browser/index.js:1
export { default as v1 } from './v1.js';
^^^^^^

SyntaxError: Unexpected token 'export'
    at wrapSafe (internal/modules/cjs/loader.js:984:16)
    at Module._compile (internal/modules/cjs/loader.js:1032:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1097:10)
    at Module.load (internal/modules/cjs/loader.js:933:32)
    at Function.Module._load (internal/modules/cjs/loader.js:774:14)
    at Module.require (internal/modules/cjs/loader.js:957:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/aws-cdk/lib/api/deploy-stack.ts:3:1)
    at Module._compile (internal/modules/cjs/loader.js:1068:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1097:10)

My node version is v14.17.0:
node -v
v14.17.0

i used the following cmd to install the cdk:

npm install -g aws-cdk

Any ideas what the issue is everywhere seems to suggest that being on v8+ of nodejs should fix the above issue.

Thanks!

**Comment by peterwoodworth** [comment]
Hey @MightyCrabKing, sorry you're having trouble with this.

Have you used the CDK before? Typically I upgrade my version by running `npm uninstall -g aws-cdk` then running `npm install -g aws-cdk@latest` 

[Here's the docs](https://docs.aws.amazon.com/cdk/latest/guide/getting_started.html#getting_started_prerequisites) for all the prerequisites to using the CDK

If you're still having issues let me know what you've tried

**Comment by MightyCrabKing** [comment]
Interestingly if i prefix with npm i get a valid return, also using npx works for a local directory install.

$  cdk --version
/usr/local/lib/node_modules/aws-cdk/node_modules/uuid/dist/esm-browser/index.js:1
export { default as v1 } from './v1.js';
^^^^^^

SyntaxError: Unexpected token 'export'
    at wrapSafe (internal/modules/cjs/loader.js:984:16)
    at Module._compile (internal/modules/cjs/loader.js:1032:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1097:10)
    at Module.load (internal/modules/cjs/loader.js:933:32)
    at Function.Module._load (internal/modules/cjs/loader.js:774:14)
    at Module.require (internal/modules/cjs/loader.js:957:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/aws-cdk/lib/api/deploy-stack.ts:3:1)
    at Module._compile (internal/modules/cjs/loader.js:1068:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1097:10)

$ npm cdk --version
6.14.13

Thanks though this should get me up and running.

**Comment by peterwoodworth** [comment]
Interesting, thanks for following up. Ping me if you have any more troubles with this
