### ISSUE TITLE
(apigateway): Support naming integrations

### ISSUE THREAD

**Issue by uqahump3** [aws/aws-cdk#15061]
The apigateway.MockIntegration feature is used to let API Gateway return a response without sending the request further to the backend. This is very helpful in the use case provided for CORS responses.
https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-apigateway.MockIntegration.html

The MockIntegration needs to add support for naming the integration. This will allow for better integration with AWS SA

### Use Case

Utilising AWS SAM for local development, once I have built my CDK template using 
`cdk synth -a "node bin/application" --no-staging > template.yaml`

I then utilise this template with SAM to develop and test. However the apigateway's MockIntegration does not possess a name value that is required for SAM, resulting in SAM throwing errors. (I intend to open a bug in SAM as well.)

The feature is required to compensate for limitations in AWS SAM.

### Other

```
Exception on /[OPTIONS]
Traceback (most recent call last):
  File "/opt/homebrew/Cellar/aws-sam-cli/1.24.1/libexec/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/opt/homebrew/Cellar/aws-sam-cli/1.24.1/libexec/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/opt/homebrew/Cellar/aws-sam-cli/1.24.1/libexec/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/opt/homebrew/Cellar/aws-sam-cli/1.24.1/libexec/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/opt/homebrew/Cellar/aws-sam-cli/1.24.1/libexec/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/opt/homebrew/Cellar/aws-sam-cli/1.24.1/libexec/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/opt/homebrew/Cellar/aws-sam-cli/1.24.1/libexec/lib/python3.8/site-packages/samcli/local/apigw/local_apigw_service.py", line 317, in _request_handler
    self.lambda_runner.invoke(route.function_name, event, stdout=stdout_stream_writer, stderr=self.stderr)
  File "/opt/homebrew/Cellar/aws-sam-cli/1.24.1/libexec/lib/python3.8/site-packages/samcli/commands/local/lib/local_lambda.py", line 107, in invoke
    function = self.provider.get(function_identifier)
  File "/opt/homebrew/Cellar/aws-sam-cli/1.24.1/libexec/lib/python3.8/site-packages/samcli/lib/providers/sam_function_provider.py", line 73, in get
    raise ValueError("Function name is required")
ValueError: Function name is required
```

---

This is a :rocket: Feature Request

**Comment by peterwoodworth** [comment]
Thanks for the feature request! How are you expecting to be able to add a name and get the name from the Integration?
