### ISSUE TITLE
(LayerVersion): Logical ID must adhere to the regular expression

### ISSUE THREAD

**Issue by bttong** [aws/aws-cdk#15093]
```
Encountered error jsii.errors.JSIIError: Resolution error: Logical ID must adhere to the regular expression: /^[A-Za-z][A-Za-z0-9]{1,254}$/, got '1F843E172' when calling LayerVersion construct in python
```

### Reproduction Steps

Python code:

```
ac = AssetCode("package")
layer = LayerVersion(self, "1", code=ac, description="Lambda power tool layer", compatible_runtimes=[_lambda.Runtime.PYTHON_3_8], layer_version_name='1.0')
```

### What did you expect to happen?

Creating a Lambda layer
### What actually happened?

Encountered the following error when running cdk synth cli:
```
Traceback (most recent call last):
  File "app.py", line 50, in <module>
    app.synth()
  File "/Users/tongbrit/Work/Artifacts/sample_codes/aws-cdk-examples/python/api-sqs-lambda/.env/lib/python3.8/site-packages/aws_cdk/core/__init__.py", line 15815, in synth
    return typing.cast(aws_cdk.cx_api.CloudAssembly, jsii.invoke(self, "synth", [options]))
  File "/Users/tongbrit/Work/Artifacts/sample_codes/aws-cdk-examples/python/api-sqs-lambda/.env/lib/python3.8/site-packages/jsii/_kernel/__init__.py", line 128, in wrapped
    return _recursize_dereference(kernel, fn(kernel, *args, **kwargs))
  File "/Users/tongbrit/Work/Artifacts/sample_codes/aws-cdk-examples/python/api-sqs-lambda/.env/lib/python3.8/site-packages/jsii/_kernel/__init__.py", line 340, in invoke
    response = self.provider.invoke(
  File "/Users/tongbrit/Work/Artifacts/sample_codes/aws-cdk-examples/python/api-sqs-lambda/.env/lib/python3.8/site-packages/jsii/_kernel/providers/process.py", line 359, in invoke
    return self._process.send(request, InvokeResponse)
  File "/Users/tongbrit/Work/Artifacts/sample_codes/aws-cdk-examples/python/api-sqs-lambda/.env/lib/python3.8/site-packages/jsii/_kernel/providers/process.py", line 326, in send
    raise JSIIError(resp.error) from JavaScriptError(resp.stack)
jsii.errors.JSIIError: Resolution error: Logical ID must adhere to the regular expression: /^[A-Za-z][A-Za-z0-9]{1,254}$/, got '1F843E172'.
```

### Environment

  - **CDK CLI Version  :** 1.108.0 (build b23f781)
  - **Framework Version:**
  - **Node.js Version:**  v14.15.4
  - **OS               :** macOS Calalina
  - **Language (Version):**  Python 3.8.7

### Other

--- 

This is :bug: Bug Report

**Comment by skinny85** [comment]
Thanks for opening the issue @bttong , but isn't it obvious from the error message what is happening?

> Encountered error jsii.errors.JSIIError: Resolution error: Logical ID must adhere to the regular expression: /^[A-Za-z][A-Za-z0-9]{1,254}$/, got '1F843E172' when calling LayerVersion construct in python

And you gave `"1"` as the logical ID.

**Comment by bttong** [comment]
oh, thank you for pointing that out. I mistakenly have version string instead of logical ID. It would be clearer if the error would say `got '1'` instead of `got '1F843E172'`
