### ISSUE TITLE
(aws-cloudwatch): GraphWidget.to_json not returning not-tokenised JSON

### ISSUE THREAD

**Issue by ciaranevans** [aws/aws-cdk#15222]
When using `aws_cloudwatch.GraphWidget`, I expect `to_json` to return me a JSON object that I could dump to a JSON string with `json.dumps()`. However the JSON object returned instead has references to `<jsii._reference_map.InterfaceDynamicProxy object at 0x1052041c0>` like objects.

For context, I'm trying to expose Widget JSONs as CfnOutputs of my Stack.

### Reproduction Steps

```python
import json

from aws_cdk import aws_cloudwatch, core


class CdkStack(core.Stack):
    def __init__(
        self, scope: core.Construct, construct_id: str, **kwargs
    ) -> None:
        super().__init__(scope, construct_id, **kwargs)

        metric_1 = aws_cloudwatch.Metric(
            metric_name="metric-1", namespace="my-metrics"
        )

        widget = aws_cloudwatch.GraphWidget(
            left=[
                metric_1
            ],
            period=core.Duration.minutes(1),
            title="My Widgets"
        )

        core.CfnOutput(self, "widget-json", value=json.dumps(widget.to_json()))

```
### What did you expect to happen?

A CfnOutput is created with the JSON String representation of my Widget.

### What actually happened?

```bash
Traceback (most recent call last):
  File "cdk/app.py", line 11, in <module>
    CdkStack(
  File "/Users/ciaran/dev/cdk-cloudwatch-custom-metrics/.venv/lib/python3.8/site-packages/jsii/_runtime.py", line 83, in __call__
    inst = super().__call__(*args, **kwargs)
  File "/Users/ciaran/dev/cdk-cloudwatch-custom-metrics/cdk/cdk_stack.py", line 83, in __init__
    core.CfnOutput(self, "widget-json", value=json.dumps(widget.to_json()))
  File "/Users/ciaran/.pyenv/versions/3.8.10/lib/python3.8/json/__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
  File "/Users/ciaran/.pyenv/versions/3.8.10/lib/python3.8/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/Users/ciaran/.pyenv/versions/3.8.10/lib/python3.8/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/Users/ciaran/.pyenv/versions/3.8.10/lib/python3.8/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type InterfaceDynamicProxy is not JSON serializable
```

If I take out the `json.dumps`:

```bash
Traceback (most recent call last):
  File "cdk/app.py", line 11, in <module>
    CdkStack(
  File "/Users/ciaran/dev/cdk-cloudwatch-custom-metrics/.venv/lib/python3.8/site-packages/jsii/_runtime.py", line 83, in __call__
    inst = super().__call__(*args, **kwargs)
  File "/Users/ciaran/dev/cdk-cloudwatch-custom-metrics/cdk/cdk_stack.py", line 83, in __init__
    core.CfnOutput(self, "widget-json", value=widget.to_json())
  File "/Users/ciaran/dev/cdk-cloudwatch-custom-metrics/.venv/lib/python3.8/site-packages/jsii/_runtime.py", line 83, in __call__
    inst = super().__call__(*args, **kwargs)
  File "/Users/ciaran/dev/cdk-cloudwatch-custom-metrics/.venv/lib/python3.8/site-packages/aws_cdk/core/__init__.py", line 16420, in __init__
    jsii.create(CfnOutput, self, [scope, id, props])
  File "/Users/ciaran/dev/cdk-cloudwatch-custom-metrics/.venv/lib/python3.8/site-packages/jsii/_kernel/__init__.py", line 278, in create
    args=_make_reference_for_native(self, args),
  File "/Users/ciaran/dev/cdk-cloudwatch-custom-metrics/.venv/lib/python3.8/site-packages/jsii/_kernel/__init__.py", line 144, in _make_reference_for_native
    return [_make_reference_for_native(kernel, i) for i in d]
  File "/Users/ciaran/dev/cdk-cloudwatch-custom-metrics/.venv/lib/python3.8/site-packages/jsii/_kernel/__init__.py", line 144, in <listcomp>
    return [_make_reference_for_native(kernel, i) for i in d]
  File "/Users/ciaran/dev/cdk-cloudwatch-custom-metrics/.venv/lib/python3.8/site-packages/jsii/_kernel/__init__.py", line 161, in _make_reference_for_native
    "data": {
  File "/Users/ciaran/dev/cdk-cloudwatch-custom-metrics/.venv/lib/python3.8/site-packages/jsii/_kernel/__init__.py", line 162, in <dictcomp>
    jsii_name: _make_reference_for_native(
  File "/Users/ciaran/dev/cdk-cloudwatch-custom-metrics/.venv/lib/python3.8/site-packages/jsii/_kernel/__init__.py", line 144, in _make_reference_for_native
    return [_make_reference_for_native(kernel, i) for i in d]
  File "/Users/ciaran/dev/cdk-cloudwatch-custom-metrics/.venv/lib/python3.8/site-packages/jsii/_kernel/__init__.py", line 144, in <listcomp>
    return [_make_reference_for_native(kernel, i) for i in d]
  File "/Users/ciaran/dev/cdk-cloudwatch-custom-metrics/.venv/lib/python3.8/site-packages/jsii/_kernel/__init__.py", line 138, in _make_reference_for_native
    "$jsii.map": {
  File "/Users/ciaran/dev/cdk-cloudwatch-custom-metrics/.venv/lib/python3.8/site-packages/jsii/_kernel/__init__.py", line 139, in <dictcomp>
    k: _make_reference_for_native(kernel, v) for k, v in d.items()
  File "/Users/ciaran/dev/cdk-cloudwatch-custom-metrics/.venv/lib/python3.8/site-packages/jsii/_kernel/__init__.py", line 138, in _make_reference_for_native
    "$jsii.map": {
  File "/Users/ciaran/dev/cdk-cloudwatch-custom-metrics/.venv/lib/python3.8/site-packages/jsii/_kernel/__init__.py", line 139, in <dictcomp>
    k: _make_reference_for_native(kernel, v) for k, v in d.items()
  File "/Users/ciaran/dev/cdk-cloudwatch-custom-metrics/.venv/lib/python3.8/site-packages/jsii/_kernel/__init__.py", line 144, in _make_reference_for_native
    return [_make_reference_for_native(kernel, i) for i in d]
  File "/Users/ciaran/dev/cdk-cloudwatch-custom-metrics/.venv/lib/python3.8/site-packages/jsii/_kernel/__init__.py", line 144, in <listcomp>
    return [_make_reference_for_native(kernel, i) for i in d]
  File "/Users/ciaran/dev/cdk-cloudwatch-custom-metrics/.venv/lib/python3.8/site-packages/jsii/_kernel/__init__.py", line 184, in _make_reference_for_native
    kernel.create(d.__class__, d)
  File "/Users/ciaran/dev/cdk-cloudwatch-custom-metrics/.venv/lib/python3.8/site-packages/jsii/_kernel/__init__.py", line 277, in create
    fqn=klass.__jsii_type__ or "Object",
AttributeError: type object 'InterfaceDynamicProxy' has no attribute '__jsii_type__'
```

### Environment

  - **CDK CLI Version  :** 1.109.0 (build c647e38)
  - **Framework Version:** 
  ```bash
  $ pip list
  ...
  aws-cdk.aws-cloudwatch              1.109.0
  aws-cdk.core                        1.109.0
  ```
  - **Node.js Version:**  v14.17.1
  - **OS               :** MacOS BigSur 11.4
  - **Language (Version):**  Python 3.8.10

### Other

I have tried playing around with `core.Lazy.string|list|any` but also have had no luck.

At this point it might just be easier to construct the Widget JSON myself 😅 

--- 

This is :bug: Bug Report

**Comment by ciaranevans** [comment]
Hey @madeline-k sorry for the tag but the bot seems to have picked you 😅 

Whilst I appreciate a fix/change isn't likely #soon, are you possibly able to confirm to me if this is the intended behaviour?

`to_json` to me, would indicate 'valid/dumpable' JSON.

**Comment by madeline-k** [comment]
Hey @ciaranevans, thanks for your patience on this! There should be a way to grab a valid JSON of your graph widgets, but it will probably not be as simple os `to_json`. 

A `stack.resolve(myWidget).to_json()` might work, or you might need to do some manipulation of the string given from `stack.resolve()`. 

Since you don't have your GraphWidgets as part of a Dashboard, they are actually not part of a stack. So in order for the above solution to work you might need to make a Dashboard just so that you can get the GraphWidget out of the Dashboard body. Here is an example of manipulating the JSON in a Cloudwatch dashboard body: https://github.com/aws/aws-cdk/issues/13942#issuecomment-865413158 It is pretty gnarly! So we probably could provide some better utilities for manipulating the Cloudwatch Dashboard and Widget JSON. 

I will take a deeper look into this, and hopefully come up with something better for you. In the mean time, the above might help you find a solution.

**Comment by madeline-k** [comment]
@ciaranevans Can you also explain your use-case? Why are you trying to output just the GraphWidget Json from you Cfn stack? I think it is more common to just create the Widgets and the Dashboards that will contain them in the same stack. But I am curious to understand your use-case to see how we can make the Cloudwatch module better!

**Comment by ciaranevans** [comment]
Hi @madeline-k thanks for getting back to me! 😄 

Sure, my use-case might be a bit fringe, we have a client who has several stacks deployed by different people (a few are from us) and we're hoping to get to a point where a stack can make a opinionated decision on _what_ metrics it deems are useful, and how they're displayed.

We can then make it so that we make another 'Dashboard Stack' that merely combs over all the stacks, grabs their exported Widget definitions and creates one dashboard with the metrics.

A lot of these stacks are ETL pipelines which just download data in the clients systems, so most of them will be exporting Widgets that will likely just be counts of files ingested, storage used etc. 

This is why we'd love to be able to define the widgets in-stack, then export them, where the dashboard stack will just create a big JSON body from them all. 

Hopefully that makes sense 😅

**Comment by madeline-k** [comment]
Hi @ciaranevans thanks for explaining your use-case! That definitely makes sense 👍 

I looked into it a little more, and I found the right way grab the JSON that you need. Change the last line of your code sample to:

```
core.CfnOutput(self, "widget-json", value=json.dumps(self.resolve(widget)))
```

And you should be good to go! I'll be closing this issue, feel free to re-open if you have any further questions on this topic.

**Comment by ciaranevans** [comment]
@madeline-k oh awesome! That works a treat!

Many thanks for the help! Out of curiosity, for next time I might find myself in a similar situation, what did you look up to find that out?
