### ISSUE TITLE
(aws-cloudfront): Lambda Edge won't delete after x days

### ISSUE THREAD

**Issue by jpSimkins** [aws/aws-cdk#15273]
## :question: General Issue

Lambda@Edge will not delete again, even after a couple of days. I had this happen before and reported on https://github.com/aws/aws-cdk/issues/15010. 

### Environment

 - **CDK CLI Version :**  1.108.0 (build b23f781)
 - **Module Version :**  1.108.0
 - **Node.js Version :**  v14.17.0
 - **OS               :**  `Linux Zeus 5.8.0-55-generic #62~20.04.1-Ubuntu SMP Wed Jun 2 08:55:04 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux`
 - **Language (Version):** Typescript (6.14.13)

### Other information

I think I narrowed it down to identify why this is happening. Whether it is a CDK issue or not, is yet to be determined. I also reported this to AWS support.

This happens when I attempted to deploy my stack and there is an error during the deployment which causes it to fail. For me, it was due to a Route53 record existing in another AWS account. It failed to deploy and notified me that the record existed in another account. I do not have the original error from the deployment. Once the deployment failed, I attempted to delete the stack but it failed. I then went to the other AWS account and deleted the legacy record. I attempted to re-deploy the stack but I got this error:

```
 ❌  TokuhdComCdnProd failed: Error [ValidationError]: Stack:arn:aws:cloudformation:us-east-1:117781944281:stack/TokuhdComCdnProd/ca18e680-d386-11eb-a2de-12446ecd5e01 is in DELETE_FAILED state and can not be updated.
    at Request.extractError (/home/jpsimkins/DevOps/oly-iac-mono-repo/aws/implementations/node_modules/aws-cdk/node_modules/aws-sdk/lib/protocol/query.js:50:29)
    at Request.callListeners (/home/jpsimkins/DevOps/oly-iac-mono-repo/aws/implementations/node_modules/aws-cdk/node_modules/aws-sdk/lib/sequential_executor.js:106:20)
    at Request.emit (/home/jpsimkins/DevOps/oly-iac-mono-repo/aws/implementations/node_modules/aws-cdk/node_modules/aws-sdk/lib/sequential_executor.js:78:10)
    at Request.emit (/home/jpsimkins/DevOps/oly-iac-mono-repo/aws/implementations/node_modules/aws-cdk/node_modules/aws-sdk/lib/request.js:688:14)
    at Request.transition (/home/jpsimkins/DevOps/oly-iac-mono-repo/aws/implementations/node_modules/aws-cdk/node_modules/aws-sdk/lib/request.js:22:10)
    at AcceptorStateMachine.runTo (/home/jpsimkins/DevOps/oly-iac-mono-repo/aws/implementations/node_modules/aws-cdk/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at /home/jpsimkins/DevOps/oly-iac-mono-repo/aws/implementations/node_modules/aws-cdk/node_modules/aws-sdk/lib/state_machine.js:26:10
    at Request.<anonymous> (/home/jpsimkins/DevOps/oly-iac-mono-repo/aws/implementations/node_modules/aws-cdk/node_modules/aws-sdk/lib/request.js:38:9)
    at Request.<anonymous> (/home/jpsimkins/DevOps/oly-iac-mono-repo/aws/implementations/node_modules/aws-cdk/node_modules/aws-sdk/lib/request.js:690:12)
    at Request.callListeners (/home/jpsimkins/DevOps/oly-iac-mono-repo/aws/implementations/node_modules/aws-cdk/node_modules/aws-sdk/lib/sequential_executor.js:116:18) {
  code: 'ValidationError',
  time: 2021-06-23T14:09:07.600Z,
  requestId: '12890703-51bc-470b-861f-7eca3004ba4f',
  statusCode: 400,
  retryable: false,
  retryDelay: 522.5789928022972
}
Stack:arn:aws:cloudformation:us-east-1:117781944281:stack/TokuhdComCdnProd/ca18e680-d386-11eb-a2de-12446ecd5e01 is in DELETE_FAILED state and can not be updated.
```

When I attempted to delete the stack, it fails with the error:

```
Resource handler returned message: "Lambda was unable to delete arn:aws:lambda:us-east-1:117781944281:function:TokuhdComCdnProd-assetsCdnedgeFunctionFn889F71D0-6DyAQZWdEyw2:1 because it is a replicated function. Please see our documentation for Deleting Lambda@Edge
Functions and Replicas. (Service: Lambda, Status Code: 400, Request ID: 0afe9035-cb74-4dd7-a516-07660f7e9f28, Extended Request ID: null)" (RequestToken: 436e305b-f5cc-02a7-14ad-fc9d198657b8, HandlerErrorCode: InvalidRequest)
```

So here I am stuck again with not being able to delete this Lambda@Edge after a few days.

This happening twice in 2 weeks. I think this is a good indication that there is an issue. While the CDK was used to deploy the stack, I assume this is where the issue may be but it could just as well be a CloudFormation issue. 

The issue seems to be when an error happens during deployment. I am 2 for 2 on this happening and the exact same issue happens where I cannot delete the stack until I can get support to do it for me. 

Both times, the issue was an existing Route53 record in another AWS account being the cause but I think this would happen for any issue during deployment (just a guess). 

Not sure if this is a CDK issue but wanted to report it with my experience to see if this helps with anything. Again, I also reported this to AWS support.

Thanks,
Jeremy

**Comment by peterwoodworth** [comment]
Thanks for submitting this issue, I'll try to investigate this and get back to ya

**Comment by jpSimkins** [comment]
To further update this, I again got the same error when trying to deploy. 

Support was able to delete the replicas for me but apparently I missed something.

This is what I get when I deploy and received the error:
```
9:38:12 AM | CREATE_FAILED        | AWS::CloudFront::Distribution | assetsCdnCloudFrontC6A5C3B1
Resource handler returned message: "Invalid request provided: One or more of the CNAMEs you provided are already associated with a different resource. (Service: CloudFront, Status Code: 409, Request ID: ae50ede7-cc53-4e15-9754-1ff1c6bce280, Extended Request ID: nul
l)" (RequestToken: ae9ec5e2-93ac-464a-23bd-87e5466db414, HandlerErrorCode: InvalidRequest)

        new Distribution (/home/jpsimkins/DevOps/oly-iac-mono-repo/aws/implementations/node_modules/@aws-cdk/aws-cloudfront/lib/distribution.ts:164:26)
        \_ CloudFrontWordPressCdn._buildCloudFrontDistribution (/home/jpsimkins/DevOps/oly-iac-mono-repo/aws/implementations/node_modules/@olympusat-devops/oly-cloudfront-templates/src/lib/CloudFrontWordPressCdn.ts:134:27)
        \_ new CloudFrontWordPressCdn (/home/jpsimkins/DevOps/oly-iac-mono-repo/aws/implementations/node_modules/@olympusat-devops/oly-cloudfront-templates/src/lib/CloudFrontWordPressCdn.ts:65:30)
        \_ new TokuhdComCdnProd (/home/jpsimkins/DevOps/oly-iac-mono-repo/aws/implementations/accounts/oly-marketing-prod/us-east-1/src/stacks/tokuhd.com/src/cdn-prod.ts:11:22)
        \_ Object.<anonymous> (/home/jpsimkins/DevOps/oly-iac-mono-repo/aws/implementations/accounts/oly-marketing-prod/us-east-1/src/stacks/tokuhd.com/index.ts:31:14)
        \_ Module._compile (internal/modules/cjs/loader.js:1068:30)
        \_ Module.m._compile (/home/jpsimkins/.npm/_npx/314291/lib/node_modules/ts-node/src/index.ts:1295:23)
        \_ Module._extensions..js (internal/modules/cjs/loader.js:1097:10)
        \_ Object.require.extensions.<computed> [as .ts] (/home/jpsimkins/.npm/_npx/314291/lib/node_modules/ts-node/src/index.ts:1298:12)
        \_ Module.load (internal/modules/cjs/loader.js:933:32)
        \_ Function.Module._load (internal/modules/cjs/loader.js:774:14)
        \_ Module.require (internal/modules/cjs/loader.js:957:19)
        \_ require (internal/modules/cjs/helpers.js:88:18)
        \_ Object.<anonymous> (/home/jpsimkins/DevOps/oly-iac-mono-repo/aws/implementations/accounts/oly-marketing-prod/us-east-1/src/index.ts:14:1)
        \_ Module._compile (internal/modules/cjs/loader.js:1068:30)
        \_ Module.m._compile (/home/jpsimkins/.npm/_npx/314291/lib/node_modules/ts-node/src/index.ts:1295:23)
        \_ Module._extensions..js (internal/modules/cjs/loader.js:1097:10)
        \_ Object.require.extensions.<computed> [as .ts] (/home/jpsimkins/.npm/_npx/314291/lib/node_modules/ts-node/src/index.ts:1298:12)
        \_ Module.load (internal/modules/cjs/loader.js:933:32)
        \_ Function.Module._load (internal/modules/cjs/loader.js:774:14)
        \_ Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)
        \_ main (/home/jpsimkins/.npm/_npx/314291/lib/node_modules/ts-node/src/bin.ts:246:14)
        \_ Object.<anonymous> (/home/jpsimkins/.npm/_npx/314291/lib/node_modules/ts-node/src/bin.ts:382:3)
        \_ Module._compile (internal/modules/cjs/loader.js:1068:30)
        \_ Object.Module._extensions..js (internal/modules/cjs/loader.js:1097:10)
        \_ Module.load (internal/modules/cjs/loader.js:933:32)
        \_ Function.Module._load (internal/modules/cjs/loader.js:774:14)
        \_ Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)
        \_ /home/jpsimkins/.nvm/versions/node/v14.17.0/lib/node_modules/npm/node_modules/libnpx/index.js:268:14

9:38:13 AM | ROLLBACK_IN_PROGRESS | AWS::CloudFormation::Stack    | TokuhdComCdnProd
The following resource(s) failed to create: [assetsCdnCloudFrontC6A5C3B1]. Rollback requested by user.

9:40:22 AM | DELETE_FAILED        | AWS::Lambda::Function         | assetsCdnedgeFunctionFn889F71D0
Resource handler returned message: "Lambda was unable to delete arn:aws:lambda:us-east-1:117781944281:function:TokuhdComCdnProd-assetsCdnedgeFunctionFn889F71D0-VVPIGDMQzgSV:1 because it is a replicated function. Please see our documentation for Deleting Lambda@Edge
Functions and Replicas. (Service: Lambda, Status Code: 400, Request ID: e37b621f-6cf5-49d5-a97c-5fa48cbf64e2, Extended Request ID: null)" (RequestToken: 5b975d96-31a2-3e9b-2ea1-a18e929af4b4, HandlerErrorCode: InvalidRequest)

        new Function (/home/jpsimkins/DevOps/oly-iac-mono-repo/aws/implementations/node_modules/@aws-cdk/aws-lambda/lib/function.ts:369:35)
        \_ EdgeFunction.createInRegionFunction (/home/jpsimkins/DevOps/oly-iac-mono-repo/aws/implementations/node_modules/@aws-cdk/aws-cloudfront/lib/experimental/edge-function.ts:119:26)
        \_ new EdgeFunction (/home/jpsimkins/DevOps/oly-iac-mono-repo/aws/implementations/node_modules/@aws-cdk/aws-cloudfront/lib/experimental/edge-function.ts:42:14)
        \_ CloudFrontWordPressCdn._buildLambdaFunction (/home/jpsimkins/DevOps/oly-iac-mono-repo/aws/implementations/node_modules/@olympusat-devops/oly-cloudfront-templates/src/lib/CloudFrontWordPressCdn.ts:116:27)
        \_ new CloudFrontWordPressCdn (/home/jpsimkins/DevOps/oly-iac-mono-repo/aws/implementations/node_modules/@olympusat-devops/oly-cloudfront-templates/src/lib/CloudFrontWordPressCdn.ts:64:32)
        \_ new TokuhdComCdnProd (/home/jpsimkins/DevOps/oly-iac-mono-repo/aws/implementations/accounts/oly-marketing-prod/us-east-1/src/stacks/tokuhd.com/src/cdn-prod.ts:11:22)
        \_ Object.<anonymous> (/home/jpsimkins/DevOps/oly-iac-mono-repo/aws/implementations/accounts/oly-marketing-prod/us-east-1/src/stacks/tokuhd.com/index.ts:31:14)
        \_ Module._compile (internal/modules/cjs/loader.js:1068:30)
```

I'm not sure why it states:
> One or more of the CNAMEs you provided are already associated with a different resource.

I deleted the legacy route53 record but I still got the same error... I am looking into this issue. 

For now, I will have to wait 24 hours but I can guarantee this will need to be requested VIA support again.

From this message, it seems that the CloudFront distro fails to deploy but the replicas are for some reason. This may be the reason it's in limbo and has to be manually deleted by support.

**Comment by peterwoodworth** [comment]
Thanks for the updates, so is this not a CDK based issue then?

**Comment by jpSimkins** [comment]
I'm not sure if it's a CDK based issue. 

It's due to the deletion of the failed resource (CloudFront Distro) during deployment but the Lambda@Edge still get deployed. So this could just be a CloudFormation issue. Unless the CDK has a way it's handling deletions on failures that I am not aware of. I reported this to support so hopefully this can help in the future.

**Comment by peterwoodworth** [comment]
Yeah this doesn't sound like a CDK issue. I'll close this for now, but feel free to ping me if you find that it's a CDK issue
