### ISSUE TITLE
(aws-lambda-python): AWS CodeBuild fails on npx cdk synth cannot find asset

### ISSUE THREAD

**Issue by ColeSiegelTR** [aws/aws-cdk#15335]
## :question: General Issue

Upon running `npx cdk synth` in AWS CodeBuild the asset staging is failing the build, see error log below:

```
243 | /codebuild/output/src859363663/src/iac/cdk/node_modules/@aws-cdk/core/lib/asset-staging.ts:113
244 | throw new Error(`Cannot find asset at ${this.sourcePath}`);
246 | Error: Cannot find asset at /codebuild/output/src553012570/src/iac/cdk/functions/initialize-roles
```

```
[Container] 2021/06/28 22:47:56 Entering phase BUILD
--
44 | [Container] 2021/06/28 22:47:56 Running command npx cdk synth
45 | Sending build context to Docker daemon  3.584kB
46 |  
47 | Step 1/9 : ARG IMAGE=public.ecr.aws/sam/build-python3.7
48 | Step 2/9 : FROM $IMAGE
49 | latest: Pulling from sam/build-python3.8
50 | eaeac1c363a0: Pulling fs layer
51 | d95b35ecc820: Pulling fs layer
52 | 56fa792ca1c4: Pulling fs layer
53 | 2a3e3019d6f8: Pulling fs layer
54 | ef44fa12b061: Pulling fs layer
55 | d70042c7753e: Pulling fs layer
56 | b843ad0a0422: Pulling fs layer
57 | 94a16f371021: Pulling fs layer
58 | 265182715ec0: Pulling fs layer
59 | d70042c7753e: Waiting
60 | b843ad0a0422: Waiting
61 | 94a16f371021: Waiting
62 | 2a3e3019d6f8: Waiting
63 | ef44fa12b061: Waiting
64 | 265182715ec0: Waiting
65 | d95b35ecc820: Verifying Checksum
66 | d95b35ecc820: Download complete
67 | 2a3e3019d6f8: Verifying Checksum
68 | 2a3e3019d6f8: Download complete
69 | 56fa792ca1c4: Verifying Checksum
70 | 56fa792ca1c4: Download complete
71 | eaeac1c363a0: Verifying Checksum
72 | eaeac1c363a0: Download complete
73 | b843ad0a0422: Verifying Checksum
74 | b843ad0a0422: Download complete
75 | d70042c7753e: Verifying Checksum
76 | d70042c7753e: Download complete
77 | 94a16f371021: Verifying Checksum
78 | 94a16f371021: Download complete
79 | 265182715ec0: Verifying Checksum
80 | 265182715ec0: Download complete
81 | ef44fa12b061: Verifying Checksum
82 | ef44fa12b061: Download complete
83 | eaeac1c363a0: Pull complete
84 | d95b35ecc820: Pull complete
85 | 56fa792ca1c4: Pull complete
86 | 2a3e3019d6f8: Pull complete
87 | ef44fa12b061: Pull complete
88 | d70042c7753e: Pull complete
89 | b843ad0a0422: Pull complete
90 | 94a16f371021: Pull complete
91 | 265182715ec0: Pull complete
92 | Digest: sha256:59b51b0e28d171e31b67fe7faeba8fee338383490c500d3150375e496fd525a3
93 | Status: Downloaded newer image for public.ecr.aws/sam/build-python3.8:latest
94 | ---> d8bd18424538
95 | Step 3/9 : RUN yum -q list installed rsync &>/dev/null \|\| yum install -y rsync
96 | ---> Running in 4831c9512ba1
97 | Removing intermediate container 4831c9512ba1
98 | ---> dab1c35202b7
99 | Step 4/9 : RUN pip install --upgrade pip
100 | ---> Running in c979434cbbd4
101 | Requirement already satisfied: pip in /var/lang/lib/python3.8/site-packages (21.1.1)
102 | Collecting pip
103 | Downloading pip-21.1.3-py3-none-any.whl (1.5 MB)
104 | Installing collected packages: pip
105 | Attempting uninstall: pip
106 | Found existing installation: pip 21.1.1
107 | Uninstalling pip-21.1.1:
108 | Successfully uninstalled pip-21.1.1
109 | Successfully installed pip-21.1.3
110 | WARNING: Running pip as root will break packages and permissions. You should install packages reliably by using venv: https://pip.pypa.io/warnings/venv
111 | Removing intermediate container c979434cbbd4
112 | ---> 93ed3020f5d3
113 | Step 5/9 : RUN pip install pipenv poetry
114 | ---> Running in 86669cb5827e
115 | Collecting pipenv
116 | Downloading pipenv-2021.5.29-py2.py3-none-any.whl (3.9 MB)
117 | Collecting poetry
118 | Downloading poetry-1.1.7-py2.py3-none-any.whl (173 kB)
119 | Collecting virtualenv-clone>=0.2.5
120 | Downloading virtualenv_clone-0.5.4-py2.py3-none-any.whl (6.6 kB)
121 | Requirement already satisfied: pip>=18.0 in /var/lang/lib/python3.8/site-packages (from pipenv) (21.1.3)
122 | Requirement already satisfied: setuptools>=36.2.1 in /var/lang/lib/python3.8/site-packages (from pipenv) (56.0.0)
123 | Collecting virtualenv
124 | Downloading virtualenv-20.4.7-py2.py3-none-any.whl (7.2 MB)
125 | Collecting certifi
126 | Downloading certifi-2021.5.30-py2.py3-none-any.whl (145 kB)
127 | Collecting pkginfo<2.0,>=1.4
128 | Downloading pkginfo-1.7.0-py2.py3-none-any.whl (25 kB)
129 | Collecting keyring<22.0.0,>=21.2.0
130 | Downloading keyring-21.8.0-py3-none-any.whl (32 kB)
131 | Collecting cachy<0.4.0,>=0.3.0
132 | Downloading cachy-0.3.0-py2.py3-none-any.whl (20 kB)
133 | Collecting pexpect<5.0.0,>=4.7.0
134 | Downloading pexpect-4.8.0-py2.py3-none-any.whl (59 kB)
135 | Collecting poetry-core<1.1.0,>=1.0.3
136 | Downloading poetry_core-1.0.3-py2.py3-none-any.whl (424 kB)
137 | Collecting clikit<0.7.0,>=0.6.2
138 | Downloading clikit-0.6.2-py2.py3-none-any.whl (91 kB)
139 | Collecting crashtest<0.4.0,>=0.3.0
140 | Downloading crashtest-0.3.1-py3-none-any.whl (7.0 kB)
141 | Collecting packaging<21.0,>=20.4
142 | Downloading packaging-20.9-py2.py3-none-any.whl (40 kB)
143 | Collecting cleo<0.9.0,>=0.8.1
144 | Downloading cleo-0.8.1-py2.py3-none-any.whl (21 kB)
145 | Collecting tomlkit<1.0.0,>=0.7.0
146 | Downloading tomlkit-0.7.2-py2.py3-none-any.whl (32 kB)
147 | Collecting requests<3.0,>=2.18
148 | Downloading requests-2.25.1-py2.py3-none-any.whl (61 kB)
149 | Collecting cachecontrol[filecache]<0.13.0,>=0.12.4
150 | Downloading CacheControl-0.12.6-py2.py3-none-any.whl (19 kB)
151 | Collecting html5lib<2.0,>=1.0
152 | Downloading html5lib-1.1-py2.py3-none-any.whl (112 kB)
153 | Collecting shellingham<2.0,>=1.1
154 | Downloading shellingham-1.4.0-py2.py3-none-any.whl (9.4 kB)
155 | Collecting requests-toolbelt<0.10.0,>=0.9.1
156 | Downloading requests_toolbelt-0.9.1-py2.py3-none-any.whl (54 kB)
157 | Collecting msgpack>=0.5.2
158 | Downloading msgpack-1.0.2-cp38-cp38-manylinux1_x86_64.whl (302 kB)
159 | Collecting lockfile>=0.9
160 | Downloading lockfile-0.12.2-py2.py3-none-any.whl (13 kB)
161 | Collecting pylev<2.0,>=1.3
162 | Downloading pylev-1.4.0-py2.py3-none-any.whl (6.1 kB)
163 | Collecting pastel<0.3.0,>=0.2.0
164 | Downloading pastel-0.2.1-py2.py3-none-any.whl (6.0 kB)
165 | Collecting webencodings
166 | Downloading webencodings-0.5.1-py2.py3-none-any.whl (11 kB)
167 | Collecting six>=1.9
168 | Downloading six-1.16.0-py2.py3-none-any.whl (11 kB)
169 | Collecting SecretStorage>=3.2
170 | Downloading SecretStorage-3.3.1-py3-none-any.whl (15 kB)
171 | Collecting jeepney>=0.4.2
172 | Downloading jeepney-0.6.0-py3-none-any.whl (45 kB)
173 | Collecting pyparsing>=2.0.2
174 | Downloading pyparsing-2.4.7-py2.py3-none-any.whl (67 kB)
175 | Collecting ptyprocess>=0.5
176 | Downloading ptyprocess-0.7.0-py2.py3-none-any.whl (13 kB)
177 | Collecting chardet<5,>=3.0.2
178 | Downloading chardet-4.0.0-py2.py3-none-any.whl (178 kB)
179 | Collecting idna<3,>=2.5
180 | Downloading idna-2.10-py2.py3-none-any.whl (58 kB)
181 | Collecting urllib3<1.27,>=1.21.1
182 | Downloading urllib3-1.26.6-py2.py3-none-any.whl (138 kB)
183 | Collecting cryptography>=2.0
184 | Downloading cryptography-3.4.7-cp36-abi3-manylinux2014_x86_64.whl (3.2 MB)
185 | Collecting cffi>=1.12
186 | Downloading cffi-1.14.5-cp38-cp38-manylinux1_x86_64.whl (411 kB)
187 | Collecting pycparser
188 | Downloading pycparser-2.20-py2.py3-none-any.whl (112 kB)
189 | Collecting distlib<1,>=0.3.1
190 | Downloading distlib-0.3.2-py2.py3-none-any.whl (338 kB)
191 | Collecting appdirs<2,>=1.4.3
192 | Downloading appdirs-1.4.4-py2.py3-none-any.whl (9.6 kB)
193 | Collecting filelock<4,>=3.0.0
194 | Downloading filelock-3.0.12-py3-none-any.whl (7.6 kB)
195 | Installing collected packages: pycparser, urllib3, idna, chardet, cffi, certifi, requests, pylev, pastel, msgpack, jeepney, cryptography, crashtest, webencodings, six, SecretStorage, pyparsing, ptyprocess, lockfile, filelock, distlib, clikit, cachecontrol, appdirs, virtualenv-clone, virtualenv, tomlkit, shellingham, requests-toolbelt, poetry-core, pkginfo, pexpect, packaging, keyring, html5lib, cleo, cachy, poetry, pipenv
196 | Successfully installed SecretStorage-3.3.1 appdirs-1.4.4 cachecontrol-0.12.6 cachy-0.3.0 certifi-2021.5.30 cffi-1.14.5 chardet-4.0.0 cleo-0.8.1 clikit-0.6.2 crashtest-0.3.1 cryptography-3.4.7 distlib-0.3.2 filelock-3.0.12 html5lib-1.1 idna-2.10 jeepney-0.6.0 keyring-21.8.0 lockfile-0.12.2 msgpack-1.0.2 packaging-20.9 pastel-0.2.1 pexpect-4.8.0 pipenv-2021.5.29 pkginfo-1.7.0 poetry-1.1.7 poetry-core-1.0.3 ptyprocess-0.7.0 pycparser-2.20 pylev-1.4.0 pyparsing-2.4.7 requests-2.25.1 requests-toolbelt-0.9.1 shellingham-1.4.0 six-1.16.0 tomlkit-0.7.2 urllib3-1.26.6 virtualenv-20.4.7 virtualenv-clone-0.5.4 webencodings-0.5.1
197 | WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
198 | Removing intermediate container 86669cb5827e
199 | ---> e0ce10f2289e
200 | Step 6/9 : WORKDIR /var/dependencies
201 | ---> Running in 9106df7e70f8
202 | Removing intermediate container 9106df7e70f8
203 | ---> c965ca623c26
204 | Step 7/9 : COPY Pipfile* pyproject* poetry* requirements.tx[t] ./
205 | ---> bda7b7c2e37f
206 | Step 8/9 : RUN [ -f 'Pipfile' ] && pipenv lock -r >requirements.txt;     [ -f 'poetry.lock' ] && poetry export --with-credentials --format requirements.txt --output requirements.txt;     [ -f 'requirements.txt' ] && pip install -r requirements.txt -t .;
207 | ---> Running in 2b2c1f588fa9
208 | Collecting requests
209 | Using cached requests-2.25.1-py2.py3-none-any.whl (61 kB)
210 | Collecting boto3
211 | Downloading boto3-1.17.102-py2.py3-none-any.whl (131 kB)
212 | Collecting certifi>=2017.4.17
213 | Using cached certifi-2021.5.30-py2.py3-none-any.whl (145 kB)
214 | Collecting chardet<5,>=3.0.2
215 | Using cached chardet-4.0.0-py2.py3-none-any.whl (178 kB)
216 | Collecting urllib3<1.27,>=1.21.1
217 | Using cached urllib3-1.26.6-py2.py3-none-any.whl (138 kB)
218 | Collecting idna<3,>=2.5
219 | Using cached idna-2.10-py2.py3-none-any.whl (58 kB)
220 | Collecting botocore<1.21.0,>=1.20.102
221 | Downloading botocore-1.20.102-py2.py3-none-any.whl (7.7 MB)
222 | Collecting s3transfer<0.5.0,>=0.4.0
223 | Downloading s3transfer-0.4.2-py2.py3-none-any.whl (79 kB)
224 | Collecting jmespath<1.0.0,>=0.7.1
225 | Downloading jmespath-0.10.0-py2.py3-none-any.whl (24 kB)
226 | Collecting python-dateutil<3.0.0,>=2.1
227 | Downloading python_dateutil-2.8.1-py2.py3-none-any.whl (227 kB)
228 | Collecting six>=1.5
229 | Using cached six-1.16.0-py2.py3-none-any.whl (11 kB)
230 | Installing collected packages: six, urllib3, python-dateutil, jmespath, botocore, s3transfer, idna, chardet, certifi, requests, boto3
231 | Successfully installed boto3-1.17.102 botocore-1.20.102 certifi-2021.5.30 chardet-4.0.0 idna-2.10 jmespath-0.10.0 python-dateutil-2.8.1 requests-2.25.1 s3transfer-0.4.2 six-1.16.0 urllib3-1.26.6
232 | WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
233 | Removing intermediate container 2b2c1f588fa9
234 | ---> b162cd8c2a44
235 | Step 9/9 : CMD [ "python" ]
236 | ---> Running in 62804394789e
237 | Removing intermediate container 62804394789e
238 | ---> 637e1798a496
239 | Successfully built 637e1798a496
240 | Successfully tagged cdk-f269639506aa52dba43a0cf22f5080d7db4c671d0612d826766762906495ae14:latest
241 | Bundling asset pipeline-stack/DEV-stage/es-stack/cognito_post_confirmation/Code/Stage...
242 |  
243 | /codebuild/output/src859363663/src/iac/cdk/node_modules/@aws-cdk/core/lib/asset-staging.ts:113
244 | throw new Error(`Cannot find asset at ${this.sourcePath}`);
245 | ^
246 | Error: Cannot find asset at /codebuild/output/src859363663/src/iac/cdk/functions/initialize-roles
247 | at new AssetStaging (/codebuild/output/src859363663/src/iac/cdk/node_modules/@aws-cdk/core/lib/asset-staging.ts:113:13)
248 | at new Asset (/codebuild/output/src859363663/src/iac/cdk/node_modules/@aws-cdk/aws-s3-assets/lib/asset.ts:127:21)
249 | at AssetCode.bind (/codebuild/output/src859363663/src/iac/cdk/node_modules/@aws-cdk/aws-lambda/lib/code.ts:277:20)
250 | at new Function (/codebuild/output/src859363663/src/iac/cdk/node_modules/@aws-cdk/aws-lambda/lib/function.ts:600:29)
251 | at ElasticsearchStack.configureKibanaAccess (/codebuild/output/src859363663/src/iac/cdk/lib/elasticsearch.ts:392:43)
252 | at new ElasticsearchStack (/codebuild/output/src859363663/src/iac/cdk/lib/elasticsearch.ts:63:14)
253 | at new PipelineStage (/codebuild/output/src859363663/src/iac/cdk/lib/pipeline/pipeline-stage.ts:15:27)
254 | at /codebuild/output/src859363663/src/iac/cdk/lib/pipeline/pipeline-stack.ts:74:25
255 | at Array.forEach (<anonymous>)
256 | at new PipelineStack (/codebuild/output/src859363663/src/iac/cdk/lib/pipeline/pipeline-stack.ts:73:22)
257 | Subprocess exited with error 1
258 |  
259 | [Container] 2021/06/28 22:49:05 Command did not exit successfully npx cdk synth exit status 1
260 | [Container] 2021/06/28 22:49:05 Phase complete: BUILD State: FAILED
261 | [Container] 2021/06/28 22:49:05 Phase context status code: COMMAND_EXECUTION_ERROR Message: Error while executing command: npx cdk synth. Reason: exit status 1
```

### Environment

  - **CDK CLI Version:** 1.110 
  - **Module Version:** 1.110
  - **Build Agent Image:** https://github.com/aws/aws-codebuild-docker-images/blob/master/ubuntu/standard/5.0/Dockerfile

### Other information

Just looking for information on how to troubleshoot this error. I have a CodePipeline deployed through `aws-cdk` and it is failing to build my lambda assets. I think it might be related to the `aws-lambda-python` library but I am not sure. Thank you in advance for any help.

**Comment by skinny85** [comment]
Hey @ColeSiegelTR ,

thanks for opening the issue. Can you share your setup? How are your sources organized in the Pipeline, what are the exact commands running in CodeBuild?

Thanks,
Adam

**Comment by ColeSiegelTR** [comment]
Hi @skinny85 

My repository has a subdirectory iac/cdk which contains the `PipelineStack`. Inside the pipeline stack is an app stage to create my Elasticsearch resources, which includes PythonFunction. The python code is organized in `iac/cdk/functions` directory.

```
entry: path.join(__dirname, '..', 'functions/cognito-post-confirm'),
index: 'cognito-post-confirm.py',
```

The CodeBuild command is `npx cdk synth` which runs OK for me locally.

I'm not sure what other info I should provide or how to go about troubleshooting this - any suggestions? It's not clear to me if there is some issue with the PythonFunction packaging or something else, but if I remove the lambdas then it works OK.

**Comment by ColeSiegelTR** [comment]
My apologies @skinny85 it turned out to be a very foolish issue, the lambda file was on my `gitignore` and so it wasn't found in the source repository.
