### ISSUE TITLE
(@aws-cdk/core): Context variable on deploy returns None

### ISSUE THREAD

**Issue by lindakung** [aws/aws-cdk#15385]
### The Question

We are trying to deploy our CDK app in Ubuntu18.04 with Github Actions. The workflow first runs a `cdk synth` job so our devs can see the template and then a `cdk deploy`.

This is our `app.py`

```
#!/usr/bin/env python
from aws_cdk import core

from test_stack import TestStack

app = core.App()

env_string = app.node.try_get_context("env")

stack_name = f"{env_string}-{name}"
TestStack(app, stack_name, env_string=env_string, env=aws)

app.synth()
```

Our Stack `stack.py`

```
from aws_cdk import aws_lambda as _lambda
from aws_cdk.core import Construct, Stack

from deploy.utils.bundle import bundle


class TestStack(Stack):
    @property
    def region(self):
        return self.node.try_get_context("aws_env")["region"]

    @property
    def account_id(self):
        return self.node.try_get_context("aws_env")["account_id"]

    def __init__(
        self,
        scope: Construct,
        id: str,
        env_string: str,
        **kwargs,
    ) -> None:  # noqa
        super().__init__(scope, id, **kwargs)

        dependencies = _lambda.LayerVersion(  # noqa
            self,
            "Layer",
            code=bundle("./code", self.region),
            compatible_runtimes=[_lambda.Runtime.PYTHON_3_8],
        )

        sample_function = _lambda.Function( 
            self,
            Sample",
            handler="handlers.sample_dependencies.lambda_handler",
            runtime=_lambda.Runtime.PYTHON_3_8,
            code=_lambda.Code.from_asset("./code"),
            layers=[dependencies],
            environment={"env": env_string},  ----> env_string returns None at deploy time which errors out deploy
        )
```

We run both our `synth` and `deploy`  commands with the context passed in. For example:
```
cdk deploy test-stack -c env=stage
```

Our `synth` script works fine and we don't run into this issue. 

As you can see, we pass in the context variable `env` from `app.py` to `stack.py` as an argument. When our Github Actions job runs the `deploy`, `env_string` actually returns `None` and errors out the deploy. 

This error also happens when we do not pass in the `env_string` to `stack.py`. I have tried:
```
        env = self.node.try_get_context("env")
        sample_function = _lambda.Function( 
            self,
            Sample",
            handler="handlers.sample_dependencies.lambda_handler",
            runtime=_lambda.Runtime.PYTHON_3_8,
            code=_lambda.Code.from_asset("./code"),
            layers=[dependencies],
            environment={"env": env},  ----> returns None and errors
        )
```

However I tried a workaround and converted the `env_string` with `str(env_string)`:

```
        sample_function = _lambda.Function( 
            self,
            Sample",
            handler="handlers.sample_dependencies.lambda_handler",
            runtime=_lambda.Runtime.PYTHON_3_8,
            code=_lambda.Code.from_asset("./code"),
            layers=[dependencies],
            environment={"env": str(env_string)},  ----> This works!
        )
```
 Wrapping the `env_string` with the `str()` function works for the deploy!

This is an issue we have never seen before as we have usually deployed our cdk app via our local command line and the context has never returned None. This is the first time we are adding this to Github Actions with our own Ubuntu runner. 

The Context documentation doesn't explain why this happens on the `deploy` script. Is there an explanation for this? And is there a way we don't have to wrap `str()` around the variable?

Thanks!

### Environment

  - **CDK CLI Version:** 1.110.1
  - **Module Version:** 1.100.0
  - **Node.js Version:** Node 14.17.1
  - **OS:** Ubuntu18.04
  - **Language (Version):** Python

**Comment by peterwoodworth** [comment]
Hmmm, I can't seem to reproduce this. The only thing in your code that you posted that sticks out to me is the `env=aws` part in `app.py`, but I assume you've just edited out some information you don't want to post here. 

Regardless, I don't have to wrap the variable with the `str()` for it to get the context, and I set it up the same way as you did here. Sorry I can't help you more right now @lindakung

**Comment by lindakung** [comment]
This is the error I'd get without the `str()` in the runner:

```
 jsii.errors.JavaScriptError: 
  Error: Got 'undefined' for non-optional instance of {"type":{"primitive":"string"}}
      at nullAndOk (/tmp/tmpsr2ro9t7/lib/program.js:9318:23)
      at Object.deserialize (/tmp/tmpsr2ro9t7/lib/program.js:8859:25)
      at Kernel._toSandbox (/tmp/tmpsr2ro9t7/lib/program.js:8505:69)
      at /tmp/tmpsr2ro9t7/lib/program.js:9007:81
      at mapValues (/tmp/tmpsr2ro9t7/lib/program.js:9341:35)
      at Object.deserialize (/tmp/tmpsr2ro9t7/lib/program.js:9007:36)
      at Kernel._toSandbox (/tmp/tmpsr2ro9t7/lib/program.js:8505:69)
      at /tmp/tmpsr2ro9t7/lib/program.js:9070:37
      at mapValues (/tmp/tmpsr2ro9t7/lib/program.js:9341:35)
      at Object.deserialize (/tmp/tmpsr2ro9t7/lib/program.js:9066:28)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "deploy/app.py", line 21, in <module>
    TestStack(app, stack_name, env_string=env_string, env=aws)
  File "/home/ubuntu/actions-runner/_work/sample/sample/.venv/lib/python3.8/site-packages/jsii/_runtime.py", line 83, in __call__
    inst = super().__call__(*args, **kwargs)
  File "/home/ubuntu/actions-runner/_work/sample/sample/deploy/jetty_lambdas_template.py", line 43, in __init__
    sample_function = _lambda.Function(  # noqa
  File "/home/ubuntu/actions-runner/_work/sample/sample/.venv/lib/python3.8/site-packages/jsii/_runtime.py", line 83, in __call__
    inst = super().__call__(*args, **kwargs)
  File "/home/ubuntu/actions-runner/_work/sample/sample/.venv/lib/python3.8/site-packages/aws_cdk/aws_lambda/__init__.py", line 15156, in __init__
    jsii.create(Function, self, [scope, id, props])
  File "/home/ubuntu/actions-runner/_work/sample/sample/.venv/lib/python3.8/site-packages/jsii/_kernel/__init__.py", line 275, in create
    response = self.provider.create(
  File "/home/ubuntu/actions-runner/_work/sample/sample/.venv/lib/python3.8/site-packages/jsii/_kernel/providers/process.py", line 344, in create
    return self._process.send(request, CreateResponse)
  File "/home/ubuntu/actions-runner/_work/sample/sample/.venv/lib/python3.8/site-packages/jsii/_kernel/providers/process.py", line 326, in send
    raise JSIIError(resp.error) from JavaScriptError(resp.stack)
jsii.errors.JSIIError: Got 'undefined' for non-optional instance of {"type":{"primitive":"string"}}
```

@peterwoodworth Thank you for the response. The `env=aws` is our AWS account data not the `env_string` that we pass in from the context. It is strange. I cannot reproduce this when I deploy via my CLI. Only happens in my Github runner.

**Comment by peterwoodworth** [comment]
Hm, interesting that it only works in your github runner. Sounds like you got everything figured out though, you have any more questions?

**Comment by peterwoodworth** [comment]
Closing this issue, ping me if you need additional help with this1
