### ISSUE TITLE
(aws-cdk.cloudformation-include): Does not take parameters 

### ISSUE THREAD

**Issue by asifiqbal** [aws/aws-cdk#15411]
### The Question

How to use parameters with **cloudformation_include.CfnInclude**? 
### Environment

  - **CDK CLI Version:** 1.111.0 (build 556ca93)
  - **Module Version:** 1.111.0
  - **Node.js Version:** v16.4.1
  - **OS:** macOS Big Sur
  - **Language (Version):** Python (3.9.5)

### Other information

I tried to follow https://pypi.org/project/aws-cdk.cloudformation-include/ and used it like this
```
from aws_cdk import cloudformation_include as cfn_inc
template = cfn_inc.CfnInclude(self, "Template",  
                template_file="quickstart-jira-dc-with-vpc.template.yaml",
                parameters={
                   "AvailabilityZones": "us-east-1a,us-east-1b" 
                }
          )
```
And it fails with this error
```
cdkworkshop failed: Error [ValidationError]: Template error: every Fn::Join object requires two parameters, (1) a string delimiter and (2) a list of strings to be joined or a function that returns a list of strings (such as Fn::GetAZs) to be joined.
    at Request.extractError (/usr/local/lib/node_modules/aws-cdk/node_modules/aws-sdk/lib/protocol/query.js:50:29)
    at Request.callListeners (/usr/local/lib/node_modules/aws-cdk/node_modules/aws-sdk/lib/sequential_executor.js:106:20)
    at Request.emit (/usr/local/lib/node_modules/aws-cdk/node_modules/aws-sdk/lib/sequential_executor.js:78:10)
    at Request.emit (/usr/local/lib/node_modules/aws-cdk/node_modules/aws-sdk/lib/request.js:688:14)
    at Request.transition (/usr/local/lib/node_modules/aws-cdk/node_modules/aws-sdk/lib/request.js:22:10)
    at AcceptorStateMachine.runTo (/usr/local/lib/node_modules/aws-cdk/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at /usr/local/lib/node_modules/aws-cdk/node_modules/aws-sdk/lib/state_machine.js:26:10
    at Request.<anonymous> (/usr/local/lib/node_modules/aws-cdk/node_modules/aws-sdk/lib/request.js:38:9)
    at Request.<anonymous> (/usr/local/lib/node_modules/aws-cdk/node_modules/aws-sdk/lib/request.js:690:12)
    at Request.callListeners (/usr/local/lib/node_modules/aws-cdk/node_modules/aws-sdk/lib/sequential_executor.js:116:18) {
  code: 'ValidationError',
  time: 2021-07-03T19:04:11.866Z,
  requestId: '1b418388-ce24-40c7-8f76-085b93da913b',
  statusCode: 400,
  retryable: false,
  retryDelay: 39.0750065319847
}
Template error: every Fn::Join object requires two parameters, (1) a string delimiter and (2) a list of strings to be joined or a function that returns a list of strings (such as Fn::GetAZs) to be joined.
```
If I update the parameters separately like below, it works fine and I can deploy the stack without any error.

```
azs = template.get_parameter("AvailabilityZones")
azs.default = 'us-east-1a,us-east-1b'
```

**Comment by asifiqbal** [comment]
Did not read the error message carefully. Needed to feed a list to AZs
`"AvailabilityZones": ["us-east-1a","us-east-1b"]`

**Comment by asifiqbal** [comment]
Did not read the error message carefully. Needed to feed a list to AZs
"AvailabilityZones": ["us-east-1a","us-east-1b"]
