### ISSUE TITLE
(aws-ec2): connections.allowTo() and connections.allowFrom() doesn't accept IConnectable implementations

### ISSUE THREAD

**Issue by Repox** [aws/aws-cdk#15474]
It seems like EC2 Security Group connection doesn't accept connections that implement the IConnectable objects.

According to [the documentation](https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-ec2.Connections.html) the `connections` object property implements IConnectable, the `allowTo()` and `allowFrom()` methods doesn't accept them as input.

### Reproduction Steps

```typescript
const rdsPrimaryDatabase = rds.DatabaseInstance.fromDatabaseInstanceAttributes(this, 'ApplicationReadWrite', {
  instanceEndpointAddress: "application_database_ewqqqrqw.eu-west-1.rds.amazonaws.com", port: 3305, securityGroups: [],
  instanceIdentifier: 'application_database'
});
const securityGroup = new ec2.SecurityGroup(this, 'ApplicationEcsSecurityGroup', {
  vpc: vpc,
  allowAllOutbound: true,
  securityGroupName: 'ApplicationEcsSecurityGroup',
})
securityGroup.connections.allowTo(rdsPrimaryDatabase.connections, 3306, 'Primary Database')
```

### What did you expect to happen?

I am hoping to allow my ECS service containers to connect with my database instance in RDS by connecting my newly created security group to the RDS instance.

### What actually happened?

When trying to connect a security group to a RDS instance (or the other way around), I'm presented with the following error:

```
danstorm:wp2-cdk/ (master✗) $ cdk synth dev 

/Users/danstorm/Documents/joe/wp2-cdk/node_modules/ts-node/src/index.ts:513
    return new TSError(diagnosticText, diagnosticCodes)
           ^
TSError: ⨯ Unable to compile TypeScript:
lib/wp2-cdk-stack.ts:51:39 - error TS2345: Argument of type 'Connections' is not assignable to parameter of type 'IConnectable'.
  The types of 'connections.defaultPort' are incompatible between these types.
    Type 'import("/Users/danstorm/Documents/joe/wp2-cdk/node_modules/@aws-cdk/aws-rds/node_modules/@aws-cdk/aws-ec2/lib/port").Port | undefined' is not assignable to type 'import("/Users/danstorm/Documents/joe/wp2-cdk/node_modules/@aws-cdk/aws-ec2/lib/port").Port | undefined'.
      Type 'import("/Users/danstorm/Documents/joe/wp2-cdk/node_modules/@aws-cdk/aws-rds/node_modules/@aws-cdk/aws-ec2/lib/port").Port' is not assignable to type 'import("/Users/danstorm/Documents/joe/wp2-cdk/node_modules/@aws-cdk/aws-ec2/lib/port").Port'.
        Types have separate declarations of a private property 'props'.

51     securityGroup.connections.allowTo(rdsPrimaryDatabase.connections, 3306, 'Primary Database');
                                         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

    at createTSError (/Users/danstorm/Documents/joe/wp2-cdk/node_modules/ts-node/src/index.ts:513:12)
    at reportTSError (/Users/danstorm/Documents/joe/wp2-cdk/node_modules/ts-node/src/index.ts:517:19)
    at getOutput (/Users/danstorm/Documents/joe/wp2-cdk/node_modules/ts-node/src/index.ts:752:36)
    at Object.compile (/Users/danstorm/Documents/joe/wp2-cdk/node_modules/ts-node/src/index.ts:968:32)
    at Module.m._compile (/Users/danstorm/Documents/joe/wp2-cdk/node_modules/ts-node/src/index.ts:1056:42)
    at Module._extensions..js (node:internal/modules/cjs/loader:1124:10)
    at Object.require.extensions.<computed> [as .ts] (/Users/danstorm/Documents/joe/wp2-cdk/node_modules/ts-node/src/index.ts:1059:12)
    at Module.load (node:internal/modules/cjs/loader:975:32)
    at Function.Module._load (node:internal/modules/cjs/loader:816:12)
    at Module.require (node:internal/modules/cjs/loader:999:19)
```

### Environment

  - **CDK CLI Version  :** 1.111.0 (build 556ca93)
  - **Framework Version:** 1.110.1
  - **Node.js Version:**  v16.4.0
  - **OS  :** MacOS
  - **Language (Version):**  Typescript 4.2.3

### Other

--- 

This is :bug: Bug Report

**Comment by madeline-k** [comment]
@Repox What you are looking for is supported. 

You should be able to pass in either `rdsPrimaryDatabase` or `rdsPrimaryDatabse.connections` as the first parameter of `allowTo`. 

The TS error you are getting looks to be a mismatch between the node_modules for aws-ec2 and aws-rds. I'd recommending cleaning your node modules and reinstalling them.

**Comment by peterwoodworth** [comment]
Make sure all your CDK versions are the same in `package.json` if you still are running into this error. Ping me if you need any more help with this 😄
