### ISSUE TITLE
s3_deployment      Can't deploy Bucket.

### ISSUE THREAD

**Issue by mrpackethead** [aws/aws-cdk#15530]
This code segment is causing an error at synth time..

```
component_bucket = s3.Bucket(self, 'componentbucket',
            bucket_name= parameters['project']['ProjectGlobals']['ComponentBucketName']
        )
        component_bucket.grant_read(image_builder_role)
        
        # this is 
        s3_deployment.BucketDeployment(self, 'ComponentsBucketDeployment',
            destination_bucket= component_bucket,
            sources = [s3_deployment.Source.asset('./components')]
        )
```
THis is error that i  i get at synth

```
jsii.errors.JavaScriptError: 
  TypeError: core_1.attachCustomSynthesis is not a function
      at new PublishAssetsAction (/tmp/jsii-kernel-uIbS9W/node_modules/@aws-cdk/pipelines/lib/actions/publish-assets-action.js:81:16)
      at AssetPublishing.addPublishAssetAction (/tmp/jsii-kernel-uIbS9W/node_modules/@aws-cdk/pipelines/lib/pipeline.js:329:54)
      at CdkStage.publishAssetDependencies (/tmp/jsii-kernel-uIbS9W/node_modules/@aws-cdk/pipelines/lib/stage.js:228:27)
      at CdkStage.addStackArtifactDeployment (/tmp/jsii-kernel-uIbS9W/node_modules/@aws-cdk/pipelines/lib/stage.js:85:14)
      at CdkStage.addApplication (/tmp/jsii-kernel-uIbS9W/node_modules/@aws-cdk/pipelines/lib/stage.js:73:22)
      at CdkPipeline.addApplicationStage (/tmp/jsii-kernel-uIbS9W/node_modules/@aws-cdk/pipelines/lib/pipeline.js:150:15)
      at /tmp/tmpcj0663jw/lib/program.js:7970:134
      at Kernel._wrapSandboxCode (/tmp/tmpcj0663jw/lib/program.js:8582:24)
      at /tmp/tmpcj0663jw/lib/program.js:7970:107
      at Kernel._ensureSync (/tmp/tmpcj0663jw/lib/program.js:8563:28)
```

My best guess is that is missing some option from cdk.json but i'm not at all sure.

**Comment by mrpackethead** [comment]
Feeling a little silly. This was my problem. dependanies.
