### ISSUE TITLE
(@aws-cdk/aws-codestarnotifications): CodeCommit repository not supported as source for Notification Rule

### ISSUE THREAD

**Issue by badfun** [aws/aws-cdk#15653]
Currently @aws-cdk/aws-codestarnotifications module does not seem to support using repository as the source. However, this does appear to be supported in Cloudformation.
From the CDK api docs:
["Currently, Supported sources include pipelines in AWS CodePipeline and build projects in AWS CodeBuild in this L2 constructor."](https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-codestarnotifications.NotificationRuleProps.html#source)

and from CloudFormation template reference:
["Supported resources include pipelines in AWS CodePipeline, repositories in AWS CodeCommit, and build projects in AWS CodeBuild."](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-codestarnotifications-notificationrule.html#aws-resource-codestarnotifications-notificationrule-properties)

In the console notification rules can easily be created for repository events and sent to SNS or Chatbot targets. I would like to replicate that with the CDK. 

### Environment

  - **CDK CLI Version:** 1.109.0
  - **Module Version:** 1.109.0
  - **Node.js Version:** 14.17.0
  - **OS:** Windows 10
  - **Language (Version):** 4.3.4

### Other information
According to CloudFormation, an ARN is required, however re-creating an ARN won't work `INotificationRuleSource` won't accept a string. Ideally it should work something like this:

```
    const repositoryNotification = new NotificationRule(this, 'PullRequestNotificationRule', {
      source: repository.repositoryArn,
      events: [
        'codecommit-repository-pull-request-created',
        'codecommit-repository-pull-request-merged'
      ],
      targets: [chatbot],
      detailType: DetailType.FULL,
      notificationRuleName: 'pull-request-status'
    })
    repositoryNotification.addTarget(chatbot)
```

**Comment by skinny85** [comment]
Thanks for opening the issue @badfun! We encourage community contributions, so if you'd be interested in submitting us a Pull Request adding this functionality, here's our "Contributing guide": https://github.com/aws/aws-cdk/blob/master/CONTRIBUTING.md.

**Comment by skinny85** [comment]
Also tagging @luckily for visibility, as he's the author of this functionality in the CDK.

**Comment by skinny85** [comment]
In the meantime, to unblock yourself, you should be able to write a class that implements the `codestarnotifications.INotificationRuleSource` interface, and takes in a CodeCommit `IRepository`, yourself:

```ts
import * as notifications from '@aws-cdk/aws-codestarnotifications';
import * as codecommit from '@aws-cdk/aws-codecommit';

export class CodeCommitNotification implements notifications.INotificationRuleSource {
  constructor(private readonly repository: codecommit.IRepository) {
  }

  bindAsNotificationRuleSource(scope: Construct): notifications.NotificationRuleSourceConfig {
    return {
      sourceArn: this.repository.repositoryArn,
    };
  }
}
```

**Comment by luckily** [comment]
Hi @badfun, can you try something like this?

```typescript
import * as cdk from '@aws-cdk/core';
import * as codecommit from '@aws-cdk/aws-codecommit';
import * as notifications from '@aws-cdk/aws-codestarnotifications';
import * as sns from '@aws-cdk/aws-sns';
import * as subs from '@aws-cdk/aws-sns-subscriptions';

const repo = new codecommit.Repository(this, 'MyRepo', {
  repositoryName: 'MyTestRepo',
  description: 'For CDK testing',
});

const topic = new sns.Topic(this, 'MySns', {
  topicName: 'NotifyFromCodecommit',
});

topic.addSubscription(new subs.EmailSubscription('my@email.address'));

const notification = new notifications.NotificationRule(this, 'MyNotificaitonRule', {
  source: {
    bindAsNotificationRuleSource: () => {
      return { sourceArn: repo.repositoryArn };
    },
  },
  events: [
    'codecommit-repository-pull-request-created',
  ],
});

notification.addTarget(topic);
```
You can also use `aws-chatbot` instead.

This is a quick workaround. It's works.

I would like to know If you want to contribute for this, I will be happy to give you suggestions and assist in the review. 🙂 If you don't want to contribute, I may try to contribute in a few days, but I'm not sure.

**Comment by badfun** [comment]
thanks @skinny85 and @luckily. I will give this a shot. @luckily I will see if I can put some time in on the solution. Have quite a bit on my plate at the moment (as do we all I'm sure) but I'd like to contribute.

**Comment by luckily** [comment]
I will wait for your contribution @badfun! 😄

**Comment by badfun** [comment]
@luckily I create a pull request: https://github.com/aws/aws-cdk/pull/15679
I spent most of my time trying to figure out how to deal with Gitpod. What a pain. Let me know if I need to make more changes.

**Comment by skinny85** [comment]
> I spent most of my time trying to figure out how to deal with Gitpod. What a pain.

What were the problems with Gitpod @badfun?

**Comment by badfun** [comment]
I couldn't figure out how to do the pull request from it. I think it may have been browser issues, but not sure. It seemed to hang when trying to authorize, etc. 
I ended up cloning the repo locally and then copying the changes from Gitpod to the local one, then pushing that.
I did test it with Gitpod on the pull request page and that worked fine.

**Comment by skinny85** [comment]
Hmm, weird... It always worked very smoothly for me. Sorry for the troubles!

**Comment by luckily** [comment]
@badfun You can develop on your local machine, it's very easy too, reference [here](https://aws.amazon.com/tw/blogs/developer/contributing-to-the-aws-cloud-development-kit/).

**Comment by badfun** [comment]
that sounds like a commitment! ;-)

**Comment by badfun** [comment]
Sorry fellas, I tried. I could not get an environment to work for me. Gitpod has some kind of access issues with my Github account and I could not push to my repo from the Workspace. I tried the local build, as per the instructions here: https://github.com/aws/aws-cdk/blob/master/CONTRIBUTING.md, but it failed on the '../../../scripts/buildup' step. I tried resuming, restarting, etc. but I always ended up with this error:

```
/c/Users/Ken/Cloud/DEV/AWS-CDK/aws-cdk/scripts/foreach.sh: line 36: printf: missing unicode digit for \U
C:\Users\Ken\Cloud\DEV\AWS-CDKws-cdk\packageswslint: yarn build  (24 remaining)
yarn run v1.22.10
$ tsc -b && eslint . --ext=.ts && pkglint && chmod +x bin/awslint
In package package.json
- [package-info/repository] repository.directory should be "packages\\awslint", is "packages/awslint" (fixable)
Error: Some package.json files had errors
    at main (C:\Users\Ken\Cloud\DEV\AWS-CDK\aws-cdk\tools\pkglint\bin\pkglint.js:29:15)
    at Object.<anonymous> (C:\Users\Ken\Cloud\DEV\AWS-CDK\aws-cdk\tools\pkglint\bin\pkglint.js:32:1)
    at Module._compile (internal/modules/cjs/loader.js:1068:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1097:10)
    at Module.load (internal/modules/cjs/loader.js:933:32)
    at Function.Module._load (internal/modules/cjs/loader.js:774:14)
    at Module.require (internal/modules/cjs/loader.js:957:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (C:\Users\Ken\Cloud\DEV\AWS-CDK\aws-cdk\tools\pkglint\bin\pkglint:2:1)
    at Module._compile (internal/modules/cjs/loader.js:1068:30)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error: last command failed. fix problem and resume by executing: /c/Users/Ken/Cloud/DEV/AWS-CDK/aws-cdk/scripts/foreach.sh
/c/Users/Ken/Cloud/DEV/AWS-CDK/aws-cdk/scripts/foreach.sh: line 40: printf: missing unicode digit for \U
directory:    C:\Users\Ken\Cloud\DEV\AWS-CDKws-cdk\packageswslint
```
I'm guessing it is something to do with packages not being correct versions or whatnot.

I have done a bunch of work which I *think* should be correct, you can access it in this branch of my fork:
https://github.com/badfun/aws-cdk/tree/add-codecommit-to-notification-source

Too frustrated to carry on right now. 
Ken

ps @luckily your code above worked fine and that is what I am using for now.

**Comment by luckily** [comment]
@badfun Sorry, I didn't expect that you might use Windows environment, but I think you can solve this problem with Docker, and you should mount  CDK source of local directory into Docker to execute some commands, and always execute scripts via Docker.

Gitpod is a good choice if you don't have suitable development environment.

**Comment by badfun** [comment]
@luckily Back in business. I followed the [blog post](https://aws.amazon.com/tw/blogs/developer/contributing-to-the-aws-cloud-development-kit/) you referenced and used WSL2 on WIndows. Got the environment working. Now I can go back to working on the code.

```
@aws-cdk/aws-codecommit: yarn run v1.22.10
@aws-cdk/aws-codecommit: $ cdk-test
@aws-cdk/aws-codecommit: test.codecommit.js
@aws-cdk/aws-codecommit: ✔ CodeCommit Repositories - add an SNS trigger to repository
@aws-cdk/aws-codecommit: ✔ CodeCommit Repositories - fails when triggers have duplicate names
@aws-cdk/aws-codecommit: ✔ CodeCommit Repositories - can be imported using a Repository ARN
@aws-cdk/aws-codecommit: ✔ CodeCommit Repositories - can be imported using a Repository ARN and respect the region in clone urls
@aws-cdk/aws-codecommit: ✔ CodeCommit Repositories - can be imported using just a Repository name (the ARN is deduced)
@aws-cdk/aws-codecommit: ✔ CodeCommit Repositories - grant push
@aws-cdk/aws-codecommit: ✔ CodeCommit Repositories - HTTPS (GRC) clone URL
@aws-cdk/aws-codecommit: OK: 13 assertions (10484ms)
@aws-cdk/aws-codecommit: =============================== Coverage summary ===============================
@aws-cdk/aws-codecommit: Statements   : 57.38% ( 70/122 )
@aws-cdk/aws-codecommit: Branches     : 57.78% ( 26/45 )
@aws-cdk/aws-codecommit: Functions    : 31.11% ( 14/45 )
@aws-cdk/aws-codecommit: Lines        : 57.02% ( 69/121 )
@aws-cdk/aws-codecommit: ================================================================================
@aws-cdk/aws-codecommit: Verifying integ.codecommit-events.js against integ.codecommit-events.expected.json ... OK.
@aws-cdk/aws-codecommit: Tests successful. Total time (42.1s) | /mnt/c/Users/Ken/cloud/dev/aws-cdk/aws-cdk/node_modules/nyc/bin/nyc.js (28.8s) | cdk-integ-assert (13.1s)
@aws-cdk/aws-codecommit: Done in 44.00s.
lerna success run Ran npm script 'test' in 1 package in 44.5s:
lerna success - @aws-cdk/aws-codecommit
```
