### ISSUE TITLE
cdk synth: cyclic dependency reported

### ISSUE THREAD

**Issue by alushnikov** [aws/aws-cdk#15741]
CDK fails to generate cloudformation template for role + policy

### Reproduction Steps
Sample code
```
class SampleCdkStack(cdk.Stack):

    def __init__(self, scope: cdk.Construct, construct_id: str, **kwargs) -> None:
        super().__init__(scope, construct_id, **kwargs)

        policy = iam.Policy(self,
                            "myApiAccessPolicyId",
                            policy_name="SamplePolicy"
                            )

        managed_policy = iam.CfnManagedPolicy(self,
                                              "myApiAccessPolicy",
                                              policy_document=policy.document
                                              )

        role = iam.CfnRole(self,
                           "myApiRole",
                           assume_role_policy_document={
                               "Version": "2012-10-17",
                               "Statement": {
                                          "Effect": "Allow",
                                          "Principal": {"Service": "lambda.amazonaws.com"},
                                          "Action": "sts:AssumeRole"
                               }
                           },
                           policies=[managed_policy]
                           )
```

### What did you expect to happen?
Expected role to be created with policy attached

### What actually happened?
`cdk synth` generates error
```
jsii.errors.JavaScriptError:
  Error: Resolution error: Resolution error: Unable to resolve object tree with circular reference. Path: /Resources/${Token[HelloCdkStack.myApiRole.LogicalID.66]}/Properties/policies/0/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host..
      at resolve (C:\Users\79118\AppData\Local\Temp\jsii-kernel-3Hq8pK\node_modules\@aws-cdk\core\lib\private\resolve.js:63:15)
      at Object.resolve (C:\Users\79118\AppData\Local\Temp\jsii-kernel-3Hq8pK\node_modules\@aws-cdk\core\lib\private\resolve.js:57:48)
      at resolve (C:\Users\79118\AppData\Local\Temp\jsii-kernel-3Hq8pK\node_modules\@aws-cdk\core\lib\private\resolve.js:145:51)
      at Object.resolve (C:\Users\79118\AppData\Local\Temp\jsii-kernel-3Hq8pK\node_modules\@aws-cdk\core\lib\private\resolve.js:57:48)
      at resolve (C:\Users\79118\AppData\Local\Temp\jsii-kernel-3Hq8pK\node_modules\@aws-cdk\core\lib\private\resolve.js:145:51)
      at Object.resolve (C:\Users\79118\AppData\Local\Temp\jsii-kernel-3Hq8pK\node_modules\@aws-cdk\core\lib\private\resolve.js:57:48)
      at resolve (C:\Users\79118\AppData\Local\Temp\jsii-kernel-3Hq8pK\node_modules\@aws-cdk\core\lib\private\resolve.js:145:51)
      at Object.resolve (C:\Users\79118\AppData\Local\Temp\jsii-kernel-3Hq8pK\node_modules\@aws-cdk\core\lib\private\resolve.js:57:48)
      at resolve (C:\Users\79118\AppData\Local\Temp\jsii-kernel-3Hq8pK\node_modules\@aws-cdk\core\lib\private\resolve.js:145:51)
      at Object.resolve (C:\Users\79118\AppData\Local\Temp\jsii-kernel-3Hq8pK\node_modules\@aws-cdk\core\lib\private\resolve.js:57:48)
```

### Environment

  - 1.115.0 (build f0ca40f)
  - aws-cdk.core==1.115.0
  - v14.17.3
  - Windows 10
  - Python 3.9.6

---

This is :bug: Bug Report

**Comment by NGL321** [comment]
Hey @alushnikov,

I have been able to reproduce this and confirmed it is a bug in the python construct library. That said, I recommend you alter the above code to not mix L1 and L2 resources, see here:

```python
        policy = iam.Policy(self,
                            "myApiAccessPolicyId",
                            policy_name="SamplePolicy"
                            )

        managed_policy = iam.ManagedPolicy(self,
                                              "myApiAccessPolicy",
                                              document=policy.document
                                              )

        role = iam.Role(self,
                           "myApiRole",
                           assumed_by=iam.ServicePrincipal("lambda.amazonaws.com"),
                           managed_policies=[managed_policy]
                           )
```

One of the devs will update this issue when they have a chance to look into a fix.


😸 😷
