### ISSUE TITLE
(bootstrap): json flag does not affect bootstrap output

### ISSUE THREAD

**Issue by awilkins** [aws/aws-cdk#15799]
### Expected: 

```sh
cdk bootstrap <params> --show-template --json # should emit JSON
```

### Actual:

It emits YAML

### Reason to change this

If you want to grab values from the bootstrap template e.g. to decide whether it needs running in a given account, it would be great to be able to

```sh
REQUIRED_VERSION=$(cdk bootstrap --show-template --json | jq .Resources.CdkBootstrapVersion.Properties.Value)
CURRENT_VERSION=$(aws ssm get-parameter <etc> )
if [ $REQUIRED_VERSION -gt $CURRENT_VERSION ]
then
  # actually bootstrap or maybe throw an error now rather than wait for your stack to fail
fi
```

`jq` is available in standard CodeBuild images but AFAICT an equivalent for parsing YAML is not.

### Environment

  - **CDK CLI Version  : *1.115.0*
  - **Framework Version: *1.115.0*
  - **Node.js Version:*v14.16.1*
  - **OS               :*Ubuntu 20.04*

--- 

This is :bug: Bug Report

**Comment by siqusoft** [comment]
getting the following error while bootstrapping wile executing 
the following command 
cdk bootstrap  -v 3

'@aws-cdk/core:newStyleStackSynthesis' context set, using new-style bootstrapping
environment.indexOf is not a function
TypeError: environment.indexOf is not a function
    at looksLikeGlob (/usr/local/lib/node_modules/aws-cdk/lib/api/cxapp/environments.ts:7:22)
    at Object.partition (/usr/local/lib/node_modules/aws-cdk/lib/util/arrays.ts:24:9)
    at CdkToolkit.bootstrap (/usr/local/lib/node_modules/aws-cdk/lib/cdk-toolkit.ts:349:23)
    at main (/usr/local/lib/node_modules/aws-cdk/bin/cdk.ts:277:20)
    at initCommandLine (/usr/local/lib/node_modules/aws-cdk/bin/cdk.ts:213:15)

**Comment by rix0rrr** [comment]
Hi @siqusoft, your issue seems unrelated to the OP. Please open a new bug report for that.

**Comment by rix0rrr** [comment]
As for the original report: reasonable ask, although one that will probably have to be contributed.

**Comment by awilkins** [comment]
Still think this would be a useful feature, but don't currently have an investment in it (the life of a consultant!)

**Comment by awilkins** [comment]
Yup, from the description of the merged PR it sounds like this is fixed.
