### ISSUE TITLE
How to connect lambda to CloudFront? AWS CDK JS

### ISSUE THREAD

**Issue by DioNNiS** [aws/aws-cdk#15846]
## :question: General Issue

Code:

```
rootOriginFunc = new cloudfront.experimental.EdgeFunction(stack, 'RootOriginFunction', {
    runtime: lambda.Runtime.NODEJS_14_X,
    handler: 'origin.handler',
    code: lambda.Code.fromAsset("./lib/lambdas"),
  });

  const lambdaFunctionAssociations = [
    {
      functionVersion: rootOriginFunc.currentVersion,
      eventType: cloudfront.LambdaEdgeEventType.ORIGIN_REQUEST,
    }
  ];

.....

....
{
    pathPattern: pathPattern,
    allowedMethods: cloudfront.CloudFrontAllowedMethods.ALL,
    forwardedValues: {
      queryString: true,
      headers: ["Authorization"],
    },
    defaultTtl,
    maxTtl,
    minTtl,
    isDefaultBehavior,
    lambdaFunctionAssociations,
  };
```

Error:
```
Users/denis/Documents/projects/ok/ok-app/cdk/node_modules/@aws-cdk/aws-cloudfront/lib/web-distribution.ts:601
        if (a.lambdaFunction.role && a.lambdaFunction.role instanceof iam.Role && a.lambdaFunction.role.assumeRolePolicy) {
                             ^
TypeError: Cannot read property 'role' of undefined
    at CloudFrontWebDistribution.toBehavior (/Users/denis/Documents/projects/ok/ok-app/cdk/node_modules/@aws-cdk/aws-cloudfront/lib/web-distribution.ts:601:30)
    at new CloudFrontWebDistribution (/Users/denis/Documents/projects/ok/ok-app/cdk/node_modules/@aws-cdk/aws-cloudfront/lib/web-distribution.ts:478:78)
    at new CdkStack (/Users/denis/Documents/projects/ok/ok-app/cdk/lib/cdk-stack.ts:68:26)
    at Object.<anonymous> (/Users/denis/Documents/projects/ok/ok-app/cdk/bin/cdk.ts:7:1)
```

### The Question
1. According to documentation: https://docs.aws.amazon.com/cdk/api/latest/docs/aws-cloudfront-readme.html#connection-behaviors-between-cloudfront-and-your-origin no role needs to be provided.
2. How to provide the required role?

### Environment

  - **CDK CLI Version:** 1.116.0
  - **Module Version:** 1.116.0
  - **Node.js Version:** v15.3.0
  - **OS:** MacOS
  - **Language (Version):** Typescript 3.9.7

**Comment by peterwoodworth** [comment]
Hey @DioNNiS, can you show your code where you create your `CloudFrontWebDistribution`? Thanks

**Comment by DioNNiS** [comment]
nothing special 

```
   // CloudFront distribution that provides HTTPS
    const distribution = new cloudfront.CloudFrontWebDistribution(
      this,
      STACK_NAME + "-Cloudfront_Distribution",
      {
        // by default Price Class PriceClass.PRICE_CLASS_100
        priceClass: cloudfront.PriceClass.PRICE_CLASS_ALL,
        aliasConfiguration: {
          acmCertRef: mainCertificateArn.certificateArn,
          names: [MAIN_DOMAIN_NAME, APP_OK_WIKI],
        },
        errorConfigurations: [
          {
            errorCode: 403,
            responseCode: 403,
            responsePagePath: "/404",
            errorCachingMinTtl: 0,
          },
          {
            errorCode: 404,
            responseCode: 200,
            responsePagePath: "/index",
            errorCachingMinTtl: 0,
          },
        ],
        originConfigs: [
          getGoogleFunctionAPIOriginConfig(),
          getFilesOriginConfig(this),
          getReactAppOriginConfig(),
        ]
      }
    );


function getReactAppOriginConfig() {
  return {
    // React Application
    customOriginSource: {
      domainName: REAСT_APP_DOMAIN_NAME,
    },
    originPath: "",
    behaviors: [
      getReactAppOriginConfigBehavior(
        "*",
        noDuration,
        noDuration,
        noDuration,
        true
      ),
    ],
  };
}
```

**Comment by peterwoodworth** [comment]
[`LambdaFunctionAssociations`](https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-cloudfront.LambdaFunctionAssociation.html) should take in:
```ts
{
  lambdaFunction: IVersion
  eventType: LambdaEdgeEventType
}
```
You're currently passing in `functionVersion` as the prop instead of `lambdaFunction`. Role isn't what's showing up as undefined, the property `role` (which as you noted isn't required) can't be found on an undefined object. This means that the `lambdaFunction` is undefined, and that's because you're not passing in a `lambdaFunction`

**Comment by DioNNiS** [comment]
thank you, @peterwoodworth! you are right.
