### ISSUE TITLE
(EC2 VPC): Removing subnet group applied in RDS Replica casues deletion of that subnet

### ISSUE THREAD

**Issue by tom10271** [aws/aws-cdk#15879]
I was created a RDS and a RDS replica. They were both in Private subnet. I later found I need to expose the replica server in public subnet so I update the CDK code.

### Reproduction Steps
Originally
```ts
RDS.POSTGRES = new DatabaseInstance(scope, "Odoo PostgreSQL RDS", {
        databaseName: 'odoo_app',
        instanceIdentifier: 'odoo-pg-rds',
        engine: DatabaseInstanceEngine.postgres({
            version: PostgresEngineVersion.VER_12_5,
        }),
        vpc: NETWORKING.VPC,
        removalPolicy: RemovalPolicy.RETAIN,
        deleteAutomatedBackups: true,
        backupRetention: Duration.days(14),
        enablePerformanceInsights: true,
        instanceType: config.rdsInstanceType,
        credentials: Credentials.fromPassword(
            "root",
            SecretValue.ssmSecure(
                'Odoo-RDS-PostgreSQL-master-password',
                config.ssmPasswordVersion
            )
        ),
        allocatedStorage: 16,
        vpcSubnets: {
            subnets: [
                NETWORKING.PRIVATE_SUBNET_2B, NETWORKING.PRIVATE_SUBNET_2C
            ]
        },
        securityGroups: [SECURITY_GROUP.RDS]
    });

    RDS.POSTGRES_REPLICA = new DatabaseInstanceReadReplica(scope, "Odoo PostgreSQL RDS replica", {
        sourceDatabaseInstance: RDS.POSTGRES,
        instanceType: config.rdsReplicaInstanceType,
        instanceIdentifier: 'odoo-pg-rds-replica',
        vpc: NETWORKING.VPC,
        vpcSubnets: {
            subnets: [
                NETWORKING.PRIVATE_SUBNET_2B, NETWORKING.PRIVATE_SUBNET_2C
            ]
        },
        securityGroups: [
            SECURITY_GROUP.RDS_GOOGLE_DATA_STUDIO_ACCESS,
            SECURITY_GROUP.RDS_STITCH_ACCESS,
            SECURITY_GROUP.RDS_INTERNAL_STAFF_ACCESS,
        ]
    });
```

To:
```ts
RDS.POSTGRES = new DatabaseInstance(scope, "Odoo PostgreSQL RDS", {
        databaseName: 'odoo_app',
        instanceIdentifier: 'odoo-pg-rds',
        engine: DatabaseInstanceEngine.postgres({
            version: PostgresEngineVersion.VER_12_5,
        }),
        vpc: NETWORKING.VPC,
        removalPolicy: RemovalPolicy.RETAIN,
        deleteAutomatedBackups: true,
        backupRetention: Duration.days(14),
        enablePerformanceInsights: true,
        instanceType: config.rdsInstanceType,
        credentials: Credentials.fromPassword(
            "root",
            SecretValue.ssmSecure(
                'Odoo-RDS-PostgreSQL-master-password',
                config.ssmPasswordVersion
            )
        ),
        allocatedStorage: 16,
        vpcSubnets: {
            subnets: [
                NETWORKING.PRIVATE_SUBNET_2B, NETWORKING.PRIVATE_SUBNET_2C
            ]
        },
        securityGroups: [SECURITY_GROUP.RDS]
    });

    RDS.POSTGRES_REPLICA = new DatabaseInstanceReadReplica(scope, "Odoo PostgreSQL RDS replica", {
        sourceDatabaseInstance: RDS.POSTGRES,
        instanceType: config.rdsReplicaInstanceType,
        instanceIdentifier: 'odoo-pg-rds-replica',
        vpc: NETWORKING.VPC,
        vpcSubnets: {
            subnets: [
                NETWORKING.PUBLIC_SUBNET_2B, NETWORKING.PUBLIC_SUBNET_2C  // This line only
            ]
        },
        securityGroups: [
            SECURITY_GROUP.RDS_GOOGLE_DATA_STUDIO_ACCESS,
            SECURITY_GROUP.RDS_STITCH_ACCESS,
            SECURITY_GROUP.RDS_INTERNAL_STAFF_ACCESS,
        ]
    });
```

### What did you expect to happen?
It should just remove the subnet applied in the replica but not deleting the subnet.

### What actually happened?
```
[Warning at /OdooStack/OdooWebSecurityGroup] Ignoring Egress rule since 'allowAllOutbound' is set to true; To add customize rules, set allowAllOutbound=false on the SecurityGroup
[Warning at /OdooStack/OdooWebSecurityGroup] Ignoring Egress rule since 'allowAllOutbound' is set to true; To add customize rules, set allowAllOutbound=false on the SecurityGroup
OdooStack: deploying...
OdooStack: creating CloudFormation changeset...
12:39:59 PM | UPDATE_FAILED        | AWS::RDS::DBSubnetGroup                   | OdooPostgreSQLRDSr...ubnetGroup87916748
Some of the subnets to be deleted are currently in use: subnet-0e989d80569f07181 (Service: AmazonRDS; Status Code: 400; Error Code: InvalidParameterValue; Request ID: cae7cafa-af29-458d-a25b-661deb912d6d; Proxy: null)

    new SubnetGroup (/Users/me/Sites/odoo-deployment/cdk/node_modules/@aws-cdk/aws-rds/lib/subnet-group.ts:78:25)
    \_ new DatabaseInstanceNew (/Users/me/Sites/odoo-deployment/cdk/node_modules/@aws-cdk/aws-rds/lib/instance.ts:641:46)
    \_ new DatabaseInstanceReadReplica (/Users/me/Sites/odoo-deployment/cdk/node_modules/@aws-cdk/aws-rds/lib/instance.ts:1112:5)
    \_ Object.databaseSetup (/Users/me/Sites/odoo-deployment/cdk/src/Database/index.ts:45:28)
    \_ OdooStack.run (/Users/me/Sites/odoo-deployment/cdk/src/odoo-stack.ts:41:9)
    \_ /Users/me/Sites/odoo-deployment/cdk/bin/cdk.ts:8:5


 ❌  OdooStack failed: Error: The stack named OdooStack failed to deploy: UPDATE_ROLLBACK_COMPLETE
    at Object.waitForStackDeploy (/Users/me/.nvm/versions/node/v14.15.1/lib/node_modules/cdk/node_modules/aws-cdk/lib/api/util/cloudformation.ts:307:11)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at Object.deployStack (/Users/me/.nvm/versions/node/v14.15.1/lib/node_modules/cdk/node_modules/aws-cdk/lib/api/deploy-stack.ts:294:26)
    at CdkToolkit.deploy (/Users/me/.nvm/versions/node/v14.15.1/lib/node_modules/cdk/node_modules/aws-cdk/lib/cdk-toolkit.ts:184:24)
    at initCommandLine (/Users/me/.nvm/versions/node/v14.15.1/lib/node_modules/cdk/node_modules/aws-cdk/bin/cdk.ts:213:9)
The stack named OdooStack failed to deploy: UPDATE_ROLLBACK_COMPLETE
```

### Environment

  - **CDK CLI Version  :** 1.116.0 (build d04661d)
  - **Framework Version:** ~1.116.0
  - **Node.js Version:**  v14.15.1
  - **OS               :** macOS 10.15.2 (19C57)
  - **Language (Version):**  TS ~3.9.7

### Other

cdk diff shows
```
Stack OdooStack
Resources
[~] AWS::RDS::DBSubnetGroup Odoo PostgreSQL RDS replica/SubnetGroup OdooPostgreSQLRDSreplicaSubnetGroup87916748 
 └─ [~] SubnetIds
     └─ @@ -4,11 +4,5 @@
        [ ]   },
        [ ]   {
        [ ]     "Ref": "odoopublicsubnetuswest2cSubnet49082E04"
        [-]   },
        [-]   {
        [-]     "Ref": "odooprivatesubnetuswest2bSubnet29F81E82"
        [-]   },
        [-]   {
        [-]     "Ref": "odooprivatesubnetuswest2cSubnet9633F252"
        [ ]   }
        [ ] ]
```

--- 

This is :bug: Bug Report

**Comment by njlynch** [comment]
Thanks for the report.

I found the following Premium Support Knowledge Center article describing the process for moving an instance from a public to private subnet; I believe the same set of steps can be followed to do the reverse (moving from private to public). https://aws.amazon.com/premiumsupport/knowledge-center/rds-move-to-private-subnet/

It looks like this will require 3 separate deployments and a manual action: (a) adding the public subnets, and removing one of the private subnets; (b) enabling multi-AZ mode; (c) rebooting the instance with failover; (d) removing the public subnet and multi-AZ settings.

Please give the above a shot. I'm going to close this out for now as resolved with the above guidance; feel free to comment and mention me to re-open if you have follow-ups.
