### ISSUE TITLE
(ec2): AttributeError: type object 'tuple' has no attribute '__jsii_type__' on cdk synth

### ISSUE THREAD

**Issue by hess-patrick-pfg** [aws/aws-cdk#15966]
When I run cdk synth, I get an error with the jsii module.

### Reproduction Steps

Run cdk synth on following code:
```
from aws_cdk import core as cdk
from aws_cdk import aws_ec2 as ec2
from aws_cdk import aws_ssm as ssm
from aws_cdk import aws_iam
from aws_cdk import aws_dlm as dlm
from src.config import Config


class AwsPbiGatewayInfraStack(cdk.Stack):

    def __init__(self, scope, construct_id, **kwargs) -> None:
        super().__init__(scope, construct_id, **kwargs)
```
More code below but the cdk doesn't even reach that code.

app.py looks like this

```
from aws_cdk import core as cdk
from aws_pbi_gateway_infra.src.aws_pbi_gateway_infra_stack import AwsPbiGatewayInfraStack
from aws_pbi_gateway_infra.src.config import Config


class Main:
    def __init__(self):
        self.create_app()

    def create_app(self):
        app = cdk.App(),
        gb_pbi_stack_name = Config.app_stack_name(),
        gb_pbi_stack = AwsPbiGatewayInfraStack(
            app,
            gb_pbi_stack_name,
            env={
                "account": Config.account,
                "region": Config.region
            }
        )

        app.synth()


if __name__ == "__main__":
    Main()
```

### What did you expect to happen?
My stack to be synthesized.

### What actually happened?

```
(.venv) λ cdk synth
(node:22916) ExperimentalWarning: The fs.promises API is experimental
Traceback (most recent call last):
  File "app.py", line 27, in <module>
    Main()
  File "app.py", line 9, in __init__
    self.create_app()
  File "app.py", line 14, in create_app
    gb_pbi_stack = AwsPbiGatewayInfraStack(
  File "C:\git\sbd-analytics-account-infra\aws_pbi_gateway_infra\.venv\lib\site-packages\jsii\_runtime.py", line 83, in __call__
    inst = super().__call__(*args, **kwargs)
  File "C:\git\sbd-analytics-account-infra\aws_pbi_gateway_infra\aws_pbi_gateway_infra\src\aws_pbi_gateway_infra_stack.py", line 12, in __init__
    super().__init__(scope, construct_id, **kwargs)
  File "C:\git\sbd-analytics-account-infra\aws_pbi_gateway_infra\.venv\lib\site-packages\aws_cdk\core\__init__.py", line 15642, in __init__
    jsii.create(Stack, self, [scope, id, props])
  File "C:\git\sbd-analytics-account-infra\aws_pbi_gateway_infra\.venv\lib\site-packages\jsii\_kernel\__init__.py", line 278, in create
    args=_make_reference_for_native(self, args),
  File "C:\git\sbd-analytics-account-infra\aws_pbi_gateway_infra\.venv\lib\site-packages\jsii\_kernel\__init__.py", line 144, in _make_reference_for_native
    return [_make_reference_for_native(kernel, i) for i in d]
  File "C:\git\sbd-analytics-account-infra\aws_pbi_gateway_infra\.venv\lib\site-packages\jsii\_kernel\__init__.py", line 144, in <listcomp>
    return [_make_reference_for_native(kernel, i) for i in d]
  File "C:\git\sbd-analytics-account-infra\aws_pbi_gateway_infra\.venv\lib\site-packages\jsii\_kernel\__init__.py", line 184, in _make_reference_for_native
    kernel.create(d.__class__, d)
  File "C:\git\sbd-analytics-account-infra\aws_pbi_gateway_infra\.venv\lib\site-packages\jsii\_kernel\__init__.py", line 277, in create
    fqn=klass.__jsii_type__ or "Object",
AttributeError: type object 'tuple' has no attribute '__jsii_type__'
Subprocess exited with error 1
```

### Environment

  - **CDK CLI Version  :1.116.0 (build d04661d)**
  - **Framework Version: 1.116.0**
  - **Node.js Version: 7.16.0** 
  - **OS               : Windows 10**
  - **Language (Version):** Python (3.8.10)
  -  All installed cdk packages are 1.116.0 in my .venv

### Other

--- 

This is :bug: Bug Report

#12900 is similar

Please let me know if I can provide further info. I can usually find work around for most of the issues I run into - but can't get past this one.

**Comment by hess-patrick-pfg** [comment]
I've been able to further troubleshoot where this is coming from. It seems there's some issue in my app.py. I changed it back to the default setup of 
```
app = cdk.App()
AwsPbiGatewayInfraStack(app, "AwsPbiGatewayInfraStack",
    # If you don't specify 'env', this stack will be environment-agnostic.
    # Account/Region-dependent features and context lookups will not work,
    # but a single synthesized template can be deployed anywhere.

    # Uncomment the next line to specialize this stack for the AWS Account
    # and Region that are implied by the current CLI configuration.

    env=cdk.Environment(account=os.getenv('CDK_DEFAULT_ACCOUNT'), region=os.getenv('CDK_DEFAULT_REGION'))
)

app.synth()
``` 
And I was able to synth. Going to step through my changes slowly and see which one breaks it again.

**Comment by hess-patrick-pfg** [comment]
Further troubleshooting lead me to find that the issue is related to structuring the app.py like this:

```
class Main:
    def __init__(self):
        self.create_app()

    def create_app(self):
        app = cdk.App(),
        gb_pbi_stack_name = Config.app_stack_name(),
        gb_pbi_stack = AwsPbiGatewayInfraStack(
            app,
            gb_pbi_stack_name,
            env=cdk.Environment(account=Config.account, region=Config.region)
        )

        app.synth()


if __name__ == "__main__":
    Main()
```

Changing it back to the default of
```
app = cdk.App()
AwsPbiGatewayInfraStack(
    app,
    Config.app_stack_name(),
    env=cdk.Environment(account=Config.account, region=Config.region)
)

app.synth()
```
Seems to resolve the issue.

**Comment by hess-patrick-pfg** [comment]
Closing for now - but will add more comments if I find a work around for the code.

**Comment by csaba-feher-sonarsource** [comment]
Hi @hess-patrick-pfg ,

I answer this just for future people who are confused by a similar error. This is not an issue with CDK. you have left an extra `,` at the end on `app = cdk.App(),` and `Config.app_stack_name(),`. removing it would solve the issue above. Python recognises those rows as would be part of 1 tuple.

```
class Main:
    def __init__(self):
        self.create_app()

    def create_app(self):
        app = cdk.App()
        gb_pbi_stack_name = Config.app_stack_name()
        gb_pbi_stack = AwsPbiGatewayInfraStack(
            app,
            gb_pbi_stack_name,
            env=cdk.Environment(account=Config.account, region=Config.region)
        )

        app.synth()

if __name__ == "__main__":
    Main()
```
