### ISSUE TITLE
codebuild: Codebuild project cannot be synthesized due to buildspec supplied

### ISSUE THREAD

**Issue by sarbajitdutta** [aws/aws-cdk#15970]
### The Question
AWS Codebuild causes issues when synthesizing - 

```
aused by: org.apache.maven.plugin.MojoExecutionException: An exception occured while executing the Java class. Expected object reference, got "${Token[TOKEN.369]}"
Error: Expected object reference, got "${Token[TOKEN.369]}"
    at Object.deserialize (/private/var/folders/kt/r42qr4ks6z5b1y89qtzgt9780000gn/T/jsii-java-runtime10609885977828072424/lib/program.js:9044:31)
    at Kernel._toSandbox (/private/var/folders/kt/r42qr4ks6z5b1y89qtzgt9780000gn/T/jsii-java-runtime10609885977828072424/lib/program.js:8505:69)
    at /private/var/folders/kt/r42qr4ks6z5b1y89qtzgt9780000gn/T/jsii-java-runtime10609885977828072424/lib/program.js:9007:81
    at mapValues (/private/var/folders/kt/r42qr4ks6z5b1y89qtzgt9780000gn/T/jsii-java-runtime10609885977828072424/lib/program.js:9341:35)
    at Object.deserialize (/private/var/folders/kt/r42qr4ks6z5b1y89qtzgt9780000gn/T/jsii-java-runtime10609885977828072424/lib/program.js:9007:36)
    at Kernel._toSandbox (/private/var/folders/kt/r42qr4ks6z5b1y89qtzgt9780000gn/T/jsii-java-runtime10609885977828072424/lib/program.js:8505:69)
    at /private/var/folders/kt/r42qr4ks6z5b1y89qtzgt9780000gn/T/jsii-java-runtime10609885977828072424/lib/program.js:9070:37
    at mapValues (/private/var/folders/kt/r42qr4ks6z5b1y89qtzgt9780000gn/T/jsii-java-runtime10609885977828072424/lib/program.js:9341:35)
    at Object.deserialize (/private/var/folders/kt/r42qr4ks6z5b1y89qtzgt9780000gn/T/jsii-java-runtime10609885977828072424/lib/program.js:9066:28)
    at Kernel._toSandbox (/private/var/folders/kt/r42qr4ks6z5b1y89qtzgt9780000gn/T/jsii-java-runtime10609885977828072424/lib/program.js:8505:69)
    at org.codehaus.mojo.exec.ExecJavaMojo.execute (ExecJavaMojo.java:311)
    at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo (DefaultBuildPluginManager.java:137)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:210)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:156)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:148)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:117)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:81)
    at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build (SingleThreadedBuilder.java:56)
    at org.apache.maven.lifecycle.internal.LifecycleStarter.execute (LifecycleStarter.java:128)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:305)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:192)
    at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:105)
    at org.apache.maven.cli.MavenCli.execute (MavenCli.java:957)
    at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:289)
    at org.apache.maven.cli.MavenCli.main (MavenCli.java:193)
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:64)
    at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke (Method.java:564)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launcher.java:282)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:225)
    at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launcher.java:406)
    at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:347)
```
```
//CodeBuild Project for ReCiter-Pubmed
        reCiterPubmedCodebuildProject = new Project(this, "reciter-pubmed-codebuild", ProjectProps.builder()
            .projectName("ReCiter-Pubmed-Retrieval-Tool")
            .source(githubSource)
            .environment(BuildEnvironment.builder()
                .buildImage(LinuxBuildImage.AMAZON_LINUX_2_3)
                .computeType(ComputeType.SMALL)
                .privileged(true)
                .build())
            .environmentVariables(new HashMap(){{
                put("ECR_REPO_URI", reCiterPubmedEcrRepo.getRepositoryUri());
                put("CLUSTER_NAME", reCiterCluster.getClusterName());
            }})
            .buildSpec(BuildSpec.fromObject(new HashMap(){{
                put("buildspec.yml", new JSONObject()
                    .put("version", "0.2")
                    .put("phases", new JSONObject()
                        .put("pre_build", new JSONObject()
                            .put("commands", new JSONArray()
                                .put("env")
                                .put("export TAG=${CODEBUILD_RESOLVED_SOURCE_VERSION}")))
                        .put("build", new JSONObject()
                            .put("commands", new JSONArray()
                                .put("`docker build -t $ECR_REPO_URI:$TAG .`")
                                .put("$(aws ecr get-login --no-include-email)")
                                .put("docker push $ECR_REPO_URI:$TAG")))
                        .put("post_build", new JSONObject()
                            .put("commands", new JSONArray()
                                .put("echo \"In Post-Build Stage\"")
                                .put("printf '[{\"name\":\"reciter-pubmed\",\"imageUri\":\"%s\"}]' $ECR_REPO_URI:$TAG > imagedefinitions.json")
                                .put("pwd; ls -al; cat imagedefinitions.json"))))
                    .put("artifacts", new JSONObject()
                        .put("files", new JSONArray()
                            .put("imagedefinitions.json"))));
            }}))
            .build());
```

### Environment

  - **CDK CLI Version:** 1.117.0
  - **Module Version:** 1.117.0
  - **Node.js Version:** 16.4.2
  - **OS:** macOS Sierra
  - **Language (Version):** Java8

**Comment by sarbajitdutta** [comment]
This was solved.

```
//CodeBuild Project for ReCiter-Pubmed
        reCiterPubmedCodebuildProject = new Project(this, "reciter-pubmed-codebuild", ProjectProps.builder()
            .projectName("ReCiter-Pubmed-Retrieval-Tool")
            .source(Source.gitHub(GitHubSourceProps.builder()
                .owner("sarbajitdutta")
                .repo("ReCiter-PubMed-Retrieval-Tool")
                .webhook(false)
                //.webhookFilters(Arrays.asList(FilterGroup.inEventOf(EventAction.PUSH).andBranchIs("master")))
                .reportBuildStatus(false)
                .build()))
            .badge(true)
            .cache(Cache.local(LocalCacheMode.DOCKER_LAYER))
            .environment(BuildEnvironment.builder()
                .buildImage(LinuxBuildImage.AMAZON_LINUX_2_3)
                .computeType(ComputeType.SMALL)
                .privileged(true)
                .build())
            .environmentVariables(new HashMap<String, BuildEnvironmentVariable>(){{
                put("ECR_REPO_URI", BuildEnvironmentVariable.builder()
                        .type(BuildEnvironmentVariableType.PLAINTEXT)
                        .value(reCiterPubmedEcrRepo.getRepositoryUri())
                        .build());
                put("CLUSTER_NAME", BuildEnvironmentVariable.builder()
                    .type(BuildEnvironmentVariableType.PLAINTEXT)
                    .value(reCiterCluster.getClusterName())
                    .build());
            }})
            .buildSpec(BuildSpec.fromObjectToYaml(new HashMap<String, Object>(){{
                put("version", "0.2");
                put("phases", new JSONObject()
                    .put("pre_build", new JSONObject()
                        .put("commands", new JSONArray()
                            .put("env")
                            .put("export TAG=${CODEBUILD_RESOLVED_SOURCE_VERSION}")))
                    .put("build", new JSONObject()
                        .put("commands", new JSONArray()
                            .put("mvn clean install -Dmaven.test.skip=true")
                            .put("docker build -t $ECR_REPO_URI:$TAG .")
                            .put("$(aws ecr get-login --no-include-email)")
                            .put("docker push $ECR_REPO_URI:$TAG")))
                    .put("post_build", new JSONObject()
                        .put("commands", new JSONArray()
                            .put("echo \"In Post-Build Stage\"")
                            .put("printf '[{\"name\":\"reciter-pubmed\",\"imageUri\":\"%s\"}]' $ECR_REPO_URI:$TAG > imagedefinitions.json")
                            .put("pwd; ls -al; cat imagedefinitions.json"))).toMap());
                put("artifacts", new JSONObject()
                .put("files", new JSONArray()
                    .put("imagedefinitions.json")).toMap());
            }}))
            .build());
```
