### ISSUE TITLE
aws-eks: onCreate fails with IAM error "could not be assumed" in OnEventHandler lambda

### ISSUE THREAD

**Issue by larhauga** [aws/aws-cdk#16037]
We have been experiencing problems when creating new EKS clusters with CDK in new accounts. 
We get the following error intermittently, with the following error message in  the `onCreate` OnEventHandler lambda: 

```
Role with arn: arn:aws:iam::XXX:role/plattform-eks-infra-eksRoleB1016F54-TGOP9GRMY6BJ, could not be assumed because it does not exist or the trusted entity is not correct
```
The role has been created ~3minutes before the clusterCreate is triggered according to the cloudformation event history. 
**Could this be a race condition in IAM?**. And would it be possible to add some error handling or retry logic in the lambda for this issue?

### Reproduction Steps
The following code illustrates what we are doing when creating the cluster, highly minimized. 
We have tried reproducing with this minimized code, but have been **unable to reproduce it this way**.

We rely on the default cluster role creation, and do not setup our own role. 

```main.go
package main

import (
        awscdk "github.com/aws/aws-cdk-go/awscdk/v2"
        "github.com/aws/aws-cdk-go/awscdk/v2/awsec2"
        "github.com/aws/aws-cdk-go/awscdk/v2/awseks"
        "github.com/aws/aws-cdk-go/awscdk/v2/awsiam"
        "github.com/aws/aws-cdk-go/awscdk/v2/awskms"
        "github.com/aws/jsii-runtime-go"
)

func main() {
        app := awscdk.NewApp(nil)

        accountID := "XXX"
        region := "eu-north-1"
        stack := awscdk.NewStack(app, jsii.String("eks-stack"), &awscdk.StackProps{Env: &awscdk.Environment{Region: &region, Account: &accountID}})

        vpc := awsec2.Vpc_FromLookup(stack, jsii.String("vpc"), &awsec2.VpcLookupOptions{IsDefault: jsii.Bool(true)})
        kmsKey := awskms.NewKey(stack, jsii.String("eks-kms"), &awskms.KeyProps{Alias: jsii.String("eks")})
        eksControlPlaneSG := awsec2.NewSecurityGroup(stack, jsii.String("eks-control-sg"), &awsec2.SecurityGroupProps{Vpc: vpc})

        cluster := awseks.NewCluster(stack, jsii.String("eksCluster"), &awseks.ClusterProps{
                Version:              awseks.KubernetesVersion_Of(jsii.String("1.21")),
                ClusterName:          jsii.String("eks-cluster"),
                Vpc:                  vpc,
                VpcSubnets:           &[]*awsec2.SubnetSelection{{SubnetGroupName: jsii.String("Private")}},
                EndpointAccess:       awseks.EndpointAccess_PRIVATE(),
                SecurityGroup:        eksControlPlaneSG,
                SecretsEncryptionKey: kmsKey,
                DefaultCapacity:      jsii.Number(0),
                /*Role: awsiam.NewRole(stack, jsii.String("eks"), &awsiam.RoleProps{}), */
        })
        cluster.Role().AddManagedPolicy(
                awsiam.ManagedPolicy_FromAwsManagedPolicyName(jsii.String("AmazonEKSVPCResourceController")),
        )

        app.Synth(nil)
}
```
```go.mod
module repo

go 1.16

require (
        github.com/aws/aws-cdk-go/awscdk/v2 v2.0.0-rc.16
        github.com/aws/jsii-runtime-go v1.31.0
        github.com/davecgh/go-spew v1.1.1 // indirect
        gopkg.in/yaml.v3 v3.0.0-20210107192922-496545a6307b // indirect
)
```

### What did you expect to happen?
We expect a new EKS cluster to be created that uses the roleArn of the default Role created by CDK. When the role is created but create cluster fails with assume on role, we would expect it to retry the operation.

### What actually happened?
When the Cluster creation operation is triggered, the lambda onCreate function failes with an IAM error (also present in cloudtrail). 

```
START RequestId: f70a3242-8bdf-4a6b-950b-6debe3017e20 Version: $LATEST
2021-08-12T09:23:35.099Z	f70a3242-8bdf-4a6b-950b-6debe3017e20	INFO	
{
    "assumeRole": {
        "RoleArn": "arn:aws:iam::xxx:role/plattform-eks-infra-eksCreationRoleF889249E-CH4GCEIK3DY6",
        "RoleSessionName": "AWSCDK.EKSCluster.Create.6d04a230-0165-4eaf-9cfa-f4fac88e0581"
    }
}

2021-08-12T09:23:35.184Z	f70a3242-8bdf-4a6b-950b-6debe3017e20	INFO	onCreate: creating cluster with options: 
{
    "encryptionConfig": [
        {
            "provider": {
                "keyArn": "arn:aws:kms:eu-north-1:xxx:key/zzz"
            },
            "resources": [
                "secrets"
            ]
        }
    ],
    "resourcesVpcConfig": {
        "endpointPrivateAccess": true,
        "securityGroupIds": [
            "sg-zzz"
        ],
        "endpointPublicAccess": false,
        "subnetIds": [
            "subnet-yyy",
            "subnet-yyy",
            "subnet-yyy"
        ]
    },
    "roleArn": "arn:aws:iam::xxx:role/plattform-eks-infra-eksRoleB1016F54-TGOP9GRMY6BJ",
    "name": "test-infra",
    "version": "1.21"
}

2021-08-12T09:23:36.285Z	f70a3242-8bdf-4a6b-950b-6debe3017e20	INFO	[AWS sts 200 1.059s 0 retries] assumeRole({
  RoleArn: 'arn:aws:iam::xxx:role/plattform-eks-infra-eksCreationRoleF889249E-CH4GCEIK3DY6',
  RoleSessionName: 'AWSCDK.EKSCluster.Create.6d04a230-0165-4eaf-9cfa-f4fac88e0581'
})
2021-08-12T09:23:45.084Z	f70a3242-8bdf-4a6b-950b-6debe3017e20	INFO	[AWS eks 400 9.86s 0 retries] createCluster({
  encryptionConfig: [
    {
      provider: {
        keyArn: 'arn:aws:kms:eu-north-1:xxx:key/zzz'
      },
      resources: [ 'secrets', [length]: 1 ]
    },
    [length]: 1
  ],
  resourcesVpcConfig: {
    endpointPrivateAccess: true,
    securityGroupIds: [ 'sg-zzz', [length]: 1 ],
    endpointPublicAccess: false,
    subnetIds: [
      'subnet-yyy',
      'subnet-yyy',
      'subnet-yyy',
      [length]: 3
    ]
  },
  roleArn: 'arn:aws:iam::xxx:role/plattform-eks-infra-eksRoleB1016F54-TGOP9GRMY6BJ',
  name: 'test-infra',
  version: '1.21',
  clientRequestToken: '8df00d18-a166-4a69-8ee0-53162c35c682'
})
2021-08-12T09:23:45.104Z	f70a3242-8bdf-4a6b-950b-6debe3017e20	ERROR	Invoke Error 	
{
    "errorType": "InvalidParameterException",
    "errorMessage": "Role with arn: arn:aws:iam::xxx:role/plattform-eks-infra-eksRoleB1016F54-TGOP9GRMY6BJ, could not be assumed because it does not exist or the trusted entity is not correct",
    "code": "InvalidParameterException",
    "message": "Role with arn: arn:aws:iam::xxx:role/plattform-eks-infra-eksRoleB1016F54-TGOP9GRMY6BJ, could not be assumed because it does not exist or the trusted entity is not correct",
    "time": "2021-08-12T09:23:45.083Z",
    "requestId": "8f8e4f48-590c-467e-8d81-87c1416d2649",
    "statusCode": 400,
    "retryable": false,
    "retryDelay": 90.1185298748437,
    "stack": [
        "InvalidParameterException: Role with arn: arn:aws:iam::xxx:role/plattform-eks-infra-eksRoleB1016F54-TGOP9GRMY6BJ, could not be assumed because it does not exist or the trusted entity is not correct",
        "    at Object.extractError (/var/runtime/node_modules/aws-sdk/lib/protocol/json.js:52:27)",
        "    at Request.extractError (/var/runtime/node_modules/aws-sdk/lib/protocol/rest_json.js:55:8)",
        "    at Request.callListeners (/var/runtime/node_modules/aws-sdk/lib/sequential_executor.js:106:20)",
        "    at Request.emit (/var/runtime/node_modules/aws-sdk/lib/sequential_executor.js:78:10)",
        "    at Request.emit (/var/runtime/node_modules/aws-sdk/lib/request.js:688:14)",
        "    at Request.transition (/var/runtime/node_modules/aws-sdk/lib/request.js:22:10)",
        "    at AcceptorStateMachine.runTo (/var/runtime/node_modules/aws-sdk/lib/state_machine.js:14:12)",
        "    at /var/runtime/node_modules/aws-sdk/lib/state_machine.js:26:10",
        "    at Request.<anonymous> (/var/runtime/node_modules/aws-sdk/lib/request.js:38:9)",
        "    at Request.<anonymous> (/var/runtime/node_modules/aws-sdk/lib/request.js:690:12)"
    ]
}

END RequestId: f70a3242-8bdf-4a6b-950b-6debe3017e20
REPORT RequestId: f70a3242-8bdf-4a6b-950b-6debe3017e20	Duration: 10045.62 ms	Billed Duration: 10046 ms	Memory Size: 128 MB	Max Memory Used: 88 MB	Init Duration: 377.88 ms	
```

### Environment

  - **CDK CLI Version  :** v2.0.0-rc.16
  - **Framework Version:** v2.0.0-rc.16
  - **Node.js Version:**  v14.17.3 (rhel) / 14.17.2 (codebuild/ubuntu/standard:5.0)
  - **OS               :** rhel 7 / codebuild ubuntu/standard:5.0
  - **Language (Version):** go 1.16.6 (aws-cdk-go: v2.0.0-rc.16)

--- 

This is :bug: Bug Report

**Comment by otaviomacedo** [comment]
Yes, it does seem like an IAM race condition. But we can add retries, as you suggest, to mitigate the problem. I'm marking the issue as `p2`, as it happens infrequently, based on your description.

As an aside, have you tried contacting AWS support about this? With the clientRequestToken and timestamp of the event, maybe they can investigate this further.

**Comment by larhauga** [comment]
@otaviomacedo thanks for the swift reply. I will follow this up with our AWS contact as well.
