### ISSUE TITLE
(aws-elasticsearch): VPC subnet selection for multi-AZ domain does not work

### ISSUE THREAD

**Issue by LinusPhoenix** [aws/aws-cdk#16176]
I am trying to create an Elasticsearch domain with 2 data nodes, in two availability zones. For this, I already have a VPC that has two private subnets, each in a different availability zone. However, trying to do this returns the error "When providing vpc options you need to provide a subnet for each AZ you are using".

### Reproduction Steps

```python
vpc = ec2.Vpc.from_vpc_attributes(
    self,
    "Vpc",
    vpc_id=vpc_id,
    availability_zones=availability_zones, # A list of availability zones, e.g. ["eu-central-1a", "eu-central-1b"]
    private_subnet_ids=subnet_ids, # Ids of two private subnets in here, each of them in a different AZ
)

# I expect this to select two private subnets, since each subnet is in a different AZ
subnets = vpc.select_subnets(subnet_type=ec2.SubnetType.PRIVATE, one_per_az=True)

es_domain = es.Domain(
    self,
    "Domain",
    domain_name="whatever",
    version=es.ElasticsearchVersion.V7_8,
    capacity=es.CapacityConfig(
        data_nodes=2, data_node_instance_type="t3.small.elasticsearch"
    ),
    encryption_at_rest=es.EncryptionAtRestOptions(enabled=True),
    # Domain should be in two AZ
    zone_awareness=es.ZoneAwarenessConfig(
        enabled=True, availability_zone_count=2
    ),
    ebs=es.EbsOptions(volume_size=20),
    vpc=vpc,
    vpc_subnets=subnets.subnets,
)
```
### What did you expect to happen?

The Elasticsearch domain should be correctly deployed, in two AZ, each in a different private subnet of the VPC.

### What actually happened?

`cdk deploy` fails with an error:

```
jsii.errors.JavaScriptError:
  Error: When providing vpc options you need to provide a subnet for each AZ you are using
      at new Domain (/tmp/jsii-kernel-a0boXt/node_modules/@aws-cdk/aws-elasticsearch/lib/domain.js:502:19)
      at /tmp/tmpwgx3qau7/lib/program.js:8367:58
      at Kernel._wrapSandboxCode (/tmp/tmpwgx3qau7/lib/program.js:8795:24)
      at Kernel._create (/tmp/tmpwgx3qau7/lib/program.js:8367:34)
      at Kernel.create (/tmp/tmpwgx3qau7/lib/program.js:8108:29)
      at KernelHost.processRequest (/tmp/tmpwgx3qau7/lib/program.js:9692:36)
      at KernelHost.run (/tmp/tmpwgx3qau7/lib/program.js:9655:22)
      at Immediate._onImmediate (/tmp/tmpwgx3qau7/lib/program.js:9656:46)
      at processImmediate (internal/timers.js:462:21)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "app.py", line 21, in <module>
    CdkStack(app, f"{global_env_name}-messageIngesterStack")
  File "/mnt/c/workspace/elasticsearch-message-ingester/cdk/venv/lib/python3.8/site-packages/jsii/_runtime.py", line 83, in __call__
    inst = super().__call__(*args, **kwargs)
  File "/mnt/c/workspace/elasticsearch-message-ingester/cdk/cdk/cdk_stack.py", line 80, in __init__
    es_domain = es.Domain(
  File "/mnt/c/workspace/elasticsearch-message-ingester/cdk/venv/lib/python3.8/site-packages/jsii/_runtime.py", line 83, in __call__
    inst = super().__call__(*args, **kwargs)
  File "/mnt/c/workspace/elasticsearch-message-ingester/cdk/venv/lib/python3.8/site-packages/aws_cdk/aws_elasticsearch/__init__.py", line 4582, in __init__
    jsii.create(Domain, self, [scope, id, props])
  File "/mnt/c/workspace/elasticsearch-message-ingester/cdk/venv/lib/python3.8/site-packages/jsii/_kernel/__init__.py", line 275, in create
    response = self.provider.create(
  File "/mnt/c/workspace/elasticsearch-message-ingester/cdk/venv/lib/python3.8/site-packages/jsii/_kernel/providers/process.py", line 344, in create
    return self._process.send(request, CreateResponse)
  File "/mnt/c/workspace/elasticsearch-message-ingester/cdk/venv/lib/python3.8/site-packages/jsii/_kernel/providers/process.py", line 326, in send
    raise JSIIError(resp.error) from JavaScriptError(resp.stack)
jsii.errors.JSIIError: When providing vpc options you need to provide a subnet for each AZ you are using
Subprocess exited with error 1
```

### Environment

  - **CDK CLI Version  : 1.109.0 (build c647e38)**
  - **Framework Version: 1.109.0**
  - **Node.js Version: v14.17.0** 
  - **OS               : Ubuntu (Windows WSL)**
  - **Language (Version): Python 3.8.5** 

### Other

A theory for why this could happen is that the domain selects availability zones in the current region, e.g. `eu-central-1a`, and `eu-central-1c`, but the subnets are in `eu-central-1a` and `eu-central-1b` respectively. In that case, the domain should infer which AZ to use by the provided subnets.

I also tried not specifying `vpc_subnets`, which according to other issues or stackoverflow questions worked at some point in the past (I assume the domain just figured out which subnets to use automatically?), but that crashes with the same error.

--- 

This is :bug: Bug Report

**Comment by LinusPhoenix** [comment]
I also don't think the subnet selection is to blame, since even specifying `vpc_subnets=vpc.private_subnets` crashes with the same error.

**Comment by LinusPhoenix** [comment]
I'm an idiot, the output when running deploy even warns me about this:
```
[Warning at /foo] fromVpcAttributes: 'subnetIds' is a list token: the imported VPC will not work with constructs that require a list of subnets at synthesis time. Use 'Vpc.fromLookup()' or 'Fn.importListValue' instead.
```
