### ISSUE TITLE
(aws-stepfunctions): `JsiiException: Maximum call stack size exceeded` for nested Parallel states with catch

### ISSUE THREAD

**Issue by clumsy** [aws/aws-cdk#16180]
When nesting a Parallel state into another state where both have catch I get: `JsiiException: Maximum call stack size exceeded`

### Reproduction Steps

Attaching sample repo

### What did you expect to happen?

Should work without issues as for non-nested Parallel states.

### What actually happened?

```
software.amazon.jsii.JsiiException: Maximum call stack size exceeded
RangeError: Maximum call stack size exceeded
    at StateGraph.registerContainedState (/private/var/folders/2c/d5xy040n10176t2qzhm_d6kh0000gn/T/jsii-kernel-DRKxjS/node_modules/@aws-cdk/aws-stepfunctions/lib/state-graph.js:130:18)
    at StateGraph.registerContainedState (/private/var/folders/2c/d5xy040n10176t2qzhm_d6kh0000gn/T/jsii-kernel-DRKxjS/node_modules/@aws-cdk/aws-stepfunctions/lib/state-graph.js:131:29)
    at StateGraph.registerContainedState (/private/var/folders/2c/d5xy040n10176t2qzhm_d6kh0000gn/T/jsii-kernel-DRKxjS/node_modules/@aws-cdk/aws-stepfunctions/lib/state-graph.js:131:29)
    at StateGraph.registerContainedState (/private/var/folders/2c/d5xy040n10176t2qzhm_d6kh0000gn/T/jsii-kernel-DRKxjS/node_modules/@aws-cdk/aws-stepfunctions/lib/state-graph.js:131:29)
    at StateGraph.registerContainedState (/private/var/folders/2c/d5xy040n10176t2qzhm_d6kh0000gn/T/jsii-kernel-DRKxjS/node_modules/@aws-cdk/aws-stepfunctions/lib/state-graph.js:131:29)
    at StateGraph.registerContainedState (/private/var/folders/2c/d5xy040n10176t2qzhm_d6kh0000gn/T/jsii-kernel-DRKxjS/node_modules/@aws-cdk/aws-stepfunctions/lib/state-graph.js:131:29)
    at StateGraph.registerContainedState (/private/var/folders/2c/d5xy040n10176t2qzhm_d6kh0000gn/T/jsii-kernel-DRKxjS/node_modules/@aws-cdk/aws-stepfunctions/lib/state-graph.js:131:29)
    at StateGraph.registerContainedState (/private/var/folders/2c/d5xy040n10176t2qzhm_d6kh0000gn/T/jsii-kernel-DRKxjS/node_modules/@aws-cdk/aws-stepfunctions/lib/state-graph.js:131:29)
    at StateGraph.registerContainedState (/private/var/folders/2c/d5xy040n10176t2qzhm_d6kh0000gn/T/jsii-kernel-DRKxjS/node_modules/@aws-cdk/aws-stepfunctions/lib/state-graph.js:131:29)
    at StateGraph.registerContainedState (/private/var/folders/2c/d5xy040n10176t2qzhm_d6kh0000gn/T/jsii-kernel-DRKxjS/node_modules/@aws-cdk/aws-stepfunctions/lib/state-graph.js:131:29)
        at software.amazon.jsii.JsiiRuntime.processErrorResponse(JsiiRuntime.java:124)
        at software.amazon.jsii.JsiiRuntime.requestResponse(JsiiRuntime.java:95)
        at software.amazon.jsii.JsiiClient.callMethod(JsiiClient.java:184)
        at software.amazon.jsii.Kernel.call(Kernel.java:52)
        at software.amazon.awscdk.services.stepfunctions.Parallel.branch(Parallel.java:103)
        at com.myorg.HelloCdkStack.create(HelloCdkStack.java:40)
        at com.myorg.HelloCdkStack.<init>(HelloCdkStack.java:33)
        at com.myorg.HelloCdkStack.<init>(HelloCdkStack.java:27)
        at com.myorg.HelloCdkStackTest.testStack(HelloCdkStackTest.java:20)
```

### Environment

  - **CDK CLI Version  :1.119.0**
  - **Framework Version:**
  - **Node.js Version:**  **16.7.0**
  - **OS               :macOS 11.5.2**
  - **Language (Version):**  **Java**

### Other

See the attached repository that reduces the issue.

--- 

This is :bug: Bug Report

**Comment by clumsy** [comment]
[hello-cdk.zip](https://github.com/aws/aws-cdk/files/7032503/hello-cdk.zip)

**Comment by clumsy** [comment]
I believe the issue happens because of a catch for a task inside Parallel that points to a state outside of the current branch (or even Parallel itself). I think this should not be allowed (right?) in which case this should have been a descriptive runtime exception.
