### ISSUE TITLE
CfnReportDefinition use results in Validation error

### ISSUE THREAD

**Issue by tjirsch** [aws/aws-cdk#16316]
### The Question
Creating a CUR Report with CfnReportDefinition with cdk deploy fails wit Validation error.
What am I doing wrong? 

### Environment

  - **CDK CLI Version:** 1.120.0 (build 6c15150)
  - **Module Version:** 1.120.0
  - **Node.js Version:** v16.3.0
  - **OS:** <!-- OSX BigSur
  - **Language:** Python

### Other information
Stack:
from aws_cdk import core as cdk
from aws_cdk import aws_cur as cur

class RepdefStack(cdk.Stack):
  def __init__(self, scope: cdk.Construct, construct_id: str, **kwargs) -> None:
    super().__init__(scope, construct_id, **kwargs)

    cur.CfnReportDefinition(self,"cur-rep-def",report_name=f"xyz-{self.account}",
                                                      compression="Parquet",
                                                           format="Parquet", 
                                                report_versioning="OVERWRITE_REPORT",
                                                        s3_bucket=f"cur-{self.account}",
                                                        s3_prefix="cur",
                                                        s3_region="eu-central-1",
                                                        time_unit="HOURLY",
                                             additional_artifacts=["ATHENA"],
                                           refresh_closed_reports=False
                                        )

Output of cdk synth:

Resources:
  currepdef:
    Type: AWS::CUR::ReportDefinition
    Properties:
      Compression: Parquet
      Format: Parquet
      RefreshClosedReports: false
      ReportName: xyz-123456789012
      ReportVersioning: OVERWRITE_REPORT
      S3Bucket: cur-123456789012
      S3Prefix: cur
      S3Region: eu-central-1
      TimeUnit: HOURLY
      AdditionalArtifacts:
        - ATHENA
    Metadata:
      aws:cdk:path: RepdefStack/sva-cur-rep
  CDKMetadata:
    Type: AWS::CDK::Metadata
    Properties:
      Analytics: v2:deflate64:H4sIAAAAAAAAEyXKTQqDQAxA4bO4H+PfpsuCHqDoCSRGmopJyWQoZfDugq4efLwGmraGunjOv1jislUZ1Qjy5DNuoVeJbgk99KuMFDUZ0hGuNxlc+FXzgVYWdlY5wuvvb5Wqgwd0xScyl5bEeScY757V2qf9cwAAAA==
    Metadata:
      aws:cdk:path: RepdefStack/CDKMetadata/Default

Output of deploy:
cdk deploy RepdefStack 
RepdefStack: deploying...
RepdefStack: creating CloudFormation changeset...

 ❌  RepdefStack failed: Error [ValidationError]: Template format error: Unrecognized resource types: [AWS::CUR::ReportDefinition]
    at Request.extractError (/usr/local/lib/node_modules/aws-cdk/node_modules/aws-sdk/lib/protocol/query.js:50:29)
    at Request.callListeners (/usr/local/lib/node_modules/aws-cdk/node_modules/aws-sdk/lib/sequential_executor.js:106:20)
    at Request.emit (/usr/local/lib/node_modules/aws-cdk/node_modules/aws-sdk/lib/sequential_executor.js:78:10)
    at Request.emit (/usr/local/lib/node_modules/aws-cdk/node_modules/aws-sdk/lib/request.js:688:14)
    at Request.transition (/usr/local/lib/node_modules/aws-cdk/node_modules/aws-sdk/lib/request.js:22:10)
    at AcceptorStateMachine.runTo (/usr/local/lib/node_modules/aws-cdk/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at /usr/local/lib/node_modules/aws-cdk/node_modules/aws-sdk/lib/state_machine.js:26:10
    at Request.<anonymous> (/usr/local/lib/node_modules/aws-cdk/node_modules/aws-sdk/lib/request.js:38:9)
    at Request.<anonymous> (/usr/local/lib/node_modules/aws-cdk/node_modules/aws-sdk/lib/request.js:690:12)
    at Request.callListeners (/usr/local/lib/node_modules/aws-cdk/node_modules/aws-sdk/lib/sequential_executor.js:116:18) {
  code: 'ValidationError',
  time: 2021-09-01T10:55:38.439Z,
  requestId: '243126ce-68e8-41fa-8457-f85659a575da',
  statusCode: 400,
  retryable: false,
  retryDelay: 175.068329791783
}
Template format error: Unrecognized resource types: [AWS::CUR::ReportDefinition]

Output:
aws cloudformation validate-template --template-body file://RepdefStack.template.json --profile dare

An error occurred (ValidationError) when calling the ValidateTemplate operation: Template format error: Unrecognized resource types: [AWS::CUR::ReportDefinition]

**Comment by tjirsch** [comment]
Stack needs to be deployed in US-EAST-1. Might be worth noting this in documentation.
