### ISSUE TITLE
(aws-codepipeline): Failed on setting account/region

### ISSUE THREAD

**Issue by byongwu** [aws/aws-cdk#16358]
Hi,
When I added in account and region setting in the CDK/CodePipeline's deployment main stack, I got an error.
```
export class MainPipelineStage extends Stage {
  constructor(scope: Construct, id: string, props?: StageProps) {
    super(scope, id, props);

    const stackMain = new CdkMainStack(this, "CdkMainService", {
      env: {  // <=== This is the added property
        account: "123456789012",
        region: "ap-northeast-2",
      },
    });
  }
}
```
This is the error.
```
Users/user/code/cdk/packages/cdk-infra % cdk synth
/Users/user/code/cdk/packages/cdk-infra/node_modules/@aws-cdk/aws-codepipeline/lib/pipeline.ts:862
      throw new Error('Pipeline stack which uses cross-environment actions must have an explicitly set region');
            ^
Error: Pipeline stack which uses cross-environment actions must have an explicitly set region
    at Pipeline.requireRegion (/Users/user/code/cdk/packages/cdk-infra/node_modules/@aws-cdk/aws-codepipeline/lib/pipeline.ts:862:13)
    at Pipeline.ensureReplicationResourcesExistFor (/Users/user/code/cdk/packages/cdk-infra/node_modules/@aws-cdk/aws-codepipeline/lib/pipeline.ts:398:10)
    at Pipeline._attachActionToPipeline (/Users/user/code/cdk/packages/cdk-infra/node_modules/@aws-cdk/aws-codepipeline/lib/pipeline.ts:353:34)
    at Stage.attachActionToPipeline (/Users/user/code/cdk/packages/cdk-infra/node_modules/@aws-cdk/aws-codepipeline/lib/private/stage.ts:155:27)
    at Stage.addAction (/Users/user/code/cdk/packages/cdk-infra/node_modules/@aws-cdk/aws-codepipeline/lib/private/stage.ts:93:29)
    at CdkStage.prepareStage (/Users/user/code/cdk/packages/cdk-infra/node_modules/@aws-cdk/pipelines/lib/legacy/stage.ts:209:26)
    at Object.visit (/Users/user/code/cdk/packages/cdk-infra/node_modules/@aws-cdk/pipelines/lib/legacy/stage.ts:72:46)
    at recurse (/Users/user/code/cdk/packages/cdk-infra/node_modules/@aws-cdk/core/lib/private/synthesis.ts:110:14)
    at recurse (/Users/user/code/cdk/packages/cdk-infra/node_modules/@aws-cdk/core/lib/private/synthesis.ts:125:9)
    at recurse (/Users/user/code/cdk/packages/cdk-infra/node_modules/@aws-cdk/core/lib/private/synthesis.ts:125:9)
Subprocess exited with error 1
```
I tried adding in the default `env: { account: process.env.CDK_DEFAULT_ACCOUNT, region: process.env.CDK_DEFAULT_REGION }` parameter, but still the result was the same failure.

FYI. I had to apply the account/region in the first place because of the following VPC function requiring the explicit account and region set.
```
    const vpcDefault = ec2.Vpc.fromLookup(this, "VPC", {
      vpcName: "vpc1",
    });
```
This is the error message when I didn't set the explicit account and region information.
```
/Users/user/code/cdk/packages/cdk-infra/node_modules/@aws-cdk/core/lib/context-provider.ts:63
      throw new Error(`Cannot retrieve value from context provider ${options.provider} since account/region ` +
            ^
Error: Cannot retrieve value from context provider vpc-provider since account/region are not specified at the stack level. Configure "env" with an account and region when you define your stack.See https://docs.aws.amazon.com/cdk/latest/guide/environments.html for more details.
    at Function.getValue (/Users/user/code/cdk/packages/cdk-infra/node_modules/@aws-cdk/core/lib/context-provider.ts:63:13)
    at Function.fromLookup (/Users/user/code/cdk/packages/cdk-infra/node_modules/@aws-cdk/aws-ec2/lib/vpc.ts:604:66)
    at new StackInfluxDB (/Users/user/code/cdk/packages/cdk-infra/src/stack-InfluxDB.ts:16:32)
    at new CdkMainStack (/Users/user/code/cdk/packages/cdk-infra/src/cdk-main-stack.ts:108:27)
    at new MainPipelineStage (/Users/user/code/cdk/packages/cdk-infra/src/pipeline-stage.ts:15:23)
    at new MainPipelineStack (/Users/user/code/cdk/packages/cdk-infra/src/pipeline-stack.ts:60:20)
    at Object.<anonymous> (/Users/user/code/cdk/packages/cdk-infra/src/cdk-main.ts:15:29)
    at Module._compile (internal/modules/cjs/loader.js:1072:14)
    at Module.m._compile (/Users/user/code/cdk/packages/cdk-infra/node_modules/ts-node/src/index.ts:1310:23)
    at Module._extensions..js (internal/modules/cjs/loader.js:1101:10)
Subprocess exited with error 1
```

### Reproduction Steps

* Enable CDK/CodePipeline as explained in https://cdkworkshop.com/20-typescript/70-advanced-topics/200-pipelines.html
* Apply the account and region as explained above.

### What did you expect to happen?

* I expected setting the account/region working.

### What actually happened?

* I got the error as shown above.

### Environment

  - **CDK CLI Version  :** 1.120.0 (build 6c15150)
  - **Framework Version:** 1.120.0
  - **Node.js Version:**  v14.17.5
  - **OS               :** MacOS
```
ProductName:    Mac OS X
ProductVersion: 10.15.7
BuildVersion:   19H1323
```
  - **Language (Version):**  TypeScript (4.3.4)

### Other

--- 

This is :bug: Bug Report

**Comment by rix0rrr** [comment]
Can you share your code or make a minimal reproducing example?

**Comment by byongwu** [comment]
Hi, @rix0rrr . Unfortunately, I am using CDK + customer's code mixed where it will take a few days work to cleanse/purge the code for public release. However, the code base is https://cdkworkshop.com/20-typescript/70-advanced-topics/200-pipelines.html. Any chance that you have a CDK + CodePipeline example working from your side?

**Comment by rix0rrr** [comment]
Sure. Here's one I use when I need to test something about pipelines: https://github.com/rix0rrr/test-cicd

**Comment by byongwu** [comment]
Just writing something to keep up the issue.
