### ISSUE TITLE
(cdk-cli): cli doesn't respect AWS_PROFILE when `credential_process` is used although `--profile` works

### ISSUE THREAD

**Issue by tobske** [aws/aws-cdk#16372]
Trying to set the profile via the environment variable `AWS_PROFILE` gives me the following error if I do e.g. `cdk diff`:
```sh
> cdk diff                                                            
Stack aStackName
Unable to resolve AWS account to use. It must be either configured when you define your CDK Stack, or through the environment
```

Running `cdk doctor` successfully detects the profile:
```sh
> cdk doctor 
ℹ️ CDK Version: 1.121.0 (build 026cb8f)
ℹ️ AWS environment variables:
  - AWS_PROFILE = xyz
  - AWS_DEFAULT_REGION = eu-central-1
  - AWS_STS_REGIONAL_ENDPOINTS = regional
  - AWS_NODEJS_CONNECTION_REUSE_ENABLED = 1
ℹ️ No CDK environment variables
```

Running the same command in the same environment with the `--profile` flag works:
```sh
> cdk diff --profile "first-admin"
[showing diff]
```

### Reproduction Steps

* Set environment variable `AWS_PROFILE` to `xyz`
* Use following `~/.aws/config`
```
[default]
region = eu-central-1

[profile xyz]
output = json
region = eu-central-1
credential_process = someNiceCommandToGetCredentials
```
* Execute `cdk diff`

### What did you expect to happen?

Execute diff without an error.

### What actually happened?

Receiving 
> Unable to resolve AWS account to use. It must be either configured when you define your CDK Stack, or through the environment

### Environment

  - **CDK CLI Version  :**  1.121.0 (build 026cb8f)
  - **Framework Version:** ?
  - **Node.js Version:** 16.8.0
  - **OS               :** macOS
  - **Language (Version):** Typescript 4.4.2

### Other

--- 

This is :bug: Bug Report

**Comment by rix0rrr** [comment]
That's very odd. Can you run with `-v` and paste the output? The issue is probably around `credential_process`, but we'll have to figure out in what way.

Does it make a difference if you set `AWS_DEFAULT_PROFILE` ?

**Comment by tobske** [comment]
@rix0rrr, here is the output when I run `cdk -v diff':

```
CDK toolkit version: 1.122.0 (build ae09c16)
Command line arguments: {
  _: [ 'diff' ],
  v: 1,
  verbose: 1,
  lookups: true,
  'ignore-errors': false,
  ignoreErrors: false,
  json: false,
  j: false,
  debug: false,
  ec2creds: undefined,
  i: undefined,
  'version-reporting': undefined,
  versionReporting: undefined,
  'path-metadata': true,
  pathMetadata: true,
  'asset-metadata': true,
  assetMetadata: true,
  'role-arn': undefined,
  r: undefined,
  roleArn: undefined,
  staging: true,
  'no-color': false,
  noColor: false,
  'context-lines': 3,
  contextLines: 3,
  strict: false,
  'security-only': false,
  securityOnly: false,
  fail: false,
  '$0': '/opt/homebrew/bin/cdk'
}
cdk.json: {
  "app": "npx ts-node --prefer-ts-exts bin/network-cdk.ts",
  "context": {
    "@aws-cdk/aws-apigateway:usagePlanKeyOrderInsensitiveId": true,
    "@aws-cdk/core:enableStackNameDuplicates": "true",
    "aws-cdk:enableDiffNoFail": "true",
    "@aws-cdk/core:stackRelativeExports": "true",
    "@aws-cdk/aws-ecr-assets:dockerIgnoreSupport": true,
    "@aws-cdk/aws-secretsmanager:parseOwnedSecretName": true,
    "@aws-cdk/aws-kms:defaultKeyPolicies": true,
    "@aws-cdk/aws-s3:grantWriteWithoutAcl": true,
    "@aws-cdk/aws-ecs-patterns:removeDefaultDesiredCount": true,
    "@aws-cdk/aws-rds:lowercaseDbIdentifier": true,
    "@aws-cdk/aws-efs:defaultEncryptionAtRest": true,
    "@aws-cdk/aws-lambda:recognizeVersionProps": true,
    "@aws-cdk/aws-cloudfront:defaultSecurityPolicyTLSv1.2_2021": true
  }
}
cdk.context.json: {
  "availability-zones:account=350815205114:region=eu-central-1": [
    "eu-central-1a",
    "eu-central-1b",
    "eu-central-1c"
  ]
}
merged settings: {
  versionReporting: true,
  pathMetadata: true,
  output: 'cdk.out',
  app: 'npx ts-node --prefer-ts-exts bin/network-cdk.ts',
  context: {
    '@aws-cdk/aws-apigateway:usagePlanKeyOrderInsensitiveId': true,
    '@aws-cdk/core:enableStackNameDuplicates': 'true',
    'aws-cdk:enableDiffNoFail': 'true',
    '@aws-cdk/core:stackRelativeExports': 'true',
    '@aws-cdk/aws-ecr-assets:dockerIgnoreSupport': true,
    '@aws-cdk/aws-secretsmanager:parseOwnedSecretName': true,
    '@aws-cdk/aws-kms:defaultKeyPolicies': true,
    '@aws-cdk/aws-s3:grantWriteWithoutAcl': true,
    '@aws-cdk/aws-ecs-patterns:removeDefaultDesiredCount': true,
    '@aws-cdk/aws-rds:lowercaseDbIdentifier': true,
    '@aws-cdk/aws-efs:defaultEncryptionAtRest': true,
    '@aws-cdk/aws-lambda:recognizeVersionProps': true,
    '@aws-cdk/aws-cloudfront:defaultSecurityPolicyTLSv1.2_2021': true
  },
  debug: false,
  assetMetadata: true,
  toolkitBucket: {},
  staging: true,
  bundlingStacks: [ '*' ],
  lookups: true
}
Determining if we're on an EC2 instance.
Does not look like an EC2 instance.
Toolkit stack: CDKToolkit
Setting "CDK_DEFAULT_REGION" environment variable to eu-central-1
Resolving default credentials
Unable to determine the default AWS account: EnvironmentCredentialsProviderFailure: Variable AMAZON_ACCESS_KEY_ID not set.
    at EnvironmentCredentials.refresh (/opt/homebrew/lib/node_modules/aws-cdk/node_modules/aws-sdk/lib/credentials/environment_credentials.js:79:11)
    at EnvironmentCredentials.get (/opt/homebrew/lib/node_modules/aws-cdk/node_modules/aws-sdk/lib/credentials.js:122:12)
    at resolveNext (/opt/homebrew/lib/node_modules/aws-cdk/node_modules/aws-sdk/lib/credentials/credential_provider_chain.js:125:17)
    at /opt/homebrew/lib/node_modules/aws-cdk/node_modules/aws-sdk/lib/credentials/credential_provider_chain.js:126:13
    at /opt/homebrew/lib/node_modules/aws-cdk/node_modules/aws-sdk/lib/credentials.js:124:23
    at EnvironmentCredentials.refresh (/opt/homebrew/lib/node_modules/aws-cdk/node_modules/aws-sdk/lib/credentials/environment_credentials.js:78:9)
    at EnvironmentCredentials.get (/opt/homebrew/lib/node_modules/aws-cdk/node_modules/aws-sdk/lib/credentials.js:122:12)
    at resolveNext (/opt/homebrew/lib/node_modules/aws-cdk/node_modules/aws-sdk/lib/credentials/credential_provider_chain.js:125:17)
    at CredentialProviderChain.resolve (/opt/homebrew/lib/node_modules/aws-cdk/node_modules/aws-sdk/lib/credentials/credential_provider_chain.js:133:7)
    at /opt/homebrew/lib/node_modules/aws-cdk/node_modules/aws-sdk/lib/util.js:839:26 {
  code: 'EnvironmentCredentialsProviderFailure',
  time: 2021-09-10T10:08:07.794Z
}
context: {
  'availability-zones:account=350815205114:region=eu-central-1': [ 'eu-central-1a', 'eu-central-1b', 'eu-central-1c' ],
  '@aws-cdk/aws-apigateway:usagePlanKeyOrderInsensitiveId': true,
  '@aws-cdk/core:enableStackNameDuplicates': 'true',
  'aws-cdk:enableDiffNoFail': 'true',
  '@aws-cdk/core:stackRelativeExports': 'true',
  '@aws-cdk/aws-ecr-assets:dockerIgnoreSupport': true,
  '@aws-cdk/aws-secretsmanager:parseOwnedSecretName': true,
  '@aws-cdk/aws-kms:defaultKeyPolicies': true,
  '@aws-cdk/aws-s3:grantWriteWithoutAcl': true,
  '@aws-cdk/aws-ecs-patterns:removeDefaultDesiredCount': true,
  '@aws-cdk/aws-rds:lowercaseDbIdentifier': true,
  '@aws-cdk/aws-efs:defaultEncryptionAtRest': true,
  '@aws-cdk/aws-lambda:recognizeVersionProps': true,
  '@aws-cdk/aws-cloudfront:defaultSecurityPolicyTLSv1.2_2021': true,
  'aws:cdk:enable-path-metadata': true,
  'aws:cdk:enable-asset-metadata': true,
  'aws:cdk:version-reporting': true,
  'aws:cdk:bundling-stacks': [ '*' ]
}
outdir: cdk.out
env: {
  CDK_DEFAULT_REGION: 'eu-central-1',
  CDK_CONTEXT_JSON: '{"availability-zones:account=350815205114:region=eu-central-1":["eu-central-1a","eu-central-1b","eu-central-1c"],"@aws-cdk/aws-apigateway:usagePlanKeyOrderInsensitiveId":true,"@aws-cdk/core:enableStackNameDuplicates":"true","aws-cdk:enableDiffNoFail":"true","@aws-cdk/core:stackRelativeExports":"true","@aws-cdk/aws-ecr-assets:dockerIgnoreSupport":true,"@aws-cdk/aws-secretsmanager:parseOwnedSecretName":true,"@aws-cdk/aws-kms:defaultKeyPolicies":true,"@aws-cdk/aws-s3:grantWriteWithoutAcl":true,"@aws-cdk/aws-ecs-patterns:removeDefaultDesiredCount":true,"@aws-cdk/aws-rds:lowercaseDbIdentifier":true,"@aws-cdk/aws-efs:defaultEncryptionAtRest":true,"@aws-cdk/aws-lambda:recognizeVersionProps":true,"@aws-cdk/aws-cloudfront:defaultSecurityPolicyTLSv1.2_2021":true,"aws:cdk:enable-path-metadata":true,"aws:cdk:enable-asset-metadata":true,"aws:cdk:version-reporting":true,"aws:cdk:bundling-stacks":["*"]}',
  CDK_OUTDIR: 'cdk.out',
  CDK_CLI_ASM_VERSION: '14.0.0',
  CDK_CLI_VERSION: '1.122.0'
}
Stack NetworkCdkStack
Reading existing template for stack NetworkCdkStack.
Unable to resolve AWS account to use. It must be either configured when you define your CDK Stack, or through the environment
Error: Unable to resolve AWS account to use. It must be either configured when you define your CDK Stack, or through the environment
    at SdkProvider.resolveEnvironment (/opt/homebrew/lib/node_modules/aws-cdk/lib/api/aws-auth/sdk-provider.ts:208:13)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at CloudFormationDeployments.prepareSdkFor (/opt/homebrew/lib/node_modules/aws-cdk/lib/api/cloudformation-deployments.ts:260:33)
    at CloudFormationDeployments.readCurrentTemplate (/opt/homebrew/lib/node_modules/aws-cdk/lib/api/cloudformation-deployments.ts:182:26)
    at CdkToolkit.diff (/opt/homebrew/lib/node_modules/aws-cdk/lib/cdk-toolkit.ts:104:33)
    at initCommandLine (/opt/homebrew/lib/node_modules/aws-cdk/bin/cdk.ts:225:9)
```

I receive the same error `Variable AMAZON_ACCESS_KEY_ID not set.` when I set `AWS_DEFAULT_PROFILE`.

**Comment by tobske** [comment]
Creating an empty file at `~/.aws/credentials` is a work around for this issue.
