### ISSUE TITLE
(RDS): Replica storage is full but unable to increase by `maxAllocatedStorage`

### ISSUE THREAD

**Issue by tom10271** [aws/aws-cdk#16425]
My master RDS have 15GB and I was inserting data into it and it hits the limit. I have later enabled `maxAllocatedStorage: 100` and I was surprised AWS will increase the allocated storage to 100GB all the way which I don't think this is a good way of scaling tbh. But this is not even the reason why I am reporting.

### Reproduction Steps

Here is my master and replica RDS setting:
```ts
    RDS.POSTGRES = new DatabaseInstance(scope, "Odoo PostgreSQL RDS", {
        databaseName: 'odoo_my_app',
        instanceIdentifier: 'odoo-pg-rds',
        engine: DatabaseInstanceEngine.postgres({
            version: PostgresEngineVersion.VER_12_5,
        }),
        vpc: NETWORKING.VPC,
        removalPolicy: RemovalPolicy.RETAIN,
        deleteAutomatedBackups: true,
        backupRetention: Duration.days(14),
        enablePerformanceInsights: true,
        instanceType: config.rdsInstanceType,
        credentials: Credentials.fromPassword(
            "root",
            SecretValue.ssmSecure(
                'Odoo-RDS-PostgreSQL-master-password',
                config.ssmPasswordVersion
            )
        ),
        // Unlikely to cause problem but check with `cdk diff` first, deleting the whole DB is disastrous
        allocatedStorage: 16,
        maxAllocatedStorage: 100,
        vpcSubnets: {
            subnets: [NETWORKING.PRIVATE_SUBNET_2B, NETWORKING.PRIVATE_SUBNET_2C]
        },
        securityGroups: [SECURITY_GROUP.RDS]
    });

    RDS.POSTGRES_REPLICA = new DatabaseInstanceReadReplica(scope, "Odoo PostgreSQL RDS replica", {
        sourceDatabaseInstance: RDS.POSTGRES,
        instanceType: config.rdsReplicaInstanceType,
        instanceIdentifier: 'odoo-pg-rds-replica',
        publiclyAccessible: true,
        vpc: NETWORKING.VPC,
        vpcSubnets: {
            subnets: [
                NETWORKING.PRIVATE_SUBNET_2B, NETWORKING.PRIVATE_SUBNET_2C,
                NETWORKING.PUBLIC_SUBNET_2B, NETWORKING.PUBLIC_SUBNET_2C
            ]
        },
        securityGroups: [
            SECURITY_GROUP.RDS_GOOGLE_DATA_STUDIO_ACCESS,
            SECURITY_GROUP.RDS_STITCH_ACCESS,
            SECURITY_GROUP.RDS_INTERNAL_STAFF_ACCESS,
        ]
    });
```

I was changing the replica storage setting to 
```ts
    RDS.POSTGRES_REPLICA = new DatabaseInstanceReadReplica(scope, "Odoo PostgreSQL RDS replica", {
        sourceDatabaseInstance: RDS.POSTGRES,
        instanceType: config.rdsReplicaInstanceType,
        instanceIdentifier: 'odoo-pg-rds-replica',
        publiclyAccessible: true,
        vpc: NETWORKING.VPC,
        maxAllocatedStorage: 100,
        vpcSubnets: {
            subnets: [
                NETWORKING.PRIVATE_SUBNET_2B, NETWORKING.PRIVATE_SUBNET_2C,
                NETWORKING.PUBLIC_SUBNET_2B, NETWORKING.PUBLIC_SUBNET_2C
            ]
        },
        securityGroups: [
            SECURITY_GROUP.RDS_GOOGLE_DATA_STUDIO_ACCESS,
            SECURITY_GROUP.RDS_STITCH_ACCESS,
            SECURITY_GROUP.RDS_INTERNAL_STAFF_ACCESS,
        ]
    });
```

### What did you expect to happen?
Work and I don't need to wait for minutes.

### What actually happened?
I need to wait for minutes to see the error. I have essentially no idea on what is wrong again that I am sure if I use the AWS panel I can get things done in minutes. CDK is not working smooth and the doc is amazingly unhelpful just like all other documents written by AWS which is long and pointless on solving common issues.

```
4:32:47 PM | UPDATE_FAILED        | AWS::RDS::DBInstance                      | OdooPostgreSQLRDS9F2FE107
Invalid storage size for engine name postgres and storage type gp2: 100 (Service: AmazonRDS; Status Code: 400; Error Code: InvalidParameterCombination; Request ID: 22924124-5a91-43b4-bb22-2e6ed56cbc29; Proxy: null)

	new DatabaseInstance (/odoo-deployment/cdk/node_modules/@aws-cdk/aws-rds/lib/instance.ts:623:22)
	\_ Object.databaseSetup (/odoo-deployment/cdk/src/Database/index.ts:19:20)
	\_ OdooStack.run (/odoo-deployment/cdk/src/odoo-stack.ts:41:9)
	\_ /odoo-deployment/cdk/bin/cdk.ts:8:5


 ❌  OdooStack failed: Error: The stack named OdooStack failed to deploy: UPDATE_ROLLBACK_COMPLETE
    at Object.waitForStackDeploy (/Users/me/.nvm/versions/node/v14.15.1/lib/node_modules/cdk/node_modules/aws-cdk/lib/api/util/cloudformation.ts:307:11)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at Object.deployStack (/Users/me/.nvm/versions/node/v14.15.1/lib/node_modules/cdk/node_modules/aws-cdk/lib/api/deploy-stack.ts:306:26)
    at CdkToolkit.deploy (/Users/me/.nvm/versions/node/v14.15.1/lib/node_modules/cdk/node_modules/aws-cdk/lib/cdk-toolkit.ts:184:24)
    at initCommandLine (/Users/me/.nvm/versions/node/v14.15.1/lib/node_modules/cdk/node_modules/aws-cdk/bin/cdk.ts:218:9)
The stack named OdooStack failed to deploy: UPDATE_ROLLBACK_COMPLETE
```

### Environment

  - **CDK CLI Version  :**
  - **Framework Version:**
  - **Node.js Version:** 
  - **OS               :**
  - **Language (Version):** 

### Other

--- 

This is :bug: Bug Report

**Comment by skinny85** [comment]
Hey @tom10271,

thanks for opening the issue, and apologies for the bad experience.

I'm wondering whether you could be running into https://github.com/aws-cloudformation/cloudformation-coverage-roadmap/issues/430? Perhaps try setting `maxAllocatedStorage` to something a little larger, maybe `105`, and see if that helps?

Thanks,
Adam
