### ISSUE TITLE
(pipelines): Deployment step 'CodeBuildStep(CustomCodeBuild)' is not supported for CodePipeline-backed pipelines

### ISSUE THREAD

**Issue by markusl** [aws/aws-cdk#16435]
We have published a CDK Construct which uses CDK v2.0.0-rc.21 and projen to generate the Construct structure.

However, when using the construct in another CDK v2 (2.0.0-rc.21) application, the following error is generated when running a snapshot test:

```
    Deployment step 'CodeBuildStep(CustomCodeBuild)' is not supported for CodePipeline-backed pipelines

      at CodePipeline.actionFromStep (node_modules/aws-cdk-lib/lib/pipelines/lib/codepipeline/codepipeline.ts:283:15)
      at CodePipeline.actionFromNode (node_modules/aws-cdk-lib/lib/pipelines/lib/codepipeline/codepipeline.ts:240:29)
      at CodePipeline.pipelineStagesAndActionsFromGraph (node_modules/aws-cdk-lib/lib/pipelines/lib/codepipeline/codepipeline.ts:174:46)
      at CodePipeline.doBuildPipeline (node_modules/aws-cdk-lib/lib/pipelines/lib/codepipeline/codepipeline.ts:139:14)
      at CodePipeline.buildPipeline (node_modules/aws-cdk-lib/lib/pipelines/lib/main/pipeline-base.ts:52:14)
      at CodePipeline.buildJustInTime (node_modules/aws-cdk-lib/lib/pipelines/lib/main/pipeline-base.ts:62:18)
      at Object.visit (node_modules/aws-cdk-lib/lib/pipelines/lib/main/pipeline-base.ts:29:50)
      at recurse (node_modules/aws-cdk-lib/lib/core/lib/private/synthesis.ts:104:20)
      at recurse (node_modules/aws-cdk-lib/lib/core/lib/private/synthesis.ts:116:17)
      at recurse (node_modules/aws-cdk-lib/lib/core/lib/private/synthesis.ts:116:17)
```

### What did you expect to happen?

The CDK Construct would be able to produce the CodeBuild step in the pipelines.CodePipeline pipeline.

### Environment

  - **CDK CLI Version  :** 2.0.0-rc.21 (build f35f136)
  - **Framework Version:** 2.0.0-rc.21 (build f35f136)
  - **Node.js Version:** 14
  - **OS               :** macOS
  - **Language (Version):** TypeScript

### Other

--- 

This is :bug: Bug Report

**Comment by rix0rrr** [comment]
You have multiple copies of the pipelines library in your dependency closure

**Comment by markusl** [comment]
As discussed with @rix0rrr, the `aws-cdk-lib` must not be part of `dependencies` of the CDK Construct, but listed in `peerDependencies`.

This can be achieved with `projen` by setting `cdkDependenciesAsDeps` to `false` in `.projenrc.js`:
```ts
  cdkDependencies: [
    'aws-cdk-lib',
  ],
  cdkDependenciesAsDeps: false,
```
