### ISSUE TITLE
(aws-lambda): regionInfo.cloudwatchLambdaInsightsArn is not a function

### ISSUE THREAD

**Issue by PatrikElfstrom** [aws/aws-cdk#16502]
### The Question

Upgraded all @aws-cdk (and the cli) from 1.74.0 to 1.122.0 and @aws-cdk/aws-lambda is triggering this error.

Lambda Insights is not enabled in AWS nor have I defined the insightsVersion property.
But to my understanding of the docs that should not be necessary.

Am I missing some documentation between versions?

### Environment

  - **CDK CLI Version:** 1.122.0
  - **Module Version:** 1.122.0
  - **Node.js Version:** 14.7.6
  - **OS:** Debian (docker node:lts)
  - **Language (Version):** Javascript

### Other information

```
$ cdk bootstrap
/node_modules/@aws-cdk/aws-lambda/lib/lambda-insights.js:46
        const versionExists = region_info_1.RegionInfo.regions.some(regionInfo => regionInfo.cloudwatchLambdaInsightsArn(insightsVersion));
                                                                                             ^
TypeError: regionInfo.cloudwatchLambdaInsightsArn is not a function
    at /node_modules/@aws-cdk/aws-lambda/lib/lambda-insights.js:46:94
    at Array.some (<anonymous>)
    at Function.fromInsightsVersion (/node_modules/@aws-cdk/aws-lambda/lib/lambda-insights.js:46:64)
    at Object.<anonymous> (/node_modules/@aws-cdk/aws-lambda/lib/lambda-insights.js:69:64)
    at Module._compile (internal/modules/cjs/loader.js:1072:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1101:10)
    at Module.load (internal/modules/cjs/loader.js:937:32)
    at Function.Module._load (internal/modules/cjs/loader.js:778:12)
    at Module.require (internal/modules/cjs/loader.js:961:19)
    at require (internal/modules/cjs/helpers.js:92:18)
Subprocess exited with error 1
```
```
const cdk = require('@aws-cdk/core');
const { AppStack } = require('../lib/app-stack');

const app = new cdk.App();
new AppStack(app, 'AppStack', {
  env: {
    region: process.env.AWS_DEFAULT_REGION,
    account: process.env.AWS_ACCOUNT,
  },
});
```
```
class AppStack extends cdk.Stack {
   const authApi = new lambda.Function(this, `${this.serviceId}AuthApi`, {
      runtime: lambda.Runtime.NODEJS_12_X,
      code: lambda.Code.fromAsset(path.join(__dirname, '../src/resources')),
      handler: 'api.auth',
      vpc: vpc,
      vpcSubnets: subnetSelection,
      securityGroups,
      environment: {
        APP_COOKIE_DOMAIN: process.env.APP_COOKIE_DOMAIN,
        APP_URL: process.env.APP_URL,
        STAGE: process.env.STAGE,
      },
    });
}
module.exports = { AppStack };
```

**Comment by JahnKhan** [comment]
python cdk same happened to me, after updating everythin this occured:

```
jsii.errors.JavaScriptError:
  C:\Users\k\AppData\Local\Temp\jsii-kernel-BvALFB\node_modules\@aws-cdk\aws-lambda\lib\lambda-insights.js:46
          const versionExists = region_info_1.RegionInfo.regions.some(regionInfo => regionInfo.cloudwatchLambdaInsightsArn(insightsVersion));
                                                                                               ^

  TypeError: regionInfo.cloudwatchLambdaInsightsArn is not a function
      at C:\Users\k\AppData\Local\Temp\jsii-kernel-BvALFB\node_modules\@aws-cdk\aws-lambda\lib\lambda-insights.js:46:94
      at Array.some (<anonymous>)
      at Function.fromInsightsVersion (C:\Users\k\AppData\Local\Temp\jsii-kernel-BvALFB\node_modules\@aws-cdk\aws-lambda\lib\lambda-insights.js:46:64)
      at Object.<anonymous> (C:\Users\k\AppData\Local\Temp\jsii-kernel-BvALFB\node_modules\@aws-cdk\aws-lambda\lib\lambda-insights.js:69:64)
      at Module._compile (node:internal/modules/cjs/loader:1101:14)
      at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
      at Module.load (node:internal/modules/cjs/loader:981:32)
      at Function.Module._load (node:internal/modules/cjs/loader:822:12)
      at Module.require (node:internal/modules/cjs/loader:1005:19)
      at require (node:internal/modules/cjs/helpers:94:18)

```

**Comment by JahnKhan** [comment]
coud you solve it? i cleared my virtual environment and installed the dependencies new and it worked

**Comment by nija-at** [comment]
@PatrikElfstrom - This method does exist - https://github.com/aws/aws-cdk/blob/124a7a1c20981c72bfdce0c857c87c46c6cb5f51/packages/%40aws-cdk/region-info/lib/region-info.ts#L117

I suspect this might be because your dependencies are not all upgraded. Can you make sure that the dependencies are all up to date, reinstall them and try again?

If you still see this error, you will need to provide a set of steps to reproduce this error.

**Comment by PatrikElfstrom** [comment]
@nija-at @JahnKhan Yes the node modules seemed to have been cached in the cicd. Cleaning the cache solved the issue.
