### ISSUE TITLE
(core): WebIdentityCredentials does not work

### ISSUE THREAD

**Issue by yamatatsu** [aws/aws-cdk#16513]
I use OIDC Provider for aws-cdk credentials as following:
https://awsteele.com/blog/2021/09/15/aws-federation-comes-to-github-actions.html

But I get an error `Unable to determine the default AWS account: Error [ConfigError]: Missing region in config`.

This is similar to #9937. And this case occur in `TokenFileWebIdentityCredentials`.
https://github.com/aws/aws-cdk/blob/master/packages/aws-cdk/lib/api/aws-auth/awscli-compatible.ts#L68

### Reproduction Steps

Use WebIdentityCredentials as following:
https://awsteele.com/blog/2021/09/15/aws-federation-comes-to-github-actions.html

My Reproduction repository is [here](https://github.com/yamatatsu/github-actions-id-sample)

### What did you expect to happen?

I expect to be able to use web identity in cdk.

### What actually happened?

A instance of SDK has no region.

I recieve following error:
```
Unable to determine the default AWS account: Error [ConfigError]: Missing region in config
    at Request.optInRegionalEndpoint (/home/runner/work/github-actions-id-sample/github-actions-id-sample/node_modules/aws-sdk/lib/services/sts.js:75:30)
    at Request.callListeners (/home/runner/work/github-actions-id-sample/github-actions-id-sample/node_modules/aws-sdk/lib/sequential_executor.js:106:20)
    at Request.emit (/home/runner/work/github-actions-id-sample/github-actions-id-sample/node_modules/aws-sdk/lib/sequential_executor.js:78:10)
    at Request.emit (/home/runner/work/github-actions-id-sample/github-actions-id-sample/node_modules/aws-sdk/lib/request.js:688:14)
    at Request.transition (/home/runner/work/github-actions-id-sample/github-actions-id-sample/node_modules/aws-sdk/lib/request.js:22:10)
    at AcceptorStateMachine.runTo (/home/runner/work/github-actions-id-sample/github-actions-id-sample/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at Request.runTo (/home/runner/work/github-actions-id-sample/github-actions-id-sample/node_modules/aws-sdk/lib/request.js:408:15)
    at Request.send (/home/runner/work/github-actions-id-sample/github-actions-id-sample/node_modules/aws-sdk/lib/request.js:372:10)
    at features.constructor.makeUnauthenticatedRequest (/home/runner/work/github-actions-id-sample/github-actions-id-sample/node_modules/aws-sdk/lib/service.js:230:31)
    at features.constructor.assumeRoleWithWebIdentity (/home/runner/work/github-actions-id-sample/github-actions-id-sample/node_modules/aws-sdk/lib/services/sts.js:44:17) {
  code: 'ConfigError',
  time: 2021-09-16T12:02:44.650Z
}
```

A result of GitHub Actions is [here](https://github.com/yamatatsu/github-actions-id-sample/runs/3620946858?check_suite_focus=true)

### Environment

  - **CDK CLI Version  :** v2.0.0-rc.21
  - **Framework Version:** v2.0.0-rc.21
  - **Node.js Version:** v14.17.6 
  - **OS               :** Ubuntu 20.04.3 LTS
  - **Language (Version):** cli 

### Other

--- 

This is :bug: Bug Report

**Comment by yamatatsu** [comment]
I solve it by setting environment variables `AWS_REGION` instead of `AWS_DEFAULT_REGION`.

Sorry!
