### ISSUE TITLE
(@aws-cdk/aws-autoscaling-hooktargets): Cannot use Lambda function as lifecycle hook notification target in JavaScript, but can in Python

### ISSUE THREAD

**Issue by wolf-allywilson** [aws/aws-cdk#16510]
Porting a stack from Python to Javascript, encountered an issue whereby I can't use a lambda as a lifecycle hook notification target.

Always get this error:

> Error: The supplied lambda Function object must be an instance of Construct

### Reproduction Steps
```
const lambda = require('@aws-cdk/aws-lambda');
const autoscaling = require('@aws-cdk/aws-autoscaling');

    var lambdaRole = new iam.Role(
      this,
      "lambdaIAMrole",
      {
        assumedBy: new iam.ServicePrincipal('lambda.amazonaws.com'),
        description: 'IAM role for lambda',
        managedPolicies: [iam.ManagedPolicy.fromAwsManagedPolicyName('AmazonSSMFullAccess')],
        roleName: 'IAMforLambda'
      }
    )

    const myLambda = new lambda.Function(
      this,
      "LambdaFunctionID",
      {
        runtime: Runtime.PYTHON_3_8,
        code: Code.fromAsset("lambda"),
        timeout: Duration.seconds(900),
        handler: 'lambdaFile.lambda_handler',
        role: lambdaRole
      }
    );

    const lfHook = new hooks.FunctionHook({fn:myLambda});

    var ASG = new autoscaling.AutoScalingGroup(
      this,
      "testASGID",
      {...}
      )

    ASG.addLifecycleHook("testLH",
    {
      notificationTarget: lfHook
    })

```
### What did you expect to happen?

In my Python code I have a lifecycle hook calling a lambda function (i.e. I run a Lambda when terminating an instance in my ASG) and it works fine, no errors.

### What actually happened?

CDK refuses to synth the code. Throws up this error: 

> /Users/myUsername/myRepos/myStack/node_modules/@aws-cdk/aws-sns-subscriptions/lib/lambda.js:34
>             throw new Error('The supplied lambda Function object must be an instance of Construct');
>             ^
> 
> Error: The supplied lambda Function object must be an instance of Construct
>     at LambdaSubscription.bind (/Users/myUsername/myRepos/myStack/node_modules/@aws-cdk/aws-sns-subscriptions/lib/lambda.js:34:19)
>     at Topic.addSubscription (/Users/myUsername/myRepos/myStack/node_modules/@aws-cdk/aws-sns/lib/topic-base.js:22:49)
>     at FunctionHook.bind (/Users/myUsername/myRepos/myStack/node_modules/@aws-cdk/aws-autoscaling-hooktargets/lib/lambda-hook.js:41:15)
>     at new LifecycleHook (/Users/myUsername/myRepos/myStack/node_modules/@aws-cdk/aws-autoscaling/lib/lifecycle-hook.js:25:54)
>     at AutoScalingGroup.addLifecycleHook (/Users/myUsername/myRepos/myStack/node_modules/@aws-cdk/aws-autoscaling/lib/auto-scaling-group.js:266:16)
>     at new LdapBuildAsgJsStack (/Users/myUsername/myRepos/myStack/lib/myStack-stack.js:295:9)
>     at Object.<anonymous> (/Users/myUsername/myRepos/myStack/bin/myStack.js:7:1)
>     at Module._compile (internal/modules/cjs/loader.js:1068:30)
>     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1097:10)
>     at Module.load (internal/modules/cjs/loader.js:933:32)
> Subprocess exited with error 1

### Environment

  - **CDK CLI Version  :** 1.122.0 (build ae09c16)
  - **Framework Version:**
  - **Node.js Version:** v14.17.0
  - **OS               :** macOS 11.5
  - **Language (Version):** Javascript 1.7 (I think), Python 3.8 and 3.9 (for the working code)

--- 

This is :bug: Bug Report

**Comment by nija-at** [comment]
`Function` is a sub-type of `Construct` so you should not get this error.

I suspect you have different versions of CDK modules in your dependency closure. Can you ensure that all CDK modules in your `node_modules` is the same version?

**Comment by wolf-allywilson** [comment]
Spun up a blank Debian 11 VM, only installed the CDK, node, npm and the aws-cdk modules and still got the error. 

Output of `npm list`:

> new_project@0.1.0 /mnt/hgfs/debian11share/newProject
> ├── @aws-cdk/assert@1.124.0
> ├── @aws-cdk/aws-autoscaling-hooktargets@1.124.0
> ├── @aws-cdk/aws-autoscaling@1.124.0
> ├── @aws-cdk/aws-ec2@1.124.0
> ├── @aws-cdk/aws-elasticloadbalancingv2@1.124.0
> ├── @aws-cdk/aws-iam@1.124.0
> ├── @aws-cdk/aws-lambda@1.124.0
> ├── @aws-cdk/aws-route53@1.124.0
> ├── @aws-cdk/core@1.124.0
> ├── aws-cdk@1.124.0
> └── jest@26.6.3

**Comment by wolf-allywilson** [comment]
Just to confirm, in that same VM with minimal installed, I get the error when `cdk synth`ing the following code:

```
const cdk = require('@aws-cdk/core');
const autoscaling = require("@aws-cdk/aws-autoscaling");
const lambda = require("@aws-cdk/aws-lambda");
const hooks = require("@aws-cdk/aws-autoscaling-hooktargets");
const iam = require("@aws-cdk/aws-iam");
const ec2 = require("@aws-cdk/aws-ec2");

class SomeProjectStack extends cdk.Stack {
  constructor(scope, id, props) {
    super(scope, id, props);

    const terminateLambda = new lambda.Function(this, "myLambda", {
      runtime: lambda.Runtime.PYTHON_3_8,
      code: lambda.Code.fromInline("print('hello world')"),
      timeout: cdk.Duration.seconds(900),
    });

    const vpc = ec2.Vpc.fromLookup(this, "myVPC", { vpcId: "vpc-123456789" });

    const ASG = new autoscaling.AutoScalingGroup(this, "myASG", {
      vpc,
      instanceType: new ec2.InstanceType("t2.small"),
      machineImage: new ec2.AmazonLinuxImage(),
    });

    const lfHook = new hooks.FunctionHook({fn: terminateLambda});

    const newHook = new autoscaling.LifecycleHook(
      this,
      "myLifecycleHook",
      {
        autoScalingGroupName: ASG,
        lifecycleTransition: autoscaling.LifecycleTransition.INSTANCE_TERMINATING,
        notificationTarget: lfHook,
        heartbeatTimeout: cdk.Duration.seconds(600),
        defaultResult: autoscaling.DefaultResult.CONTINUE,
        autoScalingGroup: ASG,
        lifecycleHookName: 'lifecycleHookName',
      },
    );

    ASG.addLifecycleHook("addLifecycleHook", {newHook})
  }
}

module.exports = { SomeProjectStack }
```
