### ISSUE TITLE
@aws-cdk/aws-codepipeline-actions: Parameter not usable in actionName

### ISSUE THREAD

**Issue by rafiwicht** [aws/aws-cdk#16568]
Cloudformation parameters are not usable in action names.

### Reproduction Steps

```typescript
const projectNameToken = new CfnParameter(this, 'projectName', {
    type: 'String',
});
const sourceAction = new CodeCommitSourceAction({
    actionName: `${projectNameToken.valueAsString}-pipeline-source`,
    repository: repo,
    output: artifact
});
```

### What did you expect to happen?

The parameter is used for the creation of the actionName.

### What actually happened?

Unrecognized token key error:
```
/home/xxxx/cdk/cdk-pipeline/node_modules/@aws-cdk/core/lib/private/token-map.ts:165
      throw new Error(`Unrecognized token key: ${key}`);
            ^
Error: Resolution error: Resolution error: Resolution error: Resolution error: Unrecognized token key: TOKEN189.
Object creation stack:
  at Execute again with CDK_DEBUG=true to capture stack traces.
Object creation stack:
  at Execute again with CDK_DEBUG=true to capture stack traces..
    at TokenMap.lookupToken (/home/xxxx/cdk/cdk-pipeline/node_modules/@aws-cdk/core/lib/private/token-map.ts:165:13)
    at TokenString.split (/home/xxxx/cdk/cdk-pipeline/node_modules/@aws-cdk/core/lib/private/encoding.ts:55:20)
    at resolve (/home/xxxx/cdk/cdk-pipeline/node_modules/@aws-cdk/core/lib/private/resolve.ts:169:29)
    at Object.resolve (/home/xxxx/cdk/cdk-pipeline/node_modules/@aws-cdk/core/lib/private/resolve.ts:119:77)
    at resolve (/home/xxxx/cdk/cdk-pipeline/node_modules/@aws-cdk/core/lib/private/resolve.ts:230:47)
    at Object.resolve (/home/xxxx/cdk/cdk-pipeline/node_modules/@aws-cdk/core/lib/private/resolve.ts:119:77)
    at /home/xxxx/cdk/cdk-pipeline/node_modules/@aws-cdk/core/lib/private/resolve.ts:200:45
    at Array.map (<anonymous>)
    at resolve (/home/xxxx/cdk/cdk-pipeline/node_modules/@aws-cdk/core/lib/private/resolve.ts:200:8)
    at Object.resolve (/home/xxxx/cdk/cdk-pipeline/node_modules/@aws-cdk/core/lib/private/resolve.ts:119:77)
```

### Environment

  - **CDK CLI Version  :** 1.123.0 (build fad855e)
  - **Framework Version:**
  - **Node.js Version:** v14.17.6
  - **OS               :** Ubuntu 20.04 (WSL2)
  - **Language (Version):** TypeScript (4.4.3)

--- 

This is :bug: Bug Report

**Comment by skinny85** [comment]
Hey @rafiwicht,

thanks for opening the issue. This is a known limitation, unfortunately. To get around it, you can use [Escape hatches](https://docs.aws.amazon.com/cdk/latest/guide/cfn_layer.html):

```ts
        const sourceOutput = new codepipeline.Artifact();
        const pipeline = new codepipeline.Pipeline(this, 'Pipeline', {
            stages: [
                {
                    stageName: 'Source',
                    actions: [new codepipeline_actions.CodeCommitSourceAction({
                        actionName: 'pipeline-source',
                        repository: codecommit.Repository.fromRepositoryName(this, 'Repo', 'my-repo'),
                        output: sourceOutput,
                    })],
                },
                {
                    stageName: 'Build',
                    actions: [new codepipeline_actions.CodeBuildAction({
                        actionName: 'CodeBuild',
                        project: codebuild.Project.fromProjectName(this, 'Project', 'my-project'),
                        input: sourceOutput,
                    })],
                },
            ],
        });

        const cfnParameter = new cdk.CfnParameter(this, 'Param');
        const cfnPipeline = pipeline.node.defaultChild as codepipeline.CfnPipeline;
        cfnPipeline.addPropertyOverride('Stages.0.Actions.0.Name', `${cfnParameter.valueAsString}-pipeline-source`);
```

Thanks,
Adam

**Comment by rafiwicht** [comment]
Hi Adam

Thanks for the solution. It works like a charm. Is there an easy way to implement it? Maybe I can look into it and make a contribution.

Best regards,

Rafael

**Comment by skinny85** [comment]
I feel like this might be tricky to implement in the generic case.

How would you feel about opening a Pull Request adding the above solution to our docs?

**Comment by rafiwicht** [comment]
Yes, maybe the documentation is the fastest solution. I will look into it next week.
