### ISSUE TITLE
(aws-elasticloadbalancingv2-targets): Adding a Lambda target to ALB in another stack results in a cyclic reference error

### ISSUE THREAD

**Issue by HashNuke** [aws/aws-cdk#16744]
Using a Lambda target to an ALB in another stack results in a cyclic reference error when running `cdk diff`. 

### Reproduction Steps

Scenario below:
* AppCommonStack - contains resources (like ALB) that are shared between different stacks.
* The HelloAppStack - creates resources that are specific to a single app's stack.

```typescript
import * as cdk from '@aws-cdk/core'
import * as ec2 from '@aws-cdk/aws-ec2'
import * as lambda from '@aws-cdk/aws-lambda';
import * as elbv2 from '@aws-cdk/aws-elasticloadbalancingv2'
import * as targets from '@aws-cdk/aws-elasticloadbalancingv2-targets';

class AppCommonStack extends cdk.Stack {
  public vpc: ec2.Vpc
  public alb: elbv2.ApplicationLoadBalancer

  constructor(scope: cdk.App, id: string, props?: cdk.StackProps) {
    super(scope, id, props)

    this.vpc = new ec2.Vpc(this, "AppCommonVpc")
    this.alb = new elbv2.ApplicationLoadBalancer(this, 'AppCommonLB', {
      vpc: this.vpc,
      internetFacing: true
    })
    new cdk.CfnOutput(this, "AlbDnsName", {value: this.alb.loadBalancerDnsName})
  }
}

interface HelloAppStackProps extends cdk.StackProps {
  alb: elbv2.ApplicationLoadBalancer
}

class HelloAppStack extends cdk.Stack {
  constructor(scope: cdk.App, id: string, props: HelloAppStackProps) {
    super(scope, id, props)

    const hellofn = new lambda.Function(this, "HelloAppFunction", {
      runtime: lambda.Runtime.NODEJS_12_X,
      handler: "index.handler",
      code: lambda.Code.fromInline(`
        exports.handler = function(event, ctx, cb) {
          return {
            statusCode: 200,
            headers: {
              "Content-Type": "text/html"
            },
            body: "Hello World"
          }
        }
      `)
    });

    const listener = props.alb.addListener(`HelloLambdaListener`, { port: 80 });

    listener.addTargets(`HelloAppFunctionTarget`, {
      targets: [new targets.LambdaTarget(hellofn)]
    })
  }
}

const app = new cdk.App()
const commonStack = new AppCommonStack(app, 'AppCommonStack')
const helloAppStack = new HelloAppStack(app, 'HelloAppStack', {alb: commonStack.alb})
helloAppStack.addDependency(commonStack)
```

### What did you expect to happen?

* ALB created for AppCommonStack
* Listener and Lambda target for the ALB created as a part of HelloAppStack

### What actually happened?

```
$ npx cdk diff AppCommonStack HelloAppStack

/Users/hashnuke/projects/cdk-tryouts/node_modules/@aws-cdk/core/lib/stack.ts:400
      throw new Error(`'${target.node.path}' depends on '${this.node.path}' (${cycle.join(', ')}). Adding this dependency (${reason}) would create a cyclic reference.`);
            ^
Error: 'HelloAppStack' depends on 'AppCommonStack' (dependency added using stack.addDependency()). Adding this dependency ("AppCommonStack/AppCommonLB/HelloLambdaListener/HelloAppFunctionTargetGroup/Resource" depends on "HelloAppStack/HelloAppFunction/InvokeServicePrincipal(elasticloadbalancing.amazonaws.com)") would create a cyclic reference.
    at AppCommonStack._addAssemblyDependency (/Users/hashnuke/projects/cdk-tryouts/node_modules/@aws-cdk/core/lib/stack.ts:400:13)
    at Object.addDependency (/Users/hashnuke/projects/cdk-tryouts/node_modules/@aws-cdk/core/lib/deps.ts:52:20)
    at CfnTargetGroup.addDependsOn (/Users/hashnuke/projects/cdk-tryouts/node_modules/@aws-cdk/core/lib/cfn-resource.ts:163:5)
    at Object.prepareApp (/Users/hashnuke/projects/cdk-tryouts/node_modules/@aws-cdk/core/lib/private/prepare-app.ts:26:16)
    at Object.synthesize (/Users/hashnuke/projects/cdk-tryouts/node_modules/@aws-cdk/core/lib/private/synthesis.ts:24:3)
    at App.synth (/Users/hashnuke/projects/cdk-tryouts/node_modules/@aws-cdk/core/lib/stage.ts:94:23)
    at process.<anonymous> (/Users/hashnuke/projects/cdk-tryouts/node_modules/@aws-cdk/core/lib/app.ts:64:45)
    at Object.onceWrapper (events.js:520:26)
    at process.emit (events.js:400:28)
    at process.emit (domain.js:470:12)
```

### Environment

  - **CDK CLI Version:** `1.125.0`
  - **Framework Version:**
  - **Node.js Version:** `14.17.5`
  - **OS**: Mac
  - **Language (Version):** TypeScript (4.4.2)

### Other info

I tried moving all the resources under one stack and it worked as expected (the resources get created). The above mentioned cyclic dependency issue only occurs when the lambda is added as a target of an ALB created in another stack.

I looked up the source code of the `aws-elasticloadbalancingv2-targets` package. The line in [lambda-target.ts](https://github.com/aws/aws-cdk/blob/master/packages/%40aws-cdk/aws-elasticloadbalancingv2-targets/lib/lambda-target.ts#L22) seems to be causing this error.

--- 

This is :bug: Bug Report

**Comment by leonk-sportsbet** [comment]
I'm having the same issue when explicitly defining dependencies between lambda stack and HttpsListener stack.
Commenting it out solves the issue:
`appStackInst.node.addDependency(albStackInst);`

Can this be resolved - following best practices and adding explicit stack dependencies causes cdk to crap itself :(

```ts
const appStackInst = new AppStack(
  app,
  appStackName,
  {
    stackName: appStackName,
    // 👇 Setting global tags at the stack level
    tags: JSON.parse(JSON.stringify(buildConfig.Tags)),
    env: {
      account: process.env.CDK_DEFAULT_ACCOUNT,
      region: process.env.CDK_DEFAULT_REGION,
    },
  },
  buildConfig,
  {
    albadminHttpsListener: albStackInst.createdAlbs["adm"].httpListener,
    albcustHttpsListener: albStackInst.createdAlbs["cst"].httpsListener,
  },
  {
    lambdaRole1:
      iamStackInst.roles[
        `mt-rar-dev-ap-southeast-2-lambdaRole1${
          buildConfig.BranchName !== "" ? `-${buildConfig.BranchName}` : ""
        }`
      ],
  },
  {
    lambdaSg1: securityStackInst.CreatedSecurityGroups["lambda"],
  },
  {
    dynamoDbTableName: dynamoDbStackInst.dynamoDbTable,
  }
);
// Set dependency of appStackInst on albStackInst, iamStackInst, securityStackInst, dynamoDbStackInst
// commenting out this line due to - `https://github.com/aws/aws-cdk/issues/16744`
// appStackInst.node.addDependency(albStackInst);
appStackInst.node.addDependency(iamStackInst);
appStackInst.node.addDependency(securityStackInst);
appStackInst.node.addDependency(dynamoDbStackInst);
```

Will produce an error, unless `appStackInst.node.addDependency(albStackInst);` is commented out (`https://github.com/aws/aws-cdk/issues/16744`):

```
Error: 'mt-rar-dev-blue-alb-testbr' depends on 'mt-rar-dev-blue-app-testbr' ({mt-rar-dev-blue-alb-testbr/alb-adm/HttpListener-adm/HTTPSListenerTargetsGroup/Resource}.addDependency({mt-rar-dev-blue-app-testbr/createFn-adm/Invoke2UTWxhlfyqbT5FTn--5jvgbLgj+FfJwzswGk55DU1H--Y=}), {mt-rar-dev-blue-alb-testbr/alb-cst/HttpsListener-cst/HTTPSListenerTargetsGroup/Resource}.addDependency({mt-rar-dev-blue-app-testbr/createFn-cst/Invoke2UTWxhlfyqbT5FTn--5jvgbLgj+FfJwzswGk55DU1H--Y=})). Adding this dependency ({mt-rar-dev-blue-app-testbr/createFn-adm/Resource}.addDependency({mt-rar-dev-blue-alb-testbr/albDefaultSecurityGroup-adm/Resource})) would create a cyclic reference.
    at AppStack._addAssemblyDependency (/Users/leonk/repos/PD/other_repos/martech/martech-requestarunner-service/infrastructure/node_modules/aws-cdk-lib/core/lib/stack.js:1:10330)
    at operateOnDependency (/Users/leonk/repos/PD/other_repos/martech/martech-requestarunner-service/infrastructure/node_modules/aws-cdk-lib/core/lib/deps.js:1:1649)
    at addDependency (/Users/leonk/repos/PD/other_repos/martech/martech-requestarunner-service/infrastructure/node_modules/aws-cdk-lib/core/lib/deps.js:1:321)
    at CfnFunction.addDependency (/Users/leonk/repos/PD/other_repos/martech/martech-requestarunner-service/infrastructure/node_modules/aws-cdk-lib/core/lib/cfn-resource.js:1:4305)
    at prepareApp (/Users/leonk/repos/PD/other_repos/martech/martech-requestarunner-service/infrastructure/node_modules/aws-cdk-lib/core/lib/private/prepare-app.js:1:536)
    at synthesize (/Users/leonk/repos/PD/other_repos/martech/martech-requestarunner-service/infrastructure/node_modules/aws-cdk-lib/core/lib/private/synthesis.js:1:922)
    at App.synth (/Users/leonk/repos/PD/other_repos/martech/martech-requestarunner-service/infrastructure/node_modules/aws-cdk-lib/core/lib/stage.js:1:2052)
    at process.<anonymous> (/Users/leonk/repos/PD/other_repos/martech/martech-requestarunner-service/infrastructure/node_modules/aws-cdk-lib/core/lib/app.js:1:1448)
    at Object.onceWrapper (node:events:628:26)
    at process.emit (node:events:513:28)
```
