### ISSUE TITLE
(aws-dynamodb): Cannot replicate DynamoDB table with BootstraplessSynthetizer

### ISSUE THREAD

**Issue by feliperugai** [aws/aws-cdk#16754]
### The Question
I'm developing a CDK script which needs to use BootstraplessSynthesizer:

```js
const stackProps = {
  synthesizer: new BootstraplessSynthesizer(app),
};
```

I'm creating an API Gateway, some Lambdas and one DynamoDB table.
The thing is that I have set it as Global Tables, so I can add replicas to other AWS regions.
According to the [docs][1] I should add `replicationRegions` to my table creation object, so I did as follows:

```js
  const table = new Table(this, 'table', {
      partitionKey: {
        name: 'partitionKey',
        type: AttributeType.STRING,
      },
      sortKey: { name: 'sortKey', type: AttributeType.STRING },
      tableName: 'table-name',
      removalPolicy: RemovalPolicy.DESTROY,
      billingMode: BillingMode.PAY_PER_REQUEST,
      stream: StreamViewType.NEW_AND_OLD_IMAGES,
      replicationRegions: regions,
    });
```

When trying to `cdk synth` my app, I got the following error:

```
throw new Error('Cannot add assets to a Stack that uses the BootstraplessSynthesizer');
^
Error: Cannot add assets to a Stack that uses the BootstraplessSynthesizer
at BootstraplessSynthesizer.addFileAsset (\node_modules\@aws-cdk\core\lib\stack-synthesizers\bootstrapless-synthesizer.ts:26:11)
at NestedStackSynthesizer.addFileAsset (\node_modules\@aws-cdk\aws-dynamodb\node_modules\@aws-cdk\core\lib\stack-synthesizers\nested.ts:30:34)
at new Asset (\node_modules\@aws-cdk\aws-lambda\node_modules\@aws-cdk\aws-s3-assets\lib\asset.ts:145:40)
at AssetCode.bind (\node_modules\@aws-cdk\aws-lambda\lib\code.ts:180:20)
at new Function (\node_modules\@aws-cdk\aws-lambda\lib\function.ts:327:29)
at new ReplicaProvider (\node_modules\@aws-cdk\aws-dynamodb\lib\replica-provider.ts:55:27)
at Function.getOrCreate (\node_modules\@aws-cdk\aws-dynamodb\lib\replica-provider.ts:31:63)
at Table.createReplicaTables (\node_modules\@aws-cdk\aws-dynamodb\lib\table.ts:1039:38)
at new Table (\node_modules\@aws-cdk\aws-dynamodb\lib\table.ts:722:12)
at new Database (\intrastructure\stacks\Database.ts:37:19)
Subprocess exited with error 1
```

I got confused why it would try to upload an asset, and went to the CDK source code, and found [this line][2] of code, which is explicitly importing an asset to my stack:

```js
const code = lambda.Code.fromAsset(path.join(__dirname, 'replica-handler'));
```

So, how can I create a DynamoDB replica while using BootstraplessSynthesizer?

  [1]: https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-dynamodb.Table.html#replicationregions
  [2]: https://github.com/aws/aws-cdk/blob/5e8e7abc16ba392f325ee4bbae05ebfee20f043f/packages/%40aws-cdk/aws-dynamodb/lib/replica-provider.ts#L52

### Environment

  - **CDK CLI Version:** 1.116.0 (build d04661d)
  - **Module Version:** 1.97.0
  - **Node.js Version:** v14.17.4
  - **OS:** Windows 10
  - **Language (Version):** Typescript

**Comment by peterwoodworth** [comment]
There isn't a way to use the `replicationRegions` prop while also using the bootstrapless synthesizer, due to the line of code you pointed out! Looks like you'll need a workaround here.

I don't know of a workaround off the top of my head, but I can look into this.

**Comment by peterwoodworth** [comment]
So, `DynamoDB::Table`s are limited and don't support replication on their own. CloudFormation released a construct called the `GlobalTable` which allows you to replicate tables natively in CloudFormation without needing to create a custom resource. I recommend migrating to the `GlobalTable` if possible, especially if you're actively deciding to use replicas. View [this article](https://acloudguru.com/blog/engineering/you-should-always-use-dynamodb-global-tables-now) for more information

If you want to still use the regular `Table`, you would have to create the infrastructure for the custom resource on your own. Essentially, do what the CDK code does when you fill in the replicationRegions prop. However unlike the CDK, you'd need to use inline code for the lambdas.

Ping me if you have any additional questions 😄

**Comment by feliperugai** [comment]
> So, `DynamoDB::Table`s are limited and don't support replication on their own. CloudFormation released a construct called the `GlobalTable` which allows you to replicate tables natively in CloudFormation without needing to create a custom resource. I recommend migrating to the `GlobalTable` if possible, especially if you're actively deciding to use replicas. View [this article](https://acloudguru.com/blog/engineering/you-should-always-use-dynamodb-global-tables-now) for more information
> 
> If you want to still use the regular `Table`, you would have to create the infrastructure for the custom resource on your own. Essentially, do what the CDK code does when you fill in the replicationRegions prop. However unlike the CDK, you'd need to use inline code for the lambdas.
> 
> Ping me if you have any additional questions 😄

Thanks for the clarification!
Should I use GlobalTables (as it seems to be [deprecated](https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-dynamodb-global.GlobalTable.html))?

**Comment by peterwoodworth** [comment]
We don't have an L2 construct which uses the CloudFormation `GlobalTable` yet. To make use of the CloudFormation `GlobalTable` use the [L1 CfnGlobalTable construct](https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-dynamodb.CfnGlobalTable.html
