### ISSUE TITLE
@aws-cdk/aws_elasticloadbalancingv2-CfnTargetGroup:: Not able to add *target_group_attributes*

### ISSUE THREAD

**Issue by ns-ajith** [aws/aws-cdk#16816]
### General Issue

target_group_attributes create/update fails 

### The Question

I'm trying to create a Loadbalancer for already existing instances, with `CfnTargetGroup` and enabling the `target_group_attributes`(https://docs.aws.amazon.com/cdk/api/latest/python/aws_cdk.aws_elasticloadbalancingv2/CfnTargetGroup.html#aws_cdk.aws_elasticloadbalancingv2.CfnTargetGroup.target_group_attributes). 
```
        target_groups = lbv2.CfnTargetGroup (self, "target_group",
                                            name = config.target_groups.name + environment,
                                            port = config.target_groups.port,
                                            protocol = config.target_groups.protocol,
                                            protocol_version = config.target_groups.protocol_version,
                                            target_type = "instance",
                                            targets = [targets],
                                            vpc_id=vpc.vpc_id,
                                            health_check_enabled = True,
                                            health_check_interval_seconds = 5,
                                            matcher = {"HttpCode" :"200"} ,        # Validate the LB health 
                                            target_group_attributes = [{"Key":"stickiness.enabled" , "Value" : "true"}]
```

This is the error I'm getting, not sure what am I missing here 

```

Failed resources:
 10:36:25 AM | UPDATE_FAILED        | AWS::ElasticLoadBalancingV2::TargetGroup  | target_group (targetgroup) 1 validation error detected: Value null at 'attributes' failed to satisfy constraint: Member must not be null (Service: AmazonElasticLoadBalancing; Status Code: 400; Error Code: ValidationError; Request ID: 1407283e-78b2-46bb-a3bf-d63f15a59f25; Proxy: null)
	/private/var/folders/19/mv6krhlx2lndqhy71b88zhxc0000gn/T/tmpq9vlba49/lib/program.js:8367:58
	\_ Kernel._wrapSandboxCode (/private/var/folders/19/mv6krhlx2lndqhy71b88zhxc0000gn/T/tmpq9vlba49/lib/program.js:8795:24)
	\_ Kernel._create (/private/var/folders/19/mv6krhlx2lndqhy71b88zhxc0000gn/T/tmpq9vlba49/lib/program.js:8367:34)
	\_ Kernel.create (/private/var/folders/19/mv6krhlx2lndqhy71b88zhxc0000gn/T/tmpq9vlba49/lib/program.js:8108:29)
	\_ KernelHost.processRequest (/private/var/folders/19/mv6krhlx2lndqhy71b88zhxc0000gn/T/tmpq9vlba49/lib/program.js:9692:36)
	\_ KernelHost.run (/private/var/folders/19/mv6krhlx2lndqhy71b88zhxc0000gn/T/tmpq9vlba49/lib/program.js:9655:22)
	\_ Immediate._onImmediate (/private/var/folders/19/mv6krhlx2lndqhy71b88zhxc0000gn/T/tmpq9vlba49/lib/program.js:9656:46)
	\_ processImmediate (node:internal/timers:464:21)

 ❌  EC2Stackdevelopment failed: Error: The stack named EC2Stackdevelopment failed to deploy: UPDATE_ROLLBACK_COMPLETE
    at Object.waitForStackDeploy (/usr/local/lib/node_modules/aws-cdk/lib/api/util/cloudformation.ts:307:11)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at prepareAndExecuteChangeSet (/usr/local/lib/node_modules/aws-cdk/lib/api/deploy-stack.ts:352:26)
    at CdkToolkit.deploy (/usr/local/lib/node_modules/aws-cdk/lib/cdk-toolkit.ts:189:24)
    at initCommandLine (/usr/local/lib/node_modules/aws-cdk/bin/cdk.ts:225:9)
The stack named EC2Stackdevelopment failed to deploy: UPDATE_ROLLBACK_COMPLETE
Error: The stack named EC2Stackdevelopment failed to deploy: UPDATE_ROLLBACK_COMPLETE
    at Object.waitForStackDeploy (/usr/local/lib/node_modules/aws-cdk/lib/api/util/cloudformation.ts:307:11)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at prepareAndExecuteChangeSet (/usr/local/lib/node_modules/aws-cdk/lib/api/deploy-stack.ts:352:26)
    at CdkToolkit.deploy (/usr/local/lib/node_modules/aws-cdk/lib/cdk-toolkit.ts:189:24)
```

### CDK CLI Version

1.126.0 (build f004e1a)

### OS

mac

### Language

Python

### Language Version

Python 3.9.7

### Other information

If I enable all of them 
```
target_group_attributes = [{"Key":"stickiness.enabled" , "Value" : "true"},{"Key":"stickiness.type" , "Value" : "lb_cookie"},{"Key":"slow_start.duration_seconds" , "Value" : "0"},{"Key":"stickiness.lb_cookie.duration_seconds" , "Value" : "86400"},{"Key":"load_balancing.algorithm.type" , "Value" : "round_robin"}]
```
I'm getting below error 
```
 9:47:57 AM | CREATE_FAILED        | AWS::ElasticLoadBalancingV2::TargetGroup  | targetgroup
Property TargetGroupAttributes contains duplicate values.

```

There is no duplicate value i can find in them

**Comment by peterwoodworth** [comment]
`Key` and `Value` need to be lowercase here, or else synth will output an empty object for the targetGroupAttributes prop. Changing to `key` and `value` should work fine 😄

**Comment by peterwoodworth** [comment]
## Examples
```ts
elbv2.CfnTargetGroup(self, "group",
    target_group_attributes = [{"Key":"stickiness.enabled" , "Value" : "true"}]
)
```
will result in
```yaml
Properties:
  TargetGroupAttributes:
  - {}
```
---
```ts
elbv2.CfnTargetGroup(self, "group",
    target_group_attributes = [{"Key":"stickiness.enabled" , "value" : "true"}]
)
```
will result in 
```yaml
Properties:
  TargetGroupAttributes:
    - Value: "true"
```
---
```ts
elbv2.CfnTargetGroup(self, "group",
    target_group_attributes = [{"key":"stickiness.enabled" , "value" : "true"}]
)
```
will result in
```yaml
Properties:
  TargetGroupAttributes:
    - Key: stickiness.enabled
      Value: "true"
```
