### ISSUE TITLE
(codepipeline): Should Codedeploy App/Group be defined along with Pipeline or Imported?

### ISSUE THREAD

**Issue by kornicameister** [aws/aws-cdk#16860]
### General Issue

Where should one define CodeDeploy Application/Group>?

### The Question

Hello, this is more or less a very generic question and/or looking for guidence.
I am trying to figure out how to write a pipeline that so that:

- pipeline is define in regionA
- application is deployed in potentially different region/account, for the sake of converstaion, let's say regionB

My application is EC2 based so naturally I am looking at `codepipeline_action.CodeDeployServerDeployAction` construct to be put into the pipeline that requires me to supply both `ServerApplication` and `ServerDeploymentGroup`. 

I've tried (its more or less pseudocode):
```python
        deployment_stage = pipeline.add_stage('deployment')
        api_codedeploy_group_name = pipeline.stack_output(
            api_stage.api_deployment_group_name,
        )
        api_codedeploy_app_name = pipeline.stack_output(
            api_stage.api_deployment_application_name,
        )
        deployment_group = cd.serverdeploymentgroup.from_server_deployment_group_attributes(
            self,
            'apideploymentgroup',
            deployment_group_name=api_codedeploy_group_name,
            application=cd.serverapplication.from_server_application_name(
                self,
                'apideploymentapp',
                server_application_name=api_codedeploy_app_name,
            ),
        )
        deployment_stage.add_actions(
            cpa.codedeployserverdeployaction(
                action='rollingupdate',
                deployment_group=deployment_group,
            ),
        )
```

Naturally I assumed to go with `stack_output` method to obtain references to outputs from a application stack deployed in regionB. That however failed with:

```sh
jsii.errors.JavaScriptError:
  Error: Expected a string, got {"$jsii.byref":"@aws-cdk/pipelines.StackOutput@10156"}
      at Object.deserialize (/private/var/folders/23/m0xp04h13tl7ht3bx69jgfvc0000gn/T/tmp6vkikhnn/lib/program.js:9080:31)
      at Kernel._toSandbox (/private/var/folders/23/m0xp04h13tl7ht3bx69jgfvc0000gn/T/tmp6vkikhnn/lib/program.js:8718:69)
      at /private/var/folders/23/m0xp04h13tl7ht3bx69jgfvc0000gn/T/tmp6vkikhnn/lib/program.js:8766:42
      at Array.map (<anonymous>)
      at Kernel._boxUnboxParameters (/private/var/folders/23/m0xp04h13tl7ht3bx69jgfvc0000gn/T/tmp6vkikhnn/lib/program.js:8766:27)
      at Kernel._toSandboxValues (/private/var/folders/23/m0xp04h13tl7ht3bx69jgfvc0000gn/T/tmp6vkikhnn/lib/program.js:8752:29)
      at /private/var/folders/23/m0xp04h13tl7ht3bx69jgfvc0000gn/T/tmp6vkikhnn/lib/program.js:8204:136
      at Kernel._wrapSandboxCode (/private/var/folders/23/m0xp04h13tl7ht3bx69jgfvc0000gn/T/tmp6vkikhnn/lib/program.js:8795:24)
      at /private/var/folders/23/m0xp04h13tl7ht3bx69jgfvc0000gn/T/tmp6vkikhnn/lib/program.js:8204:87
      at Kernel._ensureSync (/private/var/folders/23/m0xp04h13tl7ht3bx69jgfvc0000gn/T/tmp6vkikhnn/lib/program.js:8776:28)

The above exception was the direct cause of the following exception:

```sh
Traceback (most recent call last):
  File "/Users/tomasztrebski/dev-ay/ay-aws/packages/ay/app.py", line 28, in <module>
    ApiPipelineStack(
  File "/Users/tomasztrebski/.pyenv/versions/ay-app/lib/python3.9/site-packages/jsii/_runtime.py", line 86, in __call__
    inst = super().__call__(*args, **kwargs)
  File "/Users/tomasztrebski/dev-ay/ay-aws/packages/ay/ay/api_pipeline_stack.py", line 169, in __init__
    application=cd.ServerApplication.from_server_application_name(
  File "/Users/tomasztrebski/.pyenv/versions/ay-app/lib/python3.9/site-packages/aws_cdk/aws_codedeploy/__init__.py", line 4694, in from_server_application_name
    return typing.cast(IServerApplication, jsii.sinvoke(cls, "fromServerApplicationName", [scope, id, server_application_name]))
  File "/Users/tomasztrebski/.pyenv/versions/ay-app/lib/python3.9/site-packages/jsii/_kernel/__init__.py", line 143, in wrapped
    return _recursize_dereference(kernel, fn(kernel, *args, **kwargs))
  File "/Users/tomasztrebski/.pyenv/versions/ay-app/lib/python3.9/site-packages/jsii/_kernel/__init__.py", line 374, in sinvoke
    response = self.provider.sinvoke(
  File "/Users/tomasztrebski/.pyenv/versions/ay-app/lib/python3.9/site-packages/jsii/_kernel/providers/process.py", line 362, in sinvoke
    return self._process.send(request, InvokeResponse)
  File "/Users/tomasztrebski/.pyenv/versions/ay-app/lib/python3.9/site-packages/jsii/_kernel/providers/process.py", line 326, in send
    raise JSIIError(resp.error) from JavaScriptError(resp.stack)
jsii.errors.JSIIError: Expected a string, got {"$jsii.byref":"@aws-cdk/pipelines.StackOutput@10156"}
```

Ok fair enough. What should I do in such case? I cannot get the server deployment group directly because that's **crossing stage boundaries** error. AFAIR, codedeploy deploys into a region so it has to be deployed along with load balancer and all other part members in regionB, right? Which brings us back to a question: **how do we write pipeline to pick up correct details for codedeploy**

Cheers.

### CDK CLI Version

1.121.0

### Node.js Version

14.17.5

### OS

MacOs BigSur

### Language

Python

### Language Version

3.9.6

**Comment by rix0rrr** [comment]
It looks like you're partly using the [CDK Pipelines](https://docs.aws.amazon.com/cdk/api/latest/docs/pipelines-readme.html) API, and partly using the [CodePipeline API](https://docs.aws.amazon.com/cdk/api/latest/docs/aws-codepipeline-readme.html) directly.

For CDK pipelines, we are assuming everything gets deployed via CloudFormation. I would use an AutoScalingGroup and use [CloudFormation Init](https://docs.aws.amazon.com/cdk/api/latest/docs/aws-autoscaling-readme.html#configuring-instances-using-cloudformation-init) to get software onto your instances.

If you prefer using CodeDeploy, I suppose you  should have 2 different pipelines--one for the infra and one for the code. Seems to me the DeploymentGroups would be created along with your AutoScalingGroup, so they are created in your application stacks. You can combine the pipelines into one but I don't see the point of doing that.
