### ISSUE TITLE
cdk command line is not working 

### ISSUE THREAD

**Issue by nannareshkumar** [aws/aws-cdk#17197]
### What is the problem?

Hi,

Installed cdk in ec2 linux environment just following the documentation using npm. Here is the stack trace of the same

```
[ec2-user@ip-172-31-0-198 ~]$ cdk --version
/usr/lib/node_modules/aws-cdk/bin/cdk.js:26
async function parseCommandLineArguments() {
      ^^^^^^^^

SyntaxError: Unexpected token function
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:549:28)
    at Object.Module._extensions..js (module.js:586:10)
    at Module.load (module.js:494:32)
    at tryModuleLoad (module.js:453:12)
    at Function.Module._load (module.js:445:3)
    at Module.require (module.js:504:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/lib/node_modules/aws-cdk/bin/cdk:2:1)
[ec2-user@ip-172-31-0-198 ~]$ 
```

### Reproduction Steps

Executed below command to install aws-cdk  
```
sudo npm install -g aws-cdk
```
later its failing to display the version instead throws the error 
```
cdk --version
```

### What did you expect to happen?

`cdk --version` has to display the version not the error message.

### What actually happened?

Error is thrown

### CDK CLI Version

v2.0.0-rc.27

### Node.js Version

[ec2-user@ip-172-31-0-198 ~]$ npm -version 3.10.10

### OS

[ec2-user@ip-172-31-0-198 ~]$ uname -r 4.14.246-187.474.amzn2.x86_64

### Language

Typescript

### Other information
```sh
aws  awscliv2.zip  binkubectl  workshop-eventDrivenMicroservices
[ec2-user@ip-172-31-0-198 ~]$ ls
aws  awscliv2.zip  bin  kubectl  workshop-eventDrivenMicroservices
[ec2-user@ip-172-31-0-198 ~]$ uname -r
4.14.246-187.474.amzn2.x86_64
[ec2-user@ip-172-31-0-198 ~]$ cdk --version
/usr/lib/node_modules/aws-cdk/bin/cdk.js:26
async function parseCommandLineArguments() {
      ^^^^^^^^

SyntaxError: Unexpected token function
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:549:28)
    at Object.Module._extensions..js (module.js:586:10)
    at Module.load (module.js:494:32)
    at tryModuleLoad (module.js:453:12)
    at Function.Module._load (module.js:445:3)
    at Module.require (module.js:504:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/lib/node_modules/aws-cdk/bin/cdk:2:1)
[ec2-user@ip-172-31-0-198 ~]$ 
```

**Comment by peterwoodworth** [comment]
Hey @nannareshkumar, I wasn't able to reproduce this. Is there any other context you can share? I see you listed the CLI version as `v2.0.0-rc.27`, how did you install this version of the CLI?

**Comment by nannareshkumar** [comment]
Here is the command used to install CDK: npm install -g aws-cdk

**Comment by peterwoodworth** [comment]
Yeah I have no problem doing that on an EC2 Linux instance, is this error reproducible on your end?
