### ISSUE TITLE
codebuild: failing "Looking up default account ID from STS during SelfMutate"

### ISSUE THREAD

**Issue by erudisch** [aws/aws-cdk#17212]
### What is the problem?

During the SelfMutate pipeline step the command

```
cdk -a . deploy SightglassUpdateStack --require-approval=never --verbose
```

fails with the following error message:

```
Toolkit stack: CDKToolkit
--
149 | Setting "CDK_DEFAULT_REGION" environment variable to eu-west-1
150 | Resolving default credentials
151 | Looking up default account ID from STS
152 | Unable to determine the default AWS account: Error [ERR_SOCKET_CLOSED]: Socket is closed
153 | at Socket._writeGeneric (net.js:777:8)
154 | at Socket._writev (net.js:794:8)
155 | at doWrite (internal/streams/writable.js:375:12)
156 | at clearBuffer (internal/streams/writable.js:521:5)
157 | at Socket.Writable.uncork (internal/streams/writable.js:317:7)
158 | at ClientRequest._flushOutput (_http_outgoing.js:935:10)
159 | at ClientRequest._flush (_http_outgoing.js:904:22)
160 | at onSocketNT (_http_client.js:824:9)
161 | at processTicksAndRejections (internal/process/task_queues.js:83:21) {
162 | code: 'NetworkingError',
163 | region: 'eu-west-1',
164 | hostname: 'sts.eu-west-1.amazonaws.com',
165 | retryable: true,
166 | time: 2021-10-28T10:03:22.685Z,
167 | statusCode: 403
168 | }

...

❌  SightglassUpdateStack failed: Error: Need to perform AWS calls for account XXXX, but no credentials have been configured
--
263 | at SdkProvider.forEnvironment (/usr/local/lib/node_modules/aws-cdk/lib/api/aws-auth/sdk-provider.ts:149:46)
264 | at CloudFormationDeployments.prepareSdkFor (/usr/local/lib/node_modules/aws-cdk/lib/api/cloudformation-deployments.ts:270:22)
265 | at CloudFormationDeployments.deployStack (/usr/local/lib/node_modules/aws-cdk/lib/api/cloudformation-deployments.ts:190:70)
266 | at CdkToolkit.deploy (/usr/local/lib/node_modules/aws-cdk/lib/cdk-toolkit.ts:189:24)
267 | at initCommandLine (/usr/local/lib/node_modules/aws-cdk/bin/cdk.ts:225:9)
268 | Need to perform AWS calls for account XXXX, but no credentials have been configured
269 | Error: Need to perform AWS calls for account XXXX, but no credentials have been configured
270 | at SdkProvider.forEnvironment (/usr/local/lib/node_modules/aws-cdk/lib/api/aws-auth/sdk-provider.ts:149:46)
271 | at CloudFormationDeployments.prepareSdkFor (/usr/local/lib/node_modules/aws-cdk/lib/api/cloudformation-deployments.ts:270:22)
272 | at CloudFormationDeployments.deployStack (/usr/local/lib/node_modules/aws-cdk/lib/api/cloudformation-deployments.ts:190:70)
273 | at CdkToolkit.deploy (/usr/local/lib/node_modules/aws-cdk/lib/cdk-toolkit.ts:189:24)
274 | at initCommandLine (/usr/local/lib/node_modules/aws-cdk/bin/cdk.ts:225:9)


```

### Reproduction Steps

Here is my pipeline setup. I'm using a vpc and a proxy.

```
class SightglassUpdateStack extends cdk.Stack {

    constructor(scope: constructs.Construct, id: string) {
        super(scope, id);

        declare const vpc: ec2.IVpc;

        const codebuildOptions: pipelines.CodeBuildOptions = {
            buildEnvironment: {
                privileged: true,
                buildImage: codebuild.LinuxBuildImage.STANDARD_5_0,
                computeType: codebuild.ComputeType.SMALL,
                environmentVariables: {
                    PROXY_URL: {
                        value: 'some-proxy.com',
                    },
                    NO_PROXY: {
                        value: 'amazonaws.com',
                    },
                },
            },
            vpc,
        };

        const sourceFileSet = pipelines.CodePipelineFileSet.fromArtifact(sourceArtifact);
        const pipeline = new pipelines.CodePipeline(this, 'Pipeline', {
            synth: new pipelines.ShellStep('Synth', {
                input: sourceFileSet,
                commands: [
                    'export HTTPS_PROXY=https://${PROXY_URL}',
                    'npm install -g npm',
                    'cd dir',
                    'npm ci',
                    'npx cdk synth',
                ],
                primaryOutputDirectory: 'dir/cdk.out',
            }),
            codeBuildDefaults: codebuildOptions,
            synthCodeBuildDefaults: codebuildOptions,
            selfMutationCodeBuildDefaults: {
                ...codebuildOptions,
                partialBuildSpec: codebuild.BuildSpec.fromObject({
                    phases: {
                        install: {
                            commands: ['export HTTPS_PROXY=https://${PROXY_URL}'],
                        },
                    },
                }),
            },
        });
    }
}
```

### What did you expect to happen?

The SelfMutate step works and 

```
cdk -a . deploy SightglassUpdateStack --require-approval=never --verbose
```

updates the pipeline

### What actually happened?

```
cdk -a . deploy SightglassUpdateStack --require-approval=never --verbose
```

fails with the error message mentioned above.

### CDK CLI Version

2.0.0-rc.26

### Framework Version

2.0.0-rc.26

### Node.js Version

v14.17.2

### OS

aws/codebuild/standard:5.0

### Language

Typescript

### Language Version

4.4.4

### Other information

This runs on the pipeline, not local.

**Comment by rix0rrr** [comment]
The selfmutate step doesn't know how to use your proxy, because you are not setting `HTTPS_PROXY`. Instead of setting `PROXY_URL`, try setting `HTTPS_PROXY` in the global options for all CodeBuilds:

```ts
        const codebuildOptions: pipelines.CodeBuildOptions = {
            buildEnvironment: {
                privileged: true,
                buildImage: codebuild.LinuxBuildImage.STANDARD_5_0,
                computeType: codebuild.ComputeType.SMALL,
                environmentVariables: {
                    HTTPS_PROXY: {
                        value: 'https://some-proxy.com',
                    },
                    NO_PROXY: {
                        value: 'amazonaws.com',
                    },
                },
            },
            vpc,
        };
```
