### ISSUE TITLE
(events): event_bus_name not working in Python

### ISSUE THREAD

**Issue by pwrmiller** [aws/aws-cdk#17338]
### What is the problem?

Initializing an event bus as follows does not initialize the name as expected when using Python CDK

### Reproduction Steps

Does not set the name:
```python
event_bus = EventBus(
    self,
    "Notifications",
    event_bus_name=f"some-name-prefix-{self.node.try_get_context('SOME_CONTEXT')}-{Aws.STACK_NAME}"
)
```

Sets the name
```python
event_bus = EventBus(
    self,
    "Notifications",
)
event_bus.node.default_child.add_override("Properties.Name", f"some-name-prefix-{self.node.try_get_context('SOME_CONTEXT')}-{Aws.STACK_NAME}")
```

### What did you expect to happen?

I expected the first example to set the event bus name, but it does not (it uses the construct name default). 

### What actually happened?

The `Name` property was set to the default. Note that this breaks when multiple stacks use the same CDK template / region. 

### CDK CLI Version

1.123.0 (build fad855e)

### Node.js Version

v16.7.0

### OS

macOS 11.6

### Language

Python

### Language Version

Python 3.9.4

**Comment by peterwoodworth** [comment]
Hey @pwrmiller - I'm not able to reproduce this. What exactly does the name property get synthed to?

**Comment by pwrmiller** [comment]
This code reproduces the issue. I have tested two versions of CDK (1.123.0 and 1.126.0). It seems the property is not synthesized correctly if it contains any dynamic value. 

```python
#!/usr/bin/env python3
import os

from aws_cdk import core as cdk
from aws_cdk.aws_events import EventBus


class CdkIssue17338Stack(cdk.Stack):
    def __init__(self, scope: cdk.Construct, construct_id: str, **kwargs) -> None:
        super().__init__(scope, construct_id, **kwargs)

        """
        ISSUE: template does not emit an event bus with name matching the event_bus_name provided - the template
               note that thecontext "SOME_CONTEXT" must exist for this to build - pass in in as a flag if required. 
               CDK 1.123.0 (build fad855e), CDK 1.126.0 (build f004e1a) show this issue 
                
          BusId1CC6A51C6:
            Type: AWS::Events::EventBus
            Properties:
                Name: IssueReproBusId1D7C922A
            Metadata:
                aws:cdk:path: IssueRepro/BusId/Resource
        """
        EventBus(
            self,
            "BusId1",
            event_bus_name=f"{self.node.try_get_context('SOME_CONTEXT')}-{cdk.Aws.REGION}"
        )

        """
        WORKAROUND: template emits an event bus as expected 
        
          BusId2EE243C54:
            Type: AWS::Events::EventBus
            Properties:
              Name:
                Fn::Join:
                  - ""
                  - - some_context-
                    - Ref: AWS::Region
            Metadata:
              aws:cdk:path: IssueRepro/BusId2/Resource
        """
        bus2 = EventBus(
            self,
            "BusId2"
        )
        bus2.node.default_child.add_override(
            "Properties.Name",
            f"{self.node.try_get_context('SOME_CONTEXT')}-{cdk.Aws.REGION}"
        )

        """
        Is this as a result of our use of the context in the name property? No - the name is not created properly
        
          BusId3E8AC83F1:
            Type: AWS::Events::EventBus
            Properties:
              Name: some_context
            Metadata:
              aws:cdk:path: IssueRepro/BusId3/Resource
        
        """
        EventBus(
            self,
            "BusId3",
            event_bus_name=f"{self.node.try_get_context('SOME_CONTEXT')}"
        )

        """
        Is this as a result of our use of the another variable in the name? No - the name is not created properly
        
          BusId4CD7CE523:
            Type: AWS::Events::EventBus
            Properties:
              Name: IssueReproBusId4277745BA
            Metadata:
              aws:cdk:path: IssueRepro/BusId4/Resource
        """
        EventBus(
            self,
            "BusId4",
            event_bus_name=f"{cdk.Aws.REGION}"
        )

        """
        Can we use a static value? Is this property ever respected? Yes - the static name is used... 
        
          BusId5B5C574B9:
            Type: AWS::Events::EventBus
            Properties:
              Name: StaticBusName
            Metadata:
              aws:cdk:path: IssueRepro/BusId5/Resource        
        """

        EventBus(
            self,
            "BusId5",
            event_bus_name="StaticBusName"
        )

        # this may be related to CDK issue 17008, 14337 or 17172, where the generated name is overriding the provided
        # name based on some bad decision. Using a static value in event_bus_name works properly. The CDK generated
        # name collides when deploying stacks of different names in the same account/ region, which causes stack
        # deployment to fail. This is probably not the design intent, and should be fixed if possible.


app = cdk.App()
stack = CdkIssue17338Stack(app, "IssueRepro")
app.synth()
```

**Comment by njlynch** [comment]
Ran into this (or something very similar) while working on the aws-cdk-examples repo. In that case, this simple bit of code didn't work:

```python
event_bus = events.EventBus(self, "ICS_IMAGE_CONTENT_BUS")
```

This should create an EventBus with an auto-generated name, but at least on the latest CDK release, it errors out with:

```
jsii.errors.JavaScriptError:
  Error: Resolution error: Supplied properties not correct for "CfnEventBusProps"
    name: required but missing.
      at ValidationResult.assertSuccess (/private/var/folders/cf/ttmfqtv97z13mfktyqcjgq040000gr/T/jsii-kernel-IQnNYk/node_modules/@aws-cdk/core/lib/runtime.js:139:19)
      at cfnEventBusPropsToCloudFormation (/private/var/folders/cf/ttmfqtv97z13mfktyqcjgq040000gr/T/jsii-kernel-IQnNYk/node_modules/@aws-cdk/aws-events/lib/events.generated.js:476:43)
      at CfnEventBus.renderProperties (/private/var/folders/cf/ttmfqtv97z13mfktyqcjgq040000gr/T/jsii-kernel-IQnNYk/node_modules/@aws-cdk/aws-events/lib/events.generated.js:560:16)
      at PostResolveToken.ret.Resources [as processor] (/private/var/folders/cf/ttmfqtv97z13mfktyqcjgq040000gr/T/jsii-kernel-IQnNYk/node_modules/@aws-cdk/core/lib/cfn-resource.js:303:52)
      at PostResolveToken.postProcess (/private/var/folders/cf/ttmfqtv97z13mfktyqcjgq040000gr/T/jsii-kernel-IQnNYk/node_modules/@aws-cdk/core/lib/util.js:81:21)
      at Object.postProcess (/private/var/folders/cf/ttmfqtv97z13mfktyqcjgq040000gr/T/jsii-kernel-IQnNYk/node_modules/@aws-cdk/core/lib/private/resolve.js:59:82)
      at DefaultTokenResolver.resolveToken (/private/var/folders/cf/ttmfqtv97z13mfktyqcjgq040000gr/T/jsii-kernel-IQnNYk/node_modules/@aws-cdk/core/lib/resolvable.js:59:38)
      at resolve (/private/var/folders/cf/ttmfqtv97z13mfktyqcjgq040000gr/T/jsii-kernel-IQnNYk/node_modules/@aws-cdk/core/lib/private/resolve.js:130:55)
      at Object.resolve (/private/var/folders/cf/ttmfqtv97z13mfktyqcjgq040000gr/T/jsii-kernel-IQnNYk/node_modules/@aws-cdk/core/lib/private/resolve.js:57:48)
      at resolve (/private/var/folders/cf/ttmfqtv97z13mfktyqcjgq040000gr/T/jsii-kernel-IQnNYk/node_modules/@aws-cdk/core/lib/private/resolve.js:145:51)
```

I believe the `eventBusProps` method is to blame:

https://github.com/aws/aws-cdk/blob/master/packages/%40aws-cdk/aws-events/lib/event-bus.ts#L242

I think there's something funky happening here with Python+jsii to cause `props` to be defined even with no name passed in.
