### ISSUE TITLE
(aws_stepfunctions): Parallel inside StateMachineFragment causes validation errors

### ISSUE THREAD

**Issue by crh23** [aws/aws-cdk#17354]
### What is the problem?

If a StateMachineFragment contains a Parallel state (with at least one branch) and that StateMachineFragment is used multiple times in a state machine (using StateMachineFragment.prefix_states()), then an error is raised when the stack is synth'd. Example error:
`jsii.errors.JSIIError: State with name 'DoThing1' occurs in both Parallel 'InnerParallelState' branch 1 (Prefix1DoThing1) and Parallel 'InnerParallelState' branch 1 (Prefix2DoThing1). All states must have unique names.`
Judging by the error, it might be some sort of ordering issue, since the prefixes have been correctly applied in the error text.

### Reproduction Steps

```python
    from typing import List
    from aws_cdk import Stack
    from constructs import Construct
    import aws_cdk as cdk
    from aws_cdk import aws_stepfunctions as sfn
    
    
    class SubMachine(sfn.StateMachineFragment):
        def __init__(
            self,
            scope: Construct,
            construct_id: str,
        ) -> None:
            super().__init__(scope, construct_id)
    
            do_thing_1 = sfn.Pass(self, "DoThing1")
            do_thing_2 = sfn.Pass(self, "DoThing2")
    
            parallel_state = sfn.Parallel(self, "InnerParallelState")
    
            chain = parallel_state.branch(do_thing_1).branch(do_thing_2)
            self._start_state: sfn.State = parallel_state
            self._end_states: List[sfn.INextable] = [chain]
    
        @property
        def start_state(self) -> sfn.State:
            return self._start_state
    
        @property
        def end_states(self) -> List[sfn.INextable]:
            return self._end_states
    
    
    class CdkTestStack(Stack):
        def __init__(self, scope: Construct, construct_id: str, **kwargs) -> None:
            super().__init__(scope, construct_id, **kwargs)
    
            chain = (
                SubMachine(self, "SubMachine1").prefix_states("Prefix1")
                .next(SubMachine(self, "SubMachine2").prefix_states("Prefix2"))
            )
    
            machine = sfn.StateMachine(self, "Machine", definition=chain)
    
    
    app = cdk.App()
    CdkTestStack(app, "CdkTestStack")
    
    app.synth()
```

Code is collapsed into one file for the sake of verifying the bug. The bug occurs whether do_thing_2 is included or not (i.e. it doesn't seem to matter how many branches the Parallel state has).

### What did you expect to happen?

The stack to successfully synth, and produce a state machine that runs DoThing1 and DoThing2 in parallel two times.

### What actually happened?

An execption is raised when running `cdk synth` or executing the file with python.
Error message:

```sh
    jsii.errors.JSIIError: State with name 'DoThing1' occurs in both Parallel 'InnerParallelState' branch 1 (Prefix1DoThing1) and Parallel 'InnerParallelState' branch 1 (Prefix2DoThing1). All states must have unique names.
```

### CDK CLI Version

2.0.0-rc.27 (build 435e6f6)

### Framework Version

Tested on 2.0.0rc24 and 2.0.0rc27

### Node.js Version

v14.16.1

### OS

Windows 10

### Language

Python

### Language Version

Python (3.9.7)

### Other information

Stack trace:

```sh
    jsii.errors.JavaScriptError: 
      Error: State with name 'DoThing1' occurs in both Parallel 'InnerParallelState' branch 1 (Prefix1DoThing1) and Parallel 'InnerParallelState' branch 1 (Prefix2DoThing1). All states must have unique names.
          at StateGraph.registerContainedState (C:\Users\chghea\AppData\Local\Temp\jsii-kernel-72It7f\node_modules\aws-cdk-lib\lib\aws-stepfunctions\lib\state-graph.js:136:23)
          at StateGraph.pushContainedStatesUp (C:\Users\chghea\AppData\Local\Temp\jsii-kernel-72It7f\node_modules\aws-cdk-lib\lib\aws-stepfunctions\lib\state-graph.js:146:24)
          at StateGraph.registerSuperGraph (C:\Users\chghea\AppData\Local\Temp\jsii-kernel-72It7f\node_modules\aws-cdk-lib\lib\aws-stepfunctions\lib\state-graph.js:95:14)
          at Parallel.bindToGraph (C:\Users\chghea\AppData\Local\Temp\jsii-kernel-72It7f\node_modules\aws-cdk-lib\lib\aws-stepfunctions\lib\states\state.js:175:20)
          at new StateGraph (C:\Users\chghea\AppData\Local\Temp\jsii-kernel-72It7f\node_modules\aws-cdk-lib\lib\aws-stepfunctions\lib\state-graph.js:54:20)
          at new StateMachine (C:\Users\chghea\AppData\Local\Temp\jsii-kernel-72It7f\node_modules\aws-cdk-lib\lib\aws-stepfunctions\lib\state-machine.js:271:23)
          at C:\Users\chghea\AppData\Local\Temp\tmpjigtgzu4\lib\program.js:8432:58
          at Kernel._wrapSandboxCode (C:\Users\chghea\AppData\Local\Temp\tmpjigtgzu4\lib\program.js:8860:24)
          at Kernel._create (C:\Users\chghea\AppData\Local\Temp\tmpjigtgzu4\lib\program.js:8432:34)
          at Kernel.create (C:\Users\chghea\AppData\Local\Temp\tmpjigtgzu4\lib\program.js:8173:29)
    
    The above exception was the direct cause of the following exception:
    
    Traceback (most recent call last):
      File "C:\Users\chghea\PycharmProjects\CdkTest\cdk_test\cdk_test_stack.py", line 47, in <module>
        CdkTestStack(app, "CdkTestStack")
      File "C:\Users\chghea\PycharmProjects\CdkTest\.venv\lib\site-packages\jsii\_runtime.py", line 86, in __call__
        inst = super().__call__(*args, **kwargs)
      File "C:\Users\chghea\PycharmProjects\CdkTest\cdk_test\cdk_test_stack.py", line 43, in __init__
        machine = sfn.StateMachine(self, "Machine", definition=chain)
      File "C:\Users\chghea\PycharmProjects\CdkTest\.venv\lib\site-packages\jsii\_runtime.py", line 86, in __call__
        inst = super().__call__(*args, **kwargs)
      File "C:\Users\chghea\PycharmProjects\CdkTest\.venv\lib\site-packages\aws_cdk\aws_stepfunctions\__init__.py", line 5595, in __init__
        jsii.create(self.__class__, self, [scope, id, props])
      File "C:\Users\chghea\PycharmProjects\CdkTest\.venv\lib\site-packages\jsii\_kernel\__init__.py", line 290, in create
        response = self.provider.create(
      File "C:\Users\chghea\PycharmProjects\CdkTest\.venv\lib\site-packages\jsii\_kernel\providers\process.py", line 344, in create
        return self._process.send(request, CreateResponse)
      File "C:\Users\chghea\PycharmProjects\CdkTest\.venv\lib\site-packages\jsii\_kernel\providers\process.py", line 326, in send
        raise JSIIError(resp.error) from JavaScriptError(resp.stack)
    jsii.errors.JSIIError: State with name 'DoThing1' occurs in both Parallel 'InnerParallelState' branch 1 (Prefix1DoThing1) and Parallel 'InnerParallelState' branch 1 (Prefix2DoThing1). All states must have unique names.
```

**Comment by kaizen3031593** [comment]
I can reproduce this on my computer. It does seem to be an ordering issue at first glance, investigating further.

**Comment by kaizen3031593** [comment]
The bug is in `parallel.branch()`. 

https://github.com/aws/aws-cdk/blob/845be1012593a9f28457c73c9054bd98ea44d659/packages/%40aws-cdk/aws-stepfunctions/lib/states/parallel.ts#L114-L120

It creates a new `StateGraph` before the `prefixStates` method is called, so the prefixes are not appended. The incorrect stateIds are then bubbled up into the main state machine, which will see stateIds without prefixes and fail.
