### ISSUE TITLE
aws-msk: addUser does not work in Typescript

### ISSUE THREAD

**Issue by bauerjan93** [aws/aws-cdk#17425]
### What is the problem?

addUser to a MSK cluster is in Typescript not possible.

### Reproduction Steps

```ts
        const msk_key = new kms.Key(this, 'kafkaKey')
        
        const cluster = new msk.Cluster(this, "MSKCluster", {
            vpc,
            clusterName: "KafkaCluster",
            vpcSubnets: subnetsSelection,
            securityGroups: [mskSecurityGroup],
            kafkaVersion: msk.KafkaVersion.V2_8_0,
            encryptionInTransit: {
                enableInCluster: true,
                clientBroker: msk.ClientBrokerEncryption.TLS,

            },
            clientAuthentication: msk.ClientAuthentication.sasl({
                scram: true,
                key: msk_key
            }),
        });

        const kafkaUserAndPassword = new secretsmanager.Secret(this, 'AmazonMSK_kafkaUser', {
            generateSecretString: {
                secretStringTemplate: JSON.stringify({ username: 'kafkaUser',  }),
                generateStringKey: 'password',
                includeSpace: false,
                excludeNumbers: true,
                excludePunctuation: true,
                passwordLength: 10,
            },
            secretName: 'AmazonMSK_kafkaUser',
            encryptionKey: msk_key
        });

        const clusterUser = 'kafkaUser'
        cluster.addUser(clusterUser)
```
### What did you expect to happen?

Add the User with the secret from secretmanager to the Cluster.

### What actually happened?

```sh
/Users/user/Documents/Projects/DFL/workspace_bmf/stats/cdk/node_modules/@aws-cdk/aws-msk/lib/cluster.ts:558
      throw Error(
            ^
Error: Cannot create users if an authentication KMS key has not been created/provided.
    at Cluster.addUser (/Users/bauerja/Documents/Projects/DFL/workspace_bmf/stats/cdk/node_modules/@aws-cdk/aws-msk/lib/cluster.ts:558:13)
    at new KafkaStack (/Users/bauerja/Documents/Projects/DFL/workspace_bmf/stats/cdk/lib/kafka_stack.ts:93:17)
    at Object.<anonymous> (/Users/bauerja/Documents/Projects/DFL/workspace_bmf/stats/cdk/bin/cdk.ts:11:1)
    at Module._compile (node:internal/modules/cjs/loader:1109:14)
    at Module.m._compile (/Users/bauerja/Documents/Projects/DFL/workspace_bmf/stats/cdk/node_modules/ts-node/src/index.ts:1056:23)
    at Module._extensions..js (node:internal/modules/cjs/loader:1138:10)
    at Object.require.extensions.<computed> [as .ts] (/Users/bauerja/Documents/Projects/DFL/workspace_bmf/stats/cdk/node_modules/ts-node/src/index.ts:1059:12)
    at Module.load (node:internal/modules/cjs/loader:989:32)
    at Function.Module._load (node:internal/modules/cjs/loader:829:14)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:76:12)
Subprocess exited with error 1

```

### CDK CLI Version

1.130.0

### Node.js Version

v16.3.0

### OS

10.15.7

### Language

Typescript

**Comment by otaviomacedo** [comment]
Hi, @bauerjan93

This is the expected behavior (although I agree that the error message is not very helpful). When you set `scram` to `true`, you should not pass any key and, instead, let the CDK create one for you. Then, when you `addUser`, you should also let the CDK generate the secret with the correct properties, including the name with a prefix "AmazonMSK_".
