### ISSUE TITLE
(@aws-cdk/aws-ec2 | @aws-cdk/aws-elasticache  ): Lambda Cannot connect to Elasticache

### ISSUE THREAD

**Issue by IIsijola** [aws/aws-cdk#17465]
### General Issue

Cannot  connect Lambda Deployed in VPC to redis cluster. 

### The Question

For the past few days, I've been trying to replicate our existing AWS VPC using aws-cdk(typescript) and I've found connecting to Redis from a nodejs lambda function difficult. I've followed the standard tutorials on creating a new VPC, setting up the private/public/isolated subnets and deploying the services to their respective subnets.

The code I am using to try to achieve this is the following:

```
import { NodejsFunction } from "@aws-cdk/aws-lambda-nodejs";
import * as elasticache from "@aws-cdk/aws-elasticache";
import * as apiGateway from "@aws-cdk/aws-apigateway";
import * as rds from "@aws-cdk/aws-rds";
import * as iam from "@aws-cdk/aws-iam";
import * as ec2 from "@aws-cdk/aws-ec2";
import * as cdk from "@aws-cdk/core";
import * as path from "path";
import * as dotenv from "dotenv";

const some_service_path =
  "/some/service/path";

const env = dotenv.config({
  path: path.join(some_service_path, "env", ".development.env"),
});

export class TestStack extends cdk.Stack {
  constructor(scope: cdk.App, id: string, props?: cdk.StackProps) {
    super(scope, id, props);

    const vpc = new ec2.Vpc(this, "VPC", {
      subnetConfiguration: [
        {
          cidrMask: 24,
          name: "ingress",
          subnetType: ec2.SubnetType.PUBLIC,
        },
        {
          cidrMask: 24,
          name: "application",
          subnetType: ec2.SubnetType.PRIVATE_WITH_NAT,
        },
        {
          cidrMask: 28,
          name: "rds",
          subnetType: ec2.SubnetType.PRIVATE_ISOLATED,
        },
      ],
    });


    const rdsSubnetIds = vpc.selectSubnets({
      subnetGroupName: "rds",
    }).subnetIds;


    const redisClusterSubnetGroup = new elasticache.CfnSubnetGroup(
      this,
      "RedisClusterPrivateSubnetGroup",
      {
        subnetIds: rdsSubnetIds,
        cacheSubnetGroupName: "cluster-subnet",
        description: "Sandboxed redis cluster",
      }
    );

    const redisReplicationGroup = new elasticache.CfnReplicationGroup(
      this,
      "company-redis-replication-sandbox",
      {
        replicasPerNodeGroup: 2,
        numNodeGroups: 3,
        cacheSubnetGroupName: redisClusterSubnetGroup.cacheSubnetGroupName,
        replicationGroupDescription: "company Redis replication group",
        replicationGroupId: "company-redis-replication-group",
        securityGroupIds: [vpc.vpcDefaultSecurityGroup],
        authToken: "authtoken",
        cacheNodeType: "cache.t2.micro",
        transitEncryptionEnabled: true,
        atRestEncryptionEnabled: true,
        multiAzEnabled: true,
        engine: "redis",
      }
    );
    redisReplicationGroup.addDependsOn(redisClusterSubnetGroup);

    const entry = path.join(__dirname, "service", "handler.ts");


    const { subnets: applicationSubnet } = vpc.selectSubnets({
      subnetGroupName: "application",
    });

    const someServiceLambda = new NodejsFunction(this, "some-service", {
      runtime: lambda.Runtime.NODEJS_14_X,
      vpcSubnets: { subnets: applicationSubnet },
      entry: entry,
      handler: "graphqlHandler",
      environment: {
        ...env.parsed,
        REDIS_HOST: redisReplicationGroup.attrConfigurationEndPointAddress,
        REDIS_PORT: redisReplicationGroup.attrConfigurationEndPointPort,
        REDIS_PASSWORD: "authtoken",
        REDIS_MODE: "cluster",
        REDIS_USE_TLS: "true",
      },
      vpc,
    });

    new apiGateway.LambdaRestApi(this, "someServiceEndpoint", {
      handler: someServiceLambda,
    });
  }
}

```

The service is a ApolloGQL application that's reliant on the node module IORedis. When I access the lambda function from the browser, the GraphQL playground loads correcctly; however, when I try to run a mutation that connects to the Redis Cluster, I get the following IORedis error in cloudwatch:

```
ERROR   [ioredis] Unhandled error event: ClusterAllFailedError: Failed to refresh slots cache.
    at tryNode (/var/task/index.js:88946:27)
    at /var/task/index.js:88963:15
    at Timeout.<anonymous> (/var/task/index.js:89178:20)
    at Timeout.run (/var/task/index.js:84969:20)
    at listOnTimeout (internal/timers.js:559:11)
    at processTimers (internal/timers.js:500:7)

```

I fixed  the issue: stupidly I wasn't configuring the correct security groups

### CDK CLI Version

1.131.0 (build 7560c79)

### Framework Version

1.129.0

### Node.js Version

v12.20.0

### OS

MacOs

### Language

Typescript

### Language Version

3.9.10

**Comment by Alireza2018** [comment]
Hi,
How did you solve the security group configuration? I have the same issue and Redis connection is getting timed out. I tried to set up an inbound rule for the Redis security group that allows connections on port 6379 from the lambda function's security group. But that didn't help.

**Comment by lunadis** [comment]
> Hi, How did you solve the security group configuration? I have the same issue and Redis connection is getting timed out. I tried to set up an inbound rule for the Redis security group that allows connections on port 6379 from the lambda function's security group. But that didn't help.

I gotch the same issue! How do you fixed?
