### ISSUE TITLE
(aws-iot-actions): Unable to bind two TopicRule  with the same action of a lambda function

### ISSUE THREAD

**Issue by aritzg** [aws/aws-cdk#17508]
### What is the problem?

cdk synth throws when binding  TopicRule to same LambdaFunctionAction

```
throw new Error(`There is already a Construct with name '${childName}' in ${typeName}${name.length > 0 ? ' [' + name + ']' : ''}`);
            ^
Error: There is already a Construct with name '**invokedByAwsIotRule**' in Function [fn-lambda]
    at Node.addChild ./node_modules/constructs/src/construct.ts:381:13)
    at new Node (./node_modules/constructs/src/construct.ts:58:22)
    at new ConstructNode (./node_modules/@aws-cdk/core/lib/construct-compat.ts:184:24)
```

Same error happens if more than one TopicRule is bind to function in any way.
For example in:

- "actions" attr of new iot.TopicRule
- rule.addAction(callLambdaFunc);
- callLambdaFunc.bind(rule);

### Reproduction Steps

```ts
const fnLambdaFunc = new lambda.Function(this, 'fn-lambda', {
      code: lambda.Code.fromAsset('resources/fn-lambda/target/lambda-0.0.1-SNAPSHOT.jar'),
      handler: 'com.fn.lambda.Lambda',
      runtime: lambda.Runtime.JAVA_11,
      timeout: cdk.Duration.seconds(30),
    });


const callLambdaFunc  = new actions.LambdaFunctionAction(fnLambdaFunc);
const a  = new iot.TopicRule(this, 'AppRule', {
      topicRuleName: 'AppRule', 
      sql: iot.IotSql.fromStringAsVer20160323("SELECT * as payload, topic() as topic FROM '+/+/app' "),
      actions: [callLambdaFunc],
    });

const b  =new iot.TopicRule(this,  'TestConnectionRule', {
      topicRuleName: 'TestConnectionRule', 
      sql: iot.IotSql.fromStringAsVer20160323("SELECT * as payload, topic() as topic FROM '$aws/events/presence/connected/+' "),
      actions: [callLambdaFunc],
    });
```

### What did you expect to happen?

I expected two TopicRules would be bind to the same lambda function action.

### What actually happened?

Error is thrown when trying "cdk synth"

### CDK CLI Version

1.132.0 

### Node.js Version

v16.13.0

### OS

Ubuntu 20.04.2 LTS

### Language

Typescript

**Comment by skinny85** [comment]
Thanks for opening the issue @aritzg!

@yamatatsu do you mind taking a look?

**Comment by aritzg** [comment]
The whole error stack is as follows

Error: There is already a Construct with name 'invokedByAwsIotRule' in Function [gh-lambda]
    at Node.addChild (./node_modules/constructs/src/construct.ts:381:13)
    at new Node (./node_modules/constructs/src/construct.ts:58:22)
    at new ConstructNode (./node_modules/@aws-cdk/core/lib/construct-compat.ts:184:24)
    at Object.createNode (./node_modules/@aws-cdk/core/lib/construct-compat.ts:55:11)
    at new Construct (./node_modules/constructs/src/construct.ts:409:26)
    at new Construct (./node_modules/@aws-cdk/core/lib/construct-compat.ts:52:5)
    at new CfnElement (./node_modules/@aws-cdk/core/lib/cfn-element.ts:31:5)
    at new CfnRefElement (./node_modules/@aws-cdk/core/lib/cfn-element.ts:106:1)
    at new CfnResource (./node_modules/@aws-cdk/core/lib/cfn-resource.ts:68:5)
    at new CfnPermission (./node_modules/@aws-cdk/aws-lambda/lib/lambda.generated.ts:2772:9)

**Comment by yamatatsu** [comment]
@aritzg Thanks for your polite report!
I was able to reproduct this error in a test and I'm fixing it!
