### ISSUE TITLE
(aws-lambda-nodejs): cannot read directory "asset-input/index.ts": operation not permitted

### ISSUE THREAD

**Issue by franklevasseur** [aws/aws-cdk#17529]
### What is the problem?

When I deploy a stack that involves building a docker image for aws lambda, I get the following error:

<details>
  <summary>Error stack trace</summary>
  
  
  ```shell
[+] Building 0.3s (13/13) FINISHED
 => [internal] load build definition from Dockerfile                                                                                               0.0s
 => => transferring dockerfile: 37B                                                                                                                0.0s
 => [internal] load .dockerignore                                                                                                                  0.0s
 => => transferring context: 2B                                                                                                                    0.0s
 => [internal] load metadata for public.ecr.aws/sam/build-nodejs14.x:latest                                                                        0.2s
 => [1/9] FROM public.ecr.aws/sam/build-nodejs14.x@sha256:a8b7d4ed29c35762d48a648d51056ae42c46b0e85e2e43e099f503422c64dea2                         0.0s
 => CACHED [2/9] RUN npm install --global yarn@1.22.5                                                                                              0.0s
 => CACHED [3/9] RUN npm install --global pnpm                                                                                                     0.0s
 => CACHED [4/9] RUN npm install --global typescript                                                                                               0.0s
 => CACHED [5/9] RUN npm install --global --unsafe-perm=true esbuild@0                                                                             0.0s
 => CACHED [6/9] RUN mkdir /tmp/npm-cache &&     chmod -R 777 /tmp/npm-cache &&     npm config --global set cache /tmp/npm-cache                   0.0s
 => CACHED [7/9] RUN mkdir /tmp/yarn-cache &&     chmod -R 777 /tmp/yarn-cache &&     yarn config set cache-folder /tmp/yarn-cache                 0.0s
 => CACHED [8/9] RUN npm config --global set update-notifier false                                                                                 0.0s
 => CACHED [9/9] RUN /sbin/useradd -u 1000 user && chmod 711 /                                                                                     0.0s
 => exporting to image                                                                                                                             0.0s
 => => exporting layers                                                                                                                            0.0s
 => => writing image sha256:fb914f0981a13f47eadbbeff631474d0e6985d82d17ab0d1f5b57547048b00a9                                                       0.0s
 => => naming to docker.io/library/cdk-dbbc24ef5b0d2406bc0726dd8664a3b6527d6ae9bcc67bd6cebbeebe502039c8                                            0.0s

Use 'docker scan' to run Snyk tests against images to find vulnerabilities and learn how to fix them
Bundling asset Cloud-Service-NLU/com.amazonaws.cdk.custom-resources.s3file-provider/s3file-on-event/Code/Stage...
esbuild cannot run locally. Switching to Docker bundling.
 > error: Cannot read directory "asset-input/index.ts": operation not permitted

 > error: Could not resolve "/asset-input/index.ts"

2 errors

/Users/francoislevasseur/Documents/botpress-root/infra/commons/node_modules/@aws-cdk/core/lib/asset-staging.ts:398
      throw new Error(`Failed to bundle asset ${this.node.path}, bundle output is located at ${bundleErrorDir}: ${err}`);
            ^
Error: Failed to bundle asset Cloud-Service-NLU/com.amazonaws.cdk.custom-resources.s3file-provider/s3file-on-event/Code/Stage, bundle output is located at /Users/francoislevasseur/Documents/botpress-root/infra/cloud/nlu/cdk.out/bundling-temp-77552b2d484d3e17df650ce05f2f47f950bd62aec24810c9c288be76885fb977-error: Error: docker exited with status 1
    at AssetStaging.bundle (/Users/francoislevasseur/Documents/botpress-root/infra/commons/node_modules/@aws-cdk/core/lib/asset-staging.ts:398:13)
    at AssetStaging.stageByBundling (/Users/francoislevasseur/Documents/botpress-root/infra/commons/node_modules/@aws-cdk/core/lib/asset-staging.ts:246:10)
    at stageThisAsset (/Users/francoislevasseur/Documents/botpress-root/infra/commons/node_modules/@aws-cdk/core/lib/asset-staging.ts:137:35)
    at Cache.obtain (/Users/francoislevasseur/Documents/botpress-root/infra/commons/node_modules/@aws-cdk/core/lib/private/cache.ts:24:13)
    at new AssetStaging (/Users/francoislevasseur/Documents/botpress-root/infra/commons/node_modules/@aws-cdk/core/lib/asset-staging.ts:162:44)
    at new Asset (/Users/francoislevasseur/Documents/botpress-root/infra/commons/node_modules/@aws-cdk/aws-s3-assets/lib/asset.ts:68:21)
    at AssetCode.bind (/Users/francoislevasseur/Documents/botpress-root/infra/commons/node_modules/@aws-cdk/aws-lambda/lib/code.ts:183:20)
    at new Function (/Users/francoislevasseur/Documents/botpress-root/infra/commons/node_modules/@aws-cdk/aws-lambda/lib/function.ts:338:29)
    at new NodejsFunction (/Users/francoislevasseur/Documents/botpress-root/infra/commons/node_modules/@aws-cdk/aws-lambda-nodejs/lib/function.ts:53:5)
    at new S3FileProvider (/Users/francoislevasseur/Documents/botpress-root/infra/commons/src/s3/index.ts:92:23)
Subprocess exited with error 1
```
</details>

This error only occurs on my pc, my colleges have no problem.

### Reproduction Steps

As stated above, this error only occurs on my pc, my colleges have no problem.

### What did you expect to happen?

the error not throwing.

### What actually happened?

there's an error.

### CDK CLI Version

1.130.0

### Node.js Version

v16.9.1

### OS

macos Big Sur 11.5.2

### Language

Typescript

### Language Version

3.9.10

### Other information

Many thanks in advance!

**Comment by franklevasseur** [comment]
Found 2 solutions:
1 - Move my project in the home folder. It is weird, but it works.
2- Install esbuild so you don't need to fallback on docker.

**Comment by franklevasseur** [comment]
I'll close the issue since I found workarounds

thank you anyway
