### ISSUE TITLE
Error when running commands using aws-cdk-lib 2.0.0-rc.29

### ISSUE THREAD

**Issue by danieljamesscott** [aws/aws-cdk#17527]
### General Issue

jsii Error: ZlibError: zlib: incorrect data check

### The Question

I'm using python and it was working fine a couple of weeks ago (with older rc). I'm using a local install of cdk.

When I try to run:
 - npx cdk bootstrap
 - npx cdk deploy

I get the following error:

    ZlibError: zlib: incorrect data check

Things I've tried:
 - Using an old project which previously worked
 - Using a newly 'init'ed project
 - Python versions 3.8 and 3.9
 - Updating my local system packages (including python)

Any ideas?

### CDK CLI Version

2.0.0-rc.29 (build 2445842)

### Node.js Version

v14.18.1

### OS

MacOS

### Language

Python

### Language Version

3.9.9

### Other information

```sh
jsii.errors.JavaScriptError:
  ZlibError: zlib: incorrect data check
      at Unzip.write (/private/var/folders/3m/dlw0dvwd4cb4bv6qhpwxrbmm0000gn/T/tmpr3flk5sd/lib/program.js:4518:36)
      at UnpackSync.write (/private/var/folders/3m/dlw0dvwd4cb4bv6qhpwxrbmm0000gn/T/tmpr3flk5sd/lib/program.js:6063:46)
      at Yallist.<anonymous> (/private/var/folders/3m/dlw0dvwd4cb4bv6qhpwxrbmm0000gn/T/tmpr3flk5sd/lib/program.js:4169:76)
      at Yallist.forEach (/private/var/folders/3m/dlw0dvwd4cb4bv6qhpwxrbmm0000gn/T/tmpr3flk5sd/lib/program.js:7756:20)
      at ReadStreamSync.emit (/private/var/folders/3m/dlw0dvwd4cb4bv6qhpwxrbmm0000gn/T/tmpr3flk5sd/lib/program.js:4169:55)
      at ReadStreamSync.emit (/private/var/folders/3m/dlw0dvwd4cb4bv6qhpwxrbmm0000gn/T/tmpr3flk5sd/lib/program.js:1739:34)
      at ReadStreamSync.write (/private/var/folders/3m/dlw0dvwd4cb4bv6qhpwxrbmm0000gn/T/tmpr3flk5sd/lib/program.js:4043:26)
      at ReadStreamSync.[_handleChunk] (/private/var/folders/3m/dlw0dvwd4cb4bv6qhpwxrbmm0000gn/T/tmpr3flk5sd/lib/program.js:1715:41)
      at ReadStreamSync.[_read] (/private/var/folders/3m/dlw0dvwd4cb4bv6qhpwxrbmm0000gn/T/tmpr3flk5sd/lib/program.js:1761:52)
      at ReadStreamSync.emit (/private/var/folders/3m/dlw0dvwd4cb4bv6qhpwxrbmm0000gn/T/tmpr3flk5sd/lib/program.js:1730:67)
```

**Comment by ryparker** [comment]
Possibly related to this https://stackoverflow.com/questions/69793334/z-data-error-errno-3-zlib-incorrect-data-check-mba-m1

Could you try upgrading to Node 16 and NPM to w/e is latest.

Also are you using an M1 mac?

**Comment by danieljamesscott** [comment]
> Possibly related to this https://stackoverflow.com/questions/69793334/z-data-error-errno-3-zlib-incorrect-data-check-mba-m1
> 
> Could you try upgrading Node to v16 and NPM to latest.
> 
> Also are you using an M1 mac?

Thanks for the reply. I have also tried the following:

 - Upgrading Node to 16.13.0
 - Upgrading npm to 8.3.1
 - Running `npm cache clean --force`
 - Upgrading to the latest MacOS Big Sur
 - Upgrading to MacOS Monterey

Not using an M1 mac - it's a 2019 model.

Still getting the same issue. I'll probably try and run some filesystem checks/repairs next.

**Comment by danieljamesscott** [comment]
Finally!

Downgrade to npm7 seems to have done the trick.

**Comment by danieljamesscott** [comment]
Hmm, I thought that downgrading to npm7 had fixed the issue, but it's still happening

**Comment by danieljamesscott** [comment]
Is there a way to find out what `/lib/program.js` should be? The file isn't present at the moment

**Comment by danieljamesscott** [comment]
Installing node using nvm seems to have fixed the issue. I'm guessing some sort of installation/linking error.
