### ISSUE TITLE
(aws-codebuild): DockerCredential with assume_role not getting applied to CodePipeline due to CredentialsError

### ISSUE THREAD

**Issue by jr2173** [aws/aws-cdk#17590]
### General Issue

Authenticating docker in CodePipeline

### The Question

I'm attempting to pass a `DockerCredential` object into a `CodePipeline` to authenticate pull requests.  The build logs show that the credentials are being applied:

`
Running command echo '{"version":"1.0","domainCredentials":{"********.dkr.ecr.us-east-1.amazonaws.com":{"ecrRepository":true,"assumeRoleArn":"arn:aws:iam::********:role/********-DockerRole56834808-1GVAIVRU5HH7J"}}}' > $HOME/.cdk/cdk-docker-creds.json
`

However, when a docker command is run, it produces the following error:

```
debug: docker --config /tmp/cdkDockerConfigKLCMXJ build --tag cdkasset-b89d968ea933065321d0aced003be95d79bb2f3eb9553fd5db591288349b68f7 --target production --file scripts/prod/Dockerfile .
CredentialsError: Missing credentials in config, if using AWS_CONFIG_FILE, set AWS_SDK_LOAD_CONFIG=1
    at Request.extractError (/usr/local/lib/node_modules/cdk-assets/node_modules/aws-sdk/lib/protocol/query.js:50:29)
    at Request.callListeners (/usr/local/lib/node_modules/cdk-assets/node_modules/aws-sdk/lib/sequential_executor.js:106:20)
    at Request.emit (/usr/local/lib/node_modules/cdk-assets/node_modules/aws-sdk/lib/sequential_executor.js:78:10)
    at Request.emit (/usr/local/lib/node_modules/cdk-assets/node_modules/aws-sdk/lib/request.js:686:14)
    at Request.transition (/usr/local/lib/node_modules/cdk-assets/node_modules/aws-sdk/lib/request.js:22:10)
    at AcceptorStateMachine.runTo (/usr/local/lib/node_modules/cdk-assets/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at /usr/local/lib/node_modules/cdk-assets/node_modules/aws-sdk/lib/state_machine.js:26:10
    at Request.<anonymous> (/usr/local/lib/node_modules/cdk-assets/node_modules/aws-sdk/lib/request.js:38:9)
    at Request.<anonymous> (/usr/local/lib/node_modules/cdk-assets/node_modules/aws-sdk/lib/request.js:688:12)
    at Request.callListeners (/usr/local/lib/node_modules/cdk-assets/node_modules/aws-sdk/lib/sequential_executor.js:116:18)
```

I have experienced this issue with both `DockerCredential.ecr` and `DockerCredential.docker_hub` using code similar to below:

```python

docker_role = iam.Role(self, 'DockerRole',
    assumed_by=iam.ServicePrincipal('codebuild.amazonaws.com')
)

# docker_hub_secret = secrets.Secret.from_secret_complete_arn(self, 'DockerHubSecret', 'arn:aws:secretsmanager:*****')
# docker_hub_secret.grant_read(docker_role)

docker_repo = ecr.Repository.from_repository_arn(self, 'DockerRepo', 'arn:aws:ecr:*****')
docker_repo.grant_pull(docker_role)

pipeline = CodePipeline(self, 'TestPipeline',
    pipeline_name='TestPipeline',
    docker_credentials=[
        # DockerCredential.docker_hub(docker_hub_secret, assume_role=docker_secret_role)
        DockerCredential.ecr([docker_repo], assume_role=docker_role)
    ],
    ...
)
```

I also tried setting the `AWS_SDK_LOAD_CONFIG` environment variable using a `BuildEnvironment` passed to the `code_build_defaults` parameter but the issue persisted.

### CDK CLI Version

1.132.0

### Language

Python

### Language Version

3.9.9

**Comment by jr2173** [comment]
I was able to get this working by providing a `PolicyStatement` to the `code_build_defaults` parameter as opposed to assuming an arbitrary role.  The below code works as expected:

```python
docker_repo = ecr.Repository.from_repository_arn(self, 'DockerRepo', 'arn:aws:ecr:*****')

pipeline = CodePipeline(self, 'TestPipeline',
    pipeline_name='TestPipeline',
    docker_credentials=[
        DockerCredential.ecr([docker_repo])# , assume_role=docker_role)
    ],
    code_build_defaults=CodeBuildOptions(
        role_policy=[iam.PolicyStatement(
            effect=iam.Effect.ALLOW,
            actions=[
                'ecr:BatchCheckLayerAvailability',
                'ecr:GetDownloadUrlForLayer',
                'ecr:BatchGetImage'
            ],
            resources=[
                'arn:aws:ecr:*:******:repository/'
            ],
        )]
    )
    ...
)
```

Still puzzled why the `assume_role` parameter is failing as it seems to be supported in [documentation](https://docs.aws.amazon.com/cdk/api/latest/docs/pipelines-readme.html#authenticating-to-docker-registries)
