### ISSUE TITLE
(aws-cdk): Use same credential detection logic as aws cli

### ISSUE THREAD

**Issue by dejantot** [aws/aws-cdk#17651]
### What is the problem?

Cdk synth and deploy commands have different credential detection mechanisms than the aws cli, this leads to inconsistent user experiences

### Reproduction Steps

Using the following setup for the app initialization script:
```typescript
#!/usr/bin/env node
import 'source-map-support/register';
import * as cdk from '@aws-cdk/core';
import { CdkAppStack } from '../lib/cdk-app-stack';

const app = new cdk.App();
new CdkAppStack(app, 'CdkAppStack', {
   env: { account: '123456789123', region: 'eu-central-1' },
});
```

## Case 1 (synth)
**When**
running `cdk synth`
**Given**
Environment variables AWS_ACCESS_KEY, AWS_SECRET_ACCESS_KEY and AWS_SESSION_TOKEN are **defined**
_and_ `~/.aws/credentials` file contains default config:
```ini
[default]
aws_access_key_id=xxx
aws_secret_access_key=xxx
aws_session_token=xxx
```
**Then**
The cdk cli ignores defined env variables and uses the ones defined in the credentials file and the error is:
`[Error at /CdkAppStack] Need to perform AWS calls for account 12345689123, but no credentials have been configured`
(because my credentials file contains expired session token)

## Case 2 (deploy)
**When**
running `cdk deploy`
**Given**
Environment variables AWS_ACCESS_KEY, AWS_SECRET_ACCESS_KEY and AWS_SESSION_TOKEN are **defined**
_and_ `~/.aws/config` file contains default config:
```ini
[default]
region = eu-central-1
output = json
```
**Then**
The deploy command fails with the following error:
```
Cannot redefine property: default
TypeError: Cannot redefine property: default
    at Function.defineProperty (<anonymous>)
    at C:\Users\User\AppData\Roaming\npm\node_modules\aws-cdk\node_modules\aws-sdk\lib\shared-ini\ini-loader.js:11:14
    at Array.forEach (<anonymous>)
    at IniLoader.parseFile (C:\Users\User\AppData\Roaming\npm\node_modules\aws-cdk\node_modules\aws-sdk\lib\shared-ini\ini-loader.js:8:26)
    at IniLoader.loadFrom (C:\Users\User\AppData\Roaming\npm\node_modules\aws-cdk\node_modules\aws-sdk\lib\shared-ini\ini-loader.js:56:30)
    at getRegion (C:\Users\User\AppData\Roaming\npm\node_modules\aws-cdk\node_modules\aws-sdk\lib\node_loader.js:116:32)
    at Config.region (C:\Users\User\AppData\Roaming\npm\node_modules\aws-cdk\node_modules\aws-sdk\lib\node_loader.js:171:18)
    at Config.set (C:\Users\User\AppData\Roaming\npm\node_modules\aws-cdk\node_modules\aws-sdk\lib\config.js:524:39)
    at Config.<anonymous> (C:\Users\User\AppData\Roaming\npm\node_modules\aws-cdk\node_modules\aws-sdk\lib\config.js:359:12)
    at Config.each (C:\Users\User\AppData\Roaming\npm\node_modules\aws-cdk\node_modules\aws-sdk\lib\util.js:512:32)
```

### What did you expect to happen?

In **Case 1 (synth)**, I would expect the config detection mechanism to use environment variables with a higher priority over the credentials file as is the behaviour with the aws cli

In **Case 2 (deploy)**, I would expect the deploy to not fail

### What actually happened?

(stated in the reproduction steps)

### CDK CLI Version

1.133.0

### Node.js Version

v14.15.3

### OS

Windows 10

### Language

Typescript

### Language Version

~3.9.7

**Comment by corymhall** [comment]
@dejantot is this still an issue for you? I've tried to reproduce this behavior, but for me the CLI will take the environment variables first.
