### ISSUE TITLE
cdk deploy causes windows defender to detect Trojan:Script/Sabsik.TE.A!ml

### ISSUE THREAD

**Issue by m1212e** [aws/aws-cdk#17718]
### What is the problem?

When deploying my CloudFormation project, the process fails and the windows defender issues a security warning:
![image](https://user-images.githubusercontent.com/14091540/143485778-8da346ca-1369-4309-a562-054293eb5999.png)
It's in german but it basically tells that there is a severe threat to the system and that the corrupted file has been put in quarantine.
As you can see at the bottom the source of the threat is the cdk.out/cache folder.
I suspect this to be a false positive, but I'm unsure what to do, since it blocks the command from working properly.

### Reproduction Steps

cdk deploy --verbose

### What did you expect to happen?

The command to run normally

### What actually happened?

The windows defender kicked in

### CDK CLI Version

1.133.0 (build 2dea31a)

### Node.js Version

v14.18.1

### OS

Windows 10

### Language

Typescript

### Other information

Do you wish to deploy these changes (y/n)? y
TestDeploy: deploying...
Waiting for stack CDKToolkit to finish creating or updating...
Call failed: describeStacks({"StackName":"TestDeploy"}) => Stack with id TestDeploy does not exist (code=ValidationError)
Preparing asset 88f91284f171c6936c1015ca7da2741cea40d7a4ff5a6814c9492263b1477b12: {"path":"asset.88f91284f171c6936c1015ca7da2741cea40d7a4ff5a6814c9492263b1477b12","id":"88f91284f171c6936c1015ca7da2741cea40d7a4ff5a6814c9492263b1477b12","packaging":"zip","sourceHash":"88f91284f171c6936c1015ca7da2741cea40d7a4ff5a6814c9492263b1477b12","s3BucketParameter":"AssetParameters88f91284f171c6936c1015ca7da2741cea40d7a4ff5a6814c9492263b1477b12S3Bucket568B02E9","s3KeyParameter":"AssetParameters88f91284f171c6936c1015ca7da2741cea40d7a4ff5a6814c9492263b1477b12S3VersionKeyB6E84681","artifactHashParameter":"AssetParameters88f91284f171c6936c1015ca7da2741cea40d7a4ff5a6814c9492263b1477b12ArtifactHashFE6E1866"}
Storing asset asset.88f91284f171c6936c1015ca7da2741cea40d7a4ff5a6814c9492263b1477b12 at s3://cdktoolkit-stagingbucket-12norn7oa78st/assets/88f91284f171c6936c1015ca7da2741cea40d7a4ff5a6814c9492263b1477b12.zip
TestDeploy: checking if we can skip deploy
TestDeploy: no existing stack
TestDeploy: deploying...
[0%] start: Publishing 88f91284f171c6936c1015ca7da2741cea40d7a4ff5a6814c9492263b1477b12:current
[0%] check: Check s3://cdktoolkit-stagingbucket-12norn7oa78st/assets/88f91284f171c6936c1015ca7da2741cea40d7a4ff5a6814c9492263b1477b12.zip
[0%] build: Zip \cdk.out\asset.88f91284f171c6936c1015ca7da2741cea40d7a4ff5a6814c9492263b1477b12 -> [object Object]
[0%] upload: Upload s3://cdktoolkit-stagingbucket-12norn7oa78st/assets/88f91284f171c6936c1015ca7da2741cea40d7a4ff5a6814c9492263b1477b12.zip
[100%] fail: UNKNOWN: unknown error, open '\cdk.out\.cache\88f91284f171c6936c1015ca7da2741cea40d7a4ff5a6814c9492263b1477b12.zip'

 ❌  TestDeploy failed: Error: Failed to publish one or more assets. See the error messages above for more information.
    at Object.publishAssets (\awscdk\node_modules\aws-cdk\lib\util\asset-publishing.ts:25:11)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at Object.deployStack (\awscdk\node_modules\aws-cdk\lib\api\deploy-stack.ts:245:3)
    at CdkToolkit.deploy (\awscdk\node_modules\aws-cdk\lib\cdk-toolkit.ts:194:24)
    at initCommandLine (\awscdk\node_modules\aws-cdk\bin\cdk.ts:267:9)
Failed to publish one or more assets. See the error messages above for more information.
Error: Failed to publish one or more assets. See the error messages above for more information.
    at Object.publishAssets (\awscdk\node_modules\aws-cdk\lib\util\asset-publishing.ts:25:11)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at Object.deployStack (\awscdk\node_modules\aws-cdk\lib\api\deploy-stack.ts:245:3)
    at CdkToolkit.deploy (\awscdk\node_modules\aws-cdk\lib\cdk-toolkit.ts:194:24)
    at initCommandLine (\awscdk\node_modules\aws-cdk\bin\cdk.ts:267:9)

**Comment by m1212e** [comment]
Update: The error was gone after restarting. I'm unsure if there is further investigation needed.

**Comment by peterwoodworth** [comment]
Huh, I've never seen this reported before, really strange. Glad it's gone after a restart! ping me if you run into this again

**Comment by klapro** [comment]
Happened to me too, I guess its a windows 11 error
