### ISSUE TITLE
(CLI): Hotswap raises Invalid Arn when updating state machine definition

### ISSUE THREAD

**Issue by fab-mindflow** [aws/aws-cdk#17716]
### What is the problem?

CDK deploy with hotswap fails with `Invalid ARN prefix` error as follows when updating a state definition :

```
> cdk deploy --hotswap

.......

MyWorkflow123456 failed: InvalidArn: Invalid Arn: 'Invalid ARN prefix: MyWorkflow123456'
    at Request.extractError (####/node_modules/aws-cdk/node_modules/aws-sdk/lib/protocol/json.js:52:27)
    at Request.callListeners (####/node_modules/aws-cdk/node_modules/aws-sdk/lib/sequential_executor.js:106:20)
    at Request.emit (####/node_modules/aws-cdk/node_modules/aws-sdk/lib/sequential_executor.js:78:10)
    at Request.emit (####/node_modules/aws-cdk/node_modules/aws-sdk/lib/request.js:688:14)
    at Request.transition (####/node_modules/aws-cdk/node_modules/aws-sdk/lib/request.js:22:10)
    at AcceptorStateMachine.runTo (####/node_modules/aws-cdk/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at ####/node_modules/aws-cdk/node_modules/aws-sdk/lib/state_machine.js:26:10
    at Request.<anonymous> (####/node_modules/aws-cdk/node_modules/aws-sdk/lib/request.js:38:9)
    at Request.<anonymous> (####/node_modules/aws-cdk/node_modules/aws-sdk/lib/request.js:690:12)
    at Request.callListeners (####/node_modules/aws-cdk/node_modules/aws-sdk/lib/sequential_executor.js:116:18) {
  code: 'InvalidArn',
  time: 2021-11-25T16:08:44.977Z,
  requestId: '###################',
  statusCode: 400,
  retryable: false,
  retryDelay: 40.19606554280166
}
Invalid Arn: 'Invalid ARN prefix: MyWorkflow123456'
```

This may be due to this: https://github.com/aws/aws-cdk/blob/557f9c33541e74f94ca6a3a3b70106a8160d766c/packages/aws-cdk/lib/api/hotswap/stepfunctions-state-machines.ts#L59

### Reproduction Steps

Deploying with `--hotswap` a state machine in my AWS / CDK environment. A normal deploy (without hotswap) works fine.

### What did you expect to happen?

AWS Step Functions State machine updated successfully with hotswap.

### What actually happened?

Command line failure to update AWS Step Functions state machine.

### CDK CLI Version

1.134.0 (build dd5e12d)

### Node.js Version

16.13.0

### OS

macOS 12.0.1 (Monterey)

### Language

Typescript

### Language Version

4.4.3

**Comment by skinny85** [comment]
Hi @fab-mindflow,

thanks for opening the issue. Can you show your CDK code that raises this error?

Thanks,
Adam

**Comment by fab-mindflow** [comment]
Hi @skinny85, 

I can reproduce it from scratch like this:

1. Create a new CDK project from scratch (I suppose you don't really need that 😁)
```shell
cdk init --language=typescript
yarn install
yarn add @aws-cdk/aws-stepfunctions  
```

2. Create a dumb workflow with Step Functions in `lib/cdk-stack.ts`

```typescript
import * as sfn from "@aws-cdk/aws-stepfunctions"
import { WaitTime } from "@aws-cdk/aws-stepfunctions"
import * as cdk from "@aws-cdk/core"

export class CdkStack extends cdk.Stack {
  public constructor(scope: cdk.Construct, id: string, props?: cdk.StackProps) {
    super(scope, id, props)

    const waitStep = new sfn.Wait(this, "Wait", {
      time: WaitTime.duration(cdk.Duration.seconds(10)),
    })

    const succeedStep = new sfn.Succeed(this, "Start", {})
    waitStep.next(succeedStep)

    //    const startStep = waitStep
    const startStep = succeedStep

    const _stateMachine = new sfn.StateMachine(this, "MyStateMachine", {
      stateMachineName: "MyStateMachine",
      definition: startStep,
    })
  }
}
```

3. Run `cdk deploy` for first time

4. Toggle the line to include 2 steps

```typescript
    const startStep = waitStep
    //    const startStep = succeedStep
```

5. Run `cdk deploy --hotswap`. This fails with:

```shell
❯ cdk deploy --hotswap
⚠️ The --hotswap flag deliberately introduces CloudFormation drift to speed up deployments
⚠️ It should only be used for development - never use it for your production Stacks!
CdkStack: deploying...

 ❌  CdkStack failed: InvalidArn: Invalid Arn: 'Invalid ARN prefix: MyStateMachine'
    at Request.extractError (/opt/homebrew/Cellar/aws-cdk/1.134.0/libexec/lib/node_modules/aws-cdk/node_modules/aws-sdk/lib/protocol/json.js:52:27)
    at Request.callListeners (/opt/homebrew/Cellar/aws-cdk/1.134.0/libexec/lib/node_modules/aws-cdk/node_modules/aws-sdk/lib/sequential_executor.js:106:20)
    at Request.emit (/opt/homebrew/Cellar/aws-cdk/1.134.0/libexec/lib/node_modules/aws-cdk/node_modules/aws-sdk/lib/sequential_executor.js:78:10)
    at Request.emit (/opt/homebrew/Cellar/aws-cdk/1.134.0/libexec/lib/node_modules/aws-cdk/node_modules/aws-sdk/lib/request.js:686:14)
    at Request.transition (/opt/homebrew/Cellar/aws-cdk/1.134.0/libexec/lib/node_modules/aws-cdk/node_modules/aws-sdk/lib/request.js:22:10)
    at AcceptorStateMachine.runTo (/opt/homebrew/Cellar/aws-cdk/1.134.0/libexec/lib/node_modules/aws-cdk/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at /opt/homebrew/Cellar/aws-cdk/1.134.0/libexec/lib/node_modules/aws-cdk/node_modules/aws-sdk/lib/state_machine.js:26:10
    at Request.<anonymous> (/opt/homebrew/Cellar/aws-cdk/1.134.0/libexec/lib/node_modules/aws-cdk/node_modules/aws-sdk/lib/request.js:38:9)
    at Request.<anonymous> (/opt/homebrew/Cellar/aws-cdk/1.134.0/libexec/lib/node_modules/aws-cdk/node_modules/aws-sdk/lib/request.js:688:12)
    at Request.callListeners (/opt/homebrew/Cellar/aws-cdk/1.134.0/libexec/lib/node_modules/aws-cdk/node_modules/aws-sdk/lib/sequential_executor.js:116:18) {
  code: 'InvalidArn',
  time: 2021-12-04T13:32:20.700Z,
  requestId: 'b1eafc53-483f-45bd-96c1-e409945adb1c',
  statusCode: 400,
  retryable: false,
  retryDelay: 144.62321105479253
}
```

**Comment by skinny85** [comment]
Thanks for the detailed reproduction steps @fab-mindflow!

I'll let @comcalvi handle this one, as he was the original author of this functionality 🙂.

**Comment by fab-mindflow** [comment]
Great, thanks ! The hotswap feature for AWS Step Functions is really key to us so we can boost our deployment pipeline. I've seen the CDK 2.0 announcement and hope that the fix can still reach the 1.x branch.
