### ISSUE TITLE
core: add "getContext" which throws if context doesn't exist

### ISSUE THREAD

**Issue by clareliguori** [aws/aws-cdk#1771]
Construct method getContext() returns undefined when a context key is not defined.  Is that the right behavior?  I would expect it to fail fast instead of continuing, as I would expect context keys to be "required" in most stacks vs optional.  Currently, the behavior of the stack will result in confusing error messages later on, or worse, won't be caught at all when the stack is synthesized.

Reproduce:
```
new route53.AliasRecord(this, 'SiteAliasRecord', {
            zone,
            recordName: this.node.getContext('recordName'),
            target: distribution
        });
    }
```

"cdk synth" output with missing context key:
```
$ cdk synth
/XXX/@aws-cdk/aws-route53/lib/records/_util.js:19
    if (providedName.endsWith('.')) {
                     ^

TypeError: Cannot read property 'endsWith' of undefined
    at Object.determineFullyQualifiedDomainName (/XXX/@aws-cdk/aws-route53/lib/records/_util.js:19:22)
    at new AliasRecord (/XXX/@aws-cdk/aws-route53/lib/records/alias.js:14:27)
    at new StaticSite (/home/ANT.AMAZON.COM/liguori/code/aws-cdk-examples/typescript/static-site/static-site.js:42:9)
    at new MyStaticSiteStack (/home/ANT.AMAZON.COM/liguori/code/aws-cdk-examples/typescript/static-site/index.js:18:9)
    at Object.<anonymous> (/home/ANT.AMAZON.COM/liguori/code/aws-cdk-examples/typescript/static-site/index.js:24:1)
    at Module._compile (internal/modules/cjs/loader.js:734:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:745:10)
    at Module.load (internal/modules/cjs/loader.js:626:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:566:12)
    at Function.Module._load (internal/modules/cjs/loader.js:558:3)
Subprocess exited with error 1
```

**Comment by sam-goodwin** [comment]
I don't think we should assume that if someone queries a key then it must exist, that would be ugly for the case where a default value is overridden by some context value (if provided). What's wrong with:

```ts
this.getContext(key) || throw new Error(..)
```

Perhaps we need something like how `findChild` in the `ConstructNode` works:
* `tryFindChild` returns null if it doesn't exist
* `findChild` throws if it doesn't exist

**Comment by clareliguori** [comment]
If that's the recommended pattern, the docs should be updated to reflect that

**Comment by eladb** [comment]
+1 for `tryGetContext` to return `undefined` and `getContext` to throw.

**Comment by bgdnlp** [comment]
Could tryGetContext mimic the [dict.get()](https://docs.python.org/3/library/stdtypes.html#dict.get) behavior in Python? That is, accept a default parameter, `tryGetContext(key, default)`, return `default` if key is not found, return undefined/null/None if default was not passed. And let getContext throw an error.

The pythonic way would be to simply have `context` available as a dictionary (app.context, or node.context, or aws_core.cdk.context), then `context.get(key, default)` (returns default or None) and `context[key]` (throws and error) would just work as expected. But maybe that doesn't translate as good in other languages.

**Comment by mitchlloyd** [comment]
The name `tryGetContext` with its current behavior is surprising to me as a TypeScript user.

 It seems typical for getters to return `undefined` JavaScript:

```js
new Map().get('foo') // undefined
new Array()[0] // undefined
{}.foo // undefined
document.getElementById("not-there") // null
```

Adding `try` in front of the function makes me wonder if it's going to throw because when you write `try` you're usually writing `catch` soon after.

I realize that CDK needs to consider other languages as well but, through the lens of JavaScript, it seems that a throwing getter method should probably look exceptional whereas the version that returns `undefined` should look typical.

So how about `getContext` returns `undefined` when not there and `mustGetContext` or `getContextOrThrow` throws?

**Comment by eladb** [comment]
Our naming pattern in the CDK is `tryGetXxx` for getters that return undefined and `getXxx` for methods that throw (borrowed from .NET since JavaScript doesn't really have a pattern for this).

**Comment by eladb** [comment]
still relevant

**Comment by ricardosllm** [comment]
To add more examples I just faced this issue when running `cdk bootstrap` as recommended by another error message while trying to follow [this example from aws-sampes](https://github.com/aws-samples/aws-cdk-examples/tree/master/typescript/static-site) 

```
$ cdk bootstrap aws://<account>/<region>

<project_root>/node_modules/@aws-cdk/aws-route53/lib/hosted-zone.js:77
        if (response.Name.endsWith('.')) {
                          ^

TypeError: Cannot read property 'endsWith' of undefined
at Function.fromLookup (/<project_root>//node_modules/@aws-cdk/aws-route53/lib/hosted-zone.js:77:27)
at new <xxxx> (/<project_root>//static-site.js:21:41)
at new <xxxx> (/<project_root>//index.js:20:9)
at Object.<anonymous> (/<project_root>//index.js:27:1)
at Module._compile (internal/modules/cjs/loader.js:776:30)
at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
at Module.load (internal/modules/cjs/loader.js:653:32)
at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
at Function.Module._load (internal/modules/cjs/loader.js:585:3)
at Function.Module.runMain (internal/modules/cjs/loader.js:829:12)
```
