### ISSUE TITLE
(aws-ecs): TaskDescription w. compatibility External and ExternalTaskDescription won't accept "Host" or "None" networkMode

### ISSUE THREAD

**Issue by beezly** [aws/aws-cdk#17754]
### What is the problem?

If you create an `ExternalTaskDescription` or a `TaskDescription` with compatibility set to external, you cannot set networkMode to Host/None.

According to the [ECS Anywhere documentation](https://docs.aws.amazon.com/AmazonECS/latest/developerguide/ecs-anywhere.html):
> Tasks that run on external instances must use the bridge, host, or none network modes. The awsvpc network mode isn't supported.

but CDK currently enforces bridge mode for all `TasksDescription` that have compatibility set to external and all `ExternalTaskDescription`.

### TaskDefinition with compatibilty set to external

```typescript
import * as cdk from '@aws-cdk/core';
import * as ecs from '@aws-cdk/aws-ecs';

export class CdkExampleStack extends cdk.Stack {
  constructor(scope: cdk.Construct, id: string, props?: cdk.StackProps) {
    super(scope, id, props);

    // The code that defines your stack goes here
    const taskDefinition = new ecs.TaskDefinition(this, 'TaskDef', {
      compatibility: ecs.Compatibility.EXTERNAL,
      networkMode: ecs.NetworkMode.HOST,
    })
  }
}
```

produces `Error: External tasks can only have Bridge network mode, got: host`

### ExternalTaskDefinition with an attempt to set networkMode in the constructor

```typescript
import * as cdk from '@aws-cdk/core';
import * as ecs from '@aws-cdk/aws-ecs';

export class CdkExampleStack extends cdk.Stack {
  constructor(scope: cdk.Construct, id: string, props?: cdk.StackProps) {
    super(scope, id, props);

    // The code that defines your stack goes here
    const externalTaskDefinition = new ecs.ExternalTaskDefinition(this, 'TaskDef', {
      networkMode: ecs.NetworkMode.HOST,
    })
  }
}
```

produces:

```sh
/Users/ab/cdk-example/node_modules/ts-node/src/index.ts:513
    return new TSError(diagnosticText, diagnosticCodes)
           ^
TSError: ⨯ Unable to compile TypeScript:
lib/cdk-example-stack.ts:10:7 - error TS2345: Argument of type '{ networkMode: ecs.NetworkMode; }' is not assignable to parameter of type 'ExternalTaskDefinitionProps'.
  Object literal may only specify known properties, and 'networkMode' does not exist in type 'ExternalTaskDefinitionProps'.

10       networkMode: ecs.NetworkMode.HOST,
         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

    at createTSError (/Users/aberesfo/cdk-example/node_modules/ts-node/src/index.ts:513:12)
    at reportTSError (/Users/aberesfo/cdk-example/node_modules/ts-node/src/index.ts:517:19)
    at getOutput (/Users/aberesfo/cdk-example/node_modules/ts-node/src/index.ts:752:36)
    at Object.compile (/Users/aberesfo/cdk-example/node_modules/ts-node/src/index.ts:968:32)
    at Module.m._compile (/Users/aberesfo/cdk-example/node_modules/ts-node/src/index.ts:1056:42)
    at Module._extensions..js (node:internal/modules/cjs/loader:1138:10)
    at Object.require.extensions.<computed> [as .ts] (/Users/aberesfo/cdk-example/node_modules/ts-node/src/index.ts:1059:12)
    at Module.load (node:internal/modules/cjs/loader:989:32)
    at Function.Module._load (node:internal/modules/cjs/loader:829:14)
    at Module.require (node:internal/modules/cjs/loader:1013:19)
```

as there is no networkMode property to set in the constructor, and the assumption is made that networkMode should be set to bridge. 

### What did you expect to happen?

It should be possible to set the networkMode to bridge, or none.

### What actually happened?

Errors - see above. 

### CDK CLI Version

1.134.0 (build dd5e12d)

### Node.js Version

v16.3.0

### OS

Mac OS 12

### Language

Typescript

**Comment by beezly** [comment]
I created #17762 which I believe fixes this. I've not contributed to CDK before, and I'm not particularly familiar with typescript so please point me in the right direction if I've done something wrong.
