### ISSUE TITLE
(EFS): Can't create filesystem, complains about needing to configure a VPC

### ISSUE THREAD

**Issue by ffxsam** [aws/aws-cdk#17789]
### What is the problem?

I'm unable to create an EFS filesystem in CDK.

### Reproduction Steps

```js
    /** EFS storage for functions dealing with large files */
    const mainVpc = ec2.Vpc.fromLookup(this, 'MainVpc', { isDefault: true });
    const fileSystem = new efs.FileSystem(this, 'EFS', {
      vpc: mainVpc,
      vpcSubnets: {
        availabilityZones: [mainVpc.availabilityZones[0]],
        onePerAz: true,
      },
    });
    const accessPoint = fileSystem.addAccessPoint('EFSAccessPoint', {
      path: '/lambda',
      createAcl: {
        ownerGid: '1001',
        ownerUid: '1001',
        permissions: '755',
      },
      posixUser: {
        uid: '1001',
        gid: '1001',
      },
    });
```

### What did you expect to happen?

I expected an EFS filesystem to be created.

### What actually happened?

Error thrown:

```
Error: Cannot configure 'filesystem' without configuring a VPC.
    at new Function (/Volumes/SuperData/Sites/reelcrafter/v2-microservices/node_modules/@aws-cdk/aws-lambda/lib/function.ts:474:15)
    at new Function (/Volumes/SuperData/Sites/reelcrafter/v2-microservices/node_modules/@serverless-stack/resources/src/Function.ts:277:9)
    at setupStepFunction (/Volumes/SuperData/Sites/reelcrafter/v2-microservices/infra/media-processor/audio-proc-step-function.ts:62:25)
    at new MediaProcessorStack (/Volumes/SuperData/Sites/reelcrafter/v2-microservices/infra/media-processor/stack.ts:101:35)
    at Object.main (/Volumes/SuperData/Sites/reelcrafter/v2-microservices/infra/index.ts:91:3)
    at Object.<anonymous> (/Volumes/SuperData/Sites/reelcrafter/v2-microservices/.build/run.js:104:16)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:12)
```

### CDK CLI Version

1.132.0

### Node.js Version

14.18.1

### OS

macOS 11.6

### Language

Typescript

**Comment by ffxsam** [comment]
Closing - I just realized it was referring to the function, not the filesystem instance.
