### ISSUE TITLE
(integration tests): how to set environment?

### ISSUE THREAD

**Issue by markussiebert** [aws/aws-cdk#17853]
### link to reference doc page

https://github.com/aws/aws-cdk/blob/master/CONTRIBUTING.md#integration-tests

### Describe your issue?

If I run integration tests, i get the following error:

```bash
integ-provider-framework: deploying...

 ❌  integ-provider-framework failed: Error: Unable to resolve AWS account to use. It must be either configured when you define your CDK Stack, or through the environment
    at SdkProvider.resolveEnvironment (/Users/markussiebert/github/aws-cdk/packages/aws-cdk/lib/api/aws-auth/sdk-provider.ts:208:13)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at CloudFormationDeployments.prepareSdkFor (/Users/markussiebert/github/aws-cdk/packages/aws-cdk/lib/api/cloudformation-deployments.ts:260:33)
    at CloudFormationDeployments.deployStack (/Users/markussiebert/github/aws-cdk/packages/aws-cdk/lib/api/cloudformation-deployments.ts:190:70)
    at CdkToolkit.deploy (/Users/markussiebert/github/aws-cdk/packages/aws-cdk/lib/cdk-toolkit.ts:194:24)
    at initCommandLine (/Users/markussiebert/github/aws-cdk/packages/aws-cdk/bin/cdk.ts:267:9)
Unable to resolve AWS account to use. It must be either configured when you define your CDK Stack, or through the environment
Cleaning up.
integ-provider-framework: destroying...

 ❌  integ-provider-framework: destroy failed Error: Unable to resolve AWS account to use. It must be either configured when you define your CDK Stack, or through the environment
    at SdkProvider.resolveEnvironment (/Users/markussiebert/github/aws-cdk/packages/aws-cdk/lib/api/aws-auth/sdk-provider.ts:208:13)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at CloudFormationDeployments.prepareSdkFor (/Users/markussiebert/github/aws-cdk/packages/aws-cdk/lib/api/cloudformation-deployments.ts:260:33)
    at CloudFormationDeployments.destroyStack (/Users/markussiebert/github/aws-cdk/packages/aws-cdk/lib/api/cloudformation-deployments.ts:229:58)
    at CdkToolkit.destroy (/Users/markussiebert/github/aws-cdk/packages/aws-cdk/lib/cdk-toolkit.ts:348:9)
    at initCommandLine (/Users/markussiebert/github/aws-cdk/packages/aws-cdk/bin/cdk.ts:267:9)
Unable to resolve AWS account to use. It must be either configured when you define your CDK Stack, or through the environment
Error: Command exited with status 1
    at exec (/Users/markussiebert/github/aws-cdk/tools/@aws-cdk/cdk-integ-tools/lib/integ-helpers.js:349:15)
    at IntegrationTest.invokeCli (/Users/markussiebert/github/aws-cdk/tools/@aws-cdk/cdk-integ-tools/lib/integ-helpers.js:180:20)
    at main (/Users/markussiebert/github/aws-cdk/tools/@aws-cdk/cdk-integ-tools/bin/cdk-integ.js:51:32)
error Command failed with exit code 1.
```

I know how to set the account / region and so on for my app deployments, but don't know how to do this for integration tests if I want to run them on my machine in my aws account with access key id / and secret access key...

**Comment by njlynch** [comment]
How is your environment configured? Do you have a `~/.aws/config` and `~/.aws/credentials`, are you using environment variables, etc?

As the linked documentation states, we typically just run `yarn integ` or `yarn integ $testname` to run the integ tests. This resolves the current AWS credentials the same way as the `cdk` CLI does (in fact, via the same code paths).

**Comment by markussiebert** [comment]
Hi, I am using ~/.aws/config and ~/.aws/credentials, nothing else. The credentials work with cdk, but the problem isn't missing credentials, it's that cdk does not know the account and region I want to use...

**Comment by peterwoodworth** [comment]
Hey @markussiebert,

Check out #1656, that thread contains some helpful information for various CLI authentication issues. 

In particular, this comment mentions integration tests https://github.com/aws/aws-cdk/issues/1656#issuecomment-460845615, and the next comment is a followup with the solution. Maybe you've run into the same issue?
