### ISSUE TITLE
(ecs): I get an error in BaseService.RegisterLoadBalancerTargets

### ISSUE THREAD

**Issue by aetos382** [aws/aws-cdk#17876]
### What is the problem?

I am using `FargateService.RegisterLoadBalancerTargets` in CDK for C#.
This method was successfully synthesized in CDK v1.132, but fails in v1.133 and later (including v2.0).

### Reproduction Steps

1. `git clone https://github.com/aetos382/cdk-synth-error`
2. `cd cdk-synth-error`
3. `cd CdkV132`
4. `npm install`
5. `npx cdk synth` # It is synthesized successfully.
6. `cd ../CdkV133` # Also reproduced in CdkV134 and CdkV2
7. `npm install`
8. `npx cdk synth` # An error occurs.

### What did you expect to happen?

I can synthesize the stack successfully.

### What actually happened?

I get an error with CDK v1.133 or later.

`Missing required properties for @aws-cdk/aws-elasticloadbalancingv2.AddApplicationTargetGroupsProps: targetGroups`

### CDK CLI Version

1.133.0 (build 2dea31a)

### Framework Version

.NET 6

### Node.js Version

v16.13.0

### OS

Windows 10

### Language

.NET

### Language Version

C# 10

### Other information

```
Unhandled exception. Amazon.JSII.Runtime.JsiiException: Amazon.JSII.Runtime.JsiiException: Amazon.JSII.Runtime.JsiiException: Missing required properties for @aws-cdk/aws-elasticloadbalancingv2.AddApplicationTargetGroupsProps: targetGroups
   at Amazon.JSII.Runtime.Services.Client.TryDeserialize[TResponse](String responseJson)
   at Amazon.JSII.Runtime.Services.Client.ReceiveResponse[TResponse]()
   at Amazon.JSII.Runtime.Services.Client.Invoke(InvokeRequest request)
   at Amazon.JSII.Runtime.Services.Client.Invoke(ObjectReference objectReference, String method, Object[] arguments)
   at Amazon.JSII.Runtime.Deputy.DeputyBase.<>c__DisplayClass17_0`1.<InvokeInstanceMethod>b__1(IClient client, Object[] args)
   at Amazon.JSII.Runtime.Deputy.DeputyBase.<InvokeMethodCore>g__GetResult|18_0[T](<>c__DisplayClass18_0`1& )
   at Amazon.JSII.Runtime.Deputy.DeputyBase.InvokeMethodCore[T](JsiiMethodAttribute methodAttribute, Object[] arguments, Func`3 beginFunc, Func`3 invokeFunc)
   at Amazon.JSII.Runtime.Deputy.DeputyBase.InvokeInstanceMethod[T](Type[] parameterTypes, Object[] arguments, String methodName)
   at Amazon.JSII.Runtime.Deputy.DeputyBase.InvokeInstanceVoidMethod(Type[] parameterTypes, Object[] arguments, String methodName)
   at Amazon.CDK.AWS.ElasticLoadBalancingV2.ApplicationListener.AddTargetGroups(String id, IAddApplicationTargetGroupsProps props)
   at Amazon.JSII.Runtime.Services.Client.TryDeserialize[TResponse](String responseJson)
   at Amazon.JSII.Runtime.Services.Client.ReceiveResponse[TResponse]()
   at Amazon.JSII.Runtime.Services.Client.TryDeserialize[TResponse](String responseJson)
   at Amazon.JSII.Runtime.Services.Client.ReceiveResponse[TResponse]()
   at Amazon.JSII.Runtime.Services.Client.Invoke(InvokeRequest request)
   at Amazon.JSII.Runtime.Services.Client.Invoke(ObjectReference objectReference, String method, Object[] arguments)
   at Amazon.JSII.Runtime.Deputy.DeputyBase.<>c__DisplayClass17_0`1.<InvokeInstanceMethod>b__1(IClient client, Object[] args)
   at Amazon.JSII.Runtime.Deputy.DeputyBase.<InvokeMethodCore>g__GetResult|18_0[T](<>c__DisplayClass18_0`1& )
   at Amazon.JSII.Runtime.Deputy.DeputyBase.InvokeMethodCore[T](JsiiMethodAttribute methodAttribute, Object[] arguments, Func`3 beginFunc, Func`3 invokeFunc)
   at Amazon.JSII.Runtime.Deputy.DeputyBase.InvokeInstanceMethod[T](Type[] parameterTypes, Object[] arguments, String methodName)
   at Amazon.CDK.AWS.ElasticLoadBalancingV2.ApplicationListener.AddTargets(String id, IAddApplicationTargetsProps props)
   at Amazon.JSII.Runtime.Services.Client.TryDeserialize[TResponse](String responseJson)
   at Amazon.JSII.Runtime.Services.Client.ReceiveResponse[TResponse]()
   at Amazon.JSII.Runtime.Services.Client.TryDeserialize[TResponse](String responseJson)
   at Amazon.JSII.Runtime.Services.Client.ReceiveResponse[TResponse]()
   at Amazon.JSII.Runtime.Services.Client.Invoke(InvokeRequest request)
   at Amazon.JSII.Runtime.Services.Client.Invoke(ObjectReference objectReference, String method, Object[] arguments)
   at Amazon.JSII.Runtime.Deputy.DeputyBase.<>c__DisplayClass17_0`1.<InvokeInstanceMethod>b__1(IClient client, Object[] args)
   at Amazon.JSII.Runtime.Deputy.DeputyBase.<InvokeMethodCore>g__GetResult|18_0[T](<>c__DisplayClass18_0`1& )
   at Amazon.JSII.Runtime.Deputy.DeputyBase.InvokeMethodCore[T](JsiiMethodAttribute methodAttribute, Object[] arguments, Func`3 beginFunc, Func`3 invokeFunc)
   at Amazon.JSII.Runtime.Deputy.DeputyBase.InvokeInstanceMethod[T](Type[] parameterTypes, Object[] arguments, String methodName)
   at Amazon.JSII.Runtime.Deputy.DeputyBase.InvokeInstanceVoidMethod(Type[] parameterTypes, Object[] arguments, String methodName)
   at Amazon.CDK.AWS.ECS.BaseService.RegisterLoadBalancerTargets(IEcsTarget[] targets)
   at Cdk.CdkStack..ctor(Construct scope, String id, IStackProps props) in ...\cdk\Sources\CdkStack.cs:line 61
   at Cdk.Program.Main() in ...\cdk\Sources\Program.cs:line 11
Subprocess exited with error 3762504530
```

**Comment by madeline-k** [comment]
@aetos382 thanks for opening this issue, and providing repro steps. I was able to reproduce this issue, and I think it may be a regression.

**Comment by njlynch** [comment]
For what it's worth, here is an equivalent stack definition in Typescript:

```ts
import * as cdk from '@aws-cdk/core';
import * as ec2 from '@aws-cdk/aws-ec2';
import * as ecs from '@aws-cdk/aws-ecs';
import * as elbv2 from '@aws-cdk/aws-elasticloadbalancingv2';

export class Issue17876 extends cdk.Stack {
  constructor(scope: cdk.Construct, id: string, props?: cdk.StackProps) {
    super(scope, id, props);

    const vpc = new ec2.Vpc(this, 'MyVpc');
    const cluster = new ecs.Cluster(this, 'EcsCluster', { vpc });

    const taskDefinition = new ecs.FargateTaskDefinition(this, 'FargateTaskDef', {
      cpu: 256,
      memoryLimitMiB: 512,
    });

    const container = taskDefinition.addContainer('container', {
      image: ecs.ContainerImage.fromRegistry('nginx'),
      portMappings: [{ containerPort: 80 }],
    });

    const service = new ecs.FargateService(this, 'FargateService', {
      cluster,
      taskDefinition,
    });

    const loadBalancer = new elbv2.ApplicationLoadBalancer(this, 'LoadBalancer', { vpc });

    service.registerLoadBalancerTargets({
      containerName: container.containerName,
      containerPort: container.containerPort,
      newTargetGroupId: 'targetGroup',
      listener: ecs.ListenerConfig.applicationListener(new elbv2.ApplicationListener(this, 'AlbListener', {
        loadBalancer,
        protocol: elbv2.ApplicationProtocol.HTTP,
      })),
    });
  }
}
```

I can't reproduce the above error in Typescript using the above (with the appropriate CDK versions). That certainly points the finger to a quirk of `jsii`. I think the culprit is #17328, which changed a lot of code to avoid deprecation warnings within the CDK itself. It changed a lot of explicit property passing to the spread operator (`...`).

Here's the code today:

https://github.com/aws/aws-cdk/blob/59fe395a5adcd35bd59c6d9c74f4a2606aec88b0/packages/@aws-cdk/aws-elasticloadbalancingv2/lib/alb/application-listener.ts#L358-L361

Here's the code prior to the change:

https://github.com/aws/aws-cdk/blob/7dae114b7aac46321b8d8572e6837428b4c633b2/packages/@aws-cdk/aws-elasticloadbalancingv2/lib/alb/application-listener.ts#L376-L383

**Comment by RomainMuller** [comment]
We identified the cause for this issue (see aws/jsii#3339 for more details).

The jsii runtime bug has been there virtually forever, but CDK did not previously trigger that, so it went unnoticed.

Once aws/jsii#3339 is released, ensuring the updated version of the jsii runtime library should be enough to get the problem fixed (no need to wait for a CDK release).
