### ISSUE TITLE
I want to send the value from the top stack to the nested stack.

### ISSUE THREAD

**Issue by deathquin** [aws/aws-cdk#17899]
### General Issue

send the value from the top stack to the nested stack.

### The Question

I want to send the value from the top stack to the nested stack.
I executed the code as below.
However, they meet the bug as below.

```
V8CdkGoStack failed: Error: Failed to create ChangeSet cdk-deploy-change-set on V8CdkGoStack: FAILED, Internal Failure
    at C:\Users\deathquin\AppData\Roaming\npm\node_modules\aws-cdk\lib\api\util\cloudformation.ts:227:11
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at waitFor (C:\Users\deathquin\AppData\Roaming\npm\node_modules\aws-cdk\lib\api\util\cloudformation.ts:188:20)
    at Object.waitForChangeSet (C:\Users\deathquin\AppData\Roaming\npm\node_modules\aws-cdk\lib\api\util\cloudformation.ts:213:15)
    at prepareAndExecuteChangeSet (C:\Users\deathquin\AppData\Roaming\npm\node_modules\aws-cdk\lib\api\deploy-stack.ts:301:32)
    at CdkToolkit.deploy (C:\Users\deathquin\AppData\Roaming\npm\node_modules\aws-cdk\lib\cdk-toolkit.ts:189:24)
    at initCommandLine (C:\Users\deathquin\AppData\Roaming\npm\node_modules\aws-cdk\bin\cdk.ts:225:9)
Failed to create ChangeSet cdk-deploy-change-set on V8CdkGoStack: FAILED, Internal Failure

```

An error appears when a userpool value is sent from the upper stack to the nested stack.
I think the value sent from the upper stack cannot be referenced from the bottom, what should I do?

There are not many references because it is a go language.
I hope you can help me.
Thank you.

```
func NewV8CdkGoStack(scope constructs.Construct, id string, props *V8CdkGoStackProps) awscdk.Stack {
	var sprops awscdk.StackProps

	if props != nil {
		sprops = props.StackProps
	}

	stack := awscdk.NewStack(scope, &id, &sprops)

	studioPool1, _ := module.CreateCognito(stack, "studioadmin123") // create cognito

	nestedStack.TestAPIStack(stack, "dd", &nestedStack.CdkPipelineStackProps{
		UserPool: studioPool1.UserPoolId(),
	})

}

type CdkPipelineStackProps struct {
	awscdk.NestedStackProps
	UserPool 	   *string
}

func TestAPIStack(scope constructs.Construct, id string, props *CdkPipelineStackProps) {

	var sprops awscdk.NestedStackProps

	if props != nil {
		sprops = props.NestedStackProps
	}

	nestedStack := awscdk.NewNestedStack(scope, &id, &sprops)

	setup.InitAuthorizerLambda(nestedStack, api, "admin123test", &map[string]*string{
		"Region":   jsii.String(config.GetAWSConfiguration().Region),
		"UserPoolId": props.UserPool, // error point
	})

}

```

### CDK CLI Version

 v1.112.0-devpreview

### Language

Go

### Language Version

1.6

**Comment by corymhall** [comment]
@deathquin I created a simple Go app that created a UserPool in a stack and then passed the UserPoolId down to a nested stack and did not receive an error. This makes me think that there is something else going on.

Do you get any more of a descriptive error message looking at the stack in the console? Does it fail on a particular resource?
