### ISSUE TITLE
Can't deploy, can't bootstrap (requires bootstrap stack version '6' found version '4')

### ISSUE THREAD

**Issue by tamis-laan** [aws/aws-cdk#17949]
### What is the problem?

I'm trying to deploy a simple cdk stack based on `cdk init app --language=python` but I keep getting errors:

``` bash
(.venv) > cdk deploy
current credentials could not be used to assume 'arn:aws:iam::********:role/cdk-******-deploy-role-******-eu-west-1', but are for the right account. Proceeding anyway.
CdkPhlStack: deploying...
current credentials could not be used to assume 'arn:aws:iam::********:role/cdk-********-deploy-role-********-eu-west-1', but are for the right account. Proceeding anyway.

 ❌  CdkPhlStack failed: Error: CdkPhlStack: This CDK deployment requires bootstrap stack version '6', found '4'. Please run 'cdk bootstrap'.
    at CloudFormationDeployments.validateBootstrapStackVersion (/home/******/.config/yarn/global/node_modules/aws-cdk/lib/api/cloudformation-deployments.ts:323:13)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at CloudFormationDeployments.publishStackAssets (/home/******/.config/yarn/global/node_modules/aws-cdk/lib/api/cloudformation-deployments.ts:298:7)
    at CloudFormationDeployments.deployStack (/home/*******/.config/yarn/global/node_modules/aws-cdk/lib/api/cloudformation-deployments.ts:202:5)
    at CdkToolkit.deploy (/home/tux/.config/yarn/global/node_modules/aws-cdk/lib/cdk-toolkit.ts:194:24)
    at initCommandLine (/home/tux/.config/yarn/global/node_modules/aws-cdk/bin/cdk.ts:267:9)
CdkPhlStack: This CDK deployment requires bootstrap stack version '6', found '4'. Please run 'cdk bootstrap'.
(.venv) > cdk bootstrap
 ⏳  Bootstrapping environment aws://****************/eu-west-1...
 ❌  Environment aws://***********/eu-west-1 failed bootstrapping: Error: Not downgrading existing bootstrap stack from version '4' to version '0'. Use --force to force or set the '@aws-cdk/core:newStyleStackSynthesis' feature flag in cdk.json to use the latest bootstrap version.
    at BootstrapStack.update (/home/*******/.config/yarn/global/node_modules/aws-cdk/lib/api/bootstrap/deploy-bootstrap.ts:68:13)
    at Bootstrapper.legacyBootstrap (/home/***********/.config/yarn/global/node_modules/aws-cdk/lib/api/bootstrap/bootstrap-environment.ts:61:20)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at /home/tux/.config/yarn/global/node_modules/aws-cdk/lib/cdk-toolkit.ts:464:24
    at async Promise.all (index 0)
    at CdkToolkit.bootstrap (/home/tux/.config/yarn/global/node_modules/aws-cdk/lib/cdk-toolkit.ts:461:5)
    at initCommandLine (/home/tux/.config/yarn/global/node_modules/aws-cdk/bin/cdk.ts:267:9)
Not downgrading existing bootstrap stack from version '4' to version '0'. Use --force to force or set the '@aws-cdk/core:newStyleStackSynthesis' feature flag in cdk.json to use the latest bootstrap version.
```

Versions:
``` bash 
> cdk --version
1.134.0 (build dd5e12d)
>  aws --version
aws-cli/2.4.5 Python/3.8.8 Linux/5.10.79-1-MANJARO exe/x86_64.manjaro prompt/off
```

### Reproduction Steps

cdk deploy
cdk bootstrap

### What did you expect to happen?

Deployment of my stack

### What actually happened?

I got an error

### CDK CLI Version

1.134.0 (build dd5e12d)

### Node.js Version

v16.11.1

### OS

Linux

### Language

Python

**Comment by smaud** [comment]
Yeah aws-cdk@2.x is broken. 
I have a clean unbootstrapped repo and account and it fails to create the s3 bucket on bootstrap.

**Comment by smaud** [comment]
Ok, so when I upgraded to CDK v2.2 i needed to un bootstrap by deleting the CDKToolkit cloudformation remembering to delete the bucket (which doesn't get deleted by default) and then re-bootstrapping. That seemed to fix the issue.

**Comment by skinny85** [comment]
@tamis-laan I believe you're using the new-style synthesis feature flag in your CDK application as turned 'on'. Because of that, you need to bootstrap your CDK application with the new bootstrap Stack. You should be able to do that using the command `npx cdk@2.1.0 bootstrap`.

Thanks,
Adam

**Comment by rix0rrr** [comment]
@tamis-laan what skinny85 said is true. You are using the CLI 1.x with the framework 2.x, and the defaults are different.

Upgrade to CLI 2.x or do what the error message said:

```
Not downgrading existing bootstrap stack from version '4' to version '0'. Use --force to force or set the '@aws-cdk/core:newStyleStackSynthesis' feature flag in cdk.json to use the latest bootstrap version.
```

**Comment by mzaatar** [comment]
Setting the `@aws-cdk/core:newStyleStackSynthesis` didn't solve my issue:
For reference, this is my issue:
❌  Environment aws://{AWSAccountNumber}/ap-southeast-2 failed bootstrapping: Error: Not downgrading existing bootstrap stack from version '10' to version '9'. Use --force to force or set the '@aws-cdk/core:newStyleStackSynthesis' feature flag in cdk.json to use the latest bootstrap version.
    at BootstrapStack.update (/MyProjectPath/infrastructure/node_modules/aws-cdk/lib/api/bootstrap/deploy-bootstrap.ts:68:13)
    at Bootstrapper.modernBootstrap (/MyProjectPath/infrastructure/node_modules/aws-cdk/lib/api/bootstrap/bootstrap-environment.ts:136:20)
    at /MyProjectPath/infrastructure/node_modules/aws-cdk/lib/cdk-toolkit.ts:464:24
    at async Promise.all (index 0)
    at CdkToolkit.bootstrap (/MyProjectPath/infrastructure/node_modules/aws-cdk/lib/cdk-toolkit.ts:461:5)
    at initCommandLine (/MyProjectPath/infrastructure/node_modules/aws-cdk/bin/cdk.ts:267:9)
Not downgrading existing bootstrap stack from version '10' to version '9'. Use --force to force or set the '@aws-cdk/core:newStyleStackSynthesis' feature flag in cdk.json to use the latest bootstrap version.

**Comment by avibait** [comment]
@mzaatar did you figure this one out yet? I was having the same issue (even after setting` @aws-cdk/core:newStyleStackSynthesis`), and resolved it by updating the "aws-cdk" version in package.json > devDependencies from "^1.130.0"  to  "^1.143.0".

**Comment by mzaatar** [comment]
@avibait Nope. I ended up deleting my CDK bootstrap and recreate it

**Comment by mzaatar** [comment]
After battling with this one for a while on a couple of projects, we found that upgrading `aws-cdk` and `aws-cdk-lib` to `^2.13.0` solved our problem.
