### ISSUE TITLE
(aws_cdk.aws_dynamodb): adding replication_regions to Table construct causes build/deploy errors

### ISSUE THREAD

**Issue by vitaliknet** [aws/aws-cdk#17962]
### General Issue

"sam-beta-cdk build" fails with replication_regions defined in aws_dynamodb.Table 

### The Question

sam-beta-cdk build fails with replication_regions parameter, but builds successfully when replication_regions line is commented out. 

```python
from aws_cdk import App, Stack
from aws_cdk import aws_dynamodb as dynamodb

from constructs import Construct

class MyStack(Stack):
    def __init__(self, scope: Construct, construct_id: str, **kwargs) -> None:
        super().__init__(scope, construct_id, **kwargs)

        global_table = dynamodb.Table(self, "Table",
            partition_key=dynamodb.Attribute(name="id", type=dynamodb.AttributeType.STRING),
            replication_regions=["us-east-1", "us-west-2"]
        )

app = App()
MyStack(app, "dynamodb-test")

app.synth()
```

sam-beta-cdk build

```
Synthesizing CDK App
Traceback (most recent call last):
  File "runpy.py", line 194, in _run_module_as_main
  File "runpy.py", line 87, in _run_code
  File "C:\Program Files\Amazon\AWSSAMCLI_BETA_CDK\runtime\lib\site-packages\samcli\__main__.py", line 12, in <module>
    cli(prog_name="sam")
  File "C:\Program Files\Amazon\AWSSAMCLI_BETA_CDK\runtime\lib\site-packages\click\core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "C:\Program Files\Amazon\AWSSAMCLI_BETA_CDK\runtime\lib\site-packages\click\core.py", line 782, in main
    rv = self.invoke(ctx)
  File "C:\Program Files\Amazon\AWSSAMCLI_BETA_CDK\runtime\lib\site-packages\click\core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "C:\Program Files\Amazon\AWSSAMCLI_BETA_CDK\runtime\lib\site-packages\click\core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Program Files\Amazon\AWSSAMCLI_BETA_CDK\runtime\lib\site-packages\click\core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "C:\Program Files\Amazon\AWSSAMCLI_BETA_CDK\runtime\lib\site-packages\samcli\lib\iac\utils\helpers.py", line 50, in wrapper
    iac_plugin, project = get_iac_plugin(project_type, kwargs, with_build)
  File "C:\Program Files\Amazon\AWSSAMCLI_BETA_CDK\runtime\lib\site-packages\samcli\lib\iac\utils\helpers.py", line 40, in get_iac_plugin
    project = iac_plugin.get_project(lookup_paths)
  File "C:\Program Files\Amazon\AWSSAMCLI_BETA_CDK\runtime\lib\site-packages\samcli\lib\iac\cdk\plugin.py", line 114, in get_project
    project = self._get_project_from_cloud_assembly(cloud_assembly_dir)
  File "C:\Program Files\Amazon\AWSSAMCLI_BETA_CDK\runtime\lib\site-packages\samcli\lib\iac\cdk\plugin.py", line 211, in _get_project_from_cloud_assembly
    stacks: List[Stack] = [self._build_stack(cloud_assembly, ca_stack) for ca_stack in cloud_assembly.stacks]
  File "C:\Program Files\Amazon\AWSSAMCLI_BETA_CDK\runtime\lib\site-packages\samcli\lib\iac\cdk\plugin.py", line 211, in <listcomp>
    stacks: List[Stack] = [self._build_stack(cloud_assembly, ca_stack) for ca_stack in cloud_assembly.stacks]
  File "C:\Program Files\Amazon\AWSSAMCLI_BETA_CDK\runtime\lib\site-packages\samcli\lib\iac\cdk\plugin.py", line 232, in _build_stack
    self._build_resources_section(assets, ca_stack, cloud_assembly, section, section_dict)
  File "C:\Program Files\Amazon\AWSSAMCLI_BETA_CDK\runtime\lib\site-packages\samcli\lib\iac\cdk\plugin.py", line 292, in _build_resources_section
    asset = assets[asset_path]
KeyError: 'dynamodbtestawscdkawsdynamodbReplicaProviderEE4E8EAD.nested.template.json'
```

### CDK CLI Version

2.1.0 (build f4f18b1)

### Node.js Version

14.5.0, same results with 16.3.0

### OS

Windows 10

### Language

Python

### Language Version

3.8.5

### Other information

I came across this error in an attempt to troubleshoot cdk deploy failure of a more complex CDK app with multiple stages/stacks. When replication_regions is defined in aws_dynamodb.Table, the nested replication stack fails to create IsCompleteHandler7073F4DA and OnEventHandler42BEBAE0 resources:

```
Resource handler returned message: "Uploaded file must be a non-empty zip (Service: Lambda, Status Code: 400, Request ID: c2cd5506-2d68-4862-967f-2a61a8ab9b5e, Extended Request ID: null)" (RequestToken: 9e70ee27-c2b2-a433-6301-1db455fc1438, HandlerErrorCode: InvalidRequest)

Resource handler returned message: "Uploaded file must be a non-empty zip (Service: Lambda, Status Code: 400, Request ID: 87ddb923-6358-4643-b5a8-a1dca704bb44, Extended Request ID: null)" (RequestToken: 86c51774-2eca-3f8c-85bc-ce8d9c7ab84b, HandlerErrorCode: InvalidRequest)
```

**Comment by skinny85** [comment]
Hey @vitaliknet,

thanks for opening the issue. To help me pin-down the problem, can you tell me whether you get the same problem when using pure CDK, without `sam-beta-cdk`? So, when running `cdk synth` / `cdk deploy`?

Thanks,
Adam

**Comment by vitaliknet** [comment]
Hi @skinny85 -

the issue was indeed coming from sam-beta-cdk, as discussed in https://github.com/aws/aws-sam-cli/issues/2849

The original "Uploaded file must be a non-empty zip" issue was related to node version, addressed in https://github.com/serverless/serverless/issues/8772#issuecomment-825698908.

Thanks!
