### ISSUE TITLE
cdk deploy fails with "unexpected: --output is required" after upgrade to macOS 12.1

### ISSUE THREAD

**Issue by r0bs** [aws/aws-cdk#18008]
### General Issue

cdk deploy fails with `unexpected: --output is required` after upgrade to macOS 12.1

### The Question

After upgrading to macOS 12.1 running `cdk deploy` fails with
```
unexpected: --output is required
Error: unexpected: --output is required
    at Object.execProgram (/Users/omittedPath/cdk/node_modules/aws-cdk/lib/api/cxapp/exec.ts:69:11)
    at CloudExecutable.doSynthesize (/Users/omittedPath/cdk/node_modules/aws-cdk/lib/api/cxapp/cloud-executable.ts:71:24)
    at CloudExecutable.synthesize (/Users/omittedPath/cdk/node_modules/aws-cdk/lib/api/cxapp/cloud-executable.ts:57:29)
    at CdkToolkit.selectStacksForDeploy (/Users/omittedPath/cdk/node_modules/aws-cdk/lib/cdk-toolkit.ts:486:22)
    at CdkToolkit.deploy (/Users/omittedPath/cdk/node_modules/aws-cdk/lib/cdk-toolkit.ts:120:20)
    at initCommandLine (/Users/omittedPath/cdk/node_modules/aws-cdk/bin/cdk.ts:267:9)
```

cdk synth runs successfully, though

### CDK CLI Version

1.134.0 (build dd5e12d)

### Node.js Version

v14.15.4

### OS

macOs 12.1

### Language

Typescript

### Language Version

4.4.3

**Comment by r0bs** [comment]
It started working again, I can't reproduce it and will close this issue.
