### ISSUE TITLE
(aws-events): EventBus no longer generates a name if needed

### ISSUE THREAD

**Issue by ChrisSargent** [aws/aws-cdk#18070]
### What is the problem?

Before v1.29.0, when creating an EventBus without giving a specified name, cdk would generate one automatically (or if using `cdk.physicalName.GENERATE_IF_NEEDED`

A change made in v1.29.0 here, changed that behaviour: https://github.com/aws/aws-cdk/commit/707fa003a458039878a1ae5173b6665a84c1170b#diff-e578aba9e8d0d3ee80700fb06d4ab56133d869f88887efd65941d6e2e90bec98

The 'offending' line seems to be line 280 where the addition `return` was added.

### Reproduction Steps

I have create a minimal reproduction here:

Working version: https://github.com/ChrisSargent/cdk-issues/tree/cdkv1-working

Failing version: https://github.com/ChrisSargent/cdk-issues/tree/cdkv1-failing

Diff showing only package versions changed:https://github.com/ChrisSargent/cdk-issues/compare/cdkv1-working...cdkv1-failing 

FYI commenting lines 279 - 281 'fixes' this particular issue but I'm not sure if that is the right long-term fix.

### What did you expect to happen?

The physical name to be generated

### What actually happened?

Synth Errors:

```
/cdk-issues/node_modules/@aws-cdk/core/lib/runtime.ts:134
      throw new CfnSynthesisError(message);
            ^
Error: Resolution error: Supplied properties not correct for "CfnEventBusProps"
  name: required but missing.
    at ValidationResult.assertSuccess (/cdk-issues/node_modules/@aws-cdk/core/lib/runtime.ts:134:13)
    at cfnEventBusPropsToCloudFormation (/cdk-issues/node_modules/@aws-cdk/aws-events/lib/events.generated.ts:523:43)
    at CfnEventBus.renderProperties (/cdk-issues/node_modules/@aws-cdk/aws-events/lib/events.generated.ts:608:16)
    at PostResolveToken.ret.Resources [as processor] (/cdk-issues/node_modules/@aws-cdk/core/lib/cfn-resource.ts:226:40)
    at PostResolveToken.postProcess (/cdk-issues/node_modules/@aws-cdk/core/lib/util.ts:92:17)
    at Object.postProcess (/cdk-issues/node_modules/@aws-cdk/core/lib/private/resolve.ts:122:78)
    at DefaultTokenResolver.resolveToken (/cdk-issues/node_modules/@aws-cdk/core/lib/resolvable.ts:84:32)
    at resolve (/cdk-issues/node_modules/@aws-cdk/core/lib/private/resolve.ts:212:51)
    at Object.resolve (/cdk-issues/node_modules/@aws-cdk/core/lib/private/resolve.ts:119:77)
    at resolve (/cdk-issues/node_modules/@aws-cdk/core/lib/private/resolve.ts:230:47)
Subprocess exited with error 1
```

### CDK CLI Version

1.129.0

### Node.js Version

14

### OS

MacOs

### Language

Typescript

### Other information

Original PR: https://github.com/aws/aws-cdk/pull/17008

**Comment by andersonmgomes** [comment]
Hello there!

I have encountered the issue and I believe it can be resolved by making some modifications to the "events.generated.ts" file. Specifically, line 2526 needs to be updated with the following code:

` this.statement = props.statement.toJSON();
`

However, the challenge I am facing is that this file is automatically generated and I am unable to locate its source. 

Is there anyone who can assist me in finding the source and resolving this issue?
