### ISSUE TITLE
(codebuild): NoArtifacts is not possible anymore with cdk v2

### ISSUE THREAD

**Issue by eriktisme** [aws/aws-cdk#18089]
### What is the problem?

When upgrading to AWS-CDK v2 I've run into the issue that the class NoArtifacts is not exported.

```
Error: Package subpath './aws-codebuild/lib/no-artifacts' is not defined by "exports" in /Users/evandam/dev/code/eriktisme/aws-cdk-v2-codebuild-project-no-artifacts-issue/node_modules/aws-cdk-lib/package.json
    at new NodeError (node:internal/errors:371:5)
    at throwExportsNotFound (node:internal/modules/esm/resolve:440:9)
    at packageExportsResolve (node:internal/modules/esm/resolve:692:3)
    at resolveExports (node:internal/modules/cjs/loader:482:36)
    at Function.Module._findPath (node:internal/modules/cjs/loader:522:31)
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:919:27)
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/Users/evandam/dev/code/eriktisme/aws-cdk-v2-codebuild-project-no-artifacts-issue/lib/example-stack.ts:4:1)
Subprocess exited with error 1
```

### Reproduction Steps

1. Clone the replication repo https://github.com/eriktisme/aws-cdk-v2-codebuild-project-no-artifacts-issue
2. Run the command `npm run cdk list`
3. See the error message pop up in the terminal

### What did you expect to happen?

Be able to set code build project artifacts to no artifacts as in aws-cdk v1.

### What actually happened?

I receive the following exception in the terminal

```
Error: Package subpath './aws-codebuild/lib/no-artifacts' is not defined by "exports" in /Users/evandam/dev/code/eriktisme/aws-cdk-v2-codebuild-project-no-artifacts-issue/node_modules/aws-cdk-lib/package.json
    at new NodeError (node:internal/errors:371:5)
    at throwExportsNotFound (node:internal/modules/esm/resolve:440:9)
    at packageExportsResolve (node:internal/modules/esm/resolve:692:3)
    at resolveExports (node:internal/modules/cjs/loader:482:36)
    at Function.Module._findPath (node:internal/modules/cjs/loader:522:31)
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:919:27)
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/Users/evandam/dev/code/eriktisme/aws-cdk-v2-codebuild-project-no-artifacts-issue/lib/example-stack.ts:4:1)
Subprocess exited with error 1
```

### CDK CLI Version

2.2.0 (build 4f5c27c)

### Node.js Version

v16.13.1

### OS

MacOS 12.0.1

### Language

Typescript

### Language Version

~3.9.7

**Comment by skinny85** [comment]
Hey @eriktisme,

thanks for opening the issue. The class `NoArtifacts` is actually [not exported from the CodeBuild module](https://github.com/aws/aws-cdk/blob/65da9e1a7e84265820ab1acdc075fb3558c99fcc/packages/%40aws-cdk/aws-codebuild/lib/no-artifacts.ts#L11-L11), regardless whether it's CDK v1, or v2.

The way to achieve this is to simply pass nothing (or `undefined`) for the `artifacts` property.

Thanks,
Adam

**Comment by peterwoodworth** [comment]
To add to this - This was never intended to be used by the user according to the comment in the source code

https://github.com/aws/aws-cdk/blob/32f1c807a34464e8c13a8d03bfdcb6a3006f51ba/packages/%40aws-cdk/aws-codebuild/lib/no-artifacts.ts#L8-L11

**Comment by eriktisme** [comment]
@peterwoodworth and @skinny85 Thank you! I didn't know, thank you for clarifying.
