### ISSUE TITLE
(efs): fileSystem for lambda cannot be referenced from access point ARN

### ISSUE THREAD

**Issue by ttais2017** [aws/aws-cdk#18113]
### What is the problem?

`AccessPoint.fromAccessPointId` and `AccessPoint.fromAccessPointAttributes` do not allow to 'load' the access point.  

Using one of those methods for loading the access point, the same exception is thrown:  `fileSystem is not available when 'fromAccessPointId()' is used. Use 'fromAccessPointAttributes()' instead `

### Reproduction Steps

Java Code
```java
    String accessPointId = Fn.importValue(parent + Constants.__EV_ACCESS_POINT_ARN);
    IAccessPoint accessPoint = AccessPoint.fromAccessPointId(this, "ap4lambda", accessPointId);
    fs = software.amazon.awscdk.services.lambda.FileSystem.fromEfsAccessPoint(accessPoint, "/mnt/efs");
```
Exception
```
Caused by: software.amazon.jsii.JsiiException: fileSystem is not available when 'fromAccessPointId()' is used. Use 'fromAccessPointAttributes()' instead   
Error: fileSystem is not available when 'fromAccessPointId()' is used. Use 'fromAccessPointAttributes()' instead                                           
    at ImportedAccessPoint.get fileSystem [as fileSystem] (C:\TEMP\jsii-kernel-agO7DV\node_modules\@aws-cdk\aws-efs\lib\access-point.js:99:19)             
    at Function.fromEfsAccessPoint (C:\TEMP\jsii-kernel-agO7DV\node_modules\@aws-cdk\aws-lambda\lib\filesystem.js:34:29)                                   
    at C:\TEMP\jsii-java-runtime710286648045078614\lib\program.js:8269:114                                                                                 
    at Kernel._wrapSandboxCode (C:\TEMP\jsii-java-runtime710286648045078614\lib\program.js:8860:24)                                                        
    at C:\TEMP\jsii-java-runtime710286648045078614\lib\program.js:8269:87                                                                                  
    at Kernel._ensureSync (C:\TEMP\jsii-java-runtime710286648045078614\lib\program.js:8841:28)                                                             
    at Kernel.sinvoke (C:\TEMP\jsii-java-runtime710286648045078614\lib\program.js:8269:34)                                                                 
    at KernelHost.processRequest (C:\TEMP\jsii-java-runtime710286648045078614\lib\program.js:9757:36)                                                      
    at KernelHost.run (C:\TEMP\jsii-java-runtime710286648045078614\lib\program.js:9720:22)                                                                 
    at Immediate._onImmediate (C:\TEMP\jsii-java-runtime710286648045078614\lib\program.js:9721:46)                                                         
    at software.amazon.jsii.JsiiRuntime.processErrorResponse (JsiiRuntime.java:124)                                                                        
    at software.amazon.jsii.JsiiRuntime.requestResponse (JsiiRuntime.java:95)                                                                              
    at software.amazon.jsii.JsiiClient.callStaticMethod (JsiiClient.java:168)                                                                              
    at software.amazon.jsii.JsiiObject.jsiiStaticCall (JsiiObject.java:187)                                                                                
    at software.amazon.jsii.JsiiObject.jsiiStaticCall (JsiiObject.java:166)                                                                                
    at software.amazon.awscdk.services.lambda.FileSystem.fromEfsAccessPoint (FileSystem.java:71)                                                           
    at de.materna.aws.cdk.lamp.ResourcesNestedStack.importEfsAccessPoint (ResourcesNestedStack.java:83)                                                    
```

Following the suggestion (use fromAccessPointAttributes instead):
```java
    accessPointArn = Fn.importValue(parent + Constants.__EV_ACCESS_POINT_ARN);
    IAccessPoint accessPoint = AccessPoint.fromAccessPointAttributes(this, "ap4lambda",
        AccessPointAttributes.builder()
            .accessPointArn(accessPointArn)
            .build());
    fs = software.amazon.awscdk.services.lambda.FileSystem.fromEfsAccessPoint(accessPoint, "/mnt/efs");
```

The same exception  (by using fromAccessPointId):
```
Caused by: software.amazon.jsii.JsiiException: fileSystem is not available when 'fromAccessPointId()' is used. Use 'fromAccessPointAttributes()' instead      
Error: fileSystem is not available when 'fromAccessPointId()' is used. Use 'fromAccessPointAttributes()' instead                                              
    at ImportedAccessPoint.get fileSystem [as fileSystem] (C:\TEMP\jsii-kernel-gE2MK3\node_modules\@aws-cdk\aws-efs\lib\access-point.js:99:19)                
    at Function.fromEfsAccessPoint (C:\TEMP\jsii-kernel-gE2MK3\node_modules\@aws-cdk\aws-lambda\lib\filesystem.js:34:29)                                      
    at C:\TEMP\jsii-java-runtime13586202064559895875\lib\program.js:8269:114                                                                                  
    at Kernel._wrapSandboxCode (C:\TEMP\jsii-java-runtime13586202064559895875\lib\program.js:8860:24)                                                         
    at C:\TEMP\jsii-java-runtime13586202064559895875\lib\program.js:8269:87                                                                                   
    at Kernel._ensureSync (C:\TEMP\jsii-java-runtime13586202064559895875\lib\program.js:8841:28)                                                              
    at Kernel.sinvoke (C:\TEMP\jsii-java-runtime13586202064559895875\lib\program.js:8269:34)                                                                  
    at KernelHost.processRequest (C:\TEMP\jsii-java-runtime13586202064559895875\lib\program.js:9757:36)                                                       
    at KernelHost.run (C:\TEMP\jsii-java-runtime13586202064559895875\lib\program.js:9720:22)                                                                  
    at Immediate._onImmediate (C:\TEMP\jsii-java-runtime13586202064559895875\lib\program.js:9721:46)                                                          
    at software.amazon.jsii.JsiiRuntime.processErrorResponse (JsiiRuntime.java:124)                                                                           
    at software.amazon.jsii.JsiiRuntime.requestResponse (JsiiRuntime.java:95)                                                                                 
    at software.amazon.jsii.JsiiClient.callStaticMethod (JsiiClient.java:168)                                                                                 
    at software.amazon.jsii.JsiiObject.jsiiStaticCall (JsiiObject.java:187)                                                                                   
    at software.amazon.jsii.JsiiObject.jsiiStaticCall (JsiiObject.java:166)                                                                                   
    at software.amazon.awscdk.services.lambda.FileSystem.fromEfsAccessPoint (FileSystem.java:71)                                                              
    at de.materna.aws.cdk.lamp.ResourcesNestedStack.importEfsAccessPoint (ResourcesNestedStack.java:87)                                                       
```
### What did you expect to happen?

I would expect to be able to load the access point using its ARN.

### What actually happened?

an exception will be thrown.  :(

### CDK CLI Version
cdk 2.2.0

### Framework Version
1.135.0

### Node.js Version
N/A

### OS
Windows

### Language
Java

### Language Version
Java 11

**Comment by NGL321** [comment]
Hey @ttais2017,

Your latter approach is the correct one. Many of our `XXX.fromXXXXId` functions do not perform complete imports like the `XXX.fromXXXXAttributes` functions. However, receiving the same error message when attempting with that method makes me think there is either a bug in the construct or in JSII itself. Moreover, from your stack trace, its clear that the code was indeed changed at the time of rebuild

To confirm/clarify, could you try removing all installed cdk packages from the project and importing them from Maven again? There is a slim chance that this is caused by improper imports or version disparity between packages.

If that doesnt work, then we will treat this as a bug in the construct until we either confirm or determine that it is a JSII bug.

**Comment by ttais2017** [comment]
After cleaning my maven environment, the behaviour is the same.  The same exception.  :( 
I would say. that's a bug !

**Comment by kaizen3031593** [comment]
Hi @ttais2017, the error you see is in the source code here: https://github.com/aws/aws-cdk/blob/d22933bdf8b9d7b030657ba77a74fd97abef09ae/packages/%40aws-cdk/aws-efs/lib/access-point.ts#L270

I agree that this is a poor message since it does not provide the full picture. To access the file system of an imported access point, you need to use the `fromAccessPointAttributes()` API, as suggested, _and_ pass in the file system as one of the attributes. We cannot actually get the file system from just the arn, unfortunately.

Hope that helps. I will update the error message to be more descriptive.
