### ISSUE TITLE
(redshift): modifyClusterIamRoles with unexpected key 'DefaultIamRoleArn' found in params

### ISSUE THREAD

**Issue by clementy-aws** [aws/aws-cdk#18186]
### What is the problem?

The Lambda code
```
// Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
// SPDX-License-Identifier: MIT-0

const AWS = require('aws-sdk');
const redshift = new AWS.Redshift();

exports.handler = async event => {
    const clusterId = event.ResourceProperties.ClusterIdentifier;
    const roleArn = event.ResourceProperties.RoleArn;

    var data = await redshift.describeClusters({ ClusterIdentifier: clusterId }).promise();
    if (data.Clusters.length != 1) {
        throw new Error(`Unable to find cluster ${clusterId}`);
    }

    console.log(`Set this role as default ${roleArn}`)
    await redshift.modifyClusterIamRoles({
         ClusterIdentifier: clusterId,
         DefaultIamRoleArn: roleArn
    }).promise();
    console.log(`Cluster ${clusterId} default role set.`)
};
```

The error log:
```
Reason: "UnexpectedParameter: Unexpected key 'DefaultIamRoleArn' found in params\n" +
    '    at ParamValidator.fail (/var/runtime/node_modules/aws-sdk/lib/param_validator.js:50:37)\n' +
    '    at ParamValidator.validateStructure (/var/runtime/node_modules/aws-sdk/lib/param_validator.js:77:14)\n' +
    '    at ParamValidator.validateMember (/var/runtime/node_modules/aws-sdk/lib/param_validator.js:88:21)\n' +
    '    at ParamValidator.validate (/var/runtime/node_modules/aws-sdk/lib/param_validator.js:34:10)\n' +
    '    at Request.VALIDATE_PARAMETERS (/var/runtime/node_modules/aws-sdk/lib/event_listeners.js:132:42)\n' +
    '    at Request.callListeners (/var/runtime/node_modules/aws-sdk/lib/sequential_executor.js:106:20)\n' +
    '    at callNextListener (/var/runtime/node_modules/aws-sdk/lib/sequential_executor.js:96:12)\n' +
    '    at /var/runtime/node_modules/aws-sdk/lib/event_listeners.js:86:9\n' +
    '    at finish (/var/runtime/node_modules/aws-sdk/lib/config.js:386:7)\n' +
    '    at /var/runtime/node_modules/aws-sdk/lib/config.js:404:9',
```

Also tried the following CLI:
```
aws redshift modify-cluster-iam-roles \
--cluster-identifier ${CLUSTER_ID} \
--default-iam-role-arn ${ROLE_ARN}
```

It complains:
```
Unknown options: --default-iam-role-arn, 
```

Where I have:
```
clementy@ cdk-redshift % aws --version
aws-cli/2.2.42 Python/3.8.8 Darwin/20.6.0 exe/x86_64 prompt/off
```

### Reproduction Steps

As explained in the above section.

### What did you expect to happen?

The default role of redshift should be properly set.

### What actually happened?

See the exception in the first section.

### CDK CLI Version

2.3.0

### Node.js Version

v16.10.0

### OS

macOS 11.6.2

### Language

Typescript

### Language Version

Javascript

**Comment by ryparker** [comment]
This is a bug of the SDK not CDK (Cloud Development Kit). CDK is a CloudFormation template generator. [Report an issue with aws-sdk here](https://github.com/aws/aws-sdk-js/issues/new/choose)
