### ISSUE TITLE
(maybe lambda): Pipeline stack which uses cross-environment actions must have an explicitly set region

### ISSUE THREAD

**Issue by gburke-ppb** [aws/aws-cdk#18439]
### What is the problem?

Using aws-cdk 1.139.0 we are getting the error `Pipeline stack which uses cross-environment actions must have an explicitly set region` when running some unit tests.  Locking to 1.138.0 or before doesn't show this issue.

### Reproduction Steps

Being thrown due to this code, it seems:

```typescript
import * as codepipeline from '@aws-cdk/aws-codepipeline';

...

private pipeline: MySinglePipeline;  // which is just an extended SinglePipeline
this.cdkStage = pipeline.pipeline.addStage(this.stageName);

...

  public withAction(addAction: (_: cdkpipelines.CdkStage) => codepipeline.IAction): MyPipelineStageBuilder<U> {
    this.effects.push( () => {
      this.cdkStage.addActions(addAction(this.cdkStage));  // << Error is thrown on this line
    });

    return this;
  }
```

```
      at Pipeline.requireRegion (node_modules/@aws-cdk/aws-codepipeline/lib/pipeline.ts:890:13)
      at Pipeline.ensureReplicationResourcesExistFor (node_modules/@aws-cdk/aws-codepipeline/lib/pipeline.ts:425:10)
      at Pipeline._attachActionToPipeline (node_modules/@aws-cdk/aws-codepipeline/lib/pipeline.ts:380:34)
      at Stage.attachActionToPipeline (node_modules/@aws-cdk/aws-codepipeline/lib/private/stage.ts:155:27)
      at Stage.addAction (node_modules/@aws-cdk/aws-codepipeline/lib/private/stage.ts:93:29)
      at CdkStage.addActions (node_modules/@aws-cdk/pipelines/lib/legacy/stage.ts:173:26)
      at     the line highlighted above
```

### What did you expect to happen?

The code to work as it has always worked

### What actually happened?

It threw an error:

```
    Pipeline stack which uses cross-environment actions must have an explicitly set region

      43 |   public withAction(addAction: (_: cdkpipelines.CdkStage) => codepipeline.IAction): TTPipelineStageBuilder<U> {
      44 |     this.effects.push( () => {
    > 45 |       this.cdkStage.addActions(addAction(this.cdkStage));
         |                     ^
      46 |     });
      47 |
      48 |     return this;

      at Pipeline.requireRegion (node_modules/@aws-cdk/aws-codepipeline/lib/pipeline.ts:890:13)
      at Pipeline.ensureReplicationResourcesExistFor (node_modules/@aws-cdk/aws-codepipeline/lib/pipeline.ts:425:10)
      at Pipeline._attachActionToPipeline (node_modules/@aws-cdk/aws-codepipeline/lib/pipeline.ts:380:34)
      at Stage.attachActionToPipeline (node_modules/@aws-cdk/aws-codepipeline/lib/private/stage.ts:155:27)
      at Stage.addAction (node_modules/@aws-cdk/aws-codepipeline/lib/private/stage.ts:93:29)
      at CdkStage.addActions (node_modules/@aws-cdk/pipelines/lib/legacy/stage.ts:173:26)
      at pipeline/common/pipeline-stage-builder.ts:45:21
```

### CDK CLI Version

2.7.0 (build cfb09d5)

### Framework Version

aws-cdk 1.139.0

### Node.js Version

any

### OS

MacOS

### Language

Typescript

**Comment by gburke-ppb** [comment]
This is being called thus:
```
    .withAction(cdkStage => {
      return new LambdaInvokeAction({
        actionName: 'invokeLambda',
        lambda: lambda.Function.fromFunctionArn(pipelineStack, 'myLambdaFunction', 'arn:aws:lambda:eu-west-1:1234:function:myLambdaFunction'),
        runOrder: cdkStage.nextSequentialRunOrder(),
      });
    })
```
in the test.

**Comment by rix0rrr** [comment]
Please show your test
