### ISSUE TITLE
(eks fargate): provider framework handler times out after 15 minutes

### ISSUE THREAD

**Issue by mvs5465** [aws/aws-cdk#18542]
### What is the problem?

When trying to deploy an EKS cluster on Fargate using the CDK this error happens: 
```
{
    "errorType": "ResourceInUseException",
    "errorMessage": "Cluster already exists with name: <cluster_name>",
    "code": "ResourceInUseException",
    "message": "Cluster already exists with name: <cluster_name>",
    "time": "2022-01-19T18:11:25.302Z",
    "requestId": "<request_id>",
    "statusCode": 409,
    "retryable": false,
    "retryDelay": 95.58207720935809,
    "stack": [
        "ResourceInUseException: Cluster already exists with name: <cluster_name>",
        "    at Object.extractError (/var/runtime/node_modules/aws-sdk/lib/protocol/json.js:52:27)",
        "    at Request.extractError (/var/runtime/node_modules/aws-sdk/lib/protocol/rest_json.js:55:8)",
        "    at Request.callListeners (/var/runtime/node_modules/aws-sdk/lib/sequential_executor.js:106:20)",
        "    at Request.emit (/var/runtime/node_modules/aws-sdk/lib/sequential_executor.js:78:10)",
        "    at Request.emit (/var/runtime/node_modules/aws-sdk/lib/request.js:688:14)",
        "    at Request.transition (/var/runtime/node_modules/aws-sdk/lib/request.js:22:10)",
        "    at AcceptorStateMachine.runTo (/var/runtime/node_modules/aws-sdk/lib/state_machine.js:14:12)",
        "    at /var/runtime/node_modules/aws-sdk/lib/state_machine.js:26:10",
        "    at Request.<anonymous> (/var/runtime/node_modules/aws-sdk/lib/request.js:38:9)",
        "    at Request.<anonymous> (/var/runtime/node_modules/aws-sdk/lib/request.js:690:12)"
    ]
}
```

Even though the cluster gets successfully created, it appears the handler times out and gets retriggered, causing this error. 

### Reproduction Steps

Recreate just by attempting to create an EKS Fargate cluster:
```
   new aws_eks.FargateCluster(this, id, {
        version: this.props.version,
        vpc: this.props.vpc,
        securityGroup: this.props.securityGroup,
        endpointAccess: EndpointAccess.PRIVATE,
        placeClusterHandlerInVpc: true,
        vpcSubnets: [{
          subnetType: SubnetType.PRIVATE_WITH_NAT
        }]
    });
```

### What did you expect to happen?

Expect handler to report successful cluster creation.

### What actually happened?

Custom resource thinks that the cluster failed to create, causing CloudFormation to roll back the entire stack and nested stack.

### CDK CLI Version

2.8.0 (build 8a5eb49)

### Node.js Version

v17.3.1

### OS

MacOS Catalina 10.15.7

### Language

Typescript

### Language Version

TypeScript 4.5.4

### Other information

Another possibly related issue is that upon rollback the handler attempts to delete the security group before it deletes the cluster, causing a failure (security group cannot be deleted until all resources using it are deleted).

**Comment by mvs5465** [comment]
Just to be clear the provider framework handler will time out after 900 seconds and retrigger, hence why I titled it this way.

**Comment by otaviomacedo** [comment]
Hi, @mvs5465. Do you see any error message in the custom resource logs? The cluster is created asynchronously, so the `onCreate()` method should return immediately. The fact that it's timing out after 15 minutes suggests that this is not happening.

**Comment by mvs5465** [comment]
Hey @otaviomacedo - I don't see any error. On the first invocation of the function the create request almost immediately returns 200. The next log message is "starting waiter" and that is the last log message until the function times out and retriggers.
