### ISSUE TITLE
(CDK Pipelines): allow passing a Role to `CodePipeline`

### ISSUE THREAD

**Issue by skinny85** [aws/aws-cdk#18549]
### Description

Because of https://github.com/aws/aws-cdk/issues/16244, customers have to sometimes create a Role manually and control its permissions.

We should make that easy in `CodePipeline`.

### Use Case

See above.

### Proposed Solution

Add a new property `role` to the `CodePipeline` construct.

### Acknowledge

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

**Comment by rix0rrr** [comment]
You can pass a `codepipeline.Pipeline` to `CodePipeline`. It can be initialized with the role you need.

**Comment by skinny85** [comment]
Yep, that's what I recommended the customer do, but it's pretty non-trivial to figure out. A property in the construct props would make it more discoverable.

**Comment by rix0rrr** [comment]
Still don't really agree. We should control better for policy size, or injecting, instead.

**Comment by pfried** [comment]
For reference: I just deployed  a fix following the advice by @skinny85 which essentially (besides a narrower policy) looks like the code below:

The stack redeployed and kept its resources. I had to pull out the cross account property tough.

```
        // Oversimplified policy
        const codePipelineRole = new Role(this, 'CodePipelineRole', {
            assumedBy: new ServicePrincipal('codepipeline.amazonaws.com'),
            inlinePolicies: {
                rootPermissions: new PolicyDocument({
                    statements: [
                        new PolicyStatement({
                            resources: ['*'],
                            actions: ['*'],
                        }),
                    ],
                }),
            }
        })

       // Need to pull out `crossAccountKeys`
        const codePipeline = new Pipeline(this, 'CodePipeline', {
            crossAccountKeys: true,
            role: codePipelineRole
        })

        const pipeline = new CodePipeline(this, 'Pipeline', {
            codePipeline: codePipeline,
            ...
        })
```

**Comment by ac259** [comment]
Hello @rix0rrr ,

I am trying to solve for the same problem; i.e to pass a role to the `pipelines.CodePipeline`. I am trying to do this in `python`.
the official cdk documentation for [CDK Pipeline](https://docs.aws.amazon.com/cdk/api/v2/python/aws_cdk.pipelines/CodePipeline.html?highlight=codepipeline#aws_cdk.pipelines.CodePipeline) Here there seems to be a `role` parameter. But in the class definition it does not seem to have it and throws and error when I `cdk deploy`

<img width="631" alt="codepipeline-site-package-function-def" src="https://user-images.githubusercontent.com/46288072/197295990-f7f20bd4-69a9-41b9-83e7-9b5add12018e.PNG">

Code Snippet.

```
class WorkshopPipelineStack(Stack):
    def __init__(self, scope: Construct, id: str, **kwargs) -> None:
        super().__init__(scope, id, **kwargs)

        codepipeline_role = iam.Role.from_role_arn(self, "Role", "arn:aws:iam::<account>:role/<pre-existing-role>",
        # Set 'mutable' to 'false' to use the role as-is and prevent adding new
        # policies to it. The default is 'true', which means the role may be
        # modified as part of the deployment.
        mutable=False
        )

        kms_key = aws_kms.Key.from_key_arn(self,"<kms-key>", "arn:aws:kms:us-east-1:account-number:key/<key>")
        pipeline_bucket = aws_s3.Bucket(self, '<bucket-name>',encryption_key=kms_key)
        
        pipeline = pipelines.CodePipeline(self,
        "<pipeline-name>",
        synth=pipelines.ShellStep(
            "Synth",
            input=pipelines.CodePipelineSource.connection("<org/repo>", "<branch>",
                connection_arn="arn:aws:codestar-connections:<connection>"
            ),
            commands=[
                "npm install -g aws-cdk",  # Installs the cdk cli on Codebuild
                "pip install -r requirements.txt",  # Instructs Codebuild to install required packages
                "cdk synth",
            ]
        ),
        role = codepipeline_role
        )
```

Error

```
Traceback (most recent call last):
  File "C:\Users\aramji\Desktop\aws-cdk\app.py", line 7, in <module>
    WorkshopPipelineStack(app, "cmg-datasvc-cdk-codepipeline-test",
  File "C:\Users\aramji\Envs\aws-cdk\lib\site-packages\jsii\_runtime.py", line 86, in __call__
    inst = super().__call__(*args, **kwargs)
  File "C:\Users\aramji\aws-cdk\cdk_workshop\pipeline_stack.py", line 41, in __init__
    pipeline = pipelines.CodePipeline(self,
  File "C:\Users\aramji\Envs\aws-cdk\lib\site-packages\jsii\_runtime.py", line 86, in __call__
    inst = super().__call__(*args, **kwargs)
TypeError: __init__() got an unexpected keyword argument 'role'

Subprocess exited with error 1
```

Could you kindly help on the same?

Thanks,
Ani

**Comment by skinny85** [comment]
@ac259 what version of CDK are you using?

**Comment by ac259** [comment]
@skinny85 I was using an older 2.x version but I upgraded to the 2.47.0 and tested again.

```
(aws-cdk) C:\Users\aramji\Desktop\aws-cdk>cdk --version
2.47.0 (build 3528e3d)
```

**Comment by skinny85** [comment]
I'm asking about the libraries, though; not the CDK CLI version. You'll find their version in the `requirements.txt` (or just `pip list`). The libraries determine whether you have access to this feature or not.

It was released in [version `2.35.0`](https://github.com/aws/aws-cdk/commit/ff3c01a85d1bd32c149e83fda5bf44ec3253e99d), so you need your libraries to be at least at that version.

**Comment by ac259** [comment]
@skinny85 thank you so much - I was on an earlier version of the library. Was able to get it to work!

**Comment by gmournos** [comment]
Hi guys,

There is about 9 roles that each pipeline instance creates. I would be very hard to reach them all and replace them through the API.
I kind of hacked into it by using a Cloudformation macro for the pipeline libary I created:

https://medium.com/@gmournos/creating-professional-aws-native-delivery-pipelines-with-cdk-c2aed59be6e7
https://medium.com/@gmournos/creating-professional-aws-native-delivery-pipelines-with-cdk-part-2-68fde253c34e

It is quite robust, I have been using it in production for one year.
I built the Medium articles as a tutorial, so if you do not want to use it as is, you can easily pick the role reassign macro from it and adjust it to your project.

Hope this helps

G Mournos
