### ISSUE TITLE
(aws-secretsmanager): splitArn is not a function

### ISSUE THREAD

**Issue by robbinswill** [aws/aws-cdk#18752]
### What is the problem?

When calling ```cdk diff``` I receive the following error: ```TypeError: core_1.Stack.of(...).splitArn is not a function```.

It appears this issue starts when trying to generate a new ServerlessCluster. It looks like secret.ts is trying to pass a secretArn into splitArn. Aside from that, I'm not too sure what the issue could be.

Apologies for the lack of insight - I'm a student and just learning AWS and CDK. Thank you for the support!

Trace:
```
cdk diff                                                                                                                 ✔ 

/blog-app/node_modules/@aws-cdk/aws-secretsmanager/lib/secret.ts:591
  const resourceName = Stack.of(construct).splitArn(secretArn, ArnFormat.COLON_RESOURCE_NAME).resourceName;
                                           ^
TypeError: core_1.Stack.of(...).splitArn is not a function
    at parseSecretNameForOwnedSecret (/blog-app/node_modules/@aws-cdk/aws-secretsmanager/lib/secret.ts:591:44)
    at new Secret (/blog-app/node_modules/@aws-cdk/aws-secretsmanager/lib/secret.ts:389:9)
    at new DatabaseSecret (/blog-app/node_modules/@aws-cdk/aws-rds/lib/database-secret.ts:37:5)
    at Object.renderCredentials (/blog-app/node_modules/@aws-cdk/aws-rds/lib/private/util.ts:95:7)
    at new ServerlessCluster (/blog-app/node_modules/@aws-cdk/aws-rds/lib/serverless-cluster.ts:344:25)
    at new BlogAppStack (/blog-app/lib/blog-app-stack.ts:27:21)
    at Object.<anonymous> (/blog-app/bin/blog-app.ts:7:1)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Module.m._compile (/blog-app/node_modules/ts-node/src/index.ts:1056:23)
    at Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
Subprocess exited with error 1

```
blog-app-stack.ts:
```
import * as cdk from '@aws-cdk/core';
import * as ec2 from '@aws-cdk/aws-ec2';
import * as lambda from '@aws-cdk/aws-lambda';
import * as rds from '@aws-cdk/aws-rds';
import * as appsync from '@aws-cdk/aws-appsync';

export class BlogAppStack extends cdk.Stack {
  constructor(scope: cdk.Construct, id: string, props?: cdk.StackProps) {
    super(scope, id, props);

    // api
    const api = new appsync.GraphqlApi(this, 'Api', {
      name: 'appsync-blog-backend',
      schema: appsync.Schema.fromAsset('graphql/schema.graphql'),
      authorizationConfig: {
        defaultAuthorization: {
          authorizationType: appsync.AuthorizationType.API_KEY,
          apiKeyConfig: {
            name: 'blog-apikey'
          }
        }
      }
    });

    // virtual private cloud & cluster
    const vpc = new ec2.Vpc(this, 'BlogAppVpc');
    const cluster = new rds.ServerlessCluster(this, 'AuroraBlogCluster', {
      engine: rds.DatabaseClusterEngine.AURORA_POSTGRESQL,
      parameterGroup: rds.ParameterGroup.fromParameterGroupName(this, 'ParameterGroup', 'default.aurora-postgresql10'),
      defaultDatabaseName: 'BlogDB',
      vpc
    });

    // declare a lambda function
    const postFn = new lambda.Function(this, 'MyFunction', {
      runtime: lambda.Runtime.NODEJS_10_X,
      code: new lambda.AssetCode('lambda-fns'),
      handler: 'index.handler',
      memorySize: 1024,
      environment: {
        CLUSTER_ARN: cluster.clusterArn,
        SECRET_ARN: cluster.secret?.secretArn || '',
        DB_NAME: 'BlogDB',
        AWS_NODEJS_CONNECTION_REUSE_ENABLED: '1'
      }
    });

    // grant access to the cluster from the lambda function
    cluster.grantDataApiAccess(postFn);
    // set the new lambda function as a data source for the AppSync API
    const lambdaDs = api.addLambdaDataSource('lambdaDatasource', postFn);

    // create lambda datasource resolvers
    lambdaDs.createResolver({
      typeName: 'Query',
      fieldName: 'listPosts'
    });
    lambdaDs.createResolver({
      typeName: 'Query',
      fieldName: 'getPostById'
    });
    lambdaDs.createResolver({
      typeName: 'Mutation',
      fieldName: 'createPost'
    });
    lambdaDs.createResolver({
      typeName: 'Mutation',
      fieldName: 'updatePost'
    });
    lambdaDs.createResolver({
      typeName: 'Mutation',
      fieldName: 'deletePost'
    });

    // output information to cli instead of having to go to aws console
    new cdk.CfnOutput(this, 'AppSyncAPIURL', {
      value: api.graphqlUrl
    });
    new cdk.CfnOutput(this, 'AppSyncAPIKey', {
      value: api.apiKey || ''
    });
    new cdk.CfnOutput(this, 'ProjectRegion', {
      value: this.region
    });

  }
}
```
package.json:
```
{
  "name": "blog-app",
  "version": "0.1.0",
  "bin": {
    "blog-app": "bin/blog-app.js"
  },
  "scripts": {
    "build": "tsc",
    "watch": "tsc -w",
    "test": "jest",
    "cdk": "cdk"
  },
  "devDependencies": {
    "@aws-cdk/assert": "1.87.1",
    "@types/jest": "^26.0.10",
    "@types/node": "10.17.27",
    "aws-cdk": "1.87.1",
    "jest": "^26.4.2",
    "ts-jest": "^26.2.0",
    "ts-node": "^9.0.0",
    "typescript": "~3.9.7"
  },
  "dependencies": {
    "@aws-cdk/aws-appsync": "^1.142.0",
    "@aws-cdk/aws-ec2": "^1.142.0",
    "@aws-cdk/aws-lambda": "^1.142.0",
    "@aws-cdk/aws-rds": "^1.142.0",
    "@aws-cdk/core": "1.87.1",
    "source-map-support": "^0.5.16"
  }
}
```

### Reproduction Steps

Calling ```cdk diff``` with the given project and package versions.

### What did you expect to happen?

CloudFormation assets ready to be deployed.

### What actually happened?

TypeError: core_1.Stack.of(...).splitArn is not a function

### CDK CLI Version

1.87.1 (build 9eeaa93)

### Node.js Version

v16.13.1

### OS

Manjaro Linux

### Language

Typescript

### Language Version

3.9.7

### Other information

https://github.com/dabit3/graphql-api-cdk-serverless-postgres
This is the tutorial I'm trying to follow.

**Comment by robbinswill** [comment]
I think I've "fixed it".
First I ran ```sudo npm uninstall -g aws-cdk``` followed by ```sudo npm install -g aws-cdk```.
Then I updated my package.json:
```
{
  "name": "blog-app",
  "version": "0.1.0",
  "bin": {
    "blog-app": "bin/blog-app.js"
  },
  "scripts": {
    "build": "tsc",
    "watch": "tsc -w",
    "test": "jest",
    "cdk": "cdk"
  },
  "devDependencies": {
    "@types/jest": "^26.0.10",
    "@types/node": "10.17.27",
    "jest": "^26.4.2",
    "ts-jest": "^26.2.0",
    "aws-cdk": "2.10.0",
    "ts-node": "^9.0.0",
    "typescript": "~3.9.7"
  },
  "dependencies": {
    "@aws-cdk/aws-appsync": "1.73.0",
    "@aws-cdk/aws-ec2": "1.73.0",
    "@aws-cdk/aws-lambda": "1.73.0",
    "@aws-cdk/aws-rds": "1.73.0",
    "@aws-cdk/core": "1.73.0",
    "source-map-support": "^0.5.16"
  }
}
```
It might not be the prettiest solution but at least I can carry on with the tutorial.

**Comment by hariranjitkar** [comment]
Hi robbinswill, I am facing similar issue with splitArn and uninstalled and reintalled aws-cdk and changed the dependencies but still I have the error that says "TypeError: core_1.Stack.of(...).splitArn is not a function
    at Function.fromUserPoolArn" . Is there any other solution for this issue?
