### ISSUE TITLE
(aws-codepipeline): Cannot use cross-account/cross-region S3 bucket for S3DeployAction

### ISSUE THREAD

**Issue by jzybert** [aws/aws-cdk#18945]
### What is the problem?

I have a `PipelineProject` with a `CodeCommit` source defined in one AWS account in `us-west-2`. I want to have a stage in the pipeline which will deploy an output artifact from a previous build stage into the S3 bucket of another AWS account in a different region. When I do this though, I get the following error:

```
/Volumes/workplace/MyPackage/src/MyPackage/node_modules/monocdk/lib/core/lib/private/refs.js:124
            throw e;
            ^

Error: Resolution error: Resolution error: Resolution error: Resolution error: Resolution error: Only DeploymentStack or SupportingStack can be used as dependencies.
Object creation stack:
  at Execute again with CDK_DEBUG=true to capture stack traces.
Object creation stack:
  at Execute again with CDK_DEBUG=true to capture stack traces.
Object creation stack:
  at Execute again with CDK_DEBUG=true to capture stack traces..
    at /Volumes/workplace/MyPackage/src/MyPackage/node_modules/@amzn/pipelines/lib/target/pdg-subtarget.js:82:23
    at Array.forEach (<anonymous>)
    at DeploymentGroupCfnSubTarget._renderTags (/Volumes/workplace/MyPackage/src/MyPackage/node_modules/@amzn/pipelines/lib/target/pdg-subtarget.js:68:33)
    at DeploymentGroupCfnSubTarget.render (/Volumes/workplace/MyPackage/src/MyPackage/node_modules/@amzn/pipelines/lib/target/pdg-subtarget.js:31:24)
    at /Volumes/workplace/MyPackage/src/MyPackage/node_modules/@amzn/pipelines/lib/target/pdg-target.js:85:54
    at Array.map (<anonymous>)
    at DeploymentGroupTarget.render (/Volumes/workplace/MyPackage/src/MyPackage/node_modules/@amzn/pipelines/lib/target/pdg-target.js:85:41)
    at /Volumes/workplace/MyPackage/src/MyPackage/node_modules/@amzn/pipelines/lib/stage/pdg-stage.js:45:66
    at Array.map (<anonymous>)
    at DeploymentGroupStage._renderTargetsInternal (/Volumes/workplace/MyPackage/src/MyPackage/node_modules/@amzn/pipelines/lib/stage/pdg-stage.js:45:53)
Subprocess exited with error 1
    Error: Failed to run cdk synth:
    null
                                                            
                        BUILD FAILED                        
                                                            
                                                                         
  *** command 'cdk-build' with arguments '' exited with return code '1'  
```

### Reproduction Steps

class BuildStack extends DeploymentStack {
    constructor(scope: App, id: string, props: DeploymentStackProps) {
        super(scope, id, props);

        const repository = new Repository(this, 'Repository', {
            repositoryName: 'Application',
            description: 'Read-only CodeCommit repo.'
        });

        const project = new PipelineProject(this, 'Project', {
            projectName: 'Application-AutomatedBuild',
            environment: {
                buildImage: WindowsBuildImage.WIN_SERVER_CORE_2019_BASE,
                computeType: WindowsBuildImage.WIN_SERVER_CORE_2019_BASE.defaultComputeType,
            },
            role: new SecureRole(this, 'ProjectRole', {
                roleName: 'AppCodeBuildProjectRole-DO-NOT-DELETE',
                assumedBy: new SecureServicePrincipal('codebuild.amazonaws.com')
            })
        });

        const pipeline = new Pipeline(this, 'TricorderPipeline', {
            pipelineName: 'MyApp',
            crossAccountKeys: true
        });

        const sourceOutput = new Artifact('Source');
        pipeline.addStage({
            stageName: 'Source',
            actions: [
                new CodeCommitSourceAction({
                    actionName: 'source',
                    repository: repository,
                    branch: 'mainline',
                    output: sourceOutput
                })
            ]
        });

        const alphaBuildOutput = new Artifact('AlphaBuild');
        pipeline.addStage({
            stageName: 'Build',
            actions: [
                new CodeBuildAction({
                    actionName: 'build',
                    project: project,
                    input: sourceOutput,
                    outputs: [alphaBuildOutput]
                })
            ]
        });

        pipeline.addStage({
            stageName: 'DeployToAlpha',
            actions: [
                new ManualApprovalAction({
                    actionName: 'approveToAlpha',
                    notifyEmails: ['my.email@email.com'],
                    runOrder: 1
                }),
                new S3DeployAction({
                    actionName: 'deployToAlpha',
                    input: alphaBuildOutput,
                    bucket: Bucket.fromBucketAttributes(this, 'AlphaBucket', {
                        region: 'us-east-1', // Removing this line causes the error to go away at build time, but the pipeline stage fails at run time with: Invalid action configuration The bucket named my-bucket is not located in the us-west-2 AWS region
                        bucketArn: 'arn:aws:s3:::my-bucket' // This bucket is in us-east-1 in a separate AWS account from the pipeline
                    }),
                    runOrder: 2
                })
            ]
        });
    }
}

### What did you expect to happen?

I want a CodePipeline which exists in AWS Account **A** in `us-west-2` to deploy a build artifact into an S3 bucket in AWS Account **B** in `us-east-1`.

### What actually happened?

I received a build error when specifying the cross-account region for the S3 bucket. Or, if I removed the region, CodePipeline failed to find the bucket since it was looking in `us-west-2` instead of `us-east-1`.

### CDK CLI Version

1.140.0

### Node.js Version

12.x

### OS

macOS Big Sur Version 11.6.3

### Language

Typescript

### Language Version

~4.3.2

### Other information

Using `monocdk` version `1.140.0` for CDK functionality.

**Comment by suds-sky** [comment]
I am facing the same issue mentioned in the title. @jzybert Could you please share how did you make it work

**Comment by skinny85** [comment]
@suds-sky can you provide some details? What is the issue? What is your code? What error message do you get?

Really difficult to help just having the information "I'm facing an issue" 😁.

**Comment by suds-sky** [comment]
@skinny85 Apologise about not sharing the context as I thought it is known.

I did work through this and passing a role to the s3 deploy action worked and not an issue anymore. Thanks 😄
