### ISSUE TITLE
(aws-lambda-nodejs): allow comments in tsconfig.json

### ISSUE THREAD

**Issue by vvo** [aws/aws-cdk#18974]
### What is the problem?

tsconfig.json can have comments in it, as explained here: https://www.typescriptlang.org/docs/handbook/release-notes/typescript-1-8.html#allow-comments-in-tsconfigjson

But the aws-lambda-nodejs will try to load tsconfig and it fails because of comments.

### Reproduction Steps

construct:
```ts
    new lambda.NodejsFunction(this, 'put-records', {
      bundling: {
        preCompilation: true,
      },
    });
```

tsconfig.json:
```ts
{
  "compilerOptions": {
    // some comment
    "lib": ["es2019", "es2020.promise", "es2020.bigint", "es2020.string"],
    "module": "commonjs",
    "target": "es2019",

    "strict": true,
    "esModuleInterop": true,
    "skipLibCheck": true,
    "forceConsistentCasingInFileNames": true
  }
}
```

### What did you expect to happen?

The function to be compiled.

### What actually happened?

```
SyntaxError: /redacted/tsconfig.json: Unexpected token / in JSON at position 597
    at parse (<anonymous>)
    at Object.Module._extensions..json (internal/modules/cjs/loader.js:1115:22)
    at Module.load (internal/modules/cjs/loader.js:937:32)
    at Function.Module._load (internal/modules/cjs/loader.js:778:12)
    at Module.require (internal/modules/cjs/loader.js:961:19)
    at require (internal/modules/cjs/helpers.js:92:18)
    at extractTsConfig (/redacted/node_modules/aws-cdk-lib/aws-lambda-nodejs/lib/util.ts:196:56)
    at Object.getTsconfigCompilerOptions (/redacted/node_modules/aws-cdk-lib/aws-lambda-nodejs/lib/util.ts:149:27)
    at Bundling.createBundlingCommand (/redacted/node_modules/aws-cdk-lib/aws-lambda-nodejs/lib/bundling.ts:162:31)
    at new Bundling (/redacted/node_modules/aws-cdk-lib/aws-lambda-nodejs/lib/bundling.ts:133:34)
```

### CDK CLI Version

2.12.0

### Node.js Version

14.17.6

### OS

macOs 12.2

### Language

Typescript

### Language Version

4.5.2

**Comment by corymhall** [comment]
I am unassigning and marking this issue as `p2`, which means that we are unable to work on this immediately.

We use +1s to help prioritize our work, and are happy to revaluate this issue based on community feedback. You can reach out to the cdk.dev community on [Slack](https://join.slack.com/t/cdk-dev/shared_invite/zt-mso6p56d-qJp7SOTBvMaQuDrx7R2wHg) to solicit support for reprioritization.

**Comment by Oatelaus** [comment]
I want to highlight that this is a fundamentally broken interaction between CDK and TypeScript.

`tsc --init` produces a json file which contains comments - cdk cannot consume this file until large changes are done to it, and the error message often reports line numbers which do not exist.

The visibility of this issue is low, and the probability of being affected by it is quite high.
