### ISSUE TITLE
(aws-lambda-python): Unable to build PythonLayer on Windows platform.

### ISSUE THREAD

**Issue by tomeszmh** [aws/aws-cdk#19059]
### What is the problem?

I have created a PythonLayer with a requirements.txt file. It's working on MAC platforms but on Windows we have some issues. Docker is able to download all dependencies, and tries copy to output folder asset-output/python, but it seems the folder is not created: "asset-outputpython". So docker recursively copies the original folder and exit after some time.
See in the log files.

### Reproduction Steps

Simple PythonLayerVersion added to lambda with a requirements.txt file in it. 

### What did you expect to happen?

Successful Layer build 

### What actually happened?

Docker doesn't copy downloaded dependencies under asset-output/python it recursively copies folders and exited after a while.

I checked cdk soruce, and I think this command is invoked:

`'python -m pip install -r requirements.txt -t /asset-output/python && cp -rT /asset-input/ /asset-output/python',`

### CDK CLI Version

2.12

### Node.js Version

16.14.0

### OS

Windows 

### Language

Python

### Language Version

Python 3.9

### Other information

```
/usr/bin/cp: cannot copy a directory, ‘/asset-input/’, into itself, ‘asset-outputpython’
jsii.errors.JavaScriptError:
  Error: Failed to bundle asset ChimpusChatBackendStack/slack-layer-for-lambda-runtime/Code/Stage, bundle output is located at D:\Projects\chimpus\cdk.out\asset.e88186929ea1a5519ca6c365d59602a5257499baaa9fff8c906715427d92c868-error: Error: docker exited with status 1
      at AssetStaging.bundle (C:\Users\tothd\AppData\Local\Temp\jsii-kernel-sgm3Sf\node_modules\@aws-cdk\core\lib\asset-staging.js:353:19)
      at AssetStaging.stageByBundling (C:\Users\tothd\AppData\Local\Temp\jsii-kernel-sgm3Sf\node_modules\@aws-cdk\core\lib\asset-staging.js:212:14)
      at stageThisAsset (C:\Users\tothd\AppData\Local\Temp\jsii-kernel-sgm3Sf\node_modules\@aws-cdk\core\lib\asset-staging.js:75:41)
      at Cache.obtain (C:\Users\tothd\AppData\Local\Temp\jsii-kernel-sgm3Sf\node_modules\@aws-cdk\core\lib\private\cache.js:28:17)
      at new AssetStaging (C:\Users\tothd\AppData\Local\Temp\jsii-kernel-sgm3Sf\node_modules\@aws-cdk\core\lib\asset-staging.js:99:48)
      at new Asset (C:\Users\tothd\AppData\Local\Temp\jsii-kernel-sgm3Sf\node_modules\@aws-cdk\aws-s3-assets\lib\asset.js:31:25)
      at AssetCode.bind (C:\Users\tothd\AppData\Local\Temp\jsii-kernel-sgm3Sf\node_modules\@aws-cdk\aws-lambda\lib\code.js:269:26)
      at new LayerVersion (C:\Users\tothd\AppData\Local\Temp\jsii-kernel-sgm3Sf\node_modules\@aws-cdk\aws-lambda\lib\layers.js:60:33)
      at new PythonLayerVersion (C:\Users\tothd\AppData\Local\Temp\jsii-kernel-sgm3Sf\node_modules\@aws-cdk\aws-lambda-python\lib\layer.js:35:9)
      at C:\Users\tothd\AppData\Local\Temp\tmp_zw_p310\lib\program.js:8412:58
```

**Comment by corymhall** [comment]
@tomeszmh we are currently tracking this issue in #18861
