### ISSUE TITLE
(@aws-cdk/aws-ec2): Requesting guidance on a strange issue

### ISSUE THREAD

**Issue by tsingh2k15** [aws/aws-cdk#19247]
### General Issue

Error: There are no 'Private' subnet groups in this VPC. Available types: Isolated

### The Question

Apologies in advance if there is already a solution for below issue, I did spend few hours investigating myself and around the internet but could not resolve the issue. So reaching out for further guidance here. 

My usecase is to provision and deploy airflow instance via CI/CD. Using typescript for development. I am importing an existing VPC and subnet objects for my usecase. 

I am running into a strange problem. I am using `aws-cdk@2.15.0` to provision and deploy self hosted airflow instance via my CI/CD pipeline. I am using `typescript` for developing the cdk constructs. The `cdk synth` and `cdk deploy` works fine in my AWS development account. But when I do the same steps in my AWS staging account, it gives me error(pasted below). I have reviewed the development and staging accounts with respect to VPC and subnet details. We use TGW in both the accounts. There may be a little bit of difference in the accounts where one seems to have isolated subnets and the other seems to have private subnets. The code works fine in the development account with private subnets. 

The error when deploying to staging account happens on the construct to create `rds` subnet group. Somehow it is looking for "private" subnet even if I explicitly specify the `SubnetType.ISOLATED` for the `vpcPlacement`  for staging account. Any guidance here would be appreciated. This is blocking us to use upper environments with CDK. Below is the error trace. 
 
```
node_modules/@aws-cdk/aws-ec2/lib/vpc.js:184
throw new Error(`There are no '${subnetType}' subnet groups in this VPC. Available types: ${availableTypes}`);
Error: There are no 'Private' subnet groups in this VPC. Available types: Isolated
at LookedUpVpc.selectSubnetObjectsByType (node_modules/@aws-cdk/aws-ec2/lib/vpc.js:184:19
at LookedUpVpc.selectSubnetObjects (node_modules/@aws-cdk/aws-ec2/lib/vpc.js:150:28
at LookedUpVpc.selectSubnets (node_modules/@aws-cdk/aws-ec2/lib/vpc.js:51:30)
at new SubnetGroup (node_modules/@aws-cdk/aws-rds/lib/subnet-group.js:19:41)
at new DatabaseInstanceNew (node_modules/@aws-cdk/aws-rds/lib/instance.js:133:87)
at new DatabaseInstanceSource (node_modules/@aws-cdk/aws-rds/lib/instance.js:229:9)
at new DatabaseInstance (node_modules/@aws-cdk/aws-rds/lib/instance.js:327:9)
```

I am not sure why it is looking for `Private` subnet when I have specified  `SubnetType.ISOLATED` in the `vpcPlacement`

I have tried multiple approaches but all the approached result in the same error. 
Code snippets:

```
vpcPlacement : { subnetType: SubnetType.PRIVATE }
```

Explicitly specifying the SubnetType.ISOLATED did not work.

```
vpcPlacement : { subnetType: SubnetType.ISOLATED }
```

Explicitly specifying the subnets did not work.

```
vpcPlacement : { subnets: [Subnet.fromSubnetId(...), Subnet.fromSubnetId(...) ] }
```

### CDK CLI Version

aws-cdk@2.15.0 - 2.15.0 (build 151055e)

### Node.js Version

v14.19.0

### Language

Typescript

**Comment by tsingh2k15** [comment]
Issue is resolved, this was occurring due to outdated dependencies in the project.
