### ISSUE TITLE
CDK does not respect region specified in .aws/config

### ISSUE THREAD

**Issue by wonjoonSeol-WS** [aws/aws-cdk#19497]
### What is the problem?

https://docs.aws.amazon.com/cdk/v2/guide/environments.html
> to determine the target at synthesis time, your stack can use two environment variables provided by the AWS CDK CLI: CDK_DEFAULT_ACCOUNT and CDK_DEFAULT_REGION. These variables are set based on the AWS profile specified using the --profile option, or the default AWS profile if you don't specify one.

CDK does not seem to respect regions specified in a aws profile. Only AWS_DEFAULT_REGION environment value.

### Reproduction Steps

let's say I have the following aws cli profiles:

~/.aws/config
```config
[staging-kr]
region=ap-northeast-2
output=json

[staging-jp]
region=ap-northeast-1
output=json
```

CDK is bootstrapped in these 2 regions.

Without AWS_DEFAULT_REGION env variable set, I end up getting an error in any of these profiles.
```sh
~/w/gateyo master* ❯ cdk deploy DowantTakeout --profile staging-kr
Including dependency stacks: Gateyo

✨  Synthesis time: 4.66s

Gateyo
Gateyo: deploying...
[0%] start: Publishing e9f57251775b5202791b2b90bbef0f673403a3368c59355a35dfadc504ff812f:current_account-current_region

[100%] success: Published e9f57251775b5202791b2b90bbef0f673403a3368c59355a35dfadc504ff812f:current_account-current_region

 ❌  Gateyo failed: Error [ValidationError]: Stack [Gateyo] cannot be deleted while TerminationProtection is enabled
    at Request.extractError (/opt/homebrew/Cellar/aws-cdk/2.17.0/libexec/lib/node_modules/aws-sdk/lib/protocol/query.js:50:29)
    at Request.callListeners (/opt/homebrew/Cellar/aws-cdk/2.17.0/libexec/lib/node_modules/aws-sdk/lib/sequential_executor.js:106:20)
    at Request.emit (/opt/homebrew/Cellar/aws-cdk/2.17.0/libexec/lib/node_modules/aws-sdk/lib/sequential_executor.js:78:10)
    at Request.emit (/opt/homebrew/Cellar/aws-cdk/2.17.0/libexec/lib/node_modules/aws-sdk/lib/request.js:686:14)
    at Request.transition (/opt/homebrew/Cellar/aws-cdk/2.17.0/libexec/lib/node_modules/aws-sdk/lib/request.js:22:10)
    at AcceptorStateMachine.runTo (/opt/homebrew/Cellar/aws-cdk/2.17.0/libexec/lib/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at /opt/homebrew/Cellar/aws-cdk/2.17.0/libexec/lib/node_modules/aws-sdk/lib/state_machine.js:26:10
    at Request.<anonymous> (/opt/homebrew/Cellar/aws-cdk/2.17.0/libexec/lib/node_modules/aws-sdk/lib/request.js:38:9)
    at Request.<anonymous> (/opt/homebrew/Cellar/aws-cdk/2.17.0/libexec/lib/node_modules/aws-sdk/lib/request.js:688:12)
    at Request.callListeners (/opt/homebrew/Cellar/aws-cdk/2.17.0/libexec/lib/node_modules/aws-sdk/lib/sequential_executor.js:116:18) {
  code: 'ValidationError',
  time: 2022-03-21T18:26:49.722Z,
  requestId: 'd591ce3c-b6b1-4a21-8594-8cc2ba0e069b',
  statusCode: 400,
  retryable: false,
  retryDelay: 953.6950246201387
}

Stack [Gateyo] cannot be deleted while TerminationProtection is enabled
```

export AWS_DEFAULT_REGION=ap-northeast-2 (or ap-northeast-1 for the respective profile), Only then it deploys fine.

```sh
~/w/gateyo master* ❯ cdk deploy DowantTakeout --profile staging-kr                                 
Including dependency stacks: Gateyo

✨  Synthesis time: 4.29s

Gateyo
Gateyo: deploying...
[0%] start: Publishing e9f57251775b5202791b2b90bbef0f673403a3368c59355a35dfadc504ff812f:current_account-current_region
[100%] success: Published e9f57251775b5202791b2b90bbef0f673403a3368c59355a35dfadc504ff812f:current_account-current_region

 ✅  Gateyo (no changes)

✨  Deployment time: 0.79s

Outputs:
Gateyo.ExportsOutputRefGateyoHttpCustomDomainBBAEC1057627E277 = staging-api.yogiyo.co.kr
Stack ARN:
arn:aws:cloudformation:ap-northeast-2:-:stack/Gateyo/0c9c0730-dad6-11ea-80cb-022ba4b65eea

✨  Total time: 5.08s

DowantTakeout
DowantTakeout: deploying...
[0%] start: Publishing 8583779c5dbc4d0b96352e241cb547ca58ffb5a5e91a8c7b02219f7e0be6477c:current_account-current_region
[100%] success: Published 8583779c5dbc4d0b96352e241cb547ca58ffb5a5e91a8c7b02219f7e0be6477c:current_account-current_region

 ✅  DowantTakeout (no changes)

✨  Deployment time: 0.74s

Stack ARN:
arn:aws:cloudformation:ap-northeast-2:-:stack/DowantTakeout/aa58a9a0-a565-11ec-8333-02da78d3b8e8

✨  Total time: 5.03s
```

### What did you expect to happen?

Use region specified in aws/config

### What actually happened?

Did not use correct region - ended up getting validation error(?)

### CDK CLI Version

2.17.0 (build f9cd009)

### Node.js Version

v17.7.2.

### OS

mac os Montrey 12.2.1 (21D62)

### Language

Python

### Language Version

Python 3.8

**Comment by ryparker** [comment]
Hey @wonjoonSeol-WS 👋🏻 

Thanks for opening the issue. You need to make sure to prefix any non-default `~/.aws/config` profile with "profile".

e.g. `~/.aws/config`:
```cfg
[default]
region = us-east-1
output = yaml

[profile staging-kr]
region = ap-northeast-2
output = json

[profile staging-jp]
region = ap-northeast-1
output = json
```

Also make sure that you've configured credentials in `~/.aws/credentials` with the same name as the profile you are providing (no "profile" prefix here).

e.g. `~/.aws/credentials`:
```cfg
[default]
aws_access_key_id=<ACCESS_KEY_ID>
aws_secret_access_key=<SECRET_ACCESS_KEY>

[staging-kr]
aws_access_key_id=<ACCESS_KEY_ID>
aws_secret_access_key=<SECRET_ACCESS_KEY>

[staging-jp]
aws_access_key_id=<ACCESS_KEY_ID>
aws_secret_access_key=<SECRET_ACCESS_KEY>
```

I believe the reason you're running into these errors is because when you specify `cdk deploy --profile staging-kr` it is not only looking for `profile staging-kr` in  `~/.aws/config` but it is also looking for `staging-kr` in `~/.aws/credentials`.

> Although the AWS CDK uses credentials from the same sources files as other AWS tools and SDKs, including the [AWS Command Line Interface](https://docs.aws.amazon.com/cli/latest/userguide/cli-chap-welcome.html), it may behave slightly differently from these tools. See [Setting credentials](https://docs.aws.amazon.com/sdk-for-javascript/v2/developer-guide/setting-credentials.html) for complete details on setting up credentials for the AWS SDK for JavaScript, which the AWS CDK uses under the hood.
[CDK Credentials documentation](https://docs.aws.amazon.com/cdk/v2/guide/cli.html#cli-environment)

**Comment by wonjoonSeol-WS** [comment]
Thank you. 

Can confirm deployment works fine after adding "profile" prefix to ~/.aws/config.
Closing the issue. 

May I also ask why the stack error message says "the stack cannot be deleted" when in fact there is no region specified?
I have no default region set up.

Perhaps after all failover to evaluate a valid region it should terminate and send error message there.
Have a nice day!
