### ISSUE TITLE
Cluster is not getting created if I don't pass Role via withRole()

### ISSUE THREAD

**Issue by CloudDevBe** [aws/aws-cdk#1980]
I am trying to create a Cluster using CDK 0.25.2 and EKS 0.25.2 jars. If I don't pass the role via withRole() on Cluster, following issue occurs:
```
Exception in thread "main" software.amazon.jsii.JsiiException: Cannot read property 'fromComponents' of undefined
TypeError: Cannot read property 'fromComponents' of undefined
    at AwsManagedPolicy.get policyArn [as policyArn] (/private/var/folders/rl/gyf_2slx0c73w8r6vphqz1r40000gn/T/jsii-kernel-NynlGF/node_modules/@aws-cdk/aws-iam/lib/managed-policy.js:22:29)
    at new Cluster (/private/var/folders/rl/gyf_2slx0c73w8r6vphqz1r40000gn/T/jsii-kernel-NynlGF/node_modules/@aws-cdk/aws-eks/lib/cluster.js:43:74)
    at s._wrapSandboxCode (/private/var/folders/rl/gyf_2slx0c73w8r6vphqz1r40000gn/T/jsii-java-runtime2541779840332052843/jsii-runtime.js:1:86832)
    at t.Kernel._wrapSandboxCode (/private/var/folders/rl/gyf_2slx0c73w8r6vphqz1r40000gn/T/jsii-java-runtime2541779840332052843/jsii-runtime.js:1:95334)
    at t.Kernel._create (/private/var/folders/rl/gyf_2slx0c73w8r6vphqz1r40000gn/T/jsii-java-runtime2541779840332052843/jsii-runtime.js:1:86811)
    at t.Kernel.create (/private/var/folders/rl/gyf_2slx0c73w8r6vphqz1r40000gn/T/jsii-java-runtime2541779840332052843/jsii-runtime.js:1:81795)
    at t.KernelHost.processRequest (/private/var/folders/rl/gyf_2slx0c73w8r6vphqz1r40000gn/T/jsii-java-runtime2541779840332052843/jsii-runtime.js:1:78506)
    at t.KernelHost.run (/private/var/folders/rl/gyf_2slx0c73w8r6vphqz1r40000gn/T/jsii-java-runtime2541779840332052843/jsii-runtime.js:1:78195)
    at e.processRequest (/private/var/folders/rl/gyf_2slx0c73w8r6vphqz1r40000gn/T/jsii-java-runtime2541779840332052843/jsii-runtime.js:1:78221)
    at t.KernelHost.processRequest (/private/var/folders/rl/gyf_2slx0c73w8r6vphqz1r40000gn/T/jsii-java-runtime2541779840332052843/jsii-runtime.js:1:78960)
    at t.KernelHost.run (/private/var/folders/rl/gyf_2slx0c73w8r6vphqz1r40000gn/T/jsii-java-runtime2541779840332052843/jsii-runtime.js:1:78195)
    at e.processRequest (/private/var/folders/rl/gyf_2slx0c73w8r6vphqz1r40000gn/T/jsii-java-runtime2541779840332052843/jsii-runtime.js:1:78221)
    at i.then.e (/private/var/folders/rl/gyf_2slx0c73w8r6vphqz1r40000gn/T/jsii-java-runtime2541779840332052843/jsii-runtime.js:1:78834)
    at software.amazon.jsii.JsiiRuntime.processErrorResponse(JsiiRuntime.java:118)
    at software.amazon.jsii.JsiiRuntime.requestResponse(JsiiRuntime.java:90)
    at software.amazon.jsii.JsiiRuntime.processCallbackResponse(JsiiRuntime.java:163)
    at software.amazon.jsii.JsiiRuntime.requestResponse(JsiiRuntime.java:95)
    at software.amazon.jsii.JsiiRuntime.processCallbackResponse(JsiiRuntime.java:163)
    at software.amazon.jsii.JsiiRuntime.requestResponse(JsiiRuntime.java:95)
    at software.amazon.jsii.JsiiRuntime.processCallbackResponse(JsiiRuntime.java:163)
    at software.amazon.jsii.JsiiRuntime.requestResponse(JsiiRuntime.java:95)
    at software.amazon.jsii.JsiiClient.createObject(JsiiClient.java:101)
    at software.amazon.jsii.JsiiEngine.createNewObject(JsiiEngine.java:447)
    at software.amazon.awscdk.services.eks.Cluster.<init>(Cluster.java:22)
    at src.com.amazonaws.services.cloudformation.hellocdk.src.main.java.com.myorg.HelloStack4.<init>(HelloStack4.java:297)
    at src.com.amazonaws.services.cloudformation.hellocdk.src.main.java.com.myorg.HelloStack4.<init>(HelloStack4.java:33)
    at src.com.amazonaws.services.cloudformation.hellocdk.src.main.java.com.myorg.HelloApp.main(HelloApp.java:14) ```

**Comment by SomayaB** [comment]
Hi, sorry for the late reply. Are you still having this issue?

**Comment by SomayaB** [comment]
Closing this issue since there hasn't been activity on it in a while. Feel free to reopen if you are still experiencing this issue.
