### ISSUE TITLE
(pipelines): ShellStep.envFromCfnOutputs could not use in pre step

### ISSUE THREAD

**Issue by il-m-yamagishi** [aws/aws-cdk#19877]
### Describe the bug

[Official documents](https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.pipelines-readme.html#using-cloudformation-stack-outputs-in-approvals) pass `CfnOutput` to post `ShellStep.envFromCfnOutputs`, but it causes cycle error when it passes `CfnOutput` to **pre** `ShellStep.envFromCfnOutputs`.

### Expected Behavior

no error occurs

### Current Behavior

error occurs

```
$ npx cdk synth DevPipelineStack

Error: Dependency cycle in graph: Deploy => Prepare => PreDeployMessage => Deploy
    at Object.topoSort (/home/path/to/cdk/node_modules/aws-cdk-lib/pipelines/lib/helpers-internal/toposort.js:2:426)
    at Graph.sortedLeaves (/home/path/to/cdk/node_modules/aws-cdk-lib/pipelines/lib/helpers-internal/graph.js:1:3330)
    at CodePipeline.pipelineStagesAndActionsFromGraph (/home/path/to/cdk/node_modules/aws-cdk-lib/pipelines/lib/codepipeline/codepipeline.js:1:3650)
    at CodePipeline.doBuildPipeline (/home/path/to/cdk/node_modules/aws-cdk-lib/pipelines/lib/codepipeline/codepipeline.js:1:3058)
    at CodePipeline.buildPipeline (/home/path/to/cdk/node_modules/aws-cdk-lib/pipelines/lib/main/pipeline-base.js:1:1653)
    at CodePipeline.buildJustInTime (/home/path/to/cdk/node_modules/aws-cdk-lib/pipelines/lib/main/pipeline-base.js:1:1720)
    at Object.visit (/home/path/to/cdk/node_modules/aws-cdk-lib/pipelines/lib/main/pipeline-base.js:1:947)
    at recurse (/home/path/to/cdk/node_modules/aws-cdk-lib/core/lib/private/synthesis.js:1:1821)
    at recurse (/home/path/to/cdk/node_modules/aws-cdk-lib/core/lib/private/synthesis.js:1:2149)
    at recurse (/home/path/to/cdk/node_modules/aws-cdk-lib/core/lib/private/synthesis.js:1:2149)
Subprocess exited with error 1
```

### Reproduction Steps

<details>
<summary>Source code</summary>

```ts
/* eslint-disable max-classes-per-file */
import {
    App,
    CfnOutput,
    Stack,
    StackProps,
    Stage,
    StageProps,
} from 'aws-cdk-lib';
import { StringParameter } from 'aws-cdk-lib/aws-ssm';
import { Repository } from 'aws-cdk-lib/aws-codecommit';
import { CodePipeline, CodePipelineSource, ShellStep } from 'aws-cdk-lib/pipelines';
import { Construct } from 'constructs';

export class DevStack extends Stack {
    public readonly chatToken: CfnOutput;

    constructor(scope: Construct, id: string, props?: StackProps) {
        super(scope, id, props);

        const chatToken = StringParameter.fromSecureStringParameterAttributes(
            this,
            'ChatToken',
            {
                parameterName: '/dev/chat-token',
            },
        );
        this.chatToken = new CfnOutput(this, 'ChatTokenOutput', {
            value: chatToken.stringValue,
        });
    }
}

export class DevStage extends Stage {
    public readonly chatToken: CfnOutput;

    public constructor(scope: Construct, id: string, props?: StageProps) {
        super(scope, id, props);

        const stack = new DevStack(this, 'DevStack');

        this.chatToken = stack.chatToken;
    }
}

export class DevPipelineStack extends Stack {
    public constructor(scope: Construct, id: string, props?: StackProps) {
        super(scope, id, props);

        const repository = new Repository(this, 'DevRepository', {
            repositoryName: 'dev',
        });

        const pipeline = new CodePipeline(this, 'DevPipeline', {
            synth: new ShellStep('Synth', {
                input: CodePipelineSource.codeCommit(repository, 'main'),
                commands: [
                    'npm ci',
                    'npm run build',
                    'npx cdk synth',
                ],
            }),
        });

        const stage = new DevStage(this, 'DevStage');
        pipeline.addStage(stage, {
            // It does not work
            pre: [
                new ShellStep('PreDeployMessage', {
                    commands: [
                        // eslint-disable-next-line no-template-curly-in-string
                        'curl --header "Authorization: bearer ${CHAT_TOKEN}" https://some.chat.service',
                    ],
                    envFromCfnOutputs: {
                        CHAT_TOKEN: stage.chatToken,
                    },
                }),
            ],
            // It works
            //post: [
            //    new ShellStep('PostDeployMessage', {
            //        commands: [
            //            // eslint-disable-next-line no-template-curly-in-string
            //            'curl --header "Authorization: bearer ${CHAT_TOKEN}" https://some.chat.service',
            //        ],
            //        envFromCfnOutputs: {
            //            CHAT_TOKEN: stage.chatToken,
            //        },
            //    }),
            //],
        });
    }
}

const app = new App();
new DevPipelineStack(app, 'DevPipelineStack');
```
</details>

### Possible Solution

I want to send message like `"Deployment will be started"` to chat service. So I use workaround to send message in `assetPublishingCodeBuildDefaults` instead of pre step.

### CDK CLI Version

2.10.0 (build e5b301f)

### Node.js Version

v16.14.0

### OS

Ubuntu 20.04(WSL2)

### Language

Typescript

### Language Version

4.5.5

**Comment by rix0rrr** [comment]
A `CfnOutput` is a value that is produced as a result of deploying a stack. If you want to print this value before the stack is actually deployed, it is similar to trying to write the following code:

```ts
print("I am starting the deployment of stack " + stackArn);
var stackArn = 'arn:aws:cloudformation:us-east-1:123456789012:stack/MyStack/12345';
```

Maybe you want to print a static string instead.
