### ISSUE TITLE
aws-eks: HelmChart fails due to racing condition between Lambda execution and HandlerRole's grant_read

### ISSUE THREAD

**Issue by codeJack** [aws/aws-cdk#19880]
### Describe the bug

The `HelmChart` construct, combined with an s3 `chart_asset` fails due to lack of S3 read permissions.
This happens under specific circumstances where the [provider's HandlerRole s3 grantRead](https://github.com/aws/aws-cdk/blob/v2.20.0/packages/%40aws-cdk/aws-eks/lib/helm-chart.ts#L128) policy is slower to execute than the HelmChart custom resource.

### Expected Behavior

The Helm chart is correctly installed/upgraded into EKS

### Current Behavior

```python
helm_chart_asset = Asset(
    scope=self,
    id="HelmChartAsset",
    path="helm",
)

helm_chart = HelmChart(
            scope=self,
            id="HelmChart",
            cluster=cluster, # The imported EKS cluster
            chart_asset=helm_chart_asset , # The S3 asset created above
            release="helm-chart",
            namespace="default",
            wait=True,
        )
```
The `HelmChart` construct fails with the error below 

CloudFormation error
```
Received response status [FAILED] from custom resource. Message returned: Error: Command '['aws', 's3', 'cp', 's3://cdk-****-assets-000000000000-eu-central-1/a44d179be08c1*****.zip', '/tmp/chart.zip']' returned non-zero exit status 1
```

CloudWatch logs
```
fatal error: An error occurred (403) when calling the HeadObject operation: Forbidden 
```

### Reproduction Steps

The bug has been experienced after applying `permissions boundary` on CDK's cfn exec role which sensibly slows down `KubectlHandlerRolePolicyEE4E9930` creation: as a consequence, the Kubectl provider Lambda executes *before* the policy ([that grants read permissions to the bucket where the chart asset is to be found](https://github.com/aws/aws-cdk/blob/v2.20.0/packages/%40aws-cdk/aws-eks/lib/helm-chart.ts#L128)) has been attached to the HandlerRole. This causes a failure due to lack of permissions to retrieve the chart.

After introducing `permissions boundary`
```
2022-04-12 01:17:51 UTC+0200  HelmChart6800A2F9 CREATE_FAILED
2022-04-12 01:17:51 UTC+0200  HelmChart6800A2F9 CREATE_IN_PROGRESS  Resource creation Initiated
2022-04-12 01:17:50 UTC+0200  CDKMetadata CREATE_COMPLETE -
2022-04-12 01:17:49 UTC+0200  CDKMetadata CREATE_IN_PROGRESS  Resource creation Initiated
2022-04-12 01:17:49 UTC+0200  KubectlHandlerRolePolicyEE4E9930  CREATE_IN_PROGRESS  Resource creation Initiated
```

Before introducing `permissions boundary`
```
2022-04-01 12:40:19 UTC+0200  HelmChart6800A2F9 CREATE_COMPLETE -
2022-04-01 12:40:19 UTC+0200  HelmChart6800A2F9 CREATE_IN_PROGRESS  Resource creation Initiated
2022-04-01 12:40:09 UTC+0200  KubectlHandlerRolePolicyEE4E9930  CREATE_COMPLETE -
2022-04-01 12:39:52 UTC+0200  CDKMetadata CREATE_COMPLETE -
2022-04-01 12:39:52 UTC+0200  CDKMetadata CREATE_IN_PROGRESS  Resource creation Initiated
2022-04-01 12:39:51 UTC+0200  KubectlHandlerRolePolicyEE4E9930  CREATE_IN_PROGRESS  Resource creation Initiated
```

### Possible Solution

If the `HelmChart` custom resource `Custom::AWSCDK-EKS-HelmChart` had a `dependsOn` attribute against the policy CloudFormation would wait for the policy to be attached to the role before executing the custom resource.

```python
helm_chart_asset = Asset(
    scope=self,
    id="HelmChartAsset",
    path="helm",
)

helm_chart = HelmChart(
            scope=self,
            id="HelmChart",
            cluster=cluster, # The imported EKS cluster
            chart_asset=helm_chart_asset , # The S3 asset created above
            release="helm-chart",
            namespace="default",
            wait=True,
        )

# Temporary workaround
for construct in self.node.find_all():
    if isinstance(construct, Policy):
        helm_chart.node.add_dependency(construct)
```

### CDK CLI Version

2.20.0

### Framework Version

2.20.0

### Node.js Version

v17.6.0

### OS

MacOS 11.6.4

### Language

Python

### Language Version

v3.9.10

**Comment by toha-nordic** [comment]
Im still experiencing this when upgrading to CDK >=2.81.0 with Typescript, not sure if thats the only relevant change though.

**Comment by mhvelplund** [comment]
I can see this in CDK 2.115.0 (build 58027ee) too. My code looks like this:
```typescript
export class LocalChartStack extends cdk.Stack {
  constructor(scope: Construct, id: string, props: LocalChartStackProps) {
    super(scope, id, props);
    const name = props.name || id;

    const chartAsset = new Asset(this, "ChartAsset", {
      path: props.path,
    });

    props.cluster.addHelmChart(name, {
      chartAsset,
      namespace: props.namespace,
      values: props.values,
    });
  }
}
```

... and the error is the same as the one in the issue:

```
10:26:56 AM | CREATE_FAILED        | Custom::AWSCDK-EKS-HelmChart          | EksClusterchartGame20483C8D9361
Received response status [FAILED] from custom resource. Message returned: Error: Command '['aws', 's3', 'cp', 's3://cdk-hnb659fds-assets-xxxxxxxxxxxx-eu-central-1/xxxxxxxxx2a0c6358213dbb476710887475728d13df3349f09844438e58d
ec16.zip', '/tmp/chart.zip']' returned non-zero exit status 1.

Logs: /aws/lambda/EksCluster-awscdkawseksKubectlProv-Handler886CB40B-wDvSCFKLvUr4

at invokeUserFunction (/var/task/framework.js:2:6)
at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
at async onEvent (/var/task/framework.js:1:369)
at async Runtime.handler (/var/task/cfn-response.js:1:1573) (RequestId: 26f73afd-4b3b-422d-a2bb-c3a9440dab77)
```

**Comment by pivstone** [comment]
We have the same issue, here is our setup.

We are using AWS EKS blueprints to create a cluster stack.
In our backend service stack, we imported the cluster by attributes. 

And using HelmChart construct to apply our Helm Chart.
In my research, I found the S3 Policy for CDK Bootstrap S3 Asset Bucket isn't created in the cloudformtaion synth  results. 
Even in the CDK code, there is a line to grant read permission to the Provider. 

If the cluster is created in the same stack, then the permission is attached correctly.

Our workaround is create policy statement manually.

**Comment by gudipati** [comment]
The race condition should now be fixed with [this change](https://github.com/aws/aws-cdk/pull/37731)
