### ISSUE TITLE
Context can't find already-extant VPC

### ISSUE THREAD

**Issue by foscraig** [aws/aws-cdk#1994]
My VPC already exists--it was created on a previous iteration of my application. But after I've modified my code and run the application again, the application errors out saying it cannot find the VPC in my account. ([This](https://github.com/awslabs/aws-cdk/blame/e1506489318e019b93570afe5abf0920b70fd26e/packages/aws-cdk/lib/context-providers/vpcs.ts#L23) is the relevant method in CDK.)

I have a utility method in my application using AWS Java SDK to find VPCs. In my CDK app, I run this and I logged the result. Note that I logged the result before AWS CDK tries to list VPCs in its context method. 

Logged utility method to find pre-existing VPCs using AWS JAVA SDK:
```
{Vpcs: [{CidrBlock: 10.0.0.0/16,DhcpOptionsId: dopt-cc90aca4,State: available,VpcId: vpc-0d273b65fe619b841,OwnerId: 123456789012,InstanceTenancy: default,Ipv6CidrBlockAssociationSet: [],CidrBlockAssociationSet: [{AssociationId: vpc-cidr-assoc-09ad923a4e1ebe498,CidrBlock: 10.0.0.0/16,CidrBlockState: {State: associated,}}],IsDefault: false,Tags: [{Key: aws:cloudformation:stack-name,Value: infraStack}, {Key: aws:cloudformation:stack-id,Value: arn:aws:cloudformation:us-west-2:123456789012:stack/infraStack/d7e0bf00-3ef9-11e9-8ec5-021aeadbff90}, {Key: aws:cloudformation:logical-id,Value: CodeBuildVPC6E904AAD}, {Key: Name,Value: infraStack/CodeBuild VPC}]}]}
```

Verbose output from `cdk deploy`:
```
outfile: /var/folders/1r/mjmg02rn4y7_rn81ycrc8hcw72k6jw/T/cdk5XkVuT/cdk.out
{ version: '0.19.0',
  artifacts:
   { infraStack:
      { type: 'aws:cloudformation:stack',
        environment: 'aws://123456789012/us-west-2',
        properties: [Object],
        metadata: [Object] },
     'aws-java-sdk':
      { type: 'aws:cloudformation:stack',
        environment: 'aws://123456789012/us-west-2',
        properties: [Object],
        dependencies: [Array],
        metadata: [Object],
        missing: [Object] },
     ...
     [redacted]
     ...
      },
  runtime:
   { libraries:
      { '@aws-cdk/cx-api': '0.25.2',
        '@aws-cdk/cdk': '0.25.2',
        '@aws-cdk/aws-iam': '0.25.2',
        '@aws-cdk/aws-ec2': '0.25.2',
        '@aws-cdk/aws-events': '0.25.2',
        '@aws-cdk/aws-codepipeline-api': '0.25.2',
        '@aws-cdk/aws-codecommit': '0.25.2',
        '@aws-cdk/aws-kms': '0.25.2',
        '@aws-cdk/aws-s3-notifications': '0.25.2',
        '@aws-cdk/aws-s3': '0.25.2',
        '@aws-cdk/aws-autoscaling-api': '0.25.2',
        '@aws-cdk/aws-cloudwatch': '0.25.2',
        '@aws-cdk/assets': '0.25.2',
        '@aws-cdk/aws-logs': '0.25.2',
        '@aws-cdk/aws-sqs': '0.25.2',
        '@aws-cdk/aws-stepfunctions': '0.25.2',
        '@aws-cdk/aws-lambda': '0.25.2',
        '@aws-cdk/aws-sns': '0.25.2',
        '@aws-cdk/aws-codepipeline': '0.25.2',
        '@aws-cdk/aws-ecr': '0.25.2',
        '@aws-cdk/aws-cloudformation': '0.25.2',
        '@aws-cdk/assets-docker': '0.25.2',
        '@aws-cdk/aws-codebuild': '0.25.2',
        'jsii-runtime': 'Java/1.8.0_202' } },
  stacks:
   [ { name: 'infraStack',
       environment: [Object],
       template: [Object],
       metadata: [Object] },
     { name: 'aws-java-sdk',
       environment: [Object],
       template: [Object],
       metadata: [Object],
       dependsOn: [Array],
       missing: [Object] },
     ...
     [redacted]
     ...
      ] }
Removing outdir /var/folders/1r/mjmg02rn4y7_rn81ycrc8hcw72k6jw/T/cdk5XkVuT
Some context information is missing. Fetching...
Using default AWS SDK credentials for account 123456789012
Listing VPCs in 123456789012:us-west-2
Could not find any VPCs matching {"account":"123456789012","region":"us-west-2","filter":{"tag:Name":"infrasStack/CodeBuild VPC"}}
Error: Could not find any VPCs matching {"account":"123456789012","region":"us-west-2","filter":{"tag:Name":"infrasStack/CodeBuild VPC"}}
    at VpcNetworkContextProviderPlugin.findVpc (/usr/local/lib/node_modules/aws-cdk/lib/context-providers/vpcs.ts:32:13)
    at process.internalTickCallback (internal/process/next_tick.js:77:7)
```

**Comment by cynicaljoy** [comment]
Looks like you have a typo in your app. You're trying to match: `"tag:Name":"infrasStack/CodeBuild VPC"` but you're pre-existing VPC has `{Key: Name,Value: infraStack/CodeBuild VPC}]`

**Comment by SomayaB** [comment]
Hi, I apologize for the late reply. Are you still having this issue or did fixing the typo resolve the it?

**Comment by SomayaB** [comment]
Closing this issue since there hasn't been any activity on it in a while. Feel free to reopen.
