### ISSUE TITLE
AWS Skill Builder CDK Primer: TypeScript compile error TS2345 in sample code

### ISSUE THREAD

**Issue by owenblacker** [aws/aws-cdk#20042]
### Describe the bug

Following the instructions in the [AWS CDK Demonstration code-along](https://explore.skillbuilder.aws/learn/course/1475/play/4999/aws-cloud-development-kit-primer;lp=85) in AWS Skill Builder and the first time I'm asked to `cdk synth` I get a compilation error, unlike the demonstration video.

### Expected Behavior

I expected the `cdk synth` to execute correctly, outputting a non-error response that ends
```yaml
              - Ref: AWS::Region
              - us-east-1
          - Fn::Equals:
              - Ref: AWS::Region
              - us-east-2
          - Fn::Equals:
              - Ref: AWS::Region
              - us-west-1
          - Fn::Equals:
              - Ref: AWS::Region
              - us-west-2
```
like on-screen.

### Current Behavior

I get an error response, with the error occurring in one of the files I have not changed. (The instructions have only asked me to change the file `lib/cdk_primer-stack.ts` so far.)
```
/Users/owen.blacker/Projects/other/cdk-primer/node_modules/ts-node/src/index.ts:513
    return new TSError(diagnosticText, diagnosticCodes)
           ^
TSError: ⨯ Unable to compile TypeScript:
bin/cdk-primer.ts:7:20 - error TS2345: Argument of type 'App' is not assignable to parameter of type 'Construct'.
  Type 'App' is missing the following properties from type 'Construct': onValidate, onPrepare, onSynthesize, validate, and 2 more.

7 new CdkPrimerStack(app, 'CdkPrimerStack', {
                     ~~~

    at createTSError (/Users/owen.blacker/Projects/other/cdk-primer/node_modules/ts-node/src/index.ts:513:12)
    at reportTSError (/Users/owen.blacker/Projects/other/cdk-primer/node_modules/ts-node/src/index.ts:517:19)
    at getOutput (/Users/owen.blacker/Projects/other/cdk-primer/node_modules/ts-node/src/index.ts:752:36)
    at Object.compile (/Users/owen.blacker/Projects/other/cdk-primer/node_modules/ts-node/src/index.ts:968:32)
    at Module.m._compile (/Users/owen.blacker/Projects/other/cdk-primer/node_modules/ts-node/src/index.ts:1056:42)
    at Module._extensions..js (node:internal/modules/cjs/loader:1157:10)
    at Object.require.extensions.<computed> [as .ts] (/Users/owen.blacker/Projects/other/cdk-primer/node_modules/ts-node/src/index.ts:1059:12)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:77:12)

Subprocess exited with error 1
```

### Reproduction Steps

Following the instructions in the video, I have done the following:

1. On a computer where I had newly installed the CDK with `sudo npm i -g aws-cdk`
2. Open VS Code
3. Using the terminal, create and enter an empty folder (in my case `/Users/owen.blacker/Projects/other/cdk-primer/`)
4. Run `cdk init --language typescript`
5. Install modules: `npm i @aws-cdk/aws-ec2 @aws-cdk/aws-ecs @aws-cdk/aws-ecs-patterns`
6. Edit the file `lib/cdk_primer-stack.ts` to contain the TypeScript as below
7. Run `cdk synth`

The contents of `lib/cdk_primer-stack.ts` once edited are:

```typescript
import * as cdk from '@aws-cdk/core';
import * as ec2 from "@aws-cdk/aws-ec2";
import * as ecs from "@aws-cdk/aws-ecs";
import * as ecs_patterns from "@aws-cdk/aws-ecs-patterns";

export class CdkPrimerStack extends cdk.Stack {
  constructor(scope: cdk.Construct, id: string, props?: cdk.StackProps) {
    super(scope, id, props);

    const vpc = new ec2.Vpc(this, "MyVpc", {maxAzs: 2});
    const cluster = new ecs.Cluster(this, "MyCluster", {vpc: vpc});
    new ecs_patterns.ApplicationLoadBalancedFargateService(this, "MyFargateService", {
      cluster: cluster,
      taskImageOptions: { image: ecs.ContainerImage.fromRegistry("amazon/amazon-ecs-sample") },
      publicLoadBalancer: true
    });
  }
}
```
Other than the video having an extra tab at the start of line 12 (`new ecs_patterns.ApplicationLoadBalancedFargateService(...)`) and an extra linebreak after that `new` statement, this is identical to the code on-screen.

### CDK CLI Version

2.21.0 (build 3f74a81)

### Node.js Version

v16.14.2

### OS

MacOS Monterey version 12.3.1 (21E258)

### Language

Typescript

### Language Version

TypeScript 3.9.10

**Comment by peterwoodworth** [comment]
Migrating this to a discussion @owenblacker 🙂
