### ISSUE TITLE
aws_config: Unable to create rules

### ISSUE THREAD

**Issue by bearrito** [aws/aws-cdk#20106]
### Describe the bug

Running CDK synth on a aws_config rule fails.

### Expected Behavior

For the cdk synth to work.

### Current Behavior

CDK synth failed with the following stack trace.

```sh
Traceback (most recent call last):
  File "app.py", line 25, in <module>
    compliance = SecurityStack(app, "SecurityStack", security_config)
  File "/home/bstrausser/.virtualenvs/cloud-formation/lib/python3.8/site-packages/jsii/_runtime.py", line 86, in __call__
    inst = super().__call__(*args, **kwargs)
  File "/home/bstrausser/Git/platform-cloud-infrastructure/sd-wan/sd_wan_stack/security_stack.py", line 61, in __init__
    compliance.ManagedRule(
  File "/home/bstrausser/.virtualenvs/cloud-formation/lib/python3.8/site-packages/jsii/_runtime.py", line 86, in __call__
    inst = super().__call__(*args, **kwargs)
  File "/home/bstrausser/.virtualenvs/cloud-formation/lib/python3.8/site-packages/aws_cdk/aws_config/__init__.py", line 5623, in __init__
    jsii.create(self.__class__, self, [scope, id, props])
  File "/home/bstrausser/.virtualenvs/cloud-formation/lib/python3.8/site-packages/jsii/_kernel/__init__.py", line 290, in create
    response = self.provider.create(
  File "/home/bstrausser/.virtualenvs/cloud-formation/lib/python3.8/site-packages/jsii/_kernel/providers/process.py", line 344, in create
    return self._process.send(request, CreateResponse)
  File "/home/bstrausser/.virtualenvs/cloud-formation/lib/python3.8/site-packages/jsii/_kernel/providers/process.py", line 311, in send
    data = json.dumps(req_dict, default=jdefault).encode("utf8")
  File "/usr/lib/python3.8/json/__init__.py", line 234, in dumps
    return cls(
  File "/usr/lib/python3.8/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib/python3.8/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/home/bstrausser/.virtualenvs/cloud-formation/lib/python3.8/site-packages/jsii/_kernel/providers/process.py", line 151, in jdefault
    raise TypeError("Don't know how to convert object to JSON: %r" % obj)
TypeError: Don't know how to convert object to JSON: <sd_wan_stack.security_stack.SecurityStack object at 0x7f8b128246a0>
```

### Reproduction Steps
```python
from aws_cdk import aws_config as compliance
from aws_cdk import  Stack,

class ComplianceStack(Stack):
    def __init__(
        self,
        scope: Construct,
        construct_id: str,
        **kwargs,
    ) -> None:
       

        compliance.ManagedRule(
            self,
            "VPC FLOW LOGS",
            identifier=compliance.ManagedRuleIdentifiers.VPC_FLOW_LOGS_ENABLED,
            maximum_execution_frequency=compliance.MaximumExecutionFrequency.TWELVE_HOURS,
        )

  ```

### Additional Information/Context

Might be related to this  issue - 

https://github.com/aws/jsii/pull/3372
https://github.com/hashicorp/terraform-cdk/issues/1541 seems related  as well

### CDK CLI Version

2.21.1 (build a6ee543)

### Node.js Version

6.14.16

### OS

Ubuntu 20

### Language

Python

**Comment by bearrito** [comment]
That's a slightly reduced version than what I using in production. I'll see if I can create smaller stack that reproduces it.

**Comment by bearrito** [comment]
I can't reproduce this either now. I'll say that I updated CDK versions after filing this ticket, perhaps there was a fix in there.
This is probably okay to close.
