### ISSUE TITLE
(testing?): jest v28 breaks testing

### ISSUE THREAD

**Issue by ahammond** [aws/aws-cdk#20147]
### Describe the bug

```
❯ projen test
👾 test | jest --passWithNoTests --all --updateSnapshot --coverageProvider=v8
ts-jest[versions] (WARN) Version 28.0.3 of jest installed has not been tested with ts-jest. If you're experiencing issues, consider using a supported version (>=27.0.0 <28.0.0-0). Please do not report issues in ts-jest if you are using unsupported versions.
 FAIL  test/widget.test.ts
  ● Test suite failed to run

    ● Invalid return value:
      `process()` or/and `processAsync()` method of code transformer found at 
      "/Users/ahammond/Documents/ClickUp/my-new-cdk-app/node_modules/ts-jest/dist/index.js" 
      should return an object or a Promise resolving to an object. The object 
      must have `code` property with a string of processed code.
      This error may be caused by a breaking change in Jest 28:
      https://jestjs.io/docs/upgrading-to-jest28#transformer
      Code Transformation Documentation:
      https://jestjs.io/docs/code-transformation
    

      at ScriptTransformer._buildTransformResult (node_modules/@jest/transform/build/ScriptTransformer.js:507:15)
      at ScriptTransformer.transformSource (node_modules/@jest/transform/build/ScriptTransformer.js:628:17)
      at ScriptTransformer._transformAndBuildScript (node_modules/@jest/transform/build/ScriptTransformer.js:765:40)
      at ScriptTransformer.transform (node_modules/@jest/transform/build/ScriptTransformer.js:822:19)
```

### Expected Behavior

tests should run

### Current Behavior

Looks like I'll have to downgrade jest to v27 and lock it there.

### Reproduction Steps

Update jest to v28, run tests.

### CDK CLI Version

2.22.0 (build 1db4b16)

### Node.js Version

v16.13.1

### OS

Darwin Andrews-MacBook-Air.local 21.2.0 Darwin Kernel Version 21.2.0: Sun Nov 28 20:29:10 PST 2021; root:xnu-8019.61.5~1/RELEASE_ARM64_T8101 arm64

### Language

Typescript

### Language Version

TypeScript (4.6.4)

**Comment by mbonig** [comment]
This was recently spotted in projen. Update to the lastest version or override your jestVersion to ^27:

https://github.com/projen/projen/issues/1801

**Comment by ahammond** [comment]
@mbonig at last an excuse to upgrade projen again! :) Super excited to pick up the new GitHub app replacement for the TOKEN. :)
