### ISSUE TITLE
custom_resource: Converting circular structure to JSON

### ISSUE THREAD

**Issue by geoynomous** [aws/aws-cdk#20260]
### Describe the bug

TypeError: Converting circular structure to JSON when using custom resource with onEvent's parameter being a cluster

Error upon

`npx cdk synth`

### Expected Behavior

synthesizes correctly

### Current Behavior

```
/path/cdk/node_modules/.pnpm/aws-cdk-lib@2.23.0_constructs@10.0.130/node_modules/aws-cdk-lib/custom-resources/lib/aws-custom-resource/aws-custom-resource.ts:501
  JSON.stringify(obj, (_, v) => {
       ^
TypeError: Converting circular structure to JSON
    --> starting at object with constructor 'Cluster'
    |     property 'node' -> object with constructor 'Node'
    --- property 'host' closes the circle
    at JSON.stringify (<anonymous>)
    at includesPhysicalResourceIdRef (/path/cdk/node_modules/.pnpm/aws-cdk-lib@2.23.0_constructs@10.0.130/node_modules/aws-cdk-lib/custom-resources/lib/aws-custom-resource/aws-custom-resource.ts:501:8)
    at new AwsCustomResource (/path/cdk/node_modules/.pnpm/aws-cdk-lib@2.23.0_constructs@10.0.130/node_modules/aws-cdk-lib/custom-resources/lib/aws-custom-resource/aws-custom-resource.ts:359:9)
    at new CdkStack (/path/cdk/lib/cdk-stack.ts:35:33)
    at Object.<anonymous> (/path/cdk/bin/cdk.ts:11:1)
    at Module._compile (node:internal/modules/cjs/loader:1105:14)
    at Module.m._compile (/path/cdk/node_modules/.pnpm/ts-node@10.7.0_l47be6km5p57gglrggidw5gsgm/node_modules/ts-node/src/index.ts:1455:23)
    at Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
    at Object.require.extensions.<computed> [as .ts] (/path/cdk/node_modules/.pnpm/ts-node@10.7.0_l47be6km5p57gglrggidw5gsgm/node_modules/ts-node/src/index.ts:1458:12)
    at Module.load (node:internal/modules/cjs/loader:981:32)

```

### Reproduction Steps

```
import { Construct } from 'constructs';
import { aws_ec2 as ec2, aws_ecs as ecs, aws_logs as logs, custom_resources as cr, Stack, StackProps } from 'aws-cdk-lib';

export class CdkStack extends Stack {
    constructor(scope: Construct, id: string, props?: StackProps) {
        super(scope, id, props);

        const taskDefintion = new ecs.FargateTaskDefinition(this, 'taskDefinition', {
            cpu: 1024,
            memoryLimitMiB: 8192,
            ephemeralStorageGiB: 50,
        });

        const vpc = new ec2.Vpc(this, 'Vpc', {
            cidr: '10.0.0.0/20',
            natGateways: 0,
            maxAzs: 2,
        });

        const cluster = new ecs.Cluster(this, 'Cluster', {
            vpc: vpc,
        });

        const onEvent = {
            service: 'ECS',
            action: 'runTask',
            parameters: {
                cluster: cluster,
                taskDefinition: taskDefintion.taskDefinitionArn,
                launchType: ecs.LaunchType.FARGATE,
            },
            physicalResourceId: cr.PhysicalResourceId.of(taskDefintion.taskDefinitionArn),
        };

        const runTaskResource = new cr.AwsCustomResource(this, 'EcsRunTask', {
            onCreate: onEvent,
            policy: cr.AwsCustomResourcePolicy.fromSdkCalls({ resources: [ taskDefintion.taskDefinitionArn ] }),
            logRetention: logs.RetentionDays.ONE_WEEK,
            resourceType: 'Custom::RunTask',
        });
    }
}
```

Commenting out the line 

`cluster: cluster,`

synthesizes - but then we are missing the cluster we defined before

### CDK CLI Version

2.23.0

### Node.js Version

16.15.0

### OS

macOS

### Language

Typescript

**Comment by geoynomous** [comment]
Probably a problem with `JSON.stringify` the `cluster` in `includesPhysicalResourceIdRef` function

**Comment by geoynomous** [comment]
p.s. it used to work with 1.143.0

**Comment by geoynomous** [comment]
any feedback here?

**Comment by jogold** [comment]
Should be: `cluster: cluster.clusterArn` in `parameters`.

The API expects a string.

**Comment by geoynomous** [comment]
That solved it - thanks.

BTW: Why there is no "Run Task" in ECS module? Only "Run Service"
