### ISSUE TITLE
aws-apigateway: RequestAuthorizer cyclic reference error

### ISSUE THREAD

**Issue by mk0sojo** [aws/aws-cdk#20342]
### Describe the bug

We got two stacks, one for lambdas and one for API Gateway. When using a auth lambda function from the lambda stack in the API Gateway stack we get a cyclic reference error.

### Expected Behavior

No circular reference error

### Current Behavior

Circular reference error:
Error: 'LambdaStack' depends on 'Api' (LambdaStack -> Api/Api/Resource.Ref, LambdaStack -> Api/Authorizer/Resource.Ref). Adding this dependency (Api -> LambdaStack/AuthFunction/Resource.Arn) would create a cyclic reference.
    at ApiStack._addAssemblyDependency (C:\git\cdk-test\node_modules\aws-cdk-lib\core\lib\stack.ts:747:13)
    at Object.addDependency (C:\git\cdk-test\node_modules\aws-cdk-lib\core\lib\deps.ts:52:20)
    at ApiStack.addDependency (C:\git\cdk-test\node_modules\aws-cdk-lib\core\lib\stack.ts:484:5)
    at resolveValue (C:\git\cdk-test\node_modules\aws-cdk-lib\core\lib\private\refs.ts:100:12)
    at Object.resolveReferences (C:\git\cdk-test\node_modules\aws-cdk-lib\core\lib\private\refs.ts:30:24)
    at Object.prepareApp (C:\git\cdk-test\node_modules\aws-cdk-lib\core\lib\private\prepare-app.ts:30:3)
    at Object.synthesize (C:\git\cdk-test\node_modules\aws-cdk-lib\core\lib\private\synthesis.ts:32:3)
    at App.synth (C:\git\cdk-test\node_modules\aws-cdk-lib\core\lib\stage.ts:176:23)
    at process.<anonymous> (C:\git\cdk-test\node_modules\aws-cdk-lib\core\lib\app.ts:131:45)
    at Object.onceWrapper (node:events:510:26)

### Reproduction Steps

Create a new app with cdk init language=typescript with CDK 2.24.1 in a folder called cdk-test.

Modify bin/cdk-test.ts
```typescript
#!/usr/bin/env node
import 'source-map-support/register';
import * as cdk from 'aws-cdk-lib';
import { LambdaStack } from '../lib/lamdba/lambda';
import { ApiStack } from '../lib/api/api';

const app = new cdk.App();

const lamdbaStack = new LambdaStack(app, 'LambdaStack');

new ApiStack(app, 'Api', lamdbaStack.authFunction);
```

Add Lambda Stack (lib/lambda.ts):
```typescript
import * as cdk from 'aws-cdk-lib';
import * as lambda from 'aws-cdk-lib/aws-lambda-nodejs';
import { Construct } from 'constructs';
import * as path from 'path';

export class LambdaStack extends cdk.Stack {
  public readonly authFunction: lambda.NodejsFunction;

  constructor(scope: Construct, id: string, props?: cdk.StackProps) {
    super(scope, id, props);

    this.authFunction = new lambda.NodejsFunction(this, 'AuthFunction', {
      entry: path.join(__dirname, 'index.ts'),
    });
  }
}

```

Add API Gateway Stack (lib/api.ts)
```typescript
import * as cdk from 'aws-cdk-lib';
import { Construct } from 'constructs';
import * as apigateway from 'aws-cdk-lib/aws-apigateway';
import * as lambda from 'aws-cdk-lib/aws-lambda';

export class ApiStack extends cdk.Stack {
  constructor(
    scope: Construct,
    id: string,
    authFunction: lambda.Function,
    props?: cdk.StackProps,
  ) {
    super(scope, id);

    const authorizer = new apigateway.RequestAuthorizer(this, 'Authorizer', {
      handler: authFunction,
      identitySources: [apigateway.IdentitySource.header('Authorization')],
    });

    const api = new apigateway.RestApi(this, 'Api', {
      defaultMethodOptions: {
        authorizer,
      },
    });

    api.root.addResource('books').addMethod('GET');
  }
}

```

Run cdk synth

### CDK CLI Version

2.24.1

### Node.js Version

16.13.1

### OS

Windows 10

### Language

Typescript

### Language Version

3.9.7

**Comment by Jacco** [comment]
I think the code below solves this problem. Passing around interfaces between stacks does not always work.

```typescript
import * as cdk from 'aws-cdk-lib';
import { Construct } from 'constructs';
import * as apigateway from 'aws-cdk-lib/aws-apigateway';
import * as lambda from 'aws-cdk-lib/aws-lambda';

export class ApiStack extends cdk.Stack {
  constructor(
    scope: Construct,
    id: string,
    authFunction: lambda.Function,
    props?: cdk.StackProps,
  ) {
    super(scope, id);

    const func = lambda.Function.fromFunctionArn(this, 'AuthFunction', authFunction.functionArn);

    const authorizer = new apigateway.RequestAuthorizer(this, 'Authorizer', {
      handler: func,
      identitySources: [apigateway.IdentitySource.header('Authorization')],
    });

    const api = new apigateway.RestApi(this, 'Api', {
      defaultMethodOptions: {
        authorizer,
      },
    });

    api.root.addResource('books').addMethod('GET');
  }
}
```

**Comment by Jacco** [comment]
Not sure if cdk could be smarter with something like this in the RequestAuthorizer constructor:

```typescript
    let handler = props.handler;
    if (props.handler.stack != this.stack) {
      handler = lambda.Function.fromFunctionArn(this, 'Lambda', props.handler.functionArn)
    }
```

**Comment by mk0sojo** [comment]
Thanks for the quick reply. That work around seems to be working.
