### ISSUE TITLE
aws_elasticloadbalancingv2: connecting two ALBs

### ISSUE THREAD

**Issue by faemmi** [aws/aws-cdk#20571]
### Describe the bug

Hey,

I am currently trying to forward traffic from a public Application Load Balancer (ALB) to a private ALB. I know this seems to work with NLB+ALB (see [`aws_cdk.aws_elasticloadbalancingv2_targets.AlbTarget`](https://docs.aws.amazon.com/cdk/api/v2/python/aws_cdk.aws_elasticloadbalancingv2_targets/AlbTarget.html), and using a NLB, my below code example synthesizes) but trying with ALB+ALB throws an error.

### Expected Behavior

ALB forwarding traffic to another ALB.

### Current Behavior

```commandline
$ cdk <...> synth
jsii.errors.JavaScriptError:
  TypeError: target.attachToApplicationTargetGroup is not a function
      at ApplicationTargetGroup.addTarget (/tmp/jsii-kernel-7lVcR2/node_modules/aws-cdk-lib/aws-elasticloadbalancingv2/lib/alb/application-target-group.js:1:2743)
      at new ApplicationTargetGroup (/tmp/jsii-kernel-7lVcR2/node_modules/aws-cdk-lib/aws-elasticloadbalancingv2/lib/alb/application-target-group.js:1:1943)
      at ApplicationListener.addTargets (/tmp/jsii-kernel-7lVcR2/node_modules/aws-cdk-lib/aws-elasticloadbalancingv2/lib/alb/application-listener.js:1:5920)
      at /tmp/tmp51h2symn/lib/program.js:8236:134
      at Kernel._wrapSandboxCode (/tmp/tmp51h2symn/lib/program.js:8848:24)
      at /tmp/tmp51h2symn/lib/program.js:8236:107
      at Kernel._ensureSync (/tmp/tmp51h2symn/lib/program.js:8829:28)
      at Kernel.invoke (/tmp/tmp51h2symn/lib/program.js:8236:34)
      at KernelHost.processRequest (/tmp/tmp51h2symn/lib/program.js:9769:36)
      at KernelHost.run (/tmp/tmp51h2symn/lib/program.js:9732:22)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/<user>/<path>/app.py", line 8, in <module>
    stack.Stack(
  File "/home/<user>/.cache/pypoetry/virtualenvs/<python-package>-lr_F2LJr-py3.9/lib/python3.9/site-packages/jsii/_runtime.py", line 86, in __call__
    inst = super().__call__(*args, **kwargs)
  File "/home/<user>/<path>/src/<python package>/stack.py", line 90, in __init__
    target_group = public_load_balancer.add_targets(
  File "/home/<user>/<path>/src/<python package>/_load_balancing.py", line 108, in add_targets
    target_group = self.listener.add_targets(
  File "/home/<user>/.cache/pypoetry/virtualenvs/<python-package>-lr_F2LJr-py3.9/lib/python3.9/site-packages/aws_cdk/aws_elasticloadbalancingv2/__init__.py", line 13714, in add_targets
    return typing.cast("ApplicationTargetGroup", jsii.invoke(self, "addTargets", [id, props]))
  File "/home/<user>/.cache/pypoetry/virtualenvs/<python-package>-lr_F2LJr-py3.9/lib/python3.9/site-packages/jsii/_kernel/__init__.py", line 143, in wrapped
    return _recursize_dereference(kernel, fn(kernel, *args, **kwargs))
  File "/home/<user>/.cache/pypoetry/virtualenvs/<python-package>-lr_F2LJr-py3.9/lib/python3.9/site-packages/jsii/_kernel/__init__.py", line 355, in invoke
    response = self.provider.invoke(
  File "/home/<user>/.cache/pypoetry/virtualenvs/<python-package>-lr_F2LJr-py3.9/lib/python3.9/site-packages/jsii/_kernel/providers/process.py", line 359, in invoke
    return self._process.send(request, InvokeResponse)
  File "/home/<user>/.cache/pypoetry/virtualenvs/<python-package>-lr_F2LJr-py3.9/lib/python3.9/site-packages/jsii/_kernel/providers/process.py", line 326, in send
    raise JSIIError(resp.error) from JavaScriptError(resp.stack)
jsii.errors.JSIIError: target.attachToApplicationTargetGroup is not a function
```

### Reproduction Steps

Minimal code example to reproduce:

```Python
import aws_cdk.aws_elasticloadbalancingv2 as elbv2
import aws_cdk.aws_elasticloadbalancingv2_targets as elbv2_targets

# scope: aws_cdk.Stack
# vpc: aws_cdk.aws_ec2.Vpc

public_alb = elbv2.ApplicationLoadBalancer(
    scope,
    "public-alb",
    internet_facing=True,
    vpc=vpc,
)

private_alb = elbv2.ApplicationLoadBalancer(
    scope,
    "private-alb",
    internet_facing=False,
    vpc=vpc,
)

public_alb_listener = public_alb.add_listener(
    "PrivateListener",
    port=80,
    protocol=elbv2.ApplicationProtocol.HTTP,
)

public_alb_listener.add_targets(
    "Target",
    targets=[elbv2_targets.AlbTarget(private_alb, 80)],
    port=80
)
```
As said, using `elbv2.NetworkLoadBalancer` for the public load balancer at least synthesizes. I didn't test whether deployment works.

### Possible Solution

Looking in [the source code of `AlbTarget`](https://github.com/aws/aws-cdk/blob/master/packages/%40aws-cdk/aws-elasticloadbalancingv2-targets/lib/alb-target.ts) obviously shows that the method `attachToApplicationTargetGroup` is not implemented, but is this just a missing feature or is it maybe technically just not possible to attach an ALB as a target to another ALB listener?

Best regards
faemmi

### CDK CLI Version

2.26.0

### Node.js Version

v18.1.0

### OS

Ubuntu 20.04.4 LTS

### Language

Python

### Language Version

3.9.9

**Comment by faemmi** [comment]
Thanks for the reply. I was already worried that is setup is not possible.

The problem is that I need to implement authentication via Cognito UI, which only works with ALB, and JWT, which only works with API Gateway. I have a webserver running in an EC2 instance, which provides both a UI and a REST API. 

So the setup which works for me is ALB -> ALB+API Gateway -> EC2 instance. But now I have the problem that the API Gateway has a 10MB payload limit...

Anyway, thanks for your help.
Best
