### ISSUE TITLE
(cdk synth): (Unexpected token '?' Subprocess exited with error 1)

### ISSUE THREAD

**Issue by KARTHIKEYANBALAKRISHNAN** [aws/aws-cdk#20681]
### Describe the bug

Cdk synthesize fails with the following error.

Unexpected token '?'
Subprocess exited with error 1
Error: Subprocess exited with error 1
    at ChildProcess.<anonymous> (/opt/atlassian/pipelines/agent/build/cdk/node_modules/aws-cdk/lib/api/cxapp/exec.ts:122:23)
    at ChildProcess.emit (events.js:314:20)
    at ChildProcess.EventEmitter.emit (domain.js:483:12)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:276:12)

### Expected Behavior

Cdk synth should succeed

### Current Behavior

errors out -
Unexpected token '?'
Subprocess exited with error 1
Error: Subprocess exited with error 1
    at ChildProcess.<anonymous> (/opt/atlassian/pipelines/agent/build/cdk/node_modules/aws-cdk/lib/api/cxapp/exec.ts:122:23)
    at ChildProcess.emit (events.js:314:20)
    at ChildProcess.EventEmitter.emit (domain.js:483:12)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:276:12)

### Reproduction Steps

npm run cdk synth -- --verbose

### CDK CLI Version

1.87.0

### Node.js Version

12.22.12

### OS

Alpine

### Language

Typescript

### Language Version

4.1.2

### Other information

Related issue (https://github.com/aws/aws-cdk/issues/20678)

**Comment by traviswalker26** [comment]
I think this is related to the release of constructs https://github.com/aws/constructs/releases/tag/v3.4.32. A proprietary tool I'm using is giving me this error:
```
/usr/local/lib/node_modules/deployer/node_modules/constructs/lib/construct.js:501
const nodeFactory = options.nodeFactory ?? { createNode: (host, nodeScope, nodeId) => new Node(host, nodeScope, nodeId) };

SyntaxError: Unexpected token '?'
```
I'm also using node 12.22.12.

**Comment by peterwoodworth** [comment]
This should be fixed in the latest jsii release, let me know https://github.com/aws/jsii/releases/tag/v1.60.1

**Comment by KARTHIKEYANBALAKRISHNAN** [comment]
> This should be fixed in the latest jsii release, let me know https://github.com/aws/jsii/releases/tag/v1.60.1

Got it. That would fix the issue. For now, we went with Node18 upgrade. Thanks.
