### ISSUE TITLE
package/tools : java-lib - Role - unable to add assumeRolePolicy with conditioned principal

### ISSUE THREAD

**Issue by schabe77** [aws/aws-cdk#20746]
### Describe the bug

I try to add a assumeRolePolicy to a Role that was created with the same conditioned principal that was used to create the Role.

when running `cdk synth` I get this error:
```
Error: Resolution error: Resolution error: Resolution error: Trying to resolve() a Construct at /Resources/${Token[test-stack.logshipperRole.Resource.LogicalID.219]}/Properties/assumeRolePolicyDocument/Statement/0/Condition/ForAnyValue:StringEquals/node.
```

My (Java-)Stack looks like this:
```
    public TestStack(Construct parent) {
        super(parent, "test-stack");

        OpenIdConnectProvider provider = new OpenIdConnectProvider(this, "openid-connect-provider", OpenIdConnectProviderProps.builder()
                .url("https://my-provider-domain.s3.eu-central-1.amazonaws.com")
                .clientIds(List.of("sts.amazonaws.com"))
                .build());

        OpenIdConnectPrincipal principal = new OpenIdConnectPrincipal(provider, Map.of("ForAnyValue:StringEquals",
                CfnJson.Builder.create(this, "CfnJson")
                        .value(Map.of(provider.getOpenIdConnectProviderIssuer() + ":sub",
                                List.of("system:serviceaccount:account1", "system:serviceaccount:account2")))
                        .build()));

        Role role = new Role(this, "myRolename", RoleProps.builder()
                .assumedBy(principal)
                .build());

        PolicyStatement assumeRolePolicy = new PolicyStatement(PolicyStatementProps.builder()
                .actions(List.of("sts:AssumeRoleWithWebIdentity"))
                .effect(Effect.ALLOW)
                .principals(List.of(principal))
                .build());

        role.getAssumeRolePolicy().addStatements(assumeRolePolicy);
    }
```

When doing the same in Typescript:
```
import { CfnJson, Stack } from 'aws-cdk-lib';
import { Construct } from 'constructs';
import { Effect, OpenIdConnectPrincipal, OpenIdConnectProvider, PolicyStatement, Role } from 'aws-cdk-lib/aws-iam';

export class TestStack extends Stack {

    constructor(parent: Construct) {
        super(parent, "test-stack");

        const provider = new OpenIdConnectProvider(this, "openid-connect-provider", {
            url: 'https://my-provider-domain.s3.eu-central-1.amazonaws.com',
            clientIds: ['sts.amazonaws.com']
        });

        const principal = new OpenIdConnectPrincipal(provider).withConditions({
            'ForAnyValue:StringEquals': new CfnJson(this, 'CfnJson', {
                value: {
                    [`${provider.openIdConnectProviderIssuer}:sub`]: ['system:serviceaccount:account1', 'system:serviceaccount:account2'],
                },
            }),
        });

        const role = new Role(this, "myRolename", {
            assumedBy: principal
        });

        const assumeRolePolicy = new PolicyStatement({
            actions: ['sts:AssumeRoleWithWebIdentity'],
            effect: Effect.ALLOW,
            principals: [principal]
        });

        role.assumeRolePolicy?.addStatements(assumeRolePolicy);
    }
}
```
`cdk synth`runs without problems.

### Expected Behavior

I want my Stack to be transformed to a CloudFormation template without any errors. The target Policy should look like this:
```
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Effect": "Allow",
            "Principal": {
                "Federated": "arn:aws:iam::ACCOUNT_ID:oidc-provider/my-provider-domain.s3.eu-central-1.amazonaws.com"
            },
            "Action": "sts:AssumeRoleWithWebIdentity",
            "Condition": {
                "ForAnyValue:StringEquals": {
                    "my-provider-domain.s3.eu-central-1.amazonaws.com:sub": [
                        "system:serviceaccount:account1",
                        "system:serviceaccount:account2"
                    ]
                }
            }
        }
    ]
}
```

### Current Behavior

The error that occurs when running `cdk synth` with the Java Stack class is:
```
Error: Resolution error: Resolution error: Resolution error: Trying to resolve() a Construct at /Resources/${Token[test-stack.logshipperRole.Resource.LogicalID.219]}/Properties/assumeRolePolicyDocument/Statement/0/Condition/ForAnyValue:StringEquals/node.
Object creation stack:
  at new PolicyDocument (/tmp/jsii-kernel-xJFE6c/node_modules/aws-cdk-lib/aws-iam/lib/policy-document.js:1:758)
  at createAssumeRolePolicy (/tmp/jsii-kernel-xJFE6c/node_modules/aws-cdk-lib/aws-iam/lib/role.js:1:10465)
  at new Role (/tmp/jsii-kernel-xJFE6c/node_modules/aws-cdk-lib/aws-iam/lib/role.js:1:1390)
  at /tmp/jsii-java-runtime6519317117772059611/lib/program.js:8171:58
  at Kernel._wrapSandboxCode (/tmp/jsii-java-runtime6519317117772059611/lib/program.js:8592:24)
  at Kernel._create (/tmp/jsii-java-runtime6519317117772059611/lib/program.js:8171:34)
  at Kernel.create (/tmp/jsii-java-runtime6519317117772059611/lib/program.js:7919:29)
  at KernelHost.processRequest (/tmp/jsii-java-runtime6519317117772059611/lib/program.js:9506:36)
  at KernelHost.run (/tmp/jsii-java-runtime6519317117772059611/lib/program.js:9469:22)
  at Immediate._onImmediate (/tmp/jsii-java-runtime6519317117772059611/lib/program.js:9470:46)
  at processImmediate (node:internal/timers:466:21)..
    at resolve (/tmp/jsii-kernel-xJFE6c/node_modules/aws-cdk-lib/core/lib/private/resolve.js:1:2787)
    at Object.resolve (/tmp/jsii-kernel-xJFE6c/node_modules/aws-cdk-lib/core/lib/private/resolve.js:1:1136)
    at resolve (/tmp/jsii-kernel-xJFE6c/node_modules/aws-cdk-lib/core/lib/private/resolve.js:1:2958)
    at Object.resolve (/tmp/jsii-kernel-xJFE6c/node_modules/aws-cdk-lib/core/lib/private/resolve.js:1:1136)
    at resolve (/tmp/jsii-kernel-xJFE6c/node_modules/aws-cdk-lib/core/lib/private/resolve.js:1:2958)
    at Object.resolve (/tmp/jsii-kernel-xJFE6c/node_modules/aws-cdk-lib/core/lib/private/resolve.js:1:1136)
    at resolve (/tmp/jsii-kernel-xJFE6c/node_modules/aws-cdk-lib/core/lib/private/resolve.js:1:2958)
    at Object.resolve (/tmp/jsii-kernel-xJFE6c/node_modules/aws-cdk-lib/core/lib/private/resolve.js:1:1136)
    at /tmp/jsii-kernel-xJFE6c/node_modules/aws-cdk-lib/core/lib/private/resolve.js:1:2522
    at Array.map (<anonymous>)
```

### Reproduction Steps

Try to use this Stack class to create a CloudFormation template.
```
import java.util.List;
import java.util.Map;

import software.amazon.awscdk.CfnJson;
import software.amazon.awscdk.Stack;
import software.amazon.awscdk.services.iam.Effect;
import software.amazon.awscdk.services.iam.OpenIdConnectPrincipal;
import software.amazon.awscdk.services.iam.OpenIdConnectProvider;
import software.amazon.awscdk.services.iam.OpenIdConnectProviderProps;
import software.amazon.awscdk.services.iam.PolicyStatement;
import software.amazon.awscdk.services.iam.PolicyStatementProps;
import software.amazon.awscdk.services.iam.Role;
import software.amazon.awscdk.services.iam.RoleProps;
import software.constructs.Construct;

public class TestStack extends Stack {

    public TestStack(Construct parent) {
        super(parent, "test-stack");

        OpenIdConnectProvider provider = new OpenIdConnectProvider(this, "openid-connect-provider", OpenIdConnectProviderProps.builder()
                .url("https://my-provider-domain.s3.eu-central-1.amazonaws.com")
                .clientIds(List.of("sts.amazonaws.com"))
                .build());

        OpenIdConnectPrincipal principal = new OpenIdConnectPrincipal(provider, Map.of("ForAnyValue:StringEquals",
                CfnJson.Builder.create(this, "CfnJson")
                        .value(Map.of(provider.getOpenIdConnectProviderIssuer() + ":sub",
                                List.of("system:serviceaccount:account1", "system:serviceaccount:account2")))
                        .build()));

        Role role = new Role(this, "myRolename", RoleProps.builder()
                .assumedBy(principal)
                .build());

        PolicyStatement assumeRolePolicy = new PolicyStatement(PolicyStatementProps.builder()
                .actions(List.of("sts:AssumeRoleWithWebIdentity"))
                .effect(Effect.ALLOW)
                .principals(List.of(principal))
                .build());

        role.getAssumeRolePolicy().addStatements(assumeRolePolicy);
    }
}
```

### CDK CLI Version

2.28.0 (build ba233f0)

### Node.js Version

v16.15.1

### OS

Linux

### Language

Java

### Language Version

Java (11)

**Comment by indrora** [comment]
Tried, got the same answer.

Looks like something in jsii.

**Comment by rix0rrr** [comment]
Pretty sure the reason is you need to call `.toString()` on the `CfnJson` object.

Not sure why that happens automatically in JavaScript and not in Java...

**Comment by rix0rrr** [comment]
Aha okay you shouldn't *need* to, because `CfnJson` implements `IResolvable`, which `resolve()` should recognize and treat specially.

* It probably *is* a jsii issue that we don't recognize this object as being `IResolvable`.
* Calling `toString()` on it should probably still work to get around this issue.

**Comment by corymhall** [comment]
@schabe77 I think your issue is with this piece of code

```java
PolicyStatement assumeRolePolicy = new PolicyStatement(PolicyStatementProps.builder()
                .actions(List.of("sts:AssumeRoleWithWebIdentity"))
                .effect(Effect.ALLOW)
                .principals(List.of(principal))
                .build());

 role.getAssumeRolePolicy().addStatements(assumeRolePolicy);
```

I got the same error message in both Java _and_ typescript when I tried your example. When I removed this code it worked. This code isn't needed since it is re-adding the same policy statement that already gets added when you supply the principal to the role's `assumedBy` property.

**Comment by schabe77** [comment]
Yes, it seems to work now. The role is now created as expected. 
Maybe it's how @indrora said: it must have been jsii (when I reported the issue it was version 1.60.1, now it's 1.72.0)
