### ISSUE TITLE
ECS: Memory reservation is not optional

### ISSUE THREAD

**Issue by parisholley** [aws/aws-cdk#20785]
### Describe the bug

task memory config is required in CDK but not supported by windows instances

https://github.com/aws/aws-cdk/blob/ddb4766785e27fbd4d672a5ff31fb07c3d3d389a/packages/%40aws-cdk/aws-ecs/lib/base/task-definition.ts#L682-L695

### Expected Behavior

should allow it to be undefined 

### Current Behavior

throws exception

### Reproduction Steps

leave out memory keys

### CDK CLI Version

latest

### Node.js Version

16

### OS

mac

### Language

Typescript

**Comment by mrgrain** [comment]
Reference: https://docs.aws.amazon.com/AmazonECS/latest/developerguide/task_definition_parameters.html#container_definition_memory

**Comment by homakk** [comment]
Solution for your problem:

If you dont want a memory limit for the container, simply set any value in `memoryReservationMiB` , and configure the agent to use `ECS_ENABLE_MEMORY_UNBOUNDED_WINDOWS_WORKAROUND` environment variable .

for reference you can check this documents
https://github.com/aws/amazon-ecs-agent/blob/master/README.md#environment-variables
https://docs.aws.amazon.com/AmazonECS/latest/developerguide/ecs-agent-config.html

**Comment by homakk** [comment]
My feedback for this ticket after working on it:

Looks like the API does accept memoryReservationMiB for windows containers
there is a use case for setting `memoryReservationMiB` but not `memoryLimitMib`
customers can set a `ECS_ENABLE_MEMORY_UNBOUNDED_WINDOWS_WORKAROUND` environment variable, to run Windows containers without memory limits.

Which is documented here: https://github.com/aws/amazon-ecs-agent/blob/master/README.md

When `true`, ECS will ignore the memory reservation parameter (soft limit) to run along with memory bounded tasks in Windows. To run a memory unbounded task, omit the memory hard limit and set any memory reservation, it will be ignored.

So cdk to require either memory limits for windows containers.

@parisholley if you dont want a memory limit for the container, simply set any value in `memoryReservationMiB` , and configure the agent to use `ECS_ENABLE_MEMORY_UNBOUNDED_WINDOWS_WORKAROUND` environment variable .

For reference you can check following docs:
https://github.com/aws/amazon-ecs-agent/blob/master/README.md#environment-variables
https://docs.aws.amazon.com/AmazonECS/latest/developerguide/ecs-agent-config.html

**Comment by pahud** [comment]
Yes the root cause is at

https://github.com/aws/aws-cdk/blob/e03939d0091bfb24923619161948aad67524315e/packages/aws-cdk-lib/aws-ecs/lib/base/task-definition.ts#L810-L818

Possible Fix

```ts
// Proposed fix would modify the validation to check for Windows containers
if (!this._memory) {
  for (const container of this.containers) {
    // Skip validation for Windows containers
    if (!this.runtimePlatform?.operatingSystemFamily?.isWindows() && 
        !container.memoryLimitSpecified) {
      ret.push(`ECS Container ${container.containerName} must have at least one of 'memoryLimitMiB' or 'memoryReservationMiB' specified`);
    }
  }
}
```

Upgrading to p1 and will bring this up to the team for visibility. Meanwhile, as this should be a tiny fix, any PRs from the community is always welcome.

**Comment by Yogagh** [comment]
Thank you @pahud . Yes, that fix would solve our problem with this unnecessary validation and we can take out defining CPU & Memory range(s) in the Windows TaskDefinition. Please keep us posted when ur PR with the above code changes goes live!!!

**Comment by Abogical** [comment]
Hi @Yogagh ! Just to confirm, which validation error do you receive? Is it `ECS Container <Container name> must have at least one of...` or `Fargate-compatible tasks require both CPU (undefined) and memory (undefined) specifications`?

**Comment by Yogagh** [comment]
@pahud FYI:

Error: The sum of all container cpu values cannot be greater than the value of the task cpu
    at FargateTaskDefinition._linkContainer (/home/runner/work/sam-container/sam-container/node_modules/aws-cdk-lib/aws-ecs/lib/base/task-definition.js:1:11099)
    at new ContainerDefinition (/home/runner/work/sam-container/sam-container/node_modules/aws-cdk-lib/aws-ecs/lib/container-definition.js:1:3952)
    at FargateTaskDefinition.addContainer (/home/runner/work/sam-container/sam-container/node_modules/aws-cdk-lib/aws-ecs/lib/base/task-definition.js:1:10269)
    at new SAMUIStack (/home/runner/work/sam-container/sam-container/infra/lib/stack/sam-ui.ts:281:47)
    at Object.<anonymous> (/home/runner/work/sam-container/sam-container/infra/bin/samui-service.ts:17:22)
    at Module._compile (node:internal/modules/cjs/loader:1554:14)
    at Module.m._compile (/home/runner/work/sam-container/sam-container/node_modules/ts-node/src/index.ts:1618:23)
    at node:internal/modules/cjs/loader:1706:10
    at Object.require.extensions.<computed> [as .ts] (/home/runner/work/sam-container/sam-container/node_modules/ts-node/src/index.ts:1621:12)
    at Module.load (node:internal/modules/cjs/loader:1289:32)

**Comment by Abogical** [comment]
Hi @Yogagh !

It appears our [ECS documentation you linked](https://docs.aws.amazon.com/AmazonECS/latest/developerguide/task_definition_parameters.html#task_size) concerning Fargate task size for Windows is misleading. Fargate task definitions **require** the `memory` and `cpu` properties defined for Fargate tasks, even if they are ignored by ECS:
> **For tasks that are hosted on Fargate (both Linux and Windows), these fields are required** and there are specific values for both cpu and memory that are supported.
>
> _Note_
**Task-level CPU and memory parameters are ignored for Windows containers.** We recommend specifying container-level resources for Windows containers.

These two statements seem to be contradicting each other at first glance. I've made a request to the ECS team to either update their config or update their docs to stress that the properties will still be required even if they are ignored.
