### ISSUE TITLE
(cli): format of tags in cdk.json is not validated, easy to get wrong

### ISSUE THREAD

**Issue by SydneyUni-Jim** [aws/aws-cdk#20854]
### Describe the bug

After adding tags to the local cdk.json, `cdk deploy` fails with an `InvalidParameterType: Expected params.Tags to be an Array` from aws-sdk.

### Expected Behavior

The synthesized template deploys with the tags in cdk.json.

### Current Behavior

```
❯ cdk deploy

✨  Synthesis time: 3.04s

HelloCdkStack: deploying...
[0%] start: Publishing 774231a5b4dfea162ee0964f8335b364aee003aa142c95fb1c4d3e49537db261:current_account-current_region
[100%] success: Published 774231a5b4dfea162ee0964f8335b364aee003aa142c95fb1c4d3e49537db261:current_account-current_region
HelloCdkStack: creating CloudFormation changeset...

 ❌  HelloCdkStack failed: InvalidParameterType: Expected params.Tags to be an Array
    at ParamValidator.fail (/opt/homebrew/Cellar/aws-cdk/2.29.0/libexec/lib/node_modules/aws-sdk/lib/param_validator.js:50:37)
    at ParamValidator.validateType (/opt/homebrew/Cellar/aws-cdk/2.29.0/libexec/lib/node_modules/aws-sdk/lib/param_validator.js:233:10)
    at ParamValidator.validateList (/opt/homebrew/Cellar/aws-cdk/2.29.0/libexec/lib/node_modules/aws-sdk/lib/param_validator.js:100:14)
    at ParamValidator.validateMember (/opt/homebrew/Cellar/aws-cdk/2.29.0/libexec/lib/node_modules/aws-sdk/lib/param_validator.js:91:21)
    at ParamValidator.validateStructure (/opt/homebrew/Cellar/aws-cdk/2.29.0/libexec/lib/node_modules/aws-sdk/lib/param_validator.js:76:14)
    at ParamValidator.validateMember (/opt/homebrew/Cellar/aws-cdk/2.29.0/libexec/lib/node_modules/aws-sdk/lib/param_validator.js:89:21)
    at ParamValidator.validate2 [as validate] (/opt/homebrew/Cellar/aws-cdk/2.29.0/libexec/lib/node_modules/aws-sdk/lib/param_validator.js:34:10)
    at Request.VALIDATE_PARAMETERS (/opt/homebrew/Cellar/aws-cdk/2.29.0/libexec/lib/node_modules/aws-sdk/lib/event_listeners.js:132:42)
    at Request.callListeners (/opt/homebrew/Cellar/aws-cdk/2.29.0/libexec/lib/node_modules/aws-sdk/lib/sequential_executor.js:106:20)
    at callNextListener (/opt/homebrew/Cellar/aws-cdk/2.29.0/libexec/lib/node_modules/aws-sdk/lib/sequential_executor.js:96:12) {
  code: 'InvalidParameterType',
  time: 2022-06-24T02:18:15.714Z
}

Expected params.Tags to be an Array
```

### Reproduction Steps

1. `mkdir hello-cdk`
2. `cd hello-cdk`
3. `cdk init app --language typescript`
4. `cdk deploy`

So far this works.

1. Replace cdk.json with this [cdk.json](https://github.com/aws/aws-cdk/files/8972763/cdk.json.txt).
2. `cdk deploy`

This fails.

### CDK CLI Version

2.29.0 (build 47d7ec4)

### Node.js Version

v16.15.1

### OS

macOS 12.4 arm64

### Language

Typescript

### Language Version

4.7.4

### Other information

Documentation reference: https://docs.aws.amazon.com/cdk/v2/guide/cli.html#cli-config

> tags - JSON object containing tags (key-value pairs) for the stack.

**Comment by SydneyUni-Jim** [comment]
For reference the replacement cdk.json is.

```json
{
  "app": "npx ts-node --prefer-ts-exts bin/hello-cdk.ts",
  "context": {
    "@aws-cdk-containers/ecs-service-extensions:enableDefaultLogDriver": true,
    "@aws-cdk/aws-apigateway:usagePlanKeyOrderInsensitiveId": true,
    "@aws-cdk/aws-cloudfront:defaultSecurityPolicyTLSv1.2_2021": true,
    "@aws-cdk/aws-codepipeline:crossAccountKeyAliasStackSafeResourceName": true,
    "@aws-cdk/aws-ec2:uniqueImdsv2TemplateName": true,
    "@aws-cdk/aws-iam:minimizePolicies": true,
    "@aws-cdk/aws-lambda:recognizeLayerVersion": true,
    "@aws-cdk/aws-lambda:recognizeVersionProps": true,
    "@aws-cdk/aws-rds:lowercaseDbIdentifier": true,
    "@aws-cdk/core:checkSecretUsage": true,
    "@aws-cdk/core:stackRelativeExports": true,
    "@aws-cdk/core:target-partitions": ["aws"],
    "@aws-cdk/core:validateSnapshotRemovalPolicy": true
  },
  "tags": {
    "Tag1": "value1",
    "Tag2": "value2"
  },
  "watch": {
    "include": [
      "**"
    ],
    "exclude": [
      "README.md",
      "cdk*.json",
      "**/*.d.ts",
      "**/*.js",
      "tsconfig.json",
      "package*.json",
      "yarn.lock",
      "node_modules",
      "test"
    ]
  }
}
```

**Comment by rix0rrr** [comment]
This is sorely underdocumented, and if I were you I would put the tags in the CDK App rather than in the CLI config, but for reference the format of the tag field needs to be:

```ts
{
  "tags": [
    {
       "Key": "...",
       "Value": "..."
     }
  ]
}
```
