### ISSUE TITLE
(various): Docker errors are not surfaced well

### ISSUE THREAD

**Issue by indrora** [aws/aws-cdk#20892]
### Describe the bug

In quite a few different scenarios, Docker errors simply happen and "Docker returned 1" gets spat out. 

I suspect Docker is writing to stderr but it is getting squashed somewhere. 

### Expected Behavior

Docker outputs (both stdout and stderr are preserved)

### Current Behavior

Docker's error status isn't printed

### Reproduction Steps

* Run `cdk synth` on a stack that requires docker, but without permissions to talk to Docker's control plane
* watch as it crashes and burns:

```
39907defbe84: Pull complete
8f7631647f07: Pull complete
d83e11d24ec9: Pull complete
b09b92bf5cf8: Pull complete
[WARNING] 
software.amazon.jsii.JsiiException: docker exited with status 1
Error: docker exited with status 1
    at dockerExec (/tmp/jsii-kernel-ENBrAx/node_modules/@aws-cdk/core/lib/bundling.js:355:15)
    at Function.fromBuild (/tmp/jsii-kernel-ENBrAx/node_modules/@aws-cdk/core/lib/bundling.js:243:9)
    at new Bundling (/tmp/jsii-kernel-ENBrAx/node_modules/@aws-cdk/aws-lambda-python/lib/bundling.js:28:86)
    at Function.bundle (/tmp/jsii-kernel-ENBrAx/node_modules/@aws-cdk/aws-lambda-python/lib/bundling.js:43:50)
    at new PythonFunction (/tmp/jsii-kernel-ENBrAx/node_modules/@aws-cdk/aws-lambda-python/lib/function.js:43:39)
```

The error that is being quashed here was `Got permission denied while trying to connect to the Docker daemon socket at unix:///var/run/docker.sock: Post "http://%2Fvar%2Frun%2Fdocker.sock/v1.24/images/create?fromImage=public.ecr.aws%2Fsam%2Fbuild-python3.7&tag=latest": dial unix /var/run/docker.sock: connect: permission denied`

### CDK CLI Version

head

### Node.js Version

16

### OS

AL2

### Language

Typescript, Python, .NET, Java, Go

**Comment by arewa** [comment]
Hi @indrora! Could you please clarify for which cdk version is this issue? I was trying to reproduce it with cdk v2 with no success, example of output I have is below. I tried to reproduce it with `cdk synth` command but it doesn't start docker build, so that I had to use `cdk deploy`:

```
 ~/P/aws-docker-test$ cdk deploy

✨  Synthesis time: 6.32s

AwsDockerTestStack: deploying...
[0%] start: Publishing d9d4986239b91b68b974caf54bae5e914332ab04fb41ac3397a24c2c712f4193:current_account-current_region
[0%] start: Publishing f93846c14badd708cbe90a2e2477ff7a41e84e74ad43f1e78fd5bd668bde045a:current_account-current_region
[50%] success: Published d9d4986239b91b68b974caf54bae5e914332ab04fb41ac3397a24c2c712f4193:current_account-current_region
[100%] fail: docker login --username AWS --password-stdin https://xxxxx.dkr.ecr.us-east-2.amazonaws.com exited with error code 1: Got permission denied while trying to connect to the Docker daemon socket at unix:///var/run/docker.sock: Post "http://%2Fvar%2Frun%2Fdocker.sock/v1.24/auth": dial unix /var/run/docker.sock: connect: permission denied

 ❌  AwsDockerTestStack failed: Error: Failed to publish one or more assets. See the error messages above for more information.
    at publishAssets (/usr/local/lib/node_modules/aws-cdk/lib/util/asset-publishing.ts:44:11)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at CloudFormationDeployments.publishStackAssets (/usr/local/lib/node_modules/aws-cdk/lib/api/cloudformation-deployments.ts:469:7)
    at CloudFormationDeployments.deployStack (/usr/local/lib/node_modules/aws-cdk/lib/api/cloudformation-deployments.ts:343:7)
    at CdkToolkit.deploy (/usr/local/lib/node_modules/aws-cdk/lib/cdk-toolkit.ts:210:24)
    at initCommandLine (/usr/local/lib/node_modules/aws-cdk/lib/cli.ts:347:12)

Failed to publish one or more assets. See the error messages above for more information
```.

**Comment by arewa** [comment]
I was able to reproduce the scenario with Python project from https://github.com/aws/aws-cdk/issues/13245. Tried with both latest v1 (1.165.0 (build 83f1668)) and v2 (2.33.0 (build 859272d)) but can see the message from the stderr. 
My steps:

```
// Unset "write" permission for Docker socket
$ chmod u-w /Users/alex/.docker/run/docker.sock

$ cdk synth
Got permission denied while trying to connect to the Docker daemon socket at unix:///var/run/docker.sock: Post "http://%2Fvar%2Frun%2Fdocker.sock/v1.24/build?buildargs=%7B%22IMAGE%22%3A%22amazon%2Faws-sam-cli-build-image-python3.6%22%7D&cachefrom=%5B%5D&cgroupparent=&cpuperiod=0&cpuquota=0&cpusetcpus=&cpusetmems=&cpushares=0&dockerfile=.dockerfile.b76903a2e5ac5e0540d2&labels=%7B%7D&memory=0&memswap=0&networkmode=default&rm=1&shmsize=0&t=cdk-107e80688e8daa3229d859441e3341ab72cf8e60c80b84397d285860ed0da156&target=&ulimits=null&version=1": dial unix /var/run/docker.sock: connect: permission denied
jsii.errors.JavaScriptError:
  Error: docker exited with status 1
      at dockerExec (/private/var/folders/b1/3kn1vfhd47n7q384kzm6kt4c0000gn/T/jsii-kernel-LDjYry/node_modules/@aws-cdk/core/lib/bundling.js:164:15)
      at Function.fromAsset (/private/var/folders/b1/3kn1vfhd47n7q384kzm6kt4c0000gn/T/jsii-kernel-LDjYry/node_modules/@aws-cdk/core/lib/bundling.js:50:9)
      at Object.bundle (/private/var/folders/b1/3kn1vfhd47n7q384kzm6kt4c0000gn/T/jsii-kernel-LDjYry/node_modules/@aws-cdk/aws-lambda-python/lib/bundling.js:33:43)
```

**Comment by samyakb** [comment]
Dont know if its relative, but I had the same issue of docker-permission denied. After adding `esbuild` as devDependency resolved the error issue.

**Comment by RahulSurwade08** [comment]
Hey @indrora @arewa I would love to contribute to this issue under hacktoberfest. How can i get started?

**Comment by arewa** [comment]
Hi @RahulSurwade08, you could start with an empty Python stack, and the steps I mentioned in my previous comment.
