### ISSUE TITLE
gitpod not prebuild correctly

### ISSUE THREAD

**Issue by pahud** [aws/aws-cdk#21063]
### Describe the bug

When opening the repo with GitPod, it throws the prebuild error

<img width="1134" alt="image" src="https://user-images.githubusercontent.com/278432/178075353-517705c9-9d67-4ec5-b788-a38a14f83fe7.png">

### Expected Behavior

to prebuild correctly with no error

### Current Behavior

gitpod@aws-awscdk-mork8kacwjx:/workspace/aws-cdk$  HISTFILE=/workspace/.gitpod/cmd-0 history -r; {
> [ -r /workspace/.prebuild-log-0 ] && cat /workspace/.prebuild-log-0; [ -r /workspace/.gitpod/prebuild-log-0 ] && cat /workspace/.gitpod/prebuild-log-0; true
> }
{
yarn build --skip-test --no-bail --skip-prereqs --skip-compat
}; exit
gitpod@aws-awscdk-r68tfij2ejz:/workspace/aws-cdk$ {
> yarn build --skip-test --no-bail --skip-prereqs --skip-compat
> }; exit
yarn run v1.22.19
$ node ./scripts/check-yarn-lock.js
internal/modules/cjs/loader.js:905
  throw err;
  ^

Error: Cannot find module '@lerna/project'
Require stack:
- /workspace/aws-cdk/scripts/check-yarn-lock.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:902:15)
    at Function.Module._load (internal/modules/cjs/loader.js:746:27)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at require (internal/modules/cjs/helpers.js:101:18)
    at Object.<anonymous> (/workspace/aws-cdk/scripts/check-yarn-lock.js:17:21)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:12)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:75:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [ '/workspace/aws-cdk/scripts/check-yarn-lock.js' ]
}
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
exit

🤙 This task ran as a workspace prebuild

### Reproduction Steps

Just open this repo with GitPod

### Possible Solution

Modify the init task here
https://github.com/aws/aws-cdk/blob/4e0c80f89353731edc6d5f7aba6539a4f340296c/.gitpod.yml#L9

to have it execute:

`yarn install && ./scripts/foreach.sh yarn build`

### CDK CLI Version

latest

### Node.js Version

all

### OS

gitpod

### Language

Typescript

**Comment by pahud** [comment]
I will try fix this with a PR.
