### ISSUE TITLE
aws-cdk-lib: PolicyStatement.toString overflows Map.set and crashes

### ISSUE THREAD

**Issue by ahmetsevki** [aws/aws-cdk#21062]
## The Error
Recently we introduced a construct called [cdk-monitoring-constructs](https://github.com/cdklabs/cdk-monitoring-constructs) into our stack.

At deployment time our cdk deploy gives the following error stack:

```
RangeError: Value undefined out of range for undefined options property undefined
    at Map.set (<anonymous>)
    at TokenMap.registerStringKey (/home/runner/work/hidrb/hidrb/common/temp/node_modules/.pnpm/aws-cdk-lib@2.31.0_constructs@10.1.42/node_modules/aws-cdk-lib/core/lib/private/token-map.js:1:2282)
    at /home/runner/work/hidrb/hidrb/common/temp/node_modules/.pnpm/aws-cdk-lib@2.31.0_constructs@10.1.42/node_modules/aws-cdk-lib/core/lib/private/token-map.js:1:665
    at cachedValue (/home/runner/work/hidrb/hidrb/common/temp/node_modules/.pnpm/aws-cdk-lib@2.31.0_constructs@10.1.42/node_modules/aws-cdk-lib/core/lib/private/token-map.js:1:2602)
    at TokenMap.registerString (/home/runner/work/hidrb/hidrb/common/temp/node_modules/.pnpm/aws-cdk-lib@2.31.0_constructs@10.1.42/node_modules/aws-cdk-lib/core/lib/private/token-map.js:1:613)
    at Function.asString (/home/runner/work/hidrb/hidrb/common/temp/node_modules/.pnpm/aws-cdk-lib@2.31.0_constructs@10.1.42/node_modules/aws-cdk-lib/core/lib/token.js:1:1244)
    at PolicyStatement.toString (/home/runner/work/hidrb/hidrb/common/temp/node_modules/.pnpm/aws-cdk-lib@2.31.0_constructs@10.1.42/node_modules/aws-cdk-lib/aws-iam/lib/policy-statement.js:2:5201)
    at realTypeOf (/home/runner/work/hidrb/hidrb/common/temp/node_modules/.pnpm/@aws-solutions-constructs+core@2.10.0_c0baef088e30cfa8429eec04b3bc7a37/node_modules/@aws-solutions-constructs/core/node_modules/deep-diff/index.js:117:81)
    at deepDiff (/home/runner/work/hidrb/hidrb/common/temp/node_modules/.pnpm/@aws-solutions-constructs+core@2.10.0_c0baef088e30cfa8429eec04b3bc7a37/node_modules/@aws-solutions-constructs/core/node_modules/deep-diff/index.js:193:9)
    at deepDiff (/home/runner/work/hidrb/hidrb/common/temp/node_modules/.pnpm/@aws-solutions-constructs+core@2.10.0_c0baef088e30cfa8429eec04b3bc7a37/node_modules/@aws-solutions-constructs/core/node_modules/deep-diff/index.js:246:13)
```

Other useful information:
- `cdk synth` took 160 seconds and it did work. So, I am not sure if we are hitting this when we are trying to do a diff of cloudformation vs the synthesized stack.
- This is updating an existing stack, not a fresh deploy
- This is our production deployment. Our staging deployments go fine but there are some minor differences in cfn getting generated

### Expected Behavior

Deploy should happen

### Current Behavior

exception is thrown. 
- This error seems to be because we are inserting too many elements into a js Map.
- `cdk synth --debug` works fine
- `cdk synth --debug > output.txt` crashes node with out of memory error

### Reproduction Steps

unfortunately we could not reduce it to a smaller deployment yet.

### CDK CLI Version

2.31.0

### Framework Version

2.31.0

### Node.js Version

v14.17.3

### OS

Mac OS

### Language

Typescript

### Language Version

4.6.4

**Comment by ahmetsevki** [comment]
The error is happening inside `PolicyStatement.toString`. I added that as some extra information for context.

**Comment by ahmetsevki** [comment]
this is an aws-solution-constructs bug
