### ISSUE TITLE
(custom-resources): ResponseURL visible in StepFunctions state

### ISSUE THREAD

**Issue by rix0rrr** [aws/aws-cdk#21224]
### Describe the bug

The `ResponseURL` is visible in the execution state of the StepFunctions state machine, and could be used by an attacker who is able to list the executions to falsify the custom resource result. Security has deemed this a medium priority security issue that needs attention.

------

# Solution

* Write the `ResponseURL` to SSM Parameter Store as a SecretStringValue instead of keeping it in the state.
* Read it from there as well.

Niggly details

* There may be multiple executions at the same time so the exact parameter value should be unique and the reference stored in the state instead.
* Don't forget to clean up the value at the end (but don't fail the deployment if this fails)
* We should limit the permissions of the Lambda execution role, probably to something like `arn:aws:ssm:us-east-2:123456789012:parameter/cdk/custom-resource-provider/${`[`aws:userid`](https://docs.aws.amazon.com/IAM/latest/UserGuide/reference_policies_variables.html#principaltable)`}/*` (though `this.node.addr` instead might be good enough as well)

--------

While we're at it, might as well get rid of passing `ResponseURL` to user handlers based on a feature flag.

### Expected Behavior

See above.

### Current Behavior

See above.

### Reproduction Steps

See above.

### CDK CLI Version

-

### Node.js Version

-

### OS

-

### Language

Typescript, Python, .NET, Java, Go

**Comment by arewa** [comment]
Hi @rix0rrr, I would like to work on this issue, but could you give some examples of execution outputs with `ResponseURL`? I looked through my StepFunctions executions and cannot find ResponseURL nowhere. Maybe I am looking at wrong place. For example this is typical output of one of the steps (I truncated the payload):

```
{
  "ExecutedVersion": "$LATEST",
  "Payload": {
   ...
  },
  "SdkHttpMetadata": {
    "AllHttpHeaders": {
      "X-Amz-Executed-Version": [
        "$LATEST"
      ],
      "x-amzn-Remapped-Content-Length": [
        "0"
      ],
      "Connection": [
        "keep-alive"
      ],
      "x-amzn-RequestId": [
        "d65b9a69-6e74-44c5-afae-fd55785c8815"
      ],
      "Content-Length": [
        "79337"
      ],
      "Date": [
        "Mon, 27 Jun 2022 04:28:59 GMT"
      ],
      "X-Amzn-Trace-Id": [
        "root=1-62b93204-6892d9f421e0569a2d807036;sampled=0"
      ],
      "Content-Type": [
        "application/json"
      ]
    },
    "HttpHeaders": {
      "Connection": "keep-alive",
      "Content-Length": "79337",
      "Content-Type": "application/json",
      "Date": "Mon, 27 Jun 2022 04:28:59 GMT",
      "X-Amz-Executed-Version": "$LATEST",
      "x-amzn-Remapped-Content-Length": "0",
      "x-amzn-RequestId": "d65b9a69-6e74-44c5-afae-fd55785c8815",
      "X-Amzn-Trace-Id": "root=1-62b93204-6892d9f421e0569a2d807036;sampled=0"
    },
    "HttpStatusCode": 200
  },
  "SdkResponseMetadata": {
    "RequestId": "d65b9a69-6e74-44c5-afae-fd55785c8815"
  },
  "StatusCode": 200
}
```

Or probably you mean the following link?

![image](https://user-images.githubusercontent.com/1210461/185736173-4b4700ca-f023-4f12-972e-521727808d34.png)

**Comment by metuuu** [comment]
This issue is still present in aws-cdk-lib 2.266.0 and also leaks into CloudWatch. Our audit found `ResponseURL` in our CloudWatch logs.

`isComplete` logs a redacted copy, then throws the raw event:
```ts
const sanitizedRequest = { ...event, ResponseURL: '...' } as const;
log('isComplete', sanitizedRequest);
...
throw new cfnResponse.Retry(JSON.stringify(event));
```

The runtime writes that message to the provider's log group as an `Invoke Error`, presigned URL and all, once per poll (every 10s until the table is ready). Anyone with CloudWatch read access can see it.

Link to the actual code: https://github.com/aws/aws-cdk/blob/17f69d679724eff41fdbbe6ae29fd8111e7db398/packages/aws-cdk-lib/custom-resources/lib/provider-framework/runtime/framework.ts#L72-L95


We can find find many of the following logs in our CloudWatch logs where the first one is a regular log where ResponseURL is redacted and second one is an error log where ResponseURL is fully visible.

<details>
<summary>Redacted INFO log </summary>

```text
2026-XX-XXTXX:XX:XX.XXXZ	00000000-0000-0000-0000-000000000000	INFO	got event [
  '{\n' +
    '  "RequestType": "Create",\n' +
    '  "ServiceToken": "arn:aws:lambda:xx-xxxxx-1:012345678901:function:amplify-xxxxxxxxxxxxxxx-re-TableManagerCustomProvid-xxxxxxxxxxxxxxx",\n' +
    '  "ResponseURL": "[redacted]",\n' +
    '  "StackId": "arn:aws:cloudformation:xx-xxxxx-1:012345678901:stack/amplify-xxxxxxxxxxxxxxx-xxxxxxxxxxxxxxx-br-amplifyDataFileNestedStackFileNestedStackR-2GCQ0IU1BVXN/00000000-0000-0000-0000-000000000000",\n' +
    '  "RequestId": "00000000-0000-0000-0000-000000000000",\n' +
    '  "LogicalResourceId": "FileTable",\n' +
    '  "ResourceType": "Custom::AmplifyDynamoDBTable",\n' +
    '  "ResourceProperties": {\n' +
    '    "ServiceToken": "arn:aws:lambda:xx-xxxxx-1:012345678901:function:amplify-xxxxxxxxxxxxxxx-re-TableManagerCustomProvid-xxxxxxxxxxxxxxx",\n' +
    '    "globalSecondaryIndexes": [\n' +
    '      .............
    '  },\n' +
    '  "PhysicalResourceId": "File-xxxxxxxxxxxxxxxxxxxx-NONE",\n' +
    '  "Data": {\n' +
    '    "TableArn": "arn:aws:dynamodb:xx-xxxxx-1:012345678901:table/File-xxxxxxxxxxxxxxxxxxxx-NONE",\n' +
    '    "TableStreamArn": "arn:aws:dynamodb:xx-xxxxx-1:012345678901:table/File-xxxxxxxxxxxxxxxxxxxx-NONE/stream/2026-XX-XXTXX:XX:XX.XXX",\n' +
    '    "TableName": "File-xxxxxxxxxxxxxxxxxxxx-NONE"\n' +
    '  }\n' +
    '}'
]
```

</details>

<details>
<summary>ERROR Invoke Error, same event, ResponseURL fully visible</summary>

```text
2026-XX-XXTXX:XX:XX.XXXZ 00000000-0000-0000-0000-000000000000 ERROR Invoke Error
{
  "errorType": "Error",
  "errorMessage": {
    "RequestType": "Create",
    "ServiceToken": "arn:aws:lambda:xx-xxxxx-1:012345678901:function:amplify-xxxxxxxxxxxxxxx-re-TableManagerCustomProvid-xxxxxxxxxxxxxxx",
    "ResponseURL": "https://cloudformation-custom-resource-response-xxxxxxxx.s3.xx-xxxxx-1.amazonaws.com/...........",
    "StackId": "arn:aws:cloudformation:xx-xxxxx-1:012345678901:stack/amplify-xxxxxxxxxxxxxxx-xxxxxxxxxxxxxxx-br-amplifyDataPostNestedStackPostNestedStackR-xxxxxxxxxxx/00000000-0000-0000-0000-000000000000",
    "RequestId": "00000000-0000-0000-0000-000000000000",
    "LogicalResourceId": "PostTable",
    "ResourceType": "Custom::AmplifyDynamoDBTable",
    "ResourceProperties": {
      "ServiceToken": "arn:aws:lambda:xx-xxxxx-1:012345678901:function:amplify-xxxxxxxxxxxxxxx-re-TableManagerCustomProvid-xxxxxxxxxxxxxxx",
      "globalSecondaryIndexes": [
        .........
      ],
      .........
      "replaceTableUponGsiUpdate": "false",
      "allowDestructiveGraphqlSchemaUpdates": "true",
      "deletionProtectionEnabled": "false",
      "tableName": "Post-xxxxxxxxxxxxxxxxxxxx-NONE",
      "sseSpecification": {
        "sseEnabled": false
      }
    },
    "PhysicalResourceId": "Post-xxxxxxxxxxxxxxxxxxxx-NONE",
    "Data": {
      "TableArn": "arn:aws:dynamodb:xx-xxxxx-1:012345678901:table/Post-xxxxxxxxxxxxxxxxxxxx-NONE",
      "TableStreamArn": "arn:aws:dynamodb:xx-xxxxx-1:012345678901:table/Post-xxxxxxxxxxxxxxxxxxxx-NONE/stream/2026-XX-XXTXX:XX:XX.XXX",
      "TableName": "Post-xxxxxxxxxxxxxxxxxxxx-NONE"
    }
  },
  "stack": [
    Error: {
      "RequestType": "Create",
      "ServiceToken": "arn:aws:lambda:xx-xxxxx-1:012345678901:function:amplify-xxxxxxxxxxxxxxx-re-TableManagerCustomProvid-xxxxxxxxxxxxxxx",
      "ResponseURL": "https://cloudformation-custom-resource-response-xxxxxxxx.s3.xx-xxxxx-1.amazonaws.com/arn%3Aaws%3Acloudformation%3Axx-xxxxx-1%3A012345678901%3Astack/amplify-xxxxxxxxxxxxxxx-xxxxxxxxxxxxxxx-br-amplifyDataPostNestedStackPostNestedStackR-xxxxxxxxxxx/00000000-0000-0000-0000-000000000000%7CPostTable%7C00000000-0000-0000-0000-000000000000?X-Amz-Security-Token=......",
      "StackId": "arn:aws:cloudformation:xx-xxxxx-1:012345678901:stack/amplify-xxxxxxxxxxxxxxx-xxxxxxxxxxxxxxx-br-amplifyDataPostNestedStackPostNestedStackR-xxxxxxxxxxx/00000000-0000-0000-0000-000000000000",
      "RequestId": "00000000-0000-0000-0000-000000000000",
      "LogicalResourceId": "PostTable",
      "ResourceType": "Custom::AmplifyDynamoDBTable",
      "ResourceProperties": {
        "ServiceToken": "arn:aws:lambda:xx-xxxxx-1:012345678901:function:amplify-xxxxxxxxxxxxxxx-re-TableManagerCustomProvid-xxxxxxxxxxxxxxx",
        .........
      },
      "PhysicalResourceId": "Post-xxxxxxxxxxxxxxxxxxxx-NONE",
      "Data": {
        "TableArn": "arn:aws:dynamodb:xx-xxxxx-1:012345678901:table/Post-xxxxxxxxxxxxxxxxxxxx-NONE",
        "TableStreamArn": "arn:aws:dynamodb:xx-xxxxx-1:012345678901:table/Post-xxxxxxxxxxxxxxxxxxxx-NONE/stream/2026-XX-XXTXX:XX:XX.XXX",
        "TableName": "Post-xxxxxxxxxxxxxxxxxxxx-NONE"
      }
    },
    "    at isCompleteHandler (/var/task/amplify-table-manager-handler.js:98:15)",
    "    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)",
    "    at async Runtime.handler (/var/task/cfn-response.js:69:13)"
  ]
}
```

</details>

**Comment by vishwakt** [comment]
The SSM approach here has a wrinkle worth settling first: `Provider` supports `vpc`/`vpcSubnets`, and an async provider in isolated subnets currently needs no SSM or KMS reachability. Writing the URL as a `SecureString` would make an SSM VPC endpoint plus KMS access for `alias/aws/ssm` a hard deploy requirement for existing VPC-hosted providers, which is a silent breaking change.

`Type: 'String'` still gets the URL out of the state machine input and out of the rethrown `Retry` error, with access controlled by IAM scoped to the provider's `node.addr` prefix. Is String acceptable, or do you want SecureString behind a feature flag?

Happy to pick this up either way. Planning to keep the user handler payload change (stripping `ResponseURL` from what handlers receive) as a separate flagged PR so this one stays reviewable.
