### ISSUE TITLE
(module name): (short issue description)

### ISSUE THREAD

**Issue by ionscorobogaci** [aws/aws-cdk#21329]
### Describe the bug

Top level awaits cannot be used or fails at runtime always
Top level awaits are supported now in NodeJS lambda, however trying to deploy such a function with cdk contruct NodejsFunction always fails

here is the sample lambda function :

```
import {APIGatewayEvent, Context} from "aws-lambda";

import {SSMClient, GetParameterCommand} from "@aws-sdk/client-ssm";

const readParameterStore = async () => {
    console.log("reading parameter store ")
    const ssmClient = new SSMClient({});
    const input = {"Name": "test-ion"}
    const command = new GetParameterCommand(input);
    return await ssmClient.send(command);
}

const parameterValue = await readParameterStore();

export const handler = async (event: APIGatewayEvent, context: Context) => {

    console.log("parameterValue : ", parameterValue);
    return {
        statusCode: 200,
        body: JSON.stringify({
            message: 'hello world from typescript',
        }),
    };
};
```.   

here is the definition with cdk
 
```
    new NodejsFunction(scope, 'CheckTypescript', {
      functionName: props.stage.concat(HYPHEN).concat('typescript-check'),
      description: 'Sample function written in NodeJs with typescript and deployed using CDK NodejsFunction.',
      handler: 'handler',
      depsLockFilePath: join(__dirname, '../../../services/package-lock.json'),
      entry: join(__dirname, '../../../services/lambda-sample-typescript/index.ts'),
      runtime: Runtime.NODEJS_16_X,
      logRetention: RetentionDays.TWO_WEEKS,
      bundling:{
        format: OutputFormat.ESM,
        target:'es2022',
        tsconfig: join(__dirname, '../../../services/tsconfig.json')
      }
    });
```.  

it fails with the following error always when trying to use top level awaits

```
{
    "errorType": "Error",
    "errorMessage": "Dynamic require of \"crypto\" is not supported",
    "stack": [
        "Error: Dynamic require of \"crypto\" is not supported",
        "    at file:///var/task/index.mjs:7:9",
        "    at asset-input/node_modules/uuid/dist/rng.js (file:///var/task/index.mjs:2082:42)",
        "    at __require2 (file:///var/task/index.mjs:10:50)",
        "    at asset-input/node_modules/uuid/dist/v1.js (file:///var/task/index.mjs:2167:39)",
        "    at __require2 (file:///var/task/index.mjs:10:50)",
        "    at asset-input/node_modules/uuid/dist/index.js (file:///var/task/index.mjs:2550:37)",
        "    at __require2 (file:///var/task/index.mjs:10:50)",
        "    at asset-input/node_modules/@aws-sdk/client-secrets-manager/dist-cjs/protocols/Aws_json1_1.js (file:///var/task/index.mjs:2573:18)",
        "    at __require2 (file:///var/task/index.mjs:10:50)",
        "    at asset-input/node_modules/@aws-sdk/client-secrets-manager/dist-cjs/commands/CancelRotateSecretCommand.js (file:///var/task/index.mjs:4640:25)"
    ]
}
```.  

if the bundling is not specified , the function cannot be even deployed

```
      bundling:{
        format: OutputFormat.ESM,
        target:'es2022',
        tsconfig: join(__dirname, '../../../services/tsconfig.json')
      },
```

### Expected Behavior

The function should execute normally and the output should be .js and not .mjs

### Current Behavior

an .mjs file is generated and the execution always fails with 

```
{
    "errorType": "Error",
    "errorMessage": "Dynamic require of \"crypto\" is not supported",
    "stack": [
        "Error: Dynamic require of \"crypto\" is not supported",
        "    at file:///var/task/index.mjs:7:9",
        "    at asset-input/node_modules/uuid/dist/rng.js (file:///var/task/index.mjs:2082:42)",
        "    at __require2 (file:///var/task/index.mjs:10:50)",
        "    at asset-input/node_modules/uuid/dist/v1.js (file:///var/task/index.mjs:2167:39)",
        "    at __require2 (file:///var/task/index.mjs:10:50)",
        "    at asset-input/node_modules/uuid/dist/index.js (file:///var/task/index.mjs:2550:37)",
        "    at __require2 (file:///var/task/index.mjs:10:50)",
        "    at asset-input/node_modules/@aws-sdk/client-secrets-manager/dist-cjs/protocols/Aws_json1_1.js (file:///var/task/index.mjs:2573:18)",
        "    at __require2 (file:///var/task/index.mjs:10:50)",
        "    at asset-input/node_modules/@aws-sdk/client-secrets-manager/dist-cjs/commands/CancelRotateSecretCommand.js (file:///var/task/index.mjs:4640:25)"
    ]
}
```

### Reproduction Steps

create a function which uses top level await and deploy it using NodejsFunction

### Possible Solution

_No response_

### Additional Information/Context

_No response_

### CDK CLI Version

2.30.0

### Framework Version

_No response_

### Node.js Version

16

### OS

Linux

### Language

Typescript

### Language Version

_No response_

### Other information

_No response_

**Comment by ionscorobogaci** [comment]
if works perfectly when defined as simple Lambda function and not using crappy NodejsFunction

this sample works perfectly 

```
private static sampleTopLevelAwait(scope: Construct, props: ServiceProps): void {
    const sampleFunction = new LambdaFunction(scope, 'SampleTopLevelAwait', {
      functionName: props.stage.concat(HYPHEN).concat('top-level-await'),
      description: 'Check top level await',
      timeout: Duration.seconds(3),
      code: Code.fromAsset(join(__dirname, '../../../services')),
      runtime: Runtime.NODEJS_16_X,
      handler: 'lambda-sample-typescript/index.handler',
      logRetention: RetentionDays.TWO_MONTHS,
    })

    const functionPolicy = new PolicyStatement({
      actions: ['secretsmanager:*','ssm:*'],
      resources: ['*'],
      effect: Effect.ALLOW,
    });

    sampleFunction.addToRolePolicy(functionPolicy);
  }
```

**Comment by VladimirGrenaderov** [comment]
Looks like it's not CDK / SDK, it somewhere between esbuild & uuid: uuid already has esm version in 'dist/node_esm', but per my (and issue author) stack trace we see that 'dist/rng.js' used instead. It's a bit complicated 'exports' field in uuid's package.json:
  "exports": {
    ".": {
      "node": {
        "module": ".**/dist/esm-node/index.js**",
        "require": "./dist/index.js",
        "import": "**./wrapper.mjs**"
      },
      "default": "./dist/esm-browser/index.js"
    },
    "./package.json": "./package.json"
  },

ESBuild shall choose exports->node->module instead of exports->node->import (which is proper way from my understanding).
