### ISSUE TITLE
aws_lambda: AutoScalingGroupDrainECSHookFunction cannot be deployed because python3.6

### ISSUE THREAD

**Issue by sandra-selfdecode** [aws/aws-cdk#21366]
### Describe the bug

When deploying an `EcsCluster` with an `AutoscalingGroup` and `AsgCapacityProvider`, the `AutoScalingGroupDrainECSHookFunction` cannot be deployed because it is `python3.6`. The same stack deployed successfully yesterday, but today I get an error:
```
Resource handler returned message: "The runtime parameter of python3.6 is no longer supported for creating or updating
AWS Lambda functions. We recommend you use the new runtime (python3.9) while creating or updating functions.
```
I tried aws-cdk versions 2.27.0 through 2.33.0

### Expected Behavior

Stack to deploy successfully

### Current Behavior

Stack cannot deploy
```
12:47:51 PM | CREATE_FAILED        | AWS::Lambda::Function                         | ClusterEcsClusterD...okFunction83
69624A
Resource handler returned message: "The runtime parameter of python3.6 is no longer supported for creating or updating
AWS Lambda functions. We recommend you use the new runtime (python3.9) while creating or updating functions. (Service:
Lambda, Status Code: 400, Request ID: 8af04eeb-6dba-40f1-b67e-8be8a7fe9182)" (RequestToken: 88ff62aa-9504-c8c5-fc89-31
cf7f4ee9cc, HandlerErrorCode: InvalidRequest)


 ❌  file-processing-dev failed: Error: The stack named file-processing-dev failed creation, it may need to be manually deleted
from the AWS console: 
ROLLBACK_COMPLETE: Resource handler returned message: "The runtime parameter of python3.6 is
no longer supported for creating or updating AWS Lambda functions. We recommend you use the new runtime (python3.9) 
while creating or updating functions. (Service: Lambda, Status Code: 400, Request ID: 8af04eeb-6dba-40f1-b67e-
8be8a7fe9182)" (RequestToken: 88ff62aa-9504-c8c5-fc89-31cf7f4ee9cc, HandlerErrorCode: InvalidRequest)
    at prepareAndExecuteChangeSet (/usr/lib/node_modules/aws-cdk/lib/api/deploy-stack.ts:385:13)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at CdkToolkit.deploy (/usr/lib/node_modules/aws-cdk/lib/cdk-toolkit.ts:209:24)
    at initCommandLine (/usr/lib/node_modules/aws-cdk/lib/cli.ts:341:12)

The stack named file-processing-dev failed creation, it may need to be manually deleted from the AWS console: 
ROLLBACK_COMPLETE: Resource handler returned message: "The runtime parameter of python3.6 is no longer supported 
for creating or updating AWS Lambda functions. We recommend you use the new runtime (python3.9) while creating or 
updating functions. (Service: Lambda, Status Code: 400, Request ID: 8af04eeb-6dba-40f1-b67e-8be8a7fe9182)" 
(RequestToken: 88ff62aa-9504-c8c5-fc89-31cf7f4ee9cc, HandlerErrorCode: InvalidRequest)
```

### Reproduction Steps

```
        ecs_cluster = ecs.Cluster(
            self,
            "EcsCluster",
            vpc=default_vpc.vpc,
            capacity=ecs.AddCapacityOptions(
                can_containers_access_instance_role=True,
                machine_image=ecs.EcsOptimizedImage.amazon_linux2(),
                instance_type=ec2.InstanceType.of(
                    ec2.InstanceClass.MEMORY5_AMD, ec2.InstanceSize.XLARGE
                ),
                spot_instance_draining=True,
                spot_price="0.226",
                min_capacity=0,
                max_capacity=5,
            ),
        )

        ecs_cluster.autoscaling_group.scale_on_cpu_utilization(
            "AutoScaleCPU", target_utilization_percent=75
        )
        ecs_cluster.autoscaling_group.add_security_group(ecs_container_security_group)

        capacity_provider = ecs.AsgCapacityProvider(
            self,
            "AsgCapacityProvider",
            auto_scaling_group=ecs_cluster.autoscaling_group,
        )

        ecs_cluster.add_asg_capacity_provider(capacity_provider)
```

`cdk deploy`

### CDK CLI Version

2.33.0

### Node.js Version

18.6.0

### OS

ubuntu

### Language

Python

**Comment by jonasv** [comment]
This affects typescript version of cdk as well

**Comment by jonasv** [comment]
This is affecting typescript version of cdk as well

**Comment by jonasv** [comment]
Same problem, any idea when this is going to be fixed?

**Comment by yahor-mikheyenka-wttech** [comment]
Same here. Please check it and write an update. Thx

**Comment by kaizencc** [comment]
I'm curious, can you double check in package.json your `aws-cdk-lib` version?

To be clear, we moved all of our custom resources to python3.9 in this [commit](https://github.com/aws/aws-cdk/pull/19988), including this custom resource. It was [released](https://github.com/aws/aws-cdk/releases/tag/v2.28.0) in CDK v2.28.

I ran this on `aws-cdk-lib` v2.33 and it succeeded.

**Comment by sandra-selfdecode** [comment]
That's the problem, our devops team froze aws-cdk-lib at an earlier version. Thank you, I'll upgrade it
