### ISSUE TITLE
(elasticache): NameError: CloudWatchLogsDestinationDetailsProperty is not defined

### ISSUE THREAD

**Issue by zessx** [aws/aws-cdk#21378]
### Describe the bug

After upgrading from `2.33.0` to `2.34.0`, I've got the following error, without any other change:
> NameError: name 'CloudWatchLogsDestinationDetailsProperty' is not defined

### Expected Behavior

I do not expect any error, as the CHANGELOG does not mention any change on the `elasticache` module.

### Current Behavior

```sh
$ cdk diff
Deploying [staging] environment with CDK.
Traceback (most recent call last):
  File "/…/cdk/app.py", line 345, in <module>
    stack = WakeoBackStack(app, "WakeoBack-" + ENV,
  File "/…/.venv/lib/python3.9/site-packages/jsii/_runtime.py", line 86, in __call__
    inst = super().__call__(*args, **kwargs)
  File "/…/cdk/app.py", line 150, in __init__
    redis = Redis(self,
  File "/…/cdk/services/redis.py", line 70, in __init__
    cloud_watch_logs_details = elasticache.CfnCacheCluster.CloudWatchLogsDestinationDetailsProperty(
  File "/…/.venv/lib/python3.9/site-packages/aws_cdk/aws_elasticache/__init__.py", line 828, in __init__
    type_hints = typing.get_type_hints(CloudWatchLogsDestinationDetailsProperty.__init__)
NameError: name 'CloudWatchLogsDestinationDetailsProperty' is not defined
```

The related code:
```py

#
# Redis cluster
#
self.cluster = elasticache.CfnCacheCluster(stack, "RedisCluster",
    cluster_name = stack.prefix_pascal("RedisCluster"),
    engine = "redis",
    cache_node_type = os.getenv("CDK_REDIS_CLUSTER_CACHE_NODE_TYPE", "cache.t2.small"),
    num_cache_nodes = int(os.getenv("CDK_REDIS_CLUSTER_NUM_CACHE_NODES", 1)),
    vpc_security_group_ids = [self.security_group.security_group_id],
    cache_subnet_group_name = self.subnet_group.cache_subnet_group_name,
    log_delivery_configurations = [elasticache.CfnCacheCluster.LogDeliveryConfigurationRequestProperty(
        destination_details = elasticache.CfnCacheCluster.DestinationDetailsProperty(
            cloud_watch_logs_details = elasticache.CfnCacheCluster.CloudWatchLogsDestinationDetailsProperty(
                log_group = self.log_group.log_group_name)),
        destination_type = "cloudwatch-logs",
        log_format = "json",
        log_type = "slow-log")] if enable_logs else None)
self.cluster.add_depends_on(self.subnet_group)
```

### Reproduction Steps

Simply run `cdk diff` after upgrading CDK.

### CDK CLI Version

2.34.0 (build 633edab)

### Node.js Version

v14.17.6

### OS

macOS 12.3 (21E230)

### Language

Python

### Language Version

Python 3.9.13

**Comment by zessx** [comment]
Resolved by upgrading to `2.34.2`
