### ISSUE TITLE
(aws_route53): (upgrade to 2.34.0 throws: name 'RecordSetProperty' is not defined)

### ISSUE THREAD

**Issue by dborysenko** [aws/aws-cdk#21384]
### Describe the bug

Getting "NameError: name 'RecordSetProperty' is not defined" error after upgrading aws-cdk-lib python package to 2.34.0

### Expected Behavior

Behavior should not change with CDK minor upgrade.

### Current Behavior

CDK errors out.

### Reproduction Steps

1. Install CDK version 2.33.0
2. Create simple Stack:
```python
from aws_cdk import (Stack, aws_route53 as r53)
from constructs import Construct


class R53Test(Stack):

  def __init__(self, scope: Construct, construct_id: str, **kwargs) -> None:
    super().__init__(scope, construct_id, **kwargs)

    r53.CfnRecordSetGroup.RecordSetProperty(name="whatever",
                                            type="A",
                                            resource_records=["192.168.0.1"],
                                            ttl="0",
                                            set_identifier="123",
                                            weight=0)

```
3. Run cdk synth:
```shell
Resources:
  CDKMetadata:
    Type: AWS::CDK::Metadata
    Properties:
      Analytics: v2:deflate64:H4sIAAAAAAAA/zPSMzbWM1BMLC/WTU7J1s3JTNKrDi5JTM7WcU7LC0otzi8tSk6t1QmoLMnIz9M31rPUMzRSzCrOzNQtKs0rycxN1QuC0ABKeDtJSQAAAA==
    Metadata:
      aws:cdk:path: R53Test/CDKMetadata/Default
Parameters:
  BootstrapVersion:
    Type: AWS::SSM::Parameter::Value<String>
    Default: /cdk-bootstrap/hnb659fds/version
    Description: Version of the CDK Bootstrap resources in this environment, automatically retrieved from SSM Parameter Store. [cdk:skip]
Rules:
  CheckBootstrapVersion:
    Assertions:
      - Assert:
          Fn::Not:
            - Fn::Contains:
                - - "1"
                  - "2"
                  - "3"
                  - "4"
                  - "5"
                - Ref: BootstrapVersion
        AssertDescription: CDK bootstrap stack version 6 required. Please run 'cdk bootstrap' with a recent version of the CDK CLI.
```
4. Upgrade cdk to 2.34.0
5. Run cdk synth
```shell
Traceback (most recent call last):
  File "/Users/dborysenko/git/cdk-c0p2-uswest2/app.py", line 17, in <module>
    R53Test(app, "R53Test", env=c0p2_env)
  File "/Users/dborysenko/git/cdk-c0p2-uswest2/.venv/lib/python3.9/site-packages/jsii/_runtime.py", line 86, in __call__
    inst = super().__call__(*args, **kwargs)
  File "/Users/dborysenko/git/cdk-c0p2-uswest2/cdk_c0p2_uswest2/test.py", line 10, in __init__
    r53.CfnRecordSetGroup.RecordSetProperty(name="whatever",
  File "/Users/dborysenko/git/cdk-c0p2-uswest2/.venv/lib/python3.9/site-packages/aws_cdk/aws_route53/__init__.py", line 4454, in __init__
    type_hints = typing.get_type_hints(RecordSetProperty.__init__)
NameError: name 'RecordSetProperty' is not defined

Subprocess exited with error 1
```

### Possible Solution

Downgrade to 2.33.0

### CDK CLI Version

2.34.0 (build 633edab)

### Node.js Version

v16.15.0

### OS

MacOS

### Language

Python

### Language Version

Python 3.9.12

**Comment by dborysenko** [comment]
Works fine with cdk 2.34.1 version.
Closing now.
