### ISSUE TITLE
(vscode devcontainer): postcommand fails 

### ISSUE THREAD

**Issue by Xcalizorz** [aws/aws-cdk#21399]
### Describe the bug

I'm trying to use the provided vscode devcontainer but fail at the `postCreateCommand`:

```log
Running the postCreateCommand from devcontainer.json...

[4464 ms] Start: Run in container: /bin/sh -c yarn build --skip-test --no-bail --skip-prereqs --skip-compat
yarn run v1.22.19
$ node ./scripts/check-yarn-lock.js
internal/modules/cjs/loader.js:905
  throw err;
  ^

Error: Cannot find module '@lerna/project'
Require stack:
- /workspaces/aws-cdk/scripts/check-yarn-lock.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:902:15)
    at Function.Module._load (internal/modules/cjs/loader.js:746:27)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at require (internal/modules/cjs/helpers.js:101:18)
    at Object.<anonymous> (/workspaces/aws-cdk/scripts/check-yarn-lock.js:17:21)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:12)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:75:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [ '/workspaces/aws-cdk/scripts/check-yarn-lock.js' ]
}
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

### Expected Behavior

The command should not fail & all modules should already be installed.

### Current Behavior

The command fails because some modules are missing, `'@lerna/project'` 

### Reproduction Steps

Clone the repo & try to open the dev container using VSCode.

### Possible Solution

Change the `postCreateCommand` to install the yarn modules before it uses `yarn build`

```json
  "postCreateCommand": "yarn install && yarn build --skip-test --no-bail --skip-prereqs --skip-compat"
```

But do you actually want to `build` after the dev. container is created? The build takes some time & I would assume just installing the needed modules via `yarn install` is enough to start developing.

### CDK CLI Version

@main

### Node.js Version

v14.20.0

### OS

Windows WSL

### Language

Typescript, Python, .NET, Java, Go

### Other information

VSCode: 1.70.0-insider

**Comment by mrgrain** [comment]
The current `.devcontainer.json` file has been created to support GitHub Codespaces, not local development. See https://github.com/aws/aws-cdk/pull/10470

This isn't clear at all, but can you confirm if you are running this locally or on Codespaces?

**Comment by Xcalizorz** [comment]
> The current `.devcontainer.json` file has been created to support GitHub Codespaces, not local development. See #10470
> 
> This isn't clear at all, but can you confirm if you are running this locally or on Codespaces?

I am working locally, so the issue can be closed. Thanks for investigating @mrgrain
