### ISSUE TITLE
aws_codepipeline Artifact get_param: Unsupported Function

### ISSUE THREAD

**Issue by brett-bim** [aws/aws-cdk#21465]
### Describe the bug

I have an Artifact that is the output of an EcrSourceAction.  I would like to use information that exists in the `imageDetail.json` in a subsequent ManualApprovalStep for the additionalInfo property.  However, when I run `cdk deploy`, it throws and error.

This works fine when I use the `get_metadata(key)` method of this Artifact.  The documentation seems to imply that `get_param` is a first class citizen on Artifact so I'm confused why this isn't working.

### Expected Behavior

I would expect that I could pull data out of the json files that live in my Artifact.  

### Current Behavior

Error:

```
`Pipeline failed: Error [ValidationError]: Template Error: Encountered unsupported function: Fn::GetParam Supported functions are: [Fn::Base64, Fn::GetAtt, Fn::GetAZs, Fn::ImportValue, Fn::Join, Fn::Split, Fn::FindInMap, Fn::Select, Ref, Fn::Equals, Fn::If, Fn::Not, Condition, Fn::And, Fn::Or, Fn::Contains, Fn::EachMemberEquals, Fn::EachMemberIn, Fn::ValueOf, Fn::ValueOfAll, Fn::RefAll, Fn::Sub, Fn::Cidr]
    at Request.extractError (/Users/brettbim/.volta/tools/image/packages/aws-cdk/lib/node_modules/aws-sdk/lib/protocol/query.js:50:29)
    at Request.callListeners (/Users/brettbim/.volta/tools/image/packages/aws-cdk/lib/node_modules/aws-sdk/lib/sequential_executor.js:106:20)
    at Request.emit (/Users/brettbim/.volta/tools/image/packages/aws-cdk/lib/node_modules/aws-sdk/lib/sequential_executor.js:78:10)
    at Request.emit (/Users/brettbim/.volta/tools/image/packages/aws-cdk/lib/node_modules/aws-sdk/lib/request.js:686:14)
    at Request.transition (/Users/brettbim/.volta/tools/image/packages/aws-cdk/lib/node_modules/aws-sdk/lib/request.js:22:10)
    at AcceptorStateMachine.runTo (/Users/brettbim/.volta/tools/image/packages/aws-cdk/lib/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at /Users/brettbim/.volta/tools/image/packages/aws-cdk/lib/node_modules/aws-sdk/lib/state_machine.js:26:10
    at Request.<anonymous> (/Users/brettbim/.volta/tools/image/packages/aws-cdk/lib/node_modules/aws-sdk/lib/request.js:38:9)
    at Request.<anonymous> (/Users/brettbim/.volta/tools/image/packages/aws-cdk/lib/node_modules/aws-sdk/lib/request.js:688:12)
    at Request.callListeners (/Users/brettbim/.volta/tools/image/packages/aws-cdk/lib/node_modules/aws-sdk/lib/sequential_executor.js:116:18) {
  code: 'ValidationError',
  time: 2022-08-04T16:30:08.000Z,
  requestId: 'f717a110-6c5a-455e-bc75-6c639658a885',
  statusCode: 400,
  retryable: false,
  retryDelay: 804.9145064582723
}
```

### Reproduction Steps

```
        pipeline = codepipeline.Pipeline(
            self, "MyPipeline_Pipeline", cross_account_keys=False
        )
        source_output = codepipeline.Artifact("Image")

        source_action = codepipeline_actions.EcrSourceAction(
            action_name="ECR",
            repository=ecr_repository,
            image_tag="latest",  # optional, default: 'latest'
            output=source_output,
        )
        pipeline.add_stage(
            stage_name="DeployDev",
            actions=[
                codepipeline_actions.ManualApprovalAction(
                    action_name="ApproveDeployToDev",
                    additional_information=source_output.get_param(
                        "imageDetail.json", "ImageTags"
                    ),
                    # Note this works: additional_information=source_output.get_metadata("somekey"),
                ),
                codepipeline_actions.EcsDeployAction(
                    #other actions elided
                ),
            ],
        )
```

### Possible Solution

If there is a workaround, I'm happy to use it but haven't been able to think of ways to do this.  

### CDK CLI Version

2.23.0 (build 50444aa)

### Node.js Version

v16.13.1

### OS

Mac Big Sur

### Language

Python

**Comment by peterwoodworth** [comment]
Looks to be the same as [this issue](https://github.com/aws/aws-cdk/issues/15638), could you take a look through this and get back to me if you have any further questions/concerns?
