### ISSUE TITLE
Error: We don't support attributes of the 'AWS::ElastiCache::ReplicationGroup' resource. 

### ISSUE THREAD

**Issue by ecunal** [aws/aws-cdk#21479]
### Describe the bug

Hey team,

After upgrading to CDK v2, we started getting errors like the following while doing cdk deploy. Since the error message asks for a report, creating a bug report about it:

```
(node:83721) UnhandledPromiseRejectionWarning: Error: We don't support attributes of the 'AWS::ElastiCache::ReplicationGroup' resource. This is a CDK limitation. Please report it at https://github.com/aws/aws-cdk/issues/new/choose
    at EvaluateCloudFormationTemplate.formatResourceAttribute (.../node_modules/aws-cdk/lib/api/evaluate-cloudformation-template.ts:294:13)
    at EvaluateCloudFormationTemplate.findGetAttTarget (.../node_modules/aws-cdk/lib/api/evaluate-cloudformation-template.ts:281:17)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at CfnIntrinsics.Fn::GetAtt (.../node_modules/aws-cdk/lib/api/evaluate-cloudformation-template.ts:174:27)
    at EvaluateCloudFormationTemplate.evaluateCfnExpression (.../node_modules/aws-cdk/lib/api/evaluate-cloudformation-template.ts:215:22)
    at async Promise.all (index 1)
    at EvaluateCloudFormationTemplate.evaluateCfnExpression (.../node_modules/aws-cdk/lib/api/evaluate-cloudformation-template.ts:215:22)
    at async Promise.all (index 0)
    at EvaluateCloudFormationTemplate.evaluateCfnExpression (.../node_modules/aws-cdk/lib/api/evaluate-cloudformation-template.ts:215:22)
    at isHotswappableEcsServiceChange (.../node_modules/aws-cdk/lib/api/hotswap/ecs-services.ts:65:8)
```

### Expected Behavior

No errors, expected support for attributes of the 'AWS::ElastiCache::ReplicationGroup' resource. 

### Current Behavior

```
(node:83721) UnhandledPromiseRejectionWarning: Error: We don't support attributes of the 'AWS::ElastiCache::ReplicationGroup' resource. This is a CDK limitation. Please report it at https://github.com/aws/aws-cdk/issues/new/choose
    at EvaluateCloudFormationTemplate.formatResourceAttribute (.../node_modules/aws-cdk/lib/api/evaluate-cloudformation-template.ts:294:13)
    at EvaluateCloudFormationTemplate.findGetAttTarget (.../node_modules/aws-cdk/lib/api/evaluate-cloudformation-template.ts:281:17)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at CfnIntrinsics.Fn::GetAtt (.../node_modules/aws-cdk/lib/api/evaluate-cloudformation-template.ts:174:27)
    at EvaluateCloudFormationTemplate.evaluateCfnExpression (.../node_modules/aws-cdk/lib/api/evaluate-cloudformation-template.ts:215:22)
    at async Promise.all (index 1)
    at EvaluateCloudFormationTemplate.evaluateCfnExpression (.../node_modules/aws-cdk/lib/api/evaluate-cloudformation-template.ts:215:22)
    at async Promise.all (index 0)
    at EvaluateCloudFormationTemplate.evaluateCfnExpression (.../node_modules/aws-cdk/lib/api/evaluate-cloudformation-template.ts:215:22)
    at isHotswappableEcsServiceChange (.../node_modules/aws-cdk/lib/api/hotswap/ecs-services.ts:65:8)
```

### Reproduction Steps

We create a Redis replication group with the following code (subnet group and security group creations are omitted, nothing interesting there):

```typescript
        const parameterGroup = new CfnParameterGroup(this, 'RedisParameterGroup', {
            description: 'Redis specific parameters',
            cacheParameterGroupFamily: 'redis6.x',
            properties: {
                'maxmemory-policy': 'allkeys-lru',
            },
        });

        const replicationGroup = new CfnReplicationGroup(this, 'RedisReplicationGroup', {
            engine: 'redis',
            replicationGroupDescription: 'Main Redis replication group',
            cacheNodeType: 'cache.r5.large',
            port,
            numCacheClusters: props.numCacheNodes,
            automaticFailoverEnabled: props.numCacheNodes > 1,
            cacheSubnetGroupName: subnetGroup.cacheSubnetGroupName,
            securityGroupIds: [securityGroup.securityGroupId],
            preferredMaintenanceWindow: 'sun:23:00-mon:01:30',
            cacheParameterGroupName: parameterGroup.ref,
        });
```

### CDK CLI Version

2.34.1

### Node.js Version

14.20

### OS

MacOS

### Language

Typescript

### Language Version

TypeScript 4.0.8

**Comment by peterwoodworth** [comment]
I'm not able to reproduce this with the snippet you've given me, are you referencing the `replicationGroup` anywhere else?
