### ISSUE TITLE
applicationautoscaling: StepScalingPolicy Unable to resolve object tree with circular reference

### ISSUE THREAD

**Issue by Prisma-Ralf-T** [aws/aws-cdk#21475]
### Describe the bug

Hello,
I want to use ApplicationAutoscaling StepScaling with a Fargate Service.
I understood, that in order to do so I need:
1. a metric
2. a ScalableTarget
3. a StepScalingPolicy (or alternatively use ScalableTarget.scaleOnMetric())

I am using CDK 2.35 in a TypeScript project(1) with CDK V1 packages:

```
# From package.json
...
  "dependencies": {
    "@aws-cdk/aws-certificatemanager": "1.167.0",
    "@aws-cdk/aws-cloudwatch": "1.167.0",
    "@aws-cdk/aws-cloudwatch-actions": "1.167.0",
    "@aws-cdk/aws-ec2": "1.167.0",
    "@aws-cdk/aws-ecs": "1.167.0",
    "@aws-cdk/aws-ecs-patterns": "1.167.0",
    "@aws-cdk/aws-s3": "1.167.0",
    "@aws-cdk/aws-servicediscovery": "1.167.0",
    "@aws-cdk/aws-applicationautoscaling": "1.167.0",
    "@aws-cdk/aws-sns": "1.167.0",
    "@aws-cdk/core": "1.167.0",
    "source-map-support": "0.5.21",
    "yarn": "^1.22.19"
  }
```

Adding the following resources to my code, I can cdk synth, cdk diff and cdk deploy successfully:

```
    const memoryMetric = new Metric({
      metricName: 'MemoryUtilization',
      namespace: 'AWS/ECS',
      statistic: 'Average',
      period: Duration.minutes(1),
      dimensions: {
        ClusterName: writeService.cluster,
        ServiceName: writeService.serviceName,
      },
    });
  
    const scalTarget = new ScalableTarget(this, 'WriteSideScalableTarget', {
      serviceNamespace: ServiceNamespace.ECS,
      maxCapacity: 10,
      minCapacity: 1,
      resourceId: `service/${cluster.clusterName}/${writeService.serviceName}`,
      scalableDimension: 'ecs:service:DesiredCount',
    });
```

As soon as I now try to add a StepScalingPolicy cdk synth and cdk diff start to fail.
The code is:

```
    const stepScalingPolicy = new StepScalingPolicy(this, 'backend-mem-util-scalingScalingPolicy', {
      metric: memoryMetric,
      scalingSteps: [
        { upper: 30, change: -1 },
        { lower: 50, change: +2 },
        { lower: 70, change: +2 },
      ],
      scalingTarget: scalTarget,
    
      // the properties below are optional
      adjustmentType: AdjustmentType.CHANGE_IN_CAPACITY,
      cooldown: cdk.Duration.minutes(30),
      datapointsToAlarm: 2,
      evaluationPeriods: 2,
      metricAggregationType: MetricAggregationType.AVERAGE
    });
```

or

```
    scalTarget.scaleOnMetric('backend-mem-util-scaling', {
      metric: memoryMetric,
      scalingSteps: [
        { upper: 30, change: -1 },
        { lower: 50, change: +2 },
        { lower: 70, change: +2 },
      ],
    
      // Change this to AdjustmentType.PercentChangeInCapacity to interpret the
      // 'change' numbers before as percentages instead of capacity counts.
      adjustmentType: AdjustmentType.CHANGE_IN_CAPACITY,
    });
```

### Expected Behavior

I would expect that synth and diff can be run successful. 

### Current Behavior

The error I am running into is the same for both:

$ yarn cdk synth -a "npx ts-node bin/loki_testing.ts" -c "TAG=89a4915d"
```
yarn run v1.22.19
warning package.json: No license field
...
/home/xxx/Documents/loki/node_modules/@aws-cdk/core/lib/private/resolve.ts:128
    throw new Error('Unable to resolve object tree with circular reference. Path: ' + pathName);
          ^
Error: Resolution error: Resolution error: Unable to resolve object tree with circular reference. Path: /Resources/${Token[loki.backend-mem-util-scalingScalingPolicy.LowerAlarm.Resource.LogicalID.474]}/Properties/dimensions/0/value/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node..
    at resolve (/home/xxx/Documents/loki/node_modules/@aws-cdk/core/lib/private/resolve.ts:128:11)
    at Object.resolve (/home/xxx/Documents/loki/node_modules/@aws-cdk/core/lib/private/resolve.ts:120:77)
    at resolve (/home/xxx/Documents/loki/node_modules/@aws-cdk/core/lib/private/resolve.ts:231:47)
    at Object.resolve (/home/xxx/Documents/loki/node_modules/@aws-cdk/core/lib/private/resolve.ts:120:77)
    at resolve (/home/xxx/Documents/loki/node_modules/@aws-cdk/core/lib/private/resolve.ts:231:47)
    at Object.resolve (/home/xxx/Documents/loki/node_modules/@aws-cdk/core/lib/private/resolve.ts:120:77)
    at resolve (/home/xxx/Documents/loki/node_modules/@aws-cdk/core/lib/private/resolve.ts:231:47)
    at Object.resolve (/home/xxx/Documents/loki/node_modules/@aws-cdk/core/lib/private/resolve.ts:120:77)
    at resolve (/home/xxx/Documents/loki/node_modules/@aws-cdk/core/lib/private/resolve.ts:231:47)
    at Object.resolve (/home/xxx/Documents/loki/node_modules/@aws-cdk/core/lib/private/resolve.ts:120:77)

NOTICES

19836	AWS CDK v1 has entered maintenance mode
...
Subprocess exited with error 1

```
I don't understand why a circular reference issue arises. So I am not 100% sure if I am just interpreting the documentation wrong or if  @aws-cdk/aws-applicationautoscaling.StepScalingPolicy (and ScalableTarget.scaleOnMetric() ) are actually buggy?

### Reproduction Steps

* import { ScalableTarget, ServiceNamespace, StepScalingPolicy, AdjustmentType, MetricAggregationType } from '@aws-cdk/aws-applicationautoscaling';
* use code snippets from above

### CDK CLI Version

CDK 2.35

### Node.js Version

v18.7.0

### OS

Ubuntu 20.04

### Language

Typescript

### Language Version

typescript@4.6.2, ts-node@10.9.1

**Comment by Prisma-Ralf-T** [comment]
I found the problem myself. It is not a bug.
The problem was within using "dimension" (which is deprecated) and giving it an object "writeService.cluster" of type ICluster as "ClusterName"(1).
Replacing the deprecated dimensions property with a dimensionsMap showed me the wrong type and now everything is working(2).

The only thing left I'd like to complain is that:
- https://docs.aws.amazon.com/cdk/api/v1/docs/@aws-cdk_aws-cloudwatch.Metric.html does not mention "dimensionsMap?" as available property (docu version when writing: [1.167.0])  whilst
- its already in https://docs.aws.amazon.com/cdk/api/v1/docs/@aws-cdk_aws-cloudwatch.CommonMetricOptions.html

(1)
`    const memoryMetric = new Metric({
      metricName: 'MemoryUtilization',
      namespace: 'AWS/ECS',
      statistic: 'Average',
      period: Duration.minutes(1),
      dimensions: {
        ClusterName: writeService.cluster,
        ServiceName: writeService.serviceName,
      },
    });`

(2)
`    const memoryMetric = new Metric({
      metricName: 'MemoryUtilization',
      namespace: 'AWS/ECS',
      statistic: 'Average',
      period: Duration.minutes(1),
      dimensionsMap: {
        ClusterName: cluster.clusterName,
        ServiceName: writeService.serviceName,
      },
    });`
