### ISSUE TITLE
(Lambda Python): pipenv support broken

### ISSUE THREAD

**Issue by CorentinDoue** [aws/aws-cdk#21607]
### Describe the bug

Building a python lambda which use pipenv to handle its dependencies fails 

### Expected Behavior

It's creates and deploy the lambda with its correct dependencies

### Current Behavior

During the build of the lambda in docker, the step which creates the `requirements.txt` from the `Pipfile` fails.

**The command `pipenv lock -r > requirements.txt` fails because it no more exists since [pipenv v2022.8.13](https://github.com/pypa/pipenv/releases/tag/v2022.8.13)**

```
Sending build context to Docker daemon  47.62kB                                                                                                                                                                    
Step 1/11 : ARG IMAGE=amazon/aws-sam-cli-build-image-python3.7                                                                                                                                                     
Step 2/11 : FROM $IMAGE                                                                                                                                                                                            
 ---> 99b28f6360b6                                                                                                                                                                                                 
Step 3/11 : RUN yum -q list installed rsync &>/dev/null || yum install -y rsync                                                                                                                                    
 ---> Using cache                                                                                                                                                                                                  
 ---> 979f9f9c66bf                                                                                                                                                                                                 
Step 4/11 : RUN pip install --upgrade pip                                                                                                                                                                          
 ---> Using cache                                                                                                                                                                                                  
 ---> 2dc2d8e2bfb7                                                                                                                                                                                                 
Step 5/11 : RUN pip install pipenv poetry                                                                                                                                                                          
 ---> Using cache                                                                                                                                                                                                  
 ---> b5c72af635cd                                                                                                                                                                                                 
Step 6/11 : WORKDIR /var/dependencies                                                                                                                                                                              
 ---> Using cache
 ---> b30e662c1605
Step 7/11 : COPY Pipfile* pyproject* poetry* requirements.tx[t] ./
 ---> Using cache
 ---> 2032949736b3
Step 8/11 : RUN if [ -f 'Pipfile' ]; then pipenv lock -r > requirements.txt; else echo "Pipfile not found"; fi
 ---> Running in bdfc2eee57cb
Usage: pipenv lock [OPTIONS]
Try 'pipenv lock -h' for help.

Error: No such option: -r
The command '/bin/sh -c if [ -f 'Pipfile' ]; then pipenv lock -r > requirements.txt; else echo "Pipfile not found"; fi' returned a non-zero code: 2

Error: docker exited with status 2
    at dockerExec (/home/cdoue/www-dev/projects/crypto_bot_2/node_modules/aws-cdk-lib/core/lib/bundling.js:4:45)
    at Function.fromBuild (/home/cdoue/www-dev/projects/crypto_bot_2/node_modules/aws-cdk-lib/core/lib/bundling.js:1:3442)
    at bundle (file:///home/cdoue/www-dev/projects/crypto_bot_2/node_modules/@serverless-stack/core/dist/runtime/handler/pythonBundling.js:43:35)
    at Object.bundle (file:///home/cdoue/www-dev/projects/crypto_bot_2/node_modules/@serverless-stack/core/dist/runtime/handler/python.js:33:27)
    at Module.bundle (file:///home/cdoue/www-dev/projects/crypto_bot_2/node_modules/@serverless-stack/core/dist/runtime/handler/index.js:17:16)
    at new Function (file:///home/cdoue/www-dev/projects/crypto_bot_2/node_modules/@serverless-stack/resources/dist/Function.js:223:45)
    at Function.fromDefinition (file:///home/cdoue/www-dev/projects/crypto_bot_2/node_modules/@serverless-stack/resources/dist/Function.js:468:20)
    at Strategy.createRuleTarget (file:///home/cdoue/www-dev/projects/crypto_bot_2/node_modules/@serverless-stack/resources/dist/Cron.js:81:25)
    at new Cron (file:///home/cdoue/www-dev/projects/crypto_bot_2/node_modules/@serverless-stack/resources/dist/Cron.js:29:33)
    at new Strategy (file:///home/cdoue/www-dev/projects/crypto_bot_2/.build/lib/index.js:71:5)
    at EmptyStack.MainStack (file:///home/cdoue/www-dev/projects/crypto_bot_2/.build/lib/index.js:318:3)
    at stack (file:///home/cdoue/www-dev/projects/crypto_bot_2/node_modules/@serverless-stack/resources/dist/FunctionalStack.js:15:35)
    at App.stack (file:///home/cdoue/www-dev/projects/crypto_bot_2/node_modules/@serverless-stack/resources/dist/App.js:272:16)
    at Module.main (file:///home/cdoue/www-dev/projects/crypto_bot_2/.build/lib/index.js:344:7)
    at file:///home/cdoue/www-dev/projects/crypto_bot_2/.build/run.mjs:92:16
```

### Reproduction Steps

1. Create a lambda with a python runtime
2. Use pipenv to handle the dependencies of your lambda code => you have a `Pipfile` in the folder of your handler code
3. Try to deploy

### Possible Solution

According to the [pipenv doc](https://pipenv.pypa.io/en/latest/advanced/#generating-a-requirements-txt), replace `pipenv lock -r > requirements.txt` by `pipenv requirements > requirements.txt`

### CDK CLI Version

2.32.0

### Node.js Version

14

### OS

Ubuntu

### Language

Typescript

### Language Version

TypeScript (4.7.4)

**Comment by jly36963** [comment]
I think this is a breaking change in `pipenv`.

See their [changelog](https://github.com/pypa/pipenv/blob/main/CHANGELOG.rst#removals-and-deprecations), specifically the `lock -r` part

**Comment by corymhall** [comment]
@CorentinDoue are you customizing the build image at all? We are specifically installing pipenv=2022.4.8

https://github.com/aws/aws-cdk/blob/cf3bb6e9ced5e3d18e782e7144858078c70cdcf9/packages/%40aws-cdk/aws-lambda-python/lib/Dockerfile#L14

If this is not working as intended then we need to figure out why.

**Comment by ssay-work** [comment]
Seeing this issue as well.

**Comment by corymhall** [comment]
@CorentinDoue @ssay-work what version of the CDK _framework_ are you using. In a python project this will be the version of `aws-cdk-lib` listed in your `requirements.txt`. From the logs you provided it looks like you are using a pretty old version.

**Comment by ssay-work** [comment]
hmm, we have a `setup.py` configured. Here is the contents of the packages installed there, no explicit callout for aws-cdk-lib, but everything else is 1.148.0

```
        "aws-cdk.core==1.148.0",
        "aws-cdk.aws_rds==1.148.0",
        "aws-cdk.aws_ec2==1.148.0",
        "aws-cdk.aws_elasticloadbalancingv2==1.148.0",
        "aws-cdk.aws_iam==1.148.0",
        "aws-cdk.aws_lambda==1.148.0",
        "aws-cdk.aws_lambda_python==1.148.0",
        "aws-cdk.aws_s3==1.148.0",
        "aws-cdk.aws_events==1.148.0",
        "aws-cdk.aws_events_targets==1.148.0",
        "aws-cdk.aws_route53==1.148.0",
        "aws_cdk.aws_lambda_event_sources==1.148.0",
        "aws_cdk.aws_ses==1.148.0",
        "aws_cdk.aws_ses_actions==1.148.0",
        "aws_cdk.aws_cloudwatch==1.148.0",
```

Would this explain the mismatch in the github workflow and my local env?

**Comment by CorentinDoue** [comment]
@corymhall after a little more digging the problem comes from SST framework: https://github.com/serverless-stack/sst/issues/1954 which uses its own dockerfiles.

Sorry for the inconvenience
