### ISSUE TITLE
aws-cdk: Cannot read property 'ordered' of undefined

### ISSUE THREAD

**Issue by s1mrankaur** [aws/aws-cdk#21724]
### Describe the bug

All CDK commands including bootstrap, synth, deploy return 

```

npx: installed 17 in 14.897s
Cannot read property 'ordered' of undefined
Subprocess exited with error 1
Error: Subprocess exited with error 1
    at ChildProcess.<anonymous> (C:\ProgramData\nvm\v14.18.3\node_modules\cdk\node_modules\aws-cdk\lib\api\cxapp\exec.ts:127:23)
    at ChildProcess.emit (events.js:400:28)
    at ChildProcess.emit (domain.js:475:12)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:282:12)
```

### Expected Behavior

The commands should execute without errors. Have tried different versions of CDK. 

### Current Behavior

Returns the following error

```
npx: installed 17 in 14.897s
Cannot read property 'ordered' of undefined
Subprocess exited with error 1
Error: Subprocess exited with error 1
    at ChildProcess.<anonymous> (C:\ProgramData\nvm\v14.18.3\node_modules\cdk\node_modules\aws-cdk\lib\api\cxapp\exec.ts:127:23)
    at ChildProcess.emit (events.js:400:28)
    at ChildProcess.emit (domain.js:475:12)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:282:12)
```

### Reproduction Steps

Run 
`
 cdk bootstrap --profile sandbox --verbose`

### CDK CLI Version

2.36.1

### Node.js Version

14.18.3

### OS

Windows

### Language

Typescript

**Comment by peterwoodworth** [comment]
Does this issue reproduce on all CDK apps? Have you tried uninstalling your CDK CLI and reinstalling it?

**Comment by s1mrankaur** [comment]
This was an application issue. Wish CDK offered better logging.  Tried --verbose as well and that didn't give much idea either
