### ISSUE TITLE
(aws-autoscaling): jsii.errors.JSIIError: this.role.addToPrincipalPolicy is not a function

### ISSUE THREAD

**Issue by greg5123334** [aws/aws-cdk#21750]
### Describe the bug

When attempting to provision (or even synth the template of) an [AutoScalingGroup](https://docs.aws.amazon.com/cdk/api/v2/python/aws_cdk.aws_autoscaling/AutoScalingGroup.html), I am consistently encountering the following error:

```
jsii.errors.JavaScriptError: 
  TypeError: this.role.addToPrincipalPolicy is not a function
```

Please tell me that I am foolishly missing something obvious, otherwise would you kindly see my replication code and let me know if i can offer any more info.

### Expected Behavior

ASG should be provisioned.

### Current Behavior

ASG is **NOT** being provisioned.

### Reproduction Steps

Synth the following code:

```
        vpc = ec2.Vpc(self, "TheVPC")

        asg_role = Role(
            self, 'asg-role',
            role_name='asg',
            description='asg service role to be attached',
            managed_policies=[ManagedPolicy.from_aws_managed_policy_name('AutoScalingFullAccess')],
            assumed_by=ServicePrincipal('ec2.amazonaws.com'),
        )

        instance_profile = CfnInstanceProfile(
            self,
            "AsgInstanceProfile",
            roles=[asg_role.role_name],
        )

        launch_template = ec2.LaunchTemplate(self, 'LaunchTemplate',
                                             machine_image=ec2.AmazonLinuxImage(
                                                 generation=ec2.AmazonLinuxGeneration.AMAZON_LINUX_2
                                             ),
                                             instance_type=ec2.InstanceType.of(
                                                 ec2.InstanceClass.BURSTABLE3, ec2.InstanceSize.SMALL
                                             ),
                                             role=instance_profile,
                                             key_name='crikey',
                                             )

        asg = autoscaling.AutoScalingGroup(
            self,
            "app-asg",
            vpc=vpc,
            vpc_subnets=ec2.SubnetSelection(subnet_type=ec2.SubnetType.PRIVATE_WITH_NAT),
            min_capacity=1,
            desired_capacity=1,
            signals=Signals.wait_for_all(
                timeout=Duration.minutes(2)
            ),
            update_policy=UpdatePolicy.replacing_update(),
            mixed_instances_policy=MixedInstancesPolicy(
                launch_template=launch_template,
                instances_distribution=InstancesDistribution(
                    on_demand_allocation_strategy=OnDemandAllocationStrategy.PRIORITIZED,
                    on_demand_base_capacity=0,
                    on_demand_percentage_above_base_capacity=0,
                    spot_allocation_strategy=SpotAllocationStrategy.LOWEST_PRICE,
                    spot_instance_pools=4,
                ),
            ),
            termination_policies=[autoscaling.TerminationPolicy.OLDEST_INSTANCE, autoscaling.TerminationPolicy.DEFAULT
                                  ],
        )
```

### CDK CLI Version

2.38.1 (build a5ced21)

### Node.js Version

v16.17.0

### OS

Microsoft Windows 10 Enterprise Version	10.0.19044 Build 19044

### Language

Python

### Language Version

Python 3.10.5

### Other information

Full stack trace

```
jsii.errors.JavaScriptError: 
  TypeError: this.role.addToPrincipalPolicy is not a function
      at AutoScalingGroup.addToRolePolicy (C:\Users\superuser\AppData\Local\Temp\jsii-kernel-XP5FXx\node_modules\aws-cdk-lib\aws-autoscaling\lib\auto-scaling-group.js:1:18993)
      at AutoScalingGroup.applyUpdatePolicies (C:\Users\superuser\AppData\Local\Temp\jsii-kernel-XP5FXx\node_modules\aws-cdk-lib\aws-autoscaling\lib\auto-scaling-group.js:1:22885)
      at new AutoScalingGroup (C:\Users\superuser\AppData\Local\Temp\jsii-kernel-XP5FXx\node_modules\aws-cdk-lib\aws-autoscaling\lib\auto-scaling-group.js:1:16216)
      at exports.Kernel._create (C:\Users\superuser\AppData\Local\Temp\tmpat4uksy_\lib\program.js:5181:179)
      at exports.Kernel.create (C:\Users\superuser\AppData\Local\Temp\tmpat4uksy_\lib\program.js:4989:29)
      at exports.KernelHost.processRequest (C:\Users\superuser\AppData\Local\Temp\tmpat4uksy_\lib\program.js:6083:36)
      at exports.KernelHost.run (C:\Users\superuser\AppData\Local\Temp\tmpat4uksy_\lib\program.js:6057:48)
      at Immediate._onImmediate (C:\Users\superuser\AppData\Local\Temp\tmpat4uksy_\lib\program.js:6058:46)
      at processImmediate (node:internal/timers:466:21)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<path_cdk_project>\sandbox\app.py", line 14, in <module>
    demo = DemoStack(app, "DemoStack",
  File "<path_cdk_project>\sandbox\.venv\lib\site-packages\jsii\_runtime.py", line 86, in __call__
    inst = super().__call__(*args, **kwargs)
  File "<path_cdk_project>\sandbox\sandbox\demo_stack.py", line 54, in __init__
    asg = autoscaling.AutoScalingGroup(
  File "<path_cdk_project>\sandbox\.venv\lib\site-packages\jsii\_runtime.py", line 86, in __call__
    inst = super().__call__(*args, **kwargs)
  File "<path_cdk_project>\sandbox\.venv\lib\site-packages\aws_cdk\aws_autoscaling\__init__.py", line 17239, in __init__
    jsii.create(self.__class__, self, [scope, id, props])
  File "<path_cdk_project>\sandbox\.venv\lib\site-packages\jsii\_kernel\__init__.py", line 321, in create
    response = self.provider.create(
  File "<path_cdk_project>\sandbox\.venv\lib\site-packages\jsii\_kernel\providers\process.py", line 347, in create
    return self._process.send(request, CreateResponse)
  File "<path_cdk_project>\sandbox\.venv\lib\site-packages\jsii\_kernel\providers\process.py", line 329, in send
    raise JSIIError(resp.error) from JavaScriptError(resp.stack)
jsii.errors.JSIIError: this.role.addToPrincipalPolicy is not a function
```

**Comment by comcalvi** [comment]
you’ve passed a `CfnInstanceProfile` where an `IRole` was expected:
```
        instance_profile = CfnInstanceProfile(
            self,
            "AsgInstanceProfile",
            roles=[asg_role.role_name],
        )

        launch_template = ec2.LaunchTemplate(self, 'LaunchTemplate',
                             machine_image=ec2.AmazonLinuxImage(
                                     generation=ec2.AmazonLinuxGeneration.AMAZON_LINUX_2
                             ),
                             instance_type=ec2.InstanceType.of(
                                 ec2.InstanceClass.BURSTABLE3, ec2.InstanceSize.SMALL
                             ),
                             role=instance_profile, # here: `CfnInstanceProfile` does not implement `IRole`
                             key_name='crikey',
        )
```

**Comment by peterwoodworth** [comment]
Let us know if this fixes the error @greg5123334 (it should 🙂)

**Comment by greg5123334** [comment]
that's help! thanks :)
