### ISSUE TITLE
aws-cdk-lib: Duration.seconds and Duration.minutes methods not working

### ISSUE THREAD

**Issue by ionscorobogaci** [aws/aws-cdk#21778]
### Describe the bug

Duration.seconds method not working

### Expected Behavior

I have configured an lifecycle rule for an s3 bucket created with CDK and used Duration 

```
    new Bucket(this.scope, 'TestBucket', {
      bucketName: "sample-bucket",
      removalPolicy: RemovalPolicy.DESTROY,
      autoDeleteObjects: true,
      accessControl: BucketAccessControl.PUBLIC_READ,
      lifecycleRules:[
        {
          expiration:Duration.seconds(30)
        }
      ]
    });
```

Expected behaviour after `cdk synth` or `cdk deploy` is that the stack is deployed

### Current Behavior

Error is thrown when using `cdk synth` and the stack cannot be synthetized

```
Error: Resolution error: Resolution error: Resolution error: '30 seconds' cannot be converted into a whole number of days..
Object creation stack:
  at Execute again with CDK_DEBUG=true to capture stack traces..
    at convert (/Users/ion/docugen/repositories/docugen-api/ops/node_modules/aws-cdk-lib/core/lib/duration.js:1:5949)
    at Duration.toDays (/Users/ion/docugen/repositories/docugen-api/ops/node_modules/aws-cdk-lib/core/lib/duration.js:1:3407)
    at parseLifecycleRule (/Users/ion/docugen/repositories/docugen-api/ops/node_modules/aws-cdk-lib/aws-s3/lib/bucket.js:1:23672)
    at Array.map (<anonymous>)
    at Bucket.parseLifecycleConfiguration (/Users/ion/docugen/repositories/docugen-api/ops/node_modules/aws-cdk-lib/aws-s3/lib/bucket.js:1:23346)
    at Object.produce (/Users/ion/docugen/repositories/docugen-api/ops/node_modules/aws-cdk-lib/aws-s3/lib/bucket.js:1:13104)
    at LazyAny.resolve (/Users/ion/docugen/repositories/docugen-api/ops/node_modules/aws-cdk-lib/core/lib/lazy.js:1:3889)
    at LazyAny.resolve (/Users/ion/docugen/repositories/docugen-api/ops/node_modules/aws-cdk-lib/core/lib/lazy.js:1:4479)
    at RememberingTokenResolver.resolveToken (/Users/ion/docugen/repositories/docugen-api/ops/node_modules/aws-cdk-lib/core/lib/resolvable.js:1:1238)
    at RememberingTokenResolver.resolveToken (/Users/ion/docugen/repositories/docugen-api/ops/node_modules/aws-cdk-lib/core/lib/private/resolve.js:1:4058)
```

### Reproduction Steps

Crete a stack and use `Duration.minutes` or `Duration.seconds` methods

### CDK CLI Version

2.39.0

### Node.js Version

16.15.1

### OS

MacOs

### Language

Typescript

### Language Version

3.9.7

**Comment by peterwoodworth** [comment]
Like the error message and our [documentation](https://docs.aws.amazon.com/cdk/api/v1/docs/@aws-cdk_aws-s3.LifecycleRule.html#expiration) says, this prop requires you submit a value which is equivalent to a whole number of days because that's what [CloudFormation takes in](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-s3-bucket-lifecycleconfig-rule.html#cfn-s3-bucket-lifecycleconfig-rule-expirationindays)

**Comment by lauragalera** [comment]
Thank you @peterwoodworth for the clarification. The [aws-cdk-lib documentation](https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_s3.LifecycleRule.html) uses minutes though.

**Comment by electronicalias** [comment]
Possibly old news now, but this did work in mine (after coming across the same error):
'''
taskDefinition.addContainer(`${registry}ContainerDefCdk`, {
        image: ecs.ContainerImage.fromEcrRepository(imageRepo),
        essential: true,
        stopTimeout: cdk.Duration.seconds(30),
        linuxParameters: new ecs.LinuxParameters(this, `${registry}-LinuxParameters`, {
          initProcessEnabled: true,
        }),
        logging: ecs.LogDrivers.awsLogs({
          logGroup: logGroup,
          streamPrefix: 'ecs',
          mode: ecs.AwsLogDriverMode.NON_BLOCKING,
        }),
        containerName: `${registry}`
      })
      '''
