### ISSUE TITLE
cdk synth: Running cdk synth standalone requires AWS credentials. It fails with `The security token included in the request is expired`

### ISSUE THREAD

**Issue by knihit** [aws/aws-cdk#21831]
### Describe the bug

With v2.39.1, when running `cdk synth` for a Typescript runtime project, the synthesis fails with an error `The security token included in the request is expired`. After setting the `AWS_ACCESS_ID`, `AWS_SECRET_ACCESS_KEY` and `AWS_SESSION_TOKEN`, the synthesis works as expected.

### Expected Behavior

The synthesis should work standalone without the need for providing AWS credentials.

### Current Behavior

when executing `cdk synth` the output errors out to the following message `The security token included in the request is expired`.

### Reproduction Steps

After install v2.39.1, run `cdk synth` on the terminal.

### CDK CLI Version

2.39.1

### Node.js Version

16.16.0

### OS

12.5.1

### Language

Typescript

### Language Version

4.7.4

**Comment by peterwoodworth** [comment]
You don't need credentials for synth unless your stack performs any lookups during runtime. Your stack is likely performing some lookup such as `Vpc.fromLookup()` which requires credentials

**Comment by knihit** [comment]
@peterwoodworth, its not performing any lookup. I am using this library - https://github.com/awslabs/aws-solutions-constructs/. Wondering if that is doing some lookup which I am not aware of. Is there a way to dump some verbose output that would allow me to reach the root from which a call is being made that requires AWS credentials.

**Comment by knihit** [comment]
@peterwoodworth, I created a new project using `cdk init --language typescript` and then immediately run `cdk synth` right after the project is created, it gives me the same error.

**Comment by knihit** [comment]
Output from `cdk synth --verbose`

```CDK toolkit version: 2.39.1 (build f188fac)
Command line arguments: {
  _: [ 'synth' ],
  verbose: 1,
  v: 1,
  lookups: true,
  'ignore-errors': false,
  ignoreErrors: false,
  json: false,
  j: false,
  debug: false,
  ec2creds: undefined,
  i: undefined,
  'version-reporting': undefined,
  versionReporting: undefined,
  'path-metadata': true,
  pathMetadata: true,
  'asset-metadata': true,
  assetMetadata: true,
  'role-arn': undefined,
  r: undefined,
  roleArn: undefined,
  staging: true,
  'no-color': false,
  noColor: false,
  ci: false,
  validation: true,
  quiet: false,
  q: false,
  '$0': '/opt/homebrew/bin/cdk'
}
cdk.json: {
  "app": "npx ts-node --prefer-ts-exts bin/sample-cdk-app.ts",
  "watch": {
    "include": [
      "**"
    ],
    "exclude": [
      "README.md",
      "cdk*.json",
      "**/*.d.ts",
      "**/*.js",
      "tsconfig.json",
      "package*.json",
      "yarn.lock",
      "node_modules",
      "test"
    ]
  },
  "context": {
    "@aws-cdk/aws-apigateway:usagePlanKeyOrderInsensitiveId": true,
    "@aws-cdk/core:stackRelativeExports": true,
    "@aws-cdk/aws-rds:lowercaseDbIdentifier": true,
    "@aws-cdk/aws-lambda:recognizeVersionProps": true,
    "@aws-cdk/aws-lambda:recognizeLayerVersion": true,
    "@aws-cdk/aws-cloudfront:defaultSecurityPolicyTLSv1.2_2021": true,
    "@aws-cdk-containers/ecs-service-extensions:enableDefaultLogDriver": true,
    "@aws-cdk/aws-ec2:uniqueImdsv2TemplateName": true,
    "@aws-cdk/core:checkSecretUsage": true,
    "@aws-cdk/aws-iam:minimizePolicies": true,
    "@aws-cdk/aws-ecs:arnFormatIncludesClusterName": true,
    "@aws-cdk/core:validateSnapshotRemovalPolicy": true,
    "@aws-cdk/aws-codepipeline:crossAccountKeyAliasStackSafeResourceName": true,
    "@aws-cdk/aws-s3:createDefaultLoggingPolicy": true,
    "@aws-cdk/aws-sns-subscriptions:restrictSqsDescryption": true,
    "@aws-cdk/aws-apigateway:disableCloudWatchRole": true,
    "@aws-cdk/core:enablePartitionLiterals": true,
    "@aws-cdk/core:target-partitions": [
      "aws",
      "aws-cn"
    ]
  }
}
merged settings: {
  versionReporting: true,
  pathMetadata: true,
  output: 'cdk.out',
  app: 'npx ts-node --prefer-ts-exts bin/sample-cdk-app.ts',
  watch: {
    include: [ '**' ],
    exclude: [
      'README.md',
      'cdk*.json',
      '**/*.d.ts',
      '**/*.js',
      'tsconfig.json',
      'package*.json',
      'yarn.lock',
      'node_modules',
      'test'
    ]
  },
  context: {
    '@aws-cdk/aws-apigateway:usagePlanKeyOrderInsensitiveId': true,
    '@aws-cdk/core:stackRelativeExports': true,
    '@aws-cdk/aws-rds:lowercaseDbIdentifier': true,
    '@aws-cdk/aws-lambda:recognizeVersionProps': true,
    '@aws-cdk/aws-lambda:recognizeLayerVersion': true,
    '@aws-cdk/aws-cloudfront:defaultSecurityPolicyTLSv1.2_2021': true,
    '@aws-cdk-containers/ecs-service-extensions:enableDefaultLogDriver': true,
    '@aws-cdk/aws-ec2:uniqueImdsv2TemplateName': true,
    '@aws-cdk/core:checkSecretUsage': true,
    '@aws-cdk/aws-iam:minimizePolicies': true,
    '@aws-cdk/aws-ecs:arnFormatIncludesClusterName': true,
    '@aws-cdk/core:validateSnapshotRemovalPolicy': true,
    '@aws-cdk/aws-codepipeline:crossAccountKeyAliasStackSafeResourceName': true,
    '@aws-cdk/aws-s3:createDefaultLoggingPolicy': true,
    '@aws-cdk/aws-sns-subscriptions:restrictSqsDescryption': true,
    '@aws-cdk/aws-apigateway:disableCloudWatchRole': true,
    '@aws-cdk/core:enablePartitionLiterals': true,
    '@aws-cdk/core:target-partitions': [ 'aws', 'aws-cn' ]
  },
  debug: false,
  assetMetadata: true,
  toolkitBucket: {},
  staging: true,
  bundlingStacks: [ '*' ],
  lookups: true
}
Determining if we're on an EC2 instance.
Does not look like an EC2 instance.
Reading cached notices from /Users/nihitkas/.cdk/cache/notices.json
Toolkit stack: CDKToolkit
Setting "CDK_DEFAULT_REGION" environment variable to us-west-2
Resolving default credentials
Looking up default account ID from STS
Reading cached notices from /Users/nihitkas/.cdk/cache/notices.json

The security token included in the request is expired
ExpiredToken: The security token included in the request is expired
    at Request.extractError (/opt/homebrew/Cellar/aws-cdk/2.39.1/libexec/lib/node_modules/aws-sdk/lib/protocol/query.js:50:29)
    at Request.callListeners (/opt/homebrew/Cellar/aws-cdk/2.39.1/libexec/lib/node_modules/aws-sdk/lib/sequential_executor.js:106:20)
    at Request.emit (/opt/homebrew/Cellar/aws-cdk/2.39.1/libexec/lib/node_modules/aws-sdk/lib/sequential_executor.js:78:10)
    at Request.emit (/opt/homebrew/Cellar/aws-cdk/2.39.1/libexec/lib/node_modules/aws-sdk/lib/request.js:686:14)
    at Request.transition (/opt/homebrew/Cellar/aws-cdk/2.39.1/libexec/lib/node_modules/aws-sdk/lib/request.js:22:10)
    at AcceptorStateMachine.runTo (/opt/homebrew/Cellar/aws-cdk/2.39.1/libexec/lib/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at /opt/homebrew/Cellar/aws-cdk/2.39.1/libexec/lib/node_modules/aws-sdk/lib/state_machine.js:26:10
    at Request.<anonymous> (/opt/homebrew/Cellar/aws-cdk/2.39.1/libexec/lib/node_modules/aws-sdk/lib/request.js:38:9)
    at Request.<anonymous> (/opt/homebrew/Cellar/aws-cdk/2.39.1/libexec/lib/node_modules/aws-sdk/lib/request.js:688:12)
    at Request.callListeners (/opt/homebrew/Cellar/aws-cdk/2.39.1/libexec/lib/node_modules/aws-sdk/lib/sequential_executor.js:116:18)
```

**Comment by peterwoodworth** [comment]
Try using the `--no-notices` flag, see if that works?

I have a set of credentials that will expire in an hour that I'll try synthing with, but if I can't reproduce this even with expired credentials then i'm not sure what the issue would be here

**Comment by knihit** [comment]
So under `~/.aws/credentials` I had a `default` profile with expired values of `AWS_ACCESS_ID`, `AWS_SECRET_ACCESS_KEY` and `AWS_SESSION_TOKEN`. Deleting those entries and keeping `default` profile empty, did the trick and resolved the error. Before deleting these values I even tried `cdk synth --lookup false`, but I was still getting the same error. I could be wrong, but if the stack does not require a lookup, it should be use the profile credentials to access AWS.

**Comment by Naumel** [comment]
Hi,

Just a quick note on credential hygiene when using profiles: use combos that do not expire, like `aws_access_key_id` and `aws_secret_access_key`.

A session token being present means you'll have to edit the credentials' file multiple times.

It's a smoother experience to use environment variables, if sessions need to be part of the workflow.

**Comment by Naumel** [comment]
Available reference: https://docs.aws.amazon.com/cdk/v2/guide/getting_started.html#getting_started_prerequisites 

Closing the issue, as it seems a working solution was reached.
