### ISSUE TITLE
CfnInclude: Can't synthesize imported cdk stack (duplicated BootstrapVersion parameter)

### ISSUE THREAD

**Issue by fmenezes-caylent** [aws/aws-cdk#21936]
### CDK fails to synthesize app due to duplicated "BootstrapVersion" parameter in stacks imported with CfnInclude.

I'm trying to import several existing CFN stacks into a CDK app. The first cdk deploy works (which adds the CDK Metadata and parameters).
Afterwards, whenever I try to synthesize or diff the app I get a duplicated parameter error

### Expected Behavior

I expect "cdk synth/diff" to show no differences since the template was copied from CFN console

### Current Behavior

```python
>> app.synth()

jsii.errors.JavaScriptError: 
  Error: section 'Parameters' already contains 'BootstrapVersion'
      at mergeObjectsWithoutDuplicates (/private/var/folders/v_/km9ss9lx0pjd12hzdq3jj7780000gn/T/jsii-kernel-bG1ad7/node_modules/aws-cdk-lib/core/lib/stack.js:2:854)
      at mergeSection (/private/var/folders/v_/km9ss9lx0pjd12hzdq3jj7780000gn/T/jsii-kernel-bG1ad7/node_modules/aws-cdk-lib/core/lib/stack.js:2:254)
      at merge (/private/var/folders/v_/km9ss9lx0pjd12hzdq3jj7780000gn/T/jsii-kernel-bG1ad7/node_modules/aws-cdk-lib/core/lib/stack.js:1:14680)
      at Stack._toCloudFormation (/private/var/folders/v_/km9ss9lx0pjd12hzdq3jj7780000gn/T/jsii-kernel-bG1ad7/node_modules/aws-cdk-lib/core/lib/stack.js:1:12821)
      at Stack._synthesizeTemplate (/private/var/folders/v_/km9ss9lx0pjd12hzdq3jj7780000gn/T/jsii-kernel-bG1ad7/node_modules/aws-cdk-lib/core/lib/stack.js:1:8464)
      at DefaultStackSynthesizer.synthesizeStackTemplate (/private/var/folders/v_/km9ss9lx0pjd12hzdq3jj7780000gn/T/jsii-kernel-bG1ad7/node_modules/aws-cdk-lib/core/lib/stack-synthesizers/default-synthesizer.js:1:5057)
      at DefaultStackSynthesizer.synthesize (/private/var/folders/v_/km9ss9lx0pjd12hzdq3jj7780000gn/T/jsii-kernel-bG1ad7/node_modules/aws-cdk-lib/core/lib/stack-synthesizers/default-synthesizer.js:1:5554)
      at /private/var/folders/v_/km9ss9lx0pjd12hzdq3jj7780000gn/T/jsii-kernel-bG1ad7/node_modules/aws-cdk-lib/core/lib/private/synthesis.js:1:2661
      at visit (/private/var/folders/v_/km9ss9lx0pjd12hzdq3jj7780000gn/T/jsii-kernel-bG1ad7/node_modules/aws-cdk-lib/core/lib/private/synthesis.js:3:179)
      at visit (/private/var/folders/v_/km9ss9lx0pjd12hzdq3jj7780000gn/T/jsii-kernel-bG1ad7/node_modules/aws-cdk-lib/core/lib/private/synthesis.js:3:141)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/felipe/Library/Python/3.8/lib/python/site-packages/aws_cdk/__init__.py", line 18309, in synth
    return typing.cast(_CloudAssembly_c693643e, jsii.invoke(self, "synth", [options]))
  File "/Users/felipe/Library/Python/3.8/lib/python/site-packages/jsii/_kernel/__init__.py", line 148, in wrapped
    return _recursize_dereference(kernel, fn(kernel, *args, **kwargs))
  File "/Users/felipe/Library/Python/3.8/lib/python/site-packages/jsii/_kernel/__init__.py", line 386, in invoke
    response = self.provider.invoke(
  File "/Users/felipe/Library/Python/3.8/lib/python/site-packages/jsii/_kernel/providers/process.py", line 362, in invoke
    return self._process.send(request, InvokeResponse)
  File "/Users/felipe/Library/Python/3.8/lib/python/site-packages/jsii/_kernel/providers/process.py", line 329, in send
    raise JSIIError(resp.error) from JavaScriptError(resp.stack)
jsii.errors.JSIIError: section 'Parameters' already contains 'BootstrapVersion'
```

### Reproduction Steps

1. Save the following template in a file and use it to create a CFN stack 

aws cloudformation create-stack --stack-name test-bt  --template-body file://test-bt.json            

```javascript
    "Resources": {
        "VPC": {
            "Type": "AWS::EC2::VPC",
            "Properties": {
                "CidrBlock": "10.50.0.0/16",
                "EnableDnsSupport": true,
                "EnableDnsHostnames": true,
                "Tags": [
                    {
                        "Key": "Name",
                        "Value": "Bug Test"
                    }
                ]
            }
        }
    },
    "Parameters": {
        "BootstrapVersion": {
            "Type": "AWS::SSM::Parameter::Value<String>",
            "Default": "/cdk-bootstrap/hnb659fds/version",
            "Description": "Version of the CDK Bootstrap resources in this environment, automatically retrieved from SSM Parameter Store. [cdk:skip]"
        }
    },
    "Rules": {
        "CheckBootstrapVersion": {
            "Assertions": [
                {
                    "Assert": {
                        "Fn::Not": [
                            {
                                "Fn::Contains": [
                                    [
                                        "1",
                                        "2",
                                        "3",
                                        "4",
                                        "5"
                                    ],
                                    {
                                        "Ref": "BootstrapVersion"
                                    }
                                ]
                            }
                        ]
                    },
                    "AssertDescription": "CDK bootstrap stack version 6 required. Please run 'cdk bootstrap' with a recent version of the CDK CLI."
                }
            ]
        }
    }
}
```

2. Using CfnInclude, import the template into a cdk app (this runs in REPL)

```python
import aws_cdk as cdk
from aws_cdk import (
    Stack,
)
from constructs import Construct
from aws_cdk.cloudformation_include import CfnInclude

app = cdk.App()
stack_obj = Stack(app, 'wrapper-stack')
CfnInclude(
  stack_obj, 'test-bt',
  template_file="test-bt.json"
)
```
Now, if you run app.synth(), you'll find the above error:

> jsii.errors.JSIIError: section 'Parameters' already contains 'BootstrapVersion'

However, if you remove the CDK Parameters and Rules from the template and try to synthesize again, it'll work:

> Removing the cdk added parameters and rules from the file (only edit the file)

```javascript
{
    "Resources": {
        "VPC": {
            "Type": "AWS::EC2::VPC",
            "Properties": {
                "CidrBlock": "10.50.0.0/16",
                "EnableDnsSupport": true,
                "EnableDnsHostnames": true,
                "Tags": [
                    {
                        "Key": "Name",
                        "Value": "Bug Test"
                    }
                ]
            }
        }
    }
}
```
Restart the REPL session and re-run the code above, app.synth() will work as expected.

### Additional Information/Context

I have an existing set of stacks that will be migrated to CDK. Even though the first 'cdk deploy' works, subsequent ones don't, which can stop us from making changes in the future

### CDK CLI Version

2.40.0 (build 56ba2ab)

### Node.js Version

v16.16.0

### OS

Mac OS X

### Language

Python

### Language Version

Python 3.8.9

**Comment by peterwoodworth** [comment]
Your template you're trying to import looks like it was initially created with CDK. This means that it will have the `BootstrapVersion` parameter inside the template. When you import this template with CfnInclude, it will attempt to add all the parameters to your stack you're importing the template into. As a result, since the stack in our CDK app and in your template both have the same Parameter, this error will throw. 

You can fix this by removing the parameter from your template, or by [replacing the parameter](https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.cloudformation_include-readme.html#parameter-replacement) on import
