### ISSUE TITLE
aws_lambda: Unable to serialize secret arn in environment variables

### ISSUE THREAD

**Issue by mneirynck** [aws/aws-cdk#21979]
### Describe the bug

Using a reference to a manually created secret in secretsmanager fails. It seems the secret is synthesized after the lambda.

### Expected Behavior

The secret arn gets synthesized before the lambda so it can be used as an environment variable.

### Current Behavior

```
jsii.errors.JavaScriptError: 
  @jsii/kernel.SerializationError: Passed to parameter props of new aws-cdk-lib.aws_lambda.Function: Unable to deserialize value as aws-cdk-lib.aws_lambda.FunctionProps
  ├── 🛑 Failing value is an object
  │      { '$jsii.struct': [Object] }
  ╰── 🔍 Failure reason(s):
      ╰─ Key 'environment': Unable to deserialize value as map<string> | undefined
          ├── 🛑 Failing value is an object
          │      { '$jsii.map': [Object] }
          ╰── 🔍 Failure reason(s):
              ╰─ Key 'BRIO_INTEGRATION_SECRET': Unable to deserialize value as string
                  ├── 🛑 Failing value is null
                  ╰── 🔍 Failure reason(s):
                      ╰─ A value is required (type is non-optional)
      at Object.process (/tmp/tmpcf6gzbf7/lib/program.js:6194:19)
      at exports.Kernel._toSandbox (/tmp/tmpcf6gzbf7/lib/program.js:5829:29)
      at /tmp/tmpcf6gzbf7/lib/program.js:5854:42
      at Array.map (<anonymous>)
      at exports.Kernel._boxUnboxParameters (/tmp/tmpcf6gzbf7/lib/program.js:5854:27)
      at exports.Kernel._toSandboxValues (/tmp/tmpcf6gzbf7/lib/program.js:5845:29)
      at exports.Kernel._create (/tmp/tmpcf6gzbf7/lib/program.js:5593:42)
      at exports.Kernel.create (/tmp/tmpcf6gzbf7/lib/program.js:5400:29)
      at exports.KernelHost.processRequest (/tmp/tmpcf6gzbf7/lib/program.js:6618:36)
      at exports.KernelHost.run (/tmp/tmpcf6gzbf7/lib/program.js:6592:48)
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "/home/mneirynck/Development/aws-cdk/./app.py", line 85, in <module>
    VOIPPlatformStackEnvironment(app, AWSEnvironments.VOIP_LAB)
  File "/home/mneirynck/Development/aws-cdk/environments/voip_platform.py", line 121, in __init__
    self._create_application_stacks(
  File "/home/mneirynck/Development/aws-cdk/environments/voip_platform.py", line 620, in _create_application_stacks
    cicero = CiceroStack(
  File "/home/mneirynck/Development/aws-cdk/.venv/lib/python3.10/site-packages/jsii/_runtime.py", line 86, in __call__
    inst = super().__call__(*args, **kwargs)
  File "/home/mneirynck/Development/aws-cdk/stacks/voip/cicero.py", line 131, in __init__
    self._create_bus_lambda()
  File "/home/mneirynck/Development/aws-cdk/stacks/voip/cicero.py", line 429, in _create_bus_lambda
    _brio_function = Function(
  File "/home/mneirynck/Development/aws-cdk/.venv/lib/python3.10/site-packages/jsii/_runtime.py", line 86, in __call__
    inst = super().__call__(*args, **kwargs)
  File "/home/mneirynck/Development/aws-cdk/.venv/lib/python3.10/site-packages/aws_cdk/aws_lambda/__init__.py", line 21923, in __init__
    jsii.create(self.__class__, self, [scope, id, props])
  File "/home/mneirynck/Development/aws-cdk/.venv/lib/python3.10/site-packages/jsii/_kernel/__init__.py", line 321, in create
    response = self.provider.create(
  File "/home/mneirynck/Development/aws-cdk/.venv/lib/python3.10/site-packages/jsii/_kernel/providers/process.py", line 347, in create
    return self._process.send(request, CreateResponse)
  File "/home/mneirynck/Development/aws-cdk/.venv/lib/python3.10/site-packages/jsii/_kernel/providers/process.py", line 329, in send
    raise JSIIError(resp.error) from JavaScriptError(resp.stack)
jsii.errors.JSIIError: Passed to parameter props of new aws-cdk-lib.aws_lambda.Function: Unable to deserialize value as aws-cdk-lib.aws_lambda.FunctionProps
├── 🛑 Failing value is an object
│      { '$jsii.struct': [Object] }
╰── 🔍 Failure reason(s):
    ╰─ Key 'environment': Unable to deserialize value as map<string> | undefined
        ├── 🛑 Failing value is an object
        │      { '$jsii.map': [Object] }
        ╰── 🔍 Failure reason(s):
            ╰─ Key 'BRIO_INTEGRATION_SECRET': Unable to deserialize value as string
                ├── 🛑 Failing value is null
                ╰── 🔍 Failure reason(s):
                    ╰─ A value is required (type is non-optional)
```

### Reproduction Steps

1. manually create a secret
2. Get the Brio integration secret
```
self._brio_integration_secret = Secret.from_secret_name_v2(
            self, "BrioIntegrationSecret", "INTEGRATION-BRIO"
        )
```
3. Use the ARN of the secret as an environment variable
```
_brio_function = Function(
            self,
            "BrioModuleLambda",
            description="Emit events from EventBridge towards Brio integration",
            code=Code.from_asset(
                path="src/python/lambdas/cicero/emitter/modules/src/brio",
                bundling=PYTHON_BUNDLER,
            ),
            handler="main.handler",
            runtime=Runtime.PYTHON_3_9,
            log_retention=RetentionDays.ONE_DAY,
            environment={
                "BRIO_INTEGRATION_SECRET": self._brio_integration_secret.secret_full_arn
            },
        )

```

### CDK CLI Version

2.41.0

### Node.js Version

16.14.2

### OS

Arch Linux

### Language

Python

### Language Version

3.10

**Comment by pradoz** [comment]
possibly related to #18555

I noticed the value is resolving to null/None - this person was able to create a workaround by granting read access from the secret to the lambda ([see comment here](https://github.com/aws/aws-cdk/issues/18555#issuecomment-1236026872))

**Comment by mneirynck** [comment]
> possibly related to #18555
> 
> I noticed the value is resolving to null/None - this person was able to create a workaround by granting read access from the secret to the lambda ([see comment here](https://github.com/aws/aws-cdk/issues/18555#issuecomment-1236026872))

Hi,
I already have a grant for the lambda on the secret:
`self._brio_integration_secret.grant_read(_brio_function)`

**Comment by peterwoodworth** [comment]
This returns undefined when importing a secret this way because we cannot guarantee a full arn from the information given. https://github.com/aws/aws-cdk/blob/9f41881be1cca31129078b7839dded480220f060/packages/%40aws-cdk/aws-secretsmanager/lib/secret.ts#L540

If you need to reference the full arn, import with `fromSecretCompleteArn()` instead. Thanks
