### ISSUE TITLE
(aws-batch): Internal failure when deploying compute environment changes

### ISSUE THREAD

**Issue by rjuengling-hf** [aws/aws-cdk#21988]
### Describe the bug

When invoking `cdk deploy` for a stack that includes Batch compute constructs, the deployment fails with the following message.
```
rjuengling-preloader: creating CloudFormation changeset...
11:15:36 PM | UPDATE_FAILED        | AWS::Batch::JobQueue             | rjuenglingpreloaderprocess0319A3D1
Internal Failure

 ❌  rjuengling-preloader-pipeline/rjuengling/preloader (rjuengling-preloader) failed: Error: The stack named rjuengling-preloader failed to deploy: UPDATE_ROLLBACK_COMPLETE: Internal Failure
    at prepareAndExecuteChangeSet (/home/rjuengling/npm/node_modules/aws-cdk/lib/api/deploy-stack.ts:386:13)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at deployStack2 (/home/rjuengling/npm/node_modules/aws-cdk/lib/cdk-toolkit.ts:240:24)
    at /home/rjuengling/npm/node_modules/aws-cdk/lib/deploy.ts:39:11
    at run (/home/rjuengling/npm/node_modules/p-queue/dist/index.js:163:29)
```

### Expected Behavior

The deployment updates the stack without error.

### Current Behavior

The deployment fails with error `Internal Failure`, seemingly when CloudFormation is attempting to update a Batch job queue.

### Reproduction Steps

Create a stack with a Batch component and all stack resources tagged with some tag.  Change the tag value, and run `cdk diff` to confirm that a stack update would entail a replacement of the job definition and job queue. Run `cdk deploy` to update the stack.

### Possible Solution

I believe the bug is not in CDK but in AWS CloudFormation. The failure occurs when the update is done by [replacement](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/using-cfn-updating-stacks-update-behaviors.html#update-replacement). This is the case when job definition's [tag](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-batch-jobdefinition.html#cfn-batch-jobdefinition-tags) or a job queue's [tag](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-batch-jobqueue.html#cfn-batch-jobqueue-tags) changes. Without changes in tags `cdk deploy` succeeds. This has been reported before [here](https://repost.aws/questions/QULDiQw0s-TwW2WKBcri6gTA/internal-error-on-cloud-formation-batch-job-definition-tags).

I examined the events initiated by CloudFormation in Cloud Trail. I see the expected event `CreateComputeEnvironment` which returns a new ARN but no event `CreateJobQueue`. So CloudFormation fails during the update of the job queue **before** creating the new job queue. I noticed `DescribeComputeEnvironments` events with the new ARN as input and a `null` response that coincide. It might be the case that the `null` response is unexpected and unhandled and is causing the update procedure to fail. I hope this helps with resolving the issue.

### CDK CLI Version

2.41.0

### Framework Version

2.41.0

### Node.js Version

16.16.0

### OS

CentOS 7

### Language

Python

### Language Version

Python 3.8.11

**Comment by samuelthan** [comment]
Yes, i am facing this issue too. When adding a new tag, or new key value to the batch job queue. Triggers an internal failure. Seems like cloudformation related -- https://github.com/aws-cloudformation/cloudformation-coverage-roadmap/issues/1229

Frustrating to now i have to break out the Tagging to each AWS resources instead of a one line Tagging of the Stack itself.

Please look into this :)

**Comment by jamesnunn** [comment]
I haven't tried this yet but you might like to know if you're using `Tag` it looks like you can exclude types
https://docs.aws.amazon.com/cdk/api/v1/docs/@aws-cdk_core.TagProps.html

**Comment by samuelthan** [comment]
Tried the suggested approach, using something like the following in reference to 

```
EXCLUDE_RESOURCE_TYPES = [
        'AWS::Batch::JobQueue'
    ]
    
    for tag in tags:
        Tags.of(app).add(tag.key, tag.value, exclude_resource_types=EXCLUDE_RESOURCE_TYPES, priority=50) 

```
It doesn't seem to work, no matter which priority i've put in ref https://docs.aws.amazon.com/cdk/api/v2/python/aws_cdk/Tags.html, the tags are still applied to the batch job queue no matter if i did include the exclude_resource_type and priority.

Any help pls ?

**Comment by jamesnunn** [comment]
I noticed that too in that it did apply the tags that I wanted but didn't cause an internal failure. Not a solution obviously.

**Comment by peterwoodworth** [comment]
This this looks like it would be a bug for CloudFormation to solve, so unfortunately we can't help much. Please reference the issue [here](https://github.com/aws-cloudformation/cloudformation-coverage-roadmap/issues/1229) for any additional comments and concerns. Thank you 🙂

**Comment by mattiamatrix** [comment]
I am having a similar error now in `2.76.0` when trying to update a `FargateComputeEnvironment` or `ManagedEc2EcsComputeEnvironment`.
