### ISSUE TITLE
aws-cdk-lib/custom-resources: Provider isComplete function gets null return value

### ISSUE THREAD

**Issue by kirnberger1980** [aws/aws-cdk#22017]
### Describe the bug

I wrote a dummy Custom Resource to learn more about the Provider Framework for Custom Resources.

Here the code snippet of the lib file:

```javascript
import * as cdk from "aws-cdk-lib";
import { Construct } from "constructs";
import { ConfigStackProps } from "../lib/types/config";
import { NodejsFunction } from "aws-cdk-lib/aws-lambda-nodejs";
import * as cr from "aws-cdk-lib/custom-resources";
import * as lambda from "aws-cdk-lib/aws-lambda";
import * as path from "path";

export class CdkTslambdaSampleStack extends cdk.Stack {
  constructor(scope: Construct, id: string, props: ConfigStackProps) {
    super(scope, id, props);

    const onEvent = new NodejsFunction(this, "OnEventFunction", {
      memorySize: props.config.memorySize,
      timeout: cdk.Duration.seconds(props.config.timeoutSeconds),
      runtime: lambda.Runtime.NODEJS_14_X,
      handler: "onEvent",
      entry: path.join(__dirname, "/../src/OnEvent/index.ts"),
      bundling: {
        minify: true,
        externalModules: ["aws-sdk"],
      }
    });

    const isComplete = new NodejsFunction(this, "IsCompleteFunction", {
      memorySize: props.config.memorySize,
      timeout: cdk.Duration.seconds(props.config.timeoutSeconds),
      runtime: lambda.Runtime.NODEJS_14_X,
      handler: "isComplete",
      entry: path.join(__dirname, "/../src/IsComplete/index.ts"),
      bundling: {
        minify: true,
        externalModules: ["aws-sdk"],
      }
    });

    const myProvider = new cr.Provider(this, "MyProvider", {
      onEventHandler: onEvent,
      isCompleteHandler: isComplete // optional async "waiter"
    });

    new cdk.CustomResource(this, "SampleCR",
      {
        serviceToken: myProvider.serviceToken,
        properties: {
          SampleProp: new Date()
        }
      });

  }
}
```

The OnEvent function is:
```javascript
import { CloudFormationCustomResourceEvent, CloudFormationCustomResourceDeleteEvent, CloudFormationCustomResourceUpdateEvent, CloudFormationCustomResourceCreateEvent } from "aws-lambda";

interface Response {
  PhysicalResourceId: string
}

export function onEvent(
  event: CloudFormationCustomResourceEvent,
): string {
  console.log("Event 👉", event);
  let response: Response;
  switch (event.RequestType){
    case "Create":
      response = onCreate(event);
      break;
    case "Delete":
      response = onDelete(event);
      break;
    case "Update":
      response = onUpdate(event);
      break;
    default:
      throw new Error("Unknown Request Type of CloudFormation");
  }
  console.log("Return value:", JSON.stringify(response))
  return JSON.stringify(response);
}

function onCreate(event: CloudFormationCustomResourceCreateEvent) : Response {
  console.log("We are in the Create Event");
  return {
    PhysicalResourceId: "abcdef-" + event.RequestId
  }
}

function onDelete(event: CloudFormationCustomResourceDeleteEvent) : Response {
  console.log("We are in the Delete Event");
  return {
    PhysicalResourceId: event.PhysicalResourceId || ""
  }
}

function onUpdate(event: CloudFormationCustomResourceUpdateEvent) : Response {
  console.log("We are in the Update Event");
  return {
    PhysicalResourceId: event.PhysicalResourceId || ""
  }
}
```

The isComplete function is:
```javascript
import { CloudFormationCustomResourceEvent, Context } from "aws-lambda";

export function isComplete(event: CloudFormationCustomResourceEvent, context: Context ) {
  console.log("Event 👉", event);
  const requestType = event.RequestType;
  console.log("Request Type is 👉", requestType);
  const isReady = true;
  const response =  {
    "IsComplete": isReady
  }
  console.log("Return value:", JSON.stringify(response));
  return JSON.stringify(response)
}
```

### Expected Behavior

The **isComplete** handler returns a json. That should be parsed properly by the provider lambda function in order to get the boolean.

### Current Behavior

The Provider functions acts like the isComplete Handler is returning null as a result. CDK Commandline:

`
10:46:15 | CREATE_FAILED        | AWS::CloudFormation::CustomResource | SampleCR
Received response status [FAILED] from custom resource. Message returned: TypeError: Cannot read property 'IsComplete' of null
at isComplete (/var/task/framework.js:1:1317)
at processTicksAndRejections (internal/process/task_queues.js:95:5)
at async Runtime.handler (/var/task/cfn-response.js:1:1474) (RequestId: 442ad793-3859-48f3-980b-e78ba536e9df)
`

CloudWatch Logs of Provider function:
`
2022-09-13T08:46:14.272Z	0c779bad-bb7c-43fb-872b-2853f90a1e00	INFO	[provider-framework] user function response: {
    "StatusCode": 200,
    "ExecutedVersion": "$LATEST",
    "Payload": "null"
} object
2022-09-13T08:46:14.310Z	0c779bad-bb7c-43fb-872b-2853f90a1e00	INFO	[provider-framework] user isComplete returned: null
2022-09-13T08:46:14.311Z	0c779bad-bb7c-43fb-872b-2853f90a1e00	INFO	[provider-framework] submit response to cloudformation {
    "Status": "FAILED",
    "Reason": "TypeError: Cannot read property 'IsComplete' of null\n    at isComplete (/var/task/framework.js:1:1317)\n    at processTicksAndRejections (internal/process/task_queues.js:95:5)\n    at async Runtime.handler (/var/task/cfn-response.js:1:1474)",
    "StackId": "arn:aws:cloudformation:eu-central-1:733264584077:stack/BARMER-CF-STACK-CUSTOMRESOURCE-PROVIDER/27e3afb0-3340-11ed-b864-0affb5d587f6",
    "RequestId": "442ad793-3859-48f3-980b-e78ba536e9df",
    "PhysicalResourceId": "442ad793-3859-48f3-980b-e78ba536e9df",
    "LogicalResourceId": "SampleCR"
}
`

### Reproduction Steps

Deploy the code as described in the bug description.

### CDK CLI Version

2.40.0 (build 56ba2ab)

### Node.js Version

v16.17.0

### OS

macOs Monterey

### Language

Typescript

### Language Version

4.4.3

**Comment by kirnberger1980** [comment]
Fixed it for myself. The problem was, that NodeJS 14.x function needs to be `async` 

```javascript
import { CloudFormationCustomResourceEvent, Context } from "aws-lambda";

export async function isComplete(event: CloudFormationCustomResourceEvent, context: Context) {
  console.log("Event 👉", event);
  const requestType = event.RequestType;
  console.log("Request Type is 👉", requestType);
  const isReady = true;
  const response =  {
    "IsComplete": isReady
  };
  return response;
}
````
Closing this issue now.
