### ISSUE TITLE
cdk --version: ENOENT: no such file or directory, lstat 'D:\'

### ISSUE THREAD

**Issue by pavan-chithari** [aws/aws-cdk#22049]
### Describe the bug

**cdk-version**  command shows me the following error.

C:\Users\xxxxxxx>cdk --version
Error: ENOENT: no such file or directory, lstat 'D:\'
    at Object.realpathSync (node:fs:2461:5)
    at cdkHomeDir (C:\Users\xxxxxx\AppData\Roaming\npm\node_modules\aws-cdk\lib\util\directories.ts:17:21)
    at cdkCacheDir (C:\Users\xxxxxx\AppData\Roaming\npm\node_modules\aws-cdk\lib\util\directories.ts:28:20)
    at accountCacheDir (C:\Users\xxxxxx\AppData\Roaming\npm\node_modules\aws-cdk\lib\api\aws-auth\_env.ts:16:10)
    at new _AccountAccessKeyCache (C:\Users\xxxxxx\AppData\Roaming\npm\node_modules\aws-cdk\lib\api\aws-auth\account-cache.ts:24:44)
    at lib/api/aws-auth/sdk.ts (C:\Users\xxxxxx\AppData\Roaming\npm\node_modules\aws-cdk\lib\api\aws-auth\sdk.ts:85:42)    at __init (C:\Users\xxxxxx\AppData\Roaming\npm\node_modules\aws-cdk\lib\index.js:9:56)
    at lib/api/aws-auth/index.ts (C:\Users\xxxxxx\AppData\Roaming\npm\node_modules\aws-cdk\lib\api\aws-auth\index.ts:1:1)
    at __init (C:\Users\xxxxxx\AppData\Roaming\npm\node_modules\aws-cdk\lib\index.js:9:56)
    at lib/api/bootstrap/deploy-bootstrap.ts (C:\Users\xxxxxx\AppData\Roaming\npm\node_modules\aws-cdk\lib\api\bootstrap\deploy-bootstrap.ts:7:1)

Node and NPM versions as follows.
C:\Users\xxxxxx>node --version
v16.16.0

C:\Users\xxxxxx>npm --version
8.11.0

FYI, I've re installed everything also tried with latest versions of Node and NPM.

Thanks
Pavan

### Expected Behavior

~]$ cdk --version
2.41.0 (build 6ad48a3)

### Current Behavior

C:\Users\xxxxxxx>cdk --version
Error: ENOENT: no such file or directory, lstat 'D:\'
    at Object.realpathSync (node:fs:2461:5)
    at cdkHomeDir (C:\Users\xxxxxx\AppData\Roaming\npm\node_modules\aws-cdk\lib\util\directories.ts:17:21)
    at cdkCacheDir (C:\Users\xxxxxx\AppData\Roaming\npm\node_modules\aws-cdk\lib\util\directories.ts:28:20)
    at accountCacheDir (C:\Users\xxxxxx\AppData\Roaming\npm\node_modules\aws-cdk\lib\api\aws-auth\_env.ts:16:10)
    at new _AccountAccessKeyCache (C:\Users\xxxxxx\AppData\Roaming\npm\node_modules\aws-cdk\lib\api\aws-auth\account-cache.ts:24:44)
    at lib/api/aws-auth/sdk.ts (C:\Users\xxxxxx\AppData\Roaming\npm\node_modules\aws-cdk\lib\api\aws-auth\sdk.ts:85:42)    at __init (C:\Users\xxxxxx\AppData\Roaming\npm\node_modules\aws-cdk\lib\index.js:9:56)
    at lib/api/aws-auth/index.ts (C:\Users\xxxxxx\AppData\Roaming\npm\node_modules\aws-cdk\lib\api\aws-auth\index.ts:1:1)
    at __init (C:\Users\xxxxxx\AppData\Roaming\npm\node_modules\aws-cdk\lib\index.js:9:56)
    at lib/api/bootstrap/deploy-bootstrap.ts (C:\Users\xxxxxx\AppData\Roaming\npm\node_modules\aws-cdk\lib\api\bootstrap\deploy-bootstrap.ts:7:1)

### Reproduction Steps

None

### CDK CLI Version

error

### Node.js Version

v16.16.0

### OS

windows

### Language

Typescript

**Comment by rix0rrr** [comment]
Looks like your OS has `D:\` configured as temporary directory:

https://github.com/aws/aws-cdk/blob/b8c2abf06ba14f9c356864aba91180a55cbd9c3b/packages/aws-cdk/lib/util/directories.ts#L17
