### ISSUE TITLE
api_gateway: Circular dependency between KMS key and ServiceRole for gateway AuthHandler

### ISSUE THREAD

**Issue by kornicameister** [aws/aws-cdk#22047]
### Describe the bug

# Why

I wanted to have a single KMS key used for entire deployment stage (no requirements to have it other way around) that is used in multiple other stacks defining different functionalities.

# Approach 1

- I have successfully created a stack A that contains a single encryption key, called master key
- I imported master key in stack B using its ARN
- I was able to create an alias for that key in a stack B
- I was able to synthetize the stacks and able to overview the changes, however key policy was not correct, key policy entries so that service B.2 can decrypt messages and B.1 is able to encrypt them, were gone
- there was also an issue in service B3 around encryption key access for secrets used in ApiGateway lambda authorizer

However a key was properly imported via SSM and later an alias was added.

## Why I think it failed with permissions but key was 

Because keys imported via https://docs.aws.amazon.com/cdk/api/v2/python/aws_cdk.aws_kms/Key.html#aws_cdk.aws_kms.Key.from_key_arn do no contain a reference to key originally created in stack A hence calls like https://docs.aws.amazon.com/cdk/api/v2/python/aws_cdk.aws_kms/Key.html#aws_cdk.aws_kms.Key.add_to_resource_policy do not really work

# Approach 2

- I have successfully created a stack A that contains a single encryption key, called master key
- I have successfully used Fn::Export + Fn::Import to obtain an access to master key in stack B
- I was also able to create a new alias to support operations in stack B
- Key policies were correctly configured
- ApiGateway in stack B (the one with encrypted secret used in lambda authorized, mentioned in approach 1) failed to synt due to circular dependency error

```
Traceback (most recent call last):
  File "/Users/kornicameister/dev-ay/app/app.py", line 8, in <module>
    PipelineStack(
  File "/Users/kornicameister/.pyenv/versions/app/lib/python3.10/site-packages/jsii/_runtime.py", line 86, in __call__
    inst = super().__call__(*args, **kwargs)
  File "/Users/kornicameister/dev-ay/app/ay/pipeline.py", line 236, in __init__
    pipeline.add_stage(
  File "/Users/kornicameister/.pyenv/versions/app/lib/python3.10/site-packages/aws_cdk/pipelines/__init__.py", line 3534, in add_stage
    return typing.cast("StageDeployment", jsii.invoke(self, "addStage", [stage, options]))
  File "/Users/kornicameister/.pyenv/versions/app/lib/python3.10/site-packages/jsii/_kernel/__init__.py", line 148, in wrapped
    return _recursize_dereference(kernel, fn(kernel, *args, **kwargs))
  File "/Users/kornicameister/.pyenv/versions/app/lib/python3.10/site-packages/jsii/_kernel/__init__.py", line 386, in invoke
    response = self.provider.invoke(
  File "/Users/kornicameister/.pyenv/versions/app/lib/python3.10/site-packages/jsii/_kernel/providers/process.py", line 362, in invoke
    return self._process.send(request, InvokeResponse)
  File "/Users/kornicameister/.pyenv/versions/app/lib/python3.10/site-packages/jsii/_kernel/providers/process.py", line 329, in send
    raise JSIIError(resp.error) from JavaScriptError(resp.stack)
jsii.errors.JSIIError: 'AGW' depends on 'KMS' (dependency added using stack.addDependency()). Adding this dependency (KMS -> AGW/API/Authorizer/Handler/ServiceRole/Resource.Arn) would create a cyclic reference.
```

# How I could make it work and why I haven't

There's a workaround for that problem. I actually need to have:
- one version of a key that is obtained via `Fn::Import` where all `add_to_resource_policy` calls work and key policy is correct
- another version of a key imported either via `Key.fromKeyArn` (via SSM) or `Alias.fromAliasName` (I compute aliases statically so I can reference them across stacks without any error) for the sake of API gateway authorizer

But it is a bit awkward just by looking at it and I am pretty sure I would have created unmaintainable code just because I would create two dependency points:
- one via `Fn::Export` and `Fn::Import`
- another via either via SSM -> key ARN or key alias 

### Expected Behavior

Not quite sure if there's any. I mean I would love the code to work but I cannot get stop thinking that either:
- I might be doing something awfully wrong
- CDK is actually protecting me

However, I wonder if any calls to `addToResourcePolicies` executed over imported keys `Key.fromLookup`, `Key.fromKeyArn` or `Alias.fromAliasName` should fail. I mean it clearly haven't worked for me and it makes to me that it shouldn't. After all key policy is created the moment key is defined and each of mentioned methods do assume key already exists (in different stack, in different place, manually created or whatever else). If there's a point to this bug: it might be it. 

### Current Behavior

Either:
- key policy is not correct
- stack does not synth due to circular dependency

### Reproduction Steps

WIP, will try to have it done. I know I need to but I cannot have right away. Need to unbox all relevant pieces into SSCCE.

### Possible Solution

N/A

### CDK CLI Version

2.41.0

### Framework Version

?

### Node.js Version

14.17.5

### OS

MAC

### Language

Python

### Language Version

3.10.5

**Comment by peterwoodworth** [comment]
You're running into a circular dependency here for a similar reason as [this issue](https://github.com/aws/aws-cdk/issues/17786) and [this issue](https://github.com/aws/aws-cdk/issues/22515). Stack B may run code which will cause new policies to be added in Stack A which in turn attempt to reference a resource in Stack B.

These can be tricky to workaround depending on the specific case. If there are no simple escape hatches, then you may be able to introduce a third stack, and/or implement a custom resource which creates and adds the necessary policy once you have the information you need to create the policy.
