### ISSUE TITLE
(aws_sam): Properties are incomplete for CfnFunction.ScheduleEventProperty

### ISSUE THREAD

**Issue by asgrim** [aws/aws-cdk#22138]
### Describe the bug

The `CfnFunction.ScheduleEventProperty` class appears to be missing several properties from [the documentation](https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-property-function-schedule.html):

From the TS, I can see the interface has the following properties:

```
readonly input?: string;
readonly schedule: string;
```

However, the docs state the additional properties should be available:

 * DeadLetterConfig
 * Description
 * Enabled
 * Name
 * RetryPolicy

### Expected Behavior

I expect to be able to set the `name` and `description` properties for a `ScheduleEventProperty`.

### Current Behavior

I get the following error output when running `npx aws-cdk synth`: 

```
#0 7.778 /cdk-src/node_modules/ts-node/src/index.ts:859                                                                                   
#0 7.778     return new TSError(diagnosticText, diagnosticCodes, diagnostics);                                                            
#0 7.778            ^                                                                                                                     
#0 7.779 TSError: ⨯ Unable to compile TypeScript:
#0 7.779 <filenameredacted>(115,17): error TS2322: Type '{ name: string; description: string; schedule: string; input: string; }' is not assignable to type 'S3EventProperty | SNSEventProperty | SQSEventProperty | KinesisEventProperty | DynamoDBEventProperty | ... 7 more ... | IResolvable'.
#0 7.779   Object literal may only specify known properties, and 'name' does not exist in type 'S3EventProperty | SNSEventProperty | SQSEventProperty | KinesisEventProperty | DynamoDBEventProperty | ... 7 more ... | IResolvable'.
#0 7.779 
#0 7.779     at createTSError (/cdk-src/node_modules/ts-node/src/index.ts:859:12)
#0 7.779     at reportTSError (/cdk-src/node_modules/ts-node/src/index.ts:863:19)
#0 7.779     at getOutput (/cdk-src/node_modules/ts-node/src/index.ts:1077:36)
#0 7.779     at Object.compile (/cdk-src/node_modules/ts-node/src/index.ts:1433:41)
#0 7.779     at Module.m._compile (/cdk-src/node_modules/ts-node/src/index.ts:1617:30)
#0 7.779     at Module._extensions..js (node:internal/modules/cjs/loader:1173:10)
#0 7.779     at Object.require.extensions.<computed> [as .ts] (/cdk-src/node_modules/ts-node/src/index.ts:1621:12)
#0 7.779     at Module.load (node:internal/modules/cjs/loader:997:32)
#0 7.779     at Function.Module._load (node:internal/modules/cjs/loader:838:12)
#0 7.779     at Module.require (node:internal/modules/cjs/loader:1021:19) {
#0 7.779   diagnosticCodes: [ 2322 ]
#0 7.779 }
#0 7.985 
#0 7.985 Subprocess exited with error 1
```

### Reproduction Steps

Example function definition:

```js
new cdk.aws_sam.CfnFunction(this, 'TestFunction', {
    functionName: 'testfunction',
    packageType: 'Image',
    imageUri: 'someImageUri',
    role: functionRole.roleArn,
    events: {
        TestEvent: {
            type: 'Schedule',
            properties: {
                name: 'Event name',
                description: 'Event description',
                schedule: 'cron(5 * * * ? *)',
                input: '{"foo":"bar"}',
            },
        },
    },
});
```

### CDK CLI Version

2.40.0 (build 56ba2ab)

### Node.js Version

v18.9.0

### OS

Debian Bullseye

### Language

Typescript

**Comment by peterwoodworth** [comment]
As of version `2.42.0` these properties are in. Upgrade to that version at minimum and you should be good to go!
