### ISSUE TITLE
Error: true does not implement IDependable. Use "Dependable.implement()" to implement

### ISSUE THREAD

**Issue by rym23** [aws/aws-cdk#22195]
### Describe the bug

Upgrade of `aws-cdk-lib` from `2.22.0` to `2.26.0` introduces:

```
      throw new Error(`${instance} does not implement IDependable. Use "Dependable.implement()" to implement`);
            ^
Error: true does not implement IDependable. Use "Dependable.implement()" to implement
    at Function.of (/local/home/rymcg/Volumes/Workspaces/wolf/src/<redacted>/node_modules/constructs/src/dependency.ts:93:13)
    at Node.get dependencies [as dependencies] (/local/home/rymcg/Volumes/Workspaces/wolf/src/<redacted>//node_modules/constructs/src/construct.ts:317:37)
    at findTransitiveDeps (/local/home/rymcg/Volumes/Workspaces/wolf/src/<redacted>//node_modules/aws-cdk-lib/core/lib/private/prepare-app.js:1:1434)
    at Object.prepareApp (/local/home/rymcg/Volumes/Workspaces/wolf/src/<redacted>//node_modules/aws-cdk-lib/core/lib/private/prepare-app.js:1:309)
    at Object.synthesize (/local/home/rymcg/Volumes/Workspaces/wolf/src/<redacted>//node_modules/aws-cdk-lib/core/lib/private/synthesis.js:1:557)
    at App.synth (/local/home/rymcg/Volumes/Workspaces/wolf/src/<redacted>//node_modules/aws-cdk-lib/core/lib/stage.js:1:1866)
    at process.<anonymous> (/local/home/rymcg/Volumes/Workspaces/wolf/src/<redacted>//node_modules/aws-cdk-lib/core/lib/app.js:1:1164)
    at Object.onceWrapper (events.js:520:26)
    at process.emit (events.js:400:28)
    at process.emit (domain.js:475:12)
```

when running `cdk synth`

Running with `2.25.0` works just fine. Upgrading to `2.26.0` breaks it, then attempting to downgrade to `2.25.0` without undoing changes to `package-lock.json` is still broken.

### Expected Behavior

I expected stack synthesis to complete successfully

### Current Behavior

Error is thrown and stack synthesis does not complete successfully

### Reproduction Steps

Upgrade `aws-cdk-lib` from `2.22.0` to `2.26.0`

### CDK CLI Version

2.40.0 (build 56ba2ab)

### Node.js Version

14

### OS

Amazon Linux 2

### Language

Typescript

### Language Version

4.0.5

**Comment by rix0rrr** [comment]
To see where this value is coming from, can you make the following local edit to one of the Node modules on your disk, then synth again?

Edit

```
node_modules/constructs/lib/construct.js
```

And around line 247, add the following line:

```js
    addDependency(...deps) {
        for (const d of deps) {

            Dependable.of(d);   // <-- add this

            this._dependencies.add(d);
        }
    }
```

That should throw when the incorrect value is added (instead of when it is consumed)

**Comment by rym23** [comment]
```
```

**Comment by rym23** [comment]
I found a construct that was set to `true` instead of an `IDependable`, exactly as the stack trace says. Not sure what capabilities TypeScript has in terms of printing variable names along with their values in the stack trace but that would be nice.

**Comment by rix0rrr** [comment]
The issue here was a custom implementation of VPC that returned `internetConnectivityEstablished: true`, whereas that property had to be of type `IDependable`. Because of the way these types are defined, TypeScript unfortunately cannot type check this properly.

**Comment by SumiSastri** [comment]
> The issue here was a custom implementation of VPC that returned `internetConnectivityEstablished: true`, whereas that property had to be of type `IDependable`. Because of the way these types are defined, TypeScript unfortunately cannot type check this properly.

You may want to try 
`Dependable.implement(() => true, {
        dependencyRoots: [],
      } as unknown as Dependable),`

**Comment by van-vothanh** [comment]
@SumiSastri where about would you add that line, assuming you're writing a custom implementation of `ec2.IVpc`?
