### ISSUE TITLE
sample-app template: synth failing after removing bin

### ISSUE THREAD

**Issue by sravimohan** [aws/aws-cdk#22319]
### Describe the bug

After creating the sample-app, the synth work fine the first time. But fails after the bin folder is deleted.  

### Expected Behavior
tsc compiles successfully and the bin folder is created if not present.

### Current Behavior
the sample-app template fails if the bin folder is deleted.  Also recreating the bin folder does not seem to help.

### Reproduction Steps

```
$ cdk --version
2.44.0 (build bf32cb1)

$ mkdir sample-cdk-app

$ cd sample-cdk-app

$ cdk init sample-app --language=typescript

$ cdk synth
<success>

$ rm -rf bin

$ cdk synth
node:internal/modules/cjs/loader:959
  throw err;
  ^

Error: Cannot find module './sample-cdk-app.ts'
Require stack:
- /home/ravi/source/sample-cdk-app/bin/imaginaryUncacheableRequireResolveScript
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:956:15)
    at Function.resolve (node:internal/modules/cjs/helpers:108:19)
    at requireResolveNonCached (/home/ravi/source/sample-cdk-app/node_modules/ts-node/dist/bin.js:549:16)
    at getProjectSearchDir (/home/ravi/source/sample-cdk-app/node_modules/ts-node/dist/bin.js:519:40)
    at phase3 (/home/ravi/source/sample-cdk-app/node_modules/ts-node/dist/bin.js:267:27)
    at bootstrap (/home/ravi/source/sample-cdk-app/node_modules/ts-node/dist/bin.js:47:30)
    at main (/home/ravi/source/sample-cdk-app/node_modules/ts-node/dist/bin.js:33:12)
    at Object.<anonymous> (/home/ravi/source/sample-cdk-app/node_modules/ts-node/dist/bin.js:579:5)
    at Module._compile (node:internal/modules/cjs/loader:1126:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1180:10) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/home/ravi/source/sample-cdk-app/bin/imaginaryUncacheableRequireResolveScript'
  ]
}
```

### CDK CLI Version

2.44.0 (build bf32cb1)

### Node.js Version

v16.17.0

### OS

Ubuntu 20.04.4 LTS

### Language

Typescript

### Language Version

3.9.7

### Other information

I am seeing the same behaviour even with the cdk init app template.

**Comment by sravimohan** [comment]
After some troubleshooting, I realised the /bin folder needs to be checked into the repo.
