### ISSUE TITLE
cli: hotswap deploy fails on multiple CfnEvaluationException

### ISSUE THREAD

**Issue by tmokmss** [aws/aws-cdk#22323]
### Describe the bug

When we try to hotswap-deploy but there multiple changes that throw `CfnEvaluationException`, the deployment fails with an error. It seems caused by inappropriate handling of promises.

### Expected Behavior

Deployment successes without error.

### Current Behavior

We get the following error on deployment.

```
/Users/cdk/node_modules/aws-cdk/lib/api/evaluate-cloudformation-template.ts:294
      throw new CfnEvaluationException(`We don't support attributes of the '${resource.ResourceType}' resource. This is a CDK limitation. ` +
            ^
Error: We don't support attributes of the 'AWS::CloudFront::Distribution' resource. This is a CDK limitation. Please report it at https://github.com/aws/aws-cdk/issues/new/choose
    at EvaluateCloudFormationTemplate.formatResourceAttribute (/Users/cdk/node_modules/aws-cdk/lib/api/evaluate-cloudformation-template.ts:294:13)
    at EvaluateCloudFormationTemplate.findGetAttTarget (/Users/cdk/node_modules/aws-cdk/lib/api/evaluate-cloudformation-template.ts:281:17)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at CfnIntrinsics.Fn::GetAtt (/Users/cdk/node_modules/aws-cdk/lib/api/evaluate-cloudformation-template.ts:174:27)
    at async Promise.all (index 1)
    at CfnIntrinsics.Fn::Join (/Users/cdk/node_modules/aws-cdk/lib/api/evaluate-cloudformation-template.ts:149:31)
    at EvaluateCloudFormationTemplate.evaluateCfnExpression (/Users/cdk/node_modules/aws-cdk/lib/api/evaluate-cloudformation-template.ts:215:22)
    at EvaluateCloudFormationTemplate.evaluateCfnExpression (/Users/cdk/node_modules/aws-cdk/lib/api/evaluate-cloudformation-template.ts:215:22)
    at isLambdaFunctionCodeOnlyChange (/Users/cdk/node_modules/aws-cdk/lib/api/hotswap/lambda-functions.ts:185:23)
    at isHotswappableLambdaFunctionChange (/Users/cdk/node_modules/aws-cdk/lib/api/hotswap/lambda-functions.ts:34:28)
```

### Reproduction Steps

1. Deploy the below stack
2. change `literal: '1'` to `literal: '2'`
3. run `npx cdk deploy --hotswap` and you get the error above

```ts
import * as cdk from 'aws-cdk-lib';
import { Construct } from 'constructs';
import { Code, Function, Runtime } from 'aws-cdk-lib/aws-lambda';
import { BlockPublicAccess, Bucket } from 'aws-cdk-lib/aws-s3';
import { RemovalPolicy } from 'aws-cdk-lib';
import { Distribution } from 'aws-cdk-lib/aws-cloudfront';
import { S3Origin } from 'aws-cdk-lib/aws-cloudfront-origins';

export class LambdaHotswapStack extends cdk.Stack {
  constructor(scope: Construct, id: string, props?: cdk.StackProps) {
    super(scope, id, props);

    const bucket = new Bucket(this, 'Bucket', {
      blockPublicAccess: BlockPublicAccess.BLOCK_ALL,
      removalPolicy: RemovalPolicy.DESTROY,
    });

    const distribution = new Distribution(this, 'Distribution', {
      defaultBehavior: {
        origin: new S3Origin(bucket),
      },
    });

    const environment = {
      literal: '1',
      // any token that is not supported by evaluate-cloudformation-template.ts
      token: distribution.domainName,
    };

    // this will cause a CfnEvaluationException
    new Function(this, 'Function1', {
      code: Code.fromInline('exports.handler=()=>{}'),
      runtime: Runtime.NODEJS_16_X,
      handler: 'index.handler',
      environment,
    });

    // one more function for a secondary CfnEvaluationException
    new Function(this, 'Function2', {
      code: Code.fromInline('exports.handler=()=>{}'),
      runtime: Runtime.NODEJS_16_X,
      handler: 'index.handler',
      environment,
    });
  }
}
```

### Possible Solution

`CfnEvaluationException` is usually caught here. However If there are multiple ones thrown, the first one is only caught but others do not seem to be handled. I'm not quite sure how it can be generally solved - maybe using `Promise.allSettled` instead of `Promise.all`? That will need a lot of refactor though... I'll investigate about this more later but please let me know if CDK team has already come up with a solution for this kind of issue.

https://github.com/aws/aws-cdk/blob/31012c5e4a3a944796e563fcda8b8d4cff7b949e/packages/aws-cdk/lib/api/deploy-stack.ts#L294-L305

### CDK CLI Version

2.44.0

### Framework Version

2.44.0

### Node.js Version

16.13.1

### OS

macOS

### Language

Typescript

**Comment by tmokmss** [comment]
The below code is causing [unhandled rejection](https://www.geeksforgeeks.org/node-js-process-unhandledpromiserejection-event/). We must `await` promises as soon as we created a promise. If a promise that is not awaited throws an exception, it results in unhandled rejection and the process is terminated (node>v15).
https://github.com/aws/aws-cdk/blob/31012c5e4a3a944796e563fcda8b8d4cff7b949e/packages/aws-cdk/lib/api/hotswap-deployments.ts#L100-L107
