### ISSUE TITLE
(CDK Hotswap Deployment): (Deployment failed when updating asset of a lambda invoked by a statemachine)

### ISSUE THREAD

**Issue by fangp** [aws/aws-cdk#22347]
### Describe the bug

I'm using CDKv2 and I have created a StateMachine with a single LambdaInvoke task like the following. The initial deployment completed successfully, but when I updated code in Lambda, the `hotswap` deployment will fail.

```
    const lambdaInvokeTask = new LambdaInvoke(this, 'RunLambda', {
      lambdaFunction: myLambda,
    });

    const myStateMachine = new StateMachine(this, 'MyStateMachine', {
      definition: lambdaInvokeTask,
      stateMachineName: 'MyStateMachine',
    });
```

### Expected Behavior

Deployment succeeded

### Current Behavior

Got an error like the following
```
xxxx: building assets...

[0%] start: Building xxxx
[100%] success: Built xxxx

xxxx: assets built

xxxx: deploying...
[0%] start: Publishing xxxx
[100%] success: Published xxxx
(node:20364) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'newValue' of undefined
    at isStateMachineDefinitionOnlyChange (xxxx/node_modules/aws-cdk/lib/api/hotswap/stepfunctions-state-machines.ts:47:85)
    at isHotswappableStateMachineChange (xxxx/node_modules/aws-cdk/lib/api/hotswap/stepfunctions-state-machines.ts:8:46)
    at findAllHotswappableChanges (xxxx/node_modules/aws-cdk/lib/api/hotswap-deployments.ts:102:9)
    at tryHotswapDeployment (xxxx/node_modules/aws-cdk/lib/api/hotswap-deployments.ts:50:37)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at deployStack (xxxx/node_modules/aws-cdk/lib/api/deploy-stack.ts:274:39)
    at deployStack2 (xxxx/node_modules/aws-cdk/lib/cdk-toolkit.ts:240:24)
    at xxxx/node_modules/aws-cdk/lib/deploy.ts:39:11
    at run (xxxx/node_modules/p-queue/dist/index.js:163:29)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:20364) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 4)
(node:20364) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

### Reproduction Steps

* Build a StateMachine with LambdaInvoke task, deploy the stack. The deployment should pass.
* Change the code/asset of lambda or the lambda handler, deploy the stack. The deployment should fail with reported error.

### CDK CLI Version

2.38.0

### Node.js Version

v14.20.1

### OS

Linux

### Language

Typescript

**Comment by peterwoodworth** [comment]
I wasn't able to reproduce this using the code you pasted. Maybe this bug has been resolved since this reported?
