### ISSUE TITLE
(Amazon.CDK.Lib): .NET- JsonSerializationException - Amazon.JSII.JsonModel.Api.Response.ErrorResponseName

### ISSUE THREAD

**Issue by Chompetto** [aws/aws-cdk#22369]
### Describe the bug

When upgrading packages I noticed that instead of returning a "normal error" akin to: 
  ` Amazon.JSII.Runtime.JsiiException: "Cannot find file at foo/bar"`
It will instead return a generic serialization error for every exception that occurs.
```
Unhandled exception. Newtonsoft.Json.JsonSerializationException: Error converting value "Error" to type 'Amazon.JSII.JsonModel.Api.Response.ErrorResponseName'. Path 'name'.
 ---> System.ArgumentException: Requested value 'Error' was not found." 
```

### Expected Behavior

Returns a useful error message like previously.
` Amazon.JSII.Runtime.JsiiException: "Cannot find file at foo/bar"`

### Current Behavior

Unhandled exception. Newtonsoft.Json.JsonSerializationException: Error converting value "Error" to type 'Amazon.JSII.JsonModel.Api.Response.ErrorResponseName'. Path 'name'.
 ---> System.ArgumentException: Requested value 'Error' was not found.
   at Newtonsoft.Json.Utilities.EnumUtils.ParseEnum(Type enumType, NamingStrategy namingStrategy, String value, Boolean disallowNumber)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.EnsureType(JsonReader reader, Object value, CultureInfo culture, JsonContract contract, Type targetType)
   --- End of inner exception stack trace ---
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.EnsureType(JsonReader reader, Object value, CultureInfo culture, JsonContract contract, Type targetType)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.ResolvePropertyAndCreatorValues(JsonObjectContract contract, J   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObjectUsingCreatorWithParameters(JsonReader reader, JsonObjectContract contract, JsonProperty containerProperty, ObjectConstructor`1 creator, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract    at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.Linq.JToken.ToObject(Type objectType, JsonSerializer jsonSerializer)
   at Newtonsoft.Json.Linq.JToken.ToObject(Type objectType)
   at Newtonsoft.Json.Linq.JToken.ToObject[T]()
   at Amazon.JSII.Runtime.Services.Client.TryDeserialize[TResponse](String responseJson)
   at Amazon.JSII.Runtime.Services.Client.ReceiveResponse[TResponse]()
   at Amazon.JSII.Runtime.Services.Client.Create(CreateRequest request)
   at Amazon.JSII.Runtime.Services.Client.Create(String fullyQualifiedName, Object[] arguments, Override[] overrides, String[] interfaces)
   at Amazon.JSII.Runtime.Deputy.DeputyBase..ctor(DeputyProps props)
   at Constructs.Construct..ctor(DeputyProps props)
   at Amazon.CDK.AWS.Ecr.Assets.DockerImageAsset..ctor(Construct scope, String id, IDockerImageAssetProps props)

### Reproduction Steps

Working version(s) I am using.
- Amazon.CDK.Lib" Version="2.41.0"
- AWSSDK.Core" Version="3.7.13"

When upgrading to "latest" it will cause the serialization exception.
- Amazon.CDK.Lib" Version="2.44.0"
- AWSSDK.Core" Version="3.7.16"

Creating an invalid directory for DockerImageAsset will cause this exception (but any invalid configuration will do)
new Amazon.CDK.AWS.Ecr.Assets.DockerImageAsset(this, "DockerImage", new Amazon.CDK.AWS.Ecr.Assets.DockerImageAssetProps
            {
                Directory = ""
            });

### Possible Solution

I am guessing a serialization property name or config was updated between these versions listed that is causing an exception when serializing the error response.

### CDK CLI Version

2.44.0 (build bf32cb1)

### Node.js Version

v16.14.2

### OS

Window/Unix

### Language

.NET

### Language Version

6.0

**Comment by gbanister** [comment]
I'm experiencing the same error with Amazon.CDK.Lib" Version="2.45.0" and AWSSDK.Core" Version="3.7.13.16"

**Comment by ianpowell2017** [comment]
I'm having the exact same problem.  The error message is useless. Documentation is sparse, to say the least.

**Comment by BradKnowles** [comment]
I encountered the same thing while using 2.49.

**Comment by allanwright** [comment]
Confirming issue still exists in 2.50. Downgrading Amazon.CDK.Lib to 2.41.0, as mentioned above, restores meaningful error messages.

**Comment by dsdavis4** [comment]
Confirmed this is still an issue in 2.51.0 as well. This is becoming a blocker as we need to use feature introduced post version 2.45.0

Is the cdk team aware of the issue?

**Comment by MrArnoldPalmer** [comment]
Hey there, we recently made changes to error messages in JSII to add additional information in non-TS languages. I'll take a look at this and try to figure out why it's breaking in Dotnet.

**Comment by thorbenw** [comment]
A possible cause had been mentioned [here](https://github.com/aws/aws-cdk/issues/22574#issuecomment-1286764371), but unfortunately that issue has been closed without further investigations due to the root error cause being solved.

This bug currently prevents me from continuing my project. Has anyone figured out a workaround to get the _actual_ error message anyway?

**Comment by MrArnoldPalmer** [comment]
Fix incoming in JSII https://github.com/aws/jsii/pull/3855
