### ISSUE TITLE
aws-cdk-lib: Error: There are no 'Public' subnet groups in this VPC. Available types

### ISSUE THREAD

**Issue by ilanuk** [aws/aws-cdk#22572]
### Describe the bug

aws-cdk-lib: Error: There are no 'Public' subnet groups in this VPC. Available types when I issue below command ( I am in Macbook Pro m1)
`cdk bootstrap aws://XXXXX/us-west-2 `

### Expected Behavior

I should not be getting this error.  I should be getting bootstrapping successful

### Current Behavior

command failing with error  :
`cdk bootstrap aws://XXXXX/us-west-2 `

**Error:**
```
`Error: There are no 'Public' subnet groups in this VPC. Available types:
    at ImportedVpc.selectSubnetObjectsByType (/Users/exampleuser/projects/CDK/MyEcsConstruct/node_modules/aws-cdk-lib/aws-ec2/lib/vpc.js:1:4975)
    at ImportedVpc.selectSubnetObjects (/Users/exampleuser/projects/CDK/MyEcsConstruct/node_modules/aws-cdk-lib/aws-ec2/lib/vpc.js:1:3701)
    at ImportedVpc.selectSubnets (/Users/exampleuser/projects/CDK/MyEcsConstruct/node_modules/aws-cdk-lib/aws-ec2/lib/vpc.js:1:1431)
    at new BaseLoadBalancer (/Users/exampleuser/projects/CDK/MyEcsConstruct/node_modules/aws-cdk-lib/aws-elasticloadbalancingv2/lib/shared/base-load-balancer.js:1:1230)
    at new ApplicationLoadBalancer (/Users/exampleuser/projects/CDK/MyEcsConstruct/node_modules/aws-cdk-lib/aws-elasticloadbalancingv2/lib/alb/application-load-balancer.js:1:903)
    at new ApplicationLoadBalancedServiceBase (/Users/exampleuser/projects/CDK/MyEcsConstruct/node_modules/aws-cdk-lib/aws-ecs-patterns/lib/base/application-load-balanced-service-base.js:1:2508)
    at new ApplicationLoadBalancedFargateService (/Users/exampleuser/projects/CDK/MyEcsConstruct/node_modules/aws-cdk-lib/aws-ecs-patterns/lib/fargate/application-load-balanced-fargate-service.js:1:601)
    at new MyEcsConstructStack (/Users/exampleuser/projects/CDK/MyEcsConstruct/lib/my_ecs_construct-stack.ts:33:5)
    at Object.<anonymous> (/Users/exampleuser/projects/CDK/MyEcsConstruct/bin/my_ecs_construct.ts:7:1)
    at Module._compile (node:internal/modules/cjs/loader:1159:14)

Subprocess exited with error 1   `
```

My package.json versions are as below

```
"devDependencies": {
    "@types/jest": "^27.5.2",
    "@types/node": "10.17.27",
    "@types/prettier": "2.6.0",
    "jest": "^27.5.1",
    "ts-jest": "^27.1.4",
    "aws-cdk": "2.46.0",
    "ts-node": "^10.9.1",
    "typescript": "~3.9.7"
  },
  "dependencies": {
    "aws-cdk-lib": "2.46.0",
    "constructs": "^10.0.0",
    "source-map-support": "^0.5.21"
  }
```

### Reproduction Steps

Issue below command in macbook pro m1 
`cdk bootstrap aws://XXXXX/us-west-2 `

### CDK CLI Version

2.46.0 (build 5a0595e)

### Node.js Version

v18.11.0

### OS

macOS   Version:	12.3.1 BuildVersion:	21E258

### Language

Typescript

### Language Version

Version 4.8.4

**Comment by gshpychka** [comment]
This is caused by your CDK code. `cdk bootstrap` does `cdk synth`, and that's what producing the error. Run `cdk bootstrap aws://...` in a different directory and you won't see the error.

**Comment by ilanuk** [comment]
Yes. Thanks for helping out.  I am closing this
