### ISSUE TITLE
constructs.dev published package cannot find asset

### ISSUE THREAD

**Issue by rantoniuk** [aws/aws-cdk#22603]
### Describe the bug

I have created a construct library package with [projen](https://projen.io/awscdk-construct.html) and published it in npm repository and [constructs.dev](https://constructs.dev/packages/cloudwatch-retention-setter/v/0.0.0?lang=typescript).
The build and tests have passed, but when trying to consume the package in the target stack, I'm getting "assets not found" for the Lambda.

```
Error: Cannot find asset at cloudwatch/lambda
    at new AssetStaging (loudwatch/node_modules/aws-cdk-lib/core/lib/asset-staging.js:1:1072)
    at new Asset (cloudwatch/node_modules/aws-cdk-lib/aws-s3-assets/lib/asset.js:1:736)
    at AssetCode.bind (cloudwatch/node_modules/aws-cdk-lib/aws-lambda/lib/code.js:1:4628)
    at new Function (cloudwatch/node_modules/aws-cdk-lib/aws-lambda/lib/function.js:1:2803)
    at new CloudwatchRetentionSetter (cloudwatch/node_modules/cloudwatch-retention-setter/src/index.ts:20:20)
    at new CloudwatchStack (cloudwatch/lib/cloudwatch-stack.ts:10:9)
    at Object.<anonymous> (cloudwatch/bin/cloudwatch.ts:7:1)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Module.m._compile (cloudwatch/node_modules/ts-node/src/index.ts:1618:23)
    at Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
```

Of course, cloudwatch/lambda does not exist, because that should point to node_modules/cloudwatch-retention-setter/lambda which does exist. The asset is referenced [here](https://github.com/rantoniuk/cloudwatch-retention-setter/blob/main/src/index.ts#L22)

### Expected Behavior

Asset is found during deployment or the jest tests do not pass.

### Current Behavior

The tests pass but only when the package is consumed the asset is not found.

### Reproduction Steps

Just use that package in a plain new cdk TS app.

### CDK CLI Version

2.38.1 (build a5ced21)

### Node.js Version

14.9.3

### OS

MacOS

### Language

Typescript

**Comment by rantoniuk** [comment]
self-resolved.
