### ISSUE TITLE
aws_ec2: grant_attach_volume_by_resource_tag not working

### ISSUE THREAD

**Issue by shcherbak** [aws/aws-cdk#22711]
### Describe the bug

starting from release 2.48 no longer works python method grant_attach_volume_by_resource_tag
```
attach_grant = volume.grant_attach_volume_by_resource_tag(instance.grant_principal, [instance])
```
described in documentation:
https://docs.aws.amazon.com/cdk/api/v2/python/aws_cdk.aws_ec2/README.html#instances-attaching-volumes-to-themselves
version 2.47 works fine

the error is 
```
<class 'aws_cdk.aws_ec2.Instance'>
Traceback (most recent call last):
  File "/home/work/terraform/cdk/eks/app.py", line 84, in <module>
    test_infra_stack = InfraStack(
  File "/home/work/terraform/cdk/eks/.venv/lib/python3.9/site-packages/jsii/_runtime.py", line 109, in __call__
    inst = super().__call__(*args, **kwargs)
  File "/home/work/terraform/cdk/eks/stacks/infra_stack.py", line 71, in __init__
    Ec2CassandraConstruct(
  File "/home/work/terraform/cdk/eks/.venv/lib/python3.9/site-packages/jsii/_runtime.py", line 109, in __call__
    inst = super().__call__(*args, **kwargs)
  File "/home/work/terraform/cdk/eks/stacks/constructs_l2/ec2_construct.py", line 79, in __init__
    self.grant_attach_volumes_to_instances()
  File "/home/work/terraform/cdk/eks/stacks/constructs_l2/ec2_construct.py", line 157, in grant_attach_volumes_to_instances
    self.volumes[v].grant_attach_volume_by_resource_tag(
  File "/home/work/terraform/cdk/eks/.venv/lib/python3.9/site-packages/aws_cdk/aws_ec2/__init__.py", line 76426, in grant_attach_volume_by_resource_tag
    constructs: typing.Sequence[constructs.Construct],
AttributeError: 'Instance' object has no attribute 'Construct'

```

### Expected Behavior

creating grant to attach volume for instance by tag

### Current Behavior

runtime error 

### Reproduction Steps

create instance ec2.IInstance
create volume ec2.IVolume
try to create grant with grant_attach_volume_by_resource_tag

### CDK CLI Version

2.49.0, 2.48.0

### Node.js Version

v16.18.0

### OS

linux debian 11

### Language

Python

### Language Version

Python (3.9.2)

**Comment by peterwoodworth** [comment]
Thanks for reporting this bug @shcherbak, I can confirm it's been fixed as of `2.49.1`. Please upgrade to this version and you should be good, thanks!

**Comment by shcherbak** [comment]
@peterwoodworth super, thank you so much, nicely done

**Comment by shcherbak** [comment]
how can we feopen this? the same regression on 2.51 release
