### ISSUE TITLE
CLI: SignatureDoesNotMatch error when running CDK commands

### ISSUE THREAD

**Issue by jayg-hive** [aws/aws-cdk#22759]
### Describe the bug

When running `cdk deploy` I'm getting an error around `SignatureDoesNotMatch`. It also stalls on other commands such as `cdk destroy`. Commands like `cdk synth` still work, it only fails on commands where it needs to do remote stuff.

### Expected Behavior

The command would execute successfully with no errors.

### Current Behavior

Getting the following error:
```
❯ cdk bootstrap --profile <profileName>
 ⏳  Bootstrapping environment aws://<AWSID>/us-west-1...
 ❌  Environment aws://<AWSID>/us-west-1 failed bootstrapping: SignatureDoesNotMatch: Signature expired: 20221103T080139Z is now earlier than 20221103T085247Z (20221103T090747Z - 15 min.)
    at Request.extractError (/home/jayg-hive/.local/share/pnpm/global/5/.pnpm/aws-cdk@2.49.1/node_modules/aws-sdk/lib/protocol/query.js:50:29)
    at Request.callListeners (/home/jayg-hive/.local/share/pnpm/global/5/.pnpm/aws-cdk@2.49.1/node_modules/aws-sdk/lib/sequential_executor.js:106:20)
    at Request.emit (/home/jayg-hive/.local/share/pnpm/global/5/.pnpm/aws-cdk@2.49.1/node_modules/aws-sdk/lib/sequential_executor.js:78:10)
    at Request.emit (/home/jayg-hive/.local/share/pnpm/global/5/.pnpm/aws-cdk@2.49.1/node_modules/aws-sdk/lib/request.js:686:14)
    at Request.transition (/home/jayg-hive/.local/share/pnpm/global/5/.pnpm/aws-cdk@2.49.1/node_modules/aws-sdk/lib/request.js:22:10)
    at AcceptorStateMachine.runTo (/home/jayg-hive/.local/share/pnpm/global/5/.pnpm/aws-cdk@2.49.1/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at /home/jayg-hive/.local/share/pnpm/global/5/.pnpm/aws-cdk@2.49.1/node_modules/aws-sdk/lib/state_machine.js:26:10
    at Request.<anonymous> (/home/jayg-hive/.local/share/pnpm/global/5/.pnpm/aws-cdk@2.49.1/node_modules/aws-sdk/lib/request.js:38:9)
    at Request.<anonymous> (/home/jayg-hive/.local/share/pnpm/global/5/.pnpm/aws-cdk@2.49.1/node_modules/aws-sdk/lib/request.js:688:12)
    at Request.callListeners (/home/jayg-hive/.local/share/pnpm/global/5/.pnpm/aws-cdk@2.49.1/node_modules/aws-sdk/lib/sequential_executor.js:116:18) {
  code: 'SignatureDoesNotMatch',
  time: 2022-11-03T08:01:39.994Z,
  requestId: 'e11a079b-4aca-4bdb-ae49-c4d71d3f26a9',
  statusCode: 403,
  retryable: true
}

Signature expired: 20221103T080139Z is now earlier than 20221103T085247Z (20221103T090747Z - 15 min.)
```

### Reproduction Steps

Not sure if it's code-related or otherwise at the moment. In some cases the command works without errors. I've tried it on both v2.49.1 and v2.50.0

### CDK CLI Version

2.49.1 (build be5fcf4)

### Node.js Version

v16.14.0

### OS

WSL on Windows 11

### Language

Typescript

### Language Version

4.8.4

**Comment by peterwoodworth** [comment]
I don't think this is a CDK error - It looks like it [may be due to your environment's clock](https://stackoverflow.com/questions/44017410/signature-expired-is-now-earlier-than-error-invalidsignatureexception)

**Comment by jayg-hive** [comment]
Many thanks, will give it a shot sometime later today. 🙌 I'm on the Debian 12 container so the command might be slightly different than the SO answer.

**Comment by jayg-hive** [comment]
Looks to be working again. 😌 Will keep monitoring though for that env time sync issue.

**Comment by deanbantleman** [comment]
I know this issue is closed but I believe the issue is related to time synchronization issues. For me specifically I use Windows Subsysem for Linux (WSL) and I noticed that after my laptop went into standby the clock was out of sync between WSL and my Windows system. To resolve this use the following command:

`sudo hwclock -s`

You will notice that your time in WSL now changes to the same time as the clock in your Windows operating system.

You can test your credentials with:

`aws sts get-caller-identity`

I hope this helps someone else.

Dean
