### ISSUE TITLE
@aws-cdk/aws-cognito-identitypool-alpha:  is not a valid RoleMapping ProviderName or is not a configured provider. 

### ISSUE THREAD

**Issue by sheiy** [aws/aws-cdk#22951]
### Describe the bug

```TypeScript
 // IdentityPool;
    const identityPool = new IdentityPool(this, 'TestIdentityPool', {
      identityPoolName: 'testIdentityPool',
      authenticatedRole: userRole,
      allowUnauthenticatedIdentities: false,
      authenticationProviders: {
        userPools: [new UserPoolAuthenticationProvider({ userPool })],
      },
      roleMappings: [
        {
          mappingKey: 'userpool',
          providerUrl: IdentityPoolProviderUrl.userPool(
            userPool.userPoolProviderUrl,
          ),
          useToken: true,
          resolveAmbiguousRoles: false,
        },
      ],
    });
```
I define an IdentityPool and a userPool but when deploy the cdk stack I got an error
```
 ❌ Deployment failed: Error: Stack Deployments Failed: Error: The stack named CognitoCdkStack failed to deploy: UPDATE_ROLLBACK_COMPLETE: (https://cognito-idp.us-west-1.amazonaws.com/us-west-1_rRwJgkwYX) is not a valid RoleMapping ProviderName or is not a configured provider. (Service: AmazonCognitoIdentity; Status Code: 400; Error Code: InvalidParameterException; Request ID: 12edd7a6-b0e2-4a5b-b8af-30e8abf16942; Proxy: null)
    at deployStacks (/Volumes/data/code/aws/youmoo-hello-ckd/node_modules/aws-cdk/lib/deploy.ts:61:11)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at CdkToolkit.deploy (/Volumes/data/code/aws/youmoo-hello-ckd/node_modules/aws-cdk/lib/cdk-toolkit.ts:315:7)
    at initCommandLine (/Volumes/data/code/aws/youmoo-hello-ckd/node_modules/aws-cdk/lib/cli.ts:358:12)

Stack Deployments Failed: Error: The stack named CognitoCdkStack failed to deploy: UPDATE_ROLLBACK_COMPLETE: (https://cognito-idp.us-west-1.amazonaws.com/us-west-1_rRwJgkwYX) is not a valid RoleMapping ProviderName or is not a configured provider. (Service: AmazonCognitoIdentity; Status Code: 400; Error Code: InvalidParameterException; Request ID: 12edd7a6-b0e2-4a5b-b8af-30e8abf16942; Proxy: null)
error Command failed with exit code 1.

```

### Expected Behavior

deploy success

### Current Behavior

```
CognitoCdkStack: creating CloudFormation changeset...
5:17:38 PM | CREATE_FAILED        | AWS::Cognito::IdentityPoolRoleAttachment | TestIdentityPoolDe...Attachment0C63C75F
(https://cognito-idp.us-west-1.amazonaws.com/us-west-1_rRwJgkwYX) is not a valid RoleMapping ProviderName or is not a configured provider. (Service: AmazonCognitoIdentity; Status Code: 400; Error Code: Inval
idParameterException; Request ID: 12edd7a6-b0e2-4a5b-b8af-30e8abf16942; Proxy: null)


 ❌  CognitoCdkStack failed: Error: The stack named CognitoCdkStack failed to deploy: UPDATE_ROLLBACK_COMPLETE: (https://cognito-idp.us-west-1.amazonaws.com/us-west-1_rRwJgkwYX) is not a valid RoleMapping ProviderName or is not a configured provider. (Service: AmazonCognitoIdentity; Status Code: 400; Error Code: InvalidParameterException; Request ID: 12edd7a6-b0e2-4a5b-b8af-30e8abf16942; Proxy: null)
    at FullCloudFormationDeployment.monitorDeployment (/Volumes/data/code/aws/youmoo-hello-ckd/node_modules/aws-cdk/lib/api/deploy-stack.ts:505:13)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at deployStack2 (/Volumes/data/code/aws/youmoo-hello-ckd/node_modules/aws-cdk/lib/cdk-toolkit.ts:241:24)
    at /Volumes/data/code/aws/youmoo-hello-ckd/node_modules/aws-cdk/lib/deploy.ts:39:11
    at run (/Volumes/data/code/aws/youmoo-hello-ckd/node_modules/p-queue/dist/index.js:163:29)

 ❌ Deployment failed: Error: Stack Deployments Failed: Error: The stack named CognitoCdkStack failed to deploy: UPDATE_ROLLBACK_COMPLETE: (https://cognito-idp.us-west-1.amazonaws.com/us-west-1_rRwJgkwYX) is not a valid RoleMapping ProviderName or is not a configured provider. (Service: AmazonCognitoIdentity; Status Code: 400; Error Code: InvalidParameterException; Request ID: 12edd7a6-b0e2-4a5b-b8af-30e8abf16942; Proxy: null)
    at deployStacks (/Volumes/data/code/aws/youmoo-hello-ckd/node_modules/aws-cdk/lib/deploy.ts:61:11)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at CdkToolkit.deploy (/Volumes/data/code/aws/youmoo-hello-ckd/node_modules/aws-cdk/lib/cdk-toolkit.ts:315:7)
    at initCommandLine (/Volumes/data/code/aws/youmoo-hello-ckd/node_modules/aws-cdk/lib/cli.ts:358:12)

Stack Deployments Failed: Error: The stack named CognitoCdkStack failed to deploy: UPDATE_ROLLBACK_COMPLETE: (https://cognito-idp.us-west-1.amazonaws.com/us-west-1_rRwJgkwYX) is not a valid RoleMapping ProviderName or is not a configured provider. (Service: AmazonCognitoIdentity; Status Code: 400; Error Code: InvalidParameterException; Request ID: 12edd7a6-b0e2-4a5b-b8af-30e8abf16942; Proxy: null)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

```

### Reproduction Steps

All stack code is here. Deploy this will got error.
```TypeScript
export class CognitoCdkStack extends cdk.Stack {
  constructor(scope: Construct, id: string, props?: cdk.StackProps) {
    super(scope, id, props);
    // Lambda Processor
    const adminFunction = new lambda.Function(
      this,
      'adminCognitoHelloHandler',
      {
        runtime: lambda.Runtime.NODEJS_16_X,
        code: lambda.Code.fromAsset('lambda'),
        handler: 'hello-cognito-admin.handler',
      },
    );
    const userFunction = new lambda.Function(this, 'userCognitoHelloHandler', {
      runtime: lambda.Runtime.NODEJS_16_X,
      code: lambda.Code.fromAsset('lambda'),
      handler: 'hello-cognito.handler',
    });

    //API Spec
    const api = new gateway.RestApi(this, 'CognitoApi', {
      description: 'example api gateway',
      deployOptions: {
        stageName: 'dev',
      },
      // 👇 enable CORS
      defaultCorsPreflightOptions: {
        allowHeaders: [
          'Content-Type',
          'X-Amz-Date',
          'Authorization',
          'X-Api-Key',
        ],
        allowMethods: ['OPTIONS', 'GET', 'POST', 'PUT', 'PATCH', 'DELETE'],
        allowCredentials: true,
        allowOrigins: ['*'],
      },
    });

    // 👇 create an Output for the API URL
    // new cdk.CfnOutput(this, "CognitoApiUrl", {value: api.url});

    const signUpTrigger = new NodejsFunction(this, 'signUpTrigger', {
      runtime: lambda.Runtime.NODEJS_16_X,
      handler: 'onSignUp',
      entry: 'lambda/user-pool-trigger.ts',
      depsLockFilePath: 'yarn.lock',
    });

    const lambdaARole = new iam.Role(this, 'LambdaDynamoDBRole', {
      assumedBy: new iam.ServicePrincipal('lambda.amazonaws.com'),
    });

    lambdaARole.addManagedPolicy(
      iam.ManagedPolicy.fromAwsManagedPolicyName('AmazonDynamoDBFullAccess'),
    );

    const confirmTrigger = new NodejsFunction(this, 'confirmTrigger', {
      role: lambdaARole,
      runtime: lambda.Runtime.NODEJS_16_X,
      handler: 'onConfirmed',
      entry: 'lambda/user-pool-trigger.ts',
      depsLockFilePath: 'yarn.lock',
    });
    // 管理员角色
    const adminRole = new iam.Role(this, 'admin', {
      assumedBy: new iam.ServicePrincipal('lambda.amazonaws.com'),
    });
    adminRole.addToPolicy(
      new iam.PolicyStatement({
        effect: iam.Effect.ALLOW,
        actions: ['lambda:InvokeFunction'],
        resources: ['*'], //管理员可以执行所有lambda
      }),
    );
    // 普通用户角色
    const userRole = new iam.Role(this, 'user', {
      assumedBy: new iam.ServicePrincipal('lambda.amazonaws.com'),
    });
    userRole.addToPolicy(
      new iam.PolicyStatement({
        effect: iam.Effect.ALLOW,
        actions: ['lambda:InvokeFunction'],
        resources: [userFunction.functionArn], //普通用户可以执行这个方法
      }),
    );

    // UserPool
    const userPool = new cognito.UserPool(this, 'cognitoUserPool', {
      userPoolName: 'testUserPool',
      signInCaseSensitive: true, // case insensitive is preferred in most situations
      selfSignUpEnabled: true,
      lambdaTriggers: {
        preSignUp: signUpTrigger,
        postConfirmation: confirmTrigger,
      },
    });
    const adminUserPoolGroup = new cognito.CfnUserPoolGroup(
      this,
      'adminUserGroup',
      {
        userPoolId: userPool.userPoolId,
        // the properties below are optional
        description: 'admin group',
        groupName: 'adminGroup',
        precedence: 100,
        roleArn: adminRole.roleArn,
      },
    );
    const normalUserPoolGroup = new cognito.CfnUserPoolGroup(
      this,
      'normalUserGroup',
      {
        userPoolId: userPool.userPoolId,
        // the properties below are optional
        description: 'normal user group',
        groupName: 'normalUserGroup',
        precedence: 100,
        roleArn: userRole.roleArn,
      },
    );

    // Authorizer
    const authorizer = new gateway.CfnAuthorizer(this, 'cfnAuth', {
      restApiId: api.restApiId,
      name: 'HelloWorldAPIAuthorizer',
      type: 'COGNITO_USER_POOLS',
      identitySource: 'method.request.header.Authorization',
      providerArns: [userPool.userPoolArn],
    });

    // 管理员才能调用这个方法
    // hello.grantInvoke(adminRole);

    //protected-api-path
    const admin = api.root.addResource('cognito-protected-admin');
    const user = api.root.addResource('cognito-protected-user');

    // 关联Lambda 和 restapi
    admin.addMethod(
      'get',
      new gateway.LambdaIntegration(adminFunction, { proxy: true }),
      {
        authorizationType: AuthorizationType.COGNITO,
        authorizer: {
          authorizerId: authorizer.ref,
        },
      },
    );
    user.addMethod(
      'get',
      new gateway.LambdaIntegration(userFunction, { proxy: true }),
      {
        authorizationType: AuthorizationType.COGNITO,
        authorizer: {
          authorizerId: authorizer.ref,
        },
      },
    );

    // IdentityPool;
    const identityPool = new IdentityPool(this, 'TestIdentityPool', {
      identityPoolName: 'testIdentityPool',
      authenticatedRole: userRole,
      allowUnauthenticatedIdentities: false,
      authenticationProviders: {
        userPools: [new UserPoolAuthenticationProvider({ userPool })],
      },
      roleMappings: [
        {
          mappingKey: 'userpool',
          providerUrl: IdentityPoolProviderUrl.userPool(
            userPool.userPoolProviderUrl,
          ),
          useToken: true,
          resolveAmbiguousRoles: false,
        },
      ],
    });
  }
}
```

### CDK CLI Version

2.50.0 (build 4c11af6)

### Node.js Version

v18.12.1

### OS

macOS 13

### Language

Typescript

### Language Version

   "typescript": "~3.9.7"

**Comment by peterwoodworth** [comment]
It doesn't look like the template is getting generated incorrectly. Here's my template:

```
  "IDDefaultRoleAttachment1FD5A972": {
   "Type": "AWS::Cognito::IdentityPoolRoleAttachment",
   "Properties": {
    "IdentityPoolId": {
     "Ref": "IDE62427D4"
    },
    "RoleMappings": {
     "MyKey": {
      "AmbiguousRoleResolution": "Deny",
      "IdentityProvider": {
       "Fn::GetAtt": [
        "UP19EE9C77",
        "ProviderURL"
       ]
      },
      "Type": "Token"
     }
    },
```

According to [CloudFormation](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-cognito-identitypoolroleattachment-rolemapping.html#cfn-cognito-identitypoolroleattachment-rolemapping-identityprovider), the value you have passed in looks to be a valid value.

I was able to reproduce this, I'm going to report this internally to CloudFormation to see if they have any insight here

**Comment by dennisfleischmann** [comment]
Hi guys, I am facing the same issue. Some update on that?

**Comment by dennisfleischmann** [comment]
I have fixed the issue. 

@sheiy Change your provider url as following "https://cognito-idp.us-west-1.amazonaws.com/us-west-1_rRwJgkwYX" is *not* Valid

Valid

example: graph.facebook.com or cognito-idp.us-east-1.amazonaws.com/us-east-1_abcdefghi:app_client_id

In your case 

"cognito-idp.us-west-1.amazonaws.com/us-west-1_rRwJgkwYX: app_client_id"

Hope it helps
Dennis
