### ISSUE TITLE
aws_batch_alpha: granting bucket access not working

### ISSUE THREAD

**Issue by SebastianNichtern** [aws/aws-cdk#23017]
### Describe the bug

I created and deployed a AWS Batch ComputeEnvironment and S3 bucket. Now I wanted to grand permission for the ComputeEnvironment to access the S3 bucket using
```
bucket.grant_read_write(compute_environment)
```
but it results in the following error message:
```
RuntimeError: TypeError: Cannot read properties of undefined (reading 'addToPrincipalPolicy')
```

### Expected Behavior

This should deploy an IAM role giving read and write permission for the ComputeEnvironmen to the mentioned S3 bucket

### Current Behavior

```
cdk deploy
```
throws an error message
```
RuntimeError: TypeError: Cannot read properties of undefined (reading 'addToPrincipalPolicy')
```

### Reproduction Steps

```
vpc = ec2.Vpc(self, "VPC")

spot_environment = batch.ComputeEnvironment(self, "MetaflowSpotEnvironment", managed=True, enabled=True, compute_resources=batch.ComputeResources(type=batch.ComputeResourceType.SPOT, allocation_strategy=batch.AllocationStrategy.BEST_FIT, instance_types=[ec2.InstanceType("c6g.large")], bid_percentage=31, minv_cpus=0, desiredv_cpus=0, maxv_cpus=4, vpc=vpc)

job_queue = batch.JobQueue(self, "JobQueue", compute_environments=[batch.JobQueueComputeEnvironment(compute_environment=spot_environment, order=1)], priority=1)

bucket = s3.Bucket(self, "MetaflowArtifacts")

bucket.grant_read_write(spot_environment)
```

### CDK CLI Version

2.51.1

### Node.js Version

v16.16.0

### OS

MacOS

### Language

Python

### Language Version

Python (3.9.15)

### Other information

Full error output:
```
Traceback (most recent call last):
  File ".../aws_deploy/app.py", line 14, in <module>
    MetaflowBatchStack(app, str(config['project']['project_name']),
  File "/Users/basti/opt/anaconda3/envs/.../lib/python3.9/site-packages/jsii/_runtime.py", line 109, in __call__
    inst = super().__call__(*args, **kwargs)
  File "/Users/basti/.../aws_deploy/aws_deploy/metaflow_batch_stack.py", line 93, in __init__
    bucket.grant_read_write(spot_environment)
  File "/Users/basti/opt/anaconda3/envs/.../lib/python3.9/site-packages/aws_cdk/aws_s3/__init__.py", line 16721, in grant_read_write
    return typing.cast(_Grant_a7ae64f8, jsii.invoke(self, "grantReadWrite", [identity, objects_key_pattern]))
  File "/Users/basti/opt/anaconda3/envs/.../lib/python3.9/site-packages/jsii/_kernel/__init__.py", line 148, in wrapped
    return _recursize_dereference(kernel, fn(kernel, *args, **kwargs))
  File "/Users/basti/opt/anaconda3/envs/.../lib/python3.9/site-packages/jsii/_kernel/__init__.py", line 386, in invoke
    response = self.provider.invoke(
  File "/Users/basti/opt/anaconda3/envs/.../lib/python3.9/site-packages/jsii/_kernel/providers/process.py", line 365, in invoke
    return self._process.send(request, InvokeResponse)
  File "/Users/basti/opt/anaconda3/envs/.../lib/python3.9/site-packages/jsii/_kernel/providers/process.py", line 331, in send
    raise RuntimeError(resp.error) from JavaScriptError(resp.stack)
RuntimeError: TypeError: Cannot read properties of undefined (reading 'addToPrincipalPolicy')
```

**Comment by peterwoodworth** [comment]
This is because `ComputeEnvironment` doesn't extend `IGrantable` and has no `grantPrincipal`. This would be a feature we need to implement

I am marking this issue as p2, which means that we are unable to work on this immediately.

We use +1s to help prioritize our work, and are happy to revaluate this issue based on community feedback. You can reach out to the cdk.dev community on [Slack](https://cdk.dev) to solicit support for reprioritization.

**Comment by comcalvi** [comment]
Closing this one in favor of https://github.com/aws/aws-cdk/issues/16020, since all the context is on that one
