### ISSUE TITLE
[@aws-cdk/aws-ecs: Cannot add logging configuration to FargateTaskDefinition using .add_container()

### ISSUE THREAD

**Issue by Jengah** [aws/aws-cdk#23025]
### Describe the bug

Adding a logging configuration to FargateTaskDefinition fails with `RuntimeError: TypeError: Cannot read properties of undefined (reading 'addToPrincipalPolicy')`

Pseudo code:
```
from aws_cdk import aws_ecs as ecs

self._task = ecs.FargateTaskDefinition(
  self,
  "TaskDef",
  family="some_family_name",
  cpu=some_cpu,
  memory_limit_mib=some_memory,
  execution_role=some_exec_role
)

self._task.add_container(
  "Container1",
  image=ecs.EcrImage.from_registry("some-registry:with-tag"),
  logging=ecs.LogDrivers.aws_logs(stream_prefix="prefix"),
  port_mappings=[
    ecs.PortMapping(
      container_port=container_port,
      host_port=container_port,
    ),
)
```

Results in aforementioned error.  Commenting out the logging configuration results in a successful `cdk synth`, but obviously without logging configured, which is essential.

### Expected Behavior

Synthesizes to valid CloudFormation containing the Logging configuration

### Current Behavior

Results in 
```
jsii.errors.JavaScriptError:
  @jsii/kernel.RuntimeError: TypeError: Cannot read properties of undefined (reading 'addToPrincipalPolicy')
      at Kernel._ensureSync (/private/var/folders/sq/gk_zq8992cq_9mq2m78r439r0000gn/T/tmp73gx6s12/lib/program.js:8428:27)
      at Kernel.invoke (/private/var/folders/sq/gk_zq8992cq_9mq2m78r439r0000gn/T/tmp73gx6s12/lib/program.js:7840:34)
      at KernelHost.processRequest (/private/var/folders/sq/gk_zq8992cq_9mq2m78r439r0000gn/T/tmp73gx6s12/lib/program.js:11017:36)
      at KernelHost.run (/private/var/folders/sq/gk_zq8992cq_9mq2m78r439r0000gn/T/tmp73gx6s12/lib/program.js:10977:22)
      at Immediate._onImmediate (/private/var/folders/sq/gk_zq8992cq_9mq2m78r439r0000gn/T/tmp73gx6s12/lib/program.js:10978:46)
      at processImmediate (node:internal/timers:466:21)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/baxter/code/homebot/infrastructure/cdk/teleport/app.py", line 11, in <module>
    Teleport(app, "teleport-ecs", env=env)
  File "/Users/baxter/.pyenv/versions/cdk-teleport/lib/python3.9/site-packages/jsii/_runtime.py", line 109, in __call__
    inst = super().__call__(*args, **kwargs)
  File "/Users/baxter/code/homebot/infrastructure/cdk/teleport/teleport/teleport.py", line 62, in __init__
    auth_task = TaskDef(
  File "/Users/baxter/.pyenv/versions/cdk-teleport/lib/python3.9/site-packages/jsii/_runtime.py", line 109, in __call__
    inst = super().__call__(*args, **kwargs)
  File "/Users/baxter/code/homebot/infrastructure/cdk/teleport/teleport/teleport.py", line 337, in __init__
    self._task.add_container(
  File "/Users/baxter/.pyenv/versions/cdk-teleport/lib/python3.9/site-packages/aws_cdk/aws_ecs/__init__.py", line 29413, in add_container
    return typing.cast(ContainerDefinition, jsii.invoke(self, "addContainer", [id, props]))
  File "/Users/baxter/.pyenv/versions/cdk-teleport/lib/python3.9/site-packages/jsii/_kernel/__init__.py", line 148, in wrapped
    return _recursize_dereference(kernel, fn(kernel, *args, **kwargs))
  File "/Users/baxter/.pyenv/versions/cdk-teleport/lib/python3.9/site-packages/jsii/_kernel/__init__.py", line 386, in invoke
    response = self.provider.invoke(
  File "/Users/baxter/.pyenv/versions/cdk-teleport/lib/python3.9/site-packages/jsii/_kernel/providers/process.py", line 365, in invoke
    return self._process.send(request, InvokeResponse)
  File "/Users/baxter/.pyenv/versions/cdk-teleport/lib/python3.9/site-packages/jsii/_kernel/providers/process.py", line 331, in send
    raise RuntimeError(resp.error) from JavaScriptError(resp.stack)
RuntimeError: TypeError: Cannot read properties of undefined (reading 'addToPrincipalPolicy'
```

### Reproduction Steps

- Create FargateTaskDefinition
- Try to add container with aws log configuration via .add_container()

### Additional Information/Context

As mentioned, removing the logging configuration results in a successful synthesize.

### CDK CLI Version

2.50.0 (build 4c11af6)

### Framework Version

2.50.0

### Node.js Version

16.18.1

### OS

macOS 12.5.1 (M1 arm)

### Language

Python

### Language Version

3.9.15

**Comment by peterwoodworth** [comment]
This looks like a similar error that was reported earlier that's since been patched up. I tried reproducing this on the latest version using your code and I'm unable to do so, so I recommend upgrading to latest version and seeing if error still persists. Thanks!
