### ISSUE TITLE
Route53: exception creating a CfnRecordSet

### ISSUE THREAD

**Issue by markshep** [aws/aws-cdk#23033]
### Describe the bug

I'm trying to create some record sets that make use of Route53's [IP-based routing](https://docs.aws.amazon.com/Route53/latest/DeveloperGuide/routing-policy-ipbased.html).  The L2 constructs don't seem to support this so I'm using the L1 Cfn constructs.  I've got a first draft of my code which I _think_ is what's required to use this feature (which I've not used before) but I'm hitting an exception with a callstack deep into JSII JSON parsing when I try to execute the code.

### Expected Behavior

No exception.

### Current Behavior

This is the output when executing my code:

```
Unhandled exception. Newtonsoft.Json.JsonSerializationException: Error converting value "Error" to type 'Amazon.JSII.JsonModel.Api.Response.ErrorResponseName'. Path 'name'.
 ---> System.ArgumentException: Requested value 'Error' was not found.
   at Newtonsoft.Json.Utilities.EnumUtils.ParseEnum(Type enumType, NamingStrategy namingStrategy, String value, Boolean disallowNumber)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.EnsureType(JsonReader reader, Object value, CultureInfo culture, JsonContract contract, Type targetType)
   --- End of inner exception stack trace ---
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.EnsureType(JsonReader reader, Object value, CultureInfo culture, JsonContract contract, Type targetType)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.ResolvePropertyAndCreatorValues(JsonObjectContract contract, JsonProperty containerProperty, JsonReader reader, Type objectType)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObjectUsingCreatorWithParameters(JsonReader reader, JsonObjectContract contract, JsonProperty containerProperty, ObjectConstructor`1 creator, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateNewObject(JsonReader reader, JsonObjectContract objectContract, JsonProperty containerMember, JsonProperty containerProperty, String id, Boolean& createdFromNonDefaultCreator)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonSerializer.Deserialize(JsonReader reader, Type objectType)
   at Newtonsoft.Json.Linq.JToken.ToObject(Type objectType, JsonSerializer jsonSerializer)
   at Newtonsoft.Json.Linq.JToken.ToObject(Type objectType)
   at Newtonsoft.Json.Linq.JToken.ToObject[T]()
   at Amazon.JSII.Runtime.Services.Client.TryDeserialize[TResponse](String responseJson)
   at Amazon.JSII.Runtime.Services.Client.ReceiveResponse[TResponse]()
   at Amazon.JSII.Runtime.Services.Client.Send[TRequest,TResponse](TRequest requestObject)
   at Amazon.JSII.Runtime.Services.Client.Create(CreateRequest request)
   at Amazon.JSII.Runtime.Services.Client.Create(String fullyQualifiedName, Object[] arguments, Override[] overrides, String[] interfaces)
   at Amazon.JSII.Runtime.Deputy.DeputyBase..ctor(DeputyProps props)
   at Constructs.Construct..ctor(DeputyProps props)
   at Amazon.CDK.CfnElement..ctor(DeputyProps props)
   at Amazon.CDK.CfnRefElement..ctor(DeputyProps props)
   at Amazon.CDK.CfnResource..ctor(DeputyProps props)
   at Amazon.CDK.AWS.Route53.CfnRecordSet..ctor(Construct scope, String id, ICfnRecordSetProps props)
   at OdysseyMobiStack.MakeRecordSet(String zoneId, String name, CfnCidrCollection cidrCollection, String location, String targetIp) in /Users/mark.sheppard/code/odyssey/aws-odyssey-mobi/OdysseyMobi/OdysseyModiStack.cs:line 118
   at OdysseyMobiStack.AddIpRouting(String zoneId, String name, String privateIp, String publicIp) in /Users/mark.sheppard/code/odyssey/aws-odyssey-mobi/OdysseyMobi/OdysseyModiStack.cs:line 111
   at OdysseyMobiStack..ctor(App scope, String stackName, IEnvironment env) in /Users/mark.sheppard/code/odyssey/aws-odyssey-mobi/OdysseyMobi/OdysseyModiStack.cs:line 72
   at Program.<Main>$(String[] args) in /Users/mark.sheppard/code/odyssey/aws-odyssey-mobi/OdysseyMobi/Program.cs:line 8

Subprocess exited with error 134
```

### Reproduction Steps

This is the `MakeRecordSet` method in my code with the offending call to create a `CfnRecordSet`:

```csharp
void MakeRecordSet(string zoneId, string name, CfnCidrCollection cidrCollection, string location, string targetIp)
{
    new CfnRecordSet(this, ResourceName(name, "RecordSet"), new CfnRecordSetProps {
            HostedZoneId = zoneId,
            Name = name,
            Type = RecordType.A.ToString(),
            ResourceRecords = new[] { targetIp },
            CidrRoutingConfig = new CfnRecordSet.CidrRoutingConfigProperty {
                CollectionId = cidrCollection.AttrId,
                LocationName = location,
            },
        });
}
```

### CDK CLI Version

2.51.1 (build 3d30cdb)

### Node.js Version

v18.12.1

### OS

macOS Monterey (12.6.1)

### Language

.NET

### Language Version

Using dotnet 7.0.100 with a target framework of `net6.0`

### Other information

I'm using the Homebrew packages `aws-cdk` and `node@18`.

**Comment by pahud** [comment]
Can you create the L1 resource simply by

```csharp
new CfnRecordSet(this, ResourceName(name, "RecordSet"), new CfnRecordSetProps {
        HostedZoneId = zoneId,
        Name = 'sample.com',
        Type = RecordType.A.ToString(),
        ResourceRecords = new[] { targetIp },
        CidrRoutingConfig = new CfnRecordSet.CidrRoutingConfigProperty {
            CollectionId = cidrCollection.AttrId,
            LocationName = location,
        },
    });
```

I doubt the `name` might be a reserved word?

**Comment by pahud** [comment]
@markshep  I am not .NET expert but I think you can try to create with L2 and `addPropertyOverride` for `CidrRoutingConfig` like the typescript sample below:

```ts
const record = new route53.ARecord(stack, 'ARecord', {
  zone,
  target: route53.RecordTarget.fromIpAddresses('1.2.3.4'),
});

(record.node.defaultChild as route53.CfnRecordSet).addPropertyOverride('CidrRoutingConfig', {
  CollectionId: 'CollectionId',
  LocationName: 'LocationName',
});
```

It synthesized well in my environment with CDK 2.51.1 but I didn't deploy it yet. Please let me know if it works with you.

**Comment by markshep** [comment]
Unfortunately that didn't work for me.  However I have discovered that it's on the _second_ call to my `MakeRecordSet` method when the error occurs.  So there's already been a RecordSet created for a particular name with a `CidrRoutingConfig` attribute and the problem occurs when trying to create the second RecordSet for the same name as the first but with different information in its `CidrRoutingConfig` attribute.

**Comment by markshep** [comment]
This is a simplified version of the calling method:

```csharp
void AddIpRouting(string zoneId, string name, string privateIp, string publicIp)
{
    var cidrCollection = new CfnCidrCollection(this, "CidrCollection", new CfnCidrCollectionProps {
            Name = "NetworkEgresses",
            Locations = new[] {
                new CfnCidrCollection.LocationProperty {
                    LocationName = "NetworkEgress",
                    CidrList = new[] { "1.2.3.0/24" },
                }
            }
        });

    MakeRecordSet(zoneId, name, cidrCollection, "NetworkEgress", privateIp);
    MakeRecordSet(zoneId, name, cidrCollection, "*", publicIp);
}
```

**Comment by markshep** [comment]
I've managed to get it to produce a CloudFormation template by wrapping the record sets in a RecordSetGroup like this:

```csharp
void AddIpRouting(string zoneId, string name, string privateIp, string publicIp)
{
    var cidrCollection = new CfnCidrCollection(this, "CidrCollection", new CfnCidrCollectionProps {
            Name = "NetworkEgresses",
            Locations = new[] {
                new CfnCidrCollection.LocationProperty {
                    LocationName = "NetworkEgress",
                    CidrList = new[] { "1.2.3.0/24" },
                }
            }
        });

    new CfnRecordSetGroup(this, ResourceName(name, "RecordSetGroup"), new CfnRecordSetGroupProps {
            HostedZoneId = zoneId,
            RecordSets = new[] {
                MakeRecordSetProperty(zoneId, name, cidrCollection, "NetworkEgress", privateIp),
                MakeRecordSetProperty(zoneId, name, cidrCollection, "*", publicIp),
            },
        });
}

static CfnRecordSetGroup.RecordSetProperty MakeRecordSetProperty(string zoneId, string name, CfnCidrCollection cidrCollection, string location, string targetIp)
{
    return new CfnRecordSetGroup.RecordSetProperty {
        HostedZoneId = zoneId,
        Name = name,
        Type = RecordType.A.ToString(),
        ResourceRecords = new[] { targetIp },
        CidrRoutingConfig = new CfnRecordSetGroup.CidrRoutingConfigProperty {
            CollectionId = cidrCollection.AttrId,
            LocationName = location,
        },
    };
}
```
When trying to deploy I get the error `Encountered unsupported property HostedZoneId`, but at least I've made some progress!

**Comment by markshep** [comment]
As the error message I was getting was `Error converting value "Error" to type 'Amazon.JSII.JsonModel.Api.Response.ErrorResponseName'. Path 'name'.` it sounds like there's a bug in the CDK error handling.  If that was fixed then I'd have (hopefully) been presented with a more meaningful error message about RecordSets with a duplicated Name (and ideally suggesting to use a RecordSetGroup).

**Comment by MrArnoldPalmer** [comment]
@markshep there is an issue with dotnet error messages that we are investigating, track that here https://github.com/aws/aws-cdk/issues/22369

**Comment by markshep** [comment]
Testing my original code with version 2.41.0 of Amazon.CDK.Lib gives this error message instead:

```
Unhandled exception. Amazon.JSII.Runtime.JsiiException: There is already a Construct with name 'UnityRecordSet' in Stack [odyssey-mobi-domain]
   at Amazon.JSII.Runtime.Services.Client.TryDeserialize[TResponse](String responseJson)
   at Amazon.JSII.Runtime.Services.Client.ReceiveResponse[TResponse]()
   at Amazon.JSII.Runtime.Services.Client.Send[TRequest,TResponse](TRequest requestObject)
   at Amazon.JSII.Runtime.Services.Client.Create(CreateRequest request)
   at Amazon.JSII.Runtime.Services.Client.Create(String fullyQualifiedName, Object[] arguments, Override[] overrides, String[] interfaces)
   at Amazon.JSII.Runtime.Deputy.DeputyBase..ctor(DeputyProps props)
   at Constructs.Construct..ctor(DeputyProps props)
   at Amazon.CDK.CfnElement..ctor(DeputyProps props)
   at Amazon.CDK.CfnRefElement..ctor(DeputyProps props)
   at Amazon.CDK.CfnResource..ctor(DeputyProps props)
   at Amazon.CDK.AWS.Route53.CfnRecordSet..ctor(Construct scope, String id, ICfnRecordSetProps props)
   at OdysseyMobiStack.MakeRecordSet(String zoneId, String name, CfnCidrCollection cidrCollection, String location, String targetIp) in /Users/mark.sheppard/code/odyssey/aws-odyssey-mobi/OdysseyMobi/OdysseyModiStack.cs:line 167
   at OdysseyMobiStack.AddIpRouting(String zoneId, String name, String privateIp, String publicIp) in /Users/mark.sheppard/code/odyssey/aws-odyssey-mobi/OdysseyMobi/OdysseyModiStack.cs:line 162
   at OdysseyMobiStack..ctor(App scope, String stackName, IEnvironment env) in /Users/mark.sheppard/code/odyssey/aws-odyssey-mobi/OdysseyMobi/OdysseyModiStack.cs:line 114
   at Program.<Main>$(String[] args) in /Users/mark.sheppard/code/odyssey/aws-odyssey-mobi/OdysseyMobi/Program.cs:line 8

Subprocess exited with error 134
```

So I'll close this as it's a dupe of #22369.
