### ISSUE TITLE
(cdk deploy): cdk deploy does not properly assume file publishing role before attempting to call APIs on asset bucket

### ISSUE THREAD

**Issue by brunoklein99** [aws/aws-cdk#23041]
### Describe the bug

When the user calls `cdk deploy` with a stack that contains a `aws_lambda.Function` resource the CLI will call S3 APIs on the asset bucket *without* first assuming the "file publishing role". Therefore, the API call is performed with the role the user on the credentials environment variables (`AWS_ACCESS_KEY_ID`, `AWS_SECRET_ACCESS_KEY`, `AWS_SESSION_TOKEN`) causing permission errors and the deployment to fail.

### Expected Behavior

The CDK CLI should first call `AssumeRole` on the "file publishing role", which has already been setup with appropriate permissions by `cdk bootstrap`.

### Current Behavior

Logs for the current behavior of `cdk deploy`

See line below:

```
[13:17:48] Call failed: getBucketLocation({"Bucket":"cdk-hnb659fds-assets-162234902838-us-east-1"}) => Access Denied (code=AccessDenied)
```

```
> cdk deploy -vvv --debug
[13:17:35] CDK toolkit version: 2.51.1 (build 3d30cdb)
[13:17:35] Command line arguments: {
  _: [ 'deploy' ],
  v: 3,
  verbose: 3,
  debug: true,
  lookups: true,
  'ignore-errors': false,
  ignoreErrors: false,
  json: false,
  j: false,
  ec2creds: undefined,
  i: undefined,
  'version-reporting': undefined,
  versionReporting: undefined,
  'path-metadata': true,
  pathMetadata: true,
  'asset-metadata': true,
  assetMetadata: true,
  'role-arn': undefined,
  r: undefined,
  roleArn: undefined,
  staging: true,
  'no-color': false,
  noColor: false,
  ci: false,
  all: false,
  'build-exclude': [],
  E: [],
  buildExclude: [],
  force: false,
  f: false,
  parameters: [ {} ],
  'previous-parameters': true,
  previousParameters: true,
  logs: true,
  concurrency: 1,
  'asset-prebuild': true,
  assetPrebuild: true,
  '$0': 'cdk'
}
[13:17:35] cdk.json: {
  "app": "python3 app.py",
  "watch": {
    "include": [
      "**"
    ],
    "exclude": [
      "README.md",
      "cdk*.json",
      "requirements*.txt",
      "source.bat",
      "**/__init__.py",
      "python/__pycache__",
      "tests"
    ]
  },
  "context": {
    "@aws-cdk/aws-lambda:recognizeLayerVersion": true,
    "@aws-cdk/core:checkSecretUsage": true,
    "@aws-cdk/core:target-partitions": [
      "aws",
      "aws-cn"
    ],
    "@aws-cdk-containers/ecs-service-extensions:enableDefaultLogDriver": true,
    "@aws-cdk/aws-ec2:uniqueImdsv2TemplateName": true,
    "@aws-cdk/aws-ecs:arnFormatIncludesClusterName": true,
    "@aws-cdk/aws-iam:minimizePolicies": true,
    "@aws-cdk/core:validateSnapshotRemovalPolicy": true,
    "@aws-cdk/aws-codepipeline:crossAccountKeyAliasStackSafeResourceName": true,
    "@aws-cdk/aws-s3:createDefaultLoggingPolicy": true,
    "@aws-cdk/aws-sns-subscriptions:restrictSqsDescryption": true,
    "@aws-cdk/aws-apigateway:disableCloudWatchRole": true,
    "@aws-cdk/core:enablePartitionLiterals": true,
    "@aws-cdk/aws-events:eventsTargetQueueSameAccount": true,
    "@aws-cdk/aws-iam:standardizedServicePrincipals": true,
    "@aws-cdk/aws-ecs:disableExplicitDeploymentControllerForCircuitBreaker": true
  }
}
[13:17:35] cdk.context.json: {
  "acknowledged-issue-numbers": [
    19836
  ]
}
[13:17:35] merged settings: {
  versionReporting: true,
  pathMetadata: true,
  output: 'cdk.out',
  app: 'python3 app.py',
  watch: {
    include: [ '**' ],
    exclude: [
      'README.md',
      'cdk*.json',
      'requirements*.txt',
      'source.bat',
      '**/__init__.py',
      'python/__pycache__',
      'tests'
    ]
  },
  context: {
    '@aws-cdk/aws-lambda:recognizeLayerVersion': true,
    '@aws-cdk/core:checkSecretUsage': true,
    '@aws-cdk/core:target-partitions': [ 'aws', 'aws-cn' ],
    '@aws-cdk-containers/ecs-service-extensions:enableDefaultLogDriver': true,
    '@aws-cdk/aws-ec2:uniqueImdsv2TemplateName': true,
    '@aws-cdk/aws-ecs:arnFormatIncludesClusterName': true,
    '@aws-cdk/aws-iam:minimizePolicies': true,
    '@aws-cdk/core:validateSnapshotRemovalPolicy': true,
    '@aws-cdk/aws-codepipeline:crossAccountKeyAliasStackSafeResourceName': true,
    '@aws-cdk/aws-s3:createDefaultLoggingPolicy': true,
    '@aws-cdk/aws-sns-subscriptions:restrictSqsDescryption': true,
    '@aws-cdk/aws-apigateway:disableCloudWatchRole': true,
    '@aws-cdk/core:enablePartitionLiterals': true,
    '@aws-cdk/aws-events:eventsTargetQueueSameAccount': true,
    '@aws-cdk/aws-iam:standardizedServicePrincipals': true,
    '@aws-cdk/aws-ecs:disableExplicitDeploymentControllerForCircuitBreaker': true
  },
  debug: true,
  assetMetadata: true,
  toolkitBucket: {},
  staging: true,
  bundlingStacks: [ '**' ],
  lookups: true,
  assetPrebuild: true
}
[13:17:35] [trace] SdkProvider#withAwsCliCompatibleDefaults()
[13:17:35] Determining if we're on an EC2 instance.
[13:17:35] Does not look like an EC2 instance.
[13:17:35] Reading cached notices from /Users/bruklein/.cdk/cache/notices.json
[13:17:35] Toolkit stack: CDKToolkit
[13:17:35] Setting "CDK_DEFAULT_REGION" environment variable to us-east-1
[13:17:35] [trace] SdkProvider#defaultAccount()
[13:17:35] [trace]   SdkProvider#defaultCredentials()
[13:17:35] Resolving default credentials
[13:17:35] [trace]   SDK#currentAccount()
[13:17:35] [trace]     SDK#forceCredentialRetrieval()
[13:17:35] Retrieved account ID 162234902838 from disk cache
[13:17:35] Setting "CDK_DEFAULT_ACCOUNT" environment variable to 162234902838
[13:17:35] context: {
  'acknowledged-issue-numbers': [ 19836 ],
  '@aws-cdk/aws-lambda:recognizeLayerVersion': true,
  '@aws-cdk/core:checkSecretUsage': true,
  '@aws-cdk/core:target-partitions': [ 'aws', 'aws-cn' ],
  '@aws-cdk-containers/ecs-service-extensions:enableDefaultLogDriver': true,
  '@aws-cdk/aws-ec2:uniqueImdsv2TemplateName': true,
  '@aws-cdk/aws-ecs:arnFormatIncludesClusterName': true,
  '@aws-cdk/aws-iam:minimizePolicies': true,
  '@aws-cdk/core:validateSnapshotRemovalPolicy': true,
  '@aws-cdk/aws-codepipeline:crossAccountKeyAliasStackSafeResourceName': true,
  '@aws-cdk/aws-s3:createDefaultLoggingPolicy': true,
  '@aws-cdk/aws-sns-subscriptions:restrictSqsDescryption': true,
  '@aws-cdk/aws-apigateway:disableCloudWatchRole': true,
  '@aws-cdk/core:enablePartitionLiterals': true,
  '@aws-cdk/aws-events:eventsTargetQueueSameAccount': true,
  '@aws-cdk/aws-iam:standardizedServicePrincipals': true,
  '@aws-cdk/aws-ecs:disableExplicitDeploymentControllerForCircuitBreaker': true,
  'aws:cdk:enable-path-metadata': true,
  'aws:cdk:enable-asset-metadata': true,
  'aws:cdk:version-reporting': true,
  'aws:cdk:bundling-stacks': [ '**' ]
}
[13:17:35] outdir: cdk.out
[13:17:35] env: {
  CDK_DEFAULT_REGION: 'us-east-1',
  CDK_DEFAULT_ACCOUNT: '162234902838',
  CDK_DEBUG: 'true',
  CDK_OUTDIR: 'cdk.out',
  CDK_CLI_ASM_VERSION: '21.0.0',
  CDK_CLI_VERSION: '2.51.1'
}

✨  Synthesis time: 3.59s

[13:17:39] Reading existing template for stack cdk-bug-test.
[13:17:39] [trace] SdkProvider#resolveEnvironment()
[13:17:39] [trace]   SdkProvider#defaultAccount()
[13:17:39] [trace] SdkProvider#forEnvironment()
[13:17:39] [trace]   SdkProvider#resolveEnvironment()
[13:17:39] [trace]   SdkProvider#obtainBaseCredentials()
[13:17:39] [trace]     SdkProvider#defaultAccount()
[13:17:39] [trace]     SdkProvider#defaultCredentials()
[13:17:39] [trace]   SDK#validateCredentials()
[13:17:40] [AWS sts 200 1.439s 0 retries] getCallerIdentity({})
[13:17:40] [trace] SdkProvider#resolveEnvironment()
[13:17:40] [trace]   SdkProvider#defaultAccount()
[13:17:40] [trace] SdkProvider#forEnvironment()
[13:17:40] [trace]   SdkProvider#resolveEnvironment()
[13:17:40] [trace]   SdkProvider#obtainBaseCredentials()
[13:17:40] [trace]     SdkProvider#defaultAccount()
[13:17:40] [trace]     SdkProvider#defaultCredentials()
[13:17:40] [trace]   SDK#validateCredentials()
[13:17:41] [AWS sts 200 0.624s 0 retries] getCallerIdentity({})
[13:17:41] [trace] SDK#cloudFormation()
[13:17:41] [trace]   SDK#wrapServiceErrorHandling()
[13:17:42] [AWS cloudformation 200 0.849s 0 retries] describeStacks({ StackName: 'cdk-bug-test' })
[13:17:42] [AWS cloudformation 200 0.583s 0 retries] getTemplate({ StackName: 'cdk-bug-test', TemplateStage: 'Original' })
This deployment will make potentially sensitive changes according to your current security approval level (--require-approval broadening).
Please confirm you intend to make the following modifications:

IAM Statement Changes
┌───┬───────────────────────────┬────────┬────────────────┬──────────────────────────────┬───────────┐
│   │ Resource                  │ Effect │ Action         │ Principal                    │ Condition │
├───┼───────────────────────────┼────────┼────────────────┼──────────────────────────────┼───────────┤
│ + │ ${Lambda/ServiceRole.Arn} │ Allow  │ sts:AssumeRole │ Service:lambda.amazonaws.com │           │
└───┴───────────────────────────┴────────┴────────────────┴──────────────────────────────┴───────────┘
IAM Policy Changes
┌───┬───────────────────────┬────────────────────────────────────────────────────────────────────────────────┐
│   │ Resource              │ Managed Policy ARN                                                             │
├───┼───────────────────────┼────────────────────────────────────────────────────────────────────────────────┤
│ + │ ${Lambda/ServiceRole} │ arn:${AWS::Partition}:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole │
└───┴───────────────────────┴────────────────────────────────────────────────────────────────────────────────┘
(NOTE: There may be security-related changes not in this list. See https://github.com/aws/aws-cdk/issues/1299)

Do you wish to deploy these changes (y/n)? y
cdk-bug-test: deploying...
[13:17:44] [trace] SdkProvider#resolveEnvironment()
[13:17:44] [trace]   SdkProvider#defaultAccount()
[13:17:44] [trace] SdkProvider#forEnvironment()
[13:17:44] [trace]   SdkProvider#resolveEnvironment()
[13:17:44] [trace]   SdkProvider#obtainBaseCredentials()
[13:17:44] [trace]     SdkProvider#defaultAccount()
[13:17:44] [trace]     SdkProvider#defaultCredentials()
[13:17:44] [trace]   SDK#validateCredentials()
[13:17:45] [AWS sts 200 0.581s 0 retries] getCallerIdentity({})
[13:17:45] [trace] SDK#cloudFormation()
[13:17:45] [trace]   SDK#wrapServiceErrorHandling()
[13:17:45] Waiting for stack CDKToolkit to finish creating or updating...
[13:17:45] [AWS cloudformation 200 0.64s 0 retries] describeStacks({ StackName: 'CDKToolkit' })
[13:17:45] [trace] SdkProvider#resolveEnvironment()
[13:17:45] [trace]   SdkProvider#defaultAccount()
[13:17:45] [trace] SDK#appendCustomUserAgent()
[13:17:45] [trace] SDK#cloudFormation()
[13:17:45] [trace]   SDK#wrapServiceErrorHandling()
[13:17:46] [AWS cloudformation 200 0.618s 0 retries] describeStacks({ StackName: 'cdk-bug-test' })
[13:17:46] Preparing asset 9bac3d1f7fe1ea725c9e67d74ca861556b0f6ceba276a8e8114ac49333571163: {"path":"asset.9bac3d1f7fe1ea725c9e67d74ca861556b0f6ceba276a8e8114ac49333571163","id":"9bac3d1f7fe1ea725c9e67d74ca861556b0f6ceba276a8e8114ac49333571163","packaging":"zip","sourceHash":"9bac3d1f7fe1ea725c9e67d74ca861556b0f6ceba276a8e8114ac49333571163","s3BucketParameter":"AssetParameters9bac3d1f7fe1ea725c9e67d74ca861556b0f6ceba276a8e8114ac49333571163S3Bucket03527023","s3KeyParameter":"AssetParameters9bac3d1f7fe1ea725c9e67d74ca861556b0f6ceba276a8e8114ac49333571163S3VersionKey15F3B15F","artifactHashParameter":"AssetParameters9bac3d1f7fe1ea725c9e67d74ca861556b0f6ceba276a8e8114ac49333571163ArtifactHashE8D5AF65"}
[13:17:46] Storing asset asset.9bac3d1f7fe1ea725c9e67d74ca861556b0f6ceba276a8e8114ac49333571163 at s3://cdk-hnb659fds-assets-162234902838-us-east-1/assets/9bac3d1f7fe1ea725c9e67d74ca861556b0f6ceba276a8e8114ac49333571163.zip
[13:17:46] cdk-bug-test: checking if we can skip deploy
[13:17:47] [AWS cloudformation 200 0.616s 0 retries] getTemplate({ StackName: 'cdk-bug-test', TemplateStage: 'Original' })
[13:17:47] cdk-bug-test: template has changed
[13:17:47] cdk-bug-test: deploying...
[0%] start: Building and publishing 9bac3d1f7fe1ea725c9e67d74ca861556b0f6ceba276a8e8114ac49333571163:current
[13:17:47] [trace] SdkProvider#forEnvironment()
[13:17:47] [trace]   SdkProvider#resolveEnvironment()
[13:17:47] [trace]   SdkProvider#obtainBaseCredentials()
[13:17:47] [trace]     SdkProvider#defaultAccount()
[13:17:47] [trace]     SdkProvider#defaultCredentials()
[13:17:47] [trace]   SDK#validateCredentials()
[13:17:47] [AWS sts 200 0.593s 0 retries] getCallerIdentity({})
[13:17:47] [trace] SDK#s3()
[13:17:47] [trace]   SDK#wrapServiceErrorHandling()
[13:17:47] [0%] check: Check s3://cdk-hnb659fds-assets-162234902838-us-east-1/assets/9bac3d1f7fe1ea725c9e67d74ca861556b0f6ceba276a8e8114ac49333571163.zip
[13:17:48] [AWS s3 403 0.706s 0 retries] getBucketLocation({ Bucket: 'cdk-hnb659fds-assets-162234902838-us-east-1' })
[13:17:48] [trace] SDK#makeDetailedException()
[13:17:48] Call failed: getBucketLocation({"Bucket":"cdk-hnb659fds-assets-162234902838-us-east-1"}) => Access Denied (code=AccessDenied)
[13:17:48] [trace] SDK#currentAccount()
[13:17:48] [trace]   SDK#forceCredentialRetrieval()
[13:17:48] Retrieved account ID 162234902838 from disk cache
[100%] fail: Bucket named 'cdk-hnb659fds-assets-162234902838-us-east-1' exists, but not in account 162234902838. Wrong account?

 ❌  cdk-bug-test failed: Error: Failed to publish one or more assets. See the error messages above for more information.
    at publishAssets (/usr/local/lib/node_modules/aws-cdk/lib/util/asset-publishing.ts:60:11)
    at deployStack (/usr/local/lib/node_modules/aws-cdk/lib/api/deploy-stack.ts:297:3)
    at deployStack2 (/usr/local/lib/node_modules/aws-cdk/lib/cdk-toolkit.ts:264:24)
    at /usr/local/lib/node_modules/aws-cdk/lib/deploy.ts:39:11
    at run (/usr/local/lib/node_modules/p-queue/dist/index.js:163:29)

 ❌ Deployment failed: Error: Stack Deployments Failed: Error: Failed to publish one or more assets. See the error messages above for more information.
    at deployStacks (/usr/local/lib/node_modules/aws-cdk/lib/deploy.ts:61:11)
    at CdkToolkit.deploy (/usr/local/lib/node_modules/aws-cdk/lib/cdk-toolkit.ts:338:7)
    at initCommandLine (/usr/local/lib/node_modules/aws-cdk/lib/cli.ts:364:12)
[13:17:48] Reading cached notices from /Users/bruklein/.cdk/cache/notices.json

Stack Deployments Failed: Error: Failed to publish one or more assets. See the error messages above for more information.
[13:17:48] Error: Stack Deployments Failed: Error: Failed to publish one or more assets. See the error messages above for more information.
    at deployStacks (/usr/local/lib/node_modules/aws-cdk/lib/deploy.ts:61:11)
    at CdkToolkit.deploy (/usr/local/lib/node_modules/aws-cdk/lib/cdk-toolkit.ts:338:7)
    at initCommandLine (/usr/local/lib/node_modules/aws-cdk/lib/cli.ts:364:12)
```

### Reproduction Steps

1. Create clean AWS account
2. Create new stack (`cdk init`)
3. Add Lambda 
```
from aws_cdk.aws_lambda import Function, Code, Runtime
from aws_cdk.core import Stack, Construct


class CdkBugTestStack(Stack):

    def __init__(self, scope: Construct, construct_id: str, **kwargs) -> None:
        super().__init__(scope, construct_id, **kwargs)
        function = Function(
            self, 'Lambda',
            function_name='func',
            handler='lambda_handler',
            code=Code.from_asset('cdk_bug_test/function'),
            runtime=Runtime.PYTHON_3_9
        )

```
5. Remove permission of the user from the asset bucket, for testing purposes:
```
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Sid": "VisualEditor1",
            "Effect": "Deny",
            "Action": "s3:*",
            "Resource": [
                "arn:aws:s3:::cdk-abc123abc-assets-123456789123-us-east-1",
                "arn:aws:s3:::cdk-abc123abc-assets-123456789123-us-east-1/*"
            ]
        }
    ]
}
```

### Possible Solution

Have the CDK CLI call `AssumeRole` on the "file publishing role" (`cdk-abc123abc-file-publishing-role-123456789123-us-east-1`) before calling S3 APIs on the asset bucket. 

### CDK CLI Version

2.51.1 (build 3d30cdb)

### Node.js Version

v16.13.2

### OS

 MacOs Monterey 12.6.1 (21G217)

### Language

Python

### Language Version

3.9

### Other information

bruklein@

**Comment by peterwoodworth** [comment]
Hey @brunoklein99, this is a pretty core part of the deployment process, and I can confirm it hasn't broken. So I think you may be either defining a stack synthesizer when creating an instance of your stack, and/or you are forgoing the bootstrap step (I see that `bootstrap` is absent from your reproduction steps starting from a brand new account). Be sure to view our [bootstrapping documentation](https://docs.aws.amazon.com/cdk/v2/guide/bootstrapping.html)

**Comment by brunoklein99** [comment]
Hi @peterwoodworth, thanks for the reply. 

My mistake to not include `cdk bootstrap` in the steps. I have done that.

What do you mean by "stack synthesizer"? Does the default sample using `cdk init` uses a stack synthesizer. I have simply done `cdk init` and added the `Function`.

**Comment by brunoklein99** [comment]
Hi @peterwoodworth, any insights?

**Comment by peterwoodworth** [comment]
I was able to reproduce this issue by providing a role arn to my stack synthesizer which does not have file asset publishing perms

```
const s = new AssetStack(app, 'AssetStack', {
  env,
  synthesizer: new DefaultStackSynthesizer({
    fileAssetPublishingRoleArn: 'arn:aws:iam::123456789012:role/myrolewithoutperms'
  })
});
```

I suspect that for some reason in your environment that the role generated doesn't have the proper permissions, for some reason. What version does your bootstrap stack show?
