### ISSUE TITLE
CfnInclude: No longer works with !!int parameter default value

### ISSUE THREAD

**Issue by michanto** [aws/aws-cdk#23251]
### Describe the bug

This used to work. 

I have a template I am importing with CfnInclude:

```
"Parameters":
  "FlowLogsRetentionInDays":
    "Default": !!int "365"
    "Description": "number of days to retain vpc flow logs in cloudwatch logs"
    "Type": "Number"
"Resources":
  "FlowLogsGroup":
    "Condition": "ShouldCreateFlowLogsResources"
    "DeletionPolicy": "Retain"
    "Properties":
      "RetentionInDays":
        "Ref": "FlowLogsRetentionInDays"
    "Type": "AWS::Logs::LogGroup"
```

### Expected Behavior

Template should import and generate a valid template.

### Current Behavior

I used to be able to import this template with CfnInclude.  Now I get the following error:

```
CfnSynthesisError: Resolution error: Supplied properties not correct for "CfnLogGroupProps"
  retentionInDays: "" should be a number.
    at ValidationResult.assertSuccess (/local/home/michanto/brazil-ws/WisdomPlatformLegacy/src/WisdomPlatformLegacyCDK/node_modules/aws-cdk-lib/core/lib/runtime.js:1:2645)
    at cfnLogGroupPropsToCloudFormation (/local/home/michanto/brazil-ws/WisdomPlatformLegacy/src/WisdomPlatformLegacyCDK/node_modules/aws-cdk-lib/aws-logs/lib/logs.generated.js:1:5614)
    at CfnLogGroup.renderProperties (/local/home/michanto/brazil-ws/WisdomPlatformLegacy/src/WisdomPlatformLegacyCDK/node_modules/aws-cdk-lib/aws-logs/lib/logs.generated.js:1:8756)
    at PostResolveToken.Resources [as processor] (/local/home/michanto/brazil-ws/WisdomPlatformLegacy/src/WisdomPlatformLegacyCDK/node_modules/aws-cdk-lib/core/lib/cfn-resource.js:1:5082)
    at PostResolveToken.postProcess (/local/home/michanto/brazil-ws/WisdomPlatformLegacy/src/WisdomPlatformLegacyCDK/node_modules/aws-cdk-lib/core/lib/util.js:1:1566)
    at Object.postProcess (/local/home/michanto/brazil-ws/WisdomPlatformLegacy/src/WisdomPlatformLegacyCDK/node_modules/aws-cdk-lib/core/lib/private/resolve.js:1:1247)
    at DefaultTokenResolver.resolveToken (/local/home/michanto/brazil-ws/WisdomPlatformLegacy/src/WisdomPlatformLegacyCDK/node_modules/aws-cdk-lib/core/lib/resolvable.js:1:1320)
    at resolve (/local/home/michanto/brazil-ws/WisdomPlatformLegacy/src/WisdomPlatformLegacyCDK/node_modules/aws-cdk-lib/core/lib/private/resolve.js:1:2661)
    at Object.resolve (/local/home/michanto/brazil-ws/WisdomPlatformLegacy/src/WisdomPlatformLegacyCDK/node_modules/aws-cdk-lib/core/lib/private/resolve.js:1:1121)
    at resolve (/local/home/michanto/brazil-ws/WisdomPlatformLegacy/src/WisdomPlatformLegacyCDK/node_modules/aws-cdk-lib/core/lib/private/resolve.js:1:2925) {
  type: 'CfnSynthesisError'
}
```

### Reproduction Steps

I think if you just try to import the template snippet above with CfnInclude that should do it.

I got around this by passing the following to CfnInclude:

```
        let parameters: Record<string, any> = {
            "FlowLogsRetentionInDays": 365,
       }
```

But since 365 is the default value, I should not have to do this.

### CDK CLI Version

2.53.0 (build 7690f43)

### Framework Version

"aws-cdk-lib": "^2.17.0"

### Node.js Version

"^14.18.13"

### OS

AL2

### Language

Typescript

### Language Version

~4.7.4

**Comment by michanto** [comment]
Re-opened because I thought maybe this was my fault, but now I have confirmed it is not my fault.
