### ISSUE TITLE
aws_ec2: grant_attach_volume_by_resource_tag not working

### ISSUE THREAD

**Issue by shcherbak** [aws/aws-cdk#23281]
### Describe the bug

not working python method grant_attach_volume_by_resource_tag
```
attach_grant = volume.grant_attach_volume_by_resource_tag(instance.grant_principal, [instance])
```

described in documentation:
https://docs.aws.amazon.com/cdk/api/v2/python/aws_cdk.aws_ec2/README.html#instances-attaching-volumes-to-themselves
version 2.49 has the same regression, fixed in 2.49.1, and worked fine

the error is

```
Traceback (most recent call last):
  File "/home/dev/work/terraform/cdk/eks/app.py", line 84, in <module>
    test_infra_stack = InfraStack(
  File "/home/dev/work/terraform/cdk/eks/.venv/lib/python3.9/site-packages/jsii/_runtime.py", line 111, in __call__
    inst = super().__call__(*args, **kwargs)
  File "/home/dev/work/terraform/cdk/eks/stacks/infra_stack.py", line 71, in __init__
    Ec2CassandraConstruct(
  File "/home/dev/work/terraform/cdk/eks/.venv/lib/python3.9/site-packages/jsii/_runtime.py", line 111, in __call__
    inst = super().__call__(*args, **kwargs)
  File "/home/dev/work/terraform/cdk/eks/stacks/constructs_l2/ec2_construct.py", line 78, in __init__
    self.grant_attach_volumes_to_instances()
  File "/home/dev/work/terraform/cdk/eks/stacks/constructs_l2/ec2_construct.py", line 152, in grant_attach_volumes_to_instances
    self.volumes[v].grant_attach_volume_by_resource_tag(
  File "/home/dev/work/terraform/cdk/eks/.venv/lib/python3.9/site-packages/aws_cdk/aws_ec2/__init__.py", line 77835, in grant_attach_volume_by_resource_tag
    constructs: typing.Sequence[constructs.Construct],
AttributeError: 'list' object has no attribute 'Construct'
```

### Expected Behavior

creating grant to attach volume for instance by tag

### Current Behavior

runtime error

### Reproduction Steps

create instance ec2.IInstance
create volume ec2.IVolume
try to create grant with grant_attach_volume_by_resource_tag

### CDK CLI Version

2.54.0 (build 9f41881)

### Node.js Version

v16.18.1

### OS

debian 11

### Language

Python

### Language Version

Python 3.9.2

**Comment by shcherbak** [comment]
https://github.com/aws/aws-cdk/issues/22711 - older report of the same problem

**Comment by peterwoodworth** [comment]
Sorry about this @shcherbak

This is likely from the same cause as this https://github.com/aws/aws-cdk/issues/23247#issuecomment-1339887722

CC @RomainMuller @MrArnoldPalmer

**Comment by shcherbak** [comment]
@peterwoodworth our team likes cdk, we try to run automated tests with new lib version as often as we can to troubleshoot possible regressions

**Comment by shcherbak** [comment]
no updataes?
