### ISSUE TITLE
(cloudformation-diff): diff fails with imported CFN template that uses Fn::If function in a security group rule

### ISSUE THREAD

**Issue by ozeebee** [aws/aws-cdk#23359]
### Describe the bug

I want to create a CDK stack that includes an existing CloudFormation template.
This template has a security group containing a rule that has a condition using `Fn::If` function:
```json
                ...
                "SecurityGroupIngress": [
                    {
                        "Fn::If": [
                            "CreateHTTPSlistener",
                            {
                                "IpProtocol": "tcp",
                                "FromPort": "443",
                                "ToPort": "443",
                                "CidrIp": "0.0.0.0/0"
                            },
                            {
                                "Ref": "AWS::NoValue"
                            }
                        ]
                    },
                ...
```
When trying to use the `diff` command with CDK, I get an error (using verbose flag):

```
Cannot use 'in' operator to search for 'CidrIp' in {"Fn::If":["CreateHTTPSlistener",{"IpProtocol":"tcp","FromPort":"443","ToPort":"443","CidrIp":"0.0.0.0/0"}]}
[14:50:49] TypeError: Cannot use 'in' operator to search for 'CidrIp' in {"Fn::If":["CreateHTTPSlistener",{"IpProtocol":"tcp","FromPort":"443","ToPort":"443","CidrIp":"0.0.0.0/0"}]}
    at findFirst (/Users/ajo/Projects/EPFoundry/ajo/cdk-cdp-wrapper/node_modules/@aws-cdk/cloudformation-diff/lib/network/security-group-rule.ts:124:9)
    at new SecurityGroupRule (/Users/ajo/Projects/EPFoundry/ajo/cdk-cdp-wrapper/node_modules/@aws-cdk/cloudformation-diff/lib/network/security-group-rule.ts:37:9)
    at /Users/ajo/Projects/EPFoundry/ajo/cdk-cdp-wrapper/node_modules/@aws-cdk/cloudformation-diff/lib/network/security-group-changes.ts:105:34
    at Array.map (<anonymous>)
    at SecurityGroupChanges.readInlineRules (/Users/ajo/Projects/EPFoundry/ajo/cdk-cdp-wrapper/node_modules/@aws-cdk/cloudformation-diff/lib/network/security-group-changes.ts:105:18)
    at new SecurityGroupChanges (/Users/ajo/Projects/EPFoundry/ajo/cdk-cdp-wrapper/node_modules/@aws-cdk/cloudformation-diff/lib/network/security-group-changes.ts:26:35)
    at new TemplateDiff (/Users/ajo/Projects/EPFoundry/ajo/cdk-cdp-wrapper/node_modules/@aws-cdk/cloudformation-diff/lib/diff/types.ts:57:33)
    at calculateTemplateDiff (/Users/ajo/Projects/EPFoundry/ajo/cdk-cdp-wrapper/node_modules/@aws-cdk/cloudformation-diff/lib/diff-template.ts:114:10)
    at Object.diffTemplate (/Users/ajo/Projects/EPFoundry/ajo/cdk-cdp-wrapper/node_modules/@aws-cdk/cloudformation-diff/lib/diff-template.ts:43:19)
    at printStackDiff (/Users/ajo/Projects/EPFoundry/ajo/cdk-cdp-wrapper/node_modules/aws-cdk/lib/diff.ts:24:24)
```

### Expected Behavior

A diff of the stack is successfully being rendered.

### Current Behavior

I get this error (using `cdk diff -v`):
```
Cannot use 'in' operator to search for 'CidrIp' in {"Fn::If":["CreateHTTPSlistener",{"IpProtocol":"tcp","FromPort":"443","ToPort":"443","CidrIp":"0.0.0.0/0"}]}
[14:50:49] TypeError: Cannot use 'in' operator to search for 'CidrIp' in {"Fn::If":["CreateHTTPSlistener",{"IpProtocol":"tcp","FromPort":"443","ToPort":"443","CidrIp":"0.0.0.0/0"}]}
    at findFirst (/Users/ajo/Projects/EPFoundry/ajo/cdk-cdp-wrapper/node_modules/@aws-cdk/cloudformation-diff/lib/network/security-group-rule.ts:124:9)
    at new SecurityGroupRule (/Users/ajo/Projects/EPFoundry/ajo/cdk-cdp-wrapper/node_modules/@aws-cdk/cloudformation-diff/lib/network/security-group-rule.ts:37:9)
    at /Users/ajo/Projects/EPFoundry/ajo/cdk-cdp-wrapper/node_modules/@aws-cdk/cloudformation-diff/lib/network/security-group-changes.ts:105:34
    at Array.map (<anonymous>)
    at SecurityGroupChanges.readInlineRules (/Users/ajo/Projects/EPFoundry/ajo/cdk-cdp-wrapper/node_modules/@aws-cdk/cloudformation-diff/lib/network/security-group-changes.ts:105:18)
    at new SecurityGroupChanges (/Users/ajo/Projects/EPFoundry/ajo/cdk-cdp-wrapper/node_modules/@aws-cdk/cloudformation-diff/lib/network/security-group-changes.ts:26:35)
    at new TemplateDiff (/Users/ajo/Projects/EPFoundry/ajo/cdk-cdp-wrapper/node_modules/@aws-cdk/cloudformation-diff/lib/diff/types.ts:57:33)
    at calculateTemplateDiff (/Users/ajo/Projects/EPFoundry/ajo/cdk-cdp-wrapper/node_modules/@aws-cdk/cloudformation-diff/lib/diff-template.ts:114:10)
    at Object.diffTemplate (/Users/ajo/Projects/EPFoundry/ajo/cdk-cdp-wrapper/node_modules/@aws-cdk/cloudformation-diff/lib/diff-template.ts:43:19)
    at printStackDiff (/Users/ajo/Projects/EPFoundry/ajo/cdk-cdp-wrapper/node_modules/aws-cdk/lib/diff.ts:24:24)
```

### Reproduction Steps

Importing this sample CFN stack (using `CfnInclude`) causes the error:
```json
{
  "AWSTemplateFormatVersion": "2010-09-09",
  "Description": "reproducer for CDK bug related to diff",
  "Parameters": {
    "HTTPSlistener": {
      "Description": "Create an HTTPS listener?",
      "Type": "String",
      "Default": "false",
      "AllowedValues": [
          "true",
          "false"
      ]
    }
  },
  "Conditions": {
    "CreateHTTPSlistener": {
      "Fn::Equals": [
        {
          "Ref": "HTTPSlistener"
        },
        "true"
      ]
    }
  },
  "Resources": {
    "ELBSecurityGroup": {
      "Type": "AWS::EC2::SecurityGroup",
      "Properties": {
        "GroupDescription": "Test Security Group",
        "VpcId": "vpc-0d2xxxxxxxxxxxxxxxxx",
        "GroupName": "my-sec-group",
        "SecurityGroupIngress": [
          {
            "Fn::If": [
              "CreateHTTPSlistener",
              {
                "IpProtocol": "tcp",
                "FromPort": "443",
                "ToPort": "443",
                "CidrIp": "0.0.0.0/0"
              },
              {
                "Ref": "AWS::NoValue"
              }
            ]
          }
        ]
      }
    }
  }
}
```

### Possible Solution

Looks like the code in diff (`@aws-cdk/cloudformation-diff/lib/network/security-group-rule.ts`) does not expect an `Fn::If` but only Security Group properties.

### CDK CLI Version

2.55.0 (build 077d77d)

### Framework Version

2.55.0

### Node.js Version

18

### OS

macOS 12.6

### Language

Typescript

### Language Version

TypeScript (4.8.4)

**Comment by peterwoodworth** [comment]
Thanks for the report @ozeebee,

It looks to be the same issue as here https://github.com/aws/aws-cdk/issues/7413. Ping me if you disagree 🙂
