### ISSUE TITLE
wafv2: Unable to deserialize value as aws-cdk-lib.aws_wafv2.CfnWebACLProps

### ISSUE THREAD

**Issue by michaela-vid** [aws/aws-cdk#23365]
### Describe the bug

On v2.55.0 trying to create a CfnWebACL fails to synthesize. The code previously worked on past versions. I can confirm v2.49.0 worked, but not a later version as I had a different bug preventing synthesizing in those version.

Below is the stacktrace:
```
Traceback (most recent call last):
  File "../app.py", line 278, in <module>
    waf = WafStack(app, "waf", apigw_restapi=api.rest_api)
  File "../.venv/lib/python3.10/site-packages/jsii/_runtime.py", line 111, in __call__
    inst = super().__call__(*args, **kwargs)
  File "../cdk/waf.py", line 150, in __init__
    web_acl = waf.CfnWebACL(
  File "../.venv/lib/python3.10/site-packages/jsii/_runtime.py", line 111, in __call__
    inst = super().__call__(*args, **kwargs)
  File "../.venv/lib/python3.10/site-packages/aws_cdk/aws_wafv2/__init__.py", line 12126, in __init__
    jsii.create(self.__class__, self, [scope_, id, props])
  File "../.venv/lib/python3.10/site-packages/jsii/_kernel/__init__.py", line 336, in create
    response = self.provider.create(
  File "../.venv/lib/python3.10/site-packages/jsii/_kernel/providers/process.py", line 363, in create
    return self._process.send(request, CreateResponse)
  File "../.venv/lib/python3.10/site-packages/jsii/_kernel/providers/process.py", line 340, in send
    raise RuntimeError(resp.error) from JavaScriptError(resp.stack)
RuntimeError: Passed to parameter props of new aws-cdk-lib.aws_wafv2.CfnWebACL: Unable to deserialize value as aws-cdk-lib.aws_wafv2.CfnWebACLProps
```

Arguments for the WebACL:
```
        web_acl = waf.CfnWebACL(
            self,
            "WebAcl",
            default_action=waf.CfnWebACL.DefaultActionProperty(allow={}),
            scope="REGIONAL", 
            visibility_config=waf.CfnWebACL.VisibilityConfigProperty(
                cloud_watch_metrics_enabled=True,
                metric_name=waf_name,
                sampled_requests_enabled=True),
            description=f"Protects {apigw_restapi.rest_api_name} "
            "API Gateway stage "
            f"{apigw_restapi.deployment_stage.stage_name}",
            name=waf_name,
            rules=waf_rules)
```
where waf_name is a string and waf_rules are a list of waf.CfnWebACL.RuleProperty. aws_wafv2 is imported as waf

Here are the waf_rule causing the issue:
```
        match_rules = waf.CfnWebACL.RuleProperty(
            name="foobarRule",
            priority=1,
            action=waf.CfnWebACL.RuleActionProperty(allow={}),
            statement=waf.CfnWebACL.StatementProperty(
                byte_match_statement=waf.CfnWebACL.ByteMatchStatementProperty(
                    field_to_match=waf.CfnWebACL.FieldToMatchProperty(
                        single_header={"Name": "foo"}),
                    positional_constraint="STARTS_WITH",
                    text_transformations=[
                        waf.CfnWebACL.TextTransformationProperty(priority=1,
                                                                 type="NONE")
                    ],
                    search_string="bar",
                )),
            visibility_config=waf.CfnWebACL.VisibilityConfigProperty(
                cloud_watch_metrics_enabled=True,
                metric_name="foobarRule",
                sampled_requests_enabled=True,
            ),
        )
```

### Expected Behavior

The code should synthesize

### Current Behavior

The code does not synthesize

### Reproduction Steps

1) Attempt to create a web acl using the CDK with the parameters described above
2) Run `cdk synth`
3) Synth fails

### Additional Information/Context

Here is the entire error output:
```
jsii.errors.JavaScriptError: 
  @jsii/kernel.SerializationError: Passed to parameter props of new aws-cdk-lib.aws_wafv2.CfnWebACL: Unable to deserialize value as aws-cdk-lib.aws_wafv2.CfnWebACLProps
  ├── 🛑 Failing value is an object
  │      { '$jsii.struct': [Object] }
  ╰── 🔍 Failure reason(s):
      ╰─ Key 'rules': Unable to deserialize value as aws-cdk-lib.IResolvable | array<aws-cdk-lib.aws_wafv2.CfnWebACL.RuleProperty | aws-cdk-lib.IResolvable> | undefined
          ├── 🛑 Failing value is an array
          │      [ [Object], [Object], [Object], [Object], [Object] ]
          ╰── 🔍 Failure reason(s):
              ├─ [as array<aws-cdk-lib.aws_wafv2.CfnWebACL.RuleProperty | aws-cdk-lib.IResolvable>] Index 0: Unable to deserialize value as aws-cdk-lib.aws_wafv2.CfnWebACL.RuleProperty | aws-cdk-lib.IResolvable
                  ├── 🛑 Failing value is an object
                  │      { '$jsii.struct': [Object] }
                  ╰── 🔍 Failure reason(s):
                      ├─ [as aws-cdk-lib.aws_wafv2.CfnWebACL.RuleProperty] Key 'statement': Unable to deserialize value as aws-cdk-lib.aws_wafv2.CfnWebACL.StatementProperty | aws-cdk-lib.IResolvable
                          ├── 🛑 Failing value is an object
                          │      { '$jsii.struct': [Object] }
                          ╰── 🔍 Failure reason(s):
                              ├─ [as aws-cdk-lib.aws_wafv2.CfnWebACL.StatementProperty] Key 'byteMatchStatement': Unable to deserialize value as aws-cdk-lib.aws_wafv2.CfnWebACL.ByteMatchStatementProperty | aws-cdk-lib.IResolvable | undefined
                                  ├── 🛑 Failing value is an object
                                  │      { '$jsii.struct': [Object] }
                                  ╰── 🔍 Failure reason(s):
                                      ├─ [as aws-cdk-lib.aws_wafv2.CfnWebACL.ByteMatchStatementProperty] Key 'fieldToMatch': Unable to deserialize value as aws-cdk-lib.aws_wafv2.CfnWebACL.FieldToMatchProperty | aws-cdk-lib.IResolvable
                                          ├── 🛑 Failing value is an object
                                          │      { '$jsii.struct': [Object] }
                                          ╰── 🔍 Failure reason(s):
                                              ├─ [as aws-cdk-lib.aws_wafv2.CfnWebACL.FieldToMatchProperty] Key 'singleHeader': Unable to deserialize value as aws-cdk-lib.aws_wafv2.CfnWebACL.SingleHeaderProperty | aws-cdk-lib.IResolvable | undefined
                                                  ├── 🛑 Failing value is an object
                                                  │      { '$jsii.map': [Object] }
                                                  ╰── 🔍 Failure reason(s):
                                                      ├─ [as aws-cdk-lib.aws_wafv2.CfnWebACL.SingleHeaderProperty] Missing required properties for aws-cdk-lib.aws_wafv2.CfnWebACL.SingleHeaderProperty: 'name'
                                                      ╰─ [as aws-cdk-lib.IResolvable] Value does not have the "$jsii.byref" key
                                              ╰─ [as aws-cdk-lib.IResolvable] Value does not have the "$jsii.byref" key
                                      ╰─ [as aws-cdk-lib.IResolvable] Value does not have the "$jsii.byref" key
                              ╰─ [as aws-cdk-lib.IResolvable] Value does not have the "$jsii.byref" key
                      ╰─ [as aws-cdk-lib.IResolvable] Value does not have the "$jsii.byref" key
              ╰─ [as aws-cdk-lib.IResolvable] Value does not have the "$jsii.byref" key
      at Object.process (/tmp/tmp6t85xtwn/lib/program.js:9350:19)
      at Kernel._toSandbox (/tmp/tmp6t85xtwn/lib/program.js:8363:29)
      at /tmp/tmp6t85xtwn/lib/program.js:8393:42
      at Array.map (<anonymous>)
      at Kernel._boxUnboxParameters (/tmp/tmp6t85xtwn/lib/program.js:8393:27)
      at Kernel._toSandboxValues (/tmp/tmp6t85xtwn/lib/program.js:8379:29)
      at Kernel._create (/tmp/tmp6t85xtwn/lib/program.js:8022:46)
      at Kernel.create (/tmp/tmp6t85xtwn/lib/program.js:7751:29)
      at KernelHost.processRequest (/tmp/tmp6t85xtwn/lib/program.js:11037:36)
      at KernelHost.run (/tmp/tmp6t85xtwn/lib/program.js:10997:22)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "../app.py", line 278, in <module>
    waf = WafStack(app, "waf", apigw_restapi=api.rest_api)
  File "../.venv/lib/python3.10/site-packages/jsii/_runtime.py", line 111, in __call__
    inst = super().__call__(*args, **kwargs)
  File "../cdk/waf.py", line 150, in __init__
    web_acl = waf.CfnWebACL(
  File "../.venv/lib/python3.10/site-packages/jsii/_runtime.py", line 111, in __call__
    inst = super().__call__(*args, **kwargs)
  File "../.venv/lib/python3.10/site-packages/aws_cdk/aws_wafv2/__init__.py", line 12126, in __init__
    jsii.create(self.__class__, self, [scope_, id, props])
  File "../.venv/lib/python3.10/site-packages/jsii/_kernel/__init__.py", line 336, in create
    response = self.provider.create(
  File "../.venv/lib/python3.10/site-packages/jsii/_kernel/providers/process.py", line 363, in create
    return self._process.send(request, CreateResponse)
  File "../.venv/lib/python3.10/site-packages/jsii/_kernel/providers/process.py", line 340, in send
    raise RuntimeError(resp.error) from JavaScriptError(resp.stack)
RuntimeError: Passed to parameter props of new aws-cdk-lib.aws_wafv2.CfnWebACL: Unable to deserialize value as aws-cdk-lib.aws_wafv2.CfnWebACLProps
├── 🛑 Failing value is an object
│      { '$jsii.struct': [Object] }
╰── 🔍 Failure reason(s):
    ╰─ Key 'rules': Unable to deserialize value as aws-cdk-lib.IResolvable | array<aws-cdk-lib.aws_wafv2.CfnWebACL.RuleProperty | aws-cdk-lib.IResolvable> | undefined
        ├── 🛑 Failing value is an array
        │      [ [Object], [Object], [Object], [Object], [Object] ]
        ╰── 🔍 Failure reason(s):
            ├─ [as array<aws-cdk-lib.aws_wafv2.CfnWebACL.RuleProperty | aws-cdk-lib.IResolvable>] Index 0: Unable to deserialize value as aws-cdk-lib.aws_wafv2.CfnWebACL.RuleProperty | aws-cdk-lib.IResolvable
                ├── 🛑 Failing value is an object
                │      { '$jsii.struct': [Object] }
                ╰── 🔍 Failure reason(s):
                    ├─ [as aws-cdk-lib.aws_wafv2.CfnWebACL.RuleProperty] Key 'statement': Unable to deserialize value as aws-cdk-lib.aws_wafv2.CfnWebACL.StatementProperty | aws-cdk-lib.IResolvable
                        ├── 🛑 Failing value is an object
                        │      { '$jsii.struct': [Object] }
                        ╰── 🔍 Failure reason(s):
                            ├─ [as aws-cdk-lib.aws_wafv2.CfnWebACL.StatementProperty] Key 'byteMatchStatement': Unable to deserialize value as aws-cdk-lib.aws_wafv2.CfnWebACL.ByteMatchStatementProperty | aws-cdk-lib.IResolvable | undefined
                                ├── 🛑 Failing value is an object
                                │      { '$jsii.struct': [Object] }
                                ╰── 🔍 Failure reason(s):
                                    ├─ [as aws-cdk-lib.aws_wafv2.CfnWebACL.ByteMatchStatementProperty] Key 'fieldToMatch': Unable to deserialize value as aws-cdk-lib.aws_wafv2.CfnWebACL.FieldToMatchProperty | aws-cdk-lib.IResolvable
                                        ├── 🛑 Failing value is an object
                                        │      { '$jsii.struct': [Object] }
                                        ╰── 🔍 Failure reason(s):
                                            ├─ [as aws-cdk-lib.aws_wafv2.CfnWebACL.FieldToMatchProperty] Key 'singleHeader': Unable to deserialize value as aws-cdk-lib.aws_wafv2.CfnWebACL.SingleHeaderProperty | aws-cdk-lib.IResolvable | undefined
                                                ├── 🛑 Failing value is an object
                                                │      { '$jsii.map': [Object] }
                                                ╰── 🔍 Failure reason(s):
                                                    ├─ [as aws-cdk-lib.aws_wafv2.CfnWebACL.SingleHeaderProperty] Missing required properties for aws-cdk-lib.aws_wafv2.CfnWebACL.SingleHeaderProperty: 'name'
                                                    ╰─ [as aws-cdk-lib.IResolvable] Value does not have the "$jsii.byref" key
                                            ╰─ [as aws-cdk-lib.IResolvable] Value does not have the "$jsii.byref" key
                                    ╰─ [as aws-cdk-lib.IResolvable] Value does not have the "$jsii.byref" key
                            ╰─ [as aws-cdk-lib.IResolvable] Value does not have the "$jsii.byref" key
                    ╰─ [as aws-cdk-lib.IResolvable] Value does not have the "$jsii.byref" key
            ╰─ [as aws-cdk-lib.IResolvable] Value does not have the "$jsii.byref" key

```

It appears to have an issue with the single header property value being "Name" instead of "name".

### CDK CLI Version

2.54.0

### Node.js Version

16.14.2

### OS

Ubuntu 22.04.1 LTS

### Language

Python

### Language Version

3.10.6

**Comment by michaela-vid** [comment]
I can confirm that changing the single header name from Name to lowercase name, fixes the issue. Apologies for opening the bug before attempting that. 

The documentation needs updated to include this information, as some of the examples still show "Name" being used.

**Comment by peterwoodworth** [comment]
This is copied directly from the [CloudFormation docs](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-wafv2-webacl-fieldtomatch.html#cfn-wafv2-webacl-fieldtomatch-singleheader). At the bottom of the page you can click the "Provide Feedback" button, and it will go to the people who are able to fix this 🙂 The change should then be propagated through to our docs

Thanks for pointing this out!

**Comment by michaela-vid** [comment]
@peterwoodworth Thanks! I submitted feedback, but it also seems to be working again with v2.58.1. I'll close this issue.
