### ISSUE TITLE
aws_cdk.aws_certificatemanager.DnsValidatedCertificate depends on deprecated nodejs10.x runtime

### ISSUE THREAD

**Issue by anthonymobile** [aws/aws-cdk#23492]
### Describe the bug

Attempting to deploy cdk stack with python v2 API using aws_cdk.aws_certificatemanager.DnsValidatedCertificate construct causes error creating CertificateRequestorFunction due to deprecated nodejs10.x runtime referenced.

### Expected Behavior

Expected certificate object returned without error.

### Current Behavior

```
12:33:48 AM | CREATE_FAILED        | AWS::Lambda::Function               | NJTSignRailLambdaH...orFunction2F307167
Resource handler returned message: "The runtime parameter of nodejs10.x is no longer supported for creating or updating AWS Lambda functions. We recommend you use the new runtime (nodejs16.x) while
creating or updating functions. (Service: Lambda, Status Code: 400, Request ID: 3bb15d2f-a5e5-414b-aa83-6502d185bdd7)" (RequestToken: 852a0284-1ff8-44f2-c918-db3cba89651e, HandlerErrorCode: InvalidR
equest)

        new Function (/private/var/folders/lq/z1mjp6ls4ds6dd2r7zcll2q00000gn/T/jsii-kernel-K92MJk/node_modules/@aws-cdk/aws-lambda/lib/function.js:127:26)
        \_ new DnsValidatedCertificate (/private/var/folders/lq/z1mjp6ls4ds6dd2r7zcll2q00000gn/T/jsii-kernel-K92MJk/node_modules/@aws-cdk/aws-certificatemanager/lib/dns-validated-certificate.js:31:35)he following resource(s) failed to create: [NJTSignRailLambdaHandlerCertificateCertificateRequestorFunction2F307167]. Rollback requested by user.
        \_ Kernel._create (/private/var/folders/lq/z1mjp6ls4ds6dd2r7zcll2q00000gn/T/tmpcp9w6s76/lib/program.js:8022:29)
        \_ Kernel.create (/private/var/folders/lq/z1mjp6ls4ds6dd2r7zcll2q00000gn/T/tmpcp9w6s76/lib/program.js:7751:29)
        \_ KernelHost.processRequest (/private/var/folders/lq/z1mjp6ls4ds6dd2r7zcll2q00000gn/T/tmpcp9w6s76/lib/program.js:11037:36)
        \_ KernelHost.run (/private/var/folders/lq/z1mjp6ls4ds6dd2r7zcll2q00000gn/T/tmpcp9w6s76/lib/program.js:10997:22)
        \_ Immediate._onImmediate (/private/var/folders/lq/z1mjp6ls4ds6dd2r7zcll2q00000gn/T/tmpcp9w6s76/lib/program.js:10998:46)
        \_ process.processImmediate (node:internal/timers:471:21)


 ❌  njtsign-rail-stack failed: Error: The stack named njtsign-rail-stack failed creation, it may need to be manually deleted from the AWS console: ROLLBACK_COMPLETE: Resource handler returned message: "The runtime parameter of nodejs10.x is no longer supported for creating or updating AWS Lambda functions. We recommend you use the new runtime (nodejs16.x) while creating or updating functions. (Service: Lambda, Status Code: 400, Request ID: 3bb15d2f-a5e5-414b-aa83-6502d185bdd7)" (RequestToken: 852a0284-1ff8-44f2-c918-db3cba89651e, HandlerErrorCode: InvalidRequest)
    at FullCloudFormationDeployment.monitorDeployment (/Users/anthonytownsend/.nvm/versions/node/v18.12.0/lib/node_modules/aws-cdk/lib/api/deploy-stack.ts:505:13)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at deployStack2 (/Users/anthonytownsend/.nvm/versions/node/v18.12.0/lib/node_modules/aws-cdk/lib/cdk-toolkit.ts:265:24)
    at /Users/anthonytownsend/.nvm/versions/node/v18.12.0/lib/node_modules/aws-cdk/lib/deploy.ts:39:11
    at run (/Users/anthonytownsend/.nvm/versions/node/v18.12.0/lib/node_modules/p-queue/dist/index.js:163:29)

 ❌ Deployment failed: Error: Stack Deployments Failed: Error: The stack named njtsign-rail-stack failed creation, it may need to be manually deleted from the AWS console: ROLLBACK_COMPLETE: Resource handler returned message: "The runtime parameter of nodejs10.x is no longer supported for creating or updating AWS Lambda functions. We recommend you use the new runtime (nodejs16.x) while creating or updating functions. (Service: Lambda, Status Code: 400, Request ID: 3bb15d2f-a5e5-414b-aa83-6502d185bdd7)" (RequestToken: 852a0284-1ff8-44f2-c918-db3cba89651e, HandlerErrorCode: InvalidRequest)
    at deployStacks (/Users/anthonytownsend/.nvm/versions/node/v18.12.0/lib/node_modules/aws-cdk/lib/deploy.ts:61:11)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at CdkToolkit.deploy (/Users/anthonytownsend/.nvm/versions/node/v18.12.0/lib/node_modules/aws-cdk/lib/cdk-toolkit.ts:339:7)
    at initCommandLine (/Users/anthonytownsend/.nvm/versions/node/v18.12.0/lib/node_modules/aws-cdk/lib/cli.ts:374:12)

Stack Deployments Failed: Error: The stack named njtsign-rail-stack failed creation, it may need to be manually deleted from the AWS console: ROLLBACK_COMPLETE: Resource handler returned message: "The runtime parameter of nodejs10.x is no longer supported for creating or updating AWS Lambda functions. We recommend you use the new runtime (nodejs16.x) while creating or updating functions. (Service: Lambda, Status Code: 400, Request ID: 3bb15d2f-a5e5-414b-aa83-6502d185bdd7)" (RequestToken: 852a0284-1ff8-44f2-c918-db3cba89651e, HandlerErrorCode: InvalidRequest)
```

### Reproduction Steps

```
from aws_cdk import (
    aws_route53 as route53,
    aws_certificatemanager as acm,
    core
)

import lambda_fns.config as cfg

class NJTSignStack(core.Stack):
    def __init__(self, scope: core.Construct, id: str, **kwargs) -> None:
        super().__init__(scope, id, **kwargs)

        # get the hosted zone
        hosted_zone = route53.HostedZone.from_lookup(
            self,
            "HostedZone",
            domain_name=cfg.domain
            )

        # create certificate
        certificate = acm.DnsValidatedCertificate(
            self,
            "NJTSignRail_LambdaHandler_Certificate",
            domain_name=f"{cfg.subdomain}.{cfg.domain}",
            hosted_zone=hosted_zone,
            region="us-east-1"
            )
```

### CDK CLI Version

2.56.1 (build 9329a73)

### Node.js Version

18.12.0

### OS

OSX 13.0.1

### Language

Python

### Language Version

3.9.15

**Comment by peterwoodworth** [comment]
We've updated all our functions a while ago to move off the deprecated versions - I'm unable to reproduce this. Please make sure your environment is fully updated to use `2.56.1`, thanks!

**Comment by anthonymobile** [comment]
defintely using current CDK.
```
/Users/anthonytownsend: cdk --version
2.56.1 (build 9329a73)
```

any other ideas on what's going on?

**Comment by anthonymobile** [comment]
found the error, was related to re-using a CDK project from a public github repo. re-created using `cdk init` and deployment worked as expected.

**Comment by 0xdevalias** [comment]
> We've updated all our functions a while ago to move off the deprecated versions - I'm unable to reproduce this. Please make sure your environment is fully updated to use `2.56.1`, thanks!

I'll go and try to find the answer to this myself, but do you know if this fix was ever backported to the AWS CDK `1.x` versions as well? I'm using `1.201.0` (as an interim step towards upgrading to `2.x` and running into this issue.

Worst case I can generate an override to the generated CloudFormation as a workaround till I get to `2.x`.
