### ISSUE TITLE
(aws_elasticloadbalancing): add classic load balancer support for EC2 instance 

### ISSUE THREAD

**Issue by LucasSymons** [aws/aws-cdk#23500]
### Describe the bug

Trying to attach a single EC2 instance to a classic ELB when using the add target method, I get an error

##Method
```python
elb.add_target(instance.instance_id)
```

## Docs
https://docs.aws.amazon.com/cdk/api/v2/python/aws_cdk.aws_elasticloadbalancing/LoadBalancer.html#aws_cdk.aws_elasticloadbalancing.LoadBalancer.add_target

## Error
```
jsii.errors.JavaScriptError: 
  @jsii/kernel.RuntimeError: TypeError: target.attachToClassicLB is not a function
      at Kernel._ensureSync (/private/var/folders/72/tttvxd_17gz67dmn1zlcbx7m0000gn/T/tmp4b19xcp3/lib/program.js:8427:27)
      at Kernel.invoke (/private/var/folders/72/tttvxd_17gz67dmn1zlcbx7m0000gn/T/tmp4b19xcp3/lib/program.js:7827:34)
      at KernelHost.processRequest (/private/var/folders/72/tttvxd_17gz67dmn1zlcbx7m0000gn/T/tmp4b19xcp3/lib/program.js:11037:36)
      at KernelHost.run (/private/var/folders/72/tttvxd_17gz67dmn1zlcbx7m0000gn/T/tmp4b19xcp3/lib/program.js:10997:22)
      at Immediate._onImmediate (/private/var/folders/72/tttvxd_17gz67dmn1zlcbx7m0000gn/T/tmp4b19xcp3/lib/program.js:10998:46)
      at process.processImmediate (node:internal/timers:471:21)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Documents/repo/base-aws-cloudformation/stacks/gitlab/app.py", line 33, in <module>
    ec2 = GitlabStack(app, 'Gitlab-EC2', props=props, env=Environment(
  File "/.local/share/virtualenvs/gitlab-qBbXTgKn/lib/python3.10/site-packages/jsii/_runtime.py", line 111, in __call__
    inst = super().__call__(*args, **kwargs)
  File "/Documents/repo/base-aws-cloudformation/stacks/gitlab/gitlab/gitlab_ec2.py", line 177, in __init__
    gitlab_elb.add_target(gitlab_instance)
  File "/.local/share/virtualenvs/gitlab-qBbXTgKn/lib/python3.10/site-packages/aws_cdk/aws_elasticloadbalancing/__init__.py", line 2399, in add_target
    return typing.cast(None, jsii.invoke(self, "addTarget", [target]))
  File "/.local/share/virtualenvs/gitlab-qBbXTgKn/lib/python3.10/site-packages/jsii/_kernel/__init__.py", line 149, in wrapped
    return _recursize_dereference(kernel, fn(kernel, *args, **kwargs))
  File "/.local/share/virtualenvs/gitlab-qBbXTgKn/lib/python3.10/site-packages/jsii/_kernel/__init__.py", line 401, in invoke
    response = self.provider.invoke(
  File "/.local/share/virtualenvs/gitlab-qBbXTgKn/lib/python3.10/site-packages/jsii/_kernel/providers/process.py", line 378, in invoke
    return self._process.send(request, InvokeResponse)
  File "/.local/share/virtualenvs/gitlab-qBbXTgKn/lib/python3.10/site-packages/jsii/_kernel/providers/process.py", line 340, in send
    raise RuntimeError(resp.error) from JavaScriptError(resp.stack)
RuntimeError: TypeError: target.attachToClassicLB is not a function

Subprocess exited with error 1
```

### Expected Behavior

I expected to be able to register a single instance as the target for the ELB

### Current Behavior

Error posted above

### Reproduction Steps

```
# vpc: ec2.IVpc

# my_instance: ec2.Instance

lb = elb.LoadBalancer(self, "LB",
    vpc=vpc,
    internet_facing=True,
    health_check=elb.HealthCheck(
        port=80
    )
)
lb.add_target(my_instance)
```

### Possible Solution

I found a post suggesting a possible workaround but it is untested
        
```
# https://stackoverflow.com/a/68632192
        elbObj = elb.node.default_child
        if elbObj:
            elbObj.instances = [instance.instance_id, ]
```

### CDK CLI Version

2.58.0 (build 4a577f3)

### Framework Version

aws-cdk-lib = "==2.54.0"

### Node.js Version

node --version v18.1.0

### OS

MacOS Ventura 13.1 (22C65)

### Language

Python

### Language Version

Python 3.10.9

**Comment by peterwoodworth** [comment]
The `addTarget` method is designed to work on constructs which implement [`ILoadBalancerTarget`.](https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_elasticloadbalancing.ILoadBalancerTarget.html) EC2's Instance doesn't implement this, so this method isn't intended to be working here. At least yet, this is definitely something we could support.

Please try the escape hatch method described until support is provided for this. 

I am marking this issue as p2, which means that we are unable to work on this immediately.

We use +1s to help prioritize our work, and are happy to revaluate this issue based on community feedback. You can reach out to the cdk.dev community on [Slack](https://cdk.dev) to solicit support for reprioritization.

Check out our [contributing guide](https://github.com/aws/aws-cdk/blob/master/CONTRIBUTING.md) if you're interested in contributing yourself - there's a low chance the team will be able to address this soon but we can try to review a PR 🙂

**Comment by zorrofox** [comment]
We know that [ILoadBalancerTarget.](https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_elasticloadbalancing.ILoadBalancerTarget.html) only have the `addTarget` method, and if we add the [Instance](https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_ec2.Instance.html) to support this method too we need implement this method to pick up one of the `elb.LoadBalancer` `targets` which is an array and how we implement this logic? And if there have no `targets` exists do we need create a new one?
