### ISSUE TITLE
aws_s3_deployment: UserDefinedObjectMetadata does not work as documented

### ISSUE THREAD

**Issue by cvmeq** [aws/aws-cdk#23577]
### Describe the bug

Hello, I'm trying to have user-defined metadata in an S3 Deployment using `UserDefinedObjectMetadata` however it doesn't seem to work. Details below.

### Expected Behavior

Successful synthetization of the stack where the S3 Deployment is implemented.

### Current Behavior

Stack is not synthesized due to a `TypeError`:

~~~
Traceback (most recent call last):
  File "/home/cvmeq/cdk-project/app.py", line 10, in <module>
    CdkProjectStack(app, "CdkProjectStack",
  File "/home/cvmeq/cdk-project/.venv/lib/python3.10/site-packages/jsii/_runtime.py", line 111, in __call__
    inst = super().__call__(*args, **kwargs)
  File "/home/cvmeq/cdk-project/cdk_project/cdk_project_stack.py", line 23, in __init__
    metadata=s3deploy.UserDefinedObjectMetadata(A="1", b="2"),  # user-defined metadata
TypeError: UserDefinedObjectMetadata.__init__() got an unexpected keyword argument 'A'

Subprocess exited with error 1
~~~

### Reproduction Steps

Create a Python project:

~~~
mkdir cdk-project
cd cdk-project
cdk init app --language python
source .venv/bin/activate
python -m pip install -r requirements.txt
~~~

No changes in the default `app.py` required. Change `cdk_project/cdk_project_stack.py` to match the following:

~~~python
from aws_cdk import (
    Duration,
    Stack,
    aws_s3 as s3,
    aws_s3_deployment as s3deploy
)
from constructs import Construct

class CdkProjectStack(Stack):

    def __init__(self, scope: Construct, construct_id: str, **kwargs) -> None:
        super().__init__(scope, construct_id, **kwargs)

        website_bucket = s3.Bucket(self, "WebsiteBucket",
            website_index_document="index.html",
            public_read_access=True
        )

        s3deploy.BucketDeployment(self, "DeployWebsite",
            sources=[s3deploy.Source.asset("./website-dist")],
            destination_bucket=website_bucket,
            destination_key_prefix="web/static",  # optional prefix in destination bucket
            metadata=s3deploy.UserDefinedObjectMetadata(A="1", b="2"),  # user-defined metadata

            # system-defined metadata
            content_type="text/html",
            content_language="en",
            storage_class=s3deploy.StorageClass.INTELLIGENT_TIERING,
            server_side_encryption=s3deploy.ServerSideEncryption.AES_256,
            cache_control=[
                s3deploy.CacheControl.set_public(),
                s3deploy.CacheControl.max_age(Duration.hours(1))
            ],
            access_control=s3.BucketAccessControl.BUCKET_OWNER_FULL_CONTROL
        )
~~~

The code above was copied verbatim from the [documentation](https://docs.aws.amazon.com/cdk/api/v2/python/aws_cdk.aws_s3_deployment/UserDefinedObjectMetadata.html).

Now synthesize the stack to see the problem:

~~~
cdk synth CdkProjectStack
~~~

### CDK CLI Version

2.59.0 (build b24095d)

### Node.js Version

v16.18.0

### OS

Linux Ubuntu 20.04.2 LTS

### Language

Python

### Language Version

Python 3.10.6

### Other information

Python packages that are installed in the virtual environment:

~~~
Package                           Version
--------------------------------- --------
attrs                             22.2.0
aws-cdk.asset-awscli-v1           2.2.49
aws-cdk.asset-kubectl-v20         2.1.1
aws-cdk.asset-node-proxy-agent-v5 2.0.38
aws-cdk-lib                       2.59.0
cattrs                            22.2.0
constructs                        10.1.210
exceptiongroup                    1.1.0
jsii                              1.73.0
pip                               22.2.1
publication                       0.0.3
python-dateutil                   2.8.2
setuptools                        63.2.0
six                               1.16.0
typeguard                         2.13.3
typing_extensions                 4.4.0
~~~

**Comment by peterwoodworth** [comment]
Thanks for reporting this, I was able to reproduce the issue. I wasn't find a way to make this property work in Python... However you can still override the CloudFormation template at the very least.

```
        bucket_deployment = s3d.BucketDeployment(self, "DeployWebsite", ...)
        bucket_deployment.node.children[3].node.default_child.add_property_override('UserMetadata', dict(A=2, B=1))
```

I'm going to transfer this to the JSII repo, as this is a bug with the conversion from TypeScript to Python. Let's see what they say 🙂
