### ISSUE TITLE
aws-lambda: Failed to copy files from docker build

### ISSUE THREAD

**Issue by namse** [aws/aws-cdk#23587]
### Describe the bug

I tried to make lambda with the code from docker build, using method `cdk.aws_lambda.Code.fromDockerBuild`.

In my cases, I uses custom named Dockerfile, `lambda.Dockerfile`.
I could build it in my local with `docker build -f lambda.Dockerfile .`

Github actions failed to run cdk, with below error logs.

### Expected Behavior

It should copy docker image and create lambda

### Current Behavior

Failed with below log

```

Successfully built 0396162b00d1
Successfully tagged cdk-5b49c08a5866[50](https://github.com/code-squad/lucas-review-service/actions/runs/3854128012/jobs/6567784803#step:5:51)93ab02cc2e18c8cb4f2e8ae388910d8ace107d32b14ca1f0b8:latest
Error: No such container:path: 780296f09adbebe4a5e01cbea994aaf1f7e3127fa5c47[51](https://github.com/code-squad/lucas-review-service/actions/runs/3854128012/jobs/6567784803#step:5:52)6f35c0fab627a0a9a:/asset/.
780296f09adbebe4a5e01cbea994aaf1f7e3127fa5c47516f35c0fab627a0a9a

...


Error: Failed to copy files from 780296f09adbebe4a5e01cbea994aaf1f7e3127fa5c47516f35c0fab627a0a9a:/asset/. to /tmp/cdk-docker-cp-fceHcc: Error: docker exited with status 1
    at DockerImage.cp (/home/runner/work/lucas-review-service/lucas-review-service/cdk/node_modules/aws-cdk-lib/core/lib/bundling.js:1:2204)
    at DockerImage.cp (/home/runner/work/lucas-review-service/lucas-review-service/cdk/node_modules/aws-cdk-lib/core/lib/bundling.js:1:4218)
    at Function.fromDockerBuild (/home/runner/work/lucas-review-service/lucas-review-service/cdk/node_modules/aws-cdk-lib/aws-lambda/lib/code.js:1:1715)
    at new ReviewServiceStack (/home/runner/work/lucas-review-service/lucas-review-service/cdk/lib/ReviewServiceStack.ts:24:33)
    at Object.<anonymous> (/home/runner/work/lucas-review-service/lucas-review-service/cdk/bin/cdk.ts:7:1)
    at Module._compile (node:internal/modules/cjs/loader:11[59](https://github.com/code-squad/lucas-review-service/actions/runs/3854128012/jobs/6567784803#step:5:60):14)
    at Module.m._compile (/home/runner/work/lucas-review-service/lucas-review-service/cdk/node_modules/ts-node/src/index.ts:1[61](https://github.com/code-squad/lucas-review-service/actions/runs/3854128012/jobs/6567784803#step:5:62)8:23)
    at Module._extensions..js (node:internal/modules/cjs/loader:1213:10)
    at Object.require.extensions.<computed> [as .ts] (/home/runner/work/lucas-review-service/lucas-review-service/cdk/node_modules/ts-node/src/index.ts:1[62](https://github.com/code-squad/lucas-review-service/actions/runs/3854128012/jobs/6567784803#step:5:63)1:12)
    at Module.load (node:internal/modules/cjs/loader:1037:32)
Subprocess exited with error 1
```

### Reproduction Steps

Create lambda like below

```
    const lambda = new cdk.aws_lambda.Function(this, "Lambda", {
      runtime: cdk.aws_lambda.Runtime.PROVIDED_AL2,
      handler: "Handler.FROM_IMAGE",
      code: cdk.aws_lambda.Code.fromDockerBuild(
        path.join(__dirname, "../../server"),
        {
          file: "lambda.Dockerfile",
        }
      ),
      architecture: cdk.aws_lambda.Architecture.ARM_64,
      environment: {},
      initialPolicy: [],
    });
```

And lambda.Dockerfile in server directory, which is simple nodejs server

```
FROM node:18-alpine

WORKDIR /server

COPY package*.json ./
RUN npm ci

COPY . .

CMD npm start
```

### CDK CLI Version

2.53.0

### Node.js Version

18

### OS

ubuntu

### Language

Typescript

**Comment by namse** [comment]
Nevermind, I misunderstood about fromDockerBuild.
