### ISSUE TITLE
App: new App() throws Error: invalid ConstructNode type

### ISSUE THREAD

**Issue by btakita** [aws/aws-cdk#23706]
### Describe the bug

When calling:

```
new App()
```
the following error occurs.
```
Error: invalid ConstructNode type
    at Function._unwrap (/home/brian/work/portfoliome/censible-core/node_modules/.pnpm/@aws-cdk+core@1.188.0_kdgteyp2dv36ov72z7fyqhg6y4/node_modules/@aws-cdk/core/lib/construct-compat.js:2:2935)
    at new Construct (/home/brian/work/portfoliome/censible-core/node_modules/.pnpm/@aws-cdk+core@1.188.0_kdgteyp2dv36ov72z7fyqhg6y4/node_modules/@aws-cdk/core/lib/construct-compat.js:2:1040)
    at new Stage (/home/brian/work/portfoliome/censible-core/node_modules/.pnpm/@aws-cdk+core@1.188.0_kdgteyp2dv36ov72z7fyqhg6y4/node_modules/@aws-cdk/core/lib/stage.js:2:641)
    at new App (/home/brian/work/portfoliome/censible-core/node_modules/.pnpm/@aws-cdk+core@1.188.0_kdgteyp2dv36ov72z7fyqhg6y4/node_modules/@aws-cdk/core/lib/app.js:2:633)
    at file:///home/brian/work/portfoliome/censible-core/apps/cdk/src/cdk__app_.ts:1:186
    at be (file:///home/brian/work/portfoliome/censible-core/node_modules/.pnpm/@ctx-core+object@23.1.0/node_modules/@ctx-core/object/src/be_/index.js:42:15)
    at file:///home/brian/work/portfoliome/censible-core/apps/cdk/src/mi_cdk__stack.ts:1:1108
    at be (file:///home/brian/work/portfoliome/censible-core/node_modules/.pnpm/@ctx-core+object@23.1.0/node_modules/@ctx-core/object/src/be_/index.js:42:15)
    at file:///home/brian/work/portfoliome/censible-core/apps/cdk/src/mi_cdk__stack.ts:1:1347
    at be (file:///home/brian/work/portfoliome/censible-core/node_modules/.pnpm/@ctx-core+object@23.1.0/node_modules/@ctx-core/object/src/be_/index.js:42:15)
```

### Expected Behavior

Construct an App without an error

### Current Behavior

```
Error: invalid ConstructNode type
    at Function._unwrap (/home/brian/work/portfoliome/censible-core/node_modules/.pnpm/@aws-cdk+core@1.188.0_kdgteyp2dv36ov72z7fyqhg6y4/node_modules/@aws-cdk/core/lib/construct-compat.js:2:2935)
    at new Construct (/home/brian/work/portfoliome/censible-core/node_modules/.pnpm/@aws-cdk+core@1.188.0_kdgteyp2dv36ov72z7fyqhg6y4/node_modules/@aws-cdk/core/lib/construct-compat.js:2:1040)
    at new Stage (/home/brian/work/portfoliome/censible-core/node_modules/.pnpm/@aws-cdk+core@1.188.0_kdgteyp2dv36ov72z7fyqhg6y4/node_modules/@aws-cdk/core/lib/stage.js:2:641)
    at new App (/home/brian/work/portfoliome/censible-core/node_modules/.pnpm/@aws-cdk+core@1.188.0_kdgteyp2dv36ov72z7fyqhg6y4/node_modules/@aws-cdk/core/lib/app.js:2:633)
    at file:///home/brian/work/portfoliome/censible-core/apps/cdk/src/cdk__app_.ts:1:186
    at be (file:///home/brian/work/portfoliome/censible-core/node_modules/.pnpm/@ctx-core+object@23.1.0/node_modules/@ctx-core/object/src/be_/index.js:42:15)
    at file:///home/brian/work/portfoliome/censible-core/apps/cdk/src/mi_cdk__stack.ts:1:1108
    at be (file:///home/brian/work/portfoliome/censible-core/node_modules/.pnpm/@ctx-core+object@23.1.0/node_modules/@ctx-core/object/src/be_/index.js:42:15)
    at file:///home/brian/work/portfoliome/censible-core/apps/cdk/src/mi_cdk__stack.ts:1:1347
    at be (file:///home/brian/work/portfoliome/censible-core/node_modules/.pnpm/@ctx-core+object@23.1.0/node_modules/@ctx-core/object/src/be_/index.js:42:15)
```

### Reproduction Steps

```
import { App } from '@aws-cdk/core'
new App()
```

### Possible Solution

Test & fix the errors.

### CDK CLI Version

1.188.0

### Node.js Version

18.12.1

### OS

Linux

### Language

Typescript

### Language Version

TypeScript (4.9.4)

**Comment by btakita** [comment]
Using classes makes it impossible to set a prop on the object before the constructor is called.

**Comment by btakita** [comment]
Here is a workaround:

```
import { App, ConstructNode } from '@aws-cdk/core'
import { assign, be_ } from '@ctx-core/object'
import constructs from 'constructs'
assign(constructs, { ConstructMetadata: {} })
export const cdk__app_ = be_<App>('cdk__app_', ()=>{
	const { _unwrap } = ConstructNode
	ConstructNode._unwrap = (c:constructs.Node)=>{
		const construct_node = new ConstructNode(c['host'], c.scope as any, c.id)
		console.debug('ConstructNode._unwrap|debug|1', {
			construct_node
		})
		return construct_node
	}
	try {
		const cdk__app = new App()
		return cdk__app
	} finally {
		ConstructNode._unwrap = _unwrap
	}
})
```
The next issue is another error.

```
TypeError: scope?.node.addChild is not a function
    at new Node (/home/brian/work/portfoliome/censible-core/node_modules/.pnpm/constructs@10.1.221/node_modules/constructs/lib/construct.js:2:833)
    at new Construct (/home/brian/work/portfoliome/censible-core/node_modules/.pnpm/constructs@10.1.221/node_modules/constructs/lib/construct.js:2:4732)
    at new Construct (/home/brian/work/portfoliome/censible-core/node_modules/.pnpm/@aws-cdk+core@1.188.0_kdgteyp2dv36ov72z7fyqhg6y4/node_modules/@aws-cdk/core/lib/construct-compat.js:2:774)
    at new TreeMetadata (/home/brian/work/portfoliome/censible-core/node_modules/.pnpm/@aws-cdk+core@1.188.0_kdgteyp2dv36ov72z7fyqhg6y4/node_modules/@aws-cdk/core/lib/private/tree-metadata.js:2:653)
    at new App (/home/brian/work/portfoliome/censible-core/node_modules/.pnpm/@aws-cdk+core@1.188.0_kdgteyp2dv36ov72z7fyqhg6y4/node_modules/@aws-cdk/core/lib/app.js:2:1422)
    at file:///home/brian/work/portfoliome/censible-core/apps/cdk/src/cdk__app_.ts:1:425
    at be (file:///home/brian/work/portfoliome/censible-core/node_modules/.pnpm/@ctx-core+object@23.1.0/node_modules/@ctx-core/object/src/be_/index.js:42:15)
    at file:///home/brian/work/portfoliome/censible-core/apps/cdk/src/mi_cdk__stack.ts:1:1108
    at be (file:///home/brian/work/portfoliome/censible-core/node_modules/.pnpm/@ctx-core+object@23.1.0/node_modules/@ctx-core/object/src/be_/index.js:42:15)
    at file:///home/brian/work/portfoliome/censible-core/apps/cdk/src/mi_cdk__stack.ts:1:1347
```

**Comment by btakita** [comment]
To fix the error above, I added `addChild` to the ConstructNode:

```
import { App, ConstructNode } from '@aws-cdk/core'
import { assign, be_ } from '@ctx-core/object'
import constructs, { Node } from 'constructs'
assign(constructs, { ConstructMetadata: {} })
export const cdk__app_ = be_<App>('cdk__app_', ()=>{
	const { _unwrap } = ConstructNode
	ConstructNode._unwrap = (c:constructs.Node)=>{
		const host = c['host']
		const scope = c.scope
		const construct_node = new ConstructNode(host, scope as any, c.id)
		construct_node['addChild'] = Node.prototype['addChild']
		return construct_node
	}
	try {
		const cdk__app = new App({ treeMetadata: false })
		return cdk__app
	} finally {
		ConstructNode._unwrap = _unwrap
	}
})
```

**Comment by pahud** [comment]
HI @btakita 

I don't think this will return the error.

```ts
import { App } from '@aws-cdk/core'
new App()
```

Do you have any existing repo with minimal required code that I can clone and reproduce in my account?
