### ISSUE TITLE
aws-managedblockchain: [ValidationError]: Template format error: Unrecognized resource types: [AWS::ManagedBlockchain::Node]

### ISSUE THREAD

**Issue by sempfa** [aws/aws-cdk#23745]
### Describe the bug

when running CDK deploy on simple stack that only contains CfnNode from aws-cdk-lib/aws-managedblockchain 
and cfnOutput  to output nodeId once deployed.

Get error: [ValidationError]: Template format error: Unrecognized resource types: [AWS::ManagedBlockchain::Node]

### Expected Behavior

expect AMB node to be deployed and OutPut of NodeId

### Current Behavior

Stack fail to deploy due to validation error, from unrecognized resource types: AWS::ManagedBlockchain::Node

### Reproduction Steps

create AMB Stack as only stack in CDK app

cdk.ts
```
const app = new cdk.App();
new AmbStack(app, 'AmbStack');
```

AmbStack.ts
```
export class AmbStack extends Stack {
  constructor(scope: Construct, id: string, props?: StackProps) {
    super(scope, id, props);

      const cfnNode = new amb.CfnNode(this, "EthereumNode", {
        networkId: "n-ethereum-goerli",
        nodeConfiguration: {
          availabilityZone: "us-east-1a",
          instanceType: "bc.t3.large",
        },
      });

      new CfnOutput(this, "NodeId", {
        value: cfnNode.attrNodeId,
        description: "Ethereum Node ID",
        exportName: "NodeId"
      })
  }
}
```

run command> `cdk deploy`

### Additional Information/Context

Error from console =:

```
AmbStack failed: Error [ValidationError]: Template format error: Unrecognized resource types: [AWS::ManagedBlockchain::Node]
    at Request.extractError (/Users/sempfa/.nvm/versions/node/v19.0.1/lib/node_modules/aws-sdk/lib/protocol/query.js:50:29)
    at Request.callListeners (/Users/sempfa/.nvm/versions/node/v19.0.1/lib/node_modules/aws-sdk/lib/sequential_executor.js:106:20)
    at Request.emit (/Users/sempfa/.nvm/versions/node/v19.0.1/lib/node_modules/aws-sdk/lib/sequential_executor.js:78:10)
    at Request.emit (/Users/sempfa/.nvm/versions/node/v19.0.1/lib/node_modules/aws-sdk/lib/request.js:686:14)
    at Request.transition (/Users/sempfa/.nvm/versions/node/v19.0.1/lib/node_modules/aws-sdk/lib/request.js:22:10)
    at AcceptorStateMachine.runTo (/Users/sempfa/.nvm/versions/node/v19.0.1/lib/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at /Users/sempfa/.nvm/versions/node/v19.0.1/lib/node_modules/aws-sdk/lib/state_machine.js:26:10
    at Request.<anonymous> (/Users/sempfa/.nvm/versions/node/v19.0.1/lib/node_modules/aws-sdk/lib/request.js:38:9)
    at Request.<anonymous> (/Users/sempfa/.nvm/versions/node/v19.0.1/lib/node_modules/aws-sdk/lib/request.js:688:12)
    at Request.callListeners (/Users/sempfa/.nvm/versions/node/v19.0.1/lib/node_modules/aws-sdk/lib/sequential_executor.js:116:18) {
  code: 'ValidationError',
  time: 2023-01-19T03:03:04.860Z,
  requestId: '64bc4a36-9ada-4fab-9b86-746cb9cca89d',
  statusCode: 400,
  retryable: false,
  retryDelay: 341.37650586598346
```

### CDK CLI Version

2.60.0 (build 2d40d77)

### Framework Version

2.60.0

### Node.js Version

v19.0.1

### OS

Mac OS

### Language

Typescript

### Language Version

4.9.4

**Comment by sempfa** [comment]
found "workaround" ... 
This is only an issue if the env params arent set when deploying.
setting `env: { region: 'us-east-1' } ` in props allows to deploy

**Comment by pahud** [comment]
Thank you for your report. I believe Amazon Managed Blockchain is not supported to all regions and you need to check the regional table for availability:
https://aws.amazon.com/about-aws/global-infrastructure/regional-product-services/

I am closing this issue now as irrelevant.
