### ISSUE TITLE
CDK Pipelines: Failed to store notices in the cache: Error: ENOENT: no such file or directory, open '/root/.cdk/cache/notices.json'

### ISSUE THREAD

**Issue by abk7777** [aws/aws-cdk#23785]
### Describe the bug

Failing Build step using CDK Pipelines:

```bash
[Container] 2023/01/23 04:50:43 Running command npm ci
added 365 packages in 11.467s

[Container] 2023/01/23 04:51:08 Running command npm run build

> chat-bot@0.1.0 build /codebuild/output/src744489264/src
> tsc


[Container] 2023/01/23 04:51:18 Running command npx cdk --version
2.53.0 (build 7690f43)

[Container] 2023/01/23 04:51:20 Running command npx cdk synth --verbose --trace
[04:51:21] CDK toolkit version: 2.53.0 (build 7690f43)
[04:51:21] Command line arguments: {
  _: [ 'synth' ],
  verbose: 1,
  v: 1,
  trace: true,
  lookups: true,
  'ignore-errors': false,
  ignoreErrors: false,
  json: false,
  j: false,
  debug: false,
  ec2creds: undefined,
  i: undefined,
  'version-reporting': undefined,
  versionReporting: undefined,
  'path-metadata': true,
  pathMetadata: true,
  'asset-metadata': true,
  assetMetadata: true,
  'role-arn': undefined,
  r: undefined,
  roleArn: undefined,
  staging: true,
  'no-color': false,
  noColor: false,
  ci: false,
  validation: true,
  quiet: false,
  q: false,
  '$0': 'node_modules/.bin/cdk'
}
[04:51:21] cdk.json: {
  "app": "npx ts-node --prefer-ts-exts bin/chat-bot.ts",
  "watch": {
    "include": [
      "**"
    ],
    "exclude": [
      "README.md",
      "cdk*.json",
      "**/*.d.ts",
      "**/*.js",
      "tsconfig.json",
      "package*.json",
      "yarn.lock",
      "node_modules",
      "test"
    ]
  },
  "context": {
    "@aws-cdk/aws-lambda:recognizeLayerVersion": true,
    "@aws-cdk/core:checkSecretUsage": true,
    "@aws-cdk/core:target-partitions": [
      "aws",
      "aws-cn"
    ],
    "@aws-cdk-containers/ecs-service-extensions:enableDefaultLogDriver": true,
    "@aws-cdk/aws-ec2:uniqueImdsv2TemplateName": true,
    "@aws-cdk/aws-ecs:arnFormatIncludesClusterName": true,
    "@aws-cdk/aws-iam:minimizePolicies": true,
    "@aws-cdk/core:validateSnapshotRemovalPolicy": true,
    "@aws-cdk/aws-codepipeline:crossAccountKeyAliasStackSafeResourceName": true,
    "@aws-cdk/aws-s3:createDefaultLoggingPolicy": true,
    "@aws-cdk/aws-sns-subscriptions:restrictSqsDescryption": true,
    "@aws-cdk/aws-apigateway:disableCloudWatchRole": true,
    "@aws-cdk/core:enablePartitionLiterals": true,
    "@aws-cdk/aws-events:eventsTargetQueueSameAccount": true,
    "@aws-cdk/aws-iam:standardizedServicePrincipals": true,
    "@aws-cdk/aws-ecs:disableExplicitDeploymentControllerForCircuitBreaker": true,
    "@aws-cdk/core:newStyleStackSynthesis": true
  }
}
[04:51:21] merged settings: {
  versionReporting: true,
  pathMetadata: true,
  output: 'cdk.out',
  app: 'npx ts-node --prefer-ts-exts bin/chat-bot.ts',
  watch: {
    include: [ '**' ],
    exclude: [
      'README.md',
      'cdk*.json',
      '**/*.d.ts',
      '**/*.js',
      'tsconfig.json',
      'package*.json',
      'yarn.lock',
      'node_modules',
      'test'
    ]
  },
  context: {
    '@aws-cdk/aws-lambda:recognizeLayerVersion': true,
    '@aws-cdk/core:checkSecretUsage': true,
    '@aws-cdk/core:target-partitions': [ 'aws', 'aws-cn' ],
    '@aws-cdk-containers/ecs-service-extensions:enableDefaultLogDriver': true,
    '@aws-cdk/aws-ec2:uniqueImdsv2TemplateName': true,
    '@aws-cdk/aws-ecs:arnFormatIncludesClusterName': true,
    '@aws-cdk/aws-iam:minimizePolicies': true,
    '@aws-cdk/core:validateSnapshotRemovalPolicy': true,
    '@aws-cdk/aws-codepipeline:crossAccountKeyAliasStackSafeResourceName': true,
    '@aws-cdk/aws-s3:createDefaultLoggingPolicy': true,
    '@aws-cdk/aws-sns-subscriptions:restrictSqsDescryption': true,
    '@aws-cdk/aws-apigateway:disableCloudWatchRole': true,
    '@aws-cdk/core:enablePartitionLiterals': true,
    '@aws-cdk/aws-events:eventsTargetQueueSameAccount': true,
    '@aws-cdk/aws-iam:standardizedServicePrincipals': true,
    '@aws-cdk/aws-ecs:disableExplicitDeploymentControllerForCircuitBreaker': true,
    '@aws-cdk/core:newStyleStackSynthesis': true
  },
  debug: false,
  assetMetadata: true,
  toolkitBucket: {},
  staging: true,
  bundlingStacks: [ '**' ],
  lookups: true
}
[04:51:21] Toolkit stack: CDKToolkit
[04:51:21] Setting "CDK_DEFAULT_REGION" environment variable to us-east-1
[04:51:21] Resolving default credentials
[04:51:21] Looking up default account ID from STS
[04:51:21] Notices refreshed
[04:51:21] Failed to store notices in the cache: Error: ENOENT: no such file or directory, open '/root/.cdk/cache/notices.json'
[04:51:21] Default account ID: 810526023897
[04:51:21] Setting "CDK_DEFAULT_ACCOUNT" environment variable to 810526023897
[04:51:21] context: {
  '@aws-cdk/aws-lambda:recognizeLayerVersion': true,
  '@aws-cdk/core:checkSecretUsage': true,
  '@aws-cdk/core:target-partitions': [ 'aws', 'aws-cn' ],
  '@aws-cdk-containers/ecs-service-extensions:enableDefaultLogDriver': true,
  '@aws-cdk/aws-ec2:uniqueImdsv2TemplateName': true,
  '@aws-cdk/aws-ecs:arnFormatIncludesClusterName': true,
  '@aws-cdk/aws-iam:minimizePolicies': true,
  '@aws-cdk/core:validateSnapshotRemovalPolicy': true,
  '@aws-cdk/aws-codepipeline:crossAccountKeyAliasStackSafeResourceName': true,
  '@aws-cdk/aws-s3:createDefaultLoggingPolicy': true,
  '@aws-cdk/aws-sns-subscriptions:restrictSqsDescryption': true,
  '@aws-cdk/aws-apigateway:disableCloudWatchRole': true,
  '@aws-cdk/core:enablePartitionLiterals': true,
  '@aws-cdk/aws-events:eventsTargetQueueSameAccount': true,
  '@aws-cdk/aws-iam:standardizedServicePrincipals': true,
  '@aws-cdk/aws-ecs:disableExplicitDeploymentControllerForCircuitBreaker': true,
  '@aws-cdk/core:newStyleStackSynthesis': true,
  'aws:cdk:enable-path-metadata': true,
  'aws:cdk:enable-asset-metadata': true,
  'aws:cdk:version-reporting': true,
  'aws:cdk:bundling-stacks': [ '**' ]
}
[04:51:21] outdir: cdk.out
[04:51:21] env: {
  CDK_DEFAULT_REGION: 'us-east-1',
  CDK_DEFAULT_ACCOUNT: '810526023897',
  CDK_OUTDIR: 'cdk.out',
  CDK_CLI_ASM_VERSION: '21.0.0',
  CDK_CLI_VERSION: '2.53.0'
}
Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
docker exited with status 1
[04:51:31] Notices refreshed

Subprocess exited with error 1
[04:51:31] Error: Subprocess exited with error 1
    at ChildProcess.<anonymous> (/codebuild/output/src744489264/src/node_modules/aws-cdk/lib/api/cxapp/exec.ts:153:23)
    at ChildProcess.emit (events.js:400:28)
    at ChildProcess.emit (domain.js:475:12)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:285:12)

[Container] 2023/01/23 04:51:31 Command did not exit successfully npx cdk synth --verbose --trace exit status 1
[Container] 2023/01/23 04:51:31 Phase complete: BUILD State: FAILED
[Container] 2023/01/23 04:51:31 Phase context status code: COMMAND_EXECUTION_ERROR Message: Error while executing command: npx cdk synth --verbose --trace. Reason: exit status 1
[Container] 2023/01/23 04:51:31 Entering phase POST_BUILD
[Container] 2023/01/23 04:51:31 Phase complete: POST_BUILD State: SUCCEEDED
[Container] 2023/01/23 04:51:31 Phase context status code:  Message: 
[Container] 2023/01/23 04:51:31 Expanding base directory path: ${CODEBUILD_SRC_DIR}/cdk.out
[Container] 2023/01/23 04:51:31 Assembling file list
[Container] 2023/01/23 04:51:31 Expanding /codebuild/output/src744489264/src/cdk.out
[Container] 2023/01/23 04:51:31 Expanding file paths for base directory /codebuild/output/src744489264/src/cdk.out
[Container] 2023/01/23 04:51:31 Assembling file list
[Container] 2023/01/23 04:51:31 Expanding **/*
[Container] 2023/01/23 04:51:31 Found 9 file(s)
[Container] 2023/01/23 04:51:31 Phase complete: UPLOAD_ARTIFACTS State: SUCCEEDED
[Container] 2023/01/23 04:51:31 Phase context status code:  Message: 
```

### Expected Behavior

Expected to deploy the stack.

### Current Behavior

```bash
[04:51:21] Notices refreshed
[04:51:21] Failed to store notices in the cache: Error: ENOENT: no such file or directory, open '/root/.cdk/cache/notices.json'
...
[04:51:31] Notices refreshed
Subprocess exited with error 1
[04:51:31] Error: Subprocess exited with error 1
    at ChildProcess.<anonymous> (/codebuild/output/src744489264/src/node_modules/aws-cdk/lib/api/cxapp/exec.ts:153:23)
    at ChildProcess.emit (events.js:400:28)
    at ChildProcess.emit (domain.js:475:12)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:285:12)
```

### Reproduction Steps

Pipeline definition:
```javascript
const pipeline = new CodePipeline(this, 'Pipeline', {
    // The pipeline name
    pipelineName: 'Pipeline',
    crossAccountKeys: true,
    synth: new ShellStep('Synth', {
        input: CodePipelineSource.gitHub(
            `${process.env.REPO_OWNER}/${process.env.REPO_NAME}`,
            `${process.env.REPO_BRANCH}`),
        commands: [
            'echo $(pwd)',
            'ls -la',
            'printenv',
            'npm ci',
            'npm run build',
            'npx cdk --version',
            'npx cdk synth --verbose --trace'
        ],
        primaryOutputDirectory: '${CODEBUILD_SRC_DIR}/cdk.out',
        env: {
            "VAR": "value"
        },
    }),
});
```

### Possible Solution

Is cdk.json incorrect?
```json
{
  "app": "npx ts-node --prefer-ts-exts bin/chat-bot.ts",
  "watch": {
    "include": [
      "**"
    ],
    "exclude": [
      "README.md",
      "cdk*.json",
      "**/*.d.ts",
      "**/*.js",
      "tsconfig.json",
      "package*.json",
      "yarn.lock",
      "node_modules",
      "test"
    ]
  },
  "context": {
    "@aws-cdk/aws-lambda:recognizeLayerVersion": true,
    "@aws-cdk/core:checkSecretUsage": true,
    "@aws-cdk/core:target-partitions": [
      "aws",
      "aws-cn"
    ],
    "@aws-cdk-containers/ecs-service-extensions:enableDefaultLogDriver": true,
    "@aws-cdk/aws-ec2:uniqueImdsv2TemplateName": true,
    "@aws-cdk/aws-ecs:arnFormatIncludesClusterName": true,
    "@aws-cdk/aws-iam:minimizePolicies": true,
    "@aws-cdk/core:validateSnapshotRemovalPolicy": true,
    "@aws-cdk/aws-codepipeline:crossAccountKeyAliasStackSafeResourceName": true,
    "@aws-cdk/aws-s3:createDefaultLoggingPolicy": true,
    "@aws-cdk/aws-sns-subscriptions:restrictSqsDescryption": true,
    "@aws-cdk/aws-apigateway:disableCloudWatchRole": true,
    "@aws-cdk/core:enablePartitionLiterals": true,
    "@aws-cdk/aws-events:eventsTargetQueueSameAccount": true,
    "@aws-cdk/aws-iam:standardizedServicePrincipals": true,
    "@aws-cdk/aws-ecs:disableExplicitDeploymentControllerForCircuitBreaker": true,
    "@aws-cdk/core:newStyleStackSynthesis": true
  }
}
```

Have tried adding `"@aws-cdk/core:newStyleStackSynthesis": true` to cdk.json and `primaryOutputDirectory` to the CDK definition. Not sure what else I could be missing.

### Additional Information/Context

Had to convert CDK v1 to v2 from this blog post:
https://aws.amazon.com/blogs/developer/cdk-pipelines-continuous-delivery-for-aws-cdk-applications/

### CDK CLI Version

CDK toolkit version: 2.61.1 (build d319d9c)

### Node.js Version

NODE_14_VERSION=14.19.2

### OS

Amazon CodeBuild Linux

### Language

Typescript

### Language Version

4.9.4

### Other information

**Comment by abk7777** [comment]
The `npx cdk` version was out of data and I never updated it when I adapted the code. I updated it to 2.61.1 and updated everything in package.json but I am encountering the same error.

**Comment by pahud** [comment]
I am not able to debug this from the given error messages. Wondering if you have tried to deploy it in a new cdkv2 application?
