### ISSUE TITLE
TriggerFunction AND Trigger: Error: The "url" argument must be of type string. Received undefined

### ISSUE THREAD

**Issue by michhyun1** [aws/aws-cdk#23976]
### Describe the bug

When using the TriggerFunction AND Trigger construct. 

```
Received response status [FAILED] from custom resource. Message returned: Error: The "url" argument must be of type string. Received undefined
TypeError [ERR_INVALID_ARG_TYPE]: The "url" argument must be of type string. Received undefined,    at new NodeError (node:internal/errors:372:5),    at validateString (node:internal/validators:120:11),    at Url.pars
e (node:url:168:3),    at Object.urlParse [as parse] (node:url:155:13),    at /var/task/node_modules/cfn-response-promise/index.js:30:29,    at new Promise (<anonymous>),    at Object.exports.send (/var/task/node_modu
les/cfn-response-promise/index.js:13:12),    at Runtime.exports.handleS3 [as handler] (/var/task/handler.js:125:24),    at Runtime.handleOnceNonStreaming (file:///var/runtime/index.mjs:1089:29)
at handler (/var/task/index.js:1:1133)
```

### Expected Behavior

Not to run into any errors.

### Current Behavior

When trying to `cdk deploy` that TriggerFunction or Trigger, I get that error message.

### Reproduction Steps

```
  const myLambda = new TriggerFunction(this, "Singleton", {
    functionName: "xxx",
    description:
      "xxx",
    code: Code.fromAsset("xxx"),
    handler: "xxx",
    timeout: Duration.seconds(180),
    runtime: Runtime.NODEJS_18_X,
    role: xxx,
    logRetention: RetentionDays.THREE_MONTHS,
    initialPolicy: [
      new PolicyStatement({
        actions: [
          "logs:CreateLogGroup",
          "logs:CreateLogStream",
          "logs:PutLogEvents",
        ],
        resources: ["*"],
      }),
    ],
    executeAfter: [xxx],
  });
  singletonLambda.node.addDependency(xxx);
  ```

### CDK CLI Version

2.62.2

### Node.js Version

CLI v16.13.1

### OS

Mac Os 12.6.2

### Language

Typescript

### Language Version

4.6.4

**Comment by michhyun1** [comment]
[pahud](https://github.com/pahud) I'd very much appreciate a quick resolution here!

**Comment by pahud** [comment]
@michhyun1 

This is weird. Do you have any minimal working sample code that I can reproduce in my environment?

**Comment by michhyun1** [comment]
I just simply created a TriggerFunction like the sample code above:
```
  const myLambda = new TriggerFunction(this, "Singleton", {
    functionName: "xxx",
    description:
      "xxx",
    code: Code.fromAsset("xxx"),
    handler: "xxx",
    timeout: Duration.seconds(180),
    runtime: Runtime.NODEJS_18_X,
    role: xxx,
    logRetention: RetentionDays.THREE_MONTHS,
    initialPolicy: [
      new PolicyStatement({
        actions: [
          "logs:CreateLogGroup",
          "logs:CreateLogStream",
          "logs:PutLogEvents",
        ],
        resources: ["*"],
      }),
    ],
    executeAfter: [xxx],
  });
  singletonLambda.node.addDependency(xxx);
  ```

**Comment by michhyun1** [comment]
I don't see any "url" props so I dont think its a misconfiguration on my side

**Comment by michhyun1** [comment]
No updates?

**Comment by pahud** [comment]
Hi @michhyun1 

As I can't deploy your provided sample code, I am using the code below for reproduction:

```ts
import * as cdk from "aws-cdk-lib";
import { triggers, Duration,
aws_lambda as lambda, 
aws_logs as logs,
aws_iam as iam,
aws_sns as sns } from "aws-cdk-lib";
import { Construct } from "constructs";
import * as path from 'path';

export class CdkSandboxStack extends cdk.Stack {
  constructor(scope: Construct, id: string, props?: cdk.StackProps) {
    super(scope, id, props);

    const topic = new sns.Topic(this, 'Topic')

    const myLambda = new triggers.TriggerFunction(this, "Singleton", {
      code: lambda.Code.fromAsset(path.join(__dirname, '../lambda')),
      handler: "index.handler",
      timeout: Duration.seconds(180),
      runtime: lambda.Runtime.NODEJS_18_X,
      logRetention: logs.RetentionDays.THREE_MONTHS,
      initialPolicy: [
        new iam.PolicyStatement({
          actions: [
            "logs:CreateLogGroup",
            "logs:CreateLogStream",
            "logs:PutLogEvents",
          ],
          resources: ["*"],
        }),
      ],
      executeAfter: [topic],
    });
  }
}
```

And I can confirm the TriggerFunction will be provisioned after the sns Topic. I didn't see any error message.

Please provide full sample code that I can reproduce in my account so we can better assist you. Thanks.

**Comment by michhyun1** [comment]
ok then we can close this
