### ISSUE TITLE
(iam): Circular dependency with grantPrincipal in PolicyStatement

### ISSUE THREAD

**Issue by neovasili** [aws/aws-cdk#24031]
### Describe the bug

When creating a `PolicyStatement` object that grants permissions to a principal, CDK throws an error with circular dependency on `grantPrincipal` method.

A PolicyStatement could be required when trying to give cross-account permissions in a `ResourcePolicy`.

### Expected Behavior

Policy is created successfully and principal is granted as specified.

### Current Behavior

Error throw when trying to synth any stack that contains the issue:

```shell
Error: Resolution error: Resolution error: Unable to resolve object tree with circular reference. Path: /Resources/${Token[EventbusPolicyTestStack.CFN.LogicalID.25]}/Properties/policyDocument/_principals/array/0/grantPrincipal/grantPrincipal/grantPrincipal/grantPrincipal/grantPrincipal/grantPrincipal/grantPrincipal/grantPrincipal/grantPrincipal/grantPrincipal/grantPrincipal/grantPrincipal/grantPrincipal/grantPrincipal/grantPrincipal/grantPrincipal/grantPrincipal/grantPrincipal/grantPrincipal/grantPrincipal/grantPrincipal/grantPrincipal/grantPrincipal/grantPrincipal/grantPrincipal/grantPrincipal/grantPrincipal/grantPrincipal/grantPrincipal/grantPrincipal/grantPrincipal/grantPrincipal/grantPrincipal/grantPrincipal/grantPrincipal/grantPrincipal/grantPrincipal/grantPrincipal/grantPrincipal/grantPrincipal/grantPrincipal/grantPrincipal/grantPrincipal/grantPrincipal/grantPrincipal/grantPrincipal/grantPrincipal/grantPrincipal/grantPrincipal/grantPrincipal/grantPrincipal/grantPrincipal/grantPrincipal/grantPrincipal/grantPrincipal/grantPrincipal/grantPrincipal/grantPrincipal/grantPrincipal/grantPrincipal/grantPrincipal/grantPrincipal/grantPrincipal/grantPrincipal/grantPrincipal/grantPrincipal/grantPrincipal/grantPrincipal/grantPrincipal/grantPrincipal/grantPrincipal/grantPrincipal/grantPrincipal/grantPrincipal/grantPrincipal/grantPrincipal/grantPrincipal/grantPrincipal/grantPrincipal/grantPrincipal/grantPrincipal/grantPrincipal/grantPrincipal/grantPrincipal/grantPrincipal/grantPrincipal/grantPrincipal/grantPrincipal/grantPrincipal/grantPrincipal/grantPrincipal/grantPrincipal/grantPrincipal/grantPrincipal/grantPrincipal/grantPrincipal/grantPrincipal/grantPrincipal/grantPrincipal/grantPrincipal/grantPrincipal/grantPrincipal/grantPrincipal/grantPrincipal/grantPrincipal/grantPrincipal/grantPrincipal/grantPrincipal/grantPrincipal/grantPrincipal/grantPrincipal/grantPrincipal/grantPrincipal/grantPrincipal/grantPrincipal/grantPrincipal/grantPrincipal/grantPrincipal/grantPrincipal/grantPrincipal/grantPrincipal/grantPrincipal/grantPrincipal/grantPrincipal/grantPrincipal/grantPrincipal/grantPrincipal/grantPrincipal/grantPrincipal/grantPrincipal/grantPrincipal/grantPrincipal/grantPrincipal/grantPrincipal/grantPrincipal/grantPrincipal/grantPrincipal/grantPrincipal/grantPrincipal/grantPrincipal/grantPrincipal/grantPrincipal/grantPrincipal/grantPrincipal/grantPrincipal/grantPrincipal/grantPrincipal/grantPrincipal/grantPrincipal/grantPrincipal/grantPrincipal/grantPrincipal/grantPrincipal/grantPrincipal/grantPrincipal/grantPrincipal/grantPrincipal/grantPrincipal/grantPrincipal/grantPrincipal/grantPrincipal/grantPrincipal/grantPrincipal/grantPrincipal/grantPrincipal/grantPrincipal/grantPrincipal/grantPrincipal/grantPrincipal/grantPrincipal/grantPrincipal/grantPrincipal/grantPrincipal/grantPrincipal/grantPrincipal/grantPrincipal/grantPrincipal/grantPrincipal/grantPrincipal/grantPrincipal/grantPrincipal/grantPrincipal/grantPrincipal/grantPrincipal/grantPrincipal/grantPrincipal/grantPrincipal/grantPrincipal/grantPrincipal/grantPrincipal/grantPrincipal/grantPrincipal/grantPrincipal/grantPrincipal..
    at resolve (/Users/neovasili/workspace/lab/eventbus-policy-test/node_modules/aws-cdk-lib/core/lib/private/resolve.js:1:1073)
    at Object.resolve (/Users/neovasili/workspace/lab/eventbus-policy-test/node_modules/aws-cdk-lib/core/lib/private/resolve.js:1:892)
    at resolve (/Users/neovasili/workspace/lab/eventbus-policy-test/node_modules/aws-cdk-lib/core/lib/private/resolve.js:1:2755)
    at Object.resolve (/Users/neovasili/workspace/lab/eventbus-policy-test/node_modules/aws-cdk-lib/core/lib/private/resolve.js:1:892)
    at resolve (/Users/neovasili/workspace/lab/eventbus-policy-test/node_modules/aws-cdk-lib/core/lib/private/resolve.js:1:2755)
    at Object.resolve (/Users/neovasili/workspace/lab/eventbus-policy-test/node_modules/aws-cdk-lib/core/lib/private/resolve.js:1:892)
    at resolve (/Users/neovasili/workspace/lab/eventbus-policy-test/node_modules/aws-cdk-lib/core/lib/private/resolve.js:1:2755)
    at Object.resolve (/Users/neovasili/workspace/lab/eventbus-policy-test/node_modules/aws-cdk-lib/core/lib/private/resolve.js:1:892)
    at resolve (/Users/neovasili/workspace/lab/eventbus-policy-test/node_modules/aws-cdk-lib/core/lib/private/resolve.js:1:2755)
    at Object.resolve (/Users/neovasili/workspace/lab/eventbus-policy-test/node_modules/aws-cdk-lib/core/lib/private/resolve.js:1:892)
```

### Reproduction Steps

Here is a minimum Stack definition using `EventBusPolicy` that reproduces the issue when trying to do `cdk ls` or `cdk synth`:

```typescript
import * as cdk from "aws-cdk-lib";
import { Construct } from "constructs";
import * as iam from "aws-cdk-lib/aws-iam";
import * as events from "aws-cdk-lib/aws-events";

export class EventbusPolicyTestStack extends cdk.Stack {
  constructor(scope: Construct, id: string, props?: cdk.StackProps) {
    super(scope, id, props);

    const defaultEventBus = events.EventBus.fromEventBusName(this, "Default", "default");

    new events.EventBusPolicy(this, "MyPolicy", {
      eventBus: defaultEventBus,
      statementId: "MyStatement",
      statement: new iam.PolicyStatement({
        principals: [
          new iam.AccountPrincipal("123456789010"),
        ],
        actions: [
          "events:PutEvents",
        ],
        resources: [
          defaultEventBus.eventBusArn,
        ],
      }),
    });
  }
}
```

Another example:

```typescript
import * as cdk from "aws-cdk-lib";
import { Construct } from "constructs";
import * as iam from "aws-cdk-lib/aws-iam";
import * as events from "aws-cdk-lib/aws-events";

export class EventbusPolicyTestStack extends cdk.Stack {
  constructor(scope: Construct, id: string, props?: cdk.StackProps) {
    super(scope, id, props);

    const defaultEventBus = events.EventBus.fromEventBusName(this, "Default", "default");
    const policyFromJson = iam.PolicyStatement.fromJson({
      Principal: {
        AWS: "123456789010",
      },
      Action: [
        "events:PutEvents",
      ],
      Resource: [
        defaultEventBus.eventBusArn,
      ],
    });
    new events.EventBusPolicy(this, "MyPolicy", {
      eventBus: defaultEventBus,
      statementId: "MyStatement",
      statement: policyFromJson,
    });
  }
}
```

Another one for `BucketPolicy`:

```typescript
import * as cdk from "aws-cdk-lib";
import { Construct } from "constructs";
import * as s3 from "aws-cdk-lib/aws-s3";
import * as iam from "aws-cdk-lib/aws-iam";

export class EventbusPolicyTestStack extends cdk.Stack {
  constructor(scope: Construct, id: string, props?: cdk.StackProps) {
    super(scope, id, props);

    const policyFromJson = iam.PolicyStatement.fromJson({
      Principal: {
        AWS: "123456789010",
      },
      Action: [
        "events:PutEvents",
      ],
      Resource: [
        defaultEventBus.eventBusArn,
      ],
    });
    const testBucket = new s3.Bucket(this, "MyTestBucket");
    new s3.CfnBucketPolicy(this, "CFN", {
      bucket: testBucket.bucketName,
      policyDocument: policyFromJson,
    });
  }
}
```

### Additional Information/Context

In the case of `EventBusPolicy` there isc the possibility to pass principal in a different way using L1 construct that does not cause the issue:

```typescript
new events.CfnEventBusPolicy(this, "MyPolicy", {
    statementId: "MyStatement",
    action: "events:PutEvents",
    principal: "123456789010",
});
```

### CDK CLI Version

2.63.2 (build e08e34a)

### Node.js Version

v16.14.2

### OS

Mac Ventura/Monterrey

### Language

Typescript

### Language Version

>= 4.6.x

**Comment by peterwoodworth** [comment]
It looks like the `EventBusPolicy` construct doesn't properly handle the `PolicyStatement` passed in - Try using `toJSON()`

```
    const defaultEventBus = EventBus.fromEventBusName(this, "Default", "default");

    new EventBusPolicy(this, "MyPolicy", {
      eventBus: defaultEventBus,
      statementId: "MyStatement",
      statement: new iam.PolicyStatement({
        principals: [
          new iam.AccountPrincipal("123456789010"),
        ],
        actions: [
          "events:PutEvents",
        ],
        resources: [
          defaultEventBus.eventBusArn,
        ],
      }).toJSON(),
    });
```

We should either properly document this, or fix it (which I think would be a breaking change if we decide to have the construct resolve the PolicyStatement to JSON). Thanks for reporting!

**Comment by neovasili** [comment]
Thanks for the reply @peterwoodworth!

I can confirm that the `toJSON()` workaround also works for me.

Although, I don't think is an issue on the `EventBusPolicy` construct, as I illustrated in the Reproduction steps it also happens when using a `CfnBucketPolicy` construct and even with this:

```typescript
import * as cdk from "aws-cdk-lib";
import { Construct } from "constructs";
import * as iam from "aws-cdk-lib/aws-iam";
import * as events from "aws-cdk-lib/aws-events";

export class EventbusPolicyTestStack extends cdk.Stack {
  constructor(scope: Construct, id: string, props?: cdk.StackProps) {
    super(scope, id, props);

    const defaultEventBus = events.EventBus.fromEventBusName(this, "Default", "default");
    const policyFromJson = iam.PolicyStatement.fromJson({
      Principal: {
        AWS: "123456789010",
      },
      Action: [
        "events:PutEvents",
      ],
      Resource: [
        defaultEventBus.eventBusArn,
      ],
    });
    new events.CfnEventBusPolicy(this, "MyPolicy", {
      statementId: "MyStatement",
      statement: policyFromJson,
    });
  }
}
```

I didn't have the chance to look at the source code, but looks like the issue is in the `iam.PolicyStatement` construct when it has a principal (I tried to remove the principal and the issue disappears) and is used alone, thus, not wrapped with another `iam` construct, like a PolicyDocument.

**Comment by peterwoodworth** [comment]
Any `Cfn` resources won't know how to handle a `PolicyStatement` that is directly passed in as a prop. You would need to use `toJSON()` there as well

**Comment by andersonmgomes** [comment]
Hello there!

I have encountered the issue, and I believe it can be resolved by modifying the "events.generated.ts" file. Specifically, line 2526 needs to be updated with the following code:

` this.statement = props.statement.toJSON();
`

However, the challenge I am facing is that this file is automatically generated, and I cannot locate its source. 

Could anyone help me find the source and resolve this issue?

**Comment by andersonmgomes** [comment]
# Clarification Request

**Comment by mrgrain** [comment]
Cross-posting from Slack:
[Files are generated in the cfn2ts package](https://github.com/aws/aws-cdk/tree/main/tools/%40aws-cdk/cfn2ts).

Unfortunately the proposed changes to call `toJSON()` doesn't take into account that something is passed in that doesn't have a `toJson()` method. We are aware of the problem now and thinking about solutions.

**Comment by rix0rrr** [comment]
The issue is that `CfnEventBusPolicy` expects plain IAM JSON as an argument, not an `iam.PolicyStatement` object.

This example:
```ts
export class EventbusPolicyTestStack extends cdk.Stack {
  constructor(scope: Construct, id: string, props?: cdk.StackProps) {
    super(scope, id, props);

    const defaultEventBus = events.EventBus.fromEventBusName(this, "Default", "default");
    const policyFromJson = iam.PolicyStatement.fromJson({
      Principal: {
        AWS: "123456789010",
      },
      Action: [
        "events:PutEvents",
      ],
      Resource: [
        defaultEventBus.eventBusArn,
      ],
    });
    new events.CfnEventBusPolicy(this, "MyPolicy", {
      statementId: "MyStatement",
      statement: policyFromJson,
    });
  }
}

**Comment by sliedig** [comment]
I'm having the same issue using C#. I have isolated the issue to the `Principals` property in the PolicyStatement definition. If you comment `Principals = new IPrincipal[] { new AccountPrincipal("123456789012") },` out, it works fine. It only throws the resolution exception with the Principal defined. How this is classified as a circular reference, I have no idea.

```csharp
// Event bus
var unicornContractsEventBus = new EventBus(this, "UnicornContractsEventBus", new EventBusProps()
{
    EventBusName = $"UnicornContractsEventBus-{stage.ValueAsString}"
});

// Event bus policy statement to restrict who can publish events
var eventBusPublisherPolicyStatement = new PolicyStatement(new PolicyStatementProps()
{
    Principals = new IPrincipal[] { new AccountPrincipal("123456789012") },
    Actions = new[] { "events:PutEvents" },
    Resources = new[]
    {
        unicornContractsEventBus.EventBusArn
    },
    Conditions = new Dictionary<string, object>()
    {
        // Restrict to only services from UnicornContractsNamespace
        {
            "StringEquals",
            new Dictionary<string, string>()
                { { "events:source", contractsNamespace.StringValue } }
        }
    }
};

// Event bus policy
new EventBusPolicy(this, "ContractEventsBusPublishPolicy", new EventBusPolicyProps()
{
    EventBus = unicornContractsEventBus,
    StatementId = $"OnlyContactsServiceCanPublishToEventBus-${stage.ValueAsString}",
    Statement = eventBusPublisherPolicyStatement
});
```

**Comment by sliedig** [comment]
Any updates on this? I last reported on this issue over 12 months ago.
