### ISSUE TITLE
memorydb: AuthenticationMode for ACL User: extraneous key

### ISSUE THREAD

**Issue by advanderveer** [aws/aws-cdk#24087]
### Describe the bug

When using the l1 constructs using the Go SDK to create a memorydb user like so: 

```Go
	prefix := "default"
	access := fmt.Sprintf(`on ~cl:%s:* resetchannels &cl:%s:* +@all -@dangerous +info +slowlog +dbsize +cluster`, prefix, prefix)
	user := awsmemorydb.NewCfnUser(s, jsii.String("DefaultUser"), &awsmemorydb.CfnUserProps{
		AccessString: jsii.String(access),
		UserName:     jsii.String(strings.ToLower(*awscdk.Stack_Of(s).StackName() + "DefaultUser")),
		AuthenticationMode: &awsmemorydb.CfnUser_AuthenticationModeProperty{
			Passwords: jsii.Strings(prefix + prefix + prefix),
			Type:      jsii.String("password"),
		},
	})
```

It will error something like this:
```
1:48:56 PM | CREATE_FAILED        | AWS::MemoryDB::User                         | RedisDefaultUserDE8B1144
Properties validation failed for resource RedisDefaultUserDE8B1144 with message:
#/AuthenticationMode: extraneous key [type] is not permitted
#/AuthenticationMode: extraneous key [passwords] is not permitted
```

Instead, the only way to make this works is like so: 
```Go
	 prefix := "default"
	access := fmt.Sprintf(`on ~cl:%s:* resetchannels &cl:%s:* +@all -@dangerous +info +slowlog +dbsize +cluster`, prefix, prefix)
	user := awsmemorydb.NewCfnUser(s, jsii.String("DefaultUser"), &awsmemorydb.CfnUserProps{
		AccessString: jsii.String(access),
		UserName:     jsii.String(strings.ToLower(*awscdk.Stack_Of(s).StackName() + "DefaultUser")),
		AuthenticationMode: awscdk.NewCfnJson(s, jsii.String("AuthenticationMode"), &awscdk.CfnJsonProps{
			Value: map[string]any{
				"Passwords": []string{prefix},
				"Type":      "password",
			},
		}),
	})
```

It looks like the L1 construct doesn't correctly serialise its fields into underlying JSON

### Expected Behavior

L1 constructs should work without error

### Current Behavior

```
1:48:56 PM | CREATE_FAILED        | AWS::MemoryDB::User                         | RedisDefaultUserDE8B1144
Properties validation failed for resource RedisDefaultUserDE8B1144 with message:
#/AuthenticationMode: extraneous key [type] is not permitted
#/AuthenticationMode: extraneous key [passwords] is not permitted


 ❌  ClPlatform failed: Error: The stack named ClPlatform failed to deploy: UPDATE_ROLLBACK_COMPLETE: Properties validation failed for resource RedisDefaultUserDE8B1144 with message:
#/AuthenticationMode: extraneous key [type] is not permitted
#/AuthenticationMode: extraneous key [passwords] is not permitted
    at FullCloudFormationDeployment.monitorDeployment (/opt/homebrew/lib/node_modules/aws-cdk/lib/index.js:327:10235)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async deployStack2 (/opt/homebrew/lib/node_modules/aws-cdk/lib/index.js:330:144733)
    at async /opt/homebrew/lib/node_modules/aws-cdk/lib/index.js:330:130251
    at async run (/opt/homebrew/lib/node_modules/aws-cdk/lib/index.js:330:128257)

 ❌ Deployment failed: Error: Stack Deployments Failed: Error: The stack named ClPlatform failed to deploy: UPDATE_ROLLBACK_COMPLETE: Properties validation failed for resource RedisDefaultUserDE8B1144 with message:
#/AuthenticationMode: extraneous key [type] is not permitted
#/AuthenticationMode: extraneous key [passwords] is not permitted
    at deployStacks (/opt/homebrew/lib/node_modules/aws-cdk/lib/index.js:330:130558)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async CdkToolkit.deploy (/opt/homebrew/lib/node_modules/aws-cdk/lib/index.js:330:146782)
    at async exec4 (/opt/homebrew/lib/node_modules/aws-cdk/lib/index.js:385:51296)

Stack Deployments Failed: Error: The stack named ClPlatform failed to deploy: UPDATE_ROLLBACK_COMPLETE: Properties validation failed for resource RedisDefaultUserDE8B1144 with message:
#/AuthenticationMode: extraneous key [type] is not permitted
#/AuthenticationMode: extraneous key [passwords] is not permitted
```

### Reproduction Steps

Copy the snipped above in a Go stack. Should be obvious to reproduce, if not I can provide a more complete example.

### CDK CLI Version

2.63.2 (build e08e34a)

### Node.js Version

v16.14.2

### OS

MacOS

### Language

Go

### Language Version

go version go1.20 darwin/arm64

**Comment by peterwoodworth** [comment]
Thanks for the report @advanderveer, the way you've found it to work is the way that this is intended to work. This property was originally specified to `any`/`json`, and then CloudFormation pushed an update to make this property be of a specific typing. However, this broke existing customers due to the similar error you've seen, so we quickly reverted this back to `any`/`json` typing. This will be the way to specify it going forward, thanks!
