### ISSUE TITLE
DockerImageCode.fromImageAsset fails to build docker on macOS with Colima

### ISSUE THREAD

**Issue by j4zzcat** [aws/aws-cdk#24206]
### Describe the bug

I'm using [Colima](https://github.com/abiosoft/colima) for all things docker on my Mac Studio (w/Apple Silicon, i.e, M1).

I'm using this here snippet to build the container:
```
...
DockerImageFunction.Builder.create(this, "test1-tumbleweed")
  .code(DockerImageCode.fromImageAsset("/tmp/abcd"))
  .build()
...
```
But it fails with:
```
DEPRECATED: The legacy builder is deprecated and will be removed in a future release.
            Install the buildx component to build images with BuildKit:
            https://docs.docker.com/go/buildx/
```

### Expected Behavior

Successfully build a docker container with Colima on macOS.

### Current Behavior

```
tumbleweed: building assets...

[0%] start: Building c5583b814a1c36c8337304a2698bdc7c9afea5e92f3a816fc3178b4e8d6cefd2:current_account-current_region
[0%] start: Building 46ecd08daef09ebf15b2be3e6e8b7e03c52221d409e5cc70353ec9513c550042:current_account-current_region
[50%] success: Built c5583b814a1c36c8337304a2698bdc7c9afea5e92f3a816fc3178b4e8d6cefd2:current_account-current_region
DEPRECATED: The legacy builder is deprecated and will be removed in a future release.
            Install the buildx component to build images with BuildKit:
            https://docs.docker.com/go/buildx/

Cannot connect to the Docker daemon at unix:///Users/snd/.colima/default/docker.sock. Is the docker daemon running?
[100%] fail: docker build --tag cdkasset-46ecd08daef09ebf15b2be3e6e8b7e03c52221d409e5cc70353ec9513c550042 . exited with error code 1: DEPRECATED: The legacy builder is deprecated and will be removed in a future release.
            Install the buildx component to build images with BuildKit:
            https://docs.docker.com/go/buildx/

Cannot connect to the Docker daemon at unix:///Users/snd/.colima/default/docker.sock. Is the docker daemon running?

 ❌ Building assets failed: Error: Building Assets Failed: Error: Failed to build one or more assets. See the error messages above for more information.
    at buildAllStackAssets (/opt/homebrew/Cellar/aws-cdk/2.65.0/libexec/lib/node_modules/aws-cdk/lib/index.js:342:116743)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async CdkToolkit.deploy (/opt/homebrew/Cellar/aws-cdk/2.65.0/libexec/lib/node_modules/aws-cdk/lib/index.js:342:142824)
    at async exec4 (/opt/homebrew/Cellar/aws-cdk/2.65.0/libexec/lib/node_modules/aws-cdk/lib/index.js:397:51795)

Building Assets Failed: Error: Failed to build one or more assets. See the error messages above for more information.
```

### Reproduction Steps

Building the image with this snippet:
```
...
DockerImageFunction.Builder.create(this, "test1-tumbleweed")
  .code(DockerImageCode.fromImageAsset("/tmp/abcd"))
  .build()
...
```

The directory `/tmp/abcd` contains the following files:
```
Dockerfile
bootstrap
function.sh
```

File `Dockerfile`:
```
FROM public.ecr.aws/lambda/provided:al2
RUN yum install -y curl jq
COPY bootstrap ${LAMBDA_RUNTIME_DIR}
COPY function.sh ${LAMBDA_TASK_ROOT}
CMD [ "function.handler" ]
```

File `function.sh`:
```
function handler () {
  EVENT_DATA=${1}
  RESPONSE="{\"statusCode\": 200, \"body\": \"Hello!\"}"
  echo $RESPONSE
}
```

File `bootstrap` is an empty file.

### CDK CLI Version

2.65.0 (build 5862f7a)

### Node.js Version

v19.6.0

### OS

macOS 13.1

### Language

Java

**Comment by pahud** [comment]
I am new to colima but looking at its README I think first you need install the `containerd` runetime and then the `nerdctl` client and you probably have to create an aliase of `docker` to /usr/local/bin/nerdctl.

After that, create a simple Dockerfile like this in a sub-directory:

```
FROM public.ecr.aws/lambda/provided:al2
RUN yum install -y curl jq
```

Run `docker build -t test .` in this directory and make sure it builds. If it works I think you should be able to build the Docker image assets with CDK as under the hood CDK is invoking the `docker` command to build the assets.

Let me know if it works with you.

Please note we have very limited issue reports about colima so there could be some unexpected gochas and we definitely need more community feedback on this.

**Comment by j4zzcat** [comment]
When you install `colima` through `homebrew`, all the prerequisites are being taken care of and the installation defaults to `docker`. I'm able to build the `Dockerfile` manually - as all other `Dockerfiles` I have - without an issue.

**Comment by robertd** [comment]
https://github.com/abiosoft/colima/discussions/273
