### ISSUE TITLE
(aws-ecs): (failed to create fargate service)

### ISSUE THREAD

**Issue by Hao-www** [aws/aws-cdk#24321]
### Describe the bug

We failed to specify existing subnets when creating a ECS fargate service.
cdk version is 2.40.0

### Expected Behavior

The following code is supposed to help us to create a fargate service "test0224" in ECS cluster "test".

### Current Behavior

The error message:
```
TypeError: Cannot read properties of undefined (reading 'selectSubnets')
    at FargateService.configureAwsVpcNetworkingWithSecurityGroups (/home/ec2-user/2xx-cdk/MyEcsConstruct/node_modules/aws-cdk-lib/aws-ecs/lib/base/base-service.js:1:16372)
    at new FargateService (/home/ec2-user/2xx-cdk/MyEcsConstruct/node_modules/aws-cdk-lib/aws-ecs/lib/fargate/fargate-service.js:1:1938)
    at new MyEcsConstructStack (/home/ec2-user/2xx-cdk/MyEcsConstruct/lib/my_ecs_construct-stack.ts:19:21)
    at Object.<anonymous> (/home/ec2-user/2xx-cdk/MyEcsConstruct/bin/my_ecs_construct.ts:7:1)
    at Module._compile (node:internal/modules/cjs/loader:1103:14)
    at Module.m._compile (/home/ec2-user/2xx-cdk/MyEcsConstruct/node_modules/ts-node/src/index.ts:1618:23)
    at Module._extensions..js (node:internal/modules/cjs/loader:1155:10)
    at Object.require.extensions.<computed> [as .ts] (/home/ec2-user/2xx-cdk/MyEcsConstruct/node_modules/ts-node/src/index.ts:1621:12)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
Subprocess exited with error 1
```

### Reproduction Steps

Sample code we used:
```
import * as cdk from 'aws-cdk-lib';
import { Construct } from 'constructs';
const ecs = require('aws-cdk-lib/aws-ecs');
const iam = require('aws-cdk-lib/aws-iam');
// import * as sqs from 'aws-cdk-lib/aws-sqs';

export class MyEcsConstructStack extends cdk.Stack {
  constructor(scope: Construct, id: string, props?: cdk.StackProps) {
    super(scope, id, props);
    var taskexecrole = iam.Role.fromRoleArn(this, "mytaskexecrole", 'arn:aws-cn:iam::037047667284:role/ecsTaskExecutionRole', {})
    const taskDefinition = new ecs.FargateTaskDefinition(this, 'TaskDef',{
      executionRole: taskexecrole,
    });
    taskDefinition.addContainer('DefaultContainer', {
      image: ecs.ContainerImage.fromRegistry("amazon/amazon-ecs-sample"),
      memoryLimitMiB: 512,
    });
    const fargate = new ecs.FargateService(this, 'fargate', {
      taskDefinition,
      cluster: "test",      
      securityGroup: "sg-xxx",  // confimed, no issue with sg
      serviceName: "test0224",
//we tried to specify existing subnets or select subnets by type :  subnetType: ec2.SubnetType.PUBLIC
      vpcSubnets: {
          subnets: ['subnet-xxxxx','subnet-xxxxx'],
      }
    });
  }
}
```

### Possible Solution

Debug mode:

vpc object is undefined at /aws-cdk/node_modules/aws-cdk-lib/aws-ecs/lib/base/base-service.js
```
   configureAwsVpcNetworkingWithSecurityGroups(vpc, assignPublicIp, vpcSubnets, securityGroups) {
        try {
            jsiiDeprecationWarnings.aws_cdk_lib_aws_ec2_IVpc(vpc),
                jsiiDeprecationWarnings.aws_cdk_lib_aws_ec2_SubnetSelection(vpcSubnets)
        } catch (error) {
            throw process.env.JSII_DEBUG !== "1" && error.name === "DeprecationError" && Error.captureStackTrace(error, this.configureAwsVpcNetworkingWithSecurityGroups), error
        } vpcSubnets === void 0 && (vpcSubnets = assignPublicIp ? { subnetType: ec2.SubnetType.PUBLIC } : {}), (securityGroups === void 0 || securityGroups.length === 0) && (securityGroups = [new ec2.SecurityGroup(this, "SecurityGroup", { vpc })]), securityGroups.forEach(sg => { this.connections.addSecurityGroup(sg) }, this), this.networkConfiguration = { awsvpcConfiguration: { assignPublicIp: assignPublicIp ? "ENABLED" : "DISABLED", subnets: vpc.selectSubnets(vpcSubnets).subnetIds, securityGroups: securityGroups.map(sg => sg.securityGroupId) } }
    } 
```
We overwritten
```
subnets: vpc.selectSubnets(vpcSubnets).subnetIds
```
to 
```
subnets: ['subnet-xxxxx','subnet-xxxxx']
```
Fixed the subnect error, but new error "ClusterNotFound" occurred.

### CDK CLI Version

2.40.0 (build 56ba2ab)

### Node.js Version

16.14.0

### OS

4.14.290-217.505.amzn2.x86_64

### Language

Typescript

### Language Version

4.9.3

**Comment by Hao-www** [comment]
use CDK v1 can reproduce the error
```
[WARNING] @aws-cdk/aws-ecs.FargateServiceProps#securityGroup is deprecated.
  use securityGroups instead.
  This API will be removed in the next major release.
/home/ec2-user/testecserror/node_modules/@aws-cdk/aws-ecs/lib/base/base-service.js:593
                subnets: vpc.selectSubnets(vpcSubnets).subnetIds,
                             ^

TypeError: Cannot read properties of undefined (reading 'selectSubnets')
    at FargateService.configureAwsVpcNetworkingWithSecurityGroups (/home/ec2-user/testecserror/node_modules/@aws-cdk/aws-ecs/lib/base/base-service.js:593:30)
    at new FargateService (/home/ec2-user/testecserror/node_modules/@aws-cdk/aws-ecs/lib/fargate/fargate-service.js:59:14)
    at new TestecserrorStack (/home/ec2-user/testecserror/lib/testecserror-stack.js:33:5)
    at Object.<anonymous> (/home/ec2-user/testecserror/bin/testecserror.js:13:1)
    at Module._compile (node:internal/modules/cjs/loader:1105:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:77:12)
    at node:internal/main/run_main_module:17:47

NOTICES
```

**Comment by Hao-www** [comment]
Issue Resolved
