### ISSUE TITLE
CfnOutput: duplicate exportName values cause silent deployment failures

### ISSUE THREAD

**Issue by alanb-sony** [aws/aws-cdk#24349]
### Describe the bug

If two CDK stacks have `CfnOutput` with the same `exportName` then CDK fails with:
```none
MyStack: creating CloudFormation changeset...

 ❌  MyStack failed: Error: The stack named MyStack failed creation, it may need to be manually deleted from the AWS console: ROLLBACK_COMPLETE
    at FullCloudFormationDeployment.monitorDeployment (/home/yoshioka/EPE/aws-serverless/node_modules/aws-cdk/lib/index.js:344:10235)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async deployStack2 (/home/yoshioka/EPE/aws-serverless/node_modules/aws-cdk/lib/index.js:347:144797)
    at async /home/yoshioka/EPE/aws-serverless/node_modules/aws-cdk/lib/index.js:347:130251
    at async run (/home/yoshioka/EPE/aws-serverless/node_modules/aws-cdk/lib/index.js:347:128257)

 ❌ Deployment failed: Error: Stack Deployments Failed: Error: The stack named MyStack failed creation, it may need to be manually deleted from the AWS console: ROLLBACK_COMPLETE
    at deployStacks (/home/yoshioka/EPE/aws-serverless/node_modules/aws-cdk/lib/index.js:347:130558)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async CdkToolkit.deploy (/home/yoshioka/EPE/aws-serverless/node_modules/aws-cdk/lib/index.js:347:146846)
    at async exec4 (/home/yoshioka/EPE/aws-serverless/node_modules/aws-cdk/lib/index.js:402:51795)

Stack Deployments Failed: Error: The stack named MyStack failed creation, it may need to be manually deleted from the AWS console: ROLLBACK_COMPLETE
```
Looking in the cloudformation events you can see the error "Export with name xxx is already exported by stack yyy" it'd be nice if CDK itself reported this error.

### Expected Behavior

An error on the CDK console saying "Export with name xxx is already exported by stack yyy"

### Current Behavior

The stack failed to deploy with no error message

### Reproduction Steps

```
export class MyStack1 extends cdk.Stack {
  constructor(scope: Construct, id: string, props: cdk.StackProps) {
    new CfnOutput(this, "Output", {
      value: "foo",
      exportName: "Output",
    });  
  }
}

export class MyStack2 extends cdk.Stack {
  constructor(scope: Construct, id: string, props: cdk.StackProps) {
    new CfnOutput(this, "Output", {
      value: "bar",
      exportName: "Output",
    });  
  }
}
```

### CDK CLI Version

2.60.0

### Node.js Version

16

### OS

Linux

### Language

Typescript

**Comment by gshpychka** [comment]
This is tricky - what if we only synth one of the stacks?

**Comment by alanb-sony** [comment]
I don't know how this is implemented internally, I'm not expecting CDK to do something to fix the error or detect it before deployment but it'd be nice if it caught the error from cloud formation

**Comment by gshpychka** [comment]
Oh, I see. I did not read the issue closely and misunderstood what you meant. Sure, getting the error from CloudFormation would be useful. I don't think calling this failure "silent" is fair, though - you get an error message.

**Comment by pahud** [comment]
Agree. It would be great if CDK can throw this error before CFN deployment.

**Comment by alanb-sony** [comment]
yes, aws/aws-cdk-cli#804 is a duplicate of this one, the others don't seem relevant

**Comment by aemada-aws** [comment]
Marking this as a duplicate of https://github.com/aws/aws-cdk-cli/issues/804 which has more engagement. Please +1 the issue there so we can prioritize accordingly.
