### ISSUE TITLE
(cdk bootstrap): StagingBucket API: s3:PutLifecycleConfiguration Access Denied

### ISSUE THREAD

**Issue by emisbalu** [aws/aws-cdk#24437]
### Describe the bug

Getting StagingBucket API: s3:PutLifecycleConfiguration Access Denied issue while `cdk bootstrap` despite having necessary permissions

### Expected Behavior

cdk bootstrap should successfully create CDKToolkit stack in the account

### Current Behavior

Fails with below error 
```
CDKToolkit |  2/12 | 10:26:49 AM | CREATE_FAILED        | AWS::S3::Bucket         | StagingBucket API: s3:PutLifecycleConfiguration Access Denied
```

### Reproduction Steps

`npx cdk bootstrap aws://XXXXXX/us-east-1`

### CDK CLI Version

2.66.1

### Node.js Version

16

### OS

Linux

### Language

Typescript

**Comment by pahud** [comment]
Hi

Can you show me the message with `cdk bootstrap aws://XXXXXX/us-east-1 --debug` ?

**Comment by emisbalu** [comment]
> Hi
> 
> Can you show me the message with `cdk bootstrap aws://XXXXXX/us-east-1 --debug` ?

```
[Container] 2023/03/06 06:04:45 Running command npx cdk bootstrap aws://XXXXXXXXXXXX/us-east-1 --debug -c targetEnv=dev --require-approval never
[WARNING] aws-cdk-lib.aws_ec2.VpcProps#cidr is deprecated.
  Use ipAddresses instead
  This API will be removed in the next major release.
[WARNING] aws-cdk-lib.aws_certificatemanager.DnsValidatedCertificate is deprecated.
  use {@link Certificate} instead
  This API will be removed in the next major release.
[WARNING] aws-cdk-lib.aws_certificatemanager.DnsValidatedCertificate is deprecated.
  use {@link Certificate} instead
  This API will be removed in the next major release.
[WARNING] aws-cdk-lib.aws_certificatemanager.DnsValidatedCertificate is deprecated.
  use {@link Certificate} instead
  This API will be removed in the next major release.
[WARNING] aws-cdk-lib.aws_elasticloadbalancingv2.ApplicationTargetGroup#metricHealthyHostCount is deprecated.
  Use ``ApplicationTargetGroup.metrics.healthyHostCount`` instead
  This API will be removed in the next major release.
[WARNING] aws-cdk-lib.aws_elasticloadbalancingv2.ApplicationTargetGroup#metricHealthyHostCount is deprecated.
  Use ``ApplicationTargetGroup.metrics.healthyHostCount`` instead
  This API will be removed in the next major release.
[WARNING] aws-cdk-lib.aws_elasticloadbalancingv2.ApplicationTargetGroup#metricHealthyHostCount is deprecated.
  Use ``ApplicationTargetGroup.metrics.healthyHostCount`` instead
  This API will be removed in the next major release.
[WARNING] aws-cdk-lib.aws_elasticloadbalancingv2.ApplicationTargetGroup#metricHealthyHostCount is deprecated.
  Use ``ApplicationTargetGroup.metrics.healthyHostCount`` instead
  This API will be removed in the next major release.
[WARNING] aws-cdk-lib.aws_elasticloadbalancingv2.ApplicationTargetGroup#metricHealthyHostCount is deprecated.
  Use ``ApplicationTargetGroup.metrics.healthyHostCount`` instead
  This API will be removed in the next major release.
[WARNING] aws-cdk-lib.aws_elasticloadbalancingv2.ApplicationTargetGroup#metricHealthyHostCount is deprecated.
  Use ``ApplicationTargetGroup.metrics.healthyHostCount`` instead
  This API will be removed in the next major release.
[WARNING] aws-cdk-lib.aws_elasticloadbalancingv2.ApplicationTargetGroup#metricHealthyHostCount is deprecated.
  Use ``ApplicationTargetGroup.metrics.healthyHostCount`` instead
  This API will be removed in the next major release.
[WARNING] aws-cdk-lib.aws_elasticloadbalancingv2.ApplicationTargetGroup#metricTargetResponseTime is deprecated.
  Use ``ApplicationTargetGroup.metrics.targetResponseTime`` instead
  This API will be removed in the next major release.
[WARNING] aws-cdk-lib.aws_elasticloadbalancingv2.ApplicationTargetGroup#metricTargetResponseTime is deprecated.
  Use ``ApplicationTargetGroup.metrics.targetResponseTime`` instead
  This API will be removed in the next major release.
[WARNING] aws-cdk-lib.aws_elasticloadbalancingv2.ApplicationTargetGroup#metricTargetResponseTime is deprecated.
  Use ``ApplicationTargetGroup.metrics.targetResponseTime`` instead
  This API will be removed in the next major release.
[WARNING] aws-cdk-lib.aws_elasticloadbalancingv2.ApplicationTargetGroup#metricTargetResponseTime is deprecated.
  Use ``ApplicationTargetGroup.metrics.targetResponseTime`` instead
  This API will be removed in the next major release.
[WARNING] aws-cdk-lib.aws_elasticloadbalancingv2.ApplicationTargetGroup#metricTargetResponseTime is deprecated.
  Use ``ApplicationTargetGroup.metrics.targetResponseTime`` instead
  This API will be removed in the next major release.
[WARNING] aws-cdk-lib.aws_elasticloadbalancingv2.ApplicationTargetGroup#metricTargetResponseTime is deprecated.
  Use ``ApplicationTargetGroup.metrics.targetResponseTime`` instead
  This API will be removed in the next major release.
[WARNING] aws-cdk-lib.aws_elasticloadbalancingv2.ApplicationTargetGroup#metricTargetResponseTime is deprecated.
  Use ``ApplicationTargetGroup.metrics.targetResponseTime`` instead
  This API will be removed in the next major release.
[WARNING] aws-cdk-lib.aws_elasticloadbalancingv2.ApplicationTargetGroup#metricHttpCodeTarget is deprecated.
  Use ``ApplicationTargetGroup.metrics.httpCodeTarget`` instead
  This API will be removed in the next major release.
[WARNING] aws-cdk-lib.aws_elasticloadbalancingv2.ApplicationTargetGroup#metricHttpCodeTarget is deprecated.
  Use ``ApplicationTargetGroup.metrics.httpCodeTarget`` instead
  This API will be removed in the next major release.
[WARNING] aws-cdk-lib.aws_elasticloadbalancingv2.ApplicationTargetGroup#metricHttpCodeTarget is deprecated.
  Use ``ApplicationTargetGroup.metrics.httpCodeTarget`` instead
  This API will be removed in the next major release.
[WARNING] aws-cdk-lib.aws_elasticloadbalancingv2.ApplicationTargetGroup#metricHttpCodeTarget is deprecated.
  Use ``ApplicationTargetGroup.metrics.httpCodeTarget`` instead
  This API will be removed in the next major release.
[WARNING] aws-cdk-lib.aws_elasticloadbalancingv2.ApplicationTargetGroup#metricHttpCodeTarget is deprecated.
  Use ``ApplicationTargetGroup.metrics.httpCodeTarget`` instead
  This API will be removed in the next major release.
[WARNING] aws-cdk-lib.aws_elasticloadbalancingv2.ApplicationTargetGroup#metricHttpCodeTarget is deprecated.
  Use ``ApplicationTargetGroup.metrics.httpCodeTarget`` instead
  This API will be removed in the next major release.
[WARNING] aws-cdk-lib.aws_elasticloadbalancingv2.ApplicationTargetGroup#metricHttpCodeTarget is deprecated.
  Use ``ApplicationTargetGroup.metrics.httpCodeTarget`` instead
  This API will be removed in the next major release.
[WARNING] aws-cdk-lib.aws_elasticloadbalancingv2.ApplicationTargetGroup#metricRequestCountPerTarget is deprecated.
  Use ``ApplicationTargetGroup.metrics.ipv6RequestCount`` instead
  This API will be removed in the next major release.
[WARNING] aws-cdk-lib.aws_elasticloadbalancingv2.ApplicationTargetGroup#metricRequestCountPerTarget is deprecated.
  Use ``ApplicationTargetGroup.metrics.ipv6RequestCount`` instead
  This API will be removed in the next major release.
[WARNING] aws-cdk-lib.aws_elasticloadbalancingv2.ApplicationTargetGroup#metricRequestCountPerTarget is deprecated.
  Use ``ApplicationTargetGroup.metrics.ipv6RequestCount`` instead
  This API will be removed in the next major release.
[WARNING] aws-cdk-lib.aws_elasticloadbalancingv2.ApplicationTargetGroup#metricRequestCountPerTarget is deprecated.
  Use ``ApplicationTargetGroup.metrics.ipv6RequestCount`` instead
  This API will be removed in the next major release.
[WARNING] aws-cdk-lib.aws_elasticloadbalancingv2.ApplicationTargetGroup#metricRequestCountPerTarget is deprecated.
  Use ``ApplicationTargetGroup.metrics.ipv6RequestCount`` instead
  This API will be removed in the next major release.
[WARNING] aws-cdk-lib.aws_elasticloadbalancingv2.ApplicationTargetGroup#metricRequestCountPerTarget is deprecated.
  Use ``ApplicationTargetGroup.metrics.ipv6RequestCount`` instead
  This API will be removed in the next major release.
[WARNING] aws-cdk-lib.aws_elasticloadbalancingv2.ApplicationTargetGroup#metricRequestCountPerTarget is deprecated.
  Use ``ApplicationTargetGroup.metrics.ipv6RequestCount`` instead
  This API will be removed in the next major release.
[WARNING] aws-cdk-lib.aws_elasticloadbalancingv2.ApplicationTargetGroup#metricHttpCodeTarget is deprecated.
  Use ``ApplicationTargetGroup.metrics.httpCodeTarget`` instead
  This API will be removed in the next major release.
[WARNING] aws-cdk-lib.aws_elasticloadbalancingv2.ApplicationTargetGroup#metricHttpCodeTarget is deprecated.
  Use ``ApplicationTargetGroup.metrics.httpCodeTarget`` instead
  This API will be removed in the next major release.
[WARNING] aws-cdk-lib.aws_elasticloadbalancingv2.ApplicationTargetGroup#metricHttpCodeTarget is deprecated.
  Use ``ApplicationTargetGroup.metrics.httpCodeTarget`` instead
  This API will be removed in the next major release.
[WARNING] aws-cdk-lib.aws_elasticloadbalancingv2.ApplicationTargetGroup#metricHttpCodeTarget is deprecated.
  Use ``ApplicationTargetGroup.metrics.httpCodeTarget`` instead
  This API will be removed in the next major release.
[WARNING] aws-cdk-lib.aws_elasticloadbalancingv2.ApplicationTargetGroup#metricHttpCodeTarget is deprecated.
  Use ``ApplicationTargetGroup.metrics.httpCodeTarget`` instead
  This API will be removed in the next major release.
[WARNING] aws-cdk-lib.aws_elasticloadbalancingv2.ApplicationTargetGroup#metricHttpCodeTarget is deprecated.
  Use ``ApplicationTargetGroup.metrics.httpCodeTarget`` instead
  This API will be removed in the next major release.
[WARNING] aws-cdk-lib.aws_elasticloadbalancingv2.ApplicationTargetGroup#metricHttpCodeTarget is deprecated.
  Use ``ApplicationTargetGroup.metrics.httpCodeTarget`` instead
  This API will be removed in the next major release.
[WARNING] aws-cdk-lib.aws_elasticloadbalancingv2.ApplicationTargetGroup#metricHttpCodeTarget is deprecated.
  Use ``ApplicationTargetGroup.metrics.httpCodeTarget`` instead
  This API will be removed in the next major release.
[WARNING] aws-cdk-lib.aws_elasticloadbalancingv2.ApplicationTargetGroup#metricHttpCodeTarget is deprecated.
  Use ``ApplicationTargetGroup.metrics.httpCodeTarget`` instead
  This API will be removed in the next major release.
[WARNING] aws-cdk-lib.aws_elasticloadbalancingv2.ApplicationTargetGroup#metricHttpCodeTarget is deprecated.
  Use ``ApplicationTargetGroup.metrics.httpCodeTarget`` instead
  This API will be removed in the next major release.
[WARNING] aws-cdk-lib.aws_elasticloadbalancingv2.ApplicationTargetGroup#metricHttpCodeTarget is deprecated.
  Use ``ApplicationTargetGroup.metrics.httpCodeTarget`` instead
  This API will be removed in the next major release.
[WARNING] aws-cdk-lib.aws_elasticloadbalancingv2.ApplicationTargetGroup#metricHttpCodeTarget is deprecated.
  Use ``ApplicationTargetGroup.metrics.httpCodeTarget`` instead
  This API will be removed in the next major release.
[WARNING] aws-cdk-lib.aws_elasticloadbalancingv2.ApplicationTargetGroup#metricHttpCodeTarget is deprecated.
  Use ``ApplicationTargetGroup.metrics.httpCodeTarget`` instead
  This API will be removed in the next major release.
[WARNING] aws-cdk-lib.aws_elasticloadbalancingv2.ApplicationTargetGroup#metricHttpCodeTarget is deprecated.
  Use ``ApplicationTargetGroup.metrics.httpCodeTarget`` instead
  This API will be removed in the next major release.
[WARNING] aws-cdk-lib.aws_certificatemanager.DnsValidatedCertificate is deprecated.
  use {@link Certificate} instead
  This API will be removed in the next major release.
[WARNING] aws-cdk-lib.aws_certificatemanager.DnsValidatedCertificate is deprecated.
  use {@link Certificate} instead
  This API will be removed in the next major release.
current credentials could not be used to assume 'arn:aws:iam::XXXXXXXXXXXX:role/cdk-hnb659fds-lookup-role-XXXXXXXXXXXX-eu-west-2', but are for the right account. Proceeding anyway.
[WARNING] aws-cdk-lib.aws_ec2.VpcProps#cidr is deprecated.
  Use ipAddresses instead
  This API will be removed in the next major release.
[WARNING] aws-cdk-lib.aws_certificatemanager.DnsValidatedCertificate is deprecated.
  use {@link Certificate} instead
  This API will be removed in the next major release.
[WARNING] aws-cdk-lib.aws_certificatemanager.DnsValidatedCertificate is deprecated.
  use {@link Certificate} instead
  This API will be removed in the next major release.
[WARNING] aws-cdk-lib.aws_certificatemanager.DnsValidatedCertificate is deprecated.
  use {@link Certificate} instead
  This API will be removed in the next major release.
[WARNING] aws-cdk-lib.aws_elasticloadbalancingv2.ApplicationTargetGroup#metricHealthyHostCount is deprecated.
  Use ``ApplicationTargetGroup.metrics.healthyHostCount`` instead
  This API will be removed in the next major release.
[WARNING] aws-cdk-lib.aws_elasticloadbalancingv2.ApplicationTargetGroup#metricHealthyHostCount is deprecated.
  Use ``ApplicationTargetGroup.metrics.healthyHostCount`` instead
  This API will be removed in the next major release.
[WARNING] aws-cdk-lib.aws_elasticloadbalancingv2.ApplicationTargetGroup#metricHealthyHostCount is deprecated.
  Use ``ApplicationTargetGroup.metrics.healthyHostCount`` instead
  This API will be removed in the next major release.
[WARNING] aws-cdk-lib.aws_elasticloadbalancingv2.ApplicationTargetGroup#metricHealthyHostCount is deprecated.
  Use ``ApplicationTargetGroup.metrics.healthyHostCount`` instead
  This API will be removed in the next major release.
[WARNING] aws-cdk-lib.aws_elasticloadbalancingv2.ApplicationTargetGroup#metricHealthyHostCount is deprecated.
  Use ``ApplicationTargetGroup.metrics.healthyHostCount`` instead
  This API will be removed in the next major release.
[WARNING] aws-cdk-lib.aws_elasticloadbalancingv2.ApplicationTargetGroup#metricHealthyHostCount is deprecated.
  Use ``ApplicationTargetGroup.metrics.healthyHostCount`` instead
  This API will be removed in the next major release.
[WARNING] aws-cdk-lib.aws_elasticloadbalancingv2.ApplicationTargetGroup#metricHealthyHostCount is deprecated.
  Use ``ApplicationTargetGroup.metrics.healthyHostCount`` instead
  This API will be removed in the next major release.
[WARNING] aws-cdk-lib.aws_elasticloadbalancingv2.ApplicationTargetGroup#metricTargetResponseTime is deprecated.
  Use ``ApplicationTargetGroup.metrics.targetResponseTime`` instead
  This API will be removed in the next major release.
[WARNING] aws-cdk-lib.aws_elasticloadbalancingv2.ApplicationTargetGroup#metricTargetResponseTime is deprecated.
  Use ``ApplicationTargetGroup.metrics.targetResponseTime`` instead
  This API will be removed in the next major release.
[WARNING] aws-cdk-lib.aws_elasticloadbalancingv2.ApplicationTargetGroup#metricTargetResponseTime is deprecated.
  Use ``ApplicationTargetGroup.metrics.targetResponseTime`` instead
  This API will be removed in the next major release.
[WARNING] aws-cdk-lib.aws_elasticloadbalancingv2.ApplicationTargetGroup#metricTargetResponseTime is deprecated.
  Use ``ApplicationTargetGroup.metrics.targetResponseTime`` instead
  This API will be removed in the next major release.
[WARNING] aws-cdk-lib.aws_elasticloadbalancingv2.ApplicationTargetGroup#metricTargetResponseTime is deprecated.
  Use ``ApplicationTargetGroup.metrics.targetResponseTime`` instead
  This API will be removed in the next major release.
[WARNING] aws-cdk-lib.aws_elasticloadbalancingv2.ApplicationTargetGroup#metricTargetResponseTime is deprecated.
  Use ``ApplicationTargetGroup.metrics.targetResponseTime`` instead
  This API will be removed in the next major release.
[WARNING] aws-cdk-lib.aws_elasticloadbalancingv2.ApplicationTargetGroup#metricTargetResponseTime is deprecated.
  Use ``ApplicationTargetGroup.metrics.targetResponseTime`` instead
  This API will be removed in the next major release.
[WARNING] aws-cdk-lib.aws_elasticloadbalancingv2.ApplicationTargetGroup#metricHttpCodeTarget is deprecated.
  Use ``ApplicationTargetGroup.metrics.httpCodeTarget`` instead
  This API will be removed in the next major release.
[WARNING] aws-cdk-lib.aws_elasticloadbalancingv2.ApplicationTargetGroup#metricHttpCodeTarget is deprecated.
  Use ``ApplicationTargetGroup.metrics.httpCodeTarget`` instead
  This API will be removed in the next major release.
[WARNING] aws-cdk-lib.aws_elasticloadbalancingv2.ApplicationTargetGroup#metricHttpCodeTarget is deprecated.
  Use ``ApplicationTargetGroup.metrics.httpCodeTarget`` instead
  This API will be removed in the next major release.
[WARNING] aws-cdk-lib.aws_elasticloadbalancingv2.ApplicationTargetGroup#metricHttpCodeTarget is deprecated.
  Use ``ApplicationTargetGroup.metrics.httpCodeTarget`` instead
  This API will be removed in the next major release.
[WARNING] aws-cdk-lib.aws_elasticloadbalancingv2.ApplicationTargetGroup#metricHttpCodeTarget is deprecated.
  Use ``ApplicationTargetGroup.metrics.httpCodeTarget`` instead
  This API will be removed in the next major release.
[WARNING] aws-cdk-lib.aws_elasticloadbalancingv2.ApplicationTargetGroup#metricHttpCodeTarget is deprecated.
  Use ``ApplicationTargetGroup.metrics.httpCodeTarget`` instead
  This API will be removed in the next major release.
[WARNING] aws-cdk-lib.aws_elasticloadbalancingv2.ApplicationTargetGroup#metricHttpCodeTarget is deprecated.
  Use ``ApplicationTargetGroup.metrics.httpCodeTarget`` instead
  This API will be removed in the next major release.
[WARNING] aws-cdk-lib.aws_elasticloadbalancingv2.ApplicationTargetGroup#metricRequestCountPerTarget is deprecated.
  Use ``ApplicationTargetGroup.metrics.ipv6RequestCount`` instead
  This API will be removed in the next major release.
[WARNING] aws-cdk-lib.aws_elasticloadbalancingv2.ApplicationTargetGroup#metricRequestCountPerTarget is deprecated.
  Use ``ApplicationTargetGroup.metrics.ipv6RequestCount`` instead
  This API will be removed in the next major release.
[WARNING] aws-cdk-lib.aws_elasticloadbalancingv2.ApplicationTargetGroup#metricRequestCountPerTarget is deprecated.
  Use ``ApplicationTargetGroup.metrics.ipv6RequestCount`` instead
  This API will be removed in the next major release.
[WARNING] aws-cdk-lib.aws_elasticloadbalancingv2.ApplicationTargetGroup#metricRequestCountPerTarget is deprecated.
  Use ``ApplicationTargetGroup.metrics.ipv6RequestCount`` instead
  This API will be removed in the next major release.
[WARNING] aws-cdk-lib.aws_elasticloadbalancingv2.ApplicationTargetGroup#metricRequestCountPerTarget is deprecated.
  Use ``ApplicationTargetGroup.metrics.ipv6RequestCount`` instead
  This API will be removed in the next major release.
[WARNING] aws-cdk-lib.aws_elasticloadbalancingv2.ApplicationTargetGroup#metricRequestCountPerTarget is deprecated.
  Use ``ApplicationTargetGroup.metrics.ipv6RequestCount`` instead
  This API will be removed in the next major release.
[WARNING] aws-cdk-lib.aws_elasticloadbalancingv2.ApplicationTargetGroup#metricRequestCountPerTarget is deprecated.
  Use ``ApplicationTargetGroup.metrics.ipv6RequestCount`` instead
  This API will be removed in the next major release.
[WARNING] aws-cdk-lib.aws_elasticloadbalancingv2.ApplicationTargetGroup#metricHttpCodeTarget is deprecated.
  Use ``ApplicationTargetGroup.metrics.httpCodeTarget`` instead
  This API will be removed in the next major release.
[WARNING] aws-cdk-lib.aws_elasticloadbalancingv2.ApplicationTargetGroup#metricHttpCodeTarget is deprecated.
  Use ``ApplicationTargetGroup.metrics.httpCodeTarget`` instead
  This API will be removed in the next major release.
[WARNING] aws-cdk-lib.aws_elasticloadbalancingv2.ApplicationTargetGroup#metricHttpCodeTarget is deprecated.
  Use ``ApplicationTargetGroup.metrics.httpCodeTarget`` instead
  This API will be removed in the next major release.
[WARNING] aws-cdk-lib.aws_elasticloadbalancingv2.ApplicationTargetGroup#metricHttpCodeTarget is deprecated.
  Use ``ApplicationTargetGroup.metrics.httpCodeTarget`` instead
  This API will be removed in the next major release.
[WARNING] aws-cdk-lib.aws_elasticloadbalancingv2.ApplicationTargetGroup#metricHttpCodeTarget is deprecated.
  Use ``ApplicationTargetGroup.metrics.httpCodeTarget`` instead
  This API will be removed in the next major release.
[WARNING] aws-cdk-lib.aws_elasticloadbalancingv2.ApplicationTargetGroup#metricHttpCodeTarget is deprecated.
  Use ``ApplicationTargetGroup.metrics.httpCodeTarget`` instead
  This API will be removed in the next major release.
[WARNING] aws-cdk-lib.aws_elasticloadbalancingv2.ApplicationTargetGroup#metricHttpCodeTarget is deprecated.
  Use ``ApplicationTargetGroup.metrics.httpCodeTarget`` instead
  This API will be removed in the next major release.
[WARNING] aws-cdk-lib.aws_elasticloadbalancingv2.ApplicationTargetGroup#metricHttpCodeTarget is deprecated.
  Use ``ApplicationTargetGroup.metrics.httpCodeTarget`` instead
  This API will be removed in the next major release.
[WARNING] aws-cdk-lib.aws_elasticloadbalancingv2.ApplicationTargetGroup#metricHttpCodeTarget is deprecated.
  Use ``ApplicationTargetGroup.metrics.httpCodeTarget`` instead
  This API will be removed in the next major release.
[WARNING] aws-cdk-lib.aws_elasticloadbalancingv2.ApplicationTargetGroup#metricHttpCodeTarget is deprecated.
  Use ``ApplicationTargetGroup.metrics.httpCodeTarget`` instead
  This API will be removed in the next major release.
[WARNING] aws-cdk-lib.aws_elasticloadbalancingv2.ApplicationTargetGroup#metricHttpCodeTarget is deprecated.
  Use ``ApplicationTargetGroup.metrics.httpCodeTarget`` instead
  This API will be removed in the next major release.
[WARNING] aws-cdk-lib.aws_elasticloadbalancingv2.ApplicationTargetGroup#metricHttpCodeTarget is deprecated.
  Use ``ApplicationTargetGroup.metrics.httpCodeTarget`` instead
  This API will be removed in the next major release.
[WARNING] aws-cdk-lib.aws_elasticloadbalancingv2.ApplicationTargetGroup#metricHttpCodeTarget is deprecated.
  Use ``ApplicationTargetGroup.metrics.httpCodeTarget`` instead
  This API will be removed in the next major release.
[WARNING] aws-cdk-lib.aws_elasticloadbalancingv2.ApplicationTargetGroup#metricHttpCodeTarget is deprecated.
  Use ``ApplicationTargetGroup.metrics.httpCodeTarget`` instead
  This API will be removed in the next major release.
[WARNING] aws-cdk-lib.aws_certificatemanager.DnsValidatedCertificate is deprecated.
  use {@link Certificate} instead
  This API will be removed in the next major release.
[WARNING] aws-cdk-lib.aws_certificatemanager.DnsValidatedCertificate is deprecated.
  use {@link Certificate} instead
  This API will be removed in the next major release.
 ⏳  Bootstrapping environment aws://XXXXXXXXXXXX/us-east-1...
Trusted accounts for deployment: (none)
Trusted accounts for lookup: (none)
Execution policies: arn:aws:iam::XXXXXXXXXXXX:policy/emisresearch-cdk-bootstrap-managed-policy
CDKToolkit: creating CloudFormation changeset...
CDKToolkit | 0/9 | 6:05:28 AM | UPDATE_IN_PROGRESS   | AWS::CloudFormation::Stack | CDKToolkit User Initiated
CDKToolkit | 0/9 | 6:05:33 AM | UPDATE_IN_PROGRESS   | AWS::S3::Bucket         | StagingBucket 
CDKToolkit | 0/9 | 6:05:34 AM | UPDATE_IN_PROGRESS   | AWS::ECR::Repository    | ContainerAssetsRepository 
CDKToolkit | 0/9 | 6:05:34 AM | UPDATE_FAILED        | AWS::S3::Bucket         | StagingBucket API: s3:PutLifecycleConfiguration Access Denied
CDKToolkit | 0/9 | 6:05:34 AM | UPDATE_IN_PROGRESS   | AWS::SSM::Parameter     | CdkBootstrapVersion 
CDKToolkit | 0/9 | 6:05:35 AM | UPDATE_FAILED        | AWS::SSM::Parameter     | CdkBootstrapVersion Resource update cancelled
CDKToolkit | 0/9 | 6:05:35 AM | UPDATE_FAILED        | AWS::ECR::Repository    | ContainerAssetsRepository Resource update cancelled
CDKToolkit | 0/9 | 6:05:36 AM | UPDATE_ROLLBACK_IN_P | AWS::CloudFormation::Stack | CDKToolkit The following resource(s) failed to update: [CdkBootstrapVersion, StagingBucket, ContainerAssetsRepository]. 
CDKToolkit | 1/9 | 6:05:48 AM | UPDATE_COMPLETE      | AWS::ECR::Repository    | ContainerAssetsRepository 
CDKToolkit | 2/9 | 6:05:49 AM | UPDATE_COMPLETE      | AWS::S3::Bucket         | StagingBucket 
CDKToolkit | 3/9 | 6:05:49 AM | UPDATE_COMPLETE      | AWS::SSM::Parameter     | CdkBootstrapVersion 
CDKToolkit | 4/9 | 6:05:50 AM | UPDATE_ROLLBACK_COMP | AWS::CloudFormation::Stack | CDKToolkit 
CDKToolkit | 5/9 | 6:05:51 AM | UPDATE_ROLLBACK_COMP | AWS::CloudFormation::Stack | CDKToolkit 

Failed resources:
CDKToolkit | 6:05:34 AM | UPDATE_FAILED        | AWS::S3::Bucket         | StagingBucket API: s3:PutLifecycleConfiguration Access Denied
 ❌  Environment aws://XXXXXXXXXXXX/us-east-1 failed bootstrapping: Error: The stack named CDKToolkit failed to deploy: UPDATE_ROLLBACK_COMPLETE: API: s3:PutLifecycleConfiguration Access Denied
    at FullCloudFormationDeployment.monitorDeployment (/codebuild/output/src793897557/src/node_modules/aws-cdk/lib/api/deploy-stack.ts:512:13)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at /codebuild/output/src793897557/src/node_modules/aws-cdk/lib/cdk-toolkit.ts:651:24
    at async Promise.all (index 0)
    at CdkToolkit.bootstrap (/codebuild/output/src793897557/src/node_modules/aws-cdk/lib/cdk-toolkit.ts:648:5)
    at exec4 (/codebuild/output/src793897557/src/node_modules/aws-cdk/lib/cli.ts:403:12)

The stack named CDKToolkit failed to deploy: UPDATE_ROLLBACK_COMPLETE: API: s3:PutLifecycleConfiguration Access Denied
```

**Comment by emisbalu** [comment]
@pahud any development on this?

**Comment by pahud** [comment]
@emisbalu 

Hi,  are you running the CDK CLI in a container?

Can you run `cdk bootstrap` without `npx` in an empty directory like this?

```sh
$ mkdir empty
$ cdk empty
$ cdk bootstrap aws://xxxxx/us-east-1 --debug
```

From what I can tell from your log:

>Execution policies: arn:aws:iam::XXXXXXXXXXXX:policy/emisresearch-cdk-bootstrap-managed-policy

And this seems your execution policy is missing `s3:PutLifecycleConfiguration` which is required. I guess you probably have bootstrapped before with custom IAM policy because the default policy should be `AdministratorAccess` as described in the [doc](https://docs.aws.amazon.com/cdk/v2/guide/bootstrapping.html#bootstrapping-customizing). If `emisresearch-cdk-bootstrap-managed-policy` is still mandatory, you probably need to add `s3:PutLifecycleConfiguration` to your custom policy.

**Comment by emisbalu** [comment]
@pahud 

Yes, I have been running in AWS Codebuild.

I can confirm the policy used for `--cloudformation-execution-policies` has the permission `s3:PutLifecycleConfiguration`

However, the role I assumed in the Codebuild (to generate sts tokens) is missing the `s3:PutLifecycleConfiguration` permission. I added the above permission to the role, and it fixed the issue

I am confused now between `--cloudformation-execution-policies` and the policy attached to the role that I assumed in the Codebuild, which takes priority, any guidance would help

Thanks.

**Comment by pahud** [comment]
Hi

So this seems to be a required permission by the codebuild execution role, rather than the `--cloudformation-execution-policies` required by `cdk bootstrap`.

Please note you only need to run `cdk bootstrap` for once when you first attempt to deploy your CDK app in a new region.

According to the [doc](https://docs.aws.amazon.com/cdk/v2/guide/bootstrapping.html):
>The CDK Toolkit always synthesizes the AWS CDK app in the current directory. If you do not specify at least one environment in the cdk bootstrap command, it bootstraps all the environments referenced in the app.

So it's recommended to run `cdk bootstrap` in an empty project directory. 

And your issues seems to be the codebuild execution role missing required permissions, which is not related to `cdk bootstrap`.

You can always run `cdk diff` in your cdk application and see if it synthesizes correctly and print the output.

I am moving this to discussion and if you still have any questions about codebuild, feel free to bring it up in the discussion.
