### ISSUE TITLE
aws-lambda-python-alpha: "jsii-kernel-sZg8MV/node_modules/@aws-cdk/aws-lambda-python-alpha/lib/Containerfile: no such file or directory"

### ISSUE THREAD

**Issue by robert-hanuschke** [aws/aws-cdk#24458]
### Describe the bug

Hello,

I have a cdk project defined in Python and some Python Lambda functions defined in one of the stacks based on aws-lambda-python-alpha (2.67.0a0).
My machine is a Mac. When I want to deploy, I get the following error:

```
time="2023-03-05T13:30:52Z" level=fatal msg="lstat /private/var/folders/2t/f5v_syfd3bd1z5vk1h6mb15m0000gr/T/jsii-kernel-sZg8MV/node_modules/@aws-cdk/aws-lambda-python-alpha/lib/Containerfile: no such file or directory"
time="2023-03-05T14:30:52+01:00" level=fatal msg="exit status 1"
jsii.errors.JavaScriptError: 
  Error: docker exited with status 1
      at Object.dockerExec (/private/var/folders/2t/f5v_syfd3bd1z5vk1h6mb15m0000gr/T/jsii-kernel-sZg8MV/node_modules/aws-cdk-lib/core/lib/private/asset-staging.js:4:45)
      at Function.fromBuild (/private/var/folders/2t/f5v_syfd3bd1z5vk1h6mb15m0000gr/T/jsii-kernel-sZg8MV/node_modules/aws-cdk-lib/core/lib/bundling.js:1:4198)
      at new Bundling (/private/var/folders/2t/f5v_syfd3bd1z5vk1h6mb15m0000gr/T/jsii-kernel-sZg8MV/node_modules/@aws-cdk/aws-lambda-python-alpha/lib/bundling.js:31:57)
      at Function.bundle (/private/var/folders/2t/f5v_syfd3bd1z5vk1h6mb15m0000gr/T/jsii-kernel-sZg8MV/node_modules/@aws-cdk/aws-lambda-python-alpha/lib/bundling.js:54:50)
      at new PythonFunction (/private/var/folders/2t/f5v_syfd3bd1z5vk1h6mb15m0000gr/T/jsii-kernel-sZg8MV/node_modules/@aws-cdk/aws-lambda-python-alpha/lib/function.js:43:39)
      at Kernel._create (/private/var/folders/2t/f5v_syfd3bd1z5vk1h6mb15m0000gr/T/tmp9aqp7_nw/lib/program.js:9937:29)
      at Kernel.create (/private/var/folders/2t/f5v_syfd3bd1z5vk1h6mb15m0000gr/T/tmp9aqp7_nw/lib/program.js:9666:29)
      at KernelHost.processRequest (/private/var/folders/2t/f5v_syfd3bd1z5vk1h6mb15m0000gr/T/tmp9aqp7_nw/lib/program.js:11514:36)
      at KernelHost.run (/private/var/folders/2t/f5v_syfd3bd1z5vk1h6mb15m0000gr/T/tmp9aqp7_nw/lib/program.js:11474:22)
      at Immediate._onImmediate (/private/var/folders/2t/f5v_syfd3bd1z5vk1h6mb15m0000gr/T/tmp9aqp7_nw/lib/program.js:11475:46)
```

I tried

- removing and re-adding aws-cdk-aws-lambda-python-alpha to the project
- reinstalling cdk
- recreating my project virtual environment completely and installing all dependencies again
- a lower version of aws-lambda-python-alpha (2.64.0a0)
- simplifying my code to the documentation example of the python lambda

All to no avail unfortunately.

How can I fix this?

### Expected Behavior

deployment working normally

### Current Behavior

deployment failing with above message

### Reproduction Steps

I assume this very much to be related to my local environment as it happens for multiple versions of the module with only the doc example:

`python.PythonFunction(self, "MyFunction",
    entry="/tmp",  # required
    runtime=lambda_.Runtime.PYTHON_3_8,  # required
    index="my_index.py",  # optional, defaults to 'index.py'
    handler="my_exported_func"
)`

### CDK CLI Version

2.67.0 (build b6f7f39)

### Node.js Version

v16.19.0

### OS

macOS 12.6.3

### Language

Python

**Comment by pahud** [comment]
Unfortunately we can't help you troubleshooting without any provided code. Is it possible for you to share an simplified repo that we can simply clone and check in our environment?

**Comment by robert-hanuschke** [comment]
It already fails with the provided code practically straight from the docs.

`python.PythonFunction(self, "MyFunction", entry="/tmp",  runtime=lambda_.Runtime.PYTHON_3_8,  index="my_index.py",  handler="my_exported_func" )`

It does not matter what is inside my_index.py.

**Comment by rix0rrr** [comment]
The issue appears to be the use of `finch` vs the use of actual `docker`

**Comment by rix0rrr** [comment]
The reason is that your temporary directory is not automatically mapped into the finch VM. Do the following:

```sh
$ echo $TMPDIR
/var/folders/zx/d5wln9n10sn0tcj1v9798f1c0000gr/T/
```

Add this directory into `~/.finch/finch.yaml`:

```yaml
cpus: 3
memory: 4GiB
additional_directories:
    - path: /private/var/folders/zx/d5wln9n10sn0tcj1v9798f1c0000gr/T
```
