### ISSUE TITLE
integ-tests: Response is not valid JSON

### ISSUE THREAD

**Issue by nikovirtala** [aws/aws-cdk#24491]
### Describe the bug

The integration test fails if the expected result object contains UTF-8 characters.

### Expected Behavior

The test should return a successful status if the expectation match, regardless of what kind of data the user is trying to assert.

### Current Behavior

The test fails with the following error:

```
 ❌  IntegTest/DefaultTest/DeployAssert failed: Error: The stack named IntegTestDefaultTestDeployAssertE3E7D2A4 failed to deploy: CREATE_FAILED (The following resource(s) failed to create: [AwsApiCallDynamoDBquery]. ): Response is not valid JSON
    at FullCloudFormationDeployment.monitorDeployment (/Users/nikovirtala/src/github.com/nikovirtala/integ-runner-proto/node_modules/aws-cdk/lib/index.js:344:10235)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async deployStack2 (/Users/nikovirtala/src/github.com/nikovirtala/integ-runner-proto/node_modules/aws-cdk/lib/index.js:347:144797)
    at async /Users/nikovirtala/src/github.com/nikovirtala/integ-runner-proto/node_modules/aws-cdk/lib/index.js:347:130251
    at async run (/Users/nikovirtala/src/github.com/nikovirtala/integ-runner-proto/node_modules/aws-cdk/lib/index.js:347:128257)
```

### Reproduction Steps

Run the test described in: https://github.com/nikovirtala/integ-runner-proto/blob/main/test/integ.not-valid-json.ts

### Possible Solution

Maybe we shouldn't send full data objects to CloudFormation? — I don't see the data being displayed to the user.

### CDK CLI Version

2.66.1

### Node.js Version

v18.14.2

### OS

macOS Ventura

### Language

Typescript

### Language Version

4.9.5

**Comment by mrgrain** [comment]
Note this can be reproduced with any custom resource.
