### ISSUE TITLE
(core): Ability to turn off specific deprecations

### ISSUE THREAD

**Issue by moltar** [aws/aws-cdk#24512]
### Describe the feature

I'd like to be able to turn off (ack) _some_ deprecation notices, but keep others.

### Use Case

Turn off `DnsValidatedCertificate` notice.

We know the issue, but there is currently no good solution or path forward. The feature was deprecated without a matching replacement.

This warning shows up everywhere in our workflows and is very annoying. It can also cause warning blindness eventually, as developers learn to ignore it, but can also ignore others.

I want to be able to turn off this specific deprecation.

### Proposed Solution

N/A

### Other Information

```
    console.warn
Warning: RNING] aws-cdk-lib.aws_certificatemanager.DnsValidatedCertificate is deprecated.
        use {@link Certificate} instead
        This API will be removed in the next major release.

      119 |      * @see https://github.com/aws/aws-cdk/pull/21982
      120 |      */
    > 121 |     const certificate = new aws_certificatemanager.DnsValidatedCertificate(this, 'ACMCertificate', {
          |                         ^
      122 |       domainName: properties.hostedZone.zoneName,
      123 |       hostedZone: properties.hostedZone,
      124 |       /**

      at Object.print (node_modules/aws-cdk-lib/.warnings.jsii.js:3:146)
      at new DnsValidatedCertificate (node_modules/aws-cdk-lib/aws-certificatemanager/lib/dns-validated-certificate.js:1:639)
```

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### CDK version used

latest

### Environment details (OS name and version, etc.)

macOS

**Comment by pahud** [comment]
Yes this makes sense.  Please help us prioritize this feature with 👍 .

**Comment by LeoLapworthKT** [comment]
Generally having something depreciated with no viable replacement is concerning

**Comment by LeoLapworthKT** [comment]
> Generally having something depreciated with no viable replacement is concerning

I've found the cross region example in https://github.com/aws/aws-cdk/commit/64bfbf9b981a32a4db1b07476144d280d6eced32 - will have to review how this would actually work for us

**Comment by moltar** [comment]
@LeoLapworthKT I believe you meant to post in another issue. This is about turning off warnings, with the example being the `DnsValidatedCertificate` warning. It's **not** about the deprecation itself of the `DnsValidatedCertificate` construct. There's another issue for that. Please consider hiding your comments as "offtopic" so they do not confuse the issues. You can click the three dots menu `...` and choose "Hide". Thanks!

**Comment by metametadata** [comment]
Workaround in Clojure/Java is to manually filter `System/err`:

```clj
(ns ...
  (:import [java.io PrintStream]
           [java.nio.charset StandardCharsets]))

; HACK: suppress "[WARNING] aws-cdk-lib.aws_certificatemanager.DnsValidatedCertificate is deprecated" log.
; The log originates from System.err.write call in software.amazon.jsii.JsiiRuntime.ErrorStreamSink.
; https://github.com/aws/aws-cdk/issues/25343, https://github.com/aws/aws-cdk/issues/24512.
(System/setErr
  (proxy [PrintStream] [System/err]
    (write
      ([x]
       (proxy-super write x))
      ([^bytes buf off len]
       (let [s (String. buf StandardCharsets/UTF_8)]
         (when (not (str/includes? s "DnsValidatedCertificate is deprecated"))
           (proxy-super write buf off len)))))))
```
