### ISSUE TITLE
Dotnet - Amazon.CDK.AWS.Lambda.EventSources: DynamoEventSource expects an ITable, does not support CfnGlobalTable

### ISSUE THREAD

**Issue by Simonl9l** [aws/aws-cdk#24607]
### Describe the bug

Looking to set up a `DynamoEventSource` from a Dynamo DB Global Table. We need to use `CfnGlobalTable` as this support the latest version and has better support for replicas.
``[](url)

### Expected Behavior

We expected either the `DynamoEventSource` to accept the `CfnGlobalTable` or the  `CfnGlobalTable` expose `ITable` to make the hook up seemless.

### Current Behavior

We have no known way to hook up the global table.

### Reproduction Steps

define a `CfnGlobalTable`, and a Function `and` attempt to `AddEventSource` to the Lambda.

``` C#
 var table = new CfnGlobalTable(this, "tableName", new CfnGlobalTableProps
 {
 ...               
    StreamSpecification = new CfnGlobalTable.StreamSpecificationProperty
    {
         StreamViewType = StreamViewType.NEW_AND_OLD_IMAGES
     },
    ....
});

var fn = new Function(this, "name", new FunctionProps
{
      ...
});

fn.AddEventSource(new DynamoEventSource(table, new DynamoEventSourceProps
{
    Enabled = true,
}));
```

### Possible Solution

Fix up s the integration is seamless...

### Additional Information/Context

`CfnEventSourceMapping` is a possible alternative, but is not fully integrated it seems:

```C#
var mapping = new CfnEventSourceMapping(this, $"{props.Environment}-TenantStreamEnricherMapping",
     new CfnEventSourceMappingProps
     {
         FunctionName = fn.FunctionName,
         EventSourceArn = table.AttrStreamArn,
         StartingPosition = "LATEST",
  });

mapping.addPropertyOverride('FilterCriteria', {
    Filters: [
        {
             Pattern: { // your filterpattern here}
    ],
 });
```

### CDK CLI Version

2.61.1 

### Framework Version

Dotnet 7

### Node.js Version

18.0.0

### OS

MacOS

### Language

.NET

### Language Version

DotNet 7

**Comment by pahud** [comment]
Yeah the constructor of `DynamoEventSource` only accepts `ITable` now. We should consider to support Global Table as well.

https://github.com/aws/aws-cdk/blob/0b822b36bc2bb8d786d9c2fb7c8f493d80564384/packages/%40aws-cdk/aws-lambda-event-sources/lib/dynamodb.ts#L15

I am making it p2 feature request now. Any PR submission would be highly welcome and appreciated.

**Comment by Simonl9l** [comment]
@pahud thanks!


I'm unfortunately very ill equipped on the PR side of things, being nearly able to make any use of CDK in .Net....

In the mean time please can you advise on how best to set up the `FilterCriteria` override in .net as I seem unable to find any samples in the documentation or elsewhere  as this does not work...

```C#
 mapping.AddOverride("FilterCriteria", new Dictionary<string, object>
{
    {
        "Filters", new[]
            {
                FilterCriteria.Filter(new Dictionary<string, object>
                {
                    { "eventName", FilterRule.IsEqual("INSERT") } 
                })
           }
      }
});
```

I get no intelligible error
```
Unhandled exception. System.ArgumentException: Could not infer JSII type for .NET type 'IDictionary`2' (Parameter 'type')
      at Amazon.JSII.Runtime.Services.Converters.FrameworkToJsiiConverter.InferType(IReferenceMap referenceMap, Type type)
      at Amazon.JSII.Runtime.Services.Converters.FrameworkToJsiiConverter.InferType(IReferenceMap referenceMap, Type type)
      at Amazon.JSII.Runtime.Services.Converters.FrameworkToJsiiConverter.InferType(IReferenceMap referenceMap, Object value)
      at Amazon.JSII.Runtime.Services.Converters.FrameworkToJsiiConverter.TryConvertCollectionElement(Object element, IReferenceMap referenceMap, TypeReference elementType, Object& convertedElement)
      at Amazon.JSII.Runtime.Services.Converters.FrameworkToJsiiConverter.TryConvertMap(IReferenceMap referenceMap, TypeReference elementType, Object value, Object& result)
      at Amazon.JSII.Runtime.Services.Converters.ValueConverter.TryConvertCollection(IReferenceMap referenceMap, Object value, CollectionTypeReference collectionType, Object& result)
      at Amazon.JSII.Runtime.Services.Converters.ValueConverter.TryConvert(IOptionalValue optionalValue, Type type, IReferenceMap referenceMap, Object value, Object& result)
      at Amazon.JSII.Runtime.Services.Converters.ValueConverter.TryConvert(TypeReference typeReference, Type type, IReferenceMap referenceMap, Object value, Object& result)
      at Amazon.JSII.Runtime.Services.Converters.ValueConverter.ConvertAny(Type type, IReferenceMap referenceMap, Object value)
      at Amazon.JSII.Runtime.Services.Converters.ValueConverter.TryConvertPrimitive(Type type, IReferenceMap referenceMap, Object value, Boolean isOptional, PrimitiveType primitiveType, Object& result)
      at Amazon.JSII.Runtime.Services.Converters.ValueConverter.TryConvert(IOptionalValue optionalValue, Type type, IReferenceMap referenceMap, Object value, Object& result)
      at Amazon.JSII.Runtime.Services.Converters.FrameworkToJsiiConverter.TryConvert(IOptionalValue optionalValue, IReferenceMap referenceMap, Object value, Object& result)
      at Amazon.JSII.Runtime.Deputy.DeputyBase.<>c__DisplayClass20_0.<ConvertArguments>b__0(Parameter parameter, Object frameworkArgument)
      at System.Linq.Enumerable.ZipIterator[TFirst,TSecond,TResult](IEnumerable`1 first, IEnumerable`1 second, Func`3 resultSelector)+MoveNext()
      at System.Collections.Generic.LargeArrayBuilder`1.AddRange(IEnumerable`1 items)
      at System.Collections.Generic.EnumerableHelpers.ToArray[T](IEnumerable`1 source)
      at Amazon.JSII.Runtime.Deputy.DeputyBase.ConvertArguments(Parameter[] parameters, Object[] arguments)
      at Amazon.JSII.Runtime.Deputy.DeputyBase.<InvokeMethodCore>g__GetResult|18_0[T](<>c__DisplayClass18_0`1&)
      at Amazon.JSII.Runtime.Deputy.DeputyBase.InvokeMethodCore[T](JsiiMethodAttribute methodAttribute, Object[] arguments, Func`3 beginFunc, Func`3 invokeFunc)
      at Amazon.JSII.Runtime.Deputy.DeputyBase.InvokeInstanceMethod[T](Type[] parameterTypes, Object[] arguments, String methodName)
      at Amazon.JSII.Runtime.Deputy.DeputyBase.InvokeInstanceVoidMethod(Type[] parameterTypes, Object[] arguments, String methodName)
      at Amazon.CDK.CfnResource.AddOverride(String path, Object value)
```
