### ISSUE TITLE
iam: Action 'undefined' is invalid for valid action string

### ISSUE THREAD

**Issue by alexpulver** [aws/aws-cdk#24687]
### Describe the bug

I have the following role definition in Python:

```python
<snip>
iam_policy_document = iam.PolicyDocument(
    statements=[
        iam.PolicyStatement(
            effect=iam.Effect.ALLOW,
            actions=["sts:AssumeRole"],
            resources=[f"arn:aws:iam::{self.account}:role/*"],
        )
    ]
)
iam.Role(
    self,
    "ServicePrincipal",
    role_name="TokenVendingMachineAPI",
    assumed_by=lambda_function,
    inline_policies={"AssumeRolesSameAccount": iam_policy_document},
)
```

Synthesizing this code leads to the following error:
```
RuntimeError: Action 'undefined' is invalid. An action string consists of a service namespace, a colon, and the name of an action. Action names can include wildcards.
```

If I change the colon to any other character, e.g. dash, AWS CDK prints the value and not undefined (even though it is a valid error this time):
```
RuntimeError: Action 'sts-AssumeRole' is invalid. An action string consists of a service namespace, a colon, and the name of an action. Action names can include wildcards.
```

### Expected Behavior

AWS CDK should synthesize correctly.

### Current Behavior

AWS CDK produces the following stack trace with error:
```
jsii.errors.JavaScriptError: 
  Error: Action 'undefined' is invalid. An action string consists of a service namespace, a colon, and the name of an action. Action names can include wildcards.
      at PolicyStatement.validatePolicyActions (/private/var/folders/z2/db8bn7_s0534kt3hj2ds_82c0000gr/T/jsii-kernel-a7e3Lz/node_modules/aws-cdk-lib/aws-iam/lib/policy-statement.js:2:2518)
      at PolicyStatement.addActions (/private/var/folders/z2/db8bn7_s0534kt3hj2ds_82c0000gr/T/jsii-kernel-a7e3Lz/node_modules/aws-cdk-lib/aws-iam/lib/policy-statement.js:2:402)
      at new PolicyStatement (/private/var/folders/z2/db8bn7_s0534kt3hj2ds_82c0000gr/T/jsii-kernel-a7e3Lz/node_modules/aws-cdk-lib/aws-iam/lib/policy-statement.js:1:1494)
      at Object.defaultAddPrincipalToAssumeRole (/private/var/folders/z2/db8bn7_s0534kt3hj2ds_82c0000gr/T/jsii-kernel-a7e3Lz/node_modules/aws-cdk-lib/aws-iam/lib/private/assume-role-policy.js:1:316)
      at createAssumeRolePolicy (/private/var/folders/z2/db8bn7_s0534kt3hj2ds_82c0000gr/T/jsii-kernel-a7e3Lz/node_modules/aws-cdk-lib/aws-iam/lib/role.js:1:12038)
      at new Role (/private/var/folders/z2/db8bn7_s0534kt3hj2ds_82c0000gr/T/jsii-kernel-a7e3Lz/node_modules/aws-cdk-lib/aws-iam/lib/role.js:1:1617)
      at Kernel._create (/private/var/folders/z2/db8bn7_s0534kt3hj2ds_82c0000gr/T/tmphhc0xnci/lib/program.js:9959:29)
      at Kernel.create (/private/var/folders/z2/db8bn7_s0534kt3hj2ds_82c0000gr/T/tmphhc0xnci/lib/program.js:9688:29)
      at KernelHost.processRequest (/private/var/folders/z2/db8bn7_s0534kt3hj2ds_82c0000gr/T/tmphhc0xnci/lib/program.js:11539:36)
      at KernelHost.run (/private/var/folders/z2/db8bn7_s0534kt3hj2ds_82c0000gr/T/tmphhc0xnci/lib/program.js:11499:22)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/apulver/Code/api/app.py", line 26, in <module>
    API(
  File "/Users/apulver/.pyenv/versions/3.9.11/envs/api-3.9.11/lib/python3.9/site-packages/jsii/_runtime.py", line 112, in __call__
    inst = super().__call__(*args, **kwargs)
  File "/Users/apulver/Code/api/component.py", line 37, in __init__
    self._create_service_principal_role(lambda_function)
  File "/Users/apulver/Code/api/component.py", line 99, in _create_service_principal_role
    iam.Role(
  File "/Users/apulver/.pyenv/versions/3.9.11/envs/api-3.9.11/lib/python3.9/site-packages/jsii/_runtime.py", line 112, in __call__
    inst = super().__call__(*args, **kwargs)
  File "/Users/apulver/.pyenv/versions/3.9.11/envs/api-3.9.11/lib/python3.9/site-packages/aws_cdk/aws_iam/__init__.py", line 11916, in __init__
    jsii.create(self.__class__, self, [scope, id, props])
  File "/Users/apulver/.pyenv/versions/3.9.11/envs/api-3.9.11/lib/python3.9/site-packages/jsii/_kernel/__init__.py", line 334, in create
    response = self.provider.create(
  File "/Users/apulver/.pyenv/versions/3.9.11/envs/api-3.9.11/lib/python3.9/site-packages/jsii/_kernel/providers/process.py", line 362, in create
    return self._process.send(request, CreateResponse)
  File "/Users/apulver/.pyenv/versions/3.9.11/envs/api-3.9.11/lib/python3.9/site-packages/jsii/_kernel/providers/process.py", line 339, in send
    raise RuntimeError(resp.error) from JavaScriptError(resp.stack)
RuntimeError: Action 'undefined' is invalid. An action string consists of a service namespace, a colon, and the name of an action. Action names can include wildcards.

Subprocess exited with error 1
```

### Reproduction Steps

Try to define a role per below.

```python
<snip>
iam_policy_document = iam.PolicyDocument(
    statements=[
        iam.PolicyStatement(
            effect=iam.Effect.ALLOW,
            actions=["sts:AssumeRole"],
            resources=[f"arn:aws:iam::{self.account}:role/*"],
        )
    ]
)
iam.Role(
    self,
    "ServicePrincipal",
    role_name="TokenVendingMachineAPI",
    assumed_by=lambda_function,
    inline_policies={"AssumeRolesSameAccount": iam_policy_document},
)
```

### CDK CLI Version

2.69.0 (build 60a5b2a)

### Framework Version

2.69.0

### Node.js Version

v16.16.0

### OS

macOS

### Language

Python

### Language Version

Python (3.9.11)

**Comment by alexpulver** [comment]
I found the root cause. I should've used `lambda_function.role` instead of `lambda_function` for `assumed_by=`. Missed the fact that the Lambda function doesn't implement `IPrincipal`. Is it possible to improve the error message to explain this?

**Comment by pahud** [comment]
I actually tested it with TypeScript and I have to use `func.grantPrincipal` rather than the func

<img width="769" alt="image" src="https://user-images.githubusercontent.com/278432/226387059-a1d90c9f-a113-45a2-a2cb-8c2e13c4e008.png">

<img width="970" alt="image" src="https://user-images.githubusercontent.com/278432/226387187-3ca1f691-552f-4e81-ac57-5a45c8ec4613.png">

I am not sure if we can improve the experience here with Python as it is not strongly typed.
