### ISSUE TITLE
CDK Python: diff shows replacement required, deploy errors with conflict

### ISSUE THREAD

**Issue by RogerWilco80** [aws/aws-cdk#24708]
### Describe the bug

While changing vpc structure , changing `max_azs` to 3 from 2, `cdk diff` will show that a subnet and CIDR block needs replacement, but `cdk deploy` throws an error `The CIDR '10.121.2.0/24' conflicts with another subnet`.

### Expected Behavior

`cdk deploy` should do the replacements prior to creating new resources, this way the conflict wouldn't happen.

### Current Behavior

diff output:
```
Stack VPCV2ApiStack
Resources
[+] AWS::EC2::Subnet TestUI_VPC/PubASubnet3/Subnet TestUIVPCPubASubnet3Subnet25C25043 
[+] AWS::EC2::RouteTable TestUI_VPC/PubASubnet3/RouteTable TestUIVPCPubASubnet3RouteTable474E7507 
[+] AWS::EC2::SubnetRouteTableAssociation TestUI_VPC/PubASubnet3/RouteTableAssociation TestUIVPCPubASubnet3RouteTableAssociation20486625 
[+] AWS::EC2::Route TestUI_VPC/PubASubnet3/DefaultRoute TestUIVPCPubASubnet3DefaultRoute4442BF69 
[+] AWS::EC2::Subnet TestUI_VPC/PrvASubnet3/Subnet TestUIVPCPrvASubnet3Subnet6C53F792 
[+] AWS::EC2::RouteTable TestUI_VPC/PrvASubnet3/RouteTable TestUIVPCPrvASubnet3RouteTable6D9D106B 
[+] AWS::EC2::SubnetRouteTableAssociation TestUI_VPC/PrvASubnet3/RouteTableAssociation TestUIVPCPrvASubnet3RouteTableAssociationCD7CF5C5 
[+] AWS::EC2::Route TestUI_VPC/PrvASubnet3/DefaultRoute TestUIVPCPrvASubnet3DefaultRouteA53765BD 
[~] AWS::EC2::Subnet TestUI_VPC/PrvASubnet1/Subnet TestUIVPCPrvASubnet1SubnetAC3A3EF4 replace
 └─ [~] CidrBlock (requires replacement)
     ├─ [-] 10.121.2.0/24
     └─ [+] 10.121.3.0/24
[~] AWS::EC2::SubnetRouteTableAssociation TestUI_VPC/PrvASubnet1/RouteTableAssociation TestUIVPCPrvASubnet1RouteTableAssociation0DB3FAFA replace
 └─ [~] SubnetId (requires replacement)
     └─ [~] .Ref:
         ├─ [-] TestUIVPCPrvASubnet1SubnetAC3A3EF4
         └─ [+] TestUIVPCPrvASubnet1SubnetAC3A3EF4 (replaced)
[~] AWS::EC2::Subnet TestUI_VPC/PrvASubnet2/Subnet TestUIVPCPrvASubnet2Subnet8FCB9A3A replace
 └─ [~] CidrBlock (requires replacement)
     ├─ [-] 10.121.3.0/24
     └─ [+] 10.121.4.0/24
[~] AWS::EC2::SubnetRouteTableAssociation TestUI_VPC/PrvASubnet2/RouteTableAssociation TestUIVPCPrvASubnet2RouteTableAssociation5DD3C7CF replace
 └─ [~] SubnetId (requires replacement)
     └─ [~] .Ref:
         ├─ [-] TestUIVPCPrvASubnet2Subnet8FCB9A3A
         └─ [+] TestUIVPCPrvASubnet2Subnet8FCB9A3A (replaced)
```
deploy output:
```
VPCV2ApiStack: building assets...

[0%] start: Building a51e392cc65f3515cf3587e05b01c7667039bdef318ac5b1fae356cc63daa8f0:693169797761-ap-southeast-2
[100%] success: Built a51e392cc65f3515cf3587e05b01c7667039bdef318ac5b1fae356cc63daa8f0:693169797761-ap-southeast-2

VPCV2ApiStack: assets built

VPCV2ApiStack: deploying... [1/1]
[0%] start: Publishing a51e392cc65f3515cf3587e05b01c7667039bdef318ac5b1fae356cc63daa8f0:693169797761-ap-southeast-2
[100%] success: Published a51e392cc65f3515cf3587e05b01c7667039bdef318ac5b1fae356cc63daa8f0:693169797761-ap-southeast-2
VPCV2ApiStack: creating CloudFormation changeset...
9:53:09 am | CREATE_FAILED        | AWS::EC2::Subnet                      | TestUIVPCPubASubnet3Subnet25C25043
Resource handler returned message: "The CIDR '10.121.2.0/24' conflicts with another subnet (Service: Ec2, Status Code: 400, Request
ID: 5f9f5700-99e9-416f-b0f2-ec05b06288c0, Extended Request ID: null)" (RequestToken: e82bc45d-8978-75af-9266-54a84566444b, HandlerE
rrorCode: AlreadyExists)


 ❌  VPCV2ApiStack failed: Error: The stack named VPCV2ApiStack failed to deploy: UPDATE_ROLLBACK_COMPLETE: Resource handler returned message: "The CIDR '10.121.2.0/24' conflicts with another subnet (Service: Ec2, Status Code: 400, Request ID: 5f9f5700-99e9-416f-b0f2-ec05b06288c0, Extended Request ID: null)" (RequestToken: e82bc45d-8978-75af-9266-54a84566444b, HandlerErrorCode: AlreadyExists)
    at FullCloudFormationDeployment.monitorDeployment (/usr/local/lib/node_modules/aws-cdk/lib/index.js:371:10236)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async deployStack2 (/usr/local/lib/node_modules/aws-cdk/lib/index.js:374:145469)
    at async /usr/local/lib/node_modules/aws-cdk/lib/index.js:374:128787
    at async run (/usr/local/lib/node_modules/aws-cdk/lib/index.js:374:126793)

 ❌ Deployment failed: Error: Stack Deployments Failed: Error: The stack named VPCV2ApiStack failed to deploy: UPDATE_ROLLBACK_COMPLETE: Resource handler returned message: "The CIDR '10.121.2.0/24' conflicts with another subnet (Service: Ec2, Status Code: 400, Request ID: 5f9f5700-99e9-416f-b0f2-ec05b06288c0, Extended Request ID: null)" (RequestToken: e82bc45d-8978-75af-9266-54a84566444b, HandlerErrorCode: AlreadyExists)
    at deployStacks (/usr/local/lib/node_modules/aws-cdk/lib/index.js:374:129094)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async CdkToolkit.deploy (/usr/local/lib/node_modules/aws-cdk/lib/index.js:374:147518)
    at async exec4 (/usr/local/lib/node_modules/aws-cdk/lib/index.js:429:51795)

Stack Deployments Failed: Error: The stack named VPCV2ApiStack failed to deploy: UPDATE_ROLLBACK_COMPLETE: Resource handler returned message: "The CIDR '10.121.2.0/24' conflicts with another subnet (Service: Ec2, Status Code: 400, Request ID: 5f9f5700-99e9-416f-b0f2-ec05b06288c0, Extended Request ID: null)" (RequestToken: e82bc45d-8978-75af-9266-54a84566444b, HandlerErrorCode: AlreadyExists)
```

### Reproduction Steps

Create a VPC with `max_azs=2` and deploy it.
Change `max_azs=3` when doing a deploy it should try to use an existing CIDR block and throw the error.

### CDK CLI Version

2.69.0 (build 60a5b2a)

### Node.js Version

v16.15.0

### OS

MacOS 13.2.1

### Language

Python

### Language Version

Python 3.10.4

**Comment by pahud** [comment]
@RogerWilco80 Can you share your full CDK code snippet that we can reproduce in our account?

**Comment by RogerWilco80** [comment]
@pahud Let me know if you need more than this.

```
vpc = ec2.Vpc(
            self, environment.VPCName,
            ip_addresses=ec2.IpAddresses.cidr(environment.SydVPCCIDR), 
            max_azs=3, 
            nat_gateways=1, 
            subnet_configuration=[ec2.SubnetConfiguration(name="PubA", subnet_type=ec2.SubnetType.PUBLIC, map_public_ip_on_launch=False, cidr_mask=24),
                ec2.SubnetConfiguration(name="PrvA", subnet_type=ec2.SubnetType.PRIVATE_WITH_EGRESS, cidr_mask=24),
            ], 
            vpc_name=environment.VPCName, 
        )
```

**Comment by pahud** [comment]
@RogerWilco80 

Are you change the maxAz from 2 to 3 from

this

```
vpc = ec2.Vpc(
            self, environment.VPCName,
            ip_addresses=ec2.IpAddresses.cidr(environment.SydVPCCIDR), 
            max_azs=2, 
            nat_gateways=1, 
            subnet_configuration=[ec2.SubnetConfiguration(name="PubA", subnet_type=ec2.SubnetType.PUBLIC, map_public_ip_on_launch=False, cidr_mask=24),
                ec2.SubnetConfiguration(name="PrvA", subnet_type=ec2.SubnetType.PRIVATE_WITH_EGRESS, cidr_mask=24),
            ], 
            vpc_name=environment.VPCName, 
        )
```

to

```
vpc = ec2.Vpc(
            self, environment.VPCName,
            ip_addresses=ec2.IpAddresses.cidr(environment.SydVPCCIDR), 
            max_azs=3, 
            nat_gateways=1, 
            subnet_configuration=[ec2.SubnetConfiguration(name="PubA", subnet_type=ec2.SubnetType.PUBLIC, map_public_ip_on_launch=False, cidr_mask=24),
                ec2.SubnetConfiguration(name="PrvA", subnet_type=ec2.SubnetType.PRIVATE_WITH_EGRESS, cidr_mask=24),
            ], 
            vpc_name=environment.VPCName, 
        )
```

**Comment by pahud** [comment]
Unfortunately, it seems to be inevitable to conflict the subnet ip cidr in your use case.

An option is update the IpAddress.cidr from `10.121.0.0/16` to `10.122.0.0/16` with max_azs=3 as below and update the deployment followed by modify the cidr range back to `10.121.0.0/16` and re-dploy again. This probably is something we can "work around" this issue.

```py
        vpc = ec2.Vpc(
                    self, 'Vpc',
                    ip_addresses=ec2.IpAddresses.cidr('10.122.0.0/16'), 
                    max_azs=3, 
                    nat_gateways=1, 
                    subnet_configuration=[
                        ec2.SubnetConfiguration(
                            name="PubA",
                            subnet_type=ec2.SubnetType.PUBLIC,
                            map_public_ip_on_launch=False,
                            cidr_mask=24,
                            
                        ),
                        ec2.SubnetConfiguration(
                            name="PrvA",
                            subnet_type=ec2.SubnetType.PRIVATE_WITH_EGRESS,
                            cidr_mask=24
                        ),
                    ], 
                )
```

**Comment by RogerWilco80** [comment]
Thanks @pahud. I'm not too worried about it at this point as I'm still trying to build our infra in our Test environment so I was able to manually delete the offending subnets. I asked the question incase this comes up one day when we have the CDK deploying our prod env.

Thanks again for your help.

**Comment by pahud** [comment]
@RogerWilco80  Yeah and thank you for the callout. Feel free to let us know if you have any further issues.

**Comment by pahud** [comment]
To have more granular control over each subnet cidr. Consider this workaround:

```ts
export class Demo extends DemoStack {
	readonly vpc: ec2.Vpc;
	readonly publicCidrs: string[]
	readonly privateCidrs: string[]
	constructor(scope: Construct, id: string, props: StackProps) {
		super(scope, id, props);

		this.publicCidrs= ['10.0.0.0/24', '10.0.1.0/24'];
		this.privateCidrs= ['10.0.2.0/24', '10.0.3.0/24'];

		const vpc = new ec2.Vpc(this, 'Vpc', {
			maxAzs:3, 
			natGateways: 1, 
			ipAddresses: ec2.IpAddresses.cidr('10.0.0.0/16'),
			subnetConfiguration: [
				{
					/**
					 * 10.0.0.0/24
					 * 10.0.1.0/24
					 */
					subnetType: SubnetType.PUBLIC,
					name: 'Ingress',
					cidrMask: 24,
				},
				{
					/**
					 * 10.0.2.0/24
					 * 10.0.3.0/24
					 */
					subnetType: SubnetType.PRIVATE_WITH_EGRESS,
					name: 'Application',
					cidrMask: 24,
				}
			]
		});
		this.vpc = vpc;
		// explicitly assign the cidr for each subnet
		this.assignSubnetCidr('IngressSubnet1',this.publicCidrs[0]);
		this.assignSubnetCidr('IngressSubnet2',this.publicCidrs[1]);
		this.assignSubnetCidr('ApplicationSubnet1',this.privateCidrs[0]);
		this.assignSubnetCidr('ApplicationSubnet2',this.privateCidrs[1]);

		// // print the EIP of NAT Gateway
		this.printEIP();
	}
	private assignSubnetCidr(subnetName: string, cidr: string ) {
		const cfnSubnet = this.vpc.node.tryFindChild(subnetName)!.node.tryFindChild('Subnet') as ec2.CfnSubnet;
		cfnSubnet.addPropertyOverride('CidrBlock', cidr);
	}
	private printEIP() {
		const cfnIngressSubnet1 = this.vpc.node.tryFindChild('IngressSubnet1') as ec2.CfnSubnet
		const cfnEIP = cfnIngressSubnet1.node.tryFindChild('EIP') as ec2.CfnEIP
		new CfnOutput(this, 'NAT EIP', { value: cfnEIP.attrPublicIp });
	}
}
``` 

When you change `maxAzs` from 2 to 3

update your cidr assignment from this
```
this.publicCidrs= ['10.0.0.0/24', '10.0.1.0/24'];
this.privateCidrs= ['10.0.2.0/24', '10.0.3.0/24'];
```	
to this
```
this.publicCidrs= ['10.0.0.0/24', '10.0.1.0/24', '10.0.4.0/24'];
this.privateCidrs= ['10.0.2.0/24', '10.0.3.0/24', '10.0.5.0/24'];
```	

for first update to

```
this.publicCidrs= ['10.0.0.0/24', '10.0.1.0/24'];
this.privateCidrs= ['10.0.10.0/24', '10.0.11.0/24'];
```	
And then

```
this.publicCidrs= ['10.0.0.0/24', '10.0.1.0/24', '10.0.2.0/24'];
this.privateCidrs= ['10.0.10.0/24', '10.0.11.0/24', '10.0.12.0/24'];
```	

You would have full control of cidr for each subnet like this to avoid overlapping.

**Comment by marcesengel** [comment]
For anyone stumbling across this, here's a utility function accepting an `ISubnet` so you're a little more free with syntax/setup and you don't have to extract it yourself
```ts
function setCidrBlock(subnet: ec2.ISubnet, cidrBlock: string) {
  const cfnSubnet = subnet.node.tryFindChild('Subnet') as ec2.CfnSubnet
  cfnSubnet.addPropertyOverride('CidrBlock', cidrBlock)
}
```
