### ISSUE TITLE
(aws-glue-alpha): cannot create 2 partitionIndexes simultaneously

### ISSUE THREAD

**Issue by clueleaf** [aws/aws-cdk#24813]
### Describe the bug

When passing 2 indexes to `partitionIndexes` of `glue.Table`, table creation fails.

### Expected Behavior

Glue table and indexes are created.

### Current Behavior

Table indexes creation fails.

> Index index2 is in CREATING state. Only 1 index can be created or deleted simultaneously per table.

### Reproduction Steps

Create a glue table with 2 indexes.

```typescript
const bucket = new s3.Bucket(stack, 'DataBucket');
const database = new glue.Database(stack, 'MyDatabase', {
  databaseName: 'database',
});

const csvTable = new glue.Table(stack, 'CSVTable', {
  database,
  bucket,
  tableName: 'csv_table',
  columns: [
    { name: 'col1', type: glue.Schema.STRING },
    { name: 'col2', type: glue.Schema.STRING },
    { name: 'col3', type: glue.Schema.STRING },
  ],
  partitionKeys: [
    { name: 'year', type: glue.Schema.SMALL_INT },
    { name: 'month', type: glue.Schema.BIG_INT },
  ],
  partitionIndexes: [
    { indexName: 'index1', keyNames: ['month'] },
    { indexName: 'index2', keyNames: ['month', 'year'] },
  ],
  dataFormat: glue.DataFormat.CSV,
});
```

### Possible Solution

I think this a restriction of Glue service.
Remove `partitionIndexes` property of glue construct and add `partitionIndex` property instead so only one index can be provided on table creation.
Add other indexes later on using `table.AddPartitionIndex` method.

### CDK CLI Version

2.70.0

### Node.js Version

18

### OS

macOS Ventura

### Language

Typescript

**Comment by clueleaf** [comment]
Probably the order of custom resources for `addDependency` is inverted.

https://github.com/aws/aws-cdk/blob/07d3aa74e6c1a7b3b7ddf298cf3cc4b7ff180b48/packages/%40aws-cdk/aws-glue/lib/table.ts#L393-L396

Below makes more sense to me.

```typescript
partitionIndexCustomResource.node.addDependency(this.partitionIndexCustomResources[numPartitions-1]);
```

**Comment by khushail** [comment]
Hi @clueleaf , thanks for reaching out. 

Its stated in the available [documentation](https://docs.aws.amazon.com/cdk/api/v2/docs/aws-glue-alpha-readme.html#partition-indexes) that you can have a maximum of 3 partition indexes in the table. But its also stated [here](https://github.com/aws/aws-cdk/blob/07d3aa74e6c1a7b3b7ddf298cf3cc4b7ff180b48/packages/%40aws-cdk/aws-glue/lib/table.ts#L276) - `
   * Partition indexes must be created one at a time. To avoid
   * race conditions, we store the resource and add dependencies
   * each time a new partition index is created.
   `
   I am also getting the error while creating 2 indexes at the same time but it succeeds when I am adding Partition Index later on. Since workaround is there, currently I am marking this as P2 which means our team won't be able to work on it immediately. However if you would like to contribute to resolving this bug, that would be great. Here is a contributing [guide](https://github.com/aws/aws-cdk/blob/main/CONTRIBUTING.md#step-1-find-something-to-work-on) to get started.
 
We also use +1s to help prioritize our work, and are happy to re-evaluate this issue based on community feedback. You can reach out to the [cdk.dev](http://cdk.dev/) community on [Slack](https://cdk.dev/) to solicit support for re-prioritization. (edited)

**Comment by clueleaf** [comment]
@khushail Thank you for your investigation.
One wired thing is that even if I use `AddPartitionIndex` to add index later on, it fails just as the same.
It's hard to tell why it succeeds sometimes but not always.

```typescript
const bucket = new s3.Bucket(stack, 'DataBucket');
const database = new glue.Database(stack, 'MyDatabase', {
  databaseName: 'database',
});

const csvTable = new glue.Table(stack, 'CSVTable', {
  database,
  bucket,
  tableName: 'csv_table',
  columns: [
    { name: 'col1', type: glue.Schema.STRING },
    { name: 'col2', type: glue.Schema.STRING },
    { name: 'col3', type: glue.Schema.STRING },
  ],
  partitionKeys: [
    { name: 'year', type: glue.Schema.SMALL_INT },
    { name: 'month', type: glue.Schema.BIG_INT },
  ],
  partitionIndexes: [{ indexName: 'index1', keyNames: ['month'] }],
  dataFormat: glue.DataFormat.CSV,
});
csvTable.AddPartitionIndex({ indexName: 'index2', keyNames: ['month', 'year'] })
```

**Comment by clueleaf** [comment]
Sure.

```
**:**:** ** | CREATE_FAILED        | Custom::AWS           | CSVTablepartitionindexindex16247ABF6
Received response status [FAILED] from custom resource. Message returned: Index index2 is in CREATING state. Only 1 index can be created or deleted simultaneously per table. (RequestId: 9a709d0e-4e9d-49e3-8202-fd781b73266b)

 ❌  MyStack (MyStack) failed: Error: The stack named MyStack failed creation, it may need to be manually deleted from the AWS console: ROLLBACK_COMPLETE: Received response status [FAILED] from custom resource. Message returned: Index index2 is in CREATING state. Only 1 index can be created or deleted simultaneously per table. (RequestId: 9a709d0e-4e9d-49e3-8202-fd781b73266b)
    at FullCloudFormationDeployment.monitorDeployment (/Users/***/node_modules/aws-cdk/lib/index.js:380:10236)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async deployStack2 (/Users/***/node_modules/aws-cdk/lib/index.js:383:145458)
    at async /Users/***/node_modules/aws-cdk/lib/index.js:383:128776
    at async run (/Users/***/node_modules/aws-cdk/lib/index.js:383:126782)

 ❌ Deployment failed: Error: Stack Deployments Failed: Error: The stack named MyStack failed creation, it may need to be manually deleted from the AWS console: ROLLBACK_COMPLETE: Received response status [FAILED] from custom resource. Message returned: Index index2 is in CREATING state. Only 1 index can be created or deleted simultaneously per table. (RequestId: 9a709d0e-4e9d-49e3-8202-fd781b73266b)
    at deployStacks (/Users/***/node_modules/aws-cdk/lib/index.js:383:129083)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async CdkToolkit.deploy (/Users/***/node_modules/aws-cdk/lib/index.js:383:147507)
    at async exec4 (/Users/***/node_modules/aws-cdk/lib/index.js:438:51799)

Stack Deployments Failed: Error: The stack named MyStack failed creation, it may need to be manually deleted from the AWS console: ROLLBACK_COMPLETE: Received response status [FAILED] from custom resource. Message returned: Index index2 is in CREATING state. Only 1 index can be created or deleted simultaneously per table. (RequestId: 9a709d0e-4e9d-49e3-8202-fd781b73266b)
```

**Comment by khushail** [comment]
thanks @clueleaf .

**Comment by yuntaoL** [comment]
I have same issue, it worked previously.

**Comment by prazian** [comment]
IMO, the best thing is to avoid returning nothing in the `addPartitionIndex` function and instead return the object, so then we could chain dependencies between the two indexes.

Something like this (currently doesn't work because it returns void):
```typescript
        const table = new S3Table(this, 'Something', {
              .
              .
              .
             });


        const pI1 = table.addPartitionIndex({
                    indexName: 'year_month_day',
                    keyNames: ['year', 'month', 'day']
                });
        const pI2 = table.addPartitionIndex({
                    indexName: 'country_site',
                    keyNames: ['country', 'site']
                });
        pI1.addDependency(pI2); # Does't work because pI1 and pI2 are void
```

**Comment by nitvob** [comment]
> Hi [@clueleaf](https://github.com/clueleaf) , thanks for reaching out.
> 
> Its stated in the available [documentation](https://docs.aws.amazon.com/cdk/api/v2/docs/aws-glue-alpha-readme.html#partition-indexes) that you can have a maximum of 3 partition indexes in the table. But its also stated [here](https://github.com/aws/aws-cdk/blob/07d3aa74e6c1a7b3b7ddf298cf3cc4b7ff180b48/packages/%40aws-cdk/aws-glue/lib/table.ts#L276) - `
> 
>     * Partition indexes must be created one at a time. To avoid
> 
>     * race conditions, we store the resource and add dependencies
> 
>     * each time a new partition index is created.
>       `
>       I am also getting the error while creating 2 indexes at the same time but it succeeds when I am adding Partition Index later on. Since workaround is there, currently I am marking this as P2 which means our team won't be able to work on it immediately. However if you would like to contribute to resolving this bug, that would be great. Here is a contributing [guide](https://github.com/aws/aws-cdk/blob/main/CONTRIBUTING.md#step-1-find-something-to-work-on) to get started.
> 
> 
> We also use +1s to help prioritize our work, and are happy to re-evaluate this issue based on community feedback. You can reach out to the [cdk.dev](http://cdk.dev/) community on [Slack](https://cdk.dev/) to solicit support for re-prioritization. (edited)

what do you mean by adding partition index later on? Do you mean create the table without passing in `partitionIndexes` and then call .addPartitionIndex?

**Comment by pahud** [comment]
Hi @clueleaf,

**Problem at a Glance:**
```
┌────────────────┐         ┌────────────────┐
│  Index 1 CR    │         │  Index 2 CR    │
│  createIndex() │         │  createIndex() │
└───────┬────────┘         └───────┬────────┘
        │                          │
        │  ❌ index1 DependsOn     │
        │     index2 (backwards!)  │
        │                          │
        ▼                          ▼
┌──────────────────────────────────────────┐
│  Glue: "Only 1 index can be created     │
│   simultaneously per table"              │
└──────────────────────────────────────────┘
```

This is a good catch — I can confirm this bug is still present on the latest CDK (v2.257.0). There are actually two issues in [`addPartitionIndex()`](https://github.com/aws/aws-cdk/blob/main/packages/%40aws-cdk/aws-glue-alpha/lib/table-base.ts#L293):

1. **The dependency direction is backwards** — the code does `previous.addDependency(new)`, which tells CloudFormation to create index2 *first*, then index1. It should be the other way around.

2. **AwsCustomResource doesn't wait for CREATED state** — even with correct dependencies, the custom resource reports SUCCESS as soon as the `createPartitionIndex` API returns 200, while the index is still in `CREATING` state. The next index creation then races against it.

This is the same root cause as #27045 (which was auto-closed for staleness without a fix).

**Workaround:** The only reliable workaround for now is to deploy one index at a time — add one index, deploy, then add the next and deploy again.

The proper fix would be to:
- Correct the dependency direction
- Replace `AwsCustomResource` with a CDK `Provider` that uses an `isCompleteHandler` to poll `getPartitionIndexes` until the index reaches `CREATED` before reporting success

This would be a great community PR if anyone is interested — it's well-scoped and isolated to the `addPartitionIndex` method. We'd welcome a contribution here!
