### ISSUE TITLE
core: Duration.parse() doesn't parse millis iso_string()

### ISSUE THREAD

**Issue by gmiretti** [aws/aws-cdk#24971]
### Describe the bug

I can get an iso_string() from millis but I can't Duration.parse() it.

This works on Python for seconds
```python
from aws_cdk import Duration
Duration.parse(Duration.millis(2000).to_iso_string()).to_iso_string()
```

### Expected Behavior

so I expect that it works for millis
```python
In [1]: Duration.parse(Duration.millis(2).to_iso_string()).to_iso_string()
Out[1]: 'PT0.002S'
```

### Current Behavior

but it doesn't
```python
In [34]: Duration.parse(Duration.millis(2).to_iso_string()).to_iso_string()
---------------------------------------------------------------------------
JavaScriptError                           Traceback (most recent call last)
JavaScriptError: 
  @jsii/kernel.RuntimeError: Error: Not a valid ISO duration: PT0.002S
      at Kernel._ensureSync (/tmp/tmpf9jdrobc/lib/program.js:10364:27)
      at Kernel.sinvoke (/tmp/tmpf9jdrobc/lib/program.js:9785:34)
      at KernelHost.processRequest (/tmp/tmpf9jdrobc/lib/program.js:11536:36)
      at KernelHost.run (/tmp/tmpf9jdrobc/lib/program.js:11496:22)
      at Immediate._onImmediate (/tmp/tmpf9jdrobc/lib/program.js:11497:46)
      at processImmediate (internal/timers.js:464:21)

The above exception was the direct cause of the following exception:

RuntimeError                              Traceback (most recent call last)
Cell In[34], line 1
----> 1 Duration.parse(Duration.millis(2).to_iso_string()).to_iso_string()

File /var/lang/lib/python3.9/site-packages/aws_cdk/__init__.py:10638, in Duration.parse(cls, duration)
  10636     type_hints = typing.get_type_hints(Duration.parse)
  10637     check_type(argname="argument duration", value=duration, expected_type=type_hints["duration"])
> 10638 return typing.cast("Duration", jsii.sinvoke(cls, "parse", [duration]))

File /var/lang/lib/python3.9/site-packages/jsii/_kernel/__init__.py:149, in _dereferenced.<locals>.wrapped(kernel, *args, **kwargs)
    147 @functools.wraps(fn)
    148 def wrapped(kernel: "Kernel", *args: Any, **kwargs: Any):
--> 149     return _recursize_dereference(kernel, fn(kernel, *args, **kwargs))

File /var/lang/lib/python3.9/site-packages/jsii/_kernel/__init__.py:418, in Kernel.sinvoke(self, klass, method, args)
    415 if args is None:
    416     args = []
--> 418 response = self.provider.sinvoke(
    419     StaticInvokeRequest(
    420         fqn=klass.__jsii_type__,
    421         method=method,
    422         args=_make_reference_for_native(self, args),
    423     )
    424 )
    425 if isinstance(response, Callback):
    426     return _callback_till_result(self, response, InvokeResponse)

File /var/lang/lib/python3.9/site-packages/jsii/_kernel/providers/process.py:380, in ProcessProvider.sinvoke(self, request)
    379 def sinvoke(self, request: StaticInvokeRequest) -> InvokeResponse:
--> 380     return self._process.send(request, InvokeResponse)

File /var/lang/lib/python3.9/site-packages/jsii/_kernel/providers/process.py:339, in _NodeProcess.send(self, request, response_type)
    337 if resp.name == ErrorType.JSII_FAULT.value:
    338     raise JSIIError(resp.error) from JavaScriptError(resp.stack)
--> 339 raise RuntimeError(resp.error) from JavaScriptError(resp.stack)

RuntimeError: Error: Not a valid ISO duration: PT0.002S
```

### Reproduction Steps

```python
from aws_cdk import Duration
Duration.parse(Duration.millis(2).to_iso_string()).to_iso_string()
```

### Possible Solution

Reason: I need to parse millis config strings from a file and reimplement a parser when you already have one looks extra maintenance burden. Also, I think that asking to parse your own strings is something reasonable to ask.

Solution: implement parsing for milliseconds

### CDK CLI Version

2.67.0

### Framework Version

2.67.0

### Node.js Version

14.19.3

### OS

Linux

### Language

Python

### Language Version

Python 3.9.16 (main, Jan 30 2023, 22:41:17)

**Comment by peterwoodworth** [comment]
Thanks for reporting, I was able to reproduce this. It looks like we don't account for millis in our regex https://github.com/aws/aws-cdk/blob/43e681e26cab82c5dbc4ab6212314a641e676097/packages/aws-cdk-lib/core/lib/duration.ts#L69-L89

**Comment by jeffuofa93** [comment]
I'd love to take a stab at this. First time contributor and seems like a relatively straight forward fix.

**Comment by gmiretti** [comment]
All good for me, I don't think I'll be able to post a PR soon
