### ISSUE TITLE
core: crossRegionReferences cannot deploy to more than 2 regions

### ISSUE THREAD

**Issue by JBombNZ** [aws/aws-cdk#25183]
### Describe the bug

A stack that is exported to more than 2 regions using  `crossRegionReferences`  fails to deploy with an error. Example: 

````
const dnsStack = new DnsStack(app, 'DNSStack', {
    env: {
        region: 'us-east-1',
    },
    crossRegionReferences: true
})

const regions = ['us-west-1', 'us-east-1', 'ap-southeast-2']

regions.forEach((region) => {

    new ComputeStack(app, region + '-ComputeStack', {
        env: {
            region: region
        },
        crossRegionReferences: true,
        dnsStack
    })

})
````

### Expected Behavior

The exporting stack to successfully deploy with out error.

### Current Behavior

Error message:
````
1:33:23 pm | CREATE_FAILED        | Custom::CrossRegionExportWriter | ExportsWriterapsou...t2235C849A8E92266D
Received response status [FAILED] from custom resource. Message returned: AccessDeniedException: User: arn:aws:sts::705690605585:assumed-role/DNSStack-CustomCrossRegionExportWriterCustomResour-16UW94GTDPQ9N/DNSS
tack-CustomCrossRegionExportWriterCustomResour-U2MPPb2RYYXn is not authorized to perform: ssm:ListTagsForResource on resource: arn:aws:ssm:ap-southeast-2:705690605585:parameter/cdk/exports/ap-southeast-2-Compute
Stack/DNSStackuseast1RefHostedZoneDB99F8669F50CE3B because no identity-based policy allows the ssm:ListTagsForResource action
at Request.extractError (/var/runtime/node_modules/aws-sdk/lib/protocol/json.js:52:27)
at Request.callListeners (/var/runtime/node_modules/aws-sdk/lib/sequential_executor.js:106:20)
at Request.emit (/var/runtime/node_modules/aws-sdk/lib/sequential_executor.js:78:10)
at Request.emit (/var/runtime/node_modules/aws-sdk/lib/request.js:686:14)
at Request.transition (/var/runtime/node_modules/aws-sdk/lib/request.js:22:10)
at AcceptorStateMachine.runTo (/var/runtime/node_modules/aws-sdk/lib/state_machine.js:14:12)
at /var/runtime/node_modules/aws-sdk/lib/state_machine.js:26:10
at Request.<anonymous> (/var/runtime/node_modules/aws-sdk/lib/request.js:38:9)
at Request.<anonymous> (/var/runtime/node_modules/aws-sdk/lib/request.js:688:12)
at Request.callListeners (/var/runtime/node_modules/aws-sdk/lib/sequential_executor.js:116:18) (RequestId: d65433d6-5fb1-4f27-9a22-5ad43019d2c6)

````

Full output:

````
# cdk deploy --all

✨  Synthesis time: 5.09s

DNSStack: building assets...

[0%] start: Building 27f8287125ebe89b1cb7f97768a61c84b3f3221450e0a22c152addc630ab2430:current_account-us-east-1
[0%] start: Building 9f7479f6add08e85e08efb295c2d0f653600aa6ec8c3dd691e682c368cc72aa9:current_account-us-east-1
[50%] success: Built 27f8287125ebe89b1cb7f97768a61c84b3f3221450e0a22c152addc630ab2430:current_account-us-east-1
[100%] success: Built 9f7479f6add08e85e08efb295c2d0f653600aa6ec8c3dd691e682c368cc72aa9:current_account-us-east-1

DNSStack: assets built

ap-southeast-2-ComputeStack: building assets...

[0%] start: Building 4b6a500a9b63c31028b69751201d80225328cfb9df5c4a6abaac18e7d4c48a8c:current_account-ap-southeast-2
[0%] start: Building dbda9ae1b9b6c486d2511c52c372173c56407c99383a9418eb4d1cb5a93b1ef7:current_account-ap-southeast-2
[50%] success: Built 4b6a500a9b63c31028b69751201d80225328cfb9df5c4a6abaac18e7d4c48a8c:current_account-ap-southeast-2
[100%] success: Built dbda9ae1b9b6c486d2511c52c372173c56407c99383a9418eb4d1cb5a93b1ef7:current_account-ap-southeast-2

ap-southeast-2-ComputeStack: assets built

us-east-1-ComputeStack: building assets...

[0%] start: Building 46fc27549f988a0e4ac2223fb6d50d88964e0b652cdda0143432edc8480e683c:current_account-us-east-1
[100%] success: Built 46fc27549f988a0e4ac2223fb6d50d88964e0b652cdda0143432edc8480e683c:current_account-us-east-1

us-east-1-ComputeStack: assets built

us-west-1-ComputeStack: building assets...

[0%] start: Building 4b6a500a9b63c31028b69751201d80225328cfb9df5c4a6abaac18e7d4c48a8c:current_account-us-west-1
[0%] start: Building 633947078905a5fbab63b86aa4b0040d1fe0bad54d7ae2f16d59aba6a8484f8e:current_account-us-west-1
[50%] success: Built 4b6a500a9b63c31028b69751201d80225328cfb9df5c4a6abaac18e7d4c48a8c:current_account-us-west-1
[100%] success: Built 633947078905a5fbab63b86aa4b0040d1fe0bad54d7ae2f16d59aba6a8484f8e:current_account-us-west-1

us-west-1-ComputeStack: assets built

DNSStack
DNSStack: deploying... [1/4]
[0%] start: Publishing 27f8287125ebe89b1cb7f97768a61c84b3f3221450e0a22c152addc630ab2430:current_account-us-east-1
[0%] start: Publishing 9f7479f6add08e85e08efb295c2d0f653600aa6ec8c3dd691e682c368cc72aa9:current_account-us-east-1
[50%] success: Published 27f8287125ebe89b1cb7f97768a61c84b3f3221450e0a22c152addc630ab2430:current_account-us-east-1
[100%] success: Published 9f7479f6add08e85e08efb295c2d0f653600aa6ec8c3dd691e682c368cc72aa9:current_account-us-east-1
DNSStack: creating CloudFormation changeset...
1:33:23 pm | CREATE_FAILED        | Custom::CrossRegionExportWriter | ExportsWriterapsou...t2235C849A8E92266D
Received response status [FAILED] from custom resource. Message returned: AccessDeniedException: User: arn:aws:sts::705690605585:assumed-role/DNSStack-CustomCrossRegionExportWriterCustomResour-16UW94GTDPQ9N/DNSS
tack-CustomCrossRegionExportWriterCustomResour-U2MPPb2RYYXn is not authorized to perform: ssm:ListTagsForResource on resource: arn:aws:ssm:ap-southeast-2:705690605585:parameter/cdk/exports/ap-southeast-2-Compute
Stack/DNSStackuseast1RefHostedZoneDB99F8669F50CE3B because no identity-based policy allows the ssm:ListTagsForResource action
at Request.extractError (/var/runtime/node_modules/aws-sdk/lib/protocol/json.js:52:27)
at Request.callListeners (/var/runtime/node_modules/aws-sdk/lib/sequential_executor.js:106:20)
at Request.emit (/var/runtime/node_modules/aws-sdk/lib/sequential_executor.js:78:10)
at Request.emit (/var/runtime/node_modules/aws-sdk/lib/request.js:686:14)
at Request.transition (/var/runtime/node_modules/aws-sdk/lib/request.js:22:10)
at AcceptorStateMachine.runTo (/var/runtime/node_modules/aws-sdk/lib/state_machine.js:14:12)
at /var/runtime/node_modules/aws-sdk/lib/state_machine.js:26:10
at Request.<anonymous> (/var/runtime/node_modules/aws-sdk/lib/request.js:38:9)
at Request.<anonymous> (/var/runtime/node_modules/aws-sdk/lib/request.js:688:12)
at Request.callListeners (/var/runtime/node_modules/aws-sdk/lib/sequential_executor.js:116:18) (RequestId: d65433d6-5fb1-4f27-9a22-5ad43019d2c6)


 ❌  DNSStack failed: Error: The stack named DNSStack failed creation, it may need to be manually deleted from the AWS console: ROLLBACK_COMPLETE: Received response status [FAILED] from custom resource. Message returned: AccessDeniedException: User: arn:aws:sts::705690605585:assumed-role/DNSStack-CustomCrossRegionExportWriterCustomResour-16UW94GTDPQ9N/DNSStack-CustomCrossRegionExportWriterCustomResour-U2MPPb2RYYXn is not authorized to perform: ssm:ListTagsForResource on resource: arn:aws:ssm:ap-southeast-2:705690605585:parameter/cdk/exports/ap-southeast-2-ComputeStack/DNSStackuseast1RefHostedZoneDB99F8669F50CE3B because no identity-based policy allows the ssm:ListTagsForResource action
    at Request.extractError (/var/runtime/node_modules/aws-sdk/lib/protocol/json.js:52:27)
    at Request.callListeners (/var/runtime/node_modules/aws-sdk/lib/sequential_executor.js:106:20)
    at Request.emit (/var/runtime/node_modules/aws-sdk/lib/sequential_executor.js:78:10)
    at Request.emit (/var/runtime/node_modules/aws-sdk/lib/request.js:686:14)
    at Request.transition (/var/runtime/node_modules/aws-sdk/lib/request.js:22:10)
    at AcceptorStateMachine.runTo (/var/runtime/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at /var/runtime/node_modules/aws-sdk/lib/state_machine.js:26:10
    at Request.<anonymous> (/var/runtime/node_modules/aws-sdk/lib/request.js:38:9)
    at Request.<anonymous> (/var/runtime/node_modules/aws-sdk/lib/request.js:688:12)
    at Request.callListeners (/var/runtime/node_modules/aws-sdk/lib/sequential_executor.js:116:18) (RequestId: d65433d6-5fb1-4f27-9a22-5ad43019d2c6)
    at FullCloudFormationDeployment.monitorDeployment (/home/codewarrior/.nvm/versions/node/v18.9.0/lib/node_modules/aws-cdk/lib/index.js:380:10236)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async deployStack2 (/home/codewarrior/.nvm/versions/node/v18.9.0/lib/node_modules/aws-cdk/lib/index.js:383:145458)
    at async /home/codewarrior/.nvm/versions/node/v18.9.0/lib/node_modules/aws-cdk/lib/index.js:383:128776
    at async run (/home/codewarrior/.nvm/versions/node/v18.9.0/lib/node_modules/aws-cdk/lib/index.js:383:126782)

 ❌ Deployment failed: Error: Stack Deployments Failed: Error: The stack named DNSStack failed creation, it may need to be manually deleted from the AWS console: ROLLBACK_COMPLETE: Received response status [FAILED] from custom resource. Message returned: AccessDeniedException: User: arn:aws:sts::705690605585:assumed-role/DNSStack-CustomCrossRegionExportWriterCustomResour-16UW94GTDPQ9N/DNSStack-CustomCrossRegionExportWriterCustomResour-U2MPPb2RYYXn is not authorized to perform: ssm:ListTagsForResource on resource: arn:aws:ssm:ap-southeast-2:705690605585:parameter/cdk/exports/ap-southeast-2-ComputeStack/DNSStackuseast1RefHostedZoneDB99F8669F50CE3B because no identity-based policy allows the ssm:ListTagsForResource action
    at Request.extractError (/var/runtime/node_modules/aws-sdk/lib/protocol/json.js:52:27)
    at Request.callListeners (/var/runtime/node_modules/aws-sdk/lib/sequential_executor.js:106:20)
    at Request.emit (/var/runtime/node_modules/aws-sdk/lib/sequential_executor.js:78:10)
    at Request.emit (/var/runtime/node_modules/aws-sdk/lib/request.js:686:14)
    at Request.transition (/var/runtime/node_modules/aws-sdk/lib/request.js:22:10)
    at AcceptorStateMachine.runTo (/var/runtime/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at /var/runtime/node_modules/aws-sdk/lib/state_machine.js:26:10
    at Request.<anonymous> (/var/runtime/node_modules/aws-sdk/lib/request.js:38:9)
    at Request.<anonymous> (/var/runtime/node_modules/aws-sdk/lib/request.js:688:12)
    at Request.callListeners (/var/runtime/node_modules/aws-sdk/lib/sequential_executor.js:116:18) (RequestId: d65433d6-5fb1-4f27-9a22-5ad43019d2c6)
    at deployStacks (/home/codewarrior/.nvm/versions/node/v18.9.0/lib/node_modules/aws-cdk/lib/index.js:383:129083)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async CdkToolkit.deploy (/home/codewarrior/.nvm/versions/node/v18.9.0/lib/node_modules/aws-cdk/lib/index.js:383:147507)
    at async exec4 (/home/codewarrior/.nvm/versions/node/v18.9.0/lib/node_modules/aws-cdk/lib/index.js:438:51799)

Stack Deployments Failed: Error: The stack named DNSStack failed creation, it may need to be manually deleted from the AWS console: ROLLBACK_COMPLETE: Received response status [FAILED] from custom resource. Message returned: AccessDeniedException: User: arn:aws:sts::705690605585:assumed-role/DNSStack-CustomCrossRegionExportWriterCustomResour-16UW94GTDPQ9N/DNSStack-CustomCrossRegionExportWriterCustomResour-U2MPPb2RYYXn is not authorized to perform: ssm:ListTagsForResource on resource: arn:aws:ssm:ap-southeast-2:705690605585:parameter/cdk/exports/ap-southeast-2-ComputeStack/DNSStackuseast1RefHostedZoneDB99F8669F50CE3B because no identity-based policy allows the ssm:ListTagsForResource action
    at Request.extractError (/var/runtime/node_modules/aws-sdk/lib/protocol/json.js:52:27)
    at Request.callListeners (/var/runtime/node_modules/aws-sdk/lib/sequential_executor.js:106:20)
    at Request.emit (/var/runtime/node_modules/aws-sdk/lib/sequential_executor.js:78:10)
    at Request.emit (/var/runtime/node_modules/aws-sdk/lib/request.js:686:14)
    at Request.transition (/var/runtime/node_modules/aws-sdk/lib/request.js:22:10)
    at AcceptorStateMachine.runTo (/var/runtime/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at /var/runtime/node_modules/aws-sdk/lib/state_machine.js:26:10
    at Request.<anonymous> (/var/runtime/node_modules/aws-sdk/lib/request.js:38:9)
    at Request.<anonymous> (/var/runtime/node_modules/aws-sdk/lib/request.js:688:12)
    at Request.callListeners (/var/runtime/node_modules/aws-sdk/lib/sequential_executor.js:116:18) (RequestId: d65433d6-5fb1-4f27-9a22-5ad43019d2c6)

````

### Reproduction Steps

A full example can be found at complete with code and replication steps: 

https://github.com/JBombNZ/aws-cdk-multi-region-bug

1. `git clone https://github.com/JBombNZ/aws-cdk-multi-region-bug`
2. `cd aws-cdk-multi-region-bug`
1. `npm install`
3. `cdk bootstrap aws://$accountId/ap-southeast-2 aws://$accountId/us-west-1 aws://$accountId/us-east-1`
4. `cdk deploy --all`
5. Observe error

### Additional Information/Context

While the example provided is very basic and there are workarounds such as using `HostedZone.fromHostedZoneAttributes` in each region stack my current project is a lot more complicated than this.

If you remove a region from the `regions` array then this will deploy successfully.

We have `compute` ECS clusters configured in multiple regions and we are using `crossRegionReferences` to export:

1. HostedZones
2. IAM Roles
3. Secrets
4. Centralized logging bucket

We cannot scale up to more compute regions

### CDK CLI Version

2.73.0 (build 43e681e)

### Node.js Version

v18.9.0

### OS

Arch Linux (EndeavourOS)  Linux 6.1.12-arch1-3-t2

### Language

Typescript

### Language Version

Typescript (4.8.3)

**Comment by brucegl** [comment]
Hi @pahud / all, I have a situation where:

-  one stack cross-references to a stack in the same region and another stack in a different region - this works fine
- one stack cross-references to a stack in a different region and a third stack in a third region - i get the accessdeniedexception not authorized to perform: ssm:ListTagsForResource on resource... for the third stack in the third region

I hope this alone helps. I should be able to reproduce it if necessary
