### ISSUE TITLE
ec2: deprecation warning when using `ec2.BastionHostLinux` with default values.

### ISSUE THREAD

**Issue by nokok** [aws/aws-cdk#25310]
### Describe the bug

A warning will be generated if use the default values due to the use of a deprecated API in `ec2.BastionHostLinux`.

```
  console.warn
    [WARNING] aws-cdk-lib.aws_ec2.MachineImage#latestAmazonLinux is deprecated.
      use MachineImage.latestAmazonLinux2 instead
      This API will be removed in the next major release.

       8 |     const vpc = new cdk.aws_ec2.Vpc(this, "Vpc");
       9 |
    > 10 |     new cdk.aws_ec2.BastionHostLinux(this, "BastionHost", {
         |     ^
      11 |       vpc: vpc,
      12 |     });
      13 |   }

      at Object.print (node_modules/aws-cdk-lib/.warnings.jsii.js:83646:21)
      at Function.latestAmazonLinux (node_modules/aws-cdk-lib/aws-ec2/lib/machine-image/machine-image.js:139:37)
      at new BastionHostLinux (node_modules/aws-cdk-lib/aws-ec2/lib/bastion-host.ts:183:56)
      at new SandboxCdkStack (lib/sandbox-cdk-stack.ts:10:5)
      at Object.<anonymous> (test/sandbox-cdk.test.ts:9:17)
```

### Expected Behavior

No warnings should be displayed.

### Current Behavior

The following message is displayed: 

```
aws-cdk-lib.aws_ec2.MachineImage#latestAmazonLinux is deprecated.
        Use MachineImage.latestAmazonLinux2 instead
        This API will be removed in the next major release.
```

### Reproduction Steps

```typescript
import * as cdk from "aws-cdk-lib";
import { Construct } from "constructs";

export class SandboxCdkStack extends cdk.Stack {
  constructor(scope: Construct, id: string, props?: cdk.StackProps) {
    super(scope, id, props);

    const vpc = new cdk.aws_ec2.Vpc(this, "Vpc");

    new cdk.aws_ec2.BastionHostLinux(this, "BastionHost", {
      vpc: vpc,
    });
  }
}
```

### Possible Solution

Explicitly pass the `machineImage` argument.

### CDK CLI Version

2.76.0

### Node.js Version

v18.14.2

### OS

macOS

### Language

Typescript

**Comment by nokok** [comment]
Thanks for the reply! 

It was certainly not a good idea to simply replace it as it could be a breaking change. I think I will close the draft PR (#25311 ) for now.
