### ISSUE TITLE
aws-cdk-testing: Cannot build framework-integ

### ISSUE THREAD

**Issue by vsiravar** [aws/aws-cdk#25447]
### Describe the bug

From the [CONTRIBUTING.md](https://github.com/aws/aws-cdk/blob/main/CONTRIBUTING.md#step-3-work-your-magic) doc , inorder to run integration tests `framework-integ` has to be built first using `npx lerna run build --scope=@aws-cdk-testing/framework-integ` command. 

The command errors out, thereby preventing local runs of integration tests.  This happens on the `main` branch at HEAD ae9554084611a7a476a0c25ff5615f4d12ae957d. 

### Expected Behavior

`framework-integ` is built successfully. 

### Current Behavior

Errors out. Stack trace
```
px lerna run build --scope=@aws-cdk-testing/framework-integ --verbose
lerna notice cli v6.6.1
lerna verb rootPath /private/tmp/aws-cdk
lerna notice filter including "@aws-cdk-testing/framework-integ"
lerna info filter [ '@aws-cdk-testing/framework-integ' ]
lerna verb run Nx target configuration was found. Task dependencies will be automatically included.

 >  Lerna (powered by Nx)   Running target build for project @aws-cdk-testing/framework-integ and 19 tasks it depends on:

 ————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————

> aws-cdk-lib:build

yarn run v1.22.19
$ cdk-build
x fixtures/
x fixtures/symlinks/
x fixtures/test1/
x fixtures/test1/external-link.txt
x fixtures/test1/file1.txt
x fixtures/test1/local-link.txt
x fixtures/test1/subdir/
x fixtures/test1/subdir2/
x fixtures/test1/subdir2/empty-subdir/
x fixtures/test1/subdir2/subdir3/
x fixtures/test1/subdir2/subdir3/file3.txt
x fixtures/test1/subdir2/empty-subdir/.hidden
x fixtures/test1/subdir/file2.txt
x fixtures/symlinks/external-dir-link
x fixtures/symlinks/external-link.txt
x fixtures/symlinks/indirect-external-link.txt
x fixtures/symlinks/local-dir-link
x fixtures/symlinks/local-link.txt
x fixtures/symlinks/normal-dir/
x fixtures/symlinks/normal-file.txt
x fixtures/symlinks/normal-dir/file-in-subdir.txt
WARNING: Unable to represent attribute type {"PrimitiveType":"Boolean"} as a native type
WARNING: Unable to represent attribute type {"PrimitiveType":"Boolean"} as a native type
WARNING: Unable to represent attribute type {"PrimitiveType":"Double"} as a native type
WARNING: Unable to represent attribute type {"PrimitiveType":"Boolean"} as a native type
WARNING: Unable to represent attribute type {"PrimitiveType":"Boolean"} as a native type
WARNING: Unable to represent attribute type {"PrimitiveType":"Boolean"} as a native type
WARNING: Unable to represent attribute type {"PrimitiveType":"Json"} as a native type
WARNING: Unable to represent attribute type {"PrimitiveType":"Boolean"} as a native type
WARNING: Unable to represent attribute type {"PrimitiveType":"Boolean"} as a native type
WARNING: Unable to represent attribute type {"PrimitiveType":"Boolean"} as a native type
WARNING: Unable to represent attribute type {"ItemType":"AlternatePathHint","Type":"List"} as a native type
WARNING: Unable to represent attribute type {"ItemType":"Explanation","Type":"List"} as a native type
WARNING: Unable to represent attribute type {"ItemType":"PathComponent","Type":"List"} as a native type
WARNING: Unable to represent attribute type {"PrimitiveType":"Boolean"} as a native type
WARNING: Unable to represent attribute type {"ItemType":"PathComponent","Type":"List"} as a native type
WARNING: Unable to represent attribute type {"PrimitiveType":"Boolean"} as a native type
WARNING: Unable to represent attribute type {"PrimitiveType":"Boolean"} as a native type
WARNING: Unable to represent attribute type {"PrimitiveType":"Boolean"} as a native type
WARNING: Unable to represent attribute type {"PrimitiveType":"Boolean"} as a native type
WARNING: Unable to represent attribute type {"PrimitiveType":"Boolean"} as a native type
WARNING: Unable to represent attribute type {"PrimitiveType":"Boolean"} as a native type
WARNING: Unable to represent attribute type {"PrimitiveType":"Boolean"} as a native type
WARNING: Unable to represent attribute type {"PrimitiveType":"Boolean"} as a native type
WARNING: Unable to represent attribute type {"ItemType":"ServerCertificateSummary","Type":"List"} as a native type
WARNING: Unable to represent attribute type {"PrimitiveType":"Double"} as a native type
WARNING: Unable to represent attribute type {"PrimitiveType":"Double"} as a native type
WARNING: Unable to represent attribute type {"PrimitiveType":"Double"} as a native type
WARNING: Unable to represent attribute type {"PrimitiveType":"Boolean"} as a native type
WARNING: Unable to represent attribute type {"PrimitiveType":"Boolean"} as a native type
WARNING: Unable to represent attribute type {"PrimitiveType":"Boolean"} as a native type
WARNING: Unable to represent attribute type {"PrimitiveItemType":"String","Type":"Map"} as a native type
WARNING: Unable to represent attribute type {"PrimitiveType":"Double"} as a native type
WARNING: Unable to represent attribute type {"PrimitiveType":"Double"} as a native type
WARNING: Unable to represent attribute type {"PrimitiveType":"Double"} as a native type
WARNING: Unable to represent attribute type {"PrimitiveType":"Double"} as a native type
WARNING: Unable to represent attribute type {"PrimitiveType":"Double"} as a native type
WARNING: Unable to represent attribute type {"PrimitiveType":"Boolean"} as a native type
WARNING: Unable to represent attribute type {"PrimitiveType":"Boolean"} as a native type
WARNING: Unable to represent attribute type {"PrimitiveType":"Boolean"} as a native type
WARNING: Unable to represent attribute type {"PrimitiveType":"Boolean"} as a native type
WARNING: Unable to represent attribute type {"PrimitiveType":"Boolean"} as a native type
WARNING: Unable to represent attribute type {"PrimitiveType":"Boolean"} as a native type
WARNING: Unable to represent attribute type {"PrimitiveItemType":"String","Type":"Map"} as a native type
WARNING: Unable to represent attribute type {"PrimitiveType":"Boolean"} as a native type
WARNING: Unable to represent attribute type {"PrimitiveType":"Boolean"} as a native type
WARNING: Unable to represent attribute type {"PrimitiveType":"Boolean"} as a native type
WARNING: Unable to represent attribute type {"PrimitiveType":"Boolean"} as a native type
WARNING: Unable to represent attribute type {"PrimitiveType":"Boolean"} as a native type
WARNING: Unable to represent attribute type {"PrimitiveItemType":"Json","Type":"List"} as a native type
WARNING: Unable to represent attribute type {"ItemType":"Tag","Type":"List"} as a native type
WARNING: Unable to represent attribute type {"ItemType":"ConnectPeerBgpConfiguration","Type":"List"} as a native type
WARNING: Unable to represent attribute type {"ItemType":"CoreNetworkEdge","Type":"List"} as a native type
WARNING: Unable to represent attribute type {"ItemType":"CoreNetworkSegment","Type":"List"} as a native type
WARNING: Unable to represent attribute type {"ItemType":"Tag","Type":"List"} as a native type
WARNING: Unable to represent attribute type {"ItemType":"Tag","Type":"List"} as a native type
WARNING: Unable to represent attribute type {"PrimitiveType":"Double"} as a native type
WARNING: Unable to represent attribute type {"PrimitiveType":"Double"} as a native type
WARNING: Unable to represent attribute type {"PrimitiveItemType":"String","Type":"Map"} as a native type
WARNING: Unable to represent attribute type {"PrimitiveType":"Boolean"} as a native type
WARNING: Unable to represent attribute type {"PrimitiveType":"Boolean"} as a native type
WARNING: Unable to represent attribute type {"PrimitiveType":"Boolean"} as a native type
WARNING: Unable to represent attribute type {"PrimitiveType":"Boolean"} as a native type
WARNING: Unable to represent attribute type {"PrimitiveType":"Boolean"} as a native type
WARNING: Unable to represent attribute type {"ItemType":"AnalysisError","Type":"List"} as a native type
WARNING: Unable to represent attribute type {"ItemType":"Sheet","Type":"List"} as a native type
WARNING: Unable to represent attribute type {"ItemType":"DashboardError","Type":"List"} as a native type
WARNING: Unable to represent attribute type {"ItemType":"Sheet","Type":"List"} as a native type
WARNING: Unable to represent attribute type {"PrimitiveType":"Double"} as a native type
WARNING: Unable to represent attribute type {"PrimitiveType":"Double"} as a native type
WARNING: Unable to represent attribute type {"ItemType":"OutputColumn","Type":"List"} as a native type
WARNING: Unable to represent attribute type {"ItemType":"DataSetConfiguration","Type":"List"} as a native type
WARNING: Unable to represent attribute type {"ItemType":"TemplateError","Type":"List"} as a native type
WARNING: Unable to represent attribute type {"ItemType":"Sheet","Type":"List"} as a native type
WARNING: Unable to represent attribute type {"PrimitiveType":"Double"} as a native type
WARNING: Unable to represent attribute type {"ItemType":"ThemeError","Type":"List"} as a native type
WARNING: Unable to represent attribute type {"PrimitiveType":"Double"} as a native type
WARNING: Unable to represent attribute type {"PrimitiveType":"Boolean"} as a native type
WARNING: Unable to represent attribute type {"ItemType":"ConfigParameter","Type":"List"} as a native type
WARNING: Unable to represent attribute type {"ItemType":"VpcEndpoint","Type":"List"} as a native type
WARNING: Unable to represent attribute type {"PrimitiveType":"Boolean"} as a native type
WARNING: Unable to represent attribute type {"PrimitiveType":"Boolean"} as a native type
WARNING: Unable to represent attribute type {"PrimitiveType":"Boolean"} as a native type
WARNING: Unable to represent attribute type {"ItemType":"NetworkInterface","Type":"List"} as a native type
WARNING: Unable to represent attribute type {"ItemType":"VpcSecurityGroup","Type":"List"} as a native type
WARNING: Unable to represent attribute type {"PrimitiveType":"Boolean"} as a native type
WARNING: Unable to represent attribute type {"ItemType":"ClusterEndpoint","Type":"List"} as a native type
WARNING: Unable to represent attribute type {"PrimitiveType":"Boolean"} as a native type
WARNING: Unable to represent attribute type {"ItemType":"TargetAddress","Type":"List"} as a native type
WARNING: Unable to represent attribute type {"PrimitiveType":"Boolean"} as a native type
WARNING: Unable to represent attribute type {"PrimitiveType":"Boolean"} as a native type
WARNING: Unable to represent attribute type {"PrimitiveType":"Boolean"} as a native type
WARNING: Unable to represent attribute type {"PrimitiveType":"Boolean"} as a native type
WARNING: Unable to represent attribute type {"PrimitiveType":"Boolean"} as a native type
WARNING: Unable to represent attribute type {"ItemType":"NetworkInterface","Type":"List"} as a native type
WARNING: Unable to represent attribute type {"PrimitiveItemType":"String","Type":"Map"} as a native type
WARNING: Unable to represent attribute type {"PrimitiveType":"Boolean"} as a native type
WARNING: Unable to represent attribute type {"ItemType":"ConnectionAliasAssociation","Type":"List"} as a native type
WARNING: Unable to represent attribute type {"PrimitiveType":"Boolean"} as a native type
WARNING: Unable to represent attribute type {"PrimitiveType":"Boolean"} as a native type
WARNING: Unable to represent attribute type {"PrimitiveType":"Boolean"} as a native type
WARNING: Unable to represent attribute type {"PrimitiveType":"Json"} as a native type
warning JSII6: A "peerDependency" on "constructs" at "^10.0.0" means you should take a "devDependency" on "constructs" at "10.0.0" (found "^10.0.0")
aws-apigateway/lib/domain-name.ts:132:19 - warning JSII5019: The property name "domainName" conflicts with the declaring class "DomainName". This will result in renaming the class to "_DomainName" in C#. Consider renaming "domainName".

132   public readonly domainName: string;
                      ~~~~~~~~~~

  aws-apigateway/lib/domain-name.ts:117:14
    117 export class DomainName extends Resource implements IDomainName {
                     ~~~~~~~~~~
    The declaring class is introduced here
aws-apigateway/lib/gateway-response.ts:217:19 - warning JSII5019: The property name "responseType" conflicts with the declaring class "ResponseType". This will result in renaming the class to "_ResponseType" in C#. Consider renaming "responseType".

217   public readonly responseType: string;
                      ~~~~~~~~~~~~

  aws-apigateway/lib/gateway-response.ts:101:14
    101 export class ResponseType {
                     ~~~~~~~~~~~~
    The declaring class is introduced here
aws-codepipeline/lib/artifact.ts:15:17 - warning JSII5019: The method name "artifact" conflicts with the declaring class "Artifact". This will result in renaming the class to "_Artifact" in C#. Consider renaming "artifact".

15   public static artifact(name: string): Artifact {
                   ~~~~~~~~

  aws-codepipeline/lib/artifact.ts:8:14
    8 export class Artifact {
                   ~~~~~~~~
    The declaring class is introduced here
aws-codepipeline/lib/artifact.ts:124:17 - warning JSII5019: The method name "artifactPath" conflicts with the declaring class "ArtifactPath". This will result in renaming the class to "_ArtifactPath" in C#. Consider renaming "artifactPath".

124   public static artifactPath(artifactName: string, fileName: string): ArtifactPath {
                    ~~~~~~~~~~~~

  aws-codepipeline/lib/artifact.ts:123:14
    123 export class ArtifactPath {
                     ~~~~~~~~~~~~
    The declaring class is introduced here
aws-ec2/lib/connections.ts:69:19 - warning JSII5019: The property name "connections" conflicts with the declaring class "Connections". This will result in renaming the class to "_Connections" in C#. Consider renaming "connections".

69   public readonly connections: Connections;
                     ~~~~~~~~~~~

  aws-ec2/lib/connections.ts:68:14
    68 export class Connections implements IConnectable {
                    ~~~~~~~~~~~
    The declaring class is introduced here
aws-ec2/lib/instance.ts:309:19 - warning JSII5019: The property name "instance" conflicts with the declaring class "Instance". This will result in renaming the class to "_Instance" in C#. Consider renaming "instance".

309   public readonly instance: CfnInstance;
                      ~~~~~~~~

  aws-ec2/lib/instance.ts:279:14
    279 export class Instance extends Resource implements IInstance {
                     ~~~~~~~~
    The declaring class is introduced here
aws-ecr-assets/lib/image-asset.ts:80:39 - warning JSII5019: The property name "platform" conflicts with the declaring class "Platform". This will result in renaming the class to "_Platform" in C#. Consider renaming "platform".

80   private constructor(public readonly platform: string) { }
                                         ~~~~~~~~

  aws-ecr-assets/lib/image-asset.ts:56:14
    56 export class Platform {
                    ~~~~~~~~
    The declaring class is introduced here
aws-lambda/lib/lambda-version.ts:180:19 - warning JSII5019: The property name "version" conflicts with the declaring class "Version". This will result in renaming the class to "_Version" in C#. Consider renaming "version".

180   public readonly version: string;
                      ~~~~~~~

  aws-lambda/lib/lambda-version.ts:114:14
    114 export class Version extends QualifiedFunctionBase implements IVersion {
                     ~~~~~~~
    The declaring class is introduced here
Build times for aws-cdk-lib: Total time (1m50.9s) | /private/tmp/aws-cdk/tools/@aws-cdk/cdk-build-tools/node_modules/jsii/bin/jsii (1m38.7s) | ts-node ./scripts/verify-imports-resolve-same.ts && ts-node ./scripts/verify-imports-shielded.ts && ts-node ./cx-api/build-tools/flag-report.ts (6.9s) | ts-node -P tsconfig.dev.json scripts/gen.ts (2.9s) | npx ts-node -P tsconfig.dev.json region-info/build-tools/generate-static-data.ts && node aws-events-targets/build-tools/gen.js && (cp -f $(node -p 'require.resolve("aws-sdk/apis/metadata.json")') custom-resources/lib/aws-custom-resource/sdk-api-metadata.json && rm -rf custom-resources/test/aws-custom-resource/cdk.out) && (rm -rf core/test/fs/fixtures && cd core/test/fs && tar -xzf fixtures.tar.gz) && (rm -rf assets/test/fs/fixtures && cd assets/test/fs && tar -xzvf fixtures.tar.gz) (1.4s)
Done in 111.03s.


 ————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————

 >  Lerna (powered by Nx)   Successfully ran target build for project @aws-cdk-testing/framework-integ and 19 tasks it depends on

   Nx read the output from the cache instead of running the command for 10 out of 20 tasks.


 >  Lerna (powered by Nx)   spawn EBADF


Error: spawn EBADF
    at ChildProcess.spawn (node:internal/child_process:413:11)
    at spawn (node:child_process:757:9)
    at execFile (node:child_process:348:17)
    at /private/tmp/aws-cdk/node_modules/nx/src/tasks-runner/cache.js:151:46
    at new Promise (<anonymous>)
    at Cache.<anonymous> (/private/tmp/aws-cdk/node_modules/nx/src/tasks-runner/cache.js:150:20)
    at Generator.next (<anonymous>)
    at /private/tmp/aws-cdk/node_modules/tslib/tslib.js:167:75
    at new Promise (<anonymous>)
    at Object.__awaiter (/private/tmp/aws-cdk/node_modules/tslib/tslib.js:163:16)
    at Cache.copy (/private/tmp/aws-cdk/node_modules/nx/src/tasks-runner/cache.js:142:24)
    at Cache.<anonymous> (/private/tmp/aws-cdk/node_modules/nx/src/tasks-runner/cache.js:80:36)
    at Generator.next (<anonymous>)
    at fulfilled (/private/tmp/aws-cdk/node_modules/tslib/tslib.js:164:62)
```

### Reproduction Steps

```
cd /tmp
git clone git@github.com:aws/aws-cdk.git
cd aws-cdk
npx lerna run build --scope=@aws-cdk-testing/framework-integ --verbose
```

### CDK CLI Version

2.77.0 (build 06a0b19) **************************************************** *** Newer version of CDK is available [2.78.0]   *** *** Upgrade recommended (npm install -g aws-cdk) *** ****************************************************

### Node.js Version

v18.16.0

### OS

macOS 13.3.1

### Language

Typescript

**Comment by pahud** [comment]
Please run your commands as below:

```sh
$ git clone https://github.com/aws/aws-cdk.git
$ cd aws-cdk
$ yarn install
$ npx lerna run build --scope=aws-cdk-lib --scope=@aws-cdk-testing/framework-integ
```

If you see out of memory error, run `NODE_OPTIONS=--max-old-space-size=8192` before you run `npx lerna run build` as described [here](https://github.com/aws/aws-cdk/blob/main/CONTRIBUTING.md#amazon-codecatalyst-dev-environments).

Let me know if it works for you.

**Comment by vsiravar** [comment]
This works for me, sorry for not closing this earlier. I am able to build and run integration tests on my local machine. Thanks!
