### ISSUE TITLE
Exception creating CfnIdentityPool 

### ISSUE THREAD

**Issue by kianris** [aws/aws-cdk#2555]
**Describe the bug**
Using the CfnIdentityPool construct throws an error when running the CDK application.

**To Reproduce**
Create a stack with a default CfnIdentityPool construct:

```java
        new CfnIdentityPool(this, "pool-id", CfnIdentityPoolProps.builder()
                .withAllowUnauthenticatedIdentities(false)
                .build());
```

Running `cdk diff` then produces:
```
Exception in thread "main" software.amazon.jsii.JsiiException: Cannot convert undefined or null to object
TypeError: Cannot convert undefined or null to object
    at Function.entries (<anonymous>)
    at filterUndefined (/tmp/jsii-kernel-Mw2suz/node_modules/@aws-cdk/cdk/lib/util.js:54:43)
    at filterUndefined (/tmp/jsii-kernel-Mw2suz/node_modules/@aws-cdk/cdk/lib/util.js:58:24)
    at filterUndefined (/tmp/jsii-kernel-Mw2suz/node_modules/@aws-cdk/cdk/lib/util.js:58:24)
    at filterUndefined (/tmp/jsii-kernel-Mw2suz/node_modules/@aws-cdk/cdk/lib/util.js:58:24)
    at filterUndefined (/tmp/jsii-kernel-Mw2suz/node_modules/@aws-cdk/cdk/lib/util.js:58:24)
    at Object.filterUndefined (/tmp/jsii-kernel-Mw2suz/node_modules/@aws-cdk/cdk/lib/util.js:58:24)
    at renderLegacyStacks (/tmp/jsii-kernel-Mw2suz/node_modules/@aws-cdk/cdk/lib/synthesis.js:236:32)
    at SynthesisSession.close (/tmp/jsii-kernel-Mw2suz/node_modules/@aws-cdk/cdk/lib/synthesis.js:94:25)
    at Kernel._wrapSandboxCode (/tmp/jsii-java-runtime8294719311624135237/jsii-runtime.js:6967:19)
    at ret._ensureSync (/tmp/jsii-java-runtime8294719311624135237/jsii-runtime.js:6331:25)
    at Kernel._ensureSync (/tmp/jsii-java-runtime8294719311624135237/jsii-runtime.js:6935:20)
    at Kernel.invoke (/tmp/jsii-java-runtime8294719311624135237/jsii-runtime.js:6330:26)
    at KernelHost.processRequest (/tmp/jsii-java-runtime8294719311624135237/jsii-runtime.js:6024:28)
    at KernelHost.run (/tmp/jsii-java-runtime8294719311624135237/jsii-runtime.js:5970:14)
    at processRequest (/tmp/jsii-java-runtime8294719311624135237/jsii-runtime.js:5970:45)
    at KernelHost.processRequest (/tmp/jsii-java-runtime8294719311624135237/jsii-runtime.js:6066:16)
    at KernelHost.run (/tmp/jsii-java-runtime8294719311624135237/jsii-runtime.js:5970:14)
    at processRequest (/tmp/jsii-java-runtime8294719311624135237/jsii-runtime.js:5970:45)
    at KernelHost.processRequest (/tmp/jsii-java-runtime8294719311624135237/jsii-runtime.js:6066:16)
	at software.amazon.jsii.JsiiRuntime.processErrorResponse(JsiiRuntime.java:112)
	at software.amazon.jsii.JsiiRuntime.requestResponse(JsiiRuntime.java:84)
	at software.amazon.jsii.JsiiClient.callMethod(JsiiClient.java:185)
	at software.amazon.jsii.JsiiObject.jsiiCall(JsiiObject.java:57)
	at software.amazon.awscdk.App.run(App.java:33)
```

**Version:**
 - Ubuntu 18.04
 - Java
 - CDK 0.31.0 (build 7a70c08)

I believe this was working before with version 0.26.0.

**Comment by SomayaB** [comment]
Hi @kianris, I'm sorry this has gone so long without response. Are you still experiencing this issue?

**Comment by waddle-dev** [comment]
Tested again with 1.7 and it seems to be working now, thanks.

**Comment by kianris** [comment]
Tested with 1.7 and it seems to be working now, thanks.
