### ISSUE TITLE
Fn.conditionOr generates invalid CFN snippet

### ISSUE THREAD

**Issue by MalikAtalla-AWS** [aws/aws-cdk#25696]
### Describe the bug

I have a piece of code that uses `Fn.conditionOr` with a list of conditions. When the list is longer than 10 elements, CDK is smart enough to break it up into chunks of 10. Otherwise, CloudFormation would complain that an Fn::Or cannot have more than 10 elements. The problem I'm running into is for a list of 11 elements. CDK generates two Fn::Or expressions: One with 10 elements and one with 1 element. When deployment this stack, CloudFormation complains that an Fn::Or must contain at least 2 elements.
Error message from CFN: `Template error: every Fn::Or object requires a list of at least 2 and at most 10 boolean parameters.`

### Expected Behavior

Given a list of `conditions` of length 11 (let's say of type Fn::Equals) and this code snippet:
`Fn.conditionOr(...conditions)`, CDK should break up the list in a way that's valid according to CloudFormation's rules. For example into length 9 and 2:

```json
"Fn::Or": [
 {
  "Fn::Or": [
   {
    "Fn::Equals": [
     "1",
     "B"
    ]
   },
   {
    "Fn::Equals": [
     "2",
     "B"
    ]
   },
   {
    "Fn::Equals": [
     "3",
     "B"
    ]
   },
   {
    "Fn::Equals": [
     "4",
     "B"
    ]
   },
   {
    "Fn::Equals": [
     "5",
     "B"
    ]
   },
   {
    "Fn::Equals": [
     "6",
     "B"
    ]
   },
   {
    "Fn::Equals": [
     "7",
     "B"
    ]
   },
   {
    "Fn::Equals": [
     "8",
     "B"
    ]
   },
   {
    "Fn::Equals": [
     "9",
     "B"
    ]
   }
  ]
 },
 {
  "Fn::Or": [
   {
    "Fn::Equals": [
     "10",
     "B"
    ]
   },
   {
    "Fn::Equals": [
     "11",
     "B"
    ]
   }
  ]
 }
]

```

### Current Behavior

Given a list of `conditions` of length 11 (let's say of type Fn::Equals) and this code snippet:
`Fn.conditionOr(...conditions)`, CDK generates a template snippet like this:

```json
"Fn::Or": [
 {
  "Fn::Or": [
   {
    "Fn::Equals": [
     "1",
     "B"
    ]
   },
   {
    "Fn::Equals": [
     "2",
     "B"
    ]
   },
   {
    "Fn::Equals": [
     "3",
     "B"
    ]
   },
   {
    "Fn::Equals": [
     "4",
     "B"
    ]
   },
   {
    "Fn::Equals": [
     "5",
     "B"
    ]
   },
   {
    "Fn::Equals": [
     "6",
     "B"
    ]
   },
   {
    "Fn::Equals": [
     "7",
     "B"
    ]
   },
   {
    "Fn::Equals": [
     "8",
     "B"
    ]
   },
   {
    "Fn::Equals": [
     "9",
     "B"
    ]
   },
   {
    "Fn::Equals": [
     "10",
     "B"
    ]
   }
  ]
 },
 {
  "Fn::Or": [
   {
    "Fn::Equals": [
     "11",
     "B"
    ]
   }
  ]
 }
]

```

### Reproduction Steps

See example above

### CDK CLI Version

2.62.2

### Node.js Version

v16.20.0

### OS

Ubuntu 20

### Language

Typescript

### Language Version

4.9.4

**Comment by peterwoodworth** [comment]
Could you provide a code snippet which reproduces this please?

**Comment by peterwoodworth** [comment]
Will need to adjust here to account for 10n + 1 cases https://github.com/aws/aws-cdk/blob/bbdb16ad65b1217901f92782a74a6f13222cd684/packages/aws-cdk-lib/core/lib/cfn-fn.ts#L330-L338

**Comment by wafuwafu13** [comment]
I reproduced this.

```ts
import * as cdk from 'aws-cdk-lib';
import { Construct } from 'constructs';
import * as s3 from 'aws-cdk-lib/aws-s3';

export class AwsCdkPlaygroundStack extends cdk.Stack {
  constructor(scope: Construct, id: string, props?: cdk.StackProps) {
    super(scope, id, props);

    const currentRegion = this.region;

    const isEuWest1 = new cdk.CfnCondition(this, 'IsEuWest1', {
      expression: cdk.Fn.conditionOr(
        cdk.Fn.conditionEquals(currentRegion, 'eu-west-1'),
        cdk.Fn.conditionEquals(currentRegion, '2'),
        cdk.Fn.conditionEquals(currentRegion, '3'),
        cdk.Fn.conditionEquals(currentRegion, '4'),
        cdk.Fn.conditionEquals(currentRegion, '5'),
        cdk.Fn.conditionEquals(currentRegion, '6'),
        cdk.Fn.conditionEquals(currentRegion, '7'),
        cdk.Fn.conditionEquals(currentRegion, '8'),
        cdk.Fn.conditionEquals(currentRegion, '9'),
        cdk.Fn.conditionEquals(currentRegion, '10'),
        cdk.Fn.conditionEquals(currentRegion, '11'),
      ),
    });

    const myBucket = new s3.CfnBucket(this, 'MyBucket');
    myBucket.cfnOptions.condition = isEuWest1;
  }
}
```

-> 

```
$ cdk deploy   
...

 ❌  AwsCdkPlaygroundStack failed: Error [ValidationError]: Template error: every Fn::Or object requires a list of at least 2 and at most 10 boolean parameters.
    at Request.extractError (/Users/wafuwafu13/Desktop/aws-cdk-playground/node_modules/aws-cdk/lib/index.js:292:46245)
    at Request.callListeners (/Users/wafuwafu13/Desktop/aws-cdk-playground/node_modules/aws-cdk/lib/index.js:292:89237)
    at Request.emit (/Users/wafuwafu13/Desktop/aws-cdk-playground/node_modules/aws-cdk/lib/index.js:292:88685)
    at Request.emit (/Users/wafuwafu13/Desktop/aws-cdk-playground/node_modules/aws-cdk/lib/index.js:292:195114)
    at Request.transition (/Users/wafuwafu13/Desktop/aws-cdk-playground/node_modules/aws-cdk/lib/index.js:292:188666)
    at AcceptorStateMachine.runTo (/Users/wafuwafu13/Desktop/aws-cdk-playground/node_modules/aws-cdk/lib/index.js:292:153538)
    at /Users/wafuwafu13/Desktop/aws-cdk-playground/node_modules/aws-cdk/lib/index.js:292:153868
    at Request.<anonymous> (/Users/wafuwafu13/Desktop/aws-cdk-playground/node_modules/aws-cdk/lib/index.js:292:188958)
    at Request.<anonymous> (/Users/wafuwafu13/Desktop/aws-cdk-playground/node_modules/aws-cdk/lib/index.js:292:195189)
    at Request.callListeners (/Users/wafuwafu13/Desktop/aws-cdk-playground/node_modules/aws-cdk/lib/index.js:292:89405) {
  code: 'ValidationError',
  time: 2023-05-23T21:09:15.223Z,
  requestId: '<>',
  statusCode: 400,
  retryable: false,
  retryDelay: 139.10892475675584
}
```

```ts
import * as cdk from 'aws-cdk-lib';
import { Construct } from 'constructs';
import * as s3 from 'aws-cdk-lib/aws-s3';

export class AwsCdkPlaygroundStack extends cdk.Stack {
  constructor(scope: Construct, id: string, props?: cdk.StackProps) {
    super(scope, id, props);

    const currentRegion = this.region;

    const isEuWest1 = new cdk.CfnCondition(this, 'IsEuWest1', {
      expression: cdk.Fn.conditionOr(
        cdk.Fn.conditionEquals(currentRegion, 'eu-west-1'),
        cdk.Fn.conditionEquals(currentRegion, '2'),
        cdk.Fn.conditionEquals(currentRegion, '3'),
        cdk.Fn.conditionEquals(currentRegion, '4'),
        cdk.Fn.conditionEquals(currentRegion, '5'),
        cdk.Fn.conditionEquals(currentRegion, '6'),
        cdk.Fn.conditionEquals(currentRegion, '7'),
        cdk.Fn.conditionEquals(currentRegion, '8'),
        cdk.Fn.conditionEquals(currentRegion, '9'),
        cdk.Fn.conditionEquals(currentRegion, '10'),
        cdk.Fn.conditionEquals(currentRegion, '11'),
        cdk.Fn.conditionEquals(currentRegion, '12'),
        cdk.Fn.conditionEquals(currentRegion, '13'),
        cdk.Fn.conditionEquals(currentRegion, '14'),
        cdk.Fn.conditionEquals(currentRegion, '15'),
        cdk.Fn.conditionEquals(currentRegion, '16'),
        cdk.Fn.conditionEquals(currentRegion, '17'),
        cdk.Fn.conditionEquals(currentRegion, '18'),
        cdk.Fn.conditionEquals(currentRegion, '19'),
        cdk.Fn.conditionEquals(currentRegion, '20'),
        cdk.Fn.conditionEquals(currentRegion, '21'),
      ),
    });

    const myBucket = new s3.CfnBucket(this, 'MyBucket');
    myBucket.cfnOptions.condition = isEuWest1;
  }
}
```

-> 

```
$ cdk deploy   
...

 ❌  AwsCdkPlaygroundStack failed: Error [ValidationError]: Template error: every Fn::Or object requires a list of at least 2 and at most 10 boolean parameters.
...
```

**Comment by wafuwafu13** [comment]
I'm working on this

**Comment by tmokmss** [comment]
We also have to care `Fn.conditionAnd` since it has the same constraint:

`Stack failed: Error [ValidationError]: Template error: every Fn::And object requires a list of at least 2 and at most 10 boolean parameters.`
