### ISSUE TITLE
(CodeDeployServerDeployAction): adding action with CodeDeployServerDeployAction to Pipeline fails with  "Cannot read properties of undefined (reading 'region')"

### ISSUE THREAD

**Issue by dominic-lear** [aws/aws-cdk#25784]
### Describe the bug

When creating a pipeline in using javascript and "aws-cdk-lib": "^2.81.0" i receive the below error.

everything is created ok until i attempt to add the deployStage.addAction section

Am i missing something here or is this a bug? i cant seem to diagnose how to resolve it.

Region: eu-west-2
Node: v18.16.0

ℹ️ CDK Version: 2.81.0 (build bd920f2)
ℹ️ AWS environment variables:
  - AWS_STS_REGIONAL_ENDPOINTS = regional
  - AWS_NODEJS_CONNECTION_REUSE_ENABLED = 1
  - AWS_SDK_LOAD_CONFIG = 1
ℹ️ No CDK environment variables

### Expected Behavior

Stack creates working code pipeline with deploy stage that uses ServerApplication, ServerDeploymentGroup and CodeDeployServerDeployAction or a more descriptive error message is displayed.

### Current Behavior

When deploying the cdk stack with `cdk deploy --profile XXX`

`TypeError: Cannot read properties of undefined (reading 'region')
    at get effectiveRegion [as effectiveRegion] (/XXX/aws-stacks/stacks/connect/node_modules/aws-cdk-lib/aws-codepipeline/lib/private/rich-action.js:1:1063)
    at get isCrossRegion [as isCrossRegion] (/XXX/aws-stacks/stacks/connect/node_modules/aws-cdk-lib/aws-codepipeline/lib/private/rich-action.js:1:498)
    at Pipeline.ensureReplicationResourcesExistFor (/XXX/aws-stacks/stacks/connect/node_modules/aws-cdk-lib/aws-codepipeline/lib/pipeline.js:1:8351)
    `

### Reproduction Steps

```
const pipeline = new Pipeline(stack, 'pipeline');

const application = new ServerApplication(stack, 'myproduct-myenv', {
    applicationName: 'myproduct-myenv', // optional property
  });

  const role = Role.fromRoleArn(stack, 'DeployRole', 'someArn');

  const workerDeploymentGroupName = 'worker-deployment-group';
  const workerDeploymentGroup = new ServerDeploymentGroup(stack, 'DeploymentGroup2', {
    application,
    deploymentGroupName: workerDeploymentGroupName,
    autoScalingGroups: [ec2WorkerSecurityGroup],
    role,
    installAgent: false,
  });


  const deployStage = pipeline.addStage({
    stageName: 'Deploy',
    justAfter: previousStage,
  });

  deployStage.addAction(new CodeDeployServerDeployAction({
    actionName: 'DeployWorkerServers',
    deploymentGroup: workerDeploymentGroup.deploymentGroupName,
    input,
    runOrder: 1,   
  }));
```

### Possible Solution

Something tells me its to do with the region of the pipeline maybe but i can see it could also be related to the `resource` `iResource` in the action or richaction.

### CDK CLI Version

2.81.0 (build bd920f2)

### Node.js Version

v18.16.0

### OS

macos

### Language

Typescript

### Language Version

plain js

**Comment by peterwoodworth** [comment]
[Stack has no config prop](https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.Stack.html), not sure where you're getting `stack.config.stack` from.

**Comment by dominic-lear** [comment]
Those two lines are commented, if i uncomment them they were just simple string values ive set on my stack class. 

```
const config = {
  domain: 'XXX.uk',
  product: 'XXXX',
  stack: {
    accountId: 'XXXXX',
    defaultRegion: 'eu-west-2',
```

**Comment by dominic-lear** [comment]
ive updated the examples for clarity

**Comment by dominic-lear** [comment]
yes that has resolved the issue, apologies for my oversight.

If i resolve that error i then receive the issue below? appreciate thats out of scope of the original issue so feel free to close this if you dont have a quick idea on the cause.

```
TypeError: Cannot read properties of undefined (reading 'addToPrincipalPolicy')
    at Grant.addToPrincipal (/Users/dominic.lear/Sites/docker-local-development/aws-stacks/stacks/connect/node_modules/aws-cdk-lib/aws-iam/lib/grant.js:1:2028)
    at Grant.addToPrincipalOrResource (/Users/dominic.lear/Sites/docker-local-development/aws-stacks/stacks/connect/node_modules/aws-cdk-lib/aws-iam/lib/grant.js:1:649)
    at Bucket.grant (/Users/dominic.lear/Sites/docker-local-development/aws-stacks/stacks/connect/node_modules/aws-cdk-lib/aws-s3/lib/bucket.js:1:9888)
    at Bucket.grantRead (/Users/dominic.lear/Sites/docker-local-development/aws-stacks/stacks/connect/node_modules/aws-cdk-lib/aws-s3/lib/bucket.js:1:5066)
    at CodeDeployServerDeployAction.bound (/Users/dominic.lear/Sites/docker-local-development/aws-stacks/stacks/connect/node_modules/aws-cdk-lib/aws-codepipeline-actions/lib/codedeploy/server-deploy-action.js:1:1859)
```

**Comment by peterwoodworth** [comment]
If I were to guess it's likely a similar issue in that you might've passed the wrong type somewhere (is `ec2WorkerSecurityGroup` a `SecurityGroup` construct passed into something asking for `AutoScalingGroup`s?). I'd recommend using TypeScript if you are able, it makes it easier to catch these kinds of errors
