### ISSUE TITLE
eks: After upgrading to 2.80, imported cluster resources fail to deploy

### ISSUE THREAD

**Issue by dancmeyers** [aws/aws-cdk#25938]
### Describe the bug

This is a copy of #25835, because that issue was auto-resolved when a PR claiming to fix it was merged. However the associated PR did _not_ fix the issue, it merely updated the documentation. The issue is still present.

-----

After upgrading CDK to 2.80, the EKS cluster creation role no longer can be assumed by separate handlers in stacks that import the EKS cluster as explained in https://github.com/aws/aws-cdk/issues/25674.

The suggested fix of importing the whole kubectlProvider results in a `Modifying service token is not allowed` error when trying to deploy the stack.

### Expected Behavior

Kubernetes resources in the importing stack should still deploy in 2.80+ after adjusting the cluster importing as mentioned in https://github.com/aws/aws-cdk/issues/25674

### Current Behavior

cdk8s chart in the importing stack fails to deploy after the upgrade.

    StackNameRedacted: creating CloudFormation changeset...
    2:20:09 PM | UPDATE_FAILED | Custom::AWSCDK-EKS-KubernetesResource | KubeClusterCommonK8sChartA8489958
    Modifying service token is not allowed.

    ❌ StackNameRedacted failed: Error: The stack named StackNameRedacted failed to deploy: UPDATE_ROLLBACK_COMPLETE: Modifying service token is not allowed.
    at FullCloudFormationDeployment.monitorDeployment (/workdir/node_modules/aws-cdk/lib/index.js:397:10236)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Object.deployStack2 [as deployStack] (/workdir/node_modules/aws-cdk/lib/index.js:400:149977)
    at async /workdir/node_modules/aws-cdk/lib/index.js:400:135508

    ❌ Deployment failed: Error: The stack named StackNameRedacted failed to deploy: UPDATE_ROLLBACK_COMPLETE: Modifying service token is not allowed.
    at FullCloudFormationDeployment.monitorDeployment (/workdir/node_modules/aws-cdk/lib/index.js:397:10236)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Object.deployStack2 [as deployStack] (/workdir/node_modules/aws-cdk/lib/index.js:400:149977)
    at async /workdir/node_modules/aws-cdk/lib/index.js:400:135508

    The stack named StackNameRedacted failed to deploy: UPDATE_ROLLBACK_COMPLETE: Modifying service token is not allowed.

### Reproduction Steps

Export (app A, stack A)

```typescript
const kubectlProvider = cluster.stack.node
  .findChild('@aws-cdk--aws-eks.KubectlProvider') as eks.KubectlProvider

new CfnOutput(scope, 'KubectlProviderRole', {
  exportName: 'KubectlRoleArn',
  value: kubectlProvider.roleArn,
});

new CfnOutput(scope, 'KubectlProviderHandlerRole', {
  exportName: 'KubectlHandlerRoleArn',
  value: kubectlProvider.handlerRole.roleArn,
});

const customResourceProvider = kubectlProvider.node.findChild('Provider') as custom_resource.Provider;

new CfnOutput(scope, 'KubectlServiceToken', {
  exportName: 'KubectlServiceToken',
  value: customResourceProvider.serviceToken,
});

// tried also
// new CfnOutput(scope, 'KubectlServiceToken', {
//   exportName: 'KubectlServiceToken',
//   value: customResourceProvider.serviceToken,
// });
```

N.B. I have verified that the value of the `KubectlServiceToken` output is the same as the `ServiceToken` value provided to the lambda in app/stack A if a manifest is added to the cluster _there_.

Import (app B, stack B)

```typescript
const kubectlProvider = eks.KubectlProvider.fromKubectlProviderAttributes(
  scope,
  'KubectlProvider',
  {
    functionArn: Fn.importValue('KubectlServiceToken'),
    handlerRole: iam.Role.fromRoleArn(
      scope,
      'HandlerRole',
      Fn.importValue('KubectlHandlerRoleArn')
    ),
    kubectlRoleArn: Fn.importValue('KubectlRoleArn'),
  }
);

const openIdConnectProvider = iam.OpenIdConnectProvider.fromOpenIdConnectProviderArn(
  scope,
  'KubeOidcProvider',
  Fn.importValue('KubernetesOidcProviderArn')
);

const kubectlSecurityGroupId = Fn.importValue('KubernetesControlPlaneSGId');
return eks.Cluster.fromClusterAttributes(scope, 'KubeCluster', {
  clusterName,
  kubectlPrivateSubnetIds: Fn.split(',', Fn.importValue('KubernetesPrivateSubnetIds')),
  kubectlSecurityGroupId: kubectlSecurityGroupId,
  clusterSecurityGroupId: kubectlSecurityGroupId,
  vpc,
  openIdConnectProvider,
  kubectlLayer: new KubectlV25Layer(scope, 'kubectl'),
  kubectlProvider: kubectlProvider,
});
```

Then trying to deploy the (already existing) stack B fails with the mentioned error. The service token _has_ changed, because it is now referencing a function arn of a function from stack A, instead of the one in stack B that it previously referenced.

### Additional Information/Context

Both of the stacks have been in use for a long time and the only change to the cluster importing was to replace kubectlRoleArn with kubectlProvider. They are part of bigger ckd apps and this problem affects multiple stacks in multiple importing apps.

### CDK CLI Version

2.81.0 (build bd920f2)

### Node.js Version

v18.14.2

### OS

Linux

### Language

Typescript

### Language Version

TypeScript (3.9.10)

### Other information

Came across the following earlier issue with similar symptoms from back when eks was experimental in CDK: https://github.com/aws/aws-cdk/issues/6129.

**Comment by pahud** [comment]
Looking into this.

**Comment by pahud** [comment]
In `2.79.0` you should be able to deploy manifests from the imported cluster cross-stack as the sample below:

```ts
export class EksStack extends Stack {
  readonly clusterName: string;
  readonly vpc: ec2.IVpc;
  readonly KubectlRoleArn: string;

  constructor(scope: Construct, id: string, props?: StackProps) {
    super(scope, id, props);

    // create a new cluster
    const vpc = getOrCreateVpc(this);
    const kubectlLayer = new KubectlLayer(this, 'KubectlLayer');
    const cluster = new eks.Cluster(this, 'EksCluster', {
      vpc,
      version: eks.KubernetesVersion.V1_26,
      kubectlLayer,
      defaultCapacity: 0,
    });

    this.clusterName = cluster.clusterName;
    this.vpc = vpc;
    this.KubectlRoleArn = cluster.kubectlRole!.roleArn;

    // EKS service role
    new CfnOutput(this, 'ClusterRole', { value: cluster.role.roleArn });
    // EKS cluster creation role
    new CfnOutput(this, 'ClusterAdminRole', { value: cluster.adminRole.roleArn });
    // Kubectl Role
    new CfnOutput(this, 'KubectlRole', { value: cluster.kubectlRole!.roleArn });
  }
}

export interface EksImportStackProps extends StackProps {
  readonly clusterName: string;
  readonly vpc: ec2.IVpc;
  readonly kubectlRoleArn: string;
}

export class EksImportStack extends Stack {
  constructor(scope: Construct, id: string, props: EksImportStackProps) {
    super(scope, id, props);

    const vpc = props.vpc;
    const importedCluster = eks.Cluster.fromClusterAttributes(this, 'ImportedCluster', {
      vpc,
      clusterName: props.clusterName,
      kubectlRoleArn: props.kubectlRoleArn,
    });

    importedCluster.addHelmChart('NginxIngress', {
      chart: 'nginx-ingress',
      repository: 'https://helm.nginx.com/stable',
      namespace: 'kube-system',
    });
  }
}
```

in `app.ts`

```ts
const eksStack = new EksStack(app, 'eks-test7', { env })
new EksImportStack(app, 'imported-eks', { 
    env,
    clusterName: eksStack.clusterName,
    kubectlRoleArn: eksStack.KubectlRoleArn,
    vpc: eksStack.vpc,
});
```

And when you upgrade to `2.83.1`, which is the latest version as of today:

run `npx cdk diff` you will noticed the `MasterRole` and `AwsAuth` custom resource will be destroyed.

```
[-] AWS::IAM::Role EksCluster/MastersRole EksClusterMastersRole3F49FAC3 destroy
[-] Custom::AWSCDK-EKS-KubernetesResource EksCluster/AwsAuth/manifest/Resource EksClusterAwsAuthmanifest4F460A9B destroy
```

And the `AssumeRolePolicyDocument` of `CreationRole` will change.

```
[~] AWS::IAM::Role EksCluster/Resource/CreationRole EksClusterCreationRole75AABE42 
 └─ [~] AssumeRolePolicyDocument
     └─ [~] .Statement:
         └─ @@ -3,7 +3,26 @@
            [ ]     "Action": "sts:AssumeRole",
            [ ]     "Effect": "Allow",
            [ ]     "Principal": {
            [-]       "AWS": "arn:aws:iam::<deducted>:root"
            [+]       "AWS": [
            [+]         {
            [+]           "Fn::GetAtt": [
            [+]             "EksClusterKubectlHandlerRole4A986A70",
            [+]             "Arn"
            [+]           ]
            [+]         },
            [+]         {
            [+]           "Fn::GetAtt": [
            [+]             "awscdkawseksClusterResourceProviderNestedStackawscdkawseksClusterResourceProviderNestedStackResource9827C454",
            [+]             "Outputs.ekstest7awscdkawseksClusterResourceProviderIsCompleteHandlerServiceRole104F2F21Arn"
            [+]           ]
            [+]         },
            [+]         {
            [+]           "Fn::GetAtt": [
            [+]             "awscdkawseksClusterResourceProviderNestedStackawscdkawseksClusterResourceProviderNestedStackResource9827C454",
            [+]             "Outputs.ekstest7awscdkawseksClusterResourceProviderOnEventHandlerServiceRoleD6AFD446Arn"
            [+]           ]
            [+]         }
            [+]       ]
            [ ]     }
            [ ]   }
            [ ] ]
```

First, I update the export stack which creates the cluster:

```sh
npx cdk diff eks-test7
```

Now, deploy the imported stack. This should update with no error.

```
npx cdk deploy imported-eks
```

Now, I am trying to add a namespace from the imported cluster:

```
    importedCluster.addManifest('nginx-namespace', {
      apiVersion: 'v1',
      kind: 'Namespace',
      metadata: {
        name: 'nginx',
      },
    });
```

And got this error:

```
Deployment failed: Error: The stack named imported-eks failed to deploy: UPDATE_ROLLBACK_COMPLETE: Received response status [FAILED] from custom resource. Message returned: Error: b'\nAn error occurred (AccessDenied) when calling the AssumeRole operation: User: arn:aws:sts::<deducted>:assumed-role/imported-eks-importedeksI-HandlerServiceRoleFCDC14-1XEHYK9KLIOQZ/imported-eks-importedeksImportedCl-Handler886CB40B-glJ3VujcU2RG is not authorized to perform: sts:AssumeRole on resource: arn:aws:iam::<deducted>:role/eks-test7-EksClusterCreationRole75AABE42-CMWB9G9AYK3T\nUnable to connect to the server: getting credentials: exec: executable aws failed with exit code 255\n'
```

So I modified both stacks as below:

```ts
export class EksStack extends Stack {
  readonly clusterName: string;
  readonly vpc: ec2.IVpc;
  readonly KubectlRoleArn: string;
  readonly kubectlProviderHandlerRoleArn: string;
  readonly crProviderServiceToken: string;

  constructor(scope: Construct, id: string, props?: StackProps) {
    super(scope, id, props);

    // create a new cluster
    const vpc = getOrCreateVpc(this);
    const kubectlLayer = new KubectlLayer(this, 'KubectlLayer');
    const cluster = new eks.Cluster(this, 'EksCluster', {
      vpc,
      version: eks.KubernetesVersion.V1_26,
      kubectlLayer,
      defaultCapacity: 0,
    });

    this.clusterName = cluster.clusterName;
    this.vpc = vpc;
    this.KubectlRoleArn = cluster.kubectlRole!.roleArn;

    const kubectlProvider = cluster.stack.node.tryFindChild('@aws-cdk--aws-eks.KubectlProvider') as eks.KubectlProvider;
    this.kubectlProviderHandlerRoleArn = kubectlProvider.handlerRole.roleArn;
    this.crProviderServiceToken = (kubectlProvider.node.tryFindChild('Provider') as cr.Provider).serviceToken;

    // EKS service role
    new CfnOutput(this, 'ClusterRole', { value: cluster.role.roleArn });
    // EKS cluster creation role
    new CfnOutput(this, 'ClusterAdminRole', { value: cluster.adminRole.roleArn });
    // Kubectl Role
    new CfnOutput(this, 'KubectlRole', { value: cluster.kubectlRole!.roleArn });
    // Kubectl Lambda Role
    // new CfnOutput(this, 'KubectlLambdaRole', { value: cluster.kubectlLambdaRole!.roleArn });
  }
}

export interface EksImportStackProps extends StackProps {
  readonly clusterName: string;
  readonly vpc: ec2.IVpc;
  readonly kubectlRoleArn: string;
  readonly kubectlProviderHandlerRoleArn: string;
  readonly crProviderServiceToken: string;
}

export class EksImportStack extends Stack {
  constructor(scope: Construct, id: string, props: EksImportStackProps) {
    super(scope, id, props);

    const vpc = props.vpc;

    const handlerRole = iam.Role.fromRoleArn(this, 'handlerRole', props.kubectlProviderHandlerRoleArn);
    const kubectlProvider = eks.KubectlProvider.fromKubectlProviderAttributes(this, 'KubectlProvider', {
      handlerRole,
      functionArn: props.crProviderServiceToken,
      kubectlRoleArn: props.kubectlRoleArn,
    })

    const importedCluster = eks.Cluster.fromClusterAttributes(this, 'ImportedCluster', {
      vpc,
      clusterName: props.clusterName,
      kubectlRoleArn: props.kubectlRoleArn,
      kubectlProvider,
    });

    importedCluster.addHelmChart('NginxIngress', {
      chart: 'nginx-ingress',
      repository: 'https://helm.nginx.com/stable',
      namespace: 'kube-system',
    });

    importedCluster.addManifest('nginx-namespace', {
      apiVersion: 'v1',
      kind: 'Namespace',
      metadata: {
        name: 'nginx',
      },
    });
  }
}
```

And in `app.ts`

```ts
const eksStack = new EksStack(app, 'eks-test7', { env })
new EksImportStack(app, 'imported-eks', { 
    env,
    clusterName: eksStack.clusterName,
    kubectlRoleArn: eksStack.KubectlRoleArn,
    vpc: eksStack.vpc,
    crProviderServiceToken: eksStack.crProviderServiceToken,
    kubectlProviderHandlerRoleArn: eksStack.kubectlProviderHandlerRoleArn,
});
```

Now, deploy the export stack again.

```
npx cdk diff eks-test7
npx cdk deploy eks-test7
```

deploy the import stack again.

```
npx cdk diff imported-eks
```

```
Stack imported-eks
Resources
[-] AWS::CloudFormation::Stack importedeksImportedCluster03434A9D-KubectlProvider.NestedStack/importedeksImportedCluster03434A9D-KubectlProvider.NestedStackResource importedeksImportedCluster03434A9DKubectlProviderNestedStackimportedeksImportedCluster03434A9DKubectlProviderNestedStackResource45EEF770 destroy
[+] Custom::AWSCDK-EKS-KubernetesResource ImportedCluster/manifest-nginx-namespace/Resource ImportedClustermanifestnginxnamespace5677B435 
[~] Custom::AWSCDK-EKS-HelmChart ImportedCluster/chart-NginxIngress/Resource ImportedClusterchartNginxIngress7F0F815E 
 └─ [~] ServiceToken
     ├─ [-] Removed: .Fn::GetAtt
     └─ [+] Added: .Fn::ImportValue
```

And got this error as reported

```
12:46:29 PM | UPDATE_FAILED        | Custom::AWSCDK-EKS-HelmChart          | ImportedClusterchartNginxIngress7F0F815E
Modifying service token is not allowed.
```


I am afraid this is probably something we can hardly avoid since 2.80 introduced a breaking change and in this case we probably can't in-place update the deployed resources which were deployed in 2.79.


If we check the synthesized cfn template, the `ServiceToken` prop has been modified from `Fn::GetAtt` to `Fn::ImportValue`

before:
```
  ImportedClustermanifestnginxnamespace5677B435:
    Type: Custom::AWSCDK-EKS-KubernetesResource
    Properties:
      ServiceToken:
        Fn::GetAtt:
          - importedeksImportedCluster03434A9DKubectlProviderNestedStackimportedeksImportedCluster03434A9DKubectlProviderNestedStackResource45EEF770
          - Outputs.importedeksimportedeksImportedCluster03434A9DKubectlProviderframeworkonEventB9EF1D26Arn
```


after:
```
 ImportedClustermanifestnginxnamespace5677B435:
    Type: Custom::AWSCDK-EKS-KubernetesResource
    Properties:
      ServiceToken:
        Fn::ImportValue: eks-test7:ExportsOutputFnGetAttawscdkawseksKubectlProviderNestedStackawscdkawseksKubectlProviderNestedStackResourceA7AEBA6BOutputsekstest7awscdkawseksKubectlProviderframeworkonEvent6A543037ArnCE3E3561
```

This is because you will need to use the KubectlProvider from the export stack instead of the one from the import stack and this causes service token change which is not allowed by cloudformation to update an existing custom resource.

I think we probably have two options here:

1. Remove the affected helmChart or manifest from CDK and add the resource back followed by re-deploy. This will cause service disruption as you are literally removing and adding a new manifest resource.

2. Add the handler service role from the nested stack of the import one to the trust policy of the creation role. This will allow the handler service role from the import stack to assume the creation role to update manifests.
Consider the full sample for this option below:

```ts
export class EksStack extends Stack {
  readonly clusterName: string;
  readonly vpc: ec2.IVpc;
  readonly KubectlRoleArn: string;
  readonly kubectlProviderHandlerRoleArn: string;
  readonly crProviderServiceToken: string;

  constructor(scope: Construct, id: string, props?: StackProps) {
    super(scope, id, props);

    // create a new cluster
    const vpc = getOrCreateVpc(this);
    const kubectlLayer = new KubectlLayer(this, 'KubectlLayer');
    const cluster = new eks.Cluster(this, 'EksCluster', {
      vpc,
      version: eks.KubernetesVersion.V1_26,
      kubectlLayer,
      defaultCapacity: 0,
    });

    this.clusterName = cluster.clusterName;
    this.vpc = vpc;
    this.KubectlRoleArn = cluster.kubectlRole!.roleArn;

    const kubectlProvider = cluster.stack.node.tryFindChild('@aws-cdk--aws-eks.KubectlProvider') as eks.KubectlProvider;
    this.kubectlProviderHandlerRoleArn = kubectlProvider.handlerRole.roleArn;
    this.crProviderServiceToken = (kubectlProvider.node.tryFindChild('Provider') as cr.Provider).serviceToken;

    cluster.adminRole.assumeRolePolicy?.addStatements(new iam.PolicyStatement({
      actions: ['sts:AssumeRole'],
      principals: [
        new iam.ArnPrincipal('arn:aws:iam::<deducted>:role/imported-eks-importedeksI-HandlerServiceRoleFCDC14-1XEHYK9KLIOQZ'),
      ],
    }))

    // EKS service role
    new CfnOutput(this, 'ClusterRole', { value: cluster.role.roleArn });
    // EKS cluster creation role
    new CfnOutput(this, 'ClusterAdminRole', { value: cluster.adminRole.roleArn });
    // Kubectl Role
    new CfnOutput(this, 'KubectlRole', { value: cluster.kubectlRole!.roleArn });
    // Kubectl Lambda Role
    // new CfnOutput(this, 'KubectlLambdaRole', { value: cluster.kubectlLambdaRole!.roleArn });
  }
}

export interface EksImportStackProps extends StackProps {
  readonly clusterName: string;
  readonly vpc: ec2.IVpc;
  readonly kubectlRoleArn: string;
  readonly kubectlProviderHandlerRoleArn: string;
  readonly crProviderServiceToken: string;
}

export class EksImportStack extends Stack {
  constructor(scope: Construct, id: string, props: EksImportStackProps) {
    super(scope, id, props);

    const vpc = props.vpc;

    // get the handler role from the export stack
    // const handlerRole = iam.Role.fromRoleArn(this, 'handlerRole', props.kubectlProviderHandlerRoleArn);
    const handlerRole = iam.Role.fromRoleArn(this, 'handlerRole', 'arn:aws:iam::<deducted>:role/imported-eks-importedeksI-HandlerServiceRoleFCDC14-1XEHYK9KLIOQZ');

    const kubectlProvider = eks.KubectlProvider.fromKubectlProviderAttributes(this, 'KubectlProvider', {
      handlerRole,
      // functionArn: props.crProviderServiceToken,
      functionArn: 'arn:aws:lambda:us-east-1:<deducted>:function:imported-eks-importedeksI-ProviderframeworkonEvent-HkkBfYrkq7BK',
      kubectlRoleArn: props.kubectlRoleArn,
    })

    const importedCluster = eks.Cluster.fromClusterAttributes(this, 'ImportedCluster', {
      vpc,
      clusterName: props.clusterName,
      kubectlRoleArn: props.kubectlRoleArn,
      kubectlProvider,
    });

    importedCluster.addHelmChart('NginxIngress', {
      chart: 'nginx-ingress',
      repository: 'https://helm.nginx.com/stable',
      namespace: 'kube-system',
    });

    importedCluster.addManifest('nginx-namespace', {
      apiVersion: 'v1',
      kind: 'Namespace',
      metadata: {
        name: 'nginx',
      },
    });
  }
}
```

This option is not decent as it hardcodes the arn in your code but it allows you to deploy with no error with the latest CDK version. The ultimate solution I believe would be the first option though but you have the option 2 as a workaround that allows you to upgrade your CDK app to the latest release and you can plan to redeploy using the option 1.

I guess this is probably the best workaround off the top of my head and I hope it helps. Let me know if you have any thoughts or ideas.

**Comment by dancmeyers** [comment]
I'm not sure where the response went? I got the email, but I was expecting to see it as a comment here as well, and I can't.

Is there any way to lock this down with tags? I was trying to work out how to do that, I was thinking to edit the `kubectlRole` policy to allow assumption if the principal doing the assuming had a specific tag, and then set that tag on the roles the lambdas in other stacks run as. Problem is I've mostly used tags for identification before, not access control, so I wasn't sure of the logic in IAM there, let alone translating it into CFn and/or CDK. Especially as there's role assumption to execute the imported stack lambda _anyway_, so the principal is an assumed-role, not a role (I think?)

**Comment by pahud** [comment]
Hi @dancmeyers 

I just deleted the previous response as I was still thinking if we can streamline the experience.

This is my workaround. 

Consider we create this with `2.79.0`

lib.ts

```ts
export class EksStack extends Stack {
  readonly clusterName: string;
  readonly vpc: ec2.IVpc;
  readonly KubectlRoleArn: string;
  readonly kubectlProviderHandlerRoleArn: string;
  readonly crProviderServiceToken: string;

  constructor(scope: Construct, id: string, props?: StackProps) {
    super(scope, id, props);

    // create a new cluster
    const vpc = getOrCreateVpc(this);
    const kubectlLayer = new KubectlLayer(this, 'KubectlLayer');
    const cluster = new eks.Cluster(this, 'EksCluster', {
      vpc,
      version: eks.KubernetesVersion.V1_26,
      kubectlLayer,
      defaultCapacity: 0,
    });

    this.clusterName = cluster.clusterName;
    this.vpc = vpc;
    this.KubectlRoleArn = cluster.kubectlRole!.roleArn;

    const kubectlProvider = cluster.stack.node.tryFindChild('@aws-cdk--aws-eks.KubectlProvider') as eks.KubectlProvider;
    this.kubectlProviderHandlerRoleArn = kubectlProvider.handlerRole.roleArn;
    this.crProviderServiceToken = (kubectlProvider.node.tryFindChild('Provider') as cr.Provider).serviceToken;

    // EKS service role
    new CfnOutput(this, 'ClusterRole', { value: cluster.role.roleArn });
    // EKS cluster creation role
    new CfnOutput(this, 'ClusterAdminRole', { value: cluster.adminRole.roleArn });
    // Kubectl Role
    new CfnOutput(this, 'KubectlRole', { value: cluster.kubectlRole!.roleArn });
  }
}

export interface EksImportStackProps extends StackProps {
  readonly clusterName: string;
  readonly vpc: ec2.IVpc;
  readonly kubectlRoleArn: string;
}

export class EksImportStack extends Stack {
  constructor(scope: Construct, id: string, props: EksImportStackProps) {
    super(scope, id, props);

    const vpc = props.vpc;

    const importedCluster = eks.Cluster.fromClusterAttributes(this, 'ImportedCluster', {
      vpc,
      clusterName: props.clusterName,
      kubectlRoleArn: props.kubectlRoleArn,
    });

    importedCluster.addManifest('nginx-namespace', {
      apiVersion: 'v1',
      kind: 'Namespace',
      metadata: {
        name: 'nginx',
      },
    });
  }
}
```

And the `app.ts`

```ts
const eksStack = new EksStack(app, 'eks-test', { env })
new EksImportStack(app, 'imported-eks', { 
    env,
    clusterName: eksStack.clusterName,
    kubectlRoleArn: eksStack.KubectlRoleArn,
    vpc: eksStack.vpc,
});
```

After deployment, we will have a nested stack as the KubectlProvider of the imported-cluster stack.

Now, upgrade to cdk 2.83.1 which is the latest version as of today.


re-deploy the main stack:

```
npx cdk diff eks-test
npx cdk deploy eks-test
```

update the imported-eks stack as below:

```ts
export class EksImportStack extends Stack {
  constructor(scope: Construct, id: string, props: EksImportStackProps) {
    super(scope, id, props);

    const vpc = props.vpc;

    const importedCluster = eks.Cluster.fromClusterAttributes(this, 'ImportedCluster', {
      vpc,
      clusterName: props.clusterName,
      kubectlRoleArn: props.kubectlRoleArn,
      // kubectlProvider,
    });

    importedCluster.addManifest('nginx-namespace', {
      apiVersion: 'v1',
      kind: 'Namespace',
      metadata: {
        name: 'nginx',
      },
    });

    // get the kubectlProvider from this stack
    const kubectlProvider = Stack.of(this).node.findChild(`${Names.nodeUniqueId(importedCluster.node)}-KubectlProvider`) as eks.KubectlProvider;
    // Print the kubectlProvider handler role arn. This arn should be added in the creation role trust policy.
    new CfnOutput(this, 'ImportedKubectlProviderHandlerRole', { value: kubectlProvider.handlerRole.roleArn })


  }
}
```

re-deploy it, you should get the `ImportedKubectlProviderHandlerRole` role ARN, which we should add into the trust policy of the creation role.

Now let's add this in the `eks-test` stack

```ts
    cluster.adminRole.assumeRolePolicy?.addStatements(new iam.PolicyStatement({
      actions: ['sts:AssumeRole'],
      principals: [
        new iam.ArnPrincipal(YOUR_ImportedKubectlProviderHandlerRole_ARN),
      ],
    }))
```

re-deploy it to add ImportedKubectlProviderHandlerRole into the trust policy of the creation role.

Now, let's add additional manifest we'd like to add in the imported cluster stack

For example:
```ts
importedCluster.addManifest('nginx-namespace3', {
      apiVersion: 'v1',
      kind: 'Namespace',
      metadata: {
        name: 'nginx3',
      },
    });
```

Now re-deploy the imported stack. It should work!


Please note in this sample we are not specifying `kubectlProvider` in the eks.Cluster.fromClusterAttributes(). We just add the KubectlProviderHandlerRole into the trust policy of the cluster creation role.

Let me know if it works for you.

**Comment by pahud** [comment]
Another option is to reuse the `KubectlProviderHandlerRole` in the import stack.

Check out this sample:


```ts
export class EksStack extends Stack {
  readonly clusterName: string;
  readonly vpc: ec2.IVpc;
  readonly KubectlRoleArn: string;
  readonly kubectlProviderHandlerRoleArn: string;

  constructor(scope: Construct, id: string, props?: StackProps) {
    super(scope, id, props);

    // create a new cluster
    const vpc = getOrCreateVpc(this);
    const kubectlLayer = new KubectlLayer(this, 'KubectlLayer');
    const cluster = new eks.Cluster(this, 'EksCluster', {
      vpc,
      version: eks.KubernetesVersion.V1_26,
      kubectlLayer,
      defaultCapacity: 0,
    });

    this.clusterName = cluster.clusterName;
    this.vpc = vpc;
    this.KubectlRoleArn = cluster.kubectlRole!.roleArn;

    const kubectlProvider = cluster.stack.node.tryFindChild('@aws-cdk--aws-eks.KubectlProvider') as eks.KubectlProvider;
    this.kubectlProviderHandlerRoleArn = kubectlProvider.handlerRole.roleArn;

    // EKS service role
    new CfnOutput(this, 'ClusterRole', { value: cluster.role.roleArn });
    // EKS cluster creation role
    new CfnOutput(this, 'ClusterAdminRole', { value: cluster.adminRole.roleArn });
    // Kubectl Role
    new CfnOutput(this, 'KubectlRole', { value: cluster.kubectlRole!.roleArn });
    // KubectlProvider Handler Role
    new CfnOutput(this, 'KubectlProviderHandlerRole', { value: kubectlProvider.handlerRole.roleArn });
  }
}

export interface EksImportStackProps extends StackProps {
  readonly clusterName: string;
  readonly vpc: ec2.IVpc;
  readonly kubectlRoleArn: string;
  readonly kubectlProviderHandlerRole: string;
}

export class EksImportStack extends Stack {
  constructor(scope: Construct, id: string, props: EksImportStackProps) {
    super(scope, id, props);

    const vpc = props.vpc;

    const importedCluster = eks.Cluster.fromClusterAttributes(this, 'ImportedCluster', {
      vpc,
      clusterName: props.clusterName,
      kubectlRoleArn: props.kubectlRoleArn,
      // kubectlProvider,
    });

    importedCluster.addManifest('nginx-namespace', {
      apiVersion: 'v1',
      kind: 'Namespace',
      metadata: {
        name: 'nginx',
      },
    });

    // get the kubectlProvider from this stack
    const kubectlProvider = Stack.of(this).node.findChild(`${Names.nodeUniqueId(importedCluster.node)}-KubectlProvider`) as eks.KubectlProvider;
    const kubectlHandler = kubectlProvider.node.findChild('Handler') as lambda.Function;
    (kubectlHandler.node.defaultChild as lambda.CfnFunction).addPropertyOverride('Role', props.kubectlProviderHandlerRole)

    importedCluster.addManifest('nginx-namespace4', {
      apiVersion: 'v1',
      kind: 'Namespace',
      metadata: {
        name: 'nginx4',
      },
    });
  }
}
```

This essentially override the KubectlProviderHandlerRole in the import stack with the one from the cluster stack. This works as well.

**Comment by dancmeyers** [comment]
I can't get this to work:

```
const kubectlProvider = Stack.of(this).node.findChild(`${Names.nodeUniqueId(importedCluster.node)}-KubectlProvider`) as eks.KubectlProvider;
```

It says there's no node with that ID. It can't even find a node with the ID `Names.nodeUniqueId(importedCluster.node)`. It _can_ find a node with the ID `ImportedCluster` (the plain string we/you set as the ID for the `importedCluster` object, but then it can't find `ImportedCluster-KubectlProvider`. I know there must _be_ a provider generated somewhere, because we manage to update manifests using it, but looking at the code I can't see where it is created. I only see that for 'direct' clusters...

**Comment by iliapolo** [comment]
Closing in favor of https://github.com/aws/aws-cdk/issues/25835 (which was re-opened)
