### ISSUE TITLE
Codepipeline: Only one of artifact bucket and cross region replication buckets can be specified!

### ISSUE THREAD

**Issue by makr11** [aws/aws-cdk#26164]
### Describe the feature

I couldn't find an explanation of this constraint. It would be extremely beneficial to be able to specify cross region replication bucket to be reused for all project pipelines which create cross region resources.

### Use Case

Large amount of pipelines created with CDK creates a near limit amount of S3 Buckets, I would like to specify cross region replication bucket alongside artifact bucket.

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### CDK version used

2.78.0

### Environment details (OS name and version, etc.)

Ubuntu 22.04

**Comment by pahud** [comment]
What error messages did you see? Can you share more details about that?

**Comment by makr11** [comment]
Hi pahud,

This is the full error log:

jsii.errors.JavaScriptError: 
  Error: Only one of artifactBucket and crossRegionReplicationBuckets can be specified!
      at new Pipeline (/tmp/jsii-kernel-upQH8B/node_modules/aws-cdk-lib/aws-codepipeline/lib/pipeline.js:1:3732)
      at Kernel._create (/tmp/tmpb55dxvbx/lib/program.js:9964:29)
      at Kernel.create (/tmp/tmpb55dxvbx/lib/program.js:9693:29)
      at KernelHost.processRequest (/tmp/tmpb55dxvbx/lib/program.js:11544:36)
      at KernelHost.run (/tmp/tmpb55dxvbx/lib/program.js:11504:22)
      at Immediate._onImmediate (/tmp/tmpb55dxvbx/lib/program.js:11505:46)
      at process.processImmediate (node:internal/timers:476:21)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/marin/responsum/fidelity-esg/app.py", line 9, in <module>
    FidelityPipeline(app, f"FidelityPipeline-{environment}", environment, env=cdk.Environment(account="467814946077", region="us-east-1"))
  File "/home/marin/responsum/fidelity-esg/.venv/lib/python3.9/site-packages/jsii/_runtime.py", line 112, in __call__
    inst = super().__call__(*args, **kwargs)
  File "/home/marin/responsum/fidelity-esg/infra/pipeline.py", line 40, in __init__
    pipeline = codepipeline.Pipeline(self, "BasePipeline",
  File "/home/marin/responsum/fidelity-esg/.venv/lib/python3.9/site-packages/jsii/_runtime.py", line 112, in __call__
    inst = super().__call__(*args, **kwargs)
  File "/home/marin/responsum/fidelity-esg/.venv/lib/python3.9/site-packages/aws_cdk/aws_codepipeline/__init__.py", line 5937, in __init__
    jsii.create(self.__class__, self, [scope, id, props])
  File "/home/marin/responsum/fidelity-esg/.venv/lib/python3.9/site-packages/jsii/_kernel/__init__.py", line 334, in create
    response = self.provider.create(
  File "/home/marin/responsum/fidelity-esg/.venv/lib/python3.9/site-packages/jsii/_kernel/providers/process.py", line 363, in create
    return self._process.send(request, CreateResponse)
  File "/home/marin/responsum/fidelity-esg/.venv/lib/python3.9/site-packages/jsii/_kernel/providers/process.py", line 340, in send
    raise RuntimeError(resp.error) from JavaScriptError(resp.stack)
RuntimeError: Only one of artifactBucket and crossRegionReplicationBuckets can be specified!

**Comment by makr11** [comment]
Hey, any update around this issue?

**Comment by pahud** [comment]
Hi @makr11 

For cross-region and/or cross-account issues with codepipeline, we have a p1 issue for tracking at https://github.com/aws/aws-cdk/issues/24051 and please report to that issue instead.

If you are looking for a working sample for your reference, please check this out.
https://github.com/aws/aws-cdk/issues/26557#issuecomment-1800968752

**Comment by kareldonk** [comment]
I am getting the same error. I would like to use a single bucket for artifacts and replication buckets because otherwise we reach the 100 bucket limit quickly. If a single bucket cannot be used, at least 2 buckets, one for artifacts and one for replication would also be good.

```
const artifactBucket = Bucket.fromBucketName(this, `ID`, 'existing_bucketname');

const pipeline = new CodePipeline(this, `ID`, {
    artifactBucket: artifactBucket,
    crossRegionReplicationBuckets: {
        'us-east-1': artifactBucket,
    },
   ...
};
```

Results in: `Error: Only one of artifactBucket and crossRegionReplicationBuckets can be specified!` when trying to do `cdk synth`.
