### ISSUE TITLE
aws-cdk/lib/index.js: No longer able to update our cdk stacks

### ISSUE THREAD

**Issue by nathanberry97** [aws/aws-cdk#26182]
### Describe the bug

Apologies if this is the incorrect place to post this issue but we are no longer able to update our stacks through the cdk. Whenever we run `npx cdk deploy` it results in the following error:

``` 
 ❌ Deployment failed: InvalidChangeSetStatus: An operation on this ChangeSet is currently in progress.  Please attempt this operation again later.
    at Request.extractError (/home/nathan/Documents/repos/data-reporting-platform/infrastructureDataLake/node_modules/aws-cdk/lib/index.js:292:46245)
    at Request.callListeners (/home/nathan/Documents/repos/data-reporting-platform/infrastructureDataLake/node_modules/aws-cdk/lib/index.js:292:89237)
    at Request.emit (/home/nathan/Documents/repos/data-reporting-platform/infrastructureDataLake/node_modules/aws-cdk/lib/index.js:292:88685)
    at Request.emit (/home/nathan/Documents/repos/data-reporting-platform/infrastructureDataLake/node_modules/aws-cdk/lib/index.js:292:195114)
    at Request.transition (/home/nathan/Documents/repos/data-reporting-platform/infrastructureDataLake/node_modules/aws-cdk/lib/index.js:292:188666)
    at AcceptorStateMachine.runTo (/home/nathan/Documents/repos/data-reporting-platform/infrastructureDataLake/node_modules/aws-cdk/lib/index.js:292:153538)
    at /home/nathan/Documents/repos/data-reporting-platform/infrastructureDataLake/node_modules/aws-cdk/lib/index.js:292:153868
    at Request.<anonymous> (/home/nathan/Documents/repos/data-reporting-platform/infrastructureDataLake/node_modules/aws-cdk/lib/index.js:292:188958)
    at Request.<anonymous> (/home/nathan/Documents/repos/data-reporting-platform/infrastructureDataLake/node_modules/aws-cdk/lib/index.js:292:195189)
    at Request.callListeners (/home/nathan/Documents/repos/data-reporting-platform/infrastructureDataLake/node_modules/aws-cdk/lib/index.js:292:89405) {
  code: 'InvalidChangeSetStatus',
  time: 2023-06-30T09:36:34.033Z,
  requestId: '04e78400-cbcf-44ec-afbd-c53074ac1006',
  statusCode: 400,
  retryable: false,
  retryDelay: 732.9997608486826
}
An operation on this ChangeSet is currently in progress.  Please attempt this operation again later.
```

Which would make sense if the stack wasn't showing as available in the AWS console, not sure if anyone has come across this issue before and are able to advise on how to resolve

### Expected Behavior

In terms of expected behavior when I run the following:

- `npx cdk deploy` 

It deploys the cdk without it throwing the following error when the stack is showing available:

- `An operation on this ChangeSet is currently in progress.  Please attempt this operation again later.`

### Current Behavior

When running `npx cdk deploy` the response message is the following:

``` 
 ❌ Deployment failed: InvalidChangeSetStatus: An operation on this ChangeSet is currently in progress.  Please attempt this operation again later.
    at Request.extractError (/home/nathan/Documents/repos/data-reporting-platform/infrastructureDataLake/node_modules/aws-cdk/lib/index.js:292:46245)
    at Request.callListeners (/home/nathan/Documents/repos/data-reporting-platform/infrastructureDataLake/node_modules/aws-cdk/lib/index.js:292:89237)
    at Request.emit (/home/nathan/Documents/repos/data-reporting-platform/infrastructureDataLake/node_modules/aws-cdk/lib/index.js:292:88685)
    at Request.emit (/home/nathan/Documents/repos/data-reporting-platform/infrastructureDataLake/node_modules/aws-cdk/lib/index.js:292:195114)
    at Request.transition (/home/nathan/Documents/repos/data-reporting-platform/infrastructureDataLake/node_modules/aws-cdk/lib/index.js:292:188666)
    at AcceptorStateMachine.runTo (/home/nathan/Documents/repos/data-reporting-platform/infrastructureDataLake/node_modules/aws-cdk/lib/index.js:292:153538)
    at /home/nathan/Documents/repos/data-reporting-platform/infrastructureDataLake/node_modules/aws-cdk/lib/index.js:292:153868
    at Request.<anonymous> (/home/nathan/Documents/repos/data-reporting-platform/infrastructureDataLake/node_modules/aws-cdk/lib/index.js:292:188958)
    at Request.<anonymous> (/home/nathan/Documents/repos/data-reporting-platform/infrastructureDataLake/node_modules/aws-cdk/lib/index.js:292:195189)
    at Request.callListeners (/home/nathan/Documents/repos/data-reporting-platform/infrastructureDataLake/node_modules/aws-cdk/lib/index.js:292:89405) {
  code: 'InvalidChangeSetStatus',
  time: 2023-06-30T09:36:34.033Z,
  requestId: '04e78400-cbcf-44ec-afbd-c53074ac1006',
  statusCode: 400,
  retryable: false,
  retryDelay: 732.9997608486826
}
An operation on this ChangeSet is currently in progress.  Please attempt this operation again later.
```

### Reproduction Steps

In terms of reproducing the error I'm not entirely sure what has happened as the issues started happening yesterday. 

I know this isn't useful so I apologies in advance but was hoping someone has come across something similar in the past.

### CDK CLI Version

2.81

### Node.js Version

20.3.1

### OS

ubuntu 

### Language

Typescript

**Comment by nathanberry97** [comment]
I have resolved this issue now.

If anyone comes across this in the future this issue is that for some reason within CloudFormation there was a Change Set to be Executed event though the CloudFormation was showing as UPDATE_COMPLETE 

Seems like there was an update at some point in the last day which was able to execute I would assume
