### ISSUE TITLE
(aws_cognito): (The static method cognito.UserPool.from_user_pool_arn does not work inside a Custom Construct)

### ISSUE THREAD

**Issue by siddhartha2202** [aws/aws-cdk#26299]
### Describe the bug

If you create a user pool as of cognito user pool arn from a ConstructsStack(Stack) everything works fine

```
cognito.UserPool.from_user_pool_arn(
            self,
            "LHUserPool",
            user_pool_arn=(
                "arn:aws:cognito-idp:us-west-2:*********"
                + ":userpool/*********"
            )
        )
```

But if you execute the previous instrucción inside a Custom Construct send the following error message:

@jsii/kernel.RuntimeError: @jsii/kernel.SerializationError: Passed to parameter scope of static method aws-cdk-lib.aws_cognito.UserPool.fromUserPoolArn: Unable to deserialize value as constructs.Construct

├── 🛑 Failing value is an object
  │      {
  │        id: 'LHUserPool',
  │        existing_user_pool_arn: 'arn:aws:cognito-idp:us-west-2:********:userpool/************'
  │      }
  ╰── 🔍 Failure reason(s):
      ╰─ Value does not have the "$jsii.byref" key

### Expected Behavior

It shouldn't send any error

### Current Behavior

Throws errors if trying to create a UserPool from an arn from a Custom Constructor

### Reproduction Steps

1. Write the following Custom Construct

```
from constructs import Construct
from attrs import define, field
from aws_cdk import (
    aws_cognito as cognito,
)


@define
class UserPoolBuilder(Construct):
    id: str = field()
    existing_user_pool_arn: str = field()

    def __init__(
        self, scope: Construct, id: str, existing_user_pool_arn: str = None
    ) -> None:
        super().__init__(scope, id)
        self.__attrs_init__(id, existing_user_pool_arn)

        if self.existing_user_pool_arn is not None:
            self.lh_user_pool = cognito.UserPool.from_user_pool_arn(
                scope=self, id=self.id, user_pool_arn=self.existing_user_pool_arn
            )
```

2.- Invoke this Construct from a Stack

```
from aws_cdk import (
    Stack,
    aws_cognito as cognito
)
from constructs import Construct
import lh_constructs.authorization_construct as auth_cons

class LhConstructsStack(Stack):
    def __init__(self, scope: Construct, id: str, **kwargs) -> None:
        super().__init__(scope, id, **kwargs)

        auth_cons.UserPoolBuilder(
            self,
            "UserPoolBuilder",
            existing_user_pool_arn=(
                "arn:aws:cognito-idp:us-west-2:********"
                + ":userpool/**********"
            )
        )

```

3.- The following error appears:

jsii.errors.JavaScriptError:
  @jsii/kernel.RuntimeError: @jsii/kernel.SerializationError: Passed to parameter scope of static method aws-cdk-lib.aws_cognito.UserPool.fromUserPoolArn: Unable to deserialize value as constructs.Construct
  ├── 🛑 Failing value is an object
  │      {
  │        id: 'UserPoolBuilder',
  │        existing_user_pool_arn: 'arn:aws:cognito-idp:us-west-2:*********:userpool/********'
  │      }
  ╰── 🔍 Failure reason(s):
      ╰─ Value does not have the "$jsii.byref" key
      at Kernel._ensureSync (/tmp/tmp21ftd_ny/lib/program.js:10369:27)
      at Kernel.sinvoke (/tmp/tmp21ftd_ny/lib/program.js:9790:34)
      at KernelHost.processRequest (/tmp/tmp21ftd_ny/lib/program.js:11544:36)
      at KernelHost.run (/tmp/tmp21ftd_ny/lib/program.js:11504:22)
      at Immediate._onImmediate (/tmp/tmp21ftd_ny/lib/program.js:11505:46)
      at process.processImmediate (node:internal/timers:476:21)

The above exception was the direct cause of the following exception:

```
Traceback (most recent call last):
  File "/workspace/latamhub/lh-constructs/app.py", line 10, in <module>
    LhConstructsStack(
  File "/workspace/latamhub/lh-constructs/.venv/lib/python3.9/site-packages/jsii/_runtime.py", line 112, in __call__
    inst = super().__call__(*args, **kwargs)
  File "/workspace/latamhub/lh-constructs/lh_constructs/lh_constructs_stack.py", line 35, in __init__
    auth_cons.UserPoolBuilder(
  File "/workspace/latamhub/lh-constructs/.venv/lib/python3.9/site-packages/jsii/_runtime.py", line 112, in __call__
    inst = super().__call__(*args, **kwargs)
  File "/workspace/latamhub/lh-constructs/lh_constructs/authorization_construct.py", line 23, in __init__
    cognito.UserPool.from_user_pool_arn(
  File "/workspace/latamhub/lh-constructs/.venv/lib/python3.9/site-packages/aws_cdk/aws_cognito/__init__.py", line 15599, in from_user_pool_arn
    return typing.cast(IUserPool, jsii.sinvoke(cls, "fromUserPoolArn", [scope, id, user_pool_arn]))
  File "/workspace/latamhub/lh-constructs/.venv/lib/python3.9/site-packages/jsii/_kernel/__init__.py", line 149, in wrapped
    return _recursize_dereference(kernel, fn(kernel, *args, **kwargs))
  File "/workspace/latamhub/lh-constructs/.venv/lib/python3.9/site-packages/jsii/_kernel/__init__.py", line 418, in sinvoke
    response = self.provider.sinvoke(
  File "/workspace/latamhub/lh-constructs/.venv/lib/python3.9/site-packages/jsii/_kernel/providers/process.py", line 381, in sinvoke
    return self._process.send(request, InvokeResponse)
  File "/workspace/latamhub/lh-constructs/.venv/lib/python3.9/site-packages/jsii/_kernel/providers/process.py", line 340, in send
    raise RuntimeError(resp.error) from JavaScriptError(resp.stack)
RuntimeError: @jsii/kernel.SerializationError: Passed to parameter scope of static method aws-cdk-lib.aws_cognito.UserPool.fromUserPoolArn: Unable to deserialize value as constructs.Construct
├── 🛑 Failing value is an object
│      {
│        id: 'UserPoolBuilder',
│        existing_user_pool_arn: 'arn:aws:cognito-idp:us-west-2:********:userpool/*********'
│      }
╰── 🔍 Failure reason(s):
    ╰─ Value does not have the "$jsii.byref" key

Subprocess exited with error 1
```

### CDK CLI Version

2.86.0 (build 1130fab)

### Node.js Version

Node.js v18.16.0

### OS

Linux

### Language

Python

### Language Version

Python 3.9.16

**Comment by siddhartha2202** [comment]
Hi,


Apparently using Custom Constructs are not compatible with the attrs library. If I remove this library it works perfectly
