### ISSUE TITLE
eks: ProxyAgent is not a constructor

### ISSUE THREAD

**Issue by trondhindenes** [aws/aws-cdk#26771]
### Describe the bug

The newest cdk library (2.92.0) produces this error. Downgrading to 2.90.0 solves it. We create clusters where we specify the `kubectl_layer` parameter. 

### Expected Behavior

it shouldn't fail

### Current Behavior

I'm getting this error:
```
11:02:05 AM | CREATE_FAILED        | Custom::AWSCDK-EKS-Cluster            | clusterC5B25D0D
Received response status [FAILED] from custom resource. Message returned: ProxyAgent is not a constructor
```

### Reproduction Steps

See descr

### CDK CLI Version

2.89.0

### Framework Version

2.92.0

### Node.js Version

v18.17.0

### OS

Ubuntu 

### Language

Python

### Language Version

Python 3.8

**Comment by pahud** [comment]
Can you share the smallest code snippet to reproduce this error?

**Comment by juweeks** [comment]
this is also breaking my eks deployment on v2.92. reverted back to v2.91 and seems to be fixed

cfn error:
```
Received response status [FAILED] from custom resource. Message returned: ProxyAgent is not a constructor

Logs: /aws/lambda/xxxxOnEventHandler42BEBAE0-jXvWcu93ZFF4

at Object.<anonymous> (/var/task/index.js:1:417)
at Module._compile (node:internal/modules/cjs/loader:1256:14)
at Module._extensions..js (node:internal/modules/cjs/loader:1310:10)
at Module.load (node:internal/modules/cjs/loader:1119:32)
at Module._load (node:internal/modules/cjs/loader:960:12)
at Module.require (node:internal/modules/cjs/loader:1143:19)
at require (node:internal/modules/cjs/helpers:110:18)
at _tryRequireFile (file:///var/runtime/index.mjs:912:37)
at _tryRequire (file:///var/runtime/index.mjs:962:25)
at _loadUserApp (file:///var/runtime/index.mjs:991:22) (RequestId: 09418d76-9c40-46da-9cfe-1d056ff8e2ad)


 ❌  xxxstack failed: Error: The stack named xxxstack failed to deploy: UPDATE_ROLLBACK_COMPLETE: Received response status [FAILED] from custom resource. Message returned: ProxyAgent is not a constructor

Logs: /aws/lambda/xxxxOnEventHandler42BEBAE0-jXvWcu93ZFF4

    at Object.<anonymous> (/var/task/index.js:1:417)
    at Module._compile (node:internal/modules/cjs/loader:1256:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1310:10)
    at Module.load (node:internal/modules/cjs/loader:1119:32)
    at Module._load (node:internal/modules/cjs/loader:960:12)
    at Module.require (node:internal/modules/cjs/loader:1143:19)
    at require (node:internal/modules/cjs/helpers:110:18)
    at _tryRequireFile (file:///var/runtime/index.mjs:912:37)
    at _tryRequire (file:///var/runtime/index.mjs:962:25)
    at _loadUserApp (file:///var/runtime/index.mjs:991:22) (RequestId: 09418d76-9c40-46da-9cfe-1d056ff8e2ad)
    at FullCloudFormationDeployment.monitorDeployment (/usr/local/lib/node_modules/aws-cdk/lib/index.js:426:10236)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Object.deployStack2 [as deployStack] (/usr/local/lib/node_modules/aws-cdk/lib/index.js:429:153380)
    at async /usr/local/lib/node_modules/aws-cdk/lib/index.js:429:137002

 ❌ Deployment failed: Error: The stack named ursatest-ursaminor-stack-eks-b failed to deploy: UPDATE_ROLLBACK_COMPLETE: Received response status [FAILED] from custom resource. Message returned: ProxyAgent is not a constructor

Logs: xxxxOnEventHandler42BEBAE0-jXvWcu93ZFF4

    at Object.<anonymous> (/var/task/index.js:1:417)
    at Module._compile (node:internal/modules/cjs/loader:1256:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1310:10)
    at Module.load (node:internal/modules/cjs/loader:1119:32)
    at Module._load (node:internal/modules/cjs/loader:960:12)
    at Module.require (node:internal/modules/cjs/loader:1143:19)
    at require (node:internal/modules/cjs/helpers:110:18)
    at _tryRequireFile (file:///var/runtime/index.mjs:912:37)
    at _tryRequire (file:///var/runtime/index.mjs:962:25)
    at _loadUserApp (file:///var/runtime/index.mjs:991:22) (RequestId: 09418d76-9c40-46da-9cfe-1d056ff8e2ad)
    at FullCloudFormationDeployment.monitorDeployment (/usr/local/lib/node_modules/aws-cdk/lib/index.js:426:10236)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Object.deployStack2 [as deployStack] (/usr/local/lib/node_modules/aws-cdk/lib/index.js:429:153380)
    at async /usr/local/lib/node_modules/aws-cdk/lib/index.js:429:137002

The stack named ursatest-ursaminor-stack-eks-b failed to deploy: UPDATE_ROLLBACK_COMPLETE: Received response status [FAILED] from custom resource. Message returned: ProxyAgent is not a constructor

Logs: xxxOnEventHandler42BEBAE0-jXvWcu93ZFF4

    at Object.<anonymous> (/var/task/index.js:1:417)
    at Module._compile (node:internal/modules/cjs/loader:1256:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1310:10)
    at Module.load (node:internal/modules/cjs/loader:1119:32)
    at Module._load (node:internal/modules/cjs/loader:960:12)
    at Module.require (node:internal/modules/cjs/loader:1143:19)
    at require (node:internal/modules/cjs/helpers:110:18)
    at _tryRequireFile (file:///var/runtime/index.mjs:912:37)
    at _tryRequire (file:///var/runtime/index.mjs:962:25)
    at _loadUserApp (file:///var/runtime/index.mjs:991:22) (RequestId: 09418d76-9c40-46da-9cfe-1d056ff8e2ad)

```

lambda logs from handler:
```
INIT_START Runtime Version: nodejs:18.v10	Runtime Version ARN: arn:aws:lambda:us-east-1::runtime:e3aaabf6b92ef8755eaae2f4bfdcb7eb8c4536a5e044900570a42bdba7b869d9

2023-08-16T15:42:53.629Z	undefined	ERROR	Uncaught Exception 	{
    "errorType": "TypeError",
    "errorMessage": "ProxyAgent is not a constructor",
    "stack": [
        "TypeError: ProxyAgent is not a constructor",
        "    at Object.<anonymous> (/var/task/index.js:1:417)",
        "    at Module._compile (node:internal/modules/cjs/loader:1256:14)",
        "    at Module._extensions..js (node:internal/modules/cjs/loader:1310:10)",
        "    at Module.load (node:internal/modules/cjs/loader:1119:32)",
        "    at Module._load (node:internal/modules/cjs/loader:960:12)",
        "    at Module.require (node:internal/modules/cjs/loader:1143:19)",
        "    at require (node:internal/modules/cjs/helpers:110:18)",
        "    at _tryRequireFile (file:///var/runtime/index.mjs:912:37)",
        "    at _tryRequire (file:///var/runtime/index.mjs:962:25)",
        "    at _loadUserApp (file:///var/runtime/index.mjs:991:22)"
    ]
}

Unknown application error occurred
Runtime.Unknown

```

**Comment by peterwoodworth** [comment]
Could you please share your CDK code which reproduces this?

**Comment by MrArnoldPalmer** [comment]
Pretty sure this was caused by https://github.com/aws/aws-cdk/pull/26722, reproduced with the eks cluster integ test. Just need to change to import to correctly use the 6.0 export. Working on a fix.
