### ISSUE TITLE
custom_resources: Provider Lambda function is missing lambda:GetFunctionConfiguration

### ISSUE THREAD

**Issue by erwaxler** [aws/aws-cdk#26838]
### Describe the bug

The [Landing Zone Accelerator](https://github.com/awslabs/landing-zone-accelerator-on-aws) solution leverages the custom_resources module to create service-linked roles via CDK custom resources. When this custom resource Lambda function is invoked several times in succession, users intermittently receive the following error:

```
Received response status [FAILED] from custom resource. Message returned: AccessDeniedException: Resource is not in the state functionActive
```

We believe this is the result of queuing incoming requests and the role attached to the `cdk.custom_resources.Provider` function is missing the permission: `lambda:GetFunctionConfiguration`

### Expected Behavior

Custom resource provider implements appropriate permissions and retries to execute successfully when invoked several times in succession. 

### Current Behavior

Transient failures:

```
Received response status [FAILED] from custom resource. Message returned: AccessDeniedException: Resource is not in the state functionActive
```

### Reproduction Steps

Deploy v1.4.3 of the Landing Zone Accelerator on AWS.

For a smaller sample that can be extracted without deploying the entire LZA solution, you may use this custom resource construct that is used by LZA to create the service-linked roles:

https://github.com/awslabs/landing-zone-accelerator-on-aws/blob/1614a01824c5a43f97fadfb8ec0c3627a0f343dd/source/packages/%40aws-accelerator/constructs/lib/aws-iam/service-linked-role.ts#L87

### Possible Solution

Add `lambda:GetFunctionConfiguration` permission to the provider Lambda function's IAM role.

### CDK CLI Version

2.79

### Node.js Version

16.20.1

### OS

Amazon Linux

### Language

Typescript

**Comment by erwaxler** [comment]
@pahud Agreed on it likely being related to #24358, I'll work on a smaller snippet to reproduce the error. The error has been seen in at least us-east-1 and ap-southeast-2, but we've heard reports from 5+ customers so I believe the error to be region-agnostic.  I'll work on a smaller snippet to reproduce the behavior more predictably.

**Comment by pahud** [comment]
@erwaxler 

Are you able to see how many custom resources of this will be created in your LZA deployment?

https://github.com/awslabs/landing-zone-accelerator-on-aws/blob/1614a01824c5a43f97fadfb8ec0c3627a0f343dd/source/packages/%40aws-accelerator/constructs/lib/aws-iam/service-linked-role.ts#L87

**Comment by erwaxler** [comment]
@pahud Still working on a smaller reproducible snippet. LZA creates 6 individual custom resources to create the service-linked roles.

**Comment by aaronbrighton** [comment]
I've added some more details below, please advise whether it's still necessary to provide a reproducible code-snippet.

This issue is exacerbated by logic that may run these custom resources on every pipeline run, for instance: https://github.com/awslabs/landing-zone-accelerator-on-aws/issues/237

The following line and the surrounding retry logic requires the as mentioned `lambda:GetFunctionConfiguration` permission to function: https://github.com/aws/aws-cdk/blob/c695b6004219426cf0e67cbb92d916a394ddd594/packages/aws-cdk-lib/custom-resources/lib/provider-framework/runtime/outbound.ts#L66C15-L66C15

However only invokeFunction is granted on the onEventHandler Lambda function: https://github.com/aws/aws-cdk/blob/c695b6004219426cf0e67cbb92d916a394ddd594/packages/aws-cdk-lib/custom-resources/lib/provider-framework/provider.ts#L233

I believe the above `provider.ts` likely needs a `fn.addToRolePolicy` added after the above line granting "lambda:GetFunctionConfiguration" on `this.onEventHandler.functionArn`.

**Comment by yubingjiaocn** [comment]
Encountered same problem with EKS Blueprint, which is using `kubectlProvider` created from https://github.com/aws/aws-cdk/blob/v2.96.0/packages/aws-cdk-lib/aws-eks/lib/kubectl-provider.ts#L144. 

The error message on Cloudformation said:

`
Custom::AWSCDK-EKS-KubernetesResource   EKSStackAwsAuthmanifest75D20040    
CREATE_FAILED   Received response status [FAILED] from custom resource. Message returned: TimeoutError: {"state":"TIMEOUT","reason":"Waiter has timed out"} at checkExceptions ... 
`

Also found the following error message in CloudTrail: 

`
User: arn:aws:sts::[redacted]:assumed-role/EKSStack-awscdka-ProviderframeworkonEventS-duAmMCwNZO6z/EKSStack-awscdka-ProviderframeworkonEvent-4NeK4zj7Z6ab is not authorized to perform: lambda:GetFunctionConfiguration on resource: arn:aws:lambda:[redacted]:[redacted]:function:EKSStack-awscdkawseksKube-Handler886CB40B-3fOpwrZnomNI because no identity-based policy allows the lambda:GetFunctionConfiguration action
`

After added `lambda:GetFunctionConfiguration` permision to IAM role of the function, the template can be deployed.

**Comment by ejt4x** [comment]
The waiter call changed in c3a4b7b899289b04fffb6d65b3289cc5526d5397 from `waitUntilFunctionActive` to `waitUntilFunctionActiveV2`. This changed the required IAM permission from `lambda:GetFunctionConfiguration` to `lambda:GetFunction`.

[c3a4b7b899289b04fffb6d65b3289cc5526d5397](https://github.com/aws/aws-cdk/blob/c3a4b7b899289b04fffb6d65b3289cc5526d5397/packages/aws-cdk-lib/custom-resources/lib/provider-framework/runtime/outbound.ts#L66C11-L66C36)

**Comment by markhankins** [comment]
@ejt4x It looks like both PR's failed to merge based on missing tests?

https://github.com/aws/aws-cdk/pull/27204
https://github.com/aws/aws-cdk/pull/27524

I couldn't see a passing PR for this?

**Comment by ejt4x** [comment]
@markhankins Yes, it looks like the original PR was abandoned. I am not prepared to create one anytime soon. 

I was just commenting to inform any would-be submitters or reviewers that the API call and therefore required fix have changed somewhat since the original title and description of this issue were written.

**Comment by blinkdaffer** [comment]
any solution for this

**Comment by pahud** [comment]
probably related to https://github.com/aws/aws-cdk/issues/24358

@blinkdaffer @ejt4x @markhankins 

Can you tell me which region(s) are you seeing this error?

Are you able to provide a very tiny CDK app that we can deploy in that region and reproduce this error?

**Comment by ejt4x** [comment]
@pahud Here's my simplest way of producing this error.

```ts
const thisLambdaDoesNotExist = Function.fromFunctionName(this, 'NonExistentLambda', 'fakelambda');

const provider = new Provider(this, 'Provider', {
  onEventHandler: thisLambdaDoesNotExist,
});

new CustomResource(this, 'Resource1', { serviceToken: provider.serviceToken });
```

The actual exception (throttling, function does not exist, whatever) is swallowed by the try/except block, leaving the following error on the CFN event log:
```
Resource1	
CREATE_FAILED
Received response status [FAILED] from custom resource. Message returned: TimeoutError: {"state":"TIMEOUT","reason":"Waiter has timed out"} at checkExceptions (/var/runtime/node_modules/@aws-sdk/node_modules/@smithy/util-waiter/dist-cjs/index.js:59:26) at waitUntilFunctionActiveV2 (/var/runtime/node_modules/@aws-sdk/client-lambda/dist-cjs/index.js:5933:49) at process.processTicksAndRejections (node:internal/process/task_queues:95:5) at async defaultInvokeFunction (/var/task/outbound.js:1:875) at async invokeUserFunction (/var/task/framework.js:1:2192) at async onEvent (/var/task/framework.js:1:369) at async Runtime.handler (/var/task/cfn-response.js:1:1573) 
```

If we go digging in CloudTrail, we find this IAM error

```
   "errorMessage": "User: arn:aws:sts::[redacted]-ProviderframeworkonEvent-jKCdLDqBfAP0 is not authorized to perform: lambda:GetFunction on resource: arn:aws:lambda:us-west-2:redacted:function:fakelambda because no identity-based policy allows the lambda:GetFunction action",
```

All these errors mask the actual issue - the user lambda invocation failed due to throttling non-existence, or some other reason. The missing IAM permission prevents this from being discovered by the user

**Comment by pahud** [comment]
Yes when deploying

```ts
export class ProviderStack extends Stack {
  constructor(scope: Construct, id: string, props?: StackProps) {
    super(scope, id, props);

    // Import a non-existent Lambda function
    const thisLambdaDoesNotExist = lambda.Function.fromFunctionName(this, 'NonExistentLambda', 'fakelambda');

    // Create a custom resource provider using the non-existent Lambda
    const provider = new cr.Provider(this, 'Provider', {
      onEventHandler: thisLambdaDoesNotExist,
    });

    // Create a custom resource using the provider
    new CustomResource(this, 'Resource1', { 
      serviceToken: provider.serviceToken 
    });
  }
}
```

In 2.173.0 we'll get `Waiter has timed out` error.

```
Failed resources:
DummyStack2 | 11:39:53 AM | CREATE_FAILED        | AWS::CloudFormation::CustomResource | Resource1/Default (Resource1) Received response status [FAILED] from custom resource. Message returned: TimeoutError: {"state":"TIMEOUT","reason":"Waiter has timed out"}
    at checkExceptions (/var/runtime/node_modules/@aws-sdk/node_modules/@smithy/util-waiter/dist-cjs/index.js:59:26)
    at waitUntilFunctionActiveV2 (/var/runtime/node_modules/@aws-sdk/client-lambda/dist-cjs/index.js:5820:49)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async defaultInvokeFunction (/var/task/outbound.js:1:1024)
    at async invokeUserFunction (/var/task/framework.js:1:2794)
    at async onEvent (/var/task/framework.js:1:369)
    at async Runtime.handler (/var/task/cfn-response.js:1:1837) (RequestId: 1645d85b-b74b-4638-9ea3-c0e68419e42a)
❌  DummyStack2 failed: Error: The stack named DummyStack2 failed creation, it may need to be manually deleted from the AWS console: ROLLBACK_COMPLETE: Received response status [FAILED] from custom resource. Message returned: TimeoutError: {"state":"TIMEOUT","reason":"Waiter has timed out"}
    at checkExceptions (/var/runtime/node_modules/@aws-sdk/node_modules/@smithy/util-waiter/dist-cjs/index.js:59:26)
    at waitUntilFunctionActiveV2 (/var/runtime/node_modules/@aws-sdk/client-lambda/dist-cjs/index.js:5820:49)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async defaultInvokeFunction (/var/task/outbound.js:1:1024)
    at async invokeUserFunction (/var/task/framework.js:1:2794)
    at async onEvent (/var/task/framework.js:1:369)
    at async Runtime.handler (/var/task/cfn-response.js:1:1837) (RequestId: 1645d85b-b74b-4638-9ea3-c0e68419e42a)
```

Looking at the provider framework log:


```

2025-01-06T16:39:52.381Z	4cc87c28-3877-4423-a03f-a3ae6eef055e	INFO	[provider-framework] CREATE failed, responding with a marker physical resource id so that the subsequent DELETE will be ignored
--
2025-01-06T16:39:52.388Z	4cc87c28-3877-4423-a03f-a3ae6eef055e	INFO	[provider-framework] submit response to cloudformation https://cloudformation-custom-resource-response-useast1.s3.amazonaws.com//arn%3Aaws%3Acloudformation%3Aus-east-1%3A903779448426%3Astack/DummyStack2/1a3311b0-cc4c-11ef-8680-0e501d1dc595%7CResource1%7C1645d85b-b74b-4638-9ea3-c0e68419e42a?*** {     "Status": "FAILED",     "Reason": "TimeoutError: {\"state\":\"TIMEOUT\",\"reason\":\"Waiter has timed out\"}\n    at checkExceptions (/var/runtime/node_modules/@aws-sdk/node_modules/@smithy/util-waiter/dist-cjs/index.js:59:26)\n    at waitUntilFunctionActiveV2 (/var/runtime/node_modules/@aws-sdk/client-lambda/dist-cjs/index.js:5820:49)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async defaultInvokeFunction (/var/task/outbound.js:1:1024)\n    at async invokeUserFunction (/var/task/framework.js:1:2794)\n    at async onEvent (/var/task/framework.js:1:369)\n    at async Runtime.handler (/var/task/cfn-response.js:1:1837)",     "StackId": "arn:aws:cloudformation:us-east-1:903779448426:stack/DummyStack2/1a3311b0-cc4c-11ef-8680-0e501d1dc595",     "RequestId": "1645d85b-b74b-4638-9ea3-c0e68419e42a",     "PhysicalResourceId": "AWSCDK::CustomResourceProviderFramework::CREATE_FAILED",     "LogicalResourceId": "Resource1" }
```

affected code:

https://github.com/aws/aws-cdk/blob/26b361de357a3b83c59dc4931d4797328d220534/packages/aws-cdk-lib/custom-resources/lib/provider-framework/runtime/outbound.ts#L73

My take:
1. custom resource would not check if the provided lambda ARN exists and would simply [invoke and wait the state](https://github.com/aws/aws-cdk/blob/26b361de357a3b83c59dc4931d4797328d220534/packages/aws-cdk-lib/custom-resources/lib/provider-framework/runtime/outbound.ts#L65-L73), which seems would always timeout if the function actually does not exist.
2. We probably should improve the way we invoke a function with provided ARN.

Making this a p1.

**Comment by pahud** [comment]
internal: V1631223300

**Comment by moelasmar** [comment]
reopened this issue since the fixing PR https://github.com/aws/aws-cdk/pull/32904 caused issues in the release process because of its size seems causing timeouts while calculating `git diff`, and I had to revert it to unblock the release. We will revisit this issue later
