### ISSUE TITLE
CDK Deploy: Deploy with hotswap now failing

### ISSUE THREAD

**Issue by jackkitley** [aws/aws-cdk#26871]
### Describe the bug

When using the following command:

`cdk deploy dealeros-uat-web --hotswap -c config=uat --require-approval=never`

`--hotswap` is the culprit here. Without it, deploy can happen.

It was working fine this morning and nothing has changed with the way we deploy.

The following error when rolling out to ECS:

```
failed: ClientException: Log driver awslogs requires options: awslogs-region, awslogs-group
    at Request.extractError (/usr/local/lib/node_modules/aws-cdk/lib/index.js:338:33170)
    at Request.callListeners (/usr/local/lib/node_modules/aws-cdk/lib/index.js:338:89985)
    at Request.emit (/usr/local/lib/node_modules/aws-cdk/lib/index.js:338:89433)
    at Request.emit (/usr/local/lib/node_modules/aws-cdk/lib/index.js:338:196191)
    at Request.transition (/usr/local/lib/node_modules/aws-cdk/lib/index.js:338:189743)
    at AcceptorStateMachine.runTo (/usr/local/lib/node_modules/aws-cdk/lib/index.js:338:154615)
    at /usr/local/lib/node_modules/aws-cdk/lib/index.js:338:154945
    at Request.<anonymous> (/usr/local/lib/node_modules/aws-cdk/lib/index.js:338:190035)
    at Request.<anonymous> (/usr/local/lib/node_modules/aws-cdk/lib/index.js:338:196266)
    at Request.callListeners (/usr/local/lib/node_modules/aws-cdk/lib/index.js:338:90153) {
  code: 'ClientException',
  '[__type]': 'See error.__type for details.',
  time: 2023-08-24T16:44:22.046Z,
  requestId: 'fb2f5f67-5f28-4a0e-8f36-8ecd89cf01dd',
  statusCode: 400,
  retryable: false,
  retryDelay: 39.6604227853812
```

### Expected Behavior

--hotswap is acting up here.

I expect the code to deploy to ECS without issues. 

### Current Behavior

Failing the build process with --hotswap in the cdk deploy.

giving error:

```
failed: ClientException: Log driver awslogs requires options: awslogs-region, awslogs-group
    at Request.extractError (/usr/local/lib/node_modules/aws-cdk/lib/index.js:338:33170)
    at Request.callListeners (/usr/local/lib/node_modules/aws-cdk/lib/index.js:338:89985)
    at Request.emit (/usr/local/lib/node_modules/aws-cdk/lib/index.js:338:89433)
    at Request.emit (/usr/local/lib/node_modules/aws-cdk/lib/index.js:338:196191)
    at Request.transition (/usr/local/lib/node_modules/aws-cdk/lib/index.js:338:189743)
    at AcceptorStateMachine.runTo (/usr/local/lib/node_modules/aws-cdk/lib/index.js:338:154615)
    at /usr/local/lib/node_modules/aws-cdk/lib/index.js:338:154945
    at Request.<anonymous> (/usr/local/lib/node_modules/aws-cdk/lib/index.js:338:190035)
    at Request.<anonymous> (/usr/local/lib/node_modules/aws-cdk/lib/index.js:338:196266)
    at Request.callListeners (/usr/local/lib/node_modules/aws-cdk/lib/index.js:338:90153) {
  code: 'ClientException',
  '[__type]': 'See error.__type for details.',
  time: 2023-08-24T16:44:22.046Z,
  requestId: 'fb2f5f67-5f28-4a0e-8f36-8ecd89cf01dd',
  statusCode: 400,
  retryable: false,
  retryDelay: 39.6604227853812
}
```

### Reproduction Steps

CDK version: 
2.93.0 (build 724bd01)

Run this for a deploy:

`cdk deploy dealeros-uat-web -c config=uat --require-approval=never`

### Possible Solution

This was a recent change. im not sure.

### CDK CLI Version

2.93.0 (build 724bd01)

### Node.js Version

16

### OS

ubuntu

### Language

Typescript

**Comment by tmokmss** [comment]
This should be related with #26404. I'm looking at it 👀

**Comment by peterwoodworth** [comment]
Thanks for being on top of it @tmokmss

**Comment by tmokmss** [comment]
@jackkitley I just submitted a pr to fix it, sorry for inconvenience! In the mean time you can use cdk 2.92.0 🙏
