### ISSUE TITLE
aws-cdk-lib/aws-codepipeline-actions: TextDecoder is not defined (2.87 -> 2.93)

### ISSUE THREAD

**Issue by jedkass** [aws/aws-cdk#26913]
### Describe the bug

After upgrading `aws-cdk-lib` from `2.87` to `2.93`, when trying to `import { LambdaInvokeAction } from 'aws-cdk-lib/aws-codepipeline-actions';`, I get the following exception/stack trace:

```
ReferenceError: TextDecoder is not defined

      2 | Object.defineProperty(exports, "__esModule", { value: true });
      3 | exports.CodePipelineUtils = void 0;
    > 4 | const aws_codepipeline_actions_1 = require("aws-cdk-lib/aws-codepipeline-actions");
        |                                    ^
      5 | const codePipeline_1 = require("../constants/codePipeline");
      6 | const aws_lambda_1 = require("aws-cdk-lib/aws-lambda");
      7 | const aws_iam_1 = require("aws-cdk-lib/aws-iam");

      at Object.<anonymous> (../node_modules/aws-cdk-lib/custom-resources/lib/aws-custom-resource/runtime/shared.js:1:340)
      at Object.<anonymous> (../node_modules/aws-cdk-lib/custom-resources/lib/aws-custom-resource/runtime/index.js:1:171)
      at Object.<anonymous> (../node_modules/aws-cdk-lib/custom-resources/lib/aws-custom-resource/aws-custom-resource.js:1:434)
      at Object.<anonymous> (../node_modules/aws-cdk-lib/custom-resources/lib/aws-custom-resource/index.js:1:649)
      at Object.<anonymous> (../node_modules/aws-cdk-lib/custom-resources/lib/index.js:1:649)
      at Object.<anonymous> (../node_modules/aws-cdk-lib/custom-resources/index.js:1:649)
      at Object.<anonymous> (../node_modules/aws-cdk-lib/aws-events-targets/lib/log-group-resource-policy.js:1:198)
      at Object.<anonymous> (../node_modules/aws-cdk-lib/aws-events-targets/lib/log-group.js:1:304)
      at Object.<anonymous> (../node_modules/aws-cdk-lib/aws-events-targets/lib/index.js:1:1189)
      at Object.<anonymous> (../node_modules/aws-cdk-lib/aws-events-targets/index.js:1:649)
      at Object.<anonymous> (../node_modules/aws-cdk-lib/aws-codepipeline-actions/lib/codecommit/source-action.js:1:336)
      at Object.<anonymous> (../node_modules/aws-cdk-lib/aws-codepipeline-actions/lib/codebuild/build-action.js:1:492)
      at Object.<anonymous> (../node_modules/aws-cdk-lib/aws-codepipeline-actions/lib/index.js:1:887)
      at Object.<anonymous> (../node_modules/aws-cdk-lib/aws-codepipeline-actions/index.js:1:649)
      at Object.<anonymous> (../packages/infrakit/dist/utils/codePipelineUtils.js:4:36)
      at Object.<anonymous> (../packages/infrakit/dist/index.js:50:27)
      at Object.<anonymous> (worker/utils/WorkerIdleStatusEmitter.ts:1:1)
      at Object.<anonymous> (worker/process.ts:26:1)
```

### Expected Behavior

I think this should import with no issues, but not sure if I need to take any additional action on my end as part of this upgrade given the introduction of `TextDecoder`.

### Current Behavior

See above.

### Reproduction Steps

I honestly don't have a trivial setup here where I can easily extract an SSCCE so this ticket might die. Apologies in advance. I can give an overview of my setup and maybe that + the stack trace can provide enough of a hint for your expertise.

* I have a yarn workspace with a package that I use for:
  * CDK utility methods that I've reused across different CDK packages
  * Constants I use in both CDK packages _as well as_ service packages (e.g. metric names to emit and then create a CW alarm for). 
* This problem arises in the _service_ package that imports this shared package — specifically on the line I referenced above: `import { LambdaInvokeAction } from 'aws-cdk-lib/aws-codepipeline-actions';`

### Possible Solution

I've seen old `TextDecoder` issues on the internet related to Node versions, but I'm on a pretty recent version of Node (18.15.0). [This change](https://github.com/aws/aws-cdk/commit/4d3ec71e33847e80fe99da073ca0ece472e71111) seemed to introduce the [line in question](https://github.com/aws/aws-cdk/blame/main/packages/aws-cdk-lib/custom-resources/lib/aws-custom-resource/runtime/shared.ts#L11), so I'm guessing it's the source of the issue.

### CDK CLI Version

2.93.0

### Node.js Version

18.15.0

### OS

alpine3.17 (node:18.15.0-alpine3.17 docker image)

### Language

Typescript

### Language Version

TypeScript 5.1.6

**Comment by khushail** [comment]
Hi @jedkass , thanks for reaching out.

I tried reproducing the issue with statement `import { LambdaInvokeAction } from 'aws-cdk-lib/aws-codepipeline-actions'`,updating from 2.87 to 2.93 but there was no issue. I doubt its anything to do with CDK.

It seems more like a Node issue, could you tell if you are able to use TextDecoder` in your app?

**Comment by oleksii-donoha** [comment]
I'm seeing the same issue in my jest unit tests. 2.92.0 is fine, it came with 2.93.0.

```
● Test suite failed to run

[2023-08-29T10:13:24.807Z] 

[2023-08-29T10:13:24.807Z]     ReferenceError: TextDecoder is not defined

[2023-08-29T10:13:24.807Z] 

[2023-08-29T10:13:24.807Z]     > 1 | import * as cdk from 'aws-cdk-lib'

[2023-08-29T10:13:24.807Z]         | ^

[2023-08-29T10:13:24.807Z]       2 | import * as ec2 from 'aws-cdk-lib/aws-ec2'

[2023-08-29T10:13:24.807Z]       3 | import * as iam from 'aws-cdk-lib/aws-iam'

[2023-08-29T10:13:24.807Z]       4 | import '../../src/testing/testing'

[2023-08-29T10:13:24.807Z] 

[2023-08-29T10:13:24.807Z]       at Object.<anonymous> (node_modules/aws-cdk-lib/custom-resources/lib/aws-custom-resource/runtime/shared.js:1:402)

[2023-08-29T10:13:24.807Z]       at Object.<anonymous> (node_modules/aws-cdk-lib/custom-resources/lib/aws-custom-resource/runtime/index.js:1:233)

[2023-08-29T10:13:24.807Z]       at Object.<anonymous> (node_modules/aws-cdk-lib/custom-resources/lib/aws-custom-resource/aws-custom-resource.js:1:496)

[2023-08-29T10:13:24.807Z]       at Object.<anonymous> (node_modules/aws-cdk-lib/custom-resources/lib/aws-custom-resource/index.js:1:711)

[2023-08-29T10:13:24.807Z]       at Object.<anonymous> (node_modules/aws-cdk-lib/custom-resources/lib/index.js:1:711)

[2023-08-29T10:13:24.807Z]       at Object.<anonymous> (node_modules/aws-cdk-lib/custom-resources/index.js:1:711)

[2023-08-29T10:13:24.808Z]       at Object.<anonymous> (node_modules/aws-cdk-lib/aws-dynamodb/lib/replica-provider.js:1:312)

[2023-08-29T10:13:24.808Z]       at Object.<anonymous> (node_modules/aws-cdk-lib/aws-dynamodb/lib/table.js:1:658)

[2023-08-29T10:13:24.808Z]       at Object.<anonymous> (node_modules/aws-cdk-lib/aws-dynamodb/lib/index.js:1:765)

[2023-08-29T10:13:24.808Z]       at Object.<anonymous> (node_modules/aws-cdk-lib/aws-dynamodb/index.js:1:711)

[2023-08-29T10:13:24.808Z]       at Object.<anonymous> (node_modules/aws-cdk-lib/aws-backup/lib/backupable-resources-collector.js:1:217)

[2023-08-29T10:13:24.808Z]       at Object.<anonymous> (node_modules/aws-cdk-lib/aws-backup/lib/selection.js:1:386)

[2023-08-29T10:13:24.808Z]       at Object.<anonymous> (node_modules/aws-cdk-lib/aws-backup/lib/plan.js:1:385)

[2023-08-29T10:13:24.808Z]       at Object.<anonymous> (node_modules/aws-cdk-lib/aws-backup/lib/index.js:1:752)

[2023-08-29T10:13:24.808Z]       at Object.<anonymous> (node_modules/aws-cdk-lib/aws-backup/index.js:1:711)

[2023-08-29T10:13:24.808Z]       at Object.<anonymous> (node_modules/aws-cdk-lib/index.js:1:8197)

[2023-08-29T10:13:24.808Z]       at Object.<anonymous> (__tests__/compute/ec2.test.ts:1:1)
```

**Comment by khushail** [comment]
@jedkass ,it would be helpful if you could share the code snippet to repro this issue.

**Comment by rehos** [comment]
@oleksii-donoha in ran into the same issue with jest unit tests. I was using an older version of jest and ts-jest and after updating jest to 29.6.4 and ts-jest to 29.1.1 the reference error disappeared. Hope this helps.

**Comment by oleksii-donoha** [comment]
It does seem like updating to jest 29 solves the issue

**Comment by jedkass** [comment]
Ahh I didn't realize I didn't post this in the original issue description, but this exception was also cropping up for me in jest unit tests! Sounds like others have resolved this by updating that. Thanks @rehos and @oleksii-donoha!

**Comment by stefanfreitag** [comment]
Today I was also seeing this issue in a GitHub Action for one of my CDK projects.

```
ReferenceError: TextDecoder is not defined

    > 1 | import { App } from 'aws-cdk-lib';
        | ^
      2 | import { MyStack } from '../src/main';
      3 |
      4 | test('Snapshot', () => {

      at Object.<anonymous> (node_modules/aws-cdk-lib/custom-resources/lib/aws-custom-resource/runtime/shared.js:1:402)
      at Object.<anonymous> (node_modules/aws-cdk-lib/custom-resources/lib/aws-custom-resource/runtime/index.js:1:233)
      at Object.<anonymous> (node_modules/aws-cdk-lib/custom-resources/lib/aws-custom-resource/aws-custom-resource.js:1:496)
      at Object.<anonymous> (node_modules/aws-cdk-lib/custom-resources/lib/aws-custom-resource/index.js:1:711)
      at Object.<anonymous> (node_modules/aws-cdk-lib/custom-resources/lib/index.js:1:711)
      at Object.<anonymous> (node_modules/aws-cdk-lib/custom-resources/index.js:1:711)
      at Object.<anonymous> (node_modules/aws-cdk-lib/aws-dynamodb/lib/replica-provider.js:1:312)
----------|---------|----------|---------|---------|-------------------
File      | % Stmts | % Branch | % Funcs | % Lines | Uncovered Line #s 
      at Object.<anonymous> (node_modules/aws-cdk-lib/aws-dynamodb/lib/table.js:1:658)
      at Object.<anonymous> (node_modules/aws-cdk-lib/aws-dynamodb/lib/index.js:1:765)
      at Object.<anonymous> (node_modules/aws-cdk-lib/aws-dynamodb/index.js:1:711)
      at Object.<anonymous> (node_modules/aws-cdk-lib/aws-backup/lib/backupable-resources-collector.js:1:2[17](https://github.com/stefanfreitag/csv-to-heartbeat-yml/actions/runs/6043832323/job/16401510522#step:4:18))
      at Object.<anonymous> (node_modules/aws-cdk-lib/aws-backup/lib/selection.js:1:386)
      at Object.<anonymous> (node_modules/aws-cdk-lib/aws-backup/lib/plan.js:1:385)
      at Object.<anonymous> (node_modules/aws-cdk-lib/aws-backup/lib/index.js:1:752)
      at Object.<anonymous> (node_modules/aws-cdk-lib/aws-backup/index.js:1:711)
      at Object.<anonymous> (node_modules/aws-cdk-lib/index.js:1:8[19](https://github.com/stefanfreitag/csv-to-heartbeat-yml/actions/runs/6043832323/job/16401510522#step:4:20)7)
      at Object.<anonymous> (test/main.test.ts:1:1)
```

The GitHub action takes care of updating dependencies, but does not change the CDK version. This points also into the direction that the issue is unrelated to a CDK version upgrade.

Following the previous comments I updated the version(s) related to Jest 

```
 "jest": "^29",
 ...
  "ts-jest": "^29",
 ```
 and this resolves the issue for me.

**Comment by stec00** [comment]
Yep, upgrading Jest fixed the same issue for me. In light of that, think this issue can probably be closed.

**Comment by peterwoodworth** [comment]
good to hear 👍🏻 thanks for sharing the outcome
