### ISSUE TITLE
codepipeline-actions: Github connection, allow Token values

### ISSUE THREAD

**Issue by Nikola-Milovic** [aws/aws-cdk#27100]
### Describe the bug

While setting up an AWS CDK pipeline using the pipelines.CodePipelineSource.connection method, I encountered an error indicating that the Step id cannot be unresolved. Specifically, it failed on a tokenized value `${Token[TOKEN.653]}/${Token[TOKEN.656]}`, which seems to be originating from the SSM parameters `githubOwner` and `githubRepo`.

### Expected Behavior

The AWS CDK pipeline should be able to resolve and handle the tokenized values from SSM parameters seamlessly, without throwing an error related to the unresolved Step id.

### Current Behavior

When trying to synthesize the pipeline stack, the process fails with the error message:

```console
You are about to destroy the CDK environment to dev, using profile project-dev.
Are you sure? (yes/no): yes
project/deployment/node_modules/aws-cdk-lib/pipelines/lib/blueprint/step.js:1
"use strict";var _a;Object.defineProperty(exports,"__esModule",{value:!0}),exports.Step=void 0;const jsiiDeprecationWarnings=require("../../../.warnings.jsii.js"),JSII_RTTI_SYMBOL_1=Symbol.for("jsii.rtti"),core_1=require("../../../core"),step_output_1=
require("../helpers-internal/step-output");class Step{static sequence(steps){for(let i=1;i<steps.length;i++)steps[i].addStepDependency(steps[i-1]);return steps}constructor(id){if(this.id=id,this.dependencyFileSets=[],this.isSource=!1,this._dependencies
=new Set,core_1.Token.isUnresolved(id))throw new Error(`Step id cannot be unresolved, got '${id}'`)}get dependencies(){return Array.from(new Set([...this.dependencyFileSets.map(f=>f.producer),...this._dependencies]))}toString(){return`${this.constructo
r.name}(${this.id})`}get primaryOutput(){return this._primaryOutput}addStepDependency(step){try{jsiiDeprecationWarnings.aws_cdk_lib_pipelines_Step(step)}catch(error){throw process.env.JSII_DEBUG!=="1"&&error.name==="DeprecationError"&&Error.captureStac
kTrace(error,this.addStepDependency),error}this._dependencies.add(step)}addDependencyFileSet(fs){try{jsiiDeprecationWarnings.aws_cdk_lib_pipelines_FileSet(fs)}catch(error){throw process.env.JSII_DEBUG!=="1"&&error.name==="DeprecationError"&&Error.captu
reStackTrace(error,this.addDependencyFileSet),error}this.dependencyFileSets.push(fs)}configurePrimaryOutput(fs){try{jsiiDeprecationWarnings.aws_cdk_lib_pipelines_FileSet(fs)}catch(error){throw process.env.JSII_DEBUG!=="1"&&error.name==="DeprecationErro
r"&&Error.captureStackTrace(error,this.configurePrimaryOutput),error}this._primaryOutput=fs}discoverReferencedOutputs(structure){for(const output of step_output_1.StepOutput.findAll(structure))this._dependencies.add(output.step),step_output_1.StepOutpu
t.recordProducer(output)}get consumedStackOutputs(){return[]}}exports.Step=Step,_a=JSII_RTTI_SYMBOL_1,Step[_a]={fqn:"aws-cdk-lib.pipelines.Step",version:"2.94.0"};

                                             ^
Error: Step id cannot be unresolved, got '${Token[TOKEN.653]}/${Token[TOKEN.656]}'
    at new Step (project/deployment/node_modules/aws-cdk-lib/pipelines/lib/blueprint/step.js:1:550)
    at new CodePipelineSource (project/deployment/node_modules/aws-cdk-lib/pipelines/lib/codepipeline/codepipeline-source.js:1:483)
    at new CodeStarConnectionSource (project/deployment/node_modules/aws-cdk-lib/pipelines/lib/codepipeline/codepipeline-source.js:1:5010)
    at Function.connection (project/deployment/node_modules/aws-cdk-lib/pipelines/lib/codepipeline/codepipeline-source.js:1:1766)
    at new MasterPipeline (project/deployment/lib/master-pipeline.ts:29:54)
    at Object.<anonymous> (project/deployment/bin/deployment.ts:33:26)
    at Module._compile (node:internal/modules/cjs/loader:1254:14)
    at Module.m._compile (project/deployment/node_modules/ts-node/src/index.ts:1618:23)
    at Module._extensions..js (node:internal/modules/cjs/loader:1308:10)
    at Object.require.extensions.<computed> [as .ts] (project/deployment/node_modules/ts-node/src/index.ts:1621:12)

Subprocess exited with error 1
```

### Reproduction Steps

Set up an AWS CDK stack with parameters fetched from SSM.
Use these parameters in the pipelines.CodePipelineSource.connection method to define the source input.
Attempt to synthesize or deploy the stack.

```typescript
export function getSSMParameter(scope: Construct, key: string): string {
  const value = StringParameter.valueForStringParameter(scope, key);
  if (!value) {
    throw new Error(`Parameter ${key} does not exist in SSM.`);
  }
  return value;
}

    const githubOwner = getSSMParameter(this, ParameterKeys.GithubOwner);
    const githubRepo = getSSMParameter(this, ParameterKeys.GithubRepo);
    const githubConnection = getSSMParameter(this, ParameterKeys.GithubConnectionArn);

    const artifactBucket = new s3.Bucket(this, "ArtifactBucket", {
      removalPolicy: cdk.RemovalPolicy.DESTROY,
    });

    const sourceInput = pipelines.CodePipelineSource.connection(
      `${githubOwner}/${githubRepo}`,
      getBranch(props.deployEnv),
      {
        connectionArn: githubConnection,
      },
    );
```

### CDK CLI Version

2.94.0

### Node.js Version

18.16.0

### OS

Ubuntu 22.04

### Language

Typescript

### Language Version

Typescript ~5.0.3

### Other information

Not really anything too important it was just weird that this wouldnt work.

Especially since a similar pattern can be used for source actions

```
		const sourceAction =
			new codepipeline_actions.CodeStarConnectionsSourceAction({
				actionName: "GitHubSource",
				output: this.sourceOutput,
				connectionArn: getSSMParameter(this, ParameterKeys.GithubConnectionArn),
				owner: getSSMParameter(this, ParameterKeys.GithubOwner),
				repo: getSSMParameter(this, ParameterKeys.GithubRepo),
				branch: getBranch(props.deployEnv),
			});
```

**Comment by peterwoodworth** [comment]
We need to be able to parse the value at runtime, this error is explicitly thrown by us if the values supplied are tokens https://github.com/aws/aws-cdk/blob/ae455d822c9da2e4a1b23c548e9d220d8e95a346/packages/aws-cdk-lib/pipelines/lib/codepipeline/codepipeline-source.ts#L428

We don't call this out in the documentation, we need to add this to the `repoString` docstring https://github.com/aws/aws-cdk/blob/5046a9b67a50bad6748077ca16a977d0844f1775/packages/aws-cdk-lib/pipelines/lib/codepipeline/codepipeline-source.ts#L104

**Comment by DarhkVoyd** [comment]
I'm a newcomer to the project and I'd like to work on this issue.
I'm eager to help with this, so please let me know how I can get started. Thanks!

**Comment by igoodwinVolly** [comment]
I can confirm the same thing happens when using the code below to connect to a Bitbucket repo with cloudformation parameters that are tokenized (RepositoryName, Environment, ConnectionArn).

```js
    // Parameters
    const Environment = new cdk.CfnParameter(this, "Environment", {
      type: "String",
      description: "The development environment / repository branch name.",
    })
    const RepositoryName = new cdk.CfnParameter(this, "RepositoryName", {
      type: "String",
      description: "The code source repository name.",
    })
    const RepositoryConnectionArn = new cdk.CfnParameter(this, "RepositoryConnectionArn", {
      type: "String",
      description: "The code source CodeStar connection Arn. The connection must be configured BEFORE deployment.",
    })

    // Resources
    const pipeline = new CodePipeline(this, "Pipeline", {
      pipelineName: `Deployment-Pipeline-${Environment.valueAsString}`,
      synth: new ShellStep("Synth", {
        input: CodePipelineSource.connection(RepositoryName.valueAsString, Environment.valueAsString, {
          connectionArn: RepositoryConnectionArn.valueAsString,
        }),
        commands: ["cdk synth"],
      }),
    })
```
