### ISSUE TITLE
(aws-cloudtrail): setting up cloudtrail with exisiting Bucket and KMS produces error "Incorrect Bucket Policy"

### ISSUE THREAD

**Issue by khushail** [aws/aws-cdk#27168]
### Describe the bug

Setting up Cloudtrail with existing bucket and KMS gives an error "incorrect bucket policy"

[Existing ticket ](https://t.corp.amazon.com/V1032411136)

### Expected Behavior

it should succeed with access to bucket logs

### Current Behavior

Error its throwing:
2:41
SPS-SCEPT-Dev/s3CreateBucket/s3CreateBucket/SPS-SPECT-CloudTrail (s3CreateBucketSPSSPECTCloudTrail6CA6B14C) Resource handler returned message: "Invalid request provided: Incorrect S3 bucket policy is detected for bucket: sps-logging-174974834576-us-east-2 (Service: CloudTrail, Status Code: 400, Request ID: bff6e086-9c56-46ff-a32a-e4b9bc01188d)" (RequestToken: c1a89e38-2e3f-3cb9-c723-bac1ad5e5a03, HandlerErrorCode: InvalidRequest)
 AWS::CloudTrail::Trail | SPS-SCEPT-Dev/s3CreateBucket/s3CreateBucket/SPS-SPECT-CloudTrail (s3CreateBucketSPSSPECTCloudTrail6CA6B14C) Resource handler returned message: "Invalid request provided:
Incorrect S3 bucket policy is detected for bucket: sps-logging-174974834576-us-east-2 (Service: CloudTrail, Status Code: 400, Request ID: bff6e086-9c56-46ff-a32a-e4b9bc01188d)" (RequestToken: c1a89e38-2e3f-3cb9-c723-bac1ad5e5a03, HandlerErrorCode: InvalidRequest)
 :x:  SPS-SCEPT-Dev/s3CreateBucket failed: Error: The stack named SPSSCEPTDevs3CreateBucketFF6AF095 failed to deploy: UPDATE_ROLLBACK_COMPLETE: Resource handler returned message: "Invalid request provided: Incorrect S3 bucket policy is detected for bucket: sps-logging-
174974834576-us-east-2 (Service: CloudTrail, Status Code: 400, Request ID: bff6e086-9c56-46ff-a32a-e4b9bc01188d)" (RequestToken: c1a89e38-2e3f-3cb9-c723-bac1ad5e5a03, HandlerErrorCode: InvalidRequest)
    at FullCloudFormationDeployment.monitorDeployment (C:\Users\kadaragh\AppData\Roaming\npm\node_modules\aws-cdk\lib\index.js:412:10236)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Object.deployStack2 [as deployStack] (C:\Users\kadaragh\AppData\Roaming\npm\node_modules\aws-cdk\lib\index.js:415:153172)
    at async C:\Users\kadaragh\AppData\Roaming\npm\node_modules\aws-cdk\lib\index.js:415:136968
 :x: Deployment failed: Error: The stack named SPSSCEPTDevs3CreateBucketFF6AF095 failed to deploy: UPDATE_ROLLBACK_COMPLETE: Resource handler returned message: "Invalid request provided: Incorrect S3 bucket policy is detected for bucket: sps-logging-174974834576-us-eas
t-2 (Service: CloudTrail, Status Code: 400, Request ID: bff6e086-9c56-46ff-a32a-e4b9bc01188d)" (RequestToken: c1a89e38-2e3f-3cb9-c723-bac1ad5e5a03, HandlerErrorCode: InvalidRequest)
    at FullCloudFormationDeployment.monitorDeployment (C:\Users\kadaragh\AppData\Roaming\npm\node_modules\aws-cdk\lib\index.js:412:10236)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Object.deployStack2 [as deployStack] (C:\Users\kadaragh\AppData\Roaming\npm\node_modules\aws-cdk\lib\index.js:415:153172)
    at async C:\Users\kadaragh\AppData\Roaming\npm\node_modules\aws-cdk\lib\index.js:415:136968
The stack named SPSSCEPTDevs3CreateBucketFF6AF095 failed to deploy: UPDATE_ROLLBACK_COMPLETE: Resource handler returned message: "Invalid request provided: Incorrect S3 bucket policy is detected for bucket: sps-logging-174974834576-us-east-2 (Service: CloudTrail, Status Code: 400, Request ID: bff6e086-9c56-46ff-a32a-e4b9bc01188d)" (RequestToken: c1a89e38-2e3f-3cb9-c723-bac1ad5e5a03, HandlerErrorCode: InvalidRequest)

### Reproduction Steps

Code is provided in the ticket. Repro'd issue with adding the policy manually -

testbucket = s3.Bucket.from_bucket_attributes(self, "MyTestBucket", bucket_name="mytestbucket1503",
                       bucket_arn="arn:aws:s3:::mytestbucket1503",)

        iamrole = iam.Role(self, "MyRoleBucket",assumed_by=iam.ServicePrincipal('cloudtrail.amazonaws.com'))

        iamrole.add_to_policy(iam.PolicyStatement(
            effect=iam.Effect.ALLOW,
            resources=[testbucket.bucket_arn],
            actions=["s3:GetBucketAcl"],
            conditions={"StringEquals": {"s3:x-amz-acl": "bucket-owner-full-control"}},
        )) 

        iamrole.add_to_policy(iam.PolicyStatement(
            effect=iam.Effect.ALLOW,
            resources=['*'],
            actions=["s3:PutObject"],
        )) 

        trail= cloudtrail.Trail(self, "CloudTrail",
                                send_to_cloud_watch_logs=True,
                                bucket=testbucket,
        )

### CDK CLI Version

2.95.1

### Node.js Version

v18.12.1

### OS

mac

### Language

Python

**Comment by mhmdio** [comment]
same here, with `isOrganizationTrail: true`

**Comment by beniusij** [comment]
"GetBucketAcl" policy should have condition assessing for trail arn instead of `s3:x-amz-acl` I believe 🤔

**Comment by Jacky-CC** [comment]
I encountered a similar issue with 'cloudtrail.trail.' After replacing the CDK L1 **CfnTrail** with the **trail**, the problem was resolved. You can refer to the code snippet below for details, try it  

https://github.com/Jacky-CC/cdk-example-cloudtrail-s3-dataevent/blob/main/lib/s3-clourtrail-dataevent.ts
