### ISSUE TITLE
(custom-resources): AwsCustomResourcePolicy.fromSdkCalls does not work with v3 command format

### ISSUE THREAD

**Issue by luxaritas** [aws/aws-cdk#27255]
### Describe the bug

Creating an AwsCustomResource with a service/action using the AWS CDK v3 format and a policy AwsCustomResourcePolicy.fromSdkCalls fails

### Expected Behavior

A policy is correctly created

### Current Behavior

```
Error: Action '@aws-sdk/client-ec2:ModifyInstanceMetadataOptionsCommand' is invalid. An action string consists of a service namespace, a colon, and the name of an action. Action names can include wildcards.
    at PolicyStatement.validatePolicyActions (/home/jonathan/Development/eterna/infra/node_modules/aws-cdk-lib/aws-iam/lib/policy-statement.js:2:3414)
    at PolicyStatement.addActions (/home/jonathan/Development/eterna/infra/node_modules/aws-cdk-lib/aws-iam/lib/policy-statement.js:2:1290)
    at new PolicyStatement (/home/jonathan/Development/eterna/infra/node_modules/aws-cdk-lib/aws-iam/lib/policy-statement.js:2:579)
    at new AwsCustomResource (/home/jonathan/Development/eterna/infra/node_modules/aws-cdk-lib/custom-resources/lib/aws-custom-resource/aws-custom-resource.js:1:5701
```

### Reproduction Steps

The call I'm currently running into this with:

```ts
new AwsCustomResource(instance, `enableMetadataTags`, {
  onCreate: {
    service: '@aws-sdk/client-ec2',
    action: 'ModifyInstanceMetadataOptionsCommand',
    parameters: {
      InstanceId: instance.instanceId,
      InstanceMetadataTags: 'enabled'
    },
    physicalResourceId: PhysicalResourceId.of('EnableMetadataTags')
  },
  onDelete: {
    service: '@aws-sdk/client-ec2',
    action: 'ModifyInstanceMetadataOptionsCommand',
    parameters: {
      InstanceId: instance.instanceId,
      InstanceMetadataTags: 'disabled'
    }
  },
  policy: AwsCustomResourcePolicy.fromSdkCalls({
    resources: AwsCustomResourcePolicy.ANY_RESOURCE
  })
});
```

### Possible Solution

I'm assuming to construct the correct policy, the service name needs to strip `@aws-sdk/client-` and the action needs to strip `Command`

### CDK CLI Version

2.94.0 (build 987c329)

### Node.js Version

v18.17.1

### OS

Linux

### Language

Typescript

### Other information

If my assessment is correct, this should be easy for me to submit a PR for if that would be helpful!

**Comment by khushail** [comment]
Hi @luxaritas , thanks for reporting this.

@WinterYukky , thanks for submitting PR.
