### ISSUE TITLE
aws-eks: integ.eks-cluster integ test failing with import error

### ISSUE THREAD

**Issue by kishiel** [aws/aws-cdk#27302]
### Describe the bug

When executing the [integ.eks-cluster](https://github.com/aws/aws-cdk/blob/main/packages/%40aws-cdk-testing/framework-integ/test/aws-eks/test/integ.eks-cluster.ts) test the ProviderframeworkonEvent lambda is failing with an error:

```
2023-09-26T20:01:22.589Z	undefined	ERROR	Uncaught Exception 	
{
    "errorType": "Runtime.ImportModuleError",
    "errorMessage": "Error: Cannot find module './outbound'\nRequire stack:\n- /var/task/cfn-response.js\n- /var/task/framework.js\n- /var/runtime/index.mjs",
    "stack": [
        "Runtime.ImportModuleError: Error: Cannot find module './outbound'",
        "Require stack:",
        "- /var/task/cfn-response.js",
        "- /var/task/framework.js",
        "- /var/runtime/index.mjs",
        "    at _loadUserApp (file:///var/runtime/index.mjs:1061:17)",
        "    at async UserFunction.js.module.exports.load (file:///var/runtime/index.mjs:1093:21)",
        "    at async start (file:///var/runtime/index.mjs:1256:23)",
        "    at async file:///var/runtime/index.mjs:1262:1"
    ]
}
```

This also occurred when executing the ipv6 cluster test.

### Expected Behavior

I expected a cluster to create and the test to run

### Current Behavior

Cluster creation fails resulting in a rollback after no expected response returns to the handler before a timeout occurs.  This requires the stack to be deleted and the cluster resource to be left behind (although no cluster actually exists)

### Reproduction Steps

Change the name of the test (or some other inert change) and execute:

```
yarn integ test/aws-eks/test/integ.eks-cluster.js --update-on-failed
```

### CDK CLI Version

2.42.0 (build 7d8ef0b)

### Node.js Version

v18.16.0

### OS

MacOS 13.5.2

### Language

Typescript

**Comment by kishiel** [comment]
Working on this a bit more today.  I've had problems in the past with snapshots having sticky assets, so for fun I've deleted the snapshot directory for this test and am running it again.  I can see the cluster creating so whatever this issue is it's localized to the snapshot(s).  I've got a few more tests to run so I can regenerate them and see if we can just close this issue.

**Comment by kishiel** [comment]
Deleting the existing snapshot and re-running it passed with no assertions.  This makes debugging changes really expensive because it makes me doubt the existing snapshots are actually sane.  Is there anything I can do apart from running the tests in advance of a change to help prevent this condition?

**Comment by peterwoodworth** [comment]
The version you are using is pretty old. Are you still running into this on latest version?

**Comment by kishiel** [comment]
> The version you are using is pretty old. Are you still running into this on latest version?

CDK version?  Good question.  Let me try upgrading to latest and see what happens.

**Comment by go-to-k** [comment]
I also got the same error with integ tests for cluster-inference, handlers-in-vpc, cluster-bottlerocket-ng, cluster-private-endpoint, etc... in the eks module.

My fork repo is in [this commit](https://github.com/aws/aws-cdk/commit/6616026d3879f0271b7813ed00f0899c666da1e3) included in v2.99.0.

The `outbound.js` may or may not be in the asset directory commited.

- https://github.com/go-to-k/aws-cdk/tree/main/packages/%40aws-cdk-testing/framework-integ/test/aws-eks/test/integ.eks-cluster-handlers-vpc.js.snapshot/asset.81328426dba578d9ff57b0b54146bc81395a478131b0b61e40236fcc8395c2db
- https://github.com/go-to-k/aws-cdk/tree/main/packages/%40aws-cdk-testing/framework-integ/test/aws-eks/test/integ.alb-controller.js.snapshot/asset.d002370061965c69bc4caf15dddb5eccc9df318933ade6e4fa57cddb81c5abef
