### ISSUE TITLE
 Failed to stringify tree because the object is too large

### ISSUE THREAD

**Issue by zzhlogin** [aws/aws-cdk#27300]
### Describe the bug

This is the previous ticket we cut: 
https://t.corp.amazon.com/V977561298/overview

We have a CDK [pipeline](https://pipelines.amazon.com/pipelines/AWSTracingAlarms-Prod) to create CW Alarms for every region.

As we are creating more resources, the tree object gets too large, and we get an error:

```
/workplace/zzhlogin/xray-pipelines/src/AWSTracingAlarmsPipelineCDK/node_modules/monocdk/lib/core/lib/private/tree-metadata.js:78
        fs.writeFileSync(path.join(builder.outdir, FILE_PATH), JSON.stringify(tree, undefined, 2), { encoding: 'utf-8' });
                                                                    ^

RangeError: Invalid string length
    at JSON.stringify (<anonymous>)
    at TreeMetadata._synthesizeTree (/workplace/zzhlogin/xray-pipelines/src/AWSTracingAlarmsPipelineCDK/node_modules/monocdk/lib/core/lib/private/tree-metadata.js:78:69)
    at /workplace/zzhlogin/xray-pipelines/src/AWSTracingAlarmsPipelineCDK/node_modules/monocdk/lib/core/lib/private/synthesis.js:158:23
    at visit (/workplace/zzhlogin/xray-pipelines/src/AWSTracingAlarmsPipelineCDK/node_modules/monocdk/lib/core/lib/private/synthesis.js:200:9)
    at visit (/workplace/zzhlogin/xray-pipelines/src/AWSTracingAlarmsPipelineCDK/node_modules/monocdk/lib/core/lib/private/synthesis.js:197:9)
    at synthesizeTree (/workplace/zzhlogin/xray-pipelines/src/AWSTracingAlarmsPipelineCDK/node_modules/monocdk/lib/core/lib/private/synthesis.js:148:5)
    at Object.synthesize (/workplace/zzhlogin/xray-pipelines/src/AWSTracingAlarmsPipelineCDK/node_modules/monocdk/lib/core/lib/private/synthesis.js:33:5)
    at App.synth (/workplace/zzhlogin/xray-pipelines/src/AWSTracingAlarmsPipelineCDK/node_modules/monocdk/lib/core/lib/stage.js:104:41)
    at process.<anonymous> (/workplace/zzhlogin/xray-pipelines/src/AWSTracingAlarmsPipelineCDK/node_modules/monocdk/lib/core/lib/app.js:58:51)
    at Object.onceWrapper (node:events:628:26)
```

I think this error is because JSON.stringify generates a big string which length exceeds the nodejs V8 engine MAX_STRING_LENGTH limitation.

I wonder if there is any workaround to avoid this limitation or reduce the size of tree object?

Whether it is possible to replace JSON.stringify and support writing a big object?

We are temporarily splitting the pipeline into two:
https://pipelines.amazon.com/pipelines/AWSTracingAlarms-Prod
https://pipelines.amazon.com/pipelines/AWSTracingAlarmsSecond-Prod

But it will be of great help to have a solution and we can merge them back.

Thanks.

### Expected Behavior

Provide a solution to avoid nodejs V8 engine MAX_STRING_LENGTH limitation or reduce the size of tree object.

### Current Behavior

JSON.stringify generates a big string which length exceeds the nodejs V8 engine MAX_STRING_LENGTH limitation.

### Reproduction Steps

To reproduce the issue, 

```
brazil ws create --name xray-alarms
cd xray-alarms
brazil ws use \
  --versionset AWSTracingRootVersionSet/Prod \
  --platform AL2_x86_64 \
  --package AWSTracingAlarmsPipelineCDK
cd src/AWSTracingAlarmsPipelineCDK
git checkout nodejs_limit
brazil-build
```

### CDK CLI Version

CDKBuild = 3.x;

### Node.js Version

NodeJS = default;

### OS

irrelevant

### Language

Typescript

**Comment by kellertk** [comment]
Hi @zzhlogin, GitHub is a public forum. Please do not put links to internal Amazon tools on public issues. I will have someone on my team follow up with you internally for next steps.
