### ISSUE TITLE
(aws_cdk.aws_ec2/CfnTransitGatewayAttachment): parameters in OptionsProperty are not supported

### ISSUE THREAD

**Issue by shawnxue** [aws/aws-cdk#27344]
### Describe the bug

When attaching a vpc to transit gateway in AWS CDK (python), we found that keys in OptionsProperty are not supported.
CDK version: aws-cdk-lib==2.93.0
Here is our code
```
tgw_vpc = CfnTransitGatewayAttachment(
            self,
            "attachVPCToTransitGateway",
            subnet_ids=my_vpc.select_subnets(subnet_group_name='private_subnet').subnet_ids,
            transit_gateway_id=my_tgw.attr_id,
            vpc_id=my_vpc.vpc_id,
            options=CfnTransitGatewayAttachment.OptionsProperty(
                appliance_mode_support="disable",
                dns_support="enable",
                ipv6_support="disable"
            )
        )
```
Errors we got:
```
#/Options: extraneous key [dnsSupport] is not permitted
#/Options: extraneous key [ipv6Support] is not permitted
#/Options: extraneous key [applianceModeSupport] is not permitted
    at FullCloudFormationDeployment.monitorDeployment (/opt/hostedtoolcache/node/18.0.0/x64/lib/node_modules/aws-cdk/lib/index.js:467:10232)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Object.deployStack2 [as deployStack] (/opt/hostedtoolcache/node/18.0.0/x64/lib/node_modules/aws-cdk/lib/index.js:470:179911)
    at async /opt/hostedtoolcache/node/18.0.0/x64/lib/node_modules/aws-cdk/lib/index.js:470:163159
```

### Expected Behavior

parameters in OptionsProperty are supported.

### Current Behavior

We got errors when applying the code:
Errors we got:
```
#/Options: extraneous key [dnsSupport] is not permitted
#/Options: extraneous key [ipv6Support] is not permitted
#/Options: extraneous key [applianceModeSupport] is not permitted
    at FullCloudFormationDeployment.monitorDeployment (/opt/hostedtoolcache/node/18.0.0/x64/lib/node_modules/aws-cdk/lib/index.js:467:10232)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Object.deployStack2 [as deployStack] (/opt/hostedtoolcache/node/18.0.0/x64/lib/node_modules/aws-cdk/lib/index.js:470:179911)
    at async /opt/hostedtoolcache/node/18.0.0/x64/lib/node_modules/aws-cdk/lib/index.js:470:163159
```

### Reproduction Steps

1. create a transit gateway with CfnTransitGateway
2. create a transit gateway attachment with CfnTransitGatewayAttachment
3. apply the code with `cdk deploy `
4. You will get the errors above.

### CDK CLI Version

2.86.0 (build 1130fab)

### Node.js Version

18.0.0

### OS

22.04 LTS

### Language

Python

### Language Version

3.9

**Comment by peterwoodworth** [comment]
[Options takes in `any`, not `OptionsProperty`](https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_ec2.CfnTransitGatewayAttachment.html#options). Fill it out directly without that (and be sure to PascalCase the keys) and this will work fine.
