### ISSUE TITLE
(aws-cdk): (cdk deploy failed with Error: EACCES: permission denied, scandir )

### ISSUE THREAD

**Issue by maymayman** [aws/aws-cdk#27610]
### Describe the bug

I am trying to deploy CloudFormation templates using CDK
But receive an Error `EACCES: permission denied, scandir`

### Expected Behavior

Can deploy successful

### Current Behavior
```
node:fs:1527
  handleErrorFromBinding(ctx);
  ^


Error: EACCES: permission denied, scandir 'C:/Users/Phat/Desktop/workspace/resize-image-service/cdk.out/asset.a4d282274929658deaa9944f80a716703650e903f801727100f56ab94049e35a/nodejs/node_modules/.bin/prebuild-install'
    at Object.readdirSync (node:fs:1527:3)
    at GlobSync._readdir (\node_modules\aws-cdk\lib\index.js:431:848900)
    at GlobSync._readdirInGlobStar (\node_modules\aws-cdk\lib\index.js:431:848291)        
    at GlobSync._readdir (\node_modules\aws-cdk\lib\index.js:431:848723)
    at GlobSync._processGlobStar (\node_modules\aws-cdk\lib\index.js:431:849803)
    at GlobSync._process (\node_modules\aws-cdk\lib\index.js:431:846756)
    at GlobSync._processGlobStar (\npm\node_modules\aws-cdk\lib\index.js:431:850312)
    at GlobSync._process (\node_modules\aws-cdk\lib\index.js:431:846756)
    at GlobSync._processGlobStar (\node_modules\aws-cdk\lib\index.js:431:850312)
    at GlobSync._process (\aws-cdk\lib\index.js:431:846756) {
  errno: -4092,
  syscall: 'scandir',
  code: 'EACCES',
  path: 'Desktop/workspace/resize-image-service/cdk.out/asset.a4d282274929658deaa9944f80a716703650e903f801727100f56ab94049e35a/nodejs/node_modules/.bin/prebuild-install'
}
```

### Reproduction Steps

 cdk deploy

### CDK CLI Version

2.102.0

### Node.js Version

v18.18.2

### OS

Window 10 Pro x64

### Language

TypeScript

### Language Version

typescript@4.9.5

**Comment by pahud** [comment]
Looks like it's a local OS filesystem permission issue. Unfortunately I have no idea about that off the top of my head. Does it always happen when you create a new fresh cdk project and deploy that?

**Comment by maymayman** [comment]
@pahud I already resolved this issue in macOS but still have an error in Window 
unlucky it always happens even though I was install CDK to global

**Comment by Richardmbs12** [comment]
Same issue here since i installed the latest cdk version - 2.108  also on windows

**Comment by tharikrizan-praedico** [comment]
I am having the same issue

**Comment by ashishdhingra** [comment]
@maymayman I'm unsure if this is a CDK tooling issue. Could you try running command prompt in Administrator mode and try again.

**Comment by adam-mah** [comment]
Experiencing the same issue here RuntimeError: EACCES: permission denied, lstat

**Comment by Aarbel** [comment]
same issue here, have you found a solution ?
