### ISSUE TITLE
aws-cdk: Validation error for stackName

### ISSUE THREAD

**Issue by alifrugal** [aws/aws-cdk#27746]
### Describe the bug

Since @2.98, I have got a validation error on the names of the stacks when launching a cdk application with nested stacks.

`Error occurred while monitoring stack: Error [ValidationError]: 2 validation errors detected: Value '' at 'stackName' failed to satisfy constraint: Member must have length greater than or equal to 1; Value '' at 'stackName' failed to satisfy constraint: Member must satisfy regular expression pattern: [a-zA-Z][-a-zA-Z0-9]*|arn:[-a-zA-Z0-9:/._+]*
    at Request.extractError (/usr/local/lib/node_modules/aws-cdk/lib/index.js:362:46430)
    at Request.callListeners (/usr/local/lib/node_modules/aws-cdk/lib/index.js:362:90083)
    at Request.emit (/usr/local/lib/node_modules/aws-cdk/lib/index.js:362:89531)
    at Request.emit (/usr/local/lib/node_modules/aws-cdk/lib/index.js:362:196289)
    at Request.transition (/usr/local/lib/node_modules/aws-cdk/lib/index.js:362:189841)
    at AcceptorStateMachine.runTo (/usr/local/lib/node_modules/aws-cdk/lib/index.js:362:154713)
    at /usr/local/lib/node_modules/aws-cdk/lib/index.js:362:155043
    at Request.<anonymous> (/usr/local/lib/node_modules/aws-cdk/lib/index.js:362:190133)
    at Request.<anonymous> (/usr/local/lib/node_modules/aws-cdk/lib/index.js:362:196364)
    at Request.callListeners (/usr/local/lib/node_modules/aws-cdk/lib/index.js:362:90251) {
  code: 'ValidationError',
  time: 2023-10-30T06:44:13.579Z,
  requestId: '70dbfc8a-0639-4aa7-aa14-014fe1ec811a',
  statusCode: 400,`

### Expected Behavior

If I downgrade CDK (installed globally) to @2.96, I don't have the issue. 

### Current Behavior

`Error occurred while monitoring stack: Error [ValidationError]: 2 validation errors detected: Value '' at 'stackName' failed to satisfy constraint: Member must have length greater than or equal to 1; Value '' at 'stackName' failed to satisfy constraint: Member must satisfy regular expression pattern: [a-zA-Z][-a-zA-Z0-9]*|arn:[-a-zA-Z0-9:/._+]*
    at Request.extractError (/usr/local/lib/node_modules/aws-cdk/lib/index.js:362:46430)
    at Request.callListeners (/usr/local/lib/node_modules/aws-cdk/lib/index.js:362:90083)
    at Request.emit (/usr/local/lib/node_modules/aws-cdk/lib/index.js:362:89531)
    at Request.emit (/usr/local/lib/node_modules/aws-cdk/lib/index.js:362:196289)
    at Request.transition (/usr/local/lib/node_modules/aws-cdk/lib/index.js:362:189841)
    at AcceptorStateMachine.runTo (/usr/local/lib/node_modules/aws-cdk/lib/index.js:362:154713)
    at /usr/local/lib/node_modules/aws-cdk/lib/index.js:362:155043
    at Request.<anonymous> (/usr/local/lib/node_modules/aws-cdk/lib/index.js:362:190133)
    at Request.<anonymous> (/usr/local/lib/node_modules/aws-cdk/lib/index.js:362:196364)
    at Request.callListeners (/usr/local/lib/node_modules/aws-cdk/lib/index.js:362:90251) {
  code: 'ValidationError',
  time: 2023-10-30T06:44:13.579Z,
  requestId: '70dbfc8a-0639-4aa7-aa14-014fe1ec811a',
  statusCode: 400,`

### Reproduction Steps

Launch a stack with nested stacks

### CDK CLI Version

2.103.1

### Node.js Version

20.9.0

### OS

MacOS 13.6

### Language

TypeScript

**Comment by suhussai** [comment]
I believe this issue is related: https://github.com/aws/aws-cdk/issues/27526

**Comment by rix0rrr** [comment]
This was probably fixed in https://github.com/aws/aws-cdk/pull/27692 (released as `2.104.0`)

**Comment by alifrugal** [comment]
Fixed in 2.104.0
