### ISSUE TITLE
ApplicationLoadBalancer: failing call to logAccessLogs after version change from 2.105 to 2.106

### ISSUE THREAD

**Issue by ddjordjevic-daon** [aws/aws-cdk#27928]
### Describe the bug

I have a code that is creating ALBs with logAccessLogs enabled. I am passing IBucket to the method which I'm getting by referencing the bucket name with S3.fromBucketName method. In version 2.105 this piece of code has worked without any issues. Only after I switched to 2.106 I started getting issues with this. My assumption is that this is related to commit https://github.com/aws/aws-cdk/commit/1b86634c75623f34856a3578e361d81dae278f86 which fixed issue #27528

### Expected Behavior

Attach bucket for ALB to use to write access logs.

### Current Behavior

Fails with following errors:
```log
File "/codebuild/output/src3432/src/s3/01/lib/alb.py", line 108, in __init__
    self.alb.log_access_logs(
  File "/root/.pyenv/versions/3.11.4/lib/python3.11/site-packages/aws_cdk/aws_elasticloadbalancingv2/__init__.py", line 2389, in log_access_logs
    return typing.cast(None, jsii.invoke(self, "logAccessLogs", [bucket, prefix]))
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.pyenv/versions/3.11.4/lib/python3.11/site-packages/jsii/_kernel/__init__.py", line 149, in wrapped
    return _recursize_dereference(kernel, fn(kernel, *args, **kwargs))
                                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.pyenv/versions/3.11.4/lib/python3.11/site-packages/jsii/_kernel/__init__.py", line 399, in invoke
    response = self.provider.invoke(
               ^^^^^^^^^^^^^^^^^^^^^
  File "/root/.pyenv/versions/3.11.4/lib/python3.11/site-packages/jsii/_kernel/providers/process.py", line 380, in invoke
    return self._process.send(request, InvokeResponse)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.pyenv/versions/3.11.4/lib/python3.11/site-packages/jsii/_kernel/providers/process.py", line 342, in send
    raise RuntimeError(resp.error) from JavaScriptError(resp.stack)
RuntimeError: TypeError: Cannot read properties of undefined (reading 'shouldSynthesize')
```

### Reproduction Steps

```python
self.alb = elbv2.ApplicationLoadBalancer(
    scope, "ALB",
    vpc=vpc,
    internet_facing=internet_facing,
    vpc_subnets=subnets,
    security_group=security_groups[0],
    load_balancer_name=self.name,
    **kwargs
)
self.alb.log_access_logs(
    aws_s3.Bucket.from_bucket_name(
        scope, "ALBLogsBucket", get_alb_bucket_name(vpc_name)
    ),
    ""
)
```

### CDK CLI Version

2.106.0

### Framework Version

2.106.0

### Node.js Version

18.16.1

### OS

aws-codebuild-docker-images/ubuntu/standard/7.0

### Language

Python

### Language Version

3.11.4

**Comment by pahud** [comment]
Yes I ca reproduce this.

```ts
const alb = new elbv2.ApplicationLoadBalancer(this, 'ALB', {
	vpc: getDefaultVpc(this),
});

const bucket = s3.Bucket.fromBucketName(this, 'importedBucket', 'my-tmp-us-east-1')
alb.logAccessLogs(bucket);
```
Error

```
TypeError: Cannot read properties of undefined (reading 'shouldSynthesize')
    at CfnLoadBalancer.addDependency (/Users/pahud/repo/issue-triage/node_modules/aws-cdk-lib/core/lib/cfn-resource.js:1:5406)
    at ApplicationLoadBalancer.logAccessLogs (/Users/pahud/repo/issue-triage/node_modules/aws-cdk-lib/aws-elasticloadbalancingv2/lib/shared/base-load-balancer.js:1:4960)
    at new Demo (/Users/pahud/repo/issue-triage/lib/issue-triage-stack.ts:108:7)
    at Object.<anonymous> (/Users/pahud/repo/issue-triage/bin/issue-triage.ts:23:1)
    at Module._compile (node:internal/modules/cjs/loader:1254:14)
    at Module.m._compile (/Users/pahud/repo/issue-triage/node_modules/ts-node/src/index.ts:1618:23)
    at Module._extensions..js (node:internal/modules/cjs/loader:1308:10)
    at Object.require.extensions.<computed> [as .ts] (/Users/pahud/repo/issue-triage/node_modules/ts-node/src/index.ts:1621:12)
    at Module.load (node:internal/modules/cjs/loader:1117:32)
    at Function.Module._load (node:internal/modules/cjs/loader:958:12)
```

**Comment by sakshith007** [comment]
Same issue seen with 2.108.0 still . 
Installation is with npm install -g aws-cdk@2.105 . Please provide an update
