### ISSUE TITLE
(core): App Constructor Prevents Cdk Synth

### ISSUE THREAD

**Issue by Kapral67** [aws/aws-cdk#27949]
### Describe the bug

`new software.amazon.awscdk.App()` prevents `cdk synth`

### Expected Behavior

No Exception Thrown (as in v2.105.0 & v2.106.0)

### Current Behavior

```
SyntaxError: Unexpected end of input
    at internalCompileFunction (node:internal/vm:73:18)
    at wrapSafe (node:internal/modules/cjs/loader:1178:20)
    at Module._compile (node:internal/modules/cjs/loader:1220:27)
    at Module._extensions..js (node:internal/modules/cjs/loader:1310:10)
    at Module.load (node:internal/modules/cjs/loader:1119:32)
    at Module._load (node:internal/modules/cjs/loader:960:12)
    at Module.require (node:internal/modules/cjs/loader:1143:19)
    at require (node:internal/modules/cjs/helpers:119:18)
    at jsiiDeprecationWarnings (/tmp/jsii-kernel-Gt1yCb/node_modules/aws-cdk-lib/core/lib/stage.js:1:138)
    at new Stage (/tmp/jsii-kernel-Gt1yCb/node_modules/aws-cdk-lib/core/lib/stage.js:1:868)
        at software.amazon.jsii.JsiiRuntime.processErrorResponse(JsiiRuntime.java:150)
        at software.amazon.jsii.JsiiRuntime.requestResponse(JsiiRuntime.java:116)
        at software.amazon.jsii.JsiiClient.createObject(JsiiClient.java:89)
        at software.amazon.jsii.JsiiEngine.createNewObject(JsiiEngine.java:614)
        at software.amazon.awscdk.App.<init>(App.java:61)
```

### Reproduction Steps

```java
import software.amazon.awscdk.App;

public final class CdkApp {
    public static void main (final String[] args) {
        new App();  
    }
}
```

### CDK CLI Version

2.106.1

### Node.js Version

18.18.2

### OS

archlinux 6.6.1-arch1-1

### Language

Java

### Language Version

Java ( Corretto-17.0.9.8.1 (build 17.0.9+8-LTS) )

**Comment by pahud** [comment]
Are you still having this issue in the latest 2.108.0 ?

**Comment by Kapral67** [comment]
This issue doesn't affect me anymore after upgrading to 2.108.0
