### ISSUE TITLE
Construct works in TS but not in .NET

### ISSUE THREAD

**Issue by bdgmb2** [aws/aws-cdk#2812]
**Describe the bug**
Creating an EC2 Autoscaling group does not appear to work in the .NET bindings, even when reproducing the equivalent of the TypeScript example code found in the [CDK examples repo](https://github.com/aws-samples/aws-cdk-examples/blob/master/typescript/application-load-balancer/index.ts). The problem appears to be VPC/subnet related.

**To Reproduce**
I am using this .NET code that tries to mirror the TS example:
```
public class LoadBalancerStack : Amazon.CDK.Stack
    {
        public LoadBalancerStack(Amazon.CDK.App app, string ID, Amazon.CDK.StackProps props) : base(app, ID, props) {
            var vpc = new Amazon.CDK.AWS.EC2.Vpc(this, "VPC", new Amazon.CDK.AWS.EC2.VpcProps());

            var asg = new Amazon.CDK.AWS.AutoScaling.AutoScalingGroup(this, "ASG", new Amazon.CDK.AWS.AutoScaling.AutoScalingGroupProps()
            {
                Vpc = vpc,
                InstanceType = new Amazon.CDK.AWS.EC2.InstanceTypePair(InstanceClass.Burstable2, InstanceSize.Micro),
                MachineImage = new Amazon.CDK.AWS.EC2.AmazonLinuxImage(new Amazon.CDK.AWS.EC2.AmazonLinuxImageProps())
            });

            var lb = new Amazon.CDK.AWS.ElasticLoadBalancingV2.ApplicationLoadBalancer(this, "LB", new Amazon.CDK.AWS.ElasticLoadBalancingV2.ApplicationLoadBalancerProps()
            {
                Vpc = vpc,
                InternetFacing = true
            });

            var listener = lb.AddListener("Listener", new Amazon.CDK.AWS.ElasticLoadBalancingV2.ApplicationListenerProps()
            {
                Port = 80
            });

            listener.Connections.AllowDefaultPortFromAnyIpv4("Open to the world");

            asg.ScaleOnRequestCount("AModestLoad", new Amazon.CDK.AWS.AutoScaling.RequestCountScalingProps()
            {
                TargetRequestsPerSecond = 1
            });
        }
    }

    class Program
    {
        static void Main(string[] args)
        {
            var app = new Amazon.CDK.App(new Amazon.CDK.AppProps());
            var lbs = new LoadBalancerStack(app, "Stack", new Amazon.CDK.StackProps());
            app.Synth();
        }
    }
```
It builds successfully, but when attempting to generate templates (`cdk synth`), I get the following error:
```
Unhandled Exception: Amazon.JSII.Runtime.JsiiException: Got 'undefined' for non-optional instance of {"name":"subnetIds","type":{"collection":{"elementtype":{"primitive":"string"},"kind":"array"}}}
   at Amazon.JSII.Runtime.Services.Client.TryDeserialize[TResponse](String responseJson)
   at Amazon.JSII.Runtime.Services.Client.ReceiveResponse[TResponse]()
   at Amazon.JSII.Runtime.Services.Client.TryDeserialize[TResponse](String responseJson)
   at Amazon.JSII.Runtime.Services.Client.ReceiveResponse[TResponse]()
   at Amazon.JSII.Runtime.Services.Client.TryDeserialize[TResponse](String responseJson)
   at Amazon.JSII.Runtime.Services.Client.ReceiveResponse[TResponse]()
   at Amazon.JSII.Runtime.Deputy.DeputyBase..ctor(DeputyProps props)
   at KinesisTapCanaryPipeline.LoadBalancerStack..ctor(App app, String ID, StackProps props) in D:\Users\******\source\repos\********\**********\Program.cs:line 11
   at KinesisTapCanaryPipeline.Program.Main(String[] args) in D:\Users\********\source\repos\******\***********\Program.cs:line 43
```

**Expected behavior**
The code provided should generate CloudFormation templates... unless I am doing something wrong (which is also possible).

**Version:**
 - Windows 10
 - .NET Core 2.2
 - CDK Version 0.34

(Updated due to the wrong error being reported)

**Comment by rix0rrr** [comment]
When trying this code on `1.4.0`, I'm seeing some errors:

```
Unhandled Exception: Amazon.JSII.Runtime.JsiiException: Attach the AutoScalingGroup to an Application Load Balancer before calling scaleOnRequestCount()
```

Adding the following makes it work for me:

```cs
            listener.AddTargets("Default", new Amazon.CDK.AWS.ElasticLoadBalancingV2.Add­Application­Targets­Props() {
                Port = 80,
                Targets = new [] { asg }
            });
```

Closing this issue as it seems to be fixed. Please reopen if you feel I'm closing this in error.

**Comment by chefren** [comment]
Found that if using a Classic ELB, this still happens, is there another workaround for this case?
