### ISSUE TITLE
elasticache: Serverless cache attr_endpoint returning aws_cdk.Reference

### ISSUE THREAD

**Issue by Jmevorach** [aws/aws-cdk#28246]
### Describe the bug

The `attr_endpoint` attribute of the `CfnServerlessCache` should be a string or be resolvable to a string but instead it's `aws_cdk.Reference` instead. 

### Expected Behavior

I expected that this script should be able to run:
```
import aws_cdk as cdk
from aws_cdk import (
    Stack,
    aws_elasticache as elasticache,
    aws_ssm as ssm
)
from constructs import Construct
import os

class test_stack(Stack):

    def __init__(self, scope: Construct, construct_id: str, **kwargs) -> None:
        super().__init__(scope, construct_id, **kwargs)

        self.redis_cluster = elasticache.CfnServerlessCache(
            self,
            "RedisCluster",
            engine="redis",
            serverless_cache_name="ServerlessCache",
        )

        self.redis_endpoint = ssm.StringParameter(
            self,
            "redis-endpoint",
            parameter_name="redis_endpoint",
            string_value=self.redis_cluster.attr_endpoint
        )


if __name__ == "__main__":
    app = cdk.App()
    test_stack(app, "test",
    env=cdk.Environment(
        account=os.getenv('CDK_DEFAULT_ACCOUNT'),
        region=os.getenv('CDK_DEFAULT_REGION')
    ))
    app.synth()
```

### Current Behavior

Instead of running successfully this traceback is returned:
Traceback (most recent call last):
  File "/Users/home/test.py", line 32, in <module>
    test_stack(app, "test",
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/jsii/_runtime.py", line 118, in __call__
    inst = super(JSIIMeta, cast(JSIIMeta, cls)).__call__(*args, **kwargs)
  File "/Users/home/test.py", line 22, in __init__
    self.redis_endpoint = ssm.StringParameter(
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/jsii/_runtime.py", line 118, in __call__
    inst = super(JSIIMeta, cast(JSIIMeta, cls)).__call__(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/aws_cdk/aws_ssm/__init__.py", line 8397, in __init__
    props = StringParameterProps(
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/aws_cdk/aws_ssm/__init__.py", line 8924, in __init__
    check_type(argname="argument string_value", value=string_value, expected_type=type_hints["string_value"])
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/typeguard/__init__.py", line 785, in check_type
    raise TypeError(
TypeError: type of argument string_value must be str; got aws_cdk.Reference instead

### Reproduction Steps

Running this script below should reproduce the bug:
```
import aws_cdk as cdk
from aws_cdk import (
    Stack,
    aws_elasticache as elasticache,
    aws_ssm as ssm
)
from constructs import Construct
import os

class test_stack(Stack):

    def __init__(self, scope: Construct, construct_id: str, **kwargs) -> None:
        super().__init__(scope, construct_id, **kwargs)

        self.redis_cluster = elasticache.CfnServerlessCache(
            self,
            "RedisCluster",
            engine="redis",
            serverless_cache_name="ServerlessCache",
        )

        self.redis_endpoint = ssm.StringParameter(
            self,
            "redis-endpoint",
            parameter_name="redis_endpoint",
            string_value=self.redis_cluster.attr_endpoint
        )


if __name__ == "__main__":
    app = cdk.App()
    test_stack(app, "test",
    env=cdk.Environment(
        account=os.getenv('CDK_DEFAULT_ACCOUNT'),
        region=os.getenv('CDK_DEFAULT_REGION')
    ))
    app.synth()
```

### CDK CLI Version

2.113.0

### Node.js Version

v18.2.0

### OS

MacOS 13.5.2

### Language

Python

### Language Version

3.10

**Comment by pahud** [comment]
I haven't deployed this resource before it's pretty new but according to the [CFN doc](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-elasticache-serverlesscache.html)

Endpoint
Represents the information required for client programs to connect to a cache node.


And JS SDK
https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/ElastiCache.html#createServerlessCache-property


I guess it should be a json object that contains both Address and Port.

Are you able to return its address by `self.redis_cluster.attr_endpoint.address` or `attr_endpoint.get('Address')` ?

**Comment by Jmevorach** [comment]
Using `self.redis_cluster.attr_endpoint.address` gives `AttributeError: 'Reference' object has no attribute 'address'`.

Using `self.redis_cluster.attr_endpoint.get('Address')` gives `AttributeError: 'Reference' object has no attribute 'get'`.

**Comment by CEVO-MatheusJGSantos** [comment]
Same issue here. Oddly if I do `print("{}".format(self.resolve(myElasticache.get_att('Endpoint'))))` I will get a function that should work, but I can't use the actual object anywhere in my stack:  `{'Fn::GetAtt': ['serverlessRedisCache', 'Endpoint']}`

**Comment by jayhilden** [comment]
+1.  If I try to export the address I get an error using the TS client on 2.113.0

## Code
```
const redisServerlessCluster = new CfnServerlessCache(this, cacheName, {
            ...
        })

this.redisServerlessURI = "rediss://" + redisServerlessCluster.attrEndpoint
new CfnOutput(this,  'redisServerlessURI', {
    exportName: 'redisServerlessURI',
    value: this.redisServerlessURI,
})
```

## CFN Error
Requested attribute Endpoint must be a readonly property in schema for AWS::ElastiCache::ServerlessCache

**Comment by MatheusAfinovicz** [comment]
Having the same issue here with TS CDK.
Did a workaround with the SDK to get the DB using its name, and then accessing the endpoint:
```ts
        const client = new ElastiCacheClient({
		region
	});

	const describeServerlessCachesCommand = new DescribeServerlessCachesCommand({
		MaxResults: 20,
		ServerlessCacheName: your-db-name
	});

	const redis = await client.send(describeServerlessCachesCommand);

	if (!redis || !redis.ServerlessCaches) throw new Error('No redis found');

	const endpoint = redis.ServerlessCaches[0].Endpoint;

	if (!endpoint) throw new Error('No redis endpoint found');

	return `${endpoint.Address}:${endpoint.Port}`;
```

**Comment by ChadMoran** [comment]
I found a workaround.

```typescript
const cluster = new elasticache.CfnServerlessCache(this, 'RedisCluster', {
  serverlessCacheName: 'redis',
  engine: 'redis',
});

new cdk.CfnOutput(this, 'RedisEndpoint', {
  value: cluster.getAtt('Endpoint.Address').toString(),
});
```

You can also access `Endpoint.Port` as seen from `aws elasticache describe-serverless-caches`

It looks like the [docs](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-elasticache-serverlesscache.html) are out of date or incorrect. It seems that `.attr_Endpoint` should return the [`CfnServerlessCache.Endpoint`](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-elasticache-serverlesscache-endpoint.html) type.

**Comment by dang312** [comment]
Can confirm @ChadMoran  workaround work.
Currently I'm still encountering the issue on aws-cdk on 2.126.0 if not using the workaround.

**Comment by dtbayles** [comment]
i beg
