### ISSUE TITLE
CDK CodePipleine: Unable to find `.dot` file in `cdk.out` directory running `cdk deploy`

### ISSUE THREAD

**Issue by austinegri** [aws/aws-cdk#28320]
### Describe the bug

I cannot run some cdk commands. When running `cdk ls` or 'cdk deploy' I get the following response:

I am trying to follow the basic instructions at https://docs.aws.amazon.com/cdk/v2/guide/cdk_pipeline.html to institute a cdk pipeline.  I have the exact code listed in the tutorial.  I get the same issue when using `cdk deploy`.

### Expected Behavior

CDK to list stacks

### Current Behavior

Run: 

```
Error: ENOENT: no such file or directory, open '<projectdir>/cdk.out/<projectName>326AA0B4.dot'
    at Object.writeFileSync (node:fs:2352:20)
    at CodePipeline.doBuildPipeline (<projectdir>/node_modules/aws-cdk-lib/pipelines/lib/codepipeline/codepipeline.js:1:5821)
    at CodePipeline.buildPipeline (<projectdir>/node_modules/aws-cdk-lib/pipelines/lib/main/pipeline-base.js:1:2477)
    at CodePipeline.buildJustInTime (<projectdir>/node_modules/aws-cdk-lib/pipelines/lib/main/pipeline-base.js:1:2544)
    at Object.visit (<projectdir>/node_modules/aws-cdk-lib/pipelines/lib/main/pipeline-base.js:1:1489)
    at recurse (/<projectdir>/node_modules/aws-cdk-lib/core/lib/private/synthesis.js:2:2282)
    at recurse (<projectdir>/node_modules/aws-cdk-lib/core/lib/private/synthesis.js:2:2646)
    at recurse (<projectdir>/node_modules/aws-cdk-lib/core/lib/private/synthesis.js:2:2646)
    at invokeAspects (<projectdir>/node_modules/aws-cdk-lib/core/lib/private/synthesis.js:2:1906)
    at synthesize (<projectdir>/node_modules/aws-cdk-lib/core/lib/private/synthesis.js:1:1450) {
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: '<projectdir>cdk.out/<projectName>326AA0B4.dot'
}

Subprocess exited with error 1
```

### Reproduction Steps

run `cdk ls` or `cdk deploy`

```
cdk --version
2.113.0 (build ccd534a)
nodejs --version
v21.3.0
npm --version
10.2.4

Ubuntu 22.04.3 LTS
```

### CDK CLI Version

2.113.0 (build ccd534a)

### Node.js Version

v21.3.0

### OS

Ubuntu 22.04.3 LTS

### Language

TypeScript

**Comment by pahud** [comment]
Looks like you are using node v21 but it's not fully tested in CDK.

Have you tried node v20 and let us know if it works for you?

**Comment by pahud** [comment]
probably related to https://github.com/aws/aws-cdk/issues/28242

**Comment by austinegri** [comment]
This seems to bypass the issue thank you! I mustve missed the node version requirement
