### ISSUE TITLE
ssm: unable to use string values as content for CfnDocument

### ISSUE THREAD

**Issue by chrisrtaylor** [aws/aws-cdk#28341]
### Describe the bug

According to the documentation for the [content property of CfnDocument](https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_ssm.CfnDocument.html#content), it should be able to take an object representing JSON formatted content or a String if creating a YAML based document. When trying to use a string value for content, the document fails to create

### Expected Behavior

I should be able to define a document using a YAML formatted string as content. The following code should synthesize and create the appropriate resource:

```
    const ssmDoc = new ssm.CfnDocument(this, "TestSsmDoc", {
      content: `---
schemaVersion: "2.2"
description: "Test SSM doc for CDK."
mainSteps:
  - action: "aws:runShellScript"
    name: "test"
    inputs:
      runCommand: |
        echo "Hello, World!"
`,
      name: "TestSsmDocument",
      documentType: "Command",
      documentFormat: "YAML",
    });
``` 

### Current Behavior

The above code fails to synthesize with the following error:

```
CfnSynthesisError: Resolution error: Supplied properties not correct for "CfnDocumentProps"
  content: "---\nschemaVersion: \"2.2\"\ndescription: \"Test SSM doc for CDK.\"\nmainSteps:\n  - action: \"aws:runShellScript\"\n    name: \"test\"\n    inputs:\n      runCommand: |\n        echo \"Hello, World!\"\n" should be an 'object'.
    at ValidationResult.assertSuccess (<PROJECT_ROOT>/node_modules/.pnpm/aws-cdk-lib@2.114.1_constructs@10.3.0/node_modules/aws-cdk-lib/core/lib/runtime.js:1:2707)
    at convertCfnDocumentPropsToCloudFormation (<PROJECT_ROOT>/node_modules/.pnpm/aws-cdk-lib@2.114.1_constructs@10.3.0/node_modules/aws-cdk-lib/aws-ssm/lib/ssm.generated.js:1:24518)
    at CfnDocument.renderProperties (<PROJECT_ROOT>/node_modules/.pnpm/aws-cdk-lib@2.114.1_constructs@10.3.0/node_modules/aws-cdk-lib/aws-ssm/lib/ssm.generated.js:1:18952)
    at PostResolveToken.Resources (<PROJECT_ROOT>/node_modules/.pnpm/aws-cdk-lib@2.114.1_constructs@10.3.0/node_modules/aws-cdk-lib/core/lib/cfn-resource.js:1:7779)
    at PostResolveToken.postProcess (<PROJECT_ROOT>/node_modules/.pnpm/aws-cdk-lib@2.114.1_constructs@10.3.0/node_modules/aws-cdk-lib/core/lib/util.js:1:1653)
    at Object.postProcess (<PROJECT_ROOT>/node_modules/.pnpm/aws-cdk-lib@2.114.1_constructs@10.3.0/node_modules/aws-cdk-lib/core/lib/private/resolve.js:1:1205)
    at DefaultTokenResolver.resolveToken (<PROJECT_ROOT>/node_modules/.pnpm/aws-cdk-lib@2.114.1_constructs@10.3.0/node_modules/aws-cdk-lib/core/lib/resolvable.js:1:1483)
    at resolve (<PROJECT_ROOT>/node_modules/.pnpm/aws-cdk-lib@2.114.1_constructs@10.3.0/node_modules/aws-cdk-lib/core/lib/private/resolve.js:1:2711)
    at Object.resolve (<PROJECT_ROOT>/node_modules/.pnpm/aws-cdk-lib@2.114.1_constructs@10.3.0/node_modules/aws-cdk-lib/core/lib/private/resolve.js:1:1079)
    at resolve (<PROJECT_ROOT>/node_modules/.pnpm/aws-cdk-lib@2.114.1_constructs@10.3.0/node_modules/aws-cdk-lib/core/lib/private/resolve.js:1:2990) {
  type: 'CfnSynthesisError'
}
```

If I wrap the string literal in `new String(...)`, the stack synthesizes, but does so incorrectly. It renders the context as an indexed dictionary of the string array which fails to create the resource with the error `Resource handler returned message: "Invalid request provided: Missing "schemaVersion" in the document.`:

```
Resources:
  TestSsmDoc:
    Type: AWS::SSM::Document
    Properties:
      Content:
        "0": "-"
        "1": "-"
        "2": "-"
        "3": "\n"
        "4": s
        "5": c
        "6": h
        "7": e
        "8": m
        "9": a
        "10": V
        "11": e
        "12": r
        "13": s
        "14": i
        "15": o
        "16": "n"
        "17": ":"
        "18": " "
        "19": '"'
        "20": "2"
        "21": "."
        "22": "2"
<snip>
```

### Reproduction Steps

Create a stack with the following stack and attempt to synthesize the stack:

```
import * as cdk from "aws-cdk-lib";
import { Construct } from "constructs";
import * as ssm from "aws-cdk-lib/aws-ssm";

export class TestStack extends cdk.Stack {
  constructor(scope: Construct, id: string, props?: cdk.StackProps) {
    super(scope, id, props);

    const ssmDoc = new ssm.CfnDocument(this, "TestSsmDoc", {
      content: `---
schemaVersion: "2.2"
description: "Test SSM doc for CDK."
mainSteps:
  - action: "aws:runShellScript"
    name: "test"
    inputs:
      runCommand: |
        echo "Hello, World!"
`,
      name: "TestSsmDocument",
      documentType: "Command",
      documentFormat: "YAML",
    });
  }
}
```

### CDK CLI Version

2.114.1 (build 02bbb1d)

### Node.js Version

v18.16.1

### OS

Mac OS X

### Language

TypeScript

### Language Version

Typescript (5.2.2)

**Comment by pahud** [comment]
This is a little bit tricky but I was able to synthesize with this:

```ts
    const content = yaml.parse(fs.readFileSync(path.join(__dirname, './demo.yaml')).toString());
    new ssm.CfnDocument(this, "TestSsmDoc", {
      content,
      name: "TestSsmDocument",
      documentType: "Command",
      documentFormat: "YAML",
    });
```

And I got this

```yaml
  TestSsmDoc:
    Type: AWS::SSM::Document
    Properties:
      Content:
        schemaVersion: "2.2"
        description: Test SSM doc for CDK.
        mainSteps:
          - action: aws:runShellScript
            name: test
            inputs:
              runCommand: |
                echo "Hello, World!"
      DocumentFormat: YAML
      DocumentType: Command
      Name: TestSsmDocument
```

Let me know if it works for you.

**Comment by chrisrtaylor** [comment]
Yes, wrapping the string content with the yaml library does work and is an okay work around. However, the documentation linked above indicates that the `content` property does accept the String type which is still a problem.

**Comment by pahud** [comment]
> Yes, wrapping the string content with the yaml library does work and is an okay work around. However, the documentation linked above indicates that the `content` property does accept the String type which is still a problem.


This is because CDK uses cfn2ts to convert CloudFormation specifications to L1 constructs. When CloudFormation specifies `Type: Json` (which accepts both JSON objects and strings), our `cfn2ts` tool conservatively converts it to only accept JSON objects in CDK L1 constructs.

The CloudFormation specification itself correctly supports both types, but CDK's code generation is more restrictive than the underlying CloudFormation service. This is why the YAML parsing workaround works - it converts the string content to a JSON object, satisfying CDK's validation while still producing valid CloudFormation.

**Comment by kobe9286** [comment]
Is there a workaround for `documentFormat:TEXT`?

**Comment by nshiwaku** [comment]
@kobe9286 
> Is there a workaround for documentFormat:TEXT?

For the `DocumentFormat: TEXT` case, a workaround using `addPropertyOverride` works for me. Note that `cfn-lint` flags the synthesized template with [E3051](https://github.com/aws-cloudformation/cfn-lint/blob/main/docs/rules.md), but it deploys and works fine in practice.

E3051 validates the structure of an SSM document by treating Content as nested JSON/YAML. A ChangeCalendar document, however, is iCalendar text (DocumentFormat: TEXT), not a schema-based document, so cfn-lint can't parse it and reports a false positive. The deployment itself succeeds.

The `DocumentFormat: TEXT` case is an important use case in its own right — it was also reported separately in [#35583](https://github.com/aws/aws-cdk/issues/35583), where the exact `ChangeCalendar` example fails to synthesize because content won't accept a string.


```ts
import * as cdk from 'aws-cdk-lib/core';
import {
  aws_ssm as ssm,
} from 'aws-cdk-lib'
import { Construct } from 'constructs';

export class ServicecatalogStack extends cdk.Stack {
  constructor(scope: Construct, id: string, props?: cdk.StackProps) {
    super(scope, id, props);

    const changeCalendar = new ssm.CfnDocument(this, 'Document', {
      name: "ChangeCalendar",
      documentType: "ChangeCalendar",
      documentFormat: "TEXT",
      content: {}
    })

    changeCalendar.addPropertyOverride(
      'Content',
      'BEGIN:VCALENDAR\r\nPRODID:-//AWS//Change Calendar 1.0//EN\r\nVERSION:2.0\r\nX-CALENDAR-TYPE:DEFAULT_OPEN\r\nX-WR-CALDESC:test\r\nBEGIN:VTODO\r\nDTSTAMP:20200320T004207Z\r\nUID:3b5af39a-d0b3-4049-a839-d7bb8af01f92\r\nSUMMARY:Add events to this calendar.\r\nEND:VTODO\r\nEND:VCALENDAR\r\n',
    )
  }
}
```
