### ISSUE TITLE
batch: EksContainerDefinition image from ECR raises RuntimeError: Cannot read property 'obtainExecutionRole' of undefined

### ISSUE THREAD

**Issue by zaremb** [aws/aws-cdk#28417]
### Describe the bug

When specifying EKS task in batch module like this:
```
container_definition = batch.EksContainerDefinition(
            self,
            f"foo",
            image=ecs.ContainerImage.from_ecr_repository(
            repository, image_tag
        ),
            image_pull_policy=batch.ImagePullPolicy.ALWAYS,
            volumes=[
                batch.EksVolume.empty_dir(
                    name="myEmptyDirVolume",
                    mount_path="/mount/path",
                    medium=batch.EmptyDirMediumType.MEMORY,
                    readonly=True,
                    size_limit=Size.mebibytes(2048),
                )
            ],
        )

```
part `ecs.ContainerImage.from_ecr_repository` raises `RuntimeError: Cannot read property 'obtainExecutionRole' of undefined`.

CDK version:   CDK_CLI_VERSION: '2.115.0', Python

### Expected Behavior

Image is successfully set

### Current Behavior

```
RuntimeError: Cannot read property 'obtainExecutionRole' of undefined
```

### Reproduction Steps

Run CDK synth with the code above

### CDK CLI Version

2.115.0 (build 58027ee)

### Node.js Version

v16.0.0

### OS

Amazon Linux

### Language

Python

### Language Version

3.11

**Comment by pahud** [comment]
I reproduced this in typescript. Error message below:

```
                                                      ^
TypeError: Cannot read properties of undefined (reading 'obtainExecutionRole')
    at EcrImage.bind (/projects/issue-triage/node_modules/aws-cdk-lib/aws-ecs/lib/images/ecr.js:1:1133)
    at new EksContainerDefinition (/projects/issue-triage/node_modules/aws-cdk-lib/aws-batch/lib/eks-container-definition.js:1:2087)
    at new Stack5 (/projects/issue-triage/lib/issue-triage-stack.ts:119:33)
    at Object.<anonymous> (/projects/issue-triage/bin/issue-triage.ts:19:16)
    at Module._compile (node:internal/modules/cjs/loader:1241:14)
    at Module.m._compile (/projects/issue-triage/node_modules/ts-node/src/index.ts:1618:23)
    at Module._extensions..js (node:internal/modules/cjs/loader:1295:10)
    at Object.require.extensions.<computed> [as .ts] (/projects/issue-triage/node_modules/ts-node/src/index.ts:1621:12)
    at Module.load (node:internal/modules/cjs/loader:1091:32)
    at Function.Module._load (node:internal/modules/cjs/loader:938:12)
```

https://github.com/aws/aws-cdk/blob/52a5579aa52c88bb289a7a9677c35385763c8fff/packages/aws-cdk-lib/aws-batch/lib/eks-container-definition.ts#L576

The bind() essentually creates EcrImage() 

https://github.com/aws/aws-cdk/blob/52a5579aa52c88bb289a7a9677c35385763c8fff/packages/aws-cdk-lib/aws-ecs/lib/container-image.ts#L22-L24

which expects ecs task definition

https://github.com/aws/aws-cdk/blob/52a5579aa52c88bb289a7a9677c35385763c8fff/packages/aws-cdk-lib/aws-ecs/lib/images/ecr.ts#L29

But obviously eks container def does not have that.

**Comment by zaremb** [comment]
I found workaround:
Inside container definition, one can specify image to be `ContainerImage.from_registry(...)`. This skips the grantPull. I.e. this fixed it for me:
```
ecs.ContainerImage.from_registry(
            my_ecr_repo.repository_uri_for_tag(my_image_tag)
        )

```

**Comment by pahud** [comment]
@zaremb Thank you! Nice workaround!
