### ISSUE TITLE
(aws-route53): stack update doesn't work when defining Route53 via AwsCustomResource

### ISSUE THREAD

**Issue by MyNameIsOka** [aws/aws-cdk#28906]
### Describe the bug

It's basically a continuation of issue https://github.com/aws/aws-cdk/issues/12756
The proposed solution is working for deploying but doesn't work if I need to update the stack or when destroying and re-deploying it.

The error thrown is:
```
/home/runner/work/my-repo/my-repo/packages/infrastructure/node_modules/constructs/src/construct.ts:447
      throw new Error(`There is already a Construct with name '${childName}' in ${typeName}${name.length > 0 ? ' [' + name + ']' : ''}`);
            ^
Error: There is already a Construct with name 'CreatedPublicHostedZone' in PublicHostedZoneWithReusableDelegationSet [MyHostedZone]
    at Node.addChild (/home/runner/work/my-repo/my-repo/packages/infrastructure/node_modules/constructs/src/construct.ts:447:13)
    at new Node (/home/runner/work/my-repo/my-repo/packages/infrastructure/node_modules/constructs/src/construct.ts:71:17)
    at new Construct (/home/runner/work/my-repo/my-repo/packages/infrastructure/node_modules/constructs/src/construct.ts:499:17)
    at new Resource (/home/runner/work/my-repo/my-repo/packages/infrastructure/node_modules/aws-cdk-lib/core/lib/resource.js:1:1309)
    at new Import (/home/runner/work/my-repo/my-repo/packages/infrastructure/node_modules/aws-cdk-lib/aws-route53/lib/hosted-zone.js:1:1887)
    at Function.fromHostedZoneAttributes (/home/runner/work/my-repo/my-repo/packages/infrastructure/node_modules/aws-cdk-lib/aws-route53/lib/hosted-zone.js:1:2154)
    at PublicHostedZoneWithReusableDelegationSet.asPublicHostedZone (/home/runner/work/my-repo/my-repo/packages/infrastructure/src/my-repo-stack.ts:106:27)
    at new LodzInfraCdkStack (/home/runner/work/my-repo/my-repo/packages/infrastructure/src/my-repo-stack.ts:360:21)
    at Object.<anonymous> (/home/runner/work/my-repo/my-repo/packages/infrastructure/src/my-repo-stack.ts:575:1)
    at Module._compile (node:internal/modules/cjs/loader:1356:14)
Subprocess exited with error 1
```

### Expected Behavior

Being able to update the stack successfully.

### Current Behavior

Stack throws the error `There is already a Construct with name 'CreatedPublicHostedZone' in PublicHostedZoneWithReusableDelegationSet`

### Reproduction Steps

Deploy a stack with this resources:

```
// Allows CDK to use a reusable delegation set. Sourced from:
// https://pablissimo.com/1100/creating-a-route-53-public-hosted-zone-with-a-reusable-delegation-set-id-in-cdk

import {
  AwsCustomResource,
  AwsCustomResourcePolicy,
} from "@aws-cdk/custom-resources";
import { Construct, Fn, Names } from "@aws-cdk/core";
import {
  IPublicHostedZone,
  PublicHostedZone,
  PublicHostedZoneProps,
} from "@aws-cdk/aws-route53";
import { PhysicalResourceId } from "@aws-cdk/custom-resources";

export interface PublicHostedZoneWithReusableDelegationSetProps
  extends PublicHostedZoneProps {
  delegationSetId: string;
}

export class PublicHostedZoneWithReusableDelegationSet extends Construct {
  private publicHostedZone: AwsCustomResource;
  private hostedZoneName: string;

  constructor(
    scope: Construct,
    id: string,
    props: PublicHostedZoneWithReusableDelegationSetProps
  ) {
    super(scope, id);

    this.hostedZoneName = props.zoneName;

    const normaliseId = (id: string) => id.split("/").slice(-1)[0];
    const normalisedDelegationSetId = normaliseId(props.delegationSetId);

    this.publicHostedZone = new AwsCustomResource(
      this,
      "CreatePublicHostedZone",
      {
        onCreate: {
          service: "Route53",
          action: "createHostedZone",
          parameters: {
            CallerReference: Names.uniqueId(this),
            Name: this.hostedZoneName,
            DelegationSetId: normalisedDelegationSetId,
            HostedZoneConfig: {
              Comment: props.comment,
              PrivateZone: false,
            },
          },
          physicalResourceId: PhysicalResourceId.fromResponse("HostedZone.Id"),
        },
        policy: AwsCustomResourcePolicy.fromSdkCalls({
          resources: AwsCustomResourcePolicy.ANY_RESOURCE,
        }),
      }
    );

    new AwsCustomResource(this, "DeletePublicHostedZone", {
      onDelete: {
        service: "Route53",
        action: "deleteHostedZone",
        parameters: {
          Id: this.publicHostedZone.getResponseField("HostedZone.Id"),
        },
      },
      policy: AwsCustomResourcePolicy.fromSdkCalls({
        resources: AwsCustomResourcePolicy.ANY_RESOURCE,
      }),
    });
  }

  asPublicHostedZone(): IPublicHostedZone {
    return PublicHostedZone.fromHostedZoneAttributes(
      this,
      "CreatedPublicHostedZone",
      {
        hostedZoneId: Fn.select(
          2,
          Fn.split("/", this.publicHostedZone.getResponseField("HostedZone.Id"))
        ),
        zoneName: this.hostedZoneName,
      }
    );
  }
}
```

### CDK CLI Version

2.122.0

### Node.js Version

20.8.0

### OS

Ubuntu

### Language

TypeScript

### Language Version

5.3.3

**Comment by MyNameIsOka** [comment]
Okay, the reason was that I called `asPublicHostedZone` twice. They would have the same `id` and therefore the deployment would fail. I changed the code to this and then the deployment worked:
```
asPublicHostedZone(uniqueId: string): IPublicHostedZone {
  return PublicHostedZone.fromHostedZoneAttributes(
    this,
    `CreatedPublicHostedZone-${uniqueId}`,
    {
      hostedZoneId: Fn.select(
        2,
        Fn.split(
          "/",
          this.publicHostedZone.getResponseField("HostedZone.Id"),
        ),
      ),
      zoneName: this.hostedZoneName,
    },
  );
}

// ...

const certificate = new cdk.aws_certificatemanager.Certificate(
  this,
  "SiteCertificate",
  {
    domainName: DOMAIN,
    validation: cdk.aws_certificatemanager.CertificateValidation.fromDns(
      hostedZone.asPublicHostedZone("certificate"),
    ),
  },
);
```

**Comment by pahud** [comment]
Thank you for the report.
