### ISSUE TITLE
integ-runner: "Could not checkout snapshot directory" seems to uses wrong path

### ISSUE THREAD

**Issue by jvalore-medallia** [aws/aws-cdk#29278]
### Describe the bug

Running `integ-runner` results in a git failures:

```
Running test /Users/jvalore/Projects/mindful-composer2/test/integ.getConfiguration.ts in us-east-1
error: pathspec 'integ.getConfiguration.ts.snapshot' did not match any file(s) known to git
  SUCCESS    integ.getConfiguration-GetAppConfigurationLambda/DefaultTest 248.229s
       AssertionResultsLambdaInvoked2f382cf205e7f04c4f85bed1cc026bf - success
      AssertionResultsLambdaInvoke3c6d8322bda64b60f1d6ee49af533865 - success

Test Results:

Tests:    1 passed, 1 total
Could not checkout snapshot directory 'test/integ.getConfiguration.ts.snapshot'. Please verify the following command completes correctly:
git checkout $(git merge-base HEAD main) -- integ.getConfiguration.ts.snapshot
error: Error: Command exited with status 1
    at exec2 (/Users/jvalore/Projects/mindful-composer2/node_modules/@aws-cdk/integ-runner/lib/workers/extract/index.js:12932:11)
    at IntegTestRunner.checkoutSnapshot (/Users/jvalore/Projects/mindful-composer2/node_modules/@aws-cdk/integ-runner/lib/workers/extract/index.js:20124:13)
    at IntegTestRunner.deploy (/Users/jvalore/Projects/mindful-composer2/node_modules/@aws-cdk/integ-runner/lib/workers/extract/index.js:20420:18)
    at IntegTestRunner.runIntegTestCase (/Users/jvalore/Projects/mindful-composer2/node_modules/@aws-cdk/integ-runner/lib/workers/extract/index.js:20199:37)
    at Function.integTestWorker (/Users/jvalore/Projects/mindful-composer2/node_modules/@aws-cdk/integ-runner/lib/workers/extract/index.js:30637:34)
    at MessagePort.<anonymous> (/Users/jvalore/Projects/mindful-composer2/node_modules/@aws-cdk/integ-runner/lib/workers/extract/index.js:967:31)
    at [nodejs.internal.kHybridDispatch] (node:internal/event_target:807:20)
    at exports.emitMessage (node:internal/per_context/messageport:23:28)
```

The message:
```
Could not checkout snapshot directory 'test/integ.getConfiguration.ts.snapshot'. Please verify the following command completes correctly:
git checkout $(git merge-base HEAD main) -- integ.getConfiguration.ts.snapshot
```
Looks like it doesn't include the `test/`path in the `git` command.

### Expected Behavior

Test should pass and update snapshot. (Ideally there shouldn't be `git` lock-in here either, but I guess that is a different discussion).

### Current Behavior

(See error message above)

### Reproduction Steps

Have an test in the default `test/` directory. In my case `test/integ.getConfiguration.ts`

Run `integ-runner --force` once. The snapshot is created in
```
test/integ.getConfiguration.ts.snapshot
```

`git add` and `git commit` the snapshot, as is recommended in the integ-runner docs.

Run `integ-runner --force` again.
Results in the error message listed above.

### CDK CLI Version

2.129.0 (build d5ab0df)

### Node.js Version

v20.9.0

### OS

Mac

### Language

TypeScript

### Language Version

4.8.4

**Comment by pahud** [comment]
Unfortunate I can't reproduce this.

When I run `npx integ-runner --force` for the 2nd time, it just deploys with test UNCHANGED.

<img width="1145" alt="image" src="https://github.com/aws/aws-cdk/assets/278432/1a9a5c74-ceb4-475b-a48b-b76dc5bdb52e">

**Comment by jvalore-medallia** [comment]
@pahud thanks for attempting. I'll see if I can catch it happen again, and if it does I'll try to debug into cdk a bit...

**Comment by jvalore-medallia** [comment]
I haven't had this error happen again, so going to close this issue for now.

**Comment by jvalore-medallia** [comment]
@pahud I am reopening this issue since I got it to happen again.

I think this happens if you work on a branch, and your `main` branch doesn't have the snapshots yet.

This comment doesn't really make sens to me: https://github.com/aws/aws-cdk/blob/main/packages/@aws-cdk/integ-runner/lib/runner/integ-test-runner.ts#L94-L105

```
      /**
       * When running integration tests with the update path workflow
       * it is important that the snapshot that is deployed is the current snapshot
       * from the upstream branch. In order to guarantee that, first checkout the latest
       * (to the user) snapshot from upstream
       *
       * It is not straightforward to figure out what branch the current
       * working branch was created from. This is a best effort attempt to do so.
       * This assumes that there is an 'origin'. `git remote show origin` returns a list of
       * all branches and we then search for one that starts with `HEAD branch: `
       */
```

But that function tries to overwrite your current snapshot in your branch with whatever is in `main`. So in my case, my current branch has a new feature which makes a new snapshot, and `main` doesn't have that snapshot. So I get the originally noted `git` error.

So in my repro steps, that would mean doing a `git checkout -b newfeature` and making a new `test/integ.newfeature.ts` test in that branch. Then running `integ-test` will try to `git checkout -- test/integ.newfeature.ts` from the `main` branch, where it doesn't exist.

---

Is this checkout logic specific to how aws operates and uses this to test cdk itself? It doesn't seem valid for general/public use... what branch I'm currently working in has no relation to `main`. Why can't the current snapshot just be checked without trying to re-pull it from a completely different branch?

**Comment by graydenshand** [comment]
Between this issue and https://github.com/aws/aws-cdk/issues/31069, the stack update workflow is pretty unusable (at least for my projects). It seems like a really useful feature, but it has caused a lot of frustration in its current implementation.

If these issues can't be addressed, maybe the default behavior should change to reduce the friction for new users. I.e. make the stack update workflow opt-in rather than opt-out.
