### ISSUE TITLE
deploy: byte-order-mark (BOM) in existing cf template causes YAMLSyntaxError and fails deployment

### ISSUE THREAD

**Issue by markdchurchill** [aws/aws-cdk#29792]
### Describe the bug

When performing manual tweaks to stacks in the console (eg - migrating resources into nested) users can provide a template that starts with a byte-order-mark and this is accepted by the console.

On subsequent deployments using CDK this causes a deployment failure. Updating the stack in console to remove the BOM fixes the issue.

### Expected Behavior

aws-cdk should not have different behaviour to the console upload

### Current Behavior

```
XXXXXXXX: deploying... [1/1]
❌  XXXXXXXXX failed: YAMLSyntaxError: All collection items must start at the same column
    at _Collection.parse (/usr/lib/node_modules/aws-cdk/lib/index.js:401:9191)
    at /usr/lib/node_modules/aws-cdk/lib/index.js:401:28601
    at _Document.parseContents (/usr/lib/node_modules/aws-cdk/lib/index.js:401:13915)
    at _Document.parse (/usr/lib/node_modules/aws-cdk/lib/index.js:401:14863)
    at Object.parse2 [as parse] (/usr/lib/node_modules/aws-cdk/lib/index.js:401:31141)
    at parseDocument (/usr/lib/node_modules/aws-cdk/lib/index.js:423:9258)
    at Object.parse2 (/usr/lib/node_modules/aws-cdk/lib/index.js:423:9537)
    at parseYamlStrWithCfnTags (/usr/lib/node_modules/aws-cdk/lib/index.js:423:12316)
    at deserialize (/usr/lib/node_modules/aws-cdk/lib/index.js:423:1[1915](https://gitlab.championdata.com/platform/core-afl/-/jobs/490918#L1915))
    at deserializeStructure (/usr/lib/node_modules/aws-cdk/lib/index.js:423:12857) {
  source: [_Collection]
}
```

### Reproduction Steps

- Deploy a simple stack with aws-cdk
- Pull the template from the console, edit it, add a byte-order-mark, and update the stack
- Attempt to deploy against that stack with aws-cdk

### CDK CLI Version

2.136.0 (build 94fd33b)

### Node.js Version

v18.20.1

### OS

Debian 12

### Language

.NET

### Language Version

8.0.203

**Comment by pahud** [comment]
>Pull the template json from the console, edit it, add a byte-order-mark, and update the stack


This seems to be an edge case. Can you explain why you need to do this?

**Comment by markdchurchill** [comment]
Obviously the BOM isn't being added intentionally - but editors will do this to files. If this is valid CF then cdk should work with it - if it is not valid CF then the console should reject it. At minimum cdk should produce accurate error messages.

This won't catch me out again, but others might not be so lucky to spot the issue.
