### ISSUE TITLE
Golang CDK: synth fails when using lazy string due to circular reference

### ISSUE THREAD

**Issue by tdenniston** [aws/aws-cdk#29906]
### Describe the bug

This is probably specific to the Go CDK bindings, or it is also possible I am misunderstanding the use of the lazy string mechanism. When I try to use the `awscdk.Lazy_String` method for e.g. a log group name, synth fails due to a circular reference:

```
$ CDK_DEBUG=true cdk synth
panic: TypeError: Resolution error: Resolution error: Resolution error: Converting circular structure to JSON
    --> starting at object with constructor 'CfnLogGroup'
    |     property 'node' -> object with constructor 'Node'
    --- property 'host' closes the circle.
Object creation stack:
  at Lazy.string (/tmp/jsii-kernel-u0LhzS/node_modules/aws-cdk-lib/core/lib/lazy.js:1:953)
  at /tmp/jsii-runtime.3237986321/lib/program.js:9876:152
  at Kernel._Kernel_ensureSync (/tmp/jsii-runtime.3237986321/lib/program.js:10480:24)
  at Kernel.sinvoke (/tmp/jsii-runtime.3237986321/lib/program.js:9876:102)
  at KernelHost.processRequest (/tmp/jsii-runtime.3237986321/lib/program.js:11696:36)
  at KernelHost.run (/tmp/jsii-runtime.3237986321/lib/program.js:11656:22)
  at Immediate._onImmediate (/tmp/jsii-runtime.3237986321/lib/program.js:11657:46)
  at process.processImmediate (node:internal/timers:476:21)..
```

See below for a very simple example that reproduces the issue.

### Expected Behavior

Able to use the `awscdk.Lazy_String` function.

### Current Behavior

Synth fails when using the `awscdk.Lazy_String` function.

### Reproduction Steps

Complete example:

```go
package main

import (
	"github.com/aws/aws-cdk-go/awscdk/v2"
	"github.com/aws/aws-cdk-go/awscdk/v2/awslogs"

	"github.com/aws/jsii-runtime-go"
)

type LazyString struct{}

func (l *LazyString) Produce() *string {
	s := "value"
	return &s
}

func main() {
	defer jsii.Close()

	app := awscdk.NewApp(nil)
	stack := awscdk.NewStack(app, jsii.String("stack"), &awscdk.StackProps{})

	lazy := &LazyString{}
	awslogs.NewLogGroup(stack, jsii.String("log-group"), &awslogs.LogGroupProps{
		LogGroupName: awscdk.Lazy_String(lazy, &awscdk.LazyStringValueOptions{}),
	})

	app.Synth(nil)
}

```

Then just run cdk synth, and it will fail.

### CDK CLI Version

2.137.0 (build bb90b4c)

### Node.js Version

18.18.2

### OS

Linux

### Language

Go

### Language Version

go version go1.20.12 linux/amd64

**Comment by ashishdhingra** [comment]
Reproducible. Similar code below in TypeScript works:
```TypeScript
import * as cdk from 'aws-cdk-lib';
import * as awslogs from 'aws-cdk-lib/aws-logs';
import { TypescriptStack } from '../lib/typescript-stack';

const app = new cdk.App();

const stack = new cdk.Stack(app, 'MyStack');
new awslogs.LogGroup(stack, 'log-group', {
    logGroupName: cdk.Lazy.string({
        produce() {
            return 'value';
        }})
});
```
