### ISSUE TITLE
bedrock: L1 constructs error

### ISSUE THREAD

**Issue by Samir-AWS** [aws/aws-cdk#29966]
### Describe the bug

Bedrock L1 constructs have been added via https://github.com/aws/aws-cdk/pull/29911 in version 2.139.0

**Issue1**
Unable to use cdk migrate to generate it from a CloudFormation stack

```
$ cdk migrate --stack-name Test2 --from-path ./test2.yml --language csharp

This command is an experimental feature.
 ❌  Migrate failed for `Test2`: Test2Stack could not be generated because Name is not a valid property for resource BedrockKnowledgeBase of type AWS::Bedrock::KnowledgeBase

Test2Stack could not be generated because Name is not a valid property for resource BedrockKnowledgeBase of type AWS::Bedrock::KnowledgeBase
```

**Issue2**
[CfnKnowledgeBase](https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_bedrock.CfnKnowledgeBase.html) class is missing a required property `StorageConfiguration` in [CfnKnowledgeBaseProps](https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_bedrock.CfnKnowledgeBaseProps.html)

**Issue3**
I tried to deploy without this property anyway and ran into another issue-

```
$ cdk synth

<successfully synthesises - output omitted>

$ cdk deploy

Test: deploying... [1/1]
Test: creating CloudFormation changeset...

 ❌  Test failed: Error [ValidationError]: Template format error: Unrecognized resource types: [AWS::Bedrock::DataSource, AWS::Bedrock::KnowledgeBase]
    at Request.extractError (/usr/local/Cellar/aws-cdk/2.139.0/libexec/lib/node_modules/aws-cdk/lib/index.js:385:46692)
    at Request.callListeners (/usr/local/Cellar/aws-cdk/2.139.0/libexec/lib/node_modules/aws-cdk/lib/index.js:385:91559)
    at Request.emit (/usr/local/Cellar/aws-cdk/2.139.0/libexec/lib/node_modules/aws-cdk/lib/index.js:385:91007)
    at Request.emit (/usr/local/Cellar/aws-cdk/2.139.0/libexec/lib/node_modules/aws-cdk/lib/index.js:385:199533)
    at Request.transition (/usr/local/Cellar/aws-cdk/2.139.0/libexec/lib/node_modules/aws-cdk/lib/index.js:385:193085)
    at AcceptorStateMachine.runTo (/usr/local/Cellar/aws-cdk/2.139.0/libexec/lib/node_modules/aws-cdk/lib/index.js:385:157957)
    at /usr/local/Cellar/aws-cdk/2.139.0/libexec/lib/node_modules/aws-cdk/lib/index.js:385:158287
    at Request.<anonymous> (/usr/local/Cellar/aws-cdk/2.139.0/libexec/lib/node_modules/aws-cdk/lib/index.js:385:193377)
    at Request.<anonymous> (/usr/local/Cellar/aws-cdk/2.139.0/libexec/lib/node_modules/aws-cdk/lib/index.js:385:199608)
    at Request.callListeners (/usr/local/Cellar/aws-cdk/2.139.0/libexec/lib/node_modules/aws-cdk/lib/index.js:385:91727) {
  code: 'ValidationError',
  time: 2024-04-25T23:56:02.578Z,
  requestId: 'f5515800-5335-434b-9df6-d930bcf788c4',
  statusCode: 400,
  retryable: false,
  retryDelay: 236.99598614253415
}

 ❌ Deployment failed: Error [ValidationError]: Template format error: Unrecognized resource types: [AWS::Bedrock::DataSource, AWS::Bedrock::KnowledgeBase]
    at Request.extractError (/usr/local/Cellar/aws-cdk/2.139.0/libexec/lib/node_modules/aws-cdk/lib/index.js:385:46692)
    at Request.callListeners (/usr/local/Cellar/aws-cdk/2.139.0/libexec/lib/node_modules/aws-cdk/lib/index.js:385:91559)
    at Request.emit (/usr/local/Cellar/aws-cdk/2.139.0/libexec/lib/node_modules/aws-cdk/lib/index.js:385:91007)
    at Request.emit (/usr/local/Cellar/aws-cdk/2.139.0/libexec/lib/node_modules/aws-cdk/lib/index.js:385:199533)
    at Request.transition (/usr/local/Cellar/aws-cdk/2.139.0/libexec/lib/node_modules/aws-cdk/lib/index.js:385:193085)
    at AcceptorStateMachine.runTo (/usr/local/Cellar/aws-cdk/2.139.0/libexec/lib/node_modules/aws-cdk/lib/index.js:385:157957)
    at /usr/local/Cellar/aws-cdk/2.139.0/libexec/lib/node_modules/aws-cdk/lib/index.js:385:158287
    at Request.<anonymous> (/usr/local/Cellar/aws-cdk/2.139.0/libexec/lib/node_modules/aws-cdk/lib/index.js:385:193377)
    at Request.<anonymous> (/usr/local/Cellar/aws-cdk/2.139.0/libexec/lib/node_modules/aws-cdk/lib/index.js:385:199608)
    at Request.callListeners (/usr/local/Cellar/aws-cdk/2.139.0/libexec/lib/node_modules/aws-cdk/lib/index.js:385:91727) {
  code: 'ValidationError',
  time: 2024-04-25T23:56:02.578Z,
  requestId: 'f5515800-5335-434b-9df6-d930bcf788c4',
  statusCode: 400,
  retryable: false,
  retryDelay: 236.99598614253415
}

Template format error: Unrecognized resource types: [AWS::Bedrock::DataSource, AWS::Bedrock::KnowledgeBase]
```

### Expected Behavior

- Support for cdk migration
- Addition of `StorageConfiguration`
- Successful deployment without any validation error

### Current Behavior

- Migration is not possible for Bedrock resources
- `AWS::Bedrock::KnowledgeBase` is invalid without `StorageConfiguration` property
- Deployment error- not recognising AWS::Bedrock::DataSource, AWS::Bedrock::KnowledgeBase resources

### Reproduction Steps

C#

```
        var bedrockKnowledgeBase = new CfnKnowledgeBase(this, "BedrockKnowledgeBase", new CfnKnowledgeBaseProps
        {
            Name = "bedrock-dotnet-demo-kb",
            KnowledgeBaseConfiguration = new KnowledgeBaseConfigurationProperty
            {
                Type = "VECTOR",
                VectorKnowledgeBaseConfiguration = new VectorKnowledgeBaseConfigurationProperty
                {
                    EmbeddingModelArn = $"arn:aws:bedrock:{Region}::foundation-model/amazon.titan-embed-text-v1"
                }
            },
            RoleArn = bedrockExecutionRoleForKnowledgeBase.AttrArn
        });

        var bedrockKnowledgeBaseDataStore = new CfnDataSource(this, "BedrockKnowledgeBaseDataStore", new CfnDataSourceProps
        {
            Name = "bedrock-dotnet-demo-kb-data-source",
            KnowledgeBaseId = bedrockKnowledgeBase.Ref,
            DataSourceConfiguration = new DataSourceConfigurationProperty
            {
                Type = "S3",
                S3Configuration = new S3DataSourceConfigurationProperty
                {
                    BucketArn = bedrockRagDataBucket.AttrArn,
                    InclusionPrefixes = new[] { "kb-" }
                }
            }
        });
```

### Additional Information/Context

```
$ cdk version
2.139.0 (build 2699ffd)
```

DotNet `Amazon.CDK.Lib` NuGet version- 2.139.0

OS- MacOS Sonoma

### CDK CLI Version

2.139.0

### Node.js Version

18.17.0

### OS

MacOS Sonoma 14.4.1

### Language

.NET

### Language Version

8.0.201

**Comment by ssinghgai** [comment]
+1 - Observed the same behavior - "#: _required key [StorageConfiguration] not found "_"
<img width="466" alt="image" src="https://github.com/aws/aws-cdk/assets/159400816/71ddb042-c29f-4a29-a27f-035e4b60b423">

**Comment by khushail** [comment]
> +1 - Observed the same behavior - "#: _required key [StorageConfiguration] not found "_" <img alt="image" width="466" src="https://private-user-images.githubusercontent.com/159400816/326014292-71ddb042-c29f-4a29-a27f-035e4b60b423.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQxNTU1MDcsIm5iZiI6MTcxNDE1NTIwNywicGF0aCI6Ii8xNTk0MDA4MTYvMzI2MDE0MjkyLTcxZGRiMDQyLWMyOWYtNGEyOS1hMjdmLTAzNWU0YjYwYjQyMy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDI2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQyNlQxODEzMjdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04ZjYwM2RmZmFiNGRjNjI3NDM1YmZmYmNhNTdmNzgxNDk1N2U3YTlmY2UzNWZkNTgxNTY5MGViZThkYzVhNTJjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.qJkgDZHmVLFHaoJr1MNes4DtsjeXyz-EJk0GjKMrmOc">

@Samir-AWS , Thanks for reporting this issue. I am also facing the same deployment issue as shared by @ssinghgai. 

I see there is some mismatch in the [Cfn Service spec](https://d1uauaxba7bl26.cloudfront.net/latest/gzip/CloudFormationResourceSpecification.json) mentioning the StorageConfiguration -
<img width="1284" alt="Screenshot 2024-04-26 at 12 01 24 PM" src="https://github.com/aws/aws-cdk/assets/117320115/a860d1be-df75-4ddb-a9f1-d8ea94049588"> 



and the [CDK Documentation](https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_bedrock.CfnKnowledgeBaseProps.html) for CfnKnowledgeBaseProps.

CDK imports servicespec using spec2cdk and based on the [package.json](https://github.com/aws/aws-cdk/blob/f0835d937b28172bb06990c042deaede8a88f844/tools/%40aws-cdk/spec2cdk/package.json#L35), current latest CDK release is still using 0.0.64 and the main branch is using 0.0.65 now. I also see some discrepancies in documentation as well - Here is [AWS Documentation](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-bedrock-knowledgebase.html) and this is [CDK documentation](https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_bedrock.CfnKnowledgeBase.html). Marking the issue as appropriate.

**Comment by TheRealAmazonKendra** [comment]
The addition of resources in cdk migrate (in cdk-from-cfn) is independent of their addition into aws-cdk-lib. We had been blocked from releasing in that repo due to an unrelated issue so no updates made it into the last cdk release. We can now release again so these updates should make it into the next release.

**Comment by colifran** [comment]
Hi @Samir-AWS. This [PR](https://github.com/aws/aws-cdk/pull/30037) has added `StorageConfiguration` into our generated bedrock L1s

**Comment by Samir-AWS** [comment]
Thank you team for fixing this issue. `StorageConfiguration` is now available and I could deploy successfully in `us-east-1` and `us-west-2`

However, the deployment issue still exists in `ap-southeast-2` region. I haven't tried any [other regions](https://docs.aws.amazon.com/bedrock/latest/userguide/bedrock-regions.html), but assuming those might have this issue as well.

```
$ cdk deploy

❌  bedrock-dotnet-demo failed: Error [ValidationError]: Template format error: Unrecognized resource types: [AWS::Bedrock::DataSource, AWS::Bedrock::KnowledgeBase]
    at Request.extractError (/usr/local/Cellar/aws-cdk/2.140.0/libexec/lib/node_modules/aws-cdk/lib/index.js:387:46692)
    at Request.callListeners (/usr/local/Cellar/aws-cdk/2.140.0/libexec/lib/node_modules/aws-cdk/lib/index.js:387:91600)
    at Request.emit (/usr/local/Cellar/aws-cdk/2.140.0/libexec/lib/node_modules/aws-cdk/lib/index.js:387:91048)
    at Request.emit (/usr/local/Cellar/aws-cdk/2.140.0/libexec/lib/node_modules/aws-cdk/lib/index.js:387:199651)
    at Request.transition (/usr/local/Cellar/aws-cdk/2.140.0/libexec/lib/node_modules/aws-cdk/lib/index.js:387:193203)
    at AcceptorStateMachine.runTo (/usr/local/Cellar/aws-cdk/2.140.0/libexec/lib/node_modules/aws-cdk/lib/index.js:387:158075)
    at /usr/local/Cellar/aws-cdk/2.140.0/libexec/lib/node_modules/aws-cdk/lib/index.js:387:158405
    at Request.<anonymous> (/usr/local/Cellar/aws-cdk/2.140.0/libexec/lib/node_modules/aws-cdk/lib/index.js:387:193495)
    at Request.<anonymous> (/usr/local/Cellar/aws-cdk/2.140.0/libexec/lib/node_modules/aws-cdk/lib/index.js:387:199726)
    at Request.callListeners (/usr/local/Cellar/aws-cdk/2.140.0/libexec/lib/node_modules/aws-cdk/lib/index.js:387:91768) {
  code: 'ValidationError',
  time: 2024-05-05T23:30:51.682Z,
  requestId: '3f9ec639-1b0f-4eee-8258-1a60cfc7396c',
  statusCode: 400,
  retryable: false,
  retryDelay: 8.307862464785432
}

 ❌ Deployment failed: Error [ValidationError]: Template format error: Unrecognized resource types: [AWS::Bedrock::DataSource, AWS::Bedrock::KnowledgeBase]
    at Request.extractError (/usr/local/Cellar/aws-cdk/2.140.0/libexec/lib/node_modules/aws-cdk/lib/index.js:387:46692)
    at Request.callListeners (/usr/local/Cellar/aws-cdk/2.140.0/libexec/lib/node_modules/aws-cdk/lib/index.js:387:91600)
    at Request.emit (/usr/local/Cellar/aws-cdk/2.140.0/libexec/lib/node_modules/aws-cdk/lib/index.js:387:91048)
    at Request.emit (/usr/local/Cellar/aws-cdk/2.140.0/libexec/lib/node_modules/aws-cdk/lib/index.js:387:199651)
    at Request.transition (/usr/local/Cellar/aws-cdk/2.140.0/libexec/lib/node_modules/aws-cdk/lib/index.js:387:193203)
    at AcceptorStateMachine.runTo (/usr/local/Cellar/aws-cdk/2.140.0/libexec/lib/node_modules/aws-cdk/lib/index.js:387:158075)
    at /usr/local/Cellar/aws-cdk/2.140.0/libexec/lib/node_modules/aws-cdk/lib/index.js:387:158405
    at Request.<anonymous> (/usr/local/Cellar/aws-cdk/2.140.0/libexec/lib/node_modules/aws-cdk/lib/index.js:387:193495)
    at Request.<anonymous> (/usr/local/Cellar/aws-cdk/2.140.0/libexec/lib/node_modules/aws-cdk/lib/index.js:387:199726)
    at Request.callListeners (/usr/local/Cellar/aws-cdk/2.140.0/libexec/lib/node_modules/aws-cdk/lib/index.js:387:91768) {
  code: 'ValidationError',
  time: 2024-05-05T23:30:51.682Z,
  requestId: '3f9ec639-1b0f-4eee-8258-1a60cfc7396c',
  statusCode: 400,
  retryable: false,
  retryDelay: 8.307862464785432
}

Template format error: Unrecognized resource types: [AWS::Bedrock::DataSource, AWS::Bedrock::KnowledgeBase]
```

cc: @colifran  @TheRealAmazonKendra  @pahud

**Comment by colifran** [comment]
@Samir-AWS It doesn't look like `AWS::Bedrock::Datasource` or `AWS::Bedrock::KnowledgeBase` are available in `ap-southeast-2` - https://d1ane3fvebulky.cloudfront.net/latest/gzip/CloudFormationResourceSpecification.json
