### ISSUE TITLE
(@aws-cdk/aws-glue-alpha): CDK + partition indices + catalog encryption fails deployment

### ISSUE THREAD

**Issue by ksco92** [aws/aws-cdk#30364]
### Describe the bug

If you make your catalog settings using this and add a KMS key:

https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_glue.CfnDataCatalogEncryptionSettings.html

And then make an S3 table with partition indices using this:

https://docs.aws.amazon.com/cdk/api/v2/docs/@aws-cdk_aws-glue-alpha.S3Table.html

The creation of the partition indices will fail. This is from a CW log of the custom resource:

```
2024-05-28T15:05:10.698Z	5ad1162d-2cc6-4c42-8ea7-699c8a81c0fa	INFO	{
    "RequestType": "Create",
    "ServiceToken": "redacted",
    "ResponseURL": "...",
    "StackId": "redacted",
    "RequestId": "5d573d5c-a3a7-4998-818a-2a616d249e3c",
    "LogicalResourceId": "redacted",
    "ResourceType": "Custom::AWS",
    "ResourceProperties": {
        "ServiceToken": "redacted",
        "InstallLatestAwsSdk": "false",
        "Create": {
            "service": "Glue",
            "action": "createPartitionIndex",
            "parameters": {
                "DatabaseName": "redacted",
                "TableName": "redacted",
                "PartitionIndex": {
                    "IndexName": "run_date_index",
                    "Keys": [
                        "run_date"
                    ]
                }
            },
            "physicalResourceId": {
                "id": "run_date_index"
            }
        }
    }
}
```

And then:

```
2024-05-28T15:05:25.729Z	5ad1162d-2cc6-4c42-8ea7-699c8a81c0fa	INFO	InternalFailure: UnknownError
    at throwDefaultError (/var/runtime/node_modules/@aws-sdk/node_modules/@smithy/smithy-client/dist-cjs/index.js:838:20)
    at /var/runtime/node_modules/@aws-sdk/node_modules/@smithy/smithy-client/dist-cjs/index.js:847:5
    at de_CommandError (/var/runtime/node_modules/@aws-sdk/client-glue/dist-cjs/index.js:6042:14)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async /var/runtime/node_modules/@aws-sdk/node_modules/@smithy/middleware-serde/dist-cjs/index.js:35:20
    at async /var/runtime/node_modules/@aws-sdk/node_modules/@smithy/core/dist-cjs/index.js:165:18
    at async /var/runtime/node_modules/@aws-sdk/node_modules/@smithy/middleware-retry/dist-cjs/index.js:320:38
    at async /var/runtime/node_modules/@aws-sdk/middleware-logger/dist-cjs/index.js:33:22
    at async D.invoke (/var/task/index.js:1:119684)
    at async Object.qe (/var/task/index.js:1:126630) {
  '$fault': 'client',
  '$metadata': {
    httpStatusCode: 500,
    requestId: '6599dc99-d6ff-4495-9c12-8cbec9fad351',
    extendedRequestId: undefined,
    cfId: undefined,
    attempts: 3,
    totalRetryDelay: 174
  },
  __type: 'InternalFailure'
}
```

If I remove the KMS key from the catalog settings, this succeeds.

### Expected Behavior

If the catalog is encrypted, the custom resource should be given permissions to the catalog KMS key.

### Current Behavior

The deployment fails because the role that runs the lambda function has no permissions to encrypt/decrypt the catalog key.

### Reproduction Steps

In a single stack:
* Make an S3 bucket
* Create a KMS key and add it as the catalog key
* Make a table using S3Table that has partition keys and partition indices
* Make a deployment.

### Possible Solution

Allow to pass a KMS key to S3Table to indicate that the catalog is encrypted and that the custom resource should have access to it.

### CDK CLI Version

2.143.0

### Node.js Version

18

### OS

Mac

### Language

TypeScript

**Comment by ashishdhingra** [comment]
@ksco92 Good morning. Could you please share the minimal CDK code to reproduce the issue, including `CfnDataCatalogEncryptionSettings`? I tried reproducing the issue at my end, somehow unable to reproduce the issue.

Thanks,
Ashish

**Comment by ksco92** [comment]
This reproduces the error:

https://github.com/ksco92/partitions_bug

In your example you are using `connectionPasswordEncryption` rather than `encryptionAtRest`. The former encrypts connection objects to external data sources, the later encrypts the metadata of the catalog at rest.
