### ISSUE TITLE
aws_elasticloadbalancingv2: using from_lookup falsely assumes Dual Stack

### ISSUE THREAD

**Issue by timothy-cloudopsguy** [aws/aws-cdk#30828]
### Describe the bug

When running this code:

```
        nlb = elbv2.NetworkLoadBalancer.from_lookup(
            self,
            id='nlb',
            load_balancer_arn=env_data['nlb_arn']
        )
        print(f"IP_ADDRESS_TYPE: {nlb.ip_address_type}")


        listener = nlb.add_listener(
            id='listener',
            port=nlb_listener_port,
            protocol=elbv2.Protocol.UDP
        )
```

The print statement shows DUAL_STACK and not IPV4

```
IP_ADDRESS_TYPE: IpAddressType.DUAL_STACK
```

When in reality ... This is not a dual stack NLB.

```
aws elbv2 describe-load-balancers --load-balancer-arns arn:aws:elasticloadbalancing:REGION:ACCOUNT:loadbalancer/net/NLB_NAME  | jq -r .LoadBalancers[0].IpAddressType

ipv4
```

### Expected Behavior

Expected behavior is for the `.from_lookup()` function to correctly determine the `ip_address_type` instead of assume DUAL_STACK, and then properly attach the `add_listener()` as requested without errors.

### Current Behavior

Because the returned INetworkLoadBalancer does not actually grab the truthiness of ip_address_type, but assumes it to be DUAL_STACK, the CDK stack FAILS to add the listener with this message:

```
RuntimeError: Error: UDP or TCP_UDP listeners cannot be added to a dualstack network load balancer.
```

### Reproduction Steps

Create an NLB in another stack or manually, and save the ARN into an SSM Parameter.  Read in the parameter in a CDK stack and use from_lookup() to get an INetworkLoadBalancer object and add_listener() to add a UDP listener.

```
        nlb_arn_ssm = ssm.StringParameter.from_string_parameter_name(
            self,
            id="nlb-arn-ssm",
            string_parameter_name="test_nlb_arn")

        nlb = elbv2.NetworkLoadBalancer.from_lookup(
            self,
            id='nlb',
            load_balancer_arn=nlb_arn_ssm.string_value
        )

        print(f"IP_ADDRESS_TYPE: {nlb.ip_address_type}")

        nlb_listener_port = 7777

        listener = nlb.add_listener(
            id='listener',
            port=nlb_listener_port,
            protocol=elbv2.Protocol.UDP
        )
```

### Possible Solution

When pulling in information about the NLB using the ARN, pull in the ip_address_type as well using `describe-load-balancers` ? 

### CDK CLI Version

2.142.1 (build ed4e152)

### Framework Version

python

### Node.js Version

v18.19.0

### OS

macOs 14.5 (23F79)

### Language

Python

### Language Version

Python 3.12.4

### Other information

```
jsii.errors.JavaScriptError: 
  @jsii/kernel.RuntimeError: Error: UDP or TCP_UDP listeners cannot be added to a dualstack network load balancer.
      at Kernel._Kernel_ensureSync (/private/var/folders/qz/dgx8s7357r9bfpywd3q336d80000gn/T/tmp_515if_3/lib/program.js:10502:23)
      at Kernel.invoke (/private/var/folders/qz/dgx8s7357r9bfpywd3q336d80000gn/T/tmp_515if_3/lib/program.js:9866:102)
      at KernelHost.processRequest (/private/var/folders/qz/dgx8s7357r9bfpywd3q336d80000gn/T/tmp_515if_3/lib/program.js:11707:36)
      at KernelHost.run (/private/var/folders/qz/dgx8s7357r9bfpywd3q336d80000gn/T/tmp_515if_3/lib/program.js:11667:22)
      at Immediate._onImmediate (/private/var/folders/qz/dgx8s7357r9bfpywd3q336d80000gn/T/tmp_515if_3/lib/program.js:11668:46)
      at process.processImmediate (node:internal/timers:476:21)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/timothywelch/sharpen/src-openvxi/cdk/app.py", line 99, in <module>
    application_stack = ApplicationStack(
                        ^^^^^^^^^^^^^^^^^
  File "/Users/timothywelch/sharpen/src-openvxi/cdk/venv/lib/python3.12/site-packages/jsii/_runtime.py", line 118, in __call__
    inst = super(JSIIMeta, cast(JSIIMeta, cls)).__call__(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/timothywelch/sharpen/src-openvxi/cdk/lib/application.py", line 136, in __init__
    self.ecs = _ecs(
               ^^^^^
  File "/Users/timothywelch/sharpen/src-openvxi/cdk/venv/lib/python3.12/site-packages/jsii/_runtime.py", line 118, in __call__
    inst = super(JSIIMeta, cast(JSIIMeta, cls)).__call__(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/timothywelch/sharpen/src-openvxi/cdk/lib/ecs.py", line 964, in __init__
    listener = nlb.add_listener(
               ^^^^^^^^^^^^^^^^^
  File "/Users/timothywelch/sharpen/src-openvxi/cdk/venv/lib/python3.12/site-packages/aws_cdk/aws_elasticloadbalancingv2/__init__.py", line 13826, in add_listener
    return typing.cast("NetworkListener", jsii.invoke(self, "addListener", [id, props]))
                                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/timothywelch/sharpen/src-openvxi/cdk/venv/lib/python3.12/site-packages/jsii/_kernel/__init__.py", line 149, in wrapped
    return _recursize_dereference(kernel, fn(kernel, *args, **kwargs))
                                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/timothywelch/sharpen/src-openvxi/cdk/venv/lib/python3.12/site-packages/jsii/_kernel/__init__.py", line 399, in invoke
    response = self.provider.invoke(
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/timothywelch/sharpen/src-openvxi/cdk/venv/lib/python3.12/site-packages/jsii/_kernel/providers/process.py", line 380, in invoke
    return self._process.send(request, InvokeResponse)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/timothywelch/sharpen/src-openvxi/cdk/venv/lib/python3.12/site-packages/jsii/_kernel/providers/process.py", line 342, in send
    raise RuntimeError(resp.error) from JavaScriptError(resp.stack)
RuntimeError: Error: UDP or TCP_UDP listeners cannot be added to a dualstack network load balancer.

Subprocess exited with error 1
```

**Comment by timothy-cloudopsguy** [comment]
NOTE: I just tried using `.from_network_load_balancer_attributes()` and it synthesized just fine. I'll update this if it deploys successfully.

**Comment by ashishdhingra** [comment]
@timothy-cloudopsguy Good morning. Thanks for reporting the issue. I was able to reproduce the issue when executing `cdk synth` for the first time using below TypeScript CDK code:
```TypeScript
import * as cdk from 'aws-cdk-lib';
import { Construct } from 'constructs';
import * as elbv2 from 'aws-cdk-lib/aws-elasticloadbalancingv2';
import { debug } from 'console';

export class Issue30806Stack extends cdk.Stack {
  constructor(scope: Construct, id: string, props?: cdk.StackProps) {
    super(scope, id, props);

    // Manually created IPV4 NLB in AWS console.
    const nlbArn = 'arn:aws:elasticloadbalancing:us-east-2:REDACTED:loadbalancer/net/testnlb/REDACTED';
    debug(`IP_ADDRESS_TYPE 1: ${nlb.ipAddressType}`);
  }
}
```
Running `cdk synth` for the first time produced below output:
```YAML
IP_ADDRESS_TYPE 1: dualstack
IP_ADDRESS_TYPE 1: ipv4
IP_ADDRESS_TYPE 1: ipv4
Resources:
  CDKMetadata:
    Type: AWS::CDK::Metadata
    Properties:
      Analytics: v2:deflate64:H4sIAAAAAAAA/zPSMzSx0DNQTCwv1k1OydbNyUzSqw4uSUzO1glKLc4vLUpO1XFOy4Oxa3Xy8lNS9bKK9cuMDPQMDfUMFbOKMzN1i0rzSjJzU/WCIDQA2v7akFYAAAA=
    Metadata:
      aws:cdk:path: Issue30806Stack/CDKMetadata/Default
Parameters:
  BootstrapVersion:
    Type: AWS::SSM::Parameter::Value<String>
    Default: /cdk-bootstrap/hnb659fds/version
    Description: Version of the CDK Bootstrap resources in this environment, automatically retrieved from SSM Parameter Store. [cdk:skip]
Rules:
  CheckBootstrapVersion:
    Assertions:
      - Assert:
          Fn::Not:
            - Fn::Contains:
                - - "1"
                  - "2"
                  - "3"
                  - "4"
                  - "5"
                - Ref: BootstrapVersion
        AssertDescription: CDK bootstrap stack version 6 required. Please run 'cdk bootstrap' with a recent version of the CDK CLI.
```
Then running `cdk context` produced below output (REDACTED):
```YAML
Context found in cdk.json:

┌────┬───────────────────────────────────────────────────────────────────────────┬───────────────────────────────────────────────────────────────────────────┐
│ #  │ Key                                                                       │ Value                                                                     │
├────┼───────────────────────────────────────────────────────────────────────────┼───────────────────────────────────────────────────────────────────────────┤
│ 1  │ @aws-cdk-containers/ecs-service-extensions:enableDefaultLogDriver         │ true                                                                      │
├────┼───────────────────────────────────────────────────────────────────────────┼───────────────────────────────────────────────────────────────────────────┤
│ 50 │ load-balancer:account=REDACTED:loadBalancerArn=arn$:aws$:elasticloadb     │ { "loadBalancerArn": "arn:aws:elasticloadbalancing:us-east-2:REDACTED     │
│    │ alancing$:us-east-2$:REDACTED$:loadbalancer/net/testnlb/REDACTED          │ :loadbalancer/net/testnlb/REDACTED", "loadBalancerCanonicalHosted         │
│    │ 79b:loadBalancerType=network:region=us-east-2                             │ ZoneId": "REDACTED", "loadBalancerDnsName": "testnlb-REDACTED             │
│    │                                                                           │ b.elb.us-east-2.amazonaws.com", "vpcId": "vpc-REDACTED", "securi          │
│    │                                                                           │ tyGroupIds": [ "sg-REDACTED" ], "ipAddressType": "ipv4" }                 │
└────┴───────────────────────────────────────────────────────────────────────────┴───────────────────────────────────────────────────────────────────────────┘
Run cdk context --reset KEY_OR_NUMBER to remove a context key. It will be refreshed on the next CDK synthesis run.
```

Running `cdk synth` again produces below output:
```YAML
IP_ADDRESS_TYPE 1: ipv4
Resources:
  CDKMetadata:
    Type: AWS::CDK::Metadata
    Properties:
      Analytics: v2:deflate64:H4sIAAAAAAAA/zPSMzSx0DNQTCwv1k1OydbNyUzSqw4uSUzO1glKLc4vLUpO1XFOy4Oxa3Xy8lNS9bKK9cuMDPQMDfUMFbOKMzN1i0rzSjJzU/WCIDQA2v7akFYAAAA=
    Metadata:
      aws:cdk:path: Issue30806Stack/CDKMetadata/Default
Parameters:
  BootstrapVersion:
    Type: AWS::SSM::Parameter::Value<String>
    Default: /cdk-bootstrap/hnb659fds/version
    Description: Version of the CDK Bootstrap resources in this environment, automatically retrieved from SSM Parameter Store. [cdk:skip]
Rules:
  CheckBootstrapVersion:
    Assertions:
      - Assert:
          Fn::Not:
            - Fn::Contains:
                - - "1"
                  - "2"
                  - "3"
                  - "4"
                  - "5"
                - Ref: BootstrapVersion
        AssertDescription: CDK bootstrap stack version 6 required. Please run 'cdk bootstrap' with a recent version of the CDK CLI.
```

So `cdk synth` would cache CF resources during synthesis time, refer [Runtime context](https://docs.aws.amazon.com/cdk/v2/guide/context.html) for more details.

So if after running `cdk synth` for the first time, if I add the below code and run `cdk synth` again, it synthesizes properly.
```TypeScript
const targetGroupArn = 'arn:aws:elasticloadbalancing:us-east-2:REDACTED:targetgroup/testtargetgroupfornlb/REDACTED';
const listener = nlb.addListener('listener2', {
      port: nlbListernerPort, 
      protocol: elbv2.Protocol.UDP,
      defaultTargetGroups: [elbv2.NetworkTargetGroup.fromTargetGroupAttributes(this, 'tg', {targetGroupArn: targetGroupArn})]
    });
```

The reason why `NetworkLoadBalancer.fromNetworkLoadBalancerAttributes()` could be working is that it defaults to `IPV4` [here](https://github.com/aws/aws-cdk/blob/8d55d864183803e2e6cfb3991edced7496eaadeb/packages/aws-cdk-lib/aws-elasticloadbalancingv2/lib/nlb/network-load-balancer.ts#L261) (_this could be incorrect if using `DUALSTACK` balancer_). The context value for load balancer is **somehow** not populated when using `NetworkLoadBalancer.fromNetworkLoadBalancerAttributes()`.

**Comment by pahud** [comment]
In CDK, all L2 constructs have the fromXxxx() methods and they could be implemented in two major patterns:

1. Just returns the interface of the resource with all required attributes we provide  in the options. Such as `arn` or other attributes. CDK would NOT call AWS SDKs to retrieve additional information. All information has to be provided by user.

2. Query additional attributes via context provider, such as [Vpc.fromLookup()](https://github.com/aws/aws-cdk/blob/8d55d864183803e2e6cfb3991edced7496eaadeb/packages/aws-cdk-lib/aws-ec2/lib/vpc.ts#L1307-L1323), and cache additional information in the context variables i.e. `cdk.context.json`.


[elbv2.NetworkLoadBalancer.from_lookup()](https://github.com/aws/aws-cdk/blob/8d55d864183803e2e6cfb3991edced7496eaadeb/packages/aws-cdk-lib/aws-elasticloadbalancingv2/lib/nlb/network-load-balancer.ts#L186) falls into the 2nd category that returns a new [LookedUpNetworkLoadBalancer](https://github.com/aws/aws-cdk/blob/8d55d864183803e2e6cfb3991edced7496eaadeb/packages/aws-cdk-lib/aws-elasticloadbalancingv2/lib/nlb/network-load-balancer.ts#L524) for you, which is literally a `INetworkLoadBalancer`. If you look at [its implementation](https://github.com/aws/aws-cdk/blob/8d55d864183803e2e6cfb3991edced7496eaadeb/packages/aws-cdk-lib/aws-elasticloadbalancingv2/lib/nlb/network-load-balancer.ts#L534-L557), it determines the `IpAddressType` from here:

https://github.com/aws/aws-cdk/blob/8d55d864183803e2e6cfb3991edced7496eaadeb/packages/aws-cdk-lib/aws-elasticloadbalancingv2/lib/nlb/network-load-balancer.ts#L548-L552

And additional `props` are determined here:

https://github.com/aws/aws-cdk/blob/8d55d864183803e2e6cfb3991edced7496eaadeb/packages/aws-cdk-lib/aws-elasticloadbalancingv2/lib/nlb/network-load-balancer.ts#L187-L190

The query logic is defined here:

https://github.com/aws/aws-cdk/blob/8d55d864183803e2e6cfb3991edced7496eaadeb/packages/aws-cdk-lib/aws-elasticloadbalancingv2/lib/shared/base-load-balancer.ts#L130-L157

OK. When dealing with context provider, if that value does not exist in local cdk.context.json, CDK would initially insert a placeholder dummy value and replace it after it stores the real value into the cdk.context.json. This is a little bit tricky though. Unfortunately, the dummy value of ipAddressType is currently defined as 

https://github.com/aws/aws-cdk/blob/8d55d864183803e2e6cfb3991edced7496eaadeb/packages/aws-cdk-lib/aws-elasticloadbalancingv2/lib/shared/base-load-balancer.ts#L148-L149

This would be confusing because user code would not be able to initially determine if the value is a dummy value or real value. But CDK would eventually replace that value with correct value. This explains why we see this from the sample @ashishdhingra provided above.

```
IP_ADDRESS_TYPE 1: dualstack
IP_ADDRESS_TYPE 1: ipv4
IP_ADDRESS_TYPE 1: ipv4
```

Now my question is - given the value would be eventually replaced with correct value. Would this still be an issue for you? Off the top of my head, the only problem is that if you have a check on the type in your CDK code and execute different logic accordingly, that might be an issue but if you simply CfnOutput that, it should not be an issue.

Also, this only happens when your `cdk.context.json` does not have that cache. If you execute the 2nd time, it would simply return the cached value from `cdk.context.json`

Personally, I would prefer we have a way to check if we are having dummy values like:


```ts
const myIpAddressType: IpAddressType | undefined = undefined
if ( isDummy(nlb) {
  // we got dummy value, skip everything.
} else {
  // ok we got correct value from context provider
  myIpAddressType = nlb. ipAddressType;
}
```
