### ISSUE TITLE
efs: cant set allow_anonymous_access

### ISSUE THREAD

**Issue by Zujiry** [aws/aws-cdk#30929]
### Describe the bug

Setting the `allow_anonymous_access` to True like:
```
        self.s3_mirror_fs = efs.FileSystem(
            self,
            id="test_efs",
            file_system_name="test_efs",
            vpc=vpc,
            lifecycle_policy=efs.LifecyclePolicy.AFTER_90_DAYS,
            removal_policy=RemovalPolicy.DESTROY,
           allow_anonymous_access=True
        )
```
Throws the error:  

TypeError: FileSystem.__init__() got an unexpected keyword argument 'allow_anonymous_access'  
Subprocess exited with error 1  

### Expected Behavior

It should be possbile to set `allow_anonymous_access` in FileSystem creation

### Current Behavior

Its not possible to set `allow_anonymous_access`

### Reproduction Steps

Deploy an efs.FileSystem with `allow_anonymous_access`.

### CDK CLI Version

2.150.0

### Node.js Version

18

### OS

WSL2

### Language

Python

### Language Version

3.12

**Comment by pahud** [comment]
It should work.

```py
class DummyStack(Stack):
    def __init__(self, scope: Construct, construct_id: str, **kwargs) -> None:
        super().__init__(scope, construct_id, **kwargs)
        
        vpc = ec2.Vpc.from_lookup(self, 'Vpc', is_default=True)
        efs.FileSystem(
          self,
          id="test_efs",
          file_system_name="test_efs",
          vpc=vpc,
          lifecycle_policy=efs.LifecyclePolicy.AFTER_90_DAYS,
          removal_policy=RemovalPolicy.DESTROY,
          allow_anonymous_access=True
        )
```

cdk diff

```
Resources
[+] AWS::EFS::FileSystem test_efs testefsF6A4FC38 
[+] AWS::EC2::SecurityGroup test_efs/EfsSecurityGroup testefsEfsSecurityGroup8B3DA35F 
[+] AWS::EFS::MountTarget test_efs/EfsMountTarget1 testefsEfsMountTarget1A208FA23 
[+] AWS::EFS::MountTarget test_efs/EfsMountTarget2 testefsEfsMountTarget296A5B6F1 
[+] AWS::EFS::MountTarget test_efs/EfsMountTarget3 testefsEfsMountTarget3270BAE38 
```

% cdk --version
2.150.0 (build 3f93027)
% grep aws-cdk-lib requirements.txt 
aws-cdk-lib==2.150.0

Can you try again with a new directory and make sure the cdk version is up to date?

**Comment by Zujiry** [comment]
New folder created but still have the same problem:
```
Traceback (most recent call last):
  File "/home/user/repos/repo/testefs/app.py", line 10, in <module>
    TestefsStack(app, "TestefsStack",
  File "/home/user/repos/repo/.venv/lib/python3.10/site-packages/jsii/_runtime.py", line 118, in __call__
    inst = super(JSIIMeta, cast(JSIIMeta, cls)).__call__(*args, **kwargs)
  File "/home/user/repos/repo/testefs/testefs/testefs_stack.py", line 15, in __init__
    efs.FileSystem(
  File "/home/user/repos/repo/.venv/lib/python3.10/site-packages/jsii/_runtime.py", line 118, in __call__
    inst = super(JSIIMeta, cast(JSIIMeta, cls)).__call__(*args, **kwargs)
TypeError: FileSystem.__init__() got an unexpected keyword argument 'allow_anonymous_access'
```

requirements.txt:
```
aws-cdk-lib==2.150.0
constructs>=10.0.0,<11.0.0
```
% cdk --version  
2.150.0 (build 3f93027)

**Comment by Zujiry** [comment]
Maybe this helps?

% npm --version  
10.8.2  
% nodejs -v  
v18.20.4

**Comment by pahud** [comment]
Make sure you have activated the `venv`

```sh
$ source .venv/bin/activate
$ pip install -r requirements.txt
$ cdk diff
```

Let me know if it works for you.

**Comment by Zujiry** [comment]
It wasnt the not activated venv, but another venv in which it was installed... thanks!
