### ISSUE TITLE
(codepipeline): CrossRegionSupportStack Stack name must match the regular expression

### ISSUE THREAD

**Issue by jsunico** [aws/aws-cdk#31436]
### Describe the Bug

I have a State Machine from another region that is being imported to CDK via StateMachine.fromStateMachineArn. When this state machine is added as cross-region StepFunctionInvokeAction to the pipeline with an error is thrown.

### Regression Issue

- [ ] Select this option if this issue appears to be a regression.

### Expected Behavior

Cross-region action can be added to the pipeline.

### Current Behavior

```
Error: Stack name must match the regular expression: /^[A-Za-z][A-Za-z0-9-]*$/, got '${Token[TOKEN.840]}-support-eu-west-1'
    at new Stack (node_modules/aws-cdk-lib/core/lib/stack.js:1:2505)
    at new CrossRegionSupportStack (node_modules/aws-cdk-lib/aws-codepipeline/lib/private/cross-region-support-stack.js:1:1798)
    at Pipeline.createSupportResourcesForRegion (node_modules/aws-cdk-lib/aws-codepipeline/lib/pipeline.js:1:10279)
    at Pipeline.obtainCrossRegionSupportFor (node_modules/aws-cdk-lib/aws-codepipeline/lib/pipeline.js:1:9122)
    at Pipeline.ensureReplicationResourcesExistFor (node_modules/aws-cdk-lib/aws-codepipeline/lib/pipeline.js:1:8644)
    at Pipeline._attachActionToPipeline (node_modules/aws-cdk-lib/aws-codepipeline/lib/pipeline.js:1:7708)
    at Stage.attachActionToPipeline (node_modules/aws-cdk-lib/aws-codepipeline/lib/private/stage.js:1:3087)
    at Stage.addAction (node_modules/aws-cdk-lib/aws-codepipeline/lib/private/stage.js:1:1716)
    at new Stage (node_modules/aws-cdk-lib/aws-codepipeline/lib/private/stage.js:1:678)
    at Pipeline.addStage (node_modules/aws-cdk-lib/aws-codepipeline/lib/pipeline.js:1:6662)
```

### Reproduction Steps

- Import a state machine from another region using StateMachine.fromStateMachineArn
- Add StepFunctionInvokeAction to a stage in the pipeline and use the imported state machine.

### Possible Solution

NA

### CDK CLI Version

2.158.0

### Node.js Version

18.20.4

### OS

WSL Ubuntu 20

### Language

TypeScript

### Language Version

~4.6.4

**Comment by khushail** [comment]
Hey @jsunico , thanks for reaching out. 
From the initial error check, it looks like the stack name given by you, is the issue, not the code. 
https://github.com/aws/aws-cdk/blob/bf3764fe6046799a2a6e074b39b9a5f4474c603c/packages/aws-cdk-lib/core/lib/stack.ts#L455
It would be more helpful if you could share the minimal repro code with the stack name you are using.

**Comment by jsunico** [comment]
Hi @khushail, so I tried to reproduce it in a new project here: https://github.com/jsunico/aws-cdk-repro-cross-region-action-in-pipeline

I started off with just a single stack which is generated by `cdk init`. I didn't experience the issue. I then switch to nested stack to align it with our project setup and was able to reproduce the issue.

This is the error you'll get when running `npx cdk synth`

```
Error: Stack name must match the regular expression: /^[A-Za-z][A-Za-z0-9-]*$/, got '${Token[TOKEN.21]}-support-service'
    at new Stack (github-issues/pipeline-cross-region/node_modules/aws-cdk-lib/core/lib/stack.js:1:4798)
    at new CrossRegionSupportStack (github-issues/pipeline-cross-region/node_modules/aws-cdk-lib/aws-codepipeline/lib/private/cross-region-support-stack.js:1:1984)
    at Pipeline.createSupportResourcesForRegion (github-issues/pipeline-cross-region/node_modules/aws-cdk-lib/aws-codepipeline/lib/pipeline.js:1:14004)
    at Pipeline.obtainCrossRegionSupportFor (github-issues/pipeline-cross-region/node_modules/aws-cdk-lib/aws-codepipeline/lib/pipeline.js:1:12840)
    at Pipeline.ensureReplicationResourcesExistFor (github-issues/pipeline-cross-region/node_modules/aws-cdk-lib/aws-codepipeline/lib/pipeline.js:1:12360)
    at Pipeline._attachActionToPipeline (github-issues/pipeline-cross-region/node_modules/aws-cdk-lib/aws-codepipeline/lib/pipeline.js:1:11358)
    at Stage.attachActionToPipeline (github-issues/pipeline-cross-region/node_modules/aws-cdk-lib/aws-codepipeline/lib/private/stage.js:1:3313)
    at Stage.addAction (github-issues/pipeline-cross-region/node_modules/aws-cdk-lib/aws-codepipeline/lib/private/stage.js:1:1928)
    at new Stage (github-issues/pipeline-cross-region/node_modules/aws-cdk-lib/aws-codepipeline/lib/private/stage.js:1:888)
    at Pipeline.addStage (github-issues/pipeline-cross-region/node_modules/aws-cdk-lib/aws-codepipeline/lib/pipeline.js:1:9264)
```

From the error above, it seems that the method below is not getting the correct pipelineStackName. In a single stack setup, it can successfully get the stack name but in a nested stack setup it is returning `${Token[TOKEN.21]}`.

https://github.com/aws/aws-cdk/blob/1726abddbe10a22c092de7bf0b566710d13f5efd/packages/aws-cdk-lib/aws-codepipeline/lib/private/cross-region-support-stack.ts#L153C1-L155C2

**Comment by khushail** [comment]
Hi @jsunico , thanks for sharing the repro code and your investigation.

I found various related issues around this one ,sharing few of those -
https://github.com/aws/aws-cdk/issues/6190
https://github.com/aws/aws-cdk/issues/27746
https://github.com/aws/aws-cdk/issues/5029
https://github.com/aws/aws-cdk/pull/22223
PR - https://github.com/aws/aws-cdk/pull/4745 , https://github.com/aws/aws-cdk/pull/6419

Although relative PRs have been merged but this CrossAccountRegion deployment is causing the issue. I faced the sImilar issue when tried to deploy the code shared by you. I checked all the [Pipeline related guidelines](https://docs.aws.amazon.com/codepipeline/latest/userguide/limits.html), still getting this issue -
<img width="1185" alt="Screenshot 2024-09-18 at 12 13 59 PM" src="https://github.com/user-attachments/assets/b69f10ce-56b5-4edb-ba61-5cd17e33f652">

This surely seems a bug. I am marking it as P1, requesting inputs from the core team.

**Comment by GavinZZ** [comment]
@jsunico I took a deep dive into the code and I see the main source of issue is with the nested stack you used. When nested stack is used, the stack name becomes a Token representation and does not resolve until deployment. This would then fail in the check in https://github.com/aws/aws-cdk/blob/bf3764fe6046799a2a6e074b39b9a5f4474c603c/packages/aws-cdk-lib/core/lib/stack.ts#L455 because Tokenized value will fail the regex check.

I'd like to understand is there any specific reason you want to use Nested stack in this case. If you change `PipelineCrossRegionStack` in your example to be a standard `cdk.Stack` (instead of `cdk.NestedStack`), it would not fail and should allow you to continue. Let me know if this workaround works for you or you're specifically using nested stack for some purpose.

**Comment by jsunico** [comment]
Hi @GavinZZ, thanks for taking a deeper look into this issue.

We do deploy big applications using CDK and we tend to break down or group resources using NestedStacks. We would have a root stack and a few nested stacks like (network-layer, application-layer, data-layer, pipeline-layer).

In my understanding this is the best practice in managing multiple stacks within CDK. Could you please point me to the correct documentation if I have misunderstood? Thank you.

**Comment by GavinZZ** [comment]
@jsunico There isn't any documentation around best practices of using nested stack in CDK. According to [CFN documentation](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/using-cfn-nested-stacks.html), one of the key benefits of using nested stack is `As your infrastructure grows, common patterns can emerge in which you declare the same components in multiple templates. You can separate out these common components and create dedicated templates for them. Then, use the resource in your template to reference other templates, creating nested stacks.` Of course, nested stack can also helps with the 500 resource limit issue in a given stack. 

From CDK's perspective, I don't see much benefits of using nested stack. If a stack is anywhere close to 500 resource limits, the stack should be split into regular sub-stacks instead of using nested stacks as the solution given how you can simply export a resource and reference a different resource easily in CDK, like the following:

```
const stack1 = new StackThatProvidesABucket(app, 'Stack1' , { env: prod });

// stack2 will take a property { bucket: IBucket }
const stack2 = new StackThatExpectsABucket(app, 'Stack2', {
  bucket: stack1.bucket,
  env: prod
});
```

Regardless, I'm going to work on a fix for this issue as there may be other situation where a stack name can be a tokenized value causing this error.
