### ISSUE TITLE
(aws-cdk-lib): ( Error 'fact-tables not found' on v2.159 but not in v2.158)

### ISSUE THREAD

**Issue by starbuggx** [aws/aws-cdk#31502]
### Describe the bug

Error: Resolution error: Resolution error: Resolution error: Cannot find module '../../region-info/build-tools/fact-tables'
Object creation stack:
  at Execute again with CDK_DEBUG=true to capture stack traces..
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:1225:15)
    at Function.Module._resolveFilename.sharedData.moduleResolveFilenameHook.installedValue [as _resolveFilename] (/home/ubuntu/repos/**/source/cdk/node_modules/@cspotcode/source-map-support/source-map-support.js:811:30)
    at Function.Module._load (node:internal/modules/cjs/loader:1051:27)
    at Module.require (node:internal/modules/cjs/loader:1311:19)
    at require (node:internal/modules/helpers:179:18)
    at fact_tables_1 (/home/ubuntu/repos/**/source/cdk/node_modules/aws-cdk-lib/aws-ec2/lib/vpc-endpoint.js:1:1203)
    at InterfaceVpcEndpointAwsService.getDefaultEndpointPrefix (/home/ubuntu/repos/**/source/cdk/node_modules/aws-cdk-lib/aws-ec2/lib/vpc-endpoint.js:1:7106)
    at Object.produce (/home/ubuntu/repos/**/source/cdk/node_modules/aws-cdk-lib/aws-ec2/lib/vpc-endpoint.js:1:5061)
    at LazyString.resolve (/home/ubuntu/repos/**/source/cdk/node_modules/aws-cdk-lib/core/lib/lazy.js:1:4176)
    at RememberingTokenResolver.resolveToken (/home/ubuntu/repos/**/source/cdk/node_modules/aws-cdk-lib/core/lib/resolvable.js:1:1401) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/home/ubuntu/repos/**/source/cdk/node_modules/aws-cdk-lib/aws-ec2/lib/vpc-endpoint.js',
    '/home/ubuntu/repos/**/source/cdk/node_modules/aws-cdk-lib/aws-ec2/lib/index.js',
    '/home/ubuntu/repos/**/source/cdk/node_modules/aws-cdk-lib/aws-ec2/index.js',

### Regression Issue

- [ ] Select this option if this issue appears to be a regression.

### Last Known Working CDK Version

2.158.0

### Expected Behavior

continue to deploy without error

### Current Behavior

Error: Resolution error: Resolution error: Resolution error: Cannot find module '../../region-info/build-tools/fact-tables'

### Reproduction Steps

Change the cdk version to 2.159.0, this error happens every time.
Switching back to v2.158.0, it's working. 

### CDK CLI Version

2.159.0 (build d77a1b2)

### Node.js Version

v20.17.0

### OS

22.04.4 LTS (Jammy Jellyfish)

### Language

TypeScript

### Language Version

29.5.12

**Comment by pahud** [comment]
related to https://github.com/aws/aws-cdk/issues/31502

**Comment by pahud** [comment]
closing of duplicate
