### ISSUE TITLE
eks: ebs-csi-addon general guidance

### ISSUE THREAD

**Issue by jicowan** [aws/aws-cdk#31522]
### Describe the bug

I am unable to create a role for use with eks Pod Identities. When I try creating the role using `pods.eks.amazonaws.com` I get an error saying "Trust policy of the role provided is invalid. Follow the official documentation to resolve the issue. Service: AWSWesleyFrontend". How are you supposed to create a role for an eks Addon like the EBS CSI driver if pods.eks.amazonaws.com is not valid? I tried working around the issue by creating an EKS ServiceAccount, but the Lambda that creates the service account appears to run after the addon is installed. This causes it to throw an error because the service account/association already exists. What is the proper way to create role/serviceAccount for EKS addons (in Python) using Pod Identities?

### Regression Issue

- [ ] Select this option if this issue appears to be a regression.

### Last Known Working CDK Version

2.159.0 (build d77a1b2)

### Expected Behavior

I want cdk_eks Addon or CfnAddon to be able to automatically create the IAM role with the appropriate trust policy for the serviceAccount used by the Addon. During creation of the Addon I should be able to pass in an array of IAM policy ARNs that I want to associate with the role.  

### Current Behavior

This is the error I received when I tried using ServiceAccount and the referencing it and the role that's created in the CfnAddon.

```python
addon_version="addonVersion",
    configuration_values="configurationValues",
    pod_identity_associations=[eks.CfnAddon.PodIdentityAssociationProperty(
        role_arn="roleArn", # <--
        service_account="serviceAccount" # <--
    )],
```

```12:57:03 PM | CREATE_FAILED        | AWS::EKS::PodIdentityAssociation      | AwsBatchEksCluster...ccount/Association
Resource handler returned message: "Association already exists: a-fzgncpbmis5uonbtc (Service: Eks, Status Code: 409, Request ID: 4d3107a3-41
bd-46a2-9c7b-65421f019432)" (RequestToken: 4d2d81a8-9506-0cf6-caf1-05c97d530b03, HandlerErrorCode: AlreadyExists)```

### Reproduction Steps

See above descriptions

### Possible Solution

Add documentation, and an example, that explains how to create a role that can be used with EKS addons. 

### Additional Information/Context

I ultimate had to switch to using IRSA using the following code. I'm hoping there's a better/simpler way: 
```python
issuer_hostpath_ebs = CfnJson(
            self, "IssuerHostPathEbs",
            value={
                f"{eks_cluster.open_id_connect_provider.open_id_connect_provider_issuer}:sub": 
                "system:serviceaccount:kube-system:ebs-csi-node-sa"
            }
        )

        ebs_csi_trust_policy=iam.FederatedPrincipal(
            federated=eks_cluster.open_id_connect_provider.open_id_connect_provider_arn,
            conditions={
                "StringEquals": issuer_hostpath_ebs
            },
            assume_role_action="sts:AssumeRoleWithWebIdentity"
        )
        ebs_csi_driver_role=iam.Role(self, "EbsCsiDriverRole",
            managed_policies=[iam.ManagedPolicy.from_managed_policy_arn(self, "EBSCSIDriverPolicy", managed_policy_arn="arn:aws:iam::aws:policy/service-role/AmazonEBSCSIDriverPolicy")],
            assumed_by=ebs_csi_trust_policy,
        )
        
        ebs_csi_addon = eks.CfnAddon(self, "eks-ebs-csi-driver",
            cluster_name=eks_cluster.cluster_name,
            addon_name="aws-ebs-csi-driver",
            addon_version="v1.34.0-eksbuild.1",
            preserve_on_delete=False,
            service_account_role_arn=ebs_csi_driver_role.role_arn
        )
```

### CDK CLI Version

2.159.0 (build d77a1b2)

### Node.js Version

20.16.0

### OS

MacOS

### Language

Python

### Language Version

Python 3.12

**Comment by pahud** [comment]
Hi @jicowan 

To use [eks pod identities](https://github.com/aws/aws-cdk/tree/main/packages/aws-cdk-lib/aws-eks#pod-identities), you need to create `ServiceAccount` with `POD_IDENTITY` identityType.


```ts
// Create a new VPC
const vpc = new ec2.Vpc(stack, 'VPC', {
  maxAzs: 2,
});

// Create a new EKS cluster with version 1.30
const cluster = new eks.Cluster(stack, 'EKSCluster', {
  vpc,
  version: eks.KubernetesVersion.V1_30,
});

// Create a ServiceAccount with pod identity
const sa = new eks.ServiceAccount(stack, 'ServiceAccount', {
  cluster,
  name: 'test-sa',
  namespace: 'default',
  identityType: eks.IdentityType.POD_IDENTITY,
});
```

The role for the ServiceAccount would automatically be created and you have `sa.role` with construct methods.

```ts
export class DummyStack extends Stack {
  constructor(scope: Construct, id: string, props: StackProps) {
    super(scope, id, props);

    const vpc = ec2.Vpc.fromLookup(this, 'Vpc', { isDefault: true });

    const cluster = new eks.Cluster(this, 'EKSCluster', {
      vpc,
      version: eks.KubernetesVersion.V1_29,
    });

    // Create a ServiceAccount with pod identity
    const sa = new eks.ServiceAccount(this, 'ServiceAccount', {
      cluster,
      name: 'test-sa',
      namespace: 'default',
      identityType: eks.IdentityType.POD_IDENTITY,
    });
    
    // Cfnout the role name
    new CfnOutput(this, 'RoleArnOutput', { value: sa.role.roleName });
    sa.role.addManagedPolicy(iam.ManagedPolicy.fromManagedPolicyArn(this, 'EBSCSIDriverPolicy', 'arn:aws:iam::aws:policy/service-role/AmazonEBSCSIDriverPolicy'))

  }
}
```

Is this something you expect?

**Comment by jicowan** [comment]
That's what I expected and that's what I tried, however, when creating the environment, the Addon is provisioned before the SA. When the SA is finally provisioned it throws an error saying that a pod identity association and service account already exists. I saw this in the Lambda logs for the helper function. I can try it again in a clean environment. 

This still doesn't resolve the other issue I was having with the service pods.eks.amazonaws.com not being recognized.

**Comment by jicowan** [comment]
Now that I think of it, the Lambda function may be firing multiple times. Is there a way to configure it to run once and only once? The problem is, the stack rolls back or doesn't continue when it encounters the "already exists" error.

**Comment by jicowan** [comment]
Here's the code I originally used: 
```python
my_role = self.create_service_account(service_account_name="ebs-csi-node-sa", namespace="kube-system", pod_identity=True,
                                              cluster=cluster, policy=iam.ManagedPolicy.from_managed_policy_arn(self, "ebs-csi-policy", managed_policy_arn="arn:aws:iam::aws:policy/service-role/AmazonEBSCSIDriverPolicy"))

        cfn_addon = eks.CfnAddon(self, "ebs-csi-addon",
                                 addon_name="aws-ebs-csi-driver",
                                 addon_version="v1.34.0-eksbuild.1",
                                 pod_identity_associations=[eks.CfnAddon.PodIdentityAssociationProperty(
                                     role_arn=my_role.role_arn,
                                     service_account="ebs-csi-node-sa"
                                 )],
                                 cluster_name=cluster.cluster_name)

    def create_service_account(self, service_account_name: str, namespace: str, pod_identity: bool, cluster: eks.Cluster, policy: iam.ManagedPolicy):
        sa = eks.ServiceAccount(self, f"ServiceAccount-{service_account_name}",
                                cluster=cluster,
                                name=service_account_name,
                                namespace=namespace,
                                identity_type=eks.IdentityType.POD_IDENTITY if pod_identity is True else eks.IdentityType.IRSA
                                )
        role = sa.role
        role.add_managed_policy(policy=policy)
        return role
```
And the error: 
```
3:14:19 PM | CREATE_FAILED        | AWS::EKS::Addon                       | ebscsiaddon
Resource handler returned message: "Service account ebs-csi-node-sa in pod identity configuration is not supported for addon aws-ebs-csi-driver (Service: Eks, St
atus Code: 400, Request ID: d166e2bc-7ac9-453d-8821-0ea092878fa6)" (RequestToken: b95cde83-c682-a125-f5a7-e081f140bdb6, HandlerErrorCode: InvalidRequest)


 ❌  CdkStack failed: Error: The stack named CdkStack failed to deploy: UPDATE_FAILED (The following resource(s) failed to create: [ebscsiaddon]. ): Resource handler returned message: "Service account ebs-csi-node-sa in pod identity configuration is not supported for addon aws-ebs-csi-driver (Service: Eks, Status Code: 400, Request ID: d166e2bc-7ac9-453d-8821-0ea092878fa6)" (RequestToken: b95cde83-c682-a125-f5a7-e081f140bdb6, HandlerErrorCode: InvalidRequest)
    at FullCloudFormationDeployment.monitorDeployment (/usr/local/lib/node_modules/aws-cdk/lib/index.js:463:10567)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Object.deployStack2 [as deployStack] (/usr/local/lib/node_modules/aws-cdk/lib/index.js:466:200334)
    at async /usr/local/lib/node_modules/aws-cdk/lib/index.js:466:181756

 ❌ Deployment failed: Error: The stack named CdkStack failed to deploy: UPDATE_FAILED (The following resource(s) failed to create: [ebscsiaddon]. ): Resource handler returned message: "Service account ebs-csi-node-sa in pod identity configuration is not supported for addon aws-ebs-csi-driver (Service: Eks, Status Code: 400, Request ID: d166e2bc-7ac9-453d-8821-0ea092878fa6)" (RequestToken: b95cde83-c682-a125-f5a7-e081f140bdb6, HandlerErrorCode: InvalidRequest)
    at FullCloudFormationDeployment.monitorDeployment (/usr/local/lib/node_modules/aws-cdk/lib/index.js:463:10567)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Object.deployStack2 [as deployStack] (/usr/local/lib/node_modules/aws-cdk/lib/index.js:466:200334)
    at async /usr/local/lib/node_modules/aws-cdk/lib/index.js:466:181756

```
Not really sure what I'm doing wrong @pahud

**Comment by pahud** [comment]
@jicowan 

Let's first make sure we are aligned. I just deployed this with no error.

```ts
export class EksDummyStack extends Stack {
  constructor(scope: Construct, id: string, props: StackProps) {
    super(scope, id, props);

    const vpc = ec2.Vpc.fromLookup(this, 'Vpc', { isDefault: true });

    const cluster = new eks.Cluster(this, 'EKSCluster', {
      vpc,
      version: eks.KubernetesVersion.V1_30,
      defaultCapacity: 1,
      kubectlLayer: new KubectlV30Layer(this, 'KubectlLayer'),
    });

    // Create a ServiceAccount with pod identity
    const sa = new eks.ServiceAccount(this, 'ServiceAccount', {
      cluster,
      name: 'test-sa',
      namespace: 'default',
      identityType: eks.IdentityType.POD_IDENTITY,
    });
    
    // Cfnout the role name
    new CfnOutput(this, 'RoleArnOutput', { value: sa.role.roleName });
    sa.role.addManagedPolicy(iam.ManagedPolicy.fromManagedPolicyArn(this, 'EBSCSIDriverPolicy', 'arn:aws:iam::aws:policy/service-role/AmazonEBSCSIDriverPolicy'))
  }
}
```

And I believe in Python it looks like this

```py
from aws_cdk import (
    aws_ec2 as ec2,
    aws_eks as eks,
    aws_iam as iam,
    core
)

class EksDummyStack(core.Stack):
    def __init__(self, scope: core.Construct, id: str, **kwargs) -> None:
        super().__init__(scope, id, **kwargs)

        # Create a VPC
        vpc = ec2.Vpc.from_lookup(self, 'Vpc', is_default=True)

        # Create an EKS cluster
        cluster = eks.Cluster(self, 'EKSCluster',
                              vpc=vpc,
                              version=eks.KubernetesVersion.V1_30,
                              default_capacity=1,
                              kubectl_layer=eks.KubectlLayer(self, 'KubectlLayer'))

        # Create a service account
        sa = eks.ServiceAccount(self, 'ServiceAccount',
                               cluster=cluster,
                               name='test-sa',
                               namespace='default',
                               identity_type=eks.IdentityType.POD_IDENTITY)

        # Add a managed policy to the service account role
        sa.role.add_managed_policy(iam.ManagedPolicy.from_aws_managed_policy_name('AmazonEBSCSIDriverPolicy'))

        # Output the role name
        core.CfnOutput(self, 'RoleArnOutput', value=sa.role.role_name)
```

Anbd if I check the role behind the SA:

<img width="410" alt="image" src="https://github.com/user-attachments/assets/e0079132-ba13-4700-92d4-67b25f8fb8f4">

<img width="541" alt="image" src="https://github.com/user-attachments/assets/bdc9d1a7-5eb8-4977-a4d4-1dc1d63163bd">

**Comment by jicowan** [comment]
Try using that with an EBS CSI addon. It will throw an error.

**Comment by jicowan** [comment]
i'm going to try removing the pod_identity_associations from the CfnAddon object and see what happens since the SA and IAM role are already created by the service_account. If that works, it's not totally clear to me _when_ you're supposed to use the role_arn and service_account parameters. When I tried creating a role with a servicePrincipal of `pods.eks.amazonaws.com` it threw an error, saying it was not a valid servicePrincipal.

**Comment by jicowan** [comment]
I'm going to close this issue. For this to work you need to create a ServiceAccount that references the name of the Kubernetes serviceAccount that the addon uses. For example, the the ebs-csi-driver you would create a ServiceAccount with a name of ebs-csi-node-sa. Then you can use the Addon resource to create the addon (assuming the addon supports Pod Identities). When creating the Addon you DO NOT need to reference the pod identity association, the role ARN or the service account. This is not at all clear from the documentation.

**Comment by pahud** [comment]
OK after a lot of tests and iterations, this works for me!

```py
import aws_cdk.lambda_layer_kubectl_v30 as kubectl

class CdkStack(Stack):
    def __init__(self, scope: Construct, construct_id: str, **kwargs) -> None:
        super().__init__(scope, construct_id, **kwargs)

        masters_role = iam.Role(self, "eks-admin", assumed_by=iam.AccountRootPrincipal())

        # Create an EKS cluster
        cluster = eks.Cluster(self, "quant-eks",
            vpc=ec2.Vpc.from_lookup(self, "VPC", is_default=True),
            version=eks.KubernetesVersion.V1_30,
            masters_role=masters_role,
            kubectl_layer=kubectl.KubectlV30Layer(self, "KubectlLayer"),
            authentication_mode=eks.AuthenticationMode.API_AND_CONFIG_MAP
        )
        
        sa = self.create_service_account(service_account_name="ebs-csi-controller-sa", 
                namespace="kube-system", pod_identity=True,
                cluster=cluster, policy=iam.ManagedPolicy.from_managed_policy_arn(self, "ebs-csi-policy", managed_policy_arn="arn:aws:iam::aws:policy/service-role/AmazonEBSCSIDriverPolicy")
        )
        # We just need the role, we don't need the association built from the ServiceAccount L2 construct
        # sa.node.try_remove_child("Association")
        
        # create the AddOn using L2
        ebs_csi_addon = eks.Addon(self, "ebs-csi-addon",
            addon_name="aws-ebs-csi-driver",
            addon_version="v1.35.0-eksbuild.1",
            cluster=cluster,
            preserve_on_delete=False, 
            # service_account_role=sa.role
        )
        
        # add_property_override with PodIdentityAssociations
        cfnaddon = ebs_csi_addon.node.default_child 
        # cfnaddon.add_property_override("PodIdentityAssociations", [
        #     {
        #       'RoleArn': sa.role.role_arn,
        #       'ServiceAccount': sa.service_account_name,
        #     }
        # ])
        cfnaddon.add_property_override("ServiceAccountRoleArn", sa.role.role_arn)
        cfnaddon.add_property_override("ResolveConflicts", 'OVERWRITE')
        cfn_eks_pod_identity_agent_addon = cluster.node.try_find_child("EksPodIdentityAgentAddon")
        ebs_csi_addon.node.add_dependency(sa, cfn_eks_pod_identity_agent_addon)
        
        

    def create_service_account(self, service_account_name: str, namespace: str, pod_identity: bool, cluster: eks.Cluster, policy: iam.ManagedPolicy):
        sa = eks.ServiceAccount(self, f"ServiceAccount-{service_account_name}",
            cluster=cluster,
            name=service_account_name,
            namespace=namespace,
            identity_type=eks.IdentityType.POD_IDENTITY if pod_identity is True else eks.IdentityType.IRSA
        )
        # role = sa.role
        sa.role.add_managed_policy(policy=policy)
        return sa
```

```sh
 % kubectl -n kube-system get po   
NAME                                  READY   STATUS    RESTARTS        AGE
aws-node-kzlbr                        2/2     Running   2 (3h15m ago)   3h18m
aws-node-mqphl                        2/2     Running   2 (3h15m ago)   3h17m
coredns-586b798467-49fmg              1/1     Running   1 (3h15m ago)   3h21m
coredns-586b798467-99z9k              1/1     Running   1 (3h15m ago)   3h21m
ebs-csi-controller-6cb8c67fcf-dnt2b   6/6     Running   0               104s
ebs-csi-controller-6cb8c67fcf-frg5n   6/6     Running   0               104s
ebs-csi-node-btrtt                    3/3     Running   0               104s
ebs-csi-node-tlwxj                    3/3     Running   0               104s
eks-pod-identity-agent-5dhl5          1/1     Running   0               31m
eks-pod-identity-agent-pkhpx          1/1     Running   0               31m
kube-proxy-h9vxq                      1/1     Running   1 (3h15m ago)   3h18m
kube-proxy-nvxt2                      1/1     Running   1 (3h15m ago)   3h17m
```

I am pretty sure there's no existing document about how to deploy that with CDK. I hope the sample above helps.

**Comment by pahud** [comment]
@jicowan  let me know if this helps.

**Comment by neoakris** [comment]
Thank you both, this is poorly documented, but google search directs here.  
Here's a useful example of installing AWS LB Controller based on TypeScript.  
(I went with a manual installation as IMO many alternative options were poorly maintained/lacked customization or access to latest version.)  

```typescript
import request from 'sync-request-curl'; //npm install sync-request-curl (cdk requires sync functions, async not allowed)

// The eks-pod-identity-agent Add-on is purposefully commented out due to a CDK bug https://github.com/aws/aws-cdk/issues/32580
// Another call triggers it's installation, and the cdk bug complains about it already being present.
// new eks.Addon(this.stack, 'eks-pod-identity-agent', {
//     cluster,
//     addonName: 'eks-pod-identity-agent', 
//     addonVersion: 'v1.3.4-eksbuild.1' //v--query for latest
//     // aws eks describe-addon-versions --kubernetes-version=1.31 --addon-name=eks-pod-identity-agent --query='addons[].addonVersions[].addonVersion' | jq '.[0]'
// });

// Install AWS load balancer controller via Helm chart
const ALBC_Version = 'v2.11.0'; //Jan 23, 2025 latest from https://github.com/kubernetes-sigs/aws-load-balancer-controller/releases
const ALBC_IAM_Policy_Url = `https://raw.githubusercontent.com/kubernetes-sigs/aws-load-balancer-controller/refs/tags/${ALBC_Version}/docs/install/iam_policy.json`
const ALBC_IAM_Policy_JSON = JSON.parse(request("GET", ALBC_IAM_Policy_Url).body.toString());
const ALBC_IAM_Policy = new iam.Policy(this.stack, `${this.config.id}_AWS_LB_Controller_policy_for_EKS`, {
    document: iam.PolicyDocument.fromJson( ALBC_IAM_Policy_JSON ),
});
const ALBC_Kube_SA = new eks.ServiceAccount(this.stack, 'aws-load-balancer-controller', {
    cluster: cluster,
    name: 'aws-load-balancer-controller',
    namespace: 'kube-system',
    identityType: eks.IdentityType.POD_IDENTITY, //depends on eks-pod-identity-agent addon
    //Note: It's not documented, but this generates 3 things:
    //1. A kube SA in the namespace of the cluster
    //2. An IAM role paired to the Kube SA
    //3. An EKS Pod Identity Association
});
ALBC_Kube_SA.role.attachInlinePolicy(ALBC_IAM_Policy);
const awsLoadBalancerControllerChart = cluster.addHelmChart('AWSLoadBalancerController', {
    chart: 'aws-load-balancer-controller',
    repository: 'https://aws.github.io/eks-charts',
    namespace: "kube-system",
    release: 'aws-load-balancer-controller',
    version: '1.11.0', //<-- helm chart version based on the following command
    // curl https://raw.githubusercontent.com/kubernetes-sigs/aws-load-balancer-controller/refs/tags/v2.11.0/helm/aws-load-balancer-controller/Chart.yaml | grep version: | cut -d ':' -f 2
    wait: true,
    timeout: cdk.Duration.minutes(15),
    values: { //<-- helm chart values per https://github.com/kubernetes-sigs/aws-load-balancer-controller/blob/v2.11.0/helm/aws-load-balancer-controller/values.yaml
        clusterName: cluster.clusterName,
        replicaCount: 1,
        serviceAccount: {
            name: "aws-load-balancer-controller",
            create: false,
        },
    },
});
```

**Comment by jicowan** [comment]
Thanks for the example. I wrote a blog, https://jicowan.medium.com/installing-eks-addons-with-the-aws-cdk-26b66668f630, that explains how I finally resolved the issue.

**Comment by neoakris** [comment]
Btw this might still be bugged, I kept testing jicowan's examples (well the Typescript equivalent of the Python examples) and never could get them to work.

Here's a TypeScript Example that works:
```TypeScript
    const ebs_csi_addon_iam_role = new iam.Role(stack, 'aws-ebs-csi-driver-iam-role', {
        managedPolicies: [ iam.ManagedPolicy.fromAwsManagedPolicyName('service-role/AmazonEBSCSIDriverPolicy') ],
        assumedBy: (new cdk.aws_iam.ServicePrincipal("pods.eks.amazonaws.com")),
    });
    ebs_csi_addon_iam_role.assumeRolePolicy!.addStatements(
        new iam.PolicyStatement({
            actions: ['sts:AssumeRole', 'sts:TagSession'],
            principals: [new iam.ServicePrincipal('pods.eks.amazonaws.com')],
        })
    );
    const ebs_csi_addon = new eks.CfnAddon(stack, 'aws-ebs-csi-driver', {
        clusterName: cluster.clusterName,
        addonName: 'aws-ebs-csi-driver',
        addonVersion: 'v1.41.0-eksbuild.1', //v--query for latest
        // aws eks describe-addon-versions --kubernetes-version=1.31 --addon-name=aws-ebs-csi-driver --query='addons[].addonVersions[].addonVersion' | jq '.[0]'
        resolveConflicts: 'OVERWRITE',
        podIdentityAssociations: [
            {
                serviceAccount: "ebs-csi-controller-sa",
                roleArn: ebs_csi_addon_iam_role.roleArn,
            }
        ], // (v-- replicaCount: 1, makes logs easier to read/debug, and doesn't hurt stability.)
        configurationValues: `{
            controller: {
                "replicaCount": 1,
            },
        }`, //end aws-ebs-csi-driver configurationValues override
    });
```
