### ISSUE TITLE
(aws-cdk): hotswap requires assetMetadata

### ISSUE THREAD

**Issue by steven10172** [aws/aws-cdk#31562]
### Describe the issue

It would be useful to document that the hotswap feature relies on the presence of asset metadata and will fail if `"assetMetadata": false,` is present in `cdk.json`.

Relevant code check: https://github.com/aws/aws-cdk/blob/main/packages/aws-cdk/lib/api/nested-stack-helpers.ts#L124

Example error:
```
MyStack-personal (dev-xxx-MyStack): deploying... [1/1]
[0%] start: Publishing xxxxxxxx:current
[100%] success: Published xxxxxx:current

 ❌  MyStack-personal (dev-xxx-MyStack) failed: TypeError: Cannot read properties of undefined (reading 'physicalName')
    at findNestedHotswappableChanges (/Users/my-login/projects/MyProject/src/MyProjectCDK/node_modules/aws-cdk/lib/index.js:445:20423)
    at classifyResourceChanges (/Users/my-login/projects/MyProject/src/MyProjectCDK/node_modules/aws-cdk/lib/index.js:445:17863)
    at tryHotswapDeployment (/Users/my-login/projects/MyProject/src/MyProjectCDK/node_modules/aws-cdk/lib/index.js:445:16718)
    at async deployStack (/Users/my-login/projects/MyProject/src/MyProjectCDK/node_modules/aws-cdk/lib/index.js:451:605)
    at async Object.deployStack2 [as deployStack] (/Users/my-login/projects/MyProject/src/MyProjectCDK/node_modules/aws-cdk/lib/index.js:454:199716)
    at async /Users/my-login/projects/MyProject/src/MyProjectCDK/node_modules/aws-cdk/lib/index.js:454:181438

 ❌ Deployment failed: TypeError: Cannot read properties of undefined (reading 'physicalName')
    at findNestedHotswappableChanges (/Users/my-login/projects/MyProject/src/MyProjectCDK/node_modules/aws-cdk/lib/index.js:445:20423)
    at classifyResourceChanges (/Users/my-login/projects/MyProject/src/MyProjectCDK/node_modules/aws-cdk/lib/index.js:445:17863)
    at tryHotswapDeployment (/Users/my-login/projects/MyProject/src/MyProjectCDK/node_modules/aws-cdk/lib/index.js:445:16718)
    at async deployStack (/Users/my-login/projects/MyProject/src/MyProjectCDK/node_modules/aws-cdk/lib/index.js:451:605)
    at async Object.deployStack2 [as deployStack] (/Users/my-login/projects/MyProject/src/MyProjectCDK/node_modules/aws-cdk/lib/index.js:454:199716)
    at async /Users/my-login/projects/MyProject/src/MyProjectCDK/node_modules/aws-cdk/lib/index.js:454:181438

```

### Links

https://github.com/aws/aws-cdk/blob/v1-main/packages/aws-cdk/README.md#hotswap-deployments-for-faster-development

**Comment by ashishdhingra** [comment]
- Per [findNestedHotswappableChanges()](https://github.com/aws/aws-cdk/blob/4b00ffeb86b3ebb9a0190c2842bd36ebb4043f52/packages/aws-cdk/lib/api/hotswap-deployments.ts#L232), `physicalName` needs to be present for nested stack for it to be hotswappable.
- The path to customer mentioned check is [tryHotswapDeployment()](https://github.com/aws/aws-cdk/blob/4ddc702236e74abd179b5d866614066f71a0f91b/packages/aws-cdk/lib/api/hotswap-deployments.ts#L69) > [loadCurrentTemplateWithNestedStacks()](https://github.com/aws/aws-cdk/blob/4ddc702236e74abd179b5d866614066f71a0f91b/packages/aws-cdk/lib/api/nested-stack-helpers.ts#L28) > [loadNestedStacks()](https://github.com/aws/aws-cdk/blob/4ddc702236e74abd179b5d866614066f71a0f91b/packages/aws-cdk/lib/api/nested-stack-helpers.ts#L66) > [isCdkManagedNestedStack()](https://github.com/aws/aws-cdk/blob/4ddc702236e74abd179b5d866614066f71a0f91b/packages/aws-cdk/lib/api/nested-stack-helpers.ts#L124)

It would be helpful to mention that `assetMetadata` is required for hotswap deployments.
