### ISSUE TITLE
aws-lambda: aws_lambda.Function.from_function_arn returns FunctionBaseProxy instead of IFunction object

### ISSUE THREAD

**Issue by arutz12** [aws/aws-cdk#31712]
### Describe the bug

CDK: 2.161.1
Python: 3.9.18 (and 3.11.7)
aws-solutions-constructs.aws-eventbridge-lambda: 2.72.0

`aws_lambda.Function.from_function_arn` returns _FunctionBaseProxy_ instead of _IFunction_ as documented.
Therefore the object fails when typechecked in the **aws-solutions-constructs.aws-eventbridge-lambda** module:

### Regression Issue

- [ ] Select this option if this issue appears to be a regression.

### Expected Behavior

Function returns object of type _IFunction_ as documented.

### Current Behavior

Function returned _FunctionBaseProxy_ object.

### Reproduction Steps

```
#!/usr/bin/env python3

from constructs import Construct
import aws_cdk as cdk
from aws_cdk import aws_lambda, aws_events
from aws_solutions_constructs import aws_eventbridge_lambda

class LambdaFunctionTest(cdk.Stack):

    def __init__(self, scope: Construct, construct_id: str, **kwargs) -> None:
        super().__init__(scope, construct_id, **kwargs)

        function_arn = f"arn:aws:lambda:us-east-1:1234567890:function:LambdaFunctionName"

        event_lambda = aws_lambda.Function.from_function_arn(self, "LambdaFunction", function_arn)

        event_to_lambda = aws_eventbridge_lambda.EventbridgeToLambda(
            scope=self,
            id="EventToLambda",
            event_rule_props=aws_events.RuleProps(),
            existing_lambda_obj=event_lambda
        )


app = cdk.App()
LambdaFunctionTest(app, "LambdaFunctionTest")
app.synth()


```

### CDK CLI Version

2.161.1

### Node.js Version

v18.17.1

### OS

KDE neon 6.2 (Ubuntu 22.04)

### Language

Python

### Language Version

3.9.18 (also 3.11.7)

### Other information

Running _synth_ on the code:

```
Traceback (most recent call last):
  File "/tmp/lambda_test/app.py", line 26, in <module>
    LambdaFunctionTest(app, "LambdaFunctionTest")
  File "/tmp/lambda_test/.venv/lib/python3.9/site-packages/jsii/_runtime.py", line 118, in __call__
    inst = super(JSIIMeta, cast(JSIIMeta, cls)).__call__(*args, **kwargs)
  File "/tmp/lambda_test/app.py", line 17, in __init__
    event_to_lambda = aws_eventbridge_lambda.EventbridgeToLambda(
  File "/tmp/lambda_test/.venv/lib/python3.9/site-packages/jsii/_runtime.py", line 118, in __call__
    inst = super(JSIIMeta, cast(JSIIMeta, cls)).__call__(*args, **kwargs)
  File "/tmp/lambda_test/.venv/lib/python3.9/site-packages/aws_solutions_constructs/aws_eventbridge_lambda/__init__.py", line 214, in __init__
    props = EventbridgeToLambdaProps(
  File "/tmp/lambda_test/.venv/lib/python3.9/site-packages/aws_solutions_constructs/aws_eventbridge_lambda/__init__.py", line 281, in __init__
    check_type(argname="argument existing_lambda_obj", value=existing_lambda_obj, expected_type=type_hints["existing_lambda_obj"])
  File "/tmp/lambda_test/.venv/lib/python3.9/site-packages/aws_solutions_constructs/aws_eventbridge_lambda/__init__.py", line 164, in check_type
    return typeguard.check_type(argname=argname, value=value, expected_type=expected_type) # type:ignore
  File "/tmp/lambda_test/.venv/lib/python3.9/site-packages/typeguard/__init__.py", line 757, in check_type
    checker_func(argname, value, expected_type, memo)
  File "/tmp/lambda_test/.venv/lib/python3.9/site-packages/typeguard/__init__.py", line 558, in check_union
    raise TypeError('type of {} must be one of ({}); got {} instead'.
TypeError: type of argument existing_lambda_obj must be one of (aws_cdk.aws_lambda.Function, NoneType); got aws_cdk.aws_lambda._FunctionBaseProxy instead

```

**Comment by kmonihen** [comment]
I'm having this same issue and it seems to be caused by an upgrade to `typeguard`. If I pin typeguard to 2.13.3 I don't get the error.

I had 4.3.0 installed before pinning to 2.13.3:
```
Installing collected packages: typeguard
  Attempting uninstall: typeguard
    Found existing installation: typeguard 4.3.0
    Uninstalling typeguard-4.3.0:
      Successfully uninstalled typeguard-4.3.0
Successfully installed typeguard-2.13.3
```

**Comment by medley56** [comment]
I'm having a similar issue with the recent typeguard changes. 2.13.3 works for me but if I upgrade to v3 I get a bunch of warnings and v4 actually prevents cdk synthesis because `sns_subscriptions.LambdaSubscription(function)` expects an `IFunction`, which a `DockerImageFunction` apparently is not.

**Comment by joshua-haunty** [comment]
Trying to avoid saying the same thing, but this issue is reproducable on python 3.11 as well. When creating a lambda function, the layers supposedly are not of type `ILayerVersion` and the deploy fails. 

```
typeguard.TypeCheckError: list did not match any element in the union:
  Sequence[aws_cdk.aws_lambda.ILayerVersion]: item 0 is not compatible with the ILayerVersion protocol because it has no method named '__jsii_proxy_class__'
```

Setting `typeguard==2.13.3` mitigates.

**Comment by khushail** [comment]
@arutz12 , thanks for reaching out.

Sharing my analysis -
1. On checking the implementation of fromFunctionArn, which internally invokes fromFunctionAttributes(), with return of IFunction object-

https://github.com/aws/aws-cdk/blob/048975e75e718eb980cf33eb47bea04be095c585/packages/aws-cdk-lib/aws-lambda/lib/function.ts#L721

https://github.com/aws/aws-cdk/blob/048975e75e718eb980cf33eb47bea04be095c585/packages/aws-cdk-lib/aws-lambda/lib/function.ts#L721C1-L723C3
```ts
  public static fromFunctionArn(scope: Construct, id: string, functionArn: string): IFunction {
    return Function.fromFunctionAttributes(scope, id, { functionArn });
  }
 
```

2. fromFunctionAttributes() returns IFunction -

https://github.com/aws/aws-cdk/blob/048975e75e718eb980cf33eb47bea04be095c585/packages/aws-cdk-lib/aws-lambda/lib/function.ts#L736

3. this IFunction is actually from the Function-base-

https://github.com/aws/aws-cdk/blob/048975e75e718eb980cf33eb47bea04be095c585/packages/aws-cdk-lib/aws-lambda/lib/function.ts#L10C64-L10C72

**Comment by khushail** [comment]
As documented in cdk docs, the fromFunctionArn should return IFunction object -https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_lambda.Function.html#static-fromwbrfunctionwbrarnscope-id-functionarn

<img width="665" alt="Screenshot 2024-10-10 at 3 00 09 PM" src="https://github.com/user-attachments/assets/52b08377-56f7-4182-9dc5-9452ae99a6a0">

**Comment by khushail** [comment]
This seems like a JSII issue, so moving to JSII Repo for further action.
