### ISSUE TITLE
Fn.getAtt() throws Object of type @aws-cdk/core.Intrinsic is not convertible to @aws-cdk/core.Token Error

### ISSUE THREAD

**Issue by ajnarang** [aws/aws-cdk#3186]
**Note: for support questions, please first reference our [documentation](https://docs.aws.amazon.com/cdk/api/latest), then use [Stackoverflow](https://stackoverflow.com/questions/ask?tags=aws-cdk)**. This repository's issues are intended for feature requests and bug reports.

* **I'm submitting a ...**
  - [x ] :beetle: bug report
  - [ ] :rocket: feature request
  - [ ] :books: construct library gap
  - [ ] :phone: security issue or vulnerability => Please see [policy](https://github.com/awslabs/aws-cdk/security/policy)
  - [ ] :question: support request => Please see note at the top of this template.

* **What is the current behavior?**
Fn.getAttr(logicalId, attributeName) throws error 
Object of type @aws-cdk/core.Intrinsic is not convertible to @aws-cdk/core.Token
Error: Object of type @aws-cdk/core.Intrinsic is not convertible to @aws-cdk/core.Token
    at selectWireType (/private/var/folders/28/t2gr61hn3pb90_3rmnmr6b4r9389z0/T/jsii-java-runtime4445157933952523094/jsii-runtime.js:12447:23)
    at Object.serialize (/private/var/folders/28/t2gr61hn3pb90_3rmnmr6b4r9389z0/T/jsii-java-runtime4445157933952523094/jsii-runtime.js:12185:29)
    at Kernel._fromSandbox (/private/var/folders/28/t2gr61hn3pb90_3rmnmr6b4r9389z0/T/jsii-java-runtime4445157933952523094/jsii-runtime.js:7051:61)
    at Kernel.sinvoke (/private/var/folders/28/t2gr61hn3pb90_3rmnmr6b4r9389z0/T/jsii-java-runtime4445157933952523094/jsii-runtime.js:6517:31)
    at KernelHost.processRequest (/private/var/folders/28/t2gr61hn3pb90_3rmnmr6b4r9389z0/T/jsii-java-runtime4445157933952523094/jsii-runtime.js:6186:28)
    at KernelHost.run (/private/var/folders/28/t2gr61hn3pb90_3rmnmr6b4r9389z0/T/jsii-java-runtime4445157933952523094/jsii-runtime.js:6132:14)
    at processRequest (/private/var/folders/28/t2gr61hn3pb90_3rmnmr6b4r9389z0/T/jsii-java-runtime4445157933952523094/jsii-runtime.js:6132:45)
    at KernelHost.processRequest (/private/var/folders/28/t2gr61hn3pb90_3rmnmr6b4r9389z0/T/jsii-java-runtime4445157933952523094/jsii-runtime.js:6228:16)
    at KernelHost.run (/private/var/folders/28/t2gr61hn3pb90_3rmnmr6b4r9389z0/T/jsii-java-runtime4445157933952523094/jsii-runtime.js:6132:14)
    at processRequest (/private/var/folders/28/t2gr61hn3pb90_3rmnmr6b4r9389z0/T/jsii-java-runtime4445157933952523094/jsii-runtime.js:6132:45)
	at software.amazon.jsii.JsiiRuntime.processErrorResponse(JsiiRuntime.java:112)
	at software.amazon.jsii.JsiiRuntime.requestResponse(JsiiRuntime.java:84)
	at software.amazon.jsii.JsiiClient.callStaticMethod(JsiiClient.java:169)
	at software.amazon.jsii.JsiiObject.jsiiStaticCall(JsiiObject.java:76)
	at software.amazon.awscdk.core.Fn.getAtt(Fn.java:213)

* **What is the expected behavior (or behavior of feature suggested)?**
Expected behavior is to get Fn::GetAttr(logicalId, attribute) to work without error and return a String or IResolvable.

* **What is the motivation / use case for changing the behavior or adding this feature?**
Fn::GetAttr is a very important intrinsic function and must be supported

* **Please tell us about your environment:**
  
  - CDK CLI Version: 0.36.1
  - Module Version: Aws-cdk-java-0.36.x
  - OS: OSX
  - Language: Java

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. associated pull-request, stackoverflow, gitter, etc)

**Comment by rix0rrr** [comment]
This sounds like it would be caused by a version mismatch in some libraries.

**Comment by ajnarang** [comment]
I was able to get around the issue by using the resource reference and using getATTRattr() method.
