### ISSUE TITLE
CDK CLI: Tag not resolved for AsyncFunction value

### ISSUE THREAD

**Issue by scarytom** [aws/aws-cdk#32160]
### Describe the bug

Running `cdk diff` in version 2.167.1 is producing an error when trying to generate a change set, and is falling back to using a diff on template differences.  This worked fin in 2.160.0.

### Regression Issue

Confirmed Regression 

### Last Known Working CDK Version

2.166.0

### Expected Behavior

change sets to be created and used for the cdk diff

### Current Behavior

```shell
Retrieved account ID xxxxxxxxxxxx from disk cache
Error: Tag not resolved for AsyncFunction value
    at getTagObject (/usr/local/lib/node_modules/aws-cdk/lib/index.js:579:21602)
    at stringify5 (/usr/local/lib/node_modules/aws-cdk/lib/index.js:579:22499)
    at _Pair.toString (/usr/local/lib/node_modules/aws-cdk/lib/index.js:566:452)
    at stringify5 (/usr/local/lib/node_modules/aws-cdk/lib/index.js:579:22445)
    at /usr/local/lib/node_modules/aws-cdk/lib/index.js:561:3712
    at Array.reduce (<anonymous>)
    at YAMLMap2.toString (/usr/local/lib/node_modules/aws-cdk/lib/index.js:561:3202)
    at YAMLMap2.toString (/usr/local/lib/node_modules/aws-cdk/lib/index.js:568:3602)
    at stringify5 (/usr/local/lib/node_modules/aws-cdk/lib/index.js:579:22842)
    at _Pair.toString (/usr/local/lib/node_modules/aws-cdk/lib/index.js:566:452)
Could not create a change set, will base the diff on template differences (run again with -v to see the reason)
```

### Reproduction Steps

I'm just running `cdk --strict --verbose --no-version-reporting diff`

### CDK CLI Version

2.167.1

### Node.js Version

22.11.0

### OS

ubuntu

### Language

Java

### Language Version

Java (17)

**Comment by iliapolo** [comment]
@scarytom could you please also provide the following information? (whatever you can):

- Authentication method (i.e `credentials` file? `config` file? env variables? profile? anything else?)
- Output of `cdk diff` with `-vvv`? (account numbers redacted). 

Thanks!

**Comment by scarytom** [comment]
Authentication is via AWS environment variables

The output above is already from cdk diff -vvv.  I'm not sure the full output adds much, but I can attach that tomorrow if that helps at all.

**Comment by Stazz-Sphinx** [comment]
Confirm that, I have the same issue.
