### ISSUE TITLE
Python AttributeError with Lambda.Runtime 

### ISSUE THREAD

**Issue by senorkrabs** [aws/aws-cdk#3224]
**Note: for support questions, please first reference our [documentation](https://docs.aws.amazon.com/cdk/api/latest), then use [Stackoverflow](https://stackoverflow.com/questions/ask?tags=aws-cdk)**. This repository's issues are intended for feature requests and bug reports.

* **I'm submitting a ...**
  - [x] :beetle: bug report
  - [ ] :rocket: feature request
  - [ ] :books: construct library gap
  - [ ] :phone: security issue or vulnerability => Please see [policy](https://github.com/awslabs/aws-cdk/security/policy)
  - [ ] :question: support request => Please see note at the top of this template.

* **What is the current behavior?**
*If the current behavior is a :beetle:bug:beetle:: Please provide the steps to reproduce*
Code:
``` provider=cfn.CustomResourceProvider.lambda_(
                    lambda_.SingletonFunction(
                        self,
                        id= "lambdaCostAndUsageReportCustomResource",
                        uuid=str(uuid.uuid4()),
                        code=lambda_.InlineCode(code_body),
                        handler="index.handler",
                        timeout=core.Duration.seconds(60),
                        runtime= lambda_.Runtime.PYTHON_3_7
    
                    )
```
Produces this error

```
AttributeError: __jsii_type__
```

* **What is the expected behavior (or behavior of feature suggested)?**
cdk synth completes successfully

* **What is the motivation / use case for changing the behavior or adding this feature?**

* **Please tell us about your environment:**
  
  - CDK CLI Version: 0.37.0
  - Module Version: 0.37.0
  - OS: Windows 1
  - Language: Python 

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. associated pull-request, stackoverflow, gitter, etc)
Traceback below. I think this error started after upgrading to 0.37.0. It's entirely possible I'm missing something here. Tried using a string for the `runtime` instead, but got an exception because it expects an object.

```
Traceback (most recent call last):
  File "app.py", line 10, in <module>
    CurStack(app, "cur-setup", env={'region': 'us-east-1'})
  File "D:\Users\**\AppData\Roaming\Python\Python37\site-packages\jsii\_runtime.py", line 66, in __call__
    inst = super().__call__(*args, **kwargs)
  File "D:\Users\**\Documents\Repos\cdk-cur-creator\cur\cur_stack.py", line 13, in __init__
    hello = CurConstruct(self, "SampleCurReport")
  File "D:\Users\**\AppData\Roaming\Python\Python37\site-packages\jsii\_runtime.py", line 66, in __call__
    inst = super().__call__(*args, **kwargs)
  File "d:\users\**\documents\repos\cdk-cur-creator\cur\cur_construct.py", line 125, in __init__
    runtime= lambda_.Runtime.PYTHON_3_7
  File "D:\Users\**\AppData\Roaming\Python\Python37\site-packages\jsii\_runtime.py", line 66, in __call__
    inst = super().__call__(*args, **kwargs)
  File "D:\Users\**\AppData\Roaming\Python\Python37\site-packages\aws_cdk\aws_cloudformation\__init__.py", line 796, in __init__
    jsii.create(CustomResource, self, [scope, id, props])
  File "D:\Users\**\AppData\Roaming\Python\Python37\site-packages\jsii\_kernel\__init__.py", line 199, in create
    overrides=overrides,
  File "D:\Users\**\AppData\Roaming\Python\Python37\site-packages\jsii\_kernel\providers\process.py", line 331, in create
    return self._process.send(request, CreateResponse)
  File "D:\Users\**\AppData\Roaming\Python\Python37\site-packages\jsii\_kernel\providers\process.py", line 300, in send
    req_dict = self._serializer.unstructure(request)
  File "D:\Users\**\AppData\Roaming\Python\Python37\site-packages\cattr\converters.py", line 124, in unstructure
    return self._unstructure_func.dispatch(obj.__class__)(obj)
  File "D:\Users\**\AppData\Roaming\Python\Python37\site-packages\jsii\_kernel\providers\process.py", line 104, in unstructurer
    unstructured = asdict(value)
  File "D:\Users\**\AppData\Roaming\Python\Python37\site-packages\cattr\converters.py", line 189, in unstructure_attrs_asdict
    rv[name] = dispatch(v.__class__)(v)
  File "D:\Users\**\AppData\Roaming\Python\Python37\site-packages\cattr\converters.py", line 209, in _unstructure_seq
    return seq.__class__(dispatch(e.__class__)(e) for e in seq)
  File "D:\Users\**\AppData\Roaming\Python\Python37\site-packages\cattr\converters.py", line 209, in <genexpr>
    return seq.__class__(dispatch(e.__class__)(e) for e in seq)
  File "D:\Users\**\AppData\Roaming\Python\Python37\site-packages\cattr\converters.py", line 220, in _unstructure_mapping
    for k, v in mapping.items()
  File "D:\Users\**\AppData\Roaming\Python\Python37\site-packages\cattr\converters.py", line 220, in <genexpr>
    for k, v in mapping.items()
  File "D:\Users\**\AppData\Roaming\Python\Python37\site-packages\cattr\converters.py", line 220, in _unstructure_mapping
    for k, v in mapping.items()
  File "D:\Users\**\AppData\Roaming\Python\Python37\site-packages\cattr\converters.py", line 220, in <genexpr>
    for k, v in mapping.items()
  File "D:\Users\**\AppData\Roaming\Python\Python37\site-packages\jsii\_kernel\providers\process.py", line 123, in _unstructure_enum
    return {"$jsii.enum": f"{member.__class__.__jsii_type__}/{member.value}"}
  File "C:\Program Files\Python37\lib\enum.py", line 345, in __getattr__
    raise AttributeError(name)
AttributeError: __jsii_type__
```

**Comment by bgdnlp** [comment]
In my experience, that error means that you passed the wrong type to an argument somewhere. This synthesizes for me:
```python
from aws_cdk import (
    core,
    aws_lambda as lambda_
)


class Stack(core.Stack):
    def __init__(self, app, id, **kwargs):
        super().__init__(app, id, **kwargs)

        lambda_.SingletonFunction(
            self,
            id="lambdaCostAndUsageReportCustomResource",
            uuid="REPLACED",
            code=lambda_.InlineCode("REPLACED"),
            handler="index.handler",
            timeout=core.Duration.seconds(60),
            runtime=lambda_.Runtime.PYTHON_3_7
        )


app = core.App()

Stack = Stack(app, 'Stack')

app.synth()
```

Which means that it's probably `code_body`, because I only replaced that and `uuid`. I'm on 0.37.0.

**Comment by charlie0077** [comment]
@senorkrabs I am running into similar issue. Double checked the arguments, cannot find anything wrong. May I ask how did you fix it?
