### ISSUE TITLE
cdk: EEXIST: file already exists cdk.out/asset.

### ISSUE THREAD

**Issue by niqo01** [aws/aws-cdk#32405]
### Describe the bug

Once in a while my cdk pipeline build stage fails with `Error: EEXIST: file already exists, mkdir '/codebuild/output/src1655296161/src/infra/app/cdk.out/asset.0c431533151ced7f801fc37929756c810f2c25f05688ef27239525941184764e'

If I retry the stage the error goes away or can fails again.

### Regression Issue

- [ ] Select this option if this issue appears to be a regression.

### Expected Behavior

No build stage failure. 

### Current Behavior

```
Error: EEXIST: file already exists, mkdir '/codebuild/output/src1655296161/src/infra/app/cdk.out/asset.0c431533151ced7f801fc37929756c810f2c25f05688ef27239525941184764e'
--
158 | at Object.mkdirSync (node:fs:1391:3)
159 | at AssetStaging.stageAsset (/tmp/jsii-kernel-VsmgpX/node_modules/aws-cdk-lib/core/lib/asset-staging.js:1:6636)
160 | at AssetStaging.stageByCopying (/tmp/jsii-kernel-VsmgpX/node_modules/aws-cdk-lib/core/lib/asset-staging.js:1:4287)
161 | at stageThisAsset (/tmp/jsii-kernel-VsmgpX/node_modules/aws-cdk-lib/core/lib/asset-staging.js:1:2788)
162 | at Cache.obtain (/tmp/jsii-kernel-VsmgpX/node_modules/aws-cdk-lib/core/lib/private/cache.js:1:242)
163 | at new AssetStaging (/tmp/jsii-kernel-VsmgpX/node_modules/aws-cdk-lib/core/lib/asset-staging.js:1:3125)
164 | at new Asset (/tmp/jsii-kernel-VsmgpX/node_modules/aws-cdk-lib/aws-s3-assets/lib/asset.js:1:1141)
165 | at AssetCode.bind (/tmp/jsii-kernel-VsmgpX/node_modules/aws-cdk-lib/aws-lambda/lib/code.js:5:4287)
166 | at new Function (/tmp/jsii-kernel-VsmgpX/node_modules/aws-cdk-lib/aws-lambda/lib/function.js:1:10020)
167 | at Kernel._Kernel_create (/tmp/jsii-java-runtime11241269664451585625/lib/program.js:9127:25)
168 | at software.amazon.jsii.JsiiRuntime.processErrorResponse(JsiiRuntime.java:150)
169 | at software.amazon.jsii.JsiiRuntime.requestResponse(JsiiRuntime.java:116)
170 | at software.amazon.jsii.JsiiClient.createObject(JsiiClient.java:89)
171 | at software.amazon.jsii.JsiiEngine.createNewObject(JsiiEngine.java:614)
172 | at software.amazon.awscdk.services.lambda.Function.<init>(Function.java:53)
173 | at software.amazon.awscdk.services.lambda.Function$Builder.build(Function.java:1409)
174 | at enki.hangoutspipeline.stacks.ApiStack.createAliasRecord(ApiStack.kt:428)
175 | at enki.hangoutspipeline.stacks.ApiStack.createARecords(ApiStack.kt:181)
176 | at enki.hangoutspipeline.stacks.ApiStack.<init>(ApiStack.kt:75)
177 | at enki.hangoutspipeline.AppStage.<init>(AppStage.kt:61)
178 | at enki.hangoutspipeline.PipelineStack.buildStage(PipelineStack.kt:80)
179 | at enki.hangoutspipeline.PipelineStack.<init>(PipelineStack.kt:65)
180 | at enki.hangoutspipeline.AppKt.setupPipeline(App.kt:21)
181 | at enki.hangoutspipeline.AppKt.main(App.kt:13
```

### Reproduction Steps

I am not able to reproduce on my laptop and the issue is reproducible 30-40% on Aws pipeline. 
I will try to build a minimal project. 

### CDK CLI Version

2.171.1

### Node.js Version

the one with Linux STANDARD_7_0

### OS

Linux STANDARD_7_0

### Language

Java

**Comment by ashishdhingra** [comment]
@niqo01 Good afternoon. Please share the minimal CDK project and steps to reproduce the issue, including provisioning of CodeBuild project and CodePipeline.
 Do you get this issue consistently or at random?

Thanks,
Ashish
