### ISSUE TITLE
imageName undefined when applying fromEcrRepository cdk 1.0.0

### ISSUE THREAD

**Issue by nikwerhypoport** [aws/aws-cdk#3302]
**Note: for support questions, please first reference our [documentation](https://docs.aws.amazon.com/cdk/api/latest), then use [Stackoverflow](https://stackoverflow.com/questions/ask?tags=aws-cdk)**. This repository's issues are intended for feature requests and bug reports.

* **I'm submitting a ...**
  - [x ] :beetle: bug report
  - [ ] :rocket: feature request
  - [ ] :books: construct library gap
  - [ ] :phone: security issue or vulnerability => Please see [policy](https://github.com/awslabs/aws-cdk/security/policy)
  - [ ] :question: support request => Please see note at the top of this template.

* **What is the current behavior?**
*If the current behavior is a :beetle:bug:beetle:: Please provide the steps to reproduce*

I have the following Stack for a batch job. A deployed docker image exists  in ECR

```js
export class BatchJobStack extends cdk.Stack {
  constructor(scope: cdk.Construct, id: string, props?: cdk.StackProps) {
    super(scope, id, props);

    const repo = Repository.fromRepositoryArn(this, 'JobImage', 'arn:aws:ecr:XXXXXXX:XXXXXX:repository/XXXXXX-batch-job')
    const image =  EcrImage.fromEcrRepository(repo)
    console.log("++++++++++" + image.imageName)
    const jobRole = new iam.CfnRole(this, "job-role",{
         path: '/service/',
         roleName: "update-job-role",
         assumeRolePolicyDocument : new iam.PolicyDocument({
                          statements: [
                                new iam.PolicyStatement(
                                    {
                                            principals: [
                                                            new iam.ServicePrincipal("ecs-tasks.amazonaws.com"),
                                                            new iam.ArnPrincipal("arn:aws:iam::XXXXXXXXXX:root")
                                                        ],
                                            actions: [ "sts:AssumeRole"]
                                            })
                          ]
                      }),

         policies: [
           {
             policyDocument: new iam.PolicyDocument({
                   statements:[
                       new iam.PolicyStatement({
                                    actions: ["kms:Decrypt"],
                                    resources :[
                                       `arn:aws:kms:${this.region}:${this.account}:alias/*`,
                                       `arn:aws:kms:${this.region}:${this.account}:key/*`
                                    ]
                           }
                       ),
                       new iam.PolicyStatement({
                             actions: ["secretsmanager:GetSecretValue"],
                             resources: ["arn:aws:secretsmanager:XXXXXXX:XXXXXXX:secret:XXXXXX"]
                           }
                       )
                   ]
                 }
             ),
             policyName: "job-policy"
           }
         ]
    })

    const jobDef = new batch.CfnJobDefinition(this, "job-def", {
         jobDefinitionName: "job",
          type: "container",
          retryStrategy: {
              attempts: 2
          },
          containerProperties:
               {
                 memory: 512,
                 vcpus: 1,
                 image:  image.imageName,
                command: ["python3", "do_sth.py"]
               }
        })
  }
}

```
 
Execution of `cdk synth` the following error message comes up:

```sh    
++++++++++undefined


/node_modules/@aws-cdk/core/lib/runtime.ts:141
      throw new CfnSynthesisError(message);
            ^
Error: Resolution error: Supplied properties not correct for "CfnJobDefinitionProps"
  containerProperties: supplied properties not correct for "ContainerPropertiesProperty"
    image: required but missing.
Object creation stack:
  at new Intrinsic (/Users/nikolaus.werner/PycharmProjects/ep-dna-ekg-reporting/batch-job-app-cdk-1.0/node_modules/@aws-cdk/core/lib/private/intrinsic.ts:28:26)
  at new PostResolveToken (/Users/nikolaus.werner/PycharmProjects/ep-dna-ekg-reporting/batch-job-app-cdk-1.0/node_modules/@aws-cdk/core/lib/util.ts:83:5)
  at CfnJobDefinition._toCloudFormation (/Users/nikolaus.werner/PycharmProjects/ep-dna-ekg-reporting/batch-job-app-cdk-1.0/node_modules/@aws-cdk/core/lib/cfn-resource.ts:222:29)
  at /Users/nikolaus.werner/PycharmProjects/ep-dna-ekg-reporting/batch-job-app-cdk-1.0/node_modules/@aws-cdk/core/lib/stack.ts:556:56
  at Array.map (<anonymous>)
  at BatchJobAppCdk10Stack._toCloudFormation (/Users/nikolaus.werner/PycharmProjects/ep-dna-ekg-reporting/batch-job-app-cdk-1.0/node_modules/@aws-cdk/core/lib/stack.ts:556:32)
  at BatchJobAppCdk10Stack.synthesize (/Users/nikolaus.werner/PycharmProjects/ep-dna-ekg-reporting/batch-job-app-cdk-1.0/node_modules/@aws-cdk/core/lib/stack.ts:518:51)
  at Function.synth (/Users/nikolaus.werner/PycharmProjects/ep-dna-ekg-reporting/batch-job-app-cdk-1.0/node_modules/@aws-cdk/core/lib/construct.ts:59:28)
  at App.synth (/Users/nikolaus.werner/PycharmProjects/ep-dna-ekg-reporting/batch-job-app-cdk-1.0/node_modules/@aws-cdk/core/lib/app.ts:128:36)
  at process.<anonymous> (/Users/nikolaus.werner/PycharmProjects/ep-dna-ekg-reporting/batch-job-app-cdk-1.0/node_modules/@aws-cdk/core/lib/app.ts:111:45)
  at Object.onceWrapper (events.js:291:20)
  at process.emit (events.js:203:13)
  at process.EventEmitter.emit (domain.js:471:20)
  at process.emit (/Users/nikolaus.werner/PycharmProjects/ep-dna-ekg-reporting/batch-job-app-cdk-1.0/node_modules/source-map-support/source-map-support.js:465:21)
  at process.topLevelDomainCallback (domain.js:126:23)
    at ValidationResult.assertSuccess (/Users/nikolaus.werner/PycharmProjects/ep-dna-ekg-reporting/batch-job-app-cdk-1.0/node_modules/@aws-cdk/core/lib/runtime.ts:141:13)
    at cfnJobDefinitionPropsToCloudFormation (/Users/nikolaus.werner/PycharmProjects/ep-dna-ekg-reporting/batch-job-app-cdk-1.0/node_modules/@aws-cdk/aws-batch/lib/batch.generated.ts:454:48)
    at CfnJobDefinition.renderProperties (/Users/nikolaus.werner/PycharmProjects/ep-dna-ekg-reporting/batch-job-app-cdk-1.0/node_modules/@aws-cdk/aws-batch/lib/batch.generated.ts:553:16)
    at PostResolveToken.ret.Resources [as processor] (/Users/nikolaus.werner/PycharmProjects/ep-dna-ekg-reporting/batch-job-app-cdk-1.0/node_modules/@aws-cdk/core/lib/cfn-resource.ts:233:40)
    at PostResolveToken.postProcess (/Users/nikolaus.werner/PycharmProjects/ep-dna-ekg-reporting/batch-job-app-cdk-1.0/node_modules/@aws-cdk/core/lib/util.ts:92:17)
    at Object.postProcess (/Users/nikolaus.werner/PycharmProjects/ep-dna-ekg-reporting/batch-job-app-cdk-1.0/node_modules/@aws-cdk/core/lib/private/resolve.ts:50:78)
    at DefaultTokenResolver.resolveToken (/Users/nikolaus.werner/PycharmProjects/ep-dna-ekg-reporting/batch-job-app-cdk-1.0/node_modules/@aws-cdk/core/lib/resolvable.ts:133:32)
    at resolve (/Users/nikolaus.werner/PycharmProjects/ep-dna-ekg-reporting/batch-job-app-cdk-1.0/node_modules/@aws-cdk/core/lib/private/resolve.ts:131:29)
    at Object.resolve (/Users/nikolaus.werner/PycharmProjects/ep-dna-ekg-reporting/batch-job-app-cdk-1.0/node_modules/@aws-cdk/core/lib/private/resolve.ts:47:32)
    at resolve (/Users/nikolaus.werner/PycharmProjects/ep-dna-ekg-reporting/batch-job-app-cdk-1.0/node_modules/@aws-cdk/core/lib/private/resolve.ts:152:39)
Subprocess exited with error 1
``` 
As the console.log shows, the image name seems not to be set.

* **Please tell us about your environment:**
  
  - CDK CLI Version: 1.0.0
  - Module Version:1.0.0
  - OS: [OSX High Sierra ]
  - Language: [TypeScript  ]

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. associated pull-request, stackoverflow, gitter, etc)

- stack runs smoothly in cdk 0.33. (with undoing breaking changes)

**Comment by aarym** [comment]
Same issues for me as well when using existing ECR image. Be good to get this resolved asap.

**Comment by NGL321** [comment]
Hi @nikwerhypoport,

Thank you for reporting! I have not yet been able to repro, but one of us will look into it soon.

Please continue to report and submit issues about anything else you may find in the codebase!

**Comment by SanderKnape** [comment]
Also ran into this. You should run the following to get the latest image name:

`repo.repositoryUriForTag('latest')`

The `image.fromEcrRepository` only works when used in conjunction with a ContainerDefinition as only then the `bind()` command is called. Not sure what a proper fix for this is. With some pointers (@NGL321) I could create a PR for that.

**Comment by nikwerhypoport** [comment]
Ok - thx worked for me.

**Comment by rix0rrr** [comment]
Yes, sorry. The `Image.fromEcrRepository()` is only intended to be used with the service you are using the class for. Good point that this is not entirely clear. 

Sander is correct in his recommendation, `repo.repositoryUriForTag()` will be the right expression to use when you are at the L1 level (which you are for Batch currently).

Closing this issue for now, please reopen if you feel this has been closed in error.
