### ISSUE TITLE
Duration static methods don't seem to work with java API

### ISSUE THREAD

**Issue by tvanhens** [aws/aws-cdk#3385]
**Note: for support questions, please first reference our [documentation](https://docs.aws.amazon.com/cdk/api/latest), then use [Stackoverflow](https://stackoverflow.com/questions/ask?tags=aws-cdk)**. This repository's issues are intended for feature requests and bug reports.

* **I'm submitting a ...**
  - [x] :beetle: bug report
  - [ ] :rocket: feature request
  - [ ] :books: construct library gap
  - [ ] :phone: security issue or vulnerability => Please see [policy](https://github.com/aws/aws-cdk/security/policy)
  - [ ] :question: support request => Please see note at the top of this template.

* **What is the current behavior?**
*If the current behavior is a :beetle:bug:beetle:: Please provide the steps to reproduce*

Calling `Duration.seconds(29)` results in an exception.

* **What is the expected behavior (or behavior of feature suggested)?**

`Duration.seconds(29)` should return a Duration object.

* **What is the motivation / use case for changing the behavior or adding this feature?**

* **Please tell us about your environment:**

  - CDK CLI Version: 1.1.0 (build 1a11e96)
  - Module Version: 1.1.0.DEVPREVIEW
  - OS: OSX Mojave
  - Language: Java

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. associated pull-request, stackoverflow, gitter, etc)

Stacktrace:

```
   Argument to Intrinsic must be a plain value object, got () => {
   throw new Error(`Duration.toString() was used, but .toSeconds,
   .toMinutes or .toDays should have been called instead`); } Error:
   Argument to Intrinsic must be a plain value object, got () => {
   throw new Error(`Duration.toString() was used, but .toSeconds,
   .toMinutes or .toDays should have been called instead`); } at new
   Intrinsic
   (/private/var/folders/f6/fxr8vlfn6bb54sff66lx7qfr0000gn/T/jsii-kernel-MjEHJS/node_modules/@aws-cdk/core/lib/private/intrinsic.js:18:19)
   at Function.asAny
   (/private/var/folders/f6/fxr8vlfn6bb54sff66lx7qfr0000gn/T/jsii-kernel-MjEHJS/node_modules/@aws-cdk/core/lib/token.js:74:52)
   at Function.asString
   (/private/var/folders/f6/fxr8vlfn6bb54sff66lx7qfr0000gn/T/jsii-kernel-MjEHJS/node_modules/@aws-cdk/core/lib/token.js:50:69)
   at Duration.toString
   (/private/var/folders/f6/fxr8vlfn6bb54sff66lx7qfr0000gn/T/jsii-kernel-MjEHJS/node_modules/@aws-cdk/core/lib/duration.js:124:30)
   at _wrapSandboxCode
   (/private/var/folders/f6/fxr8vlfn6bb54sff66lx7qfr0000gn/T/jsii-java-runtime180821756933517341/jsii-runtime.js:6498:51)
   at Kernel._wrapSandboxCode
   (/private/var/folders/f6/fxr8vlfn6bb54sff66lx7qfr0000gn/T/jsii-java-runtime180821756933517341/jsii-runtime.js:7134:19)
   at ret._ensureSync
   (/private/var/folders/f6/fxr8vlfn6bb54sff66lx7qfr0000gn/T/jsii-java-runtime180821756933517341/jsii-runtime.js:6498:25)
   at Kernel._ensureSync
   (/private/var/folders/f6/fxr8vlfn6bb54sff66lx7qfr0000gn/T/jsii-java-runtime180821756933517341/jsii-runtime.js:7102:20)
   at Kernel.invoke
   (/private/var/folders/f6/fxr8vlfn6bb54sff66lx7qfr0000gn/T/jsii-java-runtime180821756933517341/jsii-runtime.js:6497:26)
   at KernelHost.processRequest
   (/private/var/folders/f6/fxr8vlfn6bb54sff66lx7qfr0000gn/T/jsii-java-runtime180821756933517341/jsii-runtime.js:6191:28)
   at KernelHost.run
   (/private/var/folders/f6/fxr8vlfn6bb54sff66lx7qfr0000gn/T/jsii-java-runtime180821756933517341/jsii-runtime.js:6137:14)
   at processRequest
   (/private/var/folders/f6/fxr8vlfn6bb54sff66lx7qfr0000gn/T/jsii-java-runtime180821756933517341/jsii-runtime.js:6137:45)
   at KernelHost.processRequest
   (/private/var/folders/f6/fxr8vlfn6bb54sff66lx7qfr0000gn/T/jsii-java-runtime180821756933517341/jsii-runtime.js:6233:16)
   at KernelHost.run
   (/private/var/folders/f6/fxr8vlfn6bb54sff66lx7qfr0000gn/T/jsii-java-runtime180821756933517341/jsii-runtime.js:6137:14)
   at processRequest
   (/private/var/folders/f6/fxr8vlfn6bb54sff66lx7qfr0000gn/T/jsii-java-runtime180821756933517341/jsii-runtime.js:6137:45)
   at KernelHost.processRequest
   (/private/var/folders/f6/fxr8vlfn6bb54sff66lx7qfr0000gn/T/jsii-java-runtime180821756933517341/jsii-runtime.js:6233:16)
   at KernelHost.run
   (/private/var/folders/f6/fxr8vlfn6bb54sff66lx7qfr0000gn/T/jsii-java-runtime180821756933517341/jsii-runtime.js:6137:14)
   at processRequest
   (/private/var/folders/f6/fxr8vlfn6bb54sff66lx7qfr0000gn/T/jsii-java-runtime180821756933517341/jsii-runtime.js:6137:45)
```

**Comment by eladb** [comment]
Out of context, this is not reproducing.

This prints `29`:

```java
import software.amazon.awscdk.core.Duration;

public class HelloApp {
    public static void main(final String argv[]) {
        Duration x = Duration.seconds(29);
        System.out.println(x.toSeconds());
    }
}
```

From your error it seems like you are using this in the context of a token. Can you provide some more of your code, so we can try to repro?

**Comment by tvanhens** [comment]
We have since moved to using our own Clojure wrapper for CDK rather than using the Java bindings so I no longer have a reproducible example for this issue.

**Comment by eladb** [comment]
Ok. I’ll close for now. Reopen if needed

**Comment by metametadata** [comment]
The problem is reproducible in Clojure REPLs because they call `toString` to print the expression results. 

We use `Duration` instances in our data structures related to devops tasks and it's not convenient that such data structures cannot be printed.

## Example

```
server.repl=> (def x (software.amazon.awscdk.core.Duration/seconds 29))
#'server.repl/x

server.repl=> {:some-duration x :some-other-data 123}
ExceptionInfo  #:clojure.error{:phase :print-eval-result}
	clojure.main/repl/read-eval-print--9112 (main.clj:442)
	clojure.main/repl/fn--9121 (main.clj:458)
	clojure.main/repl (main.clj:458)
	...
	clojure.lang.Var.invoke (Var.java:380)
	user/eval140 (form-init4088572569142024393.clj:1)
Caused by:
JsiiException Argument to Intrinsic must be a plain value object, got () => {
            throw new Error('Duration.toString() was used, but .toSeconds, .toMinutes or .toDays should have been called instead');
        }
Error: Argument to Intrinsic must be a plain value object, got () => {
            throw new Error('Duration.toString() was used, but .toSeconds, .toMinutes or .toDays should have been called instead');
        }
    at new Intrinsic (/private/var/folders/6g/9k9wc34n0hv_cn_1sq78xfdc0000gn/T/jsii-kernel-OqW88B/node_modules/@aws-cdk/core/lib/private/intrinsic.js:27:19)
    at Function.asAny (/private/var/folders/6g/9k9wc34n0hv_cn_1sq78xfdc0000gn/T/jsii-kernel-OqW88B/node_modules/@aws-cdk/core/lib/token.js:132:52)
    at Function.asString (/private/var/folders/6g/9k9wc34n0hv_cn_1sq78xfdc0000gn/T/jsii-kernel-OqW88B/node_modules/@aws-cdk/core/lib/token.js:101:69)
    at Duration.toString (/private/var/folders/6g/9k9wc34n0hv_cn_1sq78xfdc0000gn/T/jsii-kernel-OqW88B/node_modules/@aws-cdk/core/lib/duration.js:244:30)
    at /private/var/folders/6g/9k9wc34n0hv_cn_1sq78xfdc0000gn/T/jsii-java-runtime16685171498192926285/lib/program.js:8248:134
    at Kernel._wrapSandboxCode (/private/var/folders/6g/9k9wc34n0hv_cn_1sq78xfdc0000gn/T/jsii-java-runtime16685171498192926285/lib/program.js:8860:24)
    at /private/var/folders/6g/9k9wc34n0hv_cn_1sq78xfdc0000gn/T/jsii-java-runtime16685171498192926285/lib/program.js:8248:107
    at Kernel._ensureSync (/private/var/folders/6g/9k9wc34n0hv_cn_1sq78xfdc0000gn/T/jsii-java-runtime16685171498192926285/lib/program.js:8841:28)
    at Kernel.invoke (/private/var/folders/6g/9k9wc34n0hv_cn_1sq78xfdc0000gn/T/jsii-java-runtime16685171498192926285/lib/program.js:8248:34)
    at KernelHost.processRequest (/private/var/folders/6g/9k9wc34n0hv_cn_1sq78xfdc0000gn/T/jsii-java-runtime16685171498192926285/lib/program.js:9757:36)
	software.amazon.jsii.JsiiRuntime.processErrorResponse (JsiiRuntime.java:124)
	software.amazon.jsii.JsiiRuntime.requestResponse (JsiiRuntime.java:95)
	software.amazon.jsii.JsiiClient.callMethod (JsiiClient.java:184)
	software.amazon.jsii.Kernel.call (Kernel.java:52)
	software.amazon.awscdk.core.Duration.toString (Duration.java:295)
	clojure.core/str (core.clj:555)
	clojure.core/print-object (core_print.clj:117)
	clojure.core/fn--7299 (core_print.clj:120)
	clojure.core/fn--7299 (core_print.clj:120)
	clojure.lang.MultiFn.invoke (MultiFn.java:234)
	clojure.core/pr-on (core.clj:3662)
	clojure.core/pr (core.clj:3665)
```

In Java the same error would likely be caused by calling `System.out.println(x)` which can be reproduced in Clojure like this:

```clj
server.repl=> (.println System/out x)
JsiiException Argument to Intrinsic must be a plain value object, got () => {
            throw new Error('Duration.toString() was used, but .toSeconds, .toMinutes or .toDays should have been called instead');
        }
Error: Argument to Intrinsic must be a plain value object, got () => {
            throw new Error('Duration.toString() was used, but .toSeconds, .toMinutes or .toDays should have been called instead');
        }
    at new Intrinsic (/private/var/folders/6g/9k9wc34n0hv_cn_1sq78xfdc0000gn/T/jsii-kernel-OqW88B/node_modules/@aws-cdk/core/lib/private/intrinsic.js:27:19)
	...
```

## Proposed fix

I think the code should be fixed in CDK because `toString` docstring claims the string representation will be returned:

```java
    /**
     * Returns a string representation of this `Duration` that is also a Token that cannot be successfully resolved.
     * <p>
     * This
     * protects users against inadvertently stringifying a <code>Duration</code> object, when they should have called one of the
     * <code>to*</code> methods instead.
     */
    @software.amazon.jsii.Stability(software.amazon.jsii.Stability.Level.Stable)
    public @org.jetbrains.annotations.NotNull java.lang.String toString()
```

## Workaround

It is possible to override the printing of this type in Clojure, e.g.:

```clj
(defmethod clojure.core/print-method Duration
    [x ^java.io.Writer writer]
    (.write writer "Duration"))
```
