### ISSUE TITLE
Cannot add multiple aliases to KMS key

### ISSUE THREAD

**Issue by realharry** [aws/aws-cdk#3594]
**Note: for support questions, please first reference our [documentation](https://docs.aws.amazon.com/cdk/api/latest), then use [Stackoverflow](https://stackoverflow.com/questions/ask?tags=aws-cdk)**. This repository's issues are intended for feature requests and bug reports.

* **I'm submitting a ...**
  - [x] :beetle: bug report
  - [ ] :rocket: feature request
  - [ ] :books: construct library gap
  - [ ] :phone: security issue or vulnerability => Please see [policy](https://github.com/aws/aws-cdk/security/policy)
  - [ ] :question: support request => Please see note at the top of this template.

* **What is the current behavior?**
*If the current behavior is a :beetle:bug:beetle:: Please provide the steps to reproduce*

Try to call `addAlias()` multiple times on the same key. e.g.,
```JAVASCRIPT
key.addAlias('alias/foo');
key.addAlias('alias/bar');
```

It throws errors during `cdk synth`:

```BASH
Error: Error: There is already a Construct with name 'Alias' in Key [mainDbUserPassword]
    at ConstructNode.addChild (/Users/harry/Projects/devops/deploy/rbi0-kms/node_modules/@aws-cdk/core/lib/construct.ts:496:13)
    at new ConstructNode (/Users/harry/Projects/devops/deploy/rbi0-kms/node_modules/@aws-cdk/core/lib/construct.ts:143:18)
    at new Construct (/Users/harry/Projects/devops/deploy/rbi0-kms/node_modules/@aws-cdk/core/lib/construct.ts:547:17)
    at new Resource (/Users/harry/Projects/devops/deploy/rbi0-kms/node_modules/@aws-cdk/core/lib/resource.ts:61:5)
    at new AliasBase (/Users/harry/Projects/devops/deploy/rbi0-kms/node_modules/@aws-cdk/aws-kms/lib/alias.ts:46:1)
    at new Alias (/Users/harry/Projects/devops/deploy/rbi0-kms/node_modules/@aws-cdk/aws-kms/lib/alias.ts:82:5)
    at Key.addAlias (/Users/harry/Projects/devops/deploy/rbi0-kms/node_modules/@aws-cdk/aws-kms/lib/key.ts:71:12)
    at new Rbi0KmsStack (/Users/harry/Projects/devops/deploy/rbi0-kms/lib/rbi0-kms-stack.ts:26:12)
    at Object.<anonymous> (/Users/harry/Projects/devops/deploy/rbi0-kms/bin/rbi0-kms.ts:17:5)
    at Module._compile (internal/modules/cjs/loader.js:701:30)
```

* **What is the expected behavior (or behavior of feature suggested)?**

According to the doc, one should be able to create multiple aliases for a KMS key using CDK, https://docs.aws.amazon.com/cdk/api/latest/docs/aws-kms-readme.html

* **What is the motivation / use case for changing the behavior or adding this feature?**

One expects an API to work as documented.

* **Please tell us about your environment:**

  - CDK CLI Version: 1.3.0 (build bba9914)
  - Module Version: 1.3.0
  - OS: OSX Mojave
  - Language: TypeScript

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. associated pull-request, stackoverflow, gitter, etc)

None.

**Comment by nmussy** [comment]
Confirmed, I'm looking into it
