### ISSUE TITLE
2 APIs Using LambdaIntegration for the same Lambda function throws an error

### ISSUE THREAD

**Issue by eranation** [aws/aws-cdk#3609]
**Note: for support questions, please first reference our [documentation](https://docs.aws.amazon.com/cdk/api/latest), then use [Stackoverflow](https://stackoverflow.com/questions/ask?tags=aws-cdk)**. This repository's issues are intended for feature requests and bug reports.

* **I'm submitting a ...**
  - [x] :beetle: bug report
  - [ ] :rocket: feature request
  - [ ] :books: construct library gap
  - [ ] :phone: security issue or vulnerability => Please see [policy](https://github.com/aws/aws-cdk/security/policy)
  - [ ] :question: support request => Please see note at the top of this template.

* **What is the current behavior?**
*If the current behavior is a :beetle:bug:beetle:: Please provide the steps to reproduce*
  
  Getting "`Error: There is already a Construct with name 'ApiPermission.ANY..{proxy+}' in Function [APIFunction]`"

  **Steps to reproduce:**

  Create a simple CDK app with 2 RestApi constructs, 1 lambda.Function, and addMethod

  For example:

  ```typescript
  const apiFunction = new lambda.Function(this, "APIFunction", {
    runtime: Runtime.NODEJS_10_X,
    handler: "index.handler",
    code: lambda.Code.asset("path/to/code"),
  });

  const api1 = new apigateway.RestApi(this, "API1");
  api1.root.addProxy({defaultIntegration: new apigateway.LambdaIntegration(apiFunction )});

  const api2 = new apigateway.RestApi(this, "API2");
  api2.root.addProxy({defaultIntegration: new apigateway.LambdaIntegration(apiFunction 
  ``` 

* **What is the expected behavior (or behavior of feature suggested)?**

  It should not throw an error when doing cdk synth / diff / deploy 

* **Please tell us about your environment:**

  - CDK CLI Version: 1.3.0 (build bba9914)
  - Module Version: 1.3.0
  - OS: all
  - Language: TypeScript

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. associated pull-request, stackoverflow, gitter, etc)

  Error stack trace 
  ```
  Error: There is already a Construct with name 'ApiPermission.ANY..{proxy+}' in Function [APIFunction]
      at ConstructNode.addChild (.../aws-jam-console-typescript/cdk/node_modules/@aws-cdk/core/lib/construct.ts:496:13)
      at new ConstructNode (.../aws-jam-console-typescript/cdk/node_modules/@aws-cdk/core/lib/construct.ts:143:18)
      at new Construct (.../aws-jam-console-typescript/cdk/node_modules/@aws-cdk/core/lib/construct.ts:547:17)
      at new CfnElement (.../aws-jam-console-typescript/cdk/node_modules/@aws-cdk/core/lib/cfn-element.ts:54:5)
      at new CfnRefElement (.../aws-jam-console-typescript/cdk/node_modules/@aws-cdk/core/lib/cfn-element.ts:165:1)
      at new CfnResource (.../aws-jam-console-typescript/cdk/node_modules/@aws-cdk/core/lib/cfn-resource.ts:82:5)
      at new CfnPermission (.../aws-jam-console-typescript/cdk/node_modules/@aws-cdk/aws-lambda/lib/lambda.generated.ts:1510:9)
      at Function.addPermission (.../aws-jam-console-typescript/cdk/node_modules/@aws-cdk/aws-lambda/lib/function-base.ts:181:5)
      at LambdaIntegration.bind (.../aws-jam-console-typescript/cdk/node_modules/@aws-cdk/aws-apigateway/lib/integrations/lambda.ts:60:18)
      at Method.renderIntegration (.../aws-jam-console-typescript/cdk/node_modules/@aws-cdk/aws-apigateway/lib/method.ts:189:17)

  ```

  Could be related to this hardcoded construct id: https://github.com/aws/aws-cdk/blob/862ed7bb5ba350bb5d1c86d929298d27bdad17e8/packages/%40aws-cdk/aws-apigateway/lib/integrations/lambda.ts#L60

**Comment by hoegertn** [comment]
My PR #3532 is fixing this issue
