### ISSUE TITLE
Python CodePipeline Artifact JSII Error

### ISSUE THREAD

**Issue by josjaf** [aws/aws-cdk#3675]
* **I'm submitting a bug report

* **What is the current behavior?**
*If the current behavior is a :beetle:bug:beetle:: Please provide the steps to reproduce*

Codepipeline Artifact object throwing an error - jsii.errors.JSIIError: Expected object reference, got "${Token[TOKEN.17]}"

* **Please tell us about your environment:**

  - CDK CLI Version: 1.4
  - Module Version: xx.xx.xx
  - OS: [all | Windows 10 | OSX Mojave | Ubuntu | etc... ] OSX Mojave
  - Language: [all | TypeScript | Java | Python ] Python
* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. associated pull-request, stackoverflow, gitter, etc)

Traceback
```
Traceback (most recent call last):
  File "app.py", line 19, in <module>
    base = Pipeline(app, "aaaa-repokid-pipeline", shared_params=shared_parameters, shared_outputs=shared_outputs)
  File "/Users/mrtest/.pyenv/versions/3.6.6/envs/aaaa/lib/python3.6/site-packages/jsii/_runtime.py", line 66, in __call__
    inst = super().__call__(*args, **kwargs)
  File "/Users/mrtest/workspace/aaaa/repo_kid/cdk/Pipeline.py", line 39, in __init__
    output=source_output,
  File "/Users/mrtest/.pyenv/versions/3.6.6/envs/aaaa/lib/python3.6/site-packages/jsii/_runtime.py", line 66, in __call__
    inst = super().__call__(*args, **kwargs)
  File "/Users/mrtest/.pyenv/versions/3.6.6/envs/aaaa/lib/python3.6/site-packages/aws_cdk/aws_codepipeline_actions/__init__.py", line 2801, in __init__
    jsii.create(S3SourceAction, self, [props])
  File "/Users/mrtest/.pyenv/versions/3.6.6/envs/aaaa/lib/python3.6/site-packages/jsii/_kernel/__init__.py", line 208, in create
    overrides=overrides,
  File "/Users/mrtest/.pyenv/versions/3.6.6/envs/aaaa/lib/python3.6/site-packages/jsii/_kernel/providers/process.py", line 331, in create
    return self._process.send(request, CreateResponse)
  File "/Users/mrtest/.pyenv/versions/3.6.6/envs/aaaa/lib/python3.6/site-packages/jsii/_kernel/providers/process.py", line 316, in send
    raise JSIIError(resp.error) from JavaScriptError(resp.stack)
jsii.errors.JSIIError: Expected object reference, got "${Token[TOKEN.17]}"

```
Code
```
from aws_cdk import (

    aws_iam as aws_iam,
    aws_s3 as aws_s3,
    aws_ecr,
    aws_codebuild,
    aws_codepipeline,
    aws_codepipeline_actions,
    aws_s3,
    core,

)


class Pipeline(core.Stack):
    def __init__(self, app: core.App, id: str, shared_params: dict, shared_outputs: dict) -> None:
        super().__init__(app, id)

        source_output = aws_codepipeline.Artifact(artifact_name='source')
        #source_output = aws_codepipeline.Artifact()
        print(shared_outputs['bucket_obj'].bucket_arn)
        pipeline = aws_codepipeline.Pipeline(
            self,
            "Pipeline",

            pipeline_name='test',
            role=shared_outputs['codepipeline_role_obj'],
            stages=[
                aws_codepipeline.StageProps(

                    stage_name='Source',
                    actions=[aws_codepipeline_actions.S3SourceAction(

                        bucket=shared_outputs['bucket_obj'].bucket_arn,
                        bucket_key='source.zip',
                        action_name='S3Source',
                        run_order=1,
                        output=source_output,

                    )
                    ]
                ),
                aws_codepipeline.StageProps(

                    stage_name='Build',
                    actions=[aws_codepipeline_actions.CodeBuildAction(
                        action_name='DockerBuildImages',
                        role=shared_outputs['codebuild_role_docker_build'],
                        input=source_output,
                        project=shared_outputs['codebuild_project_docker_build'],
                        run_order=1

                    )
                    ]
                )
            ]
        )

```

**Comment by josjaf** [comment]
I think I got past this
