### ISSUE TITLE
cli: synth fails if cdk.out does not exist

### ISSUE THREAD

**Issue by rgd11** [aws/aws-cdk#3717]
### What is the problem?

`cdk synth` returns `ENOENT: no such file or directory, open 'cdk.out/manifest.json'` when the cdk.out directory is not present. 

However, this results in the creation of a default manifest.json, and subsequent calls to synth succeed

### Reproduction Steps

from cdk project directory:
1. mvn clean
2. rm -rf cdk.out
3. mvn compile
4. cdk synth

### Verbose Log

```
xxxxxxxxx:cdk xxxxxxxx$ ls
cdk.json        cdk.out         pom.xml         src             target
xxxxxxxxx:cdk xxxxxxxx$ mvn clean
[INFO] Scanning for projects...
[INFO] 
[INFO] -------------------< com.xxx.xxx:project >--------------------
[INFO] Building project 0.1
[INFO] --------------------------------[ jar ]---------------------------------
[INFO] 
[INFO] --- maven-clean-plugin:2.5:clean (default-clean) @ project ---
[INFO] Deleting /Users/xxxxxxxx/workspace/xxxxxxxx/cdk/target
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 0.303 s
[INFO] Finished at: 2019-08-19T16:27:07-07:00
[INFO] ------------------------------------------------------------------------
xxxxxxxxx:cdk xxxxxxxx$ rm -rf cdk.out
xxxxxxxxx:cdk xxxxxxxx$ mvn compile
[INFO] Scanning for projects...
[INFO] 
[INFO] -------------------< com.xxx.xxx:project >--------------------
[INFO] Building project 0.1
[INFO] --------------------------------[ jar ]---------------------------------
[INFO] 
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ project ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory /Users/xxxxxxxx/workspace/xxxxxxxx/cdk/src/main/resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.7.0:compile (default-compile) @ project ---
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 3 source files to /Users/xxxxxxxx/workspace/xxxxxxxx/cdk/target/classes
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 1.835 s
[INFO] Finished at: 2019-08-19T16:27:24-07:00
[INFO] ------------------------------------------------------------------------
xxxxxxxxx:cdk xxxxxxxx$ cdk synth
[INFO] Scanning for projects...
[INFO] 
[INFO] -------------------< com.xxx.xxx:project >--------------------
[INFO] Building project 0.1
[INFO] --------------------------------[ jar ]---------------------------------
[INFO] 
[INFO] --- exec-maven-plugin:1.6.0:java (default-cli) @ project ---
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 1.574 s
[INFO] Finished at: 2019-08-19T16:27:31-07:00
[INFO] ------------------------------------------------------------------------
ENOENT: no such file or directory, open 'cdk.out/manifest.json'
```
### Environment

  - **CDK CLI Version:** 1.4.0 (build 175471f)
  - **Module Version:** 
  - **OS:** OSX Mojave
  - **Language:** Java

**Comment by nija-at** [comment]
Unable to reproduce. 

I ran the following commands on my Mac (OSX Mojave) running cdk version 1.4.0

```shell
$ cdk init app --language=java
...

$mvn compile
...

$ mvn clean && rm -rf cdk.out

$ mvn compile
...

$ cdk synth
Successfully synthesized to /Users/nija/workplace/cdk/hello-cdk-java/cdk.out
Supply a stack name (hello-cdk-1, hello-cdk-2) to display its template.
```

I can also confirm that `cdk.out/` contains the synthesized templates in JSON.

**Comment by nija-at** [comment]
Thanks to @ivoanjo who also had this problem, I'm able to reproduce this in Java.

I was able to reproduce this using our standard sample-app package from `cdk init -l=java` and modify the code to drop `app.synth()`. Running `cdk synth` on this when there's no `cdk.out/` folder gets this error.

There seems to be some race condition between the `cdk.out/` folder being generated and when the CLI expects it to be present for parsing. This specifically happens when the app does not call `app.synth()`.

**Comment by saltman424** [comment]
I am having the same problem. However, the cause of the problem seems to differ in that in my case, it occurs whenever I specify an outdir other than cdk.out, whether or not I call app.synth().

I created a separate issue for this  (#5815), since I think the cause is different. But the relevant details from that issue are copied below.

If I synthesize without a modified outdir (producing a cdk.out/mainfest.json), and then synthesize with a modified outdir, it successfully outputs the expected files to the modified outdir. So it seems that at some point during the process it needs to read from cdk.out/manifest.json, whether or not the outdir property is set to cdk.out, and then it proceeds to behave as expected.

It also appears that a cdk.out folder is created when running cdk synth with a modified outdir.

Additionally, it seems that in at least one project where I am having this issue, running 'cdk deploy' deploys the templates in cdk.out, not the specified outdir. So it seems like currently the outdir is just not really useful.

Is it possible that 'cdk.out' is hard-coded somewhere?

**Comment by thekevinbrown** [comment]
I'm having this issue in a Lerna monorepo with Typescript:

```
$ cdk synth --verbose
CDK toolkit version: 1.22.0 (build 309ac1b)
Command line arguments: { _: [ 'synth' ],
  verbose: true,
  v: true,
  'ignore-errors': false,
  ignoreErrors: false,
  json: false,
  j: false,
  ec2creds: undefined,
  i: undefined,
  'version-reporting': undefined,
  versionReporting: undefined,
  'path-metadata': true,
  pathMetadata: true,
  'asset-metadata': true,
  assetMetadata: true,
  'role-arn': undefined,
  r: undefined,
  roleArn: undefined,
  staging: true,
  'no-color': false,
  noColor: false,
  fail: false,
  '$0':
   '[project folder]/node_modules/.bin/cdk' }
Determining whether we're on an EC2 instance.
Does not look like EC2 instance.
cdk.json: {
  "app": "ts-node src/index.ts"
}
merged settings: { versionReporting: true,
  pathMetadata: true,
  output: 'cdk.out',
  app: 'ts-node src/index.ts',
  context: {},
  tags: [],
  assetMetadata: true,
  toolkitBucket: {},
  staging: true }
Setting "CDK_DEFAULT_REGION" environment variable to ap-southeast2
Resolving default credentials
Retrieved account ID [my account ID] from disk cache
Setting "CDK_DEFAULT_ACCOUNT" environment variable to [my account ID]
context: { 'aws:cdk:enable-path-metadata': true,
  'aws:cdk:enable-asset-metadata': true }
outdir: cdk.out
env: { CDK_DEFAULT_REGION: 'ap-southeast2',
  CDK_DEFAULT_ACCOUNT: '[my account ID]',
  CDK_CONTEXT_JSON:
   '{"aws:cdk:enable-path-metadata":true,"aws:cdk:enable-asset-metadata":true}',
  CDK_OUTDIR: 'cdk.out',
  CDK_CLI_ASM_VERSION: '1.21.0',
  CDK_CLI_VERSION: '1.22.0' }
ENOENT: no such file or directory, open 'cdk.out/manifest.json'
Error: ENOENT: no such file or directory, open 'cdk.out/manifest.json'
    at Object.openSync (fs.js:443:3)
    at Object.readFileSync (fs.js:343:35)
    at new CloudAssembly ([project directory]/node_modules/@aws-cdk/cx-api/lib/cloud-assembly.ts:77:36)
    at Object.execProgram ([project directory]/node_modules/aws-cdk/lib/api/cxapp/exec.ts:85:10)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

If I create the file myself then it complains that it can't parse the version out of it, etc. I'm not sure why, and when I run the default `app --language=typescript` starter, `synth` runs fine, so it's definitely something about my specific code, but I'm not sure what yet.

**Comment by thekevinbrown** [comment]
For me the issue was that I had missed the difference between the file in `bin` and the file in `lib`, so I was missing:

```typescript
const app = new cdk.App();
new MyStack(app, 'MyStack');
```

As soon as I added that back in I stopped getting the error about the missing file. It'd be great if we could improve the error message in this case.

**Comment by joekiller** [comment]
This may help some people on MacOS. I was having a hard time occasionally with this and it turned out that my script set TMPDIR at some point and then deleted that directory. Later on nodejs picked that up and tries to extract stuff to TMPDIR and we end up with ` Error: ENOENT: no such file or directory, mkdtemp` errors.

**Comment by flashflexpro** [comment]
this is such a great idea but rather disappointing implementation:
I'm using 1.57, both Java and TS, completely following the cdk init command, hardly adding few lines of code:

Java project blocked:
`
ENOENT: no such file or directory, open 'cdk.out\manifest.json'
Error: ENOENT: no such file or directory, open 'cdk.out\manifest.json'
    at Object.openSync (fs.js:458:3)
    at Object.readFileSync (fs.js:360:35)
    at Function.loadManifest (C:\Users\annmsmn\.npm\node-v12.16.3-win-x64\node_modules\aws-cdk\node_modules\@aws-cdk\cloud-assembly-schema\lib\manifest.ts:128:29)
    at Function.loadAssemblyManifest (C:\Users\annmsmn\.npm\node-v12.16.3-win-x64\node_modules\aws-cdk\node_modules\@aws-cdk\cloud-assembly-schema\lib\manifest.ts:44:21)
    at Function.load (C:\Users\annmsmn\.npm\node-v12.16.3-win-x64\node_modules\aws-cdk\node_modules\@aws-cdk\cloud-assembly-schema\lib\manifest.ts:83:81)
    at new CloudAssembly (C:\Users\annmsmn\.npm\node-v12.16.3-win-x64\node_modules\aws-cdk\node_modules\@aws-cdk\cx-api\lib\cloud-assembly.ts:52:39)
    at createAssembly (C:\Users\annmsmn\.npm\node-v12.16.3-win-x64\node_modules\aws-cdk\lib\api\cxapp\exec.ts:79:14)
    at Object.execProgram (C:\Users\annmsmn\.npm\node-v12.16.3-win-x64\node_modules\aws-cdk\lib\api\cxapp\exec.ts:75:10)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at CloudExecutable.doSynthesize (C:\Users\annmsmn\.npm\node-v12.16.3-win-x64\node_modules\aws-cdk\lib\api\cxapp\cloud-executable.ts:66:24)`



then blocked completely by:

`
unable to determine cloud assembly output directory. Assets must be defined indirectly within a "Stage" or an "App" scope
Subprocess exited with error 1
Error: Subprocess exited with error 1
    at ChildProcess.<anonymous> (/home/ubuntu/.nvm/versions/node/v12.18.3/lib/node_modules/aws-cdk/lib/api/cxapp/exec.ts:118:23)
    at ChildProcess.emit (events.js:315:20)
    at ChildProcess.EventEmitter.emit (domain.js:483:12)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12)
`

when use 

        const lambdaSrc = new lambda.AssetCode("lambda/src");

**Comment by flashflexpro** [comment]
Also there is bug generating excessive file name after adding one line of code:

`
        // The code that defines your stack goes here

/*
        new Function( this, "lambda", FunctionProps.builder()
                .functionName( "tmp-tst135" )
                .runtime( Runtime.NODEJS_12_X )
                .code( Code.fromAsset( "", ))
                .environment( Map.of( "aaa", "kkk" ))
                .handler( "abc-handler" )
                .build() );*/
`

`
Exception in thread "main" software.amazon.jsii.JsiiException: ENAMETOOLONG: name too long, mkdir 'cdk.out\asset.42fc811dc4603f26682bbbd201e828a9dbc87016180ebacd900cd8519f1d7c5c\cdk.out\asset.42fc811dc4603f26682bbbd201e828a9dbc87016180ebacd900cd8519f1d7c5`

**Comment by wulfmann** [comment]
That's not really a bug. That happens whenever you use a `.fromAsset` lambda code.

**Comment by wysird** [comment]
I was getting the same error.
* OpenJDK 14
* macOS Catalina 10.15.7
* cdk 1.102.0 (build a75d52f)
* node v14.5.0
* npm 6.14.5

Code:
```
import software.amazon.awscdk.core.App;
...
public static void main(final String... args) {
    App app = new App();
    new MyStack(...);
}
```

```
$ rm -r cdk.out
$ mvn clean compile
...
$ cdk synth
ENOENT: no such file or directory, open 'cdk.out/manifest.json'
```

<hr />

However, after adding `app.synth();` to the end of my main method:

```
import software.amazon.awscdk.core.App;

...

public static void main(final String... args) {
    App app = new App();
    new MyStack(...);

    app.synth();     // NEW LINE
}
```

I then got the expected output when running `cdk synth`:
```
$ rm -r cdk.out
$ mvn clean compile
...
$ cdk synth
Resources:
...
```


So check that you have `app.synth()` after your resource definitions. I'm not sure why this worked for me, I haven't done a deeper dive than this (because it now works for me) but wanted to share.

Hope this is helpful in some way.

**Comment by shellscape** [comment]
@shivlaks @SomayaB it looks like ya'll closed #5815 to track the issue here, but it doesn't look like it's actually being tracked. this has been a persistent issue for a year and a half now. would be really cool if one of the maintainers there at AWS could give this a look. `outdir` (or `--output`) is crucial for parallel deployments, but it's unusable due to this bug.

**Comment by shellscape** [comment]
This is the offending line https://github.com/aws/aws-cdk/blob/5a6fa7fa17a5dce5e429eed4ebfe2dbbac3d6d07/packages/%40aws-cdk/cx-api/lib/cloud-assembly.ts#L52

I've added logging there and can confirm that it's called twice; once with the correct custom `outdir` I'm providing, and once with the incorrect `cdk.out`:

```
AWS: CloudAssembly.directory: /Users/<me>/backend/cdk.out/cron-refresh-views/1632494932295 
AWS: CloudAssembly.directory: cdk.out 
```

I'll continue to trace this and will follow up.

**Comment by shellscape** [comment]
Here's the offending block in the `aws-cdk` pacakge: https://github.com/aws/aws-cdk/blob/5a6fa7fa17a5dce5e429eed4ebfe2dbbac3d6d07/packages/aws-cdk/lib/api/cxapp/exec.ts#L68-L92

The code looks for `output` on the command line and disregards the `AppProps.outdir` passed in code. That means in order to resolve this, you have to set _both_ `outdir` in the `AppProps` during instantiation of the `App`, **as well as** use `--outdir` set to the same exact value. This is very redundant, and makes using dynamic output directories a massive pain. Not remotely ideal.

@rix0rrr  @shivlaks @SomayaB There's the triage. Can we get a fix or some documentation around this?

**Comment by rix0rrr** [comment]
I don't think setting `AppProps.outdir` *can* even work, as the CLI won't know where to look for the Cloud Assembly.

Now that you mention it, I'm not sure why we have that property in the first place. I guess it is for unit tests.

@eladb you added this property in https://github.com/aws/aws-cdk/pull/2636... do you happen to remember why it is configurable from inside the CDK app?
