### ISSUE TITLE
KMS: addAlias 1.4 - Is not able to use Account ID

### ISSUE THREAD

**Issue by notes-jj** [aws/aws-cdk#3729]
### What is the problem?

KMS: addAlias in CDK 1.4 is not able to use `this.account` as part of the alias name. Error `Cannot use tokens in construct ID: ${id}`. This was possible in CDK 1.0.

### Reproduction Steps

Call cdk synth on following code block (Part of typical CDK App)

Code:
```
import { Key } from '@aws-cdk/aws-kms';
[...]
const kmsKey = new Key(this,
    'S3 Cross Account', {
        description: 'S3 Cross Account',
        enableKeyRotation: true,
        removalPolicy: RemovalPolicy.RETAIN
    });
    
const alias = kmsKey.addAlias('alias/' + this.account + '-s3-cross-account')
```

### Verbose Log
```
SOMEPATH>cdk synth

SOMEPATH\node_modules\@aws-cdk\core\lib\construct.ts:151
      throw new Error(`Cannot use tokens in construct ID: ${id}`);
            ^
Error: Cannot use tokens in construct ID: Aliasalias/${Token[AWS::AccountId.0]}-s3-cross-account
    at new ConstructNode (SOMEPATH\node_modules\@aws-cdk\core\lib\construct.ts:151:13)
    at new Construct (SOMEPATH\node_modules\@aws-cdk\core\lib\construct.ts:563:17)
    at new Resource (SOMEPATH\node_modules\@aws-cdk\core\lib\resource.ts:61:5)
    at new AliasBase (SOMEPATH\node_modules\@aws-cdk\aws-kms\lib\alias.ts:46:1)
    at new Alias (SOMEPATH\node_modules\@aws-cdk\aws-kms\lib\alias.ts:82:5)
    at Key.addAlias (SOMEPATH\node_modules\@aws-cdk\aws-kms\lib\key.ts:71:12)
    at new EmgDom120Kms (SOMEPATH\lib\emg--dom--120-kms.ts:49:30)
    at Object.<anonymous> (SOMEPATH\bin\emg--dom--cdk.ts:49:1)
    at Module._compile (internal/modules/cjs/loader.js:868:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:879:10)
    at new ConstructNode (SOMEPATH\node_modules\@aws-cdk\core\lib\construct.ts:151:13)
    at new Construct (SOMEPATH\node_modules\@aws-cdk\core\lib\construct.ts:563:17)
    at new Resource (SOMEPATH\node_modulesnstruct.ts:151\@aws-cdk\core\lib\resource.ts:61:5)
    at new AliasBase (SOMEPATH\node_modules\@aws-cdk\aws-kms\lib\alias.ts:46:1)                                         }-s3-cross-account
    at new Alias (SOMEPATH\node_modules\@adules\@aws-cdk\core\lib\construct.ts:151:13)ws-cdk\aws-kms\lib\alias.ts:82:5)                                             s\@aws-cdk\core\lib\construct.ts:563:17)
    at Key.addAlias (SOMEPATH\node_modules\@aws-cdk\core\lib\resource.ts:61:5)\@aws-cdk\aws-kms\lib\key.ts:71:12)                                           s\@aws-cdk\aws-kms\lib\alias.ts:46:1)
    at new EmgDom120Kms (SOMEPATH\lib\emg-ws-cdk\aws-kms\lib\alias.ts:82:5)-dom--120-kms.ts:49:30)                                                       \@aws-cdk\aws-kms\lib\key.ts:71:12)
    at Object.<anonymous> (SOMEPATH\bin\em-dom--120-kms.ts:49:30)g--dom--cdk.ts:49:1)                                                          g--dom--cdk.ts:49:1)
    at Module._compile (internal/modules/cjs/loader.js:868:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:879:10)  
Subprocess exited with error 1
```

### Environment

  - **CDK CLI Version:** 1.4.0
  - **Module Version:** @aws-cdk/aws-kms 1.4.0
  - **OS:** Windows 10
  - **Language:** TypeScript

### Other information 

Workaround:

The workaround is only working correct, if deployment account and target account are the same.
The CFN variable name ist changed due to the changed String.
```
const account = process.env.CDK_DEFAULT_ACCOUNT || ""
const alias = kmsKey.addAlias('alias/' + account + '-s3-cross-account')
```

**Comment by notes-jj** [comment]
Issue is solved in CDK 1.5. :relaxed:
