### ISSUE TITLE
Using AWS CDK in pytest unit tests receives jsii.errors.JSIIError: Maximum call stack size exceeded

### ISSUE THREAD

**Issue by bverhoeve** [aws/aws-cdk#3759]
AWS Support case ID: 6378067991

### What is the problem?
I am working on a `pytest` test suite for a Python application that creates complex networks using AWS CDK. Most of the tests involve creating a small CDK app, adding some objects and matching the generated CloudFormation code using `app.synth()` with mock CloudFormation code, defined upfront.

Currently, some of our tests are failing when the full test suite is run. The tests do not fail when executed in isolation, or when only the module is executed, only when the full test suite is executed.

When using the Python debugger and `pytest`, I've located where the error occurs. It is in the following code: https://github.com/aws/jsii/blob/master/packages/jsii-python-runtime/src/jsii/_kernel/__init__.py#L71 in `jsii` in lines 71 to lines 83. The program has entered this loop due to a call to `node.apply_aspect(Tag(key, value))` which should apply tags to the `Construct` being constructed.

### Reproduction Steps
Currently, I don't have any easy reproduction steps without sharing confidential code.

### Verbose Log
```
jsii.errors.JavaScriptError:
  RangeError: Maximum call stack size exceeded
      at KernelHost.processRequest (/venv/lib/python3.7/site-packages/jsii/_embedded/jsii/jsii-runtime.js:6230:18)
      at KernelHost.run (/venv/lib/python3.7/site-packages/jsii/_embedded/jsii/jsii-runtime.js:6137:14)
      at /venv/lib/python3.7/site-packages/jsii/_embedded/jsii/jsii-runtime.js:6137:45
      at KernelHost.processRequest (/venv/lib/python3.7/site-packages/jsii/_embedded/jsii/jsii-runtime.js:6233:16)
      at KernelHost.run (/venv/lib/python3.7/site-packages/jsii/_embedded/jsii/jsii-runtime.js:6137:14)
      at /venv/lib/python3.7/site-packages/jsii/_embedded/jsii/jsii-runtime.js:6137:45
      at KernelHost.processRequest (/venv/lib/python3.7/site-packages/jsii/_embedded/jsii/jsii-runtime.js:6233:16)
      at KernelHost.run (/venv/lib/python3.7/site-packages/jsii/_embedded/jsii/jsii-runtime.js:6137:14)
      at /venv/lib/python3.7/site-packages/jsii/_embedded/jsii/jsii-runtime.js:6137:45
      at KernelHost.processRequest (/venv/lib/python3.7/site-packages/jsii/_embedded/jsii/jsii-runtime.js:6233:16)

self = <jsii._kernel.providers.process._NodeProcess object at 0x10d913710>
request = GetRequest(objref=CreateResponse(ref='@aws-cdk/core.Construct@11247'), property='node'), response_type = <class 'jsii._kernel.types.GetResponse'>

    def send(
        self, request: KernelRequest, response_type: Type[KernelResponse]
    ) -> KernelResponse:
        req_dict = self._serializer.unstructure(request)
        data = json.dumps(req_dict, default=jdefault).encode("utf8")

        # Send our data, ensure that it is framed with a trailing \n
        self._process.stdin.write(b"%b\n" % (data,))
        self._process.stdin.flush()

        resp: _ProcessResponse = self._serializer.structure(
            self._next_message(), _ProcessResponse_R
        )

        if isinstance(resp, _OkayResponse):
            return self._serializer.structure(resp.ok, response_type)
        elif isinstance(resp, _CallbackResponse):
            return resp.callback
        else:
>           raise JSIIError(resp.error) from JavaScriptError(resp.stack)
E           jsii.errors.JSIIError: Maximum call stack size exceeded

../../../venv/lib/python3.7/site-packages/jsii/_kernel/providers/process.py:316: JSIIError
```

### Environment

  - **CDK CLI Version:** 1.2.0 (the issue also occurs in the latest build 1.5.0)
  - **Module Version:** `jsii` 0.14.2`
  - **OS:** OSX Mojave
  - **Language:** Python

### Other information 
I have a feeling it has something to do with the JSII kernel being overloaded due to all the calls that occur when testing. Most tests will create a new `App`, `Stack` and multiple other `Constructs` when executing.

**Comment by bverhoeve** [comment]
I've worked a bit on how to reproduce the error and decided to see if the multitude of calls to create new `Constructs` was giving me the error. The following:
```
from aws_cdk.core import App, Stack
from aws_cdk.aws_s3 import Bucket

import os


for i in range(20):
  print('creating app')
  app = App(
    auto_synth = True,
    outdir = './tmp'
  )

  print(app)

  print('creating stack')
  stack = Stack(app, name='mystack')
  print(stack)
  print('creating buckets')

  for i in range(100):

    bucket = Bucket(scope=stack, id='mybucket' + str(i))
    for i in range(100):
      bucket2 = Bucket(scope=bucket, id='mysecondbucket'+str(i))
      print(bucket2)
    print(bucket)

  print('synth')

  app.synth()
```
Does not recreate the error, but does let the JavaScript heap run out of memory

**Comment by bverhoeve** [comment]
Okay, new effort. The following script: 
```
from aws_cdk.core import App, Stack, Tag
from aws_cdk.aws_s3 import Bucket


def scope_recursion(scope, call):
  print('current scope: ' + str(scope))
  print('current call ' + str(call))
  bucket = Bucket(scope, 'mybucket')
  call += 1
  
  
  if not call > 750:
    scope_recursion(bucket, call)
  bucket.node.apply_aspect(Tag('my', 'tag'))


app = App()
stack = Stack(app, 'mystack')
call = 0
scope_recursion(stack, call)
```

Gives the same error:
```
jsii.errors.JavaScriptError:
  RangeError: Maximum call stack size exceeded
      at KernelHost.processRequest (/Users/bverhoeve/Development/cdk-crash/venv/lib/python3.7/site-packages/jsii/_embedded/jsii/jsii-runtime.js:6230:18)
      at KernelHost.run (/Users/bverhoeve/Development/cdk-crash/venv/lib/python3.7/site-packages/jsii/_embedded/jsii/jsii-runtime.js:6137:14)
      at /Users/bverhoeve/Development/cdk-crash/venv/lib/python3.7/site-packages/jsii/_embedded/jsii/jsii-runtime.js:6137:45
      at KernelHost.processRequest (/Users/bverhoeve/Development/cdk-crash/venv/lib/python3.7/site-packages/jsii/_embedded/jsii/jsii-runtime.js:6233:16)
      at KernelHost.run (/Users/bverhoeve/Development/cdk-crash/venv/lib/python3.7/site-packages/jsii/_embedded/jsii/jsii-runtime.js:6137:14)
      at /Users/bverhoeve/Development/cdk-crash/venv/lib/python3.7/site-packages/jsii/_embedded/jsii/jsii-runtime.js:6137:45
      at KernelHost.processRequest (/Users/bverhoeve/Development/cdk-crash/venv/lib/python3.7/site-packages/jsii/_embedded/jsii/jsii-runtime.js:6233:16)
      at KernelHost.run (/Users/bverhoeve/Development/cdk-crash/venv/lib/python3.7/site-packages/jsii/_embedded/jsii/jsii-runtime.js:6137:14)
      at /Users/bverhoeve/Development/cdk-crash/venv/lib/python3.7/site-packages/jsii/_embedded/jsii/jsii-runtime.js:6137:45
      at KernelHost.processRequest (/Users/bverhoeve/Development/cdk-crash/venv/lib/python3.7/site-packages/jsii/_embedded/jsii/jsii-runtime.js:6233:16)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "scope_recursion.py", line 20, in <module>
    scope_recursion(stack, call)
  File "scope_recursion.py", line 13, in scope_recursion
    scope_recursion(bucket, call)
  File "scope_recursion.py", line 13, in scope_recursion
    scope_recursion(bucket, call)
  File "scope_recursion.py", line 13, in scope_recursion
    scope_recursion(bucket, call)
  [Previous line repeated 113 more times]
  File "scope_recursion.py", line 14, in scope_recursion
    bucket.node.apply_aspect(Tag('my', 'tag'))
  File "/Users/bverhoeve/Development/cdk-crash/venv/lib/python3.7/site-packages/aws_cdk/core/__init__.py", line 1332, in apply_aspect
    return jsii.invoke(self, "applyAspect", [aspect])
  File "/Users/bverhoeve/Development/cdk-crash/venv/lib/python3.7/site-packages/jsii/_kernel/__init__.py", line 104, in wrapped
    return _recursize_dereference(kernel, fn(kernel, *args, **kwargs))
  File "/Users/bverhoeve/Development/cdk-crash/venv/lib/python3.7/site-packages/jsii/_kernel/__init__.py", line 267, in invoke
    args=_make_reference_for_native(self, args),
  File "/Users/bverhoeve/Development/cdk-crash/venv/lib/python3.7/site-packages/jsii/_kernel/providers/process.py", line 346, in invoke
    return self._process.send(request, InvokeResponse)
  File "/Users/bverhoeve/Development/cdk-crash/venv/lib/python3.7/site-packages/jsii/_kernel/providers/process.py", line 316, in send
    raise JSIIError(resp.error) from JavaScriptError(resp.stack)
jsii.errors.JSIIError: Maximum call stack size exceeded
```

When removing the line that adds the tags, the program runs just fine. I think the call to apply the tags is going into a recursive process that is continuing too long.

**Comment by rix0rrr** [comment]
Thanks for filing and narrowing it down! This is definitely going to help us to fix the issue

**Comment by roystchiang** [comment]
FWIW, I can replicate the issue in NodeJS

It can be replicated with

```
function getStack() {
    var app = new cdk.App();
    var stack = new Stack(app, 'mystack');
    var bucket = new Bucket(stack, `mybucket`);

    console.log(app.synth().getStack('mystack').template)
}

var i;
for (i = 0; i < 1000; i++) {
    getStack();
}
```

```
<--- JS stacktrace --->

==== JS stack trace =========================================

Security context: 0x3f0b6021e6e9 <JSObject>
    0: builtin exit frame: captureStackTrace(this=0x3f0b60209719 <JSFunction Error (sfi = 0x3f0b3ea96e01)>,0x3f0b87e5e429 <JSFunction captureStackTrace (sfi = 0x3f0b527ff861)>,0x3f0b73329ee9 <Object map = 0x3f0b033e6f91>,0x3f0b60209719 <JSFunction Error (sfi = 0x3f0b3ea96e01)>)

    1: captureStackTrace [0x3f0b87e5e429] [/Users/roychi/projects/CdkLambda/node_modules/@aws-cdk/core/lib/stack-trace...

FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory
 1: 0x10003cf99 node::Abort() [/usr/local/bin/node]
 2: 0x10003d1a3 node::OnFatalError(char const*, char const*) [/usr/local/bin/node]
 3: 0x1001b7835 v8::internal::V8::FatalProcessOutOfMemory(v8::internal::Isolate*, char const*, bool) [/usr/local/bin/node]
 4: 0x100585682 v8::internal::Heap::FatalProcessOutOfMemory(char const*) [/usr/local/bin/node]
 5: 0x100588155 v8::internal::Heap::CheckIneffectiveMarkCompact(unsigned long, double) [/usr/local/bin/node]
 6: 0x100583fff v8::internal::Heap::PerformGarbageCollection(v8::internal::GarbageCollector, v8::GCCallbackFlags) [/usr/local/bin/node]
 7: 0x1005821d4 v8::internal::Heap::CollectGarbage(v8::internal::AllocationSpace, v8::internal::GarbageCollectionReason, v8::GCCallbackFlags) [/usr/local/bin/node]
 8: 0x10058ea6c v8::internal::Heap::AllocateRawWithLigthRetry(int, v8::internal::AllocationSpace, v8::internal::AllocationAlignment) [/usr/local/bin/node]
 9: 0x10058eaef v8::internal::Heap::AllocateRawWithRetryOrFail(int, v8::internal::AllocationSpace, v8::internal::AllocationAlignment) [/usr/local/bin/node]
10: 0x10055de86 v8::internal::Factory::NewFixedArrayWithFiller(v8::internal::Heap::RootListIndex, int, v8::internal::Object*, v8::internal::PretenureFlag) [/usr/local/bin/node]
11: 0x10055f96e v8::internal::Factory::NewFrameArray(int, v8::internal::PretenureFlag) [/usr/local/bin/node]
12: 0x1006436a8 v8::internal::Isolate::CaptureSimpleStackTrace(v8::internal::Handle<v8::internal::JSReceiver>, v8::internal::FrameSkipMode, v8::internal::Handle<v8::internal::Object>) [/usr/local/bin/node]
13: 0x100644016 v8::internal::Isolate::CaptureAndSetSimpleStackTrace(v8::internal::Handle<v8::internal::JSReceiver>, v8::internal::FrameSkipMode, v8::internal::Handle<v8::internal::Object>) [/usr/local/bin/node]
14: 0x10026bdf7 v8::internal::Builtin_Impl_ErrorCaptureStackTrace(v8::internal::BuiltinArguments, v8::internal::Isolate*) [/usr/local/bin/node]
15: 0x181ff23dbf9d 
16: 0x181ff23e6bd5 
17: 0x181ff238a5c3 
18: 0x181ff23918d5 
19: 0x181ff238d02f 
20: 0x181ff2409d9d 
Abort trap: 6
```

my configs are
package.json
```
{
  "name": "cdklambda",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "author": "",
  "license": "ISC",
  "devDependencies": {
    "tslint": "^5.19.0",
    "typescript": "^3.5.3"
  },
  "dependencies": {
    "@aws-cdk/aws-apigateway": "^1.5.0",
    "@aws-cdk/aws-lambda": "^1.5.0",
    "@aws-cdk/aws-s3": "^1.5.0",
    "@aws-cdk/core": "^1.5.0",
    "aws-cdk": "^1.5.0",
    "i": "^0.3.6"
  }
}
```
tsconfig.json
```
{
  "compilerOptions": {
    "target": "ES2018", /* Specify ECMAScript target version: 'ES3' (default), 'ES5', 'ES2015', 'ES2016', 'ES2017', 'ES2018', 'ES2019' or 'ESNEXT'. */
    "module": "commonjs", /* Specify module code generation: 'none', 'commonjs', 'amd', 'system', 'umd', 'es2015', or 'ESNext'. */
    "sourceMap": true, /* Generates corresponding '.map' file. */
    "outDir": "./dist", /* Redirect output structure to the directory. */
    "strict": true, /* Enable all strict type-checking options. */
    "esModuleInterop": true /* Enables emit interoperability between CommonJS and ES Modules via creation of namespace objects for all imports. Implies 'allowSyntheticDefaultImports'. */
  }
}
```
node --version
```
v10.16.0
```

**Comment by bverhoeve** [comment]
Hi everyone,

I've encountered the issue again when deploying multiple stacks (about 20 in the last run) at once. The issue seems to occur when a call is made to `node.apply_aspect(Tag()`, which ends up in a recursive call that never ends, causing the JS call stack limit to be reached. 

I think there might be an issue in the recursive application of tags to CDK resources.

**Comment by bverhoeve** [comment]
I've managed to work around the issue, by only applying tags when absolutely necessary, which does help for now. I've seen that when adding even more tests, the `jsii` kernel gives errors when creating new AWS CDK apps though, which leads me to assume it still runs into memory troubles when executing a lot of tests in one go. Is it possible to sort of flush the memory of the `jsii` kernel before the execution of tests or test suites? I think this could improve stability.

**Comment by mrandall001** [comment]
I've encountered this issue as well, but I'm not working with Tags.  It seems to happen when I have a large number of Constructs in an App or a large number of Apps.  It seems to work with 15 either way, then beyond that I get the "Maximum call stack size exceeded" error.  The only work around I can see is to create my Apps/Stacks in batches.

**Comment by roystchiang** [comment]
I think when you import the library, it creates a global variable, and initializes it with some pseudo-tokens. As you create stacks, more token are added to this variable, and it is not cleaned up when a new App is created.

**Comment by bverhoeve** [comment]
Yes, I also think that is the case. There should be a way to 'flush' that variable or have a way to increase the maximum values.

**Comment by bverhoeve** [comment]
Any news on this? We are now also experiencing the issues when deploying our applications in production, since they have quite a few resources and stacks.

**Comment by RomainMuller** [comment]
Might be fixed (or mitigated) by aws/jsii#780

**Comment by bverhoeve** [comment]
@RomainMuller, I've updated `jsii` and `aws-cdk` to the latest version, and so far so good, the test suite no longer crashes for now 🎉

**Comment by NGL321** [comment]
@bverhoeve,

Did you confirm that this issue has been resolved? I'd love to close out this issue!

😸

**Comment by bverhoeve** [comment]
@NGL321 , yes, I think the issue has been resolved, I no longer see the errors popping up. 👍 👍

**Comment by SomayaB** [comment]
@bverhoeve That's great! I will close the issue then. Please let us know if you experience any other issues.
