### ISSUE TITLE
SSM Can only return strings at synthesis time (Python)

### ISSUE THREAD

**Issue by WillBroadbentMSM** [aws/aws-cdk#3800]
Hi all, I've been looking to template some of our Fargate code recently and thought it would be a good solution to allow developers to set SSM parameters at build time before triggering some generic CDK and overwrite with values they've previously set. Problem is, to set values like ecs_patterns.LoadBalancedFargateService.memory_limit_mib I need to pass a number, at synthesis time, I can only return strings and since this will remain a "Lookup" when my code is executing I can't convert it to an Int. It would be good if the SSM had features that could specify the parameter type other than string, so that it may be passed into other code blocks.

Hope I explained this well enough, if not heres a code snippet for what I was trying to achieve

```
memLimit = ssm.StringParameter.from_string_parameter_attributes(
            self, 'memLimit', 
            parameter_name = 'template-service-mem_limit_mib'
        ).string_value
```

```
        fargate_service = ecs_patterns.LoadBalancedFargateService(
            self, "Fargate",
            cluster = cluster,
            memory_limit_mib = memLimit,
            execution_role=fargate_iam_role,
            container_port=containerPort,
            cpu = cpuSetting,
            image=ecs.ContainerImage.from_registry(ecrRepo)
        )
```

Cheers,
Will

**Comment by WillBroadbentMSM** [comment]
Alternatively its probably a better solution to allow cpu & memory_limit_mib to have ssm parameter references assigned to them! I'm getting this error if I ignore types, etc.

```
/Users/william.broadbent/temp/cdk-workshop/node_modules/@aws-cdk/core/lib/runtime.ts:141
      throw new CfnSynthesisError(message);
            ^
Error: Resolution error: Supplied properties not correct for "CfnSecurityGroupEgressProps"
  fromPort: "dummy-value-for-template-service-container_port" should be a number
  toPort: "dummy-value-for-template-service-container_port" should be a number.
Object creation stack:
  at new Intrinsic (/Users/william.broadbent/temp/cdk-workshop/node_modules/@aws-cdk/core/lib/private/intrinsic.ts:28:26)
  at new PostResolveToken (/Users/william.broadbent/temp/cdk-workshop/node_modules/@aws-cdk/core/lib/util.ts:83:5)
  at CfnSecurityGroupEgress._toCloudFormation (/Users/william.broadbent/temp/cdk-workshop/node_modules/@aws-cdk/core/lib/cfn-resource.ts:222:29)
  at elements.map.e (/Users/william.broadbent/temp/cdk-workshop/node_modules/@aws-cdk/core/lib/stack.ts:567:56)
  at Array.map (<anonymous>)
  at CdkWorkshopStack._toCloudFormation (/Users/william.broadbent/temp/cdk-workshop/node_modules/@aws-cdk/core/lib/stack.ts:567:32)
  at CdkWorkshopStack.synthesize (/Users/william.broadbent/temp/cdk-workshop/node_modules/@aws-cdk/core/lib/stack.ts:519:51)
  at Function.synth (/Users/william.broadbent/temp/cdk-workshop/node_modules/@aws-cdk/core/lib/construct.ts:59:28)
  at App.synth (/Users/william.broadbent/temp/cdk-workshop/node_modules/@aws-cdk/core/lib/app.ts:128:36)
  at process.App.process.once (/Users/william.broadbent/temp/cdk-workshop/node_modules/@aws-cdk/core/lib/app.ts:111:45)
  at Object.onceWrapper (events.js:285:13)
  at process.emit (events.js:197:13)
  at process.EventEmitter.emit (domain.js:439:20)
  at process.emit (/Users/william.broadbent/temp/cdk-workshop/node_modules/source-map-support/source-map-support.js:465:21)
  at process.topLevelDomainCallback (domain.js:120:23)
    at ValidationResult.assertSuccess (/Users/william.broadbent/temp/cdk-workshop/node_modules/@aws-cdk/core/lib/runtime.ts:141:13)
    at cfnSecurityGroupEgressPropsToCloudFormation (/Users/william.broadbent/temp/cdk-workshop/node_modules/@aws-cdk/aws-ec2/lib/ec2.generated.ts:7963:54)
    at CfnSecurityGroupEgress.renderProperties (/Users/william.broadbent/temp/cdk-workshop/node_modules/@aws-cdk/aws-ec2/lib/ec2.generated.ts:8081:16)
    at PostResolveToken.ret.Resources.util_1.PostResolveToken.props [as processor] (/Users/william.broadbent/temp/cdk-workshop/node_modules/@aws-cdk/core/lib/cfn-resource.ts:233:40)
    at PostResolveToken.postProcess (/Users/william.broadbent/temp/cdk-workshop/node_modules/@aws-cdk/core/lib/util.ts:92:17)
    at Object.postProcess (/Users/william.broadbent/temp/cdk-workshop/node_modules/@aws-cdk/core/lib/private/resolve.ts:52:78)
    at DefaultTokenResolver.resolveToken (/Users/william.broadbent/temp/cdk-workshop/node_modules/@aws-cdk/core/lib/resolvable.ts:138:32)
    at resolve (/Users/william.broadbent/temp/cdk-workshop/node_modules/@aws-cdk/core/lib/private/resolve.ts:133:29)
    at Object.resolve (/Users/william.broadbent/temp/cdk-workshop/node_modules/@aws-cdk/core/lib/private/resolve.ts:49:32)
    at resolve (/Users/william.broadbent/temp/cdk-workshop/node_modules/@aws-cdk/core/lib/private/resolve.ts:154:39)
```

**Comment by rix0rrr** [comment]
You should be able to use [`Token.as_number`](https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_core.Token.html#static-as-wbr-numbervalue).

Let me know if that doesn't solve it for you.

**Comment by WillBroadbentMSM** [comment]
Apologies for raising a feature request for this, looks like exactly what i'm after I'll give it a go thank you!
