### ISSUE TITLE
jsii.errors.JSIIError: Class @aws-cdk/core.Stack doesn't have a method 'tryGetContext'

### ISSUE THREAD

**Issue by Kisung** [aws/aws-cdk#3801]
### What is the problem?

I want to get the context in "cdk.json" file. but

### Reproduction Steps

**My "cdk.json" file**
```json
{
    "app": "python app.py",
    "context": {
        "prd-batch": "ami-0###############1"
    }
}
```

**My Script is**
```python
from aws_cdk import (
    core,
)


class QaInfra(core.Stack):
    def __init__(self, scope: core.Construct, a_id: str, **kwargs) -> None:
        super().__init__(scope, a_id, **kwargs)

        cnt = core.ConstructNode.try_get_context(self, key="prd-batch")
        print(cnt)


app = core.App()
QaInfra(app, "qa-batch", env={'account': '2##########3', 'region': 'ap-northeast-2'})

app.synth()

```

### Verbose Log
```bash
(.env) D:\work\nodejs\aws-cdk-test\cdk-workshop>cdk synth --profile xxx-prd
jsii.errors.JavaScriptError:
  Error: Class @aws-cdk/core.Stack doesn't have a method 'tryGetContext'
      at Kernel._typeInfoForMethod (D:\work\nodejs\aws-cdk-test\cdk-workshop\.env\lib\site-packages\jsii\_embedded\jsii\jsii-runtime.js:6949:19)
      at Kernel._findInvokeTarget (D:\work\nodejs\aws-cdk-test\cdk-workshop\.env\lib\site-packages\jsii\_embedded\jsii\jsii-runtime.js:6865:25)
      at Kernel.invoke (D:\work\nodejs\aws-cdk-test\cdk-workshop\.env\lib\site-packages\jsii\_embedded\jsii\jsii-runtime.js:6492:38)
      at KernelHost.processRequest (D:\work\nodejs\aws-cdk-test\cdk-workshop\.env\lib\site-packages\jsii\_embedded\jsii\jsii-runtime.js:6191:28)
      at KernelHost.run (D:\work\nodejs\aws-cdk-test\cdk-workshop\.env\lib\site-packages\jsii\_embedded\jsii\jsii-runtime.js:6137:14)
      at processRequest (D:\work\nodejs\aws-cdk-test\cdk-workshop\.env\lib\site-packages\jsii\_embedded\jsii\jsii-runtime.js:6137:45)
      at KernelHost.processRequest (D:\work\nodejs\aws-cdk-test\cdk-workshop\.env\lib\site-packages\jsii\_embedded\jsii\jsii-runtime.js:6233:16)
      at KernelHost.run (D:\work\nodejs\aws-cdk-test\cdk-workshop\.env\lib\site-packages\jsii\_embedded\jsii\jsii-runtime.js:6137:14)
      at processRequest (D:\work\nodejs\aws-cdk-test\cdk-workshop\.env\lib\site-packages\jsii\_embedded\jsii\jsii-runtime.js:6137:45)
      at KernelHost.processRequest (D:\work\nodejs\aws-cdk-test\cdk-workshop\.env\lib\site-packages\jsii\_embedded\jsii\jsii-runtime.js:6233:16)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "create_qa_infra.py", line 15, in <module>
    QaInfra(app, "qa-batch", env={'account': '2##########3', 'region': 'ap-northeast-2'})
  File "D:\work\nodejs\aws-cdk-test\cdk-workshop\.env\lib\site-packages\jsii\_runtime.py", line 66, in __call__
    inst = super().__call__(*args, **kwargs)
  File "create_qa_infra.py", line 10, in __init__
    cnt = core.ConstructNode.try_get_context(self, key="an2-ssf-prd-batch01a")
  File "D:\work\nodejs\aws-cdk-test\cdk-workshop\.env\lib\site-packages\aws_cdk\core\__init__.py", line 1386, in try_get_context
    return jsii.invoke(self, "tryGetContext", [key])
  File "D:\work\nodejs\aws-cdk-test\cdk-workshop\.env\lib\site-packages\jsii\_kernel\__init__.py", line 104, in wrapped
    return _recursize_dereference(kernel, fn(kernel, *args, **kwargs))
  File "D:\work\nodejs\aws-cdk-test\cdk-workshop\.env\lib\site-packages\jsii\_kernel\__init__.py", line 267, in invoke
    args=_make_reference_for_native(self, args),
  File "D:\work\nodejs\aws-cdk-test\cdk-workshop\.env\lib\site-packages\jsii\_kernel\providers\process.py", line 346, in invoke
    return self._process.send(request, InvokeResponse)
  File "D:\work\nodejs\aws-cdk-test\cdk-workshop\.env\lib\site-packages\jsii\_kernel\providers\process.py", line 316, in send
    raise JSIIError(resp.error) from JavaScriptError(resp.stack)
jsii.errors.JSIIError: Class @aws-cdk/core.Stack doesn't have a method 'tryGetContext'
Subprocess exited with error 1

```

### Environment

  - **CDK CLI Version:** 1.5.0 (build c020efa)
  - **Module Version:** aws-cdk.core==1.5.0
  - **OS:** Windows 10
  - **Language:** Python

**Comment by rix0rrr** [comment]
The correct location of that function would be `self.node.try_get_context()`.
