### ISSUE TITLE
elbv2.ApplicationListener.addTargets() creates security group in the wrong stack when referenced across stacks

### ISSUE THREAD

**Issue by nathanpeck** [aws/aws-cdk#3835]
### What is the problem?
When an Application Load Balancer listener is created in one stack, then passed to another stack which creates the target and adds it to the listener, the security group is created in the wrong stack, causing a cyclic dependency error.

Expectation is that the security group rule should be created in the second stack, the same stack that defines the target and adds the target to the listener.

### Reproduction Steps
Create load balancer and listener in one stack. Create a target in another stack, and attempt to add the target to the load balancer from the first stack. Sample code to repro here:

```typescript
import ec2 = require('@aws-cdk/aws-ec2');
import ecs = require('@aws-cdk/aws-ecs');
import elbv2 = require('@aws-cdk/aws-elasticloadbalancingv2');
import cdk = require('@aws-cdk/core');

class BaseResources extends cdk.Stack {
  vpc: ec2.Vpc;
  cluster: ecs.Cluster;
  loadBalancerListener: elbv2.ApplicationListener;

  constructor(scope: cdk.App, id: string, props?: cdk.StackProps) {
    super(scope, id, props);

    // Create VPC and Fargate Cluster
    // NOTE: Limit AZs to avoid reaching resource quotas
    this.vpc = new ec2.Vpc(this, 'MyVpc', { maxAzs: 2 });
    this.cluster = new ecs.Cluster(this, 'Cluster', { vpc: this.vpc });

    // Internal load balancer for the backend services
    const internalLB = new elbv2.ApplicationLoadBalancer(this, 'internal', {
      vpc: this.vpc,
      internetFacing: true
    });

    this.loadBalancerListener = internalLB.addListener('PublicListener', { port: 80, open: true });

    this.loadBalancerListener.addTargetGroups('default', {
      targetGroups: [new elbv2.ApplicationTargetGroup(this, 'default', {
        vpc: this.vpc,
        protocol: elbv2.ApplicationProtocol.HTTP,
        port: 80
      })]
    });

    // Output the DNS where you can access your service
    new cdk.CfnOutput(this, 'LoadBalancerDNS', { value: internalLB.loadBalancerDnsName });
  }
}

export interface ServiceStackProps {
  vpc: ec2.Vpc;
  cluster: ecs.Cluster;
  loadBalancerListener: elbv2.ApplicationListener;
}

class SimpleFargateService extends cdk.Stack {
  constructor(scope: cdk.App, id: string, props: ServiceStackProps) {
    super(scope, id);

    // Name service
    const nameTaskDefinition = new ecs.FargateTaskDefinition(this, 'name-task-definition', {});

    const nameContainer = nameTaskDefinition.addContainer('name', {
      image: ecs.ContainerImage.fromRegistry("nathanpeck/name"),
      memoryLimitMiB: 512
    });

    nameContainer.addPortMappings({
      containerPort: 80
    });

    const nameService = new ecs.FargateService(this, 'name-service', {
      cluster: props.cluster,
      desiredCount: 2,
      taskDefinition: nameTaskDefinition
    });

    props.loadBalancerListener.addTargets('name', {
      port: 80,
      pathPattern: '*',
      priority: 1,

      // Only 10 seconds for new tasks to become healthy.
      // Increase if your application is slower to startup
      healthCheck: {
        healthyThresholdCount: 2,
        interval: cdk.Duration.seconds(5),
        timeout: cdk.Duration.seconds(2)
      },

      // Only drain containers for 10 seconds when stopping them.
      // Increase if your app has long lived connections
      deregistrationDelay: cdk.Duration.seconds(10),

      targets: [nameService]
    });
  }
}

const app = new cdk.App();

const base = new BaseResources(app, 'ecs-samples-base-resources');
new SimpleFargateService(app, 'ecs-samples-simple-fargate-service', {
  vpc: base.vpc,
  cluster: base.cluster,
  loadBalancerListener: base.loadBalancerListener
});

app.synth();
```

### Verbose Log
```
Error: 'ecs-samples-simple-fargate-service' depends on 'ecs-samples-base-resources' (ecs-samples-simple-fargate-service/name-service/Service -> ecs-samples-base-resources/Cluster/Resource.Ref). Adding this dependency (ecs-samples-base-resources/internal/SecurityGroup/to ecssamplessimplefargateservicenameserviceSecurityGroup88168BDD:80 -> ecs-samples-simple-fargate-service/name-service/SecurityGroup/Resource.GroupId) would create a cyclic reference.
    at BaseResources.addDependency (/Users/peckn/Documents/Code/aws-cdk-ecs-examples/example-architectures/public-facing-service/node_modules/@aws-cdk/core/lib/stack.js:147:19)
    at CfnReference.consumeFromStack (/Users/peckn/Documents/Code/aws-cdk-ecs-examples/example-architectures/public-facing-service/node_modules/@aws-cdk/core/lib/private/cfn-reference.js:105:28)
    at BaseResources.prepare (/Users/peckn/Documents/Code/aws-cdk-ecs-examples/example-architectures/public-facing-service/node_modules/@aws-cdk/core/lib/stack.js:350:31)
    at Function.prepare (/Users/peckn/Documents/Code/aws-cdk-ecs-examples/example-architectures/public-facing-service/node_modules/@aws-cdk/core/lib/construct.js:89:27)
    at Function.synth (/Users/peckn/Documents/Code/aws-cdk-ecs-examples/example-architectures/public-facing-service/node_modules/@aws-cdk/core/lib/construct.js:52:14)
    at App.synth (/Users/peckn/Documents/Code/aws-cdk-ecs-examples/example-architectures/public-facing-service/node_modules/@aws-cdk/core/lib/app.js:67:52)
    at Object.<anonymous> (/Users/peckn/Documents/Code/aws-cdk-ecs-examples/example-architectures/public-facing-service/index.js:73:5)
    at Module._compile (internal/modules/cjs/loader.js:816:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:827:10)
    at Module.load (internal/modules/cjs/loader.js:685:32)
```

### Environment

  - **CDK CLI Version:** 1.6.0 (build 3a0cde0)
  - **Module Version:** 1.6.0 (build 3a0cde0)
  - **OS:** OSX
  - **Language:** TypeScript

**Comment by rix0rrr** [comment]
Closing as a duplicate of https://github.com/aws/aws-cdk/issues/3689. Some work has been done on this in the form of https://github.com/aws/aws-cdk/pull/4111.
