### ISSUE TITLE
Object of type @aws-cdk/aws-rds.DatabaseSecret is not convertible to @aws-cdk/aws-ecs.Secret

### ISSUE THREAD

**Issue by jonnyyu** [aws/aws-cdk#3879]
### What is the problem?

aws-rds.DatabaseSecret is a child class of aws-secretsmanager.Secret, so does in Python binding. But when I passing DatabaseSecret instance to places accepts Secret, it shows error message: 

```
jsii.errors.JSIIError: Object of type @aws-cdk/aws-rds.DatabaseSecret is not convertible to @aws-cdk/aws-ecs.Secret
```

### Reproduction Steps

```
db_secret = rds.DatabaseSecret(self, 'Secret', username='user')
task_def = ecs.FargateTaskDefinition(self, 'task')
taskdef.add_container('some-app',
    image=ecs.ContainerImage.from_registry('some-app:1.0'),
    secrets={"DB_SECRET": db_secret}
)
```

### Verbose Log

```
$ cdk ls
jsii.errors.JavaScriptError:
  Error: Object of type @aws-cdk/aws-rds.DatabaseSecret is not convertible to @aws-cdk/aws-ecs.Secret
      at Object.deserialize (/home/ec2-user/task_service/.env/lib/python3.7/site-packages/jsii/_embedded/jsii/jsii-runtime.js:12263:27)
      at Kernel._toSandbox (/home/ec2-user/task_service/.env/lib/python3.7/site-packages/jsii/_embedded/jsii/jsii-runtime.js:7031:61)
      at /home/ec2-user/task_service/.env/lib/python3.7/site-packages/jsii/_embedded/jsii/jsii-runtime.js:12144:47
      at mapValues (/home/ec2-user/task_service/.env/lib/python3.7/site-packages/jsii/_embedded/jsii/jsii-runtime.js:12447:27)
      at Object.deserialize (/home/ec2-user/task_service/.env/lib/python3.7/site-packages/jsii/_embedded/jsii/jsii-runtime.js:12144:20)
      at Kernel._toSandbox (/home/ec2-user/task_service/.env/lib/python3.7/site-packages/jsii/_embedded/jsii/jsii-runtime.js:7031:61)
      at /home/ec2-user/task_service/.env/lib/python3.7/site-packages/jsii/_embedded/jsii/jsii-runtime.js:12218:29
      at mapValues (/home/ec2-user/task_service/.env/lib/python3.7/site-packages/jsii/_embedded/jsii/jsii-runtime.js:12447:27)
      at Object.deserialize (/home/ec2-user/task_service/.env/lib/python3.7/site-packages/jsii/_embedded/jsii/jsii-runtime.js:12214:20)
      at Kernel._wrapSandboxCode (/home/ec2-user/task_service/.env/lib/python3.7/site-packages/jsii/_embedded/jsii/jsii-runtime.js:7134:19)
      at /home/ec2-user/task_service/.env/lib/python3.7/site-packages/jsii/_embedded/jsii/jsii-runtime.js:6498:25
      at Kernel._ensureSync (/home/ec2-user/task_service/.env/lib/python3.7/site-packages/jsii/_embedded/jsii/jsii-runtime.js:7102:20)
      at Kernel.invoke (/home/ec2-user/task_service/.env/lib/python3.7/site-packages/jsii/_embedded/jsii/jsii-runtime.js:6497:26)
      at KernelHost.processRequest (/home/ec2-user/task_service/.env/lib/python3.7/site-packages/jsii/_embedded/jsii/jsii-runtime.js:6191:28)
      at KernelHost.run (/home/ec2-user/task_service/.env/lib/python3.7/site-packages/jsii/_embedded/jsii/jsii-runtime.js:6137:14)
      at /home/ec2-user/task_service/.env/lib/python3.7/site-packages/jsii/_embedded/jsii/jsii-runtime.js:6137:45
      at KernelHost.processRequest (/home/ec2-user/task_service/.env/lib/python3.7/site-packages/jsii/_embedded/jsii/jsii-runtime.js:6233:16)
      at KernelHost.run (/home/ec2-user/task_service/.env/lib/python3.7/site-packages/jsii/_embedded/jsii/jsii-runtime.js:6137:14)
      at /home/ec2-user/task_service/.env/lib/python3.7/site-packages/jsii/_embedded/jsii/jsii-runtime.js:6137:45
      at KernelHost.processRequest (/home/ec2-user/task_service/.env/lib/python3.7/site-packages/jsii/_embedded/jsii/jsii-runtime.js:6233:16)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "app.py", line 33, in <module>
    env=account_region_env,
  File "/home/ec2-user/task_service/.env/lib64/python3.7/site-packages/jsii/_runtime.py", line 66, in __call__
    inst = super().__call__(*args, **kwargs)
  File "/home/ec2-user/task_service/deploy/cdk/src/task_service_stack.py", line 51, in __init__
    secrets={"DB_CREDENTIAL": db_secret},
  File "/home/ec2-user/task_service/.env/lib64/python3.7/site-packages/aws_cdk/aws_ecs/__init__.py", line 8047, in add_container
    return jsii.invoke(self, "addContainer", [id, props])
  File "/home/ec2-user/task_service/.env/lib64/python3.7/site-packages/jsii/_kernel/__init__.py", line 104, in wrapped
    return _recursize_dereference(kernel, fn(kernel, *args, **kwargs))
  File "/home/ec2-user/task_service/.env/lib64/python3.7/site-packages/jsii/_kernel/__init__.py", line 267, in invoke
    args=_make_reference_for_native(self, args),
  File "/home/ec2-user/task_service/.env/lib64/python3.7/site-packages/jsii/_kernel/providers/process.py", line 346, in invoke
    return self._process.send(request, InvokeResponse)
  File "/home/ec2-user/task_service/.env/lib64/python3.7/site-packages/jsii/_kernel/providers/process.py", line 316, in send
    raise JSIIError(resp.error) from JavaScriptError(resp.stack)
jsii.errors.JSIIError: Object of type @aws-cdk/aws-rds.DatabaseSecret is not convertible to @aws-cdk/aws-ecs.Secret
```

### Environment

  - **CDK CLI Version:** 1.6.0 (build 3a0cde0)
  - **Module Version:** 
aws-cdk.aws-rds                     1.6.0
aws-cdk.aws-secretsmanager          1.6.0
  - **OS:** 
AMI Linux 2
  - **Language:** 
Python

**Comment by rubenjgarcia** [comment]
I was having the same problem and I resolved it with this code

`secrets={"DB_SECRET": ecs.Secret.from_secrets_manager(db_secret)}`

Hope it helps others
