### ISSUE TITLE
argument type mismatch when Aspect visits: IScalableTableAttribute in Java

### ISSUE THREAD

**Issue by robessog** [aws/aws-cdk#3892]
### What is the problem?
Aspect's `visit(...)` method throws `java.lang.IllegalArgumentException` when I start to use `autoScaleReadCapacity` method of DynamoDB Table in Java.

### Reproduction Steps
The class composition can be very basic: MyRootStack-->MyDynamoConstruct-->Table

Example aspect:

```java
public class KeepLogicalIdAspect implements IAspect {
    public KeepLogicalIdAspect() {
    }

    public void visit(IConstruct node) {
        // Do anything
    }
}
```

Code in DynamoConstruct:
```java
TableProps inputVarTableProps = TableProps.builder()
                ... // setting properties
                .build();
Table inputVariablesTable = new Table(this, "TableInputVariables", inputVarTableProps);

        IScalableTableAttribute inputVarsReadScaleAttr = inputVariablesTable.autoScaleReadCapacity(EnableScalingProps.builder()
                .maxCapacity(40000)
                .minCapacity(inputVarTableProps.getReadCapacity())
                .build());
```

Applying aspect in MyRootStack:
```java
IAspect keepLogicalIdAspect = new KeepLogicalIdAspect();
        this.getNode().applyAspect(keepLogicalIdAspect);
```
### Verbose Log
```
Error while invoking public void cdktest.KeepLogicalIdAspect.visit(software.amazon.awscdk.core.IConstruct) with [software.amazon.awscdk.services.dynamodb.IScalableTableAttribute$Jsii$Proxy@157632c9]: java.lang.IllegalArgumentException: argument type mismatch
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at software.amazon.jsii.JsiiEngine.invokeMethod(JsiiEngine.java:386)
        at software.amazon.jsii.JsiiEngine.invokeCallbackMethod(JsiiEngine.java:36
at software.amazon.jsii.JsiiRuntime.processCallbackResponse(JsiiRuntime.java:152)
        at software.amazon.jsii.JsiiRuntime.requestResponse(JsiiRuntime.java:89)
        at software.amazon.jsii.JsiiClient.callMethod(JsiiClient.java:185)
        at software.amazon.jsii.JsiiObject.jsiiCall(JsiiObject.java:61)
        at software.amazon.awscdk.core.App.synth(App.java:70)
        at cdktest.DataInfrastructureApp.main(DataInfrastructureApp.java:19)

Exception in thread "main" software.amazon.jsii.JsiiException: argument type mismatch
Error: argument type mismatch
    at completeCallback (/private/var/folders/fq/7tq9y7n12v3bx50n9ggm6x11twz_x7/T/jsii-java-runtime6381733548583615551/jsii-runtime.js:6156:27)
    at KernelHost.callbackHandler (/private/var/folders/fq/7tq9y7n12v3bx50n9ggm6x11twz_x7/T/jsii-java-runtime6381733548583615551/jsii-runtime.js:6145:16)
    at KernelHost.kernel.jsii_kernel_1.Kernel.cb [as callbackHandler] (/private/var/folders/fq/7tq9y7n12v3bx50n9ggm6x11twz_x7/T/jsii-java-runtime6381733548583615551/jsii-runtime.js:6129:59)
```

### Environment

  - **CDK CLI Version:** 1.6
  - **Module Version:** 1.6
  - **OS:** OSX Mojave
  - **Language:** Java

### Other information
I think the issue might be one of the following two:
-  Either the visitor should not visit `IScalableTableAttribute` so that Aspects won't break
- or `IScalableTableAttribute` should be "compatible" with the type of visitor method argument type`IConstruct`

**Comment by RomainMuller** [comment]
Does this still occur with the latest CDK release? This may have been a `jsii` bug that has since been fixed.

**Comment by SomayaB** [comment]
Closing for now since there hasn't been a response in a while. Feel free to reopen.
