### ISSUE TITLE
asset staging: do not recurse into the output directory

### ISSUE THREAD

**Issue by jeshan** [aws/aws-cdk#3899]
### What is the problem?

I have hit a corner case with the code related to copy directories. It's going in recursively until Node can no longer handle such long file names.

https://github.com/aws/aws-cdk/blob/16eb65867b79798779bf98a0316b1a05915720f1/packages/%40aws-cdk/assets/lib/fs/copy.ts#L7-L18

The offending snippet is when I had a docker asset declared as follows:
```javascript
        new DockerImageAsset(this, 'app-image-asset', {
            directory: '.',
            repositoryName: 'my-repo/app',
        });
```

Running `cdk deploy` showed me this error:
```
Error: ENAMETOOLONG: name too long, mkdir 'cdk.out/asset.7e4b3cc320bdf668daa4c0d065bb1a9841162c955cb702f7a01d7d3d7e88dbfe/cdk.out/asset.7e4b3cc320bdf668daa4c0d065bb1a9841162c955cb702f7a01d7d3d7e88dbfe/cdk.out/asset.7e4b3cc320bdf668daa4c0d065bb1a9841162c955cb702f7a01d7d3d7e88dbfe/cdk.out/asset.7e4b3cc320bdf668daa4c0d065bb1a9841162c955cb702f7a01d7d3d7e88dbfe/cdk.out/asset.7e4b3cc320bdf668daa4c0d065bb1a9841162c955cb702f7a01d7d3d7e88dbfe/cdk.out/asset.7e4b3cc320bdf668daa4c0d065bb1a9841162c955cb702f7a01d7d3d7e88dbfe/cdk.out/asset.7e4b3cc320bdf668daa4c0d065bb1a9841162c955cb702f7a01d7d3d7e88dbfe/cdk.out/asset.7e4b3cc320bdf668daa4c0d065bb1a9841162c955cb702f7a01d7d3d7e88dbfe/cdk.out/asset.7e4b3cc320bdf668daa4c0d065bb1a9841162c955cb702f7a01d7d3d7e88dbfe/cdk.out/asset.7e4b3cc320bdf668daa4c0d065bb1a9841162c955cb702f7a01d7d3d7e88dbfe/cdk.out/asset.7e4b3cc320bdf668daa4c0d065bb1a9841162c955cb702f7a01d7d3d7e88dbfe/cdk.out/asset.7e4b3cc320bdf668daa4c0d065bb1a9841162c955cb702f7a01d7d3d7e88dbfe/cdk.out/asset.7e4b3cc320bdf668daa4c0d065bb1a9841162c955cb702f7a01d7d3d7e88dbfe/cdk.out/asset.7e4b3cc320bdf668daa4c0d065bb1a9841162c955cb702f7a01d7d3d7e88dbfe/cdk.out/asset.7e4b3cc320bdf668daa4c0d065bb1a9841162c955cb702f7a01d7d3d7e88dbfe/cdk.out/asset.7e4b3cc320bdf668daa4c0d065bb1a9841162c955cb702f7a01d7d3d7e88dbfe/cdk.out/asset.7e4b3cc320bdf668daa4c0d065bb1a9841162c955cb702f7a01d7d3d7e88dbfe/cdk.out/asset.7e4b3cc320bdf668daa4c0d065bb1a9841162c955cb702f7a01d7d3d7e88dbfe/cdk.out/asset.7e4b3cc320bdf668daa4c0d065bb1a9841162c955cb702f7a01d7d3d7e88dbfe/cdk.out/asset.7e4b3cc320bdf668daa4c0d065bb1a9841162c955cb702f7a01d7d3d7e88dbfe/cdk.out/asset.7e4b3cc320bdf668daa4c0d065bb1a9841162c955cb702f7a01d7d3d7e88dbfe/cdk.out/asset.7e4b3cc320bdf668daa4c0d065bb1a9841162c955cb702f7a01d7d3d7e88dbfe/cdk.out/asset.7e4b3cc320bdf668daa4c0d065bb1a9841162c955cb702f7a01d7d3d7e88dbfe/cdk.out/asset.7e4b3cc320bdf668daa4c0d065bb1a9841162c955cb702f7a01d7d3d7e88dbfe/cdk.out/asset.7e4b3cc320bdf668daa4c0d065bb1a9841162c955cb702f7a01d7d3d7e88dbfe/cdk.out/asset.7e4b3cc320bdf668daa4c0d065bb1a9841162c955cb702f7a01d7d3d7e88dbfe/cdk.out/asset.7e4b3cc320bdf668daa4c0d065bb1a9841162c955cb702f7a01d7d3d7e88dbfe/cdk.out/asset.7e4b3cc320bdf668daa4c0d065bb1a9841162c955cb702f7a01d7d3d7e88dbfe/cdk.out/asset.7e4b3cc320bdf668daa4c0d065bb1a9841162c955cb702f7a01d7d3d7e88dbfe/cdk.out/asset.7e4b3cc320bdf668daa4c0d065bb1a9841162c955cb702f7a01d7d3d7e88dbfe/cdk.out/asset.7e4b3cc320bdf668daa4c0d065bb1a9841162c955cb702f7a01d7d3d7e88dbfe/cdk.out/asset.7e4b3cc320bdf668daa4c0d065bb1a9841162c955cb702f7a01d7d3d7e88dbfe/cdk.out/asset.7e4b3cc320bdf668daa4c0d065bb1a9841162c955cb702f7a01d7d3d7e88dbfe/cdk.out/asset.7e4b3cc320bdf668daa4c0d065bb1a9841162c955cb702f7a01d7d3d7e88dbfe/cdk.out/asset.7e4b3cc320bdf668daa4c0d065bb1a9841162c955cb702f7a01d7d3d7e88dbfe/cdk.out/asset.7e4b3cc320bdf668daa4c0d065bb1a9841162c955cb702f7a01d7d3d7e88dbfe/cdk.out/asset.7e4b3cc320bdf668daa4c0d065bb1a9841162c955cb702f7a01d7d3d7e88dbfe/cdk.out/asset.7e4b3cc320bdf668daa4c0d065bb1a9841162c955cb702f7a01d7d3d7e88dbfe/cdk.out/asset.7e4b3cc320bdf668daa4c0d065bb1a9841162c955cb702f7a01d7d3d7e88dbfe/cdk.out/asset.7e4b3cc320bdf668daa4c0d065bb1a9841162c955cb702f7a01d7d3d7e88dbfe/cdk.out/asset.7e4b3cc320bdf668daa4c0d065bb1a9841162c955cb702f7a01d7d3d7e88dbfe/cdk.out/asset.7e4b3cc320bdf668daa4c0d065bb1a9841162c955cb702f7a01d7d3d7e88dbfe/cdk.out/asset.7e4b3cc320bdf668daa4c0d065bb1a9841162c955cb702f7a01d7d3d7e88dbfe/cdk.out/asset.7e4b3cc320bdf668daa4c0d065bb1a9841162c955cb702f7a01d7d3d7e88dbfe/cdk.out/asset.7e4b3cc320bdf668daa4c0d065bb1a9841162c955cb702f7a01d7d3d7e88dbfe/cdk.out/asset.7e4b3cc320bdf668daa4c0d065bb1a9841162c955cb702f7a01d7d3d7e88dbfe/cdk.out/asset.7e4b3cc320bdf668daa4c0d065bb1a9841162c955cb702f7a01d7d3d7e88dbfe/cdk.out/asset.7e4b3cc320bdf668daa4c0d065bb1a9841162c955cb702f7a01d7d3d7e88dbfe/cdk.out/asset.7e4b3cc320bdf668daa4c0d065bb1a9841162c955cb702f7a01d7d3d7e88dbfe/cdk.out/asset.7e4b3cc320bdf668daa4c0d065bb1a9841162c955cb702f7a01d7d3d7e88dbfe/cdk.out/asset.7e4b3cc320bdf668daa4c0d065bb1a9841162c955cb702f7a01d7d3d7e88dbfe/cdk.out/asset.03918990104d8973acd2ad0abe022844192fcce618cf74f7734a7077f4111d1f'
    at Object.mkdirSync (fs.js:750:3)
    at copyDirectory (/mnt/sdb/ideaProjects/my-project/node_modules/@aws-cdk/assets/lib/fs/copy.js:39:16)
    at copyDirectory (/mnt/sdb/ideaProjects/my-project/node_modules/@aws-cdk/assets/lib/fs/copy.js:40:13)
    at copyDirectory (/mnt/sdb/ideaProjects/my-project/node_modules/@aws-cdk/assets/lib/fs/copy.js:40:13)
    at copyDirectory (/mnt/sdb/ideaProjects/my-project/node_modules/@aws-cdk/assets/lib/fs/copy.js:40:13)
    at copyDirectory (/mnt/sdb/ideaProjects/my-project/node_modules/@aws-cdk/assets/lib/fs/copy.js:40:13)
    at copyDirectory (/mnt/sdb/ideaProjects/my-project/node_modules/@aws-cdk/assets/lib/fs/copy.js:40:13)
    at copyDirectory (/mnt/sdb/ideaProjects/my-project/node_modules/@aws-cdk/assets/lib/fs/copy.js:40:13)
    at copyDirectory (/mnt/sdb/ideaProjects/my-project/node_modules/@aws-cdk/assets/lib/fs/copy.js:40:13)
    at copyDirectory (/mnt/sdb/ideaProjects/my-project/node_modules/@aws-cdk/assets/lib/fs/copy.js:40:13)
```

_(Declaring the directory as its full path did not work neither.)_
This is quite a serious issue for me, personally.

A possible solution is to exclude `cdk.out`. I think it's reasonable to assume that `cdk.out` name is reserved for this project.

As a temporary workaround for me, I've edited the code so that it looks like the following:
```javascript
    const exclude = options.exclude || ['cdk.out'];
```

Another possible solution is to avoid recursion if we've already seen the directory in question.

Apparently, it's an issue where the docker build context is the same path as the cdk project. 
That said, I'm not sure if the above is enough to reproduce the issue. When I comment the code to create the docker asset, the issue disappears (probably more of a symptom rather than the cause). I've checked if symlinks are the issue (apparently, it's not)

### Environment

  - **CDK CLI Version:** 1.6.1
  - **OS:** all
  - **Language:** all

**Comment by rhboyd** [comment]
This usually happens when you try to build an image from within a directory you want included in the image as well. It creates a recursive path that never ends.

**Comment by joezhou888** [comment]
I had the same problem. 

The only way to make it work is:
Project
   -App Directory
   -Env Directory

**Comment by jeshan** [comment]
Thanks Joe.
@rhboyd , we could make the exclude directory list an option in cdk.json. What do you think?

**Comment by eladb** [comment]
This is a bug. It makes sense that when we copy assets into the output directory, we won't descend into the same directory as we copy.

**Comment by askulkarni2** [comment]
Saw this issue for a similar use case while using the aws-s3-assets module. I was trying to zip up my cdk project into s3 and use it to bootstrap CodeCommit. Excluding `cdk.out` seems to work.

**Comment by BinaryShrub** [comment]
I added `cdk*` to .dockerignore to get it working:

``` typescript
// Create Fargate Service
const fargateService = new ecs_patterns.NetworkLoadBalancedFargateService(
  this,
  'sample-app',
  {
    cluster,
    taskImageOptions: {
      image: ecs.ContainerImage.fromAsset('./') // blows up without cdk.out in .dockerignore
    }
  }
)
```

**Comment by victorL91** [comment]
I bumped into this issue again. It may be stupid but I solved it by making sure that the version of aws-cdk on my machine was the same as on the package.json. I was not bootstrapping it the correct way.

**Comment by wdolek** [comment]
> I added `cdk*` to .dockerignore to get it working:

Don't forget about checking your `cdk.json` to contain:

```json
{
  "context": {
    "@aws-cdk/aws-ecr-assets:dockerIgnoreSupport": true
  }
}
```

Otherwise `.dockerignore` is ... ignored 🤷 .

**Comment by mikeshi80** [comment]
> > I added `cdk*` to .dockerignore to get it working:
> 
> Don't forget to check your `cdk.json`, it should contain:
> 
> ```json
> {
>   "context": {
>     "@aws-cdk/aws-ecr-assets:dockerIgnoreSupport": true
>   }
> }
> ```
> 
> Otherwise `.dockerignore` is ignored

You saved me!!!

**Comment by bashleigh** [comment]
> > I added `cdk*` to .dockerignore to get it working:
> 
> Don't forget to check your `cdk.json`, it should contain:
> 
> ```json
> {
>   "context": {
>     "@aws-cdk/aws-ecr-assets:dockerIgnoreSupport": true
>   }
> }
> ```
> 
> Otherwise `.dockerignore` is ignored 🤷

Mine seems to ignore my .dockerignore file anyway. Could be because I've changed to context dir but I have also tried adding the .dockerignore file to the root of my context 

```ts
const lith = new lambda.DockerImageFunction(this, `${name}lith`, {
      code: lambda.DockerImageCode.fromImageAsset(path.join(__dirname, '../../../../'), { // root of monolith 
        file: 'packages/deployment-service/Dockerfile', // location of Dockerfile
        ignoreMode: IgnoreMode.DOCKER,
        exclude: [
          'cdk.out',
        ],
      }),
      vpc,
    })
```

Tried both ~/.dockerfile and ~/packages/deployment-service/.dockerfile. Not sure what else to try!

**Comment by stevemer** [comment]
Re:
`"@aws-cdk/aws-ecr-assets:dockerIgnoreSupport": true,`

It looks like this is no longer necessary.

```
jsii.errors.JSIIError: Unsupported feature flag '@aws-cdk/aws-ecr-assets:dockerIgnoreSupport'. This flag existed on CDKv1 but has been removed in CDKv2. CDK will now behave as the same as when the flag is enabled.
```

**Comment by wallacepreston** [comment]
I'm still seeing this issue.  I get this when adding the flag, alright.  But I still get the `ENAMETOOLONG: name too long` error about the `cdk.out` dir

> Re: `"@aws-cdk/aws-ecr-assets:dockerIgnoreSupport": true,`
> 
> It looks like this is no longer necessary.
> 
> ```
> jsii.errors.JSIIError: Unsupported feature flag '@aws-cdk/aws-ecr-assets:dockerIgnoreSupport'. This flag existed on CDKv1 but has been removed in CDKv2. CDK will now behave as the same as when the flag is enabled.
> ```

**Comment by abury** [comment]
Seeing this issue pop up again in random repos :(

**Comment by austinschrader** [comment]
> Seeing this issue pop up again in random repos :(
> 
> Figured it out thanks to @bashleigh 's detailed comment! I ignored the entire cdk folder at the root and all was well

Could you share how you ignored the entire cdk folder at the root? .dockerignore doesn't seem to work as the flag `@aws-cdk/aws-ecr-assets:dockerIgnoreSupport` was deprecated in cdk v2

**Comment by robertIanClarkson** [comment]
I am experimenting with  polylith monorepo with components, bases, projects that looks similar to this...
```
├── .dockerignore << add */**/cdk.out
├── bases
│   └── ts
│       └── some-base-pkg
│           └── src
├── components
│   └── ts
│       └── some-component-pkg
│           └── src
└── projects
    └── ts
        └── some-project-pkg << running cdk deploy
            └── Dockerfile
            └── cdk.json
            └── src
            └── bin
                └── cdk-app.ts << cdk code
```
My `cdk-app.ts` includes some code like this
```
const asset = new cdk.aws_ecr_assets.DockerImageAsset(this, "some-id", {
  directory: "/my/project/root,
  file: "projects/ts/some-project-pkg/Dockerfile"
})
```
what worked for me was added `*/**/cdk.out` to my root `.dockerignore`.
Hope this helps someone!

**Comment by andhisan** [comment]
In my project, I had specified the bundling directory as the repository root via `@aws-cdk/aws-lambda-python-alpha`.

While `assetExcludes` option works for bundling, commands like bootstrap or testing cdk causes recurse copy as it still clones entire root directory.

So I had no choice but to edit cdk.json to output cdk.out entirely outside the repository, like this:

```json
  "output": "../<repository-name>.cdk.out",
```
