### ISSUE TITLE
sam.CfnApi definitionBody doesn't respect type definition

### ISSUE THREAD

**Issue by rhboyd** [aws/aws-cdk#3900]
### What is the problem?

When using the aws-sam CfnApi L1 Construct, the definitioBody property is defined to be a string, CDK does 1 of two things:

If the value supplied by the user is a pure string, CDK will error out and say 
```
Error: Resolution error: Supplied properties not correct for "CfnApiProps"
definitionBody: "swagger: 2.0" should be an 'object'.
```

If the value supplied by the user is a format string such as `` `"swagger": 2.0,\n ....\n${cdk.Aws.REGION}` ``

CDK will convert that to an object enclosing an `Fn::Join` and Cloudformation will complain that it expected a String but got an Object consisting of a string.

### Reproduction Steps
```
const loyaltyApi = new sam.CfnApi(this, "LoyaltyApi", {
            name: `LoyaltyApi-${props.stage}`,
            stageName: 'Prod',
            methodSettings: [{
                MetricsEnabled: true,
                ResourcePath: '/*',
                HttpMethod: '*',
                ThrottlingRateLimit: 100,
                ThrottlingBurstLimit: 50
            }],
            auth: {
                defaultAuthorizer: "AWS_IAM"
            },
            definitionBody: `swagger: "2.0"
x-amazon-apigateway-request-validator: all
x-amazon-apigateway-request-validators:
  all:
    validateRequestBody: true
    validateRequestParameters: true
produces:
  - application/json
paths:
  "/loyalty/{customerId}":
    get:
      summary: 'Fetch customer loyalty points'
      parameters:
      - name: "customerId"
        in: "path"
        required: true
        type: "string"
      x-amazon-apigateway-integration:
        httpMethod: POST
        type: aws_proxy
        uri:
          Fn::Sub: arn:aws:apigateway:\${AWS::Region}:lambda:path/2015-03-31/functions/${getFunc.functionArn}/invocations
`
        })
```

### Verbose Log
```
LoyaltyStack: creating CloudFormation changeset...
Initiated creation of changeset: arn:aws:cloudformation:us-east-1:272361391940:changeSet/CDK-330d5792-4a2e-479b-bada-16241591d8c6/57b3f48c-9e7e-46b9-87b6-5e5653706363; waiting for it to finish creating...
Waiting for changeset CDK-330d5792-4a2e-479b-bada-16241591d8c6 on stack LoyaltyStack to finish creating...
Changeset CDK-330d5792-4a2e-479b-bada-16241591d8c6 on stack LoyaltyStack is still creating

 ❌  LoyaltyStack failed: Error: Failed to create ChangeSet CDK-330d5792-4a2e-479b-bada-16241591d8c6 on LoyaltyStack: FAILED, Transform AWS::Serverless-2016-10-31 failed with: Invalid Serverless Application Specification document. Number of errors found: 1. Resource with id [LoyaltyApi] is invalid. Unable to add Auth configuration because 'DefinitionBody' does not contain a valid Swagger
    at /usr/local/lib/node_modules/aws-cdk/lib/api/util/cloudformation.ts:115:11
    at processTicksAndRejections (internal/process/task_queues.js:82:5)
    at waitFor (/usr/local/lib/node_modules/aws-cdk/lib/api/util/cloudformation.ts:76:20)
    at Object.waitForChangeSet (/usr/local/lib/node_modules/aws-cdk/lib/api/util/cloudformation.ts:101:15)
    at Object.deployStack (/usr/local/lib/node_modules/aws-cdk/lib/api/deploy-stack.ts:85:32)
    at CdkToolkit.deploy (/usr/local/lib/node_modules/aws-cdk/lib/cdk-toolkit.ts:143:24)
    at main (/usr/local/lib/node_modules/aws-cdk/bin/cdk.ts:193:16)
    at initCommandLine (/usr/local/lib/node_modules/aws-cdk/bin/cdk.ts:148:9)
Failed to create ChangeSet CDK-330d5792-4a2e-479b-bada-16241591d8c6 on LoyaltyStack: FAILED, Transform AWS::Serverless-2016-10-31 failed with: Invalid Serverless Application Specification document. Number of errors found: 1. Resource with id [LoyaltyApi] is invalid. Unable to add Auth configuration because 'DefinitionBody' does not contain a valid Swagger
Error: Failed to create ChangeSet CDK-330d5792-4a2e-479b-bada-16241591d8c6 on LoyaltyStack: FAILED, Transform AWS::Serverless-2016-10-31 failed with: Invalid Serverless Application Specification document. Number of errors found: 1. Resource with id [LoyaltyApi] is invalid. Unable to add Auth configuration because 'DefinitionBody' does not contain a valid Swagger
    at /usr/local/lib/node_modules/aws-cdk/lib/api/util/cloudformation.ts:115:11
    at processTicksAndRejections (internal/process/task_queues.js:82:5)
    at waitFor (/usr/local/lib/node_modules/aws-cdk/lib/api/util/cloudformation.ts:76:20)
    at Object.waitForChangeSet (/usr/local/lib/node_modules/aws-cdk/lib/api/util/cloudformation.ts:101:15)
    at Object.deployStack (/usr/local/lib/node_modules/aws-cdk/lib/api/deploy-stack.ts:85:32)
    at CdkToolkit.deploy (/usr/local/lib/node_modules/aws-cdk/lib/cdk-toolkit.ts:143:24)
    at main (/usr/local/lib/node_modules/aws-cdk/bin/cdk.ts:193:16)
    at initCommandLine (/usr/local/lib/node_modules/aws-cdk/bin/cdk.ts:148:9)

```

### Environment

  - **CDK CLI Version:** 1.6.1 (build a09203a)
  - **Module Version:** aws-sam
  - **OS:** OSX Mojave
  - **Language:** TypeScript

**Comment by rhboyd** [comment]
Nevermind. I made a copy/paste error that was buried in the json. I got it to work now.
