### ISSUE TITLE
Can not generate Cognito UserPoolUser template. Could not infer JSII type for .NET type 'JArray'.

### ISSUE THREAD

**Issue by andryrochev** [aws/aws-cdk#3903]
### What is the problem?
CDK can not generate cloudFormation template (`cdk synth`) for Amazon.CDK.AWS.Cognito.CfnUserPoolUser (C#).

### Reproduction Steps
Do this command in powershell on windows host
```
mkdir test
cd test
npm install cdk
mkdir deploy
cd deploy
npx cdk init --language csharp --app deploy
cd deploy\src\Deploy
dotnet add package Amazon.CDK.AWS.Cognito --version 1.6.1-devpreview

@'
using Amazon.CDK;
using Amazon.CDK.AWS.Cognito;

namespace Deploy
{
    public class DeployStack : Stack
    {
        public DeployStack(Construct parent, string id, IStackProps props) : base(parent, id, props)
        {
            var userPool = new UserPool(this, "UserPool", new UserPoolProps() {});

            var userPoolUserCfn = new CfnUserPoolUser(this, "Admin", new CfnUserPoolUserProps() {
                UserPoolId = userPool.UserPoolId,
                Username = "Admin",
                DesiredDeliveryMediums = new [] {"EMAIL"},
				UserAttributes = new CfnUserPoolUser.AttributeTypeProperty[] {
                    new CfnUserPoolUser.AttributeTypeProperty () {
                        Name = "email",
                        Value = "fake@mail.fake"
                    },
                    new CfnUserPoolUser.AttributeTypeProperty () {
                        Name = "email_verified",
                        Value = "True"
                    } 
                }
            });
        }
    }
}

'@ > .\DeployStack.cs
cd ..\..
dotnet build src
npx cdk synth
```
You will see the problem:
### Verbose Log
```
Unhandled Exception: Amazon.JSII.Runtime.JsiiException: Amazon.JSII.Runtime.JsiiException: Resolution error: System.ArgumentException: Could not infer JSII type for .NET type 'JArray'
Parameter name: type
   at Amazon.JSII.Runtime.Services.Converters.FrameworkToJsiiConverter.InferType(IReferenceMap referenceMap, Type type)
   at Amazon.JSII.Runtime.Services.Converters.ValueConverter.ConvertAny(IReferenceMap referenceMap, Object value)
   at Amazon.JSII.Runtime.Services.Converters.ValueConverter.TryConvertPrimitive(IReferenceMap referenceMap, Object value, Boolean isOptional, PrimitiveType primitiveType, Object& result)
   at Amazon.JSII.Runtime.Services.Converters.ValueConverter.TryConvert(IOptionalValue optionalValue, IReferenceMap referenceMap, Object value, Object& result)
   at Amazon.JSII.Runtime.Services.Converters.FrameworkToJsiiConverter.TryConvertMap(IReferenceMap referenceMap, TypeReference elementType, Object value, Object& result)
   at Amazon.JSII.Runtime.Services.Converters.ValueConverter.TryConvert(IOptionalValue optionalValue, IReferenceMap referenceMap, Object value, Object& result)
   at Amazon.JSII.Runtime.Deputy.DeputyBase.<>c__DisplayClass20_0.<ConvertArguments>b__0(Parameter parameter, Object frameworkArgument)
   at System.Linq.Enumerable.ZipIterator[TFirst,TSecond,TResult](IEnumerable`1 first, IEnumerable`1 second, Func`3 resultSelector)+MoveNext()
   at System.Collections.Generic.LargeArrayBuilder`1.AddRange(IEnumerable`1 items)
   at System.Collections.Generic.EnumerableHelpers.ToArray[T](IEnumerable`1 source)
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at Amazon.JSII.Runtime.Deputy.DeputyBase.<InvokeMethodCore>g__GetResult|18_0[T](<>c__DisplayClass18_0`1& )
   at Amazon.JSII.Runtime.Deputy.DeputyBase.InvokeMethodCore[T](JsiiMethodAttribute methodAttribute, Object[] arguments, Func`3 beginFunc, Func`3 invokeFunc)
   at Amazon.JSII.Runtime.Deputy.DeputyBase.InvokeInstanceMethod[T](Object[] arguments, String methodName).
Object creation stack:
  at new Intrinsic (C:\Users\Andry\AppData\Local\Temp\jsii-kernel-Mkk6gw\node_modules\@aws-cdk\core\lib\private\intrinsic.js:20:44)
  at new PostResolveToken (C:\Users\Andry\AppData\Local\Temp\jsii-kernel-Mkk6gw\node_modules\@aws-cdk\core\lib\util.js:72:9)
  at CfnUserPoolUser._toCloudFormation (C:\Users\Andry\AppData\Local\Temp\jsii-kernel-Mkk6gw\node_modules\@aws-cdk\core\lib\cfn-resource.js:167:39)
  at node.addReference.resolve_1.findTokens (C:\Users\Andry\AppData\Local\Temp\jsii-kernel-Mkk6gw\node_modules\@aws-cdk\core\lib\cfn-element.js:84:77)
  at Object.findTokens (C:\Users\Andry\AppData\Local\Temp\jsii-kernel-Mkk6gw\node_modules\@aws-cdk\core\lib\private\resolve.js:126:13)
  at CfnUserPoolUser.prepare (C:\Users\Andry\AppData\Local\Temp\jsii-kernel-Mkk6gw\node_modules\@aws-cdk\core\lib\cfn-element.js:84:49)
  at _wrapSandboxCode (C:\Users\Andry\AppData\Local\Temp\xi152g5a.zgo\jsii-runtime.js:6498:51)
  at Kernel._wrapSandboxCode (C:\Users\Andry\AppData\Local\Temp\xi152g5a.zgo\jsii-runtime.js:7131:20)
  at ret._ensureSync (C:\Users\Andry\AppData\Local\Temp\xi152g5a.zgo\jsii-runtime.js:6498:25)
  at Kernel._ensureSync (C:\Users\Andry\AppData\Local\Temp\xi152g5a.zgo\jsii-runtime.js:7102:20)
  at Kernel.invoke (C:\Users\Andry\AppData\Local\Temp\xi152g5a.zgo\jsii-runtime.js:6497:26)
  at KernelHost.processRequest (C:\Users\Andry\AppData\Local\Temp\xi152g5a.zgo\jsii-runtime.js:6191:28)
  at completeCallback (C:\Users\Andry\AppData\Local\Temp\xi152g5a.zgo\jsii-runtime.js:6164:25)
  at KernelHost.callbackHandler (C:\Users\Andry\AppData\Local\Temp\xi152g5a.zgo\jsii-runtime.js:6145:16)
  at KernelHost.kernel.jsii_kernel_1.Kernel.cb [as callbackHandler] (C:\Users\Andry\AppData\Local\Temp\xi152g5a.zgo\jsii-runtime.js:6129:59)
  at CfnUserPoolUser.value (C:\Users\Andry\AppData\Local\Temp\xi152g5a.zgo\jsii-runtime.js:6848:41)
  at Function.prepare (C:\Users\Andry\AppData\Local\Temp\jsii-kernel-Mkk6gw\node_modules\@aws-cdk\core\lib\construct.js:89:27)
  at Function.synth (C:\Users\Andry\AppData\Local\Temp\jsii-kernel-Mkk6gw\node_modules\@aws-cdk\core\lib\construct.js:52:14)
  at App.synth (C:\Users\Andry\AppData\Local\Temp\jsii-kernel-Mkk6gw\node_modules\@aws-cdk\core\lib\app.js:67:52)
  at _wrapSandboxCode (C:\Users\Andry\AppData\Local\Temp\xi152g5a.zgo\jsii-runtime.js:6498:51)
  at Kernel._wrapSandboxCode (C:\Users\Andry\AppData\Local\Temp\xi152g5a.zgo\jsii-runtime.js:7131:20)
  at ret._ensureSync (C:\Users\Andry\AppData\Local\Temp\xi152g5a.zgo\jsii-runtime.js:6498:25)
  at Kernel._ensureSync (C:\Users\Andry\AppData\Local\Temp\xi152g5a.zgo\jsii-runtime.js:7102:20)
  at Kernel.invoke (C:\Users\Andry\AppData\Local\Temp\xi152g5a.zgo\jsii-runtime.js:6497:26)
  at KernelHost.processRequest (C:\Users\Andry\AppData\Local\Temp\xi152g5a.zgo\jsii-runtime.js:6191:28)
  at KernelHost.run (C:\Users\Andry\AppData\Local\Temp\xi152g5a.zgo\jsii-runtime.js:6137:14)
  at processRequest (C:\Users\Andry\AppData\Local\Temp\xi152g5a.zgo\jsii-runtime.js:6137:45)
  at KernelHost.processRequest (C:\Users\Andry\AppData\Local\Temp\xi152g5a.zgo\jsii-runtime.js:6233:16)
  at KernelHost.run (C:\Users\Andry\AppData\Local\Temp\xi152g5a.zgo\jsii-runtime.js:6137:14)
  at processRequest (C:\Users\Andry\AppData\Local\Temp\xi152g5a.zgo\jsii-runtime.js:6137:45)
  at KernelHost.processRequest (C:\Users\Andry\AppData\Local\Temp\xi152g5a.zgo\jsii-runtime.js:6233:16)
  at KernelHost.run (C:\Users\Andry\AppData\Local\Temp\xi152g5a.zgo\jsii-runtime.js:6137:14)
  at processRequest (C:\Users\Andry\AppData\Local\Temp\xi152g5a.zgo\jsii-runtime.js:6137:45)
  at KernelHost.processRequest (C:\Users\Andry\AppData\Local\Temp\xi152g5a.zgo\jsii-runtime.js:6233:16)
  at KernelHost.run (C:\Users\Andry\AppData\Local\Temp\xi152g5a.zgo\jsii-runtime.js:6137:14)
  at processRequest (C:\Users\Andry\AppData\Local\Temp\xi152g5a.zgo\jsii-runtime.js:6137:45)
  at KernelHost.processRequest (C:\Users\Andry\AppData\Local\Temp\xi152g5a.zgo\jsii-runtime.js:6233:16)
  at KernelHost.run (C:\Users\Andry\AppData\Local\Temp\xi152g5a.zgo\jsii-runtime.js:6137:14)
  at processRequest (C:\Users\Andry\AppData\Local\Temp\xi152g5a.zgo\jsii-runtime.js:6137:45)
  at promise.then.val (C:\Users\Andry\AppData\Local\Temp\xi152g5a.zgo\jsii-runtime.js:6218:21)
   at Amazon.JSII.Runtime.Services.Client.TryDeserialize[TResponse](String responseJson)
   at Amazon.JSII.Runtime.Services.Client.ReceiveResponse[TResponse]()
   at Amazon.JSII.Runtime.Services.Client.TryDeserialize[TResponse](String responseJson)
   at Amazon.JSII.Runtime.Services.Client.ReceiveResponse[TResponse]()
   at Amazon.JSII.Runtime.Deputy.DeputyBase.<InvokeMethodCore>g__GetResult|18_0[T](<>c__DisplayClass18_0`1& )
   at Amazon.JSII.Runtime.Deputy.DeputyBase.InvokeMethodCore[T](JsiiMethodAttribute methodAttribute, Object[] arguments, Func`3 beginFunc, Func`3 invokeFunc)
   at Amazon.JSII.Runtime.Deputy.DeputyBase.InvokeInstanceMethod[T](Object[] arguments, String methodName)
   at Amazon.CDK.CfnElement.Prepare()
   at Amazon.JSII.Runtime.Services.Client.TryDeserialize[TResponse](String responseJson)
   at Amazon.JSII.Runtime.Services.Client.ReceiveResponse[TResponse]()
   at Amazon.JSII.Runtime.Services.Client.TryDeserialize[TResponse](String responseJson)
   at Amazon.JSII.Runtime.Services.Client.ReceiveResponse[TResponse]()
   at Amazon.JSII.Runtime.Deputy.DeputyBase.<InvokeMethodCore>g__GetResult|18_0[T](<>c__DisplayClass18_0`1& )
   at Amazon.JSII.Runtime.Deputy.DeputyBase.InvokeMethodCore[T](JsiiMethodAttribute methodAttribute, Object[] arguments, Func`3 beginFunc, Func`3 invokeFunc)
   at Amazon.JSII.Runtime.Deputy.DeputyBase.InvokeInstanceMethod[T](Object[] arguments, String methodName)
   at Deploy.Program.Main(String[] args) in ....\test\deploy\src\Deploy\Program.cs:line 14
Subprocess exited with error 3762504530
```

### Environment

  - **CDK CLI Version: 1.6.1 (build a09203a)** 
  - **Module Version:  1.6.1-devpreview** 
  - **OS: Windows 10** 
  - **Language: csharp** 

### Other information
Pay attention on stack trace, problem in 'UserPoolUser' entity CfnUserPoolUser._toCloudFormation

**Comment by RomainMuller** [comment]
Hey @andryrochev,

First off - I'd like to thank you for the detailed bug report including a super straight forward reproduction. This is much appreciated!

Now - I have tried reproducing the issue with CDK 1.9.0, and it appears that the bug you were facing has indeed been fixed as part of the swath of bug fixes we've brought to the .NET runtime and code generation as part of the last release.

I'll be resolving this issue now, as all you'd have to do in order to fix your app is to upgrade to the latest version of the CDK. Please do not hesitate to re-open if the issue still persists for you on the latest CDK.

Regards,
Romain.
