### ISSUE TITLE
Calling toAlarmConfig on IMetric object causes JsiiException

### ISSUE THREAD

**Issue by era878** [aws/aws-cdk#3927]
On the latest CDK v1.6.1, the following code snippet in Java causes a JsiiException to be thrown when in previous version this has worked fine:

```java
final MetricProps props = MetricProps.builder()
        .metricName("METRIC_NAME")
        .namespace("NAMESPACE")
        .statistic("Average")
        .period(Duration.seconds(300))
        .build();
final IMetric metric = new Metric(props);
metric.toAlarmConfig();
```

The actual output is:
```
Exception in thread "main" software.amazon.jsii.JsiiException: Unable to instantiate a new object for FQN
 @aws-cdk/aws-cloudwatch.MetricAlarmConfig: null
    at software.amazon.jsii.JsiiEngine.createNativeProxy(JsiiEngine.java:248)
    at software.amazon.jsii.JsiiEngine.nativeFromObjRef(JsiiEngine.java:133)
    at software.amazon.jsii.JsiiObjectMapper$JsiiDeserializer.deserialize(JsiiObjectMapper.java:140)
    at com.fasterxml.jackson.databind.ObjectMapper._readValue(ObjectMapper.java:3786)
    at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2115)
    at com.fasterxml.jackson.databind.ObjectMapper.treeToValue(ObjectMapper.java:2612)
    at software.amazon.jsii.JsiiObjectMapper.treeToValue(JsiiObjectMapper.java:55)
    at software.amazon.jsii.JsiiObject.jsiiCall(JsiiObject.java:60)
    at software.amazon.awscdk.services.cloudwatch.Metric.toAlarmConfig(Metric.java:64)
    at com.amazonaws.ec2nitrocanary.MyTest.main(MyTest.java:19)
Caused by: java.lang.reflect.InvocationTargetException
    at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
    at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
    at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
    at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
    at software.amazon.jsii.JsiiEngine.createNativeProxy(JsiiEngine.java:238)
    ... 9 more
Caused by: java.lang.IllegalArgumentException: No enum constant software.amazon.awscdk.services.cloudwatch
 .Statistic.undefined
    at java.lang.Enum.valueOf(Enum.java:238)
    at software.amazon.jsii.JsiiEngine.findEnumValue(JsiiEngine.java:272)
    at software.amazon.jsii.JsiiObjectMapper$JsiiDeserializer.deserialize(JsiiObjectMapper.java:137)
    at com.fasterxml.jackson.databind.ObjectMapper._readValue(ObjectMapper.java:3786)
    at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2115)
    at com.fasterxml.jackson.databind.ObjectMapper.treeToValue(ObjectMapper.java:2612)
    at software.amazon.jsii.JsiiObjectMapper.treeToValue(JsiiObjectMapper.java:55)
    at software.amazon.jsii.JsiiObject.jsiiGet(JsiiObject.java:111)
    at software.amazon.awscdk.services.cloudwatch.MetricAlarmConfig$Jsii$Proxy.<init>(MetricAlarmConfig
    .java:186)
    ... 14 more
```

The expected output is a valid AlarmConfig object.

**Comment by rix0rrr** [comment]
I believe this has been fixed in https://github.com/aws/jsii/pull/754.

A recent CDK version should have the fix.
