### ISSUE TITLE
Support relative paths to plugins

### ISSUE THREAD

**Issue by jeshan** [aws/aws-cdk#4009]
### What is the problem?
I'm looking to load a plugin on cdk deploy as follows.

cdk.json:
```json
{
    "app": "node bin/app.js",
    "plugin": ["/full/path/to/my-plugin.js"]
}

```
This way, cdk works well. However, it's less portable since in CI the paths may not be the same.
A solution would be supporting relative paths. Since json does not support relative paths (I think), then declaring such plugins in json is not possible.

### Verbose Log
This is what I'm getting when trying to set relative paths in cdk.json:
```
Unable to resolve plugin lib/cdk-profile-plugin.js: Error: Cannot find module 'lib/my-plugin.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:580:15)
    at Function.resolve (internal/modules/cjs/helpers.js:30:19)
    at tryResolve (/home/jeshan/.nvm/versions/node/v10.13.0/lib/node_modules/aws-cdk/bin/cdk.ts:130:24)
    at loadPlugins (/home/jeshan/.nvm/versions/node/v10.13.0/lib/node_modules/aws-cdk/bin/cdk.ts:120:26)
    at initCommandLine (/home/jeshan/.nvm/versions/node/v10.13.0/lib/node_modules/aws-cdk/bin/cdk.ts:138:3)
Unable to resolve plug-in: lib/my-plugin.js
```
### Environment

  - **CDK CLI Version:** 1.7.0
  - **Module Version:** 
  - **OS:** Ubuntu
  - **Language:** JavaScript

### Other information

As a workaround, I'm doing this:

```bash
cdk --plugin `pwd`/lib/my-plugin deploy my-stack
```

Am I correct in assuming that relative paths is not possible in cdk.json at the moment?

**Comment by nmussy** [comment]
Have you tried prefixing the relative path with `./`, i.e. `./lib/my-plugin.js`? 

The plugins are `require`d, and will be treated as `node_modules`/global module if they are not prefixed with a `./` ([see Node.js doc](https://nodejs.org/api/modules.html#modules_require_id))
https://github.com/aws/aws-cdk/blob/c8bb50e80350fc1418554ae061d3d6b39efac82b/packages/aws-cdk/lib/plugin.ts#L66

**Comment by jeshan** [comment]
Relative paths like that don't work; neither in cdk.json nor the CLI.

**Comment by nmussy** [comment]
Yeah, that actually makes sense, because the file is imported relative to the `require` (`node_modules/aws-cdk/lib/`), not your current working directory, my abd.

The easiest thing I can see from a user point-of-view would be to replace `./` with `cwd()`, which is what you've been doing. Something like:

```ts
 const plugin = require(moduleSpec.replace(/^.([/\\])/, `${require('process').cwd()}$1`)); 
```

Does anyone have a better idea?

**Comment by konstantinj** [comment]
Just struggled with the same issue. I would assume cwd to be where I execute cdk.

**Comment by tiararodney** [comment]
This is tricky... As far as I can see, the `plugin` property is currently not implemented for [`src/awscdk/cdk-config.ts::CdkConfig`](https://github.com/projen/projen/blob/main/src/awscdk/cdk-config.ts#L77).

I discerned two impediments for a feature implementation:

1. There is no definitive way of discerning CDK plugin npm packages from other npm packages, as their only attributes are package names prefixed with `cdk-` and suffixed with `-plugin`.
2. If one was to try and fish the plugins of `dependencies`, and/or `peerDependencies` fields of the future package manifest, this can only be achieved through observing the `options` passed to [`src/awscdk/awscdk-app-ts::AwsCdkTypeScriptApp`](https://github.com/projen/projen/blob/main/src/awscdk/awscdk-app-ts.ts#L43) during construction. Package dependencies are only resolved after the `cdk.json` has been rendered. In addition, dependency resolution is private to [`src/javascript/node-package.ts::NodePackage`](https://github.com/projen/projen/blob/main/src/javascript/node-package.ts#L315).

Fishing for CDK plugin npm packages could be done similar to this (within the [`src/awscdk/awscdk-app-ts::AwsCdkTypeScriptApp`](https://github.com/projen/projen/blob/main/src/awscdk/awscdk-app-ts.ts#L43) constructor):

```typescript
const cdkPlugins = ( options.deps ?? [] ).reduce( ( plugins:string[], dep:string ) => { 

    if ( dep.startsWith( 'cdk-' ) && dep.endsWith( '-plugin' ) ) {

        plugins.push( dep );
    }

    return plugins;
}, [] );
```

The resulting `cdkPlugins` can then be passed onto the `this.cdkConfig` constructor. However, `(options.deps ?? [])` is pretty fugly. This will result in a lackluster implementation 💩

**My proposition for an implementation:**

1. Extend the [`src/awscdk/awscdk-deps.ts::AwsCdkDepsCommonOptions`](https://github.com/projen/projen/blob/main/src/awscdk/awscdk-deps.ts#L9) interface, to include `cdkPlugins?:string[]`.
2. Optionally, plugin names may be matched against the `cdk-` prefix and `-plugin` suffix.
2. Make the [`src/awscdk/awscdk-app-ts::AwsCdkTypeScriptApp`](https://github.com/projen/projen/blob/main/src/awscdk/awscdk-app-ts.ts#L43) constructor add all CDK plugins as additional dependencies through `this.addDevDeps`.
3. Make the [`src/awscdk/cdk-config.ts::CdkConfig`](https://github.com/projen/projen/blob/main/src/awscdk/cdk-config.ts#L77) constructor add a `plugin` field to the [`new JsonFile()`](https://github.com/projen/projen/blob/main/src/awscdk/cdk-config.ts#L102)

**Comment by rix0rrr** [comment]
A plugin gets loaded using `require()`. So you can put it anywhere so that a Node.js `require('my-plugin')` would find it: https://nodejs.org/api/modules.html#loading-from-node_modules-folders
