### ISSUE TITLE
StepFunctions - can't output a task's state JSON

### ISSUE THREAD

**Issue by plumdog** [aws/aws-cdk#4038]
### What is the problem?

The step functions module in the CDK has lots of useful things for generating the JSON for step functions tasks. I want to be able to write some CDK that creates my underlying tasks (eg, fargate tasks) and then outputs the step functions task's JSON that wraps the underlying task. This is because the underlying tasks don't have anything to specify how the hook into the step functions state machine. But there is no AWS resource to encapsulate this, just some JSON that goes into the state machine definition. In my particular case, I want to generate the state machine JSON for some tasks that I can dynamically clip together to make state machines dynamically.

So I'd like my CDK app to create the fargate tasks, and output the step functions task JSON. But when I try to output this (or write it to a file on S3) I get an error (and this error happens at synth-time):

```
Error: Cannot add elements to list token
```
(see below for more verbose output)

### Reproduction Steps

```javascript
const cdk = require('@aws-cdk/core');
const ec2 = require('@aws-cdk/aws-ec2');
const ecs = require('@aws-cdk/aws-ecs');
const sfn = require('@aws-cdk/aws-stepfunctions')
const sfnTasks = require('@aws-cdk/aws-stepfunctions-tasks')

class CdkTestStack extends cdk.Stack {
  constructor(scope, id, props) {
    super(scope, id, props);

    const vpc = new ec2.Vpc(this, 'TestVPC', {
      maxAzs: 1,
    });
    const cluster = new ecs.Cluster(this, 'TestCluster', {
      vpc,
    });

    const testTaskDefinition = new ecs.FargateTaskDefinition(this, 'TestTaskDef', {
      cluster,
      memoryLimitMiB: 512,
      cpu: 256,
    })
    testTaskDefinition.addContainer('TestContainer', {
      image: ecs.ContainerImage.fromRegistry('ubuntu'),
      logging: new ecs.AwsLogDriver({ streamPrefix: this.node.id }),
    });

    const testTask = new sfn.Task(this, 'TestTask', {
      task: new sfnTasks.RunEcsFargateTask({
        cluster,
        taskDefinition: testTaskDefinition,
        containerOverrides: [{
          containerName: 'TestContainer',
          environment: [{
            name: 'TASK_TOKEN',
            value: sfn.Context.taskToken,
          }],
        }],
      }),
    });

    // This line errors
    new cdk.CfnOutput(this, 'TaskJson', {value: JSON.stringify(testTask.toStateJson())});
    // But if I remove the above line, this line works fine
    new cdk.CfnOutput(this, 'TaskDefArn', {value: JSON.stringify({taskDefArn: testTaskDefinition.taskDefinitionArn})});
  }
}

module.exports = { CdkTestStack }
```

### Verbose Log

```
$ npm run cdk -- synth

> cdk-test@0.1.0 cdk /home/me/cdk-test
> cdk "synth"


/home/me/cdk-test/node_modules/@aws-cdk/core/lib/resolvable.ts:161
      throw new Error(`Cannot add elements to list token, got: ${xs}`);
            ^
Error: Cannot add elements to list token, got: {"End":true,"Parameters":{"Cluster":",[object Object],","TaskDefinition":",[object Object],","NetworkConfiguration":{"AwsvpcConfiguration":{"Subnets":[",[object Object],"],"SecurityGroups":["#{Token[TOKEN.310]}"]}},"Overrides":{"ContainerOverrides":[{"Name":"TestContainer","Environment":[{"Name":"TASK_TOKEN","Value.$":"$$.Task.Token"}]}]},"LaunchType":"FARGATE"},"Type":"Task","Resource":"arn:aws:states:::ecs:runTask"}
    at DefaultTokenResolver.resolveList (/home/me/cdk-test/node_modules/@aws-cdk/core/lib/resolvable.ts:161:13)
    at resolve (/home/me/cdk-test/node_modules/@aws-cdk/core/lib/private/resolve.ts:117:31)
    at Object.resolve (/home/me/cdk-test/node_modules/@aws-cdk/core/lib/private/resolve.ts:49:32)
    at obj.map (/home/me/cdk-test/node_modules/@aws-cdk/core/lib/private/resolve.ts:121:45)
    at Array.map (<anonymous>)
    at resolve (/home/me/cdk-test/node_modules/@aws-cdk/core/lib/private/resolve.ts:121:8)
    at Object.resolve (/home/me/cdk-test/node_modules/@aws-cdk/core/lib/private/resolve.ts:49:32)
    at resolve (/home/me/cdk-test/node_modules/@aws-cdk/core/lib/private/resolve.ts:154:39)
    at Object.resolve (/home/me/cdk-test/node_modules/@aws-cdk/core/lib/private/resolve.ts:49:32)
    at resolve (/home/me/cdk-test/node_modules/@aws-cdk/core/lib/private/resolve.ts:154:39)
```

### Environment

  - **CDK CLI Version:** 1.8.0
  - **Module Version:** 1.8.0
  - **OS:** Arch
  - **Language:** all (I assume, though I'm using Javascript)

### Other information

This is something in `resolvable.ts` deciding that it should error https://github.com/aws/aws-cdk/blob/0fc2c3bb622d81808139633c1f17aef13efdfbe9/packages/%40aws-cdk/core/lib/resolvable.ts, but I can't really work out why it is deciding to error - the comment says
> Must be a singleton list token, because concatenation is not allowed.

but I don't really have enough context to understand that. That message (and that code) was added in https://github.com/aws/aws-cdk/commit/cd7947ccd962e859710c7bf3d1226dee75f3e835.

Digging a bit more, it seems that it is something to do with the subnets, which are indeed an oddity in the error above:
```
"AwsvpcConfiguration":{
  "Subnets":[",[object Object],"],
  "SecurityGroups":["#{Token[TOKEN.310]}"]
}
```
I would have expected the subnets and the security groups to be treated similarly.

Those values come from here https://github.com/aws/aws-cdk/blob/v1.8.0/packages/%40aws-cdk/aws-stepfunctions-tasks/lib/run-ecs-task-base.ts#L135-L136 where one is "Lazy" and one isn't. Might that be why? I'm pretty lost now though.

**Comment by plumdog** [comment]
Ah, I think `Stack.of(this).toJsonString` is actually my answer:
https://github.com/aws/aws-cdk/blob/ac54e140303a5678ec3108fa28dda9cd00230c29/packages/%40aws-cdk/core/lib/stack.ts#L224-L229

**Comment by plumdog** [comment]
Indeed:
```javascript
JSON.stringify(testTask.toStateJson())  // bad, breaky for some values (was a hack I stumbled upon)
cdk.Stack.of(this).toJsonString(testTask.toStateJson())  // good, works (actually has a comment saying it does the thing I want)
```
