### ISSUE TITLE
Can't get a CfnInstance with instance.getInstance()

### ISSUE THREAD

**Issue by johnjelinek** [aws/aws-cdk#4080]
### What is the problem?

Can't get a `CfnInstance` with `instance.getInstance()`. I was hoping to get a `CfnInstance` to see if I can pass it in to `Targets` of `CfnMaintenanceWindowTargetProps`.

### Reproduction Steps
```
(let [app (new App)
      stack (new Stack app "stack" stack-props)
      vpc (new Vpc stack "vpc")
      instance (new Instance stack "server" instance-props)
      window (new CfnMaintenanceWindow stack "window" maintenance-window-props)
      target (new CfnMaintenanceWindowTarget stack "target" maintenance-window-target-props)]
  (.getInstance instance)
  (.synth app))
```

### Verbose Log

>Execution error (IllegalArgumentException) at com.fasterxml.jackson.databind.introspect.POJOPropertyBuilder/getSetter (POJOPropertyBuilder.java:497).
Conflicting setter definitions for property "networkInterfaces": software.amazon.awscdk.services.ec2.CfnInstance#setNetworkInterfaces(1 params) vs software.amazon.awscdk.services.ec2.CfnInstance#setNetworkInterfaces(1 params)
class software.amazon.jsii.JsiiException

or

>Execution error (IllegalArgumentException) at com.fasterxml.jackson.databind.introspect.POJOPropertyBuilder/getSetter (POJOPropertyBuilder.java:497).
Conflicting setter definitions for property "blockDeviceMappings": software.amazon.awscdk.services.ec2.CfnInstance#setBlockDeviceMappings(1 params) vs software.amazon.awscdk.services.ec2.CfnInstance#setBlockDeviceMappings(1 params)

### Environment

  - **CDK CLI Version:** 1.8.0 (build 5244f97)
  - **Module Version:** 1.8.0.DEVPREVIEW
  - **OS:** MacOS Mojave
  - **Language:** Java

### Other information
|JsiiObjectMapper.java: | 57 | software.amazon.jsii.JsiiObjectMapper/treeToValue
|-- | -- | --
|JsiiObject.java: | 111 | software.amazon.jsii.JsiiObject/jsiiGet
|Instance.java: | 66 | software.amazon.awscdk.services.ec2.Instance/getInstance
|RestFn.java: | 1523 | clojure.lang.RestFn/invoke
|AFn.java: | 22 | clojure.lang.AFn/run
|AFn.java: | 22 | clojure.lang.AFn/run
|Thread.java: | 748 | java.lang.Thread/run

**Comment by johnjelinek** [comment]
If I pass the `instance` as a list directly to `Targets`, I get this stack trace:
```
Execution error (JsiiException) at software.amazon.jsii.JsiiRuntime/processErrorResponse (JsiiRuntime.java:112).
Value did not match any type in union: Expected object reference, got [null],Value did not match any type in union: Got 'undefined' for non-optional instance of {"type":{"fqn":"@aws-cdk/core.IResolvable"}},Got 'undefined' for non-optional instance of {"type":{"fqn":"@aws-cdk/aws-ssm.CfnMaintenanceWindowTarget.TargetsProperty"}}
Error: Value did not match any type in union: Expected object reference, got [null],Value did not match any type in union: Got 'undefined' for non-optional instance of {"type":{"fqn":"@aws-cdk/core.IResolvable"}},Got 'undefined' for non-optional instance of {"type":{"fqn":"@aws-cdk/aws-ssm.CfnMaintenanceWindowTarget.TargetsProperty"}}
    at Kernel._toSandbox (/private/var/folders/gv/kjbh254n1sd02z4htvkgrfsc0000gn/T/jsii-java-runtime5564836774650058847/jsii-runtime.js:7041:15)
    at mapValues (/private/var/folders/gv/kjbh254n1sd02z4htvkgrfsc0000gn/T/jsii-java-runtime5564836
774650058847/jsii-runtime.js:12223:29)
    at mapValues (/private/var/folders/gv/kjbh254n1sd02z4htvkgrfsc0000gn/T/jsii-java-runtime5564836774650058847/jsii-runtime.js:12452:27)
    at Object.deserialize (/private/var/folders/gv/kjbh254n1sd02z4htvkgrfsc0000gn/T/jsii-java-runtime5564836774650058847/jsii-runtime.js:12219:20)
    at Kernel._toSandbox (/private/var/folders/gv/kjbh254n1sd02z4htvkgrfsc0000gn/T/jsii-java-runtime5564836774650058847/jsii-runtime.js:7031:61)
    at xs.map (/private/var/folders/gv/kjbh254n1sd02z4htvkgrfsc0000gn/T/jsii-java-runtime5564836774650058847/jsii-runtime.js:7084:33)
    at Array.map ()
    at Kernel._boxUnboxParameters (/private/var/folders/gv/kjbh254n1sd02z4htvkgrfsc0000gn/T/jsii-java-runtime5564836774650058847/jsii-runtime.js:7084:19)
    at Kernel._toSandboxValues (/private/var/folders/gv/kjbh254n1sd02z4htvkgrfsc0000gn/T/jsii-java-runtime5564836774650058847/jsii-runtime.js:7069:21)
    at Kernel._wrapSandboxCode (/private/var/folders/gv/kjbh254n1sd02z4htvkgrfsc0000g
n/T/jsii-java-runtime5564836774650058847/jsii-runtime.js:7134:19)
    at Kernel._create (/private/var/folders/gv/kjbh254n1sd02z4htvkgrfsc0000gn/T/jsii-java-runtime5564836774650058847/jsii-runtime.js:6666:26)
    at Kernel.create (/private/var/folders/gv/kjbh254n1sd02z4htvkgrfsc0000gn/T/jsii-java-runtime5564836774650058847/jsii-runtime.js:6419:21)
    at KernelHost.processRequest (/private/var/folders/gv/kjbh254n1sd02z4htvkgrfsc0000gn/T/jsii-java-runtime5564836774650058847/jsii-runtime.js:6191:28)
    at KernelHost.run (/private/var/folders/gv/kjbh254n1sd02z4htvkgrfsc0000gn/T/jsii-java-runtime5564836774650058847/jsii-runtime.js:6137:14)
    at processRequest (/private/var/folders/gv/kjbh254n1sd02z4htvkgrfsc0000gn/T/jsii-java-runtime5564836774650058847/jsii-runtime.js:6137:45)
    at KernelHost.processRequest (/private/var/folders/gv/kjbh254n1sd02z4htvkgrfsc0000gn/T/jsii-java-runtime5564836774650058847/jsii-runtime.js:6233:16)
    at KernelHost.run (/private/var/folders/gv/kjbh254n1sd02z4htvkgrfsc0000gn/T/jsii-
java-runtime5564836774650058847/jsii-runtime.js:6137:14)
    at processRequest (/private/var/folders/gv/kjbh254n1sd02z4htvkgrfsc0000gn/T/jsii-java-runtime5564836774650058847/jsii-runtime.js:6137:45)
    at KernelHost.processRequest (/private/var/folders/gv/kjbh254n1sd02z4htvkgrfsc0000gn/T/jsii-java-runtime5564836774650058847/jsii-runtime.js:6233:16)
    at KernelHost.run (/private/var/folders/gv/kjbh254n1sd02z4htvkgrfsc0000gn/T/jsii-java-runtime5564836774650058847/jsii-runtime.js:6137:14)
class software.amazon.jsii.JsiiException
```

**Comment by johnjelinek** [comment]
hmm ... I'm starting to think maybe `Instance` isn't all that baked and that I need to be building a `CfnInstance` at this point.

**Comment by jeshan** [comment]
you need to show us what your `instance-props`, `maintenance-window-props` and `maintenance-window-target-props` look like

**Comment by johnjelinek** [comment]
@jeshan: here's the whole kit n' caboodle:
```
(ns cdk.app
  (:import (software.amazon.awscdk.core App
                                        CfnOutput
                                        CfnOutputProps
                                        Environment
                                        Stack
                                        StackProps)
           (software.amazon.awscdk.services.ec2 GenericWindowsImage
                                                Instance
                                                InstanceClass
                                                InstanceProps
                                                InstanceSize
                                                InstanceType
                                                Port
                                                SubnetConfiguration
                                                SubnetSelection
                                                SubnetType
                                                Vpc
                                                VpcProps
                                                WindowsImage
                                                WindowsVersion)
           (software.amazon.awscdk.services.iam ManagedPolicy
                                                ServicePrincipal
                                                Role
                                                RoleProps)
           (software.amazon.awscdk.services.ssm CfnMaintenanceWindow
                                                CfnMaintenanceWindowProps
                                                CfnMaintenanceWindowTarget
                                                CfnMaintenanceWindowTargetProps)))

(def keypair-name "communion")
(def default-cidr "172.16.0.0/16")
(def windows-instance-type
  (InstanceType/of InstanceClass/BURSTABLE3 InstanceSize/LARGE))
(def windows-rdp-port (Port/tcp 3389))

(def latest-windows-ami
  (new WindowsImage WindowsVersion/WINDOWS_SERVER_2019_ENGLISH_FULL_BASE))

(def pinned-windows-ami
  (new GenericWindowsImage {"us-east-2" "ami-017894519635aafd2"}))

(def public-subnet-selection
  (-> (SubnetSelection/builder)
      (.subnetType SubnetType/PUBLIC)
      .build))

(defn instance-props [vpc role]
  (-> (InstanceProps/builder)
      (.instanceType windows-instance-type)
      (.keyName keypair-name)
      (.machineImage pinned-windows-ami)
      (.role role)
      (.vpc vpc)
      (.vpcSubnets public-subnet-selection)
      .build))

(def instance-role-props
  (-> (RoleProps/builder)
      (.assumedBy (new ServicePrincipal "ec2.amazonaws.com"))
      (.managedPolicies [(ManagedPolicy/fromAwsManagedPolicyName
                          "service-role/AmazonEC2RoleforSSM")
                         (ManagedPolicy/fromAwsManagedPolicyName
                          "AmazonSSMFullAccess")])
      .build))

(def stack-props
  (-> (StackProps/builder)
      (.env (-> (Environment/builder)
                (.region "us-east-2")
                .build))
      .build))

(def subnet-configuration
  (-> (SubnetConfiguration/builder)
      (.name "Public")
      (.subnetType SubnetType/PUBLIC)
      .build))

(def vpc-props
  (-> (VpcProps/builder)
      (.cidr default-cidr)
      (.subnetConfiguration [subnet-configuration])
      .build))

(def maintenance-window-props
  (-> (CfnMaintenanceWindowProps/builder)
      (.allowUnassociatedTargets false)
      (.cutoff 2)
      (.schedule "cron(* 17 * * ? *)")
      (.description
       "Maintenance window to allow for patching windows instances")
      (.duration 6)
      (.name "ultratax-windows-maintenance-window")
      .build))

(defn maintenance-window-target-props [instance maintenance-window]
  (-> (CfnMaintenanceWindowTargetProps/builder)
      (.ownerInformation "UltraTax")
      (.description "Maintenance Window for UltraTax instance")
      (.resourceType "INSTANCE")
      (.targets [{"key" "InstanceIds" "values" []}])
      (.name "ultratax-patch-targets")
      (.windowId (.getRef maintenance-window))
      .build))

;; entry-point

(defn -main []
  (let [app (new App)
        stack (new Stack app "ultratax" stack-props)
        vpc (new Vpc stack "ultratax-vpc" vpc-props)
        instance-patching-role (new Role stack "patching-role"
                                    instance-role-props)
        maintenance-window (new CfnMaintenanceWindow stack "maintenance-window"
                                maintenance-window-props)
        instance (new Instance stack "server" (instance-props
                                               vpc
                                               instance-patching-role))
        maintenance-window-target (new CfnMaintenanceWindowTarget maintenance-window "maintenance-window-target"
                                       (maintenance-window-target-props instance maintenance-window))]
    (doto (.getConnections instance)
      (.allowFromAnyIpv4 windows-rdp-port "RDP"))
    (.synth app)))
```

**Comment by johnjelinek** [comment]
note: I was trying to shove instance in another way with `(.targets [{"key" "InstanceIds" "values" [instance]}])` -- but I think that would also mean I need to `(.getInstance instance)`, which results in the error referenced above

**Comment by johnjelinek** [comment]
it looks like I am able to finagle my way to success with this:
```
(.targets [{"key" "tag:Name" "values" [(.getPath (.getNode instance))]}])
```

**Comment by johnjelinek** [comment]
ideally this would just work: `(.targets [instance])`

**Comment by johnjelinek** [comment]
This also resolves: `(.targets [{"key" "InstanceIds" "values" [(.getInstanceId instance)]}])`

**Comment by rix0rrr** [comment]
One note about `.targets`: anything class that starts with `Cfn` is at the L1 level, and those classes know nothing about interacting with "objects", they only deal with primitive types like strings (ARNs, typically), numbers etc.

So it is expected that you have to pass an ARN into `.targets`, instead of an object you're trying to target. Once we eventually get L2 support for the construct you're using there, you will be able to pass instance objects into that.

**Comment by rix0rrr** [comment]
As for the other error, looks like JSII problem. Here is the repro in Java:

```java
package com.myorg;

import software.amazon.awscdk.core.Construct;
import software.amazon.awscdk.core.Stack;
import software.amazon.awscdk.core.StackProps;
import software.amazon.awscdk.services.ec2.AmazonLinuxImage;
import software.amazon.awscdk.services.ec2.CfnInstance;
import software.amazon.awscdk.services.ec2.Instance;
import software.amazon.awscdk.services.ec2.InstanceProps;
import software.amazon.awscdk.services.ec2.InstanceType;
import software.amazon.awscdk.services.ec2.Vpc;

public class HelloStack extends Stack {
    public HelloStack(final Construct parent, final String id) {
        this(parent, id, null);
    }

    public HelloStack(final Construct parent, final String id, final StackProps props) {
        super(parent, id, props);

        Vpc vpc = new Vpc(this, "VPC");

        Instance inst = new Instance(this, "Inst", InstanceProps.builder()
            .instanceType(new InstanceType("t2.micro"))
            .machineImage(new AmazonLinuxImage())
            .vpc(vpc)
            .build());

        CfnInstance inner = inst.getInstance();
        System.out.println(inner);
    }
}
```

```
  testStack(com.myorg.HelloStackTest): com.fasterxml.jackson.databind.JsonMappingException: Conflicting setter definitions for property "blockDeviceMappings": software.amazon.awscdk.services.ec2.CfnInstance#setBlockDeviceMappings(1 params) vs software.amazon.awscdk.services.ec2.CfnInstance#setBlockDeviceMappings(1 params)(..)
```

**Comment by rix0rrr** [comment]
The reason probably being that the Java code contains an overloaded setter that Jackson can't pick between:

```java
    /**
     * `AWS::EC2::Instance.BlockDeviceMappings`.
     * 
     * @see http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-ec2-instance.html#cfn-ec2-instance-blockdevicemappings
     */
    @software.amazon.jsii.Stability(software.amazon.jsii.Stability.Level.External)
    public void setBlockDeviceMappings(final software.amazon.awscdk.core.IResolvable value) {
        this.jsiiSet("blockDeviceMappings", value);
    }

    /**
     * `AWS::EC2::Instance.BlockDeviceMappings`.
     * 
     * @see http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-ec2-instance.html#cfn-ec2-instance-blockdevicemappings
     */
    @software.amazon.jsii.Stability(software.amazon.jsii.Stability.Level.External)
    public void setBlockDeviceMappings(final java.util.List<java.lang.Object> value) {
        this.jsiiSet("blockDeviceMappings", value);
    }
```

**Comment by RomainMuller** [comment]
Yeah @rix0rrr is probably right... Somehow the overloads make Jackson angry... It's odd however how this hasn't "always" been an issue, since those aren't entirely new... And the current Java code shouldn't even attempt to use Jackson on those (although I have to be validating this assumption).

**Comment by magJ** [comment]
Hacky workaround:
```kotlin
JsiiObjectMapper.INSTANCE.setAnnotationIntrospector(object : AnnotationIntrospector() {
    override fun version(): Version {
        return Version.unknownVersion()
    }

    override fun resolveSetterConflict(config: MapperConfig<*>?, setter1: AnnotatedMethod, setter2: AnnotatedMethod): AnnotatedMethod? {
        return setter1
    }
})
```

**Comment by johnjelinek** [comment]
Any updates on this? I'd like to get the `CfnInstance` from an `Instance` and make the EBS volume encrypted.

**Comment by rix0rrr** [comment]
Are you still seeing the Jackson errors?

**Comment by johnjelinek** [comment]
Yes, no change as of `1.16.1`

**Comment by RomainMuller** [comment]
This might require a code generation update. If I don't get any other major issues (🤞🏻) I'll spend some time on this one specifically tomorrow to get to the bottom of it.

**Comment by johnjelinek** [comment]
Here's the latest error from `1.16.3`:

>Error:
Execution error (IllegalArgumentException) at com.fasterxml.jackson.databind.introspect.POJOPropertyBuilder/getSetter (POJOPropertyBuilder.java:497).
Conflicting setter definitions for property "sourceDestCheck": software.amazon.awscdk.services.ec2.CfnInstance#setSourceDestCheck(1 params) vs software.amazon.awscdk.services.ec2.CfnInstance#setSourceDestCheck(1 params)

**Comment by rix0rrr** [comment]
I believe this has been fixed in the latest release.

**Comment by rix0rrr** [comment]
Oh no it has been reverted.

**Comment by RomainMuller** [comment]
The fix for this will roll out in the next CDK release. I'll resolve this issue for now, please re-open if you still encounter the problem once the new release (probably `1.19.0`) is out.
