### ISSUE TITLE
AWS_ECS: CDK deploy will be timeout when I adding Task addVolume

### ISSUE THREAD

**Issue by davidhsuxrex** [aws/aws-cdk#4357]
### The Question
CDK will be timeout when I updating my ECS Service. Once I added my task volume configuration then deploy, it will timeout then show me security token is expired.

And other changing such as `environment`, `secrets`...etc was successful except task volume related methods.

Even though the CloudFormation showing `UPDATE_IN_PROGRESS`, CDK will be timeout. It was just stuck there and I need to cancel the CloudFormation update manually.

Does anyone also encounter this issue?

```typescript
    ec2TaskDefinition.addVolume({
      name: `${taskVolumeName}`,
      dockerVolumeConfiguration: {
        autoprovision: true,
        scope: Scope.TASK,
        driver: 'local',
        driverOpts: {
          volumeType: 'nfs',
          deviceName: ':/',
          addr: 'fs-123456.efs.ap-northeast-1.amazonaws.com,nfsvers=4.1,rsize=1048576,wsize=1048576,hard,timeo=600,retrans=2'
        }
      }
    })

```

```typescript
    container.addMountPoints({
      containerPath: '/var/lib/test',
      readOnly: false,
      sourceVolume: `${taskVolumeName}`
    })
```

<br />
And after I executed `cdk deploy` about 20 mins, I got some error logs below.

```bash
david-test: deploying...
david-test: creating CloudFormation changeset...
 0/3 | 4:38:49 PM | UPDATE_IN_PROGRESS   | AWS::ECS::TaskDefinition                  | Task (Task79114B6B) Requested update requires the creation of a new physical resource; hence creating one.
 0/3 | 4:38:49 PM | UPDATE_IN_PROGRESS   | AWS::ECS::TaskDefinition                  | Task (Task79114B6B) Resource creation Initiated
 1/3 | 4:38:50 PM | UPDATE_COMPLETE      | AWS::ECS::TaskDefinition                  | Task (Task79114B6B)
 1/3 | 4:38:54 PM | UPDATE_IN_PROGRESS   | AWS::ECS::Service                         | Service/Service (ServiceD69D759B)
1/3 Currently in progress: ServiceD69D759B

 ❌  david-test failed: ExpiredToken: The security token included in the request is expired
    at Request.extractError (/usr/local/lib/node_modules/aws-cdk/node_modules/aws-sdk/lib/protocol/query.js:50:29)
    at Request.callListeners (/usr/local/lib/node_modules/aws-cdk/node_modules/aws-sdk/lib/sequential_executor.js:106:20)
    at Request.emit (/usr/local/lib/node_modules/aws-cdk/node_modules/aws-sdk/lib/sequential_executor.js:78:10)
    at Request.emit (/usr/local/lib/node_modules/aws-cdk/node_modules/aws-sdk/lib/request.js:683:14)
    at Request.transition (/usr/local/lib/node_modules/aws-cdk/node_modules/aws-sdk/lib/request.js:22:10)
    at AcceptorStateMachine.runTo (/usr/local/lib/node_modules/aws-cdk/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at /usr/local/lib/node_modules/aws-cdk/node_modules/aws-sdk/lib/state_machine.js:26:10
    at Request.<anonymous> (/usr/local/lib/node_modules/aws-cdk/node_modules/aws-sdk/lib/request.js:38:9)
    at Request.<anonymous> (/usr/local/lib/node_modules/aws-cdk/node_modules/aws-sdk/lib/request.js:685:12)
    at Request.callListeners (/usr/local/lib/node_modules/aws-cdk/node_modules/aws-sdk/lib/sequential_executor.js:116:18) {
  message: 'The security token included in the request is expired',
  code: 'ExpiredToken',
  time: 2019-10-03T08:53:03.367Z,
  requestId: 'dddd-91b8-479c-a17d-c93bd86d25d8',
  statusCode: 403,
  retryable: true
}
```

### Environment

  - **CDK CLI Version:** 1.11.0
  - **Module Version:** 1.11.0
  - **OS:** OSX Mojave
  - **Language:** TypeScript

**Comment by davidhsuxrex** [comment]
After I changed the volume type from `dockerVolumeConfiguation` to `host`, it works. but EFS still failed.

```typescript
    ec2TaskDefinition.addVolume({
      name: `${taskVolumeName}`,
      host:{ sourcePath: '/var/lib/test' }
    })
```

I am wondering if EFS as ECS task volume needs any IAM Permission to attach? I can't understand what's the reason behind that EFS cannot mount as a task volume.

**Comment by davidhsuxrex** [comment]
Sorry all,

I found the root cause is my `dockerVolumeConfiguration` was given an incorrect argument.

It should be

```
    ec2TaskDefinition.addVolume({
      name: `${taskVolumeName}`,
      dockerVolumeConfiguration: {
        scope: Scope.TASK,
        driver: 'local',
        driverOpts: {
          type: 'nfs',
          device: ':/',
          o: 'addr=fs-abcd.efs.ap-northeast-1.amazonaws.com,nfsvers=4.1,rsize=1048576,wsize=1048576,hard,timeo=600,retrans=2'
        }
      }
```

Use `type`, `device`, `o` instead of `volumeType`, `deviceName`, `addr`. and the `'o'` of my previous script was incorrect either.

And Cloudformation will check if the container can be created, it will be stuck to waiting for container created successfully.

So make sure all arguments are right. Let me close this issue, thanks.
