### ISSUE TITLE
.NET Parameter Count Mismatch in BucketDeployment

### ISSUE THREAD

**Issue by Fizzixnerd** [aws/aws-cdk#4387]
When using the .NET CDK (1.11.0-devpreview), I have been unable to construct a `Stack` due to a Parameter number mismatch error from JSII.

### Reproduction Steps

https://github.com/Fizzixnerd/cdk-bugs/blob/master/Reproduction/Reproduction.fs is the meat of it.

1) `git clone https://github.com/Fizzixnerd/cdk-bugs; cd cdk-bugs`
2) `mono .paket/paket.exe install`
3) `cd Reproduction`
4) `dotnet build; dotnet run`

### Error Log

```Unhandled Exception: Amazon.JSII.Runtime.JsiiException: System.Reflection.TargetParameterCountException: Parameter count mismatch.
   at System.Reflection.RuntimeMethodInfo.InvokeArgumentsCheck(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Amazon.JSII.Runtime.CallbackExtensions.InvokeMethod(InvokeRequest request, IReferenceMap referenceMap)
   at Amazon.JSII.Runtime.CallbackExtensions.InvokeCallback(Callback callback, IReferenceMap referenceMap, IFrameworkToJsiiConverter converter, String& error)
   at Amazon.JSII.Runtime.Services.Client.TryDeserialize[TResponse](String responseJson)
   at Amazon.JSII.Runtime.Services.Client.ReceiveResponse[TResponse]()
   at Amazon.JSII.Runtime.Services.Client.TryDeserialize[TResponse](String responseJson)
   at Amazon.JSII.Runtime.Services.Client.ReceiveResponse[TResponse]()
   at Amazon.JSII.Runtime.Deputy.DeputyBase..ctor(DeputyProps props)
   at Reproduction.ReproductionStack..ctor(Construct parent, String id, IStackProps props) in /home/me/src/Workshop/bugs/cdk/Reproduction/Reproduction.fs:line 19
   at Reproduction.main(String[] argv) in /home/me/src/Workshop/bugs/cdk/Reproduction/Reproduction.fs:line 24
```

### Environment

  - **CLI Version      :** 1.11.0 (build 4ed4d96)
  - **Framework Version:** 1.11.0-devpreview
  - **OS               :** Linux (debian)
  - **Language         :** .NET (F#)

### Other

I hope you can forgive that its in F# and not C#; I don't know the latter well enough to rewrite it in it.  If you need clarification let me know.

--- 

This is :bug: Bug Report

**Comment by RomainMuller** [comment]
This might be fixed in the upcoming release.

**Comment by RomainMuller** [comment]
Resolving as it is believed to be fixed. Please re-open if you are still affected.
