### ISSUE TITLE
Python jsii: AttributeError: '__jsii__type__' , Error occurs when passing string value to the mandatory property <type>, while creating glue CfnTrigger instance.

### ISSUE THREAD

**Issue by rush2ranvijay** [aws/aws-cdk#4447]
**description of the bug:**

I'm using the AWS CDK with Python.  I'm trying to create a glue.CfnTrigger instance by passing string value to its mandatory property 'type' (e.g. 'ON_DEMAND') , along with other properties , I'm getting below error when i'm running cdk ls command.
**_AttributeError: 'property' object has no attribute '__jsii__type__'_**

### Reproduction Steps

      job = glue.CfnJob(
            self,'glue-test-job',
            role = 'glue_job_role',
            allocated_capacity=10,
            command=glue.CfnJob.JobCommandProperty(
                name='glueetl',
                script_location='s3://my-bucket/glue-scripts/job.scala'
            ))

        actionProperty = glue.CfnTrigger.ActionProperty
        actionProperty.job_name = job
        actions = glue.CfnTrigger.actions
        actions = actionProperty
        trigger = glue.CfnTrigger(
            self, 'glue-test-trigger',
            actions=actions, type='ON_DEMAND'
         ) 

 ### Error Log : 
File "/Users/sranvja/Desktop/tcr-apps/tcr-automation-app/.env/lib/python3.7/site-packages/jsii/_kernel/init.py", line 136, in _make_reference_for_native
d.jsii__type = "Object"
AttributeError: 'property' object has no attribute 'jsii__type'
Subprocess exited with error 1

### Environment

  - **CDK CLI Version      :1.12.0 (build 923055e)**
  - **Module Version: aws-cdk.aws-glue Version 1.12.0:**
  - **OS               :MAC**
  - **Language   :python 3.7**

### Complete Error log Trace

Traceback (most recent call last):
  File "app.py", line 12, in <module>
    TCRAutomationStack(app, "tcr-automation-stack", env={'region': 'us-west-2'})
  File "/Users/sranvja/Desktop/tcr-apps/tcr-automation-app/.env/lib/python3.7/site-packages/jsii/_runtime.py", line 66, in __call__
    inst = super().__call__(*args, **kwargs)
  File "/Users/sranvja/Desktop/tcr-apps/tcr-automation-app/tcr_infra/tcr_automation_stack.py", line 17, in __init__
    collector_workflow = CollectorWorkFlowConstruct(self, "CollectorWrkFlwConstruct")
  File "/Users/sranvja/Desktop/tcr-apps/tcr-automation-app/.env/lib/python3.7/site-packages/jsii/_runtime.py", line 66, in __call__
    inst = super().__call__(*args, **kwargs)
  File "/Users/sranvja/Desktop/tcr-apps/tcr-automation-app/glue_workflows/collector_stage_workflow.py", line 42, in __init__
    actions=actions, type='ON_DEMAND'
  File "/Users/sranvja/Desktop/tcr-apps/tcr-automation-app/.env/lib/python3.7/site-packages/jsii/_runtime.py", line 66, in __call__
    inst = super().__call__(*args, **kwargs)
  File "/Users/sranvja/Desktop/tcr-apps/tcr-automation-app/.env/lib/python3.7/site-packages/aws_cdk/aws_glue/__init__.py", line 4838, in __init__
    jsii.create(CfnTrigger, self, [scope, id, props])
  File "/Users/sranvja/Desktop/tcr-apps/tcr-automation-app/.env/lib/python3.7/site-packages/jsii/_kernel/__init__.py", line 213, in create
    args=_make_reference_for_native(self, args),
  File "/Users/sranvja/Desktop/tcr-apps/tcr-automation-app/.env/lib/python3.7/site-packages/jsii/_kernel/__init__.py", line 120, in _make_referenc
e_for_native
    return [_make_reference_for_native(kernel, i) for i in d]
  File "/Users/sranvja/Desktop/tcr-apps/tcr-automation-app/.env/lib/python3.7/site-packages/jsii/_kernel/__init__.py", line 120, in <listcomp>
    return [_make_reference_for_native(kernel, i) for i in d]
  File "/Users/sranvja/Desktop/tcr-apps/tcr-automation-app/.env/lib/python3.7/site-packages/jsii/_kernel/__init__.py", line 125, in _make_referenc
e_for_native
    return _make_reference_for_native(kernel, struct_data)
  File "/Users/sranvja/Desktop/tcr-apps/tcr-automation-app/.env/lib/python3.7/site-packages/jsii/_kernel/__init__.py", line 118, in _make_referenc
e_for_native
    return {k: _make_reference_for_native(kernel, v) for k, v in d.items()}
  File "/Users/sranvja/Desktop/tcr-apps/tcr-automation-app/.env/lib/python3.7/site-packages/jsii/_kernel/__init__.py", line 118, in <dictcomp>
    return {k: _make_reference_for_native(kernel, v) for k, v in d.items()}
  File "/Users/sranvja/Desktop/tcr-apps/tcr-automation-app/.env/lib/python3.7/site-packages/jsii/_kernel/__init__.py", line 125, in _make_referenc
e_for_native
    return _make_reference_for_native(kernel, struct_data)
  File "/Users/sranvja/Desktop/tcr-apps/tcr-automation-app/.env/lib/python3.7/site-packages/jsii/_kernel/__init__.py", line 118, in _make_referenc
e_for_native
    return {k: _make_reference_for_native(kernel, v) for k, v in d.items()}
  File "/Users/sranvja/Desktop/tcr-apps/tcr-automation-app/.env/lib/python3.7/site-packages/jsii/_kernel/__init__.py", line 118, in <dictcomp>
    return {k: _make_reference_for_native(kernel, v) for k, v in d.items()}
  File "/Users/sranvja/Desktop/tcr-apps/tcr-automation-app/.env/lib/python3.7/site-packages/jsii/_kernel/__init__.py", line 136, in _make_reference_for_native
    d.__jsii__type__ = "Object"
AttributeError: 'property' object has no attribute '__jsii__type__'
Subprocess exited with error 1

--- 

This is :bug: Bug Report

**Comment by rush2ranvijay** [comment]
@skinny85 Do you have any update on this :)

**Comment by skinny85** [comment]
Hey @rush2ranvijay ,

sorry for missing this issue. I tried it locally, and the following code works for me:

```python
        job = glue.CfnJob(
            self,'glue-test-job',
            role = 'glue_job_role',
            allocated_capacity=10,
            command=glue.CfnJob.JobCommandProperty(
                name='glueetl',
                script_location='s3://my-bucket/glue-scripts/job.scala'
            ),
        )

        trigger = glue.CfnTrigger(
            self, 'glue-test-trigger',
            actions=[
                glue.CfnTrigger.ActionProperty(
                    job_name=job.ref,
                ),
            ],
            type='ON_DEMAND',
        )
```

Might I suggest trying to use a statically typed language with the CDK, like TypeScript? I feel like a lot of the problems with the code you originally submitted (like not passing an array where it was expected, or using the wrong class name) would be immediately discovered, at compile time, in a statically-typed language. I think it would make it easier for you to know what you have to pass in each of the properties.

Hope this helps!

Adam

**Comment by rush2ranvijay** [comment]
Thanks Adam above code is working for me 👍 

Yes, you are correct it is better to use language like TypeScript. But this is something  in not my hand, also will surly discuss this option internally :)

**Comment by skinny85** [comment]
Glad to hear it :)

I'm resolving this one then, feel free to comment if you need more help with this issue.

Thanks,
Adam
