### ISSUE TITLE
ContainerImage.fromAsset got ValidationError: S3 error in China region

### ISSUE THREAD

**Issue by pahud** [aws/aws-cdk#4482]
`ContainerImage.fromAsset` from `aws-ecs` got `ValidationError` when deploy to China NingXia region(`cn-northwest-1`).

```
ValidationError: S3 error: The specified bucket does not exist
```

### Reproduction Steps

```ts
import cdk = require('@aws-cdk/core');
import { ContainerImage } from '@aws-cdk/aws-ecs';
import path = require('path');

const app = new cdk.App();
const stack = new cdk.Stack(app, 'FargateAlbSvc');
ContainerImage.fromAsset(path.join(__dirname, './assets.d/'));
```
And the `Dockerfile` in `assets.d`:

```bash
$ cat assets.d/Dockerfile                                
FROM nginx:latest

ENV FOO BAR
```

### Error Log

```
$ cdk --profile zhy --app fargate-alb-svc.js --verbose deploy  
CDK toolkit version: 1.12.0 (build 923055e)
Command line arguments: { _: [ 'deploy' ],
  profile: 'zhy',
  app: 'fargate-alb-svc.js',
  a: 'fargate-alb-svc.js',
  verbose: true,
  v: true,
  'ignore-errors': false,
  ignoreErrors: false,
  json: false,
  j: false,
  ec2creds: undefined,
  i: undefined,
  'version-reporting': undefined,
  versionReporting: undefined,
  'path-metadata': true,
  pathMetadata: true,
  'asset-metadata': true,
  assetMetadata: true,
  'role-arn': undefined,
  r: undefined,
  roleArn: undefined,
  staging: true,
  'no-color': false,
  noColor: false,
  'build-exclude': [],
  E: [],
  buildExclude: [],
  ci: false,
  '$0': 'cdk' }
Determining whether we're on an EC2 instance.
Does not look like EC2 instance.
cdk.context.json: {
  "vpc-provider:account=903779448426:filter.isDefault=true:region=us-west-2": {
    "vpcId": "vpc-a522d7dc",
    "availabilityZones": [
      "us-west-2a",
      "us-west-2b",
      "us-west-2c",
      "us-west-2d"
    ],
    "privateSubnetIds": [
      "subnet-08b2d414ad87fb172",
      "subnet-0d0069776469b2e0d",
      "subnet-0e0a074fc211df2ac",
      "subnet-023a0778a5605ae13"
    ],
    "privateSubnetNames": [
      "Private"
    ],
    "privateSubnetRouteTableIds": [
      "rtb-0c99af140fbbe3b17",
      "rtb-0c99af140fbbe3b17",
      "rtb-0c99af140fbbe3b17",
      "rtb-0c99af140fbbe3b17"
    ],
    "publicSubnetIds": [
      "subnet-0c16aec6d2bece81d",
      "subnet-050929f8c6efb7657",
      "subnet-061c38942c5b3afa8",
      "subnet-05685883c2773c212"
    ],
    "publicSubnetNames": [
      "Public"
    ],
    "publicSubnetRouteTableIds": [
      "rtb-48a79931",
      "rtb-48a79931",
      "rtb-48a79931",
      "rtb-48a79931"
    ]
  },
  "vpc-provider:account=937788672844:filter.isDefault=true:region=cn-north-1": {
    "vpcId": "vpc-c1e040a5",
    "availabilityZones": [
      "cn-north-1a",
      "cn-north-1b"
    ],
    "publicSubnetIds": [
      "subnet-9311f8f7",
      "subnet-f3610a84"
    ],
    "publicSubnetNames": [
      "Public"
    ],
    "publicSubnetRouteTableIds": [
      "rtb-078f9862",
      "rtb-078f9862"
    ]
  },
  "vpc-provider:account=937788672844:filter.isDefault=true:region=cn-northwest-1": {
    "vpcId": "vpc-0417e46d",
    "availabilityZones": [
      "cn-northwest-1a",
      "cn-northwest-1b",
      "cn-northwest-1c"
    ],
    "privateSubnetIds": [
      "subnet-0e9460dbcfc4cf6ee",
      "subnet-0562f666bdf5c29af",
      "subnet-00ab15c0022872f06"
    ],
    "privateSubnetNames": [
      "Private"
    ],
    "privateSubnetRouteTableIds": [
      "rtb-046c3173563f086e6",
      "rtb-046c3173563f086e6",
      "rtb-046c3173563f086e6"
    ],
    "publicSubnetIds": [
      "subnet-5bbe7b32",
      "subnet-0428367c",
      "subnet-1586a75f"
    ],
    "publicSubnetNames": [
      "Public"
    ],
    "publicSubnetRouteTableIds": [
      "rtb-5230cf3b",
      "rtb-5230cf3b",
      "rtb-5230cf3b"
    ]
  }
}
merged settings: { versionReporting: true,
  pathMetadata: true,
  output: 'cdk.out',
  app: 'fargate-alb-svc.js',
  context: {},
  tags: [],
  assetMetadata: true,
  toolkitBucket: {},
  staging: true }
Setting "CDK_DEFAULT_REGION" environment variable to cn-northwest-1
Resolving default credentials
Retrieved account ID 937788672844 from disk cache
Setting "CDK_DEFAULT_ACCOUNT" environment variable to 937788672844
context: { 'vpc-provider:account=903779448426:filter.isDefault=true:region=us-west-2':
   { vpcId: 'vpc-a522d7dc',
     availabilityZones: [ 'us-west-2a', 'us-west-2b', 'us-west-2c', 'us-west-2d' ],
     privateSubnetIds:
      [ 'subnet-08b2d414ad87fb172',
        'subnet-0d0069776469b2e0d',
        'subnet-0e0a074fc211df2ac',
        'subnet-023a0778a5605ae13' ],
     privateSubnetNames: [ 'Private' ],
     privateSubnetRouteTableIds:
      [ 'rtb-0c99af140fbbe3b17',
        'rtb-0c99af140fbbe3b17',
        'rtb-0c99af140fbbe3b17',
        'rtb-0c99af140fbbe3b17' ],
     publicSubnetIds:
      [ 'subnet-0c16aec6d2bece81d',
        'subnet-050929f8c6efb7657',
        'subnet-061c38942c5b3afa8',
        'subnet-05685883c2773c212' ],
     publicSubnetNames: [ 'Public' ],
     publicSubnetRouteTableIds:
      [ 'rtb-48a79931', 'rtb-48a79931', 'rtb-48a79931', 'rtb-48a79931' ] },
  'vpc-provider:account=937788672844:filter.isDefault=true:region=cn-north-1':
   { vpcId: 'vpc-c1e040a5',
     availabilityZones: [ 'cn-north-1a', 'cn-north-1b' ],
     publicSubnetIds: [ 'subnet-9311f8f7', 'subnet-f3610a84' ],
     publicSubnetNames: [ 'Public' ],
     publicSubnetRouteTableIds: [ 'rtb-078f9862', 'rtb-078f9862' ] },
  'vpc-provider:account=937788672844:filter.isDefault=true:region=cn-northwest-1':
   { vpcId: 'vpc-0417e46d',
     availabilityZones: [ 'cn-northwest-1a', 'cn-northwest-1b', 'cn-northwest-1c' ],
     privateSubnetIds:
      [ 'subnet-0e9460dbcfc4cf6ee',
        'subnet-0562f666bdf5c29af',
        'subnet-00ab15c0022872f06' ],
     privateSubnetNames: [ 'Private' ],
     privateSubnetRouteTableIds:
      [ 'rtb-046c3173563f086e6',
        'rtb-046c3173563f086e6',
        'rtb-046c3173563f086e6' ],
     publicSubnetIds: [ 'subnet-5bbe7b32', 'subnet-0428367c', 'subnet-1586a75f' ],
     publicSubnetNames: [ 'Public' ],
     publicSubnetRouteTableIds: [ 'rtb-5230cf3b', 'rtb-5230cf3b', 'rtb-5230cf3b' ] },
  'aws:cdk:enable-path-metadata': true,
  'aws:cdk:enable-asset-metadata': true }
outdir: cdk.out
env: { CDK_DEFAULT_REGION: 'cn-northwest-1',
  CDK_DEFAULT_ACCOUNT: '937788672844',
  CDK_CONTEXT_JSON:
   '{"vpc-provider:account=903779448426:filter.isDefault=true:region=us-west-2":{"vpcId":"vpc-a522d7dc","availabilityZones":["us-west-2a","us-west-2b","us-west-2c","us-west-2d"],"privateSubnetIds":["subnet-08b2d414ad87fb172","subnet-0d0069776469b2e0d","subnet-0e0a074fc211df2ac","subnet-023a0778a5605ae13"],"privateSubnetNames":["Private"],"privateSubnetRouteTableIds":["rtb-0c99af140fbbe3b17","rtb-0c99af140fbbe3b17","rtb-0c99af140fbbe3b17","rtb-0c99af140fbbe3b17"],"publicSubnetIds":["subnet-0c16aec6d2bece81d","subnet-050929f8c6efb7657","subnet-061c38942c5b3afa8","subnet-05685883c2773c212"],"publicSubnetNames":["Public"],"publicSubnetRouteTableIds":["rtb-48a79931","rtb-48a79931","rtb-48a79931","rtb-48a79931"]},"vpc-provider:account=937788672844:filter.isDefault=true:region=cn-north-1":{"vpcId":"vpc-c1e040a5","availabilityZones":["cn-north-1a","cn-north-1b"],"publicSubnetIds":["subnet-9311f8f7","subnet-f3610a84"],"publicSubnetNames":["Public"],"publicSubnetRouteTableIds":["rtb-078f9862","rtb-078f9862"]},"vpc-provider:account=937788672844:filter.isDefault=true:region=cn-northwest-1":{"vpcId":"vpc-0417e46d","availabilityZones":["cn-northwest-1a","cn-northwest-1b","cn-northwest-1c"],"privateSubnetIds":["subnet-0e9460dbcfc4cf6ee","subnet-0562f666bdf5c29af","subnet-00ab15c0022872f06"],"privateSubnetNames":["Private"],"privateSubnetRouteTableIds":["rtb-046c3173563f086e6","rtb-046c3173563f086e6","rtb-046c3173563f086e6"],"publicSubnetIds":["subnet-5bbe7b32","subnet-0428367c","subnet-1586a75f"],"publicSubnetNames":["Public"],"publicSubnetRouteTableIds":["rtb-5230cf3b","rtb-5230cf3b","rtb-5230cf3b"]},"aws:cdk:enable-path-metadata":true,"aws:cdk:enable-asset-metadata":true}',
  CDK_OUTDIR: 'cdk.out',
  CDK_CLI_ASM_VERSION: '1.10.0',
  CDK_CLI_VERSION: '1.12.0' }
Reading existing template for stack Demo.
Using default AWS SDK credentials for account 937788672844
Demo: deploying...
Waiting for stack CDKToolkit to finish creating or updating...
Using default AWS SDK credentials for account 937788672844
s3://cdktoolkit-stagingbucket-d1c7lshtafy9/cdk/Demo/5f57e0210f72b9679a532a8fab4c765f8806619fe052288110e4df34e81004e4.yml: checking if already exists
s3://cdktoolkit-stagingbucket-d1c7lshtafy9/cdk/Demo/5f57e0210f72b9679a532a8fab4c765f8806619fe052288110e4df34e81004e4.yml: uploading
s3://cdktoolkit-stagingbucket-d1c7lshtafy9/cdk/Demo/5f57e0210f72b9679a532a8fab4c765f8806619fe052288110e4df34e81004e4.yml: upload complete
Stored template in S3 at: https://cdktoolkit-stagingbucket-d1c7lshtafy9.s3.amazonaws.com/cdk/Demo/5f57e0210f72b9679a532a8fab4c765f8806619fe052288110e4df34e81004e4.yml
Attempting to create ChangeSet CDK-13882749-987d-42a8-8f5a-3418c161efc6 to create stack Demo
Demo: creating CloudFormation changeset...

 ❌  Demo failed: ValidationError: S3 error: The specified bucket does not exist
For more information check http://docs.aws.amazon.com/AmazonS3/latest/API/ErrorResponses.html
S3 error: The specified bucket does not exist
For more information check http://docs.aws.amazon.com/AmazonS3/latest/API/ErrorResponses.html
ValidationError: S3 error: The specified bucket does not exist
For more information check http://docs.aws.amazon.com/AmazonS3/latest/API/ErrorResponses.html
    at Request.extractError (/Users/pahud/.nvm/versions/node/v10.16.0/lib/node_modules/aws-cdk/node_modules/aws-sdk/lib/protocol/query.js:50:29)
    at Request.callListeners (/Users/pahud/.nvm/versions/node/v10.16.0/lib/node_modules/aws-cdk/node_modules/aws-sdk/lib/sequential_executor.js:106:20)
    at Request.emit (/Users/pahud/.nvm/versions/node/v10.16.0/lib/node_modules/aws-cdk/node_modules/aws-sdk/lib/sequential_executor.js:78:10)
    at Request.emit (/Users/pahud/.nvm/versions/node/v10.16.0/lib/node_modules/aws-cdk/node_modules/aws-sdk/lib/request.js:683:14)
    at Request.transition (/Users/pahud/.nvm/versions/node/v10.16.0/lib/node_modules/aws-cdk/node_modules/aws-sdk/lib/request.js:22:10)
    at AcceptorStateMachine.runTo (/Users/pahud/.nvm/versions/node/v10.16.0/lib/node_modules/aws-cdk/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at /Users/pahud/.nvm/versions/node/v10.16.0/lib/node_modules/aws-cdk/node_modules/aws-sdk/lib/state_machine.js:26:10
    at Request.<anonymous> (/Users/pahud/.nvm/versions/node/v10.16.0/lib/node_modules/aws-cdk/node_modules/aws-sdk/lib/request.js:38:9)
    at Request.<anonymous> (/Users/pahud/.nvm/versions/node/v10.16.0/lib/node_modules/aws-cdk/node_modules/aws-sdk/lib/request.js:685:12)
    at Request.callListeners (/Users/pahud/.nvm/versions/node/v10.16.0/lib/node_modules/aws-cdk/node_modules/aws-sdk/lib/sequential_executor.js:116:18)
```

### Environment

  - **CLI Version      :v1.12.0**
  - **Framework Version:**
  - **OS               :Mac OS X**
  - **Language         :TypeScript**

### Other

--- 

This is :bug: Bug Report

**Comment by pahud** [comment]
Is this bug related to #4289 ?

**Comment by pkandasamy91** [comment]
@pahud, were you able to `cdk bootstrap` successfully in the CN partition?

**Comment by pahud** [comment]
bootstrap failed when I cut this issue but it works today! I've even successfully spin up the Fargate service with local docker assets in Ningxia and Beijing region. Temporarily close this issue. Thanks!
