### ISSUE TITLE
DefaultAction required fields are not enough to create Listener 

### ISSUE THREAD

**Issue by tarunaroraonline** [aws/aws-cdk#4616]
I am trying to set up an Application Load Balancer using CDK. It seems Default Action needs more required fields than what's listed in the documentation?  

### Reproduction Steps

``` 
var listener_defaults = new List<CfnListener.ActionProperty>();
            listener_defaults.Add(new CfnListener.ActionProperty()
                                    {Type="forward",
                                    TargetGroupArn = targetGroup.LogicalId 
                                    });

            var listener = new CfnListener(
                this, 
                "CfnListener",
                new CfnListenerProps(){
                    LoadBalancerArn = lb.LogicalId,
                    Port = 6790,
                    Protocol = "HTTP",
                    DefaultActions = listener_defaults
                    });
```
The docs say that the default actions of type 'forward' only needs the type and target group id, which I am passing already. But the code execution fails with the below error message. 

### Error Log

```
Exception has occurred: CLR/Amazon.JSII.Runtime.JsiiException
An unhandled exception of type 'Amazon.JSII.Runtime.JsiiException' occurred in Amazon.JSII.Runtime.dll: '**Missing required properties for @aws-cdk/aws-elasticloadbalancingv2.CfnListenerProps: defaultActions**'
   at Amazon.JSII.Runtime.Services.Client.TryDeserialize[TResponse](String responseJson)
   at Amazon.JSII.Runtime.Services.Client.ReceiveResponse[TResponse]()
   at Amazon.JSII.Runtime.Deputy.DeputyBase..ctor(DeputyProps props)
   at InfraPlatform.stacks.AlbStack..ctor(Construct parent, String id, IStackProps props) in
```

### Environment

  - **CLI Version      : 1.13.1
  - **Framework Version:**
  - **OS               : Windows 
  - **Language         : csharp 

### Other

--- 

This is :bug: Bug Report

**Comment by rix0rrr** [comment]
This looks like it might be a JSII issue.

**Comment by RomainMuller** [comment]
Is this still an issue with CDK 1.16.x?
