### ISSUE TITLE
1.14 c# lambda definition error on synth

### ISSUE THREAD

**Issue by jmacnett** [aws/aws-cdk#4673]
Just upgraded my CDK nuget packages and aws-cdk npm install from 1.7 to 1.14, and now calling `cdk synth` fails on lambda constructors.

`PS D:\temp\cdk2> cdk synth

Unhandled Exception: Amazon.JSII.Runtime.JsiiException: System.Reflection.TargetParameterCountException: Parameter count mismatch.
   at System.Reflection.RuntimeMethodInfo.InvokeArgumentsCheck(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Amazon.JSII.Runtime.CallbackExtensions.InvokeMethod(InvokeRequest request, IReferenceMap referenceMap)
   at Amazon.JSII.Runtime.CallbackExtensions.InvokeCallback(Callback callback, IReferenceMap referenceMap, IFrameworkToJsiiConverter converter, String& error)
   at Amazon.JSII.Runtime.Services.Client.TryDeserialize[TResponse](String responseJson)
   at Amazon.JSII.Runtime.Services.Client.ReceiveResponse[TResponse]()
   at Amazon.JSII.Runtime.Services.Client.TryDeserialize[TResponse](String responseJson)
   at Amazon.JSII.Runtime.Services.Client.ReceiveResponse[TResponse]()
   at Amazon.JSII.Runtime.Services.Client.TryDeserialize[TResponse](String responseJson)
   at Amazon.JSII.Runtime.Services.Client.ReceiveResponse[TResponse]()
   at Amazon.JSII.Runtime.Deputy.DeputyBase..ctor(DeputyProps props)
   at Cdk2.Cdk2Stack..ctor(Construct parent, String id, IStackProps props) in D:\temp\cdk2\src\Cdk2\Cdk2Stack.cs:line 11
   at Cdk2.Program.Main(String[] args) in D:\temp\cdk2\src\Cdk2\Program.cs:line 13
Subprocess exited with error 3762504530
PS D:\temp\cdk2>`

This still works if i revert my NuGet packages to 1.7 and leave the CLI at 1.14, but once the packages are upgraded, it fails.  Sample code from stack:

`public Cdk2Stack(Construct parent, string id, IStackProps props) : base(parent, id, props)
        {
            // create lambda
            var erLambda = new Amazon.CDK.AWS.Lambda.Function(this, $"test-lambda", new FunctionProps()
            {
                FunctionName = $"test-lambda",
                Code = new AssetCode(@"D:\temp\cdk2\lambda.zip"),
                Description = $"test lambda",
                Handler = "CDKTest.Lambda::CDKTest.Lambda.LambdaEntryPoint::FunctionHandlerAsync",
                Runtime = Runtime.DOTNET_CORE_2_1,
                Environment = new System.Collections.Generic.Dictionary<string, string>()
                    {
                        { "key1", "value1" },
                        { "key2", "value2" },
                        { "key3", "value3" },
                        { "key4", "value4" },
                        { "key5", "value5" },
                    },
                Timeout = Duration.Seconds(60),
                MemorySize = 1024
            });
        }`

For now, i've reverted to 1.7.  Please advise.

**Comment by RomainMuller** [comment]
Hey!

Can you give it a shot at `1.16+`? This is a bug I hope to have fixed.

Regards,
Romain.

**Comment by jmacnett** [comment]
looks like the new assemblies require .netcore 3.0 (no 2.1 or 2.2 support; i was on 2.1 previously)...so in the purest sense, that kind of tweaked it a bit.

With that said, the cdk synth call works now when i'm univerally upraded to 1.16!  I'm alright w/ upgrading my cdk project alone to 3.0, but i don't know if that's a dealbreaker for anyone else.
