### ISSUE TITLE
AWS CDK not able to identify method  servicediscovery.PrivateDnsNamespace.create_service

### ISSUE THREAD

**Issue by varshneysan** [aws/aws-cdk#4892]
### The Question

As mention in the documentation here.
https://docs.aws.amazon.com/cdk/api/latest/python/aws_cdk.aws_servicediscovery/PrivateDnsNamespace.html

CDK python is not able to identify the method "servicediscovery.PrivateDnsNamespace.create_service". 

servicediscovery.PrivateDnsNamespace.create_service(self, id = microservice,
                routing_policy = servicediscovery.RoutingPolicy('MULTIVALUE'),
                dns_record_type = servicediscovery.DnsRecordType('A'),
                dns_ttl = core.Duration.seconds(10),
                custom_health_check = servicediscovery.HealthCheckCustomConfig(failure_threshold=5),
                name=microservice
            )

I am getting error as given below:

$ cdk synth
jsii.errors.JavaScriptError:
  Error: Class @aws-cdk/core.Stack doesn't have a method 'createService'
      at Kernel._typeInfoForMethod (/usr/local/lib/python3.6/site-packages/jsii/_embedded/jsii/jsii-runtime.js:7271:19)
      at Kernel._findInvokeTarget (/usr/local/lib/python3.6/site-packages/jsii/_embedded/jsii/jsii-runtime.js:7189:25)
      at Kernel.invoke (/usr/local/lib/python3.6/site-packages/jsii/_embedded/jsii/jsii-runtime.js:6819:38)
      at KernelHost.processRequest (/usr/local/lib/python3.6/site-packages/jsii/_embedded/jsii/jsii-runtime.js:6521:28)
      at KernelHost.run (/usr/local/lib/python3.6/site-packages/jsii/_embedded/jsii/jsii-runtime.js:6464:14)
      at Immediate._onImmediate (/usr/local/lib/python3.6/site-packages/jsii/_embedded/jsii/jsii-runtime.js:6467:37)
      at processImmediate (internal/timers.js:439:21)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "app.py", line 9, in <module>
    EcsappStack(app, "ecsapp")
  File "/usr/local/lib/python3.6/site-packages/jsii/_runtime.py", line 66, in __call__
    inst = super().__call__(*args, **kwargs)
  File "/home/ec2-user/ECSAPP/ecsapp/ecsapp_stack.py", line 125, in __init__
    name=microservice
  File "/usr/local/lib/python3.6/site-packages/aws_cdk/aws_servicediscovery/__init__.py", line 2503, in create_service
    return jsii.invoke(self, "createService", [id, props])
  File "/usr/local/lib/python3.6/site-packages/jsii/_kernel/__init__.py", line 105, in wrapped
    return _recursize_dereference(kernel, fn(kernel, *args, **kwargs))
  File "/usr/local/lib/python3.6/site-packages/jsii/_kernel/__init__.py", line 273, in invoke
    args=_make_reference_for_native(self, args),
  File "/usr/local/lib/python3.6/site-packages/jsii/_kernel/providers/process.py", line 346, in invoke
    return self._process.send(request, InvokeResponse)
  File "/usr/local/lib/python3.6/site-packages/jsii/_kernel/providers/process.py", line 316, in send
    raise JSIIError(resp.error) from JavaScriptError(resp.stack)
jsii.errors.JSIIError: Class @aws-cdk/core.Stack doesn't have a method 'createService'

### Environment

  - **CDK CLI Version:  1.15.0 (build bdbe3aa)** 
  - **Module Version: 1.15** 
  - **OS: Amazon Linux** 
  - **Language: Python** 

### Other information

$ python --version
Python 3.6.8

**Comment by varshneysan** [comment]
if we create an object for the class servicediscovery.PrivateDnsNamespace and then call create_service. it'll work. simple and easy. missed it.

namespacename = servicediscovery.PrivateDnsNamespace (self, id="ms-sd-dns-namespace", vpc=ecsvpc, name=PDNamespace, description="DNS namespace"

namespacename.create_service(id = ..... )
