### ISSUE TITLE
Missing Lambda Asset Results in Reduced Template

### ISSUE THREAD

**Issue by markprovan** [aws/aws-cdk#4927]
CDK reported a missing asset for a Lambda, correctly, but the deploy continued with a vastly reduced CloudFormation template, causing infrastructure to be torn down.

### Reproduction Steps
Add a Lambda Function to a stack and reference an asset that does not exist as it's `code` parameter. Run `cdk diff` to see the resulting changes or `cdk deploy` to see this reproduced on a stack.

### Error Log

Here is output from our CI job, showing the error, but continuing on to deployment
```bash
16:54:04  (node:176) UnhandledPromiseRejectionWarning: Error: ENOENT: no such file or directory, stat '/var/lib/jenkins/workspace/ipa/redacted/@lambda-file.zip'
16:54:04      at Object.statSync (fs.js:855:3)
16:54:04      at Object.fingerprint (/var/lib/jenkins/workspace/ipa/redacted/node_modules/@aws-cdk/assets/lib/fs/fingerprint.ts:38:28)
16:54:04      at new Staging (/var/lib/jenkins/workspace/ipa/redacted/node_modules/@aws-cdk/assets/lib/staging.ts:58:23)
16:54:04      at new Asset (/var/lib/jenkins/workspace/ipa/redacted/node_modules/@aws-cdk/aws-s3-assets/lib/asset.ts:95:21)
16:54:04      at AssetCode.bind (/var/lib/jenkins/workspace/ipa/redacted/node_modules/@aws-cdk/aws-lambda/lib/code.ts:180:20)
16:54:04      at new Function (/var/lib/jenkins/workspace/ipa/redacted/node_modules/@aws-cdk/aws-lambda/lib/function.ts:433:29)
16:54:04      at new AutomatedSnaphots (/var/lib/jenkins/workspace/ipa/redacted/src/stack/elasticsearch.ts:56:33)
16:54:04      at new InsightsElasticSearch (/var/lib/jenkins/workspace/ipa/insights-pipeline/apps/insights-pipeline/src/stack/elasticsearch.ts:220:9)
16:54:04      at new InsightsStack (/var/lib/jenkins/workspace/redacted/src/stack/stack.ts:68:55)
16:54:04      at /var/lib/jenkins/workspace/ipa/redacted/src/stack/app.ts:56:5
16:54:04  (node:176) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
16:54:04  (node:176) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
16:54:04  stack: deploying...
16:54:06  stack: creating CloudFormation changeset...
```

### Environment

  - **CLI Version     1.15.0 :**
  - **Framework Version: 1.15.0**
  - **OS               :Centos 7**
  - **Language         :**

--- 

This is :bug: Bug Report

**Comment by eladb** [comment]
I am unable to reproduce this based on the instructions below. I consistently get the following error and the CLI immediately terminates with a non-zero exit code:

```
ENOENT: no such file or directory, stat '/Users/benisrae/playground/missing-asset/not-found'
Subprocess exited with error 1
```

Please reopen and provide exact CLI command you are running in your CI/CD system, and preferably also `--verbose` log of the CLI.

**Comment by claabs** [comment]
I was able to recreate this with a certain scenario. In my case, I import various configs dynamically, so I wrap the `new Stack()` in an async function:
```typescript
async function main(): Promise<void> {
  const app = new cdk.App();
  const envProps = await envPropsFunc();
  const stack = new InfraStack(
    app, `InfraStack`,
    envProps
  );
}

main();
```

Under these circumstances, and the Lambda code asset missing, I see the deploy continue with a reduced template as described in the original post.
