### ISSUE TITLE
aws-cdk: Error: /home/ec2-user/aws-cdk/node_modules/nyc/bin/nyc.js

### ISSUE THREAD

**Issue by hacker65536** [aws/aws-cdk#4976]
It seems some tests failed when i run `yarn build` in 9a5a7616330c6475217121bd5ef683143839dd76 .

### Reproduction Steps

```console
$ node -v
v13.1.0
$ yarn -v
1.19.1

$ git clone https://github.com/aws/aws-cdk.git
$ git checkout 9a5a7616330c6475217121bd5ef683143839dd76
$ cd aws-cdk
$ yarn build
```

### Error Log
```
aws-cdk: FAILURES: Undone tests (or their setups/teardowns):
aws-cdk: - verify "future flags" are added to cdk.json
aws-cdk: To fix this, make sure all tests call test.done()
aws-cdk: =============================== Coverage summary ===============================
aws-cdk: Statements   : 51.73% ( 1214/2347 )
aws-cdk: Branches     : 36.7% ( 389/1060 )
aws-cdk: Functions    : 51.89% ( 233/449 )
aws-cdk: Lines        : 52.05% ( 1154/2217 )
aws-cdk: ================================================================================
aws-cdk: Error: /home/ec2-user/aws-cdk/node_modules/nyc/bin/nyc.js --clean /home/ec2-user/aws-cdk/node_modules/nodeunit/bin/nodeunit test/api/test.bootstrap.js test/api/test.deploy-stack.js test/api/test.stacks.js test/commands/test.context-command.js test/context-providers/test.amis.js test/context-providers/test.asymmetric-vpcs.js test/context-providers/test.generic.js test/context-providers/test.vpcs.js test/test.account-cache.js test/test.archive.js test/test.assets.js test/test.cdk-docs.js test/test.cdk-doctor.js test/test.cdk-toolkit.js test/test.context.js test/test.diff.js test/test.docker.js test/test.init.js test/test.serialize.js test/test.settings.js test/test.version.js test/test.yaml.js test/util/test.applydefaults.js test/util/test.arrays.js test/util/test.console-formatters.js test/util/test.objects.js exited with error code 1
aws-cdk: Tests failed. Total time (13.5s) | /home/ec2-user/aws-cdk/node_modules/nyc/bin/nyc.js (13.5s)
aws-cdk: !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
aws-cdk: npm ERR! Test failed.  See above for more details.
aws-cdk: error Command failed with exit code 1.
aws-cdk: info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
lerna ERR! yarn run build+test exited 1 in 'aws-cdk'
lerna WARN complete Waiting for 1 child process to exit. CTRL-C to exit immediately.

```

### Environment

  - **CLI Version      :1.6.**
  - **Framework Version: yarn 1.19.1 node 13.1**
  - **OS               :Amazon Linux 2**
  - **Language         :Typescript**

### Other

--- 

This is :bug: Bug Report

**Comment by rix0rrr** [comment]
That is odd. The required call is definitely there in the commit you quoted:

https://github.com/aws/aws-cdk/blob/9a5a7616330c6475217121bd5ef683143839dd76/packages/aws-cdk/test/test.init.ts#L103

Also the CI build succeeds so it's not the code. Try a build from a clean directory (`git clean -fqdx .`), otherwise post more of your error log.

**Comment by hacker65536** [comment]
This is my command history that from new ec2 instance.
```
aws-cdk: FAILURES: Undone tests (or their setups/teardowns):
aws-cdk: - verify "future flags" are added to cdk.json
aws-cdk: To fix this, make sure all tests call test.done()
aws-cdk: =============================== Coverage summary ===============================
aws-cdk: Statements   : 49.74% ( 1169/2350 )
aws-cdk: Branches     : 35.5% ( 377/1062 )
aws-cdk: Functions    : 50.33% ( 226/449 )
aws-cdk: Lines        : 49.93% ( 1109/2221 )
aws-cdk: ================================================================================
aws-cdk: Error: /home/ec2-user/aws-cdk/node_modules/nyc/bin/nyc.js --clean /home/ec2-user/aws-cdk/node_modules/nodeunit/bin/nodeunit test/api/test.bootstrap.js test/api/test.deploy-stack.js test/api/test.stacks.js test/commands/test.context-command.js test/context-providers/test.amis.js test/context-providers/test.asymmetric-vpcs.js test/context-providers/test.generic.js test/context-providers/test.vpcs.js test/test.account-cache.js test/test.archive.js test/test.assets.js test/test.cdk-docs.js test/test.cdk-doctor.js test/test.cdk-toolkit.js test/test.context.js test/test.diff.js test/test.docker.js test/test.init.js test/test.serialize.js test/test.settings.js test/test.version.js test/test.yaml.js test/util/test.applydefaults.js test/util/test.arrays.js test/util/test.console-formatters.js test/util/test.objects.js exited with error code 1
aws-cdk: Tests failed. Total time (13.8s) | /home/ec2-user/aws-cdk/node_modules/nyc/bin/nyc.js (13.8s)
aws-cdk: !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
aws-cdk: npm ERR! Test failed.  See above for more details.
aws-cdk: error Command failed with exit code 1.
aws-cdk: info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
lerna ERR! yarn run build+test exited 1 in 'aws-cdk'
lerna WARN complete Waiting for 1 child process to exit. CTRL-C to exit immediately.

real    2m18.663s
user    4m11.984s
sys     0m8.012s
❌  Last command failed. Scroll up to see errors in log (search for '!!!!!!!!').
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
[ec2-user@ip-172-31-8-101 aws-cdk]$ history
    1  sudo yum update -y
    2  sudo reboot
    3  sudo yum install -y git
    4  curl -SsL -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.35.1/install.sh | bash
    5  source ~/.bashrc
    6  nvm install --lts
    7  npm i -g yarn
    8  git clone https://github.com/aws/aws-cdk.git
    9  cd aws-cdk
   10  yarn build
   11  history
[ec2-user@ip-172-31-8-101 aws-cdk]$ node -v
v12.13.0
[ec2-user@ip-172-31-8-101 aws-cdk]$ yarn -v
1.19.1
[ec2-user@ip-172-31-8-101 aws-cdk]$ uname -r
4.14.152-124.171.amzn2.x86_64
```

**Comment by hacker65536** [comment]
I'm sorry. I missed  other error reports. 
When I installed donet, the build process goes on.
The `dotnet` looks like  a requirement that needed for building. 

```
aws-cdk: Applying project template app for csharp
aws-cdk: /bin/sh: dotnet: command not found
aws-cdk: (node:5640) UnhandledPromiseRejectionWarning: Error: Could not add project AwsCdkTestNz6M9F.csproj to solution AwsCdkTestNz6M9F.sln. Error code: 127
aws-cdk:     at ChildProcess.<anonymous> (/tmp/aws-cdk-testNz6M9F/tmp/add-project.hook.ts:29:16)
aws-cdk:     at Object.onceWrapper (events.js:300:26)
aws-cdk:     at ChildProcess.emit (events.js:210:5)
aws-cdk:     at ChildProcess.EventEmitter.emit (domain.js:478:20)
aws-cdk:     at Process.ChildProcess._handle.onexit (internal/child_process.js:272:12)
aws-cdk: (node:5640) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 6)
aws-cdk: (node:5640) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
aws-cdk: FAILURES: Undone tests (or their setups/teardowns):
```
