### ISSUE TITLE
Following the instructions in Getting-started runs in an error

### ISSUE THREAD

**Issue by yamatatsu** [aws/aws-cdk#5048]
[Getting Started in CONTRIBUTING.md](https://github.com/aws/aws-cdk/blob/master/CONTRIBUTING.md#getting-started) is not working.

When I run the following command,

```
$ git clone https://github.com/aws/aws-cdk.git
$ cd aws-cdk
$ yarn build
```

It fails at `yarn build` with the following error.

I believe this is caused by [this test](https://github.com/aws/aws-cdk/blob/master/packages/aws-cdk/test/test.init.ts#L73-L104) in `packages/aws-cdk`.
Because it depends on `dotnet` and `.NET SDK`.

When I install `dotnet` and `.NET SDK` then `yarn build` succeeds.

### Reproduction Steps

1. In an environment that has not installed `dotnet` command
1. Trying the following command in [Getting Started](https://github.com/aws/aws-cdk/blob/master/CONTRIBUTING.md#getting-started) as;
```
$ git clone https://github.com/aws/aws-cdk.git
$ cd aws-cdk
$ yarn build
```

3. This error will happen at `yarn test` in `packages/aws-cdk`.

### Error Log

```
Temporary working directory: /var/folders/rf/2dthxv1d5bn75wfrw2qxkdbh0000gn/T/aws-cdk-testRoXTAY
Applying project template app for csharp
/bin/sh: dotnet: command not found
(node:19271) UnhandledPromiseRejectionWarning: Error: Could not add project AwsCdkTestroBl7N.csproj to solution AwsCdkTestroBl7N.sln. Error code: 127
    at ChildProcess.<anonymous> (/private/var/folders/rf/2dthxv1d5bn75wfrw2qxkdbh0000gn/T/aws-cdk-testroBl7N/tmp/add-project.hook.ts:29:16)
    at Object.onceWrapper (events.js:288:20)
    at ChildProcess.emit (events.js:200:13)
    at ChildProcess.EventEmitter.emit (domain.js:471:20)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:272:12)
(node:19271) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 6)
(node:19271) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

FAILURES: Undone tests (or their setups/teardowns):
- verify "future flags" are added to cdk.json

To fix this, make sure all tests call test.done()

=============================== Coverage summary ===============================
Statements   : 49.57% ( 1165/2350 )
Branches     : 35.22% ( 374/1062 )
Functions    : 50.33% ( 226/449 )
Lines        : 49.75% ( 1105/2221 )
================================================================================
Error: /Users/yamamototatsuya/Projects/aws-cdk/node_modules/nyc/bin/nyc.js --clean /Users/yamamototatsuya/Projects/aws-cdk/node_modules/nodeunit/bin/nodeunit test/api/test.bootstrap.js test/api/test.deploy-stack.js test/api/test.stacks.js test/commands/test.context-command.js test/context-providers/test.amis.js test/context-providers/test.asymmetric-vpcs.js test/context-providers/test.generic.js test/context-providers/test.vpcs.js test/test.account-cache.js test/test.archive.js test/test.assets.js test/test.cdk-docs.js test/test.cdk-doctor.js test/test.cdk-toolkit.js test/test.context.js test/test.diff.js test/test.docker.js test/test.init.js test/test.serialize.js test/test.settings.js test/test.version.js test/test.yaml.js test/util/test.applydefaults.js test/util/test.arrays.js test/util/test.console-formatters.js test/util/test.objects.js exited with error code 1
Tests failed. Total time (9.8s) | /Users/yamamototatsuya/Projects/aws-cdk/node_modules/nyc/bin/nyc.js (9.8s)
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

### Environment

  - **CLI Version      :**
  - **Framework Version:**
  - **OS               :mac**
  - **Language         :**

#### Work around

In mac;
```
brew cask install dotnet
```
and
install SDK from https://aka.ms/dotnet-download.

**Comment by eladb** [comment]
Why was this assigned to @rix0rrr? I believe all language-specific issues should be assigned to @RomainMuller so he will have full visibility.

**Comment by eladb** [comment]
Suspected as P0

**Comment by pahud** [comment]
same here when I run `yarn build` with the lastest `1.17.1`

```
aws-cdk: Switching back to /Users/pahud/github/aws-cdk/packages/aws-cdk cleaning up /var/folders/7m/crqy_4ms6w16bm8vf6787xcw0000gn/T/aws-cdk-testVfjIlE
aws-cdk: ✔ create a TypeScript app project
aws-cdk: Temporary working directory: /var/folders/7m/crqy_4ms6w16bm8vf6787xcw0000gn/T/aws-cdk-testBwkizP
aws-cdk: Switching back to /Users/pahud/github/aws-cdk/packages/aws-cdk cleaning up /var/folders/7m/crqy_4ms6w16bm8vf6787xcw0000gn/T/aws-cdk-testBwkizP
aws-cdk: ✔ create a JavaScript app project
aws-cdk: Temporary working directory: /var/folders/7m/crqy_4ms6w16bm8vf6787xcw0000gn/T/aws-cdk-testNYqFiv
aws-cdk: Switching back to /Users/pahud/github/aws-cdk/packages/aws-cdk cleaning up /var/folders/7m/crqy_4ms6w16bm8vf6787xcw0000gn/T/aws-cdk-testNYqFiv
aws-cdk: ✔ git directory does not throw off the initer!
aws-cdk: Temporary working directory: /var/folders/7m/crqy_4ms6w16bm8vf6787xcw0000gn/T/aws-cdk-testsjXIkX
aws-cdk: Applying project template app for javascript
aws-cdk: Initializing a new git repository...
aws-cdk: Please run npm install!
aws-cdk: # Useful commands
aws-cdk:  * `npm run test`         perform the jest unit tests
aws-cdk:  * `cdk deploy`           deploy this stack to your default AWS account/region
aws-cdk:  * `cdk diff`             compare deployed stack with current state
aws-cdk:  * `cdk synth`            emits the synthesized CloudFormation template
aws-cdk: 
aws-cdk: Applying project template app for typescript
aws-cdk: Please run npm install!
aws-cdk: # Useful commands
aws-cdk:  * `npm run build`   compile typescript to js
aws-cdk:  * `npm run watch`   watch for changes and compile
aws-cdk:  * `npm run test`    perform the jest unit tests
aws-cdk:  * `cdk deploy`      deploy this stack to your default AWS account/region
aws-cdk:  * `cdk diff`        compare deployed stack with current state
aws-cdk:  * `cdk synth`       emits the synthesized CloudFormation template
aws-cdk: 
aws-cdk: Applying project template app for csharp
aws-cdk: /bin/sh: dotnet: command not found
aws-cdk: (node:36947) UnhandledPromiseRejectionWarning: Error: Could not add project AwsCdkTestHyRuyq.csproj to solution AwsCdkTestHyRuyq.sln. Error code: 127
aws-cdk:     at ChildProcess.<anonymous> (/private/var/folders/7m/crqy_4ms6w16bm8vf6787xcw0000gn/T/aws-cdk-testHyRUYQ/tmp/add-project.hook.ts:29:16)
aws-cdk:     at Object.onceWrapper (events.js:300:26)
aws-cdk:     at ChildProcess.emit (events.js:210:5)
aws-cdk:     at ChildProcess.EventEmitter.emit (domain.js:476:20)
aws-cdk:     at Process.ChildProcess._handle.onexit (internal/child_process.js:272:12)
aws-cdk: (node:36947) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 6)
aws-cdk: (node:36947) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
aws-cdk: FAILURES: Undone tests (or their setups/teardowns): 
aws-cdk: - verify "future flags" are added to cdk.json
aws-cdk: To fix this, make sure all tests call test.done()
aws-cdk: =============================== Coverage summary ===============================
aws-cdk: Statements   : 51.62% ( 1213/2350 )
aws-cdk: Branches     : 36.65% ( 390/1064 )
aws-cdk: Functions    : 51.89% ( 233/449 )
aws-cdk: Lines        : 51.91% ( 1153/2221 )
aws-cdk: ================================================================================
aws-cdk: Error: /Users/pahud/github/aws-cdk/node_modules/nyc/bin/nyc.js --clean /Users/pahud/github/aws-cdk/node_modules/nodeunit/bin/nodeunit test/api/test.bootstrap.js test/api/test.deploy-stack.js test/api/test.stacks.js test/commands/test.context-command.js test/context-providers/test.amis.js test/context-providers/test.asymmetric-vpcs.js test/context-providers/test.generic.js test/context-providers/test.vpcs.js test/test.account-cache.js test/test.archive.js test/test.assets.js test/test.cdk-docs.js test/test.cdk-doctor.js test/test.cdk-toolkit.js test/test.context.js test/test.diff.js test/test.docker.js test/test.init.js test/test.serialize.js test/test.settings.js test/test.version.js test/test.yaml.js test/util/test.applydefaults.js test/util/test.arrays.js test/util/test.console-formatters.js test/util/test.objects.js exited with error code 1
aws-cdk: Tests failed. Total time (17.1s) | /Users/pahud/github/aws-cdk/node_modules/nyc/bin/nyc.js (17.0s)
aws-cdk: !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
aws-cdk: npm ERR! Test failed.  See above for more details.
aws-cdk: error Command failed with exit code 1.
aws-cdk: info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
lerna ERR! yarn run build+test exited 1 in 'aws-cdk'
lerna WARN complete Waiting for 8 child processes to exit. CTRL-C to exit immediately.

real    1m7.515s
user    2m39.174s
sys     0m14.505s
❌  Last command failed. Scroll up to see errors in log (search for '!!!!!!!!').
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

Is `dotnet` required for typescript cdk developers? If it is, we should update the `CONTRIBUTING.md`.

**Comment by RomainMuller** [comment]
The requirement for *DotNet Core* is actually mentioned in `CONTRIBUTING.md`'s preprequisites section. It however currently mentions insufficient version requirements (it needs to be >= 3.0).
