### ISSUE TITLE
Permission problem on windows 

### ISSUE THREAD

**Issue by FabioGentile** [aws/aws-cdk#5050]
### The Question

Hello,

I've started using aws-cdk since few days and the firsts initial tests with Typescript went fine. I then switched to Python (not my choice, is the standard language that we are using for this project) and 
every time that i try to launch a command with the cdk cli I get a permission problem.

### Step to reproduce:
From a CMD terminal with admin permission
1. `cdk init --language=python`
2. `python3 -m venv .win_env`
3. `.win_env\Scripts\activate.bat`
4. `pip install -r requirements.txt`
5. `cdk ls --trace -v`

### Output:
```
jsii.errors.JavaScriptError:
  Error: EPERM: operation not permitted, rename 'C:\Users\F87D8~1.GEN\AppData\Local\Temp\jsii-kernel-install-staging-7hkALG\package' -> 'C:\Users\F87D8~1.GEN\AppData\Local\Temp\jsii-kernel-EHW0R3\node_modules\@aws-cdk\core'
      at Object.renameSync (fs.js:643:3)
      at rename (C:\Users\f.gentile\Desktop\test\cdk-t\.win_env\lib\site-packages\jsii\_embedded\jsii\jsii-runtime.js:10408:8)
      at doRename (C:\Users\f.gentile\Desktop\test\cdk-t\.win_env\lib\site-packages\jsii\_embedded\jsii\jsii-runtime.js:10403:10)
      at Object.moveSync (C:\Users\f.gentile\Desktop\test\cdk-t\.win_env\lib\site-packages\jsii\_embedded\jsii\jsii-runtime.js:10394:10)
      at Kernel.load (C:\Users\f.gentile\Desktop\test\cdk-t\.win_env\lib\site-packages\jsii\_embedded\jsii\jsii-runtime.js:7479:16)
      at KernelHost.processRequest (C:\Users\f.gentile\Desktop\test\cdk-t\.win_env\lib\site-packages\jsii\_embedded\jsii\jsii-runtime.js:7285:28)
      at KernelHost.run (C:\Users\f.gentile\Desktop\test\cdk-t\.win_env\lib\site-packages\jsii\_embedded\jsii\jsii-runtime.js:7225:14)
      at Immediate._onImmediate (C:\Users\f.gentile\Desktop\test\cdk-t\.win_env\lib\site-packages\jsii\_embedded\jsii\jsii-runtime.js:7228:37)
      at processImmediate (internal/timers.js:439:21)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "app.py", line 3, in <module>
    from aws_cdk import core
  File "C:\Users\f.gentile\Desktop\test\cdk-t\.win_env\lib\site-packages\aws_cdk\core\__init__.py", line 413, in <module>
    __jsii_assembly__ = jsii.JSIIAssembly.load("@aws-cdk/core", "1.16.3", __name__, "core@1.16.3.jsii.tgz")
  File "C:\Users\f.gentile\Desktop\test\cdk-t\.win_env\lib\site-packages\jsii\_runtime.py", line 40, in load
    _kernel.load(assembly.name, assembly.version, os.fspath(assembly_path))
  File "C:\Users\f.gentile\Desktop\test\cdk-t\.win_env\lib\site-packages\jsii\_kernel\__init__.py", line 209, in load
    self.provider.load(LoadRequest(name=name, version=version, tarball=tarball))
  File "C:\Users\f.gentile\Desktop\test\cdk-t\.win_env\lib\site-packages\jsii\_kernel\providers\process.py", line 330, in load
    return self._process.send(request, LoadResponse)
  File "C:\Users\f.gentile\Desktop\test\cdk-t\.win_env\lib\site-packages\jsii\_kernel\providers\process.py", line 318, in send
    raise JSIIError(resp.error) from JavaScriptError(resp.stack)
jsii.errors.JSIIError: EPERM: operation not permitted, rename 'C:\Users\F87D8~1.GEN\AppData\Local\Temp\jsii-kernel-install-staging-7hkALG\package' -> 'C:\Users\F87D8~1.GEN\AppData\Local\Temp\jsii-kernel-EHW0R3\node_modules\@aws-cdk\core'
Subprocess exited with error 1
Error: Subprocess exited with error 1
    at ChildProcess.<anonymous> (C:\Users\f.gentile\AppData\Roaming\npm\node_modules\aws-cdk\lib\api\cxapp\exec.ts:115:23)
    at ChildProcess.emit (events.js:210:5)
    at ChildProcess.EventEmitter.emit (domain.js:476:20)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:272:12)
```
Full output with `--trace -v`: https://gist.github.com/FabioGentile/29350501e3890305a94feff4b54ff1f8
### Environment

  - **CDK CLI Version:** 1.16.3 (build 8c7f593) 
  - **OS:** Windows 10 Pro 1709
  - **Language:** Python 
  - **NodeJS:** v13.1.0 (same issue with 12.13.0)

### Other information
I'm facing this problem only with Python based project. Using Typescript everything runs fine.
So far i've tried to give full permission on the folder `C:\Users\F87D8~1.GEN\AppData\Local\Temp` to all users, to clean both Node and CDK caches and to use the "native" bash shell on windows (WSL) with the same result.
However i'm not sure if this issue should be reported here or on the JSII repo (https://github.com/aws/jsii/issues).

Thanks in advance for any help

**Comment by FabioGentile** [comment]
After other several try i decided to look at the JSII source code and solved the problem by adding a retry mechanism in case of failure.
I've opened an issue in the other repository: https://github.com/aws/jsii/issues/992

**Comment by tomwaldnz** [comment]
I came across this problem as well. Following your instruction I tried again and it worked.

I also found that I had to use

`cdk bootstrap --profile profilename`

**Comment by joyofdata** [comment]
CDK 1.23.0 on Windows 10 Pro

Have been trying already about 20 times to run `cdk list`. The following is only a few of the error messages.

```
C:\repos\data-lake-infrastructure-as-code\xy_ds_datalake\cdk (xy_ds_datalake/feature/SCANA-344-distance-service-for-oi-p2p-etl -> origin)
(.env-cdk) λ cdk list
jsii.errors.JavaScriptError:
  Error: EPERM: operation not permitted, rename 'C:\Users\RAFFAE~1.VOG\AppData\Local\Temp\jsii-kernel-install-staging-QwC2Kp\package' -> 'C:\Users\RAFFAE~1.VOG\AppData\Local\Temp\jsii-kernel-a9dMAI\node_modules\@aws-cdk\cx-api'
      at Object.renameSync (fs.js:643:3)
      at rename (C:\repos\data-lake-infrastructure-as-code\.env-cdk\lib\site-packages\jsii\_embedded\jsii\jsii-runtime.js:10436:8)
      at doRename (C:\repos\data-lake-infrastructure-as-code\.env-cdk\lib\site-packages\jsii\_embedded\jsii\jsii-runtime.js:10431:10)
      at Object.moveSync (C:\repos\data-lake-infrastructure-as-code\.env-cdk\lib\site-packages\jsii\_embedded\jsii\jsii-runtime.js:10422:10)
      at Kernel.load (C:\repos\data-lake-infrastructure-as-code\.env-cdk\lib\site-packages\jsii\_embedded\jsii\jsii-runtime.js:7493:16)
      at KernelHost.processRequest (C:\repos\data-lake-infrastructure-as-code\.env-cdk\lib\site-packages\jsii\_embedded\jsii\jsii-runtime.js:7296:28)
      at KernelHost.run (C:\repos\data-lake-infrastructure-as-code\.env-cdk\lib\site-packages\jsii\_embedded\jsii\jsii-runtime.js:7236:14)
      at Object.<anonymous> (C:\repos\data-lake-infrastructure-as-code\.env-cdk\lib\site-packages\jsii\_embedded\jsii\jsii-runtime.js:7204:6)
      at __webpack_require__ (C:\repos\data-lake-infrastructure-as-code\.env-cdk\lib\site-packages\jsii\_embedded\jsii\jsii-runtime.js:20:30)
      at C:\repos\data-lake-infrastructure-as-code\.env-cdk\lib\site-packages\jsii\_embedded\jsii\jsii-runtime.js:84:18

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "app.py", line 5, in <module>
    from aws_cdk import core
  File "C:\repos\data-lake-infrastructure-as-code\.env-cdk\lib\site-packages\aws_cdk\core\__init__.py", line 411, in <module>
    import aws_cdk.cx_api
  File "C:\repos\data-lake-infrastructure-as-code\.env-cdk\lib\site-packages\aws_cdk\cx_api\__init__.py", line 31, in <module>
    __jsii_assembly__ = jsii.JSIIAssembly.load("@aws-cdk/cx-api", "1.23.0", __name__, "cx-api@1.23.0.jsii.tgz")
  File "C:\repos\data-lake-infrastructure-as-code\.env-cdk\lib\site-packages\jsii\_runtime.py", line 40, in load
    _kernel.load(assembly.name, assembly.version, os.fspath(assembly_path))
  File "C:\repos\data-lake-infrastructure-as-code\.env-cdk\lib\site-packages\jsii\_kernel\__init__.py", line 215, in load
    self.provider.load(LoadRequest(name=name, version=version, tarball=tarball))
  File "C:\repos\data-lake-infrastructure-as-code\.env-cdk\lib\site-packages\jsii\_kernel\providers\process.py", line 330, in load
    return self._process.send(request, LoadResponse)
  File "C:\repos\data-lake-infrastructure-as-code\.env-cdk\lib\site-packages\jsii\_kernel\providers\process.py", line 318, in send
    raise JSIIError(resp.error) from JavaScriptError(resp.stack)
jsii.errors.JSIIError: EPERM: operation not permitted, rename 'C:\Users\RAFFAE~1.VOG\AppData\Local\Temp\jsii-kernel-install-staging-QwC2Kp\package' -> 'C:\Users\RAFFAE~1.VOG\AppData\Local\Temp\jsii-kernel-a9dMAI\node_modules\@aws-cdk\cx-api'
Subprocess exited with error 1

C:\repos\data-lake-infrastructure-as-code\xy_ds_datalake\cdk (xy_ds_datalake/feature/SCANA-344-distance-service-for-oi-p2p-etl -> origin)
(.env-cdk) λ cdk list
jsii.errors.JavaScriptError:
  Error: EPERM: operation not permitted, rename 'C:\Users\RAFFAE~1.VOG\AppData\Local\Temp\jsii-kernel-install-staging-DILQOQ\package' -> 'C:\Users\RAFFAE~1.VOG\AppData\Local\Temp\jsii-kernel-uvMm1v\node_modules\@aws-cdk\aws-apigateway'
      at Object.renameSync (fs.js:643:3)
      at rename (C:\repos\data-lake-infrastructure-as-code\.env-cdk\lib\site-packages\jsii\_embedded\jsii\jsii-runtime.js:10436:8)
      at doRename (C:\repos\data-lake-infrastructure-as-code\.env-cdk\lib\site-packages\jsii\_embedded\jsii\jsii-runtime.js:10431:10)
      at Object.moveSync (C:\repos\data-lake-infrastructure-as-code\.env-cdk\lib\site-packages\jsii\_embedded\jsii\jsii-runtime.js:10422:10)
      at Kernel.load (C:\repos\data-lake-infrastructure-as-code\.env-cdk\lib\site-packages\jsii\_embedded\jsii\jsii-runtime.js:7493:16)
      at KernelHost.processRequest (C:\repos\data-lake-infrastructure-as-code\.env-cdk\lib\site-packages\jsii\_embedded\jsii\jsii-runtime.js:7296:28)
      at KernelHost.run (C:\repos\data-lake-infrastructure-as-code\.env-cdk\lib\site-packages\jsii\_embedded\jsii\jsii-runtime.js:7236:14)
      at Immediate._onImmediate (C:\repos\data-lake-infrastructure-as-code\.env-cdk\lib\site-packages\jsii\_embedded\jsii\jsii-runtime.js:7239:37)
      at processImmediate (internal/timers.js:439:21)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "app.py", line 9, in <module>
    from xy_ds_datalake.stacks import BaseStack, DataLakeStack
  File "c:\repos\data-lake-infrastructure-as-code\xy_ds_datalake\cdk\src\xy_ds_datalake\stacks\__init__.py", line 1, in <module>
    from .base import BaseStack
  File "c:\repos\data-lake-infrastructure-as-code\xy_ds_datalake\cdk\src\xy_ds_datalake\stacks\base\__init__.py", line 1, in <module>
    from .stack import BaseStack
  File "c:\repos\data-lake-infrastructure-as-code\xy_ds_datalake\cdk\src\xy_ds_datalake\stacks\base\stack.py", line 8, in <module>
    from xy_aws_shared.etl_model.fargate_helper import (
  File "c:\repos\data-lake-infrastructure-as-code\xy_aws_shared\src\xy_aws_shared\etl_model\fargate_helper.py", line 1, in <module>
    from aws_cdk import (aws_ec2 as ec2, aws_ecs as ecs, aws_iam as iam, core)
  File "C:\repos\data-lake-infrastructure-as-code\.env-cdk\lib\site-packages\aws_cdk\aws_ecs\__init__.py", line 637, in <module>
    import aws_cdk.aws_route53_targets
  File "C:\repos\data-lake-infrastructure-as-code\.env-cdk\lib\site-packages\aws_cdk\aws_route53_targets\__init__.py", line 98, in <module>
    import aws_cdk.aws_apigateway
  File "C:\repos\data-lake-infrastructure-as-code\.env-cdk\lib\site-packages\aws_cdk\aws_apigateway\__init__.py", line 626, in <module>
    __jsii_assembly__ = jsii.JSIIAssembly.load("@aws-cdk/aws-apigateway", "1.23.0", __name__, "aws-apigateway@1.23.0.jsii.tgz")
  File "C:\repos\data-lake-infrastructure-as-code\.env-cdk\lib\site-packages\jsii\_runtime.py", line 40, in load
    _kernel.load(assembly.name, assembly.version, os.fspath(assembly_path))
  File "C:\repos\data-lake-infrastructure-as-code\.env-cdk\lib\site-packages\jsii\_kernel\__init__.py", line 215, in load
    self.provider.load(LoadRequest(name=name, version=version, tarball=tarball))
  File "C:\repos\data-lake-infrastructure-as-code\.env-cdk\lib\site-packages\jsii\_kernel\providers\process.py", line 330, in load
    return self._process.send(request, LoadResponse)
  File "C:\repos\data-lake-infrastructure-as-code\.env-cdk\lib\site-packages\jsii\_kernel\providers\process.py", line 318, in send
    raise JSIIError(resp.error) from JavaScriptError(resp.stack)
jsii.errors.JSIIError: EPERM: operation not permitted, rename 'C:\Users\RAFFAE~1.VOG\AppData\Local\Temp\jsii-kernel-install-staging-DILQOQ\package' -> 'C:\Users\RAFFAE~1.VOG\AppData\Local\Temp\jsii-kernel-uvMm1v\node_modules\@aws-cdk\aws-apigateway'
Subprocess exited with error 1

C:\repos\data-lake-infrastructure-as-code\xy_ds_datalake\cdk (xy_ds_datalake/feature/SCANA-344-distance-service-for-oi-p2p-etl -> origin)
(.env-cdk) λ cdk list
XY Lambda Layer requirements up-to-date.
Traceback (most recent call last):
  File "app.py", line 34, in <module>
    datalake_dev = DataLakeStack(app, f"data-lake-{env_name}", env=cdk_env, tags=tags)
  File "C:\repos\data-lake-infrastructure-as-code\.env-cdk\lib\site-packages\jsii\_runtime.py", line 66, in __call__
    inst = super().__call__(*args, **kwargs)
  File "c:\repos\data-lake-infrastructure-as-code\xy_ds_datalake\cdk\src\xy_ds_datalake\stacks\data_lake\data_lake.py", line 153, in __init__
    self._aws_lambda_layer = xy_lambda_layer._create_awsdatawrangler_layer(self)
  File "c:\repos\data-lake-infrastructure-as-code\xy_lambda_layer\src\xy_lambda_layer\__init__.py", line 52, in _create_awsdatawrangler_layer
    layer_file = _aws_data_wrangler._build_layer()
  File "c:\repos\data-lake-infrastructure-as-code\xy_lambda_layer\src\xy_lambda_layer\_aws_data_wrangler.py", line 68, in _build_layer
    latest_release_url = _get_latest_release_download_url()
  File "c:\repos\data-lake-infrastructure-as-code\xy_lambda_layer\src\xy_lambda_layer\_aws_data_wrangler.py", line 29, in _get_latest_release_download_url
    with urllib.request.urlopen(LATEST_RELEASE_URL) as response:
  File "C:\Users\raffael.vogler\AppData\Local\Programs\Python\Python36\lib\urllib\request.py", line 223, in urlopen
    return opener.open(url, data, timeout)
  File "C:\Users\raffael.vogler\AppData\Local\Programs\Python\Python36\lib\urllib\request.py", line 532, in open
    response = meth(req, response)
  File "C:\Users\raffael.vogler\AppData\Local\Programs\Python\Python36\lib\urllib\request.py", line 642, in http_response
    'http', request, response, code, msg, hdrs)
  File "C:\Users\raffael.vogler\AppData\Local\Programs\Python\Python36\lib\urllib\request.py", line 570, in error
    return self._call_chain(*args)
  File "C:\Users\raffael.vogler\AppData\Local\Programs\Python\Python36\lib\urllib\request.py", line 504, in _call_chain
    result = func(*args)
  File "C:\Users\raffael.vogler\AppData\Local\Programs\Python\Python36\lib\urllib\request.py", line 650, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 403: Forbidden
Subprocess exited with error 1

C:\repos\data-lake-infrastructure-as-code\xy_ds_datalake\cdk (xy_ds_datalake/feature/SCANA-344-distance-service-for-oi-p2p-etl -> origin)
(.env-cdk) λ cdk list
jsii.errors.JavaScriptError:
  Error: EPERM: operation not permitted, rename 'C:\Users\RAFFAE~1.VOG\AppData\Local\Temp\jsii-kernel-install-staging-oOT22i\package' -> 'C:\Users\RAFFAE~1.VOG\AppData\Local\Temp\jsii-kernel-AwWuNw\node_modules\@aws-cdk\aws-lambda'
      at Object.renameSync (fs.js:643:3)
      at rename (C:\repos\data-lake-infrastructure-as-code\.env-cdk\lib\site-packages\jsii\_embedded\jsii\jsii-runtime.js:10436:8)
      at doRename (C:\repos\data-lake-infrastructure-as-code\.env-cdk\lib\site-packages\jsii\_embedded\jsii\jsii-runtime.js:10431:10)
      at Object.moveSync (C:\repos\data-lake-infrastructure-as-code\.env-cdk\lib\site-packages\jsii\_embedded\jsii\jsii-runtime.js:10422:10)
      at Kernel.load (C:\repos\data-lake-infrastructure-as-code\.env-cdk\lib\site-packages\jsii\_embedded\jsii\jsii-runtime.js:7493:16)
      at KernelHost.processRequest (C:\repos\data-lake-infrastructure-as-code\.env-cdk\lib\site-packages\jsii\_embedded\jsii\jsii-runtime.js:7296:28)
      at KernelHost.run (C:\repos\data-lake-infrastructure-as-code\.env-cdk\lib\site-packages\jsii\_embedded\jsii\jsii-runtime.js:7236:14)
      at Immediate._onImmediate (C:\repos\data-lake-infrastructure-as-code\.env-cdk\lib\site-packages\jsii\_embedded\jsii\jsii-runtime.js:7239:37)
      at processImmediate (internal/timers.js:439:21)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "app.py", line 9, in <module>
    from xy_ds_datalake.stacks import BaseStack, DataLakeStack
  File "c:\repos\data-lake-infrastructure-as-code\xy_ds_datalake\cdk\src\xy_ds_datalake\stacks\__init__.py", line 1, in <module>
    from .base import BaseStack
  File "c:\repos\data-lake-infrastructure-as-code\xy_ds_datalake\cdk\src\xy_ds_datalake\stacks\base\__init__.py", line 1, in <module>
    from .stack import BaseStack
  File "c:\repos\data-lake-infrastructure-as-code\xy_ds_datalake\cdk\src\xy_ds_datalake\stacks\base\stack.py", line 8, in <module>
    from xy_aws_shared.etl_model.fargate_helper import (
  File "c:\repos\data-lake-infrastructure-as-code\xy_aws_shared\src\xy_aws_shared\etl_model\fargate_helper.py", line 1, in <module>
    from aws_cdk import (aws_ec2 as ec2, aws_ecs as ecs, aws_iam as iam, core)
  File "C:\repos\data-lake-infrastructure-as-code\.env-cdk\lib\site-packages\aws_cdk\aws_ecs\__init__.py", line 623, in <module>
    import aws_cdk.aws_autoscaling
  File "C:\repos\data-lake-infrastructure-as-code\.env-cdk\lib\site-packages\aws_cdk\aws_autoscaling\__init__.py", line 264, in <module>
    import aws_cdk.aws_elasticloadbalancingv2
  File "C:\repos\data-lake-infrastructure-as-code\.env-cdk\lib\site-packages\aws_cdk\aws_elasticloadbalancingv2\__init__.py", line 283, in <module>
    import aws_cdk.aws_certificatemanager
  File "C:\repos\data-lake-infrastructure-as-code\.env-cdk\lib\site-packages\aws_cdk\aws_certificatemanager\__init__.py", line 103, in <module>
    import aws_cdk.aws_cloudformation
  File "C:\repos\data-lake-infrastructure-as-code\.env-cdk\lib\site-packages\aws_cdk\aws_cloudformation\__init__.py", line 125, in <module>
    import aws_cdk.aws_lambda
  File "C:\repos\data-lake-infrastructure-as-code\.env-cdk\lib\site-packages\aws_cdk\aws_lambda\__init__.py", line 262, in <module>
    __jsii_assembly__ = jsii.JSIIAssembly.load("@aws-cdk/aws-lambda", "1.23.0", __name__, "aws-lambda@1.23.0.jsii.tgz")
  File "C:\repos\data-lake-infrastructure-as-code\.env-cdk\lib\site-packages\jsii\_runtime.py", line 40, in load
    _kernel.load(assembly.name, assembly.version, os.fspath(assembly_path))
  File "C:\repos\data-lake-infrastructure-as-code\.env-cdk\lib\site-packages\jsii\_kernel\__init__.py", line 215, in load
    self.provider.load(LoadRequest(name=name, version=version, tarball=tarball))
  File "C:\repos\data-lake-infrastructure-as-code\.env-cdk\lib\site-packages\jsii\_kernel\providers\process.py", line 330, in load
    return self._process.send(request, LoadResponse)
  File "C:\repos\data-lake-infrastructure-as-code\.env-cdk\lib\site-packages\jsii\_kernel\providers\process.py", line 318, in send
    raise JSIIError(resp.error) from JavaScriptError(resp.stack)
jsii.errors.JSIIError: EPERM: operation not permitted, rename 'C:\Users\RAFFAE~1.VOG\AppData\Local\Temp\jsii-kernel-install-staging-oOT22i\package' -> 'C:\Users\RAFFAE~1.VOG\AppData\Local\Temp\jsii-kernel-AwWuNw\node_modules\@aws-cdk\aws-lambda'
Subprocess exited with error 1
```

**Comment by vpfaiz** [comment]
Running the code in Admin mode resolved this issues for me on Windows 11. I will not recommend that but that might help your investigation. I had to run the VS Code in Admin mode for my setup.
