### ISSUE TITLE
API Gateway CORS preflight causes synth error

### ISSUE THREAD

**Issue by lukehedger** [aws/aws-cdk#5232]
Running `cdk synth` on a stack that uses the API Gateway Construct (`LambdaRestApi`) with CORS preflight enabled throws an error.

### Reproduction Steps

```typescript
new LambdaRestApi(this, "SomeEndpoint", {
  defaultCorsPreflightOptions: {
    allowOrigins: Cors.ALL_ORIGINS,
    allowMethods: Cors.ALL_METHODS
  },
  handler: someLambda
});
```

### Error Log

```
$ cdk synth
some-stack/node_modules/@aws-cdk/core/lib/construct.js:395
  throw new Error(`There is already a Construct with name '${childName}' in ${typeName}${name.length > 0 ? ' [' + name + ']' : ''}`);

Error: There is already a Construct with name 'OPTIONS' in RootResource [Default]
  at ConstructNode.addChild (some-stack/node_modules/@aws-cdk/core/lib/construct.js:395:19)
  at new ConstructNode (some-stack/node_modules/@aws-cdk/core/lib/construct.js:32:24)
  at new Construct (some-stack/node_modules/@aws-cdk/core/lib/construct.js:435:21)
  at new Resource (some-stack/node_modules/@aws-cdk/core/lib/resource.js:13:9)
  at new Method (some-stack/node_modules/@aws-cdk/aws-apigateway/lib/method.js:10:9)
  at RootResource.addMethod (some-stack/node_modules/@aws-cdk/aws-apigateway/lib/resource.js:17:16)
  at ProxyResource.addMethod (some-stack/node_modules/@aws-cdk/aws-apigateway/lib/resource.js:216:33)
  at ProxyResource.addCorsPreflight (some-stack/node_modules/@aws-cdk/aws-apigateway/lib/resource.js:93:21)
  at new Resource (some-stack/node_modules/@aws-cdk/aws-apigateway/lib/resource.js:190:18)
  at new ProxyResource (some-stack/node_modules/@aws-cdk/aws-apigateway/lib/resource.js:201:9)
```

### Environment

  - **CLI Version      :** 1.18.0 (build bc924bc)
  - **Framework Version:** 1.18.0
  - **OS               :** macOS
  - **Language         :** TypeScript

--- 

This is :bug: Bug Report

**Comment by eladb** [comment]
Seems like the CORS OPTIONS conflicts with another construct named "OPTIONS"

**Comment by halvardssm** [comment]
Hi! Sorry to reawaken such an old issue, but I am facing the exact same problem on `1.149.0`. Should I create a new issue for this?

**Comment by amirmishani** [comment]
I'm also getting the same error on `2.21.0`.

**Comment by prazian** [comment]
Same here on `2.24.1`

**Comment by hhimanshu** [comment]
Any resolutions to this issue?
