### ISSUE TITLE
Can't create FargateService with VPC/subnets created in another CF stack

### ISSUE THREAD

**Issue by jishi** [aws/aws-cdk#5254]
I'm trying to wire up a Fargate service using CDK, but running into an error which looks like a bug.

### Reproduction Steps

```
    const cluster = Cluster.fromClusterAttributes(this, 'Cluster', {
      clusterName: Fn.importValue('ElefantClusterName')
    });

    const taskDefinition = new FargateTaskDefinition(this, 'TaskDefinition', {
      cpu: 256,
      family: 'elefant-ungapped',
      memoryMiB: 512,
    });

    taskDefinition.addContainer('Container', {
      image: ContainerImage.fromRegistry('elefant-ungapped')
    });
    
    const subnet1 = Subnet.fromSubnetAttributes(this, 'subnet1', {
      subnetId: Fn.importValue('SubnetExternalAZ1')
    });

    const subnet2 = Subnet.fromSubnetAttributes(this, 'subnet2', {
      subnetId: Fn.importValue('SubnetExternalAZ2')
    });
    const service = new FargateService(this, 'Service', {
      cluster,
      taskDefinition,
      desiredCount: 1,
      assignPublicIp: true,
      vpcSubnets: {
        subnets: [subnet1, subnet2]
      }

    });
```
The subnets are exported from another, vanilla Cloudformation stack. The cluster name is also exported from another stack. 

### Error Log

```
/Users/jimmy/Documents/source/reform/elefant-ungapped/node_modules/@aws-cdk/aws-ec2/lib/security-group.js:136
            vpcId: props.vpc.vpcId,
                             ^

TypeError: Cannot read property 'vpcId' of undefined
    at new SecurityGroup (/Users/jimmy/Documents/source/reform/elefant-ungapped/node_modules/@aws-cdk/aws-ec2/lib/security-group.js:136:30)
    at FargateService.configureAwsVpcNetworking (/Users/jimmy/Documents/source/reform/elefant-ungapped/node_modules/@aws-cdk/aws-ecs/lib/base/base-service.js:303:29)
    at new FargateService (/Users/jimmy/Documents/source/reform/elefant-ungapped/node_modules/@aws-cdk/aws-ecs/lib/fargate/fargate-service.js:40:14)
    at new UngappedStack (/Users/jimmy/Documents/source/reform/elefant-ungapped/cloudformation/stack.js:57:21)
    at Object.<anonymous> (/Users/jimmy/Documents/source/reform/elefant-ungapped/cloudformation/stack.js:74:1)
    at Module._compile (internal/modules/cjs/loader.js:936:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:947:10)
    at Module.load (internal/modules/cjs/loader.js:790:32)
    at Function.Module._load (internal/modules/cjs/loader.js:703:12)
    at Function.Module.runMain (internal/modules/cjs/loader.js:999:10)
```

### Environment

  - **CLI Version      : ws-cli/1.16.260**
  - **Framework Version: cdk 1.18.0**
  - **OS               : MacOS**
  - **Language         : Node.js v12.9.0**

### Other

The only thing I specify for the service that touches the VPC, is the Cluster (which is already assigned a VPC afaik), and the Subnets (which also belongs to a VPC).

Why vpcId is undefined is unclear, and this seems to relate to securityGroups which is flagged as an optional parameter. 

In a regular cloudformation template, securityGroup is not required and if supplying an empty object for it, I get this instead:  

```
/Users/jimmy/Documents/source/reform/elefant-ungapped/node_modules/@aws-cdk/aws-ecs/lib/base/base-service.js:309
                subnets: vpc.selectSubnets(vpcSubnets).subnetIds,
                             ^

TypeError: Cannot read property 'selectSubnets' of undefined
    at FargateService.configureAwsVpcNetworking (/Users/jimmy/Documents/source/reform/elefant-ungapped/node_modules/@aws-cdk/aws-ecs/lib/base/base-service.js:309:30)
    at new FargateService (/Users/jimmy/Documents/source/reform/elefant-ungapped/node_modules/@aws-cdk/aws-ecs/lib/fargate/fargate-service.js:40:14)
    at new UngappedStack (/Users/jimmy/Documents/source/reform/elefant-ungapped/cloudformation/stack.js:57:21)
    at Object.<anonymous> (/Users/jimmy/Documents/source/reform/elefant-ungapped/cloudformation/stack.js:75:1)
```
--- 

This is :bug: Bug Report

**Comment by bvtujo** [comment]
Hi, thanks for the info! Looking at your source code, I see a small issue in the signature of the `Cluster.fromClusterAttributes` method. There are two required parameters other than `clusterName`, which you provided--`vpc` and `securityGroups`. 

Can you try filling those out, then deploying the stack again? It looks like this might alleviate the problem in the first line of your stack trace, where vpc is undefined. 

You can provide these by also importing them--the `vpc` parameter will accept an imported VPC, such as the output of `Vpc.fromVpcAttributes()`, and `securityGroups` can be passed an empty array if there are no security groups attached to the cluster. If you are deterministically creating security groups in your other stack, be sure to import them individually, and provide them as an array to the `ClusterAttributes` object. See the [documentation](https://docs.aws.amazon.com/cdk/api/latest/typescript/api/aws-ecs/clusterattributes.html#aws_ecs_ClusterAttributes) for more details on cluster attributes.

**Comment by bvtujo** [comment]
Closing this for now. If you're still experiencing problems, please feel free to reopen.
