### ISSUE TITLE
Secret.from_secret_arn resolves to IResource instead of Secret

### ISSUE THREAD

**Issue by w-** [aws/aws-cdk#5255]
I'm attempting to pass database credentials from my RDS instance (created via CDK) to my fargate service.

one of the parameters to `ApplicationLoadBalancedTaskImageOptions` is `secrets`
https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-ecs-patterns.ApplicationLoadBalancedTaskImageOptions.html#secrets

When I attempt to pass the Secret using the secret arn from the rds stack, I get the following error
```
@aws-cdk/core.Resource is not convertible to @aws-cdk/aws-ecs.Secret
```

### Reproduction Steps
sample code

```
secrets={
                "DB_CONFIG": aws_secretsmanager.Secret.from_secret_arn(
                    self,
                    'MyDatabaseSecret',
                    rds_stack.db_instance.secret.secret_arn
                )
            }
```

also tried

```
secrets={
                "DB_CONFIG": aws_secretsmanager.Secret.from_secret_attributes(
                    self,
                    'MyDatabaseSecret',
                    secret_arn=rds_stack.db_instance.secret.secret_arn
                )
            }
```

### Error Log

```
jsii.errors.JavaScriptError:
  Error: Object of type @aws-cdk/core.Resource is not convertible to @aws-cdk/aws-ecs.Secret
      at Object.deserialize (<my path>/cdk/.venv/lib/python3.7/site-packages/jsii/_embedded/jsii/jsii-runtime.js:6886:27)
      at Kernel._toSandbox (<my path>/cdk/.venv/lib/python3.7/site-packages/jsii/_embedded/jsii/jsii-runtime.js:8111:61)
      at v (<my path>/cdk/.venv/lib/python3.7/site-packages/jsii/_embedded/jsii/jsii-runtime.js:6758:72)
      at mapValues (<my path>/cdk/.venv/lib/python3.7/site-packages/jsii/_embedded/jsii/jsii-runtime.js:7101:27)
      at Object.deserialize (<my path>/cdk/.venv/lib/python3.7/site-packages/jsii/_embedded/jsii/jsii-runtime.js:6758:28)
      at Kernel._toSandbox (<my path>/cdk/.venv/lib/python3.7/site-packages/jsii/_embedded/jsii/jsii-runtime.js:8111:61)
      at mapValues (<my path>/cdk/.venv/lib/python3.7/site-packages/jsii/_embedded/jsii/jsii-runtime.js:6841:29)
      at mapValues (<my path>/cdk/.venv/lib/python3.7/site-packages/jsii/_embedded/jsii/jsii-runtime.js:7101:27)
      at Object.deserialize (<my path>/cdk/.venv/lib/python3.7/site-packages/jsii/_embedded/jsii/jsii-runtime.js:6837:20)
      at Kernel._wrapSandboxCode (<my path>/cdk/.venv/lib/python3.7/site-packages/jsii/_embedded/jsii/jsii-runtime.js:8205:19)
      at Kernel._create (<my path>/cdk/.venv/lib/python3.7/site-packages/jsii/_embedded/jsii/jsii-runtime.js:7749:26)
      at Kernel.create (<my path>/cdk/.venv/lib/python3.7/site-packages/jsii/_embedded/jsii/jsii-runtime.js:7503:21)
      at KernelHost.processRequest (<my path>/cdk/.venv/lib/python3.7/site-packages/jsii/_embedded/jsii/jsii-runtime.js:7293:28)
      at KernelHost.run (<my path>/cdk/.venv/lib/python3.7/site-packages/jsii/_embedded/jsii/jsii-runtime.js:7233:14)
      at Immediate.setImmediate [as _onImmediate] (<my path>/cdk/.venv/lib/python3.7/site-packages/jsii/_embedded/jsii/jsii-runtime.js:7236:37)
      at runCallback (timers.js:705:18)
      at tryOnImmediate (timers.js:676:5)
      at processImmediate (timers.js:658:5)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "app.py", line 100, in <module>
    "container_port": CONTAINER_PORT,
  File "<my path>/cdk/.venv/lib/python3.7/site-packages/jsii/_runtime.py", line 66, in __call__
    inst = super().__call__(*args, **kwargs)
  File "<my path>/cdk/stacks/ecs_stack.py", line 65, in __init__
    domain_zone=zone
  File "<my path>/cdk/.venv/lib/python3.7/site-packages/jsii/_runtime.py", line 66, in __call__
    inst = super().__call__(*args, **kwargs)
  File "<my path>/cdk/.venv/lib/python3.7/site-packages/aws_cdk/aws_ecs_patterns/__init__.py", line 429, in __init__
    jsii.create(ApplicationLoadBalancedFargateService, self, [scope, id, props])
  File "<my path>/cdk/.venv/lib/python3.7/site-packages/jsii/_kernel/__init__.py", line 223, in create
    interfaces=[iface.__jsii_type__ for iface in getattr(klass, "__jsii_ifaces__", [])],
  File "<my path>/cdk/.venv/lib/python3.7/site-packages/jsii/_kernel/providers/process.py", line 333, in create
    return self._process.send(request, CreateResponse)
  File "<my path>/cdk/.venv/lib/python3.7/site-packages/jsii/_kernel/providers/process.py", line 318, in send
    raise JSIIError(resp.error) from JavaScriptError(resp.stack)
jsii.errors.JSIIError: Object of type @aws-cdk/core.Resource is not convertible to @aws-cdk/aws-ecs.Secret

```

### Environment

  - **CLI Version      :1.18.0 (build bc924bc)**
  - **Framework Version: 1.18.0**
  - **OS               : ubuntu 16**
  - **Language         : english**

### Other

--- 

This is :bug: Bug Report

**Comment by RomainMuller** [comment]
Can you provide a trace when running with `JSII_DEBUG=1` environment variable set?

**Comment by SomayaB** [comment]
Closing this issue since there hasn't been a response. Feel free to reopen.
