### ISSUE TITLE
Can't generate Origin Access Identity using Cfn resource in C#

### ISSUE THREAD

**Issue by drch-** [aws/aws-cdk#5318]
I'm trying to add a bucket policy to allow access to CloudFront's Origin Access Identity.  As there is no support as a construct, I'm attempting to add it with the CfnXXX classes, but am getting the error
 `Missing required properties for @aws-cdk/aws-cloudfront.CfnCloudFrontOriginAccessIdentityProps: cloudFrontOriginAccessIdentityConfig`

### Reproduction Steps
```csharp
using System.Collections.Generic;
using Amazon.CDK;
using Amazon.CDK.AWS.CloudFront;
using Amazon.CDK.AWS.S3;

namespace Cdkcf
{
    public class CdkcfStack : Stack
    {
        internal CdkcfStack(Construct scope, string id, IStackProps props = null) : base(scope, id, props)
        {
            var websiteBucket = new Bucket(this, "www-content", new BucketProps()
            {
            });

            var originAccessIdentity = new CfnCloudFrontOriginAccessIdentity(this, "cfn-oai", new CfnCloudFrontOriginAccessIdentityProps()
            {
                CloudFrontOriginAccessIdentityConfig = new Dictionary<string, string>
                {
                        ["comment"] = "the comment"
                }
            });
        }
    }
}
```

### Error Log

```
Unhandled exception. Amazon.JSII.Runtime.JsiiException: Missing required properties for @aws-cdk/aws-cloudfront.CfnCloudFrontOriginAccessIdentityProps: cloudFrontOriginAccessIdentityConfig
   at Amazon.JSII.Runtime.Services.Client.TryDeserialize[TResponse](String responseJson)
   at Amazon.JSII.Runtime.Services.Client.ReceiveResponse[TResponse]()
   at Amazon.JSII.Runtime.Services.Client.Send[TRequest,TResponse](TRequest requestObject)
   at Amazon.JSII.Runtime.Services.Client.Create(CreateRequest request)
   at Amazon.JSII.Runtime.Services.Client.Create(String fullyQualifiedName, Object[] arguments, Override[] overrides, String[] interfaces)
   at Amazon.JSII.Runtime.Deputy.DeputyBase..ctor(DeputyProps props)
   at Amazon.CDK.Construct..ctor(DeputyProps props)
   at Amazon.CDK.CfnElement..ctor(DeputyProps props)
   at Amazon.CDK.CfnRefElement..ctor(DeputyProps props)
   at Amazon.CDK.CfnResource..ctor(DeputyProps props)
   at Amazon.CDK.AWS.CloudFront.CfnCloudFrontOriginAccessIdentity..ctor(Construct scope, String id, ICfnCloudFrontOriginAccessIdentityProps props)
   at Cdkcf.CdkcfStack..ctor(Construct scope, String id, IStackProps props)
   at Cdkcf.Program.Main(String[] args) 
```

### Environment

* **CLI Version      :** aws-cli/1.16.276 Python/3.7.5 Darwin/18.7.0 botocore/1.13.12
* **Framework Version:** 1.18.0 (build [bc924bc])
* **OS               :** macOS
* **Language         :** C#

--- 

This is :bug: Bug Report

**Comment by drch-** [comment]
Dug into the docs and saw the type is expected to be a  CfnCloudFrontOriginAccessIdentity.CloudFrontOriginAccessIdentityConfigProperty

The following synth's fine

```csharp

var originAccessIdentity = new CfnCloudFrontOriginAccessIdentity(this, "cfn-oai", new CfnCloudFrontOriginAccessIdentityProps()
{
    CloudFrontOriginAccessIdentityConfig = new CfnCloudFrontOriginAccessIdentity.CloudFrontOriginAccessIdentityConfigProperty
    {
        Comment = "the comment"
    }
});
```
