### ISSUE TITLE
cdk authentication raises SignatureDoesNotMatch error due to wrong date

### ISSUE THREAD

**Issue by protocarl** [aws/aws-cdk#5384]
cdk bootstrap raises SignatureDoesNotMatch error due to wrong date calculation on signature

### Reproduction Steps

`cdk bootstrap -v`

### Error Log

`Need to perform AWS calls for account XXXXXXXXXXXX, but no credentials found. Tried: default credentials.`

The stack trace reveals:

```
Looking up default account ID from STS
Unable to determine the default AWS account (did you configure "aws configure"?): { SignatureDoesNotMatch: Signature expired: 20191011T084508Z is now earlier than 20191212T053046Z (20191212T054546Z - 15 min.)
    at Request.extractError (/usr/local/Cellar/aws-cdk/1.18.0/libexec/lib/node_modules/aws-cdk/node_modules/aws-sdk/lib/protocol/query.js:50:29)
    at Request.callListeners (/usr/local/Cellar/aws-cdk/1.18.0/libexec/lib/node_modules/aws-cdk/node_modules/aws-sdk/lib/sequential_executor.js:106:20)
    at Request.emit (/usr/local/Cellar/aws-cdk/1.18.0/libexec/lib/node_modules/aws-cdk/node_modules/aws-sdk/lib/sequential_executor.js:78:10)
    at Request.emit (/usr/local/Cellar/aws-cdk/1.18.0/libexec/lib/node_modules/aws-cdk/node_modules/aws-sdk/lib/request.js:683:14)
    at Request.transition (/usr/local/Cellar/aws-cdk/1.18.0/libexec/lib/node_modules/aws-cdk/node_modules/aws-sdk/lib/request.js:22:10)
    at AcceptorStateMachine.runTo (/usr/local/Cellar/aws-cdk/1.18.0/libexec/lib/node_modules/aws-cdk/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at /usr/local/Cellar/aws-cdk/1.18.0/libexec/lib/node_modules/aws-cdk/node_modules/aws-sdk/lib/state_machine.js:26:10
    at Request.<anonymous> (/usr/local/Cellar/aws-cdk/1.18.0/libexec/lib/node_modules/aws-cdk/node_modules/aws-sdk/lib/request.js:38:9)
    at Request.<anonymous> (/usr/local/Cellar/aws-cdk/1.18.0/libexec/lib/node_modules/aws-cdk/node_modules/aws-sdk/lib/request.js:685:12)
    at Request.callListeners (/usr/local/Cellar/aws-cdk/1.18.0/libexec/lib/node_modules/aws-cdk/node_modules/aws-sdk/lib/sequential_executor.js:116:18)
  message:
   'Signature expired: 20191011T084508Z is now earlier than 20191212T053046Z (20191212T054546Z - 15 min.)',
  code: 'SignatureDoesNotMatch',
  time: 2019-10-11T08:45:09.379Z,
  requestId: 'a4a074b1-1ca2-11ea-be22-9d8ac1202436',
  statusCode: 403,
  retryable: true }
```

Note the dates on the `Signature expired` message and `time`.  They are off by almost 2 months.
That wrong date is generated by the cdk client and is also passed via the `X-Amz-Date` header when `cdk bootstrap` sends a request to sts.amazonaws.com

Running date on my machine with `date -u +"%Y%m%dT%H%M%SZ"` returns the correct date of `20191212T055156Z`, so I don't think that is the problem.

I've also been using awscli with a standard ~/.aws/{config,credentials}  setup without any problems with authentication.

### Environment

  - **CLI Version      :1.18.0** installed with brew
  - **Framework Version:1.18.0**
  - **OS               :macos**
  - **Language         :java**

--- 

This is :bug: Bug Report

**Comment by protocarl** [comment]
I think I have found the issue.

I installed cdk with brew which also installed node as dependency.

However, `/usr/local/bin/cdk` contains

```
#!/usr/bin/env node
require('./cdk.js');
```

which will run whichever node is in the current path.  I have graalvm installed which has its own implementation of node in my path.  By removing the the graalvm node from my path, the cdk launch script uses the correct version of node that was installed with brew.

As to why graalvm's node gives the incorrect date in the auth signature, that is another question.

I am happy to use the brew installed version of node to use cdk.  Feel free to close.

**Comment by shivlaks** [comment]
interesting! and good to know in case we see another occurrence from users who get bit by this. thanks for opening and looking into it :)

resolving.

**Comment by DT07** [comment]
I faced the same issue after installing graalvm on my mac.

❌  xyz-stack failed: SignatureDoesNotMatch: Signature expired: 20210526T103633Z is now earlier than 20210526T105134Z (20210526T105634Z - 5 min.)
   at Request.extractError (/usr/local/lib/node_modules/aws-cdk/node_modules/aws-sdk/lib/protocol/query.js:50:29)
   at Request.callListeners (/usr/local/lib/node_modules/aws-cdk/node_modules/aws-sdk/lib/sequential_executor.js:106:20)
   at Request.emit (/usr/local/lib/node_modules/aws-cdk/node_modules/aws-sdk/lib/sequential_executor.js:78:10)
   at Request.emit (/usr/local/lib/node_modules/aws-cdk/node_modules/aws-sdk/lib/request.js:688:14)
   at Request.transition (/usr/local/lib/node_modules/aws-cdk/node_modules/aws-sdk/lib/request.js:22:10)
   at AcceptorStateMachine.runTo (/usr/local/lib/node_modules/aws-cdk/node_modules/aws-sdk/lib/state_machine.js:14:12)
   at /usr/local/lib/node_modules/aws-cdk/node_modules/aws-sdk/lib/state_machine.js:26:10
   at Request.<anonymous> (/usr/local/lib/node_modules/aws-cdk/node_modules/aws-sdk/lib/request.js:38:9)
   at Request.<anonymous> (/usr/local/lib/node_modules/aws-cdk/node_modules/aws-sdk/lib/request.js:690:12)
   at Request.callListeners (/usr/local/lib/node_modules/aws-cdk/node_modules/aws-sdk/lib/sequential_executor.js:116:18) {
 code: 'SignatureDoesNotMatch',
 time: 2021-05-26T10:36:33.339Z,
 requestId: '5e93867b-20f4-4f7e-adf3-cf757ef9d28d',
 statusCode: 403,
 retryable: true
}
Signature expired: 20210526T103633Z is now earlier than 20210526T105134Z (20210526T105634Z - 5 min.)
