### ISSUE TITLE
Repo build and dev env doesn’t work on Windows 10

### ISSUE THREAD

**Issue by leepa** [aws/aws-cdk#55]
pkglint doesn't work on Windows it seems - or something is running chmod which obviously does not exist.

```
C:\Users\lpack\Documents\Code\aws-cdk>node --version
v8.11.2
```

```
lerna info lifecycle prepare
lerna sill runScript prepare pkglint
lerna sill runScriptInDir prepare [] pkglint
lerna sill getExecOpts { cwd: 'C:\\Users\\lpack\\Documents\\Code\\aws-cdk\\packages\\pkglint' }
lerna sill pkglint
lerna ERR! execute Error occured with 'pkglint' while running 'npm run prepare'
lerna ERR! npm run prepare [pkglint] Output from stdout:

> pkglint@0.6.0 prepare C:\Users\lpack\Documents\Code\aws-cdk\packages\pkglint
> tsc && tslint -p . && chmod +x bin/pkglint


lerna ERR! npm run prepare [pkglint] Output from stderr:
'chmod' is not recognized as an internal or external command,
operable program or batch file.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! pkglint@0.6.0 prepare: `tsc && tslint -p . && chmod +x bin/pkglint`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the pkglint@0.6.0 prepare script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\lpack\AppData\Roaming\npm-cache\_logs\2018-06-06T21_16_29_706Z-debug.log

lerna ERR! execute Error occured with 'pkglint' while running 'npm run prepare'
{ Error: Command failed: npm run prepare
'chmod' is not recognized as an internal or external command,
operable program or batch file.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! pkglint@0.6.0 prepare: `tsc && tslint -p . && chmod +x bin/pkglint`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the pkglint@0.6.0 prepare script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\lpack\AppData\Roaming\npm-cache\_logs\2018-06-06T21_16_29_706Z-debug.log

> pkglint@0.6.0 prepare C:\Users\lpack\Documents\Code\aws-cdk\packages\pkglint
> tsc && tslint -p . && chmod +x bin/pkglint


    at Promise.all.then.arr (C:\Users\lpack\Documents\Code\aws-cdk\node_modules\lerna\node_modules\execa\index.js:236:11)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
  code: 1,
  killed: false,
  stdout: '\n> pkglint@0.6.0 prepare C:\\Users\\lpack\\Documents\\Code\\aws-cdk\\packages\\pkglint\n> tsc && tslint -p . && chmod +x bin/pkglint\n\n',
  stderr: '\'chmod\' is not recognized as an internal or external command,\r\noperable program or batch file.\r\nnpm ERR! code ELIFECYCLE\nnpm ERR! errno 1\nnpm ERR! pkglint@0.6.0 prepare: `tsc && tslint -p . && chmod +x bin/pkglint`\nnpm ERR! Exit status 1\nnpm ERR! \nnpm ERR! Failed at the pkglint@0.6.0 prepare script.\nnpm ERR! This is probably not a problem with npm. There is likely additional logging output above.\n\nnpm ERR! A complete log of this run can be found in:\nnpm ERR!     C:\\Users\\lpack\\AppData\\Roaming\\npm-cache\\_logs\\2018-06-06T21_16_29_706Z-debug.log\n',
  failed: true,
  signal: null,
  cmd: 'npm run prepare',
  timedOut: false,
  pkg:
   Package {
     _package:
      { name: 'pkglint',
        version: '0.6.0',
        private: true,
        description: 'Validate and fix package.json files',
        main: 'lib/index.js',
        types: 'lib/index.d.ts',
        repository: [Object],
        pkglint: [Object],
        bin: [Object],
        scripts: [Object],
        keywords: [Array],
        author: [Object],
        license: 'Apache-2.0',
        devDependencies: [Object],
        dependencies: [Object] },
     _location: 'C:\\Users\\lpack\\Documents\\Code\\aws-cdk\\packages\\pkglint' },
  exitCode: 1 }

C:\Users\lpack\Documents\Code\aws-cdk>node --version
v8.11.2

C:\Users\lpack\Documents\Code\aws-cdk>
```

**Comment by john-shaskin** [comment]
I'm running into the same thing, and am thinking of wrapping a Docker image around the build process, as a workaround.

**Comment by eladb** [comment]
Recommend to use the docker instructions in the contribution guide on Windows. Closing for now.

**Comment by dankmemes2020** [comment]
Hi @eladb @NGL321 can we reopen this issue? There are no Docker instructions in the contribution guide anymore, so building the CDK on Windows doesn't work. Also, it's impossible to use WSL 1 because building the CDK requires docker to be running and accessible. (WSL 2 gets around this by allowing you to interface with the docker daemon from within a WSL container). 

Even scripts like `foreach.sh` don't work on Windows environments, even with WSL - Windows will happily open Bash up when you give it a #!/bin/bash to execute, but things like path escaping are done with / in mind as the path separator, so the scripts error out on Windows. I think also `awslint` fails to build because `pkglint` finds that the `repository.directory` is wrong, again due to a path separator issue. In theory, this is all TS so it should be cross-platform, but the build system and tools weren't written with Windows in mind.

**Comment by eladb** [comment]
Yes, reopening. Thanks
