### ISSUE TITLE
Python: Not possible to set the subnet_id when creating an efs mount target

### ISSUE THREAD

**Issue by codyfy** [aws/aws-cdk#5500]
### description of the bug:
When I try to create an EFS mount target I am unable to set the subnet_id. The synth fails with the error ` Expected Scalar, got {"$jsii.byref":"@aws-cdk/core.Reference@10024"}`

[This](https://stackoverflow.com/questions/59357873/how-to-set-the-subnet-id-when-creating-an-efs-mount-target-with-aws-cdk) is my stackoverflow thread. The aws support told me to open an issue (case id 6684465821)

### Reproduction Steps
Try to `cdk synth` the code below:  
```
from aws_cdk import (
    core,
    aws_ec2 as ec2,
    aws_efs as efs
)


class CdkAuroraStack(core.Stack):

    def __init__(self, scope: core.Construct, id: str, **kwargs) -> None:
        super().__init__(scope, id, **kwargs)

        vpc = ec2.Vpc(self, "VPC")

        filesystem = efs.CfnFileSystem(self, "FileSystem",
            encrypted = True,
            throughput_mode = "bursting",
            performance_mode = "generalPurpose"    
        )

        mountTarget = efs.CfnMountTarget(self, "EfsMounttarget",
            file_system_id=filesystem.get_att("FileSystemId"),
            security_groups= [ vpc.vpc_default_security_group ],
            subnet_id=vpc.select_subnets(subnet_type=ec2.SubnetType.PUBLIC).subnets[0].subnet_id
        )
```

### Error Log

```
jsii.errors.JavaScriptError: 
  Error: Expected Scalar, got {"$jsii.byref":"@aws-cdk/core.Reference@10024"}
      at Object.deserialize (/home/username/dev/tests/hello-cdk/.env/lib/python3.7/site-packages/jsii/_embedded/jsii/jsii-runtime.js:6630:23)
      at Kernel._toSandbox (/home/username/dev/tests/hello-cdk/.env/lib/python3.7/site-packages/jsii/_embedded/jsii/jsii-runtime.js:8111:61)
      at /home/username/dev/tests/hello-cdk/.env/lib/python3.7/site-packages/jsii/_embedded/jsii/jsii-runtime.js:6841:29
      at mapValues (/home/username/dev/tests/hello-cdk/.env/lib/python3.7/site-packages/jsii/_embedded/jsii/jsii-runtime.js:7101:27)
      at Object.deserialize (/home/username/dev/tests/hello-cdk/.env/lib/python3.7/site-packages/jsii/_embedded/jsii/jsii-runtime.js:6837:20)
      at Kernel._toSandbox (/home/username/dev/tests/hello-cdk/.env/lib/python3.7/site-packages/jsii/_embedded/jsii/jsii-runtime.js:8111:61)
      at /home/username/dev/tests/hello-cdk/.env/lib/python3.7/site-packages/jsii/_embedded/jsii/jsii-runtime.js:8164:33
      at Array.map (<anonymous>)
      at Kernel._boxUnboxParameters (/home/username/dev/tests/hello-cdk/.env/lib/python3.7/site-packages/jsii/_embedded/jsii/jsii-runtime.js:8164:19)
      at Kernel._wrapSandboxCode (/home/username/dev/tests/hello-cdk/.env/lib/python3.7/site-packages/jsii/_embedded/jsii/jsii-runtime.js:8205:19)
      at Kernel._create (/home/username/dev/tests/hello-cdk/.env/lib/python3.7/site-packages/jsii/_embedded/jsii/jsii-runtime.js:7749:26)
      at Kernel.create (/home/username/dev/tests/hello-cdk/.env/lib/python3.7/site-packages/jsii/_embedded/jsii/jsii-runtime.js:7503:21)
      at KernelHost.processRequest (/home/username/dev/tests/hello-cdk/.env/lib/python3.7/site-packages/jsii/_embedded/jsii/jsii-runtime.js:7293:28)
      at KernelHost.run (/home/username/dev/tests/hello-cdk/.env/lib/python3.7/site-packages/jsii/_embedded/jsii/jsii-runtime.js:7233:14)
      at Immediate._onImmediate (/home/username/dev/tests/hello-cdk/.env/lib/python3.7/site-packages/jsii/_embedded/jsii/jsii-runtime.js:7236:37)
      at processImmediate (internal/timers.js:439:21)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "app.py", line 9, in <module>
    HelloCdkStack(app, "HelloCdkStack2", env={'region': 'eu-west-1', 'account': '000000000000'})
  File "/home/username/dev/tests/hello-cdk/.env/lib/python3.7/site-packages/jsii/_runtime.py", line 66, in __call__
    inst = super().__call__(*args, **kwargs)
  File "/home/username/dev/tests/hello-cdk/hello_cdk/hello_cdk_stack.py", line 92, in __init__
    subnet_id=vpc.select_subnets(subnet_type=ec2.SubnetType.PUBLIC).subnet_ids[0]
  File "/home/username/dev/tests/hello-cdk/.env/lib/python3.7/site-packages/jsii/_runtime.py", line 66, in __call__
    inst = super().__call__(*args, **kwargs)
  File "/home/username/dev/tests/hello-cdk/.env/lib/python3.7/site-packages/aws_cdk/aws_efs/__init__.py", line 385, in __init__
    jsii.create(CfnMountTarget, self, [scope, id, props])
  File "/home/username/dev/tests/hello-cdk/.env/lib/python3.7/site-packages/jsii/_kernel/__init__.py", line 223, in create
    interfaces=[iface.__jsii_type__ for iface in getattr(klass, "__jsii_ifaces__", [])],
  File "/home/username/dev/tests/hello-cdk/.env/lib/python3.7/site-packages/jsii/_kernel/providers/process.py", line 333, in create
    return self._process.send(request, CreateResponse)
  File "/home/username/dev/tests/hello-cdk/.env/lib/python3.7/site-packages/jsii/_kernel/providers/process.py", line 318, in send
    raise JSIIError(resp.error) from JavaScriptError(resp.stack)
jsii.errors.JSIIError: Expected Scalar, got {"$jsii.byref":"@aws-cdk/core.Reference@10024"}
Subprocess exited with error 1
```

### Environment

  - **CLI Version      : aws-cli/1.14.44 Python/3.6.9 Linux/5.0.0-37-generic botocore/1.13.13**
  - **Framework Version: cdk 1.19.0 (build 5597bbe)**
  - **OS               : Ubuntu 18.04.3 LTS**
  - **Language         : english**

### Other
Quote from aws support:  
`This could be because "subnet_ids" is not returning a list type string so that the first on the list can be selected. `

To me it seems like this could be a python related issue since I found a working example for TypeScript: https://github.com/yvthepief/cdk-wordpress-ecs

--- 

This is :bug: Bug Report

**Comment by RomainMuller** [comment]
There are two problems with the code you have, both on the same line (and with the same fix)

```python
file_system_id=filesystem.get_att("FileSystemId"),
```

The `file_system_id` property is expected to be a `string`, but the result of `get_att` is a `core.Reference`, which you would have to manually convert to be a string (by calling `.to_string()` on it).

Second, there happens to be no property named `FileSystemId` on [`AWS::EFS::FileSystem`](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-efs-filesystem.html), which is what is modeled by `CfnFileSystem`. Instead, you should use `.ref`.

So the "correct" code would look like:
```python
from aws_cdk import (
    core,
    aws_ec2 as ec2,
    aws_efs as efs
)


class TypeScriptStack(core.Stack):

    def __init__(self, scope: core.Construct, id: str, **kwargs) -> None:
        super().__init__(scope, id, **kwargs)

        vpc = ec2.Vpc(self, "VPC")

        filesystem = efs.CfnFileSystem(self, "FileSystem",
            encrypted = True,
            throughput_mode = "bursting",
            performance_mode = "generalPurpose"
        )

        mountTarget = efs.CfnMountTarget(self, "EfsMounttarget",
            file_system_id=filesystem.ref, # <-- this is already a string!
            security_groups= [ vpc.vpc_default_security_group ],
            subnet_id=vpc.select_subnets(subnet_type=ec2.SubnetType.PUBLIC).subnets[0].subnet_id
        )
```

I believe a better error message would probably have allowed you to self-diagnose the problem (something along the lines of `Expected a 'string' but received an instance of @aws-cdk/core.Reference'`), so I made an enhancement request on the `aws/jsii` repository at aws/jsii#1182.

**Comment by pgollucci** [comment]
I'm looking at the L2/L3 for this as I said in other tickets. I got delayed by re:invent, holidays,....

I now have $work time allocated starting monday to look at this
