### ISSUE TITLE
CfnMountTarget's subnet_id property cannot be satisfied

### ISSUE THREAD

**Issue by esn89** [aws/aws-cdk#5548]
Passing in the value from my vpc's subnet properties doesn't seem to work, even hard coding the actual subnet id keeps giving me an error.

- I have tried using core.Fn.import_value to get the exported subnet names.
- tried passing in the vpc as a 'property' and using it's subnet attributes, also no luck.
- hard coding with the literal string of the subnet doesn't work as well.

### Reproduction Steps

```
        elasticfilestore = efs.CfnFileSystem(
                    self, "efs-storage",
                    encrypted=False,
                    lifecycle_policies=None)

        sg_efs = ec2.SecurityGroup(
                self,
                id="sg_efs",
                vpc=props['vpc'],
                security_group_name="sg_efs"
        )

        mountpoint = efs.CfnMountTarget(
                    self,
                    f"MountTarget",
                    file_system_id=elasticfilestore,
                    security_groups=[sg_efs],
                    subnet_id="subnet-0bf3ace41660a8ba1"
                    )
```

The error it returns is on the line of "subnet_id="

### Error Log

```
Traceback (most recent call last):
  File "app.py", line 20, in <module>
    efs = StorageStack(app, "StorageStack", ns.outputs)
  File "/Users/esn89/Documents/Projects/cdk-bw/.env/lib/python3.7/site-packages/jsii/_runtime.py", line 66, in __call__
    inst = super().__call__(*args, **kwargs)
  File "/Users/esn89/Documents/Projects/cdk-bw/cdk_bw/cdk_bw_efs.py", line 30, in __init__
    subnet_id="subnet-0bf3ace41660a8ba1"
  File "/Users/esn89/Documents/Projects/cdk-bw/.env/lib/python3.7/site-packages/jsii/_runtime.py", line 66, in __call__
    inst = super().__call__(*args, **kwargs)
  File "/Users/esn89/Documents/Projects/cdk-bw/.env/lib/python3.7/site-packages/aws_cdk/aws_efs/__init__.py", line 385, in __init__
    jsii.create(CfnMountTarget, self, [scope, id, props])
  File "/Users/esn89/Documents/Projects/cdk-bw/.env/lib/python3.7/site-packages/jsii/_kernel/__init__.py", line 229, in create
    interfaces=[iface.__jsii_type__ for iface in getattr(klass, "__jsii_ifaces__", [])],
  File "/User/esn89/Documents/Projects/cdk-bw/.env/lib/python3.7/site-packages/jsii/_kernel/providers/process.py", line 333, in create
    return self._process.send(request, CreateResponse)
  File "/Users/esn89/Documents/Projects/cdk-bw/.env/lib/python3.7/site-packages/jsii/_kernel/providers/process.py", line 318, in send
    raise JSIIError(resp.error) from JavaScriptError(resp.stack)
jsii.errors.JSIIError: Expected Scalar, got {"$jsii.byref":"@aws-cdk/aws-efs.CfnFileSystem@10034"}
```

### Environment

  - **CLI Version      :**  1.19.0 (build 5597bbe)
  - **Framework Version:** 1.19.0 
  - **OS               :** Mac 10.15.2
  - **Language         :** Python

### Other

--- 

This is :bug: Bug Report

**Comment by rix0rrr** [comment]
The stack trace is misleading. The error is not really on the quoted line, it's somewhere in the statement that encompasses the quoted line.

Specifically, this is wrong:

```
                    security_groups=[sg_efs],
```

Since you're using a `CfnMountTarget` class, that is an L1 and so it maps directly onto CloudFormation.

[`security_groups` takes a list of strings](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-efs-mounttarget.html#cfn-efs-mounttarget-securitygroups), not a list of `SecurityGroup` objects.
