### ISSUE TITLE
--profile is not being used when --app is specified

### ISSUE THREAD

**Issue by leimd** [aws/aws-cdk#5590]
We have discovered that then running the following command `cdk diff --app dist/Apps/Dev.js --profile dev-cdk`, aws cdk gives this error: 

AWS region must be configured either when you configure your CDK stack or through the environment

however, running this command gives no error: `AWS_PROFILE=cdk-dev cdk diff  --app dist/Apps/Dev.js`, this suggests --profile is not being used when --app is specified.

While this is not blocking us from using CDK, it's a bit inconvenient.

This is the output when I run with the -vvv flag:
```
Unable to determine AWS region from environment or AWS configuration (profile: "dev-cdk")
Setting "CDK_DEFAULT_REGION" environment variable to undefined
Resolving default credentials
Unable to determine the default AWS account (did you configure "aws configure"?): SharedIniFileCredentialsProviderFailure: Profile dev-cdk not found
    at SharedIniFileCredentials.load (/home/tom/.nvm/versions/node/v13.2.0/lib/node_modules/aws-cdk/node_modules/aws-sdk/lib/credentials/shared_ini_file_credentials.js:101:11)
    at SharedIniFileCredentials.coalesceRefresh (/home/tom/.nvm/versions/node/v13.2.0/lib/node_modules/aws-cdk/node_modules/aws-sdk/lib/credentials.js:205:12)
    at SharedIniFileCredentials.refresh (/home/tom/.nvm/versions/node/v13.2.0/lib/node_modules/aws-cdk/node_modules/aws-sdk/lib/credentials/shared_ini_file_credentials.js:168:10
)
    at SharedIniFileCredentials.get (/home/tom/.nvm/versions/node/v13.2.0/lib/node_modules/aws-cdk/node_modules/aws-sdk/lib/credentials.js:122:12)
    at resolveNext (/home/tom/.nvm/versions/node/v13.2.0/lib/node_modules/aws-cdk/node_modules/aws-sdk/lib/credentials/credential_provider_chain.js:125:17)
    at /home/tom/.nvm/versions/node/v13.2.0/lib/node_modules/aws-cdk/node_modules/aws-sdk/lib/credentials/credential_provider_chain.js:126:13
    at /home/tom/.nvm/versions/node/v13.2.0/lib/node_modules/aws-cdk/node_modules/aws-sdk/lib/credentials.js:124:23
    at EnvironmentCredentials.refresh (/home/tom/.nvm/versions/node/v13.2.0/lib/node_modules/aws-cdk/node_modules/aws-sdk/lib/credentials/environment_credentials.js:78:9)
    at EnvironmentCredentials.get (/home/tom/.nvm/versions/node/v13.2.0/lib/node_modules/aws-cdk/node_modules/aws-sdk/lib/credentials.js:122:12)
    at resolveNext (/home/tom/.nvm/versions/node/v13.2.0/lib/node_modules/aws-cdk/node_modules/aws-sdk/lib/credentials/credential_provider_chain.js:125:17) {
  message: 'Profile dev-cdk not found',
  code: 'SharedIniFileCredentialsProviderFailure',
  time: 2019-12-30T19:27:57.665Z
}
Setting "CDK_DEFAULT_ACCOUNT" environment variable to undefined
context: {
  '@aws-cdk/core:enableStackNameDuplicates': 'true',
  'aws-cdk:enableDiffNoFail': 'true',
  'aws:cdk:enable-path-metadata': true,
  'aws:cdk:enable-asset-metadata': true
}
outdir: cdk.out
env: {
  CDK_DEFAULT_REGION: undefined,
  CDK_DEFAULT_ACCOUNT: undefined,
  CDK_CONTEXT_JSON: '{"@aws-cdk/core:enableStackNameDuplicates":"true","aws-cdk:enableDiffNoFail":"true","aws:cdk:enable-path-metadata":true,"aws:cdk:enable-asset-metadata":true
}',
  CDK_OUTDIR: 'cdk.out',
  CDK_CLI_ASM_VERSION: '1.16.0',
  CDK_CLI_VERSION: '1.19.0'
}
```

### Environment

  - **CLI Version      :**
  - **Framework Version:**
  - **OS               :**
  - **Language         :**

### Other

--- 

This is :bug: Bug Report

**Comment by leimd** [comment]
Once you guys triage it, I'd be more than happy to make a PR to fix it myself. Looks like not that hard to fix.

**Comment by netroy** [comment]
@leimd I've not been able to reproduce this with CDK version `1.19.0` & nodejs `13.2.0` (as well as `12.14.0`).

Can you please create a test project, & check if this is reproducible?

**Comment by leimd** [comment]
> @leimd I've not been able to reproduce this with CDK version `1.19.0` & nodejs `13.2.0` (as well as `12.14.0`).
> 
> Can you please create a test project, & check if this is reproducible?

Looks like a setup error on my end... I seems that my config file in .aws folder is improperlly configured. We can close this issue. Thank you
