### ISSUE TITLE
S3 notifications lambda destination does not work with Function.fromFunctionArn

### ISSUE THREAD

**Issue by wcauchois** [aws/aws-cdk#5592]
I'm trying to create an S3 bucket and set up an object created notification with a LambdaDestination. My stack looks like this (verbatim):

```typescript
export class DeliveryStreamStack extends cdk.Stack {
  constructor(scope: cdk.App, id: string, props: DeliveryStreamStackProps) {
    super(scope, id, props);

    const bucket = new s3.Bucket(this, 'Bucket');
    bucket.addObjectCreatedNotification(new s3n.LambdaDestination(
      lambda.Function.fromFunctionArn(this, 'FunctionArn', 'REDACTED_ARN')
    ));
  }
}
```

However, when I try to synthesize my application I get the following error:

```
$ yarn cdk synth DataPipelineDeliveryStream-production
yarn run v1.19.2
$ /Users/wcauchois/code/datapipeline/node_modules/.bin/cdk synth DataPipelineDeliveryStream-production

/Users/wcauchois/code/datapipeline/node_modules/@aws-cdk/core/lib/construct.ts:191
      throw new Error(`No child with id: '${id}'`);
            ^
Error: No child with id: 'AllowBucketNotificationsFromDataPipelineDeliveryStreamproductionBucketD6C74BCD'
    at ConstructNode.findChild (/Users/wcauchois/code/datapipeline/node_modules/@aws-cdk/core/lib/construct.ts:191:13)
    at LambdaDestination.bind (/Users/wcauchois/code/datapipeline/node_modules/@aws-cdk/aws-s3-notifications/lib/lambda.ts:26:37)
    at BucketNotifications.addNotification (/Users/wcauchois/code/datapipeline/node_modules/@aws-cdk/aws-s3/lib/notifications-resource/notifications-resource.ts:56:32)
    at Bucket.addEventNotification (/Users/wcauchois/code/datapipeline/node_modules/@aws-cdk/aws-s3/lib/bucket.ts:1103:24)
    at Bucket.addObjectCreatedNotification (/Users/wcauchois/code/datapipeline/node_modules/@aws-cdk/aws-s3/lib/bucket.ts:1115:17)
    at new DeliveryStreamStack (/Users/wcauchois/code/datapipeline/cdk/stacks/deliverystream.ts:22:12)
    at Object.<anonymous> (/Users/wcauchois/code/datapipeline/cdk/app.ts:9:1)
    at Module._compile (internal/modules/cjs/loader.js:774:30)
    at Module.m._compile (/Users/wcauchois/code/datapipeline/node_modules/ts-node/src/index.ts:536:23)
    at Module._extensions..js (internal/modules/cjs/loader.js:785:10)
```

I am using aws-cdk version 1.19.0. Any help on this issue would be appreciated!

**Comment by wcauchois** [comment]
I looked into it a bit and I think the issue might be that on this line:

https://github.com/aws/aws-cdk/blob/9dd177630ee684f8de67940fdb77956d0453c3c0/packages/%40aws-cdk/aws-s3-notifications/lib/lambda.ts#L26

that `findChild(permissionId)` should be `tryFindChild(permissionId)`. I'm not familiar enough with the code to know that for sure though.

**Comment by eladb** [comment]
I think you are correct. This should be `tryFindChild`. Would you like to try and submit a pull request with this fix?

**Comment by wcauchois** [comment]
cool, i gave it a try here! https://github.com/aws/aws-cdk/pull/5599

(BTW, if this change merits any sort of thanks.. perhaps you could chime in on a recent CDK-related stackoverflow question i asked - https://stackoverflow.com/questions/59545731/how-to-execute-commands-needed-to-prepare-an-artifact 🙂)
