### ISSUE TITLE
CodePipeline deploy to ASG fails "would create cyclic reference" when ASG is in different stack

### ISSUE THREAD

**Issue by codyfy** [aws/aws-cdk#5657]
When creating an auto scaling group in stack A (asg-stack) and reference it to a CodeDeployServerDeployAction in another stack B (pipeline-stack) `cdk synth` fails with `Error: 'pipeline-stack' depends on 'asg-stack'`

### Reproduction Steps
I've created a repo with a cdk app that produces the error: https://github.com/codyfy/aws-cdk-pipeline-cyclic-reference-error it basically is:

1. Create VPC and ASG construct (asg.py)
2. Create Source and Deploy Action in construct (pipeline.py)
3. Add additional parameter "autoscaling.AutoScalingGroup" for pipeline construct:
`def __init__(self, scope: core.Construct, id: str, props: autoscaling.AutoScalingGroup, **kwargs) -> None:`
4. create stack A (vpc, asg) 
5. create stack B (pipeline) with stack As asg included as a parameter

### Error Log

```
jsii.errors.JavaScriptError: 
  Error: 'pipeline-stack' depends on 'asg-stack' (dependency added using stack.addDependency(), pipeline-stack -> asg-stack/AutoScalingGroup/InstanceRole/Resource.Arn, pipeline-stack -> asg-stack/AutoScalingGroup/ASG.Ref). Adding this dependency (asg-stack -> pipeline-stack/CodePipeline/ArtifactsBucket/Resource.Arn) would create a cyclic reference.
      at Stack._addAssemblyDependency (/tmp/jsii-kernel-3vBthm/node_modules/@aws-cdk/core/lib/stack.js:443:19)
      at Object.addDependency (/tmp/jsii-kernel-3vBthm/node_modules/@aws-cdk/core/lib/deps.js:39:24)
      at Stack.addDependency (/tmp/jsii-kernel-3vBthm/node_modules/@aws-cdk/core/lib/stack.js:183:16)
      at Stack.prepareCrossReference (/tmp/jsii-kernel-3vBthm/node_modules/@aws-cdk/core/lib/stack.js:670:28)
      at Stack.prepare (/tmp/jsii-kernel-3vBthm/node_modules/@aws-cdk/core/lib/stack.js:541:43)
      at Function.prepare (/tmp/jsii-kernel-3vBthm/node_modules/@aws-cdk/core/lib/construct.js:87:27)
      at Function.synth (/tmp/jsii-kernel-3vBthm/node_modules/@aws-cdk/core/lib/construct.js:51:14)
      at App.synth (/tmp/jsii-kernel-3vBthm/node_modules/@aws-cdk/core/lib/app.js:71:52)
      at /home/hornung/.local/lib/python3.6/site-packages/jsii/_embedded/jsii/jsii-runtime.js:7588:51
      at Kernel._wrapSandboxCode (/home/hornung/.local/lib/python3.6/site-packages/jsii/_embedded/jsii/jsii-runtime.js:8224:19)
      at /home/hornung/.local/lib/python3.6/site-packages/jsii/_embedded/jsii/jsii-runtime.js:7588:25
      at Kernel._ensureSync (/home/hornung/.local/lib/python3.6/site-packages/jsii/_embedded/jsii/jsii-runtime.js:8197:20)
      at Kernel.invoke (/home/hornung/.local/lib/python3.6/site-packages/jsii/_embedded/jsii/jsii-runtime.js:7587:26)
      at KernelHost.processRequest (/home/hornung/.local/lib/python3.6/site-packages/jsii/_embedded/jsii/jsii-runtime.js:7296:28)
      at KernelHost.run (/home/hornung/.local/lib/python3.6/site-packages/jsii/_embedded/jsii/jsii-runtime.js:7236:14)
      at Immediate._onImmediate (/home/hornung/.local/lib/python3.6/site-packages/jsii/_embedded/jsii/jsii-runtime.js:7239:37)
      at processImmediate (internal/timers.js:439:21)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "app.py", line 14, in <module>
    app.synth()
  File "/home/hornung/.local/lib/python3.6/site-packages/aws_cdk/core/__init__.py", line 3463, in synth
    return jsii.invoke(self, "synth", [])
  File "/home/hornung/.local/lib/python3.6/site-packages/jsii/_kernel/__init__.py", line 113, in wrapped
    return _recursize_dereference(kernel, fn(kernel, *args, **kwargs))
  File "/home/hornung/.local/lib/python3.6/site-packages/jsii/_kernel/__init__.py", line 288, in invoke
    args=_make_reference_for_native(self, args),
  File "/home/hornung/.local/lib/python3.6/site-packages/jsii/_kernel/providers/process.py", line 348, in invoke
    return self._process.send(request, InvokeResponse)
  File "/home/hornung/.local/lib/python3.6/site-packages/jsii/_kernel/providers/process.py", line 318, in send
    raise JSIIError(resp.error) from JavaScriptError(resp.stack)
jsii.errors.JSIIError: 'pipeline-stack' depends on 'asg-stack' (dependency added using stack.addDependency(), pipeline-stack -> asg-stack/AutoScalingGroup/InstanceRole/Resource.Arn, pipeline-stack -> asg-stack/AutoScalingGroup/ASG.Ref). Adding this dependency (asg-stack -> pipeline-stack/CodePipeline/ArtifactsBucket/Resource.Arn) would create a cyclic reference.
```

### Environment

  - **CLI Version      : aws-cli/1.14.44 Python/3.6.9 Linux/5.0.0-37-generic botocore/1.13.13**
  - **Framework Version: cdk 1.19.0 (build 5597bbe)**
  - **OS               : Ubuntu 18.04.3 LTS**
  - **Language         : english**

### Other

I tried to get help from stackoverflow but was unsuccessful: https://stackoverflow.com/questions/59424730/would-create-a-cyclic-reference-when-creating-codepipeline-with-deploy-action  
there is no problem when I create everything in one stack.

--- 

This is :bug: Bug Report

**Comment by skinny85** [comment]
Hey @codyfy ,

thanks for opening the issue. You're right that this happens, I was able to reproduce this problem. One way you can work around it is to use physical names for the CodePipeline bucket, as that's the main source of the cycle. Something like this (this is TypeScript, but should be translatable to Python as well):

```ts
        const artifactBucket = new s3.Bucket(this, 'PipelineBucket,', {
            bucketName: 'my-bucket',
        });
        new codepipeline.Pipeline(this, 'Pipeline', {
            artifactBucket: s3.Bucket.fromBucketAttributes(this, 'ImportedBucket', {
                bucketName: 'my-bucket', // same name as above
            }),
        });
```

Let me know if this unblocks you!

Thanks,
Adam

**Comment by codyfy** [comment]
Hi @skinny85 ,

thank you very much for looking into this! I got it working with your example. unblocked me good!

**Comment by skinny85** [comment]
Glad I could help! I'll resolve this one then, feel free to comment if you need anything else from our side on this issue.
