### ISSUE TITLE
[apigateway] LambdaRestApi fails when the deploy option is unset

### ISSUE THREAD

**Issue by kartoffelsup** [aws/aws-cdk#5744]
I'm using Java CDK.

When setting `deploy` to `false` on `software.amazon.awscdk.services.apigateway.LambdaRestApiProps`, it fails with `Error: Unable to determine ARN for method "ANY" since there is no stage associated with this API.`. 

But when setting stageOptions it fails with: `Error: Cannot set 'deployOptions' if 'deploy' is disabled`.

Because Deployment needs a LambdaRestApi object as parameter and the error is thrown during construction of said LambdaRestApi object. I see no way of getting this to work.

### Reproduction Steps

```java
public class ReproStack extends Stack {
    public ReproStack(Construct parent) {
        super(parent, "ReproStack");

        Function function = Function.Builder.create(this, "ExampleFunction")
                .runtime(Runtime.NODEJS_10_X)
                .code(Code.fromInline("exports.handler = () => console.log('hi')"))
                .handler("index.handler")
                .build();

        LambdaRestApi api = LambdaRestApi.Builder.create(this, "ExampleAPI")
                .deploy(false)
                .handler(function)
                .build();

        Deployment deployment = Deployment.Builder.create(this, "ExampleDeployment")
                .api(api)
                .build();


        Stage stage = Stage.Builder.create(this, "ExampleStage")
                .stageName("example")
                .deployment(deployment)
                .build();
    }

    public static void main(String[] args) {
        App app = new App();
        new ReproStack(app);
        app.synth();
    }
}
```

### Error Log

```
Exception in thread "main" software.amazon.jsii.JsiiException: Unable to determine ARN for method "ANY" since there is no stage associated with this API.
Either use the `deploy` prop or explicitly assign `deploymentStage` on the RestApi
Error: Unable to determine ARN for method "ANY" since there is no stage associated with this API.
Either use the `deploy` prop or explicitly assign `deploymentStage` on the RestApi
    at Method.get methodArn [as methodArn] (/tmp/jsii-kernel-dfuWvM/node_modules/@aws-cdk/aws-apigateway/lib/method.js:66:19)
    at LambdaIntegration.bind (/tmp/jsii-kernel-dfuWvM/node_modules/@aws-cdk/aws-apigateway/lib/integrations/lambda.js:33:31)
    at Method.renderIntegration (/tmp/jsii-kernel-dfuWvM/node_modules/@aws-cdk/aws-apigateway/lib/method.js:88:21)
    at Method.renderIntegration (/tmp/jsii-kernel-dfuWvM/node_modules/@aws-cdk/aws-apigateway/lib/method.js:83:29)
    at new Method (/tmp/jsii-kernel-dfuWvM/node_modules/@aws-cdk/aws-apigateway/lib/method.js:40:31)
    at RootResource.addMethod (/tmp/jsii-kernel-dfuWvM/node_modules/@aws-cdk/aws-apigateway/lib/resource.js:17:16)
    at ProxyResource.addMethod (/tmp/jsii-kernel-dfuWvM/node_modules/@aws-cdk/aws-apigateway/lib/resource.js:221:37)
    at new ProxyResource (/tmp/jsii-kernel-dfuWvM/node_modules/@aws-cdk/aws-apigateway/lib/resource.js:212:35)
    at RootResource.addProxy (/tmp/jsii-kernel-dfuWvM/node_modules/@aws-cdk/aws-apigateway/lib/resource.js:20:16)
    at Kernel._wrapSandboxCode (/tmp/jsii-java-runtime6808886350460984407/jsii-runtime.js:8225:19)
    at Kernel._create (/tmp/jsii-java-runtime6808886350460984407/jsii-runtime.js:7762:26)
    at Kernel.create (/tmp/jsii-java-runtime6808886350460984407/jsii-runtime.js:7509:21)
    at KernelHost.processRequest (/tmp/jsii-java-runtime6808886350460984407/jsii-runtime.js:7296:28)
    at KernelHost.run (/tmp/jsii-java-runtime6808886350460984407/jsii-runtime.js:7236:14)
    at Immediate.setImmediate [as _onImmediate] (/tmp/jsii-java-runtime6808886350460984407/jsii-runtime.js:7239:37)
    at runCallback (timers.js:705:18)
    at tryOnImmediate (timers.js:676:5)
    at processImmediate (timers.js:658:5)
	at software.amazon.jsii.JsiiRuntime.processErrorResponse(JsiiRuntime.java:112)
	at software.amazon.jsii.JsiiRuntime.requestResponse(JsiiRuntime.java:84)
	at software.amazon.jsii.JsiiClient.createObject(JsiiClient.java:82)
	at software.amazon.jsii.JsiiEngine.createNewObject(JsiiEngine.java:510)
	at software.amazon.awscdk.services.apigateway.LambdaRestApi.<init>(LambdaRestApi.java:31)
	at software.amazon.awscdk.services.apigateway.LambdaRestApi$Builder.build(LambdaRestApi.java:414)
	at ReproStack.<init>(ReproStack.java:27)
	at ReproStack.main(ReproStack.java:42)

Process finished with exit code 1
```

### Environment

  - **CLI Version      :** 1.20.0
  - **Framework Version:** 1.20.0
  - **OS               :** Ubuntu 18.04.3 LTS
  - **Language         :** Java

### Other

--- 

This is :bug: Bug Report

**Comment by nija-at** [comment]
We always need a `Deployment` associated with the `RestApi`. I believe you're missing the line

```java
api.setDeploymentStage(deployment);
```

Can you make this change and see if it fixes your issue?

It seems we're missing this information in the [documentation of the `deploy` parameter](https://docs.aws.amazon.com/cdk/api/latest/java/software/amazon/awscdk/services/apigateway/LambdaRestApiProps.Builder.html#deploy-java.lang.Boolean-) but it's present in the [documentation for `setDeploymentStage()`](https://docs.aws.amazon.com/cdk/api/latest/java/software/amazon/awscdk/services/apigateway/RestApi.html#setDeploymentStage-software.amazon.awscdk.services.apigateway.Stage-).

**Comment by nija-at** [comment]
On closer look, I don't think this is the issue you're facing. There is a bug in the `LambdaRestApi` code.

The `LambdaRestApi` adds the default `ANY` method to the RestApi and attempts to bind the Lambda function to this method. This [binding](https://github.com/aws/aws-cdk/blob/master/packages/%40aws-cdk/aws-apigateway/lib/integrations/lambda.ts#L54) needs the `methodArn` which [in turn requires](https://github.com/aws/aws-cdk/blob/master/packages/%40aws-cdk/aws-apigateway/lib/method.ts#L181-L186) a `Stage` to be attached to the `RestApi`.

I'm afraid there may not be a quick fix for this and will require a closer look.

As a workaround, you could set the same thing up using the `RestApi` construct but with a few additional lines, like so -

```ts
public class HelloCdkJavaApp extends Stack {
    public HelloCdkJavaApp(Construct parent) {
        super(parent, "ReproStack");

        Function function = Function.Builder.create(this, "ExampleFunction")
                .runtime(Runtime.NODEJS_10_X)
                .code(Code.fromInline("exports.handler = () => console.log('hi')"))
                .handler("index.handler")
                .build();

        RestApi api = RestApi.Builder.create(this, "ExampleAPI")
                .deploy(false)
                .build();

        Deployment deployment = Deployment.Builder.create(this, "ExampleDeployment")
                .api(api)
                .build();


        Stage stage = Stage.Builder.create(this, "ExampleStage")
                .stageName("example")
                .deployment(deployment)
                .build();

        api.setDeploymentStage(stage);
        LambdaIntegration integration = new LambdaIntegration(function);
        api.getRoot().addMethod("ANY", integration);
    }

    public static void main(String[] args) {
        App app = new App();
        new HelloCdkJavaApp(app);
        app.synth();
    }
}
```

**Comment by kartoffelsup** [comment]
Thanks for the workaround and the fix. :)
