### ISSUE TITLE
Docker image assets do not copy the Dockerfile if Dockerfile is included in the .dockerignore file

### ISSUE THREAD

**Issue by nathanpeck** [aws/aws-cdk#6004]
According to the Docker spec you can include the `Dockerfile` in your `.dockerignore` file: 

> You can even use the .dockerignore file to exclude the Dockerfile and .dockerignore files. These files are still sent to the daemon because it needs them to do its job. But the ADD and COPY instructions do not copy them to the image.

https://docs.docker.com/engine/reference/builder/

However if you follow this pattern with AWS CDK the asset fails to build with an error about being unable to find the Dockerfile. When inspected the contents of the asset folder the Dockerfile is indeed missing.

It appears that AWS CDK is attempting to produce smaller assets by respecting the `.dockerignore` file and not copying those assets into the assets folder, however, it does not follow the special case for the `Dockerfile`

### Reproduction Steps

Create a project with a `Dockerfile` and a `.dockerignore` file that ignores the Dockerfile to avoid adding the dockerfile to the built image.
example `.dockerignore`:

```
.git
*Dockerfile*
*docker-compose*
node_modules
```

Then attempt to build the asset using AWS CDK:

```js
ecs.ContainerImage.fromAsset('./path/to/folder'),
```

### Error Log

```
chatter-message: deploying...
unable to prepare context: unable to evaluate symlinks in Dockerfile path: lstat /Users/peckn/Documents/Code/demo/cdk.out/asset.ae8c5499264f2f5958258b94afa7493583862df2a023e45404c6cb5a01e84917/Dockerfile: no such file or directory

 ❌  chatter-message failed: Error: docker build --tag 209640446841.dkr.ecr.us-east-1.amazonaws.com/aws-cdk/assets:ae8c5499264f2f5958258b94afa7493583862df2a023e45404c6cb5a01e84917 cdk.out/asset.ae8c5499264f2f5958258b94afa7493583862df2a023e45404c6cb5a01e84917 exited with error code 1
    at ChildProcess.<anonymous> (/Users/peckn/Documents/Code/demo/node_modules/aws-cdk/lib/os.ts:39:16)
    at Object.onceWrapper (events.js:428:26)
    at ChildProcess.emit (events.js:321:20)
    at ChildProcess.EventEmitter.emit (domain.js:485:12)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12)
docker build --tag 209640446841.dkr.ecr.us-east-1.amazonaws.com/aws-cdk/assets:ae8c5499264f2f5958258b94afa7493583862df2a023e45404c6cb5a01e84917 cdk.out/asset.ae8c5499264f2f5958258b94afa7493583862df2a023e45404c6cb5a01e84917 exited with error code 1
```

### Environment

  - **CLI Version      : 1.22.0**
  - **Framework Version:  1.22.0**
  - **Language         : typescript**

### Other

We should add a special case for the "Dockerfile" and ".dockerignore" file so that it always gets copied into the asset folder, even if it is included in the `.dockerignore` folder

--- 

This is :bug: Bug Report

**Comment by nathanpeck** [comment]
This appears to be the line of code that needs to change: https://github.com/aws/aws-cdk/blob/master/packages/%40aws-cdk/aws-ecr-assets/lib/image-asset.ts#L95

It needs to filter `Dockerfile` and `.dockerignore` out of the list of excludes. However it is kind of complicated by the fact that it could be a pattern like

**Comment by nathanpeck** [comment]
Added PR https://github.com/aws/aws-cdk/pull/6007 to fix this issue

**Comment by nathanpeck** [comment]
Fix merged in!
