### ISSUE TITLE
Not possible to use getters from CDK objects when building abstractions?

### ISSUE THREAD

**Issue by ivoanjo** [aws/aws-cdk#6013]
### The Question

I'm building an abstraction in Java where I create a few SQS queues and want to have a "create standard alarms for queues" method.

I was expecting the following to work:

```java
import software.amazon.awscdk.core.Duration;
import software.amazon.awscdk.core.Stack;
import software.amazon.awscdk.services.cloudwatch.Alarm;
import software.amazon.awscdk.services.cloudwatch.ComparisonOperator;
import software.amazon.awscdk.services.cloudwatch.Metric;
import software.amazon.awscdk.services.cloudwatch.TreatMissingData;
import software.amazon.awscdk.services.sqs.Queue;

public class MyTestQueues {
    public static void createQueuesAndAlarms(Stack stack) {
        Queue q1 = Queue.Builder.create(stack, "queue1").queueName("ThisIsQueue1").build();
        Queue q2 = Queue.Builder.create(stack, "queue2").queueName("ThisIsQueue2").build();

        alarmQueue(stack, q1);
        alarmQueue(stack, q2);
    }

    private static void alarmQueue(Stack stack, Queue queue) {
        Alarm.Builder.create(stack, "AlarmFor" + queue.getQueueName()) // ⬅️ this is where the magic doesn't happen
            .alarmName("alarmFor" + queue.getQueueName()) // ⬅️ this is relevant too
            .alarmDescription("test")
            .period(Duration.minutes(5))
            .comparisonOperator(ComparisonOperator.GREATER_THAN_OR_EQUAL_TO_THRESHOLD)
            .threshold(10)
            .evaluationPeriods(10)
            .datapointsToAlarm(10)
            .treatMissingData(TreatMissingData.NOT_BREACHING)
            .metric(
                Metric.Builder.create()
                    .namespace("foo")
                    .metricName("bar")
                    .build()
            )
            .build();
    }
}
```

whereas I get 

```java
Exception in thread "main" software.amazon.jsii.JsiiException: Cannot use tokens in construct ID: AlarmFor${Token[TOKEN.14]}
Error: Cannot use tokens in construct ID: AlarmFor${Token[TOKEN.14]}
    at new ConstructNode (/tmp/jsii-kernel-eRuHXk/node_modules/@aws-cdk/core/lib/construct.js:39:19)
    at new Construct (/tmp/jsii-kernel-eRuHXk/node_modules/@aws-cdk/core/lib/construct.js:448:21)
    at new Resource (/tmp/jsii-kernel-eRuHXk/node_modules/@aws-cdk/core/lib/resource.js:13:9)
    at new Alarm (/tmp/jsii-kernel-eRuHXk/node_modules/@aws-cdk/aws-cloudwatch/lib/alarm.js:52:9)
    at obj._wrapSandboxCode (/tmp/jsii-java-runtime4261158552521288222/jsii-runtime.js:7762:49)
    at Kernel._wrapSandboxCode (/tmp/jsii-java-runtime4261158552521288222/jsii-runtime.js:8225:19)
    at Kernel._create (/tmp/jsii-java-runtime4261158552521288222/jsii-runtime.js:7762:26)
    at Kernel.create (/tmp/jsii-java-runtime4261158552521288222/jsii-runtime.js:7509:21)
    at KernelHost.processRequest (/tmp/jsii-java-runtime4261158552521288222/jsii-runtime.js:7296:28)
    at KernelHost.run (/tmp/jsii-java-runtime4261158552521288222/jsii-runtime.js:7236:14)
    at Immediate.setImmediate (/tmp/jsii-java-runtime4261158552521288222/jsii-runtime.js:7239:37)
    at runCallback (timers.js:810:20)
    at tryOnImmediate (timers.js:768:5)
    at processImmediate [as _immediateCallback] (timers.js:745:5)
        at software.amazon.jsii.JsiiRuntime.processErrorResponse(JsiiRuntime.java:112)
        at software.amazon.jsii.JsiiRuntime.requestResponse(JsiiRuntime.java:84)
        at software.amazon.jsii.JsiiClient.createObject(JsiiClient.java:82)
        at software.amazon.jsii.JsiiEngine.createNewObject(JsiiEngine.java:510)
        at software.amazon.awscdk.services.cloudwatch.Alarm.<init>(Alarm.java:27)
        at software.amazon.awscdk.services.cloudwatch.Alarm$Builder.build(Alarm.java:340)
...
```

This led me to https://github.com/aws/aws-cdk/issues/1374 where this is discussed. So if I do something like

```java
    private static void alarmQueue(Stack stack, Queue queue) {
        Alarm.Builder.create(stack, "Alarm" + Math.random())
            .alarmName("alarmFor" + queue.getQueueName())
            .alarmDescription("test")
            .period(Duration.minutes(5))
            .comparisonOperator(ComparisonOperator.GREATER_THAN_OR_EQUAL_TO_THRESHOLD)
            .threshold(10)
            .evaluationPeriods(10)
            .datapointsToAlarm(10)
            .treatMissingData(TreatMissingData.NOT_BREACHING)
            .metric(
                Metric.Builder.create()
                    .namespace("foo")
                    .metricName("bar")
                    .build()
            )
            .build();
    }
```

...I do get my alarms in the output

```json
    "Alarm008234429948114941E06E253A": {
      "Type": "AWS::CloudWatch::Alarm",
      "Properties": {
        "ComparisonOperator": "GreaterThanOrEqualToThreshold",
        "EvaluationPeriods": 10,
        "AlarmDescription": "test",
        "AlarmName": {
          "Fn::Join": [
            "",
            [
              "alarmFor",
              {
                "Fn::GetAtt": [
                  "queue1A6429D98",
                  "QueueName"
                ]
              }
            ]
          ]
        },
	...
    },
    "Alarm096869038411921583E702D43": {
      "Type": "AWS::CloudWatch::Alarm",
      "Properties": {
        "ComparisonOperator": "GreaterThanOrEqualToThreshold",
        "EvaluationPeriods": 10,
        "AlarmDescription": "test",
        "AlarmName": {
          "Fn::Join": [
            "",
            [
              "alarmFor",
              {
                "Fn::GetAtt": [
                  "queue20D18E0EC",
                  "QueueName"
                ]
              }
            ]
          ]
        },
        ...

```

But:

* I lost the nice property of having an alarm id that is correlated with the queue it is serving for
* There's an unneeded indirection to build the alarm name -- all of the elements are known when the CDK runs, but it's still using a `Fn::Join` to let cloudformation do the work.

So my question is:

Am I "holding" the CDK the wrong way around? How would one go around creating an abstraction such as `alarmQueue` without all of this awkwardness?

The only "workaround" I've found is to pass around the name around instead, but it seems weird to go back to building a house of ~~cards~~ Strings when I have all of these nicely typed domain objects lying around.

### Environment

  - **CDK CLI Version:** `1.22.0 (build 309ac1b)`
  - **Module Version:** Same as shipped in CDK
  - **OS:** Ubuntu
  - **Language:** Java

**Comment by skinny85** [comment]
Hey @ivoanjo ,

this is a very interesting example, and I think I'll say that you are using the CDK slightly incorrectly here :).

The cornerstone of the CDK is *composability*. Unlike in pure CloudFormation, where a template is a flat collection of resources, the CDK constructs form a tree, which means the identifiers that you have need only to be locally unique, not globally unique.

So, having written some constructs in the CDK myself, that's how I would implement `alarmQueue`:

```java
public class MyTestQueues {
    public static void createQueuesAndAlarms(Stack stack) {
        Queue q1 = Queue.Builder.create(stack, "queue1").queueName("ThisIsQueue1").build();
        Queue q2 = Queue.Builder.create(stack, "queue2").queueName("ThisIsQueue2").build();

        alarmQueue(stack, q1);
        alarmQueue(stack, q2);
    }

    private static void alarmQueue(Stack stack, Queue queue) {
        Alarm.Builder.create(queue, "AlarmFor") // ⬅️ this is key
            .alarmName("alarmFor" + queue.getQueueName())
            .alarmDescription("test")
            .period(Duration.minutes(5))
            .comparisonOperator(ComparisonOperator.GREATER_THAN_OR_EQUAL_TO_THRESHOLD)
            .threshold(10)
            .evaluationPeriods(10)
            .datapointsToAlarm(10)
            .treatMissingData(TreatMissingData.NOT_BREACHING)
            .metric(
                Metric.Builder.create()
                    .namespace("foo")
                    .metricName("bar")
                    .build()
            )
            .build();
    }
}
```

The only change is passing as the parent the `queue`, not the stack. This way, you get the correlation that you wanted "for free" (the logical ID in the CDK is constructed taking into account the IDs of your parent constructs).

Does this make sense?

Thanks,
Adam

**Comment by skinny85** [comment]
As to this point:

> There's an unneeded indirection to build the alarm name -- all of the elements are known when the CDK runs, but it's still using a Fn::Join to let cloudformation do the work.

That is actually not true. You see, by doing it this way, there is actually a dependency relationship between the 2 resources that CloudFormation will respect, so that the Queue is created before the Alarm, which is almost certainly what you want to happen.

Plus, `queueName` is actually an optional property, so it might happen that it will not be known at CDK build time - only after the stack has been deployed.

**Comment by ivoanjo** [comment]
That makes a lot of sense! Thanks for the clear and speedy answer.

Just to add a bit more context to your answer, with your change the resulting output is:

```json
    "queue1AlarmForDE37C6FE": {
      "Type": "AWS::CloudWatch::Alarm",
      "Properties": {
        "ComparisonOperator": "GreaterThanOrEqualToThreshold",
        "EvaluationPeriods": 10,
        "AlarmDescription": "test",
        "AlarmName": {
          "Fn::Join": [
            "",
            [
              "alarmFor",
              {
                "Fn::GetAtt": [
                  "queue1A6429D98",
                  "QueueName"
                ]
              }
            ]
          ]
        },
...
      },
      "Metadata": {
        "aws:cdk:path": "SkySailMeteringInfrastructureCDK/queue1/AlarmFor/Resource"
      }
    },
    "queue2AlarmForB0BD8BDA": {
      "Type": "AWS::CloudWatch::Alarm",
      "Properties": {
        "ComparisonOperator": "GreaterThanOrEqualToThreshold",
        "EvaluationPeriods": 10,
        "AlarmDescription": "test",
        "AlarmName": {
          "Fn::Join": [
            "",
            [
              "alarmFor",
              {
                "Fn::GetAtt": [
                  "queue20D18E0EC",
                  "QueueName"
                ]
              }
            ]
          ]
        },
....
      },
      "Metadata": {
        "aws:cdk:path": "SkySailMeteringInfrastructureCDK/queue2/AlarmFor/Resource"
      }
    },
```

which is exactly what I was going for.
