### ISSUE TITLE
CDK does not support using EC2/CodeBuild credentials to assume roles in profiles

### ISSUE THREAD

**Issue by dohoangn** [aws/aws-cdk#6142]
We have the deployment box as ec2 instance. This ec2 instance is assigned a role ProvisioningInstanceProfile role, when we need to deploy new infra in AWS we assume another role (which has all permission to create infrastructure) to do the deployment

```console
unset AWS_ACCESS_KEY_ID ; $( aws sts assume-role --role-arn arn:aws:iam::90909090:role/ProvisioningRole --role-session-name "Deploy" | grep -E '(SecretAccessKey|SessionToken|AccessKeyId)' | awk '{print $2}' | tr -d ',' | awk 'NR==1 { system("echo export AWS_SECRET_ACCESS_KEY="$1) }; NR==2 { system("echo export AWS_SECURITY_TOKEN="$1) } ; NR==3 { system("echo export AWS_ACCESS_KEY_ID="$1) }' )
```
It is working fine with Cloudformation, Terraform. However it is not working with CDK. Everytime we run above command to assume ProvisioningRole, CDK set CDK_DEFAULT_ACCOUNT: undefined. 

Then it throws exception:
```console
Unable to resolve AWS account to use. It must be either configured when you define your CDK or through the environment
Error: Unable to resolve AWS account to use. It must be either configured when you define your CDK or through the environment
    at SDK.resolveEnvironment (/home/ec2-user/.nvm/versions/node/v13.7.0/lib/node_modules/aws-cdk/lib/api/util/sdk.ts:188:13)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at SDK.cloudFormation (/home/ec2-user/.nvm/versions/node/v13.7.0/lib/node_modules/aws-cdk/lib/api/util/sdk.ts:113:25)
    at CloudFormationDeploymentTarget.readCurrentTemplate (/home/ec2-user/.nvm/versions/node/v13.7.0/lib/node_modules/aws-cdk/lib/api/deployment-target.ts:53:17)
    at CdkToolkit.deploy (/home/ec2-user/.nvm/versions/node/v13.7.0/lib/node_modules/aws-cdk/lib/cdk-toolkit.ts:114:33)
    at main (/home/ec2-user/.nvm/versions/node/v13.7.0/lib/node_modules/aws-cdk/bin/cdk.ts:212:16)
    at initCommandLine (/home/ec2-user/.nvm/versions/node/v13.7.0/lib/node_modules/aws-cdk/bin/cdk.ts:164:9)
```

### Reproduction Steps

`npm run build`

`cdk deploy`

### Error Log
```console
Unable to resolve AWS account to use. It must be either configured when you define your CDK or through the environment
Error: Unable to resolve AWS account to use. It must be either configured when you define your CDK or through the environment
    at SDK.resolveEnvironment (/home/ec2-user/.nvm/versions/node/v13.7.0/lib/node_modules/aws-cdk/lib/api/util/sdk.ts:188:13)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at SDK.cloudFormation (/home/ec2-user/.nvm/versions/node/v13.7.0/lib/node_modules/aws-cdk/lib/api/util/sdk.ts:113:25)
    at CloudFormationDeploymentTarget.readCurrentTemplate (/home/ec2-user/.nvm/versions/node/v13.7.0/lib/node_modules/aws-cdk/lib/api/deployment-target.ts:53:17)
    at CdkToolkit.deploy (/home/ec2-user/.nvm/versions/node/v13.7.0/lib/node_modules/aws-cdk/lib/cdk-toolkit.ts:114:33)
    at main (/home/ec2-user/.nvm/versions/node/v13.7.0/lib/node_modules/aws-cdk/bin/cdk.ts:212:16)
    at initCommandLine (/home/ec2-user/.nvm/versions/node/v13.7.0/lib/node_modules/aws-cdk/bin/cdk.ts:164:9)
```
-->

### Environment

  - **CLI Version      :** 1.22.0 (build 309ac1b)
  - **Framework Version:**
  - **OS               :**  Linux
  - **Language         :** Typescript

### Other

--- 

This is :bug: Bug Report

**Comment by rix0rrr** [comment]
Your bug report seems to be:

`AWS_ACCESS_KEY_ID` etc. aren't respected by CDK CLI.

Since we use that facility ourselves every day, I have a hard time believing that. I don't know why it's not working on your particular setup, but it's not that the feature does not work.

Looking at your script, it seems to me it relies on the ordering of keys in the JSONified response to `assume-role`, which scares me a little. We usually use a script somewhat like this:

```
creds=$(mktemp -d)/creds.json
aws sts assume-role --role-arn "${assumeRole.roleArn}" --role-session-name "${assumeRole.sessionName}" ${externalId} > $creds
export AWS_ACCESS_KEY_ID="$(cat ${creds} | grep "AccessKeyId" | cut -d\'"\' -f 4)"
export AWS_SECRET_ACCESS_KEY="$(cat ${creds} | grep "SecretAccessKey" | cut -d\'"\' -f 4)"
export AWS_SESSION_TOKEN="$(cat ${creds} | grep "SessionToken" | cut -d\'"\' -f 4)"
```

You might try pasting the entire log with `cdk deploy -v` if you insist this is a CDK bug, but otherwise I'd refer you to StackOverflow for guidance.

**Comment by dohoangn** [comment]
this is actually working:
unset AWS_ACCESS_KEY_ID ;
creds=$(mktemp -d)/creds.json ;
aws sts assume-role --role-arn arn:aws:iam::9999999:role/ProvisioningRole --role-session-name "Deploy" > $creds ;
export AWS_ACCESS_KEY_ID=`cat ${creds} |  grep "AccessKeyId" | cut -d '"' -f 4`
export AWS_SECRET_ACCESS_KEY=`cat ${creds} | grep "SecretAccessKey" | cut -d '"' -f 4`
export AWS_SECRET_ACCESS_KEY=`cat ${creds} | grep "SecretAccessKey" | cut -d '"' -f 4`
export AWS_SESSION_TOKEN=`cat ${creds} | grep "SessionToken" | cut -d '"' -f 4`
