### ISSUE TITLE
SecretValue.secretsManager should validate input doesn't contain `:`

### ISSUE THREAD

**Issue by ahammond** [aws/aws-cdk#6272]
While deploying a delivlib pipeline, cdk fails to run with "Given input did not match expected format". `synth` and `diff` work as expected.

### Reproduction Steps
[pipeline.zip](https://github.com/aws/aws-cdk/files/4200262/pipeline.zip)

```
unzip pipeline.zip
cd pipeline
npm install
# change env for deploy in bin/pipeline.ts
cdk --profile your-env deploy
```

### Error Log

```
Do you wish to deploy these changes (y/n)? y
cdk-library-pipeline: deploying...
cdk-library-pipeline: creating CloudFormation changeset...

 ❌  cdk-library-pipeline failed: Error [ValidationError]: Given input did not match expected format
    at Request.extractError (/Users/andrew.hammond/gowork/src/github.com/myhelix/cdk-library/pipeline/node_modules/aws-sdk/lib/protocol/query.js:50:29)
    at Request.callListeners (/Users/andrew.hammond/gowork/src/github.com/myhelix/cdk-library/pipeline/node_modules/aws-sdk/lib/sequential_executor.js:106:20)
    at Request.emit (/Users/andrew.hammond/gowork/src/github.com/myhelix/cdk-library/pipeline/node_modules/aws-sdk/lib/sequential_executor.js:78:10)
    at Request.emit (/Users/andrew.hammond/gowork/src/github.com/myhelix/cdk-library/pipeline/node_modules/aws-sdk/lib/request.js:683:14)
    at Request.transition (/Users/andrew.hammond/gowork/src/github.com/myhelix/cdk-library/pipeline/node_modules/aws-sdk/lib/request.js:22:10)
    at AcceptorStateMachine.runTo (/Users/andrew.hammond/gowork/src/github.com/myhelix/cdk-library/pipeline/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at /Users/andrew.hammond/gowork/src/github.com/myhelix/cdk-library/pipeline/node_modules/aws-sdk/lib/state_machine.js:26:10
    at Request.<anonymous> (/Users/andrew.hammond/gowork/src/github.com/myhelix/cdk-library/pipeline/node_modules/aws-sdk/lib/request.js:38:9)
    at Request.<anonymous> (/Users/andrew.hammond/gowork/src/github.com/myhelix/cdk-library/pipeline/node_modules/aws-sdk/lib/request.js:685:12)
    at Request.callListeners (/Users/andrew.hammond/gowork/src/github.com/myhelix/cdk-library/pipeline/node_modules/aws-sdk/lib/sequential_executor.js:116:18) {
  message: 'Given input did not match expected format',
  code: 'ValidationError',
  time: 2020-02-13T17:52:16.805Z,
  requestId: '9059d405-d5c6-4459-8c58-ea0df9d9cdd9',
  statusCode: 400,
  retryable: false,
  retryDelay: 22.075427537895088
}
Given input did not match expected format
```

### Environment

  - **CLI Version      :** 1.23.0
  - **Framework Version:** 1.19.0
  - **OS               :** Darwin 18.7.0
  - **Language         :** Typescript

### Other

I've tried with both CLI version 1.19.0 and latest. I locked the framework version to 1.19.0 because of https://github.com/awslabs/aws-delivlib/pull/242 The code in pipeline.zip is based very closely on the example at https://github.com/awslabs/aws-delivlib/blob/master/pipeline/delivlib.ts so I don't believe it's seriously broken.

--- 

This is :bug: Bug Report

**Comment by rix0rrr** [comment]
Well that is very unhelpful. Looks like CloudFormation is telling you this which means the generated template itself must be wrong in some way. 

Have you had a look at it yet? You can find it in the `cdk.out` directory.

**Comment by ahammond** [comment]
@rix0rrr I've never actually looked in there. My only experience with CloudFormation has been via CDK. Would it make sense to post it here? Would I need to remove / obfuscate any private information before posting it?

**Comment by rix0rrr** [comment]
You might need to obfuscate account numbers and potentially bucket names (if hardcoded). You shouldn't have hardcoded secrets in there anyway. Other than that, I think nothing.

**Comment by ahammond** [comment]
@rix0rrr Thanks. Looks like there's nothing too bad. Attached:
[cdk_out.zip](https://github.com/aws/aws-cdk/files/4220887/cdk_out.zip)

**Comment by rix0rrr** [comment]
The issue is this:

```
                  "OAuthToken": "{{resolve:secretsmanager:github-token-ah::::SecretString:::}}",
```

And it's because you put `:::` in there:

```
token: cdk.SecretValue.secretsManager('github-token-ah:::'),
```

**Comment by ahammond** [comment]
@rix0rrr thanks for the debugging! I fixed my code and now have a working delivlib pipeline.

**Comment by BwL1289** [comment]
For anyone who comes across this. Check that when you are creating a secret you don't accidentally use `SecretValue` directly and you're using a method (like `SecretValue.unsafe_plain_text()`).

In python your type checker won't pick up on it so it's easy to miss.
