### ISSUE TITLE
DynamoDB global table creation fails

### ISSUE THREAD

**Issue by aaronbrashears** [aws/aws-cdk#6287]
I tested out the new DynamoDB global table available in cdk 1.24 and instead of creating a table, I got an error message. I made a quick application with `npx aws-cdk init app --language=typescript` and then added the following code to the generated stack:

```typescript
    new dynamodb.Table(this, 'GlobalTableTest', {
      partitionKey: {
        name: 'bandname',
        type: dynamodb.AttributeType.STRING,
      },
      sortKey: {
        name: 'albumname',
        type: dynamodb.AttributeType.STRING,
      },
      billingMode: dynamodb.BillingMode.PAY_PER_REQUEST,
      pointInTimeRecovery: true,
      replicationRegions: ['us-west-2', 'us-east-2'],
      stream: dynamodb.StreamViewType.NEW_AND_OLD_IMAGES,
    });
```

### Environment

  - **CDK CLI Version:** 1.24.0 (build 6619e36)
  - **Module Version:** @aws-cdk/aws-dynamodb@1.24.
  - **OS:** OSX Mojave
  - **Language:** TypeScript

### Other information
```
 4/6 | 1:36:23 PM | CREATE_FAILED        | Custom::DynamoDBReplica    | GlobalTableTest/Replicaus-west-2/Default (GlobalTableTestReplicauswest29295D371) Failed to create resource. Error: Cannot add, delete, or update the local region through ReplicaUpdates. Use CreateTable, DeleteTable, or UpdateTable as required.
    at invokeUserFunction (/var/task/framework.js:85:19)
    at process._tickCallback (internal/process/next_tick.js:68:7)
Remote function error: ValidationException: Cannot add, delete, or update the local region through ReplicaUpdates. Use CreateTable, DeleteTable, or UpdateTable as required.
    at Request.extractError (/tmp/node_modules/aws-sdk/lib/protocol/json.js:51:27)
    at Request.callListeners (/tmp/node_modules/aws-sdk/lib/sequential_executor.js:106:20)
    at Request.emit (/tmp/node_modules/aws-sdk/lib/sequential_executor.js:78:10)
    at Request.emit (/tmp/node_modules/aws-sdk/lib/request.js:683:14)
    at Request.transition (/tmp/node_modules/aws-sdk/lib/request.js:22:10)
    at AcceptorStateMachine.runTo (/tmp/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at /tmp/node_modules/aws-sdk/lib/state_machine.js:26:10
    at Request.<
	new CustomResource (.../global-table-test/node_modules/@aws-cdk/aws-cloudformation/lib/custom-resource.ts:163:21)
	\_ Table.createReplicaTables (.../global-table-test/node_modules/@aws-cdk/aws-dynamodb/lib/table.ts:1052:29)
	\_ new Table (.../global-table-test/node_modules/@aws-cdk/aws-dynamodb/lib/table.ts:663:12)
	\_ new GlobalTableTestStack (.../global-table-test/lib/global-table-test-stack.ts:9:5)
	\_ Object.<anonymous> (.../global-table-test/bin/global-table-test.ts:7:1)
	\_ Module._compile (internal/modules/cjs/loader.js:1151:30)
	\_ Module.m._compile (.../global-table-test/node_modules/ts-node/src/index.ts:814:23)
	\_ Module._extensions..js (internal/modules/cjs/loader.js:1171:10)
	\_ Object.require.extensions.<computed> [as .ts] (.../global-table-test/node_modules/ts-node/src/index.ts:817:12)
	\_ Module.load (internal/modules/cjs/loader.js:1000:32)
	\_ Function.Module._load (internal/modules/cjs/loader.js:899:14)
	\_ Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)
	\_ main (.../global-table-test/node_modules/ts-node/src/bin.ts:226:14)
	\_ Object.<anonymous> (.../global-table-test/node_modules/ts-node/src/bin.ts:485:3)
	\_ Module._compile (internal/modules/cjs/loader.js:1151:30)
	\_ Object.Module._extensions..js (internal/modules/cjs/loader.js:1171:10)
	\_ Module.load (internal/modules/cjs/loader.js:1000:32)
	\_ Function.Module._load (internal/modules/cjs/loader.js:899:14)
	\_ Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)
	\_ /usr/local/lib/node_modules/npm/node_modules/libnpx/index.js:268:14
```

**Comment by jogold** [comment]
In which region are you deploying this stack? `replicationRegions` should list additional regions only.

**Comment by RomainMuller** [comment]
If @jogold turns out right, we should look into proactively looking for this and emitting a better error message in this case...

**Comment by jogold** [comment]
@RomainMuller when the region is defined there's already an error message:
https://github.com/aws/aws-cdk/blob/a97b48ae4a7dafe050997e00bb57bf64117b551b/packages/%40aws-cdk/aws-dynamodb/lib/table.ts#L1024-L1026

See #6306 which handles this for env agnostic stacks.
