### ISSUE TITLE
Issue with CdkWorkshop typescript

### ISSUE THREAD

**Issue by ravanapel** [aws/aws-cdk#6297]
https://cdkworkshop.com/20-typescript/40-hit-counter/200-handler.html

The Typescript CdkWorkshop uses the following import statement:
```js
// file: lambda/hitcounter.js
import { DynamoDB, Lambda } from 'aws-sdk';
```
However, this produces the following error (from the deployed lambda):
```
2020-02-16T12:47:27.490Z	undefined	ERROR	Uncaught Exception
{"errorType":"Runtime.UserCodeSyntaxError","errorMessage":"SyntaxError: Unexpected token {","stack":["Runtime.UserCodeSyntaxError: SyntaxError: Unexpected token {","    
at _loadUserApp (/var/runtime/UserFunction.js:98:13)","    
at Object.module.exports.load (/var/runtime/UserFunction.js:140:17)","    
at Object.<anonymous> (/var/runtime/index.js:45:30)","    
at Module._compile (internal/modules/cjs/loader.js:778:30)","    
at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)","    
at Module.load (internal/modules/cjs/loader.js:653:32)","    
at tryModuleLoad (internal/modules/cjs/loader.js:593:12)","    
at Function.Module._load (internal/modules/cjs/loader.js:585:3)","    
at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)","    
at startup (internal/bootstrap/node.js:283:19)"]}
```
I googled the error and found the following stackoverflow page:
[https://stackoverflow.com/questions/56859727/why-do-i-get-a-usercodesyntaxerror-when-i-have-no-syntax-error-in-my-code](https://stackoverflow.com/questions/56859727/why-do-i-get-a-usercodesyntaxerror-when-i-have-no-syntax-error-in-my-code)

The guide uses an ES6 style import, which is not supported by the aws node.js 10.x runtime. I changed it to a standard module require syntax and the function worked as expected.

---

This is a 📕 documentation issue

**Comment by ravanapel** [comment]
Submitted issue to https://github.com/aws-samples/aws-cdk-intro-workshop
