### ISSUE TITLE
Pass route53 endpoint to DnsValidatedCertificate in resource property

### ISSUE THREAD

**Issue by brookhong** [aws/aws-cdk#6431]
`DnsValidatedCertificate` does not work in China regions now, as the default host `route53.cn-northwest-1.amazonaws.com.cn` is not accessible. If the custom resource `DnsValidatedCertificate` could accept endpoint from resource property, the issue could be walked around by providing an endpoint from app stack.

### Use Case

We are using `DnsValidatedCertificate` for an internal account in ZHY now, but we got below issue

    Failed to create resource. Inaccessible host: `route53.cn-northwest-1.amazonaws.com.cn'. This service may not be available in the `cn-northwest-1' region.

### Proposed Solution

Add a property to the custom resource, so that user could specify an endpoint for it from code of app stack.

### Other

N/A

* [x] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by skinny85** [comment]
Hey @brookhong ,

thanks for opening the issue. Can you tell us where does the URL `route53.cn-northwest-1.amazonaws.com.cn` come from? I believe we use the [standard SDK client in the `DnsValidatedCertificate` custom resource](https://github.com/aws/aws-cdk/blob/c8a22b176cdee7da2cde15c38a6fc107686cf2d0/packages/%40aws-cdk/aws-certificatemanager/lambda-packages/dns_validated_certificate_handler/lib/index.js#L83-L83) - is it possible that the endpoint is incorrect in the AWS SDK?

Thanks,
Adam

**Comment by brookhong** [comment]
This is where the default endpoint is generated -- https://github.com/aws/aws-sdk-js/blob/master/lib/service.js#L53-L55

Attached some trace info:

    Trace: {service}.{region}.amazonaws.com.cn
        at features.constructor.initialize (***/lib/node_modules/aws-cdk/node_modules/aws-sdk/lib/service.js:55:17)
        at features.constructor.Service [as constructor] (***/lib/node_modules/aws-cdk/node_modules/aws-sdk/lib/service.js:40:10)
        at features.constructor (***/lib/node_modules/aws-cdk/node_modules/aws-sdk/lib/util.js:624:24)
        at new features.constructor (***/lib/node_modules/aws-cdk/node_modules/aws-sdk/lib/util.js:624:24)
        at features.constructor.Service [as constructor] (***/lib/node_modules/aws-cdk/node_modules/aws-sdk/lib/service.js:31:17)
        at new features.constructor (***/lib/node_modules/aws-cdk/node_modules/aws-sdk/lib/util.js:624:24)
        at SDK.service (***/lib/node_modules/aws-cdk/lib/api/util/sdk.ts:151:12)
        at process._tickCallback (internal/process/next_tick.js:68:7)
    Trace: route53.cn-northwest-1.amazonaws.com.cn
        at features.constructor.initialize (***/lib/node_modules/aws-cdk/node_modules/aws-sdk/lib/service.js:57:17)
        at features.constructor.Service [as constructor] (***/lib/node_modules/aws-cdk/node_modules/aws-sdk/lib/service.js:40:10)
        at features.constructor (***/lib/node_modules/aws-cdk/node_modules/aws-sdk/lib/util.js:624:24)
        at new features.constructor (***/lib/node_modules/aws-cdk/node_modules/aws-sdk/lib/util.js:624:24)
        at features.constructor.Service [as constructor] (***/lib/node_modules/aws-cdk/node_modules/aws-sdk/lib/service.js:31:17)
        at new features.constructor (***/lib/node_modules/aws-cdk/node_modules/aws-sdk/lib/util.js:624:24)
        at SDK.service (***/lib/node_modules/aws-cdk/lib/api/util/sdk.ts:151:12)
        at process._tickCallback (internal/process/next_tick.js:68:7)
    [Error at /HelloCdkStack] Inaccessible host: `route53.cn-northwest-1.amazonaws.com.cn'. This service may not be available in the `cn-northwest-1' region.
    Found errors
