### ISSUE TITLE
Unable to reference resources across multiple levels of nested stacks

### ISSUE THREAD

**Issue by rzamana** [aws/aws-cdk#6473]
### Minimal repro

```ts
const top = new Stack();
const topLevel = new CfnResource(top, 'toplevel', { type: 'TopLevel' });
const nested1 = new NestedStack(top, 'nested1');
const nested2 = new NestedStack(nested1, 'nested2');

new CfnResource(nested2, 'refToTopLevel', {
  type: 'BottomLevel',
  properties: { RefToTopLevel: topLevel.ref }
});
```

### Original issue

I'm trying to create an EKS Cluster on a NestedStack.

I have all my dependencies separated in NestedStacks (VPC, LoadBalancer, Services). So, it makes sense to have a NestedStack to create my EKS Cluster.

The EKS Cluster can be included in a Main Stack, but not on a Nested. When the EKS Cluster is on a Nested Stack, the cdk gives me the follow error:
```
jsii.errors.JSIIError: Nested stack 'eks-test/EksCluster' cannot depend on a parent stack 'eks-test'
```

### Reproduction Steps

- Create a sample app using the cdk
- Create a NestedStack including an eks cluster
- Try to synth

### Error Log
```
(.env) ⋊> ~/P/s/eks_test on master ⨯ cdk synth                                                                                                                                                                                      [18:46:48]
jsii.errors.JavaScriptError:
  Error: Nested stack 'eks-test/EksCluster' cannot depend on a parent stack 'eks-test'
      at Object.addDependency (/private/var/folders/w2/t7tdyk5576q1k8kqyjg2ndhh0000gp/T/jsii-kernel-r9YaoT/node_modules/@aws-cdk/core/lib/deps.js:57:15)
      at NestedStack.addDependency (/private/var/folders/w2/t7tdyk5576q1k8kqyjg2ndhh0000gp/T/jsii-kernel-r9YaoT/node_modules/@aws-cdk/core/lib/stack.js:200:16)
      at KubectlProvider.prepareCrossReference (/private/var/folders/w2/t7tdyk5576q1k8kqyjg2ndhh0000gp/T/jsii-kernel-r9YaoT/node_modules/@aws-cdk/core/lib/stack.js:692:28)
      at KubectlProvider.prepareCrossReference (/private/var/folders/w2/t7tdyk5576q1k8kqyjg2ndhh0000gp/T/jsii-kernel-r9YaoT/node_modules/@aws-cdk/aws-cloudformation/lib/nested-stack.js:111:26)
      at KubectlProvider.prepare (/private/var/folders/w2/t7tdyk5576q1k8kqyjg2ndhh0000gp/T/jsii-kernel-r9YaoT/node_modules/@aws-cdk/core/lib/stack.js:560:43)
      at Function.prepare (/private/var/folders/w2/t7tdyk5576q1k8kqyjg2ndhh0000gp/T/jsii-kernel-r9YaoT/node_modules/@aws-cdk/core/lib/construct.js:87:27)
      at Function.synth (/private/var/folders/w2/t7tdyk5576q1k8kqyjg2ndhh0000gp/T/jsii-kernel-r9YaoT/node_modules/@aws-cdk/core/lib/construct.js:51:14)
      at App.synth (/private/var/folders/w2/t7tdyk5576q1k8kqyjg2ndhh0000gp/T/jsii-kernel-r9YaoT/node_modules/@aws-cdk/core/lib/app.js:71:52)
      at _wrapSandboxCode (/Users/rafaelzamanakineippe/Public/sentia/eks_test/.env/lib/python3.7/site-packages/jsii/_embedded/jsii/jsii-runtime.js:7665:51)
      at Kernel._wrapSandboxCode (/Users/rafaelzamanakineippe/Public/sentia/eks_test/.env/lib/python3.7/site-packages/jsii/_embedded/jsii/jsii-runtime.js:8301:19)
      at ret._ensureSync (/Users/rafaelzamanakineippe/Public/sentia/eks_test/.env/lib/python3.7/site-packages/jsii/_embedded/jsii/jsii-runtime.js:7665:25)
      at Kernel._ensureSync (/Users/rafaelzamanakineippe/Public/sentia/eks_test/.env/lib/python3.7/site-packages/jsii/_embedded/jsii/jsii-runtime.js:8274:20)
      at Kernel.invoke (/Users/rafaelzamanakineippe/Public/sentia/eks_test/.env/lib/python3.7/site-packages/jsii/_embedded/jsii/jsii-runtime.js:7664:26)
      at KernelHost.processRequest (/Users/rafaelzamanakineippe/Public/sentia/eks_test/.env/lib/python3.7/site-packages/jsii/_embedded/jsii/jsii-runtime.js:7372:28)
      at KernelHost.run (/Users/rafaelzamanakineippe/Public/sentia/eks_test/.env/lib/python3.7/site-packages/jsii/_embedded/jsii/jsii-runtime.js:7312:14)
      at Immediate.setImmediate [as _onImmediate] (/Users/rafaelzamanakineippe/Public/sentia/eks_test/.env/lib/python3.7/site-packages/jsii/_embedded/jsii/jsii-runtime.js:7315:37)
      at runCallback (timers.js:705:18)
      at tryOnImmediate (timers.js:676:5)
      at processImmediate (timers.js:658:5)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "app.py", line 13, in <module>
    app.synth()
  File "/Users/rafaelzamanakineippe/Public/sentia/eks_test/.env/lib/python3.7/site-packages/aws_cdk/core/__init__.py", line 3585, in synth
    return jsii.invoke(self, "synth", [])
  File "/Users/rafaelzamanakineippe/Public/sentia/eks_test/.env/lib/python3.7/site-packages/jsii/_kernel/__init__.py", line 113, in wrapped
    return _recursize_dereference(kernel, fn(kernel, *args, **kwargs))
  File "/Users/rafaelzamanakineippe/Public/sentia/eks_test/.env/lib/python3.7/site-packages/jsii/_kernel/__init__.py", line 288, in invoke
    args=_make_reference_for_native(self, args),
  File "/Users/rafaelzamanakineippe/Public/sentia/eks_test/.env/lib/python3.7/site-packages/jsii/_kernel/providers/process.py", line 348, in invoke
    return self._process.send(request, InvokeResponse)
  File "/Users/rafaelzamanakineippe/Public/sentia/eks_test/.env/lib/python3.7/site-packages/jsii/_kernel/providers/process.py", line 318, in send
    raise JSIIError(resp.error) from JavaScriptError(resp.stack)
jsii.errors.JSIIError: Nested stack 'eks-test/EksCluster' cannot depend on a parent stack 'eks-test'
Subprocess exited with error 1
```

### Environment

  - **CLI Version      : 1.26.0 (build e251651)**
  - **Framework Version: 1.26.0**
  - **OS               : MacOS Catalina**
  - **Language         : python**

### Other

For more information I create the public repository [rzamana/cdk_eks_tests](https://github.com/rzamana/cdk_eks_tests)

--- 

This is :bug: Bug Report

**Comment by eladb** [comment]
It seems like the is some dependency between your parent stack and the nested stack. Are you able to provide a minimal reproducing code snippet?

**Comment by kbessas** [comment]
@eladb I believe the original report also has a repo with a Python project reproducing the issue.

Posting again for reference here: https://github.com/rzamana/cdk_eks_tests

**Comment by eladb** [comment]
Confirming this is an issue caused by the fact the the EKS module uses a nested stack itself and this uncovered a bug when referencing resources across multiple levels of nesting.

**Comment by eladb** [comment]
Repurposing this issue.

**Comment by nateiler** [comment]
Also experiencing this issue in v1.30.  In our case we're constructing an API Gateway and have exceeded the 200 resource limit.

**Comment by eladb** [comment]
Thanks for letting us know

**Comment by cmckni3** [comment]
Experiencing this with 1.31.0 but with the DynamoDB `replicationRegions` custom resource as mentioned in #6726.
