### ISSUE TITLE
CDK Problem - EKS with exsiting VPC

### ISSUE THREAD

**Issue by aws-patrickc** [aws/aws-cdk#6536]
### The Question
I am trying to deploy EKS cluster in existing VPC with the use of `cdk.context.json` and I am currently stuck, any guidance/hint would be greatly appreciated.

The code looks like this:

```
class EksStack(core.Stack):

    def __init__(self, scope: core.Construct, id: str, **kwargs) -> None:
        super().__init__(scope, id, **kwargs)

        env_vpc = ec2.Vpc.from_lookup(
            self,
            id='MyVPC',
            vpc_name='my-vpc',
        )

        cluster = eks.Cluster(
            self,
            'eks-d',
            default_capacity=2,
            default_capacity_instance= ec2.InstanceType(instance_type_identifier='c5.xlarge'),
            vpc=env_vpc,
            cluster_name='my-eks-cluster',
            vpc_subnets=env_vpc.select_subnets(subnet_name='my-subnets'),
        )
```
When I try to put subnets with `vpc_subnets=env_vpc.select_subnets(subnet_name='my-subnets')` I got error, Traceback (most recent call last):

```
File "app.py", line 9, in <module>
    EksStack(app, "stack-eks-d", env={'account': '658199564749','region': 'eu-west-1'})
  File "/Users/szychowskim/eks/.env/lib/python3.6/site-packages/jsii/_runtime.py", line 66, in __call__
    inst = super().__call__(*args, **kwargs)
  File "/Users/szychowskim/eks/eks/eks_stack.py", line 25, in __init__
    vpc_subnets=env_vpc.select_subnets(subnet_name='sn-d-backend-priv'),
  File "/Users/szychowskim/eks/.env/lib/python3.6/site-packages/jsii/_runtime.py", line 66, in __call__
    inst = super().__call__(*args, **kwargs)
  File "/Users/szychowskim/eks/.env/lib/python3.6/site-packages/aws_cdk/aws_eks/__init__.py", line 3599, in __init__
    jsii.create(Cluster, self, [scope, id, props])
  File "/Users/szychowskim/eks/.env/lib/python3.6/site-packages/jsii/_kernel/__init__.py", line 229, in create
    interfaces=[iface.__jsii_type__ for iface in getattr(klass, "__jsii_ifaces__", [])],
  File "/Users/szychowskim/eks/.env/lib/python3.6/site-packages/jsii/_kernel/providers/process.py", line 333, in create
    return self._process.send(request, CreateResponse)
  File "/Users/szychowskim/eks/.env/lib/python3.6/site-packages/jsii/_kernel/providers/process.py", line 318, in send
    raise JSIIError(resp.error) from JavaScriptError(resp.stack)
jsii.errors.JSIIError: Expected array type, got {"$jsii.struct":{"fqn":"@aws-cdk/aws-ec2.SelectedSubnets","data":{"availabilityZones":["eu-west-1a","eu-west-1b","eu-west-1c"],"hasPublic":false,"internetConnectivityEstablished":{"$jsii.byref":"Object@10005"},"subnetIds":["subnet-xxxxxxxxx","subnet-xxxxxxxxx","subnet-xxxxxxxxx"],"subnets":[{"$jsii.byref":"@aws-cdk/core.Resource@10006"},{"$jsii.byref":"@aws-cdk/core.Resource@10007"},{"$jsii.byref":"@aws-cdk/core.Resource@10008"}]}}}
```
my `cdk.context.json` has these subnets:

```
 {
        "name": "my-subnets",
        "type": "Private",
        "subnets": [
          {
            "subnetId": "subnet-xxxxxxxxx",
            "cidr": "10.168.48.0/22",
            "availabilityZone": "eu-west-1a",
            "routeTableId": "rtb-1234567"
          },
          {
            "subnetId": "subnet-xxxxxxxxx",
            "cidr": "10.168.52.0/22",
            "availabilityZone": "eu-west-1b",
            "routeTableId": "rtb-1234567890123456"
          },
          {
            "subnetId": "subnet-xxxxxxxxx",
            "cidr": "10.168.56.0/22",
            "availabilityZone": "eu-west-1c",
            "routeTableId": "rtb-1234567890123456"
          }
        ]
      }
```

### Environment

  - **CDK CLI Version:** 1.26.0 (build e251651)
  - **Module Version:** 1.26
  - **OS:** MacOS
  - **Language:** Python

**Comment by jargelo** [comment]
I've had this one. `vpc_subnets` needs to be a list, so try this: `[vpc_subnets=env_vpc.select_subnets(subnet_name='my-subnets')],

Frustratingly it does not expect a list for the `vpc_subnets` parameter in the `Cluster.add_capacity` call.

**Comment by eladb** [comment]
@aws-patrickc did you manage to get this resolved?

**Comment by aws-patrickc** [comment]
@jargelo @eladb Thanks for the response.

I tried modifying the vpc_subnets as recommended:
```
class EksStack(core.Stack):

    def __init__(self, scope: core.Construct, id: str, **kwargs) -> None:
        super().__init__(scope, id, **kwargs)

        env_vpc = ec2.Vpc.from_lookup(
            self,
            id='MyVPC',
            vpc_name='my-vpc',
        )

        cluster = eks.Cluster(
            self,
            'eks-d',
            default_capacity=2,
            default_capacity_instance= ec2.InstanceType(instance_type_identifier='c5.xlarge'),
            vpc=env_vpc,
            cluster_name='my-eks-cluster',
            vpc_subnets=[env_vpc.select_subnets(subnet_name='my-subnets')],
        )
```
However when I run `cdk synth`, I get the error below:
```
raceback (most recent call last):
  File "app.py", line 9, in <module>
    HelloCdkStack(app, "HelloCdkStack", env=core.Environment(region="us-east-1",account="xxxxxxxxxxxxxx"))
  File "/Users/chenichu/WorkDocs/CDK/hello-cdk/.env/lib/python3.7/site-packages/jsii/_runtime.py", line 66, in __call__
    inst = super().__call__(*args, **kwargs)
  File "/Users/chenichu/WorkDocs/CDK/hello-cdk/hello_cdk/hello_cdk_stack.py", line 28, in __init__
    vpc_subnets=[env_vpc.select_subnets(subnet_name='sn-d-backend-priv')]
  File "/Users/chenichu/WorkDocs/CDK/hello-cdk/.env/lib/python3.7/site-packages/jsii/_runtime.py", line 66, in __call__
    inst = super().__call__(*args, **kwargs)
  File "/Users/chenichu/WorkDocs/CDK/hello-cdk/.env/lib/python3.7/site-packages/aws_cdk/aws_eks/__init__.py", line 3599, in __init__
    jsii.create(Cluster, self, [scope, id, props])
  File "/Users/chenichu/WorkDocs/CDK/hello-cdk/.env/lib/python3.7/site-packages/jsii/_kernel/__init__.py", line 229, in create
    interfaces=[iface.__jsii_type__ for iface in getattr(klass, "__jsii_ifaces__", [])],
  File "/Users/chenichu/WorkDocs/CDK/hello-cdk/.env/lib/python3.7/site-packages/jsii/_kernel/providers/process.py", line 333, in create
    return self._process.send(request, CreateResponse)
  File "/Users/chenichu/WorkDocs/CDK/hello-cdk/.env/lib/python3.7/site-packages/jsii/_kernel/providers/process.py", line 318, in send
    raise JSIIError(resp.error) from JavaScriptError(resp.stack)
jsii.errors.JSIIError: Wire struct type '@aws-cdk/aws-ec2.SelectedSubnets' does not match expected '@aws-cdk/aws-ec2.SubnetSelection'
Subprocess exited with error 1
```

Any other suggestions?

Thanks in advance!

**Comment by eladb** [comment]
Sorry, this is indeed confusing. The `vpc_subnets` property in [`ClusterProps`](https://docs.aws.amazon.com/cdk/api/latest/python/aws_cdk.aws_eks/ClusterProps.html) accepts an array of [`SubnetSelection`](https://docs.aws.amazon.com/cdk/api/latest/python/aws_cdk.aws_ec2/SubnetSelection.html#aws_cdk.aws_ec2.SubnetSelection) objects. You don't have to call `vpc.selectSubnets`:

```python
vpc_subnets=[ec2.SubnetSelection(subnet_name='my-subnets')]
```

Let me know if this works.

**Comment by bambaryla** [comment]
This is rather a workaround. As visible in the example VPC is looked up first for the cluster to be deployed. The idea was to filter some subnets from the selected VPC.
If I will call EC2 service directly then I will choose all subnets matching the name.
In this case there is no encapsulation here and we account (region in fact) wide unique subnets names must be kept.

**Comment by eladb** [comment]
> This is rather a workaround. As visible in the example VPC is looked up first for the cluster to be deployed. The idea was to filter some subnets from the selected VPC.
> If I will call EC2 service directly then I will choose all subnets matching the name.
> In this case there is no encapsulation here and we account (region in fact) wide unique subnets names must be kept.

This is the API we have across the library. You specify the `vpc` and then specify "declaration" for subnet selection, instead of specifying an explicit set of subnets.
