### ISSUE TITLE
Upgrade to aws-cdk 1.27 breaks AwsCustomResource - jsii.errors.JSIIError: Expected object reference, got "${Token[TOKEN.144]}"

### ISSUE THREAD

**Issue by mcalello** [aws/aws-cdk#6589]
After upgrading from 1.26.0 to 1.27.0 the following error occurs with any cdk operations, even cdk list:

``` python
jsii.errors.JavaScriptError: 
  Error: Expected object reference, got "${Token[TOKEN.144]}"
      at Object.deserialize (/Users/<redacted path>/.env/lib/python3.7/site-packages/jsii/_embedded/jsii/jsii-runtime.js:6952:23)
      at Kernel._toSandbox (/Users/<redacted path>/.env/lib/python3.7/site-packages/jsii/_embedded/jsii/jsii-runtime.js:8207:61)
      at mapValues (/Users/<redacted path>/.env/lib/python3.7/site-packages/jsii/_embedded/jsii/jsii-runtime.js:6919:29)
      at mapValues (/Users/<redacted path>/.env/lib/python3.7/site-packages/jsii/_embedded/jsii/jsii-runtime.js:7179:27)
      at Object.deserialize (/Users/<redacted path>/.env/lib/python3.7/site-packages/jsii/_embedded/jsii/jsii-runtime.js:6915:20)
      at Kernel._toSandbox (/Users/<redacted path>/.env/lib/python3.7/site-packages/jsii/_embedded/jsii/jsii-runtime.js:8207:61)
      at mapValues (/Users/<redacted path>/.env/lib/python3.7/site-packages/jsii/_embedded/jsii/jsii-runtime.js:6919:29)
      at mapValues (/Users/<redacted path>/.env/lib/python3.7/site-packages/jsii/_embedded/jsii/jsii-runtime.js:7179:27)
      at Object.deserialize (/Users/<redacted path>/.env/lib/python3.7/site-packages/jsii/_embedded/jsii/jsii-runtime.js:6915:20)
      at Kernel._wrapSandboxCode (/Users/<redacted path>/.env/lib/python3.7/site-packages/jsii/_embedded/jsii/jsii-runtime.js:8301:19)
      at Kernel._create (/Users/<redacted path>/.env/lib/python3.7/site-packages/jsii/_embedded/jsii/jsii-runtime.js:7838:26)
      at Kernel.create (/Users/<redacted path>/.env/lib/python3.7/site-packages/jsii/_embedded/jsii/jsii-runtime.js:7585:21)
      at KernelHost.processRequest (/Users/<redacted path>/.env/lib/python3.7/site-packages/jsii/_embedded/jsii/jsii-runtime.js:7372:28)
      at KernelHost.run (/Users/<redacted path>/.env/lib/python3.7/site-packages/jsii/_embedded/jsii/jsii-runtime.js:7312:14)
      at Immediate.setImmediate [as _onImmediate] (/Users/<redacted path>/.env/lib/python3.7/site-packages/jsii/_embedded/jsii/jsii-runtime.js:7315:37)
      at runCallback (timers.js:705:18)
      at tryOnImmediate (timers.js:676:5)
      at processImmediate (timers.js:658:5)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "app.py", line 66, in <module>
    tags=endpoint_tags, env=core.Environment(region=AWS_REGION, account=AWS_ACCOUNT))
  File "/Users/<redacted path>/.env/lib/python3.7/site-packages/jsii/_runtime.py", line 66, in __call__
    inst = super().__call__(*args, **kwargs)
  File "/Users/<redacted path>/cdk/MyStack.py", line 72, in __init__
    region=props["REGION"]
  File "/Users/<redacted path>/.env/lib/python3.7/site-packages/jsii/_runtime.py", line 66, in __call__
    inst = super().__call__(*args, **kwargs)
  File "/Users/<redacted path>/cdk/custom/MyConstruct.py", line 41, in __init__
    role= my_custom_resource_role
  File "/Users/<redacted path>/.env/lib/python3.7/site-packages/jsii/_runtime.py", line 66, in __call__
    inst = super().__call__(*args, **kwargs)
  File "/Users/<redacted path>/.env/lib/python3.7/site-packages/aws_cdk/custom_resources/__init__.py", line 471, in __init__
    jsii.create(AwsCustomResource, self, [scope, id, props])
  File "/Users/<redacted path>/.env/lib/python3.7/site-packages/jsii/_kernel/__init__.py", line 229, in create
    interfaces=[iface.__jsii_type__ for iface in getattr(klass, "__jsii_ifaces__", [])],
  File "/Users/<redacted path>/.env/lib/python3.7/site-packages/jsii/_kernel/providers/process.py", line 333, in create
    return self._process.send(request, CreateResponse)
  File "/Users/<redacted path>/.env/lib/python3.7/site-packages/jsii/_kernel/providers/process.py", line 318, in send
    raise JSIIError(resp.error) from JavaScriptError(resp.stack)
jsii.errors.JSIIError: Expected object reference, got "${Token[TOKEN.144]}"
```

### Reproduction Steps

This seems to be pointing to use of the AwsCustomResource constructor here, specifically the role argument:

```python
        my_custom_resource = cr.AwsCustomResource(self, prefix+'my-custom-resource', 
            on_create=aws_sdk_call,
            on_update=aws_sdk_call,
            resource_type="Custom::MyCustomResource",
            role=my_custom_resource_role
        )
```

### Error Log

```
jsii.errors.JSIIError: Expected object reference, got "${Token[TOKEN.144]}"
Subprocess exited with error 1
```

### Environment

  - **CLI Version      : aws-cli/1.16.223 Python/3.7.4 Darwin/18.7.0 botocore/1.12.213
  - **Framework Version: 1.27.0
  - **OS               : MAC OSX
  - **Language         : Python3

### Workaround
No workaround was found - so I had to roll back to 1.26.0.

This is :bug: Bug Report

**Comment by jogold** [comment]
Did you apply the breaking change https://github.com/aws/aws-cdk/blob/v1.27.0/CHANGELOG.md#-breaking-changes?

> **custom-resources**: `physicalResourceId` and `physicalResourceIdPath` were unified to a concrete type under the `physicalResourceId` property. Use `PhysicalResourceId.fromResponse` and `PhysicalResourceId.of` factory functions to specify it.

**Comment by mcalello** [comment]
Thanks @jogold  - we noticed that breaking change, but I'm not sure how that would apply here to an AwsCustomResource as it internally hides/manages it's PhysicalResouceId.

**Comment by iliapolo** [comment]
@mcalello What do you mean by hides/manages?

The `physical_resource_id` property is defined on the `AwsSdkCall` objects. You haven't shared the code of the `aws_sdk_call` variable instantiation, but it should be something like:

```python
aws_sdk_call = cr.AwsSdkCall(
  service='s3', 
  action='createBucket', 
  physical_resource_id=cr.PhysicalResourceId.of("Id")
)
```

**Comment by mcalello** [comment]
Thank you - @iliapolo and @jogold - you guys were both right. Updating the AwsSdkCall resolved the issue.  👍
