### ISSUE TITLE
Type '(ICfnConditionExpression | ManualApprovalAction)[]' is not assignable to type 'IAction[]

### ISSUE THREAD

**Issue by michaelday008** [aws/aws-cdk#6647]
Following CDK documents here:
 https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_core.Fn.html
https://docs.amazonaws.cn/en_us/AWSCloudFormation/latest/UserGuide/intrinsic-function-reference-conditions.html#intrinsic-function-reference-conditions-if

According to the documents,
```
Currently, AWS CloudFormation supports the Fn::If intrinsic function in the metadata attribute, update policy attribute, and property values in the Resources section and Outputs sections of a template. You can use the AWS::NoValue pseudo parameter as a return value to remove the corresponding property.
```

### Reproduction Steps

Based on the above documents, I have created the following code (snippet):
```
const deployStage = pipeline.addStage({
      stageName: 'Deploy',
      actions: [Fn.conditionIf ('deployCondition', ApprovalAction, cdk.Aws.NO_VALUE), deployAction]
    });
```

### Error Log

This results in the following error:
```
lib/dev-portal-deploy-stack.ts:302:7 - error TS2322: Type '(ICfnConditionExpression | ElasticBeanStalkDeployAction)[]' is not assignable to type 'IAction[]'.
  Type 'ICfnConditionExpression | ElasticBeanStalkDeployAction' is not assignable to type 'IAction'.
    Type 'ICfnConditionExpression' is missing the following properties from type 'IAction': actionProperties, bind, onStateChange

302       actions: [
          ~~~~~~~

  node_modules/@aws-cdk/aws-codepipeline/lib/pipeline.d.ts:38:14
    38     readonly actions?: IAction[];
                    ~~~~~~~
    The expected type comes from property 'actions' which is declared here on type 'StageOptions'

```

### Environment

  - **CLI Version      : aws-cli/1.16.309 Python/3.6.0 Windows/10 botocore/1.13.45
  - **Framework Version: 1.27.0
  - **OS               :Windows 10
  - **Language         : Typescript

### Other

Although the CDK docs state that you can use AWS::NoValue, and there are several code samples on the web also confirming this:
https://medium.com/@softwarecrafter/aws-cloudformation-advanced-template-tricks-a5fdc5e83147
https://www.frostbyte.us/conditionally-create-codepipeline-actions-based-on-cloudformation-conditions/

Actually attempting to follow the CDK docs and implement this fails because apparently, cdk.Aws.NO_VALUE cannot be assigned to actions because it expects something that complies with the IAction interface.

Is there a way around this?  I need to conditionally add either entire stages (best, but zero support for this it seems as you can't attach conditions to stages), or at very minimum have a bunch of stages that are basically just approval stages, with the deploy actions conditional inside of them.

This is a valid cloudformation action, so why does CDK not support this?

Related (python bug, but maybe this is an underlying issue with the root affecting python and typescript): https://github.com/aws/aws-cdk/issues/4792

--- 

This is :bug: Bug Report

**Comment by skinny85** [comment]
Hey @michaelday008 ,

thanks for opening the issue. The problem that you've run into is a fundamental conflict between static typing and the way CloudFormation templates are constructed.

In languages with static typing, we want things like the `actions` (and `stages`) property to have a strong type like `IAction`. Allowing you to pass `Fn::If` there kind of violates that entire premise.

Before I talk about how we can work around this, let me ask you: can you instead move the conditions from the CFN template to your code directly? Like this:

```ts
const deployStage = pipeline.addStage({
  stageName: 'Deploy',
});
if (condition) {
  deployStage.addAction(ApprovalAction);
}
```

I feel like you're trying to emulate what you had in CloudFormation 1:1, instead of maybe using the full power of a programming language that is now at your disposal (which is not the case in a CFN template).

Let me know if this is an option.

Thanks,
Adam

**Comment by michaelday008** [comment]
@skinny85 Our use case is creating service catalog templates so unfortunately we will not be able to use any language specific looping or if/then logic because we don't know what those values will be when we run `cdk synth`.

The reason service catalog templates are the preferred use case is because we want a single source of truth for what we have deployed, and a single place to view all our services.

Although you can view deployed stacks in cloudformation, it is not nearly so user friendly as the service catalog interface.

If we just put every stack in a git repository and `cdk deploy` it's much harder to reason about what is deployed because there is no concrete connection between the git repository and you have to go into each one manually and run a cdk diff to see if the stack is deployed.

**Comment by skinny85** [comment]
Ok. You can use our [escape hatch mechanism](https://docs.aws.amazon.com/cdk/latest/guide/cfn_layer.html). After adding the `ApprovalAction` like normal to the pipeline, do:

```ts
        const cfnPipeline = pipeline.node.defaultChild as codepipeline.CfnPipeline;
        cfnPipeline.addPropertyOverride('Stages.1.Actions', [
            cdk.Fn.conditionIf('Condition', ApprovalAction, cdk.Aws.NO_VALUE),
        ]);
```

Let me know if this works!

Thanks,
Adam

**Comment by michaelday008** [comment]
@skinny85 

I have tried this method in a new pipeline that I'm creating where the deployment actions are optional and tried the escape hatch mechanism, but got an error.  I tried 2 different variations below.

```
const useProdCondition = new cdk.CfnCondition(this, "useProdCondition", {
      expression: cdk.Fn.conditionEquals(usedRegion, 'ap-southeast-2')
    });
		
const cfnPipeline = pipeline.node.defaultChild as codepipeline.CfnPipeline;
        cfnPipeline.addPropertyOverride('Stages.1.Actions', [
          ebApprovalAction,
            cdk.Fn.conditionIf('useProdCondition', ebProdDeployAction, ebDevDeployAction),
        ]);		
```
C:\Users\username\code\applicationname-deploy\node_modules\@aws-cdk\core\lib\private\resolve.ts:144
    throw new Error('Trying to resolve() a Construct at ' + pathName);
          ^
Error: Trying to resolve() a Construct at /Resources/PIPELINE10101AC1/Properties/Stages/1/Actions/0/_pipeline/node
at resolve (C:\Users\username\code\applicationname-deploy\node_modules\@aws-cdk\core\lib\private\resolve.ts:144:11)
    at Object.resolve (C:\Users\username\code\applicationname-deploy\node_modules\@aws-cdk\core\lib\private\resolve.ts:49:32)
    at resolve (C:\Users\username\code\applicationname-deploy\node_modules\@aws-cdk\core\lib\private\resolve.ts:154:39)
    at Object.resolve (C:\Users\username\code\applicationname-deploy\node_modules\@aws-cdk\core\lib\private\resolve.ts:49:32)
    at resolve (C:\Users\username\code\applicationname-deploy\node_modules\@aws-cdk\core\lib\private\resolve.ts:154:39)
    at Object.resolve (C:\Users\username\code\applicationname-deploy\node_modules\@aws-cdk\core\lib\private\resolve.ts:49:32)
    at C:\Users\username\code\applicationname-deploy\node_modules\@aws-cdk\core\lib\private\resolve.ts:121:45
    at Array.map (<anonymous>)
    at resolve (C:\Users\username\code\applicationname-deploy\node_modules\@aws-cdk\core\lib\private\resolve.ts:121:8)
    at Object.resolve (C:\Users\username\code\applicationname-deploy\node_modules\@aws-cdk\core\lib\private\resolve.ts:49:32)
Subprocess exited with error 1
```

```
const cfnPipeline = pipeline.node.defaultChild as codepipeline.CfnPipeline;
        cfnPipeline.addPropertyOverride('Stages.1.Actions', [
            cdk.Fn.conditionIf('useProdCondition', ebProdDeployAction, cdk.Aws.NO_VALUE),
        ]);
```
```				
throw new Error('Trying to resolve() a Construct at ' + pathName);
          ^
Error: Resolution error: Trying to resolve() a Construct at /Resources/PIPELINE10101AC1/Properties/Stages/1/Actions/0/Fn::If/1/actionProperties/role/role/node.
Object creation stack:
  at new Intrinsic (C:\Users\username\code\applicationname-deploy\node_modules\@aws-cdk\core\lib\private\intrinsic.ts:28:26)
  at new FnConditionBase (C:\Users\username\code\applicationname-deploy\node_modules\@aws-cdk\core\lib\cfn-fn.ts:491:5)
  at new FnIf (C:\Users\username\code\applicationname-deploy\node_modules\@aws-cdk\core\lib\cfn-fn.ts:536:5)
  at Function.conditionIf (C:\Users\username\code\applicationname-deploy\node_modules\@aws-cdk\core\lib\cfn-fn.ts:209:12)
  at new DevPortalDeployDevopsSingleStack (C:\Users\username\code\applicationname-deploy\lib\applicationname-deploy-devops-single-stack.ts:377:20)
  at Object.<anonymous> (C:\Users\username\code\applicationname-deploy\bin\applicationname-deploy.ts:18:1)
  at Module._compile (internal/modules/cjs/loader.js:959:30)
  at Module.m._compile (C:\Users\username\code\applicationname-deploy\node_modules\ts-node\src\index.ts:814:23)
  at Module._extensions..js (internal/modules/cjs/loader.js:995:10)
  at Object.require.extensions.<computed> [as .ts] (C:\Users\username\code\applicationname-deploy\node_modules\ts-node\src\index.ts:817:12)
  at Module.load (internal/modules/cjs/loader.js:815:32)
  at Function.Module._load (internal/modules/cjs/loader.js:727:14)
  at Function.Module.runMain (internal/modules/cjs/loader.js:1047:10)
  at main (C:\Users\username\code\applicationname-deploy\node_modules\ts-node\src\bin.ts:226:14)  
  at Object.<anonymous> (C:\Users\username\code\applicationname-deploy\node_modules\ts-node\src\bin.ts:485:3)
  at Module._compile (internal/modules/cjs/loader.js:959:30)
  at Object.Module._extensions..js (internal/modules/cjs/loader.js:995:10)
  at Module.load (internal/modules/cjs/loader.js:815:32)
  at Function.Module._load (internal/modules/cjs/loader.js:727:14)
  at Function.Module.runMain (internal/modules/cjs/loader.js:1047:10)
  at internal/main/run_main_module.js:17:11
    at resolve (C:\Users\username\code\applicationname-deploy\node_modules\@aws-cdk\core\lib\private\resolve.ts:144:11)
    at Object.resolve (C:\Users\username\code\applicationname-deploy\node_modules\@aws-cdk\core\lib\private\resolve.ts:49:32)
    at resolve (C:\Users\username\code\applicationname-deploy\node_modules\@aws-cdk\core\lib\private\resolve.ts:154:39)
    at Object.resolve (C:\Users\username\code\applicationname-deploy\node_modules\@aws-cdk\core\lib\private\resolve.ts:49:32)
    at resolve (C:\Users\username\code\applicationname-deploy\node_modules\@aws-cdk\core\lib\private\resolve.ts:154:39)
    at Object.resolve (C:\Users\username\code\applicationname-deploy\node_modules\@aws-cdk\core\lib\private\resolve.ts:49:32)
    at resolve (C:\Users\username\code\applicationname-deploy\node_modules\@aws-cdk\core\lib\private\resolve.ts:154:39)
    at Object.resolve (C:\Users\username\code\applicationname-deploy\node_modules\@aws-cdk\core\lib\private\resolve.ts:49:32)
    at resolve (C:\Users\username\code\applicationname-deploy\node_modules\@aws-cdk\core\lib\private\resolve.ts:154:39)
    at Object.resolve (C:\Users\username\code\applicationname-deploy\node_modules\@aws-cdk\core\lib\private\resolve.ts:49:32)
Subprocess exited with error 1
```

**Comment by skinny85** [comment]
@michaelday008 I see now (the code above is different from what you posted before). What you're trying to do is fundamentally at odds with how the CodePipeline L2 works.

You see, when you add an Action to a CodePipeline, there are a lot of things that happen: roles are created if needed, permissions are added to existing roles, many validations are performed, etc. You can't delay the decision to include a given `IAction` instance until deploy time - by that time, it's too late to do things like modify permissions, etc., because the template has been already generated.

If you want to make this happen, you'll have to abandon the higher-level CodePipeline construct and use the `CfnPipeline` and related classes.

Sorry for the bad news :(.

Let me know if you need anything else from our side.

Thanks,
Adam

**Comment by SomayaB** [comment]
Closing for now since there hasn't been a response in a while. Feel free to reopen.
