### ISSUE TITLE
Error Creating CognitoUserPool with userVerification VerificationEmailStyle.LINK

### ISSUE THREAD

**Issue by dwach414** [aws/aws-cdk#6705]
When I try to create a cognito UserPool in the cdk with the VerificationEmailStyle.LINK. I always get an error saying `The message is invalid`. I've tried adding both `{##Verify Email##}` and some thing with `{####}`.  I am not able, no matter what I try, to get passed this message. If I don't include the `userVerification` node, then I am able to successfully create a stack. 

### Reproduction Steps
```
    const userPool = new UserPool(this, 'CognitoUserPool', {
      userPoolName: `${this.stackName}`,
      selfSignUpEnabled: true,
      signInAliases: {
        username: true,
        email: true,
      },
      autoVerify: {
        email: true,
        phone: false,
      },
      userVerification:  {
        emailStyle: VerificationEmailStyle.LINK,
        emailBody: 'This is a body {##Verify Email##} {####}',
        emailSubject: "Here's your verification link",
      }
    });

```

### Error Log

```
 CognitoUserPool (CognitoUserPool53E37E69) The message is invalid. (Service: AWSCognitoIdentityProviderService; Status Code: 400; Error Code: InvalidParameterException; Request ID: 320c720d-43c0-46dd-88cb-de84e3ff4383)
	new UserPool (/Users/beemo/dev/CognitoAuth/node_modules/@aws-cdk/aws-cognito/lib/user-pool.ts:498:22)
	\_ new CognitoAuthStack (/Users/beemo/dev/CognitoAuth/lib/cognito_auth-stack.ts:10:22)
	\_ Object.<anonymous> (/Users/beemo/dev/CognitoAuth/lib/cognito_auth-stack.ts:61:1)
	\_ Module._compile (internal/modules/cjs/loader.js:956:30)
	\_ Module.m._compile (/Users/beemo/dev/CognitoAuth/node_modules/ts-node/src/index.ts:439:23)
	\_ Module._extensions..js (internal/modules/cjs/loader.js:973:10)
	\_ Object.require.extensions.<computed> [as .ts] (/Users/beemo/dev/CognitoAuth/node_modules/ts-node/src/index.ts:442:12)
	\_ Module.load (internal/modules/cjs/loader.js:812:32)
	\_ Function.Module._load (internal/modules/cjs/loader.js:724:14)
	\_ Function.Module.runMain (internal/modules/cjs/loader.js:1025:10)
	\_ Object.<anonymous> (/Users/beemo/dev/CognitoAuth/node_modules/ts-node/src/bin.ts:154:12)
	\_ Module._compile (internal/modules/cjs/loader.js:956:30)
	\_ Object.Module._extensions..js (internal/modules/cjs/loader.js:973:10)
	\_ Module.load (internal/modules/cjs/loader.js:812:32)
	\_ Function.Module._load (internal/modules/cjs/loader.js:724:14)
	\_ Function.Module.runMain (internal/modules/cjs/loader.js:1025:10)
	\_ /Users/beemo/.nvm/versions/node/v12.13.0/lib/node_modules/npm/node_modules/libnpx/index.js:268:14
```

```
 ❌  CognitoAuthStack failed: Error: The stack named CognitoAuthStack failed creation, it may need to be manually deleted from the AWS console: ROLLBACK_COMPLETE
    at /Users/beemo/dev/CognitoAuth/node_modules/aws-cdk/lib/api/util/cloudformation.ts:163:13
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at waitFor (/Users/beemo/dev/CognitoAuth/node_modules/aws-cdk/lib/api/util/cloudformation.ts:76:20)
    at Object.deployStack (/Users/beemo/dev/CognitoAuth/node_modules/aws-cdk/lib/api/deploy-stack.ts:156:7)
    at CdkToolkit.deploy (/Users/beemo/dev/CognitoAuth/node_modules/aws-cdk/lib/cdk-toolkit.ts:137:24)
    at main (/Users/beemo/dev/CognitoAuth/node_modules/aws-cdk/bin/cdk.ts:218:16)
    at initCommandLine (/Users/beemo/dev/CognitoAuth/node_modules/aws-cdk/bin/cdk.ts:168:9)
The stack named CognitoAuthStack failed creation, it may need to be manually deleted from the AWS console: ROLLBACK_COMPLE
```

### Environment

  - **CLI Version      :1.16.260
  - **OS               :Mac OSX 10.15.3
  - **Language         :Typescript

--- 

This is :bug: Bug Report

**Comment by nija-at** [comment]
I am unable to reproduce this. I am able to successfully deploy the code below and am able to see that the verification email config is correctly reflecting what was specified.

I'm using cdk version 1.27.0.

```ts
import { App, Stack } from '@aws-cdk/core';
import { UserPool, VerificationEmailStyle } from '../lib';

const app = new App();
const stack = new Stack(app, 'integ-user-pool');

new UserPool(stack, 'myuserpool', {
  selfSignUpEnabled: true,
  signInAliases: {
    username: true,
    email: true,
  },
  autoVerify: {
    email: true,
    phone: false,
  },
  userVerification:  {
    emailStyle: VerificationEmailStyle.LINK,
    emailBody: 'This is a body {##Verify Email##} {####}',
    emailSubject: "Here's your verification link",
  }
});
```

**Comment by nija-at** [comment]
Closing this due to inactivity. Please re-open when you have updates.
