### ISSUE TITLE
Cannot deploy EKS workers ASG into Public subnet

### ISSUE THREAD

**Issue by pbaranow** [aws/aws-cdk#6888]
I have a CDK script which deploys EKS into public subnets only. When I attempt to deploy Control Plane together with AutoScalingGroups (one in each subnet) CDK fails with following error:
`jsii.errors.JSIIError: To set 'associatePublicIpAddress: true' you must select Public subnets (vpcSubnets: { subnetType: SubnetType.PUBLIC })`

I was able to reproduce this issue when deploying single Auto Scaling Group in our VPC setup:
- we have a VPC split into 3 subnets
- each subnet is a public subnet - VPC is connected to Internet Gateway
- by default 'auto-assign public IPv4' is disabled, as we want to selectively set which EC2 instances should have public IP

When deploying ASG with associate_public_ip_address=True script reports an error. According to aws_ec2/__init.py__ subnet is considered Public based on folllowing information:
- if 'aws-cdk:subnet-type': 'Public' tag is set, then subnet is public,
- if no tag is set, but Internet Gateway is connected, then subnet is public

I tried with adding tags to all subnets, but issue still occured. I also enabled 'auto-assign public IPv4' setting, but this also didn't help.

Then I prepared second stack, which was intended to create a single EC2 instance. I called 'cdk diff' and it succeeded. On success file cdk.context.json was saved  to my working directory - it holds information about my VPC setup.

From this moment calling script to create ASG works correctly. The same behavior was observed for my script deploying EKS with ASGs.

From investigation it seems that aws_autoscaling module incorrectly decides whether subnet is public or not.

### Reproduction Steps
Setup VPC connected to Internet Gateway, create subnet(s) in this VPC with 'auto-assign public IPv4' disabled, no tags created by CDK. Create AutoScalingGroup with associate_public_ip_address set to True.

```
vpc = aws_ec2.Vpc.from_lookup(
    scope=self,
    id='TestVpc',
    tags={
        'Name': 'TESTvpc'
    })
subnet = vpc.select_subnets(subnet_type=aws_ec2.SubnetType.PUBLIC).subnets[0]
linux_generation=aws_ec2.AmazonLinuxGeneration.AMAZON_LINUX_2
worker_asg = aws_autoscaling.AutoScalingGroup(
    scope=self,
    id='TestWorkerAsg',
    instance_type=aws_ec2.InstanceType('t2.small'),
    machine_image=aws_ec2.AmazonLinuxImage(generation=linux_generation),
    associate_public_ip_address=True,
    max_capacity=2,
    min_capacity=1,
    vpc=vpc
    )
worker_asg.node.default_child.add_override('Properties.VPCZoneIdentifier', [subnet.subnet_id])
```
### Error Log
```
jsii.errors.JavaScriptError:
  Error: To set 'associatePublicIpAddress: true' you must select Public subnets (vpcSubnets: { subnetType: SubnetType.PUBLIC })
      at new AutoScalingGroup (/tmp/jsii-kernel-EHMDCn/node_modules/@aws-cdk/aws-autoscaling/lib/auto-scaling-group.js:214:19)
      at /usr/local/lib/python3.7/site-packages/jsii/_embedded/jsii/jsii-runtime.js:7838:49
      at Kernel._wrapSandboxCode (/usr/local/lib/python3.7/site-packages/jsii/_embedded/jsii/jsii-runtime.js:8301:19)
      at Kernel._create (/usr/local/lib/python3.7/site-packages/jsii/_embedded/jsii/jsii-runtime.js:7838:26)
      at Kernel.create (/usr/local/lib/python3.7/site-packages/jsii/_embedded/jsii/jsii-runtime.js:7585:21)
      at KernelHost.processRequest (/usr/local/lib/python3.7/site-packages/jsii/_embedded/jsii/jsii-runtime.js:7372:28)
      at KernelHost.run (/usr/local/lib/python3.7/site-packages/jsii/_embedded/jsii/jsii-runtime.js:7312:14)
      at Immediate._onImmediate (/usr/local/lib/python3.7/site-packages/jsii/_embedded/jsii/jsii-runtime.js:7315:37)
      at processImmediate (internal/timers.js:439:21)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "app.py", line 81, in <module>
    env=env,
  File "/usr/local/lib/python3.7/site-packages/jsii/_runtime.py", line 66, in __call__
    inst = super().__call__(*args, **kwargs)
  File "app.py", line 54, in __init__
    vpc=vpc
  File "/usr/local/lib/python3.7/site-packages/jsii/_runtime.py", line 66, in __call__
    inst = super().__call__(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/aws_cdk/aws_autoscaling/__init__.py", line 5314, in __init__
    jsii.create(AutoScalingGroup, self, [scope, id, props])
  File "/usr/local/lib/python3.7/site-packages/jsii/_kernel/__init__.py", line 229, in create
    interfaces=[iface.__jsii_type__ for iface in getattr(klass, "__jsii_ifaces__", [])],
  File "/usr/local/lib/python3.7/site-packages/jsii/_kernel/providers/process.py", line 333, in create
    return self._process.send(request, CreateResponse)
  File "/usr/local/lib/python3.7/site-packages/jsii/_kernel/providers/process.py", line 318, in send
    raise JSIIError(resp.error) from JavaScriptError(resp.stack)
jsii.errors.JSIIError: To set 'associatePublicIpAddress: true' you must select Public subnets (vpcSubnets: { subnetType: SubnetType.PUBLIC })
```

### Environment

  - **CLI Version      :**
  - **Framework Version: 1.30.0**
  - **OS               : Linux**
  - **Language         : Python**

### Other

--- 

This is :bug: Bug Report

**Comment by pbaranow** [comment]
Issue was caused by missing vpc_subnets parameter. Another pair of eyes was needed to spot this.
