### ISSUE TITLE
EksOptimizedImage returns wrong image SSM path /aws/service/eks/optimized-ami/1.14/recommended/image_id

### ISSUE THREAD

**Issue by IronforgeV** [aws/aws-cdk#6891]
EksOptimizedImage returns the wrong image ssm path without amazon-linux-2 

`aws ssm get-parameter --name /aws/service/eks/optimized-ami/1.14/recommended/image_id --query "Parameter.[Name,Value]" --output text

An error occurred (ParameterNotFound) when calling the GetParameter operation:
`

`aws ssm get-parameter --name /aws/service/eks/optimized-ami/1.14/amazon-linux-2/recommended/image_id --query "Parameter.[Name,Value]" --output text
/aws/service/eks/optimized-ami/1.14/amazon-linux-2/recommended/image_id	ami-0d373fa5015bc43be
`

### Reproduction Steps

Create autoscaling group using EksOptimizedImage
`        asg = autoscaling.AutoScalingGroup(
            self, "KubeFleet",
            instance_type=InstanceType("t3.large"),
            machine_image=eks.EksOptimizedImage(),
            associate_public_ip_address=False,
            update_type=autoscaling.UpdateType.REPLACING_UPDATE,
            desired_capacity=3,
            vpc=vpc,
            vpc_subnets={'subnet_type': SubnetType.PRIVATE}
        )
`

### Error Log

```console
Error [ValidationError]: Unable to fetch parameters [/aws/service/eks/optimized-ami/1.14/recommended/image_id] from parameter store for this account.
    at Request.extractError (/usr/local/lib/node_modules/aws-cdk/node_modules/aws-sdk/lib/protocol/query.js:50:29)
    at Request.callListeners (/usr/local/lib/node_modules/aws-cdk/node_modules/aws-sdk/lib/sequential_executor.js:106:20)
    at Request.emit (/usr/local/lib/node_modules/aws-cdk/node_modules/aws-sdk/lib/sequential_executor.js:78:10)
    at Request.emit (/usr/local/lib/node_modules/aws-cdk/node_modules/aws-sdk/lib/request.js:683:14)
    at Request.transition (/usr/local/lib/node_modules/aws-cdk/node_modules/aws-sdk/lib/request.js:22:10)
    at AcceptorStateMachine.runTo (/usr/local/lib/node_modules/aws-cdk/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at /usr/local/lib/node_modules/aws-cdk/node_modules/aws-sdk/lib/state_machine.js:26:10
    at Request.<anonymous> (/usr/local/lib/node_modules/aws-cdk/node_modules/aws-sdk/lib/request.js:38:9)
    at Request.<anonymous> (/usr/local/lib/node_modules/aws-cdk/node_modules/aws-sdk/lib/request.js:685:12)
    at Request.callListeners (/usr/local/lib/node_modules/aws-cdk/node_modules/aws-sdk/lib/sequential_executor.js:116:18) {
  message: 'Unable to fetch parameters [/aws/service/eks/optimized-ami/1.14/recommended/image_id] from parameter store for this account.',
```

### Environment

  - **CLI Version      :2.0.0**
  - **Framework Version: 1.28.0**
  - **OS               : OSX 10**
  - **Language         : Python 3.7.6**

### Other

--- 

This is :bug: Bug Report

**Comment by eladb** [comment]
The issue here is that we don't honor the default for `nodeType`, so until this is fixed you can use:

```ts
new EksOptimizedAmi({ nodeType: NodeType.STANDARD });
```

Fix is on it's way through #7672
