### ISSUE TITLE
Cannot read property 'addToPolicy' of undefined

### ISSUE THREAD

**Issue by AmangPulo** [aws/aws-cdk#7173]
```ts
        logs_.SubscriptionFilter(self, "Subscription", log_group=log_group, 
                destination= destination_.LambdaDestination(lambda_function),
                filter_pattern=logs_.FilterPattern.all_events()
                )
```

### Reproduction Steps

1. Created Function
2. Created Log Group
3. Created SubscriptionFilter
     3a. Erroring out particularly on the filter_pattern argument

"Cannot read property 'addToPolicy' of undefined"

### Error Log

```console
(.env) ISS-Sandbox-PowerUserAccess:~/environment/Projects/certificate-reporter (master) $ cdk synth
jsii.errors.JavaScriptError: 
  TypeError: Cannot read property 'addToPolicy' of undefined
      at Function.addToPrincipal (/tmp/jsii-kernel-Q6LGTC/node_modules/@aws-cdk/aws-iam/lib/grant.js:57:65)
      at Function.addToPrincipalOrResource (/tmp/jsii-kernel-Q6LGTC/node_modules/@aws-cdk/aws-iam/lib/grant.js:31:30)
      at Function.grantInvoke (/tmp/jsii-kernel-Q6LGTC/node_modules/@aws-cdk/aws-lambda/lib/function-base.js:74:26)
      at LambdaDestination.bind (/tmp/jsii-kernel-Q6LGTC/node_modules/@aws-cdk/aws-lambda-destinations/lib/lambda.js:21:21)
      at new SubscriptionFilter (/tmp/jsii-kernel-Q6LGTC/node_modules/@aws-cdk/aws-logs/lib/subscription-filter.js:11:45)
      at obj._wrapSandboxCode (/home/ubuntu/environment/Projects/certificate-reporter/.env/lib/python3.6/site-packages/jsii/_embedded/jsii/jsii-runtime.js:7836:49)
      at Kernel._wrapSandboxCode (/home/ubuntu/environment/Projects/certificate-reporter/.env/lib/python3.6/site-packages/jsii/_embedded/jsii/jsii-runtime.js:8299:19)
      at Kernel._create (/home/ubuntu/environment/Projects/certificate-reporter/.env/lib/python3.6/site-packages/jsii/_embedded/jsii/jsii-runtime.js:7836:26)
      at Kernel.create (/home/ubuntu/environment/Projects/certificate-reporter/.env/lib/python3.6/site-packages/jsii/_embedded/jsii/jsii-runtime.js:7583:21)
      at KernelHost.processRequest (/home/ubuntu/environment/Projects/certificate-reporter/.env/lib/python3.6/site-packages/jsii/_embedded/jsii/jsii-runtime.js:7371:28)
      at KernelHost.run (/home/ubuntu/environment/Projects/certificate-reporter/.env/lib/python3.6/site-packages/jsii/_embedded/jsii/jsii-runtime.js:7311:14)
      at Immediate.setImmediate [as _onImmediate] (/home/ubuntu/environment/Projects/certificate-reporter/.env/lib/python3.6/site-packages/jsii/_embedded/jsii/jsii-runtime.js:7314:37)
      at runCallback (timers.js:705:18)
      at tryOnImmediate (timers.js:676:5)
      at processImmediate (timers.js:658:5)
```
The above exception was the direct cause of the following exception:
```console
Traceback (most recent call last):
  File "app.py", line 9, in <module>
    CertificateReporterStack(app, "certificate-reporter")
  File "/home/ubuntu/environment/Projects/certificate-reporter/.env/lib/python3.6/site-packages/jsii/_runtime.py", line 66, in __call__
    inst = super().__call__(*args, **kwargs)
  File "/home/ubuntu/environment/Projects/certificate-reporter/certificate_reporter/certificate_reporter_stack.py", line 36, in __init__
    filter_pattern=logs_.FilterPattern.all_events()
  File "/home/ubuntu/environment/Projects/certificate-reporter/.env/lib/python3.6/site-packages/jsii/_runtime.py", line 66, in __call__
    inst = super().__call__(*args, **kwargs)
  File "/home/ubuntu/environment/Projects/certificate-reporter/.env/lib/python3.6/site-packages/aws_cdk/aws_logs/__init__.py", line 2350, in __init__
    jsii.create(SubscriptionFilter, self, [scope, id, props])
  File "/home/ubuntu/environment/Projects/certificate-reporter/.env/lib/python3.6/site-packages/jsii/_kernel/__init__.py", line 229, in create
    interfaces=[iface.__jsii_type__ for iface in getattr(klass, "__jsii_ifaces__", [])],
  File "/home/ubuntu/environment/Projects/certificate-reporter/.env/lib/python3.6/site-packages/jsii/_kernel/providers/process.py", line 333, in create
    return self._process.send(request, CreateResponse)
  File "/home/ubuntu/environment/Projects/certificate-reporter/.env/lib/python3.6/site-packages/jsii/_kernel/providers/process.py", line 318, in send
    raise JSIIError(resp.error) from JavaScriptError(resp.stack)
jsii.errors.JSIIError: Cannot read property 'addToPolicy' of undefined
```

### Environment
- **CLI Version      :** 1.31.0 (build 8f3ac79)
- **Framework Version:** 
- **OS               :** Cloud9 Ubuntu
- **Language         :** Python

### Other

--- 

This is :bug: Bug Report

**Comment by rix0rrr** [comment]
You are passing a `LambdaDestination` where a `LogDestination` is expected.

```
      at LambdaDestination.bind (/tmp/jsii-kernel-Q6LGTC/node_modules/@aws-cdk/aws-lambda-destinations/lib/lambda.js:21:21)
```

You are looking for this class: https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-logs-destinations.LambdaDestination.html
