### ISSUE TITLE
Call stacks point to typescript which doesn't exist

### ISSUE THREAD

**Issue by mmkal** [aws/aws-cdk#7207]
When I do something wrong when using cdk, I get a call stack like this:

```
/Users/me/src/my-project/node_modules/@aws-cdk/aws-ec2/lib/vpc.ts:1661
    this.vpcId = props.vpcId;
                       ^
TypeError: Cannot read property 'vpcId' of undefined
    at new ImportedVpc (/Users/me/src/my-project/node_modules/@aws-cdk/aws-ec2/lib/vpc.ts:1661:24)
    at Function.fromVpcAttributes (/Users/me/src/my-project/node_modules/@aws-cdk/aws-ec2/lib/vpc.ts:889:12)
    at new ImportedCluster (/Users/me/src/my-project/node_modules/@aws-cdk/aws-eks/lib/cluster.ts:836:24)
    at Function.fromClusterAttributes (/Users/me/src/my-project/node_modules/@aws-cdk/aws-eks/lib/cluster.ts:259:12)
    at addResource (/Users/me/src/my-project/services/app-version/cdk.ts:14:30)
    at new AppVersionStack (/Users/me/src/my-project/services/app-version/cdk.ts:22:5)
    at Object.<anonymous> (/Users/me/src/my-project/cdk.ts:13:1)
    at Module._compile (internal/modules/cjs/loader.js:1158:30)
    at Module.m._compile (/Users/me/src/my-project/node_modules/ts-node/src/index.ts:493:23)
    at Module._extensions..js (internal/modules/cjs/loader.js:1178:10)
Subprocess exited with error 1
```

In VSCode, I'm unable to click any of the file pointers in `node_modules/@aws-cdk/...` because the `.ts` files don't exist. The compiled `.js` files do, but the line numbers are different and the source mapping has to be reverse-engineered for many different files.

### Reproduction Steps

Trying to deploy this stack results in an error with stack similar to above:

```typescript
import * as cdk from '@aws-cdk/core';
import * as eks from '@aws-cdk/aws-eks';

export class TestStack extends cdk.Stack {
  constructor(scope: cdk.Construct, id: string, props: cdk.StackProps) {
    super(scope, id, props);

    eks.Cluster.fromClusterAttributes(this, 'testcluster', {});
  }
}
```

### Error Log

See above

### Environment

  - **CLI Version      :** 1.31.0 (build 8f3ac79)
  - **Framework Version:** 1.31.0
  - **OS               :** Mac
  - **Language         :** TypeScript

### Other

I see two simple fixes:

1. Show javascript sources only in Error stacks. Presumably there's a call to `import source-map-support/register` somewhere.
2. Include typescript in the published packages.

Of these, 2 would be preferable, since 1 breaks if the consumer is using `source-map-support`, and it's more useful to point to source typescript than generated javascript.

In terms of implementation, it should be as simple as removing these lines from each `.npmignore` file: https://github.com/aws/aws-cdk/blob/97959f6ba40a4a576fc914772206623900d72add/packages/%40aws-cdk/core/.npmignore#L1-L3

I can't think of any problems that would arise from including the typescript, especially since the packages published by this repo aren't used in front-end environments, so increasing package size by a small amount shouldn't be a big concern.

--- 

This is :bug: Bug Report

**Comment by rix0rrr** [comment]
Personally I'm leaning towards getting rid of source maps for production builds. They unnecessarily increase file size for no good reason.

**Comment by mmkal** [comment]
As far as I know this is still an issue and should be kept open.

**Comment by MrArnoldPalmer** [comment]
We are tracking source maps availability here https://github.com/aws/aws-cdk/issues/20561. Closing in favor of that
