### ISSUE TITLE
Creating a KubernetesResource in a different stack than the EKS Cluster causes a circular dependency.

### ISSUE THREAD

**Issue by Shiroy** [aws/aws-cdk#7231]
Using `@aws-cdk/aws-eks`, when a `KubernetesResource` is instantiated for a cluster created in another stack, `cdk synth` failed. The error is that a circular dependency exists between the cluster stack and the Kubernetes application stack.

I'd expect the `KubernetesApplication` stack to depend on the `EKSCluster` stack only.

### Reproduction Steps

`lib/bug_report-stack`
```typescript
import * as cdk from '@aws-cdk/core';
import * as eks from '@aws-cdk/aws-eks'

export class EKSCluster extends cdk.Stack {
  public eksCluster: eks.Cluster; 

  constructor(scope: cdk.Construct, id: string, props?: cdk.StackProps) {
    super(scope, id, props);
    this.eksCluster = new eks.Cluster(this, "EKSCluster");
  }
}

export class KubernetesApp extends cdk.Stack {
  constructor(scope: cdk.Construct, id: string, props: cdk.StackProps & {eksCluster: eks.Cluster}) {
    super(scope, id, props);

    new eks.KubernetesResource(this, "ksNamespace", {
      cluster: props.eksCluster,
      manifest: [{
        apiVersion: 'v1',
        kind: 'Namespace',
        metadata: {
            name: "my-app-namespace"
        }
      }]
    })
  }
}
```

`bin/bug-report.ts`
```typescript
#!/usr/bin/env node
import 'source-map-support/register';
import * as cdk from '@aws-cdk/core';
import { EKSCluster, KubernetesApp } from '../lib/bug_report-stack';

const app = new cdk.App();
const eksCluster = new EKSCluster(app, 'EKSCluster');

new KubernetesApp(app, "KubeApp", {
    eksCluster: eksCluster.eksCluster
});
```

### Error Log

```
bug_report git:(master) ✗ cdk synth

/Users/wacheuxa/Documents/masterbuilder/bug_report/node_modules/@aws-cdk/core/lib/stack.ts:659
        throw new Error(`'${target.node.path}' depends on '${this.node.path}' (${cycle.join(', ')}). Adding this dependency (${reason}) would create a cyclic reference.`);
              ^
Error: 'KubeApp' depends on 'EKSCluster' (KubeApp -> EKSCluster/EKSCluster/Resource/Resource/Default.Ref, KubeApp -> EKSCluster/EKSCluster/Resource/CreationRole/Resource.Arn). Adding this dependency (EKSCluster -> KubeApp/@aws-cdk--aws-eks.KubectlProvider.NestedStack/@aws-cdk--aws-eks.KubectlProvider.NestedStackResource.Outputs.${Token[KubeApp..aws-cdk--aws-eks.KubectlProvider.KubeA...eksKubectlProviderHandlerServiceRole955AEA54Arn.LogicalID.525]}) would create a cyclic reference.
    at EKSCluster._addAssemblyDependency (/Users/wacheuxa/Documents/masterbuilder/bug_report/node_modules/@aws-cdk/core/lib/stack.ts:659:15)
    at Object.addDependency (/Users/wacheuxa/Documents/masterbuilder/bug_report/node_modules/@aws-cdk/core/lib/deps.ts:44:20)
    at EKSCluster.addDependency (/Users/wacheuxa/Documents/masterbuilder/bug_report/node_modules/@aws-cdk/core/lib/stack.ts:364:5)
    at KubernetesApp.prepareCrossReference (/Users/wacheuxa/Documents/masterbuilder/bug_report/node_modules/@aws-cdk/core/lib/stack.ts:926:24)
    at KubectlProvider.prepareCrossReference (/Users/wacheuxa/Documents/masterbuilder/bug_report/node_modules/@aws-cdk/aws-cloudformation/lib/nested-stack.ts:189:61)
    at EKSCluster.prepare (/Users/wacheuxa/Documents/masterbuilder/bug_report/node_modules/@aws-cdk/core/lib/stack.ts:769:37)
    at EKSCluster.onPrepare (/Users/wacheuxa/Documents/masterbuilder/bug_report/node_modules/@aws-cdk/core/lib/construct-compat.ts:105:10)
    at Node.prepare (/Users/wacheuxa/Documents/masterbuilder/bug_report/node_modules/constructs/lib/construct.ts:440:28)
    at Node.synthesize (/Users/wacheuxa/Documents/masterbuilder/bug_report/node_modules/constructs/lib/construct.ts:399:10)
    at Function.synth (/Users/wacheuxa/Documents/masterbuilder/bug_report/node_modules/@aws-cdk/core/lib/construct-compat.ts:225:22)
Subprocess exited with error 1
```

### Environment

  - **CLI Version      :** 1.31.0 (build 8f3ac79)
  - **Framework Version:** 1.31.0
  - **OS               :** MacOS Mojave 10.14.6
  - **Language         :** Typescript

### Other

This issue does not occur when the Kubernetes resource is created in the same stack as the Kubernetes cluster.

--- 

This is :bug: Bug Report

**Comment by eladb** [comment]
Ack. PR is ready
