### ISSUE TITLE
S3EventSource raises AttributeError: module 'aws_cdk.aws_lambda' has no attribute 'IEventSourceDlq'

### ISSUE THREAD

**Issue by Olamyy** [aws/aws-cdk#7306]
When I try to import the S3EventSource module, I get an AttributeError.

### Reproduction Steps

```
from aws_cdk.aws_lambda_event_sources import S3EventSource
```

### Error Log

```
Traceback (most recent call last):
  File "/Users/owahab/miniconda3/envs/zflow/lib/python3.7/site-packages/IPython/core/interactiveshell.py", line 3331, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-2-32b962a44e60>", line 1, in <module>
    from aws_cdk.aws_lambda_event_sources import S3EventSource
  File "/Applications/PyCharm CE.app/Contents/plugins/python-ce/helpers/pydev/_pydev_bundle/pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "/Users/owahab/miniconda3/envs/zflow/lib/python3.7/site-packages/aws_cdk/aws_lambda_event_sources/__init__.py", line 337, in <module>
    @jsii.implements(aws_cdk.aws_lambda.IEventSourceDlq)
AttributeError: module 'aws_cdk.aws_lambda' has no attribute 'IEventSourceDlq'
```

### Environment

  - **CLI Version      :*aws-cli/1.18.19   botocore/1.15.31*
  - **Framework Version:*1.32.1 (build d0dfe79)*
  - **OS               :*Darwin/19.4.0*
  - **Language         :*Python/3.7.6*

### Other

--- 

This is :bug: Bug Report

**Comment by Olamyy** [comment]
Works after updating dependency versions.
