### ISSUE TITLE
Can not create CfnMapping object in .NET : Could not infer JSII type for .NET type 'JValue' (Parameter 'type')

### ISSUE THREAD

**Issue by Pankajc123** [aws/aws-cdk#7392]
While creating CfnMapping object in .NET, I am getting error as

```
Unhandled exception. System.ArgumentException: Could not infer JSII type for .NET type 'JValue' (Parameter 'type')

```
I am able to set "Mapping" property correctly, but when I run "cdk synth command, I am getting above error.

### Reproduction Steps
Below is .Net code snippet

```
using Amazon.CDK;
using Newtonsoft.Json.Linq;
using System.IO;
using System.Collections.Generic;
namespace Missionserver
{
    public class MissionserverStack : Stack
    {
        internal MissionserverStack(Construct scope, string id, IStackProps props = null) : base(scope, id, props)
        {          
            var doccontent = File.ReadAllText("./mapping.json");

            var str = new Dictionary<string, object>();
            var str2 = new Dictionary<string, IDictionary<string,object>>();
            var str3 = JObject.Parse(doccontent);

            foreach(var item in str3)
            {
                str.Clear();
                var jobj = (JObject)str3[item.Key];
                str.Add("bucket", (object)jobj["bucket"]);
                str.Add("region", (object)jobj["region"]);
                str2.Add(item.Key, str);
            }

            var m = new CfnMapping(this, "Repositories", new CfnMappingProps
            {
                Mapping = str2
            });

        }
    }
}
```

Below is my "mapping.json" file
```

{
	"us-east-1": {
		"bucket": "arcgisdaily-repo-us-east-1",
		"region": "us-east-1"
	},
	"us-east-2": {
		"bucket": "arcgisdaily-repo-us-east-1",
		"region": "us-east-1"
	},
	"us-west-1": {
		"bucket": "arcgisdaily-repo-us-east-1",
		"region": "us-east-1"
	},
	"us-west-2": {
		"bucket": "arcgisdaily-repo-us-east-1",
		"region": "us-east-1"
	}
}

```

### Error Log

 ```
Unhandled exception. System.ArgumentException: Could not infer JSII type for .NET type 'JValue' (Parameter 'type')

at Amazon.JSII.Runtime.Services.Converters.FrameworkToJsiiConverter.InferType(IReferenceMap referenceMap, Type type)
   at Amazon.JSII.Runtime.Services.Converters.FrameworkToJsiiConverter.InferType(IReferenceMap referenceMap, Object value)
   at Amazon.JSII.Runtime.Services.Converters.ValueConverter.ConvertAny(Type type, IReferenceMap referenceMap, Object value)
   at Amazon.JSII.Runtime.Services.Converters.ValueConverter.TryConvertPrimitive(Type type, IReferenceMap referenceMap, Object value, Boolean isOptional, PrimitiveType primitiveType, Object& result)
   at Amazon.JSII.Runtime.Services.Converters.ValueConverter.TryConvert(IOptionalValue optionalValue, Type type, IReferenceMap referenceMap, Object value, Object& result)
   at Amazon.JSII.Runtime.Services.Converters.ValueConverter.TryConvert(TypeReference typeReference, Type type, IReferenceMap referenceMap, Object value, Object& result)
   at Amazon.JSII.Runtime.Services.Converters.FrameworkToJsiiConverter.TryConvertCollectionElement(Object element, IReferenceMap referenceMap, TypeReference elementType, Object& convertedElement)
   at Amazon.JSII.Runtime.Services.Converters.FrameworkToJsiiConverter.TryConvertMap(IReferenceMap referenceMap, TypeReference elementType, Object value, Object& result)
   at Amazon.JSII.Runtime.Services.Converters.FrameworkToJsiiConverter.TryConvertCollectionElement(Object element, IReferenceMap referenceMap, TypeReference elementType, Object& convertedElement)
   at Amazon.JSII.Runtime.Services.Converters.FrameworkToJsiiConverter.TryConvertMap(IReferenceMap referenceMap, TypeReference elementType, Object value, Object& result)
   at Amazon.JSII.Runtime.Services.Converters.ValueConverter.TryConvertCollection(IReferenceMap referenceMap, Object value, Boolean isOptional, CollectionTypeReference collectionType, Object& result)
   at Amazon.JSII.Runtime.Services.Converters.ValueConverter.TryConvert(IOptionalValue optionalValue, Type type, IReferenceMap referenceMap, Object value, Object& result)
   at Amazon.JSII.Runtime.Services.Converters.FrameworkToJsiiConverter.TryConvertClass(Type type, IReferenceMap referenceMap, Object value, Object& result)
   at Amazon.JSII.Runtime.Services.Converters.ValueConverter.TryConvertCustomType(Type type, IReferenceMap referenceMap,
Object value, Boolean isOptional, String fullyQualifiedName, Object& result)
   at Amazon.JSII.Runtime.Services.Converters.ValueConverter.TryConvert(IOptionalValue optionalValue, Type type, IReferenceMap referenceMap, Object value, Object& result)
   at Amazon.JSII.Runtime.Services.Converters.FrameworkToJsiiConverter.TryConvert(IOptionalValue optionalValue, IReferenceMap referenceMap, Object value, Object& result)
   at Amazon.JSII.Runtime.Deputy.DeputyBase.<>c__DisplayClass20_0.<ConvertArguments>b__0(Parameter parameter, Object frameworkArgument)
   at System.Linq.Enumerable.ZipIterator[TFirst,TSecond,TResult](IEnumerable`1 first, IEnumerable`1 second, Func`3 resultSelector)+MoveNext()
   at System.Collections.Generic.LargeArrayBuilder`1.AddRange(IEnumerable`1 items)
   at System.Collections.Generic.EnumerableHelpers.ToArray[T](IEnumerable`1 source)
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at Amazon.JSII.Runtime.Deputy.DeputyBase..ctor(DeputyProps props)
   at Amazon.CDK.Construct..ctor(DeputyProps props)
   at Amazon.CDK.CfnElement..ctor(DeputyProps props)
   at Amazon.CDK.CfnRefElement..ctor(DeputyProps props)
   at Amazon.CDK.CfnMapping..ctor(Construct scope, String id, ICfnMappingProps props)
   at Missionserver.MissionserverStack..ctor(Construct scope, String id, IStackProps props) in E:\CDKWorkshop\missionserver\src\Missionserver\MissionserverStack.cs:line 57
   at Missionserver.Program.Main(String[] args) in E:\CDKWorkshop\missionserver\src\Missionserver\Program.cs:line 17
```

### Environment

  - **CLI Version      : 1.24.0
  - **Framework Version: 1.24.0
  - **OS               :  Windows
  - **Language         :  .Net

### Other

I am quite sure my code is correct and found that similar errors are already reported. (https://github.com/aws/aws-cdk/issues/5317)

Let me know if you need more information. Your help will be much appreciated. Thanks.

--- 

This is :bug: Bug Report

**Comment by Pankajc123** [comment]
is this issue fixed?

**Comment by Pankajc123** [comment]
Hello,

Is this issue resolved?

**Comment by MrArnoldPalmer** [comment]
hey @Pankajc123, this hasn't been solved but you may be able to workaround it by specifying a more specific type if you're able as detailed in https://github.com/aws/jsii/issues/1044

**Comment by Pankajc123** [comment]
@MrArnoldPalmer  Thanks for your workaround. I am able to get past that problem. But i would still like to be fixed.
