### ISSUE TITLE
Changeset failed: Error: Failed to create ChangeSet FAILED, Internal Failure

### ISSUE THREAD

**Issue by 0xjjoyy** [aws/aws-cdk#7439]
## :question: General Issue
```
test-example failed: Error: Failed to create ChangeSet CDK-b3ba7823-3649-4c2d-be39-25ad57f0c379 on test-example: FAILED, Internal Failure
    at /usr/local/lib/node_modules/aws-cdk/lib/api/util/cloudformation.ts:189:11
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at waitFor (/usr/local/lib/node_modules/aws-cdk/lib/api/util/cloudformation.ts:150:20)
    at Object.waitForChangeSet (/usr/local/lib/node_modules/aws-cdk/lib/api/util/cloudformation.ts:175:15)
    at Object.deployStack (/usr/local/lib/node_modules/aws-cdk/lib/api/deploy-stack.ts:214:32)
    at CdkToolkit.deploy (/usr/local/lib/node_modules/aws-cdk/lib/cdk-toolkit.ts:180:24)
    at main (/usr/local/lib/node_modules/aws-cdk/bin/cdk.ts:229:16)
    at initCommandLine (/usr/local/lib/node_modules/aws-cdk/bin/cdk.ts:167:9)
Failed to create ChangeSet CDK-b3ba7823-3649-4c2d-be39-25ad57f0c379 on test-example: FAILED, Internal Failure
Error: Failed to create ChangeSet CDK-b3ba7823-3649-4c2d-be39-25ad57f0c379 on test-example: FAILED, Internal Failure
    at /usr/local/lib/node_modules/aws-cdk/lib/api/util/cloudformation.ts:189:11
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at waitFor (/usr/local/lib/node_modules/aws-cdk/lib/api/util/cloudformation.ts:150:20)
    at Object.waitForChangeSet (/usr/local/lib/node_modules/aws-cdk/lib/api/util/cloudformation.ts:175:15)
    at Object.deployStack (/usr/local/lib/node_modules/aws-cdk/lib/api/deploy-stack.ts:214:32)
    at CdkToolkit.deploy (/usr/local/lib/node_modules/aws-cdk/lib/cdk-toolkit.ts:180:24)
    at main (/usr/local/lib/node_modules/aws-cdk/bin/cdk.ts:229:16)
    at initCommandLine (/usr/local/lib/node_modules/aws-cdk/bin/cdk.ts:167:9)
```

### The Question

I'm unable to make changes to my Lambda after the initial stack deployment. I receive the following error.

```
test-example failed: Error: Failed to create ChangeSet CDK-b3ba7823-3649-4c2d-be39-25ad57f0c379 on test-example: FAILED, Internal Failure
    at /usr/local/lib/node_modules/aws-cdk/lib/api/util/cloudformation.ts:189:11
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at waitFor (/usr/local/lib/node_modules/aws-cdk/lib/api/util/cloudformation.ts:150:20)
    at Object.waitForChangeSet (/usr/local/lib/node_modules/aws-cdk/lib/api/util/cloudformation.ts:175:15)
    at Object.deployStack (/usr/local/lib/node_modules/aws-cdk/lib/api/deploy-stack.ts:214:32)
    at CdkToolkit.deploy (/usr/local/lib/node_modules/aws-cdk/lib/cdk-toolkit.ts:180:24)
    at main (/usr/local/lib/node_modules/aws-cdk/bin/cdk.ts:229:16)
    at initCommandLine (/usr/local/lib/node_modules/aws-cdk/bin/cdk.ts:167:9)
Failed to create ChangeSet CDK-b3ba7823-3649-4c2d-be39-25ad57f0c379 on test-example: FAILED, Internal Failure
Error: Failed to create ChangeSet CDK-b3ba7823-3649-4c2d-be39-25ad57f0c379 on test-example: FAILED, Internal Failure
    at /usr/local/lib/node_modules/aws-cdk/lib/api/util/cloudformation.ts:189:11
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at waitFor (/usr/local/lib/node_modules/aws-cdk/lib/api/util/cloudformation.ts:150:20)
    at Object.waitForChangeSet (/usr/local/lib/node_modules/aws-cdk/lib/api/util/cloudformation.ts:175:15)
    at Object.deployStack (/usr/local/lib/node_modules/aws-cdk/lib/api/deploy-stack.ts:214:32)
    at CdkToolkit.deploy (/usr/local/lib/node_modules/aws-cdk/lib/cdk-toolkit.ts:180:24)
    at main (/usr/local/lib/node_modules/aws-cdk/bin/cdk.ts:229:16)
    at initCommandLine (/usr/local/lib/node_modules/aws-cdk/bin/cdk.ts:167:9)
```

### Environment

  - **CDK CLI Version:**  1.33.0 (build 763b2ab)
  - **Module Version:** 
  - **OS:** 
  - **Language:**  Python

### Other information

```console
[CDK toolkit version: 1.33.0 (build 763b2ab)
Command line arguments: {
  _: [ 'deploy' ],
  verbose: true,
  v: true,
  'ignore-errors': false,
  ignoreErrors: false,
  json: false,
  j: false,
  ec2creds: undefined,
  i: undefined,
  'version-reporting': undefined,
  versionReporting: undefined,
  'path-metadata': true,
  pathMetadata: true,
  'asset-metadata': true,
  assetMetadata: true,
  'role-arn': undefined,
  r: undefined,
  roleArn: undefined,
  staging: true,
  'no-color': false,
  noColor: false,
  fail: false,
  'build-exclude': [],
  E: [],
  buildExclude: [],
  ci: false,
  execute: true,
  force: false,
  f: false,
  parameters: [ {} ],
  '$0': '/usr/local/bin/cdk',
  STACKS: [ 'test-example' ],
  stacks: [ 'test-example' ]
}
Determining whether we're on an EC2 instance.
Does not look like EC2 instance.
Unable to determine AWS region from environment or AWS configuration (profile: "test.1"), defaulting to 'us-east-1'
cdk.json: {
  "app": "python3 app.py"
}
cdk.context.json: {
  "@aws-cdk/core:enableStackNameDuplicates": "true",
  "aws-cdk:enableDiffNoFail": "true"
}
merged settings: {
  versionReporting: true,
  pathMetadata: true,
  output: 'cdk.out',
  app: 'python3 app.py',
  context: {},
  tags: [],
  assetMetadata: true,
  toolkitBucket: {},
  staging: true
}
Toolkit stack: CDKToolkit
Setting "CDK_DEFAULT_REGION" environment variable to us-east-1
Resolving default credentials
Retrieved account ID XXXXXXXXX from disk cache
Setting "CDK_DEFAULT_ACCOUNT" environment variable to XXXXXXXX
context: {
  '@aws-cdk/core:enableStackNameDuplicates': 'true',
  'aws-cdk:enableDiffNoFail': 'true',
  'aws:cdk:enable-path-metadata': true,
  'aws:cdk:enable-asset-metadata': true
}
outdir: cdk.out
env: {
  CDK_DEFAULT_REGION: 'us-east-1',
  CDK_DEFAULT_ACCOUNT: 'XXXXXXXXX',
  CDK_CONTEXT_JSON: '{"@aws-cdk/core:enableStackNameDuplicates":"true","aws-cdk:enableDiffNoFail":"true","aws:cdk:enable-path-metadata":true,"aws:cdk:enable-asset-metadata":true}',
  CDK_OUTDIR: 'cdk.out',
  CDK_CLI_ASM_VERSION: '1.33.0',
  CDK_CLI_VERSION: '1.33.0'
}
Reading existing template for stack test-example.
test-example: deploying...
Waiting for stack CDKToolkit to finish creating or updating...
checking if we can skip this stack based on the currently deployed template and tags (use --force to override)
test-example: template changed, deploying...
Preparing asset b1598fcc443df626e90a2fe22394fcff3d61daf12b886f8a55238ca752ec5e20: {"path":"asset.b1598fcc443df626e90a2fe22394fcff3d61daf12b886f8a55238ca752ec5e20","id":"b1598fcc443df626e90a2fe22394fcff3d61daf12b886f8a55238ca752ec5e20","packaging":"zip","sourceHash":"b1598fcc443df626e90a2fe22394fcff3d61daf12b886f8a55238ca752ec5e20","s3BucketParameter":"AssetParametersb1598fcc443df626e90a2fe22394fcff3d61daf12b886f8a55238ca752ec5e20S3Bucket1BD11786","s3KeyParameter":"AssetParametersb1598fcc443df626e90a2fe22394fcff3d61daf12b886f8a55238ca752ec5e20S3VersionKey85BEC7C9","artifactHashParameter":"AssetParametersb1598fcc443df626e90a2fe22394fcff3d61daf12b886f8a55238ca752ec5e20ArtifactHash2F7E7D0B"}
Storing asset asset.b1598fcc443df626e90a2fe22394fcff3d61daf12b886f8a55238ca752ec5e20 at s3://cdktoolkit-stagingbucket-1cvpts21e1gxo/assets/b1598fcc443df626e90a2fe22394fcff3d61daf12b886f8a55238ca752ec5e20.zip
Preparing asset 43c6613893c2b9a682e5df9816f3acdae6eae68a9100658c2dcb1233904137c5: {"path":"asset.43c6613893c2b9a682e5df9816f3acdae6eae68a9100658c2dcb1233904137c5","id":"43c6613893c2b9a682e5df9816f3acdae6eae68a9100658c2dcb1233904137c5","packaging":"zip","sourceHash":"43c6613893c2b9a682e5df9816f3acdae6eae68a9100658c2dcb1233904137c5","s3BucketParameter":"AssetParameters43c6613893c2b9a682e5df9816f3acdae6eae68a9100658c2dcb1233904137c5S3BucketF3A0EAA9","s3KeyParameter":"AssetParameters43c6613893c2b9a682e5df9816f3acdae6eae68a9100658c2dcb1233904137c5S3VersionKeyB0513299","artifactHashParameter":"AssetParameters43c6613893c2b9a682e5df9816f3acdae6eae68a9100658c2dcb1233904137c5ArtifactHash0C371251"}
Storing asset asset.43c6613893c2b9a682e5df9816f3acdae6eae68a9100658c2dcb1233904137c5 at s3://cdktoolkit-stagingbucket-1cvpts21e1gxo/assets/43c6613893c2b9a682e5df9816f3acdae6eae68a9100658c2dcb1233904137c5.zip
Preparing asset 06cc023f657a6bcd175405bef7a99d4f3e9450342c16f7155298262071504fd4: {"path":"asset.06cc023f657a6bcd175405bef7a99d4f3e9450342c16f7155298262071504fd4","id":"06cc023f657a6bcd175405bef7a99d4f3e9450342c16f7155298262071504fd4","packaging":"zip","sourceHash":"06cc023f657a6bcd175405bef7a99d4f3e9450342c16f7155298262071504fd4","s3BucketParameter":"AssetParameters06cc023f657a6bcd175405bef7a99d4f3e9450342c16f7155298262071504fd4S3BucketBEC46836","s3KeyParameter":"AssetParameters06cc023f657a6bcd175405bef7a99d4f3e9450342c16f7155298262071504fd4S3VersionKeyA9418B2F","artifactHashParameter":"AssetParameters06cc023f657a6bcd175405bef7a99d4f3e9450342c16f7155298262071504fd4ArtifactHash20CA3565"}
Storing asset asset.06cc023f657a6bcd175405bef7a99d4f3e9450342c16f7155298262071504fd4 at s3://cdktoolkit-stagingbucket-1cvpts21e1gxo/assets/06cc023f657a6bcd175405bef7a99d4f3e9450342c16f7155298262071504fd4.zip
Preparing asset 0db23ea19b6fada2034a03c4aa00beb1c4e2af19d91b67c4032329ac757630e1: {"path":"asset.0db23ea19b6fada2034a03c4aa00beb1c4e2af19d91b67c4032329ac757630e1","id":"0db23ea19b6fada2034a03c4aa00beb1c4e2af19d91b67c4032329ac757630e1","packaging":"zip","sourceHash":"0db23ea19b6fada2034a03c4aa00beb1c4e2af19d91b67c4032329ac757630e1","s3BucketParameter":"AssetParameters0db23ea19b6fada2034a03c4aa00beb1c4e2af19d91b67c4032329ac757630e1S3Bucket6CA4E5B3","s3KeyParameter":"AssetParameters0db23ea19b6fada2034a03c4aa00beb1c4e2af19d91b67c4032329ac757630e1S3VersionKey358B0AD8","artifactHashParameter":"AssetParameters0db23ea19b6fada2034a03c4aa00beb1c4e2af19d91b67c4032329ac757630e1ArtifactHashE7BD10E3"}
Storing asset asset.0db23ea19b6fada2034a03c4aa00beb1c4e2af19d91b67c4032329ac757630e1 at s3://cdktoolkit-stagingbucket-1cvpts21e1gxo/assets/0db23ea19b6fada2034a03c4aa00beb1c4e2af19d91b67c4032329ac757630e1.zip
Preparing asset 6e4e40d07a5603d4e91ca0ce57736f4570c9ae1c50816155719bb98da1be3c02: {"path":"asset.6e4e40d07a5603d4e91ca0ce57736f4570c9ae1c50816155719bb98da1be3c02","id":"6e4e40d07a5603d4e91ca0ce57736f4570c9ae1c50816155719bb98da1be3c02","packaging":"zip","sourceHash":"6e4e40d07a5603d4e91ca0ce57736f4570c9ae1c50816155719bb98da1be3c02","s3BucketParameter":"AssetParameters6e4e40d07a5603d4e91ca0ce57736f4570c9ae1c50816155719bb98da1be3c02S3Bucket3A4E922F","s3KeyParameter":"AssetParameters6e4e40d07a5603d4e91ca0ce57736f4570c9ae1c50816155719bb98da1be3c02S3VersionKey02CD4116","artifactHashParameter":"AssetParameters6e4e40d07a5603d4e91ca0ce57736f4570c9ae1c50816155719bb98da1be3c02ArtifactHashF404E629"}
Storing asset asset.6e4e40d07a5603d4e91ca0ce57736f4570c9ae1c50816155719bb98da1be3c02 at s3://cdktoolkit-stagingbucket-1cvpts21e1gxo/assets/6e4e40d07a5603d4e91ca0ce57736f4570c9ae1c50816155719bb98da1be3c02.zip
[0%] start: Publishing b1598fcc443df626e90a2fe22394fcff3d61daf12b886f8a55238ca752ec5e20:current
[0%] check: Check s3://cdktoolkit-stagingbucket-1cvpts21e1gxo/assets/b1598fcc443df626e90a2fe22394fcff3d61daf12b886f8a55238ca752ec5e20.zip
[0%] found: Found s3://cdktoolkit-stagingbucket-1cvpts21e1gxo/assets/b1598fcc443df626e90a2fe22394fcff3d61daf12b886f8a55238ca752ec5e20.zip
[20%] success: Published b1598fcc443df626e90a2fe22394fcff3d61daf12b886f8a55238ca752ec5e20:current
[20%] start: Publishing 43c6613893c2b9a682e5df9816f3acdae6eae68a9100658c2dcb1233904137c5:current
[20%] check: Check s3://cdktoolkit-stagingbucket-1cvpts21e1gxo/assets/43c6613893c2b9a682e5df9816f3acdae6eae68a9100658c2dcb1233904137c5.zip
[20%] found: Found s3://cdktoolkit-stagingbucket-1cvpts21e1gxo/assets/43c6613893c2b9a682e5df9816f3acdae6eae68a9100658c2dcb1233904137c5.zip
[40%] success: Published 43c6613893c2b9a682e5df9816f3acdae6eae68a9100658c2dcb1233904137c5:current
[40%] start: Publishing 06cc023f657a6bcd175405bef7a99d4f3e9450342c16f7155298262071504fd4:current
[40%] check: Check s3://cdktoolkit-stagingbucket-1cvpts21e1gxo/assets/06cc023f657a6bcd175405bef7a99d4f3e9450342c16f7155298262071504fd4.zip
[40%] found: Found s3://cdktoolkit-stagingbucket-1cvpts21e1gxo/assets/06cc023f657a6bcd175405bef7a99d4f3e9450342c16f7155298262071504fd4.zip
[60%] success: Published 06cc023f657a6bcd175405bef7a99d4f3e9450342c16f7155298262071504fd4:current
[60%] start: Publishing 0db23ea19b6fada2034a03c4aa00beb1c4e2af19d91b67c4032329ac757630e1:current
[60%] check: Check s3://cdktoolkit-stagingbucket-1cvpts21e1gxo/assets/0db23ea19b6fada2034a03c4aa00beb1c4e2af19d91b67c4032329ac757630e1.zip
[60%] build: Zip /Users/test-example/cdk.out/asset.0db23ea19b6fada2034a03c4aa00beb1c4e2af19d91b67c4032329ac757630e1 -> cdk.out/.cache/0db23ea19b6fada2034a03c4aa00beb1c4e2af19d91b67c4032329ac757630e1.zip
[60%] upload: Upload s3://cdktoolkit-stagingbucket-1cvpts21e1gxo/assets/0db23ea19b6fada2034a03c4aa00beb1c4e2af19d91b67c4032329ac757630e1.zip
[80%] success: Published 0db23ea19b6fada2034a03c4aa00beb1c4e2af19d91b67c4032329ac757630e1:current
[80%] start: Publishing 6e4e40d07a5603d4e91ca0ce57736f4570c9ae1c50816155719bb98da1be3c02:current
[80%] check: Check s3://cdktoolkit-stagingbucket-1cvpts21e1gxo/assets/6e4e40d07a5603d4e91ca0ce57736f4570c9ae1c50816155719bb98da1be3c02.zip
[80%] found: Found s3://cdktoolkit-stagingbucket-1cvpts21e1gxo/assets/6e4e40d07a5603d4e91ca0ce57736f4570c9ae1c50816155719bb98da1be3c02.zip
[100%] success: Published 6e4e40d07a5603d4e91ca0ce57736f4570c9ae1c50816155719bb98da1be3c02:current
Attempting to create ChangeSet CDK-b3ba7823-3649-4c2d-be39-25ad57f0c379 to update stack test-example
test-example: creating CloudFormation changeset...
Initiated creation of changeset: arn:aws:cloudformation:us-east-1:XXXXXXX:changeSet/CDK-b3ba7823-3649-4c2d-be39-25ad57f0c379/9245f691-cd2c-4fb6-8599-eb5d7d3b70af; waiting for it to finish creating...
Waiting for changeset CDK-b3ba7823-3649-4c2d-be39-25ad57f0c379 on stack test-example to finish creating...
Changeset CDK-b3ba7823-3649-4c2d-be39-25ad57f0c379 on stack test-example is still creating

 ❌  test-example failed: Error: Failed to create ChangeSet CDK-b3ba7823-3649-4c2d-be39-25ad57f0c379 on test-example: FAILED, Internal Failure
    at /usr/local/lib/node_modules/aws-cdk/lib/api/util/cloudformation.ts:189:11
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at waitFor (/usr/local/lib/node_modules/aws-cdk/lib/api/util/cloudformation.ts:150:20)
    at Object.waitForChangeSet (/usr/local/lib/node_modules/aws-cdk/lib/api/util/cloudformation.ts:175:15)
    at Object.deployStack (/usr/local/lib/node_modules/aws-cdk/lib/api/deploy-stack.ts:214:32)
    at CdkToolkit.deploy (/usr/local/lib/node_modules/aws-cdk/lib/cdk-toolkit.ts:180:24)
    at main (/usr/local/lib/node_modules/aws-cdk/bin/cdk.ts:229:16)
    at initCommandLine (/usr/local/lib/node_modules/aws-cdk/bin/cdk.ts:167:9)
Failed to create ChangeSet CDK-b3ba7823-3649-4c2d-be39-25ad57f0c379 on test-example: FAILED, Internal Failure
Error: Failed to create ChangeSet CDK-b3ba7823-3649-4c2d-be39-25ad57f0c379 on test-example: FAILED, Internal Failure
    at /usr/local/lib/node_modules/aws-cdk/lib/api/util/cloudformation.ts:189:11
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at waitFor (/usr/local/lib/node_modules/aws-cdk/lib/api/util/cloudformation.ts:150:20)
    at Object.waitForChangeSet (/usr/local/lib/node_modules/aws-cdk/lib/api/util/cloudformation.ts:175:15)
    at Object.deployStack (/usr/local/lib/node_modules/aws-cdk/lib/api/deploy-stack.ts:214:32)
    at CdkToolkit.deploy (/usr/local/lib/node_modules/aws-cdk/lib/cdk-toolkit.ts:180:24)
    at main (/usr/local/lib/node_modules/aws-cdk/bin/cdk.ts:229:16)
    at initCommandLine (/usr/local/lib/node_modules/aws-cdk/bin/cdk.ts:167:9)](url)
```

**Comment by shivlaks** [comment]
@0xjjoyy can you provide a bit more information. what's a minimal repro of your current lambda setup? Are there any more clues in CloudFormation as to why the changeset failed to create?

I just ran through an example of a very simple hello world lambda with a structure like
```
- project
  - my-lambda-handler
  - lib
  - test
  - ...
```

In my cdk app something like
```ts
new lambda.Function(stack, 'my-cool-function', {
  runtime: lambda.Runtime.NODEJS_10_X,
  handler: 'index.handler',
  code: lambda.AssetCode.fromAsset(path.join(__dirname, 'my-lambda-handler.handler')),
});
```
I can update and deploy my function as I grow it.
