### ISSUE TITLE
AWS Batch JobDefinition throws an exception 

### ISSUE THREAD

**Issue by farzad-xgen** [aws/aws-cdk#7465]
I'm using aws-cdk with Python. We had successfully used aws-batch to create and lunch a batch job but now we are getting errors.

### Reproduction Steps

```
from aws_cdk import (
    core,
    aws_batch as batch
)

class MyStack(core.Stack):
    def __init__(self, scope, id: str, **kwargs) -> None:
        super().__init__(scope, id, **kwargs)
  
        my_batch_job = batch.JobDefinition(self,
            "batch_job_name",
            container=my_container,
            job_definition_name="my_batch_job_name",
        )

app = core.App()
MyStack(app, "my-stack")
app.synth()

```

### Error Log

```
jsii.errors.JavaScriptError: 
  Error: Got 'undefined' for non-optional instance of {"type":{"primitive":"string"}}
      at nullAndOk (/home/farzad/xgen/b-dev/backend/xgen/iac/.venv/lib/python3.6/site-packages/jsii/_embedded/jsii/jsii-runtime.js:7153:15)
      at Object.deserialize (/home/farzad/xgen/b-dev/backend/xgen/iac/.venv/lib/python3.6/site-packages/jsii/_embedded/jsii/jsii-runtime.js:6700:17)
      at Kernel._toSandbox (/home/farzad/xgen/b-dev/backend/xgen/iac/.venv/lib/python3.6/site-packages/jsii/_embedded/jsii/jsii-runtime.js:8207:61)
      at v (/home/farzad/xgen/b-dev/backend/xgen/iac/.venv/lib/python3.6/site-packages/jsii/_embedded/jsii/jsii-runtime.js:6836:72)
      at mapValues (/home/farzad/xgen/b-dev/backend/xgen/iac/.venv/lib/python3.6/site-packages/jsii/_embedded/jsii/jsii-runtime.js:7179:27)
      at Object.deserialize (/home/farzad/xgen/b-dev/backend/xgen/iac/.venv/lib/python3.6/site-packages/jsii/_embedded/jsii/jsii-runtime.js:6836:28)
      at Kernel._toSandbox (/home/farzad/xgen/b-dev/backend/xgen/iac/.venv/lib/python3.6/site-packages/jsii/_embedded/jsii/jsii-runtime.js:8207:61)
      at mapValues (/home/farzad/xgen/b-dev/backend/xgen/iac/.venv/lib/python3.6/site-packages/jsii/_embedded/jsii/jsii-runtime.js:6919:29)
      at mapValues (/home/farzad/xgen/b-dev/backend/xgen/iac/.venv/lib/python3.6/site-packages/jsii/_embedded/jsii/jsii-runtime.js:7179:27)
      at Kernel._wrapSandboxCode (/home/farzad/xgen/b-dev/backend/xgen/iac/.venv/lib/python3.6/site-packages/jsii/_embedded/jsii/jsii-runtime.js:8301:19)
      at Kernel._create (/home/farzad/xgen/b-dev/backend/xgen/iac/.venv/lib/python3.6/site-packages/jsii/_embedded/jsii/jsii-runtime.js:7838:26)
      at Kernel.create (/home/farzad/xgen/b-dev/backend/xgen/iac/.venv/lib/python3.6/site-packages/jsii/_embedded/jsii/jsii-runtime.js:7585:21)
      at KernelHost.processRequest (/home/farzad/xgen/b-dev/backend/xgen/iac/.venv/lib/python3.6/site-packages/jsii/_embedded/jsii/jsii-runtime.js:7372:28)
      at KernelHost.run (/home/farzad/xgen/b-dev/backend/xgen/iac/.venv/lib/python3.6/site-packages/jsii/_embedded/jsii/jsii-runtime.js:7312:14)
      at Immediate.setImmediate [as _onImmediate] (/home/farzad/xgen/b-dev/backend/xgen/iac/.venv/lib/python3.6/site-packages/jsii/_embedded/jsii/jsii-runtime.js:7315:37)
      at runCallback (timers.js:705:18)
      at tryOnImmediate (timers.js:676:5)
      at processImmediate (timers.js:658:5)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "app.py", line 15, in <module>
    app = XGenApp()
  File "/home/farzad/xgen/b-dev/backend/xgen/iac/.venv/lib/python3.6/site-packages/jsii/_runtime.py", line 66, in __call__
    inst = super().__call__(*args, **kwargs)
  File "/home/farzad/xgen/b-dev/backend/xgen/iac/stacks/xgen.py", line 25, in __init__
    self.create_stacks()
  File "/home/farzad/xgen/b-dev/backend/xgen/iac/stacks/xgen.py", line 33, in create_stacks
    ai_stack = AIStack(self, "b-ai")
  File "/home/farzad/xgen/b-dev/backend/xgen/iac/.venv/lib/python3.6/site-packages/jsii/_runtime.py", line 66, in __call__
    inst = super().__call__(*args, **kwargs)
  File "/home/farzad/xgen/b-dev/backend/xgen/iac/stacks/AI/stack.py", line 664, in __init__
    container=image_processing_container,
  File "/home/farzad/xgen/b-dev/backend/xgen/iac/.venv/lib/python3.6/site-packages/jsii/_runtime.py", line 66, in __call__
    inst = super().__call__(*args, **kwargs)
  File "/home/farzad/xgen/b-dev/backend/xgen/iac/.venv/lib/python3.6/site-packages/aws_cdk/aws_batch/__init__.py", line 2691, in __init__
    jsii.create(JobDefinition, self, [scope, id, props])
  File "/home/farzad/xgen/b-dev/backend/xgen/iac/.venv/lib/python3.6/site-packages/jsii/_kernel/__init__.py", line 229, in create
    interfaces=[iface.__jsii_type__ for iface in getattr(klass, "__jsii_ifaces__", [])],
  File "/home/farzad/xgen/b-dev/backend/xgen/iac/.venv/lib/python3.6/site-packages/jsii/_kernel/providers/process.py", line 333, in create
    return self._process.send(request, CreateResponse)
  File "/home/farzad/xgen/b-dev/backend/xgen/iac/.venv/lib/python3.6/site-packages/jsii/_kernel/providers/process.py", line 318, in send
    raise JSIIError(resp.error) from JavaScriptError(resp.stack)
jsii.errors.JSIIError: Got 'undefined' for non-optional instance of {"type":{"primitive":"string"}}
```

### Environment

  - **CLI Version      :** aws-cli/1.14.44 Python/3.6.9 Linux/4.15.0-96-generic botocore/1.15.20
  - **Framework Version:** 1.33.1 (build 8ad4d34)
  - **OS               :** Ubuntu 18.04 Desktop
  - **Language         :** Python

### Other
--- 

This is :bug: Bug Report

**Comment by farzad-xgen** [comment]
It is resolved, some missing parameter elsewhere in container definition caused that.
