### ISSUE TITLE
"ValidationException: Invalid UpdateExpression: Syntax error; token: \":\", near: \"hits : incr\""

### ISSUE THREAD

**Issue by SeanDez** [aws/aws-cdk#7591]
A ValidationException is thrown to CloudWatch logs when I attempt to run `curl ` or run the request from Chromium browser to url: https://txsdqk259f.execute-api.us-east-2.amazonaws.com/prod/

### Reproduction Steps

1. Initialize/bootstrap a new cdk project. Set the core package and all scoped deps to version 1.33.1 manually in package.json. Rerun `npm i` to update to the correct versions.
2. create a new `cdk` project and replace your `lib` folder's stack file contents with below.
.  
3. run `cdk synth` and `cdk deploy`
4. Copy the output URL from terminal to the browser. The error log should propagate to CloudWatch.

Here is my stack file in the `lib` folder:

```typescript
import * as cdk from '@aws-cdk/core';
import * as lambda from "@aws-cdk/aws-lambda";
import * as apigw from "@aws-cdk/aws-apigateway";
import { HitCounter } from "./hitcounter";

export class CdkWorkshopStack extends cdk.Stack {
  constructor(scope: cdk.App, id: string, props?: cdk.StackProps) {
    super(scope, id, props);

    // defines an aws lambda resource
    // paths are relative to where CDK is executed in terminal
    const hello = new lambda.Function(this, "HelloHandler", {
      runtime : lambda.Runtime.NODEJS_12_X
      , code : lambda.Code.fromAsset("lambda")
      , handler : "hello.handler"
    });

    const helloWithCounter = new HitCounter(this, "HelloHitCounter", { downstream : hello })

    // defines api gateway resource backed by a lambda function
    new apigw.LambdaRestApi(this, "Endpoint", { 
      handler : helloWithCounter.handler
    });
  }
}

```

### Error Log

```BASH
2020-04-24T09:51:14.464Z	a0f1e921-b3c6-44b6-9ebe-1719f498a038	ERROR	Invoke Error 	
{
    "errorType": "ValidationException",
    "errorMessage": "Invalid UpdateExpression: Syntax error; token: \":\", near: \"hits : incr\"",
    "code": "ValidationException",
    "message": "Invalid UpdateExpression: Syntax error; token: \":\", near: \"hits : incr\"",
    "time": "2020-04-24T09:51:14.463Z",
    "requestId": "OQVSH2L73CBH5VQH8QAV21PVRVVV4KQNSO5AEMVJF66Q9ASUAAJG",
    "statusCode": 400,
    "retryable": false,
    "retryDelay": 21.55158142196281,
    "stack": [
        "ValidationException: Invalid UpdateExpression: Syntax error; token: \":\", near: \"hits : incr\"",
        "    at Request.extractError (/var/runtime/node_modules/aws-sdk/lib/protocol/json.js:51:27)",
        "    at Request.callListeners (/var/runtime/node_modules/aws-sdk/lib/sequential_executor.js:106:20)",
        "    at Request.emit (/var/runtime/node_modules/aws-sdk/lib/sequential_executor.js:78:10)",
        "    at Request.emit (/var/runtime/node_modules/aws-sdk/lib/request.js:683:14)",
        "    at Request.transition (/var/runtime/node_modules/aws-sdk/lib/request.js:22:10)",
        "    at AcceptorStateMachine.runTo (/var/runtime/node_modules/aws-sdk/lib/state_machine.js:14:12)",
        "    at /var/runtime/node_modules/aws-sdk/lib/state_machine.js:26:10",
        "    at Request.<anonymous> (/var/runtime/node_modules/aws-sdk/lib/request.js:38:9)",
        "    at Request.<anonymous> (/var/runtime/node_modules/aws-sdk/lib/request.js:685:12)",
        "    at Request.callListeners (/var/runtime/node_modules/aws-sdk/lib/sequential_executor.js:116:18)"
    ]
}

```

also in CloudWatch:

```BASH
{
    "resource": "/",
    "path": "/",
    "httpMethod": "GET",
    "headers": {
        "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9",
        "Accept-Encoding": "gzip, deflate, br",
        "Accept-Language": "en-US,en;q=0.9",
        "CloudFront-Forwarded-Proto": "https",
        "CloudFront-Is-Desktop-Viewer": "true",
        "CloudFront-Is-Mobile-Viewer": "false",
        "CloudFront-Is-SmartTV-Viewer": "false",
        "CloudFront-Is-Tablet-Viewer": "false",
        "CloudFront-Viewer-Country": "TH",
        "Host": "txsdqk259f.execute-api.us-east-2.amazonaws.com",
        "sec-fetch-dest": "document",
        "sec-fetch-mode": "navigate",
        "sec-fetch-site": "none",
        "upgrade-insecure-requests": "1",
        "User-Agent": "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.163 Safari/537.36 OPR/67.0.3575.137",
        "Via": "2.0 0da14962afa287e5ba55c7d30c902392.cloudfront.net (CloudFront)",
        "X-Amz-Cf-Id": "VMInYp6agTrAT2yQ5Z28EXYd-2zauiCC6VhFpbT_YvVbBNTmegCIBQ==",
        "X-Amzn-Trace-Id": "Root=1-5ea2b692-68aadba020f0f580a3124b40",
        "X-Forwarded-For": "115.87.114.182, 204.246.166.104",
        "X-Forwarded-Port": "443",
        "X-Forwarded-Proto": "https"
    },
    "multiValueHeaders": {
        "Accept": [
            "text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9"
        ],
        "Accept-Encoding": [
            "gzip, deflate, br"
        ],
        "Accept-Language": [
            "en-US,en;q=0.9"
        ],
        "CloudFront-Forwarded-Proto": [
            "https"
        ],
        "CloudFront-Is-Desktop-Viewer": [
            "true"
        ],
        "CloudFront-Is-Mobile-Viewer": [
            "false"
        ],
        "CloudFront-Is-SmartTV-Viewer": [
            "false"
        ],
        "CloudFront-Is-Tablet-Viewer": [
            "false"
        ],
        "CloudFront-Viewer-Country": [
            "TH"
        ],
        "Host": [
            "txsdqk259f.execute-api.us-east-2.amazonaws.com"
        ],
        "sec-fetch-dest": [
            "document"
        ],
        "sec-fetch-mode": [
            "navigate"
        ],
        "sec-fetch-site": [
            "none"
        ],
        "upgrade-insecure-requests": [
            "1"
        ],
        "User-Agent": [
            "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.163 Safari/537.36 OPR/67.0.3575.137"
        ],
        "Via": [
            "2.0 0da14962afa287e5ba55c7d30c902392.cloudfront.net (CloudFront)"
        ],
        "X-Amz-Cf-Id": [
            "VMInYp6agTrAT2yQ5Z28EXYd-2zauiCC6VhFpbT_YvVbBNTmegCIBQ=="
        ],
        "X-Amzn-Trace-Id": [
            "Root=1-5ea2b692-68aadba020f0f580a3124b40"
        ],
        "X-Forwarded-For": [
            "115.87.114.182, 204.246.166.104"
        ],
        "X-Forwarded-Port": [
            "443"
        ],
        "X-Forwarded-Proto": [
            "https"
        ]
    },
    "queryStringParameters": null,
    "multiValueQueryStringParameters": null,
    "pathParameters": null,
    "stageVariables": null,
    "requestContext": {
        "resourceId": "5cbwptm923",
        "resourcePath": "/",
        "httpMethod": "GET",
        "extendedRequestId": "LfF25GwEiYcF5Ww=",
        "requestTime": "24/Apr/2020:09:51:14 +0000",
        "path": "/prod/",
        "accountId": "<removed>",
        "protocol": "HTTP/1.1",
        "stage": "prod",
        "domainPrefix": "txsdqk259f",
        "requestTimeEpoch": 1587721874410,
        "requestId": "01ed2d75-4655-45bd-97c6-2acee72f1f16",
        "identity": {
            "cognitoIdentityPoolId": null,
            "accountId": null,
            "cognitoIdentityId": null,
            "caller": null,
            "sourceIp": "115.87.114.182",
            "principalOrgId": null,
            "accessKey": null,
            "cognitoAuthenticationType": null,
            "cognitoAuthenticationProvider": null,
            "userArn": null,
            "userAgent": "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.163 Safari/537.36 OPR/67.0.3575.137",
            "user": null
        },
        "domainName": "txsdqk259f.execute-api.us-east-2.amazonaws.com",
        "apiId": "txsdqk259f"
    },
    "body": null,
    "isBase64Encoded": false
}
```

### Environment

  - **CLI Version      :** 1.33.1 (and all cdk scoped package deps are also 1.331)
  - **Framework Version:**  1.33.1
  - **OS               :** Lubuntu 18.04
  - **Language         :** Typescript

### Other

I am following the tutorial. The "hello CDK step" succeeded. The hitcounter error is not lined up to the error the tutorial expected to see: https://cdkworkshop.com/20-typescript/40-hit-counter/500-logs.html  Attempting `cdk deploy` produces the problem in the original post.

The tutorial shows an IAM/authorization issue. Mine shows a Verification Issue.

Thanks for any help

--- 

This is :bug: Bug Report

**Comment by SeanDez** [comment]
In case you wanted to see:

```
// lambda/hitcounter.ts
const { DynamoDB, Lambda } = require("aws-sdk");

const dynamo = new DynamoDB();
const lambda = new Lambda();

exports.handler = async function(event: any) {
   console.log('request: ', JSON.stringify(event, undefined, 2));

   await dynamo.updateItem({
      TableName : process.env.HITS_TABLE_NAME
      , Key : { path : { S : event.path } }
      , UpdateExpression : "ADD hits : incr"
      , ExpressionAttributeValues : { ":incr" :  { N: "1" } }
   }).promise();

   // call downstream function and capture response
   const response = await lambda.invoke({
      FunctionName : process.env.DOWNSTREAM_FUNCTION_NAME
      , Payload : JSON.stringify(event)
   }).promise();

   console.log("downstream response: ", JSON.stringify(response, undefined, 2));

   // return response back to upstream caller
   return JSON.parse(response.Payload);
}
```


```
// package.json
{
  "name": "cdk-workshop",
  "version": "0.1.0",
  "bin": {
    "cdk-workshop": "bin/cdk-workshop.js"
  },
  "scripts": {
    "build": "tsc",
    "watch": "tsc -w",
    "test": "jest",
    "cdk": "cdk"
  },
  "devDependencies": {
    "aws-cdk": "1.33.1",
    "@aws-cdk/assert": "1.33.1",
    "@types/jest": "^25.2.1",
    "@types/node": "10.17.5",
    "jest": "^25.3.0",
    "ts-jest": "^25.3.1",
    "ts-node": "^8.1.0",
    "typescript": "~3.7.2"
  },
  "dependencies": {
    "@aws-cdk/aws-apigateway": "1.33.1",
    "@aws-cdk/aws-dynamodb": "1.33.1",
    "@aws-cdk/aws-lambda": "1.33.1",
    "@aws-cdk/aws-sns": "1.33.1",
    "@aws-cdk/aws-sns-subscriptions": "1.33.1",
    "@aws-cdk/aws-sqs": "1.33.1",
    "@aws-cdk/core": "1.33.1",
    "aws-sdk": "^2.660.0"
  }
}
```

**Comment by SeanDez** [comment]
Issue was a small space typo:

```
      , UpdateExpression : "ADD hits : incr"
```

should instead be:

```
      , UpdateExpression : "ADD hits :incr"
```
