### ISSUE TITLE
Unexpected token error with java CDK 1.31.0+

### ISSUE THREAD

**Issue by disordered** [aws/aws-cdk#7646]
### The Question
Regardless of what the CDK template is, it always results in `Unexpected token` for any CDK command.
This started with version `1.31.0` of Java CDK.

### Environment

  - **CDK CLI Version:** 1.35.0 (build e0810c8)
  - **Module Version:** 1.31.0+
  - **OS:** OSX Catalina
  - **Language:** Java

### Other information
```
[error] software.amazon.jsii.JsiiException: Child process exited unexpectedly: /private/var/folders/rx/qlbjbhdd6c999cc73zvth9700000gn/T/jsii-java-runtime7523662753866794540/jsii-runtime.js:9230
[error] 	      } catch {
[error] 	              ^
[error] 	
[error] 	SyntaxError: Unexpected token {
[error] 	    at createScript (vm.js:80:10)
[error] 	    at Object.runInThisContext (vm.js:139:10)
[error] 	    at Module._compile (module.js:617:28)
[error] 	    at Object.Module._extensions..js (module.js:664:10)
[error] 	    at Module.load (module.js:566:32)
[error] 	    at tryModuleLoad (module.js:506:12)
[error] 	    at Function.Module._load (module.js:498:3)
[error] 	    at Function.Module.runMain (module.js:694:10)
[error] 	    at startup (bootstrap_node.js:204:16)
[error] 	    at bootstrap_node.js:625:3
[error] 	at software.amazon.jsii.JsiiRuntime.readNextResponse(JsiiRuntime.java:289)
[error] 	at software.amazon.jsii.JsiiRuntime.handshake(JsiiRuntime.java:269)
[error] 	at software.amazon.jsii.JsiiRuntime.startRuntimeIfNeeded(JsiiRuntime.java:253)
[error] 	at software.amazon.jsii.JsiiRuntime.getClient(JsiiRuntime.java:326)
[error] 	at software.amazon.jsii.JsiiEngine.getClient(JsiiEngine.java:90)
[error] 	at software.amazon.jsii.JsiiEngine.loadModule(JsiiEngine.java:128)
[error] 	at software.amazon.jsii.JsiiEngine.loadModule(JsiiEngine.java:125)
[error] 	at software.amazon.jsii.JsiiEngine.createNewObject(JsiiEngine.java:520)
[error] 	at software.amazon.awscdk.core.App.<init>(App.java:47)
[error] 	at CDK$.synthesize(CDK.scala:15)
[error] 	at $37848eb87dbd24065794$.$anonfun$root$8(build.sbt:13)
[error] 	at $37848eb87dbd24065794$.$anonfun$root$8$adapted(build.sbt:13)
[error] 	at scala.Function1.$anonfun$compose$1(Function1.scala:49)
[error] 	at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:62)
[error] 	at sbt.std.Transform$$anon$4.work(Transform.scala:67)
[error] 	at sbt.Execute.$anonfun$submit$2(Execute.scala:281)
[error] 	at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:19)
[error] 	at sbt.Execute.work(Execute.scala:290)
[error] 	at sbt.Execute.$anonfun$submit$1(Execute.scala:281)
[error] 	at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:178)
[error] 	at sbt.CompletionService$$anon$2.call(CompletionService.scala:37)
[error] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error] 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[error] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[error] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[error] 	at java.lang.Thread.run(Thread.java:748)
[error] (createCDKStacks) software.amazon.jsii.JsiiException: Child process exited unexpectedly: /private/var/folders/rx/qlbjbhdd6c999cc73zvth9700000gn/T/jsii-java-runtime7523662753866794540/jsii-runtime.js:9230
[error] 	      } catch {
[error] 	              ^
[error] 	
[error] 	SyntaxError: Unexpected token {
[error] 	    at createScript (vm.js:80:10)
[error] 	    at Object.runInThisContext (vm.js:139:10)
[error] 	    at Module._compile (module.js:617:28)
[error] 	    at Object.Module._extensions..js (module.js:664:10)
[error] 	    at Module.load (module.js:566:32)
[error] 	    at tryModuleLoad (module.js:506:12)
[error] 	    at Function.Module._load (module.js:498:3)
[error] 	    at Function.Module.runMain (module.js:694:10)
[error] 	    at startup (bootstrap_node.js:204:16)
[error] 	    at bootstrap_node.js:625:3
```

**Comment by NetaNir** [comment]
This looks like a node version issue, what version of node are you using?
The CDK requires node > 10.12.

**Comment by disordered** [comment]
ah, crap, you are right. I thought I was running node 14, probably checked in the wrong shell.

Thanks for the pointer.
