### ISSUE TITLE
‼️ NOTICE: CDK tests breaks with Jest v25.5.0  [Error: "TypeError: Cannot read property 'map' of undefined']

### ISSUE THREAD

**Issue by NetaNir** [aws/aws-cdk#7657]
Please add your +1 👍 to let us know you have encountered this

---

### Overview:
When testing CDK apps using `jest` v25.5.0 it throws:
```
TypeError: Cannot read property 'map' of undefined
```

#### Complete Error Message:
```

    TypeError: Cannot read property 'map' of undefined

       8 |     const stack = new Dummy.DummyStack(app, 'MyTestStack');
       9 |     // THEN
    > 10 |     expectCDK(stack).to(matchTemplate({
         |     ^
      11 |       "Resources": {}
      12 |     }, MatchStyle.EXACT))
      13 | });

      at findNpmPackage (node_modules/@aws-cdk/core/lib/private/runtime-info.ts:66:27)
      at Object.collectRuntimeInformation (node_modules/@aws-cdk/core/lib/private/runtime-info.ts:14:17)
      at App.synth (node_modules/@aws-cdk/core/lib/app.ts:144:39)
      at Function._synthesizeWithNested (node_modules/@aws-cdk/assert/lib/synth-utils.ts:57:54)
      at Object.expect (node_modules/@aws-cdk/assert/lib/expect.ts:8:90)
      at Object.<anonymous>.test (test/dummy.test.ts:10:5)
```
### Workaround:

Add the following snippet to your test files

```ts
beforeEach(() => {
  jest.resetModules();
});
```

[Jest documentation](https://jestjs.io/docs/en/jest-object#jestresetmodules)

### Environment

  - **CDK CLI Version:** All
  - **Module Version:** All
  - **OS:** All
  - **Language:** Typescript and Javascript

**Comment by NetaNir** [comment]
Temporarily configure dependabot to ignore `jest` upgrades: https://github.com/aws/aws-cdk/pull/7662

**Comment by iliapolo** [comment]
This issue seems to stem from the following commit to jest: https://github.com/facebook/jest/commit/470ef2d29c576d6a10de344ec25d5a855f02d519
