### ISSUE TITLE
[Feature idea] Import entire CDK app for cross-app resouce sharing

### ISSUE THREAD

**Issue by ivawzh** [aws/aws-cdk#7721]
I found cross-cdk-repo resource importing is a massive pain point of using AWS CDK. Majority of the public static methods with the pattern of `from...Atributes(scrope, id, attrs)` (such as `fromVpcAttributes`, `fromClusterAttributes`, `fromDomainNameAttributes`, etc) are hard to work with because they require many attributes. For example, `fromClusterAttributes` requires the argument of `securityGroups`. I don't even know how to make `CfnOutput` of the array of `cluser.connection.securityGroups` via CDK while documentation doesn't mention the `securityGroups` will always be in a fixed order.

### Use case

I believe cross-repo resource sharing is a common scenario for enterprise, SOA, and micro-service architectures. 

### Proposed Solution

Instead of importing individual resources with attribute lookup and CfnOutputs, now my idea is to utilize the programming language and import the entire dependent CDK App as a library. And enhance the `App` class to better support in-memory children resource lookup. 

For example, 

At Infrastructure CDK app

```ts
const infrastructure = new cdk.App()

new VpcStack(infrastructure, 'VpcInfrastructure', ...)
new ClusterStack(infrastructure, 'ClusterInfrastructure', ...)
new HostedNameStack(infrastructure, 'KmsInfrastructure', ...)

export default infrastructure
```

At micro-service CDK app

```ts
import infrastructure from '@private-packages/infrastructure-app'

const microServiceA = new cdk.App()

const vpcInfrastructure = infrastructure.lookupByStackId('VpcInfrastructure')
const clusterInfrastructure = infrastructure.lookupByStackId('ClusterInfrastructure')

new EcsServiceStack(microServiceA, 'MicroServiceA', {
	cluster: clusterInfrastructure.cluster,
    vpc: vpcInfrastructure.vpc,
    ...
})
```

### Other

* [ ] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by ivawzh** [comment]
I tried to implement the idea and created a repo https://github.com/ivawzh/cdk-playground.

It is failing on deploying the service repo for error:

```log
Error: Cannot reference across apps. Consuming and producing stacks must be defined within the same CDK app.
    at resolveValue (./infrastructure/node_modules/@aws-cdk/core/lib/private/refs.ts:48:11)
    at Object.resolveReferences (./infrastructure/node_modules/@aws-cdk/core/lib/private/refs.ts:29:24)
    at Object.prepareApp (./infrastructure/node_modules/@aws-cdk/core/lib/private/prepare-app.ts:26:5)
    at App.prepare (./infrastructure/node_modules/@aws-cdk/core/lib/app.ts:153:5)
    at App.onPrepare (./infrastructure/node_modules/@aws-cdk/core/lib/construct-compat.ts:111:10)
    at Node.prepare (./infrastructure/node_modules/constructs/lib/construct.ts:429:12)
    at Node.synthesize (./infrastructure/node_modules/constructs/lib/construct.ts:386:10)
    at Function.synth (./infrastructure/node_modules/@aws-cdk/core/lib/construct-compat.ts:231:22)
    at App.synth (./infrastructure/node_modules/@aws-cdk/core/lib/app.ts:142:36)
    at process.<anonymous> (./infrastructure/node_modules/@aws-cdk/core/lib/app.ts:121:45)
```

Is the cross-app reference limitation necessary on AWS CDK?

**Comment by eladb** [comment]
@ivawzh this is an interesting proposal. I am moving this issue to the RFC repo. I would recommend creating an RFC and following the [RFC process](https://github.com/aws/aws-cdk-rfcs#what-is-an-rfc) to get this explored a bit deeper.
