### ISSUE TITLE
[ValidationError]: Template error: instance of Fn::GetAtt references undefined resource Ec2TaskExecutionRole

### ISSUE THREAD

**Issue by ivawzh** [aws/aws-cdk#7761]
I am deploying a stack with ECS service, asset Docker image, shared ALB, individual listener, shared kms key, shared secret, shared RDS database and shared cluster. It keeps failing for error describe below.

### Reproduction Steps

Simplified code:

```ts
export class KeyStack extends cdk.Stack {
  ...

  this.key = new Key(this, `Key`, {
    trustAccountIdentities: true,
  })
}

export class DatabaseStack extends cdk.Stack {
  ...

  this.database = new DatabaseInstance(this, `database`, {
    secretKmsKey: props.key,
    storageEncrypted: false,
    ...
  })
}

export class ServicesStack extends cdk.Stack {
  constructor(scope: cdk.Construct, id: string, props: ServicesStackProps) {
    super(scope, id, props)

    const apiTask = new Ec2TaskDefinition(this, 'ApiEc2Task')

    props.database.secret.grantRead(this.apiTask.obtainExecutionRole())

    apiTask.addContainer('Api', {
      image: ContainerImage.fromRegistry('nginx:latest'),
      cpu: 100,
      memoryReservationMiB: 200,
      secrets: {
        DATABASE_PASSWORD: ecsSecret.fromSecretsManager(props.database.secret, 'password'),
        DATABASE_USER_NAME: ecsSecret.fromSecretsManager(props.database.secret, 'username'),
      },
    })

    const apiService = new Ec2Service(this, 'ApiEc2Service', {
      cluster: props.cluster,
      taskDefinition: apiTask,
    })
  }
}

```

### Error Log

Full error:

```log
failed: Error [ValidationError]: Template error: instance of Fn::GetAtt references undefined resource ApiEc2TaskExecutionRole543F1BE9
    at Request.extractError (/node_modules/aws-cdk/node_modules/aws-sdk/lib/protocol/query.js:50:29)
    at Request.callListeners (/node_modules/aws-cdk/node_modules/aws-sdk/lib/sequential_executor.js:106:20)
    at Request.emit (/node_modules/aws-cdk/node_modules/aws-sdk/lib/sequential_executor.js:78:10)
    at Request.emit (/node_modules/aws-cdk/node_modules/aws-sdk/lib/request.js:683:14)
    at Request.transition (/node_modules/aws-cdk/node_modules/aws-sdk/lib/request.js:22:10)
    at AcceptorStateMachine.runTo (/node_modules/aws-cdk/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at /node_modules/aws-cdk/node_modules/aws-sdk/lib/state_machine.js:26:10
    at Request.<anonymous> (/node_modules/aws-cdk/node_modules/aws-sdk/lib/request.js:38:9)
    at Request.<anonymous> (/node_modules/aws-cdk/node_modules/aws-sdk/lib/request.js:685:12)
    at Request.callListeners (/node_modules/aws-cdk/node_modules/aws-sdk/lib/sequential_executor.js:116:18) {
  message: 'Template error: instance of Fn::GetAtt references undefined resource ApiEc2TaskExecutionRole543F1BE9',
  code: 'ValidationError',
  time: 2020-05-03T16:02:32.389Z,
  requestId: '6fd9d01e-d42e-4ac2-a9fd-bbb43b010473',
  statusCode: 400,
  retryable: false,
  retryDelay: 170.8336202583977
}
Template error: instance of Fn::GetAtt references undefined resource ApiEc2TaskExecutionRole543F1BE9
```
### Environment

  - **CLI Version      :** 1.36.1 (build 4df7dac)
  - **Framework Version:** ?
  - **OS               :** Mac 10.15.4 (19E287)
  - **Language         :** TypeScript

### Other

CDK CLI log:

```log
This deployment will make potentially sensitive changes according to your current security approval level (--require-approval broadening).
Please confirm you intend to make the following modifications:

IAM Statement Changes
┌───┬───────────────────────────┬────────┬─────────────┬────────────────────────────────────────────┬─────────────────────────────────────────────────────────────────────────────────────┐
│   │ Resource                  │ Effect │ Action      │ Principal                                  │ Condition                                                                           │
├───┼───────────────────────────┼────────┼─────────────┼────────────────────────────────────────────┼─────────────────────────────────────────────────────────────────────────────────────┤
│ + │ ${aaaaaaaaaaaaKmsKey.Arn} │ Allow  │ kms:Decrypt │ AWS:${ApiEc2TaskExecutionRole543F1BE9.Arn} │ "StringEquals": {                                                                   │
│   │                           │        │             │                                            │   "kms:ViaService": "secretsmanager.region.amazonaws.com"                   │
│   │                           │        │             │                                            │ }                                                                                   │
└───┴───────────────────────────┴────────┴─────────────┴────────────────────────────────────────────┴─────────────────────────────────────────────────────────────────────────────────────┘
(NOTE: There may be security-related changes not in this list. See https://github.com/aws/aws-cdk/issues/1299)

Do you wish to deploy these changes (y/n)? y

```

I have tried to manually add the task role and task execution role. The error persisted.

----------------------------------

The error will go away if I remove `secrets` settings in `task.addContainer`. Am I doing something wrong with the RDS secret? 

RDS secret was encrypted by my shared KMS key. I guess the error is caused by the  CDK tries to firstly grant access of that KMS key to the execution role before it creates the execution role.

----------------------------------

However, CDK still tries to add that conditional (`"kms:ViaService": "secretsmanager.region.amazonaws.com"`) IAM statement to the custom shared key, even when:

1. the key has already given `kms:Decrypt` to all `ServicePrincipal('ecs-tasks.amazonaws.com')`.
1. the key has set to `trustAccountIdentities: true`.
1. hardcoded execution role with:

```ts
    this.taskExecutionRole = new Role(this, 'TaskExecutionRole', {
      description: `EC2 ECS task execution IAM role with access to KMS key and Secrets`,
      assumedBy: new ServicePrincipal('ecs-tasks.amazonaws.com'),
      inlinePolicies: {
        secret: new PolicyDocument({
          statements: [
            new PolicyStatement({
              effect: Effect.ALLOW,
              resources: [
                props.key.keyArn,
                props.database.secret.secretArn,
              ],
              actions: [
                'kms:Decrypt',
                'secretsmanager:GetSecretValue',
              ],
            })
          ]
        })
      },
    })
```

Should the key not need that new IAM statement as it already has grant access to all `ServicePrincipal('ecs-tasks.amazonaws.com')`?

------------------

Also tried hardcode the KMS key to allow ALL principles with the exact condition

```ts
    this.key.addToResourcePolicy(
      new PolicyStatement({
        sid: 'Allow all ECS execution tasks to decrypt',
        effect: Effect.ALLOW,
        resources: ['*'],
        principals: [new AnyPrincipal],
        actions: ['kms:Decrypt'],
        conditions: {
          StringEquals: {
            "kms:ViaService": `secretsmanager.${props.env.region}.amazonaws.com`
          }
        },
      })
    )
```

It still tries to add the IAM statement to Key with the nonexisting execution role.

--------------------

This is :bug: Bug Report

**Comment by iamhopaul123** [comment]
Hey @ivawzh it seems like `grantRead` doesn't work as expected. Ideally it should get executed after the role's creation. Can you try using `taskDefinition.addToExecutionRolePolicy()` to see if you are able to add policies to the execution role?

**Comment by ivawzh** [comment]
@iamhopaul123 sorry, it's been a while and my repo had changed a lot since. I have lost the git commit at that time thus cannot reproduce the issue anymore. 

From memory, I have changed the approach to use the primitive account KMS key instead.
