### ISSUE TITLE
cdk synth fails after using `subprocess.Popen`

### ISSUE THREAD

**Issue by domtes** [aws/aws-cdk#7961]
If I use `subprocess.Popen` to run a subprocess that takes enough time (3 seconds), `cdk synth` process fails.

### Reproduction Steps

In the context of a stack which includes a Lambda function, this is the code I'm using:

```python
import os
import sys
import logging
import shutil
import subprocess
import zipfile

from typing import Dict, List, Union
from aws_cdk import aws_lambda as _lambda


class MissingPrerequisiteCommand(Exception):
    '''A required system command is missing'''


def execute_shell_command(command: Union[str, List[str]],
                          env: Union[Dict, None] = None) -> str:
    if isinstance(command, list):
        command = ' '.join(command)

    logging.debug(f'Executing command: {command}')

    completed_process = subprocess.run(command,
        env=env,
        shell=True,
        check=True,
        stdout=subprocess.PIPE,
        stderr=subprocess.PIPE)

    logging.debug(completed_process)
    return completed_process.stdout.strip().decode('utf-8')


def locate_command(command: str) -> str:
    path = execute_shell_command(['which', command])
    if path is None:
        raise MissingPrerequisiteCommand(f'Unable to find "{command}"')
    return path


def make_python_zip_bundle(input_path: str,
    python_version: str = '3.7',
    build_folder: str = '.build',
    requirements_file: str = 'requirements.txt',
    output_bundle_name: str = 'bundle.zip') -> _lambda.AssetCode:
    '''
    Builds a lambda AssetCode bundling python dependencies along with the code.
    The bundle is built using docker and the target lambda runtime image.
    '''

    docker = locate_command('docker')
    lambda_runtime_docker_image = f'lambci/lambda:build-python{python_version}'
    build_path = os.path.abspath(os.path.join(input_path, build_folder))

    # cleans the target folder
    logging.debug(f'Cleaning folder: {build_path}')
    shutil.rmtree(build_path, ignore_errors=True)

    # builds requirements using target runtime
    build_log = execute_shell_command(command=[
        'docker', 'run', '--rm',
        '-v', f'{input_path}:/app',
        '-w', '/app',
        lambda_runtime_docker_image,
            'pip', 'install',
            '-r', requirements_file,
            '-t', build_folder])

    logging.info(build_log)

    # creates the zip archive
    asset_path = os.path.join(build_path, output_bundle_name)

    logging.debug(f'Deleting file: {asset_path}')
    shutil.rmtree(asset_path, ignore_errors=True)

    logging.debug(f'Creating bundle: {asset_path}')
    with zipfile.ZipFile(asset_path, 'w', zipfile.ZIP_DEFLATED) as zip_obj:
        _add_folder_to_zip(zip_obj, input_path, ignore_file=output_bundle_name)
        _add_folder_to_zip(zip_obj, build_path, ignore_file=output_bundle_name, ignore_dotfiles=False)

    logging.info(f'Lambda bundle created at {asset_path}')

    # TODO: customize the source hash
    return _lambda.AssetCode.from_asset(asset_path)


def _add_folder_to_zip(zip_obj: zipfile.ZipFile, folder: str, ignore_file: str = None, ignore_dotfiles: bool = True):
    for folder_name, sub_folders, filenames in os.walk(folder):
        if ignore_dotfiles and folder_name.startswith('.'):
            continue

        if folder_name == folder:
            archive_folder_name = ''
        else:
            archive_folder_name = os.path.relpath(folder_name, folder)
            zip_obj.write(folder_name, arcname=archive_folder_name)

        for filename in filenames:
            if filename == ignore_file:
                continue
            f = os.path.join(folder_name, filename)
            d = os.path.join(archive_folder_name, filename)
            zip_obj.write(f, arcname=d)
```

I've also noticed that I can replace my *docker run* command with `sleep 3 && echo "Where is the timeout?"` to trigger the error.

If the subprocess takes *less then 3 seconds*, `cdk synth` succeeds.

### Error Log

```
INFO:root:Collecting requests==2.20.0
  Downloading requests-2.20.0-py2.py3-none-any.whl (60 kB)
Collecting certifi>=2017.4.17
  Downloading certifi-2020.4.5.1-py2.py3-none-any.whl (157 kB)
Collecting chardet<3.1.0,>=3.0.2
  Downloading chardet-3.0.4-py2.py3-none-any.whl (133 kB)
Collecting urllib3<1.25,>=1.21.1
  Downloading urllib3-1.24.3-py2.py3-none-any.whl (118 kB)
Collecting idna<2.8,>=2.5
  Downloading idna-2.7-py2.py3-none-any.whl (58 kB)
Installing collected packages: certifi, chardet, urllib3, idna, requests
Successfully installed certifi-2020.4.5.1 chardet-3.0.4 idna-2.7 requests-2.20.0 urllib3-1.24.3
DEBUG:root:Deleting file: /Users/domenico/dev/integrations_engine/integrations_engine/modules/inbound-endpoints/http_upload_handler/.build/bundle.zip
DEBUG:root:Creating bundle: /Users/domenico/dev/integrations_engine/integrations_engine/modules/inbound-endpoints/http_upload_handler/.build/bundle.zip
INFO:root:Lambda bundle created at /Users/domenico/dev/integrations_engine/integrations_engine/modules/inbound-endpoints/http_upload_handler/.build/bundle.zip
Traceback (most recent call last):
  File "app.py", line 13, in <module>
    IntegrationsEngineStack(app, "integrations-engine")
  File "/Users/domenico/dev/integrations_engine/.env/lib/python3.7/site-packages/jsii/_runtime.py", line 66, in __call__
    inst = super().__call__(*args, **kwargs)
  File "/Users/domenico/dev/integrations_engine/integrations_engine/integrations_engine_stack.py", line 180, in __init__
    export_queue=self.stateful_resources.export_queue_bucket)
  File "/Users/domenico/dev/integrations_engine/.env/lib/python3.7/site-packages/jsii/_runtime.py", line 66, in __call__
    inst = super().__call__(*args, **kwargs)
  File "/Users/domenico/dev/integrations_engine/integrations_engine/integrations_engine_stack.py", line 85, in __init__
    destination_bucket=import_queue)
  File "/Users/domenico/dev/integrations_engine/.env/lib/python3.7/site-packages/jsii/_runtime.py", line 66, in __call__
    inst = super().__call__(*args, **kwargs)
  File "/Users/domenico/dev/integrations_engine/integrations_engine/constructs/http.py", line 20, in __init__
    code=make_python_zip_bundle(handler_path),
  File "/Users/domenico/dev/integrations_engine/integrations_engine/utils/zip_asset_code.py", line 85, in make_python_zip_bundle
    return _lambda.AssetCode.from_asset(asset_path)
  File "/Users/domenico/dev/integrations_engine/.env/lib/python3.7/site-packages/aws_cdk/aws_lambda/__init__.py", line 3102, in from_asset
    return jsii.sinvoke(cls, "fromAsset", [path, options])
  File "/Users/domenico/dev/integrations_engine/.env/lib/python3.7/site-packages/jsii/_kernel/__init__.py", line 113, in wrapped
    return _recursize_dereference(kernel, fn(kernel, *args, **kwargs))
  File "/Users/domenico/dev/integrations_engine/.env/lib/python3.7/site-packages/jsii/_kernel/__init__.py", line 307, in sinvoke
    args=_make_reference_for_native(self, args),
  File "/Users/domenico/dev/integrations_engine/.env/lib/python3.7/site-packages/jsii/_kernel/providers/process.py", line 351, in sinvoke
    return self._process.send(request, InvokeResponse)
  File "/Users/domenico/dev/integrations_engine/.env/lib/python3.7/site-packages/jsii/_kernel/providers/process.py", line 307, in send
    self._process.stdin.flush()
BrokenPipeError: [Errno 32] Broken pipe
```

### Environment

  - **CLI Version      :** 1.38.0 (build d5fa31f)
  - **Framework Version:** 1.38.0 (build d5fa31f)
  - **OS               :** Darwin Kernel Version 19.4.0: Wed Mar  4 22:28:40 PST 2020; root:xnu-6153.101.6~15/RELEASE_X86_64
  - **Language         :** Python

### Other

--- 

This is :bug: Bug Report

**Comment by domtes** [comment]
Downgrading to **node 12** from **node 14** makes my code working as expected.
Can it possibly be dependent on the node version?

**Comment by shivlaks** [comment]
@domtes that's possible. what version of **node** were you using when you ran into this issue?

**Comment by domtes** [comment]
I was using  *v14.2.0* (npm v6.14.4) when I run into this issue.
Using *v12.16.3* (npm v6.14.4) doesn't show the problem.

**Comment by dvjn** [comment]
I am facing the same problem intermittently in node v16.19.0 (and npm v8.19.3). I'm tried using cdk v2.10.0 as well as v2.63.0

**Comment by jimmus69** [comment]
Likewise seeing same intermittent problem at node v16.20.2 and aws-cdk-lib==2.90.0.

`Traceback (most recent call last):
  File "app.py", line 13, in <module>
    app = cdk.App()
  File "/usr/local/lib/python3.7/site-packages/jsii/_runtime.py", line 112, in __call__
    inst = super().__call__(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/aws_cdk/__init__.py", line 26284, in __init__
    jsii.create(self.__class__, self, [props])
  File "/usr/local/lib/python3.7/site-packages/jsii/_kernel/__init__.py", line 341, in create
    for iface in getattr(klass, "__jsii_ifaces__", [])
  File "/usr/local/lib/python3.7/site-packages/jsii/_kernel/providers/process.py", line 363, in create
    return self._process.send(request, CreateResponse)
  File "/usr/local/lib/python3.7/site-packages/jsii/_kernel/providers/process.py", line 327, in send
    self._process.stdin.flush()
BrokenPipeError: [Errno 32] Broken pipe
Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/jsii/_kernel/providers/process.py", line 295, in stop
    self._process.stdin.close()
BrokenPipeError: [Errno 32] Broken pipe`
