### ISSUE TITLE
Spot worker nodes of EKS creation failed

### ISSUE THREAD

**Issue by yjw113080** [aws/aws-cdk#8004]
I provision EKS cluster with spot instances as worker nodes, and I played around it a lot of time--delete them and deploy them again...
It occasionally (approximately 1 out of 3 tries) failed to provision the cluster due to 1) i/o time out 2) no deployed release as described in the error log.
What is the root cause, and How would I prevent this happen?
Does this have anything to do with the network? I'm doing this test from Seoul, and everything seems okay when I do it in Tokyo region.

### Reproduction Steps

It happens 'time to time', 
```
    const cluster = new eks.Cluster(this, 'demogo-cluster', {
      clusterName: `demogo`,
      mastersRole: clusterAdmin,
      version: '1.14',
      defaultCapacity: 0
    });

    cluster.addNodegroup('default-group', {
      minSize: 2,
      maxSize: 4
    })

    cluster.addCapacity('spot-group', {
      instanceType: new ec2.InstanceType('m5.xlarge'),
      spotPrice: cdk.Stack.of(this).region==primaryRegion ? '0.248' : '0.192'
    });
```

### Error Log

1. No deployed releases
```
 52/60 | 오전 12:36:45 | CREATE_FAILED        | Custom::AWSCDK-EKS-HelmChart          | demogo-cluster/chart-spot-interrupt-handler/Resource/Default (demogoclusterchartspotinterrupthandler314D7675) Failed to create resource. Error: b'W0515 15:36:39.283238      13 transport.go:243] Unable to cancel request for *exec.roundTripper\nError: UPGRADE FAILED: "uswest2demogoclusterchartspotinterrupthandleraeb009ee" has no deployed releases\n'
    at invokeUserFunction (/var/task/framework.js:85:19)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

2. I/O Timeout
```
Unable to cancel request for *exec.roundTripper\nError: UPGRADE FAILED: query: failed to query with labels: Get https://A4DA6B7F63904C1C66C794F6CF51DACE.yl4.us-east-1.eks.amazonaws.com/api/v1/namespaces/kube-system/secrets?labelSelector=name%3Duseast1demogoclusterchartspotinterrupthandler7112aca7%2Cowner%3Dhelm%2Cstatus%3Ddeployed: dial tcp 3.215.171.233:443: i/o timeout\n'
    at invokeUserFunction (/var/task/framework.js:85:19)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```
### Environment

  - **CLI Version      :** 1.38.0 (build d5fa31f)
  - **Framework Version:** 1.38.0
  - **OS               :** MacOS Mojave 10.14.6(18G3020)
  - **Language         :**Typescript

### Other

--- 

This is :bug: Bug Report

**Comment by eladb** [comment]
@yjw113080 is this still an issue?

**Comment by eladb** [comment]
Closing in the meantime. Please open if relevant.
