### ISSUE TITLE
DynamoDB - Unable to create replication regions

### ISSUE THREAD

**Issue by gvhuyssteen** [aws/aws-cdk#8037]
When creating a DynamoDB table in `af-south-1`, I'm unable to create a replication into the `eu-west-1` region.  

An error shows in the terminal when running `cdk deploy` indicating that at least one of ProvisionedThroughput, BillingMode, UpdateStreamEnabled, GlobalSecondaryIndexUpdates or SSESpecification is required.

In the reproduction steps, I include billing mode, stream and encryption. Adding these properties should allow me to create the replication successfully as per error message.

### Reproduction Steps

```ts
#!/usr/bin/env node
import * as dynamodb from '@aws-cdk/aws-dynamodb';
import * as cdk from '@aws-cdk/core';

export class DynamoDbReplicationIssueStack extends cdk.Stack {
  constructor(scope: cdk.Construct, id: string, props?: cdk.StackProps) {
    super(scope, id, props);
    
    new dynamodb.Table(this, 'table', {
      partitionKey: { name: 'pk', type: dynamodb.AttributeType.STRING },
      sortKey: { name: 'sk', type: dynamodb.AttributeType.STRING },
      billingMode: dynamodb.BillingMode.PAY_PER_REQUEST,
      removalPolicy: cdk.RemovalPolicy.DESTROY,
      pointInTimeRecovery: true,
      replicationRegions: ['eu-west-1'],
      stream: dynamodb.StreamViewType.NEW_AND_OLD_IMAGES,
      encryption: dynamodb.TableEncryption.AWS_MANAGED
    });
    
  }
}

const app = new cdk.App();
new DynamoDbReplicationIssueStack(app, 'DynamoDbReplicationIssueStack', {env: {region: 'af-south-1'}});

```

### Error Log

```
 2/4 | 9:30:26 PM 
     | CREATE_IN_PROGRESS   
     | Custom::DynamoDBReplica
     | table/Replicaeu-west-1/Default (tableReplicaeuwest1C8F484DF)
 2/4 | 9:30:31 PM
     | CREATE_IN_PROGRESS
     | Custom::DynamoDBReplica
     | table/Replicaeu-west-1/Default (tableReplicaeuwest1C8F484DF)
       Resource creation Initiated
 3/4 | 9:30:31 PM
     | CREATE_FAILED
     | Custom::DynamoDBReplica
     | table/Replicaeu-west-1/Default (tableReplicaeuwest1C8F484DF)

Failed to create resource.
Error: At least one of ProvisionedThroughput, BillingMode, UpdateStreamEnabled, GlobalSecondaryIndexUpdates or SSESpecification is required
    at invokeUserFunction (/var/task/framework.js:85:19)
    at process._tickCallback (internal/process/next_tick.js:68:7)                            

Remote function error:
ValidationException: At least one of ProvisionedThroughput, BillingMode, UpdateStreamEnabled, GlobalSecondaryIndexUpdates or SSESpecification is required
    at Request.extractError (/var/runtime/node_modules/aws-sdk/lib/protocol/json.js:51:27)
    at Request.callListeners (/var/runtime/node_modules/aws-sdk/lib/sequential_executor.js:106:20)
    at Request.emit (/var/runtime/node_modules/aws-sdk/lib/sequential_executor.js:78:10)
    at Request.emit (/var/runtime/node_modules/aws-sdk/lib/request.js:683:14)
    at Request.transition (/var/runtime/node_modules/aws-sdk/lib/request.js:22:10)
    at AcceptorStateMachine.runTo (/var/runtime/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at /var/runtime/
```

### Environment

  - **CLI Version: 1.39.0 (build 5d727c1)**
  - **OS : macOS Catalina 10.15.4**
  - **Language : Typescript**

### Other

A link to the documentation on using global tables by only adding the replicationRegions property and specifying the regions:
[Amazon DynamoDB Global Types](https://www.npmjs.com/package/@aws-cdk/aws-dynamodb#amazon-dynamodb-global-tables)

--- 

This is :bug: Bug Report

**Comment by RomainMuller** [comment]
Could this be because DynamoDB Global Tables isn't available in `af-south-1`?

**Comment by gvhuyssteen** [comment]
Now I understand.  Thank you!
The error message tripped me up and did not think of looking up availability.
