### ISSUE TITLE
Unable to synthesize when calling `grantInvoke(ServicePrincipal.Builder.create("events.amazonaws.com")`

### ISSUE THREAD

**Issue by john-tipper** [aws/aws-cdk#8240]
There appears to have been a breaking change between 1.38.0 and 1.39.0 for which I cannot find documentation and which continues in recent versions. 

I attempt to grant permission to `events.amazonaws.com` to trigger my lambda, using the code below:

    myLambda.grantInvoke(ServicePrincipal.Builder.create("events.amazonaws.com")

When I attempt to synthesize the stack, I get an exception with the message:

    No child with id: 'InvokeServicePrincipal(events.amazonaws.com)'

### Reproduction Steps

I create a lambda using:

    SingletonFunction.create(...)

then attempt to grant permissions to the `events` AWS service principal:

    myLambda.grantInvoke(ServicePrincipal.Builder.create("events.amazonaws.com")

### Error Log

```
Exception in thread "main" software.amazon.jsii.JsiiException: No child with id: 'InvokeServicePrincipal(events.amazonaws.com)'
Error: No child with id: 'InvokeServicePrincipal(events.amazonaws.com)'
    at Node.findChild (C:\Users\JOHN~1.TIP\AppData\Local\Temp\jsii-kernel-38y7OI\node_modules\constructs\lib\construct.js:86:19)
    at ConstructNode.findChild (C:\Users\JOHN~1.TIP\AppData\Local\Temp\jsii-kernel-38y7OI\node_modules\@aws-cdk\core\lib\construct-compat.js:235:45)
    at Object.addToResourcePolicy (C:\Users\JOHN~1.TIP\AppData\Local\Temp\jsii-kernel-38y7OI\node_modules\@aws-cdk\aws-lambda\lib\function-base.js:89:80)
    at Function.addToPrincipalOrResource (C:\Users\JOHN~1.TIP\AppData\Local\Temp\jsii-kernel-38y7OI\node_modules\@aws-cdk\aws-iam\lib\grant.js:50:49)
    at SingletonFunction.grantInvoke (C:\Users\JOHN~1.TIP\AppData\Local\Temp\jsii-kernel-38y7OI\node_modules\@aws-cdk\aws-lambda\lib\function-base.js:75:26)
    at C:\Users\JOHN~1.TIP\AppData\Local\Temp\jsii-java-runtime10095079647419115433\jsii-runtime.js:7680:51
    at Kernel._wrapSandboxCode (C:\Users\JOHN~1.TIP\AppData\Local\Temp\jsii-java-runtime10095079647419115433\jsii-runtime.js:8316:19)
    at C:\Users\JOHN~1.TIP\AppData\Local\Temp\jsii-java-runtime10095079647419115433\jsii-runtime.js:7680:25
    at Kernel._ensureSync (C:\Users\JOHN~1.TIP\AppData\Local\Temp\jsii-java-runtime10095079647419115433\jsii-runtime.js:8289:20)
    at Kernel.invoke (C:\Users\JOHN~1.TIP\AppData\Local\Temp\jsii-java-runtime10095079647419115433\jsii-runtime.js:7679:26)
    at KernelHost.processRequest (C:\Users\JOHN~1.TIP\AppData\Local\Temp\jsii-java-runtime10095079647419115433\jsii-runtime.js:7388:28)
    at KernelHost.run (C:\Users\JOHN~1.TIP\AppData\Local\Temp\jsii-java-runtime10095079647419115433\jsii-runtime.js:7328:14)
    at Immediate._onImmediate (C:\Users\JOHN~1.TIP\AppData\Local\Temp\jsii-java-runtime10095079647419115433\jsii-runtime.js:7331:37)
    at processImmediate (internal/timers.js:456:21)
        at software.amazon.jsii.JsiiRuntime.processErrorResponse(JsiiRuntime.java:119)
        at software.amazon.jsii.JsiiRuntime.requestResponse(JsiiRuntime.java:91)
        at software.amazon.jsii.JsiiClient.callMethod(JsiiClient.java:183)
        at software.amazon.jsii.JsiiObject.jsiiCall(JsiiObject.java:120)
        at software.amazon.jsii.JsiiObject.jsiiCall(JsiiObject.java:106)
        at software.amazon.awscdk.services.lambda.FunctionBase.grantInvoke(FunctionBase.java:114)
        at com.example.MyStack.<init>(MyStack.java:325)
```

### Environment

  - **CLI Version      :  1.42.0**
  - **Framework Version: 1.39.0**
  - **OS               : Windows**
  - **Language         : Java**

### Other

There is no exception when using 1.38.0, but this issue appears to affect all subsequent versions, including 1.42.0.

--- 

This is :bug: Bug Report

**Comment by nija-at** [comment]
There was no breaking change intended for this module on those releases. `@aws-cdk/aws-lambda` is a stable module; we will not release breaking changes on minor version releases.

I was able to reproduce this with a simple typescript app - 

```ts
import { ServicePrincipal } from '@aws-cdk/aws-iam';
import { Code, Runtime, SingletonFunction } from '@aws-cdk/aws-lambda';
import { App, Stack } from '@aws-cdk/core';

const app = new App();
const stack = new Stack(app, 'mystack');

const fn = new SingletonFunction(stack, 'fn', {
  code: Code.fromInline('foo'),
  runtime: Runtime.NODEJS_12_X,
  handler: 'index.handler',
  uuid: '92e0bbf2-10d2-427c-9f79-79f671303428',
});

fn.grantInvoke(new ServicePrincipal('events.amazonaws.com'));
```

This is a bug.

**Comment by nija-at** [comment]
We're tracking this bug here - https://github.com/aws/aws-cdk/issues/8295
