### ISSUE TITLE
Error when using ssm parameter for congnitoprefix>domainprefix

### ISSUE THREAD

**Issue by jasonwu890105** [aws/aws-cdk#8314]
```ts
userPool: userPool,
  cognitoDomain: {
    domainPrefix: `${cfSubDomain}-test`}
});
```

Where `cfSubDomain` value is:

```ts
const cfSubDomain = ssm.StringParameter.valueForStringParameter(
       this,
       '/test-app/cfSubDomain'
   );
```

Supposedly, in Cognito domain, the ${cfSubDomain} should be substituted by the value of cfSubDomain from SSM. 
When CDK prints cfSubDomain, I got ${Token[TOKEN.1223]}, normally ${Token[TOKEN.1223]} is only used during synth time, these actually get filled in  with the correct value.
That normally works for other services, but not for Cognito this time. As the error saying " throw new Error('domainPrefix for cognitoDomain can contain only lowercase alphabets, numbers and hyphens'); "

===== Error Trace =====
```
error:
      throw new Error('domainPrefix for cognitoDomain can contain only lowercase alphabets, numbers and hyphens');
            ^
Error: domainPrefix for cognitoDomain can contain only lowercase alphabets, numbers and hyphens
    at new UserPoolDomain (D:\Users\mspitz\works\fix\ass\infra-kyc-pipeline\node_modules\@aws-cdk\aws-cognito\lib\user-pool-domain.ts:92:13)
    at new KycCognito (D:\Users\mspitz\works\fix\ass\infra-kyc-pipeline\lib\cognito\cognito-stack.ts:90:20)
    at Object.<anonymous> (D:\Users\mspitz\works\fix\ass\infra-kyc-pipeline\bin\kyc.ts:98:17)
    at Module._compile (internal/modules/cjs/loader.js:1176:30)
    at Module.m._compile (D:\Users\mspitz\works\fix\ass\infra-kyc-pipeline\node_modules\ts-node\src\index.ts:858:23)
    at Module._extensions..js (internal/modules/cjs/loader.js:1196:10)
    at Object.require.extensions.<computed> [as .ts] (D:\Users\mspitz\works\fix\ass\infra-kyc-pipeline\node_modules\ts-node\src\index.ts:861:12)
    at Module.load (internal/modules/cjs/loader.js:1040:32)
    at Function.Module._load (internal/modules/cjs/loader.js:929:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)
Subprocess exited with error 1
Error: Subprocess exited with error 1
    at ChildProcess.<anonymous> (D:\Users\mspitz\AppData\Roaming\npm\node_modules\aws-cdk\lib\api\cxapp\exec.ts:118:23)
```

### Environment
  - **Language**: TypeScript
 - **OS**: Windows
--- 

This is :bug: Bug Report

**Comment by MrArnoldPalmer** [comment]
@nija-at Is this an issue with cognito not being token aware?
