### ISSUE TITLE
Jsii maximum call stacksize excedeed on Ubuntu 20.04 when using boto3 and cdk

### ISSUE THREAD

**Issue by cadubentzen** [aws/aws-cdk#8397]
When running some boto3 commands before calling `core.App()` in a cdk project, jsii-runtime.js breaks with `RangeError: Maximum call stack size exceeded`

### Reproduction Steps

```python
import boto3
from aws_cdk import core
import time


class SimplestBreakageStack(core.Stack):
    def __init__(self, scope: core.Construct, id: str, **kwargs) -> None:
        super().__init__(scope, id, **kwargs)


sts = boto3.client('sts')
response = sts.get_caller_identity()
time.sleep(5)

app = core.App()
SimplestBreakageStack(app, "simplest-breakage")

app.synth()
```
and `cdk synth`

### Error Log

```
/home/bentzen/examples/simplest-breakage/.env/lib/python3.8/site-packages/jsii/_embedded/jsii/jsii-runtime.js:13582
                throw e;
                ^

RangeError: Maximum call stack size exceeded
    at new Uint8Array (<anonymous>)
    at new FastBuffer (internal/buffer.js:945:1)
    at Function.alloc (buffer.js:376:10)
    at SyncStdio.readLine (/home/bentzen/examples/simplest-breakage/.env/lib/python3.8/site-packages/jsii/_embedded/jsii/jsii-runtime.js:13558:33)
    at SyncStdio.readLine (/home/bentzen/examples/simplest-breakage/.env/lib/python3.8/site-packages/jsii/_embedded/jsii/jsii-runtime.js:13587:25)
    at SyncStdio.readLine (/home/bentzen/examples/simplest-breakage/.env/lib/python3.8/site-packages/jsii/_embedded/jsii/jsii-runtime.js:13587:25)
    at SyncStdio.readLine (/home/bentzen/examples/simplest-breakage/.env/lib/python3.8/site-packages/jsii/_embedded/jsii/jsii-runtime.js:13587:25)
    at SyncStdio.readLine (/home/bentzen/examples/simplest-breakage/.env/lib/python3.8/site-packages/jsii/_embedded/jsii/jsii-runtime.js:13587:25)
    at SyncStdio.readLine (/home/bentzen/examples/simplest-breakage/.env/lib/python3.8/site-packages/jsii/_embedded/jsii/jsii-runtime.js:13587:25)
    at SyncStdio.readLine (/home/bentzen/examples/simplest-breakage/.env/lib/python3.8/site-packages/jsii/_embedded/jsii/jsii-runtime.js:13587:25)
Traceback (most recent call last):
  File "app.py", line 17, in <module>
    app = core.App()
  File "/home/bentzen/examples/simplest-breakage/.env/lib/python3.8/site-packages/jsii/_runtime.py", line 66, in __call__
    inst = super().__call__(*args, **kwargs)
  File "/home/bentzen/examples/simplest-breakage/.env/lib/python3.8/site-packages/aws_cdk/core/__init__.py", line 8844, in __init__
    jsii.create(App, self, [props])
  File "/home/bentzen/examples/simplest-breakage/.env/lib/python3.8/site-packages/jsii/_kernel/__init__.py", line 224, in create
    response = self.provider.create(
  File "/home/bentzen/examples/simplest-breakage/.env/lib/python3.8/site-packages/jsii/_kernel/providers/process.py", line 333, in create
    return self._process.send(request, CreateResponse)
  File "/home/bentzen/examples/simplest-breakage/.env/lib/python3.8/site-packages/jsii/_kernel/providers/process.py", line 307, in send
    self._process.stdin.flush()
BrokenPipeError: [Errno 32] Broken pipe
Subprocess exited with error 1

```

### Environment

  - **CLI Version      :** aws-cli/1.18.66 Python/3.8.2 Linux/5.4.0-33-generic botocore/1.16.16
  - **Framework Version:**  aws-cdk == 1.44.0 and boto3 == 1.13.23
  - **Node.js Version:**  v12.18.0
  - **OS               :** Ubuntu 20.04
  - **Language (Version):**  Python 3.8.3

### Other

Downgrading to Node v10.21.0, I'm not able to reproduce the issue anymore.

**EDIT: after testing some versions, it seems to start breaking at Node v12.17.0. Until v12.16.3 it works fine**

--- 

This is :bug: Bug Report

**Comment by MrArnoldPalmer** [comment]
This should be solved by https://github.com/aws/jsii/pull/1717.
