### ISSUE TITLE
Asset Staging May Generate Invalid File Names

### ISSUE THREAD

**Issue by dbcfd** [aws/aws-cdk#8513]
Asset staging may generate file names with invalid characters, such as `/` which prevents files from being copied.

```
Error: ENOENT: no such file or directory, copyfile <original path>' -> 'cdk.out/asset.Rff/92n++DZ5lndYHxX4BQ==.zip'
    at Object.copyFileSync (fs.js:1912:3)
    at AssetStaging.synthesize (<somewhere>/node_modules/@aws-cdk/core/lib/asset-staging.ts:129:10)
    at AssetStaging.onSynthesize (<somewhere>/node_modules/@aws-cdk/core/lib/construct-compat.ts:123:10)
    at <somewhere>/node_modules/@aws-cdk/core/lib/private/synthesis.ts:98:46
    at visit (<somewhere>/node_modules/@aws-cdk/core/lib/private/synthesis.ts:136:5)
    at visit (<somewhere>/node_modules/@aws-cdk/core/lib/private/synthesis.ts:132:5)
    at visit (<somewhere>/node_modules/@aws-cdk/core/lib/private/synthesis.ts:132:5)
    at visit (<somewhere>/node_modules/@aws-cdk/core/lib/private/synthesis.ts:132:5)
    at synthesizeTree (<somewhere>/node_modules/@aws-cdk/core/lib/private/synthesis.ts:98:3)
    at Object.synthesize (<somewhere>/node_modules/@aws-cdk/core/lib/private/synthesis.ts:32:3)
```

Cdk 1.45

--- 

This is :bug: Bug Report

**Comment by jogold** [comment]
Are you providing a custom hash? Can you share a repro?

**Comment by dbcfd** [comment]
I do have a custom hash. I can sanitize that hash, but given that it's specified as a hash and not a staging filename, seems like the cdk should sanitize the hash for use as a file name.

**Comment by jogold** [comment]
Can you output your hash as `hex` instead of `base64`?

Agree that this should be correctly caught by CDK.
