### ISSUE TITLE
AWS::CloudFormation::Stack

### ISSUE THREAD

**Issue by anilvrathod1** [aws/aws-cdk#8671]
I have below code, 
```
 #!/usr/bin/env python3
from aws_cdk import core
from aws_cdk.core import App, Construct, Stack

from cdk_project.my_network_stack import NetworkStack as mynetworkstack
from cdk_project.my_security_stack import SecurityStack as mysecuritystack
from cdk_project.my_ec2_stack import EC2Stack as myec2stack
env_APJ = core.Environment(account="042xxxxxx31", region="ap-south-1")
env_USA = core.Environment(account="042xxxxxx31", region="us-west-2")
name_of_vpc="anil-IN"
var_az = "ap-south-1a"
varcidr = "10.55"

app = core.App()
mynetworkstack(app, 'anil-aws', varcidr, var_az, name_of_vpc, env=env_APJ)
mysecuritystack(app, 'anil-mysecurity', varcidr, name_of_vpc, env=env_APJ)
myec2stack(app, 'anil-myec2')
app.synth()
```
I am able to create the VPC, but I want to create another VPC in same region by changing the name of VPC to `name_of_vpc="anil-IN-PROD"` then I am getting below error:

```
PS C:\Users\arathod\anil-aws-cdk\cdk-project> cdk deploy anil-aws anil-mysecurity
anil-aws
anil-aws: deploying...
anil-aws: creating CloudFormation changeset...
  0/47 | 12:07:51 AM | UPDATE_ROLLBACK_IN_P | AWS::CloudFormation::Stack            | anil-aws Export anil-IN cannot be deleted as it is in use by anil-mysecurity
  0/47 | 12:08:21 AM | UPDATE_ROLLBACK_COMP | AWS::CloudFormation::Stack            | anil-aws 

 ❌  anil-aws failed: Error: The stack named anil-aws is in a failed state: UPDATE_ROLLBACK_COMPLETE
    at Object.waitForStack (C:\Users\arathod\AppData\Roaming\npm\node_modules\aws-cdk\lib\api\util\cloudformation.ts:251:11)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at Object.deployStack (C:\Users\arathod\AppData\Roaming\npm\node_modules\aws-cdk\lib\api\deploy-stack.ts:265:26)
    at CdkToolkit.deploy (C:\Users\arathod\AppData\Roaming\npm\node_modules\aws-cdk\lib\cdk-toolkit.ts:181:24)
    at main (C:\Users\arathod\AppData\Roaming\npm\node_modules\aws-cdk\bin\cdk.ts:252:16)
    at initCommandLine (C:\Users\arathod\AppData\Roaming\npm\node_modules\aws-cdk\bin\cdk.ts:184:9)
The stack named anil-aws is in a failed state: UPDATE_ROLLBACK_COMPLETE
```

**Comment by anilvrathod1** [comment]
modified issue statements

**Comment by rix0rrr** [comment]
We're happy to help you out, but GitHub issues is not a support forum. There are websites much better suited for that, such as StackOverflow.

Please ask that same question again on [StackOverflow under the aws-cdk](https://stackoverflow.com/questions/ask?tags=aws-cdk) tag. If you can't get a response to your question, please bring it to our attention again and we will do our best to answer it.
