### ISSUE TITLE
[cli] CDK Bootstrap not working as expected

### ISSUE THREAD

**Issue by jarjis** [aws/aws-cdk#8818]
**cdk bootstrap aws://[Account]/[us-east-2] is not working as expected.** 
``` console
 ❌  Environment aws://[Account]/us-east-2 failed bootstrapping: TypeError: Cannot read property 'AWS_CLOUDFORMATION_STACK' of undefined
    at Object.bootstrapEnvironment (/usr/local/lib/node_modules/aws-cdk/lib/api/bootstrap-environment.ts:78:30)
    at /usr/local/lib/node_modules/aws-cdk/bin/cdk.ts:260:24
    at async Promise.all (index 0)
    at cliBootstrap (/usr/local/lib/node_modules/aws-cdk/bin/cdk.ts:257:5)
    at main (/usr/local/lib/node_modules/aws-cdk/bin/cdk.ts:187:16)
    at initCommandLine (/usr/local/lib/node_modules/aws-cdk/bin/cdk.ts:148:9)
Cannot read property 'AWS_CLOUDFORMATION_STACK' of undefined
```
I didn't see a related issue for this. Did anyone else face this issue ?

### Environment

  - **CDK CLI Version:** 1.7.0 (build 8870695)
  - **Module Version:**
  - **Node.js Version:** v14.4.0
  - **OS:**  MacOS
  - **Language (Version):** 
``` json
{
  "name": "cdk",
  "version": "0.1.0",
  "bin": {
    "cdk": "bin/cdk.js"
  },
  "scripts": {
    "build": "tsc",
    "watch": "tsc -w",
    "cdk": "cdk"
  },
  "devDependencies": {
    "aws-cdk": "^1.9.0",
    "ts-node": "^8.1.0",
    "typescript": "~3.6.2"
  },
  "dependencies": {
    "@aws-cdk/aws-lambda": "^1.47.1",
    "@aws-cdk/core": "^1.7.0",
    "source-map-support": "^0.5.9"
  }
}
```

**Comment by shivlaks** [comment]
@jarjis - can you share the bootstrap command you ran (please redact as needed). It might be helpful to run the command with the `-v` flag to grab the verbose output.

**Comment by rix0rrr** [comment]
Closed for no response.

**Comment by austindimmer** [comment]
I have been running this for a few days in a GitHub Actions build as follows. Yesterday I started to observe a similar issue to the one reported.

My Github action looks like

 - name: CDK - Bootstrap
        run: |
          cdk bootstrap
          # cdk bootstrap aws://${{ env.AWS_ACCOUNT_ID }}/${{ env.AWS_DEFAULT_REGION }} 

I have been observing the following error I am using CDK 1.60.0

 CDK - Bootstrap15s
##[error]Process completed with exit code 1.
Run # bootstraps default account/region
 ⏳  Bootstrapping environment aws://***/***...
 ❌  Environment aws://***/*** failed bootstrapping: TypeError: Cannot read property 'AWS_CLOUDFORMATION_STACK' of undefined
    at Object.bootstrapEnvironment (/opt/hostedtoolcache/node/12.18.3/x64/lib/node_modules/aws-cdk/lib/api/bootstrap-environment.ts:78:30)
    at /opt/hostedtoolcache/node/12.18.3/x64/lib/node_modules/aws-cdk/bin/cdk.ts:260:24
    at async Promise.all (index 0)
    at cliBootstrap (/opt/hostedtoolcache/node/12.18.3/x64/lib/node_modules/aws-cdk/bin/cdk.ts:257:5)
    at main (/opt/hostedtoolcache/node/12.18.3/x64/lib/node_modules/aws-cdk/bin/cdk.ts:187:16)
    at initCommandLine (/opt/hostedtoolcache/node/12.18.3/x64/lib/node_modules/aws-cdk/bin/cdk.ts:148:9)
Cannot read property 'AWS_CLOUDFORMATION_STACK' of undefined
##[error]Process completed with exit code 1.

When I run with the -v option I observe 

 CDK - Bootstrap14s
##[error]Process completed with exit code 1.
  'aws:cdk:enable-asset-metadata': true
}
outdir: cdk.out
env: {
  CDK_DEFAULT_REGION: '***',
  CDK_DEFAULT_ACCOUNT: '***',
  CDK_CONTEXT_JSON: '{"availability-zones:account=***:region=***":["***a","***b","***c"],"aws:cdk:enable-path-metadata":true,"aws:cdk:enable-asset-metadata":true}',
  CDK_OUTDIR: 'cdk.out'
}
EACCES: permission denied, open 'cdk.out/tree.json'
Error: EACCES: permission denied, open 'cdk.out/tree.json'
    at Object.openSync (fs.js:462:3)
    at Object.writeFileSync (fs.js:1362:35)
    at TreeMetadata._synthesizeTree (/home/runner/work/S2.CSIRC.Core/S2.CSIRC.Core/node_modules/@aws-cdk/core/lib/private/tree-metadata.ts:62:8)
    at /home/runner/work/S2.CSIRC.Core/S2.CSIRC.Core/node_modules/@aws-cdk/core/lib/private/synthesis.ts:128:17
    at visit (/home/runner/work/S2.CSIRC.Core/S2.CSIRC.Core/node_modules/@aws-cdk/core/lib/private/synthesis.ts:169:5)
    at visit (/home/runner/work/S2.CSIRC.Core/S2.CSIRC.Core/node_modules/@aws-cdk/core/lib/private/synthesis.ts:165:5)
    at synthesizeTree (/home/runner/work/S2.CSIRC.Core/S2.CSIRC.Core/node_modules/@aws-cdk/core/lib/private/synthesis.ts:119:3)
    at Object.synthesize (/home/runner/work/S2.CSIRC.Core/S2.CSIRC.Core/node_modules/@aws-cdk/core/lib/private/synthesis.ts:36:3)
    at App.synth (/home/runner/work/S2.CSIRC.Core/S2.CSIRC.Core/node_modules/@aws-cdk/core/lib/stage.ts:175:23)
    at process.<anonymous> (/home/runner/work/S2.CSIRC.Core/S2.CSIRC.Core/node_modules/@aws-cdk/core/lib/app.ts:112:45)
Subprocess exited with error 1
Error: Subprocess exited with error 1
    at ChildProcess.<anonymous> (/opt/hostedtoolcache/node/12.18.3/x64/lib/node_modules/aws-cdk/lib/api/cxapp/exec.ts:110:23)
    at ChildProcess.emit (events.js:315:20)
    at ChildProcess.EventEmitter.emit (domain.js:483:12)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12)
##[error]Process completed with exit code 1.

I am not sure what is going wrong since this worked for a few days before breaking.

I tried to delete the resources the initial cdk bootstrap command created but it made no difference.

I was only able to run cdk bootstrap from my local machine.

I have disabled the build step for now in my Github Actions CI

**Comment by austindimmer** [comment]
I have been running this for a few days in a GitHub Actions build as follows. Yesterday I started to observe a similar issue to the one reported.

My Github action looks like

    name: CDK - Bootstrap
    run: |
    cdk bootstrap
    # cdk bootstrap aws://${{ env.AWS_ACCOUNT_ID }}/${{ env.AWS_DEFAULT_REGION }}

I have been observing the following error I am using CDK 1.60.0

CDK - Bootstrap15s
##[error]Process completed with exit code 1.
Run # bootstraps default account/region
? Bootstrapping environment aws:///...
? Environment aws:/// failed bootstrapping: TypeError: Cannot read property 'AWS_CLOUDFORMATION_STACK' of undefined
at Object.bootstrapEnvironment (/opt/hostedtoolcache/node/12.18.3/x64/lib/node_modules/aws-cdk/lib/api/bootstrap-environment.ts:78:30)
at /opt/hostedtoolcache/node/12.18.3/x64/lib/node_modules/aws-cdk/bin/cdk.ts:260:24
at async Promise.all (index 0)
at cliBootstrap (/opt/hostedtoolcache/node/12.18.3/x64/lib/node_modules/aws-cdk/bin/cdk.ts:257:5)
at main (/opt/hostedtoolcache/node/12.18.3/x64/lib/node_modules/aws-cdk/bin/cdk.ts:187:16)
at initCommandLine (/opt/hostedtoolcache/node/12.18.3/x64/lib/node_modules/aws-cdk/bin/cdk.ts:148:9)
Cannot read property 'AWS_CLOUDFORMATION_STACK' of undefined
##[error]Process completed with exit code 1.

When I run with the -v option I observe

CDK - Bootstrap14s
##[error]Process completed with exit code 1.
'aws:cdk:enable-asset-metadata': true
}
outdir: cdk.out
env: {
CDK_DEFAULT_REGION: '',
CDK_DEFAULT_ACCOUNT: '',
CDK_CONTEXT_JSON: '{"availability-zones:account=:region=":["***a","***b","***c"],"aws:cdk:enable-path-metadata":true,"aws:cdk:enable-asset-metadata":true}',
CDK_OUTDIR: 'cdk.out'
}
EACCES: permission denied, open 'cdk.out/tree.json'
Error: EACCES: permission denied, open 'cdk.out/tree.json'
at Object.openSync (fs.js:462:3)
at Object.writeFileSync (fs.js:1362:35)
at TreeMetadata._synthesizeTree (/home/runner/work/XXXXXXX/XXXXXXX/node_modules/@aws-cdk/core/lib/private/tree-metadata.ts:62:8)
at /home/runner/work/XXXXXXX/XXXXXXX/node_modules/@aws-cdk/core/lib/private/synthesis.ts:128:17
at visit (/home/runner/work/XXXXXXX/XXXXXXX/node_modules/@aws-cdk/core/lib/private/synthesis.ts:169:5)
at visit (/home/runner/work/XXXXXXX/XXXXXXX/node_modules/@aws-cdk/core/lib/private/synthesis.ts:165:5)
at synthesizeTree (/home/runner/work/XXXXXXX/XXXXXXX/node_modules/@aws-cdk/core/lib/private/synthesis.ts:119:3)
at Object.synthesize (/home/runner/work/XXXXXXX/XXXXXXX/node_modules/@aws-cdk/core/lib/private/synthesis.ts:36:3)
at App.synth (/home/runner/work/XXXXXXX/XXXXXXX/node_modules/@aws-cdk/core/lib/stage.ts:175:23)
at process. (/home/runner/work/XXXXXXX/XXXXXXX/node_modules/@aws-cdk/core/lib/app.ts:112:45)
Subprocess exited with error 1
Error: Subprocess exited with error 1
at ChildProcess. (/opt/hostedtoolcache/node/12.18.3/x64/lib/node_modules/aws-cdk/lib/api/cxapp/exec.ts:110:23)
at ChildProcess.emit (events.js:315:20)
at ChildProcess.EventEmitter.emit (domain.js:483:12)
at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12)
##[error]Process completed with exit code 1.

I am not sure what is going wrong since this worked for a few days before breaking.

I tried to delete the resources the initial cdk bootstrap command created but it made no difference.

I was only able to run cdk bootstrap from my local machine.

I have disabled the build step for now in my Github Actions CI

**Comment by stepin105597** [comment]
I'm facing a similar issue

throw err;
    ^

Error: EACCES: permission denied, open 'cdk.out/tree.json'
    at Object.openSync (fs.js:497:3)
    at Object.writeFileSync (fs.js:1528:35)
    at TreeMetadata.synthesize (/home/cloudshell-user/aws-lambda-sap-odp-extractor/node_modules/@aws-cdk/core/lib/private/tree-metadata.js:50:12)
    at TreeMetadata.onSynthesize (/home/cloudshell-user/aws-lambda-sap-odp-extractor/node_modules/@aws-cdk/core/lib/construct-compat.js:82:14)
    at Node.synthesize (/home/cloudshell-user/aws-lambda-sap-odp-extractor/node_modules/constructs/lib/construct.js:342:27)
    at Function.synth (/home/cloudshell-user/aws-lambda-sap-odp-extractor/node_modules/@aws-cdk/core/lib/construct-compat.js:170:26)
    at App.synth (/home/cloudshell-user/aws-lambda-sap-odp-extractor/node_modules/@aws-cdk/core/lib/app.js:72:59)
    at process.<anonymous> (/home/cloudshell-user/aws-lambda-sap-odp-extractor/node_modules/@aws-cdk/core/lib/app.js:46:51)
    at Object.onceWrapper (events.js:520:26)
    at process.emit (events.js:400:28) {
  errno: -13,
  syscall: 'open',
  code: 'EACCES',
  path: 'cdk.out/tree.json'
}
Subprocess exited with error 1
