### ISSUE TITLE
[kinesisfirehose] Error using Python CDK for Kinesis Steam to Firehose and the S3 bucket

### ISSUE THREAD

**Issue by w601sxs** [aws/aws-cdk#8881]
### The Question

Trying to do this:

`
        S3_dest_config= {
            "bucketArn": ingest_bucket.bucket_arn,
            "bufferingHints": {
              "intervalInSeconds": 60,
              "sizeInMBs": 128
            },
            "roleArn": kRole.role_arn,
            "prefix": 'raw-data/',
            "compressionFormat": 'UNCOMPRESSED',
            "s3BackupMode": 'Disabled'
        }
        
        
        Kinesis_config = {
            "KinesisStreamARN" : kinesis_stream.stream_arn,
            "RoleARN" : kRole.role_arn}
        
        kfirehose = firehose.CfnDeliveryStream(self,
                            'kfirehose',
                            delivery_stream_name='deliverystream',
                            delivery_stream_type='KinesisStreamAsSource',
                            extended_s3_destination_configuration = S3_dest_config,
                            kinesis_stream_source_configuration = Kinesis_config)
`

Fails with 

`jsii.errors.JavaScriptError: 
  Error: Value did not match any type in union: Got an array where a @aws-cdk/aws-kinesisfirehose.CfnDeliveryStream.KinesisStreamSourceConfigurationProperty was expected. Did you mean to pass a variable number of arguments?,Expected object reference, got [{"$jsii.map":{"KinesisStreamARN":"${Token[TOKEN.25]}","RoleARN":"${Token[TOKEN.56]}"}}]
      at Kernel._toSandbox (/home/ubuntu/anaconda3/lib/python3.7/site-packages/jsii/_embedded/jsii/jsii-runtime.js:8232:15)
      at mapValues (/home/ubuntu/anaconda3/lib/python3.7/site-packages/jsii/_embedded/jsii/jsii-runtime.js:6906:29)
      at mapValues (/home/ubuntu/anaconda3/lib/python3.7/site-packages/jsii/_embedded/jsii/jsii-runtime.js:7167:27)
      at Object.deserialize (/home/ubuntu/anaconda3/lib/python3.7/site-packages/jsii/_embedded/jsii/jsii-runtime.js:6902:20)
      at Kernel._toSandbox (/home/ubuntu/anaconda3/lib/python3.7/site-packages/jsii/_embedded/jsii/jsii-runtime.js:8222:61)
      at xs.map (/home/ubuntu/anaconda3/lib/python3.7/site-packages/jsii/_embedded/jsii/jsii-runtime.js:8275:33)
      at Array.map (<anonymous>)
      at Kernel._boxUnboxParameters (/home/ubuntu/anaconda3/lib/python3.7/site-packages/jsii/_embedded/jsii/jsii-runtime.js:8275:19)
      at Kernel._toSandboxValues (/home/ubuntu/anaconda3/lib/python3.7/site-packages/jsii/_embedded/jsii/jsii-runtime.js:8260:21)
      at Kernel._wrapSandboxCode (/home/ubuntu/anaconda3/lib/python3.7/site-packages/jsii/_embedded/jsii/jsii-runtime.js:8316:19)
      at Kernel._create (/home/ubuntu/anaconda3/lib/python3.7/site-packages/jsii/_embedded/jsii/jsii-runtime.js:7853:26)
      at Kernel.create (/home/ubuntu/anaconda3/lib/python3.7/site-packages/jsii/_embedded/jsii/jsii-runtime.js:7600:21)
      at KernelHost.processRequest (/home/ubuntu/anaconda3/lib/python3.7/site-packages/jsii/_embedded/jsii/jsii-runtime.js:7388:28)
      at KernelHost.run (/home/ubuntu/anaconda3/lib/python3.7/site-packages/jsii/_embedded/jsii/jsii-runtime.js:7328:14)
      at Immediate.setImmediate [as _onImmediate] (/home/ubuntu/anaconda3/lib/python3.7/site-packages/jsii/_embedded/jsii/jsii-runtime.js:7331:37)
      at runCallback (timers.js:705:18)
      at tryOnImmediate (timers.js:676:5)
      at processImmediate (timers.js:658:5)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "app.py", line 9, in <module>
    DetectanomalyappStack(app, "detectanomalyapp")
  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/jsii/_runtime.py", line 66, in __call__
    inst = super().__call__(*args, **kwargs)
  File "/home/ubuntu/environment/detectanomalyapp/detectanomalyapp/detectanomalyapp_stack.py", line 85, in __init__
    kinesis_stream_source_configuration = [Kinesis_config,])
  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/jsii/_runtime.py", line 66, in __call__
    inst = super().__call__(*args, **kwargs)
  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/aws_cdk/aws_kinesisfirehose/__init__.py", line 57, in __init__
    jsii.create(CfnDeliveryStream, self, [scope, id, props])
  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/jsii/_kernel/__init__.py", line 229, in create
    interfaces=[iface.__jsii_type__ for iface in getattr(klass, "__jsii_ifaces__", [])],
  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/jsii/_kernel/providers/process.py", line 333, in create
    return self._process.send(request, CreateResponse)
  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/jsii/_kernel/providers/process.py", line 318, in send
    raise JSIIError(resp.error) from JavaScriptError(resp.stack)
jsii.errors.JSIIError: Value did not match any type in union: Got an array where a @aws-cdk/aws-kinesisfirehose.CfnDeliveryStream.KinesisStreamSourceConfigurationProperty was expected. Did you mean to pass a variable number of arguments?,Expected object reference, got [{"$jsii.map":{"KinesisStreamARN":"${Token[TOKEN.25]}","RoleARN":"${Token[TOKEN.56]}"}}]

`
### Environment

  - **CDK CLI Version:** 1.38.0
  - **Module Version:** 1.38.0
  - **Node.js Version:** v10.18.0
  - **OS:** cloud9
  - **Language (Version):** Python

### Other information

Trying to take a kinesis stream and add it to a firehose with the destination being an S3 bucket. When I try without this line:

`
kinesis_stream_source_configuration = Kinesis_config
`

it works, but deployment fails because it needs a kinesis stream config. When I added that, that error shows up.

**Comment by w601sxs** [comment]
Upgraded to 1.49.1, still same isse

**Comment by w601sxs** [comment]
Passing both kinesis stream source and S3 destination fails...

`
kfirehose = firehose.CfnDeliveryStream(self,
                            'kfirehose',
                            delivery_stream_name='deliverystream',
                            delivery_stream_type='KinesisStreamAsSource',
                            extended_s3_destination_configuration = S3_dest_config)#,
                            # kinesis_stream_source_configuration = Kinesis_config)
`

Adding these properties later lets me do cdk synth, but the cloud formation does not have the stream source config.

`
        kfirehose.KinesisStreamSourceConfigurationProperty(
            kinesis_stream_arn = kinesis_stream.stream_arn,
            role_arn = kRole.role_arn)
`

**Comment by iliapolo** [comment]
Hi @w601sxs 

Notice that you should always pass strong types classes, rather than raw dictionaries. 

Here is how it should be configured:

```python
s3_dest_config = firehose.CfnDeliveryStream.ExtendedS3DestinationConfigurationProperty(
  bucket_arn='bucket-arn',
  buffering_hints=firehose.CfnDeliveryStream.BufferingHintsProperty(
    interval_in_seconds=60,
    size_in_m_bs=128
  ),
  role_arn='role-arn',
  prefix='raw-data/',
  compression_format='UNCOMPRESSED',
  s3_backup_mode='Disabled'
)

stream_source_config = firehose.CfnDeliveryStream.KinesisStreamSourceConfigurationProperty(
  kinesis_stream_arn='stream-arn',
  role_arn='role-arn'
)

kfirehose = firehose.CfnDeliveryStream(self,
                    'kfirehose',
                    delivery_stream_name='deliverystream',
                    delivery_stream_type='KinesisStreamAsSource',
                    extended_s3_destination_configuration = s3_dest_config,
                    kinesis_stream_source_configuration = stream_source_config)
```

This will produce the following CloudFormation template:

```yaml
Resources:
  kfirehose:
    Type: AWS::KinesisFirehose::DeliveryStream
    Properties:
      DeliveryStreamName: deliverystream
      DeliveryStreamType: KinesisStreamAsSource
      ExtendedS3DestinationConfiguration:
        BucketARN: bucket-arn
        BufferingHints:
          IntervalInSeconds: 60
          SizeInMBs: 128
        CompressionFormat: UNCOMPRESSED
        Prefix: raw-data/
        RoleARN: role-arn
        S3BackupMode: Disabled
      KinesisStreamSourceConfiguration:
        KinesisStreamARN: stream-arn
        RoleARN: role-arn
```

Let us know if this resolves the issue for you. 

Thanks

**Comment by w601sxs** [comment]
Thanks, got it to work!
