### ISSUE TITLE
[aws-lambda] Cannot use 'in' operator to search for 'accountId' in principle

### ISSUE THREAD

**Issue by gattasrikanth** [aws/aws-cdk#8906]
CfnPermission props requires **principal** to be type string but cdk synth failing because **parsePermissionPrincipal** expecting an object

### Reproduction Steps

```

    const myFunction = new lambda.Function(this, 'Handler', {
      runtime: lambda.Runtime.NODEJS_12_X,
      code: lambda.Code.fromBucket(lambda_source, 'lambda.zip'),
      handler: 'index.handler',
      functionName: 'Testing',
    });

    myFunction.addPermission('example', new lambda.CfnPermission(this, id, {
      action: 'lambda:InvokeFunction',
      sourceAccount: this.account,
      principal: 's3.amazonaws.com',
      functionName: myFunction.functionArn,
      sourceArn: resultsBucket.bucketArn
    }))



```

### Error Log

```
 if ('accountId' in principal) {
                        ^

TypeError: Cannot use 'in' operator to search for 'accountId' in s3.amazonaws.com
    at Function.parsePermissionPrincipal (/Users/sggatta/Downloads/cdk/node_modules/@aws-cdk/aws-lambda/lib/function-base.js:134:25)
    at Function.addPermission (/Users/sggatta/Downloads/cdk/node_modules/@aws-cdk/aws-lambda/lib/function-base.js:21:32)
    at new CdkStack (/Users/sggatta/Downloads/cdk/lib/cdk-stack.js:31:19)
    at Object.<anonymous> (/Users/sggatta/Downloads/cdk/bin/cdk.js:6:1)
    at Module._compile (internal/modules/cjs/loader.js:1151:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1171:10)
    at Module.load (internal/modules/cjs/loader.js:1000:32)
    at Function.Module._load (internal/modules/cjs/loader.js:899:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)
    at internal/main/run_main_module.js:17:47
```

### Environment

  - **CLI Version      :** AWS CLI Version? when I type `aws --version` this is what I see: `aws-cli/2.0.0 Python/3.7.4 Darwin/18.7.0 botocore/2.0.0dev4`
  - **Framework Version:** CDK? `^1.49.1`
  - **Node.js Version:**  `v13.8.0`
  - **OS               :** `Mac 10.14.6`
  - **Language (Version):**  JavaScript

### Other

If I simply put `return principal` before the line `if('accountId' in principal)` then `cdk synth` and `cdk deploy` both are working as I expected. So I am not blocked for now.

--- 

This is :bug: Bug Report

**Comment by nija-at** [comment]
The error is in your code at this line - 

```
myFunction.addPermission('example', new lambda.CfnPermission(this, id, {
```

The second argument for [`addPermission()` API](https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-lambda.Function.html#add-wbr-permissionid-permission) is not `CfnPermission`. It's a different [`Permission` interface](https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-lambda.Permission.html).
