### ISSUE TITLE
[core] asset bundling fails with DOCKER_BUILDKIT=1

### ISSUE THREAD

**Issue by elthrasher** [aws/aws-cdk#8910]
Asset bundler fails with Docker buildkit. This is because of a regex searching for "Successfully built <imageId>" which doesn't appear when using buildkit. Buildkit may some day be the default and some systems are already using buildkit by default so it's best to support both versions of docker build.

### Reproduction Steps

The tests in aws-s3-assets can reproduce this issue handily:

```
% DOCKER_BUILDKIT=0 npm t

> @aws-cdk/aws-s3-assets@0.0.0 test /Users/mattmorgan/mine/aws-cdk/packages/@aws-cdk/aws-s3-assets
> cdk-test

PASS test/compat.test.js
PASS test/asset.test.js

=============================== Coverage summary ===============================
Statements   : 94.23% ( 49/52 )
Branches     : 86.21% ( 25/29 )
Functions    : 100% ( 6/6 )
Lines        : 94.23% ( 49/52 )
================================================================================

Test Suites: 2 passed, 2 total
Tests:       16 passed, 16 total
Snapshots:   0 total
Time:        2.039s, estimated 3s
Ran all test suites.
Verifying integ.assets.bundling.lit.js against integ.assets.bundling.lit.expected.json ... OK.
Verifying integ.assets.directory.lit.js against integ.assets.directory.lit.expected.json ... OK.
Verifying integ.assets.file.lit.js against integ.assets.file.lit.expected.json ... OK.
Verifying integ.assets.permissions.lit.js against integ.assets.permissions.lit.expected.json ... OK.
Verifying integ.assets.refs.lit.js against integ.assets.refs.lit.expected.json ... OK.
Verifying integ.multi-assets.js against integ.multi-assets.expected.json ... OK.
Tests successful. Total time (5.4s) | cdk-integ-assert (2.8s) | /Users/mattmorgan/mine/aws-cdk/node_modules/jest/bin/jest.js (2.6s)
```

The test works just fine when buildkit is disabled.

```
% DOCKER_BUILDKIT=1 npm t

> @aws-cdk/aws-s3-assets@0.0.0 test /Users/mattmorgan/mine/aws-cdk/packages/@aws-cdk/aws-s3-assets
> cdk-test

PASS test/compat.test.js
PASS test/asset.test.js

=============================== Coverage summary ===============================
Statements   : 94.23% ( 49/52 )
Branches     : 86.21% ( 25/29 )
Functions    : 100% ( 6/6 )
Lines        : 94.23% ( 49/52 )
================================================================================

Test Suites: 2 passed, 2 total
Tests:       16 passed, 16 total
Snapshots:   0 total
Time:        2.19s, estimated 3s
Ran all test suites.
Verifying integ.assets.bundling.lit.js against integ.assets.bundling.lit.expected.json ... /Users/mattmorgan/mine/aws-cdk/packages/@aws-cdk/core/lib/bundling.js:37
            throw new Error('Failed to extract image ID from Docker build output');
            ^

Error: Failed to extract image ID from Docker build output
    at Function.fromAsset (/Users/mattmorgan/mine/aws-cdk/packages/@aws-cdk/core/lib/bundling.js:37:19)
    at new TestStack (/Users/mattmorgan/mine/aws-cdk/packages/@aws-cdk/aws-s3-assets/test/integ.assets.bundling.lit.js:14:51)
    at Object.<anonymous> (/Users/mattmorgan/mine/aws-cdk/packages/@aws-cdk/aws-s3-assets/test/integ.assets.bundling.lit.js:28:1)
    at Module._compile (internal/modules/cjs/loader.js:1138:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1158:10)
    at Module.load (internal/modules/cjs/loader.js:986:32)
    at Function.Module._load (internal/modules/cjs/loader.js:879:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)
    at internal/main/run_main_module.js:17:47
Error: Command exited with status 1
    at exec (/Users/mattmorgan/mine/aws-cdk/tools/cdk-integ-tools/lib/integ-helpers.js:297:15)
    at IntegrationTest.cdkSynthFast (/Users/mattmorgan/mine/aws-cdk/tools/cdk-integ-tools/lib/integ-helpers.js:85:15)
    at main (/Users/mattmorgan/mine/aws-cdk/tools/cdk-integ-tools/bin/cdk-integ-assert.js:17:35)
Error: cdk-integ-assert exited with error code 1
Tests failed. Total time (3.2s) | /Users/mattmorgan/mine/aws-cdk/node_modules/jest/bin/jest.js (2.7s) | cdk-integ-assert (0.4s)
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
npm ERR! Test failed.  See above for more details.
```
It fails when buildkit is enabled.

### Error Log

Error: Failed to extract image ID from Docker build output

### Environment

  - **CLI Version      :1.49.1
  - **Framework Version:1.49.1
  - **Node.js Version:12.18.2
  - **OS               :MacOS
  - **Language (Version):TypeScript(3.9.5)

### Other

It's a fairly easy fix. PR coming.

--- 

This is :bug: Bug Report

**Comment by elthrasher** [comment]
Should be fixed by https://github.com/aws/aws-cdk/pull/8911
