### ISSUE TITLE
Supplied properties not correct for "CfnRuleProps" error thrown

### ISSUE THREAD

**Issue by whelen-cchevalier** [aws/aws-cdk#9136]
The error occurs when binding lambda to rule 

specific line:
`nightlyServiceRule.addTarget(
      targets.LambdaFunction.bind(nightlyServiceRule, nightlySimServiceLambda),
    );`

### Reproduction Steps

```ts
import lambda = require('@aws-cdk/aws-lambda');
import { Vpc, SecurityGroup, IVpc, ISecurityGroup } from '@aws-cdk/aws-ec2';
import { IFunction } from '@aws-cdk/aws-lambda';
import { Rule, Schedule } from '@aws-cdk/aws-events';
import apigateway = require('@aws-cdk/aws-apigateway');
import targets = require('@aws-cdk/aws-events-targets');

export class DeviceApiStack extends cdk.Stack {
  constructor(scope: cdk.App, id: string, props?: cdk.StackProps, env?: { [key: string]: string }) {
    super(scope, id, props);
    this.env = env as { [key: string]: string };

    // Create API and paths
    const api = new apigateway.RestApi(this, 'deviceApi', {
      restApiName: 'Device Service',
    });

    this.vpc = Vpc.fromLookup(this, 'vpc', { vpcId: 'vpc-sdf' });
    this.securityGroup = SecurityGroup.fromSecurityGroupId(
      this,
      'Security Group',
      'sg-sdf',
    );

    // Nightly service
    const nightlySimServiceLambda = this.createLambda(
      'nightlySimServiceLambda',
      'NightlySimService.handler',
      60 * 15,
    );
    const nightlyServiceRule = new Rule(this, 'NightlyServiceRule', {
      schedule: Schedule.cron({ minute: '0', hour: '1' }),
    });
    nightlyServiceRule.addTarget(
      targets.LambdaFunction.bind(nightlyServiceRule, nightlySimServiceLambda),
    );
  }

  vpc: IVpc;
  env: { [key: string]: string };
  securityGroup: ISecurityGroup;

  createLambda(name: string, code: string, runLength: number = 20): IFunction {
    return new lambda.Function(this, name, {
      code: new lambda.AssetCode('source'),
      handler: code,
      runtime: lambda.Runtime.NODEJS_10_X,
      vpc: this.vpc,
      environment: this.env,
      timeout: cdk.Duration.seconds(runLength),
      securityGroup: this.securityGroup,
    });
  }
}
```

### Error Log

```console
C:\Users\cchevali\Documents\GitHub\VerizonInteraction\node_modules\@aws-cdk\aws-events\node_modules\@aws-cdk\core\lib\runtime.ts:141
      throw new CfnSynthesisError(message);
            ^
Error: Resolution error: Supplied properties not correct for "CfnRuleProps"
  targets: element 0: supplied properties not correct for "TargetProperty"
    arn: required but missing.
Object creation stack:
  at new Intrinsic (C:\Users\cchevali\Documents\GitHub\VerizonInteraction\node_modules\@aws-cdk\aws-events\node_modules\@aws-cdk\core\lib\private\intrinsic.ts:28:26)
  at new PostResolveToken (C:\Users\cchevali\Documents\GitHub\VerizonInteraction\node_modules\@aws-cdk\aws-events\node_modules\@aws-cdk\core\lib\util.ts:83:5)
  at CfnRule._toCloudFormation (C:\Users\cchevali\Documents\GitHub\VerizonInteraction\node_modules\@aws-cdk\aws-events\node_modules\@aws-cdk\core\lib\cfn-resource.ts:272:29)
  at C:\Users\cchevali\Documents\GitHub\VerizonInteraction\node_modules\@aws-cdk\core\lib\stack.ts:799:56
  at Array.map (<anonymous>)
  at DeviceApiStack._toCloudFormation (C:\Users\cchevali\Documents\GitHub\VerizonInteraction\node_modules\@aws-cdk\core\lib\stack.ts:799:32)
  at DeviceApiStack.synthesize (C:\Users\cchevali\Documents\GitHub\VerizonInteraction\node_modules\@aws-cdk\core\lib\stack.ts:757:38)
  at DeviceApiStack.onSynthesize (C:\Users\cchevali\Documents\GitHub\VerizonInteraction\node_modules\@aws-cdk\core\lib\construct-compat.ts:129:10)
  at C:\Users\cchevali\Documents\GitHub\VerizonInteraction\node_modules\@aws-cdk\core\lib\private\synthesis.ts:98:46
  at visit (C:\Users\cchevali\Documents\GitHub\VerizonInteraction\node_modules\@aws-cdk\core\lib\private\synthesis.ts:136:5)
  at visit (C:\Users\cchevali\Documents\GitHub\VerizonInteraction\node_modules\@aws-cdk\core\lib\private\synthesis.ts:132:5)
  at synthesizeTree (C:\Users\cchevali\Documents\GitHub\VerizonInteraction\node_modules\@aws-cdk\core\lib\private\synthesis.ts:98:3)
  at Object.synthesize (C:\Users\cchevali\Documents\GitHub\VerizonInteraction\node_modules\@aws-cdk\core\lib\private\synthesis.ts:32:3)
  at App.synth (C:\Users\cchevali\Documents\GitHub\VerizonInteraction\node_modules\@aws-cdk\core\lib\stage.ts:168:23)
  at process.<anonymous> (C:\Users\cchevali\Documents\GitHub\VerizonInteraction\node_modules\@aws-cdk\core\lib\app.ts:112:45)
  at Object.onceWrapper (events.js:418:26)
  at process.emit (events.js:311:20)
  at process.EventEmitter.emit (domain.js:482:12)
  at process.emit (C:\Users\cchevali\Documents\GitHub\VerizonInteraction\node_modules\source-map-support\source-map-support.js:495:21)
  at process.topLevelDomainCallback (domain.js:137:15)
    at ValidationResult.assertSuccess (C:\Users\cchevali\Documents\GitHub\VerizonInteraction\node_modules\@aws-cdk\aws-events\node_modules\@aws-cdk\core\lib\runtime.ts:141:13)
    at cfnRulePropsToCloudFormation (C:\Users\cchevali\Documents\GitHub\VerizonInteraction\node_modules\@aws-cdk\aws-events\lib\events.generated.ts:579:39)
    at CfnRule.renderProperties (C:\Users\cchevali\Documents\GitHub\VerizonInteraction\node_modules\@aws-cdk\aws-events\lib\events.generated.ts:761:16)
    at PostResolveToken.ret.Resources [as processor] (C:\Users\cchevali\Documents\GitHub\VerizonInteraction\node_modules\@aws-cdk\aws-events\node_modules\@aws-cdk\core\lib\cfn-resource.ts:283:40)
    at PostResolveToken.postProcess (C:\Users\cchevali\Documents\GitHub\VerizonInteraction\node_modules\@aws-cdk\aws-events\node_modules\@aws-cdk\core\lib\util.ts:92:17)
    at Object.postProcess (C:\Users\cchevali\Documents\GitHub\VerizonInteraction\node_modules\@aws-cdk\core\lib\private\resolve.ts:52:78)
    at DefaultTokenResolver.resolveToken (C:\Users\cchevali\Documents\GitHub\VerizonInteraction\node_modules\@aws-cdk\core\lib\resolvable.ts:138:32)
    at resolve (C:\Users\cchevali\Documents\GitHub\VerizonInteraction\node_modules\@aws-cdk\core\lib\private\resolve.ts:133:29)
    at Object.resolve (C:\Users\cchevali\Documents\GitHub\VerizonInteraction\node_modules\@aws-cdk\core\lib\private\resolve.ts:49:32)
    at resolve (C:\Users\cchevali\Documents\GitHub\VerizonInteraction\node_modules\@aws-cdk\core\lib\private\resolve.ts:154:39)
Subprocess exited with error 1
```

### Environment

  - **CLI Version      :** 1.51.0 (build 8c2d53c)
  - **Framework Version:**
  - **Node.js Version:** v12.16.1
  - **OS               :** window 10
  - **Language (Version):** 

### Other

--- 

This is :bug: Bug Report

**Comment by rix0rrr** [comment]
Have you tried instantiating `LambdaFunction`? 

We're happy to help you out, but GitHub issues is not a support forum. There are websites much better suited for that, such as StackOverflow.

Please ask that same question again on [StackOverflow under the aws-cdk](https://stackoverflow.com/questions/ask?tags=aws-cdk) tag. If you can't get a response to your question, please bring it to our attention again and we will do our best to answer it.
