### ISSUE TITLE
[eks] expose EncryptionConfig in eks.Cluster Construct 

### ISSUE THREAD

**Issue by nicolai86** [aws/aws-cdk#9140]
## :question: General Issue

Cloudformation supports passing in an EncryptionConfig when creating an EKS cluster via the eks.Cluster.
CDK only exposes EncryptionConfig in the CfnCluster construct.

### The Question

Can we expose encryptionConfig as part of `ClusterProps` to allow this to be managed with the higher level CDK construct?

### Environment

  - **CDK CLI Version:** 1.51.0
  - **Module Version:** 1.51.0
  - **Node.js Version:** v12.18.2 
  - **OS:** OSX Mojave
  - **Language (Version):** TypeScript

### Other information

CfnCluster exposes EncryptionConfig
https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-eks.CfnClusterProps.html#encryptionconfig
ClusterProps does not expose EncryptionConfig
https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-eks.ClusterProps.html

**Comment by davidsung** [comment]
Hi @iliapolo , I could contribute PR for this issue

**Comment by iliapolo** [comment]
@davidsung that would be great! Happy to review

**Comment by SaikiranDaripelli** [comment]
Is there any workaround until this is merged? as it is not possible to edit the config after cluster creation.

**Comment by iliapolo** [comment]
@SaikiranDaripelli If you are using `kubectlEnabled: false`, you can use [escape hatches](https://docs.aws.amazon.com/cdk/latest/guide/cfn_layer.html) to manipulate the underlying CFN configuration. 

If you are using `kubectlEnabled: true` (or just omitted) there currently is no way since it is implemented with a custom resource.

However, I wouldn't recommend using `kubectlEnabled: false` and escape hatches as this will soon be deprecated and eventually removed. See discussion here: https://github.com/aws/aws-cdk/issues/9332.

I dont imagine it would take very long for this PR to be merged. Stay tuned.

**Comment by eladb** [comment]
https://github.com/aws/aws-cdk/pull/9472

**Comment by arul-gupta** [comment]
There also seems to an issue with AWS lambda runtime used to create custom resource. The latest nodejs12.x runtime uses AWS-SDK v2.631.0 which doesn't seem to have support for encryption. I get the following error:

> Failed to create resource. Error: Unexpected key 'encryptionConfig' found in params
at invokeUserFunction (/var/task/framework.js:85:19)
at process._tickCallback (internal/process/next_tick.js:68:7)
Remote function error: UnexpectedParameter: Unexpected key 'encryptionConfig' found in params
at ParamValidator.fail (/var/runtime/node_modules/aws-sdk/lib/param_validator.js:50:37)
at ParamValidator.validateStructure (/var/runtime/node_modules/aws-sdk/lib/param_validator.js:77:14)
at ParamValidator.validateMember (/var/runtime/node_modules/aws-sdk/lib/param_validator.js:88:21)
at ParamValidator.validate (/var/runtime/node_modules/aws-sdk/lib/param_validator.js:34:10)
at Request.VALIDATE_PARAMETERS (/var/runtime/node_modules/aws-sdk/lib/event_listeners.js:126:42)
at Request.callListeners (/var/runtime/node_modules/aws-sdk/lib/sequential_executor.js:106:20)
at callNextListener (/var/runtime/node_modules/aws-sdk/lib/sequential_executor.js:96:12)
at /var/runtime/node_modules/aw


AWS-SDK added support for envelope encryption only in v2.634.0.

**Comment by eladb** [comment]
Indeed this API is still not supported by the [AWS Lambda node.js runtime](https://docs.aws.amazon.com/lambda/latest/dg/lambda-runtimes.html). Let's wait until lambda the SDK version in their runtime and then we can merge this.

**Comment by davidsung** [comment]
As figured out by @pahud, the `aws-sdk` version in the Lambda node12.x runtime env in most AWS regions is now `2.712.0` (already tested on `us-east-1`, `us-east-2`, `ap-southeast-1`, `ap-northeast-1`, `ap-southeast-2`, `eu-central-1`, `eu-west-1`, `eu-west-2`, `sa-east-1`). We thought the docs https://docs.aws.amazon.com/lambda/latest/dg/lambda-runtimes.html is outdated.
<img width="1244" alt="Screenshot 2020-08-10 at 9 46 37 PM" src="https://user-images.githubusercontent.com/473354/89794309-76cdea00-db59-11ea-80b4-fbddc24c29b7.png">

Tested with Lambda function:
```js
const aws = require('aws-sdk');

exports.handler = async (event) => {
  console.log("request:", JSON.stringify(event, undefined, 2));
  const response = {
    statusCode: 200,
    body: JSON.stringify({version: aws.VERSION}),
  };
  return response;
};
```

**Comment by eladb** [comment]
Thanks for testing this. I am following up with the Lambda team to validate.

**Comment by davidsung** [comment]
@eladb Kindly take note that the version specified in the [Lambda runtime docs](https://docs.aws.amazon.com/lambda/latest/dg/lambda-runtimes.html) has been updated to `2.721.0`
