### ISSUE TITLE
Getting  CDK command errors when trying to deploy AWS Chalice application with CDK

### ISSUE THREAD

**Issue by johnnywong1** [aws/aws-cdk#9198]
I believe the issue has something to do with versioning from what I gather from Gitter and other similar GitHub issues.

### Reproduction Steps

Following the exact steps on this blog post here (https://aws.amazon.com/blogs/developer/deploying-aws-chalice-application-using-aws-cloud-development-kit/).  I've tested this both on mac host machine and cloud9. 

### Error Log
Depending on the version of node you have, you get one of the following errors.

**Bug1**
```
jsii.errors.JavaScriptError: 
  internal/modules/cjs/loader.js:800
      throw err;
      ^
  
  Error: Cannot find module '@aws-cdk/core/lib/cfn-parse'
  Require stack:
  - /private/var/folders/1p/_r6fjwgn2pvfy44lqzp661986sb0st/T/jsii-kernel-VjbHVn/node_modules/@aws-cdk/aws-iam/lib/iam.generated.js
  - /private/var/folders/1p/_r6fjwgn2pvfy44lqzp661986sb0st/T/jsii-kernel-VjbHVn/node_modules/@aws-cdk/aws-iam/lib/managed-policy.js
  - /private/var/folders/1p/_r6fjwgn2pvfy44lqzp661986sb0st/T/jsii-kernel-VjbHVn/node_modules/@aws-cdk/aws-iam/lib/index.js
  - 47
      at Function.Module._resolveFilename (internal/modules/cjs/loader.js:797:15)
```

**Bug 2**
```
internal/fs/utils.js:230
    throw err;
    ^

Error: EAGAIN: resource temporarily unavailable, read
    at Object.readSync (fs.js:578:3)
    at SyncStdio.readLine (/usr/local/lib/python3.8/site-packages/jsii/_embedded/jsii/jsii-runtime.js:13350:25)
    at InputOutput.read (/usr/local/lib/python3.8/site-packages/jsii/_embedded/jsii/jsii-runtime.js:13300:34)
    at KernelHost.run (/usr/local/lib/python3.8/site-packages/jsii/_embedded/jsii/jsii-runtime.js:7231:32)
    at Immediate.<anonymous> (/usr/local/lib/python3.8/site-packages/jsii/_embedded/jsii/jsii-runtime.js:7239:37)
    at processImmediate (internal/timers.js:456:21) {
  errno: -35,
  syscall: 'read',
  code: 'EAGAIN'
}
```
**Bug 3**
Similar to Bug 2, but missing a utils in @aws_cdk instead of cfn-parse

### Environment

  - **CLI Version:**  git version 2.24.3 
  - **Framework Version:** 1.53.0 (build 6c326cb)
  - **Node.js Version:** 12.3.1, 12.13.1, 12.18.1, 13.1.0, 13.14.0, 14.1.0, 14.2.0, 14.5.0 
  - **OS             :** MacOS & Cloud9 Linux
  - **Language (Version):** Python 

### Other

--- 

This is :bug: Bug Report

**Comment by rirze** [comment]
Running in this issue as well with the following versions:

**CDK: 1.54.0  (build c01b9b9)**
**Node: v12.14.0**

Currently I have the setup working on a dev machine but the production machine runs into this error. Node and CDK versions are the same on both, maybe there's a configuration setting that causes this issue?

**Comment by jadeknightjr** [comment]
Has there been a status update on this issue?

**Comment by shivlaks** [comment]
@jadeknightjr - I'll be going through the blog post this week and post an update once I get to the repro steps and dig into the root cause. stay tuned!

**Comment by dnlopes** [comment]
Any news on this thread? I'm also hitting this issue.

**Comment by pancodia** [comment]
Im also having this issue.

```
$ cdk --version                                                                                                                                                                                                                               
1.111.0 (build 556ca93)

$ node --version                                                                                                                                                                                                                              
v12.22.3
```
