### ISSUE TITLE
[aws-elasticloadbalancingv2] ApplicationListener.addTargetGroups() ignores the new `conditions` array 

### ISSUE THREAD

**Issue by realharry** [aws/aws-cdk#9262]
`ApplicationListener.addTargetGroups()` accepts an `AddApplicationTargetGroupsProps` argument.  According to the doc (https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-elasticloadbalancingv2.AddApplicationTargetGroupsProps.html), existing fields such as `hostHeader` have been deprecated and a new field, `conditions` have been added. However, the `conditions` field is not accepted by the `addTargetGroups()` method, and it throws an error:

```
At least one of 'conditions', 'hostHeader', 'pathPattern' or 'pathPatterns' is required when defining a load balancing rule.
```

### Reproduction Steps

```
    const hostHeaders = [props.domain1, props.domain2];
    listener.addTargetGroups(
      listenerTgId,
      {
        targetGroups: [extraTG],
        conditions: [
          elb.ListenerCondition.hostHeaders(hostHeaders),
        ],
        priority: props.priority,
      }
    );
```

### Error Log

```
At least one of 'conditions', 'hostHeader', 'pathPattern' or 'pathPatterns' is required when defining a load balancing rule.

/projects/app1/node_modules/@aws-cdk/core/lib/private/synthesis.ts:118
    throw new Error(`Validation failed with the following errors:\n  ${errorList}`);
          ^
Error: Validation failed with the following errors:
  [Inf2AlphaMetroshopandplacTg/listener/extraTg] Listener rule needs at least one action
    at validateTree (/extra0/Projects/shoppingweb/devops/infra2-angular-apps/node_modules/@aws-cdk/core/lib/private/synthesis.ts:118:11)
    at Object.synthesize (/extra0/Projects/shoppingweb/devops/infra2-angular-apps/node_modules/@aws-cdk/core/lib/private/synthesis.ts:21:5)
    at App.synth (/extra0/Projects/shoppingweb/devops/infra2-angular-apps/node_modules/@aws-cdk/core/lib/stage.ts:168:23)
    at process.<anonymous> (/extra0/Projects/shoppingweb/devops/infra2-angular-apps/node_modules/@aws-cdk/core/lib/app.ts:112:45)
    at Object.onceWrapper (events.js:422:26)
    at process.emit (events.js:315:20)
    at process.EventEmitter.emit (domain.js:483:12)
    at process.emit (/extra0/Projects/shoppingweb/devops/infra2-angular-apps/node_modules/source-map-support/source-map-support.js:495:21)
Subprocess exited with error 1
```

### Environment

  - **CLI Version      :*1.50.0 (build 84acc92)*
  - **Framework Version:*1.54.0*
  - **Node.js Version:*v12.18.3*
  - **OS               :*ubuntu 20.04*
  - **Language (Version):*typescript 3.9.7*

### Other

--- 

This is :bug: Bug Report

**Comment by realharry** [comment]
Found a related issue, https://github.com/aws/aws-cdk/issues/8328, which was marked as fixed as of 6/05/2020.
