### ISSUE TITLE
[aws-dynamodb] when setting PhysicalName.GENERATE_IF_NEEDED to tableName, throwing error `Invalid physical name passed to CloudFormation. Use "this.physicalName" instead`

### ISSUE THREAD

**Issue by flyingImer** [aws/aws-cdk#9374]
Hi team, I'm trying to do a cross-env reference on a ddb table. After I specify the tableName to PhysicalName.GENERATE_IF_NEEDED, synthesizing process breaks. 

The error message says:
```
Error: Resolution error: Invalid physical name passed to CloudFormation. Use "this.physicalName" instead.
```
I suspect this is a bug, as my experiment on a cross-env referenced IAM role works just fine with PhysicalName.GENERATE_IF_NEEDED (not included in the example below)

And I think this error message is confusing. I have no idea what to do with this message. Any context how should I interpret it?

### Reproduction Steps

here is an example I used: https://github.com/flyingImer/cdk-mkii

`cdk synth` breaks even without `SomeStack` referencing to the ddb table defined in `CdkMkiiStack`

### Error Log

```
Error: Resolution error: Invalid physical name passed to CloudFormation. Use "this.physicalName" instead.
    at GeneratedWhenNeededMarker.resolve (/Users/Can/ws-local/github/cdk-mkii/node_modules/@aws-cdk/core/lib/private/physical-name-generator.ts:89:11)
    at DefaultTokenResolver.resolveToken (/Users/Can/ws-local/github/cdk-mkii/node_modules/@aws-cdk/core/lib/resolvable.ts:134:24)
    at resolve (/Users/Can/ws-local/github/cdk-mkii/node_modules/@aws-cdk/core/lib/private/resolve.ts:133:29)
    at Object.resolve [as mapToken] (/Users/Can/ws-local/github/cdk-mkii/node_modules/@aws-cdk/core/lib/private/resolve.ts:49:32)
    at TokenizedStringFragments.mapTokens (/Users/Can/ws-local/github/cdk-mkii/node_modules/@aws-cdk/core/lib/string-fragments.ts:71:33)
    at DefaultTokenResolver.resolveString (/Users/Can/ws-local/github/cdk-mkii/node_modules/@aws-cdk/core/lib/resolvable.ts:155:22)
    at resolve (/Users/Can/ws-local/github/cdk-mkii/node_modules/@aws-cdk/core/lib/private/resolve.ts:91:31)
    at Object.resolve (/Users/Can/ws-local/github/cdk-mkii/node_modules/@aws-cdk/core/lib/private/resolve.ts:49:32)
    at Object.resolve (/Users/Can/ws-local/github/cdk-mkii/node_modules/@aws-cdk/core/lib/private/resolve.ts:155:39)
    at CdkMkiiStack.resolve (/Users/Can/ws-local/github/cdk-mkii/node_modules/@aws-cdk/core/lib/stack.ts:363:12)
```

### Environment

  - **CLI Version      :** 1.55.0 (build 48ccf09)
  - **Framework Version:** 1.55.0
  - **Node.js Version:** v12.16.2
  - **OS               :** macOS 10.15.6
  - **Language (Version):**  TypeScript

### Other

--- 

This is :bug: Bug Report

**Comment by skinny85** [comment]
Hey @flyingImer ,

thanks for opening the issue. Would you mind showing a particular snippet that causes this? It's hard to find it in an entire GutHub project. That will help us diagnose immensely. Thanks!

**Comment by flyingImer** [comment]
@skinny85 yes, this is the line: https://github.com/flyingImer/cdk-mkii/blob/master/lib/cdk-mkii-stack.ts#L16

**Comment by skinny85** [comment]
@flyingImer thanks! I confirm I can reproduce it on a minimal example like this:

```ts
        new ddb.Table(this, 'SomeTable', {
            partitionKey: {
                name: 'someKey',
                type: ddb.AttributeType.STRING
            },
            tableName: cdk.PhysicalName.GENERATE_IF_NEEDED // even without cross-env reference, this line still throws the error
        });
```

Thanks for reporting - this definitely looks like a bug, either in the DynamoDB library, or in the core physical name resolution.

**Comment by skinny85** [comment]
Yep, I think it's in the DynamoDB library. I should have a fix out soon.

**Comment by ChristianTrummer99** [comment]
This seems to still be an issue, except for API Gateway 
```        
api = apigateway.LambdaRestApi(self, 'TransactionServicesAPIs',
            deploy_options=apigateway.StageOptions(
                stage_name='test'
            ),
            handler=fn,
            proxy=False,
            rest_api_name=PhysicalName.GENERATE_IF_NEEDED
        )
```
-> jsii.errors.JSIIError: Resolution error: Resolution error: Resolution error: Invalid physical name passed to CloudFormation. Use "this.physicalName" instead...

**Comment by skinny85** [comment]
Confirmed I was able to reproduce the issue @ChristianTrummer99 (in TypeScript, the language doesn't actually matters here as it turns out).

Working on a fix.

**Comment by skinny85** [comment]
Fix: https://github.com/aws/aws-cdk/pull/19638.

**Comment by isaiahvita** [comment]
hello,
I am seeing a similar issue for S3 buckets. is this still an issue for S3?
```
        this.pluginBucket = new Bucket(this, "DistributionBucket", {
            bucketName: PhysicalName.GENERATE_IF_NEEDED,
            blockPublicAccess: BlockPublicAccess.BLOCK_ALL,
            objectOwnership: ObjectOwnership.BUCKET_OWNER_ENFORCED,
            enforceSSL: true,
            serverAccessLogsBucket: pluginBucketServerAccessLogsBucket,
            versioned: true
        })
```
results in:
```
Error: Resolution error: Resolution error: Resolution error: Invalid physical name passed to CloudFormation. Use "this.physicalName" instead...
    at GeneratedWhenNeededMarker.resolve (/home/ubuntu/gorgon-nuke/cdk/pipeline/node_modules/aws-cdk-lib/core/lib/private/physical-name-generator.js:1:2022)
    at RememberingTokenResolver.resolveToken (/home/ubuntu/gorgon-nuke/cdk/pipeline/node_modules/aws-cdk-lib/core/lib/resolvable.js:1:1238)
    at RememberingTokenResolver.resolveToken (/home/ubuntu/gorgon-nuke/cdk/pipeline/node_modules/aws-cdk-lib/core/lib/private/resolve.js:1:4058)
    at resolve (/home/ubuntu/gorgon-nuke/cdk/pipeline/node_modules/aws-cdk-lib/core/lib/private/resolve.js:1:2661)
    at Object.resolve [as mapToken] (/home/ubuntu/gorgon-nuke/cdk/pipeline/node_modules/aws-cdk-lib/core/lib/private/resolve.js:1:1121)
    at TokenizedStringFragments.mapTokens (/home/ubuntu/gorgon-nuke/cdk/pipeline/node_modules/aws-cdk-lib/core/lib/string-fragments.js:1:1365)
    at RememberingTokenResolver.resolveString (/home/ubuntu/gorgon-nuke/cdk/pipeline/node_modules/aws-cdk-lib/core/lib/resolvable.js:4:358)
    at RememberingTokenResolver.resolveString (/home/ubuntu/gorgon-nuke/cdk/pipeline/node_modules/aws-cdk-lib/core/lib/private/resolve.js:1:4134)
    at resolve (/home/ubuntu/gorgon-nuke/cdk/pipeline/node_modules/aws-cdk-lib/core/lib/private/resolve.js:1:2045)
    at Object.resolve (/home/ubuntu/gorgon-nuke/cdk/pipeline/node_modules/aws-cdk-lib/core/lib/private/resolve.js:1:1121)
```

**Comment by skinny85** [comment]
@isaiahvita are you 100% sure the problem is with this code? Not somewhere else?

**Comment by renschler** [comment]
I'm seeing this error for SecretsManager keys 

```
    const sengridAPIKey = new secretsmanager.Secret(
      this,
      `sengridAPIKey-${deployEnv}`,
      {
        secretName: PhysicalName.GENERATE_IF_NEEDED,
      }
    );
```

```
Error: Resolution error: Resolution error: Resolution error: Resolution error: Invalid physical name passed to CloudFormation. Use "this.physicalName" instead..
Object creation stack:
```

**Comment by skinny85** [comment]
@renschler can you show how are you using `sengridAPIKey`?

**Comment by joshbalfour** [comment]
I'm also seeing this when referencing `secret.secretName`, `secret.secretArn` works fine though.
