### ISSUE TITLE
[SAM] CDK generates unsupported property when combining with Condition

### ISSUE THREAD

**Issue by NGL321** [aws/aws-cdk#9471]
*Copied from @yidimu*

### What did you expect to happen?

I was trying to create a lambda function within VPC when a `RunLambdaInVPC` condition equals to true.
Below is the expected and correct CFN template. Please note the first letter of `SecurityGroupIds` and `SubnetIds` are upper case.
``` json
        "FindingsEsIndexer": {
            "Type": "AWS::Serverless::Function",
            "Properties": {
                "CodeUri": { ... },
                "Handler": "...",
                "Runtime": "...",
                "AutoPublishAlias": { ... },
                "DeploymentPreference": { ... },
                "Environment": { ... },
                "Events": { ... },
                "FunctionName": "...",
                "MemorySize": ...,
                "Role": { ... },
                "Timeout": ...,
                "VpcConfig": {
                    "SecurityGroupIds": [
                        {
                            "Fn::GetAtt": [
                                "LambdaSecurityGroup",
                                "GroupId"
                            ]
                        }
                    ],
                    "SubnetIds": [
                        {
                            "Fn::ImportValue": "PrivateSubnet01"
                        },
                        {
                            "Fn::ImportValue": "PrivateSubnet02"
                        }
                    ]
                },
                "ProvisionedConcurrencyConfig": { ... }
            },
            "Metadata": { ... }
        },
```

### What actually happened?

However, when I add condition, with the following code, CDK generates the template with `securityGroupIds` and `subnetIds` (first letter lower case). And I got "Encountered unsupported property securityGroupIds" error. CDK could still generate correct property name when removing the condition though.
``` java
CfnFunction.VpcConfigProperty vpcConfigProperty = CfnFunction.VpcConfigProperty.builder()
                .securityGroupIds(Arrays.asList(cfnSecurityGroup.getAttrGroupId()))
                .subnetIds(Arrays.asList(
                        Fn.importValue("PrivateSubnet01"),
                        Fn.importValue("PrivateSubnet02")
                ))
                .build();
CfnFunction function = new CfnFunction(this, "functionName",
                CfnFunctionProps.builder()
                        .codeUri(...)
                        .handler(...)
                        .runtime(...)
                        .memorySize(...)
                        .timeout(...)
                        .environment(...)
                        .role(...)
                        .functionName(...)
                        .autoPublishAlias(stackHelper.getStage())
                        .vpcConfig(Fn.conditionIf(runLambdaInVPC.getLogicalId(), vpcConfigProperty, Fn.ref("AWS::NoValue")))
                        .build());
```

### Environment

  - **CLI Version      :**
  - **Framework Version:**
  - **Node.js Version:** 
  - **OS               :**
  - **Language (Version):** Java

### Other

--- 

This is :bug: Bug Report

**Comment by NGL321** [comment]
I have reproduced this issue and can confirm the behavior in the cfn output.

**Comment by nija-at** [comment]
@NGL321 - can you paste the CDK app that you used to reproduce this here?

**Comment by nija-at** [comment]
This seems to be a problem specific to Java (or non-typescript languages).
I was able to get this working in typescript but **not** in Java.

Typescript:

```typescript
#!/usr/bin/env node
import { App, CfnOutput, Stack, Construct, Fn, Aws } from '@aws-cdk/core';
import { CfnFunction } from '@aws-cdk/aws-sam';

const app = new App();
const stack = new Stack(app, 'mystack');

const vpcConfig: CfnFunction.VpcConfigProperty = {
  securityGroupIds: [ 'group1' ],
  subnetIds: [ 'subnet1' ],
};
const conditional = Fn.conditionIf("condition", vpcConfig, Aws.NO_VALUE);

new CfnFunction(stack, 'fn', {
  runtime: 'runtime',
  handler: 'index.handler',
  codeUri: 'uri',
  vpcConfig: conditional
});
```

Java:

```java
package com.myorg;

import software.amazon.awscdk.core.App;
import software.amazon.awscdk.core.ICfnConditionExpression;
import software.amazon.awscdk.core.Fn;
import software.amazon.awscdk.core.Stack;
import software.amazon.awscdk.services.sam.CfnFunction;
import software.amazon.awscdk.services.sam.CfnFunctionProps;

import java.util.List;
import java.util.ArrayList;

public class HelloCdkJavaApp {
    public static void main(final String[] args) {
        final App app = new App();
        final Stack stack = new Stack(app, "mystack");

        final List<String> groups = new ArrayList<String>();
        groups.add("securitygroup1");

        final List<String> subnets = new ArrayList<String>();
        subnets.add("subnet1");

        final CfnFunction.VpcConfigProperty prop = new CfnFunction.VpcConfigProperty.Builder()
            .securityGroupIds(groups)
            .subnetIds(subnets)
            .build();
        
        final ICfnConditionExpression conditional = Fn.conditionIf("some condition", prop, "AWS::NoValue");

        new CfnFunction(stack, "fn", CfnFunctionProps.builder()
            .codeUri("codeuri")
            .handler("index.handler")
            .runtime("runtime")
            .vpcConfig(conditional)
            .build());

        app.synth();
    }
}
```

Capturing the error on `cdk synth` -

```
⇒  cdk synth
[ERROR] Failed to execute goal org.codehaus.mojo:exec-maven-plugin:1.6.0:java (default-cli) on project hello-cdk-java: An exception occured while executing the Java class. Module '@aws-cdk/aws-sam' not found
[ERROR] Error: Module '@aws-cdk/aws-sam' not found
[ERROR]     at Kernel._typeInfoForFqn (/private/var/folders/st/psj93qkd2ngfry3chfd4zvgj7_v654/T/jsii-java-runtime2774755706388367735/jsii-runtime.js:8195:19)
[ERROR]     at Object.deserialize (/private/var/folders/st/psj93qkd2ngfry3chfd4zvgj7_v654/T/jsii-java-runtime2774755706388367735/jsii-runtime.js:6917:36)
[ERROR]     at Object.deserialize (/private/var/folders/st/psj93qkd2ngfry3chfd4zvgj7_v654/T/jsii-java-runtime2774755706388367735/jsii-runtime.js:7101:67)
[ERROR]     at Kernel._toSandbox (/private/var/folders/st/psj93qkd2ngfry3chfd4zvgj7_v654/T/jsii-java-runtime2774755706388367735/jsii-runtime.js:8304:61)
[ERROR]     at /private/var/folders/st/psj93qkd2ngfry3chfd4zvgj7_v654/T/jsii-java-runtime2774755706388367735/jsii-runtime.js:8357:33
[ERROR]     at Array.map (<anonymous>)
[ERROR]     at Kernel._boxUnboxParameters (/private/var/folders/st/psj93qkd2ngfry3chfd4zvgj7_v654/T/jsii-java-runtime2774755706388367735/jsii-runtime.js:8357:19)
[ERROR]     at Kernel._toSandboxValues (/private/var/folders/st/psj93qkd2ngfry3chfd4zvgj7_v654/T/jsii-java-runtime2774755706388367735/jsii-runtime.js:8342:21)
[ERROR]     at /private/var/folders/st/psj93qkd2ngfry3chfd4zvgj7_v654/T/jsii-java-runtime2774755706388367735/jsii-runtime.js:7768:73
[ERROR]     at Kernel._wrapSandboxCode (/private/var/folders/st/psj93qkd2ngfry3chfd4zvgj7_v654/T/jsii-java-runtime2774755706388367735/jsii-runtime.js:8398:19)
[ERROR]     at /private/var/folders/st/psj93qkd2ngfry3chfd4zvgj7_v654/T/jsii-java-runtime2774755706388367735/jsii-runtime.js:7768:25
[ERROR]     at Kernel._ensureSync (/private/var/folders/st/psj93qkd2ngfry3chfd4zvgj7_v654/T/jsii-java-runtime2774755706388367735/jsii-runtime.js:8371:20)
[ERROR]     at Kernel.sinvoke (/private/var/folders/st/psj93qkd2ngfry3chfd4zvgj7_v654/T/jsii-java-runtime2774755706388367735/jsii-runtime.js:7767:26)
[ERROR]     at KernelHost.processRequest (/private/var/folders/st/psj93qkd2ngfry3chfd4zvgj7_v654/T/jsii-java-runtime2774755706388367735/jsii-runtime.js:7446:28)
[ERROR]     at KernelHost.run (/private/var/folders/st/psj93qkd2ngfry3chfd4zvgj7_v654/T/jsii-java-runtime2774755706388367735/jsii-runtime.js:7384:14)
[ERROR]     at Immediate._onImmediate (/private/var/folders/st/psj93qkd2ngfry3chfd4zvgj7_v654/T/jsii-java-runtime2774755706388367735/jsii-runtime.js:7387:37)
[ERROR]     at processImmediate (internal/timers.js:456:21)
[ERROR] -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.codehaus.mojo:exec-maven-plugin:1.6.0:java (default-cli) on project hello-cdk-java: An exception occured while executing the Java class. Module '@aws-cdk/aws-sam' not found
```
