### ISSUE TITLE
All AWS CDK packages dead on NPM

### ISSUE THREAD

**Issue by Dzhuneyt** [aws/aws-cdk#9482]
Trying to update AWS CDK packages in a project, I get 404 errors on all packages that are part of the @aws-cdk namespace. All other third party libraries update just fine.

Steps to reproduce:
```
npm cache clear --force
npm update
```

Output:
```
npm info it worked if it ends with ok
npm verb cli [
npm verb cli   '/Users/dzhuneytahmed/.nvm/versions/node/v13.11.0/bin/node',
npm verb cli   '/Users/dzhuneytahmed/.nvm/versions/node/v13.11.0/bin/npm',
npm verb cli   'update',
npm verb cli   '--verbose'
npm verb cli ]
npm info using npm@6.14.7
npm info using node@v13.11.0
npm verb npm-session 2627e755ce8ccbf8
npm verb update computing outdated modules to update
npm http fetch GET 200 https://registry.npmjs.org/uglifyjs-webpack-plugin 196ms
npm http fetch GET 200 https://registry.npmjs.org/ts-loader 199ms
npm http fetch GET 200 https://registry.npmjs.org/ts-jest 246ms
npm http fetch GET 200 https://registry.npmjs.org/webpack-cli 343ms
npm http fetch GET 200 https://registry.npmjs.org/ts-node 365ms
npm http fetch GET 200 https://registry.npmjs.org/@types%2fjest 374ms
npm http fetch GET 404 https://registry.npmjs.org/@aws-cdk%2faws-codebuild 418ms
npm http fetch GET 404 https://registry.npmjs.org/@aws-cdk%2faws-ec2 425ms
npm http fetch GET 200 https://registry.npmjs.org/jest 423ms
npm http fetch GET 200 https://registry.npmjs.org/aws-cdk 426ms
npm http fetch GET 404 https://registry.npmjs.org/@aws-cdk%2faws-codepipeline-actions 456ms
npm http fetch GET 404 https://registry.npmjs.org/@aws-cdk%2fassert 463ms
npm http fetch GET 404 https://registry.npmjs.org/@aws-cdk%2faws-ssm 497ms
npm http fetch GET 200 https://registry.npmjs.org/@types%2fnode 506ms
npm http fetch GET 404 https://registry.npmjs.org/@aws-cdk%2faws-batch 532ms
npm http fetch GET 200 https://registry.npmjs.org/dotenv 528ms
npm http fetch GET 404 https://registry.npmjs.org/@aws-cdk%2faws-sqs 535ms
npm http fetch GET 404 https://registry.npmjs.org/@aws-cdk%2faws-codepipeline 547ms
npm http fetch GET 404 https://registry.npmjs.org/@aws-cdk%2faws-rds 546ms
npm http fetch GET 200 https://registry.npmjs.org/webpack 586ms
npm http fetch GET 200 https://registry.npmjs.org/source-map-support 618ms
npm http fetch GET 404 https://registry.npmjs.org/@aws-cdk%2faws-appsync 687ms
npm http fetch GET 200 https://registry.npmjs.org/mysql 680ms
npm http fetch GET 404 https://registry.npmjs.org/@aws-cdk%2faws-iam 689ms
npm http fetch GET 404 https://registry.npmjs.org/@aws-cdk%2faws-route53-targets 716ms
npm http fetch GET 404 https://registry.npmjs.org/@aws-cdk%2faws-codebuild 316ms
npm http fetch GET 200 https://registry.npmjs.org/typescript 741ms
npm http fetch GET 404 https://registry.npmjs.org/@aws-cdk%2faws-batch 357ms
npm http fetch GET 404 https://registry.npmjs.org/@aws-cdk%2faws-ec2 461ms
npm http fetch GET 404 https://registry.npmjs.org/@aws-cdk%2faws-ssm 436ms
npm http fetch GET 404 https://registry.npmjs.org/@aws-cdk%2faws-certificatemanager 992ms
npm http fetch GET 404 https://registry.npmjs.org/@aws-cdk%2faws-cloudwatch 1003ms
npm http fetch GET 404 https://registry.npmjs.org/@aws-cdk%2faws-elasticloadbalancingv2 1014ms
npm http fetch GET 200 https://registry.npmjs.org/@types%2fmysql 1016ms
npm http fetch GET 404 https://registry.npmjs.org/@aws-cdk%2faws-appsync 349ms
npm http fetch GET 404 https://registry.npmjs.org/@aws-cdk%2faws-codepipeline 500ms
npm http fetch GET 404 https://registry.npmjs.org/@aws-cdk%2faws-lambda 1101ms
npm http fetch GET 404 https://registry.npmjs.org/@aws-cdk%2faws-iam 443ms
npm http fetch GET 404 https://registry.npmjs.org/@aws-cdk%2faws-route53-targets 415ms
npm http fetch GET 404 https://registry.npmjs.org/@aws-cdk%2faws-ecs 1150ms
npm http fetch GET 404 https://registry.npmjs.org/@aws-cdk%2faws-certificatemanager 292ms
npm http fetch GET 404 https://registry.npmjs.org/@aws-cdk%2fassert 831ms
npm http fetch GET 404 https://registry.npmjs.org/@aws-cdk%2faws-cloudwatch 307ms
npm http fetch GET 404 https://registry.npmjs.org/@aws-cdk%2faws-rds 876ms
npm http fetch GET 404 https://registry.npmjs.org/@aws-cdk%2faws-sqs 1059ms
npm http fetch GET 404 https://registry.npmjs.org/@aws-cdk%2faws-ecs 456ms
npm http fetch GET 404 https://registry.npmjs.org/@aws-cdk%2faws-elasticloadbalancingv2 868ms
npm http fetch GET 404 https://registry.npmjs.org/@aws-cdk%2faws-lambda 861ms
npm http fetch GET 404 https://registry.npmjs.org/@aws-cdk%2fcore 2535ms
npm http fetch GET 404 https://registry.npmjs.org/@aws-cdk%2faws-codepipeline-actions 2085ms
npm http fetch GET 404 https://registry.npmjs.org/@aws-cdk%2fcore 336ms
npm verb stack Error: 404 Not Found - GET https://registry.npmjs.org/@aws-cdk%2faws-codebuild - Not found
npm verb stack     at /Users/dzhuneytahmed/.nvm/versions/node/v13.11.0/lib/node_modules/npm/node_modules/npm-registry-fetch/check-response.js:114:15
npm verb stack     at runMicrotasks (<anonymous>)
npm verb stack     at processTicksAndRejections (internal/process/task_queues.js:97:5)
npm verb statusCode 404
npm verb pkgid @aws-cdk/aws-codebuild@^1.33.0
npm verb cwd /Users/dzhuneytahmed/WebstormProjects/Audiobooke/cdk
npm verb Darwin 19.5.0
npm verb argv "/Users/dzhuneytahmed/.nvm/versions/node/v13.11.0/bin/node" "/Users/dzhuneytahmed/.nvm/versions/node/v13.11.0/bin/npm" "update" "--verbose"
npm verb node v13.11.0
npm verb npm  v6.14.7
npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/@aws-cdk%2faws-codebuild - Not found
npm ERR! 404 
npm ERR! 404  '@aws-cdk/aws-codebuild@^1.33.0' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404 
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.
npm verb exit [ 1, true ]
npm timing npm Completed in 4332ms

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/dzhuneytahmed/.npm/_logs/2020-08-06T09_11_30_268Z-debug.log

```

**Comment by snorberhuis** [comment]
I can confirm that this is happening.

**Comment by Marty-Me** [comment]
It is an NPM scoped package issue:
https://status.npmjs.org/

**Comment by atownsend247** [comment]
Getting the same issue for me also.

**Comment by saksham** [comment]
👍  Facing the same issue.

**Comment by deanforan** [comment]
Getting the same issues myself.

A fix to install the latest version just to keep you moving is to run:
cdk install https://github.com/aws/aws-cdk.git

Takes a bit longer to install the packages and you can't control the version.

**Comment by eladb** [comment]
> A fix to install the latest version just to keep you moving is to run: `cdk install https://github.com/aws/aws-cdk.git`

TIL

**Comment by eladb** [comment]
This was an issue in npm. Seems to be resolved now.

**Comment by MusaNdlala** [comment]
I am getting the same error.
Steps to reproduce 
npm install

[2022-08-15T05_52_00_664Z-debug-0.log](https://github.com/aws/aws-cdk/files/9335341/2022-08-15T05_52_00_664Z-debug-0.log)
