### ISSUE TITLE
[Amazon.CDK.AWS.EC2] SecurityGroup.FromSecurityGroupId not working in .NET

### ISSUE THREAD

**Issue by mark-ashton** [aws/aws-cdk#9483]
Trying to create a `SecurityGroup` construct using the `FromSecurityGroupId` method produces an exception during synthesis:

```
Unhandled exception. Amazon.JSII.Runtime.JsiiException: No stack could be identified for the construct at path cache-sg-sandbox
   at Amazon.JSII.Runtime.Services.Client.TryDeserialize[TResponse](String responseJson)
   at Amazon.JSII.Runtime.Services.Client.ReceiveResponse[TResponse]()
   at Amazon.JSII.Runtime.Services.Client.Send[TRequest,TResponse](TRequest requestObject)
   at Amazon.JSII.Runtime.Services.Client.StaticInvoke(StaticInvokeRequest request)
   at Amazon.JSII.Runtime.Services.Client.StaticInvoke(String fullyQualifiedName, String method, Object[] arguments)
   at Amazon.JSII.Runtime.Deputy.DeputyBase.<>c__DisplayClass16_0`1.<InvokeStaticMethod>b__1(IClient client, Object[] args)
   at Amazon.JSII.Runtime.Deputy.DeputyBase.<InvokeMethodCore>g__GetResult|18_0[T](<>c__DisplayClass18_0`1& )
   at Amazon.JSII.Runtime.Deputy.DeputyBase.InvokeMethodCore[T](JsiiMethodAttribute methodAttribute, Object[] arguments, Func`3 beginFunc, Func`3 invokeFunc)
   at Amazon.JSII.Runtime.Deputy.DeputyBase.InvokeStaticMethod[T](Type type, Type[] parameterTypes, Object[] arguments, String methodName)
   at Amazon.CDK.AWS.EC2.SecurityGroup.FromSecurityGroupId(Construct scope, String id, String securityGroupId, ISecurityGroupImportOptions options)
   at ApiHub.ApiHubStack..ctor(Construct scope, String id, IStackProps props) in C:\dev\surepetcare-cloud-server\cdk\Api.Hub\src\ApiHub\ApiHubStack.cs:line 133
   at ApiHub.Program.Main(String[] args) in C:\dev\surepetcare-cloud-server\cdk\Api.Hub\src\ApiHub\Program.cs:line 21
```

### Reproduction Steps

* Create and deploy a security group in stack A:
```
            var sg = new SecurityGroup(scope,$"cache-sg-{id}",new SecurityGroupProps()
            {
                AllowAllOutbound = true,
                Description = $"Security group for Elasticache on {id}",
                SecurityGroupName = $"cache-sg-{id}",
                Vpc = vpc
            });
```
* Attempt to create a security group in a stack B using the now known security group id:
`var cacheSg = SecurityGroup.FromSecurityGroupId(scope, $"cache-sg-{id}", "sg-0692ece9e1e229166",new SecurityGroupImportOptions(){Mutable = true});`
* `cdk synth` stack B and it produces an exception

### What did you expect to happen?

I'd expected the SG to be available in stack B so that I could modify the `.Connections` based on services created in stack B.

### What actually happened?

An exception

### Environment

  - **CLI Version      :** 1.48.0 (build 6080fa8)
  - **Framework Version:** aws-cli/2.0.14 Python/3.7.7 Windows/10 botocore/2.0.0dev18
  - **Node.js Version:**  v14.2.0
  - **OS               :** Windows 10 version 1909 build 18363.900
  - **Language (Version):** 

### Other

Originally the plan was to export the SG id out of Stack A and then import it into Stack B.

Stack A had this: 

```

            // output the security group id used by the cache for other services to add to
            new CfnOutput(scope, $"export-cache-sg-{id}", new CfnOutputProps()
            {
                ExportName = $"cache-sg-{id}",
                Value = sg.SecurityGroupId
            });
```
and Stack B had this:

```
var cacheSg = SecurityGroup.FromSecurityGroupId(scope, $"cache-sg-{id}", Fn.ImportValue($"cache-sg-{id}"), new SecurityGroupImportOptions() { Mutable = true });
```
... but this produced the exception.
Searching shed no light on the problem, and people trying to achieve the same thing were given code like this which worked for them. To troubleshoot it I replaced the export/import with a static SG id and found I still have the same exception.

--- 

This is :bug: Bug Report

**Comment by mark-ashton** [comment]
Value used for 'scope' in the FromSecurityGroupId was incorrect 🙍‍♂️
