### ISSUE TITLE
[aws-eks] Error when creating Kubernetes Resource

### ISSUE THREAD

**Issue by ten-lac** [aws/aws-cdk#9499]
When trying to create a `KubernetesResource` via a loop, the Cloudformation task errors out with the following message from CloudWatch.

**Log from Cloudwatch**
```
[ERROR] Exception: b'Error from server (NotFound): error when creating "/tmp/manifest.yaml": namespaces "test-space" not found\n'
Traceback (most recent call last):
  File "/var/task/index.py", line 13, in handler
    return apply_handler(event, context)
  File "/var/task/apply/__init__.py", line 43, in apply_handler
    kubectl('apply', manifest_file)
  File "/var/task/apply/__init__.py", line 63, in kubectl
    raise Exception(output)
```

**Log From CloudFormation**
```
6:18:04 PM | CREATE_FAILED        | Custom::AWSCDK-EKS-KubernetesResource | ControlPlane/EKS/m...e/Resource/Default
Failed to create resource. Error: b'Error from server (NotFound): error when creating "/tmp/manifest.yaml": namespaces "test-space"
not found\n'

Logs: /aws/lambda/Tenna-K8S-dv3-awscdkawseksKubectlP-Handler886CB40B-6DC4QWGNAES

at invokeUserFunction (/var/task/framework.js:95:19)
at process._tickCallback (internal/process/next_tick.js:68:7)
```

### Reproduction Steps

**My code that causes the error**

_The_ construct that contains the loop_
```
'use strict';

const { Construct } = require('@aws-cdk/core');
const { DockerRegistrySecret, FargateProfileSet, Namespace } = require('./kubernetes');

class Organization extends Construct {
    constructor(scope, id, props) {
        super(scope, id, props);

        const {
            options: { controlPlane, permission, namespaces: namespacesOptions = [] }
        } = props;

        const serviceAccountName = 'appmesh-default';

        const namespaces = namespacesOptions.forEach((namespaceOption) => {
            const namespace = new Namespace(this, `Namespace-${namespaceOption.name}`, {
                cluster: controlPlane.cluster,
                namespaceName: namespaceOption.name,
                withAppMesh: true
            });

            const dockerRegistrySecret = new DockerRegistrySecret(this, `DockerRegistry-${namespaceOption.name}`, {
                controlPlane,
                namespace: namespaceOption.name,
                dockerRegistries: namespaceOption.dockerRegistries
            });

            dockerRegistrySecret.node.addDependency(namespace);

            const fargateProfileSet = new FargateProfileSet(this, `FargateProfileSet-${namespaceOption.name}`, {
                controlPlane,
                permission,
                namespace: namespaceOption.name,
                dockerRegistries: namespaceOption.dockerRegistries
            });

            permission.decorateOrganizationWorkloadServiceAccount(
                controlPlane.cluster.addServiceAccount(`SA-${namespaceOption.name}-${serviceAccountName}`, {
                    name: serviceAccountName,
                    namespace: namespaceOption.name
                })
            );

            return {
                namespace,
                dockerRegistrySecret,
                fargateProfileSet
            };
        });

        Object.assign(this, { namespaces });
    }
}

module.exports = Organization;
```

_The construct that creates the `KubernetesResource`._
```
'use strict';

const { Construct } = require('@aws-cdk/core');
const { KubernetesResource } = require('@aws-cdk/aws-eks');
const Constants = require('../../constants');

class Namespace extends Construct {
    constructor(scope, id, props) {
        super(scope, id, props);

        const { cluster, namespaceName, withAppMesh = false, meshSelector = Constants.GLOBAL_MESH_SELECTOR } = props;

        const appMeshLabels = withAppMesh
            ? { mesh: meshSelector, 'appmesh.k8s.aws/sidecarInjectorWebhook': 'enabled' }
            : {};

        const manifest = cluster.addResource(`${namespaceName}-namespace-manifest`, {
            apiVersion: 'v1',
            kind: 'Namespace',
            metadata: {
                name: namespaceName,
                labels: {
                    name: namespaceName,
                    ...appMeshLabels
                }
            }
        });

        Object.assign(this, { manifest });
    }
}

module.exports = Namespace;

```

### What did you expect to happen?

I expect no errors.

### Environment

  - **CLI Version      :
```
> cdk version
1.56.0 (build c1c174d)
```
  - **Framework Version: 
```
> npm ls --depth=0
cdk-kubernetes@0.1.0 /Users/lac/git/tenna-llc/cdk-kubernetes
├── @aws-cdk/assert@1.56.0
├── @aws-cdk/aws-appmesh@1.56.0
├── @aws-cdk/aws-ec2@1.56.0
├── @aws-cdk/aws-eks@1.56.0
├── @aws-cdk/aws-iam@1.56.0
├── @aws-cdk/cdk@0.36.1
├── @aws-cdk/core@1.56.0
├── @aws-cdk/custom-resources@1.56.0
├── @hapi/eslint-config-hapi@13.0.2
├── @hapi/eslint-plugin-hapi@4.3.5
├── aws-cdk@1.56.0
├── config@3.3.1
├── doctoc@1.4.0
├── eslint@7.6.0
├── eslint-config-prettier@6.11.0
├── eslint-plugin-prettier@3.1.4
├── jest@25.5.4
└── prettier@2.0.5
```
  - **Node.js Version:** 
```
> node --version
v12.18.2
```
  - **OS               : macOS 10.15.6
  - **Language (Version):** 

### Other

--- 

This is :bug: Bug Report

**Comment by ten-lac** [comment]
Nevermind, this isn't a bug with the framework.  It was a bug in my code.  I needed to add a `node.addDependency(...)` relation between a resource that was using the namespace.  It was so obvious once I really dug into it.
