### ISSUE TITLE
[aws-eks] cannot define eks cluster and network in different stacks

### ISSUE THREAD

**Issue by alexey-boyko** [aws/aws-cdk#9536]
in v1.57.0 stack reference doesn't work, everything is fine in v1.56.0

### Reproduction Steps

```
network_sg_stack = NetworkSgStack(
    scope=app,
    id='sg-stack-' + environment,
    env=env,
    environment=environment,
    vpc_id=app.node.try_get_context(target_env)['vpc_id'],
)

eks_stack = EksStack(
    scope=app,
    id='eks-stack-' + environment,
    env=env,
    environment=environment,
    vpc=network_sg_stack.vpc,
    subnet_a_eks=network_sg_stack.subnet_c_eks,
    subnet_b_eks=network_sg_stack.subnet_b_eks,
    subnet_c_eks=network_sg_stack.subnet_c_eks,
    cluster_version=aws_eks.KubernetesVersion.V1_16
    tags=tags,
    eks_control_plane_role=iam_stack.eks_control_plane_role,
    eks_control_plane_sg=network_sg_stack.eks_control_plane_sg,
)
```
-->

### What actually happened?
```
jsii.errors.JavaScriptError: 
  Error: 'sg-stack-develop-cdk2' depends on 'edp-eks-stack-develop-cdk2' (sg-stack-develop-cdk2 -> eks-stack-develop-cdk2/cluster/KubectlProviderSecurityGroup/Resource.GroupId). Adding this dependency (stack-develop-cdk2 -> sg-stack-develop-cdk2/eks-control-plane-sg-develop-cdk2/Resource.GroupId) would create a cyclic reference.
      at Stack._addAssemblyDependency (/tmp/jsii-kernel-mpylii/node_modules/@aws-cdk/core/lib/stack.js:415:19)
      at Object.addDependency (/tmp/jsii-kernel-mpylii/node_modules/@aws-cdk/core/lib/deps.js:47:24)
      at Stack.addDependency (/tmp/jsii-kernel-mpylii/node_modules/@aws-cdk/core/lib/stack.js:194:16)
      at resolveValue (/tmp/jsii-kernel-mpylii/node_modules/@aws-cdk/core/lib/private/refs.js:85:14)
      at Object.resolveReferences (/tmp/jsii-kernel-mpylii/node_modules/@aws-cdk/core/lib/private/refs.js:27:30)
      at Object.prepareApp (/tmp/jsii-kernel-mpylii/node_modules/@aws-cdk/core/lib/private/prepare-app.js:34:16)
      at Object.synthesize (/tmp/jsii-kernel-mpylii/node_modules/@aws-cdk/core/lib/private/synthesis.js:16:19)
      at App.synth (/tmp/jsii-kernel-mpylii/node_modules/@aws-cdk/core/lib/stage.js:78:41)
      at /home/alexey/.local/lib/python3.7/site-packages/jsii/_embedded/jsii/jsii-runtime.js:7746:51
      at Kernel._wrapSandboxCode (/home/alexey/.local/lib/python3.7/site-packages/jsii/_embedded/jsii/jsii-runtime.js:8398:19)
      at /home/alexey/.local/lib/python3.7/site-packages/jsii/_embedded/jsii/jsii-runtime.js:7746:25
      at Kernel._ensureSync (/home/alexey/.local/lib/python3.7/site-packages/jsii/_embedded/jsii/jsii-runtime.js:8371:20)
      at Kernel.invoke (/home/alexey/.local/lib/python3.7/site-packages/jsii/_embedded/jsii/jsii-runtime.js:7745:26)
      at KernelHost.processRequest (/home/alexey/.local/lib/python3.7/site-packages/jsii/_embedded/jsii/jsii-runtime.js:7446:28)
      at KernelHost.run (/home/alexey/.local/lib/python3.7/site-packages/jsii/_embedded/jsii/jsii-runtime.js:7384:14)
      at Immediate._onImmediate (/home/alexey/.local/lib/python3.7/site-packages/jsii/_embedded/jsii/jsii-runtime.js:7387:37)
      at processImmediate (internal/timers.js:456:21)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "app.py", line 105, in <module>
    app.synth()
  File "/home/alexey/.local/lib/python3.7/site-packages/aws_cdk/core/__init__.py", line 11426, in synth
    return jsii.invoke(self, "synth", [options])
  File "/home/alexey/.local/lib/python3.7/site-packages/jsii/_kernel/__init__.py", line 113, in wrapped
    return _recursize_dereference(kernel, fn(kernel, *args, **kwargs))
  File "/home/alexey/.local/lib/python3.7/site-packages/jsii/_kernel/__init__.py", line 296, in invoke
    return _callback_till_result(self, response, InvokeResponse)
  File "/home/alexey/.local/lib/python3.7/site-packages/jsii/_kernel/__init__.py", line 181, in _callback_till_result
    response = kernel.sync_complete(response.cbid, None, result, response_type)
  File "/home/alexey/.local/lib/python3.7/site-packages/jsii/_kernel/__init__.py", line 339, in sync_complete
    response_type=response_type
  File "/home/alexey/.local/lib/python3.7/site-packages/jsii/_kernel/providers/process.py", line 369, in sync_complete
    resp = self._process.send(_CompleteRequest(complete=request), response_type)
  File "/home/alexey/.local/lib/python3.7/site-packages/jsii/_kernel/providers/process.py", line 318, in send
    raise JSIIError(resp.error) from JavaScriptError(resp.stack)
jsii.errors.JSIIError: 'sg-stack-develop-cdk2' depends on 'eks-stack-develop-cdk2' (sg-stack-develop-cdk2 -> eks-stack-develop-cdk2/cluster/KubectlProviderSecurityGroup/Resource.GroupId). Adding this dependency (eks-stack-develop-cdk2 -> sg-stack-develop-cdk2/eks-control-plane-sg-develop-cdk2/Resource.GroupId) would create a cyclic reference.
Subprocess exited with error 1
```

### Environment

  - **CLI Version      *1.57.0*
  - **Framework Version:*1.57.0*
  - **Node.js Version:*v12.18.1*
  - **OS               :ubuntu 18.04
  - **Language (Version):*Python 3.7.5*

### Other

--- 

This is :bug: Bug Report

**Comment by alexey-boyko** [comment]
I see you defined it as a bug in eks but it doesn't work for any reference between stacks

**Comment by alexey-boyko** [comment]
actually you are right, when i changes code to 
```  
       # Control plane
        self.cluster = aws_eks.LegacyCluster(
            scope=self,
            id='cluster',
            cluster_name="cluster-" + environment,
            # kubectl_enabled=True,
``` 

using  aws_eks.LegacyCluster  and commenting kubectl_enabled=False and now works fine,looks like related to changes in v1.57.0 related to eks construct,  would be nice to have this fix. thanks

**Comment by iliapolo** [comment]
@alexey-boyko Could you please share exactly which resources are you creating in each stack?

**Comment by alexey-boyko** [comment]
@iliapolo do you want me to share the code in archive?

**Comment by iliapolo** [comment]
@alexey-boyko Not archive. Just paste the relevant resources. Specifically, i'm interested in exactly how are you instantiating the subnets and the VPC in the `NetworkSgStack`.

**Comment by alexey-boyko** [comment]
app.py
```
#!/usr/bin/env python3

from aws_cdk import (
    core,
    aws_eks,
    aws_ec2,
)

from eks_auth_mapping_stack import EksAuth
from eks_control_plane_stack import EksStack
from eks_worker_nodes_stack import EksWorkerNodesStack
from iam_stack import IamStack
from lib.permission_boundary import PermissionBoundaryAspect
from network_sg_stack import NetworkSgStack

app = core.App()

# Define target environment from input  cdk synth -c env=develop
target_env = app.node.try_get_context('environment')
# Define environment  variables
account = app.node.try_get_context(target_env)['account']
region = app.node.try_get_context(target_env)['region']
env = core.Environment(account=account, region=region)
environment = app.node.try_get_context(target_env)['name']
permissions_boundary = app.node.try_get_context(target_env)['permissions_boundary']
tags = {
    'Project': 'edp',
    'Environment': environment,
}

# Declare stacks using CDK

network_sg_stack = NetworkSgStack(
    scope=app,
    id='edp-sg-stack-' + environment,
    env=env,
    environment=environment,
    # Import values from cf output
    # core.Fn.import_value("vpc-VpcId") track this issue https://github.com/aws/aws-cdk/issues/4096
    vpc_id=app.node.try_get_context(target_env)['vpc_id'],
)

iam_stack = IamStack(
    scope=app,
    id='edp-iam-stack-' + environment,
    env=env,
    environment=environment,
)

eks_stack = EksStack(
    scope=app,
    id='edp-eks-stack-' + environment,
    env=env,
    environment=environment,
    vpc=network_sg_stack.vpc,
    subnet_a_eks=network_sg_stack.subnet_c_eks,
    subnet_b_eks=network_sg_stack.subnet_b_eks,
    subnet_c_eks=network_sg_stack.subnet_c_eks,
    cluster_version=aws_eks.KubernetesVersion.V1_16,  # hardcoded du to new cdk update
    tags=tags,
    eks_control_plane_role=iam_stack.eks_control_plane_role,
    eks_control_plane_sg=network_sg_stack.eks_control_plane_sg,
)

# Apply  permissions_boundary globally to all iam roles using hacky library until implemented by aws cdk
app.node.apply_aspect(PermissionBoundaryAspect(permissions_boundary))

# Synthesize!
app.synth()
```
network_sg_stack.py
```
