### ISSUE TITLE
[s3] Mismatch between Cloudformation supported parameter and CDK required property

### ISSUE THREAD

**Issue by raphael-riel** [aws/aws-cdk#9688]
`s3.CfnBucket.replicationConfiguration.rules[].destination.metrics.eventThreshold` is Required but not supported by CloudFormation.

(Note: Using `s3.CfnBucket` since `replicationConfiguration` is not available otherwise.

### Reproduction Steps

```
import * as iam from "@aws-cdk/aws-iam";
import * as s3 from "@aws-cdk/aws-s3";
import * as cdk from "@aws-cdk/core";

export class TestStack extends cdk.Stack {

    constructor(scope: cdk.App, id: string, props?: cdk.StackProps) {
        super(scope, id, props);

        // RESOURCES

        const repBucket = new s3.Bucket(this,`RepBucket`, {
                versioned: true,
            },
        );

        const role = new iam.Role(this, "BackupRole", {
            assumedBy: new iam.ServicePrincipal("s3"),
        });

        const bucket = new s3.CfnBucket(
            this,
            `Bucket`,
            {
                replicationConfiguration: {
                    role: role.roleArn,
                    rules: [
                        {
                            destination: {
                                bucket: repBucket.bucketArn,
                                metrics: {
                                    eventThreshold: {
                                        minutes: 15
                                    },
                                    status: "Enabled",
                                },
                            },
                            status: "Enabled",
                        },
                    ],
                },
            }
        );
    }
}
```

### What did you expect to happen?

I Expect the property `eventThreshold` being optional.

### What actually happened?

When used as-is:
![image](https://user-images.githubusercontent.com/474697/90183623-d27abc00-dd81-11ea-8baf-7cc4360e78ba.png)

When Trying to trick CDK's Typescript code to allow `undefined` on the property:
![image](https://user-images.githubusercontent.com/474697/90182448-fb01b680-dd7f-11ea-9bec-a2f6e2aabe4d.png)

![image](https://user-images.githubusercontent.com/474697/90182461-00f79780-dd80-11ea-94f3-f95943c7bd90.png)
Ref: https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-s3-bucket-metrics.html#cfn-s3-bucket-metrics-eventthreshold

Logs:
```
4:26:40 p.m. | CREATE_FAILED        | AWS::S3::Bucket    | Bucket83908E77
Metrics is not supported in this region. (Service: Amazon S3; Status Code: 400; Error Code: InvalidRequest; Request ID: 056EDAA68E0EF9B9; S3 Extended Request ID: IAOSjFKe7jzSeSTU0eQ+fMvLPfjl8QTCibd0ydU2O+5VzRszTgDIZRK36hfVjEeQPwt2ZuVMVjk=)

	new Bucket (/Users/rriel/projects/poka/data-ingestion-api-events/node_modules/@aws-cdk/aws-s3/lib/bucket.ts:1205:22)
	\_ new TestStack (/Users/rriel/projects/poka/data-ingestion-api-events/lib/test-stack.ts:32:24)
	\_ Object.<anonymous> (/Users/rriel/projects/poka/data-ingestion-api-events/bin/app.ts:22:1)
	\_ Module._compile (internal/modules/cjs/loader.js:1176:30)
	\_ Module.m._compile (/Users/rriel/projects/poka/data-ingestion-api-events/node_modules/ts-node/src/index.ts:858:23)
	\_ Module._extensions..js (internal/modules/cjs/loader.js:1196:10)
	\_ Object.require.extensions.<computed> [as .ts] (/Users/rriel/projects/poka/data-ingestion-api-events/node_modules/ts-node/src/index.ts:861:12)
	\_ Module.load (internal/modules/cjs/loader.js:1040:32)
	\_ Function.Module._load (internal/modules/cjs/loader.js:929:14)
	\_ Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)
	\_ main (/Users/rriel/projects/poka/data-ingestion-api-events/node_modules/ts-node/src/bin.ts:227:14)
	\_ Object.<anonymous> (/Users/rriel/projects/poka/data-ingestion-api-events/node_modules/ts-node/src/bin.ts:513:3)
	\_ Module._compile (internal/modules/cjs/loader.js:1176:30)
	\_ Object.Module._extensions..js (internal/modules/cjs/loader.js:1196:10)
	\_ Module.load (internal/modules/cjs/loader.js:1040:32)
	\_ Function.Module._load (internal/modules/cjs/loader.js:929:14)
	\_ Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)
	\_ internal/main/run_main_module.js:17:47


 ❌  Test failed: Error: The stack named Test failed creation, it may need to be manually deleted from the AWS console: ROLLBACK_COMPLETE
    at Object.waitForStackDeploy (/Users/rriel/projects/poka/data-ingestion-api-events/node_modules/aws-cdk/lib/api/util/cloudformation.ts:292:11)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at Object.deployStack (/Users/rriel/projects/poka/data-ingestion-api-events/node_modules/aws-cdk/lib/api/deploy-stack.ts:266:26)
    at CdkToolkit.deploy (/Users/rriel/projects/poka/data-ingestion-api-events/node_modules/aws-cdk/lib/cdk-toolkit.ts:181:24)
    at main (/Users/rriel/projects/poka/data-ingestion-api-events/node_modules/aws-cdk/bin/cdk.ts:268:16)
    at initCommandLine (/Users/rriel/projects/poka/data-ingestion-api-events/node_modules/aws-cdk/bin/cdk.ts:188:9)
The stack named Test failed creation, it may need to be manually deleted from the AWS console: ROLLBACK_COMPLETE
```

### Environment

  - **CLI Version      :** 1.57.0
  - **Framework Version:**
  - **Node.js Version:** v14.1.0
  - **OS               :** macOS
  - **Language (Version):** TypeScript (Probably all)

### Other

Seems to be a problem between CloudFormation's definition and the generated code.
I tried to manually "fix" the generated code, but without success.

--- 

This is :bug: Bug Report

**Comment by raphael-riel** [comment]
Ok, false alert. `Metrics` is not supported by CloudFormation at all. Misread the documentation 😛
