### ISSUE TITLE
[aws-s3-assets] ci build fails due to docker hub rate limit

### ISSUE THREAD

**Issue by bvtujo** [aws/aws-cdk#9803]
## Context

I'm trying to merge #8467 and just encountered what I hope to be a transient failure in CI due to a Docker Hub rate limit. The CI project is not able to complete its build because the aws-s3-assets tests rely on a repository which is rate limited. 

The relevant build logs: 

> AWS CodeBuild CI Report
> CodeBuild project: AutoBuildProject6AEA49D1-qxepHUsryhcu
> Commit ID: [c4fb1d7](https://github.com/aws/aws-cdk/commit/c4fb1d7d3070d24b174e6c440e4de8b5a8a15f0b)
> Result: FAILED
> [Build Logs](https://6sc75qyfl7.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=9eaab505-180c-4a8c-86fc-b9579c6dab3e%2Fbuild.log) (available for 30 days)
> Powered by github-codebuild-logs, available on the AWS Serverless Application Repository

[Link to Codebuild Build](https://us-east-1.console.aws.amazon.com/codebuild/home?region=us-east-1#/builds/AutoBuildProject6AEA49D1-qxepHUsryhcu:9eaab505-180c-4a8c-86fc-b9579c6dab3e/view/new)

### Environment
  - AWS Codebuild (CDK CI project)
  - Commit ID `c4fb1d7`
  - Yarn version 1.22.4

### Other information
[More information on Docker's rate limit](https://docs.docker.com/docker-hub/download-rate-limit/)
And their [suggested solution](https://aws.amazon.com/blogs/devops/how-to-use-docker-images-from-a-private-registry-in-aws-codebuild-for-your-build-environment/) for running Codebuild as a logged-in Dockerhub user.

#### Detailed logs
```
@aws-cdk/aws-glue: PASS test/table.test.js (7.728s)
time="2020-08-18T16:38:27.515200112Z" level=error msg="Not continuing with pull after error: error pulling image configuration: toomanyrequests: Too Many Requests. Please see https://docs.docker.com/docker-hub/download-rate-limit/"
@aws-cdk/aws-glue: =============================== Coverage summary ===============================
@aws-cdk/aws-glue: Statements   : 97.09% ( 167/172 )
@aws-cdk/aws-glue: Branches     : 87.32% ( 62/71 )
@aws-cdk/aws-glue: Functions    : 100% ( 29/29 )
@aws-cdk/aws-glue: Lines        : 98.82% ( 167/169 )
@aws-cdk/aws-glue: ================================================================================
@aws-cdk/aws-glue: Test Suites: 3 passed, 3 total
@aws-cdk/aws-glue: Tests:       61 passed, 61 total
@aws-cdk/aws-glue: Snapshots:   0 total
@aws-cdk/aws-glue: Time:        8.462s
@aws-cdk/aws-glue: Ran all test suites.
@aws-cdk/aws-s3-assets: /codebuild/output/src092728685/src/github.com/aws/aws-cdk/packages/@aws-cdk/core/lib/bundling.js:103
@aws-cdk/aws-s3-assets:             throw new Error(`[Status ${proc.status}] stdout: ${(_b = proc.stdout) === null || _b === void 0 ? void 0 : _b.toString().trim()}\n\n\nstderr: ${(_c = proc.stderr) === null || _c === void 0 ? void 0 : _c.toString().trim()}`);
@aws-cdk/aws-s3-assets:             ^
@aws-cdk/aws-s3-assets: Error: [Status 1] stdout: 
@aws-cdk/aws-s3-assets: stderr: Sending build context to Docker daemon  2.048kB
@aws-cdk/aws-s3-assets: Step 1/2 : FROM alpine
@aws-cdk/aws-s3-assets: latest: Pulling from library/alpine
@aws-cdk/aws-s3-assets: df20fa9351a1: Pulling fs layer
@aws-cdk/aws-s3-assets: error pulling image configuration: toomanyrequests: Too Many Requests. Please see https://docs.docker.com/docker-hub/download-rate-limit/
@aws-cdk/aws-s3-assets:     at dockerExec (/codebuild/output/src092728685/src/github.com/aws/aws-cdk/packages/@aws-cdk/core/lib/bundling.js:103:19)
@aws-cdk/aws-s3-assets:     at Function.fromAsset (/codebuild/output/src092728685/src/github.com/aws/aws-cdk/packages/@aws-cdk/core/lib/bundling.js:34:24)
@aws-cdk/aws-s3-assets:     at new TestStack (/codebuild/output/src092728685/src/github.com/aws/aws-cdk/packages/@aws-cdk/aws-s3-assets/test/integ.assets.bundling.lit.js:14:51)
@aws-cdk/aws-s3-assets:     at Object.<anonymous> (/codebuild/output/src092728685/src/github.com/aws/aws-cdk/packages/@aws-cdk/aws-s3-assets/test/integ.assets.bundling.lit.js:28:1)
@aws-cdk/aws-s3-assets:     at Module._compile (internal/modules/cjs/loader.js:778:30)
@aws-cdk/aws-s3-assets:     at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
@aws-cdk/aws-s3-assets:     at Module.load (internal/modules/cjs/loader.js:653:32)
@aws-cdk/aws-s3-assets:     at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
@aws-cdk/aws-s3-assets:     at Function.Module._load (internal/modules/cjs/loader.js:585:3)
@aws-cdk/aws-s3-assets:     at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)
@aws-cdk/aws-s3-assets: Error: Command exited with status 1
@aws-cdk/aws-s3-assets:     at exec (/codebuild/output/src092728685/src/github.com/aws/aws-cdk/tools/cdk-integ-tools/lib/integ-helpers.js:335:15)
@aws-cdk/aws-s3-assets:     at IntegrationTest.cdkSynthFast (/codebuild/output/src092728685/src/github.com/aws/aws-cdk/tools/cdk-integ-tools/lib/integ-helpers.js:88:19)
@aws-cdk/aws-s3-assets:     at main (/codebuild/output/src092728685/src/github.com/aws/aws-cdk/tools/cdk-integ-tools/bin/cdk-integ-assert.js:19:33)
@aws-cdk/aws-s3-assets: Error: cdk-integ-assert exited with error code 1
@aws-cdk/aws-s3-assets: Tests failed. Total time (12.1s) | /codebuild/output/src092728685/src/github.com/aws/aws-cdk/node_modules/jest/bin/jest.js (9.3s) | cdk-integ-assert (2.8s)
@aws-cdk/aws-s3-assets: !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
@aws-cdk/aws-s3-assets: npm ERR! Test failed.  See above for more details.
@aws-cdk/aws-s3-assets: error Command failed with exit code 1.
@aws-cdk/aws-s3-assets: Verifying integ.assets.bundling.lit.js against integ.assets.bundling.lit.expected.json ... info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
lerna ERR! yarn run build+test exited 1 in '@aws-cdk/aws-s3-assets'
lerna WARN complete Waiting for 3 child processes to exit. CTRL-C to exit immediately.
```

**Comment by bvtujo** [comment]
Seems like this is also affecting #9800 and #9802. It does not affect the CI build on #9798, which puts the origin of this issue sometime between 7:00AM PDT and 9:30AM PDT.

**Comment by iliapolo** [comment]
Thanks @bvtujo - We are checking this.
