### ISSUE TITLE
[ECR] Creation of ECR with a name is being passed as a token cause CDK to error out.   

### ISSUE THREAD

**Issue by gfina** [aws/aws-cdk#9806]
## :question: General Issue

Please see the stack trace below.    A variable which needs to be passed to environment variables is not working it's a token.   causing CDK to fail.    Snippet of code is below as well as the stack trace from CDK.  

### Environment

  - **CDK CLI Version:** 
  - **Module Version:** aws-cdk.aws-ecr                     1.59.0 
                                        aws-cdk.aws-codebuild               1.59.0
  - **Node.js Version:** v10.16.3
  - **OS:**   OSX Mojave 
  - **Language:**  Python  

### Code 
```py
        ecr_repo = ecr.Repository(self,'masterbuilder4-ECRRepo')
        environment = {
            'build_image': codebuild.LinuxBuildImage.from_asset(self, id='Custom', directory='./dockerAssets.d'),
            'privileged': True}

        environmentvariables ={
            'ECR_REPO_URI': ecr_repo.repository_uri
        }

        cdk_build = codebuild.PipelineProject(self,"Cdkbuild", build_spec=buildspec, environment=environment,
                                              environment_variables=environmentvariables)`
```

### Other information
```
8c85903d2f80:masterbuilder finagreg$ cdk synth PipelineEKSStack
(node:90952) ExperimentalWarning: The fs.promises API is experimental
jsii.errors.JavaScriptError: 
  Error: Expected object reference, got "${Token[TOKEN.736]}.dkr.ecr.${Token[TOKEN.735]}.${Token[AWS::URLSuffix.1]}/${Token[TOKEN.729]}"
      at Object.deserialize (/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/jsii/_embedded/jsii/jsii-runtime.js:6915:23)
      at Kernel._toSandbox (/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/jsii/_embedded/jsii/jsii-runtime.js:8304:61)
      at mapValues (/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/jsii/_embedded/jsii/jsii-runtime.js:6862:74)
      at mapValues (/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/jsii/_embedded/jsii/jsii-runtime.js:7219:27)
      at Object.deserialize (/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/jsii/_embedded/jsii/jsii-runtime.js:6862:28)
      at Kernel._toSandbox (/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/jsii/_embedded/jsii/jsii-runtime.js:8304:61)
      at mapValues (/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/jsii/_embedded/jsii/jsii-runtime.js:6947:29)
      at mapValues (/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/jsii/_embedded/jsii/jsii-runtime.js:7219:27)
      at Object.deserialize (/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/jsii/_embedded/jsii/jsii-runtime.js:6943:20)
      at Kernel._wrapSandboxCode (/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/jsii/_embedded/jsii/jsii-runtime.js:8398:19)
      at Kernel._create (/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/jsii/_embedded/jsii/jsii-runtime.js:7922:26)
      at Kernel.create (/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/jsii/_embedded/jsii/jsii-runtime.js:7666:21)
      at KernelHost.processRequest (/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/jsii/_embedded/jsii/jsii-runtime.js:7446:28)
      at KernelHost.run (/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/jsii/_embedded/jsii/jsii-runtime.js:7384:14)
      at Immediate.setImmediate [as _onImmediate] (/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/jsii/_embedded/jsii/jsii-runtime.js:7387:37)
      at runCallback (timers.js:705:18)
      at tryOnImmediate (timers.js:676:5)
      at processImmediate (timers.js:658:5)
```

The above exception was the direct cause of the following exception:

```console
Traceback (most recent call last):
  File "app.py", line 15, in <module>
    PipelineStack(app, "PipelineEKSStack", repo_name="blue-green-repo", branch="master",  cluster=cluster1)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/jsii/_runtime.py", line 66, in __call__
    inst = super().__call__(*args, **kwargs)
  File "/Users/finagreg/code/masterbuilder/masterbuilder/pipeline_stack.py", line 44, in __init__
    environment_variables=environmentvariables)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/jsii/_runtime.py", line 66, in __call__
    inst = super().__call__(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/aws_cdk/aws_codebuild/__init__.py", line 10265, in __init__
    jsii.create(PipelineProject, self, [scope, id, props])
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/jsii/_kernel/__init__.py", line 229, in create
    interfaces=[iface.__jsii_type__ for iface in getattr(klass, "__jsii_ifaces__", [])],
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/jsii/_kernel/providers/process.py", line 333, in create
    return self._process.send(request, CreateResponse)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/jsii/_kernel/providers/process.py", line 318, in send
    raise JSIIError(resp.error) from JavaScriptError(resp.stack)
jsii.errors.JSIIError: Expected object reference, got "${Token[TOKEN.736]}.dkr.ecr.${Token[TOKEN.735]}.${Token[AWS::URLSuffix.1]}/${Token[TOKEN.729]}"
Subprocess exited with error 1
```

**Comment by hencrice** [comment]
I ran into this issue as well

**Comment by hencrice** [comment]
I suspect that you might need to write `"ECR_REPO_URI": BuildEnvironmentVariable(value=<value>)`, where `BuildEnvironmentVariable` is https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-codebuild.BuildEnvironmentVariable.html
