### ISSUE TITLE
[core] overriding getAvailabilityZones causes crash when accessing super method 

### ISSUE THREAD

**Issue by chris-bannister-privitar** [aws/aws-cdk#9822]
In Java when overriding the `getAvailabilityZones` method, calling `super.getAvailabilityZones()` on the Stack causes a `software.amazon.jsii.JsiiException` exception`. This worked in previous versions of CDK, at least 1.57. 

### Reproduction Steps

```java
package com.myorg;

import software.amazon.awscdk.core.Construct;
import software.amazon.awscdk.core.Stack;
import software.amazon.awscdk.core.StackProps;
import java.util.Arrays;
import java.util.List;

public class CdkTestStack extends Stack {
    public CdkTestStack(final Construct scope, final String id) {
        this(scope, id, null);
    }

    public List<String> getAvailabilityZones() {
        return Arrays.asList("test");
    };

    public CdkTestStack(final Construct scope, final String id, final StackProps props) {
        super(scope, id, props);
	System.out.println(getAvailabilityZones());
	System.out.println(super.getAvailabilityZones());

        // The code that defines your stack goes here
    }
}
```
### What did you expect to happen?

`cdk synth` works corectly

### What actually happened?

```
Caused by: software.amazon.jsii.JsiiException: Got 'undefined' for non-optional instance of {"docs":{"remarks":"If the stack is environment-agnostic (either account and/or region are\ntokens), this property will return an array with 2 tokens that will resolve\nat deploy-time to the first two availability zones returned from CloudFormation's\n`Fn::GetAZs` intrinsic function.\n\nIf they are not available in the context, returns a set of dummy values and\nreports them as missing, and let the CLI resolve them by calling EC2\n`DescribeAvailabilityZones` on the target environment.\n\nTo specify a different strategy for selecting availability zones override this method.","stability":"stable","summary":"Returns the list of AZs that are available in the AWS environment (account/region) associated with this stack."},"immutable":true,"locationInModule":{"filename":"lib/stack.ts","line":590},"name":"availabilityZones","type":{"collection":{"elementtype":{"primitive":"string"},"kind":"array"}}}
Error: Got 'undefined' for non-optional instance of {"docs":{"remarks":"If the stack is environment-agnostic (either account and/or region are\ntokens), this property will return an array with 2 tokens that will resolve\nat deploy-time to the first two availability zones returned from CloudFormation's\n`Fn::GetAZs` intrinsic function.\n\nIf they are not available in the context, returns a set of dummy values and\nreports them as missing, and let the CLI resolve them by calling EC2\n`DescribeAvailabilityZones` on the target environment.\n\nTo specify a different strategy for selecting availability zones override this method.","stability":"stable","summary":"Returns the list of AZs that are available in the AWS environment (account/region) associated with this stack."},"immutable":true,"locationInModule":{"filename":"lib/stack.ts","line":590},"name":"availabilityZones","type":{"collection":{"elementtype":{"primitive":"string"},"kind":"array"}}}
    at nullAndOk (/private/var/folders/gm/ld3w53xd25v2pjcllsv6wtqh0000gn/T/jsii-java-runtime7237114721820270231/jsii-runtime.js:7202:15)
    at Object.serialize (/private/var/folders/gm/ld3w53xd25v2pjcllsv6wtqh0000gn/T/jsii-java-runtime7237114721820270231/jsii-runtime.js:6820:17)
    at Kernel._fromSandbox (/private/var/folders/gm/ld3w53xd25v2pjcllsv6wtqh0000gn/T/jsii-java-runtime7237114721820270231/jsii-runtime.js:8339:61)
    at Kernel.get (/private/var/folders/gm/ld3w53xd25v2pjcllsv6wtqh0000gn/T/jsii-java-runtime7237114721820270231/jsii-runtime.js:7729:26)
    at KernelHost.processRequest (/private/var/folders/gm/ld3w53xd25v2pjcllsv6wtqh0000gn/T/jsii-java-runtime7237114721820270231/jsii-runtime.js:7456:28)
    at KernelHost.run (/private/var/folders/gm/ld3w53xd25v2pjcllsv6wtqh0000gn/T/jsii-java-runtime7237114721820270231/jsii-runtime.js:7394:14)
    at Immediate._onImmediate (/private/var/folders/gm/ld3w53xd25v2pjcllsv6wtqh0000gn/T/jsii-java-runtime7237114721820270231/jsii-runtime.js:7397:37)
    at processImmediate (internal/timers.js:458:21)
    at software.amazon.jsii.JsiiRuntime.processErrorResponse (JsiiRuntime.java:119)
    at software.amazon.jsii.JsiiRuntime.requestResponse (JsiiRuntime.java:91)
    at software.amazon.jsii.JsiiClient.getPropertyValue (JsiiClient.java:111)
    at software.amazon.jsii.JsiiObject.jsiiGet (JsiiObject.java:240)
    at software.amazon.awscdk.core.Stack.getAvailabilityZones (Stack.java:489)
    at com.myorg.CdkTestStack.<init> (CdkTestStack.java:21)
    at com.myorg.CdkTestStack.<init> (CdkTestStack.java:11)
    at com.myorg.CdkTestApp.main (CdkTestApp.java:11)
    at sun.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke (Method.java:498)
    at org.codehaus.mojo.exec.ExecJavaMojo$1.run (ExecJavaMojo.java:282)
    at java.lang.Thread.run (Thread.java:748)
```
### Environment

  - **CLI Version      : 1.59.0 (build 1d082f4)**
  - **Framework Version: 1.59.0**
  - **Node.js Version: v14.8.0** 
  - **OS               : OSX 10.15.6 **
  - **Language (Version):** openjdk version "1.8.0_265"

### Other

--- 

This is :bug: Bug Report

**Comment by RomainMuller** [comment]
Looks like a bug in `jsii`... I'm investigating...

**Comment by RomainMuller** [comment]
At this point I'm pretty sure the *real* reason why the behavior changed is because you've upgraded `node` in between, and the new `node` version behaves differently with respects to `Object.getOwnPropertyDescriptor` (which used to return a descriptor, and now returns `undefined` until we actually start searching in parent prototypes).

I'm not certain whether this is a bug in `node` or not, and it does not matter - the prototype tree crawling should be done as otherwise, extending a property from a transitive superclass would yield the exact problem you are now consistently facing.
