### ISSUE TITLE
[ecr] repositoryName must be lowercase but this isn't enforced

### ISSUE THREAD

**Issue by Jerry-AWS** [aws/aws-cdk#9877]
## :question: General Issue

The repositoryName property of an ECR Repository must not contain uppercase letters, but the construct does not validate this. This allows a template to be synthesized that won't deploy.

Is this a bug, or documentation issue, or just something expected?

### Environment

  - **CDK CLI Version:** 1.60.0 (build 8e3f53a)
  - **Module Version:** 1.60.0
  - **Node.js Version:** v12.16.3
  - **OS:** Windows 10
  - **Language (Version):** Python 3.7.4

### Other information

Simple stack that demonstrates the problem.

```python
from aws_cdk import core
import aws_cdk.aws_ecr as ecr

class TestStack(core.Stack):

    def __init__(self, scope: core.Construct, id: str, **kwargs) -> None:
        super().__init__(scope, id, **kwargs)

        repo = ecr.Repository(self, "MyRepo", repository_name="MyRepo")
```

Result:

```
test: deploying...
test: creating CloudFormation changeset...
 0/3 | 9:23:11 AM | REVIEW_IN_PROGRESS   | AWS::CloudFormation::Stack | test User Initiated
 0/3 | 9:23:16 AM | CREATE_IN_PROGRESS   | AWS::CloudFormation::Stack | test User Initiated
 0/3 | 9:23:20 AM | CREATE_IN_PROGRESS   | AWS::ECR::Repository | MyRepo (MyRepoF4F48043)
 0/3 | 9:23:20 AM | CREATE_IN_PROGRESS   | AWS::CDK::Metadata   | CDKMetadata
 0/3 | 9:23:21 AM | CREATE_FAILED        | AWS::ECR::Repository | MyRepo (MyRepoF4F48043) Model validation failed (#/RepositoryName: failed validation constraint for keyword [pattern])       
        new Repository (C:\Users\jkindall\AppData\Local\Temp\jsii-kernel-EQ7UJq\node_modules\@aws-cdk\aws-ecr\lib\repository.js:157:26)
        \_ C:\Users\jkindall\cdk\python\test\.env\lib\site-packages\jsii\_embedded\jsii\jsii-runtime.js:7932:49
        \_ Kernel._wrapSandboxCode (C:\Users\jkindall\cdk\python\test\.env\lib\site-packages\jsii\_embedded\jsii\jsii-runtime.js:8405:20)
        \_ Kernel._create (C:\Users\jkindall\cdk\python\test\.env\lib\site-packages\jsii\_embedded\jsii\jsii-runtime.js:7932:26)
        \_ Kernel.create (C:\Users\jkindall\cdk\python\test\.env\lib\site-packages\jsii\_embedded\jsii\jsii-runtime.js:7676:21)
        \_ KernelHost.processRequest (C:\Users\jkindall\cdk\python\test\.env\lib\site-packages\jsii\_embedded\jsii\jsii-runtime.js:7456:28)
        \_ KernelHost.run (C:\Users\jkindall\cdk\python\test\.env\lib\site-packages\jsii\_embedded\jsii\jsii-runtime.js:7394:14)
        \_ Immediate._onImmediate (C:\Users\jkindall\cdk\python\test\.env\lib\site-packages\jsii\_embedded\jsii\jsii-runtime.js:7397:37)
        \_ processImmediate (internal/timers.js:456:21)
 0/3 | 9:23:22 AM | CREATE_FAILED        | AWS::CDK::Metadata   | CDKMetadata Resource creation cancelled
 0/3 | 9:23:23 AM | ROLLBACK_IN_PROGRESS | AWS::CloudFormation::Stack | test The following resource(s) failed to create: [MyRepoF4F48043, CDKMetadata]. . Rollback requested by user.
 2/3 | 9:23:43 AM | DELETE_IN_PROGRESS   | AWS::CDK::Metadata   | CDKMetadata
 2/3 | 9:23:43 AM | DELETE_SKIPPED       | AWS::ECR::Repository | MyRepo (MyRepoF4F48043)
 2/3 | 9:23:44 AM | DELETE_COMPLETE      | AWS::CDK::Metadata   | CDKMetadata
 2/3 | 9:23:45 AM | ROLLBACK_COMPLETE    | AWS::CloudFormation::Stack | test

test failed: Error: The stack named test failed creation, it may need to be manually deleted from the AWS console: ROLLBACK_COMPLETE
    at Object.waitForStackDeploy (C:\Users\jkindall\AppData\Roaming\npm\node_modules\aws-cdk\lib\api\util\cloudformation.ts:292:11)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at Object.deployStack (C:\Users\jkindall\AppData\Roaming\npm\node_modules\aws-cdk\lib\api\deploy-stack.ts:274:26)
    at CdkToolkit.deploy (C:\Users\jkindall\AppData\Roaming\npm\node_modules\aws-cdk\lib\cdk-toolkit.ts:181:24)
    at main (C:\Users\jkindall\AppData\Roaming\npm\node_modules\aws-cdk\bin\cdk.ts:268:16)
    at initCommandLine (C:\Users\jkindall\AppData\Roaming\npm\node_modules\aws-cdk\bin\cdk.ts:188:9)
The stack named test failed creation, it may need to be manually deleted from the AWS console: ROLLBACK_COMPLETE
```

**Comment by ayush987goyal** [comment]
I am trying to implement a fix for the above by doing the following based on [ref](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-ecr-repository.html#aws-resource-ecr-repository-return-values):

```ts
protected validate(): string[] {
    const errors = super.validate();
    errors.push(...this.policyDocument?.validateForResourcePolicy() || []);
    errors.push(...validateRepositoryName(this.physicalName));
    return errors;
}


function validateRepositoryName(repoName: string): string[] {
  const errors: string[] = [];

  if (repoName.length < 2 || repoName.length > 256) {
    errors.push('Repository Name must have minimun 2 and maximum 256 characters.');
  }

  const regex = new RegExp('(?:[a-z0-9]+(?:[._-][a-z0-9]+)*/)*[a-z0-9]+(?:[._-][a-z0-9]+)*', 'g');
  const match = repoName.match(regex);
  if (!match || match.length > 1) {
    errors.push(`Repository Name must match the following pattern ${regex.toString()}`);
  }

  return errors;
}
```

But this is failing for the tests since the `this.physicalName` does not obey the pattern. Am I doing anything wrong? Should I not make a comparison of `physicalName`? [Reference](https://github.com/aws/aws-cdk/blob/master/packages/%40aws-cdk/aws-ecr/lib/repository.ts#L414) for where we assign passed `repositoryName` to `physicalName`

**Comment by gyang-vonage** [comment]
This is the most annoying one, not only lowercase but two dashes together can break the whole stack build.
